### ISSUE TITLE
Support PriorityBlockingQueue

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast#1]
http://java.sun.com/j2se/1.5.0/docs/api/java/util/concurrent/PriorityBlockingQueue.html

i.e. add prioritization support to the clustered blocking queue.<p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=72</p><hr/><h2>earlier comments</h2>

<p><strong>mingfai.ma said, at 2009-05-22T07:06:56.000Z:</strong></p>

<p>i meant PriorityQueue, not PriorityBlockingQueue
http://java.sun.com/j2se/1.5.0/docs/api/java/util/PriorityQueue.html

it would be great if there is a non-FIFO queue.</p><p><strong>kevin.witten222 said, at 2010-12-07T15:49:46.000Z:</strong></p>

<p>Also implement PriorityBlockingQueue, so far I like Hazelcast, but this would be a requirement to it to use.</p><p><strong>jatinksharma said, at 2011-11-03T21:31:15.000Z:</strong></p>

<p>This would be really useful.</p><p><strong>matthew.sandoz@ihg.com said, at 2011-12-20T22:08:24.000Z:</strong></p>

<p>agreed - i would really use this. in fact, i am trying to combine the concept of a multimap with a priority queue - or even a multimap with an ordered collection for each key...</p>

**Comment by alezx** [comment]
any update ? @gurbuzali I saw your implementation, what do you mean not production ready ?

**Comment by wildnothing** [comment]
Is the any update on when or if this will ever be implemented? It would be incredibly useful.

**Comment by Holmistr** [comment]
@wildnothing The feature is finally implemented and coming in 4.1 - https://github.com/hazelcast/hazelcast/pull/17201/files#diff-8787fd9af4d211a60ce1c9edc453dfd9R994
