### ISSUE TITLE
Client properties configurable system property

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#10012]
The client properties should be configurable using a system property just like the serverside.

**Comment by sancar** [comment]
They are using same infrastructure `HazelcastProperties` and `HazelcastProperty`. That enables using system property in both sides. 
@pveentjer If we are in the same page , I would like to close this issue .

**Comment by sancar** [comment]
@pveentjer Am I missing something here ? or Can we close this one ?
