### ISSUE TITLE
ClientMapBasicTest.testMapStatistics_withClientOperations

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10025]
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapBasicTest.testMapStatistics_withClientOperations(ClientMapBasicTest.java:1192)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/32/testReport/junit/com.hazelcast.client.map/ClientMapBasicTest/testMapStatistics_withClientOperations/

**Comment by hasancelik** [comment]
*maintenance*
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapBasicTest.testMapStatistics_withClientOperations(ClientMapBasicTest.java:1192)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast-client/500/testReport/junit/com.hazelcast.client.map/ClientMapBasicTest/testMapStatistics_withClientOperations/

**Comment by hasancelik** [comment]
*master*
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapBasicTest.testMapStatistics_withClientOperations(ClientMapBasicTest.java:1192)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client/1288/testReport/junit/com.hazelcast.client.map/ClientMapBasicTest/testMapStatistics_withClientOperations/

**Comment by ihsandemir** [comment]
Examined the logs: We can not see the exact numbers for statistics. It does 1123 put get and delete. And the total get time is total of get times for the 1123 get operation time, if each operation was fast enough and each runs under 1 msec than we end up summing 1123 times zero value. Hence, it is possible to get a 0 value since the resolution of the statistic is milliseconds.

**Comment by ihsandemir** [comment]
We need to see the verbose log output of the test to say if previous comment really holds true or not.

**Comment by hasancelik** [comment]
```
get latency : stats1LocalMapStatsImpl{lastAccessTime=0, lastUpdateTime=0, hits=0, numberOfOtherOperations=0, numberOfEvents=0, getCount=568, putCount=568, removeCount=568, totalGetLatencies=0, totalPutLatencies=40, totalRemoveLatencies=28, ownedEntryCount=0, backupEntryCount=0, backupCount=0, ownedEntryMemoryCost=0, backupEntryMemoryCost=0, creationTime=1496972232088, lockedEntryCount=0, dirtyEntryCount=0, heapCost=0, nearCacheStats=} stats2:LocalMapStatsImpl{lastAccessTime=0, lastUpdateTime=0, hits=0, numberOfOtherOperations=0, numberOfEvents=0, getCount=555, putCount=555, removeCount=555, totalGetLatencies=0, totalPutLatencies=39, totalRemoveLatencies=31, ownedEntryCount=0, backupEntryCount=0, backupCount=0, ownedEntryMemoryCost=0, backupEntryMemoryCost=0, creationTime=1496972232089, lockedEntryCount=0, dirtyEntryCount=0, heapCost=0, nearCacheStats=}
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/601/testReport/junit/com.hazelcast.client.map/ClientMapBasicTest/testMapStatistics_withClientOperations/

**Comment by ihsandemir** [comment]
I examined the latest failure logs. The log still states that the get latency total is still zero. It comes out that the resolution of the time interval is milliseconds and if one million get requests are executed and each one completes less than a second, the total still becomes zero.
