### ISSUE TITLE
LastAccessTime and hits of EnTryView are not being updated when get is called in IMap

### ISSUE THREAD

**Issue by pratick-celtris** [hazelcast/hazelcast#10032]
I need last access time of entries to find out when the last the values was get.

Map configuration:
```xml
<hz:map name="vehicle-current-address-fetch-data"
				backup-count="2"
				read-backup-data="true"
				max-idle-seconds="0" eviction-policy="NONE"
				merge-policy="com.hazelcast.map.merge.LatestUpdateMapMergePolicy"
				in-memory-format="OBJECT"/>
```

```java
hazelcastInstance.getMap("vehicle-current-address-fetch-data").get(vehicleId);
EntryView<Object, Object> entryView1 = hazelcastInstance.getMap("vehicle-current-address-fetch-data");

hazelcastInstance.getMap("vehicle-current-address-fetch-data").get(vehicleId);
EntryView<Object, Object> entryView2 = hazelcastInstance.getMap("vehicle-current-address-fetch-data");
```

Last access time and hits is same both in entryView1 and entryView2.

Hazel Cast version: 3.5.3
Java Version: 1.8.0_60
OS: Redhat 7
Cluster Size: 2

**Comment by jerrinot** [comment]
Hello @pratick-celtris,

can you please elaborate it? What behaviour do you expect? The code you pasted is not quite clear - it does not compile and it's not clear what its intent.

**Comment by pratick-celtris** [comment]
I am using hazel cast inside spring. My problem is that the last access time and hits of EntryView is changed only when the entry is updated. Whenever a get operation on the entry is performed, hits and last access time remains same.

**Comment by jerrinot** [comment]
@pratick-celtris: thanks for your reply. let me check it.

**Comment by jerrinot** [comment]
I managed to reproduce it, thanks for a good reproducer! 

It's triggered by the `read-backup-data=true`. When you disable reading from backup then the stats are updated correctly. 

This makes this issue to be a duplicate of https://github.com/hazelcast/hazelcast/issues/7341 and I'm closing it as DUP.

**Comment by pratick-celtris** [comment]
Thank you for the help. It will be helpful for the users if this constraint is added into the Hazelcast docs.
