### ISSUE TITLE
NullPointerException when using PagingPredicate with Comparator inIMap.keySet(<predicate>)

### ISSUE THREAD

**Issue by carlo-activia** [hazelcast/hazelcast#10043]
Hazelcast version: 3.8

Just wondering if it is ok to use PagingPredicate with Comparator in IMap.keySet(), cause PagingPredicate with Comparator will sort the elements, but IMap.keySet() returns a Set (which does not guarantee an order).
I think if not supported then a different exception should be thrown or if supported then a LinkedHashSet  might be returned keeping the order that the Comparator applied.

import com.hazelcast.config.Config;
import com.hazelcast.config.InMemoryFormat;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MapIndexConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.query.PagingPredicate;
import com.hazelcast.query.Predicate;
import com.hazelcast.query.Predicates;
import org.junit.Assert;
import org.junit.Test;

import java.io.Serializable;
import java.util.Collection;
import java.util.Comparator;
import java.util.Map;
import java.util.Set;

public class TestHazelcastService {

  @Test
  public void issue() throws Exception {
    final String fieldName = "lastValue";
    final String mapName = "testMap";

    Config config = new Config();
    MapConfig testMapConfig = config.getMapConfig(mapName);
    testMapConfig.setInMemoryFormat(InMemoryFormat.OBJECT);
    testMapConfig.getMapIndexConfigs().add(new MapIndexConfig(fieldName, true));
    HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

    try {
      IMap<Object, Object> testMap = instance.getMap(mapName);
      testMap.set(1L, new MyData(10));
      testMap.set(2L, new MyData(25));
      testMap.set(3L, new MyData(20));

      Predicate betweenPredicate = Predicates.between(fieldName, 0, 30);
      PagingPredicate pagingPredicate = new PagingPredicate<>(betweenPredicate, new LastValueComparator(), 3);

      Collection<Object> values = testMap.values(pagingPredicate);  // No issues here. (using IMap.values)
      Assert.assertEquals(3, values.size());

      Set<Object> keys = testMap.keySet(pagingPredicate); // NullPointer thrown here. (using IMap.keySet)
      Assert.assertEquals(3, keys.size());
    } finally {
      instance.shutdown();
    }
  }
}

class MyData implements Serializable {
  private long lastValue;

  public MyData() {
  }

  public MyData(long lastValue) {
    this.lastValue = lastValue;
  }

  public long getLastValue() {
    return lastValue;
  }

  public void setLastValue(long lastValue) {
    this.lastValue = lastValue;
  }
}

class LastValueComparator implements Comparator<Map.Entry<Long, MyData>>, Serializable {
  @Override
  public int compare(Map.Entry<Long, MyData> entry1, Map.Entry<Long, MyData> entry2) {
    long lastValue1 = entry1.getValue().getLastValue();
    long lastValue2 = entry2.getValue().getLastValue();
    return Long.compare(lastValue1, lastValue2);
  }
}

**Comment by gurbuzali** [comment]
it is ok to use `PagingPredicate` with keyset. The problem is your comparator, it does compare values. If you query keys, `entry.getValue()` will return null. For example this one works:
```
class LastValueComparator implements Comparator<Map.Entry<Long, MyData>>, Serializable {
        @Override
        public int compare(Map.Entry<Long, MyData> entry1, Map.Entry<Long, MyData> entry2) {
            long lastValue1 = entry1.getKey();
            long lastValue2 = entry2.getKey();
            return Long.compare(lastValue1, lastValue2);
        }
    }
```

**Comment by carlo-activia** [comment]
Thank you so much for the clarification.
