### ISSUE TITLE
[map] [map-store] loadAll(boolean replaceExistingValues) doesn't reload the mapstore after cache.evictAll is called

### ISSUE THREAD

**Issue by prabhu-nishant** [hazelcast/hazelcast#10057]
We have exposed the caches via JMX and we have defined a reloadCache functionality where in we first do a evictAll and then call loadAll(true). However it doesn't get keys and the cache is empty. 

We often require reloadCache functionality in production in case of issues and this has been causing issues for a while after we migrated from 3.4 to 3.7

Expecting a reply

Thanks

**Comment by jerrinot** [comment]
@prabhu-nishant: what's your exact Hazelcast version?

**Comment by prabhu-nishant** [comment]
3.7.1

**Comment by jerrinot** [comment]
can you try the latest 3.7.x? there was a [bugfix in 3.7.4](https://github.com/hazelcast/hazelcast/pull/9260)

**Comment by prabhu-nishant** [comment]
As per my observation loadAll(true) fails even if nothing is changed in the cache. Does the bugfix cover that as well?

**Comment by jerrinot** [comment]
I am not sure how to interpret "nothing is change in the cache". I recommend to always use the latest available patch release.

**Comment by prabhu-nishant** [comment]
What I meant was that we are not adding/deleting/updating keys in the cache. Just a simple reload empties the cache and it happens intermittently.
