### ISSUE TITLE
Allow custom joiners to be added dynamically

### ISSUE THREAD

**Issue by viniciusccarvalho** [hazelcast/hazelcast#1006]
Currently its not possible to add other types of joiners. It would be awesome if HZ allowed developers to extend it to have other joiners/config

Some implementations to go around non multicast environments:
- Zookeeper
- Swift 

Maybe if joiners were added as modules, one could just add a new module and its joiner would be picked instead of the default one.

Regards

**Comment by noctarius** [comment]
This is related to HEP2 https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI

**Comment by mdogan** [comment]
Discovery SPI allows adding custom joiners: http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#discovery-spi
There are already provided discovery plugins: https://hazelcast.org/plugins/
