### ISSUE TITLE
[map] Updates with IMap#putTransient should trigger EntryUpdatedListener 

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#10077]
see https://groups.google.com/d/msgid/hazelcast/fd413042-9057-4a46-a9a6-55686e41d2ea%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by vbekiaris** [comment]
Test (2 `ADDED` events are triggered instead of 1 `ADDED` & 1 `UPDATED`):
```
    @Test
    public void testPutTransient_triggersEntryEvents() throws InterruptedException {
        final IMap<String, String> map = getInstance().getMap("testPutTransient_triggersEntryEvents");
        final CountDownLatch addedLatch = new CountDownLatch(1);
        final CountDownLatch updatedLatch = new CountDownLatch(1);
        map.addEntryListener(new EntryAdapter<String, String>() {
            @Override
            public void entryAdded(EntryEvent<String, String> e) {
                addedLatch.countDown();
            }

            @Override
            public void entryUpdated(EntryEvent<String, String> event) {
                updatedLatch.countDown();
            }

        }, true);
        map.putTransient("hello", "world", 0, SECONDS);
        map.putTransient("hello", "another world", 0, SECONDS);
        assertOpenEventually(addedLatch);
        assertOpenEventually(updatedLatch);
    }
```

**Comment by neilstevenson** [comment]
See http://stackoverflow.com/questions/43659013/why-does-hazelcast-imap-puttransient-fire-the-entryaddedlistener

The provided code snippet doesn't function correctly on 3.8.1. One ADDED and then seven UPDATED events which is correct, but followed by EVICTED which is incorrect.

**Comment by ahmetmircik** [comment]
see this: https://github.com/hazelcast/hazelcast/pull/10082#issuecomment-298090506

**Comment by ahmetmircik** [comment]
@neilstevenson Noticed that there is no javaDoc for the relation of regular `put(k,v)` and TTL. I would like to close this issue by documenting that relation like this:

`
If entry has a TTL associated with it (either with map config or with explicit ttl-ed put), `put(k,v)` only shifts expiration time and doesn't cancel existing TTL.
`

WDYT?

**Comment by neilstevenson** [comment]
I view that `put(K,V)` implies you get the default TTL

It you do `put(key1, value1)` and `put(key2, value2)` at the same time, you should expect them to expire together or not at all.

Current behaviour is that they could expire at radically different times, due to previous operations, which doesn't seem right.

**Comment by ahmetmircik** [comment]
That can be possible if we choose entry `creationTime` as TTL-start-time instead of `lastUpdateTime`. Is this what you want? If yes, this seems a new feature request and we can create a new issue for it.

**Comment by neilstevenson** [comment]
This should pass
```
// 1. Put with timeout
imap.put("hello", "world", 5L, TimeUnit.SECONDS);
TimeUnit.SECONDS.sleep(2L);

// 2. Put without timeout
imap.put("hello", "again");
imap.out("goodbye", "issue10077");

// 3. Wait to "prove" timeout has or hasn't occurred
TimeUnit.SECONDS.sleep(10L);

// 4. Test
assertThat(imap.containsKey("hello").equals(imap.containsKey("goodbye")), is(true));
```

Or something better. Waiting for the timeout isn't quite safe, but you get the idea.

If two keys are inserted without a timeout in step 2, what happened to one of them in step 1 is irrelevant.

**Comment by ahmetmircik** [comment]
Ok this makes sense. 
But i see this as a behavioral change. Can you file an issue for 4.0?

**Comment by ahmetmircik** [comment]
created an issue for the discussion above.
