### ISSUE TITLE
[discovery] MulticastDiscoveryStrategy works incorrect with client discovery

### ISSUE THREAD

**Issue by uladzimirFilipchanka** [hazelcast/hazelcast#10089]
We have client-server interaction based on MulticastDiscoveryStrategy. 

Let's say we have **_appC_** (client) and **_appS_** (server). 
Several instances of **_appC_** go to **_appS_** instances via hazelcast client using `MulticastDiscoveryStrategy` (only one way). When we need to restart one node of **_appS_** we usually have discovery troubles. Hazelcast can't find other nodes of **_appS_** which are live and available. And new node stays alone, split brain occur. After some restarts (from 0 to 10 and more), node successfully joins cluster. 

Here is out  part of hazelcast.xml for appS (the server)
``` xml
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
    </properties>
    <group>
        <name>appS</name>
        <password>appSPass</password>
    </group>

    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <discovery-strategies>
                <discovery-strategy class="com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy" enabled="true">
                    <properties>
                        <property name="group">224.2.2.8</property>
                        <property name="port">54324</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
    </network>
```
And part of hazelcast.xml for _**appC**_ (uses to connect to server)

``` xml
    <properties>
        <property name="hazelcast.discovery.enabled">true</property>
        <property name="hazelcast.client.invocation.timeout.seconds">1</property>
    </properties>

    <group>
        <name>appS</name>
        <password>appSPass</password>
    </group>

    <network>
        <smart-routing>true</smart-routing>
        <redo-operation>true</redo-operation>

        <connection-attempt-limit>0</connection-attempt-limit>
        <connection-attempt-period>500</connection-attempt-period>
        <connection-timeout>1000</connection-timeout>

        <discovery-strategies>
            <discovery-strategy class="com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategy" enabled="true">
                <properties>
                    <property name="group">224.2.2.8</property>
                    <property name="port">54324</property>
                </properties>
            </discovery-strategy>
        </discovery-strategies>
    </network>

```

After some debugging, we noticed that `MulticastDiscoveryReceiver` on _**appS**_ can catches data from **_appC_** during initialization. And it leads to splitbrain issue and discovery failure. 
Next investigation took us to `MulticastDiscoveryStrategy.start` method. There we have a new thread creation for multicast porposes. And the thread should be created only if this node isn't a client. 
And looks like here is the problem. Based on the code, isClient is always false. 

So client application multicasting information about the server it connects to. And new node of the server can catch this data for discovery. 

If this is true, fix is simple. `MulticastDiscoveryStrategy.initializeMulticastSocket` need to contain:
```java
 // code 
            if (discoveryNode == null) {
                isClient = true;
            }
```

**Comment by jerrinot** [comment]
@uladzimirFilipchanka: awesome finding and analysis, many thanks!

**Comment by jerrinot** [comment]
@uladzimirFilipchanka: fancy sending a PR?

**Comment by mdogan** [comment]
There's already a discovery mode setting `DiscoveryServiceSettings.discoveryMode`;

```java
public enum DiscoveryMode {
    /**
     * The current runtime environment is a Hazelcast member node
     */
    Member,

    /**
     * The current runtime environment is a Hazelcast client
     */
    Client
}
```

Both member and client side impl are passing correct mode to the service. But unfortunately, `DiscoveryServiceSettings.getDiscoveryMode()` is not used at all.

**Comment by mdogan** [comment]
And as far as I see, `MulticastDiscoveryStrategy` is not optimal. It has more issues.

**Comment by jerrinot** [comment]
@mdogan: can you elaborate it please?

**Comment by mdogan** [comment]
I don't remember all, these two are the ones I see now;
- First problem is, as I already stated above, `DiscoveryMode` setting is not used. Instead a hacky workaround is used to distinguish a client and a member.
- Second is, `MulticastDiscoverySender` continuously publishes discovery packet every 2 (hardcoded) seconds, even after members join, until member shutdowns. So, every member is flooding the network every 2 seconds with multicast messages.

**Comment by sancar** [comment]
Multicast discovery is also not working in a simple scenario. 
I have come across the issue when trying to understand what is going on in https://github.com/hazelcast/hazelcast/issues/10606

Our `MemberToMemberDiscoveryTest` is passing just because it is using discovery mechanism available in mock network. When I switch the test to real network, nodes are not able to find each other in start. They are finding each other only when SplitBrainHandler kicks in, which is too late for the test. 

It seems that DiscoveryStrategy with multicast also needs some work to make it usable.

**Comment by emrahkocaman** [comment]
@mdogan Yes there already is `DiscoveryMode` setting but it's not passed to `DiscoveryStrategy` instances, it's only used within `DiscoveryServiceProvider`. So we need an SPI change to pass it. Instead I'm proposing to keep SPI as is and use `DiscoveryNode` as @uladzimirFilipchanka suggested. WDY? 

This is just to close this specific problem, IMO other mentioned problems should have their own issues/PRDs.

**Comment by mdogan** [comment]
That workaround solves the problem in this issue. It's up to you (cc: @jerrinot ), I can't decide that. 

Discovery SPI and its default implementation (`DefaultDiscoveryServiceProvider`, `DefaultDiscoveryService` etc) are broken, because `DiscoveryMode` is never used at all. It's set by members and clients but it's never read. I consider this a bug.

**Comment by jerrinot** [comment]
for 3.9 I'd just apply the [workaround](https://github.com/hazelcast/hazelcast/pull/10987). 

Later we can discuss how to pass the DiscoveryNode with the smallest possible impact on compatibility.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/10987
see for further improvements https://github.com/hazelcast/hazelcast/issues/11357
