### ISSUE TITLE
3.9-SNAPSHOT hzcmd.map.validate.LocalKeySetSizeLessThan threadId=0 global.AssertionException: map mapBak1_MaxSize_PER_NODE_1000_map-max localKeySet size 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10098]
hazelcast 3.9-SNAPSHOT

map max size policy is exceed,  this test fails every time.  looks like a regression. 

HzMember1HZ _map-max_mapValidate hzcmd.map.validate.LocalKeySetSizeLessThan threadId=0 global.AssertionException: map mapBak1_MaxSize_PER_NODE_1000_map-max localKeySet size 2502 > 2500

map configuration

```
 <map name="mapBak1_MaxSize_PER_NODE_1000*">
        <max-size policy="PER_NODE">1000</max-size>
        <in-memory-format>BINARY</in-memory-format>
        <backup-count>1</backup-count>
        <hot-restart enabled="false">
            <fsync>false</fsync>
        </hot-restart>
    </map>
```

test configuration: https://github.com/hazelcast/hzCmd-bench/tree/zeta/lab/hz/stable/map-max

jenkins run
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All/32/console

logs
http://54.163.63.218/~jenkins/workspace/stable-All/3.9-SNAPSHOT/2017_03_17-12_14_29/stable/map-max/

**Comment by Danny-Hazelcast** [comment]
add an evection policy fixed the issue.

however I think this is a change in behaviour,  as before we did not explicitly add an evection
configuration, and it used to work ok ?

so may be this change need to be documented ?
if it is a change in behaviour

**Comment by ahmetmircik** [comment]
It was same behaviour for the older versions so you need to define at least `eviction-policy` to enable eviction on a map, as an example see this: http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#understanding-map-eviction

**Comment by Danny-Hazelcast** [comment]
ok then we can close this issue
