### ISSUE TITLE
Builtin DistinctValuesAggregator and MultiAttributeProjection return java serializable to client causes non-java clients fail

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast#10104]
`DistinctValuesAggregator` class returns a set of object for distinct values. Default hazelcast serializer does not support Set<T> so it serialize the result using java serializer.

`MultiAttributeProjection` returns Object[]. Default hazelcast serializer does not support Object[] so it serialize the result using java serializer.

This has two side effects:

* Non-java clients cannot support `DistinctValuesAggregator` and `MultiAttributeProjection`
* java client will use slow java serialization to deserialize the result

**Comment by sancar** [comment]
This is a requirement by non-java clients. And aggregator and projection are not implemented there. 
Since fixing this will break compatibility of java clients, this issue postponed until it is needed(or 4.0), in non-java clients.
