### ISSUE TITLE
Print diagnostic info for client as in server side health monitor

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#10122]
This helps to better diagnose problems on client side.
For example print diagnostic info after reaching a configured memory level.

**Comment by pveentjer** [comment]
This task should be closed. Clients have diagnostics; which is a way more powerful system than the old health monitor. Health monitor provides a tiny fraction of the data of the diagnostics; actually health monitor runs on top of diagnostics.
