### ISSUE TITLE
Fast Aggregations on [any] operator on empty array does not work

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast#10126]
For  builtin aggregations like Count, LongSum etc.
If we used them with an `attributePath` on list/array field like;

```
class Person implements Portable {
...
    int[] valueArray;
...
}
```

if we initialize valueArray with an empty array`valueArray = new int[]{};`

```
map.aggregate(Aggregators.<Map.Entry<Integer, Person>>integerSum.integerSum("valueArray[any]"));
```
throws NullPointerException instead of returning 0, 

```
map.aggregate(Aggregators.<Map.Entry<Integer, Person>>count("valueArray[any]"));
```
returns 1 instead of 0.

Other builtin aggregators may also fail, they should be tested.

**Comment by tombujok** [comment]
Confirmed, the spec test didn't test on empty arrays.

**Comment by tombujok** [comment]
With the current design of the AbstractMultiValue getter it is impossible to support in-built fast-aggregations with the [any] operator.
