### ISSUE TITLE
CacheEntryExpiredListener isn't triggered

### ISSUE THREAD

**Issue by asarigul** [hazelcast/hazelcast#10149]
Hi,

I'm testing jcache event hooks. I use Hazelcast (3.6.2) as the jcache implementation. When I create a cache with createdExpiryPolicy, entries do expire, but onExpired event is not triggered. Here is my test class:

```
public class CacheEntryExpiredListenerTest {
    static AtomicInteger expiredMessageCount = new AtomicInteger();

    @Test
    public void testExpiryListener() throws InterruptedException {
        final int expiryMillis = 2000;
        Duration duration = new Duration(TimeUnit.MILLISECONDS, expiryMillis);
        MutableConfiguration<Integer, Integer> config = new MutableConfiguration<Integer, Integer>().setExpiryPolicyFactory(CreatedExpiryPolicy.factoryOf(duration));

        MyCacheEntryExpiredListener expiryListener = new MyCacheEntryExpiredListener();
        MutableCacheEntryListenerConfiguration<Integer, Integer> listenerConfig = new MutableCacheEntryListenerConfiguration<>(
                FactoryBuilder.factoryOf(expiryListener), null, true, true);

//        config.addCacheEntryListenerConfiguration(listenerConfig)

        final int entryCount = 100;
        try (Cache<Integer, Integer> cache = Caching.getCachingProvider().getCacheManager().createCache("testCache",
                                                                                                        config)) {
            cache.registerCacheEntryListener(listenerConfig);

            for (int i = 0; i < entryCount; i++) {
                cache.put(i, i);
                Thread.sleep(10);
            }

            Thread.sleep(expiryMillis * 2);

            Assert.assertFalse(cache.iterator().hasNext());
            Assert.assertEquals(entryCount, expiredMessageCount.get());
        }
    }

    private static class MyCacheEntryExpiredListener implements CacheEntryExpiredListener<Integer, Integer>, Serializable {
        private static final long serialVersionUID = -2715739866442411122L;

        public MyCacheEntryExpiredListener() {
            // 
        }

        @Override
        public void onExpired(
                Iterable<CacheEntryEvent<? extends Integer, ? extends Integer>> events)
                throws CacheEntryListenerException {
            for(CacheEntryEvent<? extends Integer, ? extends Integer> next : events) {
                System.out.println("EXPIRED: " + next);
                expiredMessageCount.incrementAndGet();
            }
        }
    }
}
```

Here, Assert.assertFalse(cache.iterator().hasNext()); works as expected, so we are sure all entries are expired, but onExpired method on the listener is never invoked (I debugged it), so   Assert.assertEquals(entryCount, expiredMessageCount.get()); always fails (java.lang.AssertionError: expected:<100> but was:<0>)

I tried to register expiryListener config to cache (as in this example), and to the config via addCacheEntryListenerConfiguration, but none seems to work.

**Comment by ahmetmircik** [comment]
Hi, 
You need to touch entries to see expiry events fired. Jcache implementation doesn't sweep expired entries automatically. For ex, you can do a `get` to trigger events.

**Comment by asarigul** [comment]
Hi @ahmetmircik 

I tried what you suggest, but result didn't change. I  touched all the entries using a second loop. onExpired still doesn't triggered: 

```
  for (int i = 0; i < entryCount; i++) {
       cache.put(i, i);
       Thread.sleep(10);
       cache.get(i);
   }

   Thread.sleep(expiryMillis * 2);

   for (int i = 0; i < entryCount; i++) {
       cache.get(i);
   }
```

**Comment by asarigul** [comment]
Hi again,

This time I put a break point on  Assert.assertEquals(entryCount, expiredMessageCount.get()); and events triggered. I guess events fired with a little lag, so waiting on assertion line fixes the problem.

A question, should touching the entries to trigger the events be after the expiry? What is the best practice to ensure event callback called?

**Comment by ahmetmircik** [comment]
Yes touching needs to be done after expiry. You can check out [CacheClientListenerTest](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/test/java/com/hazelcast/client/cache/CacheClientListenerTest.java#L101) and [ClientCacheEntryExpiredLatchCountdownListener](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCacheEntryExpiredLatchCountdownListener.java) to see handling of events in a similar test.

**Comment by asarigul** [comment]
Allright, thank you very much.
