### ISSUE TITLE
HazelcastOSGiInstanceTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10152]
```
17:20:42 Running com.hazelcast.osgi.HazelcastOSGiInstanceTest
20:27:27 Build timed out (after 240 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/213/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/214/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/215/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/54/console

**Comment by jerrinot** [comment]
last failure from March. closing.
