### ISSUE TITLE
[query] [map] PagingPredicate does not work for executeOnEntries() method

### ISSUE THREAD

**Issue by awakestu** [hazelcast/hazelcast#10174]
As far as I can see it just ignores paging and returns full resultset despite of page size

**Comment by tombujok** [comment]
It never supported Paging actually. There are more method in the IMap that support a Predicate but do not support Paging.

**Comment by pveentjer** [comment]
@tombujok how to proceed with this ticket? Is it working as designed or is it a bug?

**Comment by tombujok** [comment]
@pveentjer @ahmetmircik It never supported paging as I said in the comment in April, but I'm not sure why I haven't closed the ticket. Paging there does not make much sense.
