### ISSUE TITLE
hazelcast.jar contains release_notes.txt and changelog.txt

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#10177]
`hazelcast.jar` contains the files `release_notes.txt` and `changelog.txt`. When we shade `hazelcast.jar` into `hazelcast-jet`, results in an awkward situation where `hazelcast-jet` contains release notes for Hazelcast. These text files should not be included in the JAR itself, but just in the distribution package.

**Comment by mesutcelik** [comment]
master: b8cbe279aa4436579d66e41eb0bf66a841ace3fd
maintenance: d3b24b0e7ae8ebc794837bbe59e769ce4df0284c
3.8.1: e62c5dad4507bbcfea1ce5965730bb7f5dd418e5
Release script: https://github.com/hazelcast/DevOps/pull/108

@emre-aydin @hasancelik Can you please review release script PR. if it is ok, you can close this issue.

**Comment by emre-aydin** [comment]
Release script PR looks good, we can close the issue after Hasan's review.
