### ISSUE TITLE
Eviction and max-size less then 271 cause map to never populate

### ISSUE THREAD

**Issue by jtesser** [hazelcast/hazelcast#10179]
This is my config
<map name="indiciescache">
        <max-size>8</max-size>
        <eviction-policy>LFU</eviction-policy>
    </map>

While I understand you CANNOT set the max-size below the partition count which is 271 by default Hazel should handle this and if max-size is lower then partition-count THEN set it to the partition count.  

What happens is nothing ever makes it into the map. This is confusing behavior.  The config is not rejected meaning no errors on startup.  Everything looks like it works but it is not.

**Comment by ahmetmircik** [comment]
Thanks for reporting this. I guess you observe this for imap. Lets see what we can do.

**Comment by jtesser** [comment]
Hi yes using iMap.

**Comment by tombujok** [comment]
Moving to 3.8.3 as discusses with @ahmetmircik @vbekiaris
