### ISSUE TITLE
Ring buffer OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10189]
version 3.8.1

this ring buffer test has failed for the first time with an OOME,
we have has successful runs of this test, before, using the same version 3.8.1
I thing the difference, is this run is 15 mins longer than previous,  at a duration of 30 mins. 

bulid
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-All/40/console

/disk1/jenkins/workspace/stable-All/3.8.1/2017_03_29-23_49_29/stable/ring Failed

http://54.163.63.218/~jenkins/workspace/stable-All/3.8.1/2017_03_29-23_49_29/stable/ring

Fail oome
```
HzMember1HZ _ring_ring_read hzcmd.ring.ReadOne threadId=1 java.lang.Exception: java.lang.OutOfMemoryError: GC overhead limit exceeded 
```

8 boxes, aws-ec2 c4.2xlarge

D4M4C8  (dedicated member box 4,  members 4,  client 8)

memberOps "-Xms2G -Xmx2G"
clientOps      "-Xms200M -Xmx200M"

Hprof java.lang.OutOfMemoryError: GC overhead limit exceeded

http://54.163.63.218/~jenkins/workspace/stable-All/3.8.1/2017_03_29-23_49_29/stable/ring/HzMember1HZ.hprof.zip
or
http://54.163.63.218/~jenkins/workspace/stable-All/3.8.1/2017_03_29-23_49_29/stable/ring/output/HZ/HzMember1HZ/HzMember1HZ.hprof

GC charts
http://54.163.63.218/~jenkins/workspace/stable-All/3.8.1/2017_03_29-23_49_29/stable/ring/gc.html

Member1 GC chart
![image](https://cloud.githubusercontent.com/assets/5988678/24510483/0c638aae-1572-11e7-89ae-bb50393d6b99.png)

Test Config
https://github.com/hazelcast/hzCmd-bench/tree/zeta/lab/hz/stable/ring

all though is't named async we do wait for the result after the call. 
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/ring/AddAsync.java#L26
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/ring/ReadOne.java

looks like build up of add msgs

<img width="944" alt="screen shot 2017-03-30 at 18 30 37" src="https://cloud.githubusercontent.com/assets/5988678/24512369/0ef44ef2-1577-11e7-8863-f51113cbc7ae.png">

**Comment by tkountis** [comment]
![ringbuffer-mat](https://cloud.githubusercontent.com/assets/3369598/24518839/194a5c94-157b-11e7-9d14-72899c2ec04b.png)

this seems to be the store of the ringbuffer, and not the ringbuffer itself. I checked the Store implementation and its a plain HashMap, which just accumulates stuff (https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/ring/Store.java), so the OOM is justified and its outside our jurisdiction

@Danny-Hazelcast please confirm, and update issue accordingly.

**Comment by Danny-Hazelcast** [comment]
@tkountis   so i changed the store to remove the element on load
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/ring/Store.java#L24

and changed the load,  to more read / get threads  than add threads 
https://github.com/hazelcast/hzCmd-bench/blob/zeta/lab/hz/stable/ring/add-read

a 30min run with this setup passed 
https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x/18/console

but the gc looks like its going the same way 
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_30-21_17_39/gc.html


the rate of add operations is 
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_30-21_17_39/ring/output/HZ_3.8.1__ring_ring_add_hzcmd.ring.AddAsync_1-bench.csv-charts/HZ_3.8.1__ring_ring_add_hzcmd.ring.AddAsync_1-bench.csv-ops-perSec-1min-rate.png

the rate of read operations is 
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_30-21_17_39/ring/output/HZ_3.8.1__ring_ring_read_hzcmd.ring.ReadOne_1-bench.csv-charts/HZ_3.8.1__ring_ring_read_hzcmd.ring.ReadOne_1-bench.csv-ops-perSec-1min-rate.png


so some how, i assume the store is still growing, faster than it can be drained by call's to load ?

maybe i don't understand how to use / or how the the ring buffer is working,  when combined with the ring store ?

**Comment by Danny-Hazelcast** [comment]
also there are 500 ring buffers used in the test

**Comment by tkountis** [comment]
We discussed this offline, the `load` is used when a sequence is not found in the ringbuffer so it attempts to load the item from the back-end store. This happens when a reader falls behind and your producer is significantly faster. So in your use-case, your producer / consumer are pretty much in sync, so the `load` shouldn't be called, and you still accumulate items. Ideally, a store should be a disk based store, eg. a database, you could do some batching to prevent hitting the DB every time you add an item, but you wouldn't have to keep everything in memory. Having said that, a store's implementation is not under our control, so one can do anything he wants.

**Comment by Danny-Hazelcast** [comment]
next version of the store

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/ring/Store.java

better looking gc
http://54.163.63.218/~jenkins/workspace/stable-x/3.8.1/2017_03_31-12_06_09/ring/gc.html

member1 gc
![image](https://cloud.githubusercontent.com/assets/5988678/24545440/d0c7cce6-160f-11e7-9ff8-08ce5317488a.png)



and charts

_ring_add throughput
![image](https://cloud.githubusercontent.com/assets/5988678/24545484/f90be39a-160f-11e7-8a2b-ae04c8701732.png)

ring add 99 latency
![image](https://cloud.githubusercontent.com/assets/5988678/24545499/0abbe946-1610-11e7-9ad0-40d1a0d910b9.png)



ring read throughput
![image](https://cloud.githubusercontent.com/assets/5988678/24545553/404f11b4-1610-11e7-8d9e-c18b5c68ad1b.png)


ring read 99 latency
![image](https://cloud.githubusercontent.com/assets/5988678/24545572/4df084ba-1610-11e7-9443-91f15844dee2.png)
