### ISSUE TITLE
[lock] ILock stuck in locked state

### ISSUE THREAD

**Issue by agherardi** [hazelcast/hazelcast#10192]
See also https://github.com/hazelcast/hazelcast/issues/6520

We're seeing this issue again, using Hazelcast 3.5.5. We have a debugging utility that retrieves all LockResource objects stored on a node then displays some information about each LockResource. When the lock in question - named LOCKXXX - is stuck, the utility displays this information about the lock:

```
"namespace":"com.hazelcast.concurrent.lock.InternalLockNamespace@ce6cf218","key":"LOCKXXX","owner":null,"threadId":938,"count":1,"acquireTime":"Tue Mar 28 18:44:40 MDT 2017","expiration":"Sun Aug 17 15:12:55 MDT 292278994"
```

The "owner" is determined as follows:

```
LockResource lockResource = ...;
String owner = getMember(lockResource.getOwner());

private String getMember(String memberUuid)
{
  for (Member member : hazelcastInstance.getCluster().getMembers())
  {
      if (member.getUuid().equals(memberUuid))
      {
        return member.toString();
      }
      return null;
  }
}
```

How can a lock be owned by a member that is no longer part of the cluster? When the member left the cluster, Hazelcast should have automatically release the lock.

Also notice that everywhere our code calls ILock.lock() we have a finally block that calls unlock().

Any suggestions?

Thank you in advance.

**Comment by mdogan** [comment]
It seems there's a bug/race while releasing locks automatically when a member leaves the cluster. But also there are some fixes later than 3.5.5 regarding locks:

3.6: https://github.com/hazelcast/hazelcast/pull/5601
3.6: https://github.com/hazelcast/hazelcast/pull/5602
3.8: https://github.com/hazelcast/hazelcast/pull/9558

Can you please upgrade to 3.8 and see if the problem still exists?

**Comment by mmedenjak** [comment]
@agherardi were you able to test with Hazelcast 3.8? There were some improvements on member leaving the cluster and a couple of more cases will be covered in hazelcast 3.9.

**Comment by agherardi** [comment]
So far, we haven't seen the issue with 3.8. But it's still early to tell.

**Comment by mmedenjak** [comment]
@agherardi I'm closing the issue then. Feel free to open a new one if you encounter the same (or a different problem). Hazelcast 3.8 has had several improvements for locks and Hazelcast 3.9 is going to fix some more edge cases.
