### ISSUE TITLE
Call timed-out either in operation queue or during wait-notify phase

### ISSUE THREAD

**Issue by brian-dawn** [hazelcast/hazelcast#10212]
Hi, we're running into an issue in our staging environment (2 node cluster) where Hazelcast (v3.8) is at times performing really slow put/remove operations.

When the operation is slow we see the following log messages:

```
17-03-27 05:10:07 staging TRACE [com.hazelcast.spi.impl.operationservice.impl.Invocation:60] - nil [172.16.0.150]:5701 [test-cluster] [3.8] Call timed-out either in operation queue or during wait-notify phase, retrying call: Invocation{op=com.hazelcast.collection.impl.queue.operations.PollOperation{serviceName='hz:impl:queueService', identityHash=1932149081, partitionId=178, replicaIndex=0, callId=206558, invocationTime=1490591347709 (2017-03-27 00:09:07.709), waitTimeout=-1, callTimeout=60000, name=events}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1490567400002, firstInvocationTime='2017-03-26 17:30:00.002', lastHeartbeatMillis=1490591398287, lastHeartbeatTime='2017-03-27 00:09:58.287', target=[172.16.0.150]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
```

What's interesting about that is the firstInvocationTime is almost a day behind when we logged this.

These slow operations appear to happen about 10% of the time. I did a jstack dump during the slow operations and noticed the following from the thread that was performing the put:

```

Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode):

"Attach Listener" #7580 daemon prio=9 os_prio=0 tid=0x00006ddee8005000 nid=0x3835 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"nREPL-worker-7" #7579 daemon prio=5 os_prio=0 tid=0x00006dde542c8000 nid=0x37dc waiting on condition [0x00006dddf4ee2000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:371)
        at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:342)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:129)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:119)
        at org.apache.shiro.cache.MapCache.put(MapCache.java:62)
        [remaining stack trace removed]
```

Any help/insight would be appreciated! I'm unsure how to go about debugging this...

**Comment by pveentjer** [comment]
The log message can be explained. Due to some legacy code, the call is being retried periodically where locally we check for interrupt etc etc. So if you have a blocking call and it blocks for a long period, then under the hood every minute or so the operation is retried. You see this in the trace logging; but it works as 'designed'. 

So apart from these log entries, is there another problem?

**Comment by brian-dawn** [comment]
Yes, the issue is that hazelcast is taking several seconds to perform simple put operations.

We managed to track the issue down to a library in our system creating a lot of threads that were consuming hazelcast queues. Closing the ticket.
