### ISSUE TITLE
Policy for backporting fixes from 3.8 to 3.7.x

### ISSUE THREAD

**Issue by JChrist** [hazelcast/hazelcast#10242]
Hello.
I was trying to compare in the [release notes](http://docs.hazelcast.org/docs/release-notes/) if there are any fixes in 3.8 that have not been backported to the latest 3.7 and I can see some of them not being mentioned in the 3.7 series, such as https://github.com/hazelcast/hazelcast/issues/9453 and https://github.com/hazelcast/hazelcast/issues/9189

I would like to know whether there are any fixes not backported from 3.8 to 3.7 (the ones I mentioned or others), and generally what your policy is for backporting fixes.
Is it safe to assume that all fixes in the latest release series will be brought to the previous (i.e. from 3.8.x to 3.7.x)?

**Comment by mdogan** [comment]
Our policy is to backport all fixes on development branch (master) to maintenance branch unless fix breaks the patch level compatibility. 

Backport for issue https://github.com/hazelcast/hazelcast/issues/9189 is https://github.com/hazelcast/hazelcast/pull/9549

Other issue doesn't seem backported, I don't know the actual reason.
