### ISSUE TITLE
question for new lock type

### ISSUE THREAD

**Issue by publicocean0** [hazelcast/hazelcast#10243]
hi , 
i have a huge set of element stored in a file in node A and B.
before to update element keys 1,5,8 i have to lock in all the nodes for evoiding inconsistent data among nodes  
I thought to develop a new lock faster for this problem.

SetLock a =hanzelcast.newSetLock(1,5,8).
just a message to other nodes for synchronization.

First idea is to develop it using hz executor but id dont know if there is a faster solution.
What do you think?
Where can i see the classes developing The default lock in hanzelcast ?

**Comment by mdogan** [comment]
You can start by reading [Extending Hazelcast](http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#extending-hazelcast) part of the user manual and [Mastering Hazelcast IMDG eBook](https://hazelcast.com/resources/mastering-hazelcast/).

Also you can see current lock impl: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast/concurrent/lock

**Comment by publicocean0** [comment]
Thanks :)
