### ISSUE TITLE
[cluster] Incompatible partition groups! expected: disabled / PER_MEMBER, found: enabled / CUSTOM

### ISSUE THREAD

**Issue by costap** [hazelcast/hazelcast#10241]
We have deployment of hazelcast 3.8 with partition groups setup. It runs internally with a spring app. Recently we have added feign as a dependency in the same app and since then, some of the nodes fail to start with the error: "Incompatible partition groups! expected: disabled / PER_MEMBER, found: enabled / CUSTOM".

The nodes all have exactly the same config so the error doesn't make sense.

If we just remove the Feign dependency the error disappears.

Any known incompatibilities between hazelcast with partition groups and feign?

**Comment by mdogan** [comment]
@costap: There's nothing reported. Were you able to find the problem? Can you post a code snippet to reproduce the issue?

**Comment by mmedenjak** [comment]
@costap what's your cluster size? Is it possible that one member has different partition group config (enabled=false, group type=PER_MEMBER)? You should see some other log statements such as :
`Invalid join request from ..., cause: ...`. You should check the configuration on those members.

**Comment by mmedenjak** [comment]
@costap any updates on the issue?

**Comment by costap** [comment]
@mmedenjak no updates I can't remember anymore but we didn't have this issue anymore. I think can be closed.
