### ISSUE TITLE
Proper way of heap-data conversion 

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#10249]
Current workaround is `ToHeapDataConverter` : https://github.com/hazelcast/hazelcast/pull/10245

**Comment by mmedenjak** [comment]
@ahmetmircik there is now a method exposed in OS: `InternalSerializationService#toData(java.lang.Object, com.hazelcast.nio.serialization.DataType)`. Can you use this?

**Comment by ahmetmircik** [comment]
@mmedenjak this issue was originally requested by @jerrinot but i'm ok with the new method `InternalSerializationService#toData(java.lang.Object, com.hazelcast.nio.serialization.DataType`

**Comment by mmedenjak** [comment]
I know there are some concerns as to how it should be exposed but this variant seems fine to me - at least as a start. Perhaps it could be even better but at least you don't need to subclass/override anything in EE, instantiate that EE class and inject it instead of the OS version...

**Comment by ahmetmircik** [comment]
@jerrinot wdyt, can we close this one?

**Comment by burakcelebi** [comment]
Closing with @jerrinot's confirmation.
