### ISSUE TITLE
[transaction] [map] TransactionalMapProxy depends on MapContainer

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#10254]
Creating a `TransactionalMapProxy` should not also trigger creation of the backing `MapContainer`.

**Comment by mmedenjak** [comment]
@vbekiaris can this be closed now?

**Comment by vbekiaris** [comment]
The fix for `TransactionalMap` is still pending.

**Comment by Donnerbart** [comment]
I started to work on this, but I'm stuck a bit on the `RecordFactory` dependency. All other fields could be initialized via the `MapConfig`, without the `MapContainer`: https://github.com/hazelcast/hazelcast/pull/11192
