### ISSUE TITLE
Hazelcast cluster with different data centers creating issue with file upload from my app, and noticed that network is low between the nodes

### ISSUE THREAD

**Issue by veerumallavarapu** [hazelcast/hazelcast#10319]
Hi All,

We have Hazelcast cluster with different data centers.  We are having this cluster along with our Application.  When we are using a uploading  a file feature from our application, the file is not getting uploaded especially the network traffic between the nodes is less than 20Kbps, if it is more than 400 kbps everything seems to be fine.  We are really not sure why the network traffic between the cluster nodes over 5701 port is poor and how it is impacting the application feature like uploading a file.

We are using tcipIPjoin for joining all the cluster nodes and hazelcast version is 3.6.4.

Your quick response to this issue is very much appreciated.

**Comment by veerumallavarapu** [comment]
The latest update is when the second cluster node is started , they are seeing the upload file feature in that first cluster became an issue.  I am really not sure how it is related to hazel cast as we know in the case of file upload first it will write the file to temp location of same cluster.   


It would be really appreciated for any quick pointers related to this issue.

**Comment by vbekiaris** [comment]
@veerumallavarapu it is not evident how Hazelcast is related to file upload in you application. Could you explain how is Hazelcast involved? Do you put the file itself in an `IMap` or other datastructure? 

It would be great if you could describe how you use Hazelcast, what is your configuration and any evidence (Hazelcast log entries, thread / heap dumps etc) which demonstrate an issue with Hazelcast. This way we will be able to diagnose any issue more effectively.

**Comment by veerumallavarapu** [comment]
In our case fileuploadStore is a map (private Map<String, UploadJobData> fileUploadStore). which holds an object UploadJobData.java it has four attributes (	String id;   int percentComplete,  int bytesUploaded ,  String errorMessage ).   We don't keep the file in this Map.  It will be copied to temp location then after to some DiskStorage.  


As I have mentioned earlier we have three cluster nodes.  Two are in same data center and one is in another data center.

The issue is occuring when file is getting uploaded from Data Center A and mean time if the node in other data center is joined.  

We have noticed in logs while joining nodes using tcpipjoin. I am not sure whether it helps. 

[serverlog2.txt](https://github.com/hazelcast/hazelcast/files/920242/serverlog2.txt)
[serverlog1.txt](https://github.com/hazelcast/hazelcast/files/920243/serverlog1.txt)

**Comment by mdogan** [comment]
@veerumallavarapu: We don't recommend having a cluster spanning multiple data centers, especially when there's a latency between data centers. 

You can gather more detailed metrics on members by enabling diagnostics;

```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30
```

See more at http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#diagnostics
