### ISSUE TITLE
Split Brain messages still occupies memory after recovery

### ISSUE THREAD

**Issue by sjursky** [hazelcast/hazelcast#10325]
Hi,  
we have Hazelcast v3.8 cluster with around 80 nodes distributed over 4 servers (2x24,2x16)
Usually the cluster breaks down during server-by-server apps redeployment and recovers after a while.

When we analyzed our last heap dump (~97% full), we found ~66k messages of `com.hazelcast.internal.cluster.impl.SplitBrainJoinMessage` allocated in 616MB. That's a lot.

Each message occupied 9kB and most of the message (8KB) consists of `memberAddresses ArrayList<com.hazelcast.nio.Address>` of 80 items (=number of nodes).

Those messages cannot even be GarbageCollected because of a reference from thread `com.hazelcast.internal.partition.impl.MigrationThread`.

We also noticed this behavior without server restart. After 26h server uptime there were 18k SplitBrainJoinMessages taking 167MB on heap. No restart was done, only some heavy tests and there are no Hazelcast errors in logs other than "MonitorInvocationsTask/BroadcastOperationControlTask delayed" right before heap dump creation.

What can we do to somehow debug this, or cleanup those messages from heap?
If you need more information please let me know.

Thanks in advance.
Regards

Stanislav

Environment:
Hazelcast 3.8
Cluster of 80 members
0 clients, each web application acts as a cluster member.
JDK7u75
hazelcast JVM related params: -Djava.net.preferIPv4Stack=true -DscMulticastAddress=231.12.21.132 -DscMulticastPort=50000 -DscIpTtl=1
OS: Oracle Linux 6.1

**Comment by mdogan** [comment]
Hi @sjursky,

Can you please attach a screenshot from heap dump analysis which shows how `MigrationThread` keeps references to `SplitBrainJoinMessage`s?  I'm still struggling to figure out how, a concrete sample will make its easier for us.

**Comment by sjursky** [comment]
Hi,
using memory analyzer merge paths to GC roots
![merge_paths](https://cloud.githubusercontent.com/assets/10976569/24963826/fd992442-1f9f-11e7-9efd-9d0b8064ac09.png)

I will try to find out that `MigrationThread` 
currently some screenshots from 18k messages heap is showing `com.hazelcast.spi.impl.operationexecutor.impl.PartitionOperationThread`

![reference](https://cloud.githubusercontent.com/assets/10976569/24963838/058b1d9a-1fa0-11e7-9df3-203358c6726e.png)

and from 66k messages `java.lang.Thread hz._hzInstance_1_UNIUS_APP.MulticastThread`

![reference_multicastthread](https://cloud.githubusercontent.com/assets/10976569/24964156/c29afc66-1fa0-11e7-8ee3-426222b83617.png)
