### ISSUE TITLE
add cluster health/safe check to rest api for kubernetes cluster

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#10330]
In kubernetes cluster, if you have multiple hazelcast members ( they form a cluster) then in case of:
- kubernetes rescheduling
- rolling upgrade
- scaling up/down
hazelcast members might be killed and re-deployed in the cluster. 
Kubernetes can restart the members one by one. In this process, when a member killed and deployed, every time hazelcast data migration process should be waited in order to prevent data lose.
Kubernetes has a health check feature ( https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-readiness-probes).. So if hazelcast offers cluster safe status as rest api, then all kubernetes operations are achieved without losing any data.

Somehow Kubernetes needs to check hazelcast members whether it is ready or not. After they are safe, then kubernetes will restart another member.
If hazelcast offers such a rest api, then an user can make rolling version upgrade to their hazelcast cluster without losing any data and just one command line.
Another use case might be map load/store scenario.

**Note: this api should return between 200-400 code in case of safe cluster.. Kubernetes looks response code.**

**Comment by mdogan** [comment]
I think this is already fixed via https://github.com/hazelcast/hazelcast/pull/9284

**Comment by bilalyasar** [comment]
@mdogan, i don't think so, kubernetes only looks return code rather than content of the response.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
`Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.
`
#9284 might return 200 in case of cluster not ready. this will be problematic for k8s.

**Comment by mdogan** [comment]
Ok then, I misunderstood the problem.

**Comment by googlielmo** [comment]
I think this is solved by the `liveness.sh` script that is included in the Hazelcast Kubernetes Docker image: https://github.com/googlielmo/hazelcast-docker/blob/master/hazelcast-kubernetes/liveness.sh

The script uses the API from #9284 but adds extra logic to parse the response and exits with an appropriate status code (0 or 1).

It can be configured like this:
```
        livenessProbe:
          exec:
            command:
            - "./liveness.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10```

See https://github.com/googlielmo/hazelcast-docker/blob/master/hazelcast-kubernetes/README.md for a complete example.

@bilalyasar could you please confirm that this addresses the original issue?
