### ISSUE TITLE
ExecutionCallback.onFailure behaves differently between client and server

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#10335]
In hazelcast servers, exceptions are delivered to `ExecutionCallback.onFailure` directly.
In hazelcast clients, they are wrapped to ExecutionException.

**Comment by sancar** [comment]
Decided not to apply fix right now because of compatibility. Postponed to 4.0

**Comment by pveentjer** [comment]
We should align this with the CompletableFuture behavior.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/6247
