### ISSUE TITLE
Client invoking long operation causes a member to leave cluster for some time

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10384]
I described this issue in the chat so just copy&pasting the same information here.

Running a test in a large 3.7.3 cluster (do not remember exactly - something about 40 nodes). Cluster has a single IMap  in it populated with about half a million entries. The cluster put under a heavy load with many threads from multiple nodes firing invoking EntryProcessors on that map. Everything seem to work ok until I run another test.

Now, the problem-causing test client attempts to use PagingPredicate to iterate over all the entries there. Every time I run the client, it crashes saying that a member has left the cluster. Checking logs from all the members in Kibana I can see that (and below it the copy&paste of what I sent to chat):

So yes, looks like one member was kicked out of the cluster. There was relatively low log traffic as nodes communicated about that:
* the first one said 
```
[10.0.163.225]:5701 [] [3.7.3] Connection[id=3462, /10.0.163.225:58555->/10.0.151.73:5701, endpoint=[10.0.151.73]:5701, alive=false, type=MEMBER] closed. Reason: Removing Member [10.0.151.73]:5701 - 14fe04f0-0622-4c49-9e63-e5395975045c because it has not sent any heartbeats for 30000 ms. Now: 2017-04-18 16:34:40.999, last heartbeat time was 2017-04-18 16:34:09.538
```
* all others followed "[10.0.170.244]:5701 [] [3.7.3] Connection[id=3413, /10.0.170.244:45281-
```
/10.0.151.73:5701, endpoint=[10.0.151.73]:5701, alive=false, type=MEMBER] closed. Reason: Removing member [10.0.151.73]:5701, uuid: 14fe04f0-0622-4c49-9e63-e5395975045c, requested by: [10.0.163.225]:5701
```

From the perspective of the 10.0.151.73, it lost connection to everything so it "removed" all members from its version of cluster. And where all nodes together logged less than a thousand messages, the 10.0.151.73 logged 63K messages (!). Just endless series of
* [10.0.151.73]:5701 [] [3.7.3] Established socket connection between /10.0.151.73:5701 and /10.0.174.205:54042
* [10.0.151.73]:5701 [] [3.7.3] Accepting socket connection from /10.0.174.205:54042
* [10.0.151.73]:5701 [] [3.7.3] Connection[id=49652, /10.0.151.73:5701->/10.0.174.205:54042, endpoint=null, alive=false, type=NONE] closed. Reason: Connection closed by the other side

-------------------

The 30 seconds mentioned in the first timeout message matches to the 
```
<property name="hazelcast.max.no.heartbeat.seconds">30</property>
```
which I configured on server side. Which makes me believe that "select all" operation invoked by the client completely occupies one node for more than 30 seconds preventing it even from sending heartbeats.

**Comment by mdogan** [comment]
I think, this can happen when members suffer from long pauses under heavy load (CPU & memory wise). During long pauses, members can fail to send heartbeat messages to each other and assume failing members as dead/crashed. 

Can you gather GC logs during execution (via `-verbose:gc`)? 

Also you can enable Hazelcast diagnostics http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#diagnostics 

```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30
```

**Comment by mmedenjak** [comment]
@dimas have you had time to add some statistics and collect GC logs? Also, how big is your data set over which you are paging?

**Comment by dimas** [comment]
Gosh, it was 3 months ago and we ran dozens of different tests since then to check hazelcast scalability so I won't be able to remember which one exactly I ran before raising this issue...

I think the dataset was about 5G-10G in total or 125Mb-250Mb per node. Each entry is just a multi-level nested Map. It won't be easy recreating the same test and I doubt I can do it really soon.

**Comment by mmedenjak** [comment]
Seems like the member stopped sending heartbeats to other members - could be because it was under heavy load. Have you lowered the heartbeat timeout to 30 seconds? You should probably try increasing that - it will take more time to determine that a member has crashed but the cluster will be more tolerant to one member not sending heartbeats.
You can also try using a profiling tool to determine where the most time is being spent but given that you were running lots of entry processors, I expect that to come on top.
PagingPredicate is not very efficient so in the combination with entry processors could have caused a high load on the cluster.

**Comment by jerrinot** [comment]
closing due inactivity of the reported. feel free to reopen it.
