### ISSUE TITLE
[map] [io] Loss of throughput when after scaling cluster down and then back up

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10418]
We ran a series of scale tests with Hazelcast 3.7.3 cluster and noticed a strange thing.

Background:
Two maps in the cluster, 1M entries each. Multiple load test clients invoke the same operation on randomly selected entries. Each operation involves invocation of two EntryProcessors, one on each map.
(Initially dataset is empty, but these EntryProcessors when invoked create an entry if it does not exist yet)

1. started with 15 node cluster
2. put that cluster under load, let it stabilise measured requests per second across all the clients. 89K op/sec
3. reduced cluster size to 12. This caused some loss of data as no backups were used but those repetitive operations from clients effectively re-create the same entries so it will be back to 1M after some time
4. let it stabilise again and measured total throughput of test clients. No surprise here, it dropped to 64K op/sec.
5. Grew cluster back to 15 nodes
6. let it stabilise again and measured total throughput again. 77K op/sec

Now, the last bit is a bit surprising because cluster performance never returned to its original level.
We do not understand reason for this because there is no noticeable imbalance in CPU utilisation across these nodes. Nor there is significant imbalance in how dataset is partitioned.

To be frank, our setup is a bit more involved than described as there is a RESTful web service between client and Hazelcast. This extra step should explain to you initial 89K/sec in case you expected more from cluster of that size. Obviously web service adds some latency but it is absolutely stateless thing - when you make HTTP call to it, it just immediately makes a call to Hazelcast and does nothing more. And we put a huge cluster of these web servers - way more than needed to handle the volume we had. And during the experiment we did not touch these web servers, only played with number of Hazelcast servers.

Creating an isolated test seems to be a lot of effort so before doing anything like that I would really like to:
* get your feedback on that - maybe you already encountered similar issue before and know what can be causing it
* check if you already have such (or a similar) test

Cheers

**Comment by jerrinot** [comment]
hi @dimas,

this is certainly suspicious and unexpected. Are you using clients-server or server-server topology? 

Could you start your cluster with the `hazelcast.io.thread.count` property set to `1`  and each node and repeat the test? It's quite likely the throughput will be lower, but I wonder if it resumes to the original level in the 6th step.

**Comment by dimas** [comment]
Sorry, I am not sure what you mean by clients-server or server-server. When our web servers call Hazelcast, they use hazelcast client (smart one) to make these calls. They are not join the cluster themselves. Is it what you asked?
We will try the test with hazelcast.io.thread.count=1
Thanks

**Comment by jerrinot** [comment]
yes, that's exactly what I was asking for - you are using clients. thanks for clarification.

I am looking forward to see your test results!

**Comment by ttamimi** [comment]
I conducted the test again using Hazelcast version 3.7.7. The permanent drop was still observed when setting hazelcast.io.thread.count=1, but it was less severe. See chart:
![Metrics chart] (https://www.dropbox.com/s/axudy0rhqye0djj/hazelcast-3.7.7%20annotated-public.png?dl=0)

**Comment by dimas** [comment]
@jerrinot , do you need anything else from us? Or were you able to replicate the problem?

**Comment by dimas** [comment]
Chaps?

**Comment by tombujok** [comment]
@dimas If it's easy for you to reproduce, could you try with 3.8.3 to see if it's still there?

**Comment by dimas** [comment]
Unfortunately we cannot move to 3.8 as some stuff has been deprecated there.
What changes in Hazelcast make you believe it can be fixed in 3.8.3 ?

**Comment by tombujok** [comment]
@dimas We work on the infrastructure in every release, 3.8 included many non-functional fixes. Did you ever manage to test with 3.8? It would help us a lot.

**Comment by Holmistr** [comment]
Hi @dimas , seems like there was some inactivity for quite some time. During the 3.9, there were also so many changes in the infrastructure and we performed extensive testing on it, even with scaling down and back up and didn't notice any issues. Would it be possible to re-run the tests one more time? I believe you should not hit the issue anymore.

**Comment by dimas** [comment]
We can ask @ttamimi to give it a go. But we are pretty busy too so don't expect that to happen within the few days... Couple of weeks time seems more realistic.

**Comment by Holmistr** [comment]
@dimas I totally understand, these things take much more time than expected usually. We would really appreciate this effort. Please keep up in the loop if anything new. Thanks :)

**Comment by ttamimi** [comment]
@Holmistr, we re-ran the scale tests with version 3.9 and I am happy to report that the problem has indeed been solved. Please feel free to close this ticket. Thank you.

**Comment by mmedenjak** [comment]
@ttamimi glad to hear that. Feel free to open a different issue if needed.
