### ISSUE TITLE
Please update hazelcast-client-config.xsd

### ISSUE THREAD

**Issue by zhangchi** [hazelcast/hazelcast#10449]
even for the latest hazelcast-client-config, 
```xml
<xs:element name="global-serializer" type="xs:string" minOccurs="0" maxOccurs="1"/>
```
`global-serializer` is missing the attribute of `override-java-serialization`, which has been available in `hazelcast-config.xsd` for a while. 
```xml
<xs:complexType name="global-serializer">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="override-java-serialization" type="xs:boolean" default="false" use="optional">
            </xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>
```
We have created a local `hazelcast-client-config.xsd`, copied the `global-serializer` from `hazelcast-config-xsd` and it worked.  Would be great if you guys can update the `client-config.xsd`

**Comment by jerrinot** [comment]
good catch, thanks!
