### ISSUE TITLE
WAN backup events are published twice

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#10457]
The `publishWanReplicationEventBackups` method is called in the `run` and `afterRun` method in the `PartitionWideEntryBackupOperation`. Elsewhere it is only called in `afterRun`. This needs to be checked but possibly the fix is just to remove the call in `run`.

**Comment by ahmetmircik** [comment]
@mmedenjak this PR should fix that problem: https://github.com/hazelcast/hazelcast/pull/10453
