### ISSUE TITLE
Future.complete(Object value) can only be called once

### ISSUE THREAD

**Issue by aunlu** [hazelcast/hazelcast#10456]
V3.7.7 Hz client gets following warning:

> 2017-04-27 11:35:07,522 WARN  [hz.client_0.response-] [ClientInvocationService]  hz.client_0 [NE_GROUP] [3.7.7] Future.complete(Object value) can only be called once. Request: ClientMessage{length=43, correlationId=2016, messageType=306, partitionId=80, isComplete=true, isRetryable=false, isEvent=false, writeOffset=0}, current value: java.lang.InterruptedException, offered value: ClientMessage{length=22, correlationId=2016, messageType=69, partitionId=-1, isComplete=false, isRetryable=false, isEvent=false, writeOffset=0}

Scenario:
There is one hz server node, several hz client nodes. There is a distributed queue. At one point, threads, waiting on queue.take() in clients, get interrupted. Later, more threads are created for waiting on queue.take() in the client. When items are put into the queue, items are lost and above warning is printed in the client log.

**Comment by pveentjer** [comment]
I think the warning level is too high. It is possible that an invocation gets multiple responses

**Comment by sancar** [comment]
The log from is `AbstractInvocationFuture` . It is both used on server and client. 
One option could be to suppress the warning on when current value is InterruptedException, because this is specifically asked by user.

Other option to change the warning to info completely. 
@pveentjer What do you think ?

**Comment by jerrinot** [comment]
moving to 3.9.1. the logging can be changed later. 
messages can be lost when a waiting thread is interrupted. you can use Hazelcast ReliableTopic if you cannot tolerate this.

**Comment by sancar** [comment]
If there is no objection, I would like to close this issue without taking any action. 
WARNING log here seems more appropriate to me. 
Any objections/ideas @pveentjer @mmedenjak  ?

**Comment by mmedenjak** [comment]
Closing the issue. As mentioned here, if a waiting thread is interrupted, that does not mean that the operation will not take effect. In your case, items were taken off the queue even though you have interrupted the calling thread.
Please reopen the issue or create a new one if this is not expected.
