### ISSUE TITLE
Management Console Reporting incorrect values for backups

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#10454]
Given that there is one copy of the data across a Native Map I was expecting to see identical memory footprint on the entry and the backups with identical sum across a server. But it's not the case.
I am running 3.8.1 Dot Net client and 3.8.1 server side on Windows
The same stats on Linux servers shows the Entry memory and Backup Memory correctly with consistent results per server (running 3.8.1).
1st screen shots (2 servers) represents the Windows view: here the total memory entries does not match the total memory backups
2nd screen shot is the home view of that first Map view
3rd screen shot shots the map view of Linux where memory on entries = memory on backups
1:
![image001](https://cloud.githubusercontent.com/assets/3787862/25479035/2bfbab0e-2b4c-11e7-805b-78ba2a97fb57.png)
2:
![image002](https://cloud.githubusercontent.com/assets/3787862/25479067/48f930c8-2b4c-11e7-8d54-92e61cf4cedb.png)
3:
![image003](https://cloud.githubusercontent.com/assets/3787862/25479080/51b31468-2b4c-11e7-86b3-c526c95e6a71.png)

**Comment by sertugkaya** [comment]
ZD no: 2655

**Comment by tkountis** [comment]
Back-ported in 3.8.2 hazelcast/hazelcast#1462

**Comment by tkountis** [comment]
This appears to be a problem with partition migrations, rather than the OS itself. When partitions are cleared due to replication/migration etc, then the size was not cleared, and the new data just added up to the previous value. The fix should mitigate that issue.
