### ISSUE TITLE
3.7.7 Hz client failover not working

### ISSUE THREAD

**Issue by aunlu** [hazelcast/hazelcast#10466]
We have a setup with 2 server nodes (with IPs 10.133.203.34, 10.133.203.35) and several client nodes. Clients are using distributed queues. Queues have one backup. All queues are working on 10.133.203.34, backups are on 10.133.203.35.

At one point, 10.133.203.34 rebooted abruptly. Clients got the following errors:

> 2017-05-02 03:42:51,246 WARN  [hz.client_1.internal-1] [ClientConnectionManager]  hz.client_1 [NE_GROUP] [3.7.7] Heartbeat failed to connection : ClientConnection{live=true, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/10.133.203.32:38812 remote=/10.133.203.34:5701]}, remoteEndpoint=[10.133.203.34]:5701, lastReadTime=2017-05-02 03:41:46.245, lastWriteTime=2017-05-02 03:42:46.245, closedTime=never, lastHeartbeatRequested=2017-05-02 03:42:46.245, lastHeartbeatReceived=2017-05-02 03:41:46.246, connected server version=3.7.7}

I was expecting clients to connect to to 10.133.203.35 and move on their operations with no downtime. Instead clients got following error:

> 2017-05-02 03:44:17,279 WARN  [hz.client_1.event-6] [ClientConnection]  hz.client_1 [NE_GROUP] [3.7.7] ClientConnection{live=false, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/10.133.203.32:38812 remote=/10.133.203.34:5701]}, remoteEndpoint=[10.133.203.34]:5701, lastReadTime=2017-05-02 03:41:46.245, lastWriteTime=2017-05-02 03:44:16.245, closedTime=2017-05-02 03:44:17.261, lastHeartbeatRequested=2017-05-02 03:44:16.245, lastHeartbeatReceived=2017-05-02 03:41:46.246, connected server version=3.7.7} lost. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[Closing connection to member [10.133.203.34]:5701. The client has closed the connection to this member, after receiving a member left event from the cluster. Connection=ClientConnection{live=true, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/10.133.203.32:38812 remote=/10.133.203.34:5701]}, remoteEndpoint=[10.133.203.34]:5701, lastReadTime=2017-05-02 03:41:46.245, lastWriteTime=2017-05-02 03:44:16.245, closedTime=never, lastHeartbeatRequested=2017-05-02 03:44:16.245, lastHeartbeatReceived=2017-05-02 03:41:46.246, connected server version=3.7.7}]

When I checked hz logs on 10.133.203.35. I found following:

> 2017-05-02 03:43:00,933 INFO  [hz._hzInstance_1_NE_GROUP.IO.thread-Acceptor] [SocketAcceptorThread] [10.133.203.35]:5701 [NE_GROUP] [3.7.7] Accepting socket connection from /10.133.203.32:51273
2017-05-02 03:43:00,934 INFO  [hz._hzInstance_1_NE_GROUP.cached.thread-5] [TcpIpConnectionManager] [10.133.203.35]:5701 [NE_GROUP] [3.7.7] Established socket connection between /10.133.203.35:5701 and /10.133.203.32:51273
2017-05-02 03:43:00,936 INFO  [hz._hzInstance_1_NE_GROUP.priority-generic-operation.thread-0] [AuthenticationMessageTask] [10.133.203.35]:5701 [NE_GROUP] [3.7.7] Received auth from Connection[id=76, /10.133.203.35:5701->/10.133.203.32:51273, endpoint=null, alive=true, type=JAVA_CLIENT], successfully authenticated, principal : ClientPrincipal{uuid='004fe5dd-2412-4498-847d-f809954e30b5', ownerUuid='c16315f4-925f-49d8-9869-359a005af081'}, owner connection : true, client version : 3.7.7

> 2017-05-02 03:43:03,938 INFO  [hz._hzInstance_1_NE_GROUP.IO.thread-in-0] [TcpIpConnection] [10.133.203.35]:5701 [NE_GROUP] [3.7.7] Connection[id=76, /10.133.203.35:5701->10.133.203.32:51273, endpoint=[10.133.203.32]:51273, alive=false, type=JAVA_CLIENT] closed. Reason: Connection closed by the other side
> 2017-05-02 03:43:03,938 INFO  [hz._hzInstance_1_NE_GROUP.event-5] [ClientEndpointManager] [10.133.203.35]:5701 [NE_GROUP] [3.7.7] Destroying ClientEndpoint{connection=Connection[id=76, 0.0.0.0/0.0.0.0:5701->10.133.203.32:51273, endpoint=[10.133.203.32]:51273, alive=false, type=JAVA_CLIENT], principal='ClientPrincipal{uuid='004fe5dd-2412-4498-847d-f809954e30b5', ownerUuid='c16315f4-925f-49d8-9869-359a005af081'}, firstConnection=true, authenticated=true, clientVersion=3.7.7}

Why the clients could not connect to 10.133.203.35 ?

**Comment by sancar** [comment]
Are clients using smartRouting ? 
It says it is closing connection to 10.133.203.34 because it left the cluster ? 
What does 10.133.203.35 is reporting about this ? What is the member list it prints around that time ?
From the logs it seems that client successfully connected at first. 10.133.203.35 is saying that client closed the connection. You need to check what client is saying about connection to `10.133.203.35` at that time

**Comment by sancar** [comment]
Hi @aunlu , 
I have to close this because I could not get any response from you. Please provide feedback when you are available if there is still an issue.
