### ISSUE TITLE
New cache eviction is populated among nodes very slow

### ISSUE THREAD

**Issue by krueger** [hazelcast/hazelcast#10470]
I configured a two node Hazelcast cluster with a NearCache and measured the time when a put in one node is propagated to the other node. It always takes some seconds when the other node can see the new value.

For my use case I need a faster propagation. Is this possible?

**Comment by ahmetmircik** [comment]
Hi, 
Can you see it propagated faster when you set `hazelcast.map.invalidation.batch.enabled` to `false`?

Some more details are here:  http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#near-cache-invalidation

**Comment by ahmetmircik** [comment]
Please reopen this issue, if my suggestion doesn't work.

**Comment by krueger** [comment]
The suggestion was helpful. Thx.
