### ISSUE TITLE
When are cached deserialised values cleared(garbage-collected)?

### ISSUE THREAD

**Issue by pratikkumar19** [hazelcast/hazelcast#10512]
The issue I am facing is that :
- Predicate queries are run from multiple clients(IMap are indexed on  a single field and queries are run on the same field)
- After a few mins, memory is filled up in Old Gen  and triggers an old gc
- After the old gc runs, most of the old gen space is freed-up.(Java Flight Record shows most of garbage collected objects as weak-references)
My question is: Are the cache serialised values getting tenured to old gen? If yes, then, is there an option in hazelcast to set a time-to-live for these objects?
Hazelcast Version: 3.8.1

**Comment by tombujok** [comment]
What memory format are you using?
I assume there were no delete operation in-between?

**Comment by pratikkumar19** [comment]
We are using BINARY memory format. There are no delete operations in between.(if delete operations means deleting key-value entry)

**Comment by mdogan** [comment]
might be related to https://github.com/hazelcast/hazelcast/issues/10672

**Comment by pratikkumar19** [comment]
Any updates?

**Comment by pratikkumar19** [comment]
This problem is currently occurring in our production environment. Also this is kept in check currently by limiting the amount of client restarts simultaneously.

**Comment by mmedenjak** [comment]
@pratikkumar19 are you sure those are cached deserialised values in the old gen? Have you analysed a heap dump? 
Can you provide a reproducer or a snippet of code which you are running?

**Comment by mmedenjak** [comment]
@pratikkumar19 any update on the issue?

**Comment by mmedenjak** [comment]
@pratikkumar19 any update on the issue?

**Comment by jerrinot** [comment]
closing due inactivity of the reporter. feel free to re-open it when you have more data. thanks!
