### ISSUE TITLE
Way to get key ownership information

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10510]
Would be nice to have ability to quickly find which partition given key is assigned to and what member owns has it.

One obvious place where to put that functionality is Management Centre map browser. But may be there are better places like the CLI tool.

**Comment by pveentjer** [comment]
In the code you can use something like this

```
  Member owner = hazelcastInstance.getPartitionService().getPartition("foobar").getOwner();
```

**Comment by dimas** [comment]
The code was already deployed and running when the need to find owner for a particular key was identified (to investigate other issues with the cluster).
We ended up writing script for Management Center to do that but this looks like a diagnostic functionality that should be available out of the box. Either in MC or in CLI. Of course, it is possible to write another java app that will connect to the cluster and give you that info but then each of your users will be building their own diagnostics tools.
Cheers

**Comment by emre-aydin** [comment]
@dimas Management Center 4.1 will have this feature. Closing the issue.
