### ISSUE TITLE
Delaying AWS discovery until tags propagate

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10537]
We use AWS discovery and since old times (hazelcast 3.5) our startup script has a hardcoded delay with a comment saying it is needed for Amazon EC2 instances tag to propagate. So I was told the problem is that when EC2 instance boots and Hazelcast starts on it, there is no guarantee that Amazon's discover-instances call that looks for instances by their tags will see them as it may take some time for tags to propagate.

So how the problem did manifest itself for us: when a new server cluster is started and Hazelcast on multiple nodes starts roughly at the same time, these nodes may not find each other and the cluster won't build as each of them will believe it is the only member in the cluster.

Yes, the delay was introduced when we used very old hazelcast version (3.5, as I said) but I do not see anything to mitigate the issue in the current code base. It looks to me that the same will happen with the current code: https://github.com/hazelcast/hazelcast-aws/blob/d746d4cb39d263728684204a22e7ad3c81105ae5/src/main/java/com/hazelcast/aws/AwsDiscoveryStrategy.java#L97

I was thinking - isn't it a better approach for AwsDiscoveryStrategy to block until it can successfully find at least one member?

PS: I do not know if I can reproduce problem reliably and how to do that but I witnessed Hazelcast failure to build cluster and building multiple small clusters instead couple of times.
PPS: It can, of course, be AWS issue instead - I do not know what are their guarantees in that area but I would assume they are about "eventual consistency" there...

**Comment by mesutcelik** [comment]
With that [PR](https://github.com/hazelcast/hazelcast-aws/pull/23), we have gained tremendous amount of time where we have been spending on parsing so getting tag values are quicker now. 
This version is not released yet and that is beneficial if tag is already there.

I believe you somehow be sure that `tag propagation` is there before launching cluster which might be done by some other tool or script.

**Comment by dimas** [comment]
I do not think that PR has anything to do with the issue I raised. It is not a question of how quickly can you get tags from Amazon. It is the question of can guarantee that at the moment of Hazelcast start tags have propagated at all and are searchable.

Of course, waiting for tag propagation can be done by some other means and this is what we do - our Hazelcast startup script tries to find running instances matching the specification before it starts the Hazelcast itself. However that means that everyone using Hazelcast in EC2 environment will have to invent something like that. But people are not even aware of the problem so they won't. Until one time their Hazelcast do not fail to cluster. And that won't be obvious what exactly went wrong.

After all, I personally see no point in starting a member if you cannot find other members with your search criteria. Even in the case of single-node cluster, a member at least should be able to find itself. If it cannot, how anything else with the same search criteria can find it ?

**Comment by mesutcelik** [comment]
@dimas , you are right. 
I have created an issue in aws repo for that. 
https://github.com/hazelcast/hazelcast-aws/issues/28
