### ISSUE TITLE
Wrong property name partition.count in xsd files

### ISSUE THREAD

**Issue by 3mek** [hazelcast/hazelcast#10544]
Still wrong here:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.9.xsd#L1951
and here:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.8.xsd#L1951
and so on...

this also applies to older documentation.

**Comment by emrahkocaman** [comment]
Thanks for reporting @3mek .  Good finding 👍
