### ISSUE TITLE
Hazelcast get returning None even if key is present

### ISSUE THREAD

**Issue by vinznv** [hazelcast/hazelcast#10568]
Hi

Scenario is, we keep key 'sync_complete' in hazelcast. and we poll it once per minute. If key is present or we received any exception like connection not active etc, we dont do resync.  but If key is missing, indicates us that Hazelcast cluster restarted and we lost required data from that. So we trigger sync again.

Problem what we observe is sometimes even if key is present, we get None in return. We are using Hazelcast-Python-Client version 3.8.1. Say we miss value for 1 in 10000 iteration. but this is critical for us. 

To reproduce just poll for a key consistently in a loop. we have reproduced it consistently like this. sometimes it happences 1/10,000 and sometimes 1/100,000. This is kind of unpredictable for us.
In scale test beds which has 175k entries in a map, Its observed very frequently. 

When I tried to reproduce, I kept only one key in map. I am happy to provide more information on this. This is a release blocker for us for next release. 

with regards
Vinayaka

**Comment by mdogan** [comment]
Might be a https://github.com/hazelcast/hazelcast-python-client issue.

**Comment by vinznv** [comment]
Hi,

Can you please let us know whats the issue. Is there any workaround.
This is a production blocker for us.

**Comment by mdogan** [comment]
Can you please provide a reproducer? I tried following but issue didn't appear;

**Comment by tombujok** [comment]
@vinznv reproducer appreciated

**Comment by vinznv** [comment]
Hi mdogan / tombujok

Sorry for delay. I will done a reproducer code and get back here with logs. As far as I see snippet, What's different without our's is we close client connection. 

Steps : 
1. Open connection
2. Retrieve key value
3. Close connection

Steps 1 to 3 are repeated once in minute.

When we observed issue, In a dev setup when we continuously polled for key.

I am validating reproducer code. I will attach logs for code snippet here.

This information may be helpful for you.

I will be frequently checking this thread. Incase If you dont see my response , please drop a mail to 
vvasantha@arubanetworks.com , I will get back ASAP.

with regards
Vinayaka

**Comment by vinznv** [comment]
Hi mdogan / tombujok

Tried to reproduce issue. I am not able to reproduce this scenario. In case I hit this issue again, I will raise ticket with reproducer. Closing this issue.

It will be great help if you can give me a code snippet with listener,  When Entire cluster goes down, and how we ensure, when one of clusters come up, we will get call back.

It will be great help for us.

**Comment by vinznv** [comment]
Closing this issue as we are not able to reproduce.
