### ISSUE TITLE
Security token logged by AWS joiner on a failed attempt to describe instances

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#10576]
com.hazelcast.cluster.impl.TcpIpJoinerOverAWS:
```
[10.0.167.250]:5701 [] [3.7.7] Server returned HTTP response code: 503 for URL: https://ec2.eu-west-1.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...&X-Amz-Date=20170512T200742Z&X-Amz-Expires=30&X-Amz-Security-Token=...&X-Amz-Signature=...&X-Amz-SignedHeaders=host
```
I know little about AWS security tokens, most likely the one logged cannot be used for anything sinister besides another DescribeInstances call but still feels a bit dodgy when anything like "credentials" or "securitytoken" goes to logs. People may be sending logs to some syslog server...

**Comment by pveentjer** [comment]
That should indeed by resolved.

**Comment by mesutcelik** [comment]
@leszko is this still the case after your latest refactorings?

**Comment by leszko** [comment]
The case is still valid at the moment, but I plan to remove (soon) "TcpIpJoinerOverAWS" and all the deprecated `<aws>`. So, I'm assigning myself to this issue.

**Comment by SheuShec** [comment]
Any update on this front @leszko ?

**Comment by leszko** [comment]
`TcpIpJoinerOverAWS` is removed and the security token is not printed anywhere. Closing the issue. Please reopen if needed.
