### ISSUE TITLE
Key specific TTL is not invalidated when calling put(K key, V value) causing the latest value to still be evicted

### ISSUE THREAD

**Issue by wneild** [hazelcast/hazelcast#10580]
Scenario: Putting an entry into a map with an explicit TTL and subsequently, before the TTL has expired, putting an entry without an explicit TTL

Expected: the original TTL is invalidated and the latest inserted entry does not get evicted
Actual: the latest value inserted without a TTL is evicted

Here's a failing test that demonstrates this behaviour:

```java
public void shouldNotExpireEntriesThatAreSetWithTTLThenOverwrittenWithoutTTL() throws InterruptedException {

    final HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance();
    final IMap<String, String> map = hazelcastInstance.getMap(MAP_NAME);

    assertNull(map.get(KEY));

    map.put(KEY, VALUE_ONE, 1L, TimeUnit.SECONDS);

    assertEquals(VALUE_ONE, map.get(KEY));

    map.put(KEY, VALUE_TWO);

    Thread.sleep(1000L);

    assertEquals(VALUE_TWO, map.get(KEY)); // Assertion failure, value is null
}
```

**Comment by tombujok** [comment]
Looks like a bug. thx

**Comment by ahmetmircik** [comment]
@wneild you can also set map-wide TTL via map config. What will be the expected behaviour of `map.put(key,value)` in that case? Will `map.put(key,value)` override map wide TTL and make it live forever? 

Currently, `map.put(key,value)` preserves whatever the existing TTL is. If TTL is wanted to be changed, it should be given explicitly. This is the intended design. I assume any change here can break lots of existing code which coded against this behaviour.

**Comment by wneild** [comment]
@ahmetmircik If this is the intended behaviour I would criticise the interface of IMap. Moreover, the behaviour of setting a ttl on a key should never have been conflated with the action of putting a value into the map. A more intuitive interface, in my opinion, would be `void setTtl(K key, long ttl, TimeUnit timeunit)`, scrapping `void set(K key, V value, long ttl, TimeUnit timeunit)`.

**Comment by ahmetmircik** [comment]
Configuring `max-idle-seconds` can be thought as an alternative to `setTtl`. Not sure about possible use cases of it.  But in any case, you can file a new issue and if we see demand, it can be implemented.

**Comment by wneild** [comment]
`max-idle-seconds` is map-wide setting as opposed to key specific setting so I can't see how it could be an alternative? My previous comment was addressing rethinking the interface to configuring key-specific ttl to avoid this confusion in the future. If you agree with the principle of my argument, I'll raise a separate issue referencing this one for the proposed change.

**Comment by ahmetmircik** [comment]
>max-idle-seconds is map-wide setting as opposed to key specific setting so I can't see how it could be an alternative? 

it depends on the scenario but right `max-idle-seconds` is not a one-to-one alternative.

>My previous comment was addressing rethinking the interface to configuring key-specific ttl to avoid this confusion in the future. If you agree with the principle of my argument, I'll raise a separate issue referencing this one for the proposed change.

Please, file an issue, solution may be different or similar but recording the problem will be a step further. I'm ok with creating a new issue for this.

**Comment by wneild** [comment]
Working as intended (see comments).
