### ISSUE TITLE
[io] Spinning_TcpIpConnectionManager_ConnectMemberTest  & Spinning_TcpIpConnection_BasicTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#10659]
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.getOrConnect_whenAlreadyConnectedSameConnectionReturned
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.testConnectionCount
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.connect
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.destroyConnection_whenActive
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.destroyConnection_whenAlreadyDestroyed_thenCallIgnored
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnectionManager_ConnectMemberTest.getOrConnect_whenNotConnected_thenEventuallyConnectionAvailable
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.getPort
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.test_equals
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.write_whenNonUrgent
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.lastWriteTime_whenNothingWritten
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.getInetAddress
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.write_whenUrgent
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.getRemoteSocketAddress
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.write_whenNotAlive
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.lastReadTimeMillis
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.lastReadTime_whenNothingWritten
com.hazelcast.internal.networking.spinning.Spinning_TcpIpConnection_BasicTest.lastWriteTimeMillis_whenPacketWritten

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1511/#showFailuresLink

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1359/consoleFull#1654123599befca796-5603-419b-b87e-3b231b9aafc7

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/1358/consoleFull#1654123599befca796-5603-419b-b87e-3b231b9aafc7

**Comment by pveentjer** [comment]
This test failed at the moment the cleanup to the IO system was done and hasn't failed since. So I'm assuming it is related to that cleanup.
