### ISSUE TITLE
Hazelcast member is removed from cluster

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast#10683]
We are getting the following warning and the hazelcast member is removed from the cluster

WARNING: [plat-app01.com]:5701 [dev] [3.8.1] Removing Member [plat-app01.com.io]:5702 - 2cd19320-17bd-4861-86a3-a68e208a9c4f because it has not sent any heartbeats for 300000 ms. Now: 2017-05-31 13:37:22.878, last heartbeat time was 2017-05-31 13:32:22.172

What could be the reason for the above warning?Same warning is getting displayed in all clusters and the members are disconnected.

**Comment by mdogan** [comment]
That means ` [plat-app01.com.io]:5702` didn't send heartbeat messages in last 5mins. Each Hazelcast member sends heartbeats to other members periodically (each 5 seconds by default). And if a member fails to send a heartbeat in a timeout period (5mins by default), then it's considered dead/crashed and it's removed from the cluster by the eldest member.

Reasons for not sending heartbeat can be a network failure between members or long process pauses (GC pause) on a member etc.
