### ISSUE TITLE
No API to add a ClassDefinition to Config in C++ Client

### ISSUE THREAD

**Issue by mstier** [hazelcast/hazelcast#10680]
Use-Case:
I'd like to exchange objects between a C++ client and a Java client using Hazelcast.

Current implementation:
The classes implement the portable interface with the methods readPortable() and writePortable(). Some members are objects themselves whose classes implement portable too. 

Problem:
Some of those object members might be NULL at the time of writing them into Hazelcast. ProtableWriter raises an Exception that NULL objects can't be written unless a ClassDefinition is registered into the SerializationConfiguration. There is an API which would allow doing that using the Java-client, but not for C++.

Sample code for Java:

```
final ClassDefinition classDefinition = new ClassDefinitionBuilder(Foo.factoryId, Foo.getClassId)
                       .addUTFField("foo").build();
config.getSerializationConfig().addClassDefinition(classDefinition);
Hazelcast.newHazelcastInstance(config); 
```

The method "addClassDefinition()" is missing in the C++ API

**Comment by ihsandemir** [comment]
Yes, this API is missing currently for C++ client. I opened an issue to implement it at the C++ repository: https://github.com/hazelcast/hazelcast-cpp-client/issues/292 Thanks for reporting.

**Comment by sancar** [comment]
Then I am closing this one. There is no need to keep both tickets. 
@mstier please follow the issue from  hazelcast/hazelcast-cpp-client#292
