### ISSUE TITLE
3.9-SNAPSHOT  A Configuration mismatch was detected: Incompatible group password!

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10692]
https://hazelcast-l337.ci.cloudbees.com/view/multi-version/job/multi-version-stable-All/7/console

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_02-03_57_59/stable/aggregator/predicate/output/HZ/HzMember8HZ/out.txt

```
SEVERE: [10.0.0.190]:5701 [HZ] [3.9-SNAPSHOT] Node could not join cluster. A Configuration mismatch was detected: Incompatible group password! Node is going to shutdown now!
```

```
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:135)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
```

6 node cluster formed ok 
node 1,2  version 3.8
node 3,4  version 3.8.1
node 5,6  version 3.8.2

node 7,8  version 3.9-SNAPSHOT  failed to join

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_02-03_57_59/stable/aggregator/predicate/output/HZ/HzMember1HZ/out.txt
```
Members [6] {
	Member [10.0.0.34]:5701 - 993c9294-e73c-4403-91e5-686839a0dfc5 this
	Member [10.0.0.196]:5701 - f68186f0-6418-459c-a2fe-3bdf31dfc80f
	Member [10.0.0.4]:5701 - 47867c5b-305c-4f1d-9e31-8cbb9e26dc26
	Member [10.0.0.101]:5701 - dbba8494-1c38-4ebd-a4fc-2f4f52a3b9d6
	Member [10.0.0.85]:5701 - cb98e61f-ed4e-4213-877d-bcff70a3f1fc
	Member [10.0.0.61]:5701 - 59f0d4ca-2610-4700-9ae7-2799595a7d71
}
```

No diff in hazelcast.xml
```
diff predicate/output/HZ/HzMember1HZ/hazelcast.xml predicate/output/HZ/HzMember8HZ/hazelcast.xml
```

xml

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_02-03_57_59/stable/aggregator/predicate/output/HZ/HzMember1HZ/hazelcast.xml

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_02-03_57_59/stable/aggregator/predicate/output/HZ/HzMember6HZ/hazelcast.xml

http://54.163.63.218/~jenkins/workspace/multi-version-stable-All/3.9-SNAPSHOT/2017_06_02-03_57_59/stable/aggregator/predicate/output/HZ/HzMember8HZ/hazelcast.xml

**Comment by mdogan** [comment]
@Danny-Hazelcast: Currently a 3.9 member cannot join 3.8 and 3.8.1 members. 3.9 can join only 3.8.2. This limitation is introduced via a security fix.

See https://github.com/hazelcast/hazelcast-enterprise/issues/1492

**Comment by Danny-Hazelcast** [comment]
waiting for a fix related to 

Keep broadcasting group password to support RU - this is a revert of a compatibility breaking  postpone into Hazelcast 4

**Comment by Danny-Hazelcast** [comment]
fix merged 
https://github.com/hazelcast/hazelcast/pull/10726
