### ISSUE TITLE
Add default fallback configuration for Cache

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#10695]
Other data structures' `Config.findXYZConfig()` methods include fallback to a "default" config, however this is not the case for `Cache`s. Using wildcards is a workaround but is not consistent with how other data structures work.

By including the fallback, the behavior of Hazelcast's `CacheManager.getCache` methods will change to return a preconfigured `Cache` instead of `null` (as is the case in Hazelcast 3.x): this seems compliant to the specification of `getCache` methods as both state in their javadoc: 
```
   * Implementations that support declarative mechanisms for pre-configuring
   * {@link Cache}s may return a pre-configured {@link Cache} instead of
   * <code>null</code>.
```

**Comment by mmedenjak** [comment]
+1 to do in 4.0 with other config cleanup - https://github.com/hazelcast/hazelcast/issues/12617

**Comment by vbekiaris** [comment]
It seems the JSR 107 spec does not allow for this behaviour. The JSR107 TCK includes tests that enforce that under default (= no) configuration, implementations return `null` from `getCache`. It is only allowed to create & return a `Cache` from `getCache` when an implementation is configured with explicit non-default configuration.

Related discussion: https://github.com/jsr107/jsr107tck/issues/148
