### ISSUE TITLE
Mulesoft Integration Documentation

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#10703]
We've recently encountered classpath issues with Hazelcast Clients and Mulesoft.  Mulesoft has its own embedded Hazelcast Client, which is often an older version.

Since 3.8.1 we've had a fix that allows Mule 3.8 and Hazelcast 3.8.1+ to co-exist together.

However to enable this the user has to add some extra information to the mule deployments configuration.  But, this is not obvious to users.

Can we create a Documentation Section similar to our "Integrating with JEE/JBoss" sections that describes how you can integrate Mule and Hazelcast.

**Comment by Serdaro** [comment]
@dbrimley , @gurbuzali , Do we have any content somewhere explaining this? With whom I can work with?

**Comment by dbrimley** [comment]
@Serdaro I have some basic information, that I've listed below but could you ask @jerrinot for further information such as versions and more detailed explanation, he worked on the fix.


To ensure that the embedded Mulesoft version of Hazelcast is not referenced for user code, the following edits need to be made to the file 
```mule-deploy.properties``` 
with this this entry: 
```loader.override=com.hazelcast```

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/ef456bfd09ba0d62fa63d6fa5c23f5899f8cff2e
