### ISSUE TITLE
Hazelcase LocalMapStat not retrieving the Map status

### ISSUE THREAD

**Issue by svrmurthy** [hazelcast/hazelcast#10731]
Req: Need to get the memory occupied by the IMAP.

Issue: I am connecting the HazelcastInstance using ClientConfig and retrieved the IMAP (sample). I have created the LocalmapStats object in order to get the map statistics. I am getting the values as zero rather than the actual memory size.

Sample Code:

`ClientConfig clientConfig = new ClientConfig();`
`clientConfig.addAddress("localhost");`
`clientConfig.getGroupConfig().setName("dev").setPassword(""dev-pass);`
`HazelcastInstance hz = HazelcastClient.newHazelcastClient(clientConfig);`

`IMap<String,String> map1 = hz.getMap("sample");`
`map1.put("key1","Value1");`
`map1.put("key2","Value2");`

`LocalMapStats mapstats = map1.getLocalMapStats();`
`int records = mapstats.getOwnedEntryCount();`
`long memoryOccupied = mapstats.getOwnedEntryMemoryCost();`

From the above example i am able to get the memory occupied and mapsize value as 0 rather given the actual map size and actual memory occupied by the map. When I was using Config to create the hazelcast instance I am able to get the map size and mapspace.But when I use ClientConfig then the scenario is not working. Can anyone help me on working with ClientConfig to get the map status by using LocalMapStats. Thanks in advance.

**Comment by Donnerbart** [comment]
The `LocalMapStats` are no global statistics for the cluster. They just represent the statistics for the current node. Regarding `ownedEntryCount` and `OwnedEntryMemoryCost` it's very simple for clients: they don't have local data, the data is just distributed among member nodes. So those statistics are always empty.

The only reason the `getLocalMapStats()` doesn't throw an `UnsupportedOperationException` is, that this method provides access to the `NearCacheStats`, which are also available on the clients.

If you need global cluster statistics, please have a look at the Management Center.

**Comment by svrmurthy** [comment]
So is there any way to get the IMap details using java through hazelcast.
