### ISSUE TITLE
Hazelcast near cache entries still remain on the heap even after eviction

### ISSUE THREAD

**Issue by prabhu-nishant** [hazelcast/hazelcast#10741]
Hi Team,

I am having a hazelcast cluster with near caches configured on it. I have created a hook to print the near cache size.

There are basically two maps A & B. A is an independent object and B contains A as one of the attributes. I have near caches for both of them. Now when the client receives bulk request the near cache stays within limits. However I can see that the near cache object (A) still exist on the heap and the number of instance grows causing OOM.

Is this related to eviction of near caches not happening properly.

**Comment by prabhu-nishant** [comment]
This is for version 3.7

**Comment by ahmetmircik** [comment]
Hi, can you please re-try with latest patch release 3.7.8? There was some related issues fixed.

**Comment by ahmetmircik** [comment]
closing this, please re-open this issue if you still encounter the problem after testing with 3.7.8.
