### ISSUE TITLE
[security] [config] SSL/TLS configuration not complete

### ISSUE THREAD

**Issue by martinfurmanski** [hazelcast/hazelcast#10750]
It does not seem to be possible to configure a list of cipher suites nor a list of SSL/TLS protocols.

Client auth is implemented, but you have to pass in a populated Properties object. The NONE option also seems to be missing from documentation at least. Perhaps it is implicitly so when not set.

To have complete SSL/TLS support it would be good to include all of these features and make them clearly available programatically, by extending SSLConfig or perhaps SSLContextFactory.

I have looked at 3.7.8 and 3.8.2.

**Comment by pveentjer** [comment]
Configuring the ciphersuite is possible with the new OpenSSL integration. So you can use that + benefit from the performance improvements.
