### ISSUE TITLE
Http health check JSON output

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#10753]
With `-Dhazelcast.http.healthcheck.enabled=true`, a current output format is just too custom.

```
Hazelcast::NodeState=ACTIVE
Hazelcast::ClusterState=ACTIVE
Hazelcast::ClusterSafe=TRUE
Hazelcast::MigrationQueueSize=0
Hazelcast::ClusterSize=1
```

How about JSON format like this

```
{
  "nodeState": "ACTIVE",
  "clusterState": "ACTIVE",
  "isClusterSafe": "TRUE",
  "migrationQueueSize": 0,
  "clusterSize": 1
}
```

or 

```
{
  "hazelcast": {
    "nodeState": "ACTIVE",
    "clusterState": "ACTIVE",
    "isClusterSafe": true,
    "migrationQueueSize": 0,
    "clusterSize": 1
  }
}
```

in this case, this format can be parsed standard tools like `jq` or any json viewer.

```
❯ curl http://localhost:5701/hazelcast/health | jq '.'
{
  "hazelcast": {
    "nodeState": "ACTIVE",
    "clusterState": "ACTIVE",
    "isClusterSafe": true,
    "migrationQueueSize": 0,
    "clusterSize": 1
  }
}
```

Thoughts?
I can implement the patch if we agree on this format.

**Comment by emre-aydin** [comment]
@gAmUssA I think the second format with an actual JSON boolean is better. I agree with you that a JSON output would be better.

```
{
  "hazelcast": {
    "nodeState": "ACTIVE",
    "clusterState": "ACTIVE",
    "isClusterSafe": true,
    "migrationQueueSize": 0,
    "clusterSize": 1
  }
}
```

**Comment by emrahkocaman** [comment]
Nice one, I'd go for second format too.

**Comment by lazerion** [comment]
I believe that `JSON` producing endpoint should be done, and it should be backward compatible. Since we have already scripts that depends on `custom` format.

**Comment by gAmUssA** [comment]
@lazerion like `http://localhost:5701/hazelcast/health/json` or 
`curl -X GET -H "Content-type: application/json" http://localhost:5701/hazelcast/health` ?

**Comment by dbrimley** [comment]
Output can be based on request HTTP header, default will have to remain as we have right now to preserve backwards compatability for people who are scraping the output.

**Comment by mmedenjak** [comment]
For 4.0 I think we ought to align all output to JSON and simply remove the old output. The problems with the old output was that it was very custom and that different URI's had different output format while lots of the newer URI's (e.g. CP subsystem status) used exclusively JSON.

Sure, we can make JSON the default and return the old format if the content-type is "custom" but is there a strong reason why to do so? There are enough tools out there to parse and handle JSON output.

WDYT @dbrimley @lazerion @emre-aydin ?

**Comment by emre-aydin** [comment]
+1 for only JSON
