### ISSUE TITLE
Ability to add timeout to get operations for Spring HazelcastCache

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast#10756]
HazelcastCache on hazelcast-spring project uses map.get() for fetching results. In some cases, users need to define a timeout to guarantee reliable response times.

Hazelcase map as map.getAsync() method that can be used directly but with Spring abstraction, `@Cachable` annotation, it's not possible. And asking users to use Hazelcast map.getAsync directly will make their code base dependent to Hazelcast.

This can be achieved a couple of ways:

1.  Spring team can add a get(key, timeout) method to `org.springframework.cache.Cache` and we can implement
   This doesn't seem possible. See: https://jira.spring.io/browse/SPR-15655

2. We can ask spring team to add a property to their CacheProperties for hazelcast ,which they already have parameters for caching solutions like Infinispan, Couchbase etc. 
 https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/cache/CacheProperties.java

This doesn't' seem right because then we'll need to depend on Spring Boot.

3. We can define a property just for the spring, document it and ask users to define it if they need.

The only think I'm still not sure is, if we should define 1 timeout for all caches, or cache based, so users can choose to define a timeout for some caches and not for some others.

**Comment by tombujok** [comment]
@gokhanoner I see that the PRs are merged. Can we close this issue?

**Comment by gokhanoner** [comment]
@tombujok  yes we can.
