### ISSUE TITLE
[OSGi] Hazelcast declares commons-logging as a required dependency but it is not required

### ISSUE THREAD

**Issue by netudima** [hazelcast/hazelcast#10770]
> Caused by: org.osgi.framework.BundleException: Unresolved constraint in bundle com.hazelcast [315]: Unable to resolve 315.0: missing requirement [315.0] osgi.wiring.package; (&(osgi.wiring.package=org.apache.commons.logging)(version>=1.2.0)(!(version>=2.0.0)))
 at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4097)[org.apache.felix.framework-4.6.1.jar:]
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2114)[org.apache.felix.framework-4.6.1.jar:]
 at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977)[org.apache.felix.framework-4.6.1.jar:]

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/pom.xml#L125 - need to add:
org.apache.commons.logging;resolution:=optional,

**Comment by jerrinot** [comment]
@netudima:

good catch, thanks a lot for your report.

**Comment by mdogan** [comment]
@netudima: 
As far as I see only `hazelcast-spring` module declares `commons-logging` as a dependency. From output of `mvn dependency:tree`:

```
[INFO] +- org.springframework:spring-context:jar:4.3.0.RELEASE:provided
[INFO] |  +- org.springframework:spring-aop:jar:4.3.0.RELEASE:provided
[INFO] |  +- org.springframework:spring-beans:jar:4.3.0.RELEASE:provided
[INFO] |  +- org.springframework:spring-core:jar:4.3.0.RELEASE:provided
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:provided
[INFO] |  \- org.springframework:spring-expression:jar:4.3.0.RELEASE:provided
```

**Comment by netudima** [comment]
Yes, you are right. I rechecked manifests for JARs and the following ones only have the OSGi import (`org.apache.commons.logging`):
- `hazelcast-spring`
- `hazelcast-all`

**Comment by netudima** [comment]
Updated pull request to change manifests only for the mentioned JARs.

**Comment by mdogan** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/10771
