### ISSUE TITLE
Ringbuffer - head and tail out of sync

### ISSUE THREAD

**Issue by hos-p** [hazelcast/hazelcast#10774]
Hi, I am running hazelcast (3.8.2) on 3 servers and using ringbuffer for storing data. Ringbuffer has capacity 500 and no backup. 

I am using addAllAsync(dataCollection, OverflowPolicy.OVERWRITE) for storing data in just 1 thread in whole cluster. This thread calls this method one times per second and stores collection with up to 500 entries.

Reading is performed by more threads in parallel using readManyAsync() method.

And sometimes after node outage get headSequence and tailSequence out of sync as you can see on attached image.

And it seems that version 3.7.8 does not have this problem. 

![ringbuffer](https://user-images.githubusercontent.com/6361016/27231876-629b2588-52b4-11e7-96e1-2bb87a3db474.PNG)

**Comment by hos-p** [comment]
I have tried to write some example simulating this issue.
[rbissue.zip](https://github.com/hazelcast/hazelcast/files/1084409/rbissue.zip)

You can find 3 main classes in attached maven project.
1. Writer
2. Reader1
3. Reader2

Execute all of them. Wait some time and stop/start Reader2 several times. All three classes have implemented check of ringbuffer size which throws RuntimeException if this issue happens.

**Comment by mdogan** [comment]
Thanks for the reproducer.
