### ISSUE TITLE
TimeoutException while merging causes partial un-lock

### ISSUE THREAD

**Issue by stanislavprokopov** [hazelcast/hazelcast#10781]
Hi.

I am using Linux 3.10, Java 1.8.0_25, Hazelcast 3.8, and have a 4 member cluster connected over tcp-ip.
There are several queues, maps and lists, and each member writes and reads from them. Map has backup-count = 1, lists and queues - async-backup-count = 1.

Yesterday we encountered a strange bug, one member has dropped out of the cluster and when re-joining other members a TimeoutException: null has been thrown while merging. After this members were unable to processing some queues and maps, but kept processing others, as-if some of them were still locked because of merge. Can this partial un-lock happen? Unfortunately i am not able to reproduce it currently.

```
00:10:43.770 INFO  [hz._hzInstance_1_gw.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptorThread - [M3]:11703 [gw] [3.8] Accepting socket connection from /M4:47012
00:10:43.770 INFO  [hz._hzInstance_1_gw.cached.thread-6] com.hazelcast.nio.tcp.TcpIpConnectionManager - [M3]:11703 [gw] [3.8] Established socket connection between /M3:11703 and /M4:47012
00:10:43.772 INFO  [hz._hzInstance_1_gw.priority-generic-operation.thread-0] com.hazelcast.client.impl.protocol.task.AuthenticationMessageTask - [M3]:11703 [gw] [3.8] Received auth from Connection[id=3148, /M3:11703->/M4:47012, endpoint=null, alive=true, type=JAVA_CLIENT], successfully authenticated, principal : ClientPrincipal{uuid='1ddbfe32-7838-469b-bfe2-896ecb436950', ownerUuid='019c5d14-d9ef-4ee7-a83d-206d45891812'}, owner connection : false, client version : 3.8
00:10:46.812 WARN  [hz._hzInstance_1_gw.cached.thread-6] com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager - [M3]:11703 [gw] [3.8] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 5000 ms, Heartbeat-Timeout: 5000 ms
...
00:11:44.868 ERROR [hz._hzInstance_1_gw.cached.thread-4] com.hazelcast.internal.cluster.impl.ClusterMergeTask - [M3]:11703 [gw] [3.8] While merging...
java.util.concurrent.TimeoutException: null
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:225) ~[hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.waitOnFutureInterruptible(ClusterMergeTask.java:154) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.executeMergeTasks(ClusterMergeTask.java:137) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.cluster.impl.ClusterMergeTask.run(ClusterMergeTask.java:74) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.instance.LifecycleServiceImpl.runUnderLifecycleLock(LifecycleServiceImpl.java:107) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.cluster.impl.ClusterServiceImpl.merge(ClusterServiceImpl.java:319) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.internal.cluster.impl.operations.MergeClustersOperation$1.run(MergeClustersOperation.java:60) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228) [hazelcast-3.8.jar!/:3.8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-3.8.jar!/:3.8]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-3.8.jar!/:3.8]
00:11:44.868 INFO  [hz._hzInstance_1_gw.cached.thread-4] com.hazelcast.core.LifecycleService - [M3]:11703 [gw] [3.8] [M3]:11703 is MERGED

```

**Comment by mdogan** [comment]
@stanislavprokopov:
What do you mean by _locked_? Are they inaccessible after/during merge? We don't lock data structures.

Timeout during merge process doesn't indicate that merge completely/partially failed. Merge tasks are already submitted, they are offloaded to be able to run concurrently. But still all or some of them can fail, because nodes can become (re)split while merging.

As far as I understand from the log below, you set `hazelcast.max.no.heartbeat.seconds` to 5 seconds.
> 00:10:46.812 WARN  [hz._hzInstance_1_gw.cached.thread-6] com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager - [M3]:11703 [gw] [3.8] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 5000 ms, Heartbeat-Timeout: 5000 ms

Have you also changed `hazelcast.heartbeat.interval.seconds`? Because it's 5 sec by default and when both `hazelcast.heartbeat.interval.seconds` and `hazelcast.max.no.heartbeat.seconds` is 5 sec then you'll get very frequent cluster splits. 

Are there any explicit system properties you set?

**Comment by stanislavprokopov** [comment]
@mdogan 
I can only assume what happened, the application stopped processing the queue`s, the application has several threads, that process queues and maps. In the logs i can see that some queues and maps were still processing, others did not log anything and did not die, so my best guess is that they were locked. I have added some additional information to the log, next time this issue occurs i might have a better understanding.

While investigating this issue i have discovered that the application uses a few locks without lease time, if the merge partially failed, could these locks be in a dead-lock state? Is there a way to know if the merge succeeded or failed, is hz logging this kind of info?

`hazelcast.max.no.heartbeat.seconds` was set to 5 seconds, but `hazelcast.heartbeat.interval.seconds` was left at default value, i have already instructed the client to fix this and increase `hazelcast.max.no.heartbeat.seconds` to at least 15 seconds.

**Comment by stanislavprokopov** [comment]
I am closing this issue, as it appears to have been related to locks used in the application, after adding lease time, we have seen same TimeoutException`s but the application was able to continue working without any issues.
