### ISSUE TITLE
[docker] "pickMatchingAddress" picks wrong bind address when running as docker swarm service

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#10801]
Deploying a hazelcast app as a docker container as a swarm service on a specific docker overlay network

In my hazelcast config I have :
```
        <interfaces enabled="true">
            <interface>10.0.3.*</interface>        
        </interfaces> 
```

The swarm service address vip is 10.0.3.5

The deployed container's `ifconfig` shows the following:

```
/ # ifconfig -a
eth0      Link encap:Ethernet  HWaddr 02:42:0A:00:03:06
          inet addr:10.0.3.6  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:aff:fe00:306%32690/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:9 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:718 (718.0 B)  TX bytes:718 (718.0 B)

eth1      Link encap:Ethernet  HWaddr 02:42:AC:15:00:05
          inet addr:172.21.0.5  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe15:5%32690/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35 errors:0 dropped:0 overruns:0 frame:0
          TX packets:46 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:6718 (6.5 KiB)  TX bytes:4378 (4.2 KiB)

gre0      Link encap:UNSPEC  HWaddr 00-00-00-00-35-00-7B-8F-00-00-00-00-00-00-00-00
          NOARP  MTU:1476  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

gretap0   Link encap:Ethernet  HWaddr 00:00:00:00:00:00
          BROADCAST MULTICAST  MTU:1462  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6_vti0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6gre0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          NOARP  MTU:1448  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

ip_vti0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-7B-8F-00-00-00-00-00-00-00-00
          NOARP  MTU:1332  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%32690/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:59 errors:0 dropped:0 overruns:0 frame:0
          TX packets:59 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:3642 (3.5 KiB)  TX bytes:3642 (3.5 KiB)

sit0      Link encap:IPv6-in-IPv4
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

tunl0     Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-7B-8F-00-00-00-00-00-00-00-00
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

The problem is that when hazelcast is booting up it selects the wrong address to bind to... `10.0.3.5` (it should be selecting `10.0.3.6`....)

https://github.com/hazelcast/hazelcast/blob/210475c806328c6655ea551f6fc59ef8220b601d/hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java#L334

The above method relies on `NetworkInterface.getNetworkInterfaces();` to enumerate through all interfaces as detected by Java.

For whatever reason this is returning a set of interfaces as follows....

I have no idea why 10.0.3.5 is in that list on eth0... when ifconfig from within the container shows otherwise. The net result is that hazelcast binds to the wrong address

```
2017-06-21T19:41:42.896874504Z /fe80:0:0:0:42:acff:fe15:5%eth1
2017-06-21T19:41:42.896883193Z /172.21.0.5
2017-06-21T19:41:42.896890685Z /fe80:0:0:0:42:aff:fe00:306%eth0
2017-06-21T19:41:42.896896677Z /10.0.3.5
2017-06-21T19:41:42.896903869Z /10.0.3.6
2017-06-21T19:41:42.896911360Z /0:0:0:0:0:0:0:1%lo
2017-06-21T19:41:42.896917752Z /127.0.0.1
```

```
2017-06-21T19:41:41.995842305Z INFO: [LOCAL] [xx] [3.7.8] Interfaces is enabled, trying to pick one address matching to one of: [10.0.3.*]
2017-06-21T19:41:41.996807855Z Jun 21, 2017 7:41:41 PM com.hazelcast.instance.DefaultAddressPicker
2017-06-21T19:41:41.996825534Z INFO: [LOCAL] [xx] [3.7.8] Prefer IPv4 stack is true.
2017-06-21T19:41:42.015019470Z Jun 21, 2017 7:41:42 PM com.hazelcast.instance.DefaultAddressPicker
2017-06-21T19:41:42.015051132Z INFO: [LOCAL] [xx] [3.7.8] Picked [10.0.3.5]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
2017-06-21T19:41:42.035666984Z Jun 21, 2017 7:41:42 PM com.hazelcast.system
```

Not sure where to point the finger as `NetworkInterface.getNetworkInterfaces();` is java stuff not hazelcast, but if this cannot be fixed it makes hazelcast deployed on docker swarm very very difficult.

Workarounds? Perhaps you guys can add some additional qualifiers for selecting the correct interface? Including exclusion matching rules?

**Comment by bitsofinfo** [comment]
Also output of `ip address list` shows it

```
/ # ip address list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
4: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: ip_vti0@NONE: <NOARP> mtu 1332 qdisc noop state DOWN qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
6: ip6_vti0@NONE: <NOARP> mtu 1500 qdisc noop state DOWN qlen 1
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
7: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
8: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN qlen 1
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
9: ip6gre0@NONE: <NOARP> mtu 1448 qdisc noop state DOWN qlen 1
    link/[823] 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
424: eth0@if425: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:42:0a:00:03:06 brd ff:ff:ff:ff:ff:ff
    inet 10.0.3.6/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.3.5/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:306/64 scope link
       valid_lft forever preferred_lft forever
426: eth1@if427: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:15:00:05 brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.5/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe15:5/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by bitsofinfo** [comment]
https://github.com/moby/moby/issues/33770

**Comment by bitsofinfo** [comment]
Seem like there is really no effective way to configure hazelcast to pick the right address in this scenario without interrogating the swarm service/task api to cross reference the real VIP against what the container itself reports back on eth0 via `NetworkInterface.getNetworkInterfaces()`. There is no effective use of the `interfaces` config that I can take advantage of as the swarm can randomly assign any valid address as a vip to either the container or shared service vip itself. 

I can't do this kind of logic unless I could provide my own AddressPicker

**Comment by gAmUssA** [comment]
did you set property `hazelcast.socket.bind.any` to false in order to make `interfaces>interface` honored? @bitsofinfo

**Comment by bitsofinfo** [comment]
It currently is not binding to "any" (prior to the interfaces declaration it was just grabbing the `172.x` bridge ip) but specifically something on `10.0.3.*` which it is, its just that its picking the wrong one due to the way the service vip and container vips are bound to eth0 (there are 2 and its just grabbing the first match). The behavior of the AddressPicker needs to be more flexible, custom impl I think to deal w/ this kind of scenario.

**Comment by mdogan** [comment]
You can inject custom `AddressPicker` using internal api as a workaround. _Note that; this internal api is subject to change anytime._

```java
NodeContext nodeContext = new DefaultNodeContext() {
    @Override
    public AddressPicker createAddressPicker(Node node) {
        return myAddressPicker;
    }
};
HazelcastInstance instance =
        HazelcastInstanceFactory.newHazelcastInstance(config, "my-instance-name", nodeContext);
```

**Comment by bitsofinfo** [comment]
@mdogan yeah. I'm trying to create a discovery SPI for docker swarm for the community. I could create such a class and embed it in the SPI, but having to tell people who want to use the SPI that they would also have to instantiate this custom AddressPicker, DefaultNodeContext and start Hazelcast as described above, but this really should be drop in functionality. Its just awkward all these related issues around interface selection, binding, nat issues when in a containerized env.

**Comment by bitsofinfo** [comment]
@gAmUssA I also re-verified this am that no combination of what you suggested w/ the interface selection (wildcard or not) works for this scenario.

**Comment by bitsofinfo** [comment]
So working on this: https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi

The custom AddressPicker solves the issue by cross referencing what the JVM thinks the interface is, against what the swarm API says it is for all containers in the service. This works around the VIP issue in hazelcast but is a bit awkward from a SPI usage standpoint, for the above reason (custom HazelcastInstance instantiation the user has to do)

**Comment by bitsofinfo** [comment]
This also returns the correct vip, but my gut tells me I would not rely on this 100% of the time vs a cross reference method via the API I mentioned above

```
System.out.println(java.net.InetAddress.getByName(java.net.InetAddress.getLocalHost().getHostName()).getHostAddress());
```

**Comment by bitsofinfo** [comment]
When are all these docker networking, interface, binding issue related things going to finally be looked at or scheduled to be addressed?

**Comment by jerrinot** [comment]
hi @bitsofinfo,

would an SPI like this help? 
```java
public interface AddressLocator {
    /**
      Address to be used for binding
    **/
    InetSocketAddress getBindAddress();
    /**
     Address to be advertised to other cluster members
    **/
    InetSocketAddress getPublicAddress();
}
```

**Comment by tunix** [comment]
@bitsofinfo Have you seen this reply? I think it can work.

**Comment by tunix** [comment]
@jerrinot btw there is also a class called `DiscoveryNode` which seems to have a similar purpose?

**Comment by bitsofinfo** [comment]
@tunix it should, seems similar to `AddressPicker` minus getServerSocketChannel()

**Comment by bitsofinfo** [comment]
see: https://github.com/hazelcast/hazelcast/blob/3cede71cad1fe87312f0901ff77f903ed2d4383d/hazelcast/src/main/java/com/hazelcast/spi/MemberAddressProvider.java

**Comment by mmedenjak** [comment]
Closing this one as well. Please see: https://github.com/hazelcast/hazelcast/issues/9963#issuecomment-336072459

**Comment by bitsofinfo** [comment]
Starting work on https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi 1.0-RC4 which will integrate this new `MemberAddressProvider` in a version of the SPI for hazelcast 3.9.x+
