### ISSUE TITLE
[SPI] [Cloud] Create/extend discovery SPI to permit custom AddressPicker implementations

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#10802]
Hazelcast definitely has a need to allow (perhaps the Discovery SPI) to optionally provide a custom implementation of `AddressPicker` to use instead of the default which does not always make the right choice when deployed in a container framework.

I am proposing that a new SPI, or extension to the existing Discovery SPI be added that allows people to drop in a custom `AddressPicker` implementation

https://github.com/hazelcast/hazelcast/issues/10801

**Comment by bitsofinfo** [comment]
Note this is needed for: https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi  the current way its done is a hack and awkward for the user of an SPI.

**Comment by bitsofinfo** [comment]
When will this be looked at?

**Comment by mmedenjak** [comment]
This has been added in 3.9 (see https://github.com/hazelcast/hazelcast/issues/9963#issuecomment-336072459). Next, we will need to add convenience implementations bundled with discovery plugins for easier setup on docker, AWS, instances behind NAT, etc.
