### ISSUE TITLE
[security] [config] [dynamic-config] Clarify DynamicSecurityConfig & SecurityService lifecycle

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#10834]
Currently a new instance is created each time `DynamicConfigurationAwareConfig.getSecurityConfig` is invoked

**Comment by mmedenjak** [comment]
@vbekiaris do you mean this lifecycle is just unclear or there is a possible bug (e.g. leak)?

**Comment by vbekiaris** [comment]
It's a leftover from https://github.com/hazelcast/hazelcast/pull/10832 , there might be a bug in `DynamicSecurityConfig` wrapping so created this issue to investigate further.
