### ISSUE TITLE
[security] Eliminate synchronization when checking task permissions

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#10833]
#10832 & https://github.com/hazelcast/hazelcast-enterprise/pull/1559 introduce synchronization when checking permissions for each message task with security enabled.

**Comment by gurbuzali** [comment]
I believe this is not a critical issue, because the introduced synchronization is not in the happy-path.
We touch the synchronization block once only for each principal, not for each message task.
