### ISSUE TITLE
[map] Separate responsibility of setting an individual entry explicit TTL from a put operation to promote a more intuitive IMap interface

### ISSUE THREAD

**Issue by wneild** [hazelcast/hazelcast#10845]
In reference to #10580, the current IMap interface for the operation of putting a value into a map is not clear where the resulting value of the entry's TTL is concerned.

The confusion stems from methods `V put(K key, V value)` and `V put(K key, V value, long ttl, TimeUnit timeunit)` where `V put(K key, V value)` has no effect on the TTL, meaning a previously explicitly set TTL, on a key, will still expire the value set by this operation.

My suggestion would be to separate the operation of setting an explicit TTL on a key to its own method `void setTtl(K key, long ttl, TimeUnit timeunit)` and remove put interfaces conflating the two operations.

**Comment by mmedenjak** [comment]
@wneild it's possible we add this some time in the future. For now I believe we should clarify the behaviour in the javadoc.

**Comment by dmitrymz** [comment]
+1 for this change. the main advantage of suggested approach is in scenario when we need to update ttl of existing entry. currently we have to get the entry, and put it back with ttl.

**Comment by mmedenjak** [comment]
Relevant method : `com.hazelcast.map.impl.ExpirationTimeSetter#updateExpiryTime` : 
```
public static void updateExpiryTime(Record record, long ttl, MapConfig mapConfig) {

        // Preserve previously set TTL, if TTL < 0.
        if (ttl < 0) {
            ttl = record.getTtl();
        }
        // If TTL == 0, convert it to Long.MAX_VALUE.
        ttl = checkedTime(ttl);

        record.setTtl(ttl);

        long maxIdleMillis = calculateMaxIdleMillis(mapConfig);
        setExpirationTime(record, maxIdleMillis);
    }
```

**Comment by mustafaiman** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/13324

**Comment by wneild** [comment]
@mustafaiman Unsure how that PR addresses this ticket? It seems to address a feature of the cache interface rather than problem I've highlighted around the IMap interface.
