### ISSUE TITLE
[map] [index] [hd] Dynamic HD Indexes creation in PostJoinMapOperation broken

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#10841]
`PostJoinMapOperation` is running on a generic thread -> It cannot create HD indexes. 
It should probably spawn partition specific operations.

**Comment by mmedenjak** [comment]
@jerrinot can this be closed because of the merged PR or is there something more to this issue?

**Comment by jerrinot** [comment]
@mmedenjak it cannot be closed. the PRs linked above only disable the index creation to prevent a JVM crash. @tombujok is working on a proper fix.
