### ISSUE TITLE
ILock.tryLock(..) leads to thread collision

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#10862]
**LockProxySupport.tryLock** uses _ThreadUtil.getThreadId()_ in new LockOperation. This leads to thread collision as threads might get assigned same IDs in different app JVMs and if 2 threads with same IDs happen to invoke _tryLock()_ at the same time, it returns true for both the threads.

**Comment by Donnerbart** [comment]
We also check the caller ID when acquiring a lock. So a thread ID collision should not be enough to obtain a lock. Can you provide more details, e.g. a stable reproducer?

**Comment by jerrinot** [comment]
we also use callerUUID. the pair `(threadId, callerUUID)` is used associate a thread with a lock.

**Comment by wildnez** [comment]
Closing as not a valid issue.
