### ISSUE TITLE
How to change MapConfig when using HazelcastClient

### ISSUE THREAD

**Issue by rajavikram** [hazelcast/hazelcast#10872]
Hi,
We are using Hazelcast v3.9.
As part of our project, we have a need to change/set the the TTL of a specific IMap during run time.  
We have a cluster size of 5 machines and 4 clients. The jdk version is 1.8(131).
So now when i access the getConfig() from the client i get the following:
    
    java.lang.UnsupportedOperationException: Client cannot access cluster config!
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getConfig(HazelcastClientInstanceImpl.java:424) ~[hazelcast-client-3.8.jar:3.8]
	at com.hazelcast.client.impl.HazelcastClientProxy.getConfig(HazelcastClientProxy.java:78) ~[hazelcast-client-3.8.jar:3.8]

And the ClientConfig which i obtained using : 

    if (hazelcastInstance instanceof HazelcastClientInstanceImpl){
            HazelcastClientInstanceImpl hazelcastClientInstance = (HazelcastClientInstanceImpl) hazelcastInstance;
            hazelcastClientInstance.getClientConfig()
      }
Does not have the `getMapConfig(mapName)` method while it has other config methods like `getNearCacheConfig()`.
So now, how do i go about setting the TTL and other settings in the MapConfig as a client?

**Comment by jerrinot** [comment]
hi @rajavikram,

you can't change a map configuration once a cluster is up and running. You can either [per-entry TTL](https://github.com/jerrinot/hazelcast/blob/16bd03c7794322b5989d1bd5641c80352c1117cb/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L668-L668) tho. 

In Hazelcast 3.9 it's possible to create new map configuration in a running cluster, but it's still not possible to change an existing map configuration.

**Comment by ahmetmircik** [comment]
@rajavikram if it fits your case, an alternative approach can be using management centre. Some properties of an existing `MapConfig`can be updated from there including `TTL`.

**Comment by rajavikram** [comment]
@jerrinot, what do you mean by "once the cluster is up and running" ?
I'm joining as a client so of course, the cluster is up and running. 
Do you mean to say that you do not support changing the MapConfig as a client?
If so can you put that somewhere in your documentation so that others don't waste their time on this.

**Comment by rajavikram** [comment]
@ahmetmircik, thanks for the tip.
We might just have to go with this approach - have a node in the cluster for this purpose.

**Comment by davidkarlsen** [comment]
+1 This should be documented

**Comment by mmedenjak** [comment]
@davidkarlsen https://docs.hazelcast.org/docs/latest/manual/html-single/#dynamically-adding-data-structure-configuration-on-a-cluster

**Comment by davidkarlsen** [comment]
https://github.com/hazelcast/hazelcast/issues/14750

**Comment by geraldo-netto** [comment]
Dear Friends,

May I ask your help?
Is it possible to set mapConfig values like TTL and backup-count when a Hazelcast client is started from a ClientConfig?

This is my sample code
```java
String hazelcastConfigPath = RestServerConfig.getHazelcastClientConfigurationPath(servletContext);

ClientConfig hazelcastClientConfig = new ClientConfig();
if (hazelcastConfigPath != null) {
    hazelcastClientConfig = new XmlClientConfigBuilder(hazelcastConfigPath).build();
}

hazelcastClientConfig.setProperty("hazelcast.logging.type", "slf4j");
HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient(hazelcastClientConfig);
MapConfig mapConfig = ???;
mapConfig.setBackupCount(2);
mapConfig.setTimeToLiveSeconds(time);
```

Thank You Very Much,
Geraldo Netto
