### ISSUE TITLE
MapProxyImpl.executeOnKeys broken when ConcurrentSkipListSet is passed

### ISSUE THREAD

**Issue by gulzarsingh12** [hazelcast/hazelcast#10877]
It throws NullPointerException when underlying Set implementation is ConcurrentSkipListSet.

> **public Map<K, Object> executeOnKeys(Set<K> keys, EntryProcessor entryProcessor)** {
>         if(keys != null && !keys.contains((Object)null)) {

contains() implementation is different in ConcurrentSkipListSet from HashSet.

> private V doGet(Object key) {
>         if (key == null)
>             throw new NullPointerException();

so the check in MapProxyImpl  **!keys.contains((Object)null)** would always throw a NPE.

**Comment by ahmetmircik** [comment]
Thanks for reporting this.

**Comment by ahmetmircik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/10884
