### ISSUE TITLE
[map] containsKey return true even the key is not exist in the map

### ISSUE THREAD

**Issue by jmchen** [hazelcast/hazelcast#10923]
Hazelcast version is 3.8.3
Cluster size is 1
Java version 1.8
Operating system MacOS 10.12.5

Reproduce steps:
1. Make sure the map doesn't have key "somekey".
2. Call m.get("somekey"), it will return null.
3. Call m.containsKey("somekey"), it returns true.

**Comment by ahmetmircik** [comment]
Can you please share your configuration?

**Comment by jmchen** [comment]
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.7.xsd">
     <group>
          <name>mint-platform-main</name>
          <password>****</password>
     </group>
     <license-key>5NKIwbrH0Tk7OfAj1aFluSyEUm6VJ7700110010209810109009110100027</license-key>
     <management-center enabled="true" update-interval="3">http://localhost:8089/mancenter</management-center>
     <properties>
          <property name="hazelcast.merge.next.run.delay.seconds">30</property>
          <property name="hazelcast.elastic.memory.enabled">true</property>
          <property name="hazelcast.heartbeat.interval.seconds">1</property>
          <property name="hazelcast.merge.first.run.delay.seconds">60</property>
          <property name="hazelcast.elastic.memory.unsafe.enabled">true</property>
          <property name="hazelcast.logging.type">slf4j</property>
          <property name="hazelcast.member.list.publish.interval.seconds">180</property>
          <property name="hazelcast.max.no.master.confirmation.seconds">120</property>
          <property name="hazelcast.max.no.heartbeat.seconds">30</property>
          <property name="hazelcast.operation.call.timeout.millis">30000</property>
          <property name="hazelcast.icmp.ttl">0</property>
          <property name="hazelcast.elastic.memory.total.size">128M</property>
          <property name="hazelcast.icmp.enabled">false</property>
          <property name="hazelcast.initial.min.cluster.size">0</property>
          <property name="hazelcast.icmp.timeout">10000</property>
          <property name="hazelcast.prefer.ipv4.stack">true</property>
          <property name="hazelcast.elastic.memory.chunk.size">16</property>
          <property name="hazelcast.master.confirmation.interval.seconds">30</property>
     </properties>
     <network>
          <port port-count="100" auto-increment="true">5701</port>
          <join>
               <multicast enabled="false" loopbackModeEnabled="false">
                    <multicast-group>224.2.2.3</multicast-group>
                    <multicast-port>54327</multicast-port>
                    <multicast-timeout-seconds>2</multicast-timeout-seconds>
                    <multicast-time-to-live>32</multicast-time-to-live>
               </multicast>
               <tcp-ip enabled="true">
                    <member-list>
                         <member>127.0.0.1</member>
                    </member-list>
               </tcp-ip>
               <aws enabled="false">
                    <access-key>null</access-key>
                    <secret-key>null</secret-key>
                    <region>us-east-1</region>
                    <security-group-name>null</security-group-name>
                    <tag-key>null</tag-key>
                    <tag-value>null</tag-value>
               </aws>
          </join>
          <interfaces enabled="false">
               <interface>127.0.0.1</interface>
          </interfaces>
          <ssl enabled="false"/>
          <socket-interceptor enabled="false"/>
     </network>
  
     <map name="applicationRegistryMap">
          <in-memory-format>BINARY</in-memory-format>
          <backup-count>2</backup-count>
          <async-backup-count>0</async-backup-count>
          <time-to-live-seconds>0</time-to-live-seconds>
          <max-idle-seconds>0</max-idle-seconds>
          <eviction-policy>NONE</eviction-policy>
          <max-size policy="PER_NODE">2147483647</max-size>
          <eviction-percentage>25</eviction-percentage>
          <min-eviction-check-millis>100</min-eviction-check-millis>
          <read-backup-data>false</read-backup-data>
          <hot-restart enabled="false">
               <fsync>false</fsync>
          </hot-restart>
          <statistics-enabled>true</statistics-enabled>
          <map-store enabled="false">
               <class-name>null</class-name>
               <write-delay-seconds>0</write-delay-seconds>
               <write-batch-size>1</write-batch-size>
          </map-store>
     </map>
     <topic name="default">
          <global-ordering-enabled>false</global-ordering-enabled>
          <multi-threading-enabled>false</multi-threading-enabled>
     </topic>
     <executor-service name="default">
          <pool-size>16</pool-size>
          <queue-capacity>2147483647</queue-capacity>
     </executor-service>
     <partition-group enabled="false" group-type="PER_MEMBER"/>
     <listeners>
          <listener>com.uxpsystems.mint.framework.commons.hazelcast.listener.ClusterMembershipListener</listener>
          <listener>com.uxpsystems.mint.framework.commons.hazelcast.listener.ServerLifecycleListener</listener>
     </listeners>
     <lite-member enabled="false"/>
     <hot-restart-persistence enabled="false">
          <base-dir>/Users/echen/2-app-svr/apache-tomcat-8.5.3/bin/hot-restart</base-dir>
          <parallelism>1</parallelism>
          <validation-timeout-seconds>120</validation-timeout-seconds>
          <data-load-timeout-seconds>900</data-load-timeout-seconds>
     </hot-restart-persistence>
</hazelcast>

**Comment by ahmetmircik** [comment]
@jmchen seems it is not reproducible with the configuration you sent but i think there should also be a near-cache configured?

**Comment by ahmetmircik** [comment]
should be closed by https://github.com/hazelcast/hazelcast/pull/10927

**Comment by mishraakashmyself** [comment]
Nope. Should now return true if key does not exist.; 

Tried following code

  Map<String, String> employees = new HashMap<>();

        // keys and values (Name, Department)
        employees.put("John", "HR");
        employees.put("Eric", "IT");
        employees.put("Joe", "LEGAL");

        if (employees.containsKey("No-Key")) {
            System.out.format("Key Exist");
        } else {
            System.out.format("Key Does not Exist");
        }
Output: Key Does not Exist

There is some Hashmap example and solutions are given [Here](https://www.quizcure.com/java/hashmap-class-definition-usage-with-examples) which you may like.
