### ISSUE TITLE
Consider logging new HTTP connections with DEBUG or lower level

### ISSUE THREAD

**Issue by dannygu** [hazelcast/hazelcast#10924]
Hi,

I've enabled the following in hazelcast.xml
`<property name="hazelcast.http.healthcheck.enabled">true</property>`

I've setup Consul to check health of the HC service every 30 seconds by http://X:5701/hazelcast/health, now I get the following 'error'/'info' in the HC log every 30 seconds

```
13-Jul-2017 21:00:28.016 INFO [hz._hzInstance_1_docker_int.IO.thread-Acceptor] com.hazelcast.nio.tcp.SocketAcceptorThread.null [10.0.2.71]:33334 [docker_int] [3.8.3] Accepting socket connection from /10.0.1.160:41488
13-Jul-2017 21:00:28.016 INFO [hz._hzInstance_1_docker_int.cached.thread-3] com.hazelcast.nio.tcp.TcpIpConnectionManager.null [10.0.2.71]:33334 [docker_int] [3.8.3] Established socket connection between /172.17.0.2:5701 and /10.0.1.160:41488
13-Jul-2017 21:00:28.017 INFO [hz._hzInstance_1_docker_int.IO.thread-in-1] com.hazelcast.nio.tcp.TcpIpConnection.null [10.0.2.71]:33334 [docker_int] [3.8.3] Connection[id=32, /172.17.0.2:5701->/10.0.1.160:41488, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side
```

Is there any way to turn this off  without turning off the entire log ? 

Thanks!

**Comment by mmedenjak** [comment]
Hi @dannygu! I don't think it will be possible to turn it off the connection information per-IP address. But you can configure your logging framework to log at `WARN` level for these classes : 
`com.hazelcast.nio.tcp.SocketAcceptorThread`
`com.hazelcast.nio.tcp.TcpIpConnectionManager`
`com.hazelcast.nio.tcp.TcpIpConnection`
Unfortunately that also means that you won't be able to see connection lifecycle information on client and members.

**Comment by dannygu** [comment]
Hi @mmedenjak , thanks for the answer.

This is what i was trying to avoid, turning off logging completely isn't very wise.

IMHO this is a bug /health shouldn't generated this errors in the log as we aren't trying to initiate a new cluster connection/member.

Thanks!

**Comment by mmedenjak** [comment]
The logs are at `INFO` level, not `ERROR`. So you could raise the log level for just those three classes and still see any errors.

**Comment by rbalabomm** [comment]
Hi Guys,

our team is facing same issue! is the issue resolved?

**Comment by mmedenjak** [comment]
@rbalabomm the enhancement has not been addressed. You can increase the log level for that class in your logging configuration for now.

**Comment by Holmistr** [comment]
We decided that we're not going to address this issue. We agree with the point in https://github.com/hazelcast/hazelcast/issues/11196#issuecomment-325993470 comment and we see it the way that users can always configure their logger appropriately. Closing the issue.
