### ISSUE TITLE
Chapter "Hazelcast Configuration" missing since version 3.6.2

### ISSUE THREAD

**Issue by PeterStofferis** [hazelcast/hazelcast#10950]
Up to version 3.6.1. a chapter "Hazelcast Configuration" was available in the Hazelcast Reference Manual. From version 3.6.2 on this chapter has disappeared from the Hazelcast Reference Manual.

Shouldn't this chapter be present in all version of the Hazelcast Reference Manual?

**Comment by Donnerbart** [comment]
Are you searching for this chapter? http://docs.hazelcast.org/docs/3.8.3/manual/html-single/index.html#understanding-configuration

If there are any further issues with the reference manual, please file them here: https://github.com/hazelcast/hazelcast-reference-manual

**Comment by Serdaro** [comment]
Also please note that System Properties section back then is now a separate chapter: http://docs.hazelcast.org/docs/3.8.3/manual/html-single/index.html#system-properties

**Comment by PeterStofferis** [comment]
@Donnerbart @Serdaro The 2 sections of the documentation you pointed me to seem to cover a part of the section I was looking for. It looks like more documentation of the configuration is spread across the different chapters. e.g. The configuration documentation of near cache is located in the section 21.5 "Near Cache".
The conclusion is the chapter isn't missing but it has been reorganized and spread over the different sections of the documentation - closer to the topic being discussed. I guess this is an improvement.
Thanks for your help!

@Donnerbart Thanks for pointing me to the github repo of the reference manual. I found this one on the documentation home (http://docs.hazelcast.org) - on the left, the text "Find a bug? Report it in the Issue Tracker.", the link points to https://github.com/hazelcast/hazelcast/issues. So I guess this link should point to https://github.com/hazelcast/hazelcast-reference-manual?

**Comment by Serdaro** [comment]
@PeterStofferis , Actually the Reference Manual has a "Send Us a Fix!" button located at the right bottom of its page (it is a floating fixed button that appears when you start to scroll).

**Comment by Donnerbart** [comment]
I think Peter is referring to this one:
![screenshot from 2017-07-19 13-42-07](https://user-images.githubusercontent.com/4196298/28365266-227d1b6c-6c88-11e7-868e-0273953509f7.png)

**Comment by Serdaro** [comment]
Yes, please refer to my above comment.

**Comment by Serdaro** [comment]
@PeterStofferis , could we close this issue?

**Comment by PeterStofferis** [comment]
@Donnerbart Indeed, that's the one I'm referrring to.

@Serdaro I didn't notice the hovering "Send Us a Fix!" button, but it's there. I should have used that one.

The link on the left however is misleading and conflicts with the "Send Us a Fix!" button.
I suggest to update (or remove?) the link on the left.
But that's another issue.

@Serdaro Yes, you can close this issue - issue is solved!

Thanks for your help!
