### ISSUE TITLE
SSL Incorrect Error Message : Memcached not enabled

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#10971]
If you try to connect to a Hazelcast Cluster that has SSL/Security disabled with a Hazelcast Client that has SSL enabled we seem to get a very strange error message...where it complains that "Memcached not enabled".  

This is using 3.8.1 both sides.  Not tried 3.8.3/3.9-EA

Can we please change this to tell the user they're trying to connect with an SSL enabled client to a non SSL cluster 

```
2017-07-24T14:10:30,644 INFO  [TcpIpConnection] [x.x.x.x]:47501 [dev] [3.8.1] Connection[id=32, /x.x.x.x:47501->/x.x.x.x:54938, endpoint=null, alive=false, type=NONE] closed. Reason: Memcached not enabled
```
ip addresses redacted.

```
ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();
networkConfig.setSSLConfig((new SSLConfig()).setEnabled(true));
clientConfig.setNetworkConfig(networkConfig);
return HazelcastClient.newHazelcastClient(clientConfig);
```

**Comment by jerrinot** [comment]
I think the only sensible way is to change the error message. 
otherwise we would have to detect SSL/TLS Hello Message on our own. See https://idea.popcount.org/2012-06-16-dissecting-ssl-handshake/

**Comment by dbrimley** [comment]
Yes, that's all I'm asking can we change the error message.

Maybe we could put a hint in there, rather than doing the detection.

e.g. "You might have an issue connecting to non TLS cluster with a TLS client."

**Comment by pveentjer** [comment]
If it is just an error message improvement, we can easily slip it in 3.9.
