### ISSUE TITLE
IMap Near cache xml config "local-update-policy"

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#10974]
@ahmetmircik says
"For map near caches `<local-update-policy>CACHE_ON_UPDATE</local-update-policy>` 
can not be used, i expect to see an exception message but seems no in the logs"

**Comment by ahmetmircik** [comment]
we already have that exception, this is the related test that verifies behaviour:https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/internal/config/ConfigValidatorTest.java#L284

**Comment by Danny-Hazelcast** [comment]
when i add some invalid xml, e.g in this case https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x/100/console


we see the issue in the logs


 ```fail HzClient4HZ com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'SOME-INVALID-XML'. One of '{"http://www.hazelcast.com/schema/client-config":in-memory-format, "http://www.hazelcast.com/schema/client-config":serialize-keys, "http://www.hazelcast.com/schema/client-config":invalidate-on-change, "http://www.hazelcast.com/schema/client-config":time-to-live-seconds, "http://www.hazelcast.com/schema/client-config":max-idle-seconds, "http://www.hazelcast.com/schema/client-config":eviction, "http://www.hazelcast.com/schema/client-config":max-size, "http://www.hazelcast.com/schema/client-config":eviction-policy, "http://www.hazelcast.com/schema/client-config":cache-local-entries, "http://www.hazelcast.com/schema/client-config":local-update-policy, "http://www.hazelcast.com/schema/client-config":preloader}' is expected.```
(edited)


which we do not see for `<local-update-policy>CACHE_ON_UPDATE</local-update-policy>`

**Comment by Danny-Hazelcast** [comment]
this issue is effecting EE only
