### ISSUE TITLE
[diagnostics] rolling average

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#10990]
Certain fields like connection bytes send give an absolute value. But there is no out of the box outputting of windows data, e.g. 1 minute average. It would be useful to have such an option as well. Perhaps through the annotation

```
@Probe
@Rolling(1, Minute)
long send(){...}
```

So then when outputting the diagnostics data ,next to the absolute value, we also get an average for a minute.

**Comment by burakcelebi** [comment]
We have no plans to implement this.
