### ISSUE TITLE
NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject when using Payara Server and hazelcast-aws

### ISSUE THREAD

**Issue by Imadevops** [hazelcast/hazelcast#10994]
Hazelcast comes bundled with Payara which is an OSGI environment. The `com.hazelcast.com.eclipsesource.json.JsonObject` class is not exported in the OSGI metadata in the MANIFEST of the Hazelcast.jar. Therefore cannot be loaded by classes in the hazelcast-aws-2.0.1.jar.  Because of this, when we use the hazelcast-aws-2.0.1.jar and the Discovery SPI strategy with `iam-role`  we get `NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject `.    The discovery works fine when we provide the proper `access-key` and `secret-key` but fails with `iam-role`.  

I raised an issue with the Payara team (https://github.com/payara/Payara/issues/1806) regarding this.  The suggested workaround was to manually edit the hazelcast.jar  MANIFEST file and add `com.hazelcast.com.eclipsesource.json;version="3.7.4"` to the Export-Package section.  This resolved our issue. 

Contents of hazelcast-config.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>group-name</name>
        <password>group-pass</password>
    </group>
  <properties>
     <property name="hazelcast.discovery.enabled">true</property>
  </properties>
   <network>
        <port auto-increment="false">5700</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <multicast enabled="false" />
            <tcp-ip enabled="false" />
            <aws enabled="false" />
           <discovery-strategies>
              <discovery-strategy  enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                <properties>
                   <property name="access-key">my-access-key</property>
                   <property name="secret-key">my-secret-key</property>
                   <property name="iam-role">IAM_ROLE</property>
                   <property name="region">us-west-1</property>
                   <property name="tag-key">TagName</property>
                   <property name="tag-value">TagValue</property>
                   <property name="hz-port">5700</property>
                </properties>
              </discovery-strategy>
            </discovery-strategies>
        </join>
      </network>
</hazelcast>
```

## Environment ##
* **Payara Version**: 4.1.1.171.1
* **Hazelcast Version**: 3.7.4
* **JDK Version**: 8 u131 - OpenJDK
* **Operating System**: Linux - Amazon Linux

**Comment by mesutcelik** [comment]
As discussed with @jerrinot , I am closing the issue here but have created a new one on hazelcast-aws repository. https://github.com/hazelcast/hazelcast-aws/issues/42

Hi @Imadevops ,
please follow up the [issue](https://github.com/hazelcast/hazelcast-aws/issues/42) for further update.

Thanks a lot for heads up!
