### ISSUE TITLE
MapEvictionPolicy.compare error in javadoc

### ISSUE THREAD

**Issue by balazspeterfi** [hazelcast/hazelcast#11074]
hazelcast 3.8.4

The javadoc for MapEvictionPolicy.compare says:
> If you prefer to evict the 1st entry then return positive number, if the 2nd entry is a better candidate then return a negative number or return 0 if both entries are equally good candidates for eviction

which seems to be incorrect as the implementations (LRUEvictionPolicy and LFUEvictionPolicy) behave the opposite way i.e. return -1 if the first entry needs to be evicted and +1 if the second.

**Comment by ahmetmircik** [comment]
Indeed javaDoc needs to be updated. Thanks for reporting this.
