### ISSUE TITLE
Add support for properties in RingbufferStoreConfig xml 

### ISSUE THREAD

**Issue by dpwegener** [hazelcast/hazelcast#11077]
There is currently no support for adding properties to a RingBufferStoreConfig in an XML configuration file.  The RingBufferStoreConfigFactory interface includes a properties argument taken from the RBSC.  However, there is no way to get the properties initialized using only XML.  Adding support will allow properties such as file paths or db urls to be passed in to the store via the config file.  Adding support would provide behavior to the MapStoreConfig and QueueStoreConfig building in the XMLConfigBuilder class.

I've attached a pull request that contains what I believe are the necessary changes including a test for the new code. #11070

**Comment by mmedenjak** [comment]
@dpwegener thanks for reporting the issue and providing a PR. Can you please sign the contributors agreement so we can include your change in the next release?

**Comment by tkountis** [comment]
This has been fixed and merged in 3.9.
See https://github.com/hazelcast/hazelcast/pull/11070 & https://github.com/hazelcast/hazelcast/pull/11338
