### ISSUE TITLE
MapLoader validation on loadAll(Collection)

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11080]
This code does not result in a warning/error on 3.8.3
```
	@Override
	public Map<String, String> loadAll(Collection<String> keys) {
	    Map<String, String> result = new HashMap<>();
	    for(String key : keys) {
			String key2 = "!" + key + "!";
    			String value = this.load(key2);
    			result.put(key2, value);
	    }
	    return result;
	}
```

The keyset of the output shouldn't be allowed to contain keys not in the input

**Comment by tombujok** [comment]
What would be the point of this validation?

**Comment by pveentjer** [comment]
Question is if we want to make an explicit validation, or if we should add it to the documentation only.

I think it should be sufficient to explicitly state it in the contract that the keyset of the resulting map should be the same as the input keys.

**Comment by tombujok** [comment]
I agree. There's no point in validation 10 different scenarios that we can come up with. If you want to do harm somehow you can do it anyway...

**Comment by tombujok** [comment]
@neilstevenson @gokhanoner if that's fine by you this one will be a no-fix. But I managed to squash the three other issues related to MapLoader that you and Gokhan submitted.
