### ISSUE TITLE
REST URLs for cluster version

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11139]
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpGetCommandProcessor.java
will do the same thing for
`http://127.0.0.1:5701/hazelcast/rest/cluster/version`
and
`http://127.0.0.1:5701/hazelcast/rest/cluster/state`

As it's testing
`} else if (uri.startsWith(URI_CLUSTER)) {` on line 48
before
`} else if (uri.startsWith(URI_CLUSTER_VERSION_URL)) {` on line 52

Tried on 3-9-SNAPSHOT

**Comment by vbekiaris** [comment]
`URI_CLUSTER_VERSION_URL` is `/hazelcast/rest/management/cluster/version` so there is no overlap with `URI_CLUSTER = "/hazelcast/rest/cluster"`. Is the cluster version management URL documented as `/hazelcast/rest/cluster/version`? Maybe we need to update docs.

**Comment by gokhanoner** [comment]
@vbekiaris it's not documented anywhere. We need to add all those links to documentation clearly, with example outputs and everything.

**Comment by neilstevenson** [comment]
@vbekiaris Putting all the links in the documentation would work for me, be enough to see this closed.

I'd misinterpreted the code, so `HttpGetCommandProcessor` isn't wrong, but it's difficult to folk (for me :-) ) so documentation for 3.9 would be good.

**Comment by vbekiaris** [comment]
Here is the documentation PR: https://github.com/hazelcast/hazelcast-reference-manual/pull/310
