### ISSUE TITLE
getmap returns null when values are present

### ISSUE THREAD

**Issue by imranrajjad** [hazelcast/hazelcast#11159]
I am seeing some strange behavior while checking out hazelcast basic demo example(version 3.8.4). I have run three console applications 2 on Linux machines and 1 on Windows. I have connected to the cluster through Java client and added 3 values in the 'default' map that is created by console apps. Strangely when I list the keys and values, I am able to see keys and values but the get method returns null.

Junit Java code used to connect to the cluster through the server

```
ClientConfig clientConfig = new ClientConfig();
clientConfig.addAddress("127.0.0.1:5701");
client = HazelcastClient.newHazelcastClient(clientConfig);
map = client.getMap("default");
map.put(1, "One");
map.put(2, "Two");
map.put(3, "Three");
```
The output of Junit on eclipse console

```
Aug 21, 2017 9:38:18 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.8.4] HazelcastClient 3.8.4 (20170809 - 297a77e) is STARTING
Aug 21, 2017 9:38:18 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.8.4] HazelcastClient 3.8.4 (20170809 - 297a77e) is STARTED
Aug 21, 2017 9:38:18 AM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [dev] [3.8.4] Trying to connect to [127.0.0.1]:5701 as owner member
Aug 21, 2017 9:38:18 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.8.4] Setting ClientConnection{alive=true, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:55664 remote=/127.0.0.1:5701]}, remoteEndpoint=[192.168.10.60]:5701, lastReadTime=2017-08-21 09:38:18.776, lastWriteTime=2017-08-21 09:38:18.776, closedTime=never, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=3.8.4} as owner  with principal ClientPrincipal{uuid='1d0e8e88-85d2-4dd7-97cd-53acd59595b5', ownerUuid='7501645e-e9fe-465d-b0f9-f2c458ea4973'}
Aug 21, 2017 9:38:18 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.8.4] Authenticated with server [192.168.10.60]:5701, server version:3.8.4 Local address: /127.0.0.1:55664
Aug 21, 2017 9:38:18 AM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [dev] [3.8.4] 

Members [2] {
	Member [192.168.10.60]:5701 - 7501645e-e9fe-465d-b0f9-f2c458ea4973
	Member [192.168.10.200]:5701 - 0cda8964-873f-4afb-a61a-2c5e9237d1c1
}

Aug 21, 2017 9:38:18 AM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [dev] [3.8.4] HazelcastClient 3.8.4 (20170809 - 297a77e) is CLIENT_CONNECTED
Aug 21, 2017 9:38:18 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [dev] [3.8.4] Authenticated with server [192.168.10.200]:5701, server version:3.8.4 Local address: /192.168.10.60:55665
Map Size:0
Map Size:3
[2, 1, 3]
[Two, One, Three]
One
```
after this when I go to the console app 
```
hazelcast[default] > m.keys
3
2
1
Total 3
hazelcast[default] > m.values
Two
One
Three
Total 3
hazelcast[default] > m.get 1
null
```
This happens the otherway around also, the Java client lists the keys and values but getmap returns null. Please note I have not touched the settings yet, if this is not an issue then what configuration needs to be done to fix this?

regards,
Imran

**Comment by vbekiaris** [comment]
Hi @imranrajjad , thanks for your issue report. The behavior you observe is due to the demo console app [treating all keys / values as `String`s](https://github.com/vbekiaris/hazelcast/blob/b1c425e8598cde123ab11493b4dc7896dbfec15e/hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java#L682-L684). The binary representation of the boxed `Integer` 1 in the java client is different than the `String` "1" which is the console app's interpretation of the argument in `map.get 1` --> you see `null` as value. Try switching your java test client to use `String`s as keys and you should observe consistent results.

Feel free to re-open this issue if you think there's still something wrong to be fixed.
