### ISSUE TITLE
Prefix query (indexing on key)

### ISSUE THREAD

**Issue by nikoncode** [hazelcast/hazelcast#11171]
Hi.

If I have composite key in my map like piece1:piece2:piece3 and if I execute query like below:
* aa:bb:*
* aa:*

does any indexes used and which query I should execute for that: like, ilike or regex?

Thanks.

**Comment by mmedenjak** [comment]
@nikoncode Currently neither the `like` predicate nor regex use the index. The index is used for exact searches only.
What is the issue you are experiencing?

**Comment by mmedenjak** [comment]
@nikoncode can you explain the issue you are experiencing?

**Comment by mmedenjak** [comment]
Closing this as a non-issue. Please reopen if you have more information.
