### ISSUE TITLE
health monitor docs

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#11183]
I searched reference manual but could not find any info about health monitor.
Just there is just related system properties, nothing more.

**Comment by pveentjer** [comment]
What would you like to see? Health monitor is poor mans solutions; diagnostics is the future.

**Comment by ahmetmircik** [comment]
@enesakar ?

**Comment by Serdaro** [comment]
Just in case, fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/5b5e1633b6c1ae903da0c1256e4f79b3758bbeb2
