### ISSUE TITLE
Hazelcast cluster died under load and did not recover

### ISSUE THREAD

**Issue by Illapikov** [hazelcast/hazelcast#11188]
Recently we've experiment with load testing (self written tool) when Hazelcast cluster died under load and did not recover.

Hazelcast version is 3.7.7 for both server and client.

We had cluster of 5 Hazelcast nodes with OBJECT in memory format (this is essential, because with BINARY we hadn't such situation).
We ran couple of long running queries in parallel (using predicate by one field in addition to the entry processor) on 1 million entries. (again, this is essential, because simple findOne or create/update entry do not cause failing)

Symptoms:
- Low load: 2 load generators. HZ CPU ~16% on each node
- Medium load: 10 load generators. HZ CPU ~40%
- High load: 15 load generators. HZ CPU jumped to almost 100%

After 2 minutes on high load HZ nodes stopped responding and reporting metrics (JMX agent was included) and did not recover when load was removed.

In the logs we had tonns of messages on a clients:
`com.hazelcast.client.HazelcastClientNotActiveException: ConnectionManager is not active!`
and
`com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!`

**Comment by pveentjer** [comment]
Can you attach some of the logs around the time this problem happened.

**Comment by Illapikov** [comment]
Unfortunately, logs are sensitive and cannot be easily shared, also, for some reason there were huge amount of them ~2 million records for around of 4 hours.

The single query should process 500000 entries and extract 2 fields (small string and integer) in a map, compose and return this result.
The size of the objects in Hazelcast map is around 2.5 KB.

**Comment by pveentjer** [comment]
How many results are expected for the query? I'm trying to get an impression of the size.

**Comment by Illapikov** [comment]
The expected result is literally: 
500 000 *
```
Map<String, Object> map = new HashMap<String, Object>(2);
map.put("field1", "value1");
map.put("field2", 50);
```

**Comment by pveentjer** [comment]
So you have an IMap where the value is a HashMap?

**Comment by Illapikov** [comment]
Not really, the IMap values is a complex object, but the entry processor extracts those fields during the query.
The code looks like:
```
map.executeOnEntries(new CustomEntryProcessor(queryToExtractFields), Predicates.equal("field", predicateValue))
```

So, both Predicate filtering and EntryProcessor are involved.

The whole IMap contains 1m records, given predicate decrease number to 500000 records and this entry processor extracts 2 fields from object and puts them into the HashMap.

**Comment by pveentjer** [comment]
Ok. Then my guess is that there is a problem with these huge results building up.

Have you checked with a profiler where time is being spend? Java Flight Recorder is an excellent tool to see what happens in your JVM, as long as you can run it locally otherwise you will get uncle Larry in your back.

Also if you upgrade to 3.8, we can see better what is going on inside these the HZ instance. Especially what is happening with the connections (my guess is that is the problem)

**Comment by Illapikov** [comment]
The thing is - we are running our cluster in Amazon cloud, so I don't think it is possible to reproduce this locally.

Also, I think we'll have a lot of deprecate code used if we upgrade to 3.8 version.

Is there anything else I could be looking for? 
Anything specific in the logs, which might light up the case?
Is there any diagnostics available for 3.7?

**Comment by pveentjer** [comment]
Run with the following

```
-Dhazelcast.diagnostics.enabled=true
-Dhazelcast.diagnostics.metric.level=info
-Dhazelcast.diagnostics.invocation.sample.period.seconds=30
-Dhazelcast.diagnostics.pending.invocations.period.seconds=30
-Dhazelcast.diagnostics.slowoperations.period.seconds=30
```

This runs without performance problems in production. 

Lets see what happens.

What kind of instance are you running on btw?

**Comment by Illapikov** [comment]
Instance type is m3.2xlarge.

I'll post my findings in couple of hours, when load testing is done.

**Comment by Illapikov** [comment]
Alright, done another one load testing, everything gone the same way as previous runs, but I've spotted suspicious entry in Kibana:
```
com.hazelcast.core.OperationTimeoutException: PartitionWideEntryWithPredicateOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2017-08-24 14:23:04.731. Total elapsed time: 113459 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2017-08-24 14:22:44.938. Invocation{op=com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation{serviceName='hz:impl:mapService', identityHash=338169688, partitionId=0, replicaIndex=0, callId=0, invocationTime=1503584461942 (2017-08-24 14:21:01.942), waitTimeout=-1, callTimeout=60000, entryProcessor=com.company.hazelcast.processor.CustomEntryProcessor@70bf2146, predicate=field=value}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1503584471272, firstInvocationTime='2017-08-24 14:21:11.272', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[10.0.173.112]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=84, /10.0.145.153:45701->/10.0.173.112:5701, endpoint=[10.0.173.112]:5701, alive=true, type=MEMBER]}
```

Judging from Wavefront graphs JVM memory grows faster than CPU usage and only after additional load CPU % jumps to 100.

We are using JMX agent so it is possible to build graph in Wavefront using metrics from it. So, the question is what metrics do we want to check?

I've added diagnostics to the Hazelcast as you requested and here is link to google drive with files: https://drive.google.com/open?id=0B2PQ5hMV1WTQTm9jcUk1d2Z6bms

**Comment by pveentjer** [comment]
First the exception:

```
com.hazelcast.core.OperationTimeoutException:
 PartitionWideEntryWithPredicateOperation invocation failed to complete due to operation-heartbeat-timeout. 

Current time: 14:23:05 
Total elapsed time: 113.459 ms. 
Last operation heartbeat: never. 
Last operation heartbeat from member: 14:22:45
```

What this tells me is that the network and therefor the remote JVM is still running 'ok' since a heartbeat has been received recently from that member. However this operation never managed to receive a heartbeat. My guess is that because you are using entry processors, the entry processor (that processes the partition in 1 go) is hogging the partition thread and therefor subsequent entry processors for that same partition get blocked and eventually run into a heartbeat timeout since such type of blocked operations don't receive heartbeats.

I'm downloading the diagnostics and hope to get some better understanding what is happening.

**Comment by pveentjer** [comment]
With the help of the diagnostics files I can some serious problems on the operation thread. For example the following:

```
 com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation[
                                  invocations=1
                                  stackTrace[
                                          com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.ensureAvailable(ByteArrayObjectDataOutput.java:360)
                                          	com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.write(ByteArrayObjectDataOutput.java:71)
                                          	java.io.OutputStream.write(OutputStream.java:75)
                                          	com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeByteArray(ByteArrayObjectDataOutput.java:264)
                                          	com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeData(ByteArrayObjectDataOutput.java:377)
                                          	com.hazelcast.map.impl.MapEntries.writeData(MapEntries.java:141)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:189)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:54)
                                          	com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
                                          	com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:234)
                                          	com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:371)
                                          	com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation$PartitionResponse.writeData(PartitionIteratingOperation.java:260)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:189)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:54)
                                          	com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
                                          	com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:234)
                                          	com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:371)
                                          	com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.writeData(NormalResponse.java:91)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:189)
                                          	com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:54)
                                          	com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
                                          	com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:140)
                                          	com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:124)
                                          	com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:427)
                                          	com.hazelcast.spi.impl.operationservice.impl.RemoteInvocationResponseHandler.sendResponse(RemoteInvocationResponseHandler.java:51)
                                          	com.hazelcast.spi.Operation.sendResponse(Operation.java:291)
                                          	com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponse(OperationRunnerImpl.java:281)
                                          	com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:259)
                                          	com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:182)
                                          	com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:396)
                                          	com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
                                          	com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)]
                                  slowInvocations[
                                          startedAt=1,503,582,541,116
                                          durationNs=15,413
                                          operationDetails=com.hazelcast.spi.impl.operationservice.impl.operations.PartitionIteratingOperation{serviceName='hz:impl:mapService', identityHash=441054006, partitionId=-1, replicaIndex=0, callId=6120920, invocationTime=1503582529612 (2017-08-24 13:48:49.612), waitTimeout=-1, callTimeout=60000, operationFactory=com.hazelcast.client.impl.operations.OperationFactoryWrapper@37a652bc}]]
```

So this operation took 15 seconds to complete. Meaning that it has stalled other operations mapped to the same thread for 15 seconds. And these delays can quickly add up and eventually can lead to an operation timeout.


If you have a closer look at the stacktrace;   you see it is busy with 'ensureAvailable'. This is where the system is growing the output buffer (copying the content to a new buffer). This can happen multiple times for a single response. 

So it seems that the system is chocking on your map of map responses.

**Comment by pveentjer** [comment]
Since you are using the entry processor just for reading data, it could be that by accident you are executing the same entry processor on the backup causing more load than needed. Can you post me your entry processor code. The most important parts I need to know is its parent class/interfaces. If it extends AbstractEntryProcessor, I need to know how it calls the super constructor. And I need to know if/how it implements  EntryBackupProcessor<K, V> getBackupProcessor();.

**Comment by pveentjer** [comment]
Something else that probably reduces your problems a lot is getting rid of that map you use as return value. I made a small extremely non professional benchmarking to show the difference between map and array based entry processor.


```
package com.hazelcast;

import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.map.EntryBackupProcessor;
import com.hazelcast.map.EntryProcessor;

import java.util.HashMap;
import java.util.Map;

public class Main {

    public static void main(String[] args) {
        Config config = new Config();
        config.addMapConfig(new MapConfig("foo").setBackupCount(0));

        HazelcastInstance hz1 = Hazelcast.newHazelcastInstance(config);
        HazelcastInstance hz2 = Hazelcast.newHazelcastInstance(config);

        IMap map = hz1.getMap("foo");
        for (int k = 0; k < 500 * 1000; k++) {
            map.put(k, k);
        }

        System.out.println("Inserting data complete");
        for (; ; ) {
            long s = System.currentTimeMillis();
            map.executeOnEntries(new ArrayEP());
            long d = System.currentTimeMillis() - s;
            System.out.println("Duration:" + d + " ms");
        }
    }

    static class ArrayEP implements EntryProcessor<Integer, Integer> {
        @Override
        public Object process(Map.Entry<Integer, Integer> entry) {
            int key = entry.getKey();
            int value = entry.getKey();
            return new int[]{key, value};
        }

        @Override
        public EntryBackupProcessor<Integer, Integer> getBackupProcessor() {
            return null;
        }
    }

    static class MapEP implements EntryProcessor<Integer, Integer> {
        @Override
        public Object process(Map.Entry<Integer, Integer> entry) {
            Map map = new HashMap();
            int key = entry.getKey();
            int value = entry.getKey();
            map.put("key", key);
            map.put("value", value);
            return map;
        }

        @Override
        public EntryBackupProcessor<Integer, Integer> getBackupProcessor() {
            return null;
        }
    }
}
```

And here are the results
```
Map based

Duration:3903 ms
Duration:3267 ms
Duration:2692 ms
Duration:2522 ms
Duration:2365 ms
Duration:2296 ms
Duration:2168 ms
Duration:2131 ms
Duration:2156 ms
Duration:2387 ms
Duration:2703 ms

Array based
Duration:577 ms
Duration:230 ms
Duration:297 ms
Duration:182 ms
Duration:263 ms
Duration:175 ms
Duration:236 ms
Duration:173 ms
Duration:180 ms
Duration:232 ms
Duration:180 ms
Duration:175 ms
Duration:173 ms
Duration:196 ms
Duration:173 ms
Duration:171 ms
```

For this test the array based EP is an order of magnitude faster than the map based version.

**Comment by Illapikov** [comment]
Here is code for our EntryProcessor.
```
public class CurrentValuesExtractor extends AbstractEntryProcessor<String, POJO> {

    private static final long serialVersionUID = 4962752409816738045L;

    private Set<String> properties;

    public CurrentValuesExtractor(final Set<String> properties) {
        this.properties = properties;
    }

    @Override
    public Object process(final Map.Entry<String, POJO> entry) {

        final POJO pojo = entry.getValue();

        if (pojo == null || properties.isEmpty()) {
            return null;
        }

        final Map<Integer, Map<String, Object>> resultMap = new HashMap<Integer, Map<String, Object>>();

        for (final Map.Entry<Integer, POJO.AnotherPOJO> anotherPOJOs : pojo.getAnotherPOJO().entrySet()) {

            final Integer key = anotherPOJOs.getKey() == null ? Integer.valueOf(0) : anotherPOJOs.getKey();

            final Map<String, Object> map = new HashMap<String, Object>(properties.size());

            for (final String property : properties) {

                final POJO.AnotherPOJO anotherPOJO = anotherPOJOs.getValue();
                if (anotherPOJO.hasProperty(property)) {
                    map.put(property, anotherPOJO.getCurrentValue(property));
                }
            }

            resultMap.put(key, map);
        }

        return resultMap;
    }
}
```

This explains why memory grows (so fast and so much), but the question about CPU remains.

**Comment by pveentjer** [comment]
Your current EntryProcessor implementation is applied on primary and backups; in your case doing the calculation on the backups makes no sense. Have a look at my implementations or call the super(false) to prevent repeating on backup.

**Comment by pveentjer** [comment]
I see you have a map of maps which again is wrapped inside a map. This is going to be terribly inefficient. It will probably make use of regular Java serialization (which is very slow and gives very big objects).

You can speed this up by implementing a custom serializer. But first fix the backup problem from my previous message.

**Comment by Illapikov** [comment]
Alright, this is going to be fixed.

But why CPU grows (it literally jumps from 40% to 100% at some point) as well?

Also, after this run, when I left only 1 load generator working, I've seen that memory remained on a high level (~20/26 G) and we've lost around 100k entries.

Any ideas about this?

**Comment by pveentjer** [comment]
Can you elaborate on the 100k entries loss? How do you determine this?

**Comment by Illapikov** [comment]
In the Wavefront I have access to JMX metrics, specifically `IMap.mapName.localOwnedEntryCount`.
Previously it was 1m as expected, but right after I lowered load from 15 to 1 load generator it got 896k only.

**Comment by pveentjer** [comment]
@ahmetmircik do you know what is going on.

**Comment by Illapikov** [comment]
Actually, about backup entry processing, we have no backups:
`<backup-count>0</backup-count>`
so, it should not affect us.

**Comment by dsukhoroslov** [comment]
Hi @pveentjer. Recently I got a similar issue with long running entry processor. The EP process several thousands of records in a loop, so it does take some time. My question is: how can I emit operation heartbeat manually from my code to prevent the opertion timeout?

Thanks, Denis.

**Comment by mmedenjak** [comment]
@Illapikov can you try retesting with hazelcast 3.10.4? We've made quite a few improvements and your issue might have been solved.

**Comment by mmedenjak** [comment]
@Illapikov any updates on the issue?

**Comment by mmedenjak** [comment]
Closing as there are no updates. Please try with the latest stable Hazelcast which is now 3.11.2. Hazelcast 3.12 will also be released soon with more improvements. Please reopen if this issue persists.
