### ISSUE TITLE
Cleanup CachingProvider code

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#11190]
There are opportunities for [cleanup and deduplication](https://github.com/hazelcast/hazelcast/pull/11045#discussion_r134447229) of code shared across client and member `CachingProvider` implementations.

**Comment by jerrinot** [comment]
moving to 3.10

**Comment by pveentjer** [comment]
@vbekiaris is this a bug or a cleanup?

**Comment by vbekiaris** [comment]
It's a cleanup
