### ISSUE TITLE
[scheduled-executor] Registration objects causing memory leak while using ScheduledExecutor

### ISSUE THREAD

**Issue by Mihajlovski** [hazelcast/hazelcast#11221]
I originally posted this question on [stackoverflow](https://stackoverflow.com/questions/45862782/hazelcast-registration-objects-causing-memory-leak-while-using-scheduledexecutor).

We are using Hazelcast (version 3.8.2) ScheduledExecutor to perform tasks in a cluster. We have a memory issue. 

[Zabbix memory graph - OLD GC Usage](https://i.stack.imgur.com/4kEkJ.png)

Profiling was done, and we realized that the leak is happening in EventServiceSegment for registration maps. It's all for .partitionLost events. Or, well, majority.

[Yourkit memory profiling](https://i.stack.imgur.com/ESs3u.png)

We know about disposing finished future, and here's our code that is performed on each instance periodically.

```
final long futureDisposed = service.getAllScheduledFutures().values().stream().flatMap(Collection::stream)
            .filter(future -> future.getStats().getTotalRuns() > 0).peek(IScheduledFuture::dispose).count();
final long futuresLeft = service.getAllScheduledFutures().values().stream().flatMap(Collection::stream).count();
```

What we get when logging those values is okay, correct number of tasks is disposed, and correct number of tasks remains scheduled. At the moment of this heap dump, futuresLeft logged ~2500 scheduled futures as left in the system. But the memory is still growing.

Our tasks get generated in batches of hundreds, then get scheduled for same delay. The tasks are implementing Runnable, Serializable and HazelcastInstanceAware. We also have transient references to some objects we pick up from userContext of HazelcastInstance.

Scheduling is done as:
```
this.scheduler = instance.getScheduledExecutorService(schedulerName);
this.scheduler.schedule(new Task(taskId), delay, TimeUnit.MILLISECONDS);
```

When tasks are executed, they might get rescheduled, and then we create a new object (previously we would schedule same objects back, but then we changed it, hoping it would help, but it didn't).

Scheduler is configured with durability 1 and poolSize of 2.

I've went through code, googled whatever keyword I could find, but nothing helped. I can see that these registrations are supposed to be cleaned when calling dispose, but they are not.

How to properly clean this registrations map when tasks are finished?

**Comment by Danny-Hazelcast** [comment]
I was just looking at scheduled executor, and making this test https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/executor/scheduled/ScheduleDispose.java

each task is scheduled with a long delay, of 3600 seconds, then i  schedule.dispose();  the IScheduledFuture task on the next line (edited)

but looking at the GC of the member after running this for 1 hour http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_08_25-09_56_38/gc.html

looks like a leak,

(links private)

**Comment by Danny-Hazelcast** [comment]
2nd run with one member  version 3.9-SNAPSHOT

GC  http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_08_25-12_04_23/scheduled-dispose/gc.html

Hprof
http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_08_25-12_04_23/scheduled-dispose/output/HZ/HzMember1HZ/HzMember1HZ.hprof

**Comment by Donnerbart** [comment]
I got a very simple reproducer. Just add this test to `ScheduledExecutorServiceBasicTest`:
```java
    @Test
    public void schedule_thenDisposeLeakTest() throws Exception {
        int delay = 10000;
        String taskName = "Test";

        HazelcastInstance[] instances = createClusterWithCount(2);
        IScheduledExecutorService executorService = getScheduledExecutor(instances, "s");

        for (int i = 0; i < 10000000; i++) {
            IScheduledFuture<Double> future = executorService.schedule(
                    named(taskName, new PlainCallableTask()), delay, SECONDS);
            future.dispose();
        }
    }
```
I just monitored it with Visual GC, and it looks like it's leaking:
![screenshot from 2017-08-25 12-02-39](https://user-images.githubusercontent.com/4196298/29709624-5439923a-898d-11e7-8b2a-ae8eeb4d1ab6.png)

Like in the linked hprof from Danny, it looks like a lot of `ScheduledTaskStatisticsImpl` instances are created and not being removed.

**Comment by mmedenjak** [comment]
The cause is the task decoration - the decorated (`LoggingDelegatingFuture`) instance is put into the `LoggingScheduledExecutor.workQueue`. On cancellation, the cancellation is delegated to the wrapped future. It tries to remove the future from the workQueue but it doesn't contain the delegate, it contains the decorator instance.

**Comment by Mihajlovski** [comment]
Are you sure that's the same leak. Our heap dump contains different objects. Mostly PartitionLostListenerAdapter.
![yourkit](https://user-images.githubusercontent.com/153186/29717594-061237e2-89b0-11e7-8534-82d46b127ec1.PNG)

**Comment by Mihajlovski** [comment]
And, of course, is there any work around we can use so we don't have to restart our instances every now and then?

**Comment by mmedenjak** [comment]
Might not be. Can you traverse the references to see which hazelcast class is holding the reference to those hashmap nodes?

**Comment by Mihajlovski** [comment]
It's (mostly) EventServiceSegment.registrations and .registrationById maps. 
Here's EventServiceImpl object.
![serviceimpl](https://user-images.githubusercontent.com/153186/29717897-3519b0c8-89b1-11e7-8e8d-d81fdf530103.PNG)

And the biggest EventServiceSegment for hz:core:partitionService
![servicesegment](https://user-images.githubusercontent.com/153186/29717940-50387290-89b1-11e7-95d2-c3fd52c371ef.PNG)

**Comment by mmedenjak** [comment]
Hm but those look like listener registrations and are not related to the scheduled executor usage. Are you using event listeners? This might be a legitimate use of heap. In any case, we have certainly detected a leak in the disposal of scheduled executor tasks

**Comment by Mihajlovski** [comment]
We do use MembershipListener, but all it does is log. And it's set on the hazelcast instance, not on the tasks.
And, as said, our tasks are HazelcastInstanceAware.
We didn't explicitly set any option for event listening. 

PartitionLostListenerAdapter as it's listener has a ScheduledFutureProxy.
Which as its handler has ScheduledTaskHandlerImpl.

**Comment by tkountis** [comment]
These are two different leaks, from a quick look I had.
ScheduledFutures are member & partition loss aware (or they try to be), meaning that they register themselves as listeners to these kind of events. However, @Mihajlovski is not using the returned Future, but rather re-fetches them with `getAllScheduled`, therefore causing extra refs to stay live.

I will play wth this use-case a bit to see what alternative solutions I can come up with.
For now I guess, as a temporary fix, to avoid that leak, is to use the original Future, as you got it out of `.schedule...()`. Maybe store it in a local `Set` and once you dispose it, then remove it.

**Comment by Mihajlovski** [comment]
Is it enough only to call dispose on the instance that scheduled the task? What happens on other instances in cluster if that one fails?

**Comment by tkountis** [comment]
@Mihajlovski I didn't quite get the question, could you please re-phrase it ?
Just for reference, maybe it helps, `dispose` stops (if still running), cleans listeners & removes the task. This means that any attempt to interact with that Future again, it will fail. Also, all calls to `getAllScheduled` after disposing a task, wont return this task. 

Bottom line, you only have to dispose the Future once, and you can do that by holding the original reference, to a map, and periodically checking when to clean. 

The leak at your use-case is that you never interact with the return value of `executor.schedule()` but rather periodically fetch them all over again & again, by `executor.getAllScheduled()`. This creates new Futures which in turn register themselves as listeners.

**Comment by tkountis** [comment]
Now if you store a reference to the Future in a local `Set<Future>`, and this node/member goes down, you don't have to worry about re-fetching the tasks, next time you restart. You do this once, and you keep that list. I hope that this makes sense.

We will work on potentially providing a better approach to deal with this.

**Comment by Mihajlovski** [comment]
Re-phrase coming :)
We have instances A, B and C. All of them generate some tasks. Each of them stores the futures for the tasks it creates in local set. When they are finished, occasionally it checks which of them are finished, and it calls `dispose()`.
Instance A goes down. Some of the futures weren't cleaned. Do they stay in B and C? Is the system resilient to instance failures or will the leaks at some point sum-up to an OOME?

Here's where we picked up the code for the cleaning by calling `getAllScheduled()`: 
https://github.com/hazelcast/hazelcast/issues/9799

I would never guess that calling `getAllScheduled()` creates new futures, at least from reading the documentation.

**Comment by tkountis** [comment]
@Mihajlovski Firstly, let me clarify what 'creates new futures' means in this context. When you schedule a task, the real future is handled internally by Hazelcast, you never get access to this. What you get, is a **proxy** Future, that acts as the messenger of your commands, eg. when you say, `.get()` it finds the actual future/task, gets the result and brings it back to you. So, now when we say we create new futures when we do `getAllScheduled()` it just means, that we create more proxy objects that interact with that same Future that Hazelcast internally handles. Hope that helps a bit.

Now, back to your question. All tasks you schedule (except from `OnMember` variants) are durable, meaning that they have backups in case one node goes down. As far as you don't use `getAllScheduled()` to often, eg. just once when you boot, you wont run out of heap.

**Comment by Danny-Hazelcast** [comment]
schedule-dispose test,  leak fixed, improved member GC 

![image](https://user-images.githubusercontent.com/5988678/29922825-05ff265e-8e77-11e7-9e22-ca55fde5df17.png)

**Comment by Mihajlovski** [comment]
Storing and disposing local futures did the trick for us. I'd suggest a documentation update. :)

**Comment by Danny-Hazelcast** [comment]
for 3.9
hazelcast.executionservice.taskscheduler.remove.oncancel = true
prevents this issue.
