### ISSUE TITLE
Hazelcast server enters "Zombie mode" after an out of memory error

### ISSUE THREAD

**Issue by matthiasmutam** [hazelcast/hazelcast#11223]
When out of memory, our hazelcast servers stop working, but the process is still running. Port stays open, but no requests accepted. The last error that can be seen in the log is:

    Exception in thread "hz.ShutdownThread" java.lang.OutOfMemoryError: Java heap space

**Comment by mmedenjak** [comment]
Hi @matthiasmutam!

The default OOME handler should try and stop the instance :
https://github.com/hazelcast/hazelcast/blob/73673199472b3fb25cf6c72de378a1d2bab18605/hazelcast/src/main/java/com/hazelcast/instance/DefaultOutOfMemoryHandler.java#L82-L82

That might not work though sometimes if the error is not captured by hazelcast code. Do you see in the logs that it is trying to shut down some time around the error?

**Comment by matthiasmutam** [comment]
No log entries hinting to a shutdown. Just info messages about Socket connections. However, I was assuming from the thread name that Hazelcast was indeed trying to shut down.

**Comment by mmedenjak** [comment]
If you're not seeing connections and services being closed it would seem the error was not captured and handled by hazelcast code. Do you have a stacktrace of where it was thrown from?

**Comment by matthiasmutam** [comment]
Unfortunately not. This log message is all I have.

**Comment by matthiasmutam** [comment]
My current conjecture is that the OutOfMemoryError is thrown during shutdown and kills the shutdown thread, leaving Hazelcast hanging in limbo.

**Comment by mmedenjak** [comment]
Closing this as we are unable to act on this information and hazelcast already has a handler for OOME. Please reopen when if you encounter the issue again with more information.
