### ISSUE TITLE
[event-journal] Incorrect UnsupportedOperationException message

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#11220]
https://github.com/hazelcast/hazelcast/blob/843519c75e235bf8e72ad4dd7f760d576cf17b57/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapEventJournalReadTask.java#L65

Misleading statement, should be  "Event journal actions are available when cluster version is 3.9 or higher");

**Comment by mmedenjak** [comment]
Hi, thanks for your report, we will fix that.
Can you describe the scenario in which you ran into this exception? Were you calling the event journal API? Do you have it enabled? Or was it triggered indirectly while using the IMap or ICache API?

**Comment by lukasherman** [comment]
I have just noticed that reading the code.
