### ISSUE TITLE
Slow database loads broken [HZ-1178]

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#11237]
If a system loads a lot of data and needs to build up a large index, then the client will run into problems. It isn't a good out of the box experience because effectively it means that we can't rely on loading a lot of data. 

So imagine a slow database load taking several minutes; then every operation that is parked behind this operation is going to timeout. Database loading should always be offloaded.

**Comment by mdogan** [comment]
I didn't understand what this issue is about. Is it MapLoader, Hazelcast client or something else? Can you show a sample?

**Comment by mdogan** [comment]
Also if this is *Critical*, why is it postponed?

**Comment by mmedenjak** [comment]
Seems more like a core issue that affects client calls - a slow database load can cause `get` calls to timeout

**Comment by mmedenjak** [comment]
Offloading map loader seems a pretty big task. I'm keen on having a PRD for this. cc @burakcelebi

**Comment by Holmistr** [comment]
We're finally implementing the MapLoader/Store offloading in 5.2

**Comment by AyberkSorgun** [comment]
Done via https://github.com/hazelcast/hazelcast/pull/21651
