### ISSUE TITLE
[client] networkconfig address validation missing

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#11242]
The following program runs fine even though no valid address has been added.

```
public class Main {

    public static void main(String[] args){
        HazelcastInstance server = Hazelcast.newHazelcastInstance();

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getNetworkConfig().addAddress("");

        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        System.out.println(client.getAtomicLong("foo").incrementAndGet());
    }
}
```

So we violate fail-fast.

We should check if the passed address is a valid ip address or hostname.

**Comment by sancar** [comment]
I am planning to add only check for empty string as it is done on server. Server does not do any further validation. 
@pveentjer 
Checking if Ipv4 and Ipv6 format is straightforward but how are we gonna check if it is a valid hostname ?

**Comment by pveentjer** [comment]
We should at least check for empty string (after trimming).
