### ISSUE TITLE
Feature Request : Queries Involving Multi-Value Attributes 

### ISSUE THREAD

**Issue by pmanvi** [hazelcast/hazelcast#1125]
As storing multi values or a list for key (Multimap, Multiset) is a dominant use case, it will be extremely useful to extend the predicate values API available with IMap.
- Collection<V> values(Predicate predicate)

**Comment by imranrajjad** [comment]
did this ever happen? I want to do it in ISet, since documentation says List stays on local machine.

**Comment by mmedenjak** [comment]
@imranrajjad no, it's still a feature request. You may express your request on the linked issue: https://github.com/hazelcast/hazelcast/issues/593
