### ISSUE TITLE
Mock HazelcastInstance for unit testing

### ISSUE THREAD

**Issue by mst-appear** [hazelcast/hazelcast#1126]
It would be nice to have a mock HazelcastInstance for unit testing. That mock should not do any networking and be very fast.

**Comment by dimitrovvlado** [comment]
Perhaps a system property can solve the problem - if "hazelcast.mock.instance" is set to true, Hazelcast.newHazelcastInstance(config) will return a mock implementation with no connections and sockets. Another option is to set a field in the config.

This would be a good optimization when doing unit testing.

**Comment by gurbuzali** [comment]
Hi @dimitrovvlado,
We've already done that, please check our unit-tests. Below is the class which will help you to create a mock-networked instance: `createHazelcastInstance()`
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java
