### ISSUE TITLE
CacheEntryProcessorEntry exists() inconsistent behaviour

### ISSUE THREAD

**Issue by MichelePaterniti** [hazelcast/hazelcast#11266]
Suppose a MutableEntry<K, T> entry exists.

```
System.out.println( entry.exists() ); // prints out true
System.out.println( entry.getValue() ); // prints out the objects toString
System.out.println( entry.exists() ); // prints out false 
```
I would expect the second entry.exists() invocation would return true, since the entry was not removed.

**Comment by jerrinot** [comment]
@MichelePaterniti: thanks for your report. I can confirm it's indeed a bug.
