### ISSUE TITLE
[Hazelcast 3.8.3] Members not rejoining cluster after an elongated network blip.

### ISSUE THREAD

**Issue by RahulSharma21** [hazelcast/hazelcast#11267]
We are trying to test out cluster against network failures and are disconnecting network traffic between couple of nodes using tcpkill .. refer to below command

tcpkill -i  eth1 host 10.31.38.90

Initially there is a cluster of 8 nodes and when the connectivity for a node is broken it gets eliminated from the 8 node cluster and forms a single node cluster. The original cluster contains 7 nodes at this point of time. This is working as expected. However, when the connectivity is restored then disconnected member is not able to join the original cluster and remains isolated.

Below exception is observed even after restoration of network connectivity.
```
2017-08-31T10:33:49Z{GMT} stencdvvap10.va.neustar.com ALL_CALL_QUERY  WARN StandardLoggerFactory.java:49[29842][10.31.38.90]:5701 [dev] [3.8.3] Connection[id=6, /10.31.38.90:5709->/10.58.0.172:5701, endpoint=[10.58.0.172]:5701, alive=false, type=MEMBER] closed. Reason: Exception in NonBlockingSocketReader
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:197)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at com.hazelcast.nio.tcp.DefaultSocketChannelWrapper.read(DefaultSocketChannelWrapper.java:61)
        at com.hazelcast.internal.networking.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:150)
        at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:349)
        at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:334)
        at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.selectLoop(NonBlockingIOThread.java:252)
        at com.hazelcast.internal.networking.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:205)
```

Please see the configuration in attached file.

**Comment by RahulSharma21** [comment]
[hazlecast.xml.txt](https://github.com/hazelcast/hazelcast/files/1266813/hazlecast.xml.txt)

**Comment by jerrinot** [comment]
hi @RahulSharma21, thanks for reporting the issue. 

do you have a logs from all members?

**Comment by RahulSharma21** [comment]
Thanks for taking time and looking into the issue. We are able to consistently reproduce this issue using a 2 -3 node cluster.  Refer below information - 
                
1) We had a running hazelcast cluster of 3 nodes 10.31.38.89, 10.31.38.90 & 10.31.38.91.

2) We executed tcp kill on (2017-08-31 13:31:29) to deliberately break n/w connectivity b/w 10.31.38.89 & 10.31.38.90 nodes. Below command was executed on node 10.31.38.89 to break connectivity -
 
tcpkill -i  eth1 host 10.31.38.90

3) We observed from the logs that two separate clusters were created once containing a single node  10.31.38.89 and another containing both 10.31.38.90 & 10.31.38.91 nodes. This is as expected as n/w is down and hazelcast instance will not be able to send heartbeat.

4) We then terminated tcpkill at around 2017-08-31 13:40:57 and verify that the connectivity is restored using the below two commands - 

[root@10.31.38.89 sshrivas]# telnet 10.31.38.90 5701 
Trying 10.31.38.90...
Connected to 10.31.38.90.

[trs@10.31.38.90 all_call_query]$ telnet 10.31.38.89 5701 
Trying 10.31.38.89...
Connected to 10.31.38.89.
Escape character is '^]'.

The problem starts from here. In an ideal scenario the nodes must rejoin and reform original 3 node cluster, however even after waiting for half an hour the cluster members are not able to merge. Attached zip archive contains hazelcast DEBUG and diagnostic logs.

Please feel free to let us know in case you require anything else from our side. Thanks.

FYI, we are using Hazlecast IMDG Open Source Version 3.8.3 

[issue-logs.zip](https://github.com/hazelcast/hazelcast/files/1269526/issue-logs.zip)

**Comment by stian-kantega** [comment]
We are observing the same symptom in one of our production environments, is there an ETA on when this issue will be addressed?

**Comment by metanet** [comment]
Hi @RahulSharma21 

I just checked the logs. Here is the member list printed in the logs: 

```
Members [3] {
	Member [10.31.38.91]:5701 - 1642c3f5-446f-4af7-b033-0c9d2519f0b6
	Member [10.31.38.89]:5701 - 27ccbd66-8b1a-4b11-8614-6f3e5f3f800b this
	Member [10.31.38.90]:5701 - a9845714-bc24-42e3-8345-6f24f40b8fdd
}
```
You are breaking the connection between 89 and 90, but it does not lead to a full split. I could not spot 2 clusters. there is still 1 cluster in the logs. The reason is, 91 is alive and reachable for both 89 and 90, so both 89 and 90 accept 91 as their master and don't go anywhere. They are repeatedly trying to reconnect to each other. We don't support all partial network connectivity problems. 

Around 13:36, 89 removes 91 because of heartbeat timeout, but I couldn't see what is wrong with 91 because its logs are missing. This is before you recover the network problem.

**Comment by metanet** [comment]
Btw, we made some major improvements in the clustering system in 3.9. I would strongly recommend you to upgrade your cluster.
