### ISSUE TITLE
DefaultRecordStore#replace methods should load from MapLoader when key not found in storage

### ISSUE THREAD

**Issue by hbrands** [hazelcast/hazelcast#11300]
`DefaultRecordStore#replace(Data key, Object update)`
and
`DefaultRecordStore#replace(Data key, Object expect, Object update)`

look for the current record in the storage only.
If not found in the Storage, they should ask the MapStore (if available) via `MapLoader#load(Data key)` to load the data into memory from the store.

This would be consistent with other methods like
`#remove(Data key)`
`#remove(Data key, Object testValue)`
`#put(Data key, Object value, long ttl)`
`#putIfAbsent(Data key, Object value, long ttl)`

See also forum question here:
https://groups.google.com/forum/#!topic/hazelcast/-_beV0VY7Ms

**Comment by hbrands** [comment]
Well, I would consider this a defect, not an enhancement, but that's my personal opinion ;-)

**Comment by mmedenjak** [comment]
@hbrands might be. I'll remove that tag for now, it will probably get set by the developer working on it.

**Comment by mmedenjak** [comment]
@ahmetmircik do you think this is easy enough to add in 3.9 or will we push this to 3.9.1?
