### ISSUE TITLE
Hazelcast enterprise version required for commercial ?

### ISSUE THREAD

**Issue by veerumallavarapu** [hazelcast/hazelcast#11320]
Hi All,

At present we are using hazelcast for clustering. Can you please let me know should we use enterprise version for production deployment. 

and also please let me know for using hazelcast management center , is there any license terms

**Comment by mdogan** [comment]
Hazelcast IMDG is Apache 2 licensed. You don't need to use enterprise version unless you need enterprise features.

Management Center is available when you buy professional support or enterprise version. See https://hazelcast.com/products/

Please use mail group for questions https://groups.google.com/forum/#!forum/hazelcast.
