### ISSUE TITLE
[query-cache] Client Continuous Query Cache - unexpected behaviours with batchSize and delaySeconds 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#11331]
In Client Continuous Query Cache, it is expected that updates are pushed to cache either after batchSize is reached or delaySeconds passed, whichever comes first. 
But in some cases it does not push any updates. 

I prepared 2 failing tests in the attached class file. I tested with version 3.8.4 and latest master. 
[ClientQueryCacheEventPushTest.java.txt](https://github.com/hazelcast/hazelcast/files/1292341/ClientQueryCacheEventPushTest.java.txt)

**Comment by ahmetmircik** [comment]
Seems attached reproducer `ClientQueryCacheEventPushTest.java.txt` working as expected (eventually). After having a true reproducer we can re-open this issue.
