### ISSUE TITLE
[cache] jcache put TTL, OOME memory leak on backup partitions

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11330]
this run is Map only http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_09_09-11_25_38/ttl/

and the GC charts, http://54.82.84.143/~jenkins/workspace/stable-xx/3.9-SNAPSHOT/2017_09_09-11_25_38/ttl/gc.html do not show a leak pattern

this run is Cache put TTL only http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_09-12_28_57/ttl/

and we see the leak http://54.82.84.143/~jenkins/workspace/stable-x3/3.9-SNAPSHOT/2017_09_09-12_28_57/ttl/gc.html (edited)

and this run is cache put wait get in caches configed with XML expiry-policy-factory

http://54.82.84.143/~jenkins/workspace/stable-x2/3.9-SNAPSHOT/2017_09_09-12_25_32/ttl/

and gain we see the leak pattern

also  we have a OOME hprof, ziped as http://54.82.84.143/~jenkins/workspace/stable-x2/3.9-SNAPSHOT/2017_09_09-12_25_32/ttl/output/HZ/HzMember2HZ/HzMember2HZ.hprof.zip

I have also added an extra assert,  to the Cache TTL test https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/cache/PutTtlWaitGetNull.java asserting that the returned value from cache get i null as expected

**Comment by Danny-Hazelcast** [comment]
notes from slack

this run https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x2/97/console  which uses only cache configured with xml expiry-policy-factory also failed with a hprof
 ```
<cache name="cacheBak1TTL*">
<expiry-policy-factory>
<timed-expiry-policy-factory expiry-policy-type="CREATED" duration-amount="1" time-unit="MILLISECONDS"/>
</expiry-policy-factory>
<in-memory-format>BINARY</in-memory-format>
<backup-count>1</backup-count>
<statistics-enabled>false</statistics-enabled>
<eviction eviction-policy="LFU" max-size-policy="ENTRY_COUNT" size="2000000000"/>
<hot-restart enabled="false">
<fsync>false</fsync>
</hot-restart>
</cache>
```


checked the dump, 9 biggest partition segments so far are for backups. I won’t be checking all of them  But I think Ahmet is right, this is a memory leak on backup partitions

this 0 backup run, http://54.82.84.143/~jenkins/workspace/stable-x2/3.9-SNAPSHOT/2017_09_11-14_07_16/ttl/gc.html  GC is ok


there is some this kind of discrepancy between map and cache.
for the scope of that leak issue, as Matko pointed, i also think it is not an issue for 3.9 due to the needed extra implementation and it is not a newly introduced regression in 3.9, all releases <=3.9 have this weakness.

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-All/52/consoleFull
/disk1/jenkins/workspace/shutdown-All/3.9/2017_10_20-17_17_19/stable/ttl Failed
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by Danny-Hazelcast** [comment]
on 3.10-SANPSHOT

https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x1/188/console

http://54.82.84.143/~jenkins/workspace/stable-x1/3.10-SNAPSHOT/2018_03_15-15_47_45/ttl 
```
output/HZ/HzMember2HZ/HzMember2HZ.hprof
output/HZ/HzMember2HZ/HzMember2HZ.oome
output/HZ/HzMember4HZ/HzMember4HZ.hprof
output/HZ/HzMember4HZ/HzMember4HZ.oome
```

**Comment by taburet** [comment]
AFAIU, caches don't clean up expired items in the background like maps do. Expired items are removed only during the eviction procedure, but eviction is not performed until the configured maximum cache size is reached. In this test case the configured threshold is 2B items.

@vbekiaris @ahmetmircik WDYT should this be fixed or not?

**Comment by taburet** [comment]
Basically all the items in the cache are expired in this test case, but since eviction is not performed this produces OOME.

**Comment by ahmetmircik** [comment]
@taburet, to me, this is an improvement and not an urgent thing for 3.10.

We know that  occupied memory space of a cache can only be controlled by eviction. If we see a leak with eviction, it will a problem. But for the moment, when we try to put an entry to a backup partition, eviction opens space for it, even expired are still there. 

So this issue seems a postponable one.

**Comment by Danny-Hazelcast** [comment]
maybe we can make a RPD for this ?

it would be good to unify the, cache and map ttl behaviour.

**Comment by mmedenjak** [comment]
Slack discussion: https://hazelcast.slack.com/archives/G6EDCRY49/p1505120566000291
I will open a PRD.

**Comment by mmedenjak** [comment]
Created https://hazelcast.atlassian.net/wiki/spaces/PM/pages/508231697/Introduce+background+expiration+task+for+JCache. Please fill in any details which are missing.

**Comment by Danny-Hazelcast** [comment]
I am running this test on

https://github.com/hazelcast/hazelcast/pull/13478 

and its EE counterpart 

so fare I do not see the member oome

**Comment by Danny-Hazelcast** [comment]
happy to close this issue
