### ISSUE TITLE
[map] [map-store] Add option to avoid invoking the MapLoader on IMap.containsKey(k)

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#11342]
A call to `IMap.containsKey(k)` triggers `MapLoader.load(k)`

While this is exactly what the documentation says will happen "_If the key is not found, and if a key is attributed, a MapLoader will then attempt to load the key._", it is an unwanted side-effect

Can an alternative be provided that doesn't trigger the load ?

See also https://github.com/hazelcast/hazelcast/issues/7771

**Comment by mmedenjak** [comment]
Assessed the best way (for the user) to implement this is to add a `IMap.containsKey(Object key, boolean performLoad)` method. Unfortunately I don't see many incentive for implementing this at this point and the `IMap` API is trying to be agnostic to the fact that there is an underlying store (at least for now). If there will be interest in the future, this can be voted and implemented easily.

In a more general sense, we could add some configuration to determine which IMap methods should trigger a call to the map store and which should not. For instance, in addition to determining whether the `containsKey` should call the map store, the `IMap.put` could be configured to avoid calling the map store to return the previously associated value (if there was no value in-memory).

**Comment by mmedenjak** [comment]
Added as PRD which can be included in a future release, closing this issue.

**Comment by vertex-github** [comment]
Did this PRD ever get implemented?  If so, which release did it make it into?
I've come across this a handful of times in the past (one as recently as July 2019) and a recently posted chat-group question reminded me.  Being able to ask the cache if you have a key without triggering the maploader would be useful in some scenarios.

**Comment by mmedenjak** [comment]
Hi @vertex-github ! 
No, it did not get implemented. Yet! :)

**Comment by vertex-github** [comment]
Thanks.  Ive not seen the PRD but something like `queryKey( K key )` or the suggested overload of `containsKey( K key, boolean checkMapstore )` would work.

**Comment by ldwnt** [comment]
It's a pity that this feature is still in the air after 3 years. I thinks it's reasonable for users to check if a key exists in cache or not. It's too heavy to execute the keySet method if too many keys in the map.

**Comment by mmedenjak** [comment]
@ldwnt we just didn't see much interest in it, and on the other hand it present effort to implement it, effort to maintain it, and increases the API surface which is already quite big.
