### ISSUE TITLE
[discovery] MulticastDiscoveryStrategy Improvements

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#11357]
MulticastDiscoveryStrategy requires some improvements. see comments [here](https://github.com/hazelcast/hazelcast/issues/10089#issuecomment-317408313)

Some other improvement ideas:

- [ ] use a shared codebase by discovery spi and native implementation or only use one implementation by keeping both config options. `<multicast>` or `<discovery-strategies>`
- [ ] promote an easier client based multicast discovery option in [hazelcast client config like aws](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/resources/hazelcast-client-config-3.9.xsd#L85)

see https://github.com/hazelcast/hazelcast/issues/10089

**Comment by burakcelebi** [comment]
Closed as internal request
