### ISSUE TITLE
[operation] NPE when response and no response handler

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#11375]
if i use [execute](https://github.com/hazelcast/hazelcast/blob/maintenance-3.x/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationServiceImpl.java#L283) to call an operation and if it times out, [here](https://github.com/hazelcast/hazelcast/blob/maintenance-3.x/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java#L258) operation cannot send response because `responseHandler` is null (assuming caller didn't set it initially). And it leads NPE.

**Comment by pveentjer** [comment]
This only leads to problems for operations that are not following the path of a regular invocation since then an a response handler will be set.

**Comment by pveentjer** [comment]
Making this a 3.9 issue. The error is benign since the execution of the operation is wrapped in a try/catch so on the OperationThread level. So I don't see a good reason to backport; especially since I don't know of occurrences in the wild.
