### ISSUE TITLE
Using PartitionAware in conjunction with EntryProcessor and MapStore

### ISSUE THREAD

**Issue by vinrar** [hazelcast/hazelcast#11376]
We have a Write EntryProcessor, which updates the data. And the HazelcastMapConfig is configured to a MapStore. Whenever we are loading some data, if the data is not present in the map, load() method of MapStore is automatically triggered and data is populated into the map. (load() method calls database and fetches data.)

I'm unable to use PartitionAware and direct the data into a partition as the put method, I guess, is called internally in case of EntryProcessor with the use of MapStore. We don't have control on the partition here.

How do I put the data into a specific partition here(when using an entry processor and MapStore)?

**Comment by ahmetmircik** [comment]
Hi @vinrar,
Making your key `PartitionAware` and calling your updating `EntryProcessor` on the key should be sufficient to have this behavior. `MapLoader` will load data into the partition of your key.

I'm closing this issue now. If you still see the issue after my suggestion, please comment here.
