### ISSUE TITLE
[scheduled-executor] Add possibility to do not serialize a task using IScheduledExecutorService scheduleAtFixedRate

### ISSUE THREAD

**Issue by kadkaz** [hazelcast/hazelcast#11373]
Add possibility to do not serialize a task using `IScheduledExecutorService` `scheduleAtFixedRate`.
I expect to run inner anonymous task's classes using `scheduleAtFixedRate` but I can't.
Inner anonymous classes has reference to outer class which is Spring Bean class and should not be serialized. it would be great to use lambda expressions as well.

So it's so few cases when we can use the current solution.

**Comment by tkountis** [comment]
@kadkaz serialization is needed to transfer the tasks to the executor node. For local executions, see. `scheduleOnMemberAtFixedRate` there is no serialization involved, but you lose the benefit of durability. Does this answer your question?

**Comment by kadkaz** [comment]
Hi @tkountis, I could understand for some cases. But there is another simple scheduled task which are stateless. So just transfer class and not instance. Create interface which will distinguish stateless and state full tasks.

**Comment by tkountis** [comment]
I am presuming you are using default Java's serialization, and that's why it attempts to serialize the parent reference. How about trying using `IdentifiedDataSerializable` this way you rely on your factory to create an instance of that class.

**Comment by kadkaz** [comment]
It makes sense. I will try to do it. thanks.
