### ISSUE TITLE
Performance issue in MapProxyImpl.readFromEventJournal with projection

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#11410]
The application wastes CPU cycles on serialization here:
https://github.com/hazelcast/hazelcast/blob/dfd6aa4e74318ff9153409b52206e6e453096ce3/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L984
when  called from Jet [StreamEventJournalP.poll()](https://github.com/hazelcast/hazelcast-jet/blob/fbe68f865bb6e877d4e9a3863f9c892d14fe36aa/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/StreamEventJournalP.java#L136) repeatedly. 

Example: 10 active SourceProcessors.streamMap() instances generate 20% cpu constant load on empty maps. 
I would expect the projection to be applied only when event arrives.

**Comment by mmedenjak** [comment]
Thanks @lukasherman for reporting it. I saw that and I already have a fix in mind, I just haven't gotten around to making the PR. It will be included in 3.9 GA.

**Comment by tombujok** [comment]
@mmedenjak Matko, could we have this new method added for jet ASAP, where we do not clone?
Jet should clone their projections/aggregations just once instead of cloning in every call. This is a quick fix, the `Immutable` fix we have decided to postpone to 3.9.1 or 4.0.

**Comment by tombujok** [comment]
@mmedenjak ok, we're actually moving it to 3.9.1.

**Comment by mmedenjak** [comment]
I would rather that we avoid cloning on this method in 3.9 as it is invoked repeatedly (unlike other methods accepting projections and aggregations) and does not use the query engine so not the same reasons for cloning may apply.

**Comment by mmedenjak** [comment]
@tombujok I've amended the PR and I think it's simple enough to merge in 3.9 and will allow jet to be more performant when using this API without upgrading to 3.9.1. But if you feel like this is too risky, feel free to move the PR to 3.9.1 as well.
