### ISSUE TITLE
IMap with mapstore has duplicate keys

### ISSUE THREAD

**Issue by tvd12** [hazelcast/hazelcast#11462]
![97043970-8cb5-4bc9-94b8-7dd1b9c127f8](https://user-images.githubusercontent.com/6251901/30903827-4f2cf526-a39a-11e7-9e64-9756cc34c206.jpg)

**Comment by ahmetmircik** [comment]
Hi @tvd12 can you also please share a reproducer + the hazelcast version?

**Comment by tvd12** [comment]
I've used Hazelcast 3.8.1

**Comment by tvd12** [comment]
I'm sorry, my source code is private (my company policy).
I simply create a mapstore and put some value to its (IMap<Integer,JackpotBankInitValue>)

**Comment by tombujok** [comment]
Just share a small reproducer in a separate project - just minimal code that will reproduce it, without any of your company's code.
we don't see this behaviour in our tests.

**Comment by tvd12** [comment]
Mapstore:

```java
 @Override
    public JackpotBankInitValue load(Integer key) {
        return storeService.getInitValue(key);
    }

    @Override
    public Map<Integer, JackpotBankInitValue> loadAll(Collection<Integer> keys) {
    	Map<Integer, JackpotBankInitValue> map = new HashMap<>();
    	for(Integer key : loadAllKeys())
    		map.put(key, load(key));
    	return map;
    }

@Override
    public Iterable<Integer> loadAllKeys() {
        return Lists.newArrayList(0, 1, 2);
    }
```

I use hazelcast client to push value to map:

```java
public void save(JackpotBankInitValue jackpot, Integer id) {
		IMap<Integer, JackpotBankInitValue> imap = hzInstance.getMap(Entities.JACKPOT_BANK_INIT_VALUE);
		imap.set(id, jackpot);
	}
```

**Comment by tvd12** [comment]
It's enough to you?

**Comment by ahmetmircik** [comment]
the map you gave the content [above](https://github.com/hazelcast/hazelcast/issues/11462#issue-260892506) cannot be imap, its internal representation is different. 
From where did you get the map?

**Comment by tvd12** [comment]
I get the map from Hazelcast client.

![a32d05ea-35d5-4b1a-bf3d-83b4f0aa14be](https://user-images.githubusercontent.com/6251901/30905118-1a72e210-a39e-11e7-99e1-394982b70116.jpg)

**Comment by ahmetmircik** [comment]
so you get the map [above](https://github.com/hazelcast/hazelcast/issues/11462#issue-260892506) after calling `imap#getAll` ?

**Comment by tvd12** [comment]
You can see in [https://user-images.githubusercontent.com/6251901/30905190-43d9b192-a39e-11e7-800f-2ddfb75bc2a9.png](above image), I haven't called ```imap#getAll```, I only get ```imap``` from Hazelcast Client instance

**Comment by tvd12** [comment]
```java
```

**Comment by ahmetmircik** [comment]
Seems you need to fix `loadAll` implementation, please use below fixed version:

```
@Override
    public Map<Integer, JackpotBankInitValue> loadAll(Collection<Integer> keys) {
    	Map<Integer, JackpotBankInitValue> map = new HashMap<>();
    	for(Integer key : keys) <-- don't call loadAllKeys(), it causes the duplicates
    		map.put(key, load(key));
    	return map;
    }
```

**Comment by tvd12** [comment]
I fixed that, but I think we shouldn't have a map with duplicated keys.

**Comment by ahmetmircik** [comment]
You are right, I will mark this as an enhancement issue. Let's see what we can have.
Thanks for the report.
