### ISSUE TITLE
IMap.add/remove- EntryListener randomly hangs

### ISSUE THREAD

**Issue by medvand** [hazelcast/hazelcast#11470]
Accordingly to thread dump the problem is in the following:
- Client registers/unregisters entry listeners using IMap.add/remove- EntryListener, this is performed by ClientSmartListenerService which blocks calling thread until registration is done
- Registration itself is performed by ClientSmartListenerService in a single thread by calling ClientInvocation.invokeUrgent and blocking this thread until a response is received from the server.
- For some reason, registration/deregistration response from the server is not received by the client (thread dump shows that ResponseThread is waiting on empty incoming messages queue).
- Therefore all calling threads are blocked on registrations/deregistrations on a period of completing this registration/deregistration procedure. If something goes wrong during that period, entire server hangs forever

**Comment by sancar** [comment]
Hi @medvand , 
ClientSmartListenerService uses single thread to solve the thread safety issues. It could have been multithread but it will be complicated and error prone. Making it single thread potentially means operations will wait for each other, that is expected. 
But registration response not coming from server is not expected. Server will either close the connection, send response or client will detect heartbeat issues and close the connection. These timeouts could be long depending on your configuration. But none of them should cause a hang forever. 
Some defaults timeouts that your invocations may expire after is as following:
"hazelcast.client.invocation.timeout.seconds", 120, SECONDS
"hazelcast.client.heartbeat.timeout", 60000, MILLISECONDS
Do you have a reproducer for us to try ? 
If not, can you share server and client logs of problematic run with us to investigate ?

**Comment by medvand** [comment]
Hi Sancar. The problem occurs randomly, approx. several times a week. We could not write a sample, that reproduces it. Version 3.8.5 Community Edition is used. The following properties were changed:
            <javaoption name="hazelcast.io.thread.count" value="8"/>
            <javaoption name="hazelcast.event.thread.count" value="8"/>
            <javaoption name="hazelcast.event.queue.timeout.millis" value="250"/>
            <javaoption name="hazelcast.operation.thread.count" value="64"/>
            <javaoption name="hazelcast.map.entry.filtering.natural.event.types" value="true"/>
            <javaoption name="hazelcast.max.no.heartbeat.seconds" value="600"/>
            <javaoption name="hazelcast.max.no.master.confirmation.seconds" value="600"/>
            <javaoption name="hazelcast.slow.operation.detector.stacktrace.logging.enabled" value="true"/>
            <javaoption name="hazelcast.slow.operation.detector.log.retention.seconds" value="86400"/>

Our topology: 16 server nodes (8G ram), 4 client nodes (8G ram)

**Comment by sancar** [comment]
Hi @medvand , only known bug of ClientSmartListenerService after 3.8.6 is
https://github.com/hazelcast/hazelcast/pull/11763
which does not seem directly related to your issue. 
This is fixed in 3.9.1 (https://github.com/hazelcast/hazelcast/pull/11763) , if you would like to try. 

If you don't have a reproducer, logs of the client and member could help us to reason about problem. 
I am closing the issue for now. If you have anything new,(logs etc), please share here so that we can identify the problem.
