### ISSUE TITLE
Regression after returning ResultSet instead of SortedQueryResultSet

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#11489]
First see this [group question](https://groups.google.com/d/msgid/hazelcast/0a3f8ed6-2fed-4fc2-8ad1-d7aa1d99a175%40googlegroups.com?utm_medium=email&utm_source=footer).

Problem occurs in [getSortedQueryResultSet](https://github.com/hazelcast/hazelcast/blob/28d373e90dcbbba2dcaabdde33f8349b1dfbef38/hazelcast/src/main/java/com/hazelcast/util/SortingUtil.java#L158) method: 
When returned object is [SortedQueryResultSet](https://github.com/hazelcast/hazelcast/blob/13026001f507ea67deff19157f146b4371d2b6b8/hazelcast/src/main/java/com/hazelcast/map/impl/query/SortedQueryResultSet.java) there is no problem but when it is [ResultSet](https://github.com/hazelcast/hazelcast/blob/28d373e90dcbbba2dcaabdde33f8349b1dfbef38/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/ResultSet.java) failure happens.

**Comment by stevehu** [comment]
@ahmetmircik Thanks for opening the issue here. I wasn't sure if it was an issue or just there is a new way to use the API.

**Comment by tombujok** [comment]
Set milestone to 3.9, will back-port to 3.8.x
