### ISSUE TITLE
Add support for ScheduledExecutorService

### ISSUE THREAD

**Issue by mlaccetti** [hazelcast/hazelcast#115]
Would be delightful to be able to use a distributed ScheduledExecutorService that could guarantee execution of something across a cluster, on each node, etc, etc.

**Comment by isaeedm** [comment]
+1
Is this feature going to be released with Hazelcast 3.5? if yes when will 3.5 be released?

**Comment by crowdconnected** [comment]
+1

**Comment by tazio** [comment]
+1, I need it

**Comment by bwzhang2011** [comment]
@gurbuzali , how does this going on ? could it be integrated in 3.5 and also with support for cron expression.

**Comment by bmcustodio** [comment]
@enesakar any news/progress on this?

**Comment by pveentjer** [comment]
Will be added in 3.6.

**Comment by bmcustodio** [comment]
@pveentjer is there no way for it to make to 3.5?

**Comment by pveentjer** [comment]
I doubt it because 3.5 isn't that far away and we still have a lot of stuff to do.

**Comment by tmazzaro** [comment]
@pveentjer we are evaluating using hazelcast vs other alternatives but we do need this feature. can you please let me know when this will be available in which version? many thanks tom

**Comment by pveentjer** [comment]
It is on the radar for 3.6. We are already working on gathering the requirements for this particular feature.

**Comment by tmazzaro** [comment]
Couldn't find in the website when 3.6 is planned for pls?

**Comment by bwzhang2011** [comment]
@pveentjer, any update with the issue ? hope it could be provided in hz3.5 or else we should do more integration with quartz to make the schedule distributed.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?

**Comment by jamesmmchugh** [comment]
+1

**Comment by sertugkaya** [comment]
+1

**Comment by Petikoch** [comment]
+1

**Comment by edoparo** [comment]
+1

**Comment by logemann** [comment]
it was on the radar a year ago and now its dropped?

**Comment by sertugkaya** [comment]
@logemann it has a milestone set for 3.7

**Comment by marcolattarulo** [comment]
+1

**Comment by olivergg** [comment]
+1

**Comment by drshriveer** [comment]
+1

**Comment by mikemainguy** [comment]
+1

**Comment by danfink** [comment]
+1

**Comment by JAC2703** [comment]
+1

**Comment by wneild** [comment]
+1

**Comment by tommagowan** [comment]
+1

**Comment by cristcost** [comment]
Hi all,
may I ask you please why this feature is being delayed since 4 years?
Is there any technical problem in implementing it or nobody care?
Or maybe it exist a workaround to schedule execution of Runnable etc. with a delay on an Hazelcast Cluster? 

anyway, +1 also for me

(please note the irony: I've discovered the issue just now, "one hour" after it has been postponed again to the next release...)

**Comment by jerrinot** [comment]
Hi @cristcost:

it's easy to implement the happy scenario. However things can become very hairy when you have members joining&leaving a cluster. We are now on the edge of the code-freeze for 3.7 hence it's not possible to have in this release. 

That being said there is VERY visible interests in this feature and I hope to have this included in Hazelcast 3.8 plans.

**Comment by kfatih** [comment]
+1

**Comment by liefra** [comment]
+1

**Comment by MatthiasGerth** [comment]
+1

**Comment by bjoernw** [comment]
+1

**Comment by dasbh** [comment]
+1

**Comment by pedrohsd** [comment]
+1

**Comment by lucasmogari** [comment]
+1

**Comment by oksyque** [comment]
+1

**Comment by jerrinot** [comment]
ScheduledExecutorService is [available](https://github.com/jerrinot/hazelcast/blob/4c046c79f45643a1d972b547dbf71b19b55b16b5/hazelcast/src/main/java/com/hazelcast/scheduledexecutor/IScheduledExecutorService.java#L77-L77) in the latest snapshot version. 

It'll be also included in the Hazelcast 3.8 Early Access which should be released very soon.

**Comment by cristcost** [comment]
Already noted the issue was closed yesterday, 
thank you very much!

**Comment by jerrinot** [comment]
all the credits go to @tkountis ;-)
