### ISSUE TITLE
client side OOME hot-shutdown

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11501]
I have just run this test https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/hot-shutdown/326/console

on `./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.127]:5701 [HZ] [3.9-SNAPSHOT] Hazelcast Enterprise 3.9-SNAPSHOT (20171003 - 2556542, 01f3b43) starting at [10.0.0.127]:5701` (edited)

the first exception was `HzMember1HZ shutdown hzcmd.ops.ClusterShutDown threadId=0 com.hazelcast.core.HazelcastException: java.util.concurrent.TimeoutException: LockClusterStateOp`

but also we have client side OOME,
5 out of the 50 connected clients hit the OOME (edited)

GC charts http://54.82.84.143/~jenkins/workspace/hot-shutdown/3.9-SNAPSHOT/2017_10_03-12_35_44/gc.html

or this could be raised more as a client side issue ?

a 2ND occurrence of the hot-shutdown Client OOME https://hazelcast-l337.ci.cloudbees.com/view/hot-restart/job/hot-shutdown/329/console

member config using
```
<property name="hazelcast.heartbeat.failuredetector.type">phi-accrual</property>
<property name="hazelcast.max.no.heartbeat.seconds">300</property>
<property name="hazelcast.heartbeat.interval.seconds">3</property>
```

http://54.82.84.143/~jenkins/workspace/hot-shutdown/3.9-SNAPSHOT/2017_10_03-17_36_41/gc.html

only 1 out of the 50 clients hit the OOME
./output/HZ/HzClient20HZ/

http://54.82.84.143/~jenkins/workspace/hot-shutdown/3.9-SNAPSHOT/2017_10_03-17_36_41/output/HZ/HzClient20HZ/HzClient20HZ.hprof

**Comment by Danny-Hazelcast** [comment]
![](https://files.slack.com/files-pri/T024PDR4H-F7CL2PUJZ/screen_shot_2017-10-03_at_17.33.19.png)

**Comment by mmedenjak** [comment]
The heap dump indicated that the `LoadTracker#tasks` queue was full with tasks (in one case there were 7577 instances of io balancer tasks in queue). This queue is usually cleaned up every `ClientProperty#IO_BALANCER_INTERVAL_SECONDS`

**Comment by mmedenjak** [comment]
Logs from first run: [logs.tar.gz](https://github.com/hazelcast/hazelcast/files/1354843/logs.tar.gz)
Logs from second run: [logs2.tar.gz](https://github.com/hazelcast/hazelcast/files/1354844/logs2.tar.gz)
Heap dump of OOME on second run: [dump.tar.gz](https://github.com/hazelcast/hazelcast/files/1354845/dump.tar.gz)

**Comment by sancar** [comment]
In the second run, there are 3000 channel reader/writer in the heap. Each having a full buffer containing 131000 byte.
That is making total of 380 mb which occupies the whole heap .

**Comment by pveentjer** [comment]
I'll have a look at it to figure out why the client connections are retained. Also normally the io balancer should not be active on the client because there is only 1 input thread and 1 output thread; so there is nothing to balance. Perhaps that is the problem??

**Comment by pveentjer** [comment]
I think it is caused because the iobalancer is disabled (since there is nothing to balance). But still AddHandlerTask tasks are created; but never processed. These tasks are put on a queue and contain a reference to the connections.

**Comment by pveentjer** [comment]
The fix is very straight forward and solves the problem for client and server; if the server would ever be configured with a single thread.
