### ISSUE TITLE
hazelcast-all built from sources contains minimal-json as a dependency

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11524]
When hazelcast is built locally by `mvn clean install`, then resulting `hazelcast-all-[version].pom` (in local repo) wrongly contains dependency on `minimal-json`. This happens even the minimal-json classes are correctly included and relocated by Maven shade plugin (done in hazelcast module).

When the hazelcast-all module is built afterwards (`mvn install -rf :hazelcast-all`), then the resulting POM doesn't contain the minimal-json dependency. 

My guess is, it could be caused by Maven Reactor resolving dependencies upfront and not updating it after reduced POM for a module is created. 

The hazelcast-all POMs released in Maven central have correct dependencies (i.e. without the minimal-json).

**Comment by mdogan** [comment]
I guess, this issue is resolved after the change https://github.com/hazelcast/hazelcast/pull/13405.

**Comment by kwart** [comment]
@mdogan You are right. Thanks for noticing.
Closing.
