### ISSUE TITLE
data loss on split brain and cluster reform

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11542]
starting with 6 node cluster,  
validate data loaded
split into two 3 node clusters
wait 5 mins
heal network
wait till cluster size is 6
wait till cluster is safe
validate data loaded  -->  Data loss

i assert that the full data set for the tests, can fit into a 3 node cluster, in the first place

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-data-loss/3/console

http://54.82.84.143/~jenkins/workspace/split-data-loss/3.9-SNAPSHOT/2017_10_09-14_34_25/

**Comment by tombujok** [comment]
@metanet promised to triage it today in the evening.

**Comment by mdogan** [comment]
@Danny-Hazelcast: Currently we don't support cluster merge for HD data structures. Can you please run only using on-heap in memory format?

**Comment by tombujok** [comment]
@Danny-Hazelcast OK, so it's a wrong expectation for HD memory. Plz reopen in case of on-heap failure.

**Comment by Danny-Hazelcast** [comment]
when i make a cluster split of
1 node cluster and a 5 node cluster,  we see no data loss

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-data-loss/6/console

**Comment by Danny-Hazelcast** [comment]
when i split the cluster 
2 node cluster and a 4 node cluster,  we see data loss
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-data-loss/7/console

**Comment by mdogan** [comment]
@Danny-Hazelcast: make sense, because 5 member cluster will recover data using 1st backup.

**Comment by Danny-Hazelcast** [comment]
I have an unusual results, from the split data loss test,

when i run with only on heap map / cache,  the test will pass.
when running with only HD, we have data loss as expected.
but
when running with HD and on heap, we see data loss, for the heap based map and cache  also

`mapBak1HD_data-loss key 8 value null`  &&  `mapBak1_data-loss key 9 value null`

so i appears that some how,  the data loss of HD effects / "causes"  
data loss in heap based structures,  which seams odd.

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-data-loss/11/console

**Comment by metanet** [comment]
I think you are waiting for for "cluster safe" status after the sub-clusters merge. However, the "cluster safe" mechanism does not check if there are still data entries being merged. You should make eventual assertions.

**Comment by Danny-Hazelcast** [comment]
ok, waiting for cluster to come to MERGED state,  
results in only data loss from HD as expected
