### ISSUE TITLE
XSD should work independently of hazelcast-spring.jar

### ISSUE THREAD

**Issue by crazyguyonabike** [hazelcast/hazelcast#11577]
Since the hazelcast-spring.xsd is at https://hazelcast.com/schema/spring/hazelcast-spring-3.9.xsd but the namespace is http://www.hazelcast.com/schema/spring you can't get it to load. 

If you try to load it all with http you get:
```
org.xml.sax.SAXParseException; systemId: http://hazelcast.com/schema/spring/hazelcast-spring-3.9.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
```
If you try to load it all with https you get:
```
org.xml.sax.SAXParseException; systemId: https://hazelcast.com/schema/spring/hazelcast-spring-3.9.xsd; lineNumber: 23; columnNumber: 47; TargetNamespace.1: Expecting namespace 'https://www.hazelcast.com/schema/spring', but the target namespace of the schema document is 'http://www.hazelcast.com/schema/spring'.
```

If you try and mix them i.e.
       xmlns:hz="http://www.hazelcast.com/schema/spring"
and 
       http://www.hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.9.xsd

Then you get:
```
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unable to locate Spring NamespaceHandler for XML schema namespace [http://www.hazelcast.com/schema/spring]
```

**Comment by mesutcelik** [comment]
Hi @crazyguyonabike ,

The same question is already answered by @googlielmo  in Google Groups. 

Can you please follow-up in this [link](https://groups.google.com/d/msg/hazelcast/WiCASedVvFo/zQECZAcSAgAJ) ?

**Comment by crazyguyonabike** [comment]
I created the issue because I think the errors with XSD are separate from the workaround. If the .jar is not present, the errors should be more related to classes not found. Since you are serving the XSD over HTTPS, the namespaces in the both the XSD on the web and the XSD in the .jar are incorrect. So this issue is to fix the namespaces.
