### ISSUE TITLE
Feature Request: Plugin for Eclipse/InterlliJ for generating hazelcast portable

### ISSUE THREAD

**Issue by pmanvi** [hazelcast/hazelcast#1157]
Writing serializers for all the cached objects with portable is a tedious and error prone task.
It will be greatly helpful to have plugin for all major IDEs (Eclipse, IntelliJ & NetBeans) to auto generate the same. Also it will be help to generate the Query DSL for distributed query for given filter object.

**Comment by mdogan** [comment]
See https://github.com/asimarslan/hazelcast-tools
