### ISSUE TITLE
Hazelcast takes up a lot of memory

### ISSUE THREAD

**Issue by Zeous9** [hazelcast/hazelcast#11591]
Hi, i want to know will it use hard disk space,  if memory isn't enough ???
Thanks in advance,
Rich

**Comment by Donnerbart** [comment]
Hazelcast is an In-Memory Data-Grid (IMDG). It's purpose is to hold all data in memory. We don't persist or overflow data to disk at the moment. We have HotRestart features, which allow a quick restart of Hazelcast, but still all data has to fit into the memory.

**Comment by mmedenjak** [comment]
I'm closing this as it isn't an issue. Please post questions on the hazelcast google groups: https://groups.google.com/forum/#!forum/hazelcast
