### ISSUE TITLE
Doing rolling upgrade without enterprise key should produce better error message

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#11602]
When you try to do rolling upgrade with OS version (by accident or because you just missed it), the rolling upgrade fails with:
`Reason of failure for node join: Joining node's version 3.10.0 is not compatible with 3.8.6`
Since rolling upgrade is an enterprise feature, it would be nice to provide better error message that would guide you in the right direction.

**Comment by Donnerbart** [comment]
I'm having a look at this right now. I have two improvements in mind:
* if the versions are rolling upgrade compatible (just one minor version difference), we should print that this requires EE
* if the versions are not rolling upgrade compatible, we should inform the user about that

**Comment by Holmistr** [comment]
+1
