### ISSUE TITLE
Use create destroy test under kill / stable conditions OperationTimeoutException / MemberLeftException / NativeOutOfMemoryError

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11618]
http://54.82.84.143/~jenkins/workspace/kill-All/3.9/2017_10_17-00_14_33/stable/destroy/create-use-destroy
`com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException` queryCache thrown the generic exception instead and wraps member left

Danny Conlon [4:50 PM] 
http://54.82.84.143/~jenkins/workspace/kill-All/3.9/2017_10_17-00_14_33/stable/destroy/create-use-dist-destroy
hits `.NativeOutOfMemoryError`

but stable version http://54.82.84.143/~jenkins/workspace/stable-All/3.9/2017_10_16-16_56_44/destroy/create-use-dist-destroy
got a `com.hazelcast.core.OperationTimeoutException`

**Comment by mmedenjak** [comment]
@Danny-Hazelcast can you test with more metadata space?

**Comment by tkountis** [comment]
@Danny-Hazelcast can you do another run here, its been quite some time, we should try the latest code with the suggestions above.

**Comment by pveentjer** [comment]
@Danny-Hazelcast please rerun. The resources listed in the opening message are gone; so there is not much that can be done with it.

Also I don't see the added value of destroy tests since we know that destroying things in HZ is not possible since we automatically recreate.

**Comment by Danny-Hazelcast** [comment]
I have re-run https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x1/195/console
and I hit any issues.   the GC also looked good for members and clients.

i am closing this issue
