### ISSUE TITLE
aggregate shutdown java.lang.IllegalStateException node failed to start

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11616]
this test https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-aggregate/  failed 2 time, to day 17th  with `java.lang.IllegalStateException: Node failed to start! `

**Comment by mdogan** [comment]
A 2nd member is being started on Hz Member4:
```
Oct 17, 2017 9:20:27 AM com.hazelcast.system
INFO: [10.0.0.236]:5702 [HZ] [3.9] Hazelcast Enterprise 3.9 (20171016 - f9e55c6, 4e89e6d) starting at [10.0.0.236]:5702
...

Oct 17, 2017 9:25:52 AM com.hazelcast.cluster.impl.TcpIpJoiner
WARNING: [10.0.0.236]:5702 [HZ] [3.9] Couldn't join to the master: [10.0.0.236]:5701
Oct 17, 2017 9:25:52 AM com.hazelcast.instance.Node
SEVERE: [10.0.0.236]:5702 [HZ] [3.9] Could not join cluster in 300000 ms. Shutting down now!
Oct 17, 2017 9:25:52 AM com.hazelcast.core.LifecycleService
INFO: [10.0.0.236]:5702 [HZ] [3.9] [10.0.0.236]:5702 is SHUTTING_DOWN
```

http://54.82.84.143/~jenkins/workspace/shutdown-aggregate/3.9/2017_10_17-12_13_59/output/HZ/HzMember4HZ/out.txt

Is this 2nd member expected on the same machine?

**Comment by Danny-Hazelcast** [comment]
I am shutting down each member of the cluster,
and then i am restarting the hazelcast instance inside each of the jvm's

**Comment by Danny-Hazelcast** [comment]
fixed shutdown and restart 
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-aggregate/193/
