### ISSUE TITLE
[lock] add logging to ILock operations

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#11622]
Currently `ILock` operations don't appear to be logged at any level.  It would be very helpful if I could enable diagnostic log output, with the log line containing the name of the ILock, the operation (`create`, `lock`, `unlock`, `destroy`) and the usual timestamp, thread ID etc.

This would not only help diagnose locking problems (order of operations etc), but it would also help expose locks that are not being destroyed after use.

**Comment by IgnatBeresnev** [comment]
Any hope you'll implement it for map-based locking? `IMap.lock()`

**Comment by mmedenjak** [comment]
@IgnatBeresnev no plans yet. Feel free to open a new issue for it.
