### ISSUE TITLE
Keep start scripts to run in foreground

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11625]
The `bin/start.sh` sends the java process (`com.hazelcast.core.server.StartServer`) to background, but it keeps logging messages to standard streams (stdout/stderr).  This inconsistency is confusing for users as the script itself finishes.

Standard script behavior is:
* either keep the process running in the foreground and let the user decide when to send it to background;
* or run the server in background and also redirect its output to a log file.

**Suggestion to improvement**
Keep the script running in the foreground, handling correctly signals (`SIGTERM`). And let the user decide when/if it should be sent to the background.

**Comment by mmedenjak** [comment]
This issue may be outdated with the focus on the hazelcast-member tool.

**Comment by alparslanavci** [comment]
Fixed by #15934
