### ISSUE TITLE
Hazelcast IMap performance

### ISSUE THREAD

**Issue by jevel0per** [hazelcast/hazelcast#11638]
i use the hazelcast 3.8.6. There is a IMAP{Key, Value} with next settings:

```
mapConfig.setBackupCount(5);
mapConfig.setReadBackupData(true);

```
the Key is

```
long userId;
long contentId;
```
also there are 6 nodes where the data is. As far as i understand according the setting each node will be have all data. Such way i turn a distributed map to a replicated map to increase speed of get operations and don't do networking calls.

let's image i need get all data for user by id. in usual mode i would write next code:

```
EntryObject eo = new PredicateBuilder().getEntryObject();
Predicate predicate = eo.key().get("this.userId").equal(userId);
map.values(predicate).stream().map(.....)
```
this code will be executed on all nodes and result will be returned to node which make the call. Am i right understding that in case of the settings "setReadBackupData(true)" the request won't be send to other nodes and all data will be found on node wich make this request? or in that case to avoid networking calls i just should use something like this:

```
map.entrySet().stream()
.filter(entry->entry.getKey().getUserId().equals(userId))
.map(.....)
```
What should I do to get all the table records without network calls?
I don't wanna use the ReplicatedMap because of want to have other features IMap.

thanks.

**Comment by ahmetmircik** [comment]
Hi @jevel0per,
 
No, only `IMap#get` tries to read data from backup, other operations will be distributed calls. 
Seems you can also use replicated map for this purpose.

PS: Please use hazelcast group to ask this kind of questions. https://groups.google.com/forum/#!forum/hazelcast

Thanks.
