### ISSUE TITLE
Hazelcast Managerment Center 3.9 Release Date

### ISSUE THREAD

**Issue by bhagathk** [hazelcast/hazelcast#11659]
We noticed that Hazelcast IMDG 3.9 was released yesterday but not the management center. Is there a date for its release?

**Comment by mmedenjak** [comment]
The management center has it's own release cycle. @mesutcelik do you know the release date for the mancenter?

P.S. Please ask questions on the google groups or gitter channel if you are not experiencing any issue

**Comment by mesutcelik** [comment]
Hi @bhagathk ,
We are planning to release it this week.

**Comment by bhagathk** [comment]
Thanks Guys.
