### ISSUE TITLE
Spring Integration with Hazelcast MapStore

### ISSUE THREAD

**Issue by bhagathk** [hazelcast/hazelcast#11656]
I am trying to integration Spring and Hazelcast with Mapstore Implementation. I am not able to autowire the JdbcTemplate in the Mapstore class. 
1.) Is there a way I can actually autowire my repository in the MapStore Class?

```java
public class DefaultNoSQLMapStore implements MapStore<String,Object>{
	@Autowired
	private JdbcTemplate jdbcTemplate;
```	

Here, jdbcTemplate results a null value.

As a work around I am able to implement mapstore and use the jdbcTemplate using the 
MapStoreLifeCycleSupport and init() method to load instantiate jdbcTemplate and use it in the MapStore.

Also I have seen an example where we add hazelcast as a bean in the spring configuration xml and get the jdbc template using applicationContext.getBean() method.
2.) If this is the only solution to actually Integrate Hazelcast Mapstore with Spring then 
Is there a way to have Hazelcast.xml seperated from spring configuration xml and still achieve this?

**Comment by vbekiaris** [comment]
@bhagathk you should be able to get spring-managed beans injected in your `MapStore` implementation by annotating your implementation as `@SpringAware`. See [documentation here](http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#enabling-springaware-objects) and the [sample code here](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/springaware-annotation)

**Comment by bhagathk** [comment]
@vbekiaris  In this Documentation, the hazelcast is a bean in the spring configuration xml. I want to have the hazelcast.xml seperate from the spring configuration and should be able to achieve this functinality as I explained above. Is it possible?

**Comment by bhagathk** [comment]
@vbekiaris Any Information related to my Above Question?

**Comment by mesutcelik** [comment]
Hi @bhagathk ,
It is actually inconvenient not to use spring configuration because it is an option we offer to keep all configuration in the same place. 

If you want to use hazelcast.xml seperately, here are the options you can use in your application
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#checking-configuration

**Comment by bhagathk** [comment]
Hi @mesutcelik,
I am actually looking to use two files Spring application-context.xml and Hazelcast.xml. Where the application-context.xml will be able to read the hazelcast.xml we have provided. So that Hazelcast will be part of the Spring Configuration.

**Comment by mesutcelik** [comment]
If you are using hazelcast.xml based on [hazelcast-config.xsd](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-config-3.9.xsd) then what you ask is not possible.

If it is based on[ hazelcast-spring.xsd](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.9.xsd) then you just need to import it into applicationContext.xml as below.


`<import resource="classpath:spring_xsd_based_hazelcast.xml" />`

**Comment by bhagathk** [comment]
We are able resolve the issue by using Spring's ApplicationContextAware to get the Application Context. Using this Application Context we are getting the JBDC Template in the mapstore class.
