### ISSUE TITLE
[query-cache] QueryCache on an IMap that is subsequently destroyed and recreated doesnt work

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#11666]
Create a QueryCache on an IMap (which triggers the IMap creation).
Destroy the IMap.
Get the IMap by name again.
Get the QueryCache from the IMap.

HZ returns a seemingly valid QueryCache.

Update the IMap.

The update event never gets fired to the QueryCache.

I expect either the QueryCache to get the event, or the QueryCache should be destroyed when the 1st IMap is destroyed, and any attempts to retrieve it after that fact should result in a `null`

**Comment by ahmetmircik** [comment]
@vertex-github Please try with 3.8.6, this seems fixed there, if not, we can re-open this issue.

**Comment by vertex-github** [comment]
Can you point to a changeset between 3.8.1 and 3.8.6 that fixes this?

**Comment by ahmetmircik** [comment]
It should be this according to my tests: https://github.com/hazelcast/hazelcast/pull/10168

Did have a chance to try with 3.8.6?

**Comment by vertex-github** [comment]
OK, I tested with 3.8.6 (along with all versions in between 3.8.1 and up).  The behavior is different with 3.8.6.
