### ISSUE TITLE
Let NetworkConfig.setPortCount() return the NetworkConfig instance

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11669]
The `NetworkConfig.setPortCount(int)` doesn't return `this` instance compared to other setter methods in the class.

So it can't be used in the middle of a fluent API network configuration.

**Comment by mmedenjak** [comment]
There was already a discussion on fixing the fluent API for other caches. See discussion: https://github.com/hazelcast/hazelcast/pull/11107
