### ISSUE TITLE
Improve group password configuration

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11667]
There is an ongoing effort related to removing group password from Hazelcast configuration. The password is not checked anymore during member joins. This should be also reflected in XML configurations and XSD element descriptions.

**Suggestion for improvement:**
* remove the `<password>` element from `hazelcast-default.xml`, `hazelcast-full-example.xml` (fix also the related comment) and `hazelcast-client-full.xml`
* update `password` element description in  `hazelcast-config-3.10.xsd` and `hazelcast-client-config-3.10.xsd`. Add there a note that this is deprecated and not used for join checks anymore.

**Comment by nlwillia** [comment]
What's the alternative if you don't care about fine grained security (an Enterprise feature), but do want to prevent just any process from being able to connect to your cluster (as a member or as a client)?

**Comment by kwart** [comment]
I've realized the the client connections still check the group passwords. New issue #11867 was reported to fix it

**Comment by ramtech123** [comment]
Thanks @mmedenjak. That helps 👍

**Comment by ramtech123** [comment]
Just verified the behavior of `hazelcast.application.validation.token` - new member having same group name but a non-matching validation token will not be able to start itself, as it will be forcefully shutdown. So, group name is the only field which will let two (or more) different nodes run as separate independent clusters.

`Node could not join cluster. A Configuration mismatch was detected: Incompatible 'hazelcast.application.validation.token'! expected: test.validation.token1, found: test.validation.token2 Node is going to shutdown now!`

**Comment by sancar** [comment]
Client side is also fixed by https://github.com/hazelcast/hazelcast/pull/13597 in 3.11.
Related documentation will be addressed with https://github.com/hazelcast/hazelcast-reference-manual/issues/590 in 3.11. 
Moving this to 3.11 and closing the issue since there is nothing left to do on main repo.
