### ISSUE TITLE
How to use variables in hazelcast.xml instead of hardcoding?

### ISSUE THREAD

**Issue by sshorkey** [hazelcast/hazelcast#11676]
I'm running Hazelcast in a docker swarm running on a set of AWS EC2 nodes. Because of the various limitations of Hazelcast in docker, I need to manually set the bind address (<public-address>whatevertheipis:5701</public-address>) in the hazelcast.xml file. This is a huge PITA however, as it means I have to basically have a separate hazelcast.xml file, separably configured for each node. This presents a huge barrier to autoscaling and automation.

What I'm trying to do is find a way of instead of having a separate hazelcast.xml on each container, having a single hazelcast.xml file used for all containers, with the public-address value set to an environment variable instead, so I can simply run an "export PUBLICIP=whatever" on each new node as its spun up.

However, trying to set <public-address>${PUBLICIP}:5701</public-address> in the hazelcast.xml doesn't work, it complains of syntax errors and shuts down. How do I do this?

**Comment by jerrinot** [comment]
hi @sshorkey,

can you try to start your JVM with this parameter `-DPUBLICIP=$PUBLICIP` ? I believe Hazelcast does not use environment variable when resolving placeholder, but passing a system property should work. 

Alternatively - in Hazelcast 3.9 you can use this SPI and Hazelcast will call your own Java code to select its public IP: https://github.com/hazelcast/hazelcast/blob/3cede71cad1fe87312f0901ff77f903ed2d4383d/hazelcast/src/main/java/com/hazelcast/config/MemberAddressProviderConfig.java#L38

**Comment by sshorkey** [comment]
Worked, thanks!
