### ISSUE TITLE
Node Initialization order is wrong

### ISSUE THREAD

**Issue by Glamdring** [hazelcast/hazelcast#11681]
While trying to setup Hazelcast on AWS I got a strange NullPointerException:

```
Caused by: java.lang.NullPointerException: null
        at com.hazelcast.partition.membergroup.SPIAwareMemberGroupFactory.createInternalMemberGroups(SPIAwareMemberGroupFactory.java:59)
```

Digging a little bit lead me to the Node class, line 209. There the PartitionService is initialized with the yet-uninitialized node. A few calls up the stack, through PartitionStateManager, there's a call to node.getDiscoveryService() which at this stage returns null and hence the SPIAwareMemberGroupFactory is initialized with a null discovery service. This is rather unfortunate, as it means practically Hazelcast is not working in this setup (SPI discovery).

**Comment by jerrinot** [comment]
@Glamdring: thanks for reporting this, much appreciated!
just to double-check: what's Hazelcast version is this?

**Comment by Glamdring** [comment]
@jerrinot 3.8.6

**Comment by jerrinot** [comment]
@Glamdring: you are right, it's a bug, once again thanks for reporting it! Let me see what we can do about it. 

What discovery implementation are you using? I have yet to write a test for this but I reckon as a workaround you could just change your [PartitionGroupConfig](https://github.com/jerrinot/hazelcast/blob/b1c425e8598cde123ab11493b4dc7896dbfec15e/hazelcast/src/main/java/com/hazelcast/config/PartitionGroupConfig.java#L153) not use use the SPI for creating member groups. The SPI will be still use for discovery, but it won't be used for creating member groups. You could use e.g. [PER_MEMBER](https://github.com/jerrinot/hazelcast/blob/b1c425e8598cde123ab11493b4dc7896dbfec15e/hazelcast/src/main/java/com/hazelcast/config/PartitionGroupConfig.java#L142) strategy.

**Comment by Glamdring** [comment]
@jerrinot I'm using hazelcast-aws (https://github.com/hazelcast/hazelcast-aws)

**Comment by Glamdring** [comment]
btw you may spot a slight issue with my config - config.getProperties().put("...", true) is putting a boolean and not a string. And that check later fails silently. What's the reason for exposing the properties? You are allowing users of the API to violate the restrictions that the config.setProperty(..) has imposed

**Comment by Glamdring** [comment]
Switching to ZONE_AWARE worked; previously it failed because of the boolean vs string property
