### ISSUE TITLE
IAtomicLong's addAndGet() method is causing OperationTimeoutException 

### ISSUE THREAD

**Issue by Mohit-Tiwari** [hazelcast/hazelcast#11706]
i have a multithreaded distributed env, where different threads from separate jvms are updating the IAtomicLong object stored in the hazelcast cluster. 
i seem to get this error sometimes: 
com.hazelcast.core.OperationTimeoutException:[ATOMIC_NUMBER_ADD_GET] Operation Timeout (with no response!):0 

what does this error mean? 
is it safe to use IAtomicLong in such a set up? 

i am using 3.7.1 version of hazelcast with java 8.

**Comment by pveentjer** [comment]
Can you give the whole exception? It is unlikely that the actual addAndGet is causing problems; it is more likely that you have either networking problems or the operation threads are getting stalled.

Can you upgrade to HZ 3.9; contains a lot of bug fixes and improved exceptions for operation timeouts.

**Comment by tkountis** [comment]
@Mohit-Tiwari unless you could share detailed logs of this error, or a reproducer, its very hard to troubleshoot it or even comment on it. Would you be able to share some detailed logs of all boxes at the time of the discrepancy?

**Comment by Mohit-Tiwari** [comment]
Hi Peter,

Thanks for your response. actually this issue is very rare, i am also
trying to reproduce it but no success yet.
definitely i will share the detailed logs if the issue will occur again. is
there any other suggestion/alternative
on this besides of upgrading to 3.9.

**Comment by pveentjer** [comment]
When upgrading to 3.9, also enable diagnostics

http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Diagnostics/Enabling_Diagnostics_Logging.html

It will contain data regarding networking (and networking problems) and regarding slow operations.

**Comment by metanet** [comment]
As others said, I think we don't have much to do about this issue without having more insight. Closing for now and we can re-open it later on if needed.
