### ISSUE TITLE
ReplicatedMap API Doc reflects Member only behaviour

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast#11707]
ReplicatedMap Api Doc contains member only behaviours/requirements that client cannot meet  due to its technical difference.

Most of the data providing methods like `Collection<V> values();` promise to return a lazy data set backed by the map where changes to the map might be reflected in the set.

Members returns "a lazy set view of the mappings"  as in api doc,
but client returns "a clone of the mappings" instead. 

As all data exists on all members, such a behaviour easily provided. Whereas client provide simple proxy of a member and always return a clone of data.

The documentation should be review with this in mind.

**Comment by sancar** [comment]
@asimarslan And member documentation is also not correct. It seems that server side implementation is refactored later and does not return lazy list/set anymore.
