### ISSUE TITLE
Exception in ResponseThreadRunnable causes REST API to fail

### ISSUE THREAD

**Issue by paykin** [hazelcast/hazelcast#11722]
When there is an exception while processing single command, entire thread got killed. It causes unrecoverable condition when system does not process any incoming REST command and causing memory leak (incoming commands are accumulated in blockingQueue).
The only resolution is restart of entire system.

In our case heavy system swapping caused this situation to occur. Here is the full stack trace (for version 3.6.2):

```
Exception in thread "hz.MY_CLUSTER.ascii.service.response" java.lang.NullPointerException
at com.hazelcast.internal.ascii.TextCommandServiceImpl$ResponseThreadRunnable.run(TextCommandServiceImpl.java:379)
at java.lang.Thread.run(Thread.java:745)
```

Here is the PR that fixes it: https://github.com/hazelcast/hazelcast/pull/11721

**Comment by jerrinot** [comment]
actually I am not sure if just catching/logging the exception is the right thing to do. in this case it would just a hide an issue with a write handler initialization.

**Comment by paykin** [comment]
@jerrinot you may want to change behavior during initialization, but during runtime you do not want that single exception will make entire system non-functional without any option to recover (full restart does not count).

**Comment by jerrinot** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/12481
