### ISSUE TITLE
Coverity - resource leak in client's ProxyManager

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11751]
The method `ProxyManager.getOrCreateProxy()` creates a `ClientProxy` even if it's not used - i.e. when it already have a `ClientProxyFuture` instance in the `proxies` Map:

```java
final ClientProxy clientProxy = createClientProxy(id, factory);
proxyFuture = new ClientProxyFuture();
final ClientProxyFuture current = proxies.putIfAbsent(ns, proxyFuture);
if (current != null) {
    return current.get();
}
```

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29225745&defectInstanceId=5757191&mergedDefectId=202188&eventId=5757191-18

**Comment by sancar** [comment]
@kwart 
This design in intentional. 
Extra proxy creation only happen when there is concurrent calls to this method. 
In other cases, the proxies map is checked a few lines before as follows:
```
ClientProxyFuture proxyFuture = proxies.get(ns);
        if (proxyFuture != null) {
            return proxyFuture.get();
        }
```

**Comment by kwart** [comment]
Is there a reason why not to move the `clientProxy = createClientProxy(id, factory);` few lines down to only  happen if `current==null`?

**Comment by sancar** [comment]
I took a second look. Yes, you are right. we can move down client proxy creation. 
I was assuming that clientProxy is used when creating ProxyFuture. And we can not move the proxyFuture .
