### ISSUE TITLE
Coverity - RestartingMemberIterator uses volatile field 

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11750]
Field `retryCounter` is not atomically updated in the `RestartingMemberIterator.retry(Set)` method.

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29221847&defectInstanceId=5757129&mergedDefectId=202210

**Comment by Donnerbart** [comment]
FindBugs would also complain about this, but there is a suppression with a justification for this one:
```
    @SuppressFBWarnings(value = "VO_VOLATILE_INCREMENT",
            justification = "retryCounter is accessed by multiple threads, but never concurrently")
```
I has been added by @jerrinot, so maybe he can confirm this here.

**Comment by kwart** [comment]
Thanks @Donnerbart for letting me know. Coverity reports more of these problems. I'll look for the `@SuppressFBWarnings` annotation next time and mark  such records as false positives in the coverity.
