### ISSUE TITLE
Coverity - dereference null return value - NearCachedClientCacheProxy.onInitialize()

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11762]
The call `clientConfig.getNearCacheConfig(name)` may result in `null` value in `com.hazelcast.client.cache.impl.NearCachedClientCacheProxy.onInitialize()`. 
The value is then dereferenced without a null-check in  `checkNearCacheConfig();` call.

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29225645&defectInstanceId=5757182&mergedDefectId=202161&eventId=5757182-15

**Comment by sancar** [comment]
@kwart 
This proxy is created only when a related nearcache config is present. This guarantees that `getNearCacheConfig` in `onInitialize ` will never return `null`. 
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheProxyFactory.java#L50

I admit that It took me a couple of minutes to figure it out. An automized tool can give false alarm easily.

**Comment by kwart** [comment]
Thanks for investigation @sancar , I'll mark it as false positive in the Coverity.
