### ISSUE TITLE
Coverity - dereference null return value - ClientConnectionManagerImpl.encodeAuthenticationRequest()

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11767]
The call `cr.getPassword()` may return `null` value in the `com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.encodeAuthenticationRequest(boolean, SerializationService, ClientPrincipal)` method. The value is then dereferenced without a `null` check in `ClientAuthenticationCodec.encodeRequest` call:

```java
ClientAuthenticationCodec.encodeRequest(cr.getUsername(), cr.getPassword(), uuid, ownerUuid, asOwner, ClientTypes.JAVA,
    serializationVersion, BuildInfoProvider.getBuildInfo().getVersion());
```

The `encodeRequest()` calls `ParameterUtil.calculateDataSize(String string)` in which `string.length()` is called.

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29225738&defectInstanceId=5757169&mergedDefectId=202151

**Comment by sancar** [comment]
`UsernamePasswordCredentials` constructor does not except null values of password. 
The empty constructor is not used anywhere except portable factory. 
`getPassword` can not return null values but I except that it looks confusing
```
public String getPassword() {
        if (password == null) {
            return null;
        } else {
            return bytesToString(password);
        }
    }
```
I think it is safe to simplify this to 
```
public String getPassword() {
            return bytesToString(password);

    }
```

**Comment by kwart** [comment]
The problem can cause the fact the `UsernamePasswordCredentials` class is part of a public API. So even if we ourselves don't use `null` passwords, we do not force user to do the same.

**Comment by sancar** [comment]
@kwart 
I don't think `UsernamePasswordCredentials` meant to be part of public api. But it is already in public.

Actually we are forcing to use not null password because of current implementation via NPE. And also we want to force it. How about if we throw a IllegalArgumentException when password is null so that user won't see NullPointerException but a well defined exception ?

**Comment by sancar** [comment]
@kwart I have just updated the pr with our `Preconditions.checkNotNull` which throws NPE.

**Comment by kwart** [comment]
:+1:
