### ISSUE TITLE
Coverity - Dereference null return value - ClientConnectionManagerImpl.InitConnectionTask.run()

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11771]
The `addressTranslator.translate(target)` in `com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.InitConnectionTask.run()` may return `null`. The returned value is used as an argument for `createSocketConnection(Address)` which uses the value without a null-check.

https://scan4.coverity.com/reports.htm#v32322/p13030/fileInstanceId=29225738&defectInstanceId=5757171&mergedDefectId=202185

**Comment by sancar** [comment]
This is not a bug that in the sense that we are catching and handling the `NullPointerException`. 
We may add a specific check to increase readability tough.
