### ISSUE TITLE
Excessive EntryEventType[] allocations

### ISSUE THREAD

**Issue by tbabinski** [hazelcast/hazelcast#11777]
A high number `EntryEventType[]` are created in a client application which receives many entry events.  In a specific application, `EntryEventType[]` dominates the application's overall memory allocation.  

![entryeventtype allocations](https://user-images.githubusercontent.com/22600996/32676358-2c26117e-c60f-11e7-9ba2-b9a41adf63b4.png)

I suspect that this is the result of a leak in `EventryEventType.getByType(final int eventType)`.  That method calls `EntryEventType.values()`, which allocates a new array on each call.  If this suspicion is correct, a fix could be to cache the values array in a private static variable.

Hazelcast version 3.9 running on java 9

**Comment by mdogan** [comment]
`EventryEventType.getByType(final int eventType)` can be implemented via `switch/case`:

```java
switch (eventType) {
    case Type.ADDED:
        return ADDED;
    case Type.REMOVED:
        return REMOVED;
    case Type.UPDATED:
        return UPDATED;
    case Type.EVICTED:
        return EVICTED;
    case Type.EVICT_ALL:
        return EVICT_ALL;
    case Type.CLEAR_ALL:
        return CLEAR_ALL;
    case Type.MERGED:
        return MERGED;
    case Type.EXPIRED:
        return EXPIRED;
    case Type.INVALIDATION:
        return INVALIDATION;
}
```

**Comment by tbabinski** [comment]
Thank you.
