### ISSUE TITLE
Incorrect null log message in Delegating Address Picker

### ISSUE THREAD

**Issue by smillidge** [hazelcast/hazelcast#11783]
The log message of Delegating Address Picker uses the wrong variable here
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/instance/DelegatingAddressPicker.java#L63 

The line should be
```java
logger.info("Using bind address: " + bindAddress);
```

**Comment by jerrinot** [comment]
@smillidge: many thanks for reporting this. I am glad to see there are already users of `MemberAddressProvider`!

**Comment by smillidge** [comment]
I'd rather not be a user ;-) but Hazelcast seems to reject many network connections based purely on the address chosen at boot. In my case the computer has two networks docker0 and eth0 and Hazelcast keeps choosing docker0 and rejecting connections from the LAN.

**Comment by jerrinot** [comment]
related to https://github.com/hazelcast/hazelcast/pull/11504

**Comment by smillidge** [comment]
What is the use case that Hazelcast is implementing when it refuses connections that do not have the same "name"? It also refuses connection attempts that use IPv6 over IPv4 just because the "name" doesn't match. This will come a bit of a nightmare in a multi-homed network and as we proliferate more and more virtual interfaces for docker et al.

**Comment by mmedenjak** [comment]
@smillidge some checks were added as security checks but I agree that some checks don't make sense and are making deployment harder. We're working on improving this and any input is welcome.

**Comment by smillidge** [comment]
I don't understand the security argument. I can lock down the network security simple enough via firewall rules. You also have cluster name, password and then all the security features in Hazelcast Enterprise. Simplest change would be a flag to switch the check off.

**Comment by mmedenjak** [comment]
Just to be clear, which check are you referring to?

**Comment by mmedenjak** [comment]
This issue was closed since the initial log message was fixed and will be released with 3.9.1. Please open a new issue (or elaborate here) with which check is rejecting the connections. We have numerous checks and it is possible the check was added because of a specific reason or the check is a defect and could be fixed or improved.

**Comment by smillidge** [comment]
There's already an issue open #9219 for the checks.
