### ISSUE TITLE
[cluster] MembershipFailureTest.heartbeat_not_sent_to_suspected_member

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11797]
**com.hazelcast.internal.cluster.impl.MembershipFailureTest.heartbeat_not_sent_to_suspected_member[fd:deadline]**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 2
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:957)
	at com.hazelcast.internal.cluster.impl.MembershipFailureTest.heartbeat_not_sent_to_suspected_member(MembershipFailureTest.java:305)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11602/testReport/junit/com.hazelcast.internal.cluster.impl/MembershipFailureTest/heartbeat_not_sent_to_suspected_member_fd_deadline_/

**Comment by viliam-durina** [comment]
[log-excerpt.log.gz](https://github.com/hazelcast/hazelcast/files/1506430/log-excerpt.log.gz)

**Comment by viliam-durina** [comment]
Looks like an intermittent issue when starting three members. Before the cluster was formed, some members already left, because they didn't receive heartbeats timely. `slave1` split before `slave2` was able to join.

```
12:54:55,320  INFO |heartbeat_not_sent_to_suspected_member[fd:deadline]| - [MembershipManager] hz._hzInstance_6_dev.cached.thread-5 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Starting mastership claim process...
...
12:54:55,323 DEBUG |heartbeat_not_sent_to_suspected_member[fd:deadline]| - [InternalPartitionService] hz._hzInstance_6_dev.cached.thread-17 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Removing Member [127.0.0.1]:5003 - 02f7d86b-9307-4eb3-8aff-9738eb726cb9
...
12:54:55,373  WARN |heartbeat_not_sent_to_suspected_member[fd:deadline]| - [ClusterHeartbeatManager] hz._hzInstance_2_dev.cached.thread-2 - [127.0.0.1]:5003 [dev] [3.10-SNAPSHOT] Resetting heartbeat timestamps because of huge system clock jump! Clock-Jump: 8267 ms, Heartbeat-Timeout: 10000 ms
```

See attached `log-excerpt.log`.

**Comment by Donnerbart** [comment]
It looks like this was an intermittent failure. The test is timing sensitive (due to the heartbeats), we see no (simple) solution to make the test itself more robust. A normal countermeasure would be to remove the `ParallelTest` for those tests, so there are no other test classes being executed in parallel.

But this test is a parameterized one and the `HazelcastParametersRunnerFactory` also uses the `ParallelTest` annotation to determine if the test methods should run in parallel. So if we remove the annotation, the test duration explodes.

What I would recommend is to introduce a `HazelcastParallelParametersRunnerFactory` and `HazelcastSerialParametersRunnerFactory`, so we use the `ParallelTest` for the test class level only. Then we can make this test more stable, by running it with parallel test methods, but not in parallel with other tests.

**Comment by mmedenjak** [comment]
Is it possible to add some annotation like `ParallelMethodTest` and have the `ParallelTest` class extend it? And then change the type check in `HazelcastParametersRunnerFactory#isParallel` to check for this parent annotation type?

**Comment by viliam-durina** [comment]
We decided to create two new subclasses of `HazelcastParametersRunnerFactory`. There are two reasons:
- `ParallelMethodTest` as a superclass of `ParallelTest` would not imply parallel methods for `HazelcastSerialClassRunner`.
- it won't be possible to have parallel test and not parallel methods with `HazelcastParametersRunnerFactory`
