### ISSUE TITLE
Dynamic config added on lite member not found after split brain healing

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#11815]
_Scenario:_
Say split occurred then we have 2 brains. 
First brain has lite member and second brain has data member. 
If we add a config dynamically from lite member, that config should be found after brains merge. 
But now, config disappears.

**Comment by vbekiaris** [comment]
The split-brain merge still [invokes on all partitions](https://github.com/hazelcast/hazelcast/commit/d1bae9c134322830de8d4888351f56eb8b5b2de6#diff-e85fa9f1c4a7da229ee2dab58ec52f89R564) the merge operation, seems like a left-over from https://github.com/hazelcast/hazelcast/pull/10997
