### ISSUE TITLE
Switch to IPv6 is not seamless

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#11820]
When I enable IPv6 for Hazelcast, the started member still sets an IPv4 as a local address by default.

Hazelcast reference manual talks about a [seamless support of IPv6](http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#ipv6-support), so the current behavior is unexpected.

**Reproducer:**
```java
System.setProperty("java.net.preferIPv4Stack", "false");
System.setProperty("java.net.preferIPv6Addresses", "true");
System.setProperty("hazelcast.prefer.ipv4.stack", "false");

Hazelcast.newHazelcastInstance();
```
and its output:
```
INFO: [LOCAL] [dev] [3.9] Picked [172.17.0.1]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Nov 20, 2017 1:36:48 PM com.hazelcast.system
INFO: [172.17.0.1]:5701 [dev] [3.9] Hazelcast 3.9 (20171018 - 4e89e6d) starting at [172.17.0.1]:5701
...
```

**Expected behavior**
When IPv6 is enabled/preferred, Hazelcast picks an IPv6 address to bind to.

**Comment by Donnerbart** [comment]
IPv6 seems to be not tested well, see the coverage of `TcpIpConnector`: https://hazelcast-l337.sonar.cloudbees.com/resource/index/35831?display_title=true&metric=coverage
