### ISSUE TITLE
Performance issue in INDEX_COPY_BEHAVIOR

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#11841]
I just tried this new option with HZ 3.8.7. Tried all 3 values. With COPY_ON_READ I see no performance improvement, it works like it was in HZ 3.8.6. With NEVER the performance for reads increased in 2..3 times, very good, but not sure this value can be used safely. With COPY_ON_WRITE I see the same improve for reads, but there is huge performance degradation on inserts, they become 30..50 times slower.
Have a look, please.

**Comment by mdogan** [comment]
Related to https://github.com/hazelcast/hazelcast/issues/11280

**Comment by mmedenjak** [comment]
Hi @dsukhoroslov !

I believe these observations depend heavily on your setup, the machine you're running on, the objects you store in the map and index, the access patterns, the distribution of write vs read, etc. 

Can you describe each one of them? Or maybe just share a minimal reproducer?

**Comment by tombujok** [comment]
Hey @dsukhoroslov.  Yes, COPY_ON_READ is how it was before. NEVER is how it was last year. COPY_ON_WRITE is just a third setting for read-only map cases mainly.

So yes, it's how it works.  There's not free lunch, the set with the entries needs to be copied somewhere, to separate the internal structure with the structure that is returned on index read.
you trade performance for consistency. NEVER is not 100% safe, but these are corner cases, described here: https://github.com/hazelcast/hazelcast/pull/9688
The biggest drawback of NEVER is that the set you get from the index may be modified while you hold a reference to it, so you may check size, and then suddenly it's different. But it's a concurrent structure.

**Comment by dsukhoroslov** [comment]
Hi @tombujok. My understanding was that COPY_ON_READ will copy search results on both index reads and writes, COPY_ON_WRITE will do that on writes only and NEVER does not copy results at all. So, it is not clear why COPY_ON_WRITE is so slower then COPY_ON_READ on inserts (index writes).

**Comment by dsukhoroslov** [comment]
Hi @mmedenjak. I just run a standard YCSB tests against [BagriDB](https://github.com/dsukhoroslov/bagri). It can be easily reproduced on any machine, so if you're going to investigate it in more detail I'll provide detailed instructions on how to start Bagri server and run YCSB tests on it.

**Comment by mmedenjak** [comment]
`COPY_ON_READ` will copy the results only on index reads making it useful for write-heavy maps. It does not copy on writes.
`COPY_ON_WRITE` copies on writes making it useful for read-heavy maps. `NEVER` does not do any copying.
Given this explanation, is the behaviour of `COPY_ON_WRITE` still surprising? If so, please explain how it is surprising and how to setup the benchmark.

**Comment by dsukhoroslov** [comment]
Sorry for the late response. No, with this explanation the behaviour looks correct. I just thought the copy of results on writes was also implemented/used earlier, that is why I was surprised in so significant performance degradation.
