### ISSUE TITLE
Default BackupEntryProcessor is Serializable

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#11851]
EntryBackupProcessorImpl inside AbstractEntryProcessor is Serializable and everything inside will use Java Serialization for that reason. Make it IdentifiedDataSerializable for performance and consistency reasons (because custom serialization won't be taken into account here).

**Comment by jerrinot** [comment]
good finding! a pain to implement due rolling upgrade compat.

**Comment by mmedenjak** [comment]
Also, [fixing bugs is a problem](https://github.com/hazelcast/hazelcast/blob/10c1d716875f74726880b9c76d342698affe98c0/hazelcast/src/main/java/com/hazelcast/map/AbstractEntryProcessor.java#L73-L79) once a class is `Serializable`

**Comment by mmedenjak** [comment]
It's possible that the class is `Serializable` because it is intended to be implemented by the user. We might turn it into a `IdentifiedDataSerializable` but that would be imposing a serialisation scheme on the user since we don't know how to serialise and deserialise it.

**Comment by noctarius** [comment]
I don't think it makes a difference, the BackupEntryProcessor we use internally (in AbstractEntryProcessor) is never handed out to a user, therefore it can be perfectly changed to a Hazelcast serialization scheme, not in a backwards compatible way though. But the current situation enforces Java Serialization or (in my case) a NotSerializableException which is why I actually found it.

**Comment by lukasherman** [comment]
Unfortunately it affects HazelcastWriters.updateMapP, I need to find workaround for that.

**Comment by mmedenjak** [comment]
I believe if the entry processor implements `IdentifiedDataSerialisable` or `DataSerialisable`, that serialisation will be preferred over java serialisation. @lukasherman can you verify this?

**Comment by lukasherman** [comment]
Entry processor used in [updateMapP](https://github.com/hazelcast/hazelcast-jet/blob/5f8e59640e9536123e4838a100044b25804b788d/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/connector/HazelcastWriters.java#L105) does not implement that interfaces. It goes right into JavaSerializer:
```
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_152]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.write(JavaDefaultSerializers.java:242) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250) ~[hazelcast-jet-0.6-20180109.155423-37.jar:0.6-SNAPSHOT]
```
I will test updateMapP variant with custom processor instead.

**Comment by mmedenjak** [comment]
@eminn can the EntryProcessor in `updateMapP` be changed to implement `DataSerialisable` or `IdentifiedDataSerialisable`?

**Comment by eminn** [comment]
@mmedenjak yes we can replace `AbstractEntryProcessor` with a `IdentifiedDataSerialisable` counterpart.

**Comment by mmedenjak** [comment]
`EntryBackupProcessorImpl` and `AbstractEntryProcessor` have been removed in HZ 4.0 - https://github.com/hazelcast/hazelcast/pull/14995
