### ISSUE TITLE
EvictionConfig.size is obsolete but not mentioned in JavaDoc

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#11856]
`EvictionConfig.size` is there only for backward compatibility but it is not stated in javadoc. 
It created confusion with one user, so it looks like we should update javadoc to avoid confusions in the future.

**Comment by Donnerbart** [comment]
`EvictionConfig.size` is used. Actually `EvictionConfig` is the preferred way to configure an eviction. Could you please elaborate in which context you are using the `EvictionConfig` (Cache or NearCache?) and what do you think the actual way is? Also which Hazelcast version are we talking about?

You can see here, that the `EvictionConfig` is used with all its fields for the Near Cache configuration:
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#configuring-near-cache

**Comment by Donnerbart** [comment]
I'm closing this issue. Please feel free to re-open if you can provide more details.
