### ISSUE TITLE
Hazelcast Mancenter nodel level map details rest api

### ISSUE THREAD

**Issue by sundeepsid** [hazelcast/hazelcast#11877]
Hello all,

Is there a rest api to get the map details for a particular imdg node? Right now I am getting map details using this uri `localhost:port/mancenter/rest/clusters/dev/maps/map-name` but this URI returns entries of map in cluster but i want to get the map entries of particular IMDG node

**Comment by hasancelik** [comment]
Hi @sundeepsid, 

You can get some detailed informations (ownedPartitionCount, connectedClientCount, memory stats etc) for a particular hazelcast node via `localhost:port/mancenter/rest/clusters/dev/members/{member}` but getting map entries of particular hazelcast node is not possible in the current implementation of our Clustered REST:

http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html

I have added `Enhancement` label on this issue so I will talk with my team about it. If it is possible to implement, we will add it to our roadmap for the next releases.

**Comment by emre-aydin** [comment]
Closing the issue as the question is answered and we track the feature request in MC GitHub repo issues.
