### ISSUE TITLE
Event Journal consumer might never catch up

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#11895]
Currently when reading from event journal, the reader throws `StaleSequenceException` when the consumer is behind the current head of the journal. The exception contains the new head of the journal, however by the time the client gets to read again this new head can be stale again. It can mean that the reader is never able to catch up once it falls behind.

Another mechanism should be in place to detect missing items and the reader should be able to catch up eventually.

**Comment by pveentjer** [comment]
Probably best to make a new operation 'listen to most recent head' so that the head doesn't need to be passed explicitly.

**Comment by mmedenjak** [comment]
As it's private API, the behaviour will be changed to not throw an exception or a boolean parameter will be added to signify this. We can mostly keep the existing operation as the response contains enough information to determine how many items were missed which is relevant to the use case.

**Comment by cangencer** [comment]
I noticed something else: if you try to subscribe with an offset which is greater than the current tail, you get `IllegalStateException`. This can happen when a Jet job restarts and some of the partitions have been lost, and it will try to restart from an offset which doesn't exist. What should happen in this case? Intuitively it feels to me it should start from the latest available offset in this set.

**Comment by mmedenjak** [comment]
@cangencer as it is private API, we can alter it to whatever suits your needs. Jet does not support rolling upgrades, right? It does not support having a cluster of hazelcast members with different versions?

**Comment by cangencer** [comment]
Yes there's no need to support rolling upgrades.
