### ISSUE TITLE
Hazelcast - Locks acquired on distributed map are NOT shown in management center

### ISSUE THREAD

**Issue by simpleusr** [hazelcast/hazelcast#11907]
I am trying to evaluate hazelcast for distributed lock solution.
I am creating a hazelcast client instance from my application. Then I am acquiring lock over map using IMap.tryLock method. During debug and from logs I am seeing that I could acquire the lock successfully.After successful lock acquisition I am putting an entry to map.So at that time instant there is one entry and one lock in the map.In management center, I can see that there is only one entry in the map but can not see the lock.

![questionmc](https://user-images.githubusercontent.com/5550814/33538295-80c83b06-d8d1-11e7-80d9-d707ad4afe45.png)

Is this the expected behaviour? If this is the expected behaviour what does locks mean for maps in management center?

**Comment by Donnerbart** [comment]
@hasancelik @emre-aydin Could you please have a look?

**Comment by emre-aydin** [comment]
@simpleusr I have answered your question on Stackoverflow -> https://stackoverflow.com/a/47674559/2080975 

Let's continue the discussion there. Closing the issue.
