### ISSUE TITLE
ScheduledTaskStatistics.getLastRunDuration() returns negative values for quick executions

### ISSUE THREAD

**Issue by bedrin** [hazelcast/hazelcast#11929]
I can see that for some of my scheduled jobs getLastRunDuration() returns negative values.
Issue is intermittent. It seems that it is triggered by fast jobs

**Comment by tkountis** [comment]
Interesting finding, thanks for the report.
I will have a look and try to reproduce, but if you have any logs that could help please share.
Maybe members going offline in the logs?

**Comment by bedrin** [comment]
I have reproduced it on my local workstation with a single member in cluster.

Looking at the code I can see that race-condition between updating lastRunStart/lastRunEnd fields and taking snapshot is possible:

1. Thread 1 updates lastRunStart
1. Thread 2 takes a snapshot (effectively copy values from lastRunStart and lastRunEnd)
1. Thread 1 updates lastRunEnd

In this case result of getLastRunDuration() operation would be negative

**Comment by tkountis** [comment]
Can you share the reproducer here?

**Comment by bedrin** [comment]
Sorry, cannot share any code from office.

Basically what I do is call schedule job at fixed rate R (say 1 minute) and immediately after that start a timer (vanila java Timer from JRE) with the same rate which calls IScheduledFuture.getStats() method

If my job takes a few seconds to execute, IScheduledFuture.getStats() called from Timer will get into race-condition described above and print the difference between lastRunEnd from previous execution and lastRunStart from current execution which is obviously negative

**Comment by tkountis** [comment]
I see. This is a good finding, 
and i think there are a couple of ways to hit this.

Will fix.
