### ISSUE TITLE
Hazelcast custer was crashed and didn't restored. 

### ISSUE THREAD

**Issue by borodatu** [hazelcast/hazelcast#11926]
Hi,
I have a periodical problem when one host from cluster is going out and became unavailable.

Architecture:
Hosts on EC2 prdc1rsvc1 and prdc2rsvc1 putted under load balancer, and simple host prdc1agwnode1.
And host in our data center prd1agwnode1.
Hazelcat version 3.6.4
Java version 1.8.0_60

prd1agwnode1 periodically disappears from cluster. 
Logs from each hosts:
[prdc1agwnode1.txt](https://github.com/hazelcast/hazelcast/files/1536960/prdc1agwnode1.txt)
[prdc1rsvc1.txt](https://github.com/hazelcast/hazelcast/files/1536961/prdc1rsvc1.txt)
[prdc2rsvc1.txt](https://github.com/hazelcast/hazelcast/files/1536962/prdc2rsvc1.txt)
[prd1agwnode1.txt](https://github.com/hazelcast/hazelcast/files/1536956/prd1agwnode1.txt)

**Comment by jerrinot** [comment]
hi @borodatu, Hazelcast 3.6 was released 2 years ago. Can you try it with a new version?

**Comment by borodatu** [comment]
Hi @jerrinot, yes we have already moved on 3.9.2
But the problem was in badly configured network in our side. We changed host names in Hazelcast config files on real IPs, and the problem was resolved.
