### ISSUE TITLE
Joining node's version 3.9.1 is not compatible with 3.8.7

### ISSUE THREAD

**Issue by abunjevac** [hazelcast/hazelcast#11924]
Active node [127.0.0.1]:5701 is running version 3.8.7.
New node [127.0.0.1]:5702 (running version 3.9.1) is failing to start.

`SEVERE: [127.0.0.1]:5702 [dev] [3.9.1] Reason of failure for node join: Joining node's version 3.9.1 is not compatible with 3.8.7`

Code:

`config.setProperty("hazelcast.socket.bind.any", "false");
config.getNetworkConfig().setPort(5701).setReuseAddress(true).setPortAutoIncrement(true).getInterfaces().addInterface("127.0.0.1").setEnabled(true);
config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
config.getNetworkConfig().getJoin().getTcpIpConfig().addMember("127.0.0.1:5701").addMember("127.0.0.1:5702").setEnabled(true);
`
Cluster forms correctly when both nodes are running version 3.9.1.

**Comment by vbekiaris** [comment]
@abunjevac this is expected when using Hazelcast open source, are you indeed using Hazelcast IMDG open source? The [compatibility guarantees](http://docs.hazelcast.org/docs/3.9.1/manual/html-single/index.html#hazelcast-members-compatibility-guarantees) section in the reference manual reads:
> Patch level compatibility applies to both Hazelcast IMDG and Hazelcast IMDG Enterprise.
Rolling upgrades across minor versions is a Hazelcast IMDG Enterprise feature, starting with version 3.8.

So when using Hazelcast open source, you can expect each 3.8.x version to be compatible with any previous 3.8.y version, but not across minor versions (3.8 -> 3.9).

**Comment by abunjevac** [comment]
Yes, I am indeed using open source. Somehow I forgot about this minor versions compatibility thing, sorry.

**Comment by vbekiaris** [comment]
no worries, thanks for the heads up!
