### ISSUE TITLE
Backup mismatch in SetSplitBrainTest and ListSplitBrainTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#11930]
I've added testing of backup count and content for ISet and IList in my split-brain healing PR (https://github.com/hazelcast/hazelcast/pull/11677). Those checks spuriously fail. I have not figured out, if this just happens in split-brain scenarios, when migrations happen (which is a part of the split-brain healing) or even in a normal cluster state.

For the `CustomMergePolicy` the error looks like:
```
java.lang.AssertionError: backupSet should contain 25 items [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] 
Expected :25
Actual   :15
```
The initial items `item0` to `item9` are missing, just the merged values `0` to `14` are there.

For the `PassThroughMergePolicy` the error looks like:
```
java.lang.AssertionError: set should contain 40 items [item2, item3, item4, item5, item8, item10, item11, item16, item17, item19, item20, item21, item22, item23, item24, item25, item26, item27, item28, item29, item30, item31, item32, item33, item34, item35, item36, item37, item38, item39] 
Expected :40
Actual   :30
```
Some of the initial items `item0` to `item9` are missing. Also some of the merged values `item10` to `item39` are missing.

The split-brain healing uses the same backup operation like the normal set operations.

**Comment by Donnerbart** [comment]
I've added a backup test for an up- and down-scaling cluster for the collection data structures: https://github.com/hazelcast/hazelcast/pull/11978

Those seem to be okay, so the backup creation and migration should work.

**Comment by Donnerbart** [comment]
Okay, I can now tell better when this happens.

We have a cluster of 3 nodes and it's split in 2|1 sub-clusters, so during the split-brain it's:
* 5001 cluster A
* 5002 cluster A
* 5003 cluster B

An `ISet` is not partitioned, so when I switch the test from a random name to `generateKeyOwnedBy()` I can force the primary owner of the data structure. And this determines if the test fails or not:

Works all the time:
```
setNameA = generateKeyOwnedBy(instances[0]);
owner instance is: 5001
backup instance is: 5002|5003
```
```
setNameA = generateKeyOwnedBy(instances[1]);
owner instance is: 5002
backup instance is: 5001|5003
```
Fails all the time:
```
setNameA = generateKeyOwnedBy(instances[2]);
owner instance is: 5003
backup instance is: 5001|5002
```

The mismatches look like this:
```
java.lang.AssertionError: set should contain 25 items [item10, item11, item12, item13, item14, item15, item16, item17, item18, item19, item20, item21, item22, item23, item24] 
Expected :25
Actual   :15

java.lang.AssertionError: set should contain 25 items [item2, item3, item4, item5, item8, item10, item11, item16, item17, item19, item20, item21, item22, item23, item24] 
Expected :25
Actual   :15
```
We insert `item0` to `item9` before the split-brain happens. And `item10` to `item24` during the split-brain (in both sub-clusters). The inserted `lostItem0` to `lostItem14` are expected to be missing, since we discard them.

So what we see is that even backup items from before the split-brain are lost.

**Comment by Donnerbart** [comment]
Okay, we seem to lose the backups in the larger cluster, when the additional items `item0` to `item24` are added to the `ISet`.
```
onAfterSplitBrainCreated, owner instance is: 5001
onAfterSplitBrainCreated, backup instance is: 5002
onAfterSplitBrainCreated: backupSet [item0, item2, item1, item8, item7, item9, item4, item3, item6, item5]
afterSplitDiscardMergePolicy: adding items item10 to item24...
onAfterSplitBrainCreated: backupSet [item19, item18, item17, item16, item15, item14, item13, item24, item12, item23, item11, item22, item10, item21, item20]
```
And I have an idea what could happen here...

**Comment by Donnerbart** [comment]
The `CollectionContainer` has
```java
Map<Long, CollectionItem> itemMap;
```
The `SetContainer` has an additional
```java
private Set<CollectionItem> itemSet;
```
and it has the methods
```java
public Set<CollectionItem> getCollection();
public Map<Long, CollectionItem> getMap();
```
which return the according data structure, but also create it from the other one, if they are `null`:
* on `getCollection()` the `itemSet` will be created from the `itemMap` if `null`.
* on `getMap()` the `itemMap` will be created from the `itemSet` if `null`.

I already ran in an issue when using `getCollection()` and `getMap()` in the same method for the split-brain handling. They are normally used in two different contexts. `getCollection()` is used for the primary and `getMap()` for the backups.

`getCollection()` is used by:
```java
public long add(Data value)
public CollectionItem remove(Data value)
public int size()
public Map<Long, Data> clear()
public boolean contains(Set<Data> valueSet)
public Map<Long, Data> addAll(List<Data> valueList)
...
```

`getMap()` is used by:
```java
public void addBackup(long itemId, Data value)
public void removeBackup(long itemId)
public void clearBackup(Set<Long> itemIdSet)
public void addAllBackup(Map<Long, Data> valueMap)
...
```

My guess is that we lose the backups on a transformation between the `itemMap` and the `itemSet` or another mixup in that area.

**Comment by Donnerbart** [comment]
Oh, it's even simpler, we seem to overwrite the existing backups, because we start with `itemId` 1 again...
```
onAfterSplitBrainCreated, owner instance is: 5002
onAfterSplitBrainCreated, backup instance is: 5001
onAfterSplitBrainCreated: [item0, item2, item1, item8, item7, item9, item4, item3, item6, item5]
1 with value item0 will be overwritten with item10
2 with value item1 will be overwritten with item11
3 with value item2 will be overwritten with item12
4 with value item3 will be overwritten with item13
5 with value item4 will be overwritten with item14
6 with value item5 will be overwritten with item15
7 with value item6 will be overwritten with item16
8 with value item7 will be overwritten with item17
9 with value item8 will be overwritten with item18
10 with value item9 will be overwritten with item19
11 will be stored with item20
12 will be stored with item21
13 will be stored with item22
14 will be stored with item23
15 will be stored with item24
onAfterSplitBrainCreated: [item19, item18, item17, item16, item15, item14, item13, item24, item12, item23, item11, item22, item10, item21, item20]
```

**Comment by Donnerbart** [comment]
This issue doesn't happen with `IQueue`, which also uses an `itemId` to handle the backups. I had a look and it seems like @hasancelik and @jerrinot fixed this 2014 for `IQueue` via https://github.com/hazelcast/hazelcast/pull/2844 and https://github.com/hazelcast/hazelcast/pull/4275

I guess we need a similar fix for `ISet` and `IList`.

**Comment by mmedenjak** [comment]
Congrats on finding this! This was an interesting read :)

**Comment by Donnerbart** [comment]
Thanks :) I've added the fix to my split-brain PR and re-enabled the backup tests: https://github.com/hazelcast/hazelcast/pull/11677/files#diff-6f9203b1bbfee8dc7959b0dfd15cfc4e

I'm also running the `ISet` and `IList` split-brain tests locally in a loop, so far no failures. Looks like this was indeed the root cause.

**Comment by Donnerbart** [comment]
After more than 350 successful local test executions of each `SetSplitBrainTest` and `ListSplitBrainTest` I'm closing this issue. The details and possible improvements of the fix can be discussed in the split-brain PR.
