### ISSUE TITLE
IMap aggregate, projection, localKeySet &  executeOnEntries methods throws exception when PartitionPredicate used

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast#11962]
See: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L797

A Partition predicate check can be added & query can be sent only that partition, This will also improve the performance of the aggregations. See `Map.values` with Predicate as an example: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L658

**Comment by tombujok** [comment]
It's all due to the fact how broken the process of implementing the PartitionPredicate was. I was against its design, and now we can also see how many holes it has...
CC @taburet It may be interesting for you.

**Comment by dimas** [comment]
There is also https://github.com/hazelcast/hazelcast/issues/12238 which is very similar. Does this ticket cover it too?
