### ISSUE TITLE
ISet add() boolean return value unreliable on split brain, due to at least once

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11972]
`set.add()` can return false, even if the item added is not a duplicate

For example, the operation was retried because the first one timed out, but was successful on target, but the caller didn't know? Then the retrial would return that key was already present...
add is idempotent in the way it affects the target set, but not in its return value

this scenario possible? Two members, A, B.

A sends CollectionAddOperation to B (the partition owner)
B sends sync backup back to A
now split occurs, A doesn't receive response from B
CollectionAddOperation timeouts and is retried, now A is partition owner.
operation succeeds, but it already contained the key, so the set.add call returns true -> this causes duplicate ID error

yes, hazelcast provides at-least-once guarantees: http://docs.hazelcast.org/docs/latest/manual/html-single/#exactly-once-at-least-once-or-at-most-once-execution

failing Test for ISet add under split
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-x1/2/console
https://github.com/hazelcast/hzCmd-bench/tree/zeta/lab/hz/split/set/add
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/set/FillIUnique.java

related to this issue
https://github.com/hazelcast/hazelcast/issues/11967

**Comment by Danny-Hazelcast** [comment]
possible adding documentation is the only thing we can do

**Comment by mmedenjak** [comment]
I see you've provided the link to the documentation. Do you think this should be documented elsewhere?

**Comment by Danny-Hazelcast** [comment]
that link is a generic description of the issue.
and set.add() is an example of its effect.
set.add() may return false event if item is unique.

are we going to put the issue to back log, or just close ?

**Comment by mmedenjak** [comment]
I propose closing the issue unless there is a better option. There are many methods that are affected by this and I wouldn't want to bloat the javadoc by writing this to each and every one:
- `IMap.put` may return a value even though there was no previously associated key
- `IMap.remove` may return null even though there was a previously associated key
- `IMap.tryPut` may return false even though the call succeded
- `ILock.tryLock` may return false even though the lock was obtained
- `IAtomicLong.incrementAndGet` may increment the long twice
...

If you have a suggestion how this can be improved, please say so.
