### ISSUE TITLE
Improve index support in predicates

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#11970]
1. ~~Make `or` predicate indexed in the same way as `and` predicate. For now, `and` predicate is considered indexed when at least one child predicate is indexed, while `or` predicate requires all the child predicates to be indexed. Also, it must short-curcuit starting from the most selective index in the same way as `and` does but on `true` instead of `false`.~~

2. It may be a good idea to sort all the child predicates for `and` and `or` by their index selectivity (`IndexAwarePredicate.filter(qc).size()`) and evaluate them in that order. For now, `and` predicate is just picking the most selective one to evaluate it first, then it evaluates other indexed predicates, then the remaining non-indexed ones; `or` just evaluating them in the order they were provided.

3. Make `not` predicate an `IndexAwarePredicate`.

**Comment by jerrinot** [comment]
ad point no.1: I think the reasoning is this: when `or` has at least 1 non-indexed child predicate then you need to do a full map-scan anyway.

**Comment by taburet** [comment]
@jerrinot got it, removing from the list.

**Comment by burakcelebi** [comment]
Closed as internal request.
