### ISSUE TITLE
Topic Message Listener in Web App

### ISSUE THREAD

**Issue by imranrajjad** [hazelcast/hazelcast#11973]
Hello,
What is the correct way to register a message listener on a Hazelcast topic in Web Application (e.g Spring) running inside Tomcat 8.x. Although it has not causing any issues but the container in the logs constantly complains about the hazel-cast thread. I am connecting to an external Hazelcast 3.8.4 cluster through the client.

regards,
Imran

**Comment by vbekiaris** [comment]
> but the container in the logs constantly complains about the hazel-cast thread

Can you be more specific about this? What kind of log output do you see, can you paste the log entries here?

**Comment by blazember** [comment]
@imranrajjad is your question still actual? If so, could you please make your question more specific?

**Comment by imranrajjad** [comment]
`WARNING: The web application [test_web_app] appears to have started a thread named [hz.client_0.eventRegistration-] but has failed to stop it. This is very likely to create a memory leak. `

this is what appears at times

**Comment by jerrinot** [comment]
@imranrajjad: I would expect to see this error when you are redeploying your app / restarting a container. Is this the case? You you calling `hazelcastInstance.shutdown()` when your application is about to be stopped?

**Comment by jerrinot** [comment]
closed due inactivity. @imranrajjad: feel free to re-open it once you have more informations. thanks!
