### ISSUE TITLE
Improve MigrationRequestOperation with the new Offload abstraction

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#11989]
See 
- [Operation Continuation: Offloaded Abstraction - Design](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/276070519/Operation+Continuation+Offloaded+Abstraction+-+Design)
- Blocked on https://github.com/hazelcast/hazelcast/pull/11894

**Comment by mmedenjak** [comment]
@mdogan can you do this in 3.10 or are we postponing this for 3.11?

**Comment by mdogan** [comment]
@mmedenjak: This is blocked on https://github.com/hazelcast/hazelcast/pull/11894
