### ISSUE TITLE
block ICMP large cluster OOME

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#11990]
bock ICMP allow TCP gives continues split and join, as expected.

suddenly every member in the large cluster, show large GC pause times, and all of them OOME
other wise memory usage was very light

job / run
https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-icmp/1/console

output
http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2017_12_14-13_09_45/block-icmp/

output/HZ/HzMember3HZBB/HzMember3HZBB.hprof
output/HZ/HzMember3HZBB/HzMember3HZBB.oome
output/HZ/HzMember5HZBB/HzMember5HZBB.hprof
output/HZ/HzMember5HZBB/HzMember5HZBB.oome
output/HZ/HzMember4HZBB/HzMember4HZBB.hprof
output/HZ/HzMember4HZBB/HzMember4HZBB.oome

GC
http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2017_12_14-13_09_45/block-icmp/gc.html

Test
https://github.com/hazelcast/hzCmd-bench/tree/zeta/lab/hz/icmp/block-icmp

**Comment by Danny-Hazelcast** [comment]
all though a 2nd run with double heap size it 1G, did run ok for the same duration
https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-icmp/2/console
http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2017_12_14-14_23_47/block-icmp/gc.html

**Comment by Danny-Hazelcast** [comment]
started a longer run, https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-icmp/3/console with 1G heap,  
if this passes, and content of hprof's do not look unusual we can close this issue

**Comment by Danny-Hazelcast** [comment]
the 3rd longer run at 1G heap, 
https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-icmp/3/console

No OOME, GC looks good 
http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2017_12_14-15_30_36/block-icmp/gc.html

however we lose data 
```
18:03:23 fail HzMember2HZAA split_validate_mapA hzcmd.map.multi.SizeAssert threadId=0 global.AssertionException: mapBak1_split_A0 size 6 != 100 
```

**Comment by tkountis** [comment]
@Danny-Hazelcast lets put this info in a Map related issue, or rename this one.
It appears that ICMP has nothing todo with this, its rather related to split brain healing.

**Comment by Danny-Hazelcast** [comment]
given longer run with a larger heap passed.
and if you are happy that the content of the hprof is not unusual, then we can close this issue.

**Comment by Danny-Hazelcast** [comment]
OOME seams to be fixed by giving jvm more heap even for longer run.
@tkountis,  I assume the hprof's for this issue did not show any cause for concern 

the data loss also mentioned in the issue is fixed in the test, by waiting for cluster merge and safe at the end after last heal and validate
