### ISSUE TITLE
No documentation on new MemberAddressProvider SPI?

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#11998]
This referenced link does not contain any information on the new MemberAddressProvider SPI

http://docs.hazelcast.org/docs/latest/manual/html-single/#member-address-provider-spi

via: https://github.com/hazelcast/hazelcast/issues/10477#issuecomment-343870741

The only doc I could find is: https://github.com/hazelcast/hazelcast/blob/44045949b683b958e4e245040b65f947f143a9ef/hazelcast/src/main/resources/hazelcast-full-example.xml#L408

**Comment by mmedenjak** [comment]
@bitsofinfo Fixed, thanks for pointing this out!
