### ISSUE TITLE
Id like to be able to provide custom TTL policies

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#12022]
I'd like to be able to provide custom TTL expiration policies for IMap entries, beyond a simple global TTL per Map or TTL per entry on the `set` or `put` - I want to be able to specify a custom class that has logic that can operate on the Map.Entry key/value, for both on-heap and off-heap IMaps.

Clients typically have use cases where they want to keep around certain data values for set time periods, but that changes based on some logic. Furthermore, this expiration is typically fixed around a point in time stored in an external system or within the Map.Entry.value.  Such expiration logic needs to work beyond a cluster restart.

This is the 4th client that I've seen with a need/desire for such functionality (v3.6, 3.7, 3.8 and 3.9)

**Comment by burakcelebi** [comment]
Closed as internal request.
