### ISSUE TITLE
data loss map put after split brain 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12037]
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-map/

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-map/18/consoleFull
http://54.82.84.143/~jenkins/workspace/split-map/3.10-SNAPSHOT/2017_12_20-07_14_58/map/map/

fail HzMember3HZBB split_validate_mapC hzcmd.map.multi.SizeAssert threadId=0 global.AssertionException: mapBak1_split_C0 size 199 != 200 
from the script
http://54.82.84.143/~jenkins/workspace/split-map/3.10-SNAPSHOT/2017_12_20-07_14_58/map/map/go

after we split the cluster and after Cluster AA Size is 2 and Cluster BB Size is 3

we are loading 500 maps mapBak1_split_C* in both split cluster's with 100 unique keys

but we do not check if either cluster is safe before we load map's mapBak1_split_C*

when the cluster is joined we assert the size of the mapBak1_split_C* map's it 200

could it be that the data loss happens when we are loading the data into the map's mapBak1_split_C* as we do not check for cluster safe, and not at the time of merging the 2 clusters.

I will add a validation for the size of the map's mapBak1_split_C* to be 100 in each cluster before
healing the split.

typically the next run with the added validation passed
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-map/19/consoleFull

showing the issue is not so easy to reproduce

and a next run fails
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-map/20/console

but we can see
```
11:56:35 split all AA [BB]
11:56:36 untilClusterAASize2@class=hzcmd.ops.UntilClusterSize [driver=Member.*AA, threads=1, warmup=0, duration=300, bench=Metrics, interval=0, recordException=false, size=2]
11:56:52 untilClusterSize2 Done
11:56:52 untilClusterBBSize3@class=hzcmd.ops.UntilClusterSize [driver=Member.*BB, threads=1, warmup=0, duration=300, bench=Metrics, interval=0, recordException=false, size=3]
11:56:52 untilClusterSize3 Done
11:56:53 split_load_mapB@class=hzcmd.map.member.multi.MultiLoad [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, keyDomain=100, name=mapBak1_split_B]
11:57:00 loadB Done
11:57:00 split_load_mapC_AA@class=hzcmd.map.member.multi.MultiLoad [driver=Member.*AA, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, keyDomain=100, keyDomainMin=0, name=mapBak1_split_C]
11:57:00 split_load_mapC_BB@class=hzcmd.map.member.multi.MultiLoad [driver=Member.*BB, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, keyDomain=200, keyDomainMin=100, name=mapBak1_split_C]
11:57:06 loadC Done
11:57:07 split_validate_mapC@class=hzcmd.map.multi.SizeAssert [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, size=100, name=mapBak1_split_C]
11:57:08 fail HzMember1HZAA split_validate_mapC hzcmd.map.multi.SizeAssert threadId=0 global.AssertionException: mapBak1_split_C0 size 99 != 100 
11:57:10 heal [.*]
11:57:11 clusterAAMerged@class=hzcmd.ops.Merged [driver=Member.*AA, threads=1, warmup=0, duration=400, bench=Metrics, interval=0, recordException=true]
11:58:43 until_AA_merged Done
11:58:43 untilClusterSafe@class=hzcmd.ops.UntilClusterSafe [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true]
11:59:54 untilClusterSafe Done
11:59:55 split_validate_mapA@class=hzcmd.map.multi.SizeAssert [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, size=100, name=mapBak1_split_A]
11:59:56 validateA Done
11:59:57 split_validate_mapB@class=hzcmd.map.multi.SizeAssert [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, size=100, name=mapBak1_split_B]
11:59:58 validateB Done
11:59:59 split_validate_mapC@class=hzcmd.map.multi.SizeAssert [driver=Member, threads=1, warmup=0, duration=0, bench=Metrics, interval=0, recordException=true, count=500, size=200, name=mapBak1_split_C]
12:00:00 fail HzMember3HZBB split_validate_mapC hzcmd.map.multi.SizeAssert threadId=0 global.AssertionException: mapBak1_split_C0 size 199 != 200 
the validation of map's mapBak1_split_C* to be 100 in each cluster fails. before we join the clusters together
```

so this issue is not with split brain heal join, but rather adding the data into the 2 sub clusters
before the cluster's are "safe"

with the extra validation  we can see the problem some time happens, not at the cluster merge stage, but in putting to the sub clusters before they are healed and joined

making map put operations, while cluster size reports the correct size
but might not be in a "safe" stage results in data loss

do we expect to loose data, when making put operations while partition migration operations are running

**Comment by Danny-Hazelcast** [comment]
@mdogan could you take a look over the issue. thanks

**Comment by mdogan** [comment]
@Danny-Hazelcast:

Test script was before:
```
    hz split -p all AA BB
    hz run untilClusterSize2  untilClusterSize3

    hz run loadB loadC

    hz heal
    hz run until_AA_merged untilClusterSafe

    hz run validateA
    hz run validateB
    hz run validateC
```

Then `hz run validateC100` is added to validate `mapBak1_split_C*` on both splits.
```
    hz split -p all AA BB
    hz run untilClusterSize2  untilClusterSize3

    hz run loadB loadC
    hz run validateC100 # <--------- NEW VALIDATION ADDED

    hz heal
    hz run until_AA_merged untilClusterSafe

    hz run validateA
    hz run validateB
    hz run validateC
```

Test was failing _sometimes_ using former script but is not failing anymore after `validateC100` addition. Is this correct?

I'm still not sure if the failure is expected or an issue, just trying to understand the case.

**Comment by Danny-Hazelcast** [comment]
@mdogan the test is still failing some time with 

hz run validateC100 # <--------- NEW VALIDATION ADDED

this was added to see where the data loss happens.
we see it fails at the new added validation

**Comment by mdogan** [comment]
In my testing, I observed failures during `validateA` and `validateC`. Still I don't know the cause but losing data from `mapBak1_split_A*` makes me think that there's an issue while merging the maps from sub-cluster. Because `mapBak1_split_A*` is populated once and never modified.

**Comment by Donnerbart** [comment]
Do we have any progress in the analysis? Is this a blocker for the feature freeze?

**Comment by Danny-Hazelcast** [comment]
last occurance of this issue
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-map/30/console
http://54.82.84.143/~jenkins/workspace/split-map/3.10-SNAPSHOT/2018_01_22-16_50_08/map/

where just 1 iteration failed with 
```
fail HzMember2HZAA split_validate_mapC hzcmd.map.multi.SizeAssert threadId=0 global.AssertionException: mapBak1_split_C0 size 98 != 100 
```

**Comment by mmedenjak** [comment]
@mdogan any update on this issue?

**Comment by mdogan** [comment]
@mmedenjak: I haven't looked at this yet after initial investigation. I tried to reproduce locally with the same 5 member setup, but no luck yet.

**Comment by mdogan** [comment]
I think I figured out the problem here. In short, issue is in test code, in [MultiLoader](https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/map/member/multi/MultiLoader.java), which is used to load multiple entries into multiple maps.

Following `timeStep()` function is supposed to put `keyDomain` entries to the maps.

```java
    public void timeStep() {
        while(Utils.remoteKey(key, hzInstance)){
            key++;
        }

        if(key >= keyDomain){
            return;
        }

        Object keyObj = getKey(key);
        Object val = getValue(key);

        for (IMap map : getMaps()) {
            map.put(keyObj, val);
        }

        key++;
    }
```

But while partitions are migrating, `Utils.remoteKey(key, hzInstance)` may return `true` on all members for a specific key. That causes some keys to be skipped and map to be loaded with less than expected entries.

For example say there are 2 members [A, B] and `key=K` which belongs to the `Partition X`. Initially `Partition X` is owned by member B. 

- `Utils.remoteKey(K, hzInstance)` returns `true` when it's called on member A. 
- Member A increments the key, hence skips the key `K`.
- `Partition X` migrates to member A.
- `Utils.remoteKey(K, hzInstance)` returns `true` when it's called on member B. 
- Member B increments the key, hence skips the key `K`.
- Since both members skip the key `K`, map will have less than `keyDomain` entries.

I removed the loop with `Utils.remoteKey(key, hzInstance)` and re-tested and haven't seen any failure after multiple runs.

```java
    public void timeStep() {

        if(key >= keyDomain){
            return;
        }

        Object keyObj = getKey(key);
        Object val = getValue(key);

        for (IMap map : getMaps()) {
            map.put(keyObj, val);
        }

        key++;
    }
```

**Comment by Danny-Hazelcast** [comment]
@mdogan  ok, so if wait for 

hz run untilClusterSafe

before 

 hz run loadB loadC

then it should fix the issue as, partition migration as finished ?

**Comment by mdogan** [comment]
@Danny-Hazelcast: yes, it should.

**Comment by Danny-Hazelcast** [comment]
@mdogan ok then we can close this issue, thanks for working it out
