### ISSUE TITLE
Unable to setup Hazelcast cluster in multiple server using multicast 

### ISSUE THREAD

**Issue by akb2017** [hazelcast/hazelcast#12044]
Here i am trying to setup hazelcast cluster in multiple server using multicast ,But its not communicating to each other ,Its running as standalone 

My configuration is 
```xml
        <join>
            <multicast enabled="true">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>54327</multicast-port>
                <multicast-time-to-live>32</multicast-time-to-live>
                <multicast-timeout-seconds>2</multicast-timeout-seconds>
                <trusted-interfaces>
                   <interface>192.168.1.*</interface>
                </trusted-interfaces>   
            </multicast>
            <tcp-ip enabled="false">
            </tcp-ip>
            <aws enabled="false">
            </aws>
        </join>
```

Same like [http://docs.hazelcast.org/docs/latest-development/manual/html/Setting_Up_Clusters/Discovering_Members_by_Multicast.html](url)

Iam using the same configuration in all the 3 different machines (example: 192.168.1.24,192.168.1.25,192.168.1.26
Can anybody please help me !

**Comment by akb2017** [comment]
`<join> <multicast enabled="true"> <multicast-group>224.2.2.3</multicast-group> <multicast-port>54327</multicast-port> <multicast-time-to-live>32</multicast-time-to-live> <multicast-timeout-seconds>2</multicast-timeout-seconds> <trusted-interfaces> <interface>192.168.1.*</interface> </trusted-interfaces> </multicast> <tcp-ip enabled="false"> </tcp-ip> <aws enabled="false"> </aws> </join>`

**Comment by akb2017** [comment]
Hazelcast cluster started to communicate each other by using the following configurations in my hazelcast.xml file But i have a doubt is this the best way of configuring hazelcast cluster using multicast..??

`<network> 
      <port auto-increment="true" port-count="100">5701</port>
     <join> 
              <multicast enabled="true"> 
                        <multicast-group>224.2.2.3</multicast-group>
                       <multicast-port>54327</multicast-port> 
                       <multicast-time-to-live>32</multicast-time-to-live>
                       <multicast-timeout-seconds>2</multicast-timeout-seconds>
            </multicast>
            <tcp-ip enabled="false">
           </tcp-ip> 
          <aws enabled="false">
           </aws> 
   </join> 
   <interfaces enabled="true"> 
           <interface>192.168.1.22</interface> 
           <interface>192.168.1.23</interface> 
           <interface>192.168.1.24</interface>
   </interfaces> 
</network>`

Please help me!!

**Comment by akb2017** [comment]
Hazelcast cluster started to communicate each other by using the following configurations in my hazelcast.xml file But i have a doubt is this the best way of configuring hazelcast cluster using multicast..??
`<network>
   <port auto-increment="true" port-count="100">5701</port>
   <join>
      <multicast enabled="true">
         <multicast-group>224.2.2.3</multicast-group>
         <multicast-port>54327</multicast-port>
         <multicast-time-to-live>32</multicast-time-to-live>
         <multicast-timeout-seconds>2</multicast-timeout-seconds>
      </multicast>
      <tcp-ip enabled="false" />
      <aws enabled="false" />
   </join>
   <interfaces enabled="true">
      <interface>192.168.1.22</interface>
      <interface>192.168.1.23</interface>
      <interface>192.168.1.24</interface>
   </interfaces>
</network>`


Please help me!!

**Comment by pveentjer** [comment]
It could very well be that multicast is disabled on your environment. Please try the regular tcpip discovery.

**Comment by akb2017** [comment]
Multicast is enabled on my network

**Comment by blazember** [comment]
@akb2017 has your issue been solved since then?

**Comment by jerrinot** [comment]
@akb2017: the report does not have enough information, it's very likely an issue in your environment. feel free to re-open this issue when you have additional evidence (logs, etc.)
