### ISSUE TITLE
Is there a way to change the Default log level of Log4j2 in Hazelcast in the Hazelcast.xml file.

### ISSUE THREAD

**Issue by bhagathk** [hazelcast/hazelcast#12058]
I am trying to start the hazelcast using the hazelcast.xml. I am setting the logging type to log4j2. I am seeing this message in the logs.

```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'log4j2.debug' to show Log4j2 internal initialization logging.
```
I couldn't figure out the way to change the default log level. Could anyone help me on how to set the default log level?

**Comment by hasancelik** [comment]
Hi @bhagathk,

It seems this error is not related to hazelcast logging mechanism. Do you have any `log4j2.xml` file in your class path? If you want to change default log level of log4j2, you need to add [log4j2.xml](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/resources/log4j2.xml) in your classpath.

**Comment by bhagathk** [comment]
I don’t have any log4j2.xml file in the classpath. Since, I am runnin the hazelcast using the start script provided. Could you suggest me how to set the log4j2.xml file to classpath.

**Comment by hasancelik** [comment]
@bhagathk,

Sorry for the late answer. You need to edit `start.sh` and add `-Dlog4j.configurationFile` parameter to java command:
`$RUN_JAVA -server -Dlog4j.configurationFile=path/to/log4j2.xml $JAVA_OPTS com.hazelcast.core.server.StartServer &`
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/start.sh#L43

**Comment by mdogan** [comment]
@bhagathk: As Hasan already said, to be able use log4j2, you need a valid `log4j2.xml` configuration file and  either you should that file into root of classpath or set `log4j.configurationFile` system property to point location of `log4j2.xml` file.
