### ISSUE TITLE
latest hazelcast docker image is corrupted

### ISSUE THREAD

**Issue by gokcesurenkok** [hazelcast/hazelcast#12055]
Hi,

the latest docker image of hazelcast is exited with 
standard_init_linux.go:185: exec user process caused "no such file or directory"

whereas version 3.8.8 is fine

**Comment by mesutcelik** [comment]
Thanks @gokcesurenkok !
We are looking into it and notify you when we have the fix...

**Comment by googlielmo** [comment]
Hi @gokcesurenkok, it should be okay now. Thank you.
