### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by mibes404** [hazelcast/hazelcast#12059]

**Comment by mesutcelik** [comment]
Hi @mibes404 ,
Can you please be more specific about this github issue? It is only title without description.

I suppose you are looking for Hazelcast Docker Images. If so, feel free to start with Hazelcast Docker Repository. 
https://github.com/hazelcast/hazelcast-docker

**Comment by mibes404** [comment]
Sorry for this uninformative issue. I was looking for ways to use Hazelcast within a Docker container and not use multi-cast. Although I've not yet found the definitive solution, I did find various sources of information and possible plugins to use. 

I had no intention to open the ticket as such; without any detail that is. 

Thanks for getting back.
