### ISSUE TITLE
Reading Data in spark dataframe/dataset from Hazelcast map using python client

### ISSUE THREAD

**Issue by thedevd** [hazelcast/hazelcast#12074]
@jerrinot @enesakar @pveentjer

Hi, just exploring if hazelcast python client offers out of the box support for reading hazelcast map into spark dataframe/dataset. Actually I have a requirement to provide input in my spark mlib program from the hazelcast map and I need to know if there is way to create spark dataframe/dataset from a hazelcast map using python client. Although I see the way in scala or java given in https://github.com/hazelcast/hazelcast-spark

Also want to know if there is any way to write spark dataframe/dataset directly into hazelcast like we have it for RDD ?

**Comment by sancar** [comment]
Hi @thedevd We don't have any support for python client integration with spark.

**Comment by mmedenjak** [comment]
Adding this to backlog as this is a new feature request.

**Comment by burakcelebi** [comment]
Moved to python client repo: https://github.com/hazelcast/hazelcast-python-client/issues/190
