### ISSUE TITLE
SHUFFLE_MEMBER_LIST javaDoc is wrong

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#12082]
[JavaDoc](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/spi/properties/ClientProperty.java#L30) should be fixed as shuffling is done when property is set to `true`.

- [x] Is this only wrong for java client? What about other clients?

**Comment by sancar** [comment]
@ahmetmircik I have just checked our other clients. This property is not available in any of them.
