### ISSUE TITLE
Replicated Map sends memory usage statistics only if in-memory format is `BINARY`

### ISSUE THREAD

**Issue by emre-aydin** [hazelcast/hazelcast#12093]
Default in-memory format is `OBJECT`. As a result, no memory usage statistics are kept for a replicated map with default configuration. 

Not sure if there's something fundamental that's blocking us from keeping memory usage statistics for `OBJECT` in-memory format. If that's the situation, we might just warn the Management Center users about it on the UI.

**Comment by jerrinot** [comment]
I believe it's the same for IMap - we don't calculate memory consumption of deserialzied objects.

**Comment by mmedenjak** [comment]
@emre-aydin 
The `OBJECT` in-memory-format is missing on all structures and we have a PRD for it:
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/132163815/OBJECT+In-Memory+Format+Calculation

There should be a cost per structure when using HD though:
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/109117947/Entry+Cost+Stats+For+HD+Memory
But I guess this is available only for IMap, right?
https://github.com/hazelcast/management-center/pull/357

**Comment by emre-aydin** [comment]
@mmedenjak Apparently, the `NATIVE` format is not supported for Replicated Maps.

```
java.lang.IllegalStateException: Native memory not yet supported for replicated map
```

I've updated the issue description. So as we already have a PRD for this, I think we can just close the issue.
