### ISSUE TITLE
Setting hazelcast.mc.max.visible.instance.count to Integer.MAX or a huge value causes OOME

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast#12095]
Reproducer

Run a ManCenter & start an HZ instance using the below code & create an empty map proxy.

```
        System.setProperty("hazelcast.mc.max.visible.instance.count", String.valueOf(Integer.MAX_VALUE));
        Config config = new Config();
        config.getManagementCenterConfig().setEnabled(true).setUrl("http://localhost:8080/mancenter");
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
        hz.getMap("test");
```

I believe issue is this line: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/management/TimedMemberStateFactory.java#L227

Either here or inside `com.hazelcast.util.SetUtil.createHashSet`, we should prevent creation of huge preallocated maps/sets.

**Comment by mmedenjak** [comment]
@emre-aydin I see the PR is merged. Can we close the issue?

**Comment by emre-aydin** [comment]
@mmedenjak  Sure, that should've happened automatically but anyway, I'm closing the issue.
