### ISSUE TITLE
Ringbuffer.readManyAsync inconsistent exception handling client vs. member

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#12108]
Client unwraps the ExecutionException before throwing it to the user code.
The member never does it. It also does not happen on other async proxies. Client should not unwrap.

RingbufferQuorumReadTest & ClientRingbufferQuorumReadTest are a good example how to reproduce it.

After fixing, clean-up this test by removing the catch clause and adding
`expectedException.expectCause(isA(QuorumException.class));`

https://github.com/tombujok/hazelcast/blob/9bb5df6812c50ac769bd93fdf72a5a3a5b7db34b/hazelcast/src/test/java/com/hazelcast/quorum/ringbuffer/RingbufferQuorumReadTest.java#L148-L152

**Comment by sancar** [comment]
Made a little bit investigation here. Problem is not with wrapping. 

Clients does a remote call inside `readManyAsync` (to get `capacity`)  while members do not. That results with client behaving differently. 

```
ICompletableFuture future = ring(3).readManyAsync(1L, 1, 1, new Filter());
future.get();
```

In a test above when quorum is not present. Client fails with QuorumException in the first line. 
Member fails with ExecutionException(cause QuorumException)  in the second line.
