### ISSUE TITLE
Spring config order sensitive? - to be verified

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#12117]
I'm not an XSD expert, so maybe I'm confusing something, but it seems that using `sequence` instead of `all` in the spring-config.xsd makes the config order-sensitive.

Example:
open the fullConfig-applicationContext-hazelcast.xml and change the order of some attribuets, e.g. in atomic-long. The `TestFullApplicationContext` test will fail. 

Plz verify it.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/9749

**Comment by mmedenjak** [comment]
Closing as a duplicate.
