### ISSUE TITLE
LSM tree based persistence write to hard disk

### ISSUE THREAD

**Issue by vspatel** [hazelcast/hazelcast#12122]
Write behind implementation for data persistence on hard disk using LSM tree

**Comment by mmedenjak** [comment]
@vspatel we have log-structured based disk persistence as part of the enterprise edition - http://docs.hazelcast.org/docs/3.9.2/manual/html-single/index.html#hot-restart-persistence.
Can you elaborate what is the issue here?

**Comment by mmedenjak** [comment]
Closing the issue. Please open a new one and with an issue you are experiencing or elaborate this one.
