### ISSUE TITLE
client side OOME with ICMP detector enabled, and blocking only ICMP protocol 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12129]
just blocking icmp and not tcp, creates continues splits and rejoins

failing test 
https://hazelcast-l337.ci.cloudbees.com/view/icmp/job/block-icmp/15/console

/disk1/jenkins/workspace/block-icmp/3.10-SNAPSHOT/2018_01_09-16_27_16/block-icmp Failed

http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2018_01_09-16_27_16/block-icmp

http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2018_01_09-16_27_16/block-icmp/gc.html

output/HZ/HzClient3HZBB/HzClient3HZBB.hprof
output/HZ/HzClient4HZBB/HzClient4HZBB.hprof

**Comment by sancar** [comment]
Is this a valid use case scenario ? 
This is expected behaviour for me. The code wrote should work this way. 
But we need to decide if this is a problem. 

We have two detectors one is heartbeat the other is icmp. And assumption was that if icmp is failing, heartbeat can not work. Because icmp fail means machine is gone.

**Comment by sancar** [comment]
@tkountis What do you think ? 
What is the behaviour of our members in a similar scenario, when `hazelcast.icmp.parallel.mode` enabled ?

**Comment by Danny-Hazelcast** [comment]
@sancar it looks like a client side memory leak when a client is repeatedly connected and disconnected.  

it's just we see it quicker as using ICMP, we can get more connection / dissconection cycles in a short time, which then exposes the client side leak OOME

**Comment by Danny-Hazelcast** [comment]
also looking at the GC charts

http://54.82.84.143/~jenkins/workspace/block-icmp/3.10-SNAPSHOT/2018_01_09-16_27_16/block-icmp/gc.html

we see members are fine.

we see the clients on the smaller "merging" sub cluster "AA" do not show the issue

we see only the clients on the bigger "BB" cluster side have the OOME issue

**Comment by Danny-Hazelcast** [comment]
icmp fail means that maybe a sys admin in the data center decides to block ICMP one day.
but luckily the hazelcast cluster still stays up and survives the unfortunate scenario without issue

**Comment by sancar** [comment]
Indeed OOME is problem. I am looking into it. 

> icmp fail means that maybe a sys admin in the data center decides to block ICMP one day

But, I still am not convinced that we should take core the scenario where ICMP is blocked later. 
ICMP detector is implemented to make faster decision than our old one. 
If that is not working, client will take action immediately. I agree that client should not go OOME, but it will close/reopen lots of connections , and will not work properly. 

> but luckily the hazelcast cluster still stays up and survives the unfortunate scenario without issue

By this, if you mean, the problem will be detected and sys admin will remove the block on ICMP as solution, then we are on the same page.
