### ISSUE TITLE
HazelcastNamespaceHandler - missing multiple top-level types

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#12121]
The types array misses multiple top-level types, e.g. `serializer`. etc. 
Weird thing is that there were even data-structures missing there prior to 3.10, e.g. cardinalityEstimator. I don't know how/if `HazelcastNamespaceHandler` is used at all. 
This PR #12112 adds some of them, but there are still multiple missing.

It needs to be verified.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/11913

**Comment by mmedenjak** [comment]
`HazelcastNamespaceHandler` is used to register a parser for some spring namespace. For instance, `<hz:hazelcast id="...` is parsed with the `HazelcastInstanceDefinitionParser`.
`<hz:lock...`, `<hz:semaphore...` (when outside the `hz:hazelcast` tag) will be parsed by `HazelcastTypeBeanDefinitionParser`. The `HazelcastTypeBeanDefinitionParser` actually gets an instance of that data structure.

**Comment by blazember** [comment]
Reference doc also needs to be brought into sync.
