### ISSUE TITLE
All dynamic configs are sent out in a prejoin operation regardless of the cluster version

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#12151]
The `PreJoinOperation` is collected here:
https://github.com/hazelcast/hazelcast/blob/29954a17026e301c88326ccc89aaa2b909f1c481/hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/ClusterWideConfigurationService.java#L168-L179

It will collect all of the configurations regardless of the hazelcast version they were introduced in. For instance, 3.10 introduces `FlakeIdGeneratorConfig` as well as `PNCounterConfig`. Sending these to 3.9 members during rolling upgrade could cause errors.

OTOH not sending the configs might mean that some members will not have all of the configurations when the cluster version is switched to 3.10.

**Comment by jerrinot** [comment]
we should not allow adding dynamic configs for 3.10 structures when running in the 3.9 mode.
