### ISSUE TITLE
Hazelcast is stuck on IMap.putIfAbsent()

### ISSUE THREAD

**Issue by tzvatot** [hazelcast/hazelcast#12155]
I have a 2 node cluster of hazelcast (v.3.9).
Both nodes have stuck threads on HZ IMap.putIfAbsent():

Node 1 thread dump:
```
 "artemisTpTaskQueueListener-1" #84 prio=5 os_prio=0 tid=0x00007f40c5c7c000 nid=0x3c7d waiting on condition [0x00007f40a682d000]
        java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:417)
        at com.hazelcast.map.impl.proxy.MapProxySupport.putIfAbsentInternal(MapProxySupport.java:396)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:160)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:151)
```

```
"http-apr-8080-exec-5" #96 daemon prio=5 os_prio=0 tid=0x00007f40e4044800 nid=0x3c89 waiting on condition [0x00007f40a4923000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:417)
        at com.hazelcast.map.impl.proxy.MapProxySupport.putIfAbsentInternal(MapProxySupport.java:396)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:160)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:151)
```

Node 2 thread dump:
```
"artemisTpTaskQueueListener-1" #89 prio=5 os_prio=0 tid=0x00007efc19aa5800 nid=0x5383 waiting on condition [0x00007efbf5471000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:153)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:417)
        at com.hazelcast.map.impl.proxy.MapProxySupport.putIfAbsentInternal(MapProxySupport.java:396)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:160)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.putIfAbsent(MapProxyImpl.java:151)
```

Only restarting the cluster solved it.

**Comment by mmedenjak** [comment]
Hi @tzvatot ! Is the entry which is being updated locked ? Are you locking the map entries at all?

**Comment by tzvatot** [comment]
After the putIfAbset() is finish, code calls for tryLock().
So in case there's a dead lock, putIfAbsent() will be stuck?

**Comment by mmedenjak** [comment]
`putIfAbsent` only if some lock isn't released. You should check if all calls to `tryLock` are releasing the lock in all cases, including when there's an exception.

**Comment by tzvatot** [comment]
Seems like there was a condition that wrapped the unlock, and that might cause the issue.
Any API for listing all keys that are locked?
And possibly adding documentation for the putIfAbsent() that will be blocked in case the key is locked.

**Comment by jerrinot** [comment]
I wonder why `putIfAbsent()` is blocked at all. If they key is locked then it means the key is there -> the `put()` won't be performed -> no need to wait until the lock is acquired? 

@ahmetmircik: does it make sense?

**Comment by ahmetmircik** [comment]
@jerrinot yes it makes sense to not to block on an existing value. But lets see this:

Current behavior:

|  on the same key 	| t1  	|  t2 	|  t3 	| t4 |
|---	|---	|---	|---	|--- |
| T1	doing write under lock|  lock  	|  write	|   unlock 	|      |
| T2 	doing putIfAbsent|   	| wait unlock  | wait unlock | read latest write and return|

Your proposed behavior:

|  on the same key 	| t1  	|  t2 	|  t3 	| t4 |
|---	|---	|---	|---	|--- |
| T1	doing write under lock|  lock  	|  write	|   unlock 	|      |
| T2 	doing putIfAbsent|   	|  read what the value is at t2  |   ||

currently,  if `T2` tries to read at `t2`, it waits till `t4` to read. At that point `T2` reads  latest write by `T1`, but if we just return existing value as proposed, `T2` will not read last write but will have a fast response.

Although i don't know whether current behavior is documented somewhere, the suggestion seems to cause a behavior change and for this reason, maybe we can think to do it for 4.0.

**Comment by mmedenjak** [comment]
Agree with @ahmetmircik. This is a bigger change and I don't see this as a clear-cut decision. Some users might want to wait for the lock to be unlocked while some other might want to have a lock-free read. This may be a different method on the `IMap` or a configurable behaviour. Moving this to backlog to see if there is more community requests to implement such a feature.

**Comment by bitsofinfo** [comment]
experiencing the same

**Comment by bitsofinfo** [comment]
Please, when is an ETA on fixing this? Here i have a size call blocked for 5 minutes waiting on aother thread in putIfAbsent

```com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.awaitCompletion(InvokeOnPartitions.java:107)
com.hazelcast.spi.impl.operationservice.impl.InvokeOnPartitions.invoke(InvokeOnPartitions.java:76)
com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.invokeOnAllPartitions(OperationServiceImpl.java:385)
com.hazelcast.map.impl.proxy.MapProxySupport.size(MapProxySupport.java:723)
com.hazelcast.map.impl.proxy.MapProxyImpl.size(MapProxyImpl.java:109)```

**Comment by devozerov** [comment]
Hi, do we still target this for 4.0? If yes, is there a consensus on the correct behavior? To me, existing behavior appears to be sufficiently correct. In concurrent map data structures, users typically expect that access to the same key will be serialized in some way. This serialization mechanics is not concerned with the fact of whether the value is associated with the key or not. JDK's `ConcurrentHashMap` works this way - notice how it acquires an exclusive lock on the entry irrespectively of whether the key exists or not for all operations, including `putIfAbsent`.

Also please note that if the has locked the key, it doesn't mean that he will actually associate some value with it. It means, that if `putIfAbsent` is called in after the lock is acquired, but before the lock is released, we can neither apply nor fail it. Otherwise, the following sequence of events is possible:
T1: lock(K)
T2: putIfAbsent(K, V) -> return false
T1: unlock(K)

From T2 point of view, it would mean that some value was associated with the key, while it is not. I.e. we observe out-of-thin-air value.

So unless I misread the problem description, IMO current behavior is sufficiently correct. 

Please let me know what do you think about that.

**Comment by mmedenjak** [comment]
Yes, I was thinking the same thing. The user may lock an entry without creating the entry at all so the response might be wrong. The only reason why I chose to keep this issue open is to assess during 4.0 development if this behaviour was acceptable enough and if there were other operations that don't follow the same behaviour and should be aligned as I didn't do enough analysis of the bigger picture initially.

I think we can close this issue as wont-fix. For anyone interested, if you really want to read the current value without respecting the lock, you can use the `IMap#executeOnKey` methods which executes an `EntryProcessor` on a specific key. `EntryProcesssor`s don't wait for the lock on an entry to be released but instead can implement `LockAware` to get information if a lock is acquired or not.

cc @alex-dukhno 

Thank you for the analysis @ahmetmircik @devozerov !

**Comment by mmedenjak** [comment]
Keep in mind that this current lock-free behaviour of EntryProcessors might change as ideally we would like all operations to respect locks. But it won't change in 4.0 and I don't think it will change for a long time.
