### ISSUE TITLE
Additional parameters for Maploader

### ISSUE THREAD

**Issue by pavan2017** [hazelcast/hazelcast#12168]
I am using Maploader for my project to load data from database.
The following is an example 

```java
public class CustomerMapLoader implements MapLoader<String, Customer>{

	@Override
	public Customer load(String key) {
		System.out.println("load");
		return null;
	}

	@Override
	public Map<String, Customer> loadAll(Collection<String> keys) {
		System.out.println("loadAll"+keys);
		Map<String, Customer> map = new HashMap<String, Customer>();
		for(String key :keys){
			map.put(key, new Customer(key, "customer"+key));
		}
		return map;
	}

	@Override
	public Iterable<String> loadAllKeys() {
		return getList();
	}

	private Iterable<String> getList() {
		List<String> list = new ArrayList<String>();
		IntStream.range(1, 1000000).forEach(t->{
			list.add(String.valueOf(t));
		});
		return list;
	}

}
```

Maploader now doesnt take any additional parameters when loading.Lets assume that i need to load customers only some criteria.Lets say that i deploy same application on multiple servers i wanted to deal with customers based on country on different server?.How do i pass this additional parameters?I dont want to query everything and then filter ?Is it possible to add an additional parameter which takes list of arguments?

**Comment by mmedenjak** [comment]
Hi @pavan2017 ,

you can have a map loader implement the `MapLoaderLifecycleSupport` interface and initialise the map store with some configuration properties. You can then use these properties to invoke different database queries on different instances.

**Comment by mdogan** [comment]
As a similar alternative to `MapLoaderLifecycleSupport`, you can use `MapStoreFactory` too, to create different `MapLoader` impls according to configured properties.

See 
http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Data_Structures/Map/Loading_and_Storing_Persistent_Data.html for more info.

**Comment by pavan2017** [comment]
Is there any example of MapLoaderLifecycleSupport impl ?

**Comment by mmedenjak** [comment]
There's an example in this repo: https://github.com/hazelcast/hazelcast-code-samples/tree/master/distributed-map/mapstore

**Comment by pavan2017** [comment]
This doesnt solve my problem.It would be nice to have loadAllKeys with additional properties.I have solved my problem using System.Property for now.

**Comment by mmedenjak** [comment]
You should be able to initialise the map loader with properties set in your configuration, e.g.
```java
        <map-store enabled="true">
            <class-name>com.hazelcast.examples.MapStore</class-name>
            <properties>
                <property name="property1">property</property>
                <property name="jdbc_url">my.jdbc.com</property>
            </properties>
        </map-store>
```
And then you should get these properties when map loader is being initialised:
```java
    public static class MapStore implements MapLoaderLifecycleSupport, com.hazelcast.core.MapStore {

        @Override
        public void init(HazelcastInstance hazelcastInstance, Properties properties, String mapName) {
            // read properties here
        }

        ...

        @Override
        public Iterable loadAllKeys() {
            return null;
        }
    }
```
or by using the map store factory:
```java
public static class MapStoreFactory implements com.hazelcast.core.MapStoreFactory{

        @Override
        public MapStore newMapStore(String mapName, Properties properties) {
            // read properties here
            return new MapStore(...);
        }
    }
```

And you can then use those properties to affect how the call to `loadAllKeys` behaves. Please open an issue if you think this can be improved.

**Comment by ahmetmircik** [comment]
Hi @pavan2017, can you please also state what is wrong about suggested approaches above? Why did not they work in your case?

**Comment by pavan2017** [comment]
We are not using xml configuration.Is there anyway to do this in java config?i will try it and reopen and post the example if it doesn't work for me

**Comment by mmedenjak** [comment]
Yes, you can:
```java
MapStoreConfig mapStoreConfig = new MapStoreConfig()
                .setEnabled(true)
                .setImplementation(new SimpleMapLoader(size, true));
        mapStoreConfig.setProperty("property", "value");
        mapStoreConfig.setProperty("someOtherProperty", "otherValue");
```

**Comment by pavan2017** [comment]
Thank you .This worked perfectly for me :).I have one more question.When a map intialized or on first touch of map,loadAllKeys will executed.If i invoke loadAll(keys),still after loadAll is execueted,maploader still execuetes loadAllKeys .Is there anyway to control this.i dont want maploader to call loadAllKeys  when i invoke loadAll
