### ISSUE TITLE
Move channel creation responsibility to EventLoopGroup

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#12164]
Now there are 2 places to deal with different types of EventLoopGroup. One is to create the ChannelFactory and one is to create the EventLoopGroup.

If the EventLoopGroup would just create the channel, the whole factory can be deleted and we get rid of the duplication of logic

**Comment by pveentjer** [comment]
For this the ssl stuff needs to be fixed first.

**Comment by mmedenjak** [comment]
@pveentjer is this issue still valid with the new design?
