### ISSUE TITLE
Management Center not working behind Load Balancer

### ISSUE THREAD

**Issue by limsonmichael** [hazelcast/hazelcast#12206]
We have setup management center on multiple nodes behind a load balancer. Updated hazelcast.xml with the load balanced url. We see the data displayed on Management Center is not consistent. Sometimes all nodes in the cluster are visible, sometime only few are visible and sometimes none. 
After refreshing multiple times we get a message "make sure the management center url is configured to properly".
Does management center support deployment to multiple nodes?

**Comment by emre-aydin** [comment]
Hi @limsonmichael,

Management Center currently does not support deployment to multiple nodes. There is no central storage location for all the metrics data. Each instance stores metrics in its own memory (and persists it into its own filesystem if time travel is enabled). So if you want to see all metrics in each Management Center instance, you need to configure your load balancer to send all requests to each Management Center instance.
