### ISSUE TITLE
Introduce EntryEventType.LOADED

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#12224]
Jet streaming job listening on map ADDED events is triggered when previously evicted item is loaded from backing mapstore. Introducing LOADED event provides better job semantics so that ADDED event is fired only when application puts data to the map. 
See [discussion thread on Google Groups](https://groups.google.com/forum/#!topic/hazelcast-jet/aXhcXUud3tk).

**Comment by mdogan** [comment]
Related 
- https://github.com/hazelcast/hazelcast/issues/9348
- https://github.com/hazelcast/hazelcast/issues/1542#issuecomment-57153200

**Comment by dbrimley** [comment]
FYI, there is also work scheduled for 3.11 that will introduce finer grained controlled over event firing, plus there will be a LOADED event to signify a mapstore load rather than a put.

**Comment by ahmetmircik** [comment]
see https://github.com/hazelcast/hazelcast/pull/13181#discussion_r192969070

**Comment by lukasherman** [comment]
`EntryLoadedListener` looks good, looking forward to `eventJournal.writeLoadEvent`.

**Comment by mmedenjak** [comment]
Closing as the addition to event journal will now be tracked in https://github.com/hazelcast/hazelcast/issues/13667.
