### ISSUE TITLE
Merge policy cannot be defined for replicated maps with xml config

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#12223]
Currently, merge policy cannot be defined for replicated maps with xml configuration as `merge-policy` is missing in `hazelcast-config.xsd` for `replicatedmap`, and the same is true for xml based Spring configuration. The fix needs to be done in the following files: 
- `hazelcast-config-3.10.xsd`
- `hazelcast-spring-3.10.xsd`
- `ConfigXmlGenerator.java`
- `hazelcast-fullconfig.xml`
- `fullConfig-applicationContext-hazelcast.xml`
- `ConfigXmlGeneratorTest.java`

Related #12120

**Comment by Donnerbart** [comment]
The ReplicatedMap PR has not been merged yet. This should fix it: https://github.com/hazelcast/hazelcast/pull/12196

**Comment by blazember** [comment]
All listed places apart from `ConfigXmlGeneratorTest` have been covered by #12196.  Only that one is in the scope.
