### ISSUE TITLE
IMap.removeAll() doesn't support PartitionPredicate 

### ISSUE THREAD

**Issue by awakestu** [hazelcast/hazelcast#12238]
When trying to call removeAll with PartitionPredicate it results in UnsupportedOperationException

**Comment by dimas** [comment]
JFYI, Hazelcast is 3.9 and operation is invoked via client (so not directly on a member).

**Comment by blazember** [comment]
@awakestu and @dimas `IMap.removeAll()` does not support `PartitionPredicate`.
`PartitionPredicate` was added for some specific use cases and is not yet supported by each method accepting `Predicate`s. 

As an alternative, `IMap.executeOnEntries()` accepts `PartitionPrecicate`. With that, entries can be removed from the map by setting the value to `null` in the `EntryProcessor`. Does this fit in your use-case?

**Comment by dimas** [comment]
@blazember, thanks for the suggestion but we were not for other ways of going the same thing - we can just call `keySet()` with the predicate and then iterate over keys calling `delete` (and this is what we actually do).
Still, the fact that `removeAll` does not handle `PartitionPredicate` properly seems like an oversight not a feature than need defending :)
The `removeAll` javadoc does not mention anywhere that certain types of predicates are not supported and I do not see any reason not to support it properly. `keySet` handles it so why `removeAll` should not?
Cheers
