### ISSUE TITLE
3.9.3 member oome, (shutdown) create use destroy distributed objects 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12259]
we have test failed with OOME hprof for 3.9.3

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9.3/2018_02_02-00_59_21/stable/destroy/create-use-dist-destroy/

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9.3/2018_02_02-00_59_21/stable/destroy/create-use-dist-destroy/output/HZ/HzMember3HZ/

for this issue we just need to check the hprof,  if there is nothing unexpected we can closes this issue. 

this is the first time this test has failed with a member oome,

**Comment by Danny-Hazelcast** [comment]
3.9 version of the test 
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9/2017_10_20-17_17_19/stable/destroy/create-use-dist-destroy/gc.html


and 3.9.3 version of the test 
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9.3/2018_02_02-00_59_21/stable/destroy/create-use-dist-destroy/gc.html

**Comment by tkountis** [comment]
Regarding the 3.9.3 OOME, I am skeptical on the settings of this run
```
<property name="hazelcast.operation.backup.timeout.millis">120000</property>
<property name="hazelcast.operation.call.timeout.millis">600000</property>
```

These are not the same with the 3.9 run, and I can see quite a number of Invocations retained in the registry.

@danny can you reset these to the default values, especially the latter, to 1min instead of 10mins and re-run?

**Comment by Danny-Hazelcast** [comment]
I have rerun without timeout property's 

and got a `com.hazelcast.memory.NativeOutOfMemoryError: System allocations limit exceeded! Limit: 2048 KB, usage: 2048 KB, requested: 16 bytes` 

maybe as distributed object destroy from member size is not cleaning up client side near cache ?

```
HzClient2HZ _create-use-dist-destroy_createUseDistDestroy-Obj hzcmd.distributed.Destroy threadId=1 java.lang.Exception: com.hazelcast.memory.NativeOutOfMemoryError: System allocations limit exceeded! Limit: 2048 KB, usage: 2048 KB, requested: 16 bytes
```

but the NOOME came from hzcmd.distributed.Destroy  which is odd

i am now re running ignoring `com.hazelcast.memory.NativeOutOfMemoryError` to see if we still end up with a heap OOME

**Comment by Danny-Hazelcast** [comment]
I am also ignoring the operation timeout exception which is much easier to hit 
without the extended time out props

**Comment by tkountis** [comment]
@Danny-Hazelcast any update on the last run?

**Comment by Danny-Hazelcast** [comment]
the latest run https://hazelcast-l337.ci.cloudbees.com/view/stable/job/stable-x1/187/console
if no 'oome' then i think we can closes this issue

**Comment by Danny-Hazelcast** [comment]
ok no oome, just 

`fail HzClient2HZ _create-use-dist-destroy_createUseDistDestroy-Obj hzcmd.distributed.Destroy threadId=1 java.lang.Exception: com.hazelcast.memory.NativeOutOfMemoryError: System allocations limit exceeded! Limit: 2048 KB, usage:`

client near cache NOOME which is reported in a different issue. we can close this issue.
