### ISSUE TITLE
Adding Dynamic MapConfig From HazelcastClient omits timeToLiveSeconds value

### ISSUE THREAD

**Issue by skwangh** [hazelcast/hazelcast#12273]
When using HazelcastClient instance to add dynamic MapConfig, It generally works for most of other parameters but **timeToLiveSeconds parameter is always 0**.

I found [getConfig() method in com.hazelcast.client.impl.protocol.task.dynamicconfig.AddMapConfigMessageTask class](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/AddMapConfigMessageTask.java)
 is called by hazelcast cluster when I add dynamic MapConfig from client, but there is no code for timeToLiveSeconds.

Is it intended?

Hazelcast version : 3.9.2
Cluster size : 1
Number of the clients : 1 (seperated from cluster)
Version of Java : JDK 1.8
Operating system : Windows10 (for development)
Logs and stack traces : N/A
Detailed description of the steps to reproduce your issue : 
 1. Run cluster with default config.
 2. Run client and add dynamic MapConfig with some customized timeToLiveSeconds value using HazelcastClient instance
     ex)  hazelcastClient.getConfig().addMapConfig(mapConfig);
 3. Check config is added
     ex) hazelcastClient.getConfig().getMapConfigs();
 4. You can see mapConfig is added but timeToLiveSeconds is 0
Unit test with the hazelcast.xml file : N/A
integration module versions : Spring Boot 1.5.6 with embedded tomcat

**Comment by vbekiaris** [comment]
@skwangh this sounds like an omission, thanks for the awesome issue report. The fix should be pretty easy, we just need to transfer the `timeToLiveSeconds` value from `parameters` to the `Config` in `AddMapConfigMessageTask` as you noticed and add `timeToLiveSeconds` in the [`MapConfig` used in the related tests](https://github.com/vbekiaris/hazelcast/blob/6bbacb817016ec11652c891969bc2c5ef9ba18c7/hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java#L843). Fancy preparing a pull request?

**Comment by skwangh** [comment]
@vbekiaris , @mumukiller Thanks for your kindness and greate job! :)

**Comment by vbekiaris** [comment]
Fixed by #12276
