### ISSUE TITLE
split-heal brain / quorum OOME

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12278]
split heal quorum jenkins test job. 

this run https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/42/console 
Failed the multi Member OOME

http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_07-03_19_23/quorum/gc.html
```
output/HZ/HzMember3HZBB/HzMember3HZBB.hprof
output/HZ/HzMember1HZBB/HzMember1HZBB.hprof
output/HZ/HzMember2HZBB/HzMember2HZBB.hprof
```

in the failing run case, all 3 members of the "big" cluster oome'd,
and the small cluster GC is not looking to great also.

This is the first time I have seen an OOME from this test job. 

The main action needed is to check the hprof, to make sure we have not encountered a leak of some 
kind. 

and an example of a normal passing run,  the next job number using the same hazelcast jars. 
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/43/console
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_07-12_47_20/quorum/gc.html

**Comment by Danny-Hazelcast** [comment]
Checked hprof of HzMember1HZBB, there are 200 ring-buffer-containers and they are full at their capacity (10_000).  OOME seems normal under these conditions. A re-run can be done by setting capacity and number-of-ringbuffers a to lower value.


In the hprof, 50% of heap is full of ring-buffer and durable-executors internal task-ring-buffer


using a DurableExecutorService  `submit and future.get` while cluster is split and healed, it is expected that we have a memory leak


possible leak in the code, in the scheduledexec, we clean the running tasks, but not the backups.

**Comment by tkountis** [comment]
ScheduledExecutor side should now be fixed. Please re-run the test, and close if this works as expected. Then we can open individual tickets for each DataStructure that fails.

**Comment by Danny-Hazelcast** [comment]
running https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/45/console

will check the gc charts,

**Comment by mmedenjak** [comment]
@Danny-Hazelcast I am moving this test failure from the https://hazelcast.atlassian.net/wiki/spaces/PM/pages/144540336/Extend+Hazelcast+Split-Brain+Protection to the https://hazelcast.atlassian.net/wiki/spaces/EN/pages/207585505/Merge+Policies+for+Additional+Data+Structures+Design
since this doesn't seem related to the quorum protection but rather to the merge functionality.

**Comment by Danny-Hazelcast** [comment]
Runs with smaller heap produced OOME hprof.
```
hz memberOps "-Xms300M -Xmx300M ${hzProps}"
hz clientOps "-Xms100M -Xmx100M ${hzProps}"
```
however maybe the small heap is just to small, this could be a possibility.
but we should check over the OOME, to make sure we do not have a leak at the root cause. 

some very unusual member gc charts.
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_14-03_19_03/quorum/gc.html


./output/HZ/HzMember3HZBB/HzMember3HZBB.hprof
./output/HZ/HzMember5HZAA/HzMember5HZAA.hprof
./output/HZ/HzMember2HZBB/HzMember2HZBB.hprof


http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_14-03_19_03/quorum/

**Comment by mmedenjak** [comment]
There’s 100k+ of `TaskRingBuffer`s which hold the task or the result. Can you try running with something like:
- smaller partition count (less task ringbuffers)
- smaller `DurableExecutorConfig#setCapacity` (smaller ringbuffers)
- less number of executors (currently there’s 400 different executors)

**Comment by Danny-Hazelcast** [comment]
for this run https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/50/consoleFull

I disabled all Durable executor test.

GC charts still show a leak pattern.  but very slow
http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_15-00_35_09/quorum/gc.html


the heap sizes used was
```
hz memberOps "-Xms300M -Xmx300M ${hzProps}"
hz clientOps "-Xms100M -Xmx100M ${hzProps}"
```

very small heap for the 50 iteration loop test.

**Comment by tkountis** [comment]
@Danny-Hazelcast there is not much we can do here without some data. Can you maybe incorporate some periodic heap-dumps in your tests? (eg. beginning, middle, end) This way we can run an analysis on the dumps to see if we can spot any leaks.

**Comment by Danny-Hazelcast** [comment]
this run did get member hprof   http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_15-11_07_33/quorum/  but the heap is small so no so reliable
```./output/HZ/HzMember3HZBB/HzMember3HZBB.hprof
./output/HZ/HzMember2HZBB/HzMember2HZBB.hprof```

**Comment by Danny-Hazelcast** [comment]
I got another oome hprof, 

http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_02_14-13_52_08/all/gc.html

http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_02_14-13_52_08/all/output/HZ/HzMember3HZBB/

from https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-executors/6/console

this time using, `executor.retrieveAndDisposeResult(future.getTaskId());` which should be disposing the durable exe results ?

**Comment by Danny-Hazelcast** [comment]
@tkountis  so the above to OOME could to with a check over.

**Comment by Danny-Hazelcast** [comment]
run
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-quorum/52/console

results in OOME
output/HZ/HzMember1HZBB/HzMember1HZBB.hprof

http://54.82.84.143/~jenkins/workspace/split-quorum/3.10-SNAPSHOT/2018_02_21-03_19_02/quorum

**Comment by tkountis** [comment]
Having a look

**Comment by tkountis** [comment]
@Danny-Hazelcast can't see anything suspicious in the dump. I would have to blame the heap size as the first candidate. Do you mind doing a much longer run, but with reasonably sized heap?

**Comment by Danny-Hazelcast** [comment]
this run, with double size heap,

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-executors/23/console

GC
http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_05-10_45_53/executors/gc.html

looks like a leak style pattern, if slow.


and a 2nd issue, the test hangs at
```
[jenkins@ip-10-72-134-107 executors]$ pwd
/disk1/jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_05-10_45_53/executors
[jenkins@ip-10-72-134-107 executors]$ find . -name out.txt | xargs grep 'at hzcmd'
./output/HZ/HzClient6HZCC/out.txt:	at hzcmd.executor.scheduled.ScheduleGetDispose.timeStep(ScheduleGetDispose.java:28)
./output/HZ/HzClient5HZAA/out.txt:	at hzcmd.executor.scheduled.ScheduleGetDispose.timeStep(ScheduleGetDispose.java:28)
```

**Comment by mmedenjak** [comment]
Possible causes for the hanging - https://github.com/hazelcast/hazelcast/issues/12197#issuecomment-370474846

**Comment by tkountis** [comment]
@Danny-Hazelcast  regarding the leak, please run for even more time. If it is indeed a leak, then it will eventually fail.
As for the hanging, will investigate as part of #12197 (Thanks @mmedenjak )

**Comment by Danny-Hazelcast** [comment]
@tkountis  after a very long time we did get an OOME

http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_05-16_54_27/executors/gc.html

hprof
http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_05-16_54_27/executors/output-oome/HZ/HzMember5HZAA/


leak is so small maybe it's not important ?

**Comment by tkountis** [comment]
Had another look at the new hprof.
I don't see anything suspicious about leaks. Most of the heap is occupied by Scheduled Executor related stuff, and I noticed that your config is, 3 backups, 100 tasks capacity / partition, 271 partitions & 200 executors => up to 16,260,000 items in under 500MB of heap! This looks like running out of space, rather than a leak.

**Comment by tkountis** [comment]
@Danny-Hazelcast I reckon this is not an issue (based on the comment above regarding the config, and the fact that we can't spot a leak in the dumps). I am comfortable enough to close this, for now, and if we have any stronger evidence down the line we can re-open. Your thoughts?

**Comment by mmedenjak** [comment]
Can we run this with a more sensible config (bigger heap, smaller backup count, smaller capacity, smaller executor count) and see if there is still a leak?

**Comment by tkountis** [comment]
@Danny-Hazelcast whats the update here? Did you have another go with @mmedenjak suggestion above?

**Comment by Danny-Hazelcast** [comment]
I made this run, using 1G member heap.  first hour of the run we used a stable cluster.
then we made 200 split heal cycles.

https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-executors/26/console

script
http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_07-15_32_59/executors/go


GC results 
http://54.82.84.143/~jenkins/workspace/split-executors/3.10-SNAPSHOT/2018_03_07-15_32_59/executors/gc.html

members show classic leak pattern.  if very small
clients show classic saw pattern. 


in the test.
we should have a limit to the number of concurrent executor jobs that can be inprogress.
as all the drivers submit a job, and then get the results and try to dispose the results.

e.g.
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/executor/regular/SubmitToAllAndUse.java


so the max number of concurrent executors in progress, is caped by the number of test drivers by the number of threads used.

4 clients,  12 tests 4 threads each,  should be 192 concurrent executors over the cluster of 4 members.

**Comment by tkountis** [comment]
@Danny-Hazelcast I had another look at the older hprof in here, and I noticed that there are 30k tasks in a completed state in there. That got me thinking about the leak. I checked the benchmark code and saw that you are creating and disposing tasks, so my question is when you split the cluster in between creating and disposing, if the task is not available on the half cluster that you are communicating with, your dispose command will just come back with a StaleTaskException, therefore its not disposed. Once the cluster forms back again, you will still have the task in the heap. That could explain the small leak you are seeing, but could you verify my logic? Is what I am describing accurate? If so, you can always call a dispose on the `getAllScheduledFutures` from the executor after the healing.

**Comment by Danny-Hazelcast** [comment]
@tkountis, yes I think this is the cause of the slow leak.  

I could add a `getAllScheduledFutures` thread, which calls dispose to clear up any "lost" tasks

**Comment by tkountis** [comment]
Awesome, let me know if you can verify that, so we can close this :+1:

**Comment by mmedenjak** [comment]
@Danny-Hazelcast can you verify your hypothesis for the leak?

**Comment by Danny-Hazelcast** [comment]
I think i can run another thread which gets all scheduled futures and dispose them.

**Comment by Danny-Hazelcast** [comment]
adding a thread for gets all scheduled futures dispose really changes the type of test.
as the "leak" is very slow its not so much of and issue.

is there are way we can fix the underlying issue of ```if the task is not available on the half cluster that we call dispose one, can we stop the `StaleTaskException` and in face dispose of the completed future

**Comment by tkountis** [comment]
I can think of many reasons why this would be an even bigger issue:
- Keeping the task name for pending disposal (sth like tombstones) after split healing is yet another leak
- Disposing of the task on the other half, after the healing it's dangerous. What if the task legitimately existed in both clusters?

For my point of view, the leak is similar to destroying a distributed object e.g (AtomicLong) on half of the brain, where it doesn't exist.

Furthermore, I believe we are interacting with the end-user by throwing a relevant exception i.e. StaleTaskException and we also provide the APIs to support future disposal of the task, by `getAllScheduledFutures` after healing.

To close this, due to the nature of this leak, a tight loop of scheduling/disposal tasks during split/heal phases, I see no reason to further invest time on addressing sth that fairly looks like a leak, but isn't. Do you have any objections? @Danny-Hazelcast @mmedenjak

**Comment by mmedenjak** [comment]
Moving into 3.10.1 for now. I mostly agree with Thomas but I'll take a closer look later.

**Comment by Danny-Hazelcast** [comment]
ok i agree,
