### ISSUE TITLE
Docker Swarm Support based on Member Address Provider SPI

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#12275]
[Member Address Provider SPI](http://docs.hazelcast.org/docs/3.9.2/manual/html-single/#member-address-provider-spi) is a new SPI released with Hazelcast 3.9 version. It basically allows you to define the bind and public address when starting the hazelcast instance dynamically instead of defining it statically via `<public-address>`

We need Docker Swarm Support based on new SPI.

see https://github.com/hazelcast/hazelcast/issues/9219#issuecomment-310205252

**Comment by bitsofinfo** [comment]
Its already at: https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi

**Comment by mmedenjak** [comment]
@mesutcelik any idea when we could have this implementation? Can we set a milestone?

**Comment by mesutcelik** [comment]
We do not have any priority so I am setting milestone to Backlog.

**Comment by mesutcelik** [comment]
No plan to implement this in future.
