### ISSUE TITLE
Fail-fast when custom merge policy is not appropriate

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#12284]
now failure happens when trying to merge clusters, seems too late to detect a wrongly implemented merge policy

For example this works without exception now:
```
Config config = new Config();
QueueConfig queueConfig = config.getQueueConfig("test");
queueConfig.getMergePolicyConfig().setPolicy(Object.class.getName());

HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
IQueue<String> queue = instance.getQueue("test");
queue.offer("one");
```

**Comment by Donnerbart** [comment]
This is already a checkpoint in the overview issue and will be fixed soon by PR: https://github.com/hazelcast/hazelcast/issues/11969

**Comment by mmedenjak** [comment]
@Donnerbart is this fixed by https://github.com/hazelcast/hazelcast/pull/12347?

**Comment by Donnerbart** [comment]
Oh, it could be that I forgot to add that "is no merge policy at all" check. Let me try this, otherwise I'll prepare a fix.

**Comment by Donnerbart** [comment]
Yeah, the check is missing, but it's not sooo easy to implement. The config is just a String and in the `ConfigValidator` we don't have the `NodeEngine` to access the `SplitBrainMergePolicyProvider`. I'll try to figure out a clean solution for this.

**Comment by ahmetmircik** [comment]
@Donnerbart maybe we can also check it in this method: https://github.com/hazelcast/hazelcast/blob/1063f895476ee78fd129e3f28667e1ae40355f57/hazelcast/src/main/java/com/hazelcast/internal/config/ConfigValidator.java#L302

**Comment by Donnerbart** [comment]
After the next design improvement, there might anyway be other checks necessary (e.g. if the data structure can provide the required value types which the merge policy needs). So this is still on my todo, yes.

**Comment by Donnerbart** [comment]
Will be fixed by https://github.com/hazelcast/hazelcast/pull/12573
