### ISSUE TITLE
ClientConsoleApp class is missing a test

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#12298]
Add a test for ClientConsoleApp

**Comment by mumukiller** [comment]
Looks like a lot of methods in ClientConsoleApp are duplicated in ConsoleApp. What's the reason to have both classes?

**Comment by sancar** [comment]
These are classes that are implemented for demonstration purposes. I am guessing that we want everything in the same place to make the presentation easier. But right now, it does not seem bad to make ClientConsoleApp extend to ConsoleApp reuse almost every method. I think this small change does not affect presentation also.

**Comment by KowalczykBartek** [comment]
initial PR here https://github.com/hazelcast/hazelcast/pull/16712

**Comment by Holmistr** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/16712
