### ISSUE TITLE
Document removing entries via EntryProcessors

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#12320]
It is supported to remove entries from an `IMap` by executing `EntryProcessor`s on the map, which nulls the Entry's value. This, however, isn't officially documented by either the reference manual, the `IMap` or the `EntryProcessor` javadoc. This feature should be clearly documented in the above-mentioned places.

Triggered by #12238.

**Comment by Serdaro** [comment]
https://github.com/hazelcast/hazelcast-reference-manual/commit/f4185e903a59dd466343e0c02676376417a2931b

**Comment by Holmistr** [comment]
@Serdaro :rocket: Fantastic. Closing this issue as solved.
