### ISSUE TITLE
DurableExecutorService.retrieveResult(...).isDone() always returns False

### ISSUE THREAD

**Issue by adamlwgriffiths** [hazelcast/hazelcast#12368]
I'm seeing an issue similar to #850.
I'm running Java 8 and Hazelcast 3.9.2 while performing the checks on the client.

I submit tasks and return a series of Job IDs.
When I later come back to check on them, I call `retrieveResult(jobid);` and check `.isDone()`.
But `isDone` always returns `false`.

However, if I call `.get()` first on the future before calling is `.isDone()`, I will get then the appropriate result from `isDone`.

I've had a quick look and it doesn't seem there are any tests that check for this. They only seem to assert that `get` returns a valid result, but not `isDone`.

**Comment by adamlwgriffiths** [comment]
I can use the `.get(time, unit)` method as a work around.
* Fails -`f.get(0, TimeUnit.NANOSECONDS)`
* Fails -`f.get(1000, TimeUnit.NANOSECONDS)`
* Works -`f.get(10000, TimeUnit.NANOSECONDS)`
* Fails -`f.get(1, TimeUnit.MICROSECONDS)`
Obviously the future is doing some asynchronous call, but I have no desire to add some "it sort of works" hack, nor do I want to introduce artificial latency to a check such as this.

`.isDone` should query the completion state of the job and block until such time it can actually determine the state.

**Comment by tkountis** [comment]
@adamlwgriffiths the `isDone` API is unfortunately not supported for the DurableExecutor. The Future you are getting is the future representing the in-flight operation to fetch the result (i.e., `retrieveResult`), and has nothing to do with **your** task/job. You could switch to `IScheduledExecutor` which supports `isDone`, simple schedule a task with 0 delay, and this will behave as a submit.

There are plans to unify the executors in the future in one service, so you wont have to choose in the future.

**Comment by adamlwgriffiths** [comment]
I cannot get a task by ID with any other executor except for DurableExecutor.
This API is infuriating.

**Comment by tkountis** [comment]
You can take an ID from the IScheduledFuture see http://docs.hazelcast.org/docs/3.8/javadoc/com/hazelcast/scheduledexecutor/IScheduledFuture.html#getHandler--v

The handler can be serialized into a string using `handler.toUrn()` (http://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/scheduledexecutor/ScheduledTaskHandler.html#toUrn--) and you can re-construct it by using the static helper (http://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/scheduledexecutor/ScheduledTaskHandler.html#of-java.lang.String-).

With that in functionality in mind, you can access the task again at any given time by calling (http://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/scheduledexecutor/IScheduledExecutorService.html#getScheduledFuture-com.hazelcast.scheduledexecutor.ScheduledTaskHandler-)

One thing that you need to keep in mind is to always `dispose` the task once it finishes its job. 
Hope this helps:

```
IScheduledExecutorService executorService = instance.getScheduledExecutorService("my-scheduler");
IScheduledFuture future = executorService.schedule(new PlainCallableTask(), 0, SECONDS);
String taskId = future.getHandler().toUrn();
        
// Retrieve back the task with that id
IScheduledFuture secondFuture = executorService.getScheduledFuture(ScheduledTaskHandler.of(taskId));
```

**Comment by adamlwgriffiths** [comment]
Excellent, thank you! This has been driving me nuts for days
