### ISSUE TITLE
IMap MBean is not created when client reconnects to cluster 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#12417]
MBean for IMap is not created when client uses cached map proxy. 

When the client disconnects from the cluster, it does not clear the cache for distributed object proxies. To get a proxy for a distributed object, we see [proxyManager.getOrCreateProxy(serviceName, name)](https://github.com/hazelcast/hazelcast/blob/96c028f5aeecd278f57b950991018f5bb97b95bc/hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java#L706) is called. 
Then in getOrCreateProxy, proxy is obtained from [cache](https://github.com/hazelcast/hazelcast/blob/96c028f5aeecd278f57b950991018f5bb97b95bc/hazelcast-client/src/main/java/com/hazelcast/client/spi/ProxyManager.java#L295).  

The scenario as follows: 

Member is up with JMX enabled. Client connects and creates a map. In a for loop, it puts data to map. 
MBean for the map is monitored via JMX. 
Member is restared. 
Client reconnects to member and continues to put entries on the map. 
Now, MBean cannot be monitored via JMX. 
Here expectation is the recreation of MBean after client reconnects and operates on the map.

**Comment by jerrinot** [comment]
I assume this is an issue only when there is a single cluster member? is it correct? 

as when you have a multiple members and restart one of them then on a join it'll receive a list of created distributed objects.
