### ISSUE TITLE
After RU completed, PQ configured `ISet` does not behave as expected, when cluster size drops below required quorum size

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#12434]
Initial Cluster information
```
Size: 3
Version: Hazelcast 3.9.2
Client Count: 1
Client Docker : FROM openjdk:8-slim (debian)
Member Docker: FROM openjdk:8-jre (debian)
Client log level: DEBUG [slf4j]
Member log level: ALL [jdk]
```
Steps:
1] Sanity check for HZ 3.9.2-EE cluster has member count 3 and all of them `active`
2] Run RU to HZ 3.10-SNAPSHOT EE
3] Verify no exceptions and failures during RU
4] Sanity check on 3.10-SNAPSHOT EE
5] Apply network delays to 2 members of cluster
6] Verify that cluster size drops to `1` that is below quorum size of `ISet`. `ISet` also uses PQ for 3.10-SNAPSHOT EE configuration
7] Collect statistics for 20 secs 
8] Expect Quorum exceptions only

However we got below statistics
```
QuorumStatistics(success=158, failures=0, exceptions=0, quorumExceptions=79)
```
`success` metrics greater than `0` is not expected.

Please note that when we apply below quorum setting in 3.10-SNAPSHOT configuration for `ISet` we got **all** Quorum exceptions as expected
```
<quorum enabled="true" name="pq">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
    </quorum>
```

Test repo can be found [here](https://github.com/hazelcast/hazelcast-qe/tree/master/it/shorten-split-brain-detection)
Test case can be found [here](https://github.com/hazelcast/hazelcast-qe/blob/master/it/shorten-split-brain-detection/runner/src/test/java/com/hazelcast/shorten/split/brain/it/runner/ShortenSplitBrainDetectionTest.java#L142-L178)
Logs are attached as below
[Archive.zip](https://github.com/hazelcast/hazelcast/files/1761703/Archive.zip)

Logs for members are also follow RU pattern, which means member `1` is upgraded with `4`.
```
1->4
2->5
3->6
```

**Comment by lazerion** [comment]
@mmedenjak do we need to add 3.10 milestone tag for it?

**Comment by mmedenjak** [comment]
Yes, whenever you open an issue, please put labels and the milestone so it can be picked up. You can also put in the current milestone so it's looked into soon and moved if it's not related to current milestone. Issues without any label or milestone are easily overlooked.

**Comment by vbekiaris** [comment]
`ISet` was not protected by quorum in version 3.9. In order for quorum protection to apply, after upgrading all members to codebase version 3.10, and before introducing network delays, the cluster version must be upgraded to 3.10 using eg `cluster.sh`:
```
cluster.sh -o change-cluster-version -v 3.9 -a 172.16.254.1 -p 5701 -g groupname -P grouppassword
```

Once the cluster is in cluster version 3.10, the new quorum protections are applied properly.

**Comment by lazerion** [comment]
@vbekiaris thanks for guidance. I added required changes, we are now validating expectation successfully.
