### ISSUE TITLE
Initializing cluster partition table arrangement… in Hazelcast 3.9.1 takes too long

### ISSUE THREAD

**Issue by nitineman** [hazelcast/hazelcast#12433]
I am trying to create a Hazelcast service Project wherein I will be subscribing to a RDBMS (Oracle DB 12c) datastore, create a POJO/Java Bean on the fly using reflection and then parsing that Java Bean object to map the JDBC ResultSet as Result row values into the Java Bean object and load those mapped objects into the Distributed Map.

I checked the data volume of the two tables from which I'm trying to load in the Hazelcast IMap and it is as low as 0.0625 and 0.0316 MB. So this is a simpler Hazelcast implementation just initializing two parallel instances/nodes on localhost.

I'm timing in the Java Main method the total run time from the instant the Java POJO class is created and each of the corresponding Object is created and loaded in the Hazelcast IMAP.

In my understanding, this is taking too long from a system perspective because we are seeing similar behavior even in test and prod boxes with system specs 3 to 4 times better than the one given below. Kindly help giving suggestions on whats wrong with or is this a usual for the first time partitioning within a hazelcast IMDG with 2 nodes in a cluster.

The system specifications are as follows:

Macbook Pro 2014 Processor: 2.6 GHz Intel Core i5 Memory: 8 GB 1600 MHz DDR3

Please find the logs...

Feb 26, 2018 10:30:39 AM com.hazelcast.internal.partition.impl.PartitionStateManager INFO: [xx.xxx.xx.xxx]:5702 [dev] [3.9.1] Initializing cluster partition table arrangement... Number of entries in userMaster Map: 883

Number of entries in userMaster Map: 7499

Duration approx was:92520 milliseconds Feb 26, 2018 10:32:10 AM com.hazelcast.core.LifecycleService INFO: [xx.xxx.xx.xxx]:5701 [dev] [3.9.1] [xx.xxx.xx.xxx]:5701 is SHUTTING_DOWN

**Comment by mdogan** [comment]
Hi @nitineman;

Where this `Number of entries in userMaster Map ... ` log comes from? Are you using `MapLoader`/`MapStore`? Or are you loading data from DB to `IMap` yourself?

`PartitionStateManager: Initializing cluster partition table arrangement ` log is printed for initial partition table assignment and completes almost immediately, you can't even see how much it takes from the logs.

**Comment by nitineman** [comment]
Hi, I tried creating MapLoader with different Server and client jars running on the same machine with `loadAllKeys()` implemented with correct keySet() - Primary Key(ID) for the remote RDBMS to which its connected. Is this called when the server (Hazelcast Instances are created) through a separate jar or when the client is called. 

`<map name="userMaster"> <map-store enabled="true" initial-mode="EAGER"> <class-name>com.apple.sci.opfcache.beans.JPojo</class-name> </map-store> </map>`

 The above was the config in hazelcast.xml of the server to run. Let me know where I might be going wrong.

**Comment by nitineman** [comment]
The issue was with the ResultSet of JDBC fetching only 10 records in one I/O trip to DB.

When increased to let's say 1000 or more its much better.
