### ISSUE TITLE
ProxyManager won't remove Proxy even after original distributed object destroyed.

### ISSUE THREAD

**Issue by ghqian** [hazelcast/hazelcast#12470]
This seems to be a bug.

ProxyManager won't remove Proxy even after original distributed object destroyed.
This caused memory leak after long time such as 1 month.

The only removing event happens when hazelcast client instance call the getDistributedObjects function.
https://github.com/hazelcast/hazelcast/blob/e0ea8ed98b3c30d4e8a03d38fc6fd9c6bca57574/hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java#L661

To avoid memory leak we had to call getDistributedObjects function in distributedObjectDestroyed event in our program.

**Comment by z-guohui-qian** [comment]
I think what I mentioned is problem of hazelcastclient not hazelcast server.
I am not sure  how ProxyRegistry.destroy() can fix this problem.
Can you please check it again?

**Comment by sancar** [comment]
This is because we do not listen distributed objects by default on clients. When a distributed object removed in a remote server, client has no idea. getDistributedObjects makes a remote call and cleans up the leftovers locally. Your solution is the correct workaround for this. 
As a solution, we could add a distributed object listener internally or have a scheduled task to run periodically and collect the leftovers.

**Comment by sancar** [comment]
We have reverted the fix because it caused more serious problems. Since correct fix for this issue requires much more time and work, we are postponing the fix to a later release.

**Comment by mmedenjak** [comment]
Closed by mistake.

**Comment by asimarslan** [comment]
related issue https://github.com/hazelcast/hazelcast/issues/14571

**Comment by ihsandemir** [comment]
A possible solution (as reliable as the event system):
Client registers distributed object listener similar to membership listener.
The client only acts upon the `distributedObjectDestroyed` and destroys the local proxy based on this event.
The server side will NOT send event to the original client which issued the destroy request but the server will send the event to other clients. 

This solves the order problem when a client does:
Create
Destroy
Create

We are NOT solving the case if the destroy is from another client.

**Comment by sancar** [comment]
Fix is reverted by https://github.com/hazelcast/hazelcast/pull/16559 and postponed to 4.1
