### ISSUE TITLE
`WanPublisherConfigDTO` doesnt handle discovery strategies

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#12505]
`WanPublisherConfigDTO` doesnt handle discovery strategies so cloud deployed clusters utilizing cloud discovery, like AWS for WAN, cannot be created dynamically.  This impacts the ability of customers to create new clusters on-the-fly and closes off an avenue to blue/green deployments

**Comment by burakcelebi** [comment]
Closed as internal request.
