### ISSUE TITLE
Make MemberMap.SINGLETON_MEMBER_LIST_VERSION value configurable

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#12528]
`FlakeIdGenerator` relies on `nodeId`, which is currently automatically assigned. It would be helpful to set up  a different base member ID for certain use cases, so that flake IDs generated are always unique, even when generating nodes are not participating in the same cluster.

**Comment by viliam-durina** [comment]
I suppose you are referring to the use case mentioned [here](https://groups.google.com/forum/#!searchin/hazelcast/node%7Csort:date/hazelcast/h0t7b45TnuQ/suqgHzHbAAAJ):

>The scenario is A/B type deployment, where old application cluster version A is still running and new separate application cluster version B goes from standby to running mode. For a limited period of time there is possibility for A and B clusters to generate duplicate IDs. 

There's one solution available out of the box right now: `FlakeIdGeneratorConfig.setIdOffset()`. If you can cap the time during which A & B will both generate IDs, you configure the ID offset for cluster B as follows:

    idOffset = DAYS.toMillis(parallelRunLength) << 22;

22 is the number of bits reserved for nodeId and sequence in the ID.

**Comment by lukasherman** [comment]
It would effectively modify the timestamp part of the generated ID, right? We are using timestamp part to identify datastore partition where data should be persisted, at least on yy-mm-dd level. This is great FlakeId feature. 
{{FlakeIdGeneratorConfig}} seems like a great place to put {{nodeIdOffset}}.

**Comment by viliam-durina** [comment]
Yes, it modifies the timestamp part of the ID.

**Comment by pveentjer** [comment]
Does this need to be resolved in the 3.10 time window? It seems that it an improvement of an existing feature. So unless we need to break API's, I'm suggesting to move this task to 3.11 (or 3.10 maintenance if it is low risk and high value).

**Comment by metanet** [comment]
We handled this request with a small addition into the flake id configuration without breaking any existing API.

**Comment by lukasherman** [comment]
Thanks, it looks good.
