### ISSUE TITLE
CACHE_ON_UPDATE policy breaks near-cache consistency

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#12548]
see https://github.com/hazelcast/hazelcast/issues/9735

**Comment by Holmistr** [comment]
I have ignored the test from https://github.com/hazelcast/hazelcast/issues/9735 . The root cause is in this issue's subject. Please don't forget to re-enable the test once the root cause is fixed.

**Comment by mmedenjak** [comment]
@ahmetmircik how critical is this? Do we need to address this in 3.11?

**Comment by ahmetmircik** [comment]
@mmedenjak yes, it is critical and is on my todo list for 3.11.

**Comment by dbrimley** [comment]
Could we please make sure this does make it into 4.0.  I consider this critical.
