### ISSUE TITLE
Client count is not retrieved as expected from ExecutorService, when cluster join burst and collapse triggered

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#12556]
```
Version: Hazelcast 3.10-SNAPSHOT
Client Count: varies during test
Clients Docker : FROM openjdk:8-slim (debian)
Member Docker: FROM openjdk:8-jre (debian)
Client log level: INFO [slf4j]
Member log level: ALL [jdk]
```
Steps:
1] Cluster up with 2 set of member cluster and client cluster
1.1] Set 1 contains 5 member and 5 client
1.2] Set 2 contains 1 member and client
1.3] `hazelcast-client_1` postfix client also used as probe
2] Wait for above cluster to form up regarding members
3] Scale `set 1` to `0` both members and clients
4] Scale `set 2` to `5` both members and clients
5] Wait for member count to reach `5` ✅ 
6] Wait for client count to reach `6` since we have a client that is used as probe. 🛑 

As you may see logs from `hazelcast-client_1`, client count does not reach to expected count within 40 secs in attached logs, we also conducted same for 2 mins also, result did not change.
Please also note that `step 6` test fails are not stable producible, they generally pass.

We get client uuids from ExecutorService as below
```
IExecutorService executorService =
                client.getExecutorService(RandomStringUtils.randomAlphabetic(42));
        Map<Member, Future<Set<String>>> futures = executorService
                .submitToMembers(new Retrieval(), client.getCluster().getMembers());
        Set<String> clients = futures.values().stream()
                .map(it -> {
                    try {
                        return it.get();
                    } catch (InterruptedException | ExecutionException e) {
                        logger.error(e.getMessage());
                        return Collections.<String>emptySet();
                    }
                })
                .flatMap(Collection::stream)
                .collect(Collectors.toSet());
        logger.info("Clients count after executor service {}", clients.size());
        return clients;
```
You may find `Retrieval` class code [here](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-resource-management/uuid-task/src/main/java/com/hazelcast/it/client/resource/management/uuid/task/Retrieval.java)
I believe I am missing a configuration setting, could you please guide me?

Test repo can be found [here](https://github.com/hazelcast/hazelcast-qe/tree/master/it/client-resource-management)

Test case can be found [here  as clientShouldBeIntactWhenClusterCollapseAndBurst](https://github.com/hazelcast/hazelcast-qe/blob/master/it/client-resource-management/runner/src/test/java/com/hazelcast/it/client/resource/management/runner/ResourceManagementTest.java#L113). 

Logs and configs are attached below contains members and clients logs after scale burst completed.
Log postfixed with `hazelcast-client_1` is a client and always up during above test execution time window.
Log postfixed with `hazelcast-2_1` is a member and always up during above test execution time window.
[scale.burst.zip](https://github.com/hazelcast/hazelcast/files/1799257/scale.burst.zip)

**Comment by sancar** [comment]
It looks like one of the clients can not connected back to cluster. In that case count is expected. 
To make the test more reliable, can you increase connection timeout and connection attempt limit of clients in these tests ?
Connection timeout could be around 1 minutes
http://docs.hazelcast.org/docs/latest-development/manual/html/Hazelcast_Clients/Java_Client/Configuration/Client_Network.html#page_Setting+Connection+Timeout
Connection attempt limit could be something like 100
http://docs.hazelcast.org/docs/latest-development/manual/html/Hazelcast_Clients/Java_Client/Configuration/Client_Network.html#page_Setting+Connection+Attempt+Limit
Note that default connection timeout and attempt limit is starting to be a problem in our pr builders also. And this issue is already in the scope of client team.

**Comment by pveentjer** [comment]
It seems this issue is a configuration issue that can be solved by applying the suggested configuration changed. I'm proposing to close this task for the time being. If the TS still has problems after applying the changes, we should re-open it.

**Comment by jerrinot** [comment]
@lazerion: can you please try what @sancar suggested?

**Comment by lazerion** [comment]
@sancar we can close it based on your comment
```
Note that default connection timeout and attempt limit is starting to be a problem in our pr builders also. And this issue is already in the scope of client team.
```
