### ISSUE TITLE
IMap `replace` could fail if the Map entry is a Hash collection

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast#12574]
Reproducer
```java
HazelcastInstance instance = Hazelcast.newHazelcastInstance();

IMap<String, Collection<String>> store = instance.getMap("store");

Collection<String> val = new HashSet<>();
val.add("a");

store.put("a", val);

Collection<String> oldVal = store.get("a");

byte[] dataOld = ((HazelcastInstanceProxy) hz).getSerializationService().toBytes(oldVal);
byte[] dataNew = ((HazelcastInstanceProxy) hz).getSerializationService().toBytes(val);

System.out.println(Arrays.equals(dataNew, dataOld));
```

Due to optimization is `HashSet.readObject` method,  initial serialized byte[] and des/ser byte[] is different.  This causes multiple issues, like `replace` method fails & infinite loop case as described in #12557. Hazelcast have an `ArrayList` serializer but don't have one for Hash collections, like HashSet/HashMap. The only permanent solution is to implement one. We can simply create a `Collection` serializer & all collections can extend it & implement only collection creation part.

**Comment by mmedenjak** [comment]
> Hazelcast have an ArrayList serializer but don't have one for Hash collections, like HashSet/HashMap. The only permanent solution is to implement one. We can simply create a Collection serializer & all collections can extend it & implement only collection creation part.

@ihsandemir can you check if this issue is solved now?

**Comment by mmedenjak** [comment]
@ihsandemir any updates ? Have you checked this out?

**Comment by ahmetmircik** [comment]
Closing this issue, i tested it and it is working as expected on 4.0. 
Fixer PR is here for further info: https://github.com/hazelcast/hazelcast/pull/15371
