### ISSUE TITLE
Missing Map Config validation

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#12588]
Currently the cluster does not validate map configs and it has the potential of making a cluster unstable if a cluster accepts nodes with different map configs. 

For example, cluster has Map A with 1 backup. A member joins with backup count = 0 for this Map A. In current scenario, this member will be allowed to join the cluster and no backup partitions will be created on this member. And more such members will cause imbalance in cluster.

Capability of cluster operating smoothly in this situation is unknown.

MapConfig validation existed (but broken) until this:
https://github.com/hazelcast/hazelcast/issues/3257
https://github.com/hazelcast/hazelcast/pull/3300

**Comment by dbrimley** [comment]
We should be doing some kind of hash on certain parts of config rather than the whole for example some elements of config could be different per member such as networking but certainly map configs should be the same.  hashed and compared on joining.

**Comment by mmedenjak** [comment]
The work put into this should be extended to all structures. I wouldn't like to see config validation for one structure but not the other.

**Comment by burakcelebi** [comment]
Closed as internal request.
