### ISSUE TITLE
IOUtil.compress hangs on input [0, 0, 0, 0]

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#12611]
looks like a bug in JDK, but you better to know about it. I encountered it when tried to writeInt(0) and then compress it via HZ IOUtil. JDK 1.8.x
 it hangs at line 228:
```
            int count = compressor.deflate(buf);
```
and totally utilises one CPU core

**Comment by mdogan** [comment]
This is a bug in ` IOUtil.compress(..)` method. `ByteArrayOutputStream` and temp `byte[]` are created with capacity `input.length / 10`. In this case, `input.length / 10 == 0`. That's why deflate loop never ends.

```java
        ByteArrayOutputStream bos = new ByteArrayOutputStream(input.length / 10);
        byte[] buf = new byte[input.length / 10];
```

**Comment by dsukhoroslov** [comment]
I see. Please add a unit test for this edge case :)
