### ISSUE TITLE
High network usage when app is idle

### ISSUE THREAD

**Issue by ndjordjevic** [hazelcast/hazelcast#12630]
Hi,

I'm using hazelcast as a hibernate's second level cache for a java/spring application deployed to AWS. When the second or more instances (the hazelcast nodes as well) are added I noticed the high network traffic even when the app is idle... Is that normal? ... Traffic goes 6-7MB approximately... Is hazelcast syncing the caches or ...? 

Thanks

**Comment by pveentjer** [comment]
Can you check what the network traffic is when the hibernate second level cache through HZ is disabled? It should be very low; just some periodic heartbeats etc traffic.

**Comment by blazember** [comment]
@ndjordjevic Is it a constant/periodic traffic, or you experience it only around the time when the new instances are added? 

The latter case is expected as the instances need to repartition a new member joins the cluster. The traffic is depending on the amount of the data you store in your cache. You can read about [data partitioning](http://docs.hazelcast.org/docs/3.9.3/manual/html-single/index.html#data-partitioning) in the docs.

**Comment by mmedenjak** [comment]
@ndjordjevic have you had time to take a look at the suggestions?

**Comment by mmedenjak** [comment]
Closing the issue due to non-activity. @ndjordjevic please open a new issue if the problem persists or if you encounter a new issue.
