### ISSUE TITLE
Member / Client OOME GC overhead limit, create-use-distributed-obj-destroy

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12679]
/disk1/jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/destroy/create-use-dist-destroy Failed

```
fail HzClient1HZ _create-use-dist-destroy_createUseDistDestroy_id hzcmd.id.generator.CreateUse threadId=0 java.lang.Exception: java.lang.OutOfMemoryError: GC overhead limit exceeded 
```

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/destroy/create-use-dist-destroy

GC
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/destroy/create-use-dist-destroy/gc.html

```
output/HZ/HzMember4HZ/HzMember4HZ.hprof
output/HZ/HzClient2HZ/exception.txt
output/HZ/HzClient2HZ/HzClient2HZ.hprof
output/HZ/HzClient1HZ/exception.txt
output/HZ/HzClient1HZ/HzClient1HZ.oome
output/HZ/HzClient1HZ/HzClient1HZ.hprof
```

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/destroy/create-use-dist-destroy/output/HZ/HzMember4HZ/

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/destroy/create-use-dist-destroy/output/HZ/HzClient1HZ/

**Comment by Danny-Hazelcast** [comment]
GC from  3.9.3 
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9.3/2018_02_02-00_59_21/stable/destroy/create-use-dist-destroy/gc.html

also not looking good but no oome, and members look better.

**Comment by ahmetmircik** [comment]
Hprof file says, `NioOutboundPipeline#writeQueue` is the main consumer.

**Comment by pveentjer** [comment]
Running with the overloaded connections plugin will help to determine the content of of the writeQueue.

**Comment by tkountis** [comment]
@Danny-Hazelcast can you do another run with the additional props Peter suggested?

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-x/64/console

/disk1/jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_04_04-19_30_56/create-use-dist-destroy Failed

fail HzClient3HZ _create-use-dist-destroy_createUseDistDestroy_id hzcmd.id.generator.CreateUse threadId=0 java.lang.Exception: java.lang.OutOfMemoryError: GC overhead limit exceeded 

http://54.82.84.143/~jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_04_04-19_30_56/create-use-dist-destroy

http://54.82.84.143/~jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_04_04-19_30_56/create-use-dist-destroy/gc.html

http://54.82.84.143/~jenkins/workspace/shutdown-x/3.10-SNAPSHOT/2018_04_04-19_30_56/create-use-dist-destroy/output/HZ/HzClient3HZ/HzClient3HZ.hprof

**Comment by pveentjer** [comment]
![image](https://user-images.githubusercontent.com/105243/38538161-21bf31ea-3c9b-11e8-8587-f0e8bc74eccb.png)
