### ISSUE TITLE
Excessive logging when using liveness/readiness scripts in Kubernetes, etc.

### ISSUE THREAD

**Issue by mappamundi** [hazelcast/hazelcast#12687]
_master, current release._

Several users have reported log flooding with INFO level messages when using `readiness.sh` and/or `liveness.sh` scripts in Kubernetes and OpenShift.

See issues:
https://github.com/hazelcast/hazelcast-openshift/issues/7
https://github.com/hazelcast/hazelcast-docker/issues/52

These scripts run typically every 10 seconds, so the amount of logging is really annoying.

A logging sample:

> Jan 10 2018 15:19:29:833 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-Acceptor] - INFO - com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptSocket - [192.168.12.190]:5701 [local-cluster] [3.9.2] Accepting socket connection from /192.168.12.190:41586
> Jan 10 2018 15:19:29:838 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.cached.thread-1] - INFO - com.hazelcast.nio.tcp.TcpIpConnectionManager.newConnection - [192.168.12.190]:5701 [local-cluster] [3.9.2] Established socket connection between /192.168.12.190:5701 and /192.168.12.190:41586
> Jan 10 2018 15:19:29:843 UTC - [hz.hazelcast-imdg-os-test-13-s9vcz.IO.thread-in-2] - INFO - com.hazelcast.nio.tcp.TcpIpConnection.close - [192.168.12.190]:5701 [local-cluster] [3.9.2] Connection[id=24, /192.168.12.190:5701->/192.168.12.190:41586, endpoint=null, alive=false, type=REST_CLIENT] closed. Reason: Connection closed by the other side

The scripts issue a GET request with `curl` to the `http://$HOSTNAME:5701/hazelcast/health` endpoint. For example, see: https://github.com/hazelcast/hazelcast-docker/blob/84ff4dd3728afda9b4113d218bdd5c43c2003124/hazelcast-kubernetes/liveness.sh#L4

The connection is therefore closed by the client as expected.

Looks like `TcpIpConnection.close` intentionally logs with `info` when connection is closed by the other side: https://github.com/hazelcast/hazelcast/blob/64ad53ae12047e330ca2d9af0e42a9c503c6ed2e/hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnection.java#L223

When accepting connection: https://github.com/hazelcast/hazelcast/blob/64ad53ae12047e330ca2d9af0e42a9c503c6ed2e/hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpAcceptor.java#L270

On new connection established: https://github.com/hazelcast/hazelcast/blob/64ad53ae12047e330ca2d9af0e42a9c503c6ed2e/hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java#L390

We should lower the logging level to DEBUG _at least when the endpoint is the health check_ if not in all cases.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/10924

As mentioned in the related issue, the connection information is very useful when debugging issues regarding cluster and client membership changes. 
In some cases, such as automated health checks, this periodically logs the connection lifecycle. You may then configure the logging to log on WARN for these classes:
`com.hazelcast.nio.tcp.SocketAcceptorThread`
`com.hazelcast.nio.tcp.TcpIpConnectionManager`
`com.hazelcast.nio.tcp.TcpIpConnection`
Unfortunately that also means that you won't be able to see connection lifecycle information on client and members.

**Comment by googlielmo** [comment]
Good point @mmedenjak 
Is there any way to differentiate between the health checks and other connections? (Probably not, at the TcpIpConnection level)...

**Comment by mmedenjak** [comment]
Unfortunately I don't think we can currently differentiate between connections.

**Comment by googlielmo** [comment]
Okay. Custom logging configuration (or some context-sensitive logging filter perhaps) is a good workaround.

**Comment by mesutcelik** [comment]
@Holmistr ,Do you think we should close this based on your comment here?
https://github.com/hazelcast/hazelcast/issues/10924#issuecomment-362569542

**Comment by Holmistr** [comment]
@mesutcelik Yes, from my point of view this is the same situation and I believe that custom logging configuration is not only an acceptable workaround, but I think a correct solution actually. Feel free to close the issue, if you agree.

**Comment by mesutcelik** [comment]
Thanks @Holmistr!
closing this as per https://github.com/hazelcast/hazelcast/issues/10924#issuecomment-362569542
