### ISSUE TITLE
Client OOME near cache async 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12698]
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-All/56/console

/disk1/jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async Failed

```
fail HzClient1HZ _near-cache_async_put_mapBak0HD-ncHD hzcmd.map.PutAsync threadId=3 java.lang.Exception: java.lang.OutOfMemoryError: Java heap space 
```

```
output/HZ/HzClient1HZ/exception.txt
output/HZ/HzClient1HZ/HzClient1HZ.oome
output/HZ/HzClient1HZ/HzClient1HZ.hprof
```

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async

operations are async put's
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async/ops

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async/config-hz/client-hazelcast.xml
`http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async/config-hz/client-hazelcast.xml` 

GC so we see only 1 client moves into the leak pattern.
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10-SNAPSHOT/2018_03_20-18_17_05/stable/near-cache/async/gc.html

for comparison under same test. 
GC of 3.9.3  
http://54.82.84.143/~jenkins/workspace/shutdown-All/3.9.3/2018_02_02-00_59_21/stable/near-cache/async/gc.html

**Comment by Danny-Hazelcast** [comment]
duplicated https://github.com/hazelcast/hazelcast/issues/12683

**Comment by mmedenjak** [comment]
@Danny-Hazelcast both issues are closed. Is this fixed?
