### ISSUE TITLE
shutdown data loss, client map get returns null 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12718]
It is very rare for this job to fail,

Client reported data loss from cluster, when a member node was shutdown using, hzInstance.shutdown();

This issue is very rare, could it but due to environment issues ? however i see no evidence for this in the logs,  the cluster took the expected form during the test,  

jenkins job.
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-data-loss/

Rare failed job run.
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-data-loss/331/console

location on disk.
/disk1/jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss

web link to data.
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss

fail
`fail HzClient3HZ get_mapBak0 hzcmd.map.GetNotNull threadId=2 global.AssertionException: DATA LOSS! for map mapBak0 key 852`

but all Clients reported the same exception 
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzClient1HZ/exception.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzClient2HZ/exception.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzClient3HZ/exception.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzClient4HZ/exception.txt

GC charts  (looks normal)
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/gc.html

Client1 log snipit
```
Mar 26, 2018 12:02:27 AM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: hz.client_0 [HZ] [3.10-SNAPSHOT] 

Members [3] {
	Member [10.0.0.90]:5701 - b34b2f35-40e8-46cc-bda9-b5b30d5ac5f3
	Member [10.0.0.177]:5701 - dcbb649d-3426-41fe-92a9-a3d64a8baa17
	Member [10.0.0.233]:5701 - 8cb519f0-cff3-4c13-8d7d-33b0a9147edc
}

Mar 26, 2018 12:02:27 AM com.hazelcast.client.connection.nio.ClientConnection
WARNING: hz.client_0 [HZ] [3.10-SNAPSHOT] ClientConnection{alive=false, connectionId=4, channel=NioChannel{/10.0.0.177:32928->/10.0.0.234:5701}, remoteEndpoint=[10.0.0.234]:5701, lastReadTime=2018-03-26 00:02:27.035, lastWriteTime=2018-03-26 00:02:27.035, closedTime=2018-03-26 00:02:27.039, lastHeartbeatRequested=2018-03-26 00:01:54.704, lastHeartbeatReceived=2018-03-26 00:01:54.704, connected server version=3.10-SNAPSHOT} closed. Reason: com.hazelcast.spi.exception.TargetDisconnectedException[The client has closed the connection to this member, after receiving a member left event from the cluster. ClientConnection{alive=true, connectionId=4, channel=NioChannel{/10.0.0.177:32928->/10.0.0.234:5701}, remoteEndpoint=[10.0.0.234]:5701, lastReadTime=2018-03-26 00:02:27.035, lastWriteTime=2018-03-26 00:02:27.035, closedTime=never, lastHeartbeatRequested=2018-03-26 00:01:54.704, lastHeartbeatReceived=2018-03-26 00:01:54.704, connected server version=3.10-SNAPSHOT}]
com.hazelcast.spi.exception.TargetDisconnectedException: The client has closed the connection to this member, after receiving a member left event from the cluster. ClientConnection{alive=true, connectionId=4, channel=NioChannel{/10.0.0.177:32928->/10.0.0.234:5701}, remoteEndpoint=[10.0.0.234]:5701, lastReadTime=2018-03-26 00:02:27.035, lastWriteTime=2018-03-26 00:02:27.035, closedTime=never, lastHeartbeatRequested=2018-03-26 00:01:54.704, lastHeartbeatReceived=2018-03-26 00:01:54.704, connected server version=3.10-SNAPSHOT}
	at com.hazelcast.client.spi.impl.ClientMembershipListener.newTargetDisconnectedExceptionCausedByMemberLeftEvent(ClientMembershipListener.java:203)
	at com.hazelcast.client.spi.impl.ClientMembershipListener.memberRemoved(ClientMembershipListener.java:159)
	at com.hazelcast.client.spi.impl.ClientMembershipListener.handle(ClientMembershipListener.java:77)
	at com.hazelcast.client.impl.protocol.codec.ClientAddMembershipListenerCodec$AbstractEventHandler.handle(ClientAddMembershipListenerCodec.java:182)
	at com.hazelcast.client.spi.impl.ClientMembershipListener.handle(ClientMembershipListener.java:48)
	at com.hazelcast.client.spi.impl.listener.AbstractClientListenerService$ClientEventProcessor.run(AbstractClientListenerService.java:129)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)

Mar 26, 2018 12:02:27 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [HZ] [3.10-SNAPSHOT] Removed connection to endpoint: [10.0.0.234]:5701, connection: ClientConnection{alive=false, connectionId=4, channel=NioChannel{/10.0.0.177:32928->/10.0.0.234:5701}, remoteEndpoint=[10.0.0.234]:5701, lastReadTime=2018-03-26 00:02:27.040, lastWriteTime=2018-03-26 00:02:27.043, closedTime=2018-03-26 00:02:27.039, lastHeartbeatRequested=2018-03-26 00:01:54.704, lastHeartbeatReceived=2018-03-26 00:01:54.704, connected server version=3.10-SNAPSHOT}
Mar 26, 2018 12:02:27 AM com.hazelcast.client.connection.ClientConnectionManager
INFO: hz.client_0 [HZ] [3.10-SNAPSHOT] Authenticated with server [10.0.0.234]:5701, server version:3.10-SNAPSHOT Local address: /10.0.0.177:46528

global.AssertionException: DATA LOSS! for cache cacheBak0HD key 690
```

All Member logs look similar and of similar size.
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzMember1HZ/out.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzMember2HZ/out.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzMember3HZ/out.txt
http://54.82.84.143/~jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss/output/HZ/HzMember4HZ/out.txt

**Comment by Danny-Hazelcast** [comment]
looking at the exceptions show it all types of maps and caches and different keys returning null 

[jenkins@ip-10-72-134-107 data-loss]$ pwd
/disk1/jenkins/workspace/shutdown-data-loss/3.10-SNAPSHOT/2018_03_26-03_00_01/data-loss
[jenkins@ip-10-72-134-107 data-loss]$ hz-errors | xargs grep -oah 'DATA LOSS.*'
DATA LOSS! for map mapBak0 key 852
DATA LOSS! for map mapBak0HD key 336
DATA LOSS! for map mapBak0HD key 321
DATA LOSS! for cache cacheBak0HD key 257
DATA LOSS! for map mapBak0 key 945
DATA LOSS! for cache cacheBak0 key 575
DATA LOSS! for map mapBak0 key 114
DATA LOSS! for map mapBak0 key 174
DATA LOSS! for cache cacheBak0HD key 985
DATA LOSS! for cache cacheBak0HD key 273
DATA LOSS! for map mapBak0HD key 667
DATA LOSS! for map mapBak0HD key 628
DATA LOSS! for cache cacheBak0 key 140
DATA LOSS! for cache cacheBak0 key 870
DATA LOSS! for cache cacheBak0HD key 899
DATA LOSS! for cache cacheBak0 key 542
DATA LOSS! for cache cacheBak0HD key 36
DATA LOSS! for map mapBak0 key 490
DATA LOSS! for map mapBak0HD key 105
DATA LOSS! for map mapBak0HD key 554
DATA LOSS! for cache cacheBak0HD key 2
DATA LOSS! for map mapBak0 key 525
DATA LOSS! for cache cacheBak0 key 873
DATA LOSS! for cache cacheBak0HD key 998
DATA LOSS! for map mapBak0HD key 640
DATA LOSS! for cache cacheBak0 key 214
DATA LOSS! for cache cacheBak0HD key 257
DATA LOSS! for map mapBak0 key 589
DATA LOSS! for cache cacheBak0 key 122
DATA LOSS! for map mapBak0HD key 690
DATA LOSS! for cache cacheBak0 key 835
DATA LOSS! for map mapBak0 key 233
DATA LOSS! for map mapBak0 key 791
DATA LOSS! for cache cacheBak0HD key 893
DATA LOSS! for map mapBak0 key 144
DATA LOSS! for map mapBak0HD key 683
DATA LOSS! for cache cacheBak0 key 333
DATA LOSS! for map mapBak0HD key 998
DATA LOSS! for cache cacheBak0 key 852
DATA LOSS! for map mapBak0HD key 259
DATA LOSS! for map mapBak0 key 934
DATA LOSS! for cache cacheBak0HD key 315
DATA LOSS! for map mapBak0 key 376
DATA LOSS! for cache cacheBak0 key 217
DATA LOSS! for map mapBak0HD key 957
DATA LOSS! for cache cacheBak0HD key 248
DATA LOSS! for cache cacheBak0HD key 241
DATA LOSS! for cache cacheBak0 key 140
DATA LOSS! for cache cacheBak0HD key 690
DATA LOSS! for map mapBak0 key 76
DATA LOSS! for map mapBak0HD key 250
DATA LOSS! for cache cacheBak0 key 872
DATA LOSS! for map mapBak0 key 94
DATA LOSS! for map mapBak0HD key 628
DATA LOSS! for cache cacheBak0 key 183
DATA LOSS! for map mapBak0 key 302
DATA LOSS! for map mapBak0HD key 502
DATA LOSS! for cache cacheBak0 key 150
DATA LOSS! for cache cacheBak0HD key 556
DATA LOSS! for map mapBak0 key 640
DATA LOSS! for cache cacheBak0HD key 412
DATA LOSS! for cache cacheBak0 key 464
DATA LOSS! for map mapBak0HD key 162
DATA LOSS! for cache cacheBak0HD key 927

**Comment by Danny-Hazelcast** [comment]
hz-errors | xargs grep -oah 'DATA LOSS.*' | awk '{ print $5 }' | sort | uniq
cacheBak0
cacheBak0HD
mapBak0
mapBak0HD

**Comment by Danny-Hazelcast** [comment]
`
[jenkins@ip-10-72-134-107 data-loss]$ find . -name out.txt  | xargs grep partition
./output/HZ/HzMember2HZ/out.txt:INFO: [10.0.0.233]:5701 [HZ] [3.10-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
./output/HZ/HzMember4HZ/out.txt:Mar 26, 2018 12:01:45 AM com.hazelcast.internal.partition.impl.PartitionStateManager
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Initializing cluster partition table arrangement...
./output/HZ/HzMember4HZ/out.txt:Mar 26, 2018 12:02:27 AM com.hazelcast.internal.partition.impl.MigrationManager
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 204
./output/HZ/HzMember4HZ/out.txt:Mar 26, 2018 12:02:31 AM com.hazelcast.internal.partition.impl.MigrationThread
./output/HZ/HzMember4HZ/out.txt:Mar 26, 2018 12:03:17 AM com.hazelcast.internal.partition.impl.MigrationManager
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Re-partitioning cluster data... Migration queue size: 271
./output/HZ/HzMember4HZ/out.txt:Mar 26, 2018 12:03:21 AM com.hazelcast.internal.partition.impl.MigrationThread
./output/HZ/HzMember1HZ/out.txt:INFO: [10.0.0.177]:5701 [HZ] [3.10-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
./output/HZ/HzMember3HZ/out.txt:Mar 26, 2018 12:02:28 AM com.hazelcast.internal.partition.InternalPartitionService
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Fetching most recent partition table! my version: 1085
./output/HZ/HzMember3HZ/out.txt:Mar 26, 2018 12:02:28 AM com.hazelcast.internal.partition.InternalPartitionService
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Most recent partition table version: 1085
./output/HZ/HzMember3HZ/out.txt:Mar 26, 2018 12:02:28 AM com.hazelcast.internal.partition.impl.MigrationManager
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Partition balance is ok, no need to re-partition cluster data...
./output/HZ/HzMember3HZ/out.txt:Mar 26, 2018 12:03:09 AM com.hazelcast.internal.partition.impl.MigrationManager
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
`

**Comment by Danny-Hazelcast** [comment]
```
find . -name out.txt  | xargs grep migration
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] All migration tasks have been completed, queues are empty.
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] All migration tasks have been completed, queues are empty.
```

**Comment by Danny-Hazelcast** [comment]
from 
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-data-loss/331/console

we can see the data was loaded into the cluster,
and data was validated / check, the each key value was in the map

**Comment by mdogan** [comment]
There's a heartbeat problem between master `[10.0.0.90]:5701` and member `[10.0.0.234]:5701`. They suspect each other and `[10.0.0.234]:5701` splits from the rest. Then `[10.0.0.234]:5701` is shutdown and restarted by the test. 

On master:
```
Mar 26, 2018 12:02:27 AM com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
WARNING: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Suspecting Member [10.0.0.234]:5701 - 47cc18d7-ab47-4f3e-ab79-997fd9d88814 because it has not sent any heartbeats since 2018-03-26 00:02:15.025. Now: 2018-03-26 00:02:27.030, heartbeat timeout: 10000 ms, suspicion level: 38.21

Mar 26, 2018 12:02:27 AM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Connection[id=5, /10.0.0.90:5701->/10.0.0.234:47228, endpoint=[10.0.0.234]:5701, alive=false, type=MEMBER] closed. Reason: Suspecting Member [10.0.0.234]:5701 - 47cc18d7-ab47-4f3e-ab79-997fd9d88814 ...

Mar 26, 2018 12:02:27 AM com.hazelcast.internal.cluster.impl.MembershipManager
INFO: [10.0.0.90]:5701 [HZ] [3.10-SNAPSHOT] Removing Member [10.0.0.234]:5701 - 47cc18d7-ab47-4f3e-ab79-997fd9d88814
```

On member `[10.0.0.234]:5701`:
```
Mar 26, 2018 12:02:28 AM com.hazelcast.internal.cluster.impl.ClusterHeartbeatManager
WARNING: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Suspecting Member [10.0.0.90]:5701 - b34b2f35-40e8-46cc-bda9-b5b30d5ac5f3 because it has not sent any heartbeats since 2018-03-26 00:02:16.031. Now: 2018-03-26 00:02:28.025, heartbeat timeout: 10000 ms, suspicion level: 37.10

[...]

Mar 26, 2018 12:02:28 AM com.hazelcast.internal.cluster.impl.MembershipManager
INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] Starting mastership claim process...

Mar 26, 2018 12:02:28 AM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.0.234]:5701 [HZ] [3.10-SNAPSHOT] 

Members {size:1, ver:5} [
	Member [10.0.0.234]:5701 - 47cc18d7-ab47-4f3e-ab79-997fd9d88814 this
]
```

**Comment by Danny-Hazelcast** [comment]
ok so if 
[10.0.0.234]:5701 splits from the rest. Then [10.0.0.234]:5701 is restarted. 

so the clients could be calling get on '[10.0.0.234]:5701'  which would return null
as it is a cluster of 1.


have we change the way we detect splits by default ?  
is it more likely we detect small latencies and split the cluster a bit early ?
do have new changes which suspect node failures more quickly in 3.10-SNAPSHOT ?

**Comment by mdogan** [comment]
I don't remember any changes but in this specific run, heartbeat timeout is set to 10 seconds: `-Dhazelcast.max.no.heartbeat.seconds=10`.

**Comment by Danny-Hazelcast** [comment]
ok, so i can close this issue. and we put it down to AWS network.
