### ISSUE TITLE
Split-brain merging entries are wasting memory and network capacity

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12725]
The actual implementation uses the same `FullMergingEntryImpl` for `IMap`, `ICache`, `ReplicatedMap` and `MultiMap`, although only `IMap` provides all fields which are stored in memory and transferred over the wire.

We should use data specific classes to solve this issue.

**Comment by pveentjer** [comment]
Is this important to get fixed in the 3.10 time window?

**Comment by mmedenjak** [comment]
This issue was opened to indicate one of the things an existing PR is fixing. If possible, please review the PRs:
https://github.com/hazelcast/hazelcast/pull/12573 
https://github.com/hazelcast/hazelcast-enterprise/pull/2002
