### ISSUE TITLE
DataSerializable unwanted String

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#12777]
In DataSerializableSerializer:

```
  } else {
                className = in.readUTF();<----
                if (null == aClass) {
                    ds = ClassLoaderUtil.newInstance(in.getClassLoader(), className);
                }
            }
```

**Comment by sancar** [comment]
I believe the workaround is to use IdentifiedDataSerializable which uses two ints instead of String class-name.

**Comment by mmedenjak** [comment]
Agree, probably this issue is low-priority as we might guide new users towards newer serialization formats soon.

**Comment by sancar** [comment]
@pveentjer We are closing the issue since we already have workarounds for users. 
If you can add your reasoning for opening this issue and also your expected solution, we can follow up on that.
