### ISSUE TITLE
ExternalizableSerializer unwanted String

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#12770]
```
 @Override
        public Externalizable read(final ObjectDataInput in) throws IOException {
            String className = in.readUTF();
       
```

A string and  char array is created to determine the class. This is very inefficient.

**Comment by sancar** [comment]
The workaround is to use other formats like IdentifiedDataSerializable. We can not determine class without getting an explicit configuration from the user. I don't believe this should change, but the user should be directed to more efficient methods.

**Comment by mmedenjak** [comment]
Agree, probably this issue is low-priority as we might guide new users towards newer serialization formats soon.

**Comment by sancar** [comment]
@pveentjer We are closing the issue since we already have workarounds for users. 
If you can add your reasoning for opening this issue and also your expected solution, we can follow up on that.
