### ISSUE TITLE
StartServer should be renamed.

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#12791]
When using the start scripts in the bin directory, from zip distribution.

The class to start a Hazelcast Member is called...

`com.hazelcast.core.server.StartServer`

When you run a JPS command it will just show `StartServer`.

In Technical documentation we call these `Members`.

We should rename the class to be...

`com.hazelcast.core.member.StartHazelcastMember`

In this way it complies with our naming standards and it also makes things more intuitive when reading process lists.

**Comment by ahmetmircik** [comment]
liked this issue, maybe we can even rename it to `HazelcastMemberStarter` like JUnits' `JUnitStarter`

**Comment by tkountis** [comment]
Why not plain old `HazelcastMember`? When I see a process list, I expect to see the name of the process. The `Start` or `Starter` prefix/suffix, even though make sense on the code side, they aren't intuitive to the admin of the system. @dbrimley @ahmetmircik WDYT?

**Comment by emre-aydin** [comment]
+1 for `HazelcastMember`

**Comment by ahmetmircik** [comment]
@tkountis i think it depends on how you look it. I see it as an abstraction to start a member with, in the future some other capability(don't know what they are now) may also be added. But i'm ok with any naming if i can see `Hazelcast` in the name.

**Comment by pveentjer** [comment]
This isn't critical for the 3.10 release. I'm proposing to get it moved to 3.11.

**Comment by eminn** [comment]
Note to the future implementer: Please double check all the starter scripts in the docker images since most of them uses that class.

**Comment by pveentjer** [comment]
Since this isn't critical for the 3.10 release, moving it to the 3.11 release.

**Comment by mesutcelik** [comment]
This needs to be renamed in all hazelcast docker images and start scripts as @eminn mentioned.
What is the latest decision of the name here @dbrimley ?

**Comment by dbrimley** [comment]
I worry that `HazelcastMember` may convey something unintended to the user. As @ahmetmircik says, its intent should be that it is a starter for a hazelcast member.  It's not THE `HazelcastMember`.

I'd like to call it `HazelcastMemberStarter`, I admit its not as clean and nice in the process list but it at least is better than we have.

**Comment by leszko** [comment]
I've created the related PRs:
- https://github.com/hazelcast/hazelcast/pull/13818
- https://github.com/hazelcast/hazelcast-enterprise/pull/2440

Keep in mind the PRs were the easy part, there are a lot to things related to be done after the release:
- Dockerfiles in hazelcast-docker
- Dockerfile in hazelcast-openshift
- hazelcast-code-samples
- hazelcast-qe
- something more?

What's more, users may have `StartServer` somewhere in their scripts, so we may break it. 

Saying that I would re-consider if we really want to rename it. After all `HazelcastMemeberStarter` is not so much better than `StartServer` IMO.

@mmedenjak @jerrinot , What are your thoughts?

**Comment by dbrimley** [comment]
@leszko I guess the problem we're trying to solve here is making the process identifiable as a Hazelcast Member.  Who knows what `StartServer` is.

**Comment by dbrimley** [comment]
For backwards compatibility we could keep the original class and duplicate it with the new name and change our start scripts to use it.  Other 3rd party scripts would then still work?

**Comment by mmedenjak** [comment]
I agree with @dbrimley . I am against breaking compatibility. We try so hard to keep it everywhere else to break it so easily here.

**Comment by leszko** [comment]
SGTM 👍 

Added `StartServer` to the PRs for the backwards-compatibility. @mmedenjak PTAL.
