### ISSUE TITLE
Destroy reliable topic memory leak OOME hprof

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12808]
I was just trying to reproduce the topic issue described in the community channel, as I got OOME from the members,

the hprof is http://54.82.84.143/~jenkins/workspace/temp/HzMember1HZ-topic.hprof

simply i was creating topics using and destroying, and it results in OOME.

the main difference to the usual create-use-destroy test i run is.
before I would operate on the same topic over and over 
where as in this latest fails test,

I create use and destroy a topic with a random name each time.
when we destroy a structure, do we intentionally keep some small amount of data/state about it in the cluster ?

Matko Medenjak 
we aren’t supposed to. I’ll take a quick look at the heap dump
looks like we keep the ringbuffers so this might be a bug

**Comment by pveentjer** [comment]
Datastructures are difficult to destroy in HZ because they are automatically recreated. So if you have some kind of operation interaction with a data-structure previously destroyed, it will be recreated. And since you are using random names, you can get a build up of recreated data-structures. 

This is nothing new. I'm failing to see the added value for this family of tests since the underlying issue is known.

**Comment by mmedenjak** [comment]
@Danny-Hazelcast do you have the test code somewhere? The directory in the link does not contain it.

**Comment by mmedenjak** [comment]
We even have a [unit test](https://github.com/hazelcast/hazelcast/blob/00ee8406b7945b601fc6c2e3783b7c53a5dd582d/hazelcast/src/test/java/com/hazelcast/topic/impl/reliable/ReliableTopicDestroyTest.java#L78-L93) which asserts that the ringbuffer is cleaned up when the reliable topic is destroyed which makes this failure a bit strange.

**Comment by mmedenjak** [comment]
I also ran code similar to a create-use-destroy pattern:
```
        for (int i = 0; i < 1000000; i++) {
            final ITopic<Object> topic = hz.getReliableTopic(randomString());
            topic.publish("lala");
            topic.destroy();
        }
```
And I can't see a leak:
<img width="551" alt="screen shot 2018-04-10 at 14 42 46" src="https://user-images.githubusercontent.com/17194871/38557487-765cb0ba-3ccd-11e8-8652-58dd50337fbf.png">

**Comment by Danny-Hazelcast** [comment]
@mmedenjak os i have the same simple code,  mabey the difference is running on a members and clients ?


```_create-use-destroy_createUseDestroy_reliableTopic@class=hzcmd.topic.CreateUseDestroy
_create-use-destroy_createUseDestroy_reliableTopic@reliable=true
_create-use-destroy_createUseDestroy_reliableTopic@threads=1
_create-use-destroy_createUseDestroy_reliableTopic@name=topicReliableCreateUseDestroy_create-use-destroy
_create-use-destroy_createUseDestroy_reliableTopic@max=900000000
_create-use-destroy_createUseDestroy_reliableTopic@ignore=com.hazelcast.spi.exception.DistributedObjectDestroyedException```

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/topic/CreateUseDestroy.java

running on members and clients, using a 3 member 3 client setup

**Comment by Danny-Hazelcast** [comment]
@mmedenjak if i run just from Member i do not see the OOMe

if i run just from client I see the OOME

if i run from member and client i also see the OOME

**Comment by mmedenjak** [comment]
Yes, looks like there's a leak in client code and it's pretty simple to fix.

**Comment by mmedenjak** [comment]
@Danny-Hazelcast the fix for reliable topic was merged, please retest

**Comment by Danny-Hazelcast** [comment]
@mmedenjak after fix was merged, I can not reproduce the Member OOME
