### ISSUE TITLE
Split-brain merging of collection like data structures is lossy

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#12803]
The actual merging algorithm for collection like data structures (e.g. `ISet`, `IList`, `IQueue`, `Ringbuffer` and `MultiMap`) can be lossy. The issue occurs when e.g. a list contains the same value multiple times. The search for an existing entry will eliminate all duplicates in this case.

The search for existing items also has a bad complexity. It searches a new existing item for each `MergingValue`, while each merged value is added to the existing items.

The proposed solution is to give the whole collection to the merge policy and let the user decide how to merge them. This will still work for the out-of-the-box merge policies like `DiscardMergePolicy`, `PassthroughMergePolicy` and `PutIfAbsentMergePolicy`. You can also write a common merge policy for all collection based policies, by implementing `SplitBrainMergePolicy<Collection<Object>, MergingValue<Collection<Object>>`, so there is no need to write a specific one for each data structure.

**Comment by pveentjer** [comment]
Since the merge API is marked as beta, why not do this in the 3.11 release? So how big will be the impact on the code API if this is left out in the 3.10 release?

**Comment by Donnerbart** [comment]
Jaromir put us on the task to fix this.

Beside the API changes the wire-protocol needs a change to fix this. So it's the easiest to fix this in 3.10, so we don't need to deal with RU and cluster version checks for this in 3.11.

**Comment by mmedenjak** [comment]
Closing as all PRs related to this were merged.
