### ISSUE TITLE
QueryCache is created after each getQueryCache call

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#12814]
Hi!

Recently I've submitted the issue about OOM in Hazelcast 3.10. This ticket is a follow-up, because we found where Hazelcast leaks memory.

In commit 918c9f3ef44b0e3fbd9734595105df1b530c3a54, @ahmetmircik changed that Query Cache is created by Cache ID, not Cache Name. Cache ID is generated randomly in method MapProxyImpl#getQueryCacheInternal. 

So, after each call to getQueryCache, Hazelcast creates new query cache and populates it. 

From IMap.getQueryCache:

>  Returns corresponding {@code QueryCache} instance for the supplied {@code name} or null. If there is a previously created {@link QueryCache} with the supplied {@code name} or if a declarative
>     configuration exists for the supplied {@code name} this method returns or creates the instance respectively, otherwise returns null.

So we have 2 possibilities:
 - Java Doc is wrong
 - Code does not work as expected

**Comment by ahmetmircik** [comment]
definitely this is a bug, thanks for reporting.
