### ISSUE TITLE
Fix HazelcastProperties javadoc

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#12820]
The javadoc says:
```java
...
 * A {@link HazelcastProperty} can be set as:
 * <ul>
 * <li>an environmental variable using {@link System#setProperty(String, String)}</li>
...
```

It should say system property not environment variable. It is set using java -D as as system property.

**Comment by hgvanpariya** [comment]
@mmedenjak , I've updated the javadoc, please provide your review comments.
