### ISSUE TITLE
rollup 3.9.4 to 3.10-SANPSHOT near cache async operation client side OOME

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#12873]
https://hazelcast-l337.ci.cloudbees.com/view/rollup/job/rollup-All_3.9.4_3.10/23/console

/disk1/jenkins/workspace/rollup-All_3.9.4_3.10/3.10-SNAPSHOT/2018_04_13-18_48_43/stable/near-cache/async Failed

```
fail HzClient6HZ _near-cache_async_put_cacheBak0HD-ncHD hzcmd.cache.PutAsync threadId=1 java.lang.OutOfMemoryError: GC overhead limit exceeded 
```

http://54.82.84.143/~jenkins/workspace/rollup-All_3.9.4_3.10/3.10-SNAPSHOT/2018_04_13-18_48_43/stable/near-cache/async

```
HzClient5HZ Started on 10.0.0.18 14171@ip-10-0-0-18 /home/ec2-user/hz-root/hz-lib/3.9.4
HzClient6HZ Started on 10.0.0.194 12370@ip-10-0-0-194 /home/ec2-user/hz-root/hz-lib/3.10-SNAPSHOT
```

```
hz-root/HzClient5HZ/HzClient5HZ.hprof
hz-root/HzClient5HZ/HzClient5HZ.oome
hz-root/HzClient5HZ/exception.txt

hz-root/HzClient6HZ/HzClient6HZ.oome
hz-root/HzClient6HZ/HzClient6HZ.hprof
hz-root/HzClient6HZ/exception.txt
```

version used 
```
/disk1/jenkins/workspace/rollup-All_3.9.4_3.10/3.10-SNAPSHOT/2018_04_13-18_48_43/stable/near-cache/async
[jenkins@ip-10-72-134-107 async]$ find . -name out.txt | xargs grep STARTING
./output/HZ/HzClient3HZ/out.txt:INFO: hz.client_0 [HZ] [3.9.4] HazelcastClient 3.9.4 (20180413 - 62999da, a26e29f) is STARTING
./output/HZ/HzMember2HZ/out.txt:INFO: [10.0.0.194]:5701 [HZ] [3.9.4] [10.0.0.194]:5701 is STARTING
./output/HZ/HzMember4HZ/out.txt:INFO: [10.0.0.135]:5701 [HZ] [3.9.4] [10.0.0.135]:5701 is STARTING
./output/HZ/HzClient4HZ/out.txt:INFO: hz.client_0 [HZ] [3.9.4] HazelcastClient 3.9.4 (20180413 - 62999da, a26e29f) is STARTING
./output/HZ/HzClient5HZ/out.txt:INFO: hz.client_0 [HZ] [3.9.4] HazelcastClient 3.9.4 (20180413 - 62999da, a26e29f) is STARTING
./output/HZ/HzMember1HZ/out.txt:INFO: [10.0.0.18]:5701 [HZ] [3.9.4] [10.0.0.18]:5701 is STARTING
./output/HZ/HzMember1HZ/out.txt:INFO: [10.0.0.18]:5701 [HZ] [3.9.4] [10.0.0.18]:5701 is STARTING
./output/HZ/HzMember3HZ/out.txt:INFO: [10.0.0.150]:5701 [HZ] [3.9.4] [10.0.0.150]:5701 is STARTING
./output/HZ/HzClient2HZ/out.txt:INFO: hz.client_0 [HZ] [3.9.4] HazelcastClient 3.9.4 (20180413 - 62999da, a26e29f) is STARTING
./output/HZ/HzClient1HZ/out.txt:INFO: hz.client_0 [HZ] [3.9.4] HazelcastClient 3.9.4 (20180413 - 62999da, a26e29f) is STARTING
./output/HZ/HzClient6HZ/out.txt:INFO: hz.client_0 [HZ] [3.10-SNAPSHOT] HazelcastClient 3.10-SNAPSHOT (20180413 - 1d9471e, 84d1b29) is STARTING
```

@ahmetmircik  config used http://54.82.84.143/~jenkins/workspace/rollup-All_3.9.4_3.10/3.10-SNAPSHOT/2018_04_13-18_48_43/stable/near-cache/async/config-hz/

**Comment by Danny-Hazelcast** [comment]
all though hit during a holup grate test, it more of a client side async ops near cache issue ?

**Comment by sancar** [comment]
From the logs, it seems like the 3.10-snapshot is before following fix.
https://github.com/hazelcast/hazelcast/pull/12795

@Danny-Hazelcast Can we check the revision number used ?

**Comment by sancar** [comment]
9dd6d73 is pointing to enterprise which does not really help. 
And 1bb3ffd is giving not found. 
https://github.com/hazelcast/hazelcast/commit/1bb3ffd  ???

**Comment by sancar** [comment]
This time problem seems to be changed. Event packages seems to be pilled up this time.

**Comment by sancar** [comment]
both client 5 and client 6 has around 18000 event packages(around 140 mb's) in the eventExecutor waiting to be consumed. Event thread seems to be trying to handle near cache events, but can not really keep up.

**Comment by ahmetmircik** [comment]
@sancar this was a known issue, we had a fix for 3.10 and i just backported it : https://github.com/hazelcast/hazelcast/pull/12880

**Comment by Danny-Hazelcast** [comment]
this issue https://github.com/hazelcast/hazelcast/issues/12683

**Comment by ahmetmircik** [comment]
should be closed by https://github.com/hazelcast/hazelcast/pull/12880
