### ISSUE TITLE
unknown REST calls made to nodes fail silently

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#12904]
If we make an invalid REST call to a Hazelcast node using curl, we don't see any visible indication (i.e. no response) that the call failed.  Could we change the default behavior to return a 404 error, along with an appropriate text/JSON response that people can visually see when testing out REST calls using tools like wget and curl?

**Comment by leszko** [comment]
@vertex-github , could you give an example of a request that does not return a valid HTTP code?

I've tried the following and they make sense to me:
- `$ curl -v localhost:5701/hazelcast/rest/invalid-rest-call`  : `HTTP/1.1 400 Bad Request`
- `$ curl -v localhost:5701/hazelcast/rest/maps/non-existing-map/k`: `HTTP/1.1 204 No Content`

**Comment by dbrimley** [comment]
@vertex-github Looks like @leszko has shown that invalid rest calls return 400. Unless we're missing something I'm going to close this issue.

Feel free to ping us back if we've got this wrong.

**Comment by vertex-github** [comment]
I don't recall the specific calls but we hit this problem while on client site. Both the client and I reproduced this
