### ISSUE TITLE
AbstractPbeReplacerTest.testWrongVariables failure

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#12910]
```
java.lang.AssertionError: expected null, but was:<�»��&amp#30;&amp#8;=�i�&amp#7;6&amp#30;�>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at com.hazelcast.config.replacer.AbstractPbeReplacerTest.testWrongVariables(AbstractPbeReplacerTest.java:122)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/15229/

**Comment by blazember** [comment]
I could reproduce this failure locally by running the test until failure, haven't yet found the root cause.
Maybe some resource is not closed/freed?

**Comment by blazember** [comment]
In this test we replace the iterations from 77 to 1 for decryption and expect null result due to a `BadPaddingException`. My understanding of the failure is that in some rare cases this replacement doesn't lead to the expected exception and makes the `Cipher#doFinal()` to return a non-null result. 

Based on this above, I believe it is a test error. 
@kwart could you please confirm?

**Comment by kwart** [comment]
It's interesting issue. The failure happens as there is a random password salt used for each encryption.
I'll prepare a fix with a hardcoded value used instead of a generated encrypted one.
