### ISSUE TITLE
Little endian test failures

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12932]
There are number of test failures related to little endian encoding. Most (maybe all?)  of them are actually failures of test that explicitly assume big endian, hence it's a false positive. List of failing jobs:
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-little-endian/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-little-endian/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-EE-3.maintenance-little-endian/
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Enterprise/job/Hazelcast-EE-3.x-little-endian/1/

**Comment by vbekiaris** [comment]
Most failures will be addressed by #12933 . Other failures:
- `ClientCompatibilityTest_1_x` & `ServerCompatibilityTest_1_x` are auto-generated from client protocol, maybe to be checked by client team?
- `EvictionTest.testTTL_prolongationAfterNonTTLUpdate_Quick` seems to be fragile anyway (#12376)

**Comment by mmedenjak** [comment]
I'm in favour of closing this issue. The little endian failures were fixed and there is an issue for the eviction test. The only remaining issue here are the failing `ClientCompatibilityTest_1_x` & `ServerCompatibilityTest_1_x`, for which we can open a new issue and ask the client team to take a look. @Holmistr WDYT?

**Comment by Holmistr** [comment]
TBH, I would rather like to see the [Server|Client]CompatibilityTest fixed. Let me ask somebody from client team to fix it.

**Comment by mmedenjak** [comment]
Right, my point being this is no longer a little endian issue.

**Comment by Holmistr** [comment]
As confirmed with @vbekiaris and my manual testing, the ClientCompatibilityTest_1_x & ServerCompatibilityTest_1_x test failures are related to little endian.

Stacktrace:
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec <<< FAILURE! - in com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_6
test(com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_6)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_6.test(ServerCompatibilityTest_1_6.java:6434)

Running com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_5
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE! - in com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_5
test(com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_5)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.client.protocol.compatibility.ServerCompatibilityTest_1_5.test(ServerCompatibilityTest_1_5.java:6452)
```

Command to reproduce: 
```
mvn -Dtest=ServerCompatibility* test -pl hazelcast -Dhazelcast.serialization.byteOrder=LITTLE_ENDIAN
```

**Comment by Holmistr** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/13111

**Comment by mustafaiman** [comment]
Enterprise failure are not fixed yet.

**Comment by mustafaiman** [comment]
last two PRs:
https://github.com/hazelcast/hazelcast-enterprise/pull/2120
https://github.com/hazelcast/hazelcast-enterprise/pull/2121

Let us close the issue after we see the builds pass.

**Comment by Holmistr** [comment]
All jobs passed, closing.
