### ISSUE TITLE
HealthMonitor tips

### ISSUE THREAD

**Issue by marke352788** [hazelcast/hazelcast#12950]
the logs print:HealthMonitor I com.hazelcast.util.HealthMonitor [processors=2,physcial.memory.total=-1,physical.memory.free=183.2M,swap.space.total=-1,swap.space.free=-1,heap.memory.used=743.6M,heap.memory.free

**Comment by mdogan** [comment]
@marke352788: Can you be more specific? What's the issue here?

**Comment by marke352788** [comment]
After this prompt is displayed, the program runs for a period of time and discovers an overflow，the logs error:java.lang.OutOfMemory.

**Comment by mdogan** [comment]
It seems your app is running out of memory after some time, either configured memory amount is not enough or your app has a memory leak. You can try increasing JVM heap memory and get a heap dump when JVM goes OOM using these JVM params: `-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/path/to/heap/dump`.

You should inspect that heap dump to see what's going on. We can't do much further without a heap dump analysis, without knowing application's Hazelcast usage style/pattern and detailed logs.
