### ISSUE TITLE
AbstractLoadBalancer unused parameter

### ISSUE THREAD

**Issue by YiYeHuang** [hazelcast/hazelcast#12974]
Hi ClientConfig in  AbstractLoadBalancer init doesn't seems do anything

```java
@Override
 public final void init(Cluster cluster, ClientConfig config) {
    this.clusterRef = cluster;
    cluster.addMembershipListener(this);
}
```

**Comment by mdogan** [comment]
Because `ClientConfig` argument is part of `LoadBalancer.init(Cluster, ClientConfig)` interface method signature. It may be required/used in different `LoadBalancer` implementations but not used in `AbstractLoadBalancer`.
