### ISSUE TITLE
Delete AbstractCompletableFuture

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#12986]
This class is making use of intrinsic locks leading to problematic gc's; that was one of the reasons the AbstractInvocationFuture was introduced in the first place.

**Comment by pveentjer** [comment]
This class is only used by HD queries; so probably I'll deal with it there.

**Comment by mmedenjak** [comment]
Removed with https://github.com/hazelcast/hazelcast/pull/15441, closing.
