### ISSUE TITLE
MapIndexLifecycleTest.recordStoresAndIndexes_createdDestroyedProperly failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#12991]
*maintenance* (commit 295e5ebab8772a693b761df9645653107603e1c4)

Failed on Zing JDK8: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZingJDK8/3/consoleFull#1654123599befca796-5603-419b-b87e-3b231b9aafc7

Stacktrace:
```
10:40:20 java.lang.AssertionError: record stores not empty
10:40:20 	at org.junit.Assert.fail(Assert.java:88)
10:40:20 	at org.junit.Assert.assertTrue(Assert.java:41)
10:40:20 	at com.hazelcast.map.MapIndexLifecycleTest.assertAllPartitionContainersAreEmpty(MapIndexLifecycleTest.java:212)
10:40:20 	at com.hazelcast.map.MapIndexLifecycleTest.recordStoresAndIndexes_createdDestroyedProperly(MapIndexLifecycleTest.java:91)
```

I think that the cause it the same as in https://github.com/hazelcast/hazelcast/issues/12597 - improper usage of assertTrue instead of assertEventually. I will prepare a fix soon.

**Comment by vbekiaris** [comment]
After `IMap.destroy`, it is expected that the map's containers have already been destroyed synchronously, so `assertTrue` should be ok in this case. Do we have complete logs from the test run?

**Comment by Holmistr** [comment]
@vbekiaris Yes, you can find it here: https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-3.maintenance-ZingJDK8/3/?region=us-east-1

**Comment by vbekiaris** [comment]
The failure is due to map-loading operations being executed concurrently with `map.destroy` -> a race results in creation of `RecordStore`s which are assumed destroyed and assertion fails. Since the `MapLoader` is irrelevant to the purpose of the test, we should remove the configured `MapLoader` and fill the map with plain `put`s.

Sample of test failure (from a branch with additional logging):
```
12:38:33,842  INFO |recordStoresAndIndexes_createdDestroyedProperly| - [MapServiceContextImpl] recordStoresAndIndexes_createdDestroyedProperly - [127.0.0.1]:5605 [dev] [3.10.1-SNAPSHOT] Local map stats destroyed  <-- [localMapStatsProvider.destroyLocalMapStatsImpl(mapContainer.getName());](https://github.com/hazelcast/hazelcast/blob/6c5c6302734849c9e164ac8fdd8bc58d9b678d65/hazelcast/src/main/java/com/hazelcast/map/impl/MapServiceContextImpl.java#L396) executed

12:38:33,844 ERROR |recordStoresAndIndexes_createdDestroyedProperly| - [OperationRunnerImpl] hz._hzInstance_605_dev.partition-operation.thread-1 - [127.0.0.1]:5605 [dev] [3.10.1-SNAPSHOT] beforeRun of class com.hazelcast.map.impl.operation.KeyLoadStatusOperation invokes PartitionContainer.getRecordStore <-- this gets-or-creates a RecordStore concurrently with their destruction
```
