### ISSUE TITLE
Ringbuffer.addAsync() can add items out-of-order

### ISSUE THREAD

**Issue by ekoutanov** [hazelcast/hazelcast#13010]
**Observed behaviour**
Calling `Ringbuffer.addAsync()` in rapid succession from a single thread will result in items being placed on the ringbuffer in an order that is occasionally _different_ from the order that `addAsync()` was called. In other words, when adding items _A_, _B_ and _C_ sequentially in that order, they may appear as _B_, _C_, _A_ on the ringbuffer.

**Expected behaviour**
While the ordering semantics don't appear to be documented explicitly, one would expect that when building strictly-ordered messaging systems, the order of the messages sequentially enqueued by the sender would equate to the order of their deposition in the ringbuffer, irrespective of whether or not they were sent asynchronously. While the `ExecutionCallback` may be invoked in arbitrary order in `ICompletableFuture`, the sequence numbers should match the order in which the items were added.

**Note:** The problem is only observable when multiple `HazelcastInstance`s are used and a proper cluster is formed. When a single instance is used, sequences are always asigned in the order of calls to `addAsync()`.

The following test replicates this scenario, publishing a bunch of items on the ringbuffer from a single instance, asserting the order of sequenceIds assigned in the `ExecutionCallback`, and also subsequently reading back from the ringbuffer to verify the order. Because of its non-deterministic nature, the test might need to cycle a few times before it picks up on the race condition.

The test below uses a `TestHazelcastInstanceFactory` to speed things up; the issue is also observable with a conventional `HazelcastInstanceFactory`

```java
public final class AddAsyncOrderTest {
  @Test
  public void test() throws InterruptedException, ExecutionException {
    final int numInstances = 4;        // only fails with multiple instances
    final int iterations = 10;         // sometimes takes a few iterations to fail
    final int itemsPerIteration = 100; // how many items will be added to the buffer
    
    for (int iteration = 0; iteration < iterations; iteration++) {
      System.out.println("iteration=" + iteration);
      // configure and prestart a bunch of instances
      final List<HazelcastInstance> instances = new ArrayList<>(numInstances);
      final Config config = new Config()
          .setProperty("hazelcast.logging.type", "none")
          .addRingBufferConfig(new RingbufferConfig().setName("default").setBackupCount(3).setCapacity(itemsPerIteration));
      final TestHazelcastInstanceFactory factory = new TestHazelcastInstanceFactory();
      IntStream.range(0, numInstances).parallel().forEach(i -> instances.add(factory.newHazelcastInstance(config)));
      
      // get a ringbuffer from one of the instances
      final HazelcastInstance instance = instances.get(iteration % numInstances);
      final Ringbuffer<Integer> ring = instance.getRingbuffer("buffer-" + iteration);
      
      // send all the items and await all callbacks with a countdown latch
      final CountDownLatch latch = new CountDownLatch(itemsPerIteration);
      final AtomicReference<AssertionError> error = new AtomicReference<>();
      final int _iteration = iteration;
      for (int item = 0; item < itemsPerIteration; item++) {
        // send each item one by one and compare its queued number with the allocated sequence number
        final ICompletableFuture<Long> writeFuture = ring.addAsync(item, OverflowPolicy.FAIL);
        final int _item = item;
        writeFuture.andThen(new ExecutionCallback<Long>() {
          @Override 
          public void onResponse(Long sequence) {
            // the callback may be called out of order, which is perfectly fine; but the sequence numbers
            // must match the order in which the items were enqueued
            try {
              assertEquals(_item, (long) sequence);
            } catch (AssertionError e) {
              // if we detect a problem, save the AssertionError as the unit test is running in a different thread
              System.err.println("SEQUENCE OUT OF ORDER: item=" + _item + ", sequence=" + sequence + ", iteration=" + _iteration);
              error.set(e);
            } finally {
              latch.countDown();
            }
          }
  
          @Override 
          public void onFailure(Throwable t) {
            t.printStackTrace();
          }
        });
      }
      
      // wait for all callbacks
      latch.await();
      
      // assert correct order by reading from the buffer
      final ICompletableFuture<ReadResultSet<Integer>> readFuture = ring.readManyAsync(0, itemsPerIteration, 1000, null);
      final ReadResultSet<Integer> readResultSet = readFuture.get();
      assertEquals(itemsPerIteration, readResultSet.size());
      for (int itemIndex = 0; itemIndex < itemsPerIteration; itemIndex++) {
        final int readItem = readResultSet.get(itemIndex);
        assertEquals(itemIndex, readItem);
      }
      
      // clean up
      instances.forEach(inst -> inst.getLifecycleService().terminate());
      
      // check if any assertion errors were observed during the run
      if (error.get() != null) {
        throw error.get();
      }
    }
  }
}

```

**Environment**
JDK10, MacOS, Hazelcast versions tested 3.9, 3.10-BETA-2, 3.10

**Comment by pveentjer** [comment]
This isn't a big, it works as intended.

Order isn't defined when an invocation starts. Async invocations are considered concurrent invocations and concurrent invocations can be executed in any order. 

If you want guaranteed ordering, you need to wait till the invocation completes and then send the next.

**Comment by pveentjer** [comment]
I'm reopening it for further discussion. But we don't provide any a consistency model based on invocation start. Because it would prevent optimizations and make life for us a lot more complex. Also in case of failover messages get be reordered.

**Comment by ekoutanov** [comment]
To further stimulate the conversation...

Consider as a comparative example Kafka's approach to asynchronous publishing. The `Producer.send()` method is asynchronous, returning a `Future`. (Much like `Ringbuffer.addAsync()`.) It may also complete the invocation in arbitrary order. However, messages are deposited in the strict order of `send()` invocations, while at the same time preserving asynchrony and being sufficiently performant. In other words, offsets are assigned in the same order as the messages are sent on the producer.

While I'm not suggesting that Hazelcast should necessarily emulate Kafka's behaviour, there are some similarities in prospective applications of message streaming and the use of ringbuffers — namely, creating totally ordered message sequences. In these contexts, it is typically necessary to preserve order without necessarily blocking the producer. The current `Ringbuffer.addAsync()` API requires you to send messages one-at-a-time, blocking until the previous message completes before enqueuing the next message. (If you want to preserve order.) Needless to say that this approach leads to abysmal throughput.

I do realise that a `Ringbuffer`also has an `addAllAsync()` method, which does preserve item order, albeit for the batch of items within a single method call, but not across batches. It may be prudent to update the documentation to elaborate on these semantics, and perhaps include a big GOTCHA clause that elaborates on the expected behaviour and associated implications. Currently, the workaround that I use is `addAllAsync()`, with custom micro-batching of messages to get decent throughput.

**Comment by mmedenjak** [comment]
As Peter mentions, this is a deeper change. From what I see in the test, you are using different members to publish each item. Effectively, this is concurrently sending operations to a single member which owns the ringbuffer. The catch being, that Kafka probably waits for the receiver to acknowledge that the operation was received (but not processed) while Hazelcast doesn't.

If you were to use a single member to publish all items (even in a multi-member cluster), you might achieve this ordering as there is ordering when writing to a single connection. That is, until one operation has to be retried.

**Comment by ekoutanov** [comment]
Hi @mmedenjak ,
For any given iteration of the test, the messages are published from a _single_ instance. (Which I'm assuming is equivalent to 'member'.) The test picks the instance from the pool if instances (by modding the iteration number by the number of instances) and sticks with that instace for the duration of the iteration. It publishes 100 items from the same instance and moves on to the next iteration (unless it detects a failure). The other instances act as replicas.

You are absolutely right in that Kafka will wait for receiver to acknowledge before cueing the next. (To be precise, Kafka has the concept of max in-flight requests, which are user-configurable. Setting that to one leads to guaranteed ordering, even in the event of node failure and leader changes.)

I feel that, at minimum, the documentation should be amended to clarify this behaviour.

Just for additional context, I'm using it in the [Meteor](https://github.com/obsidiandynamics/meteor) project — essentially emulating Kafka-like semantics within an in-memory data grid. And I'm rather enjoying the abstractions that Hazelcast offers to build higher order messaging infrastructure. I've since changed the solution to implement custom micro-batching and use `Ringbuffer.addAllAsync()` to ensure strict order while maintaining high throughput and predicatable latency.
