### ISSUE TITLE
Hazelcast 3.10 xsd on website does not correspond to the xsd in the jar

### ISSUE THREAD

**Issue by MichelSchudel** [hazelcast/hazelcast#13011]
The Hazelcast 3.10 xsd located at https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd  does not correspond to the hazelcast-config-3.10.xsd in the hazelcast jar. We encountered this while configuring a merge policy for a multiMap while we had a schema declaration in the config xml that pointed to the external xsd on the website.

**Comment by mmedenjak** [comment]
@MichelSchudel thanks for the report!
@mesutcelik do you know how this XSD is published? Do we need to republish?

**Comment by mesutcelik** [comment]
It is normally published when we do release of hazelcast patch or minor version. There is no nightly upload unfortunately.

@MichelSchudel Is this any issue in your IDE? Normally hazelcast uses XSD within the jar file so no need to check what is available on the web.

**Comment by mmedenjak** [comment]
@MichelSchudel any updates on this issue?

**Comment by MichelSchudel** [comment]
I have no idea how the xsd is published on the hazelcast site. I only
noticed that that 3.10 version on the site was not equal to the 3.10
version in the release jars.

**Comment by mdogan** [comment]
XSD file on website is still different than XSD file on repo in v3.10 tag.

- https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd
- v3.10 tag: https://raw.githubusercontent.com/hazelcast/hazelcast/v3.10/hazelcast/src/main/resources/hazelcast-config-3.10.xsd
- v3.10.4 tag: https://raw.githubusercontent.com/hazelcast/hazelcast/v3.10.4/hazelcast/src/main/resources/hazelcast-config-3.10.xsd

**Comment by mesutcelik** [comment]
@Holmistr @hasancelik 
I remember each .com website refresh was overriding XSDs. Did we fix that problem?

**Comment by Holmistr** [comment]
I believe it should be fixed now. I'm kind of busy, would you mind checking this?

**Comment by mesutcelik** [comment]
@Holmistr ,
I checked and they are the same. If you think after your fix , that will not happen again then you can close the issue.

**Comment by Holmistr** [comment]
Yep, closing this issue.
