### ISSUE TITLE
Setting an Exception in an IAtomicReference causes it to be thrown when getting it

### ISSUE THREAD

**Issue by mirkoluchi** [hazelcast/hazelcast#13138]
I'm using an Hazelcast **IAtomicReference** to store a **reference to an Exception** object. When I try to get the stored **Exception**, it is **thrown** rather than returned.
Is it a **desired behaviour** (I couldn't find any mention to it in the documentation) **or** is it a **defect**?

```Java
@Test(expected=RuntimeException.class)
public void testExceptionInAtomicReference {
        Config config = new Config();
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);

        Exception e = new RuntimeException("my exception");
        IAtomicReference<Exception> ref = hz.getAtomicReference("excRef");
        ref.set(e);
        Exception exception = ref.get(); // <--- This throws the exception stored rather than returning it
}
```

**Comment by tkountis** [comment]
Reopening.
Change got reverted in master. (see https://github.com/hazelcast/hazelcast/pull/13601)
Will revisit in the future.

@mirkoluchi as a temporary fix, you could wrap the Exceptions in another object.
