### ISSUE TITLE
Rest endpoint should not send HTTP 200 on error

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#13150]
It appears the Rest interface - in some cases - still sends HTTP 200 even when the operation failed. 
Example: [Change cluster version](https://github.com/jerrinot/hazelcast/blob/e9b80f83326a22ce1bc1f49045c3873e70b8ad39/hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpPostCommandProcessor.java#L159-L182)

When there is an exception during a version change then the stacktrace is part of the response body, but Hazelcast still returns HTTP 200. This makes the Rest API hard to use in cluster automation.

**Comment by the-thing** [comment]
This seems to be fixed by https://github.com/hazelcast/hazelcast/pull/16148

**Comment by jerrinot** [comment]
@the-thing good catch, thank you!
I am closing it as fixed by https://github.com/hazelcast/hazelcast/pull/16148
