### ISSUE TITLE
Paging predicate causes full scans on small result sets

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#13159]
If the inner predicate of the paging predicate returns an empty result set, the paging predicate returns `null` as the indexed query result, this interpreted as an absence of the indexed result by the query engine and the execution falls back to the full scan.

For OS edition this causes the full scan reevaluation of the indexed query returned an empty result. For HD this causes the full scan reevaluation on every partition returned an empty result.

**Comment by sertugkaya** [comment]
Related to ZD3902.
