### ISSUE TITLE
Print a warning when British spelling of "License" is used [HZ-3156]

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast#13161]
Consider adding a warning if `-Dhazelcast.enterprise.licence.key` is used instead of `-Dhazelcast.enterprise.license.key`.

Initially propsed by @jerrinot for the Docker image: https://github.com/hazelcast/hazelcast-docker/issues/68

**Comment by JackPGreen** [comment]
Hazelcast properties that *could* have a British English alternative:
| Property Name                               | Suggested British English Property Name         |
|---------------------------------------------|-------------------------------------------------|
| hazelcast.enterprise.license.key            | hazelcast.enterprise.**licence**.key            |
| hazelcast.index.copy.behavior               | hazelcast.index.copy.**behaviour**              |
| hazelcast.serialization.version             | hazelcast.**serialisation**.version             |
| raft.linearizable.read.optimization.enabled | raft.linearizable.read.**optimisation**.enabled |

I'm not suggesting we change the rest, I just wanted to see how often this scenario occurs (generated using `com.hazelcast.spi.properties.HazelcastPropertiesTest.main(String[])` in my PR)
