### ISSUE TITLE
com.hazelcast.spi.exception.RetryableHazelcastException throw to user calling getMap()

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13225]
should we be throwing this exception out to the user ? 

```
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[10.0.0.41]:5701] is not active!
    at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:368)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.<init>(ProxyRegistry.java:53)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:81)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl$1.createNew(ProxyServiceImpl.java:79)
    at com.hazelcast.util.ConcurrencyUtil.getOrPutIfAbsent(ConcurrencyUtil.java:107)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getOrCreateRegistry(ProxyServiceImpl.java:138)
    at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.getDistributedObject(ProxyServiceImpl.java:146)
    at com.hazelcast.instance.HazelcastInstanceImpl.getDistributedObject(HazelcastInstanceImpl.java:387)
    at com.hazelcast.instance.HazelcastInstanceImpl.getMap(HazelcastInstanceImpl.java:187)
    at com.hazelcast.instance.HazelcastInstanceProxy.getMap(HazelcastInstanceProxy.java:98)
```

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-All/64/console



/disk1/jenkins/workspace/shutdown-All/3.10.2/2018_05_29-17_06_14/stable/sql/serializable Failed

```
fail HzMember2HZ _serializable__sql_sz_mapBak1HDSqlIdx com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[10.0.0.41]:5701] is not active! 
```

http://54.82.84.143/~jenkins/workspace/shutdown-All/3.10.2/2018_05_29-17_06_14/stable/sql/serializable

**Comment by Danny-Hazelcast** [comment]
this is a shutdown test, so it is expected that members of that cluster can be shutdown while the test is running.

**Comment by mmedenjak** [comment]
I think this might be expected. The member is currently shutting down:
```
May 30, 2018 2:55:08 PM com.hazelcast.core.LifecycleService
INFO: [10.0.0.41]:5701 [HZ] [3.10.2] [10.0.0.41]:5701 is SHUTTING_DOWN
May 30, 2018 2:55:31 PM com.hazelcast.instance.Node
INFO: [10.0.0.41]:5701 [HZ] [3.10.2] Shutting down connection manager...
May 30, 2018 2:55:31 PM com.hazelcast.instance.Node
INFO: [10.0.0.41]:5701 [HZ] [3.10.2] Shutting down node engine...
```
And concurrently we try and add a map index:
```
MQ msg in = {"taskId":"_serializable__sql_sz_mapBak1HDSqlIdx","cmd":"InitCmd"}
com.hazelcast.spi.exception.RetryableHazelcastException: HazelcastInstance[[10.0.0.41]:5701] is not active!
```
The problem here is that the instance has already shut down its services, its connections to other members and does not contain the partition table. So I don't know what the instance can do with the add index command other than throw an exception. 

Or is the problem that the method throws a `RetryableHazelcastException` instead of a `HazelcastInstanceNotActiveException`? WDYT @Danny-Hazelcast

**Comment by Danny-Hazelcast** [comment]
@mmedenjak  

method throws RetryableHazelcastException: instead of one of the following 

com.hazelcast.core.OperationTimeoutException:
com.hazelcast.core.MemberLeftException:
com.hazelcast.spi.exception.TargetDisconnectedException:
com.hazelcast.spi.exception.TargetNotMemberException:
com.hazelcast.core.HazelcastInstanceNotActiveException:
java.util.concurrent.ExecutionException:
java.lang.IllegalStateException:

the above list is all ready very long. should we be throwing yet another type of exception out the user ?

**Comment by Danny-Hazelcast** [comment]
re running https://hazelcast-l337.ci.cloudbees.com/view/shutdown/job/shutdown-x/77/console

**Comment by Danny-Hazelcast** [comment]
looks like it's fixed

**Comment by Holmistr** [comment]
@mmedenjak Wohooo, congrats! Thanks, @Danny-Hazelcast !
