### ISSUE TITLE
Apache Mesos Enhancement Request

### ISSUE THREAD

**Issue by hvandenb** [hazelcast/hazelcast#1323]
When running a cluster of hazelcast nodes it's not always that each node is being fully used. In addition, if you're wanting to optimize the resource usage of other components, hadoop cassandra on the same node a good resource manager would be great to have.

The Apache Mesos framework allows for cluster management. Is this something on the roadmap to integrate with this framework?
http://mesos.apache.org

**Comment by jjongsma** [comment]
Hazelcast has issues with Docker containerization from my experience - host networking mode and explicit network interface configuration is required to avoid IP mismatches during initial connection checks, so it won't scale well on Mesos if you're packing many containers per slave.

**Comment by resouer** [comment]
Hi, @jjongsma , I think you should not use Hazelcast with Docker host networking, you need more advanced container framework like Kubernetes can handle Hazelcast well. 

For anyone interested in this, see: https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/hazelcast

**Comment by eschizoid** [comment]
@enesakar Is there any update related to this ticket?

**Comment by hvandenb** [comment]
After reviewing the proposal closer with Docker that would not make sense. The goal of Mesos is to provide resource management. Like Kubernetes it's a resource scheduler that sits between the resources (hardware) and the software Hazelcast.

**Comment by gAmUssA** [comment]
@hvandenb Hazelcast support for Mesos landed here https://github.com/hazelcast/hazelcast-mesos. 
Let us know what do you think!
Cheers,
Vik
