### ISSUE TITLE
Built-in predicate implementations do not implement equals/hashCode

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#13245]
The predicate implementations can be compared for equality based on their fields' values. Additionally, not having `equals` implementation makes it hard to test those classes. Leftover from https://github.com/hazelcast/hazelcast/pull/13242.

**Comment by webashutosh** [comment]
@vbekiaris I just added a commit to implement the methods. I am a first-time committer to this repo and I am very keen on contributing more. Could you please let me know of any review comments?

**Comment by vbekiaris** [comment]
@webashutosh that's awesome! As a first time contributor, you need to sign the [contributor agreement (see here for instructions)](https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement). I'll post my review comments on the pull request. Thanks!

**Comment by taburet** [comment]
Implemented in https://github.com/hazelcast/hazelcast/pull/13318 , closing.
