### ISSUE TITLE
Hazelcast + Hibernate Query cache configurations (Local Region)

### ISSUE THREAD

**Issue by tandonraghav** [hazelcast/hazelcast#13288]
I am trying to integrate hazelcast with a Spring boot project.
**Hazelcast - 3.9.4**
**hazelcast-hibernate4**

Setting up Hibernate L2 cache in Cluster Mode and connecting like a Native client.
The setup works fine (both for L2+Query cache) and I can see data in my cluster , but I want to do configuration for **Query cache** also like **TTL,Max elements** etc. which I am not able to figure out.

I know Query cache data is on Local heap which bothers me as it should not go beyond a certain limit.
I understand there is a cleanUp() and MAX_SIZE and TTL is defined by default but this might be too less.

Is there a way to set up configuration for **org.hibernate.cache.internal.StandardQueryCache**.
But how to configure if I am connecting as a Native Client as it **ClientInstance** does not allow to configure anything in hazelcast.xml. 

**HibernateConfig.java**

                    properties.put(Environment.CACHE_REGION_FACTORY, HazelcastCacheRegionFactory.class.getName());
			properties.put(Environment.CACHE_PROVIDER_CONFIG, systemSettings.getHibernateCacheServerPropertiesLocation());
			properties.setProperty(Environment.TRANSACTION_STRATEGY, JdbcTransactionFactory.class.getName());
			properties.put("javax.persistence.sharedCache.mode", SharedCacheMode.ENABLE_SELECTIVE);
			properties.put("javax.persistence.cache.retrieveMode", CacheRetrieveMode.USE);

			properties.put("hibernate.cache.hazelcast.use_native_client",true);
			properties.put("hibernate.cache.hazelcast.native_client_address","127.0.0.1:5704");
			properties.put("hibernate.cache.hazelcast.native_client_group","dev");
			properties.put("hibernate.cache.hazelcast.native_client_password","dev-pass");
                    properties.put(Environment.USE_QUERY_CACHE, true);		        
                    properties.put(Environment.USE_SECOND_LEVEL_CACHE,true);

  <hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.9.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">

    <hazelcast-client xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.hazelcast.com/schema/client-config
                               http://www.hazelcast.com/schema/client-config/hazelcast-client-config-3.9.xsd"
                  xmlns="http://www.hazelcast.com/schema/client-config">

    <group>
        <name>dev</name>
        <password>dev-pass</password>
    </group>

    <network>
        <cluster-members>
            <address>127.0.0.1:5701</address>
        </cluster-members>
    </network>
</hazelcast-client>

**Comment by tandonraghav** [comment]
Any updates on this?? I need to change default value of MAX_SIZE and TTl for StandardQueryCache?

**Comment by enozcan** [comment]
Hi @tandonraghav 

It seems like not possible when using Hazelcast Client. 

In P2P mode, if you set a map config for Hazelcast Instance and use this region for your query results to be cached, then the region will have these customized properties. Such that:

```xml
<map name="*-with-TTL">
        <time-to-live-seconds>15</time-to-live-seconds>
</map>
```
```java
List<Item> itemList =  session.createQuery(<query_stmt>)
                .setCacheable(true)
                .setCacheRegion("Item-Query-Cache-with-TTL").list();
```

Here the cache region will have TTL value of 15 seconds. However, this is not the case when you use client since you cannot configure the cluster maps from clients. 

A related issue is [that](https://github.com/hazelcast/hazelcast-hibernate5/issues/73).

**Comment by Holmistr** [comment]
Hi @tandonraghav , looks like your question has been answered, although you might not be happy with the answer :(
If you have any further questions, please go ahead. Otherwise I guess we can close the issue?

**Comment by tandonraghavs** [comment]
@Holmistr Yeah close this issue.
