### ISSUE TITLE
node suddenly left the cluster

### ISSUE THREAD

**Issue by sremus** [hazelcast/hazelcast#13285]
I'm using Hazelcast together with Payara Micro 4(.174) on AWS/ECS and I've experienced an issue I've never seen before and I'm wondering if you guys could throw me a bone.

Log attached.

[hazelcast_log.log](https://github.com/hazelcast/hazelcast/files/2090391/hazelcast_log.log)

TL;DR a node suddenly left the cluster and then noticed some exceptions.

**Comment by sremus** [comment]
Hey @jerrinot 

Thing is, I'm sending all the logs to Cloudwatch and the attached logs, are actually from there; it's not the whole log just the chunk whit the error. 

I'll attach the whole thing but there's not much info I could personally find.

Thanks !

[hazelcast_full_log.log](https://github.com/hazelcast/hazelcast/files/2092860/hazelcast_full_log.log)

**Comment by sremus** [comment]
I've added the log from the .248 node and I've filtered messages from the HealthMonitor like:

`[2018-06-09T00:00:06.499+0000] [] [1;92m[INFO][0m [] [[1;94mcom.hazelcast.internal.diagnostics.HealthMonitor[0m] [tid: _ThreadID=53 _ThreadName=hz._hzInstance_1_dev.HealthMonitor] [timeMillis: 1528502406499] [levelValue: 800] [10.48.98.248]:5701 [dev] [3.8.5] processors=2, physical.memory.total=3.9G, physical.memory.free=2.3G, swap.space.total=0, swap.space.free=0, heap.memory.used=765.1M, heap.memory.free=19.9M, heap.memory.total=785.0M, heap.memory.max=878.5M, heap.memory.used/total=97.47%, heap.memory.used/max=87.10%, minor.gc.count=912, minor.gc.time=12931ms, major.gc.count=486, major.gc.time=453048ms, load.process=0.00%, load.system=0.01%, load.systemAverage=0.00%, thread.count=100, thread.peakCount=106, cluster.timeDiff=-4, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=6448865, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=2, client.connection.count=0, connection.count=2`

[hazelcat_log_alternate_node.log](https://github.com/hazelcast/hazelcast/files/2093810/hazelcat_log_alternate_node.log)

**Comment by mdogan** [comment]
From the logs from 10.48.99.245, it's obvious that 10.48.98.248 is removed because of a ping failure:
```
[2018-06-09T18:35:41.873+0000] [WARNING] ClusterHeartbeatManager [10.48.99.245]:5701 [dev] 
 [3.8.5] [10.48.99.245]:5701 will ping [10.48.98.248]:5701

[2018-06-09T18:35:41.880+0000] [WARNING] ClusterHeartbeatManager [10.48.99.245]:5701 [dev] 
 [3.8.5] [10.48.99.245]:5701 could not ping [10.48.98.248]:5701

[2018-06-09T18:35:41.881+0000] [INFO] ClusterService [10.48.99.245]:5701 [dev] [3.8.5] Old master 
 [10.48.98.248]:5701 left the cluster, assigning new master Member [10.48.99.245]:5701 - 24627300- 
 253c-4d19-b1e1-caefb8d123fa this

[2018-06-09T18:35:41.881+0000] [INFO] TcpIpConnection [10.48.99.245]:5701 [dev] [3.8.5] 
 Connection[id=1, /10.48.99.245:44483->/10.48.98.248:5701, endpoint=[10.48.98.248]:5701, 
 alive=false, type=MEMBER] closed. Reason: [10.48.99.245]:5701 could not ping [10.48.98.248]:5701

[2018-06-09T18:35:41.882+0000] [INFO] ClusterService [10.48.99.245]:5701 [dev] [3.8.5] Removing 
 Member [10.48.98.248]:5701 - b4c2fafe-9924-46fc-89f9-886bc8f0fb04
```

If you look at the following logs from 10.48.98.248, it seems it's facing a few long pauses (`MonitorInvocationsTask delayed 90072 ms`):

```
[2018-06-09T18:35:23.676+0000] [WARNING] InvocationMonitor [10.48.98.248]:5701 [dev] [3.8.5] 
 MonitorInvocationsTask delayed 19819 ms

[2018-06-09T18:35:25.655+0000] [WARNING] ClusterHeartbeatManager [10.48.98.248]:5701 [dev] 
 [3.8.5] Ignoring heartbeat from Member [10.48.99.245]:5701 - 24627300-253c-4d19-b1e1- 
 caefb8d123fa since it is expired (now: 2018-06-09 18:34:37.960, timestamp: 2018-06-09 
 18:34:01.870)

[2018-06-09T18:35:26.877+0000] [WARNING] ClusterHeartbeatManager [10.48.98.248]:5701 [dev] 
 [3.8.5] Ignoring heartbeat from Member [10.48.99.179]:5701 - 2f93adea-d7c1-4530-83c5- 
 cac2c324ecc5 since it is expired (now: 2018-06-09 18:34:37.960, timestamp: 2018-06-09 
 18:34:04.284)

[2018-06-09T18:36:17.595+0000] [WARNING] InvocationMonitor [10.48.98.248]:5701 [dev] [3.8.5] 
 MonitorInvocationsTask delayed 42718 ms

[2018-06-09T18:36:57.755+0000] [WARNING] InvocationMonitor [10.48.98.248]:5701 [dev] [3.8.5] 
 MonitorInvocationsTask delayed 90072 ms
```

**Comment by mdogan** [comment]
Please note that ICMP ping failure detector may not work as expected before Hazelcast version 3.9.1. We introduced an enhanced version of ICMP ping failure detector in 3.9.1. 
See https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#ping-failure-detector

**Comment by mdogan** [comment]
Closing this issue for now. With those huge pauses, it's expected to observe member removals because of heartbeat failures. Feel free to report a new issue if you have more details or a member removals with a different cause.
