### ISSUE TITLE
Connected clients slow down dramatically when server port is connected without receiving anything

### ISSUE THREAD

**Issue by wangxhere** [hazelcast/hazelcast#13298]
**Pre-Condition**

HC cluster with 2 nodes, running as embedded servers. There is a health monitoring script on each of the nodes which connect to the server port 5701 using `nc` every half minute, disconnects after 1 seconds without sending anything.

There are 2 clients connecting to the cluster using Java client. A 1-second timeout is set for all the operations performed by those clients.

**Scenario**

There is a high chance client-side operation would slow down around the time when `nc` on server instance tries to connect and disconnect, causing client procedure to timeout.

This scenario is replicable in different network and server setups on our side.

**Expected Result**

As the health check is not even trying to connect to server port in a malicious way, it is expected that this should not affect normal client-side operation.

**Comment by sancar** [comment]
Hi @wangxhere  ,
Can you post the exact command that you use including the parameters you pass with `nc` ?
`A 1-second timeout is set for all the operations performed by those clients.`
Which property exactly you are referring to ? If there is any other special config you use, can you share them with us also ?

**Comment by tezc** [comment]
Hi @wangxhere ,
We are trying to reproduce the issue. In addition to @sancar  's, can you share some more details with us? What is the version of Hazelcast? Do clients reconnect each time? (Client connect, perform single op, disconnect vs Client connect once, perform all operations).

**Comment by wangxhere** [comment]
@tezc @sancar 
I was using `nc -w 1 127.0.0.1 5701` to connect to the port and immediately disconnect (without sending anything). During doing this, the other clients were experiencing pauses. Version of Hazelcast was 3.9.2 (embedded in own app). Normal client does not reconnect but maintains long connection at all times. Only that `nc` disconnects each time.

**Comment by tezc** [comment]
Hi @wangxhere ,
This issue is fixed in 3.10.3, see https://github.com/hazelcast/hazelcast/pull/13363
I can only reproduce it with 3.10.2 and below. Please upgrade and test it with 3.10.3 and above.

**Comment by tezc** [comment]
Closing the issue, please open a new issue if you see this problem in newer versions.
