### ISSUE TITLE
Support for distributed B+tree

### ISSUE THREAD

**Issue by romix** [hazelcast/hazelcast#133]
Currently Hazelcast is based on the DHT (Distributed Hash Table) approach, which is very popular these days.
This approach is very effective if you do only key-based queries, i.e. single point queries.

But if you need to perform range queries (e.g. "give me all entries with key > minVal and key < maxVal), they cannot be performed efficiently using the DHT approach, as hashing does not preserve sorting order. Therefore a full scan is usually performed. To improve performance in such cases, some sort of indexing is required. Most DBs use different variations of B+trees for this purpose. 

Remark: 
- B+trees can be also efficiently used for storing data on external storage (HDDs, SSDs, etc).
- distributed B+trees would also make implementation of tree-based data structures much easier
- distributed B+trees can be used for session replication, where the session state or set of session's attributes is structured as trees.

Proposal:
- Add support for distributed B+trees into Hazelcast
- Add support for distributed indices based on B+trees
- Add support for effective execution of range queries
- Optional: Add support for further data structures that can be built on top of distributed B+tress.
- Optional: Add B+tree based storage backend to Hazelcast to overcome the overall RAM size limitations of the cluster? E.g. using JDBM or something similar for it?

Some useful links:

Paper: A Practical Scalable Distributed B-Tree 
www.vldb.org/pvldb/1/1453922.pdf

Paper: Efficient Btree-Based Indexing for Cloud Data Processing
https://www.iusb.edu/computerscience/people/raman/.../R107.pdf

Distributed B+tree implementation (open-source)
http://www.mckoi.com/mckoiddb/index.html

JDBM3 (Apache license)
https://github.com/jankotek/JDBM3

**Comment by ib84** [comment]
for reference, there is now a documentation:  http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html
However, implementing a distributed Tree doesn't seem "easy to implement".
It would still be nice to have a one datastructure with good support for sorting, implemented by the HZ-chefs...

**Comment by jyizheng** [comment]
What is the status of this issue?

**Comment by jerrinot** [comment]
@jyizheng Hazelcast support range queries using an index. See [this](https://docs.hazelcast.org/docs/4.0.1/manual/html-single/index.html#distributed-query) for an intro into querying, [here](https://docs.hazelcast.org/docs/4.0.1/manual/html-single/index.html#indexing-queries) is an index configuration. 

If you prefer to see tests then [this is a good starting point](https://github.com/hazelcast/hazelcast/blob/017512b508ea8d19b89d2eb2327475e39571a72c/hazelcast/src/test/java/com/hazelcast/map/impl/query/QueryBasicTest.java#L68). See also other tests classses in the same package.

**Comment by jyizheng** [comment]
@jagliot  Thanks, I just read. What is the data structure being used for the sorted index?

**Comment by jerrinot** [comment]
@jyizheng: As of Hazelcast 4.0 it's either Skip-list map or Red-black tree (for HD maps)

We are doing some major improvements into the query subsystem (see [design documents](https://github.com/hazelcast/hazelcast/tree/master/docs/design/sql)) and it's very likely we'll replace the Red-black tree index with B+tree.
