### ISSUE TITLE
Dynamically changed IMap config doesn't get picked by existing running member

### ISSUE THREAD

**Issue by ncherkas** [hazelcast/hazelcast#13305]
Code snippet to reproduce:

```
package com.hazelcast.reproducer.lch.map.backup.count;

import com.hazelcast.config.ClasspathXmlConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;

import java.util.concurrent.TimeUnit;

public class Member {

    public static void main(String[] args) throws Exception {
        Config config = new ClasspathXmlConfig("hazelcast.xml");
        HazelcastInstance member = Hazelcast.newHazelcastInstance(config);
        member.getMap("test1").put("k1", "v1");

        TimeUnit.SECONDS.sleep(10);

        member.getConfig().addMapConfig(new MapConfig("test1").setBackupCount(3));

        while (true) {
            System.out.println(member.getMap("test1").getLocalMapStats());
            TimeUnit.SECONDS.sleep(5);
        }
    }
}


```

In my `hazelcast.xml` I have only the license key and MC config.

Steps to reproduce:
 - run 1st member, observe that the local stats output is showing the backup count 1 even after 10 sec.
 - run 2nd, 3rd member
 - 1st member will be still printing the backup count 1 though other members are printing the correct value 3.

The expectation is that all members print the recent value of backup count. It seems like only new joined members are observing the correct value.

**Comment by ncherkas** [comment]
It also doesn't get updated on the Management Center UI if there is only one member in the cluster.

**Comment by jerrinot** [comment]
it should have thrown an exception at this line: `member.getConfig().addMapConfig(new MapConfig("test1").setBackupCount(3));`

as at the time when this line is executed there already exists a map with the same name. updating an existing configuration is illegal -> it should fail-fast and throw an exception.

**Comment by mdogan** [comment]
Created a new issue, see #13517.
