### ISSUE TITLE
com.hazelcast.query.impl.getters.ReflectionHelper#createGetter should ignore java.util.Optional getter methods

### ISSUE THREAD

**Issue by wneild** [hazelcast/hazelcast#13300]
It's not uncommon from Java 8 onwards for Java models with Nullable fields to adopt `Optional<T>` as the getter return type where the underlying field is type `T`.

This becomes a problem when attempting to index against a nullable field, as the underlying implementation finds the Optional getter method first rather than the value of the underlying field. A workaround _we_ use is to use a value extractor to extract the value from the optional as a map attribute and index against that.

The suggestion would be to add quality of life improvements to the ReflectionHelper to recognise an Optional getter method and fall through to resolving against the field value directly instead.

**Comment by Donnerbart** [comment]
Thanks for reporting this. Can you give us a short example/reproducer? This would help a lot to create a fix.

**Comment by wneild** [comment]
@Donnerbart Sure, here's an example of what I would like to see handled, that currently results in this being thrown internally on the .put invocation: 
``` It is not allowed to used a type that is not Comparable: class java.util.Optional
java.lang.IllegalArgumentException: It is not allowed to used a type that is not Comparable: class java.util.Optional
```

Code:
```
class Model implements Serializable {

    @Nullable
    private String example;

    public Optional<String> getExample() {
        return Optional.ofNullable(example);
    }

    public void setExample(@Nullable final String example) {
        this.example = example;
    }
}

class Application {

    public static void main(String[] args) {
        Config config = new Config();
        MapConfig mapConfig = config.getMapConfig("myExampleMap");
        mapConfig.addMapIndexConfig(new MapIndexConfig("example", true));

        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

        IMap<String, Model> map = instance.getMap("myExampleMap");
        map.put("key", new Model());
    }
}
```
