### ISSUE TITLE
ClientCheckDependenciesIT.testNoMandatoryDependencyDeclared failure

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#13358]
*master* (commit 60e11525cd85977b9ee6bd51611f463cc2452994)
*maintenance* (commit 3be1639dd4b5e497950aede41a41fbadecbafc34 )

Failed on various JDKs 8 (maintenance): https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.maintenance-OracleJDK8/com.hazelcast$hazelcast-client/642/testReport/junit/com.hazelcast.client.osgi/ClientCheckDependenciesIT/testNoMandatoryDependencyDeclared/
Failed on various JDKs 8 (master): https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/1537/testReport/junit/com.hazelcast.client.osgi/ClientCheckDependenciesIT/testNoMandatoryDependencyDeclared/

Stacktrace:
```
java.lang.AssertionError: Import com.eclipsesource.json is not declared as optional
```

**Comment by kwart** [comment]
The problem is rooted in #13189 and #13191. The newly introduced class `HazelcastCloudDiscovery` imports classes from `com.eclipsesource.json` so they are also added by `maven-bundle-plugin` to `MANIFEST.MF`
