### ISSUE TITLE
What's the recommended HA strategy for data upgrade in a cluster?

### ISSUE THREAD

**Issue by chaschev** [hazelcast/hazelcast#13389]
Consider we have a cluster running an app with JAR.v1. We want to upgrade it to JAR.v2, which will have different serialisation schema. Our serialisation is forward and backward compatible (Protocol Buffers or Kryo), but there is one problem - Hazelcast partition migrations. We don't want it to happen before our upgrade is finished, otherwise we won't be able to write v2 data updates on hosts running JAR.v1.

These instance restarts might take time or even fail. How do we make sure that data migration won't start? Is there a better way to do a job? 

I can think of several strategies, but none of them will guarantee to work a case when dev goes for peanuts and leaves cluster unattended. At least, I didn't find a way to temporarily disable migrations. Restart job fails, Hazelcast migration (unfortunately!) starts and then cluster is in a messy state and significant part of data cannot be written.

Thanks, Andrey.

**Comment by jerrinot** [comment]
hello @chaschev,

have a look at [`hazelcastInstance.getCluster().changeClusterState(ClusterState.NO_MIGRATION)`](https://github.com/jerrinot/hazelcast/blob/00ee8406b7945b601fc6c2e3783b7c53a5dd582d/hazelcast/src/main/java/com/hazelcast/cluster/ClusterState.java#L93) That should do the trick for you. Do not forget to change the state again once you are upgraded. 

I am closing this issue for now. If you need an additional help then please open a topic at our [forums](https://groups.google.com/forum/#!forum/hazelcast) and link this issue.
