### ISSUE TITLE
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 

### ISSUE THREAD

**Issue by hezouat** [hazelcast/hazelcast#13406]
Hello,

I often get this issue `com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type` during the de-serialiazer and  serialization/ de-serialization takes so much time. 

Environment:  Hazelcast version 3.10.2 (Latest),  glassfish 4.1. 

Could you tell me how I can fix it ?

Thank you for your support,

Zahir,

**Comment by pveentjer** [comment]
Do you have a reproducer?

And perhaps there is a serialization incompatibility between members and or clients. So imagine put an object in e.g. an IMap on one member with the proper serialization configuration to write/read that object.

And now on another member/client you read the object, but it doesn't have the proper serialization configuration to read/write that object. When it reads the object, then you will get a serialization exception.

So are you sure that the serialization configuration on all members/clients is the same?

**Comment by hezouat** [comment]
The HZ version is 3.10.2 (latest version) but I had this issue with 3.9.3 version. The serialization is the same in each members, we use serializers. However, we have hibernate librairies in your classloader, that might be the root cause ..

**Comment by mmedenjak** [comment]
@hezouat any updates on the issue?

**Comment by mmedenjak** [comment]
Closing as we are unable to fix the issue without more information. If you have any updates or encounter a new problem, please open a new issue.
