### ISSUE TITLE
QueueCache missing key/value information

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#13423]
On 3.11, an entry listener on the query cache lists the key as `null`, the value as `null` on added/updated, the old value as `null` on updated, etc. This doesn't happen for an entry listener on a map.

See the reproducer on https://github.com/hazelcast/hazelcast/issues/13402 to demonstrate the issue

**Comment by neilstevenson** [comment]
Slight correction

If you use

```
entryListenerConfig.setIncludeValue(false);
```

then the key and value is null. Key shouldn't be null here.

If you use

```
entryListenerConfig.setIncludeValue(true);
```

it works as expected.

**Comment by mmedenjak** [comment]
@ahmetmircik is this something we need to address in 4.0?

**Comment by ahmetmircik** [comment]
yes better to address it in 4.0.
