### ISSUE TITLE
Efficient serializers for common collections like HashMap, etc.

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#13448]
The problem is that these data-structures are currently serialized using java Serializable. And this is very effcient and what is worse, also the content is forced to be Serializable.

We should have out of the box serializers for HashMap, HashSet, LinkedList/ArrayList etc.

Since this leads to wire level change of data, this is a breaking change and should be moved into HZ 4.0

**Comment by mdogan** [comment]
Related: 
- https://github.com/hazelcast/hazelcast/issues/634
- https://github.com/hazelcast/hazelcast/issues/8791

**Comment by pveentjer** [comment]
Going to close this one since it is a duplicate.
