### ISSUE TITLE
Multi Map put hangs under split brain cluster conditions.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13465]
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-ops/5/console

/disk1/jenkins/workspace/split-ops/3.11-SNAPSHOT/2018_07_17-20_20_56/hangers Failed

http://54.82.84.143/~jenkins/workspace/split-ops/3.11-SNAPSHOT/2018_07_17-20_20_56/hangers

```
find . -name out.txt | xargs grep 'at hzcmd'
./output/HZ/HzMember3HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzClient5HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzClient3HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzClient2HZAA/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzMember2HZAA/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzMember5HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzMember4HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzClient1HZAA/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzClient4HZBB/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
./output/HZ/HzMember1HZAA/out.txt:	at hzcmd.multimap.Put.timeStep(Put.java:9)
```

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hzcmd/multimap/Put.java#L9

**Comment by Danny-Hazelcast** [comment]
the test.

https://github.com/hazelcast/hzCmd-bench/tree/zeta/lab/hz/split/hangers

https://github.com/hazelcast/hzCmd-bench/blob/zeta/lab/hz/split/hangers/go

operations performed during the split heal

https://github.com/hazelcast/hzCmd-bench/blob/zeta/lab/hz/split/hangers/ops

**Comment by Danny-Hazelcast** [comment]
only  hzcmd.multimap.Put.timeStep is hanging all other operations come to a stop.

**Comment by Danny-Hazelcast** [comment]
I did note the same hang in multi map put,  as a secondary problem in
issue https://github.com/hazelcast/hazelcast/issues/12197, in a different test 

however in this test, the issue is happening on every run.

**Comment by Danny-Hazelcast** [comment]
```
"pool-2-thread-1" prio=10 tid=0x00007f1d84005000 nid=0xd86 waiting on condition [0x00007f1d373b2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.multimap.impl.MultiMapProxySupport.invoke(MultiMapProxySupport.java:266)
	at com.hazelcast.multimap.impl.MultiMapProxySupport.putInternal(MultiMapProxySupport.java:69)
	at com.hazelcast.multimap.impl.ObjectMultiMapProxy.put(ObjectMultiMapProxy.java:110)
	at hzcmd.multimap.Put.timeStep(Put.java:9)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Danny-Hazelcast** [comment]
I have updated the test 
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-ops/29/console

we see that. the test allways fails at 
https://github.com/hazelcast/hzCmd-bench/blob/ttlMax/lab/hz/split/hangers/go#L50

on every run, multimap put operation only hang at network heal / cluster merge.

**Comment by Danny-Hazelcast** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-ops/31/console

has 60 stack trace collect 1 every 2 seconds while put ops and merging and hanging is happening.

and diagnostics

**Comment by vbekiaris** [comment]
[Job run #32 (w/ `DEBUG` logging)](https://hazelcast-l337.ci.cloudbees.com/view/split/job/split-ops/32/console)

From job console:
```
15:26:38 AA_merged Done
15:26:48 untilClusterSafe Done
15:26:50 HzMember3HZBB .* stopping 
15:26:50 HzClient1HZAA .* stopping 
15:26:50 HzMember4HZBB .* stopping 
15:26:50 HzMember2HZAA .* stopping 
15:26:50 HzClient2HZAA .* stopping 
15:26:50 HzClient4HZBB .* stopping 
15:26:50 HzClient5HZBB .* stopping 
15:26:50 HzMember1HZAA .* stopping 
15:26:50 HzClient3HZBB .* stopping 
15:26:50 HzMember5HZBB .* stopping 
15:30:57 /disk1/jenkins/hzCmd/bin/hz: line 6: 32699 Killed                  java -cp "${HZ_CMD_BIN}/*:${HZ_CMD_BIN}/dependency/*:${HZ_CMD_SRC}/stash/local/" ${ops} main.HzCmd $@
15:30:58 hz-root/HzClient1HZAA/timeout
...
```
(Jenkins console time is local UTC+3, member logs are UTC)

At 15:30:58 all pending invocations reported in diagnostics logs are targeted to `10.0.0.133` (-> `Member2AA`) with `duration` >= 240000ms. This means that the `Multimap.put` calls are waiting for more than 4 minutes for completion. Operation heartbeats are received on time, so there is no operation heartbeat timeout. Every 60sec a new `callId` is assigned to the `PutOperation` implying a retry. Still `invokeCount` is always 1 (not really sure about the semantics of `Invocation.invokeCount`). Thread dumps on `Member2AA` taken every 2-3 seconds during the hanging period show no trace of `PutOperation` being executed.

As a result [`sleep 240 && if ps -p ${PID} > ...`](https://github.com/hazelcast/hzCmd-bench/blob/ttlMax/lab/hz/split/hangers/go#L65) timed out waiting for the `MultiMap.put` test to finish for 4 minutes and the test failed.

[pending invocations at end of test.txt](https://github.com/hazelcast/hazelcast/files/2393374/pending.invocations.at.end.of.test.txt)

Sample of invocation evolution during the test: invocation with `identityHash=257551225` was first listed as a pending invocation at 18-09-2018 12:27:01 and was still listed as a pending invocation until the test was killed
[invocation evolution.txt](https://github.com/hazelcast/hazelcast/files/2393416/invocation.evolution.txt)

**Comment by vbekiaris** [comment]
- on creation a `MultiMap`’s record store gets a `LockStore` proxy. This `LockStoreProxy` is a proxy for an actual `LockStoreImpl`
- upon merge, all services are reset -> the internal `LockStoreImpl`’s are cleared in `MultiMapService.reset()`
- any subsequent operation checking `canAcquireLock` on the `LockStoreProxy` will get a `false` because `lockStore` is `null` here https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockStoreProxy.java#L107 .
