### ISSUE TITLE
Unable to start spring hazelcast application! Critical!

### ISSUE THREAD

**Issue by prem2204** [hazelcast/hazelcast#13475]
Hi, I found the below issue being reported by multiple people online and tried out every change suggested but to no avail. I tried changing **_xsi:schemaLocation_** to http and https, still the issue persists. Could you please help?
I keep getting either of the 2 issues below:
1. ```Exception in thread "main" ....nested exception is org.xml.sax.SAXParseException; systemId: http://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'..........```

2. ```nested exception is org.xml.sax.SAXParseException; lineNumber: 12; columnNumber: 33; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'.```

**Comment by prem2204** [comment]
An excerpt from the applicationContext.xml (tried with v3.10): 
_<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:hz="http://www.hazelcast.com/schema/spring"
xsi:schemaLocation="http://www.springframework.org/schema/beans 
http://www.springframework.org/schema/beans/spring-beans-3.0.xsd 
https://hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.10.xsd">
    <hz:hazelcast id="instance">
        <hz:config>....._

**Comment by prem2204** [comment]
_<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:hz="http://www.hazelcast.com/schema/spring"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
 
http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
 
https://hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.10.xsd">
    <hz:hazelcast id="instance">
        <hz:config>_

**Comment by neilstevenson** [comment]
Looks like an error on your XML

    https://hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.10.xsd">

Should be

    http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.10.xsd">

Try using lines 1-9 from here https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-configuration/src/main/resources/applicationContext.xml

**Comment by neilstevenson** [comment]
@prem2204  I'm going to close as I don't think this is a Hazelcast issue. Feel free to reopen if you disagree.
