### ISSUE TITLE
HZ cluster loses data when one box turned off

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#13553]
I got a cluster with 54 nodes deployed on 9 physical boxes. After cache population I got 480K entries in cache with 1 backup. Then I turner off one box, so all 6 nodes from that box were shut down. After cache rebalancing I see 475013 entries in cache. My expectation was that lost data will be restored from backups, but the 5K entries were lost completely.

**Comment by mdogan** [comment]
Can you make clear that how you turned off the box? Unplugged the power cable or shutdown/halt via OS command?

Hazelcast backups are lazy replications so even when cache populated completely, it's not guaranteed that they are replicated to backup nodes. See http://docs.hazelcast.org/docs/3.10.4/manual/html-single/index.html#hazelcast-s-replication-algorithm for more details.

Can you also try shutting down those 6 nodes from that box using `hazelcastInstance.shutdown()` explicitly before turning off the machine? This is just to make sure it's related to lazy replication and graceful shutdown works correctly.

Or alternatively you can ensure that `PartitionServie.isClusterSafe()` returns true before turning off the machine.

**Comment by dsukhoroslov** [comment]
I kill 6 nodes via OS command. Ok, I’ll double check backup size, but I believe it was correct because I shutdown nodes after 1 or 2 hours after cache population. 
Can it be that some backups were created on the same box (but in the other nodes) with data owner nodes?

**Comment by mdogan** [comment]
Ah silly me. Of course backups can be created on the same box. 
You can use `HOST_AWARE` partition grouping to ensure backups on different hosts. 

See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/PartitionGroupConfig.java
http://docs.hazelcast.org/docs/3.10.4/manual/html-single/index.html#partition-group-configuration

**Comment by dsukhoroslov** [comment]
Thank you @mdogan , just tested with HOST_AWARE partition grouping, now it works. Closing issue.
