### ISSUE TITLE
Member OOME hprof, put max idle

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#13616]
while running test on put max idle, I have hit a member size hprof
http://54.82.84.143/~jenkins/workspace/stable-x3/3.11-SNAPSHOT/2018_08_21-22_43_48/max-idle/gc.html
2 member hit the OOME
http://54.82.84.143/~jenkins/workspace/stable-x3/3.11-SNAPSHOT/2018_08_21-22_43_48/max-idle/output/HZ/HzMember2HZ/
and
http://54.82.84.143/~jenkins/workspace/stable-x3/3.11-SNAPSHOT/2018_08_21-22_43_48/max-idle/output/HZ/HzMember3HZ/
heap size was 2GB.
and the operations done was
http://54.82.84.143/~jenkins/workspace/stable-x3/3.11-SNAPSHOT/2018_08_21-22_43_48/max-idle/put

i am making 8000 put max idle operation per second, 
with a max idle of 1 second for each put operation.

each put is key int, value 1 byte.

however interestingly i have other long running test's where I Put with a max idle wail until expiry get the key and assert it is null.
so they key/val's do seam to be expiring as expected.

**Comment by tkountis** [comment]
I looked into the HPROF, and here is my observations

- I can see loads of Map Records in different partitions
- I inspected around 2K Records, and they all have correctly an expiration time of 1sec
- The expiration task is running, and as a matter of fact, that thread is the one who got the OOME during iteration and adding an expired entry to the batch
- The expiration task is runs in intervals of 5 seconds, and cleans-up 10% of the records.

Given the above, 8K / Puts / sec isn't sustainable.
I might be missing sth from the picture, but we can try a couple of things. for starter, i would say to make the clean-up process more aggressive, eg.
`hazelcast.internal.cache.expiration.cleanup.percentage = 100` and `hazelcast.internal.cache.expiration.task.period.seconds= 1` and re-run your test, af the very least we should see an improvement.

**Comment by Danny-Hazelcast** [comment]
ok so that explains the oome hprof,  I have passing long run's a much slower put rates.
so I am happy to close the issue.

are the properties   
```
hazelcast.internal.cache.expiration.task.period.seconds
hazelcast.internal.cache.expiration.cleanup.percentage
```

just for JCache as the name suggests  or for IMap also.

**Comment by tkountis** [comment]
Closing the issue then. Thanks Danny.
The properties are for JCache, IMap have the respective ones with `map` in-place of `cache` in the name.
