### ISSUE TITLE
Map Loader doesnt load after map is cleared

### ISSUE THREAD

**Issue by Pankaj227Sharma** [hazelcast/hazelcast#13637]
Hi All,

I am using Hazelcast 3.9.4. I have a scenario where i need to clear out the cache after certain period of time. I am achieving this using setTimetoLiveSeconds(100) method. And its working fine. 

I used MapLoader to load the data initially but after 100 Seconds the maploader is not loading the data.
I need the MapLoader to execute the loadAll() to get the data added in map again. 
Is there any configuration or any way to achieve this.

Thanks in advance.

**Comment by ahmetmircik** [comment]
Hi @Pankaj227Sharma, `IMap#loadAll` can reload data, did you try it?

**Comment by Pankaj227Sharma** [comment]
@ahmetmircik  Yes it worked.. Thanks for your quick response.
