### ISSUE TITLE
Map ldapFieldsMap is still loading data from external store

### ISSUE THREAD

**Issue by Pankaj227Sharma** [hazelcast/hazelcast#13671]
Hi All, 

I am using Hazelcast 3.9 and while i am trying to load the data using MapLoader. Due to large number of data its taking bit time to load into the Map and in logs i am seeing Map ldapFieldsMap is still loading data from external store. Is there any ways i can fix this or i will have to ignore this message and let it finish,

Please suggest.

**Comment by mmedenjak** [comment]
Hi @Pankaj227Sharma !

Currently you can configure the behaviour of the initial load using the `InitialLoadMode` : http://docs.hazelcast.org/docs/3.10.4/manual/html-single/index.html#initializing-map-on-startup.

You can also try returning an empty iterable from `com.hazelcast.core.MapLoader#loadAllKeys`. That way, there will not be any entries loaded on startup but they can be loaded lazily as you access each. It means the hazelcast map will be empty and populated as you call `IMap.get` for each key.

Other than that, we are working on offloading the map store operations. This will be available in a future hazelcast release and will allow you to perform map loading asynchronously in the background.

Closing this as I believe this is not an issue. If you have further questions, please contact us on [our gitter channel](https://gitter.im/hazelcast/hazelcast) or [google groups](https://groups.google.com/forum/#!forum/hazelcast).
If you encounter some other problem, please open a new github issue.
