### ISSUE TITLE
No-more write lock on partition migration

### ISSUE THREAD

**Issue by bothapn** [hazelcast/hazelcast#13672]
Hi,

Feature request:
Current scenario: When a partition is being migrated , writes to caches on the partition is being blocked.
Ideas:
1:
- force the specified amount of partitions to be created and split data accordingly and move only 1 partition at a time
2:
- when a write is requested to a cache which as a partition that is being migrated, only block the write if it is an update to a key that resides on that partition, OR write a new key record to another partition that is not being migrated and then delete the previous key on the migrated partition once it is migrated.
-- when a write is requested to a cache which as a partition that is being migrated, attempt to rather write to a different partition that is not being migrated.

Thanks!

**Comment by metanet** [comment]
Hi @bothapn 

We already do your first suggestion. After a topological change, only 1 partition is migrated at a time. So only the operations that hit to the migrating partition are blocked. 

For your second suggestion, what is your thinking behind blocking an update, but offloading an insert to another partition? To me, both cases look the same. In Hazelcast, mapping between keys and partitions are deterministic. For a given key, Hazelcast always hits the same partition. Moreover, partition migration already involves a huge amount of complexity. So such changes are not very easy. 

If you give more details about your use case, maybe we can discuss other solutions for you.

Regards,

**Comment by bothapn** [comment]
Hi **@metanet**,

Unfortunately I didn't know that keys to partitions are deterministic. I was assuming it would be something along the lines of a best effort load-balanced strategy. The complexity of the idea might not make it feasible.
The idea was that the system differentiates between inserts (new record) and updates(existing record) and could then act on that based on partition availability.
 
Regards,
