### ISSUE TITLE
PagingPredicate's (Predicate predicate, int pageSize)  constructor is non-generic 

### ISSUE THREAD

**Issue by jeppec** [hazelcast/hazelcast#13779]
The `public PagingPredicate(Predicate predicate, int pageSize)` constructor is non generic as opposed to the the other constructors.

```java
public class PagingPredicate<K, V> implements IndexAwarePredicate<K, V>, IdentifiedDataSerializable {

    public PagingPredicate(Predicate predicate, int pageSize) {
        this(pageSize);
        setInnerPredicate(predicate);
    }
```

**Comment by mmedenjak** [comment]
Fixed with https://github.com/hazelcast/hazelcast/pull/15142. Since Hazelcast 4.0, you can now use `Predicates#pagingPredicate(com.hazelcast.query.Predicate, int)`.
