### ISSUE TITLE
Accidental leak of the min. json dependency

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#13883]
there is an accidental leak of the min. json dependency in the hazelcast-all artefact.
compare:
https://mvnrepository.com/artifact/com.hazelcast/hazelcast-all/3.10.4 <-- compile time dependency
https://mvnrepository.com/artifact/com.hazelcast/hazelcast/3.10.4 <-- no dependency
https://mvnrepository.com/artifact/com.hazelcast/hazelcast-all/3.9.3 <-- no dependency
https://mvnrepository.com/artifact/com.hazelcast/hazelcast-all/3.9.3 <-- compile time dependency

**Comment by kwart** [comment]
This issue duplicates #11524. Let's use it to resolve the issue in the maintenance branch.

**Comment by mmedenjak** [comment]
Closing as fixed by https://github.com/hazelcast/hazelcast/pull/13885
