### ISSUE TITLE
XML for FlakeId

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#13951]
Flake ID Generator can only be configured in Java

In 3.10 XSD, there's no section for `hazelcast` or `hazelcast-client`.

**Comment by neilstevenson** [comment]
It's missing from
https://hazelcast.com/schema/client-config/hazelcast-client-config-3.10.xsd
and
https://hazelcast.com/schema/config/hazelcast-config-3.10.xsd

**Comment by mmedenjak** [comment]
Closing as the root cause has been identified as another issue.
