### ISSUE TITLE
Error 400: Not able to open /hazelcast/health URL

### ISSUE THREAD

**Issue by anurag2305** [hazelcast/hazelcast#13954]
Hi

Is http://<my_host_ip>:5702/hazelcast/health works with hazelcast version 3.7?

I have enabled REST services and also the health check flag to true in the configuration but while accessing the above url I am getting 400 error. Same output on browser as well
**-Dhazelcast.rest.enabled=true -Dhazelcast.http.healthcheck.enabled=true**

curl -IX GET -H "Content-type: application/json" http://<my_host_ip>:5702/hazelcast/health

**HTTP/1.1 400 Bad Request
Content-Length: 0**

Message in the logs after hitting the above URL

06:33:57.937 [hz._hzInstance_1_default.IO.thread-Acceptor] INFO c.h.n.t.SocketAcceptorThread - [10.150.187.9]:5702 [default] [3.7.4] Accepting socket connection from /146.213.0.134:33656
06:33:57.938 [hz._hzInstance_1_default.cached.thread-3] INFO c.h.n.t.TcpIpConnectionManager - [10.150.187.9]:5702 [default] [3.7.4] Established socket connection between /<my_host_IP>:5702 and /146.213.0.134:33656

**Comment by vbekiaris** [comment]
@anurag2305 the health check URL was added in Hazelcast 3.8 via #9284, so it's not available in Hazelcast 3.7. You are welcome to ask any further questions at the [Hazelcast google group](https://groups.google.com/forum/#!forum/hazelcast). Cheers!

**Comment by anurag2305** [comment]
@vbekiaris : Thank a lot for your inputs. Clarified the doubt now regarding version.
