### ISSUE TITLE
Hazelcast is slow when put data to distributedmap

### ISSUE THREAD

**Issue by khanhlv93** [hazelcast/hazelcast#14008]
I have two hazelcast nodes (16GB RAM, 4 core per node), one distributed map with async-backups, near cache,  data-serializable,key string[25chars] value is object (string[25 chars], string [25 char]) .when i tried put to distributed map in one embed instance ,hazelcast was very slow (1904 puts/s) but if i shutdown another node, performance is increase (30000 puts/s). Anyone can help me turning performance in multi nodes ?. Thank you

  <map name="msisdn">

        <in-memory-format>OBJECT</in-memory-format>

        <backup-count>0</backup-count>

        <async-backup-count>1</async-backup-count>
        
        <time-to-live-seconds>864000</time-to-live-seconds>
        
        <max-idle-seconds>864000</max-idle-seconds>
        
        <eviction-policy>LRU</eviction-policy>
     
        <near-cache>
            <max-size>0</max-size>
            <time-to-live-seconds>864000</time-to-live-seconds>
            <max-idle-seconds>864000</max-idle-seconds>
            <eviction-policy>LRU</eviction-policy>
            <invalidate-on-change>true</invalidate-on-change>
            <in-memory-format>BINARY</in-memory-format>
            <cache-local-entries>false</cache-local-entries>
            <eviction size="1000" max-size-policy="ENTRY_COUNT" eviction-policy="LFU"/>
        </near-cache>
    </map>

**Comment by pveentjer** [comment]
The reason why performance is so high with a single node is that there is no backup and no networking. So a single node is always very fast.

If you want do faster bulk insert please have a look at the IMap.putAll method

Also you have underprovisioned your machine. We recommend at least 8 cores.

**Comment by khanhlv93** [comment]
can i use putall without call mapstore ?.
