### ISSUE TITLE
hazelcast(3.11) is using 20% of cpu usage in linux machine (application is idle state, embedded mode with out cluster or standalone ) 

### ISSUE THREAD

**Issue by gkishorerao123** [hazelcast/hazelcast#14059]
Hazelcast (3.11) is using 20% of cpu usage in linux machine (application is idle state, embedded mode with out cluster or standalone ).
We are using hazelcast in standalone mode.  We are having total five caches.

```java

@Bean
    public Config standaloneConf() {
      

        final Config config = new Config();
        final JoinConfig join = config
                .getNetworkConfig()
                .getJoin();
        standalone(join);


        return config;
    }

    private static void standalone(JoinConfig join) {
        join
                .getMulticastConfig()
                .setEnabled(false);
        join
                .getTcpIpConfig()
                .setEnabled(false);
    }
```

do we need to use any other configurations?

**Comment by mmedenjak** [comment]
Hi @gkishorerao123 !

The configuration heavily depends on the needs of your application. Please take a look at the reference manual - https://docs.hazelcast.org/docs/latest/manual/html-single.

Closing this issue as there is nothing that we can do from our side. Please open a new issue if you encounter other problems.

**Comment by mmedenjak** [comment]
Reopening as you mention issues with CPU usage. Please profile your application so we can determine where CPU time is being spent.
