### ISSUE TITLE
HazelcastClient xsd defines `enabled` for discovery-strategy but not used in the config object

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#14069]
There is also `DiscoveryStrategyFactory` in `DiscoveryStrategyConfig` but it is not used besides testing.

**Comment by sancar** [comment]
There is no enabled boolean on the `DiscoveryStrategyConfig `, but when a discovery config is not enabled on the xsd, it looks like we don't add it to config list of discovery-strategies. So effectively, it seems correct to me. 
See:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/config/impl/ClientDomConfigProcessor.java#L531:L543

And `DiscoveryStrategyFactory` used here
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java#L178

@gurbuzali Am i missing something ? Can we close this issue ?

**Comment by gurbuzali** [comment]
I guess I've stumbled upon this issue when implementing jet-spring-boot-starter but looks like the `enabled` attribute works as intended although not in line the rest of the config options. 

I don't remember why I thought that `DiscoveryStrategyFactory` is not used at all, maybe a mistake on the IDE

I think we can close it
