### ISSUE TITLE
Add "/ready" endpoint to health check

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast#14089]
The `/ready` endpoint should return HTTP_OK if a member already joined (or formed) a cluster. So, the user can safely use that member. It would be helpful in the following scenarios:
- in Kubernetes service: not to send any traffic to unready member
- in Kubernetes Rolling Upgrade - to restart member and wait until it joins to cluster, before the next member is terminated

Such an approach will improve K8 user experience and will guarantee that the cluster will not reduce its size significantly during rolling upgrade.

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/14152
