### ISSUE TITLE
Question: Group Password

### ISSUE THREAD

**Issue by JuKu** [hazelcast/hazelcast#14082]
Why was the group password removed?
And how can i secure my hazelcast cluster now? Is there a new type of authentification / cluster password?

**Comment by JuKu** [comment]
@mmedenjak Thanks!
But how can i set this `hazelcast.application.validation.token` at runtime?

**Comment by mmedenjak** [comment]
Sorry for the late reply. Setting it in programmatic or declarative config is the only supported scenario at the moment. You can try setting it once the cluster is running (by getting the configuration via `HazelcastInstance#getConfig` and setting the property with `Config#setProperty`) but we are not supporting it.
