### ISSUE TITLE
Current thread is not owner of the lock Exception Version 3.8.3

### ISSUE THREAD

**Issue by hashmiusama** [hazelcast/hazelcast#14083]
We are facing issue related to locking. An exception gets thrown 
`java.lang.IllegalMonitorStateException: Current thread is not owner of the lock! -> <not-locked>`

The exception is thrown at the lock.unlock() line in the following code

```
  if (lock.isLockedByCurrentThread()) {
            lock.unlock();
        } else if (lock.isLocked()) {
            lock.forceUnlock();
        }
```

The lock.lock method is a couple of lines above it and not throwing any error.

The locking mechanisms look messed up. Are there other ways of avoiding concurrent modification (Semaphores do not work for us,)?

**Comment by cforce** [comment]
related to
https://github.com/hazelcast/hazelcast/issues/14083
https://github.com/hazelcast/hazelcast/issues/11617
https://github.com/hazelcast/hazelcast/issues/13699

**Comment by mmedenjak** [comment]
Hi @hashmiusama !

It might have happened that between the invocation of `lock.isLockedByCurrentThread()` and `lock.unlock()` there was some issue in the cluster and the lock information was unavailable or lost. The logs should help identify the issue but I assume that you don't have the logs after such a long time or are not using the same code anymore.

I'm pleased to tell you that with Hazelcast 4.0, we have replaced the entire implementation of ILock with the unsafe mode of CP subsystem (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). If you don't require strong consistency guarantees, that mode might fit your use case and solve the issue. If you do require strong consistency guarantees, you definitely might want to try out using the CP subsystem by turning off unsafe mode and running the appropriate number of members. Please try it out.

Closing this issue as the old lock implementation is no longer maintained.
