### ISSUE TITLE
Not all of the resources are cleared when destroying DurableExecutorService

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#14087]
When destroying a `DurableExecutorService`, the `DurableExecutorPartitionContainer` instances are not cleared. This makes some of the resources such as `TaskRingBuffer` still left in the heap even the service itself is destroyed.

**Comment by yilmazorhan** [comment]
Hello,
Do you have a workaround for this issue?
Thanks

**Comment by mmedenjak** [comment]
Hi @yilmazorhan ! The fix was just created in time for 3.12. We'll try and merge it.

**Comment by yilmazorhan** [comment]
Thanks
