### ISSUE TITLE
mapEvictionPolicy is not configured via giving class name of custom eviction policy at PCF

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#14092]
I was trying to reproduce/fix https://github.com/hazelcast/hazelcast/issues/14086, realized that `mapEvictionPolicy` is not configurable from JSON file. Creating instance from the configured class is executed by XMLConfigBuilder so we need similar logic for JSON config:

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java#L1435

**Comment by mmedenjak** [comment]
Should be covered by https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1190035695/YAML+Configuration+Support.

**Comment by mmedenjak** [comment]
@blazember @hasancelik  can this issue be closed, given that YAML support is merged?

**Comment by blazember** [comment]
I think this issue can be closed, the test covering `evictionPolicy` is passing: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java#L1092-L1113
