### ISSUE TITLE
[Hazelcast Mancenter] LDAP group search with scope 'subtree'

### ISSUE THREAD

**Issue by vcariven** [hazelcast/hazelcast#14118]
Hazelcast Management Center  LDAP authenticator does not make a LDAP `subtree`search for groups. 

As group search is **mandatory** for role mapping, having an existing deep group hierarchy prevents from using ldap authenticator with mapping with existing groups.

LDAP group search scope could be configurable from `ldap.properties` file, e.g. by adding a property flag in `ldap.properties` : 
```
# default value : false
groupSearchSubtree=true
```

Regards

**Comment by burakcelebi** [comment]
@vcariven Thanks for your request! @jgardiner68 could provide more information about this.

**Comment by emre-aydin** [comment]
Management Center will do a search with subtree scope by default, starting with version 3.12.
