### ISSUE TITLE
Distribuited computing on star topology cluster 

### ISSUE THREAD

**Issue by Fabryprog** [hazelcast/hazelcast#14125]
Hello eveyone

I would use hazelcast to delegate and execute tasks into a cluster (distribuited computing)

Network topology is a star (1 dispatcher N workers). Note: workers aren't in the same network!!!

How to config hazelcast for my purpose?

Actually I am using:
 - Dispatcher
   - public address 
   - tcp enabled
 - Workers
   - setRequireMember()
   - tcp enabled

Using this configuration I have some errors because the workers would connect them without success!

**Comment by Fabryprog** [comment]
+1

**Comment by mmedenjak** [comment]
Hi @Fabryprog !

Have you looked at the API for the `HazelcastInstance#getScheduledExecutorService` and the `HazelcastInstance#getDurableExecutorService`? Using these, you can delegate and execute tasks in a cluster.
I suggest you run hazelcast members as single-node workers (or a cluster of workers) and create separate hazelcast client instances in your dispatcher to connect to each worker in your application. Each client can only connect to a single worker so you will have to create as many clients as there are workers.
Using a client, you can then delegate/dispatch running a task to a certain worker. But you will have to implement the load balancing/dispatch logic. As I mentioned, please take a look at the above mentioned API.

For any other questions, please use [gitter chat](https://gitter.im/hazelcast/hazelcast) or the [Hazelcast google group](https://groups.google.com/forum/#!forum/hazelcast) for questions. Please create github issues for reporting suspected bugs and feature requests.
