### ISSUE TITLE
Hazelcast version update in AWS

### ISSUE THREAD

**Issue by mpgallage** [hazelcast/hazelcast#14124]
Hi All,

I'm trying to upgrade hazelcast from 3.7.2 to 3.11. We have deployed all our servers and clients on AWS.
Obviously we have to use new AWS Discovery SPI with the new version. But we have some risks upgrading the hazelcast clients at the moments due to some internal reasons.

Is there anyway I can support older clients with the new server version which uses Discovery SPI?

Thanks

**Comment by dbrimley** [comment]
@mesutcelik Have you any ideas about this question from @mpgallage.

Is it possible to use 3.7.2 clients connecting to a 3.11 cluster?

So I'm guessing the clients will use the old AWS discovery and cluster will use new AWS Discovery SPI?

**Comment by mesutcelik** [comment]
I don't think that would be an issue because old and new discovery are not really about features but implementation details. As hazelcast client 3.7.x supports newer server versions, I think it should be ok.

**Comment by dbrimley** [comment]
@mpgallage Hi, with the answer above, did you manage to run this yourself in the 3.7.2 client configuration?

**Comment by dbrimley** [comment]
I'm closing this ticket due to inactivity.  @mpgallage if you do have any feedback please do let us know.
