### ISSUE TITLE
All DataStructures with name should extend NamedConfig 

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#14144]
In pr https://github.com/hazelcast/hazelcast/pull/14014, all suitable data structures implements NamedConfig. 
`ClientReliableTopicConfig` and `FlakeIdGeneratorConfig` can not implement the interface because return type of setName is not compatible. 

`EventJournalConfig` also can not implement it because it has two different method for it, `setMapName` and `setCacheName`. This can also be cleaned up. 

This can be cleaned-up in 4.0.

**Comment by mmedenjak** [comment]
Event journal and merkle tree config are no longer top-level configs and are now part of map and cache config:
https://github.com/hazelcast/hazelcast/pull/15185
https://github.com/hazelcast/hazelcast/pull/15180
