### ISSUE TITLE
FlakeIdGenerator advanced configuration

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast#14150]
Hello Hazelcast team,
is it possible to externalize `FlakeIdGeneratorProxy` constants, namely `EPOCH_START, BITS_TIMESTAMP, BITS_SEQUENCE, BITS_NODE_ID, ALLOWED_FUTURE_MILLIS` into `FlakeIdGeneratorConfig`?
This would allow as to generate wider range of IDs for different use cases, such as those which rotate once per day, week, month, in exchange for shorter generated bit length.

With regards
Lukas Herman

**Comment by lukasherman** [comment]
The tricky part is to correctly handle possible id overflow. The current implementation simply grows without any bounds.

**Comment by mmedenjak** [comment]
Hi @lukasherman ! Yes, it's possible but currently it's not high-priority. We'll consider it.

**Comment by lukasherman** [comment]
@mmedenjak are you interested in PR for that?

**Comment by mmedenjak** [comment]
@lukasherman yes, sure. Keep in mind that the master branch is now targeting Hazelcast 4.0 while the maintenance-3.x branch are patch releases for 3.12. Although it might be possible to introduce some smaller enhancements in patch releases, generally we refrain from it as we have various compatibility restraints (e.g. no serialization changes).
What I'm saying is - it will be easier for you to create it against master but that means it will come out in Hazelcast 4.0.

**Comment by lukasherman** [comment]
OK, no problem. I have implemented the changes as a separate service into 3.1x. The code might need some review though. What is the schedule for 4.0? I need some planning first.

**Comment by mmedenjak** [comment]
Roughly, this fall.

**Comment by lukasherman** [comment]
We are analyzing FlakeIdGenerator nodeId overflow behavior and would like to get your opinion whether the following code:
https://github.com/hazelcast/hazelcast/blob/9e65699058f5cd22289bf9ab654fca283bd44016/hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java#L222
could be replaced by `getMemberIndex()`:
```
 private int getMemberIndex(){
        int index = 0;
        Iterator<Member> memberIterator = getNodeEngine().getClusterService().getMembers().iterator();
        while (memberIterator.hasNext()){
            index++;
            if(memberIterator.next().localMember()){
                break;
            }
        }
        return index;
    }
```
It is not clear whether member index invariant applies to this use case.

Thanks and regards
Lukas
