### ISSUE TITLE
Enable insecure health check if SSL Mutual Authentication is REQUIRED

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast#14156]
When SSL is enabled and `mutualAuthentication` is set to `REQUIRED`, then all connecting clients need to have valid certificates. That is an issue in case of HTTP/HTTPS connection done by `readinessProbe` and `livenessProbe` on Kubernetes, like [here](https://github.com/hazelcast/charts/blob/master/stable/hazelcast-enterprise/templates/statefulset.yaml#L47).

A solution is to allow HTTPS (or even HTTP) connections to `/health` endpoints even when SSL is enabled (and SSL Mutual Authentication is REQUIRED). We can either allow it in REQUIRED or create a new `mutualAuthentication` mode for that purpose (like it's [done in the Istio tool](https://istio.io/help/faq/security/#k8s-health-checks)).

We can consider even skipping all the security checks in case of health checks (for example, Socket Interceptors, etc.)

**Comment by kwart** [comment]
This could/should be resolved by ongoing work related to WAN improvements and separating public/private IP
- see https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1217888911
Once we separate sockets for our protocols each of them can have different TLS configuration.
Please coordinate with GDT (Greek Dream Team: @vbekiaris and @tkountis) on this topic.

If we would want to use existing approach with a single port for all protocols, we would need to implement opportunistic TLS approach as described in https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1204027685

**Comment by mmedenjak** [comment]
Since we don't allow different protocols on the same port and we don't have opportunistic TLS implemented, this may be solved by having different sockets with different TLS configurations. I propose to close or move this issue to a further release if we can further improve on this. @vbekiaris and @tkountis can comment on the approach.

**Comment by tkountis** [comment]
Currently in 3.12 we allow different ports per service (i.e., Member, Client, REST)
REST is still treated as a single service, however, the infrastructure is there to allow us to split this even further and allow more than 1 REST interface, each with different REST-GROUPS and different TLS configurations. I suppose we can even do that in a minor release.

**Comment by mmedenjak** [comment]
Then I suggest the approach would be having TLS enabled for member and insecure config for REST + possibly rest group config only to allow health checking.
We can create a PRD to allow multiple configurations for the same service (REST).

@leszko can you try setting up the above-mentioned config with TLS and non-TLS and seeing if it works for you?

**Comment by leszko** [comment]
If I understand correctly, you mean that now we can set up for example:
- TLS, port 5701 for Member-Member and Member-Client communication
- non-TLS, 5702 for the REST communication

Am I correct? @tkountis , could you point me to the doc with the description of how to set it up?

Such configuration would be fine for my scenario. We could have non-TLS enabled REST enabled, but not expose this port outside the infrastructure, which would guarantee the security. Spiting the REST endpoints to some groups would be even better, but I agree that we can create a PRD for it and release it in some of the further Hazelcast versions.

So, the plan:
1. @mmedenjak @tkountis Please point me to the doc how to set up a different port for REST
2. I'll check it
3. We create a PRD 
4. We close this ticket

**Comment by mmedenjak** [comment]
I don't know which documentation or sample would be best, I'll leave that to @tkountis and @vbekiaris :)

**Comment by leszko** [comment]
Ok, I checked and it works fine. Thanks @vbekiaris for the help and the code sample! 👍 

So the last case that is not covered is super niche: If a user would like to use Hazelcast REST on kubernetes, but at the same time she would like to have the SSL Mutual Auth enabled. I'm not sure we even support SSL Mutual Authentication for the REST endpoints, do we? @mmedenjak @vbekiaris 

If yes, then I'd create a PRD and close this ticket. If no, then just close this ticket.

**Comment by mmedenjak** [comment]
Not sure myself, I'll let @vbekiaris or @kwart answer this one :)

**Comment by tkountis** [comment]
@leszko I am not sure I followed the question, but here is my answer.

All types of endpoints (REST, MEMBER, CLIENT) support all types of socket configurations, eg. TLS, with or without mutual auth and what not. All indepented from each other. Its a matter of the client connecting to that endpoint, if he can deal with the specific configuration.

I hope this answers your question?

**Comment by leszko** [comment]
Yeah, then let's create a PRD to split Health and Rest into separate groups. I guess the priority of such PRD will be super lower, because the scenario is super niche.

**Comment by tkountis** [comment]
Closing this one then. :+1:
