### ISSUE TITLE
DefaultQueryCache entrySet inefficient result building

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#14177]
Hi,

DefaultQueryCache handles queries to query caches. However, it's performance is degradated because of current flow in case of index aware query:
1. get results from index
2. if not null -> check `isEmpty` (which traverse whole result set!)
3. again ask for `query.size()` - here it's not so bad, because `size` result is cached after point 2
4. again traverse result set and add to final HashSet

This should be much faster: if `query` is not null, `isEmpty` should look only if any element was found; what's more, we can at first construct resultingSet, without isEmpty and size calls, because this eager optimization causes in real life huge performance degradation.

**Comment by ahmetmircik** [comment]
Hi @TomaszGaweda, 
>if not null -> check isEmpty (which traverse whole result set!)

Can you please give reference to this issue? Where does it happen in the code?

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/pull/14229
