### ISSUE TITLE
Hazelcast Map Read -Write mechanism

### ISSUE THREAD

**Issue by veerumallavarapu** [hazelcast/hazelcast#14172]
Hi All

Can you please explain whether do I need to apply any lock before writing the data to Hazelcast map ? In our system , Map is being read by many process while It is being updated by another process.

Any pointers would helpful for me.  I am using hazelcast 3.10.x version.

**Comment by veerumallavarapu** [comment]
Hi mmedenjak

can you explain what is the meaning adding to 3.12 milestone.  That means it will be taken care in future releases of hazelcast??

**Comment by veerumallavarapu** [comment]
Hi All

Can someone respond ???

**Comment by ahmetmircik** [comment]
Hi @veerumallavarapu, 

Unless it is not a bug report or feature request, please use Hazelcast google group. Thanks for understanding this. 

Regarding your question, you can think of Hazelcast IMap as a `java.util.concurrent.ConcurrentHashMap`. If you need lock when using `java.util.concurrent.ConcurrentHashMap`, you will also need a lock for Hazelcast IMap. But for regular `put` and `get` no lock is needed.
