### ISSUE TITLE
MapStore write-delay-seconds at millisecond granularity

### ISSUE THREAD

**Issue by Deepakkoli93** [hazelcast/hazelcast#14176]
This is a proposal for a feature to have write-behind-delay in case of write behind cache at sub-second level. Currently the minimum non zero value to which it can be set is one second. 
Oracle's coherence cache provides it at millisecond level. https://docs.oracle.com/cd/E24290_01/coh.371/e22837/appendix_cacheconfig.htm#COHDG4630

**Comment by burakcelebi** [comment]
@Deepakkoli93 Thanks for your request. AFAIKN, currently, we do not have any plans to support the MS level. 

Dear community, please add your comments with "+1" if you are interested in this enhancement.

**Comment by nfrankel** [comment]
Two years have passed and there's no additional interest for this issue. Can we close it as "Won't fix"?

**Comment by Holmistr** [comment]
Hi @Deepakkoli93 , I would be interested in the reason why you would need less than a second. After analysis, from our perspective, this would be very inefficient and not really usable in the real world.

I'm going to close this issue but please feel free to comment if you still believe it would be useful - with the explanation of your usecase. Thanks a lot!
