### ISSUE TITLE
Warning When one of clusters crashed, and visit is very slow

### ISSUE THREAD

**Issue by qh3001** [hazelcast/hazelcast#14199]
Hi,
I'm doing a Hazelcast test by using two machine. Using the default config, set the map backup count = 1. First, i put the data into the map on one machine, then at the other machine can get all the object in the map; then I close down one of the machine and try to visit the map on the alived machine, the machine will take almost 1 minutes to get the map. And the Warning message is `RetryableIOException packet not sent to ***`. I try to set `hazelcast.backpressure.backoff.timeout.millis = 3000` or `hazelcast.operation.call.timeout.millis = 3000` but no use.  How can I speed up the visit when one of the clusters crashed?
Thx.

**Comment by vbekiaris** [comment]
You are welcome to use [gitter chat](https://gitter.im/hazelcast/hazelcast) or the [Hazelcast google group](https://groups.google.com/forum/#!forum/hazelcast) for questions. Please create github issues for reporting suspected bugs and feature requests. Let's continue the discussion on [gitter](https://gitter.im/hazelcast/hazelcast?at=5c00e77c9aec405095a3dacd).
