### ISSUE TITLE
Start.bat script doesn't work on Windows machines with Russian locale

### ISSUE THREAD

**Issue by ayaz-ashrapov** [hazelcast/hazelcast#14217]
Hello Hazelcast team.
I found an issue with the start.bat batch file.
If the user is trying to run the start.bat file on Windows machine with Russian locale, the script will fail to start a hazelcast instance. This happens because of the following two lines of code in the start.bat file:
`FOR /F "tokens=2 delims=," %%F in ('tasklist /NH /FI "WINDOWTITLE eq hazelcast %CLASSPATH%" /fo csv') DO (
SET PID=%%F
)
IF NOT "%PID%"=="" (
    goto alreadyrunning
)`

In the code above the delimiter is a comma mark, so when we run this code on Windows machine with English locale it will return us the following message: **INFO: No tasks are running which match the specified criteria.** Now, based on the delimiters, the start script will not find any token and will leave PID variable empty and the rest of the script will work fine. But if we try to run tasklist on a Windows machine with Russian locale we get the following output: **Информация: Задачи, отвечающие заданным критериям, отсутствуют**.  The script will apply a comma mark as a delimiter and PID will be set to ' **отвечающие заданным критериям**' value. Since PID is not empty, the script will report an error and fail to start the instance. 
As a workaround, I changed "tokens=2 delims=," to "tokens=2 delims= ," (added space as a second delimiter) and after that, I managed to start the instance.

**Comment by alparslanavci** [comment]
Yes, this issue exists but the PID management will be removed with 4.0 (see: https://github.com/hazelcast/hazelcast/pull/15934) and the issue will be gone. 

@dbrimley WDYT about backporting PID management removal to 3.x?

**Comment by Holmistr** [comment]
@ayaz-ashrapov @alparslanavci Looks like this issue was resolved. Can we close it? :)

**Comment by alparslanavci** [comment]
@Holmistr, yes, it is resolved with 4.0. Closing it now.
