### ISSUE TITLE
3.11 Node could not join cluster. Incompatible group password. Node is going to shutdown now

### ISSUE THREAD

**Issue by kdohz** [hazelcast/hazelcast#14252]
I have 2 HZS members (41 and 43) in a cluster. Both of them run 3.8 version.
When upgrade member-43 to 3.11, member-43 cannot join the cluster.

The following log is seen in member-43
        [10.94.169.43]:5701 [as] [3.11] Node could not join cluster. A Configuration mismatch was detected: Incompatible group password! Node is going to shutdown now!

The following log is seen in member-41
        [10.94.169.41]:5701 [as] [3.8] Received an invalid join request from [10.94.169.43]:5701, cause: Incompatible group password!

Before upgrade, the password for all members in the group are the same and they comply with the password rule (* contain 8 or more characters. * have at least 1 lower and 1 upper case characters. * contain at least 1 number. *contain at least 1 special character.)

I notice that this issue has been raised in the past and some fix was submitted to resolve this (https://github.com/hazelcast/hazelcast/pull/10726). Is it true??
What is the proper procedure to upgrade from 3.8 to 3.11?

Regards,
Kinh

**Comment by vbekiaris** [comment]
@kdohz my understanding is that you are executing a rolling upgrade of your cluster members from 3.8 to 3.11. This is not supported. The short version of rolling upgrade compatibility guarantees is:
- if you are using Hazelcast open source, you can rolling upgrade your cluster members to subsequent `patch` versions, within the same `major.minor` version. For example you can rolling upgrade your cluster members from 3.8.3 to 3.8.5, but not from 3.8.3 to 3.9.1.
- having a Hazelcast enterprise license with the rolling upgrade feature enables you to perform a rolling upgrade to the next minor version, so you can upgrade for example from 3.8.3 to 3.9.1 but you still cannot upgrade directly from 3.8.x to 3.11.y. You have to either restart the cluster or make each next-minor-version rolling upgrade (3.8 to 3.9, then to 3.10 etc) to avoid downtime.

You can read more about compatibility guarantees in the relevant [section in the reference manual](https://docs.hazelcast.org/docs/3.11/manual/html-single/index.html#rolling-member-upgrades).

**Comment by kdohz** [comment]
Hello @vbekiaris 

I have a question that I need confirmation.
Given major.minor.patch (Ex: 3.10.1)
I can go from 3.10.1 to 3.10.9 skipping patch version without downtime.
Or
I can go from 3.10 to 3.11 without downtime
But 
3.10 to 3.12 will cause downtime
Is it true? 

Thanks
Kinh

**Comment by vbekiaris** [comment]
hi @kdohz 

> I can go from 3.10.1 to 3.10.9 skipping patch version without downtime.

correct for both Hazelcast open source and enterprise

>  I can go from 3.10 to 3.11 without downtime

correct only when using Hazelcast enterprise license with the rolling upgrade feature. There is no minor version upgrade compatibility guarantee for Hazelcast open source.

>  3.10 to 3.12 will cause downtime

correct, directly upgrading 2 minor versions is not supported for either Hazelcast open source or enterprise.

**Comment by kdohz** [comment]
Thank you @vbekiaris

**Comment by aruntirath** [comment]
When trying to start hazelcast getting below error-

`Node could not join cluster. Before join check failed node is going to shutdown now!`

Please help to sort out this one.

**Comment by mmedenjak** [comment]
@aruntirath this is not enough information to figure out what is wrong. We'll need to see the full logs of the node starting up and other nodes in the cluster, if there are any.
