### ISSUE TITLE
Unable to have an empty group password

### ISSUE THREAD

**Issue by rickymemphis** [hazelcast/hazelcast#14260]
Hi Hazelcast team,

I have look around a bit on the group password related issues but I have not found a request similar to mine.

I would like to get rid of the log: `INFO: [192.168.99.1]:5701 [dev] [3.11] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.` but it seems not possible.

If I do not set a password a default one will be configured and I can not set an empty one because GroupConfig.setPassword() method is deprecated.

Would it be possible to use an empty string as default password for GroupConfig?
Moreover I think the group password should be removed from the hazelcast-default.xml

Please let me know what you think about my proposal.
Kindly Regards,
Riccardo

**Comment by mmedenjak** [comment]
Hi @rickymemphis !

We will consider this as an enhancement but for now please use any non-empty password as a workaround.

**Comment by nlwillia** [comment]
This is pretty clearly a defect.  One part of the platform should not be defaulting a non-removable value that another part of the platform complains about being populated.  It’s a benign problem, but stuff like this adds friction for everyone upgrading and watching for new issues afterwards.

**Comment by rickymemphis** [comment]
Hi @mmedenjak,

Thank you for taking my request into consideration.

Regards,
Riccardo
