### ISSUE TITLE
Distributed object can be safely used after destroy

### ISSUE THREAD

**Issue by mirkoluchi** [hazelcast/hazelcast#14267]
I expected a DistributedObject on which destroy has been called to be no longer working.
Instead this code perfectly works:
```Java

IQueue<String> q = hz.getQueue("test");
q.destroy();
q.offer("aaa"); 
String v = q.take();
assertEquals("aaa",v);

```
The behaviour I expected was that any API called after the object is destroyed caused a DistributedObjectDestroyedException, but this is not the case. Can you clarify this behaviour please?

**Comment by dbrimley** [comment]
@burakcelebi Could you check with somebody about this?  It seems to me @mirkoluchi assumption should be correct.

**Comment by pveentjer** [comment]
It works as designed.

In Hazelcast there is no difference between a first time access and access after destroy. Once an object is destroyed, all its internal content is removed and if you access it again, it will be recreated as if it was used for the very first time.

**Comment by dbrimley** [comment]
@pveentjer Thanks for the information.  I'll close this ticket.

**Comment by burakcelebi** [comment]
Thanks Peter! 

@mirkoluchi this behavior was also mentioned in the reference manual: 

https://docs.hazelcast.org//docs/3.11.1/manual/html-single/index.html#loading-and-destroying-a-distributed-object

**Comment by burakcelebi** [comment]
@mirkoluchi We have decided to enhance our documentation to clarify the behavior. Please see: https://github.com/hazelcast/hazelcast-reference-manual/issues/643

Thank you for your time to raise this! 👍
