### ISSUE TITLE
com.hazelcast.partition.MigrationEndpoint should be part of the SPI package

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#1427]
com.hazelcast.partition.MigrationEndpoint is part of the SPI, but its method 
```
getMigrationEndpoint()
```
returns
```
com.hazelcast.partition.MigrationEndpoint 
```
which makes a dependency on internal (non-SPI) structures of HZ.

**Comment by pveentjer** [comment]
Fixed. The MigrationEndpoint is now in com.hazelcast.spi.partition.
