### ISSUE TITLE
Lack of group details for cluster version check

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#14276]
Cluster state operation requires group name / password (eg. in `cluster.sh` script)

```
request="http://${ADDRESS}:${PORT}/hazelcast/rest/management/cluster/state"
response=$(curl --data "${GROUPNAME}&${PASSWORD}" --silent "${request}");
```

Cluster version operation does not

```
request="http://${ADDRESS}:${PORT}/hazelcast/rest/management/cluster/version"
response=$(curl --silent "${request}");
```

This is inconsistent. The latter should work in the same way as the former.

**Comment by kwart** [comment]
Closing as fixed in 3.12. The REST API calls don't require a password when security is not used.

For cases with security enabled (Enterprise edition only), a new PRD is created:
https://hazelcast.atlassian.net/wiki/spaces/PM/pages/1492419250/Unify+REST+API+authentication
