### ISSUE TITLE
Schema error: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:config'

### ISSUE THREAD

**Issue by Brevotto** [hazelcast/hazelcast#14313]
Please help! I am getting errors with I think hazelcast schema. 

When I use this schema:

`
		http://www.hazelcast.com/schema/spring 
		https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">
`

I am getting this error:

`cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:config'.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)`

and when I change the schema to:

`		http://www.hazelcast.com/schema/spring 
		http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd`

I am getting this error:

`cvc-complex-type.2.4.a: Invalid content was found starting with element 'hz:map'. One of '{"http://www.hazelcast.com/schema/spring":serialization, "http://www.hazelcast.com/schema/spring":native-memory, "http://www.hazelcast.com/schema/spring":security, "http://www.hazelcast.com/schema/spring":member-attributes, "http://www.hazelcast.com/schema/spring":services, "http://www.hazelcast.com/schema/spring":quorum, "http://www.hazelcast.com/schema/spring":lite-member, "http://www.hazelcast.com/schema/spring":hot-restart-persistence}' is expected.` 

Is there something that I am missing? I have also tried with different hazelcast schema versions and the generic one and a similar error would occur.

**Comment by vbekiaris** [comment]
@Brevotto can you post your actual config so we can have a look?

**Comment by Brevotto** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>

<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>

</beans>

`

**Comment by Brevotto** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>
</beans>`

**Comment by Brevotto** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.3.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.myhealthforce.eform.exist.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
	</hz:config>
	<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.hfp.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
</beans>`

**Comment by Brevotto** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>
</beans>

**Comment by Brevotto** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>
</beans>`

**Comment by Brevotto** [comment]
` 
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>
</beans>
`

**Comment by Brevotto** [comment]
`	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
		<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>`

**Comment by Brevotto** [comment]
<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.xxxxxxxx.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
		<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.xxxxxxxx.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>

**Comment by Brevotto** [comment]
Is there something wrong with my config? I was trying to add the <hz:map> to it.

**Comment by mmedenjak** [comment]
Hi @Brevotto !

I don't see the schema declarations in the XML snippet you've provided. Can you provide the full XML config? Can you confirm that you are using hazelcast 3.7?

**Comment by Brevotto** [comment]
`<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">`

yes I am using 3.7 in my pom file.

**Comment by Brevotto** [comment]
`<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">
		
	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.myhealthforce.eform.exist.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
		<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.hfp.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>

</beans>`


Yes I am using 3.7 in my pom file.

**Comment by Brevotto** [comment]
`<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:p="http://www.springframework.org/schema/p" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:util="http://www.springframework.org/schema/util" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:task="http://www.springframework.org/schema/task" xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
		http://www.springframework.org/schema/context 
		http://www.springframework.org/schema/context/spring-context-3.0.xsd 
		http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/util 
		http://www.springframework.org/schema/util/spring-util-3.0.xsd
		http://www.springframework.org/schema/task 
		http://www.springframework.org/schema/task/spring-task-3.0.xsd
		http://www.hazelcast.com/schema/spring
        http://www.hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">`


`	<hz:config id="cluster">
		<hz:group name="${cluster.name}" password="${cluster.pwd}" />
		<hz:network port="5701" port-auto-increment="false">
			<hz:join>
				<hz:multicast enabled="false" multicast-group="224.2.2.3" multicast-port="54327" />
				<hz:tcp-ip enabled="true">
					<hz:members>${cluster.members}</hz:members>
				</hz:tcp-ip>
			</hz:join>
		</hz:network>
		<hz:listeners>
    		<hz:listener class-name="com.myhealthforce.eform.exist.form.cached.FormCacheLifecycleListener"/>
    		<hz:listener implementation="formCacheLifecycleListener"/>
		</hz:listeners>
		<hz:map name="programMap">
			<hz:indexes>
				<hz:index attribute="program"/>
			</hz:indexes>
			<hz:attributes>
				<hz:attribute name="program" extractor="com.hfp.ldap.user.ProgramValueExtractor" />
			</hz:attributes>
		</hz:map>
	</hz:config>

</beans>`

For some reason I can't paste all of them together. Also yes I have 3.7 in my pom file. Thanks.

**Comment by mmedenjak** [comment]
Hi @Brevotto !

Unfortunately the XSD schema requires appropriate ordering. You will need to put the map config above the listener configuration. Then it should work.

**Comment by leszko** [comment]
Closing, feel free to reopen if you have any follow-up question.
