### ISSUE TITLE
maven-shade-plugin cannot create instance of HazelcastManifestTransformer

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#14338]
_master_ (commit 8b0a17f574591f61440d9ac8a2b37f0f3977aa09)

Failed in Hazelcast-3.x-deploy job: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-deploy/2718/console

Error message:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.2:shade (shade-artifacts) on project hazelcast-all: Unable to parse configuration of mojo org.apache.maven.plugins:maven-shade-plugin:2.2:shade for parameter transformer: Cannot create instance of class com.hazelcast.buildutils.HazelcastManifestTransformer: org/apache/log4j/Logger: org.apache.log4j.Logger -> [Help 1]
```

It was caused by commit https://github.com/hazelcast/hazelcast/commit/8b0a17f574591f61440d9ac8a2b37f0f3977aa09

**Comment by mdogan** [comment]
I think problem is, deploy task is setting `log4j` as the Hazelcast logger, I don't know why. But `log4j` is not available at the classpath during build, since it's an optional dependency.
 
```
clean deploy -B -DskipTests -Prelease-snapshot -DargLine="-Dhazelcast.assertTrueEventually.timeout=600" -DretryFailedDeploymentCount=5 -Dhazelcast.logging.type=log4j -U
```

`-Dhazelcast.logging.type=log4` is not needed here.

**Comment by olukas** [comment]
Thanks @mdogan . Removing `-Dhazelcast.logging.type=log4` fixed the reported issue. Closing.
