### ISSUE TITLE
When METRICS_DISTRIBUTED_DATASTRUCTURES is enabled, Cache statistics is not available on the metrics

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#14361]
The reason is that the Cache service doesn't implement the `StatisticsAwareService` interface.

P.S. While implementing this, there is an opportunity to remove the cache specific statistics collection code from `com.hazelcast.internal.management.TimedMemberStateFactory#createMemState`

**Comment by pveentjer** [comment]
TimedMemberState should be deleted or at least heavily reduced. It is the old way of getting metrics of members into MC.

**Comment by mmedenjak** [comment]
@pveentjer what's the new way? Is it merged yet?

**Comment by pveentjer** [comment]
The new way is doing everything through metrics.

It isn't merged since it has not been given priority and the previous implementation was way too complex to get merged.

**Comment by alex-dukhno** [comment]
@blazember, @mmedenjak does anyone working on this? I'd like to work on it

**Comment by mmedenjak** [comment]
@alex-dukhno we were planning on fixing it before 4.0-GA but it seems you beat us to it :) We'll check it out, thanks! 👏

**Comment by kwart** [comment]
Closing as fixed by #15889.
