### ISSUE TITLE
Names are not unique when clients are scaled out

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#14363]
We have below test case from this [Test Plan](https://hazelcast.atlassian.net/wiki/spaces/TES/pages/1311541766/Send+Client+Instance+Name+To+Member+Test+Plan). Please note that it is Docker deployment.

```
Case 2 - 3.12 Clients -> 3.12 Member When no explicit naming

Precondition:

Client-A as probe service 
Scaleable Client-S service to scale out for collecting names
Single Member cluster
Assumption: Clients have no name setting in configuration or programmatically 

Test Steps:

Wait for cluster sanity, Client-A should see 1 member
Check registered names on member 
Verify Client-A name
Scale Client-S to random count between inclusive 2, 5
Retrieve registered names on member 
Verify all names unique and equals connected client UUID size
```

Case currently is falling, since after scale out clients we do not see unique names iterating as stated in [TDD](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1242039173/Send+Client+Instance+Name+To+Member+Design)
```
When not set they are named as hz.client_0 , hz.client_1 .... etc.
For each java process, the count in the name starts from zero and incremented locally. 
```
We have below logs that shows the difference `names` and `uuids` as `set` that are retrieved from member, however, we are expecting iterating client names as `as hz.client_0 , hz.client_1`

```
INFO Names [hz.client_0, probe]
INFO UUID [f8109a61-5ed0-4a22-b3a2-059053c8d98b, 71c5d674-bfa9-4dbe-9489-dd558083f193, 34c6e6b9-4d5a-41a8-a4a1-222dfd265e7a]
```
Could you guide us?
TIA

**Comment by sancar** [comment]
`For each java process, the count in the name starts from zero and incremented locally. `

Since you are starting clients from different processes, we should expect to get `hz. client_0` for all clients here. The result is correct. I am closing the issue.
