### ISSUE TITLE
com.hazelcast.core.OperationTimeoutException: IsLockedOperation invocation failed to complete due to operation-heartbeat-timeout in after upgrade to 3.11.1 version

### ISSUE THREAD

**Issue by ajay2vns** [hazelcast/hazelcast#14395]
```
com.hazelcast.core.OperationTimeoutException: IsLockedOperation invocation failed to complete due to operation-heartbeat-timeout. Current time: 2019-01-18 12:39:31.757. Start time: 2019-01-18 12:37:30.759. Total elapsed time: 120998 ms. Last operation heartbeat: never. Last operation heartbeat from member: 2019-01-18 12:39:17.237. Invocation{op=com.hazelcast.concurrent.lock.operations.IsLockedOperation{serviceName='hz:impl:lockService', identityHash=1290231712, partitionId=232, replicaIndex=0, callId=-79718, invocationTime=1547815050760 (2019-01-18 12:37:30.760), waitTimeout=-1, callTimeout=60000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=cluster.map.batch.passenger}, threadId=0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1547815050759, firstInvocationTime='2019-01-18 12:37:30.759', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 01:00:00.000', target=[machineo1]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=Connection[id=1, /20.132.84.81:52659->machineo1/20.132.84.82:5701, endpoint=[machineo1]:5701, alive=true, type=MEMBER]}
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:164)
```

**Comment by mmedenjak** [comment]
Hi @ajay2vns !

Unfortunately this error message doesn't say much - it only says that there was an operation sent from `20.132.84.81` to `machineo1` (`20.132.84.82:5701`) to determine if the lock was locked. But there was never any response or indication that the operation was ongoing. It is possible your `machineo1` stopped responding, was somehow disconnected or there were other issues. Please look into the logs of that machine around the same time.

**Comment by mmedenjak** [comment]
As mentioned before, an operation timeout means the member responsible for running the operation is unresponsive. You might want to try and see why the member is unresponsive by profiling and monitoring it. Or, if you expect such pauses, you might want to increase the heartbeat timeout by increasing the `com.hazelcast.spi.properties.GroupProperty#OPERATION_CALL_TIMEOUT_MILLIS`.

On this note, with Hazelcast 4.0, we have replaced the entire implementation of ILock with the unsafe mode of CP subsystem (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#removal-of-deprecated-concurrency-api-implementations). If you don't require strong consistency guarantees, that mode might fit your use case and solve the issue. If you do require strong consistency guarantees, you definitely might want to try out using the CP subsystem by turning off unsafe mode and running the appropriate number of members. Please try it out.
