### ISSUE TITLE
Validate spring.schemas

### ISSUE THREAD

**Issue by lazydays79** [hazelcast/hazelcast#14441]
Hi!

This is a follow up to issue #14398.

I'm a little bit concerned that this problem might reoccur in the future.

So I wrote a little unit test which validates the spring.schemas file with 4 tests:

- check if all XSD files named in spring.schemas are available in src/main/resources
- check if the file names in the URLs of spring.schemas match the file name in src/main/resources
- check if the perma link (http://../hazelcast-spring.xsd) matches the highest known version of all xsd files in src/main/resources
- check if every http entry has a https entry and vice versa

I will create a pull request for this within the next minutes.

Since I'm on vacation for the rest of the week, I'm using my private GitHub account (lazydays79) instead of my work account (MichaelRisthausAtos).

I hope this is ok.

Best regards,
Michael

**Comment by burakcelebi** [comment]
Nice! Thank you for your contribution @lazydays79!
