### ISSUE TITLE
Local Map Stats per Map not Entry

### ISSUE THREAD

**Issue by notz** [hazelcast/hazelcast#1448]
I don't know why this is implemented per Entry as default setting. Their should be generell local stats per maps and that should be default.

I think in most use cases you only need the generell stats (>99%) like on mongodb. If you have some huge maps with only generics as value the overhead is immense. We shouldn't waste RAM for nothing.

**Comment by StanAccy** [comment]
This is the second time Ive heard this - that Map stats are per Entry and not per Map.  What does this mean?  When we request statistics from an IMap, we do it on a per node basis and then aggregate.  What are the statistics for if not for the portion of the IMap present on a node?

**Comment by pveentjer** [comment]
Closing this task. There is an option in map config to disable per entry statistics.

MapConfig.setStatisticsEnabled(false) will disable it.
