### ISSUE TITLE
cp atomic reference cas test with member kill returns null value 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14481]
http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicRefCas-kill/4/console
/disk1/jenkins/workspace/cp-atomicRefCas-kill/3.12-SNAPSHOT/2019_02_12-10_06_22/cas Failed
fail HzClient2HZ cp_atomicRef hzcmd.cp.ref.Cas threadId=10 java.lang.NullPointerException
15:46:19 http://54.234.90.98/~jenkins/workspace/cp-atomicRefCas-kill/3.12-SNAPSHOT/2019_02_12-10_06_22/cas
```
cat output/HZ/HzClient2HZ/exception.txt
java.lang.NullPointerException
	at hzcmd.cp.ref.Cas.timeStep(Cas.java:24)
```

http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicRefCas-kill/5/console
/disk1/jenkins/workspace/cp-atomicRefCas-kill/3.12-SNAPSHOT/2019_02_12-10_16_53/cas Failed
fail HzClient1HZ cp_atomicRef hzcmd.cp.ref.Cas threadId=10 java.lang.NullPointerException
15:56:55 http://54.234.90.98/~jenkins/workspace/cp-atomicRefCas-kill/3.12-SNAPSHOT/2019_02_12-10_16_53/cas
```
cat output/HZ/HzClient3HZ/exception.txt
java.lang.NullPointerException
	at hzcmd.cp.ref.Cas.timeStep(Cas.java:24)
```

both runs of the test failed after a few iterations of the member side kill -9 and restart cycle.

https://github.com/hazelcast/hzCmd-bench/blob/cp/src/main/java/hzcmd/cp/ref/Cas.java#L24
NPE at line 24 show the cp atomic referance returned null.

https://github.com/hazelcast/hzCmd-bench/blob/cp/src/main/java/hzcmd/cp/ref/Cas.java#L14
line 14 show we init all cp atomic referances to the value 0 at the start of the test.

looks like the shutdown version also has the same issue sometimes it fails with the same NPE 
http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicRefCas-shutdown/5/console

I do not see this NPE issue in other atomic reference cas test's

http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicRefCas-stable/3/console
http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicRefCas-split/4/console

or in the cp atomic long cas tests.
http://jenkins.hazelcast.com/view/cp-system/job/cp-atomicLongCas-kill/7/console

which do a similar action
https://github.com/hazelcast/hzCmd-bench/blob/cp/src/main/java/hzcmd/cp/ilong/Cas.java#L17

**Comment by mdogan** [comment]
I think this is the same issue with https://github.com/hazelcast/hazelcast/issues/14480. There was a trivial mistake in snapshotting logic in atomiclong and atomicref, which was causing restoration of atomiclong/atomicref with a wrong name. 
That's why atomicref was returning `null` and atomiclong was returning `0` after snapshot. 

We'll send the fix soon to the PR branch.

**Comment by Danny-Hazelcast** [comment]
fixed
