### ISSUE TITLE
Remaining todos for multiple endpoints work

### ISSUE THREAD

**Issue by tkountis** [hazelcast/hazelcast#14497]
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r253442957 (not a regression, issue may be addressed in the future)
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r253432880 (addressed in #14658)
- [ ] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256351866
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256359102 (addressed in #14658)
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256362406 (addressed in #14658)
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256369342 (addressed in https://github.com/hazelcast/hazelcast/pull/14700)
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256369484 (already addressed in previous PR)
- [x] https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256369903 (addressed in #14658)

**Comment by tkountis** [comment]
https://github.com/hazelcast/hazelcast/pull/14383#discussion_r256351866 is ignored for now, since we dont have a scope. Once Jet starts integration with 3.12 we will revisit to help with potential changes.
cc. @cangencer for future reference.

**Comment by mmedenjak** [comment]
@tkountis shall we move the issue to a later release or open a new one so we better track it?

**Comment by tkountis** [comment]
We've left a remaining TODO in the relevant code section  (see. https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/instance/NodeContext.java#L40)  that might cause a problem with JET integration. I believe that should be enough, if you insist on a separate issue, I am totally fine with it.
