### ISSUE TITLE
Non distributed Map loader alternative

### ISSUE THREAD

**Issue by maciekwiso** [hazelcast/hazelcast#14556]
MapLoader API when `loadAllKeys` method is invoked once on one member and then `loadAll(keys)` is distributed among all members doesn't really work for my case.
In my case I'm loading data from a source that only allows you to make single request to get all data, you can't do a query just for keys and then separate queries for data for specific set of keys.
It'd be very useful to have an alternative interface which would allow you to just load all data using one method on one member.

**Comment by dbrimley** [comment]
I think the only option you would have here is to write a loader youself using a client to read from your source and then load into the cluster using the Map API.

The only concern here could be that the size of the Dataset you have to load in one go might be very large and exceed the memory of the client.

We have no plans to enable an API such as this directly within the MapLoader itself.

I'm going to close the issue, but feel free to continue our chat here about how your could do your one shot load.

**Comment by maciekwiso** [comment]
What about allowing for configuring maploaders to be executed only on one node?
That would also help with this issue cause I'd be able to do the query just once in maploader on one node and then just load it to hazelcast cache.

**Comment by dbrimley** [comment]
A quick solution would be the client as mentioned above, or you could just start one member to perform the load and once loaded start the rest of the members to form a cluster.
