### ISSUE TITLE
IMDG 3.12-BETA-1 ships with ManagementCenter 3.11.3 in download

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#14562]
Management Center 3.11.3 is incompatible with 3.12,
claims 
`Cluster version 3.12.0 is not compatible with this version of Management Center (3.11.3)`

**Comment by tksarul** [comment]
I face this issue too.

**Comment by emre-aydin** [comment]
We have fixed this issue in later versions and always ship with a compatible MC.
