### ISSUE TITLE
Allow tagging of members for IExecutorService

### ISSUE THREAD

**Issue by tliron** [hazelcast/hazelcast#1457]
It's currently very difficult to do proper "task farming" in Hazelcast.

Our problem is that in our deployment we have dedicated nodes that should handle tasks. The only way to properly execute tasks only on those nodes is to put them in a separate group, creating two clusters. However, these nodes are _also_ part of the main group, so that they have to run two HazelcastInstances. Though this is fully supported by Hazelcast, it's cumbersome and wasteful: we don't actually need two clusters, we just want tasks to be executed on a smaller group of nodes.

IExecutorService has a submitToMember method that could help. We thought of creating our own list of members, and implementing our own round-robin to submit to a different member in order. But this quickly became complicated due to the dynamic nature of clusters.

It seems that this could easily be optimized. I suggest adding a submitToMemberWithTag method, which would submit to one of the members that have a certain tag. (There should also be a corresponding submitToAllMembersWithTag.)

In order for this to work, members must be configured with one or more tag. I suggest adding this directly to Config class, as a Set of strings, so it would look something like this:

```
config.getTags().add("task-farm");
```

This set could be broadcast to the other members in the cluster as part of its entry to the cluster, so that they could keep a simple table of which member has which tags.

And then, to submit a task:

```
executorService.submitToMemberWithTag(myTask, "task-farm");
```

Tags might be useful for other APIs, too, that need to work on a subset of members. I hope you will agree!

**Comment by mikeyg123** [comment]
Hi, Please can you clarify - does the above example execute the task once on one of the selected members - or on all members for which the MemberSelector returns true?
I suspect the latter - in which case can we have an "executeOnOneMember()" method?
Also can the same be added to the ScheduledExecutorService?
Thank you

**Comment by Donnerbart** [comment]
Since a new public API will just be added in minor versions and the time window for 3.9 is already closed, please try the following code:
```java
    public void executeOnSingleMember(Runnable task, HazelcastInstance hz) {
        Member member = hz.getCluster().getLocalMember();
        member.setBooleanAttribute("my-attribute", true);

        IExecutorService es = hz.getExecutorService("default");
        es.executeOnMembers(task, new SingleMemberAttributeSelector("my-attribute"));
    }

    private static class SingleMemberAttributeSelector implements MemberSelector {
        
        private final String attributeName;
        
        private boolean memberFound = false;

        private SingleMemberAttributeSelector(String attributeName) {
            this.attributeName = attributeName;
        }

        public boolean select(Member member) {
            if (memberFound) {
                return false;
            }
            if (Boolean.TRUE.equals(member.getBooleanAttribute(attributeName))) {
                memberFound = true;
            }
            return memberFound;
        }
    }
```

**Comment by mikeyg123** [comment]
Thank you, that's the sort of thing I was looking for.

As I need to schedule at fixed rate and the set of available members may change I'm going to need a 2 stage job.  A scheduled wrapper job that can run on regularly on any node which then selects an appropriate node to submit a single execution of the real task.  
Since not every node has the same classpath there's a little bit of work to make sure the final callable can be deserialized on the intermediate node where the wrapper job runs. I'll probably have to resort to passing the class name and parameters inside another wrapper that can classload it when run() is called.

I don't think there's any other way to dynamically run repeating task on one of a subset of nodes while the set of active nodes in the subset can change.
