### ISSUE TITLE
Vague documentation about QueryCache being always up-to-date view of the IMap

### ISSUE THREAD

**Issue by gdela** [hazelcast/hazelcast#14612]
An excerpt from the documentation of [Continous Query Cache](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#continuous-query-cache):

> A continuous query cache is used to cache the result of a continuous query. After the construction of a continuous query cache, all changes on the underlying IMap are immediately reflected to this cache as a stream of events. Therefore, this cache will be an always up-to-date view of the IMap. You can create a continuous query cache either on the client or member.

I think that it misleads readers, that the changes to the `IMap` are being synchronously propagated to the `QueryCache`. They are not "immediately reflected" and such view is not "always up-to-date", see my [example code on stackoverflow](https://stackoverflow.com/questions/54928516), which one could expect to work based on the above description of Continous Query Caches.

**Comment by Serdaro** [comment]
Thank you @gdela .

@ahmetmircik , Could you please comment and lend a hand on how to update the related content?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/f03a71da0fdaf2ff83700b3c635d65ff9f5eb1b9
