### ISSUE TITLE
is it HZ acceptable to use GitHub as general forum for questions/answers/musings?

### ISSUE THREAD

**Issue by Cotton-Ben** [hazelcast/hazelcast#14694]

**Comment by Cotton-Ben** [comment]
... hopeful this might be ok?  working now on client site that strictly prohibits posts to StackOverflow, GoogleGroups, Gitter, etc.

**Comment by burakcelebi** [comment]
Hi @Cotton-Ben! Sure, please go ahead. (Although this is not the preferred way :) 

Closing this one, and looking forward to your questions.
