### ISSUE TITLE
Unknown GC for RHEL

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast#14701]
Hazelcast running on RHEL (OpenJDK8) shows "unknown gc" in the logs (instead of "major" and "minor" gc). Looks like RHEL OpenJDK GC is not supported in Hazelcast.

```
minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=224, unknown.gc.time=421ms
```

Steps to reproduce:
1. Create EC2 Instance from AMI (https://eu-central-1.console.aws.amazon.com/ec2/v2/home?region=eu-central-1#Images:search=ami-081df3d85a2ec2965)
2. SSH to the instance
3. Start Management Center: "cd ./management-center/hazelcast-management-center-3.11.3 && ./start.sh"
4. Start Hazelcast: "cd hazelcast-enterprise/ && ./start.sh"
5. In the Management Center, you'll see that GC is not shown (so unknown GC is used)

**Comment by mmedenjak** [comment]
Java version:
```
[ec2-user@ip-172-31-1-129 ~]$ java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)
```

GC names reported on that machine:
```java
public class GcNames {
    public static void main(String[] args) {
        for (GarbageCollectorMXBean gc : ManagementFactory.getGarbageCollectorMXBeans()) {
            System.out.println(gc.getName());
        }
    }
}
```
Output:
```
Copy
MarkSweepCompact
```

This needs to be added [here](https://github.com/hazelcast/hazelcast/blob/248ef7be63b1467c176eb7f3695749c87ce4dafc/hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/GarbageCollectionMetricSet.java#L45-L55).

**Comment by RobbanHoglund** [comment]
Hello, 
Since you are supporting IBM java (OpenJ9) you should also add the following collectors:

- scavenge (Hotspot´s Minor Gc)
- global (Hotspot´s Full Gc)

**Comment by mmedenjak** [comment]
Hi @RobbanHoglund ! Thanks for the tip! I know we still missed some collector algorithms, didn't have time to figure out which ones yet.

**Comment by RobbanHoglund** [comment]
Hello,

I added some to the list

  static {
        final Set<String> youngGC = createHashSet(4);
        // Hotspot JREs
        youngGC.add("PS Scavenge");
        youngGC.add("ParNew");
        youngGC.add("G1 Young Generation");
        youngGC.add("Copy");
        youngGC.add("ZGC"); //Should this be treated as a minor of full GC?
        //IBM & OpenJ9 JREs
        youngGC.add("partial gc"); 
        youngGC.add("scavenge"); 
        YOUNG_GC = Collections.unmodifiableSet(youngGC);

        final Set<String> oldGC = createHashSet(5);
        // Hotspot JREs
        oldGC.add("PS MarkSweep");
        oldGC.add("ConcurrentMarkSweep");
        oldGC.add("G1 Old Generation");
        oldGC.add("G1 Mixed Generation");
        oldGC.add("MarkSweepCompact");
        //IBM & OpenJ9 JREs
        oldGC.add("global");
        oldGC.add("global garbage collect");
        OLD_GC = Collections.unmodifiableSet(oldGC);
    }

**Comment by mmedenjak** [comment]
https://github.com/hazelcast/hazelcast/pull/17561

**Comment by RobbanHoglund** [comment]
Great! 👍
