### ISSUE TITLE
Document CP subsystem and advanced network config in full examples

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#14721]
No documentation for CP subsystem and advanced network configuration in `hazelcast-full-example.xml` and the YAML counterpart. Should be done for 3.12.

**Comment by mdogan** [comment]
All CP subsystem configuration elements are explained in at least 4 different places; reference-manual, javadoc, hazelcast.xsd, spring.xsd. What's the point of having them in configuration examples too?

**Comment by blazember** [comment]
The aim - _I guess_ - of the full-example configs is that the end users can take and start playing with them with in-place explanatory comments, like with the code samples. We historically add comments and explain the configuration options in these files. We're missing these for CP and advanced network, so I created this to fill the gap.

Additionally, since YAML has no schema definition where we can document what and how to configure, having an example config with explanations in it is even more important.

**Comment by blazember** [comment]
Closing as implemented by the two referenced PRs.
