### ISSUE TITLE
Application server performance  gets degraded in clustered environment.  

### ISSUE THREAD

**Issue by veerumallavarapu** [hazelcast/hazelcast#14736]
Hi All

We are encountering an application performance issue , if individual instances are joined in cluster.  

Without cluster we are not seeing any issues.  We have captured the diagnostics from the individual nodes with Hazelcast version 3.10.4.    And we still using the below parameter with default value.

hazelcast.health.monitoring.delay.seconds=60

hazelcast.diagnostics.enabled=true
hazelcast.diagnostics.metric.level=info
hazelcast.diagnostics.invocation.sample.period.seconds=30
hazelcast.diagnostics.pending.invocations.period.seconds=30
hazelcast.diagnostics.slowoperations.period.seconds=30

hazelcast.operation.call.timeout.millis=<default_value>. Can you confirm me what is the default value?

**Comment by veerumallavarapu** [comment]
attached files

**Comment by veerumallavarapu** [comment]
Diagnostics files are available at below location as I am not able to upload here.  Making it available from google drive.

https://drive.google.com/file/d/1Im1MWokLP9HxHnM34ZHUwTLMq4OftHPB/view?usp=sharing

https://drive.google.com/file/d/1ygC1-09p69TD07IjkIdpUA_BfpsYpfJk/view?usp=sharing

**Comment by veerumallavarapu** [comment]
It is an extension to https://github.com/hazelcast/hazelcast/issues/7689 , with Hazelcast 3.10 version.

Awaiting your response as it is very much critial to our product. It is a blocker for us.

**Comment by veerumallavarapu** [comment]
Can someone respond on this  please ???

**Comment by tkountis** [comment]
@veerumallavarapu could you please define performance issue? What is the behavior you are seeing, which actions manifests it? Also, it would be very handy to give us some app logs, and the code that actually runs during this performance issue. Lastly, a JFR recording or any other profiler capture would be very handy.

**Comment by veerumallavarapu** [comment]
Hi tkountis

thanks for your response.  I have fixed it by replacing the IMap.put() with IMap.setAsync() method.

It is very much improved now as it doesn't do any serialization.

**Comment by veerumallavarapu** [comment]
https://hazelcast.com/performance-top-5-1-map-put-vs-map-set/
