### ISSUE TITLE
Communication with particular member 

### ISSUE THREAD

**Issue by haegThe** [hazelcast/hazelcast#14860]
Hi，
We hope one member can send send messages to a particular member in the same cluster. And the particular member should do something when it receives a message.

Please let's know how it possible,

Thanks

**Comment by vbekiaris** [comment]
@haegThe sounds like you could use `HazelcastInstance.getExecutorService()` to obtain an `IExecutorService` (see [reference manual here](https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#executor-service) ) and then use it to submit `Runnable`s to a particular `Member`.

That said, maybe a longer discussion about your particular use case could be better continued at [Hazelcast google group](https://groups.google.com/forum/#!forum/hazelcast) (prefer github issues for reporting issues or requesting enhancements). Closing this question now.
