### ISSUE TITLE
Bad dependency EndpointQualifier in Networking

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#14871]
We do not want dependencies of the HZ cluster to networking. Networking should remain agnostic about higher level concepts like clients/qualifiers etc. So these issues need to be addresses outside of networking.

Once we start to integrate such concepts, networking will become more difficult to use in different scenario's.

```
    Channel register(EndpointQualifier endpointQualifier,
                     ChannelInitializerProvider channelInitializerProvider,
                     SocketChannel socketChannel,
                     boolean clientMode) throws IOException;


```

Probably this can be replaced by doing the channelInitializerProvider call outside of the Networking before the register call is made.

**Comment by pveentjer** [comment]
Probably the ChannelInitializerProvider should be removed out of the networking package as well

**Comment by mmedenjak** [comment]
Setting to 4.1 as this might be an internal change without breaking any API.

**Comment by pveentjer** [comment]
IMHO minor changes should be done quickly to prevent technical debt accumulation. The longer you wait, the bigger the expense.

**Comment by mmedenjak** [comment]
True. But we also want to be strict with the 4.0 scope as it's still pretty huge and we might end up releasing in a year.
