### ISSUE TITLE
HazelcastJsonValue is not Comparable

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#14888]
HazelcastJsonValue is not Comparable, so can't be used in a PagingPredicate

```
java.lang.ClassCastException: class com.hazelcast.core.HazelcastJsonValue cannot be cast to class java.lang.Comparable
```

Comparable on `toString()` would be enough

**Comment by mmedenjak** [comment]
Since we're heavily invested in the new query engine, I don't think we should spend too much time on this.
