### ISSUE TITLE
Node could not join cluster. A configuration mismatch was detected

### ISSUE THREAD

**Issue by kdohz** [hazelcast/hazelcast#14893]

**Comment by mdogan** [comment]
@kdohz: Can you please add more description about the issue? 
- version information
- cluster configuration
- cluster size
- stacktraces
- logs
- ...

**Comment by kdohz** [comment]
Hello @mdogan 

I apologize I should not raise this ticket. It was an accident.
The issue I reported was already in https://github.com/hazelcast/hazelcast/issues/14252

Please close the ticket

Thanks,
Kinh
