### ISSUE TITLE
Client misses notifications after initialization

### ISSUE THREAD

**Issue by agherardi** [hazelcast/hazelcast#14902]
I'm using Hazelcast 3.8. I have a test that does the following:
- Creates a cluster with 2 server nodes
- Connects a client to the cluster
- Immediately after HazelcastClient.newHazelcastClient() returns the client instance, get an ITopic and registers a MessageListener
- Has the 2 server nodes publish messages to the ITopic

Often, the client doesn't receive the ITopic messages.

The logs show that HazelcastClient.newHazelcastClient() returns when the client has connected to 1 server but not the other. After HazelcastClient.newHazelcastClient() returns, the client connects to the 2nd server in a background task.

The problem goes away if I make the test sleep until the client is connected to both nodes.

I came up with the following workaround: Before subscribing to the ITopic, I have the client submit a dummy Callable on all members and call get() on the future. The rationale being that, to execute the Callable and wait for a result, the client must connect to all servers nodes.

Any thoughts?

Thanks,
Alessandro

**Comment by sancar** [comment]
Hi @agherardi , 
We have a fix to address your use case. As of 3.8.7, your use case should be ok. 
https://github.com/hazelcast/hazelcast/pull/11421
Please reopen the issue if it does not solve your problem. Thanks for the feedback.
