### ISSUE TITLE
How to modify complex objects using hazelcast management center?

### ISSUE THREAD

**Issue by pavan2017** [hazelcast/hazelcast#14903]
Using scripting from management center it is easy modify simple objects. Are there any plans to enhance management center to modify complex or nested objects?

**Comment by emre-aydin** [comment]
Hi @pavan2017,

Do you mean using the Scripting screen or the Console screen? On Scripting screen, you can do everything programmatically. If it's for Console screen, do you have anything specific in mind, such as JSON support etc?

**Comment by emre-aydin** [comment]
Closing the issue as the user is not responding.
