### ISSUE TITLE
Wrong class name entry for Eureka in AliasedDiscoveryConfigUtils

### ISSUE THREAD

**Issue by amaykumar** [hazelcast/hazelcast#14926]
I am trying to initialize Hazelcast client using Eureka registry ( the Hz members are registered in Eureka). The initialization fails. Upon debugging, I found that the ALIAS_MAPPINGS in the class com.hazelcast.config.AliasedDiscoveryConfigUtils has wrong entry for Eureka. It is com.hazelcast.eureka.one.HazelcastKubernetesDiscoveryStrategy, but the correct value should be com.hazelcast.eureka.one.EurekaOneDiscoveryStrategy.

**Comment by mmedenjak** [comment]
Fixed with https://github.com/hazelcast/hazelcast/pull/14347. Thank you for the report @amaykumar !
