### ISSUE TITLE
map size() returns negative integer 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#14935]
the doc says 
```
If the map contains more than Integer.MAX_VALUE elements
size(), returns Integer.MAX_VALUE
```
I loaded a map with more that Integer.MAX_VALUE key values.
I see that size() returns a negative integer.

should map size be changed to long ?

**Comment by mdogan** [comment]
Since we implement `j.u.Map` interface, `size()` cannot return `long`. But this is a bug if `size()` returns a negative value.

PS: btw, congratz on loading a map with more than 2 billion items.

**Comment by mdogan** [comment]
Maybe we should change the milestone to `3.12.1`...

**Comment by mmedenjak** [comment]
Changed to 3.12.1. Not sure which number we should actually return though :)

**Comment by Danny-Hazelcast** [comment]
```
load@class=hzcmd.map.loader.LoaderQuickApprox [driver=.*, threads=160, warmup=0, duration=0, bench=No, interval=0, recordException=true, keyDomain=3000000000, valueSize=1000, name=mapBak1HD]
loadHz Done
size@class=hzcmd.map.validate.Size [driver=Member1HZ, threads=1, warmup=0, duration=0, bench=No, interval=0, recordException=true, name=mapBak1HD, size=3000000000]
fail HzMember1HZ size hzcmd.map.validate.Size threadId=0 global.AssertionException: map mapBak1HD size -2147154796 != expected 3000000000
```

**Comment by Danny-Hazelcast** [comment]
can we add a long get size method ? 

long getLongSize()
