### ISSUE TITLE
hazelcast for open source can support to store the data in the hard disk ?

### ISSUE THREAD

**Issue by wanshitaotao** [hazelcast/hazelcast#14930]
Now I try to restart my module in the docker, the Memory-based data maybe lost , so I want to add the persistence on the hard disk.

**Comment by ahmetmircik** [comment]
Yes you can persist your data with open source version. For further info, please see this: https://docs.hazelcast.org/docs/latest/manual/html-single/#loading-and-storing-persistent-data

I'm closing this issue, you can use [google forum](https://groups.google.com/forum/#!forum/hazelcast) for similar how-to questions.
