### ISSUE TITLE
HazelcastInstance.getConfig().getConfigurationUrl() is null when bootstrapped with system property

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#14960]
If Hazelcast is bootstrapped with the presence of the standard System property, the `Config` instance does not reflect the location of the configuration:

```
Apr 29, 2019 3:04:26 PM com.hazelcast.config.AbstractConfigLocator
INFO: Loading configuration 'classpath:org/springframework/boot/autoconfigure/hazelcast/hazelcast-specific.yaml' from System property 'hazelcast.config'
Apr 29, 2019 3:04:26 PM com.hazelcast.config.AbstractConfigLocator
INFO: Using classpath resource at org/springframework/boot/autoconfigure/hazelcast/hazelcast-specific.yaml
```

`HazelcastInstance.getConfig().getConfigurationUrl()` is `null`. 

The Javadoc states it should:

> Returns the URL to the XML configuration, which has been parsed to create this Config instance.

If there are cases where this is not available, please update the Javadoc to document them.

**Comment by blazember** [comment]
The javadoc is updated. Many thanks for raising this @snicoll :+1:
