### ISSUE TITLE
Expire Time 

### ISSUE THREAD

**Issue by LuffeyZero** [hazelcast/hazelcast#14977]
Why not provide an API  set expires time to key,If somebody got a idea to achieve , please tell me

**Comment by ahmetmircik** [comment]
Did you see [IMap#setTtl](https://github.com/hazelcast/hazelcast/blob/66b226d7d1fd92ccc5a244ab2a09e911e06e5a6f/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L3016)?

**Comment by ahmetmircik** [comment]
Closing this now, please reopen if ` IMap#setTtl` doesn't work for you.

**Comment by ldwnt** [comment]
@ahmetmircik 
I'm working with 3.12.7. According to the comments "New TTL value is valid starting from the time this operation is invoked, not since the time the entry was created." However, I test it and it seems the TTL is set against the original creation time:

```
        hazelcastInstance.getMap(map).set(key, key, 1, TimeUnit.HOURS);
        EntryView ev = hazelcastInstance.getMap(map).getEntryView(isLong ? Long.parseLong(key) : key);
        log.debug("oldexp {}", DateUtil.formatDateTime(new Date(ev.getExpirationTime())));
        log.debug("oldupdate {}", DateUtil.formatDateTime(new Date(ev.getLastUpdateTime())));
        log.debug("oldttl {}", ev.getTtl());

        try {
            TimeUnit.SECONDS.sleep(10);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        hazelcastInstance.getMap(map).setTtl(key, 1, TimeUnit.HOURS);

        hazelcastInstance.getMap(map).setTtl(isLong ? Long.parseLong(key) : key, ttl, TimeUnit.MILLISECONDS);
        ev = hazelcastInstance.getMap(map).getEntryView(isLong ? Long.parseLong(key) : key);
        log.debug("exp {}", DateUtil.formatDateTime(new Date(ev.getExpirationTime())));
        log.debug("update {}", DateUtil.formatDateTime(new Date(ev.getLastUpdateTime())));
        log.debug("ttl {}", ev.getTtl());
```

As you can see, 10s passed but both expiration/update time is not changed.
```
2021-05-28 17:58:06.022 DEBUG 11012 --- [ XNIO-1 task-42] oldexp 2021-05-28 18:58:06
2021-05-28 17:58:06.023 DEBUG 11012 --- [ XNIO-1 task-42] oldupdate 2021-05-28 17:58:06
2021-05-28 17:58:06.023 DEBUG 11012 --- [ XNIO-1 task-42] oldttl 3600000
2021-05-28 17:58:16.024 DEBUG 11012 --- [ XNIO-1 task-42] exp 2021-05-28 18:58:06
2021-05-28 17:58:16.024 DEBUG 11012 --- [ XNIO-1 task-42] update 2021-05-28 17:58:06
2021-05-28 17:58:16.024 DEBUG 11012 --- [ XNIO-1 task-42] ttl 3600000
```

**Comment by ahmetmircik** [comment]
@ldwnt seems you are right, there is an inconsistency between method javaDoc and running code. In 4.2, this seems to be fixed unintentionally as a result of cleanups there. 

Would you mind to create an issue?

**Comment by ldwnt** [comment]
> @ldwnt seems you are right, there is an inconsistency between method javaDoc and running code. In 4.2, this seems to be fixed unintentionally as a result of cleanups there.
> 
> Would you mind to create an issue?

no problem
