### ISSUE TITLE
Yaml config failures

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14988]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZuluJDK7/21/testReport/

Yaml tests should check JDK8+

**Comment by tezc** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/14992

**Comment by tezc** [comment]
Not the same root cause but : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-Windows-OracleJDK8/37/testReport/

**Comment by lazerion** [comment]
Similar cases fails on [Hazelcast-3.x-Windows-OracleJDK8](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-Windows-OracleJDK8/lastCompletedBuild/testReport/)
