### ISSUE TITLE
LockBasicDistributedTest failures

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#14980]
`maintenance` (commit e1361b6226ac2ed1c1fa5fb5a00be696e5ceae13)

LockBasicDistributedTest.testLockLeaseTime_lockIsReleasedEv
LockBasicDistributedTest.testTryLockLeaseTime_whenLockAcquiredTwice
LockBasicDistributedTest.testTryLockLeaseTime_lockIsReleasedEventually
LockBasicDistributedTest.testLockLeaseTime_whenLockAcquiredTwice

Failed on IBMJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/30/testReport/

Hiccups : 

```
00:14:55, accumulated pauses: 38 ms, max pause: 6 ms, pauses over 1000 ms: 0
00:15:00, accumulated pauses: 1079 ms, max pause: 1023 ms, pauses over 1000 ms: 1
00:15:05, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
00:15:10, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
00:15:15, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
00:15:20, accumulated pauses: 36 ms, max pause: 4 ms, pauses over 1000 ms: 0
00:15:25, accumulated pauses: 1800 ms, max pause: 1096 ms, pauses over 1000 ms: 1
00:15:30, accumulated pauses: 52 ms, max pause: 7 ms, pauses over 1000 ms: 0
00:15:35, accumulated pauses: 1881 ms, max pause: 1864 ms, pauses over 1000 ms: 1
00:15:40, accumulated pauses: 48 ms, max pause: 6 ms, pauses over 1000 ms: 0
00:15:45, accumulated pauses: 39 ms, max pause: 3 ms, pauses over 1000 ms: 0
00:15:50, accumulated pauses: 40 ms, max pause: 2 ms, pauses over 1000 ms: 0
00:15:55, accumulated pauses: 66 ms, max pause: 11 ms, pauses over 1000 ms: 0
00:16:00, accumulated pauses: 364 ms, max pause: 328 ms, pauses over 1000 ms: 0
00:16:05, accumulated pauses: 3 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-IbmJDK7/33/testReport/com.hazelcast.concurrent.lock/LockBasicDistributedTest/testLockLeaseTime_whenLockAcquiredTwice/

**Comment by mmedenjak** [comment]
These are all tests with leases so I'm assuming some hiccups made them fail. What needs to be seen is if we can improve the resilience of the tests.
