### ISSUE TITLE
split brain Client OOME com.hazelcast.client.spi.impl.listener.SmartClientListenerService

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#15034]
http://jenkins.hazelcast.com/view/split/job/split-rest/4/console

/disk1/jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest Failed

fail HzClient1HZAA rest-get-Map hzcmd.map.rest.curl.Get threadId=7 java.lang.OutOfMemoryError: Java heap space 

http://54.147.27.51/~jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest

./output/HZ/HzClient2HZAA/HzClient2HZAA.hprof
./output/HZ/HzClient1HZAA/HzClient1HZAA.hprof
./output/HZ/HzClient1HZAA/exception.txt

http://54.147.27.51/~jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest/gc.html

the client side heap is set intentionally small to catch OOME issue like this one.
we can see 2 very different GC patterns from the clients on the small and big sides of the split brain.   

we see the clients on the "small" side of the split brain show a classic leak pattern
http://54.147.27.51/~jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest/output/HZ/HzClient1HZAA/verbosegc.log.png

we see the clients on the "big" side of the split brain show stable GC
http://54.147.27.51/~jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest/output/HZ/HzClient3HZBB/verbosegc.log.png

we see the client on the outside of the split brain shows stable GC
http://54.147.27.51/~jenkins/workspace/split-rest/4.0-SNAPSHOT/2019_05_13-21_18_06/rest/output/HZ/HzClient6HZCC/verbosegc.log.png

from HzClient1HZAA.hprof
<img width="824" alt="Screen Shot 2019-05-14 at 13 00 32" src="https://user-images.githubusercontent.com/5988678/57689542-5d817980-7648-11e9-9231-830f5238a01b.png">
<img width="854" alt="Screen Shot 2019-05-14 at 13 00 45" src="https://user-images.githubusercontent.com/5988678/57689546-5d817980-7648-11e9-9eec-45b8fb06eb06.png">
<img width="794" alt="Screen Shot 2019-05-14 at 13 00 56" src="https://user-images.githubusercontent.com/5988678/57689548-5e1a1000-7648-11e9-945a-cdb0f4be9f98.png">

HzClient2HZAA.hprof shows same leak suspects.
<img width="859" alt="Screen Shot 2019-05-14 at 13 02 52" src="https://user-images.githubusercontent.com/5988678/57689697-afc29a80-7648-11e9-8c04-b1a8ef5f37f2.png">

**Comment by Danny-Hazelcast** [comment]
it took a long time to hit the OOME.

would this be an issue int 3.12 also ?

**Comment by sancar** [comment]
I think I found the cause. There is also a problem with 3.12. Fix is on the way.

**Comment by lazerion** [comment]
@sancar 
I think commit backported to `3.12.1`, causes below compilation error on 
```
08:02:32 [ERROR] /home/ec2-user/~/jenkins/workspace/Hazelcast-3.maintenance-ZingJDK7/hazelcast-client/src/test/java/com/hazelcast/client/listeners/leak/ListenerLeakTest.java:[253,32] error: local variable listenerService is accessed from within inner class; needs to be declared final
```
Sample job: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.maintenance-ZingJDK7/41/console

kindly check.

**Comment by sancar** [comment]
@lazerion Here is the fix https://github.com/hazelcast/hazelcast/commit/02a370111f509be5d2ce02821be0150837eb23a3
