### ISSUE TITLE
ConnectionManager JMX metrics are missing in 3.12

### ISSUE THREAD

**Issue by maxout123** [hazelcast/hazelcast#15080]
After upgrade of Hazelcast from 3.11.2 to 3.12, JMX metrics for ConnectionManager are not available anymore. All other metrics are there.

We are using hazelcast-docker images with built-in prometheus jmx exporter.

**Comment by maxout123** [comment]
I may be wrong, but it seems that ConnectionManager was replaced by NetworkingService in 3.12. But there are no any metrics for NetworkingService in jmx prometheus exporter also.

**Comment by pveentjer** [comment]
The 3.12 release contains a redesign of the connection logic. So the issue is probably caused by that.

**Comment by tkountis** [comment]
@maxout123 can you share your config? with default config, I can still see the JMX metrics on 3.12
<img width="715" alt="Untitled" src="https://user-images.githubusercontent.com/3369598/58817379-4543bf80-8634-11e9-841b-debf80f1dc58.png">

You are right about the renaming, everything is now under the 'NetworkingService' node.

**Comment by tkountis** [comment]
Closing this with no response.
Please re-open if you still have issues with the specific functionality.
