### ISSUE TITLE
I have one instance of hazelcast & that one is also not working

### ISSUE THREAD

**Issue by satishpatro44** [hazelcast/hazelcast#15084]
Previously I used embedded hazelcast in spring boot application 3.11.4 version which I closed. And I downloaded hazelcast zip file & started using start.bat yesterday. It was working fine. I closed it yesterday.

Now, when I am opening start.bat it is giving exception & close down

`com.hazelcast.security
Reasonn of failure for node  join: Joining node's version 3.12.0 is not compatible with 3.8.2
`

whereas I don't even have version of 3.8.2 that to running. I checked ports are open or not too

**Comment by pveentjer** [comment]
There must be a 3.8.2 version running somewhere. Else you would not get this error.
