### ISSUE TITLE
Missing default serializers

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#15179]
These common types are missing default serializers:

`Object[]`
`Map.Entry`
`HashMap`
`HashSet`
`PriorityQueue`

These are currently implemented in Jet:

https://github.com/hazelcast/hazelcast-jet/tree/master/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/serialization

Some of them could be moved into IMDG for 4.0

**Comment by mmedenjak** [comment]
Some were added with https://github.com/hazelcast/hazelcast/pull/15371. @ihsandemir do you think it's worth adding the rest?

**Comment by ihsandemir** [comment]
I think we can add the rest @mmedenjak . I will send a PR @cangencer.

**Comment by mmedenjak** [comment]
@cangencer @eminn we've added the remaining serializers to IMDG
