### ISSUE TITLE
XA compatibility regression between 3.9 and 3.10 - Commit of prepared Xid on second XAResource fails

### ISSUE THREAD

**Issue by lichtin** [hazelcast/hazelcast#15175]
XA compatibility regression between 3.9 and 3.10
A commit of prepared Xid on second XAResource fails.
See also #2696

**Comment by lichtin** [comment]
[HazelcastXaCompatibilityTest.java.txt](https://github.com/hazelcast/hazelcast/files/3290615/HazelcastXaCompatibilityTest.java.txt)

These tests work fine with Hazelcast versions <= 3.9 and start to fail with >= 3.10

**Comment by kwart** [comment]
It seems the `OperationRunnerImpl` refactoring in 3.10 caused the backup operations are not fired anymore if the original operation returns `false` from `boolean returnsResponse()` method.

**Comment by lichtin** [comment]
Thanks much for this. Would it be possible to merge this into a 3.11/3.12 version?
The problem is that 4.x is a major release and rolling upgrades will not work.

**Comment by mmedenjak** [comment]
Yes, I believe it is possible. @kwart can you prepare a backport?

**Comment by kwart** [comment]
Just working on it :)
