### ISSUE TITLE
Warning “Master version should be greater than ours” on new nodes start

### ISSUE THREAD

**Issue by apanasevich** [hazelcast/hazelcast#15232]
We had two Hazelcast nodes running in a cluster of six nodes. Setup is described here: #15160. Then, we started two new nodes simultaneously and got a single warning on one new nodes.

[WARN ] hz._hzInstance_2_cross-shard.generic-operation.thread-7 - com.hazelcast.internal.partition.InternalPartitionService : [172.16.20.94]:6004 [cross-shard] [3.10.5] Master version should be greater than ours! Local version: 881, Master version: 880 Master: [172.16.20.88]:6002

I've found #8736 with the similar question, but the case is different: no nodes are shutting down.

Did we lose some data? What does the warning mean in this case? Shall we ignore it?

**Comment by mdogan** [comment]
Hi @apanasevich:
That was a wrongly printed warning as far as I remember and should be fixed in later versions. Can you please test with latest 3.12.x version?

**Comment by apanasevich** [comment]
Thank you for answering.

> Can you please test with latest 3.12.x version?

Yes, we have already upgraded to 3.12.2. I'll be look after logs and let you know the result.

**Comment by mmedenjak** [comment]
Thank you for upgrading! I'll close this issue as fixed by https://github.com/hazelcast/hazelcast/pull/14351. Please reopen this issue or open a new one if the issue reoccurs.
