### ISSUE TITLE
SQL: Optimized serialization with backward compatibility support

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15245]
SQL engine requires the serialization of many objects. Specifically:
- Execution stages (`PhysicalNode`)
- Expressions (`Expression`)
- Rows and batches (`SendBatch`)

This current implementation of serialization has two problems:
- It uses `writeObject` and `readObject` routines a lot, which are very expensive
- It doesn't support compatibility in any way

What we need:
- Implement a "version" concept which will govern how data is serialized *AND* which operators are allowed in the plan (e.g. consider a new operator which is not implemented on the member of the previous version)
- Implement proper serialization routines for all serializable objects without expensive `writeObject` and `readObject` calls
- Make sure that we do not write redundant information. E.g. when writing N rows, current we write the number of attributes N times, while it could be written only once per batch
- Check if `IdentifiedDataSerializable` is more appropriate for us than `IDataSerialziable`

**Comment by mmedenjak** [comment]
We have [Versioned](https://github.com/hazelcast/hazelcast/blob/c7700c26915756d3c67476b0a278fdc04eeb0f95/hazelcast/src/main/java/com/hazelcast/nio/serialization/impl/Versioned.java) for backwards compatibility during rolling upgrades.

**Comment by devozerov** [comment]
Closing this ticket for now. The compatibility problem is already solved for beta - we do not allow the execution of a query on a mixed-version topology. The concrete solution to the compatibility will be worked out when moving the engine out of the beta state. Any suggestions before that are highly speculative and subjected to frequent change. There is no need to keep the outdated ticket open for now.
