### ISSUE TITLE
SQL: Implement declarative partitioning strategy

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15256]
This is a key pre-requisite for co-located joins #15257, which are the most prevalent and performant joins types (together with joins w/ replicated maps).

Keys are mapped to partitions based either on the whole key, or part of it. The latter case is handled by the `PartitioningStrategy` interface. Default implementation checks if the key is an instance of `PartitionAware` interface. If yes - it is invoked to get partition key, otherwise, the whole key is used. While suitable for standard map operations, this approach doesn't work for SQL.

When doing a query it is very important to understand whether one of the top-level conjunctive equality predicates (if any) is a predicate on partition column. If yes, co-located joins could be used. E.g.:
```sql
SELECT * FROM a, b WHERE a.__key.partAttr = b.__key
```
If we know that the map "a" **always** uses "partAttr" as the partition key and the map "b" **always** uses its full key as the partition key, then the join is co-located, i.e. all matching pairs are always on the same member.

The reason why current API doesn't work is that we need to answer the question "Are **all** entries in these two maps are collocated on the given attributes?" **before** we know the actual keys. Hence, we need a **declarative** partitioning strategy rather than **programmatic**.

One possible solution is a new `PartitioningStrategy` which will use predefined attribute name, rather than some non-deterministic code:
``` java
class AttributePartitioningStrategy implements PartitioningStrategy {
    private String attributeName;
}
```

**Comment by mmedenjak** [comment]
I also think it should be simple to implement and introduce in 4.0, possibly as a special case of a programmatic `PartitioningStrategy`.
A question - even though we should provide for a way to define the attribute declaratively, can we still allow for more complex programmatic partitioning strategies? Or do programmatic partitioning strategies somehow preclude running certain types of queries or queries in general, in which case the recommendation would be to remove programmatic partitioning strategies in general?

**Comment by devozerov** [comment]
@mmedenjak Nothing prevents us from having both declarative and programmatic strategies. The downside of a programmatic strategy is that the SQL engine will not be able to guarantee collocation, so a less optimal (safe) execution plan will be chosen.

Some products, such as Hazelcast or Apache Ignite, allow users to define programmatic strategies for the sake of flexibility. But a number of other products (e.g. Cassandra, Mongo, Couchbase), don't, because most use cases could be covered without programmatic stuff or annotations at all. In general, the following are the most important things, which could be set declaratively:
1) Allow using the whole key
2) Allow using key's field
3) Allow to configure some backup- and rack-awareness

But this is a part of a much wider and complex discussion. My personal opinion, after being for years in IMDG, is that programmatic strategies do more harm than good. If I am to create an IMDG from scratch, I would have only declarative strategies. Or mostly declarative strategies to cover 99,9% of cases and some programmatic extension for super-advanced users. 

BTW, one very important reason why programmatic strategies are bad is that they do not work well with non-Java clients, while declarative strategies could be implemented easily on every language to enable partition-awareness.

**Comment by devozerov** [comment]
Discussed with the team, no objections. However, @taburet made an important comment: without information about the field's type it will be difficult to use this interface in some cases, e.g. partition pruning. Consider the following code:
```sql
SELECT * FROM Person WHERE dept_id=:1
```
Let `dept_id` be a partitioning field of type A. If the query parameter `:1` is of the same type, everything will work fine. But if it is of different, yet compatible type, e.g. `Long` instead of `Integer`, then partition pruning (#15255) will not work, because `(Long)1` and `(Integer)1` will be mapped to different partitions. One potential solution to the problem is field constraints, i.e. when the type of a specific field is constrained to a certain type. Or a kind of explicit type defined in the partitioning strategy level, which will convert an object field to some fixed type (if the conversion is possible).

**Comment by devozerov** [comment]
Implemented in the prototype.
