### ISSUE TITLE
persist configuration with hot restart

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#15261]
**Case definition:**
Start a cluster with hot-restart enabled.
Add a new map configuration programmatically while the cluster is running. 
Restart the cluster.
The started cluster does not have the newly added configuration.

I expect the newly added configuration to be persisted too.

**Comment by jerrinot** [comment]
this is already supported. feel free to re-open it if you think it's buggy.

**Comment by mmedenjak** [comment]
This should be where it's written to disk: https://github.com/hazelcast/hazelcast-enterprise/blob/d6bb8355f94ecf101148756a3428701ba2eb7a34/hazelcast-enterprise/src/main/java/com/hazelcast/spi/hotrestart/PersistentConfigDescriptors.java#L134

**Comment by mdogan** [comment]
As far as I see, `IMap` does not persist its configuration. 
```java
String name = mapContainer.getName();
hotRestartService.ensureHasConfiguration(MapService.SERVICE_NAME, name, null); // <--- passing NULL here
prefix = hotRestartService.registerRamStore(this, MapService.SERVICE_NAME, name, partitionId);

```

Whereas `ICache` does;

```java
// store in hot restart persistent store with PreJoinCacheConfig format
hotRestartService.ensureHasConfiguration(SERVICE_NAME, cacheNameWithPrefix,
        new PreJoinCacheConfig(cacheConfig, false));
prefix = hotRestartService.registerRamStore(this, SERVICE_NAME, cacheNameWithPrefix, partitionId);
```

**Comment by mdogan** [comment]
But interestingly both `IMap` and `ICache` persist configs when dynamic configuration is created. See https://github.com/hazelcast/hazelcast-enterprise/blob/master/hazelcast-enterprise/src/main/java/com/hazelcast/internal/dynamicconfig/HotRestartConfigListener.java#L36
