### ISSUE TITLE
SQL: Threading architecture with a single pool

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15264]
Currently, we use two thread pools - control and data. 

Control pool is responsible for query start, routing of unmapped data batches, and, in future, query cancel. It establishes clear happens-before between start and cancellation with stripes hashed by `QueryId` so that control requests of a single query always end up in a single thread. Data pool processes mapped batch requests, striped by mapped stripe ID so that a single executor is always processed in a single thread. Moreover, currently, we use operation executor as an intermediate pool.

The problem with this approach is excessive thread wakeups. We should do the following:
- Add a priority queue to the data pool (kudos to @mmedenjak for the idea)
- Merge control and data pools: when the control request arrives, the data pool should stop current stage execution and process the control request
- Avoid using operation executor: add a new flag to `Packet` class and route requests to correct stripes directly.

This way we will have only one pool and as a result, fewer context switches. 

N.B.: Yet, the proposed approach might be a subject to some problems which should be investigated in the future:
- First unmapped requests will still be processed with additional thread switch from virtual control stripe to virtual data stripe. For single-threaded fragments, this could be alleviated by mapping data stripe to the same QueryId stripe. But this may lead to unfortunate schedules when some data threads are idle, while others are busy
- Currently, data fragments are bound to a stripe forever. Again, this may yield bad schedules when some CPUs are overloaded, while others are idle. Can we solve it with job stealing? Probably yes, but how to remap mapped batches with minimal overhead? And what kind of locking will be required to support it?
- Currently, the root fragment is executed in the data pool, and results are transferred back to user thread through an additional queue. This might be good for internal consumers (e.g. asynchronous client ), but may be less than optimal for normal synchronous consumers (public API). Caller-runs approach may help, i.e. root fragment will be executed on user thread and park while waiting for more batches to arrive.

**Comment by mmedenjak** [comment]
NIO pipelines have this concept of owning thread and the IO balancer migrates the pipelines between threads based on load: https://github.com/hazelcast/hazelcast/blob/92ca85687ad1f9cc2057a7cd3b7a27f22bad8019/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java#L200-L214

**Comment by devozerov** [comment]
In the end, we fell back to the original architecture with two thread pools. See https://github.com/hazelcast/hazelcast/pull/16806
