### ISSUE TITLE
MapConfig is not shared across the cluster

### ISSUE THREAD

**Issue by RebelUA** [hazelcast/hazelcast#15298]
Hi all!
I've encountered a problem with `max-idle-seconds` not evicting entries while working in cluster mode. I've managed to reproduce this issue and it seems that MapConfig that was set on one node is not copied to other nodes that join cluster later and `max-idle-seconds` evicts entries only on the first node that was created with MapConfig. I'm using latest Hazelcast 3.12.1.

[Link to gist](https://gist.github.com/RebelUA/cedc2cfb4738f917c186d17e84cff7d5)

**Comment by ahmetmircik** [comment]
Hi @RebelUA, you need to start all nodes with exact same config. In your code, only 1 node aware from `max-idle-seconds` others are not. Can you please re-try by giving same exact config to all nodes?

**Comment by RebelUA** [comment]
So map config is not replicated to other nodes?
And as I understood there is no way to change map config after the cluster is up and running?

**Comment by ahmetmircik** [comment]
>So map config is not replicated to other nodes?

Right.
 
>And as I understood there is no way to change map config after the cluster is up and running?

At runtime, you can only change a subset of MapConfig via management center, there is no other way to do it for an existing config. But if it fits your situation, there is a [dynamic config facility](https://docs.hazelcast.org/docs/latest/manual/html-single/#dynamically-adding-data-structure-configuration-on-a-cluster) which you can add new MapConfigs with it.

**Comment by RebelUA** [comment]
Thanks!
