### ISSUE TITLE
MultiMap other operation count stat reports per partition

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#15307]
Issues with operation-related `MultiMap` stats:
- Client-triggered operation invocations are not reflected in `LocalMultiMapStat` operation counts.
- Other operations count in `MultiMap` statistics report per partition instead of reporting the number of user calls. This is an analog issue to the one previously fixed by https://github.com/hazelcast/hazelcast/commit/5af07e2b8512d7600decda0f4c4470963fd8933f in `IMap`.

Possibly other data structures - such as `ReplicatedMap` - are also affected, look for `LocalInstanceStats` descendants and all `get*OperationCount` methods. This issue is hidden because of tests for these statistics are incomplete or not existing. These tests need to be completed/written to ensure the stats are gathered in a consistent way. See `LocalMapStatsTest` and its client and HD-specific variants.

Labeled with `4.0`, but it would make sense to backport the fix(es) when done.

Related https://github.com/hazelcast/hazelcast/issues/13007 https://github.com/hazelcast/hazelcast/issues/11951 https://github.com/hazelcast/hazelcast/issues/3703

**Comment by abdulazizali77** [comment]
hi @mmedenjak can i pick this up?

**Comment by mmedenjak** [comment]
Hi @abdulazizali77 ! On first glance, I believe you can. But I'm currently a bit overwhelmed so I can't look deeper into it to provide pointers. Perhaps @blazember can, or I will share some ideas in a couple of days.
