### ISSUE TITLE
SQL: Packaging of SQL module

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15315]
The current prototype already separates Calcite's dependent code from the core. However, it is not integrated with the build system anyhow. Final packaging should create `hazelcast-sql.jar` and place it near the core JAR. Success criteria are that SQL works out of the box without any additional user actions when downloaded from the site.

**Comment by mmedenjak** [comment]
Is it a similar case as when packaging `hazelcast-client.jar` as a separate module jar and having all of the modules included in a `hazelcast-all.jar` uberjar?

**Comment by devozerov** [comment]
@mmedenjak I think yes. We do not want to bother the user, everything should work out of the box, probably except Maven project, when a user will have to define the dependency on `hazelcast-sql` explicitly. 

On the other hand, we do not understand the whole dependency graph at the moment. Who knows - maybe it will be only the Calcite as well, plus several small dependencies, so that we can pack everything into `hazelcast-core`? As a part of this ticket, we should analyze the dependency graph first.

**Comment by devozerov** [comment]
Moved from "SQL: Research" to "SQL" component. We will have to implement it very soon.

**Comment by devozerov** [comment]
Duplicate to https://github.com/hazelcast/hazelcast/issues/16911
