### ISSUE TITLE
SQL: Research "SELECT *" support

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#15320]
`SELECT *` ("select star") normally returns all the fields of the table. But what are the fields in case of Hazelcast? What can be returned in theory:
- Top-level objects (key, value)
- Top-level fields of key/value
- Nested fields

At first glance. it seems that we should return the whole key plus all top-level fields of the value. But this may be not good for composite keys (e.g. in case of co-located maps).

**Comment by mmedenjak** [comment]
I guess in some cases the choice of representation is up to the user, e.g. https://documentation.progress.com/output/DataDirect/jdbcmongohelp/index.html#page/mongohelp%2Fcreating-a-schema-with-the-table-wizard.html%23wwID0EESIM

**Comment by devozerov** [comment]
The research outcome:
1. We decided to switch to the approach with a predefined schema (not fully reflected in the prototype yet), so it is trivial to get the full list of top-level fields
2. Nested fields are not supported at the moment

Therefore, it will be trivial to expand the start. The appropriate prod ticket will be created soon.
