### ISSUE TITLE
MembershipListener.memberAdded after split brain merge shows different member order

### ISSUE THREAD

**Issue by npiv** [hazelcast/hazelcast#15353]
hazelcast 3.12.1
Java 11

steps: 
1) Create a cluster with 2 members (lets call them A and B) on separate servers
2) Add a MembershipListener on each side. 
3) Simulate a network split, (eg. with iptables) and restore the connections. 

When the clusters merge again `memberAdded(MembershipEvent event)` is called on both sides, but `event.getmembers()` contains `[A,B]` on server A and `[B,A]` on server B.

**Comment by mdogan** [comment]
Hi @npiv,

Can you reproduce this issue every time or is it occasional? Can you also share the logs of both members when you hit the issue?

**Comment by npiv** [comment]
Hi @mdogan 

It is definitely every time. I can reproduce this consistently with a simple project like
-  https://github.com/npiv/brain-split,
-  started on 2 separate servers
-  remove network, and bring it back

See the logs below from the merge. The Members list as logged by Hazelcast is correct, but the one from the MemberAdded event on server 1 (at 19:59:15.752) puts 192.168.1.136 first.

Perhaps this is expected behavior, and we need to subscribe to a different event to recover from a merge, but it is not intuitive to me that it would happen.

Server 1:
`Jul 23, 2019 7:55:37 PM com.hazelcast.transaction.TransactionManagerService
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Committing/rolling-back live transactions of [192.168.1.121]:5701, UUID: 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce
Jul 23, 2019 7:59:09 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Initialized new cluster connection between /192.168.1.136:55378 and /192.168.1.121:5701
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] We should merge to [192.168.1.121]:5701, both have the same data member count: 1
Jul 23, 2019 7:59:09 PM com.hazelcast.cluster.impl.TcpIpJoiner
WARNING: [192.168.1.136]:5701 [brain-split-group] [3.12.1] [192.168.1.136]:5701 is merging [tcp/ip] to [192.168.1.121]:5701
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Locking cluster state. Initiator: [192.168.1.136]:5701, lease-time: 60000
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Extending cluster state lock. Initiator: [192.168.1.136]:5701, lease-time: 20000
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Changing cluster state from ClusterState{state=ACTIVE, lock=LockGuard{lockOwner=[192.168.1.136]:5701, lockOwnerId='62f57851-dd75-40d4-875a-9d37369ebd0d', lockExpiryTime=1563904829684}} to ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, initiator: [192.168.1.136]:5701, transient: false
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.impl.operations.MergeClustersOp
WARNING: [192.168.1.136]:5701 [brain-split-group] [3.12.1] [192.168.1.136]:5701 is merging to [192.168.1.121]:5701, because: instructed by master [192.168.1.136]:5701
Jul 23, 2019 7:59:09 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] [192.168.1.136]:5701 is MERGING
Jul 23, 2019 7:59:09 PM com.hazelcast.internal.cluster.ClusterService
WARNING: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Resetting local member UUID. Previous: c6d0aa7b-f1e4-4cca-99d6-1635153b9c11, new: 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf
Jul 23, 2019 7:59:09 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Connection[id=2, /192.168.1.136:55378->/192.168.1.121:5701, qualifier=null, endpoint=[192.168.1.121]:5701, alive=false, type=MEMBER] closed. Reason: EndpointManager is stopping
Jul 23, 2019 7:59:09 PM com.hazelcast.nio.tcp.TcpIpConnector
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Connecting to /192.168.1.121:5701, timeout: 10000, bind-any: true
Jul 23, 2019 7:59:09 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] Initialized new cluster connection between /192.168.1.136:55379 and /192.168.1.121:5701
Jul 23, 2019 7:59:15 PM com.hazelcast.internal.cluster.ClusterService
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] 

Members {size:2, ver:4} [
	Member [192.168.1.121]:5701 - 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce
	Member [192.168.1.136]:5701 - 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf this
]

19:59:15.752 INFO  npiv.ReportingMemberListener.memberAdded() @15 - memberAdded [Member [192.168.1.136]:5701 - 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf this, Member [192.168.1.121]:5701 - 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce]
19:59:15.752 [hz._hzInstance_1_brain-split-group.event-5] INFO  npiv.ReportingMemberListener - memberAdded [Member [192.168.1.136]:5701 - 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf this, Member [192.168.1.121]:5701 - 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce]
Jul 23, 2019 7:59:16 PM com.hazelcast.core.LifecycleService
INFO: [192.168.1.136]:5701 [brain-split-group] [3.12.1] [192.168.1.136]:5701 is MERGED`

Server 2
`INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1]
Committing/rolling-back live transactions of [192.168.1.136]:5701,
UUID: c6d0aa7b-f1e4-4cca-99d6-1635153b9c11
Jul 23, 2019 7:55:44 PM
com.hazelcast.internal.partition.InternalPartitionService
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1] Fetching most
recent partition table! my version: 0
Jul 23, 2019 7:55:44 PM
com.hazelcast.internal.partition.InternalPartitionService
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1] Most recent
partition table version: 0
Jul 23, 2019 7:59:10 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1] Initialized
new cluster connection between /192.168.1.121:5701 and
/192.168.1.136:55378
Jul 23, 2019 7:59:10 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1]
[192.168.1.136]:5701 should merge to us , both have the same data
member count: 1
Jul 23, 2019 7:59:10 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1]
Connection[id=2, /192.168.1.121:5701->/192.168.1.136:55378,
qualifier=null, endpoint=[192.168.1.136]:5701, alive=false,
type=MEMBER] closed. Reason: Connection closed by the other side
Jul 23, 2019 7:59:10 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1] Initialized
new cluster connection between /192.168.1.121:5701 and
/192.168.1.136:55379
Jul 23, 2019 7:59:16 PM com.hazelcast.internal.cluster.ClusterService
INFO: [192.168.1.121]:5701 [brain-split-group] [3.12.1]

Members {size:2, ver:4} [
    Member [192.168.1.121]:5701 - 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce this
    Member [192.168.1.136]:5701 - 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf
]

19:59:16.545 INFO  npiv.ReportingMemberListener.memberAdded() @15 -
memberAdded [Member [192.168.1.121]:5701 -
56cff975-3fb0-4172-a7bf-5f4ba1cb90ce this, Member [192.168.1.136]:5701
- 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf]
19:59:16.545 [hz._hzInstance_1_brain-split-group.event-4] INFO
npiv.ReportingMemberListener - memberAdded [Member
[192.168.1.121]:5701 - 56cff975-3fb0-4172-a7bf-5f4ba1cb90ce this,
Member [192.168.1.136]:5701 - 4b5333d9-0df9-459b-ac56-5c0bfcef8ccf]`
