### ISSUE TITLE
Improvements on OS map operations based on removed HD map operations

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15369]
Found some things that might be improved from removed HD map operations which are not a part of OS map operations:
https://github.com/hazelcast/hazelcast/pull/14968#pullrequestreview-265971555 (addressed by https://github.com/hazelcast/hazelcast/pull/15832)
https://github.com/hazelcast/hazelcast-enterprise/pull/2941#pullrequestreview-265981158

**Comment by alex-dukhno** [comment]
@mmedenjak I'd like to work on this one

**Comment by mmedenjak** [comment]
Great, thank you @alex-dukhno ! Let me know if you need anything. I admit, we can be slow at responding but we do try!

**Comment by mmedenjak** [comment]
Let me just copy my other comment since the first one is already addressed and the second is in the EE repo for which you don't have access.

> mmedenjak on 24 Jul
> The OS version has some additional logic where it tries to obtain the keys from the global index. Can we add an optimisation there to skip the global index in case of NATIVE maps? Can you check that it always fails to find the global index in case of NATIVE?
> It should in the case of NATIVE always return null from somewhere in QueryRunner#runUsingGlobalIndexSafely since there is no global index for NATIVE.

This relates to the `PartitionWideEntryWithPredicateOperationFactory` class. And some additional background - for on-heap (OBJECT and BINARY in-memory format), we create global indexes for query operations which are accessed concurrently from different threads. But for HD/NATIVE/off-heap in-memory format, we use indexes per-partition. This is because the indexes are stored off-heap and the backing structure is not thread-safe.

So the second comment tries to ask for a small enhancement to skip checking the global index if we already know the in-memory format is NATIVE.
