### ISSUE TITLE
Member UUID is lost on network disconnect/re-join

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#15365]
I have observed that if a node loses connection to the cluster then re-joins it receives a brand new UUID.  This is unexpected behavior (on my part) as I rely on the UUID of the node to determine if state changes propagating through the cluster are 'local' or not.  Please advise if this is the expected behavior or if there is something I can do to keep the same UUID.

**Comment by mdogan** [comment]
This is intentional. Because disconnected member re-joins as a fresh new member, it changes its identity too.

**Comment by markathomas** [comment]
OK, I have worked around it; just wanted some clarification.
