### ISSUE TITLE
Management center 3.12.2 incompatibility

### ISSUE THREAD

**Issue by tomaerden** [hazelcast/hazelcast#15374]
To demonstrate this, I've launched just a single hazelcast **3.12.1** member.
When connecting it to a **3.12.2** hazelcast management center, the map statistics data are different than when connecting it to a 3.12.1 hazelcast management center.
The columns displayed in the map statistics differ between both versions, resulting in data displayed in the wrong column when using hazelcast: events are displayed in the locks column.

Mgmt center 3.12.1
![hazelcast_3 12 1](https://user-images.githubusercontent.com/15321420/61881271-a2eade80-aef6-11e9-9234-51a716dfab9a.png)

Mgmt center 3.12.2
![hazelcast-3 12 2](https://user-images.githubusercontent.com/15321420/61881316-b433eb00-aef6-11e9-8f0e-79585d4b1640.png)

**Comment by mmedenjak** [comment]
cc @emre-aydin

**Comment by emre-aydin** [comment]
Hi @tomaerden, this is a known issue and was fixed in `v3.12.4` - see [the second item in MC release notes](https://docs.hazelcast.org/docs/management-center/rn/index.html#3-12-4). Can you please try with latest stable version of Management Center (`3.12.6` currently)?
