### ISSUE TITLE
Investigate whether Bits#readUtf8Char and Bits#writeUtf8Char can be replaced with standard String utf8 conversion

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#15402]
In reference to https://github.com/hazelcast/hazelcast/pull/15238#issuecomment-515875936 , please check to see if we can remove the Bits#readUtf8Char and Bits#writeUtf8Char methods. These methods does not handle 4-byte utf8 char conversion.

The methods are currently used by JSON serialization.

**Comment by devozerov** [comment]
PRs:
https://github.com/hazelcast/hazelcast/pull/16210
https://github.com/hazelcast/hazelcast-enterprise/pull/3422
