### ISSUE TITLE
IAtomicLong was reset on nodes shutdown

### ISSUE THREAD

**Issue by apanasevich** [hazelcast/hazelcast#15453]
Hi,

We had a running cluster of  four nodes (Hazelcast 3.10.5) and then stopped two of them. IAtomicLong started from zero value.

It was mentioned in https://docs.hazelcast.org/docs/3.10/manual/html-single/index.html#iatomiclong that IAtomicLong has only one syncronous backup. 

Is this the reason of reset? Is there a workaround?

**Comment by apanasevich** [comment]
Two nodes were shut down simultaneously. Is it a correct workaround to stop them one-by-one with a 5 minute span?

**Comment by mdogan** [comment]
Hey @apanasevich, sorry for the late response. 

`IAtomicLong` in Hazelcast 3.x series has only single backup and if you lose multiple members then it's possible to lose `IAtomicLong` data. But if you shutdown members gracefully, via `HazelcastInstance.shutdown()` method, you should not lose any data, regardless of you shutdown them simultaneously or one-by-one. Data loss is possible only when members are lost non-gracefully, such as:

- `HazelcastInstance.terminate()`
- Process kill/crash
- Network split
etc.

In Hazelcast 3.12, we have a CP version of the `IAtomicLong` which is built on a consensus algorithm and provides stronger consistency guarantees compared to older `IAtomicLong` implementation, which was built on lazy-replication of Hazelcast.

- For lazy replication and consistency guarantees of Hazelcast data structures see: [Consistency and Replication Model](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#consistency-and-replication-model)
- For the new CP subsystem see: [CP Subsystem](https://docs.hazelcast.org/docs/latest/manual/html-single/index.html#cp-subsystem)

In 4.0, we removed the old implementations of concurrency primitives and Hazelcast will have only CP based implemenations.

**Comment by apanasevich** [comment]
Thanks for details!
