### ISSUE TITLE
Refactor hazelcast to use clean code | Fixing Sonar issues

### ISSUE THREAD

**Issue by kailasandhalevu** [hazelcast/hazelcast#15474]
There are many code smells in the code and code can be updated to remove code smells

**Comment by kailasandhale** [comment]
@mmedenjak This task needs to be divided into multiple tasks as there are many such tasks and does not look ideal to do under single issue.

**Comment by mmedenjak** [comment]
HI @kailasandhalevu and @kailasandhale !

Yes, we are aware of this and we are slowly improving the situation but unfortunately the codebase is big and it's not possible to fix everything immediately. If you would like to fix some issues yourselves, please send a PR with the fix and we'll try to include it in the next release.

**Comment by mmedenjak** [comment]
Closing this issue as it is too broad. We are constantly improving the situation but it will take time. Please open a new issue for a more specific piece of code or send a PR fixing some issue.
