### ISSUE TITLE
Fail fast clients for Custom partition strategy

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast#15482]
Custom Partition Strategy is broken for clients: https://github.com/hazelcast/hazelcast/issues/13950

For example, if a map is configured with a custom partition strategy, clients should fail fast when getting that map. We should notify the user that this is not supported when accessing it via clients. 

Related: https://github.com/hazelcast/hazelcast-reference-manual/issues/710

**Comment by mmedenjak** [comment]
I assume this is a breaking change. Is this something we should address in 4.0 @sancar @asimarslan ?

**Comment by sancar** [comment]
This will require adding a new message to the client protocol. We are doing it only on minor releases. It is not possible to add this in a patch release.

**Comment by mmedenjak** [comment]
Can we reopen it and move it into 4.0 then?

**Comment by burakcelebi** [comment]
@mmedenjak we've already had a critical issue in 4.0 to fix it. This was only for fail-fasting in 3.12.x 

Please see: https://github.com/hazelcast/hazelcast/issues/13950

**Comment by mmedenjak** [comment]
Ah, right, thanks!
