### ISSUE TITLE
JMX: operationExecutorQueueSize attribute is not exposed correctly

### ISSUE THREAD

**Issue by kennymacleod** [hazelcast/hazelcast#15523]
The `operationExecutorQueueSize` attribute of `OperationServiceMBean` is not being exposed via JMX as expected.

This is because, unlike the other attributes that *are* exposed, the `getOperationExecutorQueueSize` method is not `public`. Looks like a simple omission, but it's been like that since day 1.

**Comment by mmedenjak** [comment]
Closing as fixed by https://github.com/hazelcast/hazelcast/pull/15524 and https://github.com/hazelcast/hazelcast/pull/15531.
