### ISSUE TITLE
Sorting not using index

### ISSUE THREAD

**Issue by kovalcikm** [hazelcast/hazelcast#15559]
Hello.

In our application we have to use "BINARY" as in memory format. Using "ValueExtractor" I was able to set all the indexes needed in our application. When searching using "PagingPredicate" everything works very good and the performance is OK.

The problem is sorting. Paging predicate expects "Comparator". If in the comparator method "Entry.getValue()" is called the value has to be deserialized and the performance is very poor.
I believe there should be some possibility to use indexes when sorting?

Regards,
Milos.

**Comment by Paranoia1988** [comment]
I agree with Milos, I have the same problem. Is there a possibility to use indexes while sorting?

Thanks!
Martin

**Comment by Gerrygames** [comment]
Yes I agree. This is a very important feature in my opinion. We have a dataset with currently 32k entries. The database can run a query for getting the first 50 (ordered) entries in 150ms. Running the same query with a page size of only 10 on Hazelcast takes over 5s.
Also being able to create a QueryCache for PagingPredicates would be nice.

**Comment by mmedenjak** [comment]
Hi all, we are currently working on redesigning the query engine. This, and many more, will come in one of the following minor versions.

**Comment by kovalcikm** [comment]
Any news?

**Comment by mmedenjak** [comment]
The initial version of the new query engine is about to be released next week. We'll have more information on what is and what is not possible soon. Sorting isn't possible, unless you're using a sorted index I guess. That should come in 4.2.

**Comment by Holmistr** [comment]
Hey all, we will be introducing the `ORDER BY` capabilities in the 4.2 that is coming out in the middle of March. The query engine will be able to use indexes for sorting (it will actually be required).

**Comment by Holmistr** [comment]
I'm closing this issue as the support for sorting using indexes (as mentioned above) is already merged in the master and will definitely be released.
You can actually try it already with the 4.2-BETA-1 release! https://hazelcast.org/imdg/download/#hazelcast-imdg-beta

**Comment by mmedenjak** [comment]
BTW the sorting on index is part of the SQL engine, not the predicate API.

**Comment by bicabone** [comment]
@Holmistr Do we have to use sql dialect to leverage a sorted indexConfig on a map?

**Comment by Holmistr** [comment]
Hi @bicabone , I no longer work at Hazelcast, so I'm not confident to say 100% sure. @vbekiaris @frant-hartm Could you please check this one? :)
