### ISSUE TITLE
Fix public/private API for EvictionPolicyComparator and CacheEvictionPolicyComparator

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15614]
From a discussion with @vbekiaris :
> internal class com.hazelcast.internal.eviction.EvictionPolicyComparator is used in very public class com.hazelcast.config.EvictionConfig but its subclass com.hazelcast.cache.CacheEvictionPolicyComparator is in public package and not used anywhere in production classes… my guess is that since a user should be able to supply its own EvictionPolicyComparator implementation, even EvictionPolicyComparator should be actually moved to a public package (and CacheEvictionPolicyComparator is probably a template class for a cache-specific eviction policy comparator? but I need to look closer tomorrow morning)

**Comment by ahmetmircik** [comment]
this will be handled in https://github.com/hazelcast/hazelcast/pull/15939
