### ISSUE TITLE
Client in status CLIENT_DISCONNECTED will never receive cluster member attributes changes

### ISSUE THREAD

**Issue by heliheli** [hazelcast/hazelcast#15623]
If client connected to cluster with 2 nodes, and owner node shutdowns, if other node set some attribute (for example setBooleanAttribute), client will never receive this information.

Scenario:
1. client connects to cluster with 2 nodes, node_1 and node_2
2. node_1 is owner member for client
3. node_1 shutdowns
4. client changes status to CLIENT_DISCONNECTED
5. node_2 calls getCluster().getLocalMember().setBooleanAttribute
6. client changes status to CLIENT_CONNECTED with owner member node_2
7. client knows nothing about setBooleanAttribute

Is this behavior correct? If yes, how can i reinitialize member attributes on client after reconnect?

Test case:
```java
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.stream.Collectors;

public class HazelcastMemberAttributeTest {

	private static final Logger LOGGER = LoggerFactory.getLogger(
			HazelcastMemberAttributeTest.class);

	@Test(timeout = 40000)
	public void testMemberAttribute() {
		final Config config = new Config();
		config.getGroupConfig().setName("dev");
		config.getNetworkConfig().setPort(12703);
		config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
		config.getNetworkConfig().getJoin().getTcpIpConfig()
				.setEnabled(true)
				.addMember("127.0.0.1:12703")
				.addMember("127.0.0.1:12704");

		final HazelcastInstance server1 = Hazelcast.newHazelcastInstance(config);
		server1.getCluster().getLocalMember().setBooleanAttribute("READY", false);

		config.getNetworkConfig().setPort(12704);
		final HazelcastInstance server2 = Hazelcast.newHazelcastInstance(config);
		server2.getCluster().getLocalMember().setBooleanAttribute("READY", false);

		final ClientConfig clientConfig = new ClientConfig();
		clientConfig.getProperties().setProperty("hazelcast.logging.type", "slf4j");

		// '127.0.0.1:12703' is always owner member
		clientConfig.getProperties().setProperty("hazelcast.client.shuffle.member.list", "false");

		clientConfig.getNetworkConfig().addAddress("127.0.0.1:12703", "127.0.0.1:12704");
		final HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);

		LOGGER.info("member ready: {}", client.getCluster().getMembers().stream()
				.map(m -> m.getAddress().toString() + "=" + m.getBooleanAttribute("READY"))
				.collect(Collectors.joining(", ")));

		server1.getCluster().getLocalMember().setBooleanAttribute("READY", true);

		while (true) {
			if (client.getCluster().getMembers().stream().anyMatch(m -> m.getBooleanAttribute("READY"))) {
				break;
			}
		}

		LOGGER.info("member ready: {}", client.getCluster().getMembers().stream()
				.map(m -> m.getAddress().toString() + "=" + m.getBooleanAttribute("READY"))
				.collect(Collectors.joining(", ")));

		server1.getCluster().getLocalMember().setBooleanAttribute("READY", false);
		server1.shutdown();

		// Client will never receive this attribute
		server2.getCluster().getLocalMember().setBooleanAttribute("READY", true);

		while (true) {
			if (client.getCluster().getMembers().stream().anyMatch(m -> m.getBooleanAttribute("READY"))) {
				break;
			}
		}

		LOGGER.info("member ready: {}", client.getCluster().getMembers().stream()
				.map(m -> m.getAddress().toString() + "=" + m.getBooleanAttribute("READY"))
				.collect(Collectors.joining(", ")));

		server2.shutdown();
	}

}
```

Hazelcast: 3.12.1 (same behavior in 3.12.2, and in older versions, like 3.8, 3.9, 3.10)

**Comment by sancar** [comment]
Hi @heliheli 
Event misses are expected during connection problems. We don't have any mechanism to mitigate that for most of the events in hazelcast. There are exceptions like ReliableTopic that will deliver the event even after connection problems. 

I tried your code on 4.0-SNAPSHOT and 3.12.5. In 4.0 SNAPSHOT, even though event is lost, the attributes are updated eventually. So your test passes in current master. 

In 3.12.5, even the attribute is not updated eventually. I will check if backport possible and post the result here.

**Comment by sancar** [comment]
Hi @heliheli , 
After a long discussion, we have decided to remove the support for changing attributes after member restarted in 4.0. 
1. It is a replication problem that is needed to be solved for a use case that is rarely used. 
2. There are better alternatives that you can use for similar use-cases. You can use  map / Multimap with listeners and member-uuid associated keys. Or ReliableTopic with associated messages. 

Sorry to share this but since solution is too complicated we are not doing a backport fix. 
Please try alternative data structures for your use case. And if they can not solve your problem, please share it with us. 
Closing the issue for now.
