### ISSUE TITLE
/hazelcast/rest/cluster HTTP endpoint returns HTTP 500 status

### ISSUE THREAD

**Issue by emre-aydin** [hazelcast/hazelcast#15635]
This is on `maintenance-3.x` branch.

When advanced network config is enabled but no client endpoint config is specified, sending an HTTP request to `/hazelcast/rest/cluster` endpoint fails with a status code of 500. It's caused by a NPE on https://github.com/hazelcast/hazelcast/blob/c513873301d9d5b6222fe4177c2066901452495c/hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpGetCommandProcessor.java#L357.

Following config causes the issue:

```
config.getAdvancedNetworkConfig()
                .setEnabled(true)
                .setMemberEndpointConfig(new ServerSocketEndpointConfig().setPort(5701))
                .setRestEndpointConfig(new RestServerEndpointConfig()
                        .setPort(5702)
                        .enableAllGroups());
```

And this one has no issues:

```
config.getAdvancedNetworkConfig()
                .setEnabled(true)
                .setMemberEndpointConfig(new ServerSocketEndpointConfig().setPort(5701))
                .setClientEndpointConfig(new ServerSocketEndpointConfig().setPort(5703))
                .setRestEndpointConfig(new RestServerEndpointConfig()
                        .setPort(5702)
                        .enableAllGroups());
```

**Comment by vbekiaris** [comment]
Fixed by #16150
