### ISSUE TITLE
Questions about cluster consolidation

### ISSUE THREAD

**Issue by a544793138** [hazelcast/hazelcast#15793]
When I read the Hazelcast IMDG 3.12.3 Reference Manual, I was puzzled by [28.4 Split-Brain Recovery](https://docs.hazelcast.org/docs/latest/manual/html-single/#split-brain-recovery).
According to my understanding, this paragraph means this:
1. The partitioned cluster will be merged first, and then the data conflicts generated by the merged cluster will be handled according to Merge Policies.
2. There is only one fixed cluster consolidation rule. Usually small clusters are merged into large clusters. If the number of members in the cluster is equal, a Hash algorithm determines the direction of the merge.
3. For the sake of understanding and description, it is assumed that there are two clusters A and B. A has more members than B. A, B Two clusters have been partitioned, and now they will be merged. According to the above understanding, B should be merged into A.
Then the original text in the document:
"After the merging side is decided, the master member (the eldest one) of the merging side initiates the cluster merge process by sending merge instructions to the members in its cluster."
Now I have this understanding of the above sentence:
When it is determined that B needs to be merged into A, the master member in B will direct other members of B to initiate the merge process.

Is my understanding correct? If not, what is it like?
If my understanding is correct, can you provide information about the Hash algorithm that determines the direction of cluster consolidation? At least tell me where I can see the code.

Thank you

**Comment by mmedenjak** [comment]
Hi @a544793138 !

Yes, you're right. Each cluster has a single master member which is responsible for maintaining membership lists, initating migrations and other tasks. Once another cluster has been detected and the merging side is decided, the master of the smaller cluster (or generally speaking, the "merging side" cluster) will send instructions to each of its' members to disjoin and start merging into the other side.

You can find the logic for determining the sides [here](https://github.com/hazelcast/hazelcast/blob/572c7485fbe9560c9032f75ee7730c8ef9826184/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java#L772-L828) and if you clone the hazelcast repo you can try running the `com.hazelcast.map.merge.MapSplitBrainTest` test to see it in action.
