### ISSUE TITLE
Code samples failures for 4.0

### ISSUE THREAD

**Issue by tezc** [hazelcast/hazelcast#15790]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-code-samples-OracleJDK10/264/consoleFull

After 4.0 PRs, code samples are broken. Looks like there are broken tests related with  client(@sancar) / completable future (@vbekiaris ) / security(@kwart) etc.. (probably even more).

Client and completable future related issues look simple to fix but I've no idea about security related ones. @kwart Could you take a look at that?

**Comment by kwart** [comment]
I'm looking into the security-related samples now.

**Comment by mmedenjak** [comment]
@tezc there were some PRs merged to fix the code samples. Are they still broken?

**Comment by tezc** [comment]
It's fixed, forgot to close this issue.
