### ISSUE TITLE
Set ItemListener do not receive update item either with dedicated parameter

### ISSUE THREAD

**Issue by agagliardi** [hazelcast/hazelcast#158]
With version 2.1, a simple HelloWorld code to eval distributed Set (**Map works well**)

```
    set.addItemListener(new ItemListener<Object>()
    {...
        public void itemAdded(ItemEvent<Object> item)
        {
            System.out.println("itemAdded=" + item.getItem() + "-" + set.size());
            for (Object object : set)
            {
                System.out.println(object);
            }
        }
    }, true);
```

Output:
- itemAdded=null-3
- item1
- item2
- item3

**Comment by gurungjulian** [comment]
I'm having an issue where I have a server node starts my item listener. I then start a client node and put an object in the queue from the client. It does not seem to be picked up by the item listener in my Server straight away for some reason. Any ideas?
