### ISSUE TITLE
Query ignores index but processes successfully

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#15808]
See https://github.com/hazelcast/hazelcast/issues/15806 https://github.com/hazelcast/hazelcast/issues/15807

If index correctly defined as
```
<index ordered="false">__key#hello</index>
```

This `__key#hello = 'world'` uses the index, index stats confirm.
This `__key.hello = 'world'` doesn't use the index, index stats confirm.

Both return same value. Ie the latter form with the dot rather than the hash is inconsistently handled.

Tested on 3.12.3

**Comment by taburet** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/15817
