### ISSUE TITLE
bin/start.sh only allows one process

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#15831]
Try starting two hazelcast instances using the `./bin/start.sh script. ` 

Because there is only very basic PID management it fails and asks the user to create another copy of the bin directory.  **This is poor user experience**.

I've tested other distributions from Redis and Kafka.  They provide more advanced PID management that allows running multiple processes.

Allow start.sh to run more processes without the need to copy the bin directory.  In hand with this the `/bin/stop.sh` script should take a PID.

**Comment by pveentjer** [comment]
Will this not cause issues with e.g. logging? So having 2 or more Hazelcast processes sharing the logging directory.

**Comment by alparslanavci** [comment]
Fixed by #15934
