### ISSUE TITLE
Provide a way of checking the existence of a key without trying to load it from the backend service

### ISSUE THREAD

**Issue by felipeek** [hazelcast/hazelcast#15856]
Hello,

We are using Hazelcast in an application where we dynamically create multiple maps to store some content that is persisted in some backend. For our application, the idea is that, when the map is initialized, it will be fully filled with backend's content, and after initialization there should be no more read requests to the backend whatsoever - the cache will be up-to-date with the backend. The backend is only accessed again for write-through scenarios.

The problem that we are having is that we are having a really hard time to use Hazelcast `IMap`'s functionalities to be able to check if the map contains a key or not. In our use case, the most crucial requirement that we have from Hazelcast is the ability to know if a certain key is present in the map or not.

We currently implement a `MapStore` for each map that we create and we fill the map using Hazelcast `loadAllKeys` functionality with `EAGER` mode. This works absolutely fine, and we are able to fully fill all maps upon their initialization. The problem, however, appears when we need to access the map to check if it contains a key or not. We tried to do this simply by doing:

```
IMap map = hzClient.getMap(...);
map.containsKey("...");
```

This works fine when the key is contained in the cache, but when it is not in the cache, Hazelcast always calls the `load` function implemented in our `MapStore`. The problem is that we don't see a way of actually telling Hazelcast, inside the `load` function, that the key does not exist. `containsKey` even appears a little silly in this case, since if the key is not found, Hazelcast forces the load and always expect to get some value, so the result would always be `true` in this case?

We tried also using `map.get()`, but it also calls `load` when the key is not found.

Currently, we found 2 workarounds, which would be:

1 - Always use `map.keySet()`, which returns all keys in the map (without calling load), and then iterate over the whole keySet to see if the key exists. This seems like a overkill, and it's not the desired solution
2 - Implement `MapStore` `load` function to always return a custom exception when called. This way, everytime we call `map.containsKey` or `map.get`, we can catch that exception to see that the key is not present. This is possible because since the map is always fully load in the initialization, we just need to implement `loadAllKeys` and `loadAll`. It seems that `load` should not be called ever. But again, not the best solution.

Our maps usually have the format `IMap<String, Boolean>`. In the `load` function, we tried returning `false`, `true` and even `null`. Hazelcast always put the value in the cache and considers that the key exist. So `containsKey` always returns true, unless we throw an exception in the `load` function, then it also throws the exception.

Any suggestions are appreciated. We researched a lot and didn't find any mention to this issue in the docs.
Thanks!

**Comment by gurbuzali** [comment]
from the javadoc on `load` method:
```
@return value of the key; returning {@code null} value signals value missing in the underlying store
```
I've tried returning null in `load` method and `containsKey` returns false.

below is how I've tested:
```
    public static void main(String[] args) throws Exception {
        Config config = new Config();
        MapConfig mapConfig = config.getMapConfig("map");
        MapStoreConfig mapStoreConfig = mapConfig.getMapStoreConfig();
        mapStoreConfig.setEnabled(true)
                      .setImplementation(new MyMapStore())
                      .setInitialLoadMode(MapStoreConfig.InitialLoadMode.EAGER);

        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

        IMap<String, Boolean> map = instance.getMap("map");
        System.out.println(map.containsKey("key"));
    }

    static class MyMapStore implements MapStore<String, Boolean> {

        @Override public void store(String key, Boolean value) {

        }

        @Override public void storeAll(Map<String, Boolean> map) {

        }

        @Override public void delete(String key) {

        }

        @Override public void deleteAll(Collection<String> keys) {

        }

        @Override public Boolean load(String key) {
            return null;
        }

        @Override
        public Map<String, Boolean> loadAll(Collection<String> keys) {
            return null;
        }

        @Override public Iterable<String> loadAllKeys() {
            return null;
        }
    }
```

**Comment by PedroCardouzo** [comment]
@gurbuzali Can you link where you found this doc?
https://docs.hazelcast.org/docs/3.9/javadoc/com/hazelcast/core/MapLoader.html#load-K-
says that return value can not be null

**Comment by gurbuzali** [comment]
I think I've tested against the latest master 
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/MapLoader.java#L79

**Comment by PedroCardouzo** [comment]
Ok this seems to be a recently implemented featue on 3.12 (at least is available there). @gurbuzali sorry, my bad and thanks for your help.

**Comment by gurbuzali** [comment]
btw, I've tested above code snippet with 3.9 and it produced `false` too.

I'll close the issue for now, feel free to re-open it if you encounter any more problems

**Comment by felipeek** [comment]
Thanks @gurbuzali . We think that it would be a lot better if we could configure Hazelcast to not trigger the `load` function when calling `containsKey` and similar functions that shouldn't touch the backend at all. However, your suggested workaround of always returning `null` in the `load` function seems to work fine, and we will go with that approach.

Thanks for your help!

**Comment by PedroCardouzo** [comment]
> btw, I've tested above code snippet with 3.9 and it produced `false` too.
> 
> I'll close the issue for now, feel free to re-open it if you encounter any more problems

Documentation for 3.9 is wrong then as it mentions that it should never return null.

**Comment by Holmistr** [comment]
@JakeSCahill @Serdaro Could you please double check that this has been corrected in the documentation?

Additionally, there's an alternative solution - use `getEntryView(K key).getValue()` which doesn't trigger `load()` functions. @JakeSCahill @Serdaro I would be great to also clearly mention this clearly in the documentation, something like "When do I trigger MapLoader and when do I not?" because it seems to be a rather popular question.
