### ISSUE TITLE
Hazelcast Configuring issue on unix servers

### ISSUE THREAD

**Issue by saindavs** [hazelcast/hazelcast#15886]
Hi,

I am reading the hazelcast documentation and i found that it will run on the JVM using hazelcast jar.

We have 10 unix servers for one of our application, we wanted to use hazelcast as a caching mechanism.
Could you please let me know how to create a hazelcast cluster out of these 10 unix servers?

In other words, we wanted a centralized hazelcast cluster as a backed mechanism.

Regards,
Sudhakar

**Comment by mmedenjak** [comment]
Hi @saindavs !

You can take a look at the [code samples](https://github.com/hazelcast/hazelcast-code-samples)  and the [documentation](https://hazelcast.org/documentation/) for inspiration. 
There is not much that can be said other than that as the details will heavily depend on your use case. I suggest you start running a hazelcast cluster locally, using the basic features like `IMap` and then try deploying into your target environment.

Also, take a look at the reference manual or stop by one of [our community channels](https://hazelcast.org/get-involved/) for further questions.
