### ISSUE TITLE
[Question] Avoid explicitly call the Map.Entry.setValue(V) on EntryProcessor.

### ISSUE THREAD

**Issue by tgodinho** [hazelcast/hazelcast#15901]
Hello guys nice work,

I was looking for a way to avoid calling the `Map.Entry.setValue(V)` on our Entry Processors. Since our `IMap` entries are quite big, the serialization overhead introduced by `setValue(V)` is unacceptable. I was already using the InMemoryFormat.OBJECT hopping to avoid most serializations.

To what extend can my changes to the `Entry` be 'lost'?? Can you provide an example??
I was hopping that I could relax this constraint in our scenario :)

Do you recommend any workaround for this issue??

PS: This processor is really simple, it only add some elements to a `Map` and change one or two attributes per `Entry`. However, this nested map is expected to have >10k entries.

Thnks

**Comment by ahmetmircik** [comment]
Hi, to clarify things, your OBJECT in-memory-formatted map uses indexes. Is this the case?

**Comment by ahmetmircik** [comment]
Which hazelcast version are you using? Normally, there shouldn't be any serialization need, can you please send a simple reproducer?

**Comment by tgodinho** [comment]
We are using Hazelcast 3.8.9.
Humm really, even when the `Map.Entry.setValue(V)` is called??
It is really not that easy to reproduce our environment without all our App logic, but I will try to get the relevant stacktraces.

**Comment by ahmetmircik** [comment]
Please re-open the issue if you still encounter it with the latest versions.
