### ISSUE TITLE
wrong spring config file

### ISSUE THREAD

**Issue by carstenartur** [hazelcast/hazelcast#15924]
There seem to be several mistakes in the file checked in at
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/test/resources/com/hazelcast/spring/fullConfig-applicationContext-hazelcast.xml
eg. the nested tags 

`<hz:cp-subsystem><hz:semaphores><hz:semaphore>`

are invalid. Better is
`<hz:cp-subsystem><hz:semaphores><hz:cp-semaphore>`

Another problem is that the sample contains:

`<hz:semaphores>
                    <hz:semaphore>
                        <hz:name>sem1</hz:name>
                        <hz:jdk-compatible>true</hz:jdk-compatible>
                        <hz:initial-permits>1</hz:initial-permits>
                    </hz:semaphore>
`

Unfortunately using `<hz:initial-permits>` is not allowed at that point.

And then somewhere should clearly stated that you cannot migrate from ilock to fencedlock when you have only 2 cluster nodes because the minimal group size is 3 - or do I get something wrong?

**Comment by vbekiaris** [comment]
> And then somewhere should clearly stated that you cannot migrate from ilock to fencedlock when you have only 2 cluster nodes because the minimal group size is 3 - or do I get something wrong?

In (yet unreleased) 4.0, "unsafe mode" is introduced for CP subsystem; this allows you to still use `IAtomicLong`, `FencedLock` etc without setting up a CP group (and apparently weaker consistency guarantees). You can check the relevant [4.0 migration part](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#removal-of-deprecated-concurrency-api-implementations) and [unsafe mode section](https://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#cp-subsystem-unsafe-mode) in the latest snapshot of the reference manual.

> There seem to be several mistakes in the file checked in at...

Not a spring expert here, but [the test](https://github.com/hazelcast/hazelcast/blob/b117e00b1d0cd97a6a68d6f528908c4a5f785b7e/hazelcast-spring/src/test/java/com/hazelcast/spring/TestFullApplicationContext.java#L188) that sets up the application context based on that file passes in current `master`. Also `initial-permits` look ok as defined in the [XSD](https://github.com/hazelcast/hazelcast/blob/3e3782f86bec3cb959da8794a8e023c3f61724d0/hazelcast-spring/src/main/resources/hazelcast-spring-4.0.xsd#L4675-L4683). Can you elaborate about what kind of errors you get?

**Comment by carstenartur** [comment]
Hm, the sample file is using http://www.hazelcast.com/schema/spring/hazelcast-spring-4.0.xsd and I use  http://www.hazelcast.com/schema/spring/hazelcast-spring-3.12.xsd. So that might be my mistake...

**Comment by carstenartur** [comment]
Ok, I have to check into details but as your unreleased 4.0 seems to be have some incompatible differences this problem is explained now. A short hint in the migration docu would be nice. Thanks!
