### ISSUE TITLE
Throw exception when REST URI does not match any pattern

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#15957]
In `RestApiFilter#getHttpApiEndpointGroup`, we try to find the appropriate `RestEndpointGroup` for the given URI. If no pattern matches, we return `RestEndpointGroup#CLUSTER_WRITE`. It may happen that the URI is in fact a legacy one and should belong to some other group. Such is the case for some WAN URI's:

```
public static final String LEGACY_URI_WAN_SYNC_MAP = "/hazelcast/rest/wan/sync/map";
    public static final String LEGACY_URI_WAN_SYNC_ALL_MAPS = "/hazelcast/rest/wan/sync/allmaps";
    public static final String LEGACY_URI_ADD_WAN_CONFIG = "/hazelcast/rest/wan/addWanConfig";
```

These end up in the `RestEndpointGroup#CLUSTER_WRITE` group.

**Comment by tkountis** [comment]
@mmedenjak do you have a reproducer? We already handle these URIs as `RestEndpointGroup#WAN` https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/nio/ascii/RestApiFilter.java#L82

I am looking into handling the last case with Exception, but not sure yet, it might be more demanding to keep that list up-to-date. On the other hand, at least it will fail and we will know.

**Comment by mmedenjak** [comment]
True, just got this issue from @mtopolnik and @cangencer . Seems the WAN URIs are covered so this isn't an issue after all. But yes, once a new URI pops up, it immediately ends up in the `RestEndpointGroup#CLUSTER_WRITE` group. Maybe we should consider throwing an exception like "no matching group found" instead and have a test which will force devs to add it to a group.

**Comment by mmedenjak** [comment]
@kwart @tkountis WDYT about the change to throw an exception in case no patterns are matched?

**Comment by tkountis** [comment]
I already started playing with that. If its high prio I can unassign myself, otherwise, I can open a PR early next week with an alternative approach (not throwing an exception, just returning null and logging the occurrence).

**Comment by mmedenjak** [comment]
No, it's not high-priority, just wondering if I'm (we're - including Can and Marko) missing something obvious why we can't change the defaults. Carry on :)

**Comment by kwart** [comment]
I don't see any problem in changing the behavior.
