### ISSUE TITLE
Inconsistent EventService registrations after forming cluster

### ISSUE THREAD

**Issue by vojtechtoman** [hazelcast/hazelcast#15950]
Occasionally, after forming a cluster, certain members do not contain `EventService` registrations for some other members. Normally, all members should have the same set of registrations.

After some investigation, I figured out what the problem is:

Suppose there are (at least) three members: `A`, `B`, `C`, joining the cluster in this order. When `B` joins the cluster, the master (`A`) generates the `FinalizeJoinOp` and executes it on `B`. `B` then executes the `preJoin` operations (which, among others, include a snapshot of `A`’s event registrations to be propagated to `B`) and when done, it sends its `postJoin` operations back to the other cluster members (only `A` in this case). The purpose of these operations is, among others, to propagate `B`’s event registrations to the rest of the cluster.

Now, suppose `C` joins the cluster before `B`’s `postJoin` operations reach `A`. In such scenario (which `ClusterJoinManager.startJoin()` is not protected against), `A`’s snapshot of event registrations does not include `B`’s registrations (which include `B` itself) yet, therefore the `preJoin` operations sent to `C` do not contain any mention of `B`. If `C` is the last member to join the cluster, there is no other member that can fix this at a later point (by sending their `postJoin` operation to `C` that would add `B` to the list of event registrations).

It is quite possible that the above problem applies not only to `EventService`, but also to other `PreJoinAwareService`/`PostJoinAwareService` services.

I encountered this while working on an unrelated issue on 3.12.x. It (occasionally) occurs in Hot Restart tests where we start all members at once, in parallel. In many real situations, I believe the issue is quite unlikely to occur.

**Comment by vojtechtoman** [comment]
Reproducer (run this repeatedly until the final `assertEventRegistrations()` fails - it takes about 10 runs on my machine):

```
package com.hazelcast.spi.hotrestart.cluster;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.instance.Node;
import com.hazelcast.nio.Address;
import com.hazelcast.spi.EventRegistration;
import com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl;
import com.hazelcast.test.AssertTask;
import com.hazelcast.test.HazelcastSerialClassRunner;
import com.hazelcast.test.annotation.ParallelTest;
import com.hazelcast.test.annotation.QuickTest;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.runner.RunWith;

import java.util.Collection;

import static com.hazelcast.cluster.ClusterShutdownTest.assertNodesShutDownEventually;
import static com.hazelcast.cluster.ClusterShutdownTest.getNodes;
import static org.junit.Assert.assertEquals;

@RunWith(HazelcastSerialClassRunner.class)
@Category({QuickTest.class, ParallelTest.class})
public class HotRestartEventServiceTest extends AbstractHotRestartClusterStartTest {

    @Test
    public void test_eventRegistrations_afterHotRestart() {
        HazelcastInstance[] instances = startNewInstances(3);
        instances[0].getMap("map0").put("foo", "bar");

        Address[] addresses = getAddresses(instances);
        Node[] nodes = getNodes(instances);
        instances[0].getCluster().shutdown();
        assertNodesShutDownEventually(nodes);

        assertEventRegistrations(3, restartInstances(addresses));
    }

    private static void assertEventRegistrations(final int expected, final HazelcastInstance... instances) {
        assertTrueEventually(new AssertTask() {
            @Override
            public void run() {
                for (HazelcastInstance instance : instances) {
                    Collection<EventRegistration> regs = getNodeEngineImpl(instance).getEventService().getRegistrations(
                            ProxyServiceImpl.SERVICE_NAME, ProxyServiceImpl.SERVICE_NAME);
                    assertEquals(instance + ": " + regs, expected, regs.size());
                }
            }
        });
    }
}
```

**Comment by silvaran** [comment]
Is it possible this is related to https://github.com/hazelcast/hazelcast/issues/14060 ?

**Comment by mmedenjak** [comment]
@silvaran might be but I'm not quite sure. This issue manifests itself if multiple members are started at roughly the same time whereas you don't mention this in your issue. Regardless, I've added your issue to the current milestone and I'll try to get someone to take a closer look.

**Comment by silvaran** [comment]
@mmedenjak There's definitely a multi-node startup involved.  In fact, my workflow at the time involved issuing a reload to a domain-controlled Wildfly, which is going to stop/start everything at roughly the same time.

**Comment by mmedenjak** [comment]
That's good news then actually because it means you can try upgrading to 4.0 or 3.12.5 where the issue has been fixed.
