### ISSUE TITLE
Surprising null default for NetworkConfig#restApiConfig

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#15968]
Unlike other Hazelcast configuration classes, the default value of `NetworkConfig#restApiConfig` is `null`, so this code throws `NullPointerException`:

```
Config config = new Config();
config.getNetworkConfig().getRestApiConfig().setEnabled(true);
```

**Comment by mmedenjak** [comment]
Closing as fixed since PR was merged.
