### ISSUE TITLE
Is Hazelcast management center jar available for use?

### ISSUE THREAD

**Issue by anki2189** [hazelcast/hazelcast#16092]
War file for hazelcast management center is available for use , it can be downloaded from https://hazelcast.org/download/ . I am not to find jar file for  hazelcast management center, is it available for use?

**Comment by mmedenjak** [comment]
Hi @anki2189 !

I don't think there is a JAR, maybe @emre-aydin  does. You can always package our WAR with your own application server and create a JAR yourself as we don't provide an application server. Maybe something like this - https://stackoverflow.com/questions/41447442/how-to-convert-a-spring-application-war-to-stand-alone-jar

**Comment by emre-aydin** [comment]
@anki2189 we don't have a JAR available but the WAR file of MC is executable via `java -jar ...` and includes an embedded Jetty instance. It's easy to build one as @mmedenjak pointed out. I had done one quite some time ago for another user, you can use it as an example to build your own: https://github.com/emre-aydin/mcStarter
