### ISSUE TITLE
Possible memory leak with IMap.loadAll(true)

### ISSUE THREAD

**Issue by jaspal28** [hazelcast/hazelcast#16096]
We are keeping some data in hazelcast grid. For that we are using IMap. 
Total records 48K (approx). Total size for 48K records is not more than 600MB.
After every 5 - 15 mins, we need to refresh this Map. For that we are using loadAll(true). 
We see that there is a continue increase of heap memory usage. 
We profiled the GC (garbage colelctor) using different parameters but no help.
Then we used IMap.clear and IMap.loadAll(false). After this, the heap memory usage is near about consistent.
So, it seems that there is a memory leak when using IMap.loadAll(true).
Or we might be missing some hazelcast configuration. 
We are using hazelcast version 3.10.4. We also tested same scenario on 3.12.4. Facing same issue.
Can you please suggest us what wrong we are doing?

**Comment by ahmetmircik** [comment]
Hi @jaspal28, is it possible to share a reproducer?

**Comment by jaspal28** [comment]
Actually, We are not able to share the exact code as it is part of our application. 
We tested with backup count 0, single node, near by cache having eviction policy LRU. 
Not defined any eviction policy for Map.  
Please let us know if any other configuration value do you need.

We created a test program to simulate the scenario:
1) HazelcastTestWithClearLoadAll.java : Clear the map before loading
2) HazelcastTestWithLoadAll.java : loadAll

Please go through the below gist for the code:
https://gist.github.com/jaspal28/c0367faba5a7b30acec0144c4208d211

  This test program is calling loadAll after every 1 second. You can change this time.  With loadAll, no gargabe collection is happening. 
With clear and loadAll, garbage collection is happening properly.

JVM arguments used to run this test code:
-Xms1G -Xmx1G -XX:+UseG1GC  -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:tvs-gc.log

**Comment by ahmetmircik** [comment]
Hi again @jaspal28,
Thanks for the reproducer, i ran it. We have a memory leak there. 
And it manifests itself, if you call `loadAll` multiple times.
This leak should exist in all versions starting back from 3.10 to current version 4.0 (even though i haven't tested with all).

__Workaround:__
If you also call another map method after `loadAll`, which touches all partitions of map, the leak disappears. So in your reproducer, calling `cache.size()` after `loadAll` fixes the issue.

__Fix for the reproducer(see comment below):__
```
@Override
        public Set<StoreKey> loadAllKeys() {
            System.out.println("SimpleStore - loading all keys");
            Calendar cal = Calendar.getInstance();
            cal.clear(); <-- Added this line, otherwise each loading loop loads different keys.

```

**Comment by jaspal28** [comment]
Hi @ahmetmircik ,
Thanks for looking into this issue. 
My understanding : call any IMap method after loadall(true) to resolve the memory leak issue like size() method or keys(). We will test this with main application.

In reproducer, we just used Calendar.getInstance to create unique keys. In our main application, we are not using this. All data is from database.

Any idea in which coming version we will get fix for this issue.

**Comment by ahmetmircik** [comment]
>My understanding : call any IMap method after loadall(true) to resolve the memory leak issue like size() method or keyset(). We will test this with main application.

With any operation that runs in all partitions like clear, size, evictAll. keyset may not be one of them when it gets keys from indexes.


>Any idea in which coming version we will get fix for this issue.

Target release, which may include fix, is 4.0. We will also try to backport it to next 3.12.

**Comment by jaspal28** [comment]
Hi @ahmetmircik,
 We called size() method after loadAll(true) in our application and seems that it is working fine. Heap size usage seems fine. Initially heap size is growing and its coming back to normal.
_Thanks for providing work around for the time being._

Do you see any issue if we go by : clear() and then loadAll(false)?
A case may happen where system may initiate some get request immediately after clear() and before loadAll(false) or loadAll(false) is not fully done. 
In this case, no data found in hazelcast Map. So, system will load it for the request key and put it in Map.

**Comment by ahmetmircik** [comment]
>Do you see any issue if we go by : clear() and then loadAll(false)?

If it fits your use case it is ok i think. Only thing i can say, since clear() deletes cached keys from map-store before memory, evictAll can be a better and safer alternative. Just in case you may want to implement MapStore#deleteAll one day.
