### ISSUE TITLE
Composite index programatically

### ISSUE THREAD

**Issue by alenbec** [hazelcast/hazelcast#16103]
Hi guys,

I'm struggling to find any examples of how to create composite indexes programatically. Can this be done and if yes, how? Documentation only shows how to do it in xml...

Are composite indexes used automatically? Also is there any way we can know if index has been used or not by predicate?

Thanks,
Alen

**Comment by alenbec** [comment]
Thanks @taburet for taking your time and answering in detail, appreciate it!

Regarding possibility of "lost" indexes if cluster is fully restarted. We are not using hazelcast as standalone product. Instead we have it embeded into our service which also configures hazelcast (indexes, mapstores and other configs) at startup so configuration won't be lost after restart.

**Comment by Holmistr** [comment]
Hi @alenbec , just checking, was your question answered? Would you have something else to continue with? :)

**Comment by alenbec** [comment]
Hi @Holmistr, everything answered, thanx for asking!
