### ISSUE TITLE
Test failure ClientRegressionWithRealNetworkTest

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#16126]
Stacktrace
```
java.lang.AssertionError: Values should be different. Actual: 0
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testListenersAfterClientDisconnected(ClientRegressionWithRealNetworkTest.java:219)
	at com.hazelcast.client.ClientRegressionWithRealNetworkTest.testListenersAfterClientDisconnected_memberHostname_clientHostname(ClientRegressionWithRealNetworkTest.java:174)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4715/testReport/junit/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberHostname_clientHostname/

**Comment by tezc** [comment]
http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK11/58/testReport/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberHostname_clientHostname/

**Comment by sancar** [comment]
Another failure here 
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4828/testReport/junit/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberIp_clientIp/

**Comment by vojtechtoman** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5156/testReport/junit/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberHostname_clientIp/

**Comment by lazerion** [comment]
It seems continue to fail for `testListenersAfterClientDisconnected_memberIp_clientIp` on `Hazelcast-3.x-ZingJDK8` in [this job](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/lastCompletedBuild/testReport/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberIp_clientIp/)
kindly check

**Comment by metanet** [comment]
the failed build is this one => http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/125/testReport/junit/com.hazelcast.client/ClientRegressionWithRealNetworkTest/testListenersAfterClientDisconnected_memberIp_clientIp/
