### ISSUE TITLE
Does TTL expiration from IMap will trigger StoreAll in case of Write-Behind 

### ISSUE THREAD

**Issue by anirbanroy1983** [hazelcast/hazelcast#16120]
We would like to know in case of TTL expiration whether hazecast make sure object still be persisted in store in case DB is taking more time to commit than TTL value ?

**Comment by ahmetmircik** [comment]
Hi @anirbanroy1983,
 
Yes it should persist regardless of the DB time. Please also try it yourself and write here if you find any issue.

Now i'm closing this issue.

**Comment by anirbanroy1983** [comment]
@ahmetmircik  Thanks for your confirmation , have tried in local env and yes expire TTL entry is going to write behind queue and retrying to persist in DB again and again.
