### ISSUE TITLE
hz_client shutdown after an OOM 

### ISSUE THREAD

**Issue by lishijun121910** [hazelcast/hazelcast#16185]
**V3.12
Using a server-client topology**

**hazelcast-node suffered from an OOM,  client get a message and shutdown:**

`|2019-12-05T15:48:29.717+0800|INFO|pool-2-thread-4|49|c.h.c.c.nio.ClientConnection:hz.client_0 [hazelcast-server] [3.12] ClientConnection{alive=false, connectionId=2, channel=NioChannel{/10.11.117.34:40854->/10.11.117.38:5701}, remoteEndpoint=[10.11.117.38]:5701, lastReadTime=2019-12-05 15:48:29.714, lastWriteTime=2019-12-05 15:48:03.859, closedTime=2019-12-05 15:48:29.715, connected server version=3.12} closed. Reason: Hazelcast client is shutting down
`
**Restart the hazelcast, and client continuous get this:**

```
|2019-12-05T16:13:05.039+0800|INFO|hz.client_0.cluster-|49|c.h.c.c.nio.ClusterConnectorService:hz.client_0 [hazelcast-server] [3.12] Trying to connect to [10.11.117.39]:5701 as owner member
|2019-12-05T16:13:05.039+0800|WARN|hz.client_0.cluster-|49|c.h.c.c.nio.ClusterConnectorService:hz.client_0 [hazelcast-server] [3.12] Exception during initial connection to [10.11.117.39]:5701: com.hazelcast.client.HazelcastClientNotActiveException: ConnectionManager is not active!
|2019-12-05T16:13:05.039+0800|WARN|hz.client_0.cluster-|49|c.h.c.c.nio.ClusterConnectorService:hz.client_0 [hazelcast-server] [3.12] Unable to get live cluster connection, retry in 1000 ms, attempt 1301 of 2147483647.
```

so is this a defect? how can hz_client recover from an OOM of hazelcast-server.

**Comment by sancar** [comment]
`Hazelcast client is shutting down`
A shutdown client will not recover. If you want to keep using client for a long time, you need to change its shutdown behaviour.  You can set attempt-limit and attempt-period big enough not to shutdown immediately when cluster experience a problem(cluster restart, heartbeat problems, OOME etc)
See following doc for configuration details:
https://docs.hazelcast.org/docs/3.12.7/manual/html-single/index.html#configuring-client-connection-retry

**Comment by sancar** [comment]
@lishijun121910 Closing this issue. Feel free to reopen or ask on the hazelcast mailing list if you still have problems. https://groups.google.com/forum/#!forum/hazelcast
