### ISSUE TITLE
Config file should support ".yml" as a default extension as well as ".yaml"

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#16205]
Default config location will find `hazelcast.yaml` and `hazelcast.xml` on the classpath but not `hazelcast.yml`.

Same for client `hazelcast-client.yaml` and `hazelcast-client.xml` but not `hazelcast-client.yml`

".yaml" and ".yml" are commonly used, so both should be supported

**Comment by neilstevenson** [comment]
Vaguely related https://github.com/hazelcast/hazelcast/issues/14924

**Comment by mmedenjak** [comment]
We'll consider this an enhancement. Moving into 4.1 as it's not a 4.0 blocker. cc @blazember

**Comment by neilstevenson** [comment]
See https://github.com/hazelcast/hazelcast/pull/16377
