### ISSUE TITLE
Add support for addMigrationListener on client

### ISSUE THREAD

**Issue by oobles** [hazelcast/hazelcast#16260]
Feature request: add support on the client for addMigrationListener.

In some cases, it is useful for a client to be informed of migration events.  This can be used to pause processing or stop sending new data to the server while changes are occurring.  Currently calling instance.getPartitionService().addMigrationListener on the client throws an UnsupportedOperationException.

**Comment by peterjot** [comment]
Could I take that issue? @mmedenjak  @Holmistr

**Comment by mmedenjak** [comment]
Sure, as far as I'm concerned. Since I'm not familiar with the client architecture too much, I'd prefer if @sancar is able to provide some initial pointers.

**Comment by Holmistr** [comment]
@peterjot From my side absolutely as well :) But @sancar is the expert in this area, we will need his involvment for this one :) @sancar Could you provide guidelines on how to approach this? I guess it's not that easy one.

**Comment by sancar** [comment]
Hi @peterjot. You can use `addPartitionLostListener` as an example of how to implement this. It should be almost the same. 

You are gonna need to generate codes for the client-side. 
see `ClientAddPartitionLostListenerCodec` and `ClientRemovePartitionLostListenerCodec` 
You need to add related codec definitions to the following repo. 
https://github.com/hazelcast/hazelcast-client-protocol 
There is a ReadMe on this repo that explains how to use it. 
You can see here how it is implemented for addPartitionLostListener and removePartitionLostListener See https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/Client.yaml#L344 
and https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/Client.yaml#L390

For server-side implementation see `AddPartitionLostListenerMessageTask` . You will need to implement a similar task as `AddMigrationListenerMessageTask`. 

If you got stuck at any point I can help you.

**Comment by peterjot** [comment]
Hi @sancar, thanks for the tips. I added the migration tasks you mentioned and added two events to the protocol: https://github.com/hazelcast/hazelcast-client-protocol/pull/356 and core: https://github.com/hazelcast/hazelcast/pull/17713 Would be great if you could have a look at that
