### ISSUE TITLE
Remove metrics-only MBeans

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#16265]
There are MBeans that only exist show metrics. Since all metrics are exposed over JMX by default, these MBeans are not needed anymore. Examples for these MBeans are OperationServiceMBean, NetworkingServiceMBean, EventMBean. The concrete list should be checked by enabling JMX for the member and compare the MBeans and the MetricsMBean.

The data structure metrics expose the configuration and typically have some operations too, therefore, all data structure MBeans should be kept and no attributes should be removed from these MBeans, despite the overlapping between metrics and the MBean attributes. The reason is to stay consistent with the DS MBeans.

Also, whether or not to create the MetricsMBean should respect both the MetricsConfiguration and the JMX system property. Currently, the MetricsMBean is created if enabled in the configuration (it is enabled by default), which is out of sync with the logic followed with the creation of the other MBeans.

**Comment by jerrinot** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/16425
