### ISSUE TITLE
Enforce stability of Metric names

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#16266]
Metric names are currently coming from inline strings and field names annotated with `@Probe` annotations. Since Management Center will depend on the names and that the metrics are exposed over JMX, their name should be ensured to be stable. To guarantee the stability the following needs to be done:
- Make the `name` mandatory on the `@Probe` annotation.
- Check with the MC team if any metric needs to be renamed.
- Create a constant class(es) for hosting the metric, prefix, discriminator names (see `MetricDescriptor`). Using enums instead of string constants would be an even stronger guarantee for stability. This, however, would come with changing the `MetricDescriptor` interface and implies changes in Jet too. The cost of this change should be assessed. Note that the Metrics API is an internal API. 
- Mention in the reference manual that the metric names are guaranteed to be stable between patch releases and might change only in minor releases (see the Jet manual for reference).

**Comment by mmedenjak** [comment]
Closing as fixed, reopen if this is not true :)
