### ISSUE TITLE
`mvn install` leaves test files behind on 4.0-SNAPSHOT

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#16284]
On OSX 10.15.2, Java 1.8.0_232, `mvn install` leaves behind two diagnostic files and a password file

```% ls hazelcast/dia* hazelcast/pass*
hazelcast/diagnostics-127.0.0.1_5701-1576616233213-000.log
hazelcast/diagnostics-127.0.0.1_5701-1576616233214-000.log
hazelcast/password.txt
```

The password file isn't ignore by .gitignore, the diagnostic files are. However, for cleanliness, none should be present.

**Comment by neilstevenson** [comment]
This was a clean build, ```[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hazelcast Root 4.0-SNAPSHOT:
[INFO] 
[INFO] Hazelcast Root ..................................... SUCCESS [  1.392 s]
[INFO] hazelcast .......................................... SUCCESS [  02:22 h]
[INFO] hazelcast-spring ................................... SUCCESS [01:05 min]
[INFO] hazelcast-build-utils .............................. SUCCESS [  4.816 s]
[INFO] hazelcast-all ...................................... SUCCESS [  4.233 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------```

**Comment by mmedenjak** [comment]
The password file might be created by `XmlYamlConfigBuilderEqualsTest#testFullExample`

**Comment by neilstevenson** [comment]
```
mvn -Dtest=com.hazelcast.internal.diagnostics.MetricsPluginTest test
```
is responsible for one of the files. Still leaves one to track down.

**Comment by JackPGreen** [comment]
I can reproduce `hazelcast/password.txt` with a `mvn install`

**Comment by JackPGreen** [comment]
Re-opened awaiting fix for https://github.com/hazelcast/hazelcast/pull/25537
