### ISSUE TITLE
Spring Boot + Hazelcast Client Config with setInstance Name Problem

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#16313]
**Reproducer**
```
$ git clone https://github.com/mesutcelik/gs-rest-service
$ cd complete
$ mvn spring-boot:run
```

The reason it fails is because [HazelcastClient.getHazelcastClientByName(this.clientConfig.getInstanceName())](https://github.com/spring-projects/spring-boot/blob/aef92b9295f62d008faa9ab79905a474bf3496f3/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/hazelcast/HazelcastClientFactory.java#L75) returns `null` with the following config.

```
ClientConfig clientConfig = new ClientConfig();
clientConfig.setInstanceName("Istanbul");
return clientConfig;
```

Do we have getOrCreate like method for Client?

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/16363
