### ISSUE TITLE
how does it work hazelcast.client.statistics.enabled flag ?

### ISSUE THREAD

**Issue by pkgonan** [hazelcast/hazelcast#16369]
HI,

[In Client]
- hazelcast.client.statistics.enabled = true   ==> Statistics.java's scheduler send statistics to cluster server.

[In Server]
- What Class file is receive client message at server?
- How does it work in a cluster using statistics message which is client sended ?

Thank you :)

**Comment by sancar** [comment]
Hi @pkgonan 
ClientStatisticsMessageTask is the receiver on the server. 
The informations is mainly used by `ManagementCenterService` . It is job to send the information to the Management Center 
See https://docs.hazelcast.org/docs/management-center/3.12.8/manual/html/index.html#monitoring-clients

**Comment by pkgonan** [comment]
Thank you @sancar :)
