### ISSUE TITLE
Make it easier to create SpringManagedContext programmatically

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#16400]
If one wants to set up a `SpringManagedContext` programmatically, they have to create an instance with the default constructor and then call a setter. That's not a great arrangement IMO and the following would be much easier:

```java
// Config config = ...
config.setManagedContext(new SpringManagedContext(applicationContext));
```

See also https://github.com/spring-projects/spring-boot/issues/19487

**Comment by mmedenjak** [comment]
@snicoll thank you for the report! Does this PR provide what you would expect? https://github.com/hazelcast/hazelcast/pull/16386

**Comment by snicoll** [comment]
Thanks for the feedback. No, it does not. Did you reference the wrong PR maybe?

**Comment by mmedenjak** [comment]
Ah, ok, now I see the difference. The additional constructor should be simple enough to add.

**Comment by mmedenjak** [comment]
@snicoll created https://github.com/hazelcast/hazelcast/pull/16401
