### ISSUE TITLE
Issue with two hazelcast clusters on single JVM

### ISSUE THREAD

**Issue by coded9** [hazelcast/hazelcast#16432]
We have a scenario,where we are creating two hazelcast instances from two different config files.While the first instance creates a cluster with all the members given under tcp-ip config,but the second instance creates cluster only with the current node from which this hazelcast instance was started.
```
//First instance creation,the config is read from hazelcast.config,which is set to path of config1.xml
instance = Hazelcast.newHazelcastInstance();

//Second instance creation,reads config2 file 
config = new FileSystemXmlConfig(hazelCastPath);
instance = Hazelcast.newHazelcastInstance(config);
```
//First instance cluster
![image](https://user-images.githubusercontent.com/9302330/71954552-b0c5bf00-320b-11ea-91fc-6ef9c8b16ab4.png)
//Second instance cluster
![image](https://user-images.githubusercontent.com/9302330/71954583-c935d980-320b-11ea-80a7-10d9f9706ae8.png)
```
HazelCast Jar version: 3.11.4
Java 8
OS:Cent OS 7
Server : Apache Tomcat
```
Attached zip file with config files
[configs.zip](https://github.com/hazelcast/hazelcast/files/4033773/configs.zip)

I have configured these in a single JVM,one cluster starts fine,but the other has issues.

Am I missing something or Is it a known issue ?

**Comment by sancar** [comment]
Hi @coded9 
For the second cluster to join first one, it needs to have same group name and password.

**Comment by coded9** [comment]
I don't need the second cluster to join the first one,but the two clusters should run independently on single JVM with their respective members forming the cluster.

**Comment by coded9** [comment]
Update: 
I just tried removing common members from first cluster config and started the tomcat. The behavior doesn't change at all.

**Comment by sancar** [comment]
When I see member1 member2 on the second xml, I have assumed that you have the same memberlist on both configuration. 

The logs of members that should form the second cluster should tell us more.  Can you take a look at /share the logs of two members that should be the second cluster ?

**Comment by coded9** [comment]
Attached the log file,please check 
All members are same for both clusters.
[Uploading hazelcast.log…]()

**Comment by sancar** [comment]
```
08-Jan-2020 02:25:48.167 INFO [hz._hzInstance_2_two.cached.thread-2] com.hazelcast.nio.tcp.TcpIpConnector.null [10.3.121.21]:6702 [two] [3.11.4] Could not connect to: /10.3.121.22:6702. Reason: SocketException[No route to host to address /10.3.121.22:6702]
```

Could it be the case that ports 670* are disabled via a security manager on the machine that you are running on ?  
`No route to host to address /10.3.121.22:6702`

**Comment by coded9** [comment]
But why a single member cluster got formed for second instance,if the ports with 670* are disabled ?

**Comment by sancar** [comment]
It tried to connect to other members with port 670* but could not reach to them. We do not prevent a node starting if other members can not be reached. Imagine the first node started with that config, it needs start as single node cluster and then wait for the others to join him.

**Comment by coded9** [comment]
So,you are saying, ports are open for starting a process on the current node and closed for accepting connections from external nodes ? 
I'll get in touch with infra team if this is the case.

**Comment by sancar** [comment]
@coded9 Is there an update ?

**Comment by coded9** [comment]
Ports are closed for accepting connections from the firewall. It's fixed

**Comment by sancar** [comment]
Glad to hear that. I am closing the issue
