### ISSUE TITLE
Promote IMap.putAllAsync and IMap.submitToKeys to public API

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#16449]
`IMap.putAllAsync` is available both on Client and Member APIs, but as non-public methods. I don't see any reason not to promote it to public API as it has the same code path as the blocking `putAll`

**Comment by cangencer** [comment]
Same is true for `submitToKeys()` method, I'm not creating another issue since it's essentially in the same situation as `putAllAsync`

**Comment by Holmistr** [comment]
After discussion, @santhoshkumarbs would like to take this issue. Could you please comment here, so I would be able to assign it to you?

**Comment by santhoshkumarbs** [comment]
Yes please. Thanks.

**Comment by Holmistr** [comment]
Fantastic, it work @santhoshkumarbs :) We can't wait for your first initial pull request. Don't hesitate to open in completely simple, we will work together, so it would make it to final state :) Good luck!

**Comment by santhoshkumarbs** [comment]
Thank you Jiri. I will do that.

Regards,
Santhosh

**Comment by Holmistr** [comment]
Hi @santhoshkumarbs , just checking in - is there anything we can help you out with? I just want to make sure that you're not stuck on something and just afraid to ask :)

**Comment by santhoshkumarbs** [comment]
Hi @Holmistr, so for putAllAsync & submitToKeys, implementations were present already & I added it to IMap for exposing it as a public API. However, I am not sure how I can test & verify if it's working as expected. I've committed the enhancement in my forked repo(enhancement/4.1/16449). Is it possible for you to have a look at it & give feedback(I haven't yet covered other methods requested as part of #5337 ) or should I raise a PR? Thanks & apologies for the delay.

**Comment by Holmistr** [comment]
Hey @santhoshkumarbs , great to hear that! Let's create a PR and we can start reviewing it. And absolutely no need to apologize, we appreciate your effort! :fist_oncoming:

**Comment by santhoshkumarbs** [comment]
Thanks @Holmistr. I've created a PR for this(https://github.com/hazelcast/hazelcast/pull/16704).
