### ISSUE TITLE
Make diagnostics runtime togglable

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#16467]
The feature includes the following:
1) Enable/disable diagnostics at runtime
2) Enable/disable diagnostics plugins at runtime
3) Enable/disable collecting `DEBUG` metrics at runtime

Currently, enabling diagnostics and `DEBUG` metrics can be done only at startup time, with system property. Making them togglable at runtime would be a very useful feature, the ops could read out more details from a running cluster without restarting the members/clients, which might increase the probability of reading out useful information after an incident by a great factor.

Enabling a diagnostics plugin is also done at startup. With making it dynamic, great care should be taken to prevent issues from registration/deregistration races.

**Comment by mmedenjak** [comment]
Since we have a PRD, can we close this issue @Holmistr ?

https://hazelcast.atlassian.net/wiki/spaces/IMDG/pages/2483650686/Change+log+level+and+enable+diagnostics+at+runtime

**Comment by Holmistr** [comment]
:+1:
