### ISSUE TITLE
Resource leaks related to ClusterViewListenerService.clusterListeningEndpoints

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#16482]
While investigating a Jet OOME, we've realized there can be issues related to `ClusterViewListenerService.clusterListeningEndpoints`.

First of all, there were cca 27000 `TcpIpConnection` instances, but just about 20 of them were alive. The size of `clusterListeningEndpoints` map was about 25000 entries. (@olukas can provide the original heapdump).

We didn't find the reason for this behavior, but we realized there can be a resource leak in `com.hazelcast.client.impl.ClientEndpointImpl.destroy()` E.g. when a `logout` throws a `LoginException` or another problem jumps in before removing endpoint from the map.

https://github.com/hazelcast/hazelcast/blob/fdc6a205b2b6f50e01d21a263c373a0894ad2e67/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEndpointImpl.java#L214-L231

**Comment by sancar** [comment]
@kwart 
I have send a fix for this recently. https://github.com/hazelcast/hazelcast/pull/16452 
It seems that there are still problems. 

It make sense to make the `logout` last here. Other methods are not sending any exception. 
I will prepare a simple fix. 
Are we certain that this is the only problem ? Is there a reproducer that I can try easily ?
