### ISSUE TITLE
member side OOME NioOutboundPipeline

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16499]
http://jenkins.hazelcast.com/view/split/job/split-atomic-long/92/console

fail HzMember2HZAA untilClusterSafe hzcmd.ops.UntilClusterSafe threadId=0 global.AssertionException: isClusterSafe()=false try's=151 interval 10 

 output/HZ/HzMember2HZAA/exception.txt
 output/HZ/HzMember2HZAA/HzMember2HZAA.oome
 output/HZ/HzMember2HZAA/HzMember2HZAA.hprof

/disk1/jenkins/workspace/split-atomic-long/4.0-SNAPSHOT/2020_01_18-10_33_57/long Failed

fail HzMember2HZAA untilClusterSafe hzcmd.ops.UntilClusterSafe threadId=0 global.AssertionException: isClusterSafe()=false try's=151 interval 10 [0m

http://54.147.27.51/~jenkins/workspace/split-atomic-long/4.0-SNAPSHOT/2020_01_18-10_33_57/long

One instance of "com.hazelcast.internal.networking.nio.NioOutboundPipeline" loaded by "sun.misc.Launcher$AppClassLoader @ 0xfce01260" occupies 30,431,064 (63.48%) bytes. 

Keywords
com.hazelcast.internal.networking.nio.NioOutboundPipeline
sun.misc.Launcher$AppClassLoader @ 0xfce01260

http://54.147.27.51/~jenkins/workspace/split-atomic-long/4.0-SNAPSHOT/2020_01_18-10_33_57/long/gc.html

shows only ./output/HZ/HzMember2HZAA/verbosegc.log.png
has GC issues.

**Comment by Danny-Hazelcast** [comment]
the test normally passes.

In this failing run the partition count was increased, from the default to 2707

**Comment by mmedenjak** [comment]
We are aware that increasing partition count increases the heap usage and this is also something that we must take into account when working on https://hazelcast.atlassian.net/wiki/spaces/PM/pages/128308945/Change+The+Number+of+Partitions+to+1999.

**Comment by Danny-Hazelcast** [comment]
I have run with a larger client side heap and larger partition count 2707
I do not see the OOME issue.

if the hprof is not indication an obvious issue or it not cause for more investigation then
I am happy for this issue to be closed

**Comment by mmedenjak** [comment]
Great, thanks!
