### ISSUE TITLE
JSP bean properties are not updated

### ISSUE THREAD

**Issue by bakedzebra** [hazelcast/hazelcast#16534]
Currently I`m facing an issue with JSP beans property management. Please follow the source code below:

```java
...
<jsp:useBean id="user" class="...User" scope="session"/>
<jsp:useBean id="list" class="...LinkedList" scope="session"/>
...
```

Previously, all the JSPs were handled by Oracle Weblogic but now I had to migrate the project to Spring Boot with Embedded Tomcat and Hazelcast Session Management. So the issue occurs if we do smth like this:

```java
user.setUsername("test");
list.add(new Object());
response.setRedirect(...);
```

After the redirect is made I`m trying to reach the username or list values but what I actually receive is:

```java
user.getUsername() => null
list.size() => 0
This one was working using the Weblogic.
```

Note: But there is a easy but not very effective solution for this issue:

```java
session.putValue("user", user);
session.putValue("list", list);
response.setRedirect(...);
```

I have a lot of JSP pages so I can`t cover all of this issues. Could you please help me with this one? Thanks!

**Comment by mmedenjak** [comment]
Hi @bakedzebra !

I see the issue is related to sessions. Maybe it's better if you open an issue against these repos - 
https://github.com/hazelcast/hazelcast-tomcat-sessionmanager or https://github.com/hazelcast/hazelcast-jetty-sessionmanager?

**Comment by bakedzebra** [comment]
@mmedenjak Thanks a lot! I will :)
