### ISSUE TITLE
client OOME ClientListenerServiceImpl  split brain test

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16540]
http://jenkins.hazelcast.com/view/split/job/split-x2/2/console

sh hz-bench-run-jenkins-split hz/stable

/disk1/jenkins/workspace/split-x2/4.0-SNAPSHOT/2020_01_22-14_11_42/stable/list

./output/HZ/HzClient2HZAA/HzClient2HZAA.hprof
./output/HZ/HzClient1HZAA/HzClient1HZAA.hprof

http://54.147.27.51/~jenkins/workspace/split-x2/4.0-SNAPSHOT/2020_01_22-14_11_42/stable/list/

http://54.147.27.51/~jenkins/workspace/split-x2/4.0-SNAPSHOT/2020_01_22-14_11_42/stable/list/output/HZ/HzClient1HZAA/

<img width="1114" alt="Screen Shot 2020-01-23 at 14 06 57" src="https://user-images.githubusercontent.com/5988678/72979582-b9142180-3de9-11ea-9444-b3517c29d65e.png">

**Comment by mmedenjak** [comment]
Related?
https://github.com/hazelcast/hazelcast/issues/16482 and https://github.com/hazelcast/hazelcast/issues/16484

**Comment by Danny-Hazelcast** [comment]
2nd OOME   diff test 

/disk1/jenkins/workspace/split-x3/4.0-SNAPSHOT/2020_01_22-17_22_11/sql/serializable

http://54.147.27.51/~jenkins/workspace/split-x3/4.0-SNAPSHOT/2020_01_22-17_22_11/sql/serializable/output/HZ/HzClient2HZAA/verbosegc.log.png

http://54.147.27.51/~jenkins/workspace/split-x3/4.0-SNAPSHOT/2020_01_22-17_22_11/sql/serializable/output/HZ/HzClient2HZAA/

**Comment by sancar** [comment]
@mmedenjak @Danny-Hazelcast I found the root cause. It is not related to #16482 or #16484. 

It is related to my recent changes here https://github.com/hazelcast/hazelcast/pull/16502. I am preparing a fix

**Comment by sancar** [comment]
@Danny-Hazelcast https://github.com/hazelcast/hazelcast/pull/16545
Can you verify that my fix resolves the OOME issue?
