### ISSUE TITLE
ITopic durable subscribers

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#1655]
Currently there is no support for durable subscribers for topics; so if a topic has send the messages to the queue for a certain listener, and the member that owns that queue crashes, then all messages send for a particular subscriber are lost.

With JMS you have durable subscribers to prevent this form happening. So your messages are stored somewhere (e.g. a IQueue) and if you come online again, all messages for you are waiting to be processed.

**Comment by pveentjer** [comment]
Durable subscription is very easy to add once the reliable topics are merged. The difference with a durable and non durable subscription is that a non durable subscription always begins at the tail of the ringbuffer when it starts, and with a durable one the topic begins reading from the previous sequenceId he has read. 

So if we expose an interface SequenceIdRepo with a load/store of the sequenceId and topic name, then a user can very easily put his own storage solution underneath. 

Another thing we need to think about is at failure sementics semantics. So do we store the sequenceId before we process the message (at most once) or do we store the sequenceId after we have processed the message (at least once).

**Comment by StanAccy** [comment]
Give us the option on store-before vs store-after.  For our use case, and
similar ones I've worked on in the past, we would store before - we want
the message.  The latency of receipt isn't important in these use cases -
we just want to ensure we get the message regardless of reboots, service
upgrades, outages etc.

N

**Comment by pveentjer** [comment]
Sure. It should be part of the reliable topic improvements. PS: we also expose the underlying ringbuffer and you can do anything you want here. So if you are not happy (yet) with the topic behavior, you can also directly access the underlying ringbuffer.

**Comment by bwzhang2011** [comment]
@pveentjer, pity that durable topic implementation postponed to hz3.5.1, looking forward to hz3.5 release. it has many changed compared with upgrade between hz3.4 and hz3.3

**Comment by bwzhang2011** [comment]
@pveentjer, how about some support for transaction topic, as reliable topic is going to add support for subscirbe topic, will it be supported for topic transaction. or else the fire-forget mod will not be supported for transaction use cases.

**Comment by pveentjer** [comment]
No transactional topics planned. 

Durable subscription has been added to the reliable topic.

**Comment by bwzhang2011** [comment]
@pveentjer, would you mind leaving more message for that ? I just mean the detail or background for transactionContext without support for topic compared with transactionQueue support.

**Comment by pveentjer** [comment]
No support for transactional topics is lpanned.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ? as reliable topic merged in latest hazelcast snapshot, s store-before should take store into consideration for first step while hazelcast currently lacks of some support for internal file system support like gridgain, so looking forward to the disk based one for the default implementation.

**Comment by jerrinot** [comment]
I'm moving milestone to backlog. This would be very hard if not impossible to back-port into a maintenance release.

**Comment by bwzhang2011** [comment]
@jerrinot, maybe it's the wise choice to move it into backlog. as hazelcast announced its light and convenient message api like IQueue or ITopic but it seems lack of some enterprise features or strict definitions like JMS or AMQP within its broker or provider implementation as for us so it could not under take the role like message middle-ware. maybe after hazelcast 3.6 releasing, more enterprise feature could be provided and planned and look forward to that in the future.

**Comment by jerrinot** [comment]
@bwzhang2011: I'd greatly appreciate if you could list queue-related features your would like to eventually see in Hazelcast.

**Comment by bwzhang2011** [comment]
@jerrinot, thanks for feed back quickly. there's no point of arguing for the features provided from hazelcast out of my intention. in fact I also benefited from them for such use cases for point to point or publish-subscribe way with simple and easy use api so it is with the transaction manner. what I focused was it seemed lack of the standard support or completed solution from AMQP or JMS broker implementation  like RabbitMQ or ActiveMQ. people would prefer to take more matured or widely proved even to reach industrial strength solution. so It's not fair play that to require hazelcat IQueue or ITopic to satisfy complete features like AMQP or JMS (and of course AMQP or JMS is actual the standard). so I think it's wise choice to do that and prepare more time to add the features needed.

**Comment by jerrinot** [comment]
@bwzhang2011: Thank you for your feedback! I didn't want to argue about features, not at all. I was genuinely trying to gather requirements / feedback :) 

I don't think we are going to provide official JMS support any time soon. There is a community project you probably know about: https://github.com/mpilone/hazelcastmq

AMQP is wire-level format rather API. Perhaps we could treat it as another interface into Hazelcast messaging capabilities, but I know too little about AMQP to be able to tell whether it makes a sense or not.

**Comment by bwzhang2011** [comment]
@jerrinot. thanks for your feed back. frankly speaking, the domain area of my company was e-commerce. and most popular queue based solution is apache kafka or similar solution like rocketmq (originated from alibaba the most biggest e-commerce company around the world) https://github.com/rocketmq. besides for the traditional use cases or standard like AMQP or JMS way or like your suggestion hazelcastmq, it would not satisfy the e-commerce requirements especially for the big data accumulation ability which simply to be some super disk queue solution. it will make full use of the disk or file on reading or writing which I think hazelcast lack of some original support for its file system to cope with for certain use cases.  as mq should satisfy big data like huge log data transferring. so maybe if hazelcast wants to enhance such area for more message middle-aware features, it should make more side-effect project to absorb these idea for we need more specific solution so hazelcast should do more to make it more competitive.

**Comment by burakcelebi** [comment]
We have no plans to implement this feature. If you find this useful then please add +1 or please contribute to development via the HEP process.

https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals

**Comment by pooja-achievement** [comment]
Hi,

I need to use Hazelcast Topic for one of my requirement. There are two types of Topics: Basic and Reliable. I am not able to decide whether I should use basic topic or reliable topic as I am not able to understand that what kind of event loss would happen for basic Topic and to rectify that we need to use Reliable topic. Hazelcast manual says below for Reliable Topic,

```
Events are not lost since the Ringbuffer is configured with one synchronous backup by default.
Each Reliable ITopic gets its own Ringbuffer; if a topic has a very fast producer, it will not lead to problems at topics that run at a slower pace.
Since the event system behind a regular ITopic is shared with other data structures, e.g., collection listeners, you can run into isolation problems. This does not happen with the Reliable ITopic.
```
I am not able to understand what synchronous backup would do??

My scenario:

A node stores some config in internal memory. The node receives a request to reload the config from database, so the node would publish the info and all the nodes in the cluster including the one who has published the message would receive the message and all the nodes would reload the config from database.

**I need to decide whether I should use basic Topic or Reliable Topic??**
