### ISSUE TITLE
client OOME internal.util.executor.StripedExecutor:  create use destroy with member kill

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16551]
http://jenkins.hazelcast.com/view/shutdown/job/kill-All/36/console

/disk1/jenkins/workspace/kill-All/4.0-SNAPSHOT/2020_01_23-22_26_37/stable/destroy/create-use-destroy

http://54.147.27.51/~jenkins/workspace/kill-All/4.0-SNAPSHOT/2020_01_23-22_26_37/stable/destroy/create-use-destroy/

http://54.147.27.51/~jenkins/workspace/kill-All/4.0-SNAPSHOT/2020_01_23-22_26_37/stable/destroy/create-use-destroy/gc.html

version 
HazelcastClient 4.0-SNAPSHOT (20200123 - 79150ac, bb2e37b) is STARTING

./output/HZ/HzClient3HZ/HzClient3HZ.hprof
./output/HZ/HzClient2HZ/HzClient2HZ.hprof
./output/HZ/HzClient1HZ/HzClient1HZ.hprof

client4 no oome looks ok from GC chart.

this test normally passes.

could the fix for https://github.com/hazelcast/hazelcast/issues/16498
have some thing to do with this issue ?  

all 5 StripedExecutor$Worker look to hold same amount of heap.

The thread com.hazelcast.internal.util.executor.StripedExecutor$Worker @ 0xf38a1af8 hz.client_1.event-5 keeps local variables with total size 36,979,184 (19.14%) bytes.

<img width="841" alt="Screen Shot 2020-01-24 at 11 05 45" src="https://user-images.githubusercontent.com/5988678/73053717-845fa300-3e99-11ea-8bbd-2daade5b8f7f.png">

**Comment by Danny-Hazelcast** [comment]
run with latest master OS EE

http://jenkins.hazelcast.com/view/kill/job/kill-x2/28/console

**Comment by Danny-Hazelcast** [comment]
stable cluster version of same test 
http://jenkins.hazelcast.com/view/stable/job/stable-x3/64/console

looks to be passing

**Comment by Danny-Hazelcast** [comment]
shutdown re-start cluster members version of the same test 

http://jenkins.hazelcast.com/view/shutdown/job/shutdown-x2/26/console

fail HzClient1HZ _create-use-destroy_createUseDestroy_latch hzcmd.latch.CreateUseDestroy threadId=0 java.lang.OutOfMemoryError: GC overhead limit exceeded

http://54.147.27.51/~jenkins/workspace/shutdown-x2/4.0-SNAPSHOT/2020_01_24-09_41_03/create-use-destroy/


better looking GC
http://54.147.27.51/~jenkins/workspace/shutdown-x2/4.0-SNAPSHOT/2020_01_24-09_41_03/create-use-destroy/gc.html


./output/HZ/HzClient4HZ/HzClient4HZ.hprof
./output/HZ/HzClient1HZ/HzClient1HZ.hprof
./output/HZ/HzClient1HZ/exception.txt

**Comment by Danny-Hazelcast** [comment]
Metin Dumandag

The problem seems like the huge number of create/destroy proxy events that comes to the client. It seems the stem from this addition 

https://github.com/hazelcast/hazelcast/commit/a4f2b76dbfb45d1f81ed6b2bd33db5f0de570270#diff-9e861ee310f3c44123f003fe8630304eR141

**Comment by Danny-Hazelcast** [comment]
@ihsandemir  

using  hazelcast-use git://github.com/ihsandemir/hazelcast.git candidateFix

failed
http://jenkins.hazelcast.com/view/shutdown/job/shutdown-x2/27/console

and failed
http://jenkins.hazelcast.com/view/kill/job/kill-x2/29/console

**Comment by ihsandemir** [comment]
Our findings:

- The local proxy destroy for a number of services actually do remote calls and this needs to be fixed. But there is a significant number of such proxies. When the proxy is destroyed due to event then no remote invocation should be done.

**Comment by ihsandemir** [comment]
related to https://github.com/hazelcast/hazelcast/issues/12470
