### ISSUE TITLE
MapProxyImpl - Spring Boot

### ISSUE THREAD

**Issue by bakedzebra** [hazelcast/hazelcast#16560]
Hi,

Could you please help me to clarify something:
I've noticed that all Sessions that are retrieved from HazelcastSessionRepository are the copies of basic sessions that stored in MapProxyImpl instance. So if I change a proxy session's attribute property:
(This example is not an actual usage, Its just for clarification)
```
List list = hazelcastRepository.getSession("1").getAttribute("List");
list.add(new Object()); //list.size = 1

List list1 = hazelcastRepository.getSession("1").getAttribute("List");
list1.size() // 0
```

The basic session's (in MapProxyImpl) attribute 'List' is not updated as well.

Is there a way to merge original session object inside MapProxyImpl and the proxy (copy) session attributes?

I know, that I could use HazelcastSessionRepository.save() - but it will work when there is delta value (any changes) in parameters map. But in my case the List remain itself in the session.

Thanks!

**Comment by mmedenjak** [comment]
Hi @bakedzebra ! Which artifact is this? I cannot find `HazelcastSessionRepository` in this repository.

**Comment by bakedzebra** [comment]
Hey! I think  it`s in the `org.springframework.session` package

**Comment by mdogan** [comment]
It's in `spring-session` project: https://github.com/spring-projects/spring-session/blob/master/spring-session-hazelcast/src/main/java/org/springframework/session/hazelcast/HazelcastSessionRepository.java

**Comment by bakedzebra** [comment]
Thanks!
