### ISSUE TITLE
How to implement file-based hazelcast QueueStore?

### ISSUE THREAD

**Issue by wikwon69** [hazelcast/hazelcast#16626]
Hi,

I'm trying to implement hazelcast QueueStore.
Is it possible storing data in file not in DB?

If so, could you give me some info like coding sample?

Thanks in advance.

**Comment by mmedenjak** [comment]
Hi @wikwon69 !

Yes, it's possible to implement a queue store that stores items to a file. There is no ready example yet that works with files and most examples either print out the item on console or store it to an in-memory list, for example [this one](https://github.com/hazelcast/hazelcast-code-samples/tree/master/distributed-collections/queuestore).

Generally, you can do anything you want in the `QueueStore` implementation, you can write items to a file, you can write to a database, you can send items over the network, enqueue them in some external queue and so on. But keep in mind that these methods will be called on the partition thread which is used by Hazelcast to execute incoming operations. This means, if you do any blocking calls in your queue store implementation (like writing out to network), other Hazelcast operations on that queue will be stalled for the duration of the call. So in case you have blocking calls in your queue store implementation, you might have to think about offloading the calls to some thread pool or some other solution to decouple the threads.

Closing this issue as it is not an issue. For further questions, please refer to our [Gitter channel](https://gitter.im/hazelcast/hazelcast) or our [Google groups](https://groups.google.com/forum/#!forum/hazelcast). If you have another issue, please open a new issue. Happy Hazelcasting!
