### ISSUE TITLE
About firewall setting for outbound ports in hazelcast client side

### ISSUE THREAD

**Issue by wikwon69** [hazelcast/hazelcast#16668]
Hi,

When HZ client is in WebLogic Server and firewall is set in that WAS machine.
Should we set outbound-ports in HZ client side and those ports should be opened via firewall?

I mean I'd like to know in addition to HZ client -> HZ server communication, outbound port of HZ Client is used for HZ server -> HZ client communication and for HZ server -> HZ client communication, outbound-ports in HZ client should be opened in firewall?

Additionally I hope you to guide about tuning the number of outbound ports. 

Thanks in advance.

**Comment by wikwon69** [comment]
Hi,
Isn't there any update?

**Comment by kwart** [comment]
Copy/paste from https://groups.google.com/d/msg/hazelcast/Xl9QR_AIWak/LRLZ1vGaAAAJ
Feel free to reopen if it doesn't answer your question.

Usually, the outbound connections are not restricted in firewalls. E.g.

```
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
```

In such a case, you don't need to specify outbound ports in Hazelcast.

If your firewall needs to have defined rules for outbound ports, then
pick some range from ephemeral ports (e.g. 5000-50500). The minimal
size of the range should be on member side roughly:
```
#members + #clients + few others (used e.g. for node discovery)
```

On the client, with smart routing enabled, you will need following port count:
```
#members + few others
```

The problem can come if you run more members or a client and member
together on one machine. Then you have to multiply the port range size
or pick non-overlapping port ranges for each Hazelcast Instance.
