### ISSUE TITLE
Product Description Update in Readme 

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast#16675]
Consider rephrasing the following paragraph of [README.md](https://github.com/hazelcast/hazelcast/blob/master/README.md). It might need an update due to the new hazelcast.org work. 

> With its various distributed data structures, distributed caching capabilities, elastic nature, memcache support, integration with Spring and Hibernate and more importantly with so many happy users, Hazelcast is feature-rich, enterprise-ready and developer-friendly in-memory data grid solution.

Also, see [this reddit comment](https://www.reddit.com/r/Cplusplus/comments/f56d7w/hazelcast_open_source_distributed_caching_for_c/fhxmgc2/
).

**Comment by mmedenjak** [comment]
Closing as fixed by https://github.com/hazelcast/hazelcast/pull/16815.
