### ISSUE TITLE
Session Replication is not scalable.

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#1668]
Interaction with the session is done using predicates that go over all entries in the map; they are not routed calls to specific map entries. This design doesn't scale.

**Comment by mesutcelik** [comment]
This is fixed in 3.5. Invalidation is done on the session entry itself and we don't have to traverse all entries on the session map.

**Comment by dfex55** [comment]
@mesutcelik Can you reference the commit? thx

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5374
