### ISSUE TITLE
Hazelcast Consul plugin incompatible with Hazelcast 4.0

### ISSUE THREAD

**Issue by timoinstana** [hazelcast/hazelcast#16696]
**Describe the bug**
The documentation for Hazelcast 4.0 contains a section for Consul discovery (https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#consul-cloud-discovery). Due to package changes, this plugin is not compatible with Hazelcast 4.0 anymore.

**Expected behavior**
a) The plugin is fixed
b) The documentation is updated

**Additional context**
Issue in Consul discovery project: https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/issues/33

**Comment by bitsofinfo** [comment]
if anyone wants to contribute a PR to the project, def welcome! https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/issues/33

**Comment by amrsamii** [comment]
can I take this issue? I am new to Hazelcast and I did not solved any issues before

**Comment by Holmistr** [comment]
Hi @amrsamii, glad to see that you're interested! :tada: I'm assigning you the issue. 

I don't know how familiar you are with Consul. If not that much (like myself), I would suggest you following workflow:
* Setup Consul locally (https://learn.hashicorp.com/consul/getting-started/install)
* Setup Hazelcast IMDG locally with Consul Discovery, but with Hazelcast IMDG 3.12.6 version, which should still be working without problems (https://github.com/bitsofinfo/hazelcast-consul-discovery-spi#usage)
* Then upgrading the code to Hazelcast IMDG to 4.0, which should stop working
* Fix it.

In case you get stuck anywhere, don't hesitate to ping us on Gitter or here. Looking forward to your contribution! :)

**Comment by amrsamii** [comment]
Consul discovery is now compatible with Hazelcast 4.0. https://github.com/bitsofinfo/hazelcast-consul-discovery-spi/pull/34

**Comment by Holmistr** [comment]
Fantastic @amrsamii , thank you very much for your contribution! :tada:
