### ISSUE TITLE
Hazelcast queue - Write in queue with REST CLIENT and poll entry with NodeJs client

### ISSUE THREAD

**Issue by NutellaTorte** [hazelcast/hazelcast#16713]
**Describe the bug**
Hello,
I want to write entries to a queue using REST call. This is no problem, this works fine.
Next step is to create a item listener on this queue using the NodeJs client. This item listener should poll the entries which I added by the REST call. If I try to start the NodeJs client, there will be an error: 

RangeError: There is no Identified Data Serializer factory with id -37.

I read a lot of your documentation and tried to create a custom serializer, identified data serializer. Nothing works. I dont know what to do next.

**Expected behavior**
I expect the NodeJs Client to receive the JSON string that was written to the queue via the REST call.

**To Reproduce**

1. Curl 
```
 curl -v -H "Content-Type: text/plain" -d '{"name":"example"}' http://<host>/hazelcast/rest/queues/myqueue
```
2. NodeJs Files
index.ts
```
import { HazelcastClient } from './hazelcast';

const client = new HazelcastClient();
client.startClient().then(client => {
    client.getQueue('myqueue').then(queue => {
        const itemListener = {
            itemAdded: (itemEvent) => {
                console.log('item added', itemEvent.item);
            } ,
            itemRemoved: (itemEvent) => {
                console.log('item removed', itemEvent.item);
            }
        };
        queue.addItemListener(itemListener, true).then(value => {
            console.log(value);
        });
    });
}); 
```
hazelcast.ts
```
import { Client, Config } from 'hazelcast-client';
export class HazelcastClient {
    config = new Config.ClientConfig();

    constructor() {
        this.config.networkConfig.addresses.push(
               'myaddresses:5701
        );
    }

    startClient() {
        return Client.newHazelcastClient(this.config);
    }
}
```
3. Error Message: 
```
RangeError: There is no Identified Data Serializer factory with id -37.
```

**Additional context**
```
"dependencies": {
    "@types/bluebird": "^3.5.29",
    "@types/long": "^4.0.1",
    "@types/node": "^13.7.0",
    "hazelcast-client": "^3.12.2",
    "typescript": "^3.7.5"
}
``` 
Hazelcast Version: 3.12.7

**Comment by burakcelebi** [comment]
Moved to the Node.js Client repo: https://github.com/hazelcast/hazelcast-nodejs-client/issues/518
