### ISSUE TITLE
Beans missing Java type

### ISSUE THREAD

**Issue by ofek** [hazelcast/hazelcast#16729]
**Describe the bug**

It appears that all beans of type `Metrics` are missing the [standard](https://www.oracle.com/technetwork/java/javase/tech/best-practices-jsp-136021.html) type information that many monitoring solutions rely on.

![Capture](https://user-images.githubusercontent.com/9677399/76185429-983f3a00-61a5-11ea-9b2f-d275938b17fd.PNG)

**Comment by blazember** [comment]
Thank you for reporting this @ofek! I could reproduce the issue and come up with a fix candidate. I will send a fix soon.

**Comment by blazember** [comment]
@ofek The fix is merged and will be part of the 4.0.1 release. You can test it with the `4.0.1-SNAPSHOT` version if you wish. Thanks again for raising this :+1:

**Comment by ofek** [comment]
Thanks! When will that be available on Docker Hub?

**Comment by blazember** [comment]
@ofek We don't have a concrete date for the 4.0.1 release yet, but you can expect it in the next weeks. You can check our release announcements.

**Comment by ofek** [comment]
Thank you! Have you had a chance to look into https://github.com/hazelcast/hazelcast/issues/16741?
