### ISSUE TITLE
Management Center beans broken

### ISSUE THREAD

**Issue by ofek** [hazelcast/hazelcast#16741]
**Describe the bug**

https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html#clustered-jmx-api

Similar to https://github.com/hazelcast/hazelcast/issues/16729, data for `Clusters` cannot be seen.

![Capture](https://user-images.githubusercontent.com/9677399/76541833-8934e200-645a-11ea-96bc-94c2a46d8997.PNG)

**Comment by puzpuzpuz** [comment]
Hi @ofek 

Clustered JMX and REST APIs in Hazelcast Management Center are Enterprise features. That means that you need to [configure](https://docs.hazelcast.org/docs/management-center/4.0.1/manual/html/index.html#starting-with-a-license) a license key in order to use them.
