### ISSUE TITLE
Client xml configuration cannot handle empty near-cache name

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast#16768]
Client XML configuration for near caches name attribute is optional and its default value is "default".

The `hazelcast-client-full-example.xml` has this explanation for name attribute:

```
 - name: You can give a name for your Near Cache. It is optional and its default value is "default".
```
Conflicting behaviour
* Client xsd has `required`on the name attribute of near-cache.
* API config default to `default` if left empty

**Expected behavior**

* When XML name attribute does not exist then it should default to `default` similar to API config.
* related XSD definition should be fixed too

**Reproducer**

The below test fails if added to `XmlClientConfigBuilderTest`

```
    @Test
    public void testNearCacheDefaultName() {
        String xml = HAZELCAST_CLIENT_START_TAG
                + "  <near-cache>\n"
                + "    <in-memory-format>NATIVE</in-memory-format>\n"
                + "    <serialize-keys>false</serialize-keys>\n"
                + "  </near-cache>\n"
                + HAZELCAST_CLIENT_END_TAG;

        ClientConfig clientConfig = buildConfig(xml);
        NearCacheConfig ncConfig = clientConfig.getNearCacheConfig("default");

        assertEquals(InMemoryFormat.NATIVE, ncConfig.getInMemoryFormat());
        assertTrue(ncConfig.isSerializeKeys());
    }

```

**Comment by jawitcher** [comment]
Hi! Is that issue actual? I would like to work on this

**Comment by burakcelebi** [comment]
Of course @jawitcher, thank you! Please let us know if you need any help. cc: @sancar

**Comment by sancar** [comment]
Hi @jawitcher did you have a chance to work on this? Do you need any help?

**Comment by sancar** [comment]
@jawitcher I took over the issue since we could not hear from you.
