### ISSUE TITLE
Rename IdentifiedDataSerializable.getId()

### ISSUE THREAD

**Issue by danfin** [hazelcast/hazelcast#1677]
The `getId()` method of the interface `IdentifiedDataSerializable` is a common method, meaning a naming conflict will happen frequently.  For example, database entities will also have a `getId()` method.

Consider renaming this method to a more unique name.

For the forum discussion, please see
https://groups.google.com/forum/#!searchin/hazelcast/dan%7Csort:date/hazelcast/sW7xDXgRhWQ/IR9jhMbiqo4J

**Comment by magiccrafter** [comment]
Any progress/plans for releasing this in the near future?
