### ISSUE TITLE
Incorrect LocalCacheStats metrics computation

### ISSUE THREAD

**Issue by alex-dukhno** [hazelcast/hazelcast#16796]
`LocalCacheStatsImpl` states that it reports the following metrics in **milli**seconds:
```java
@Probe(name = CACHE_METRIC_AVERAGE_GET_TIME, unit = MS)
private float averageGetTime;
@Probe(name = CACHE_METRIC_AVERAGE_PUT_TIME, unit = MS)
private float averagePutTime;
@Probe(name = CACHE_METRIC_AVERAGE_REMOVAL_TIME, unit = MS)
private float averageRemoveTime;
```
It is instantiated from `CacheStatisticsImpl` which computes them in **micro**seconds https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/cache/impl/CacheStatisticsImpl.java#L195

**Expected behavior**
Consistent measurement of the above metric. (However, I assume we need to check if other metrics are computed in the correct time units)

**Comment by mmedenjak** [comment]
Fixed with  https://github.com/hazelcast/hazelcast/pull/17742
