### ISSUE TITLE
Release dangling ISemaphore

### ISSUE THREAD

**Issue by menih** [hazelcast/hazelcast#16810]
If a semaphore is acquired in one instance and that instance dies (kill -9), how can one clean it up? 
I tried reacting to when memberRemove() notification, by keeping a member to semaphore map and releasing these semaphores, but that encountered an error 

```
Mar 28, 2020 6:48:24 PM com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl
SEVERE: [240.0.64.14]:5701 [factory] [4.0] hz.vigilant_pasteur.event-4 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@7edec1d7
**java.lang.IllegalStateException: No valid session!**
        at com.hazelcast.cp.internal.datastructures.semaphore.proxy.SessionAwareSemaphoreProxy.newIllegalStateException(SessionAwareSemaphoreProxy.java:252)
        at com.hazelcast.cp.internal.datastructures.semaphore.proxy.SessionAwareSemaphoreProxy.release(SessionAwareSemaphoreProxy.java:164)
        at com.hazelcast.cp.internal.datastructures.semaphore.proxy.SessionAwareSemaphoreProxy.release(SessionAwareSemaphoreProxy.java:156)
```

**Expected behavior**
Semaphore is released. I don't understand what session is in context here...

**To Reproduce**
1) Create two Hazelcast instances, acquire a semaphore and manage a cluster map of semaphore to instance
2) Abruptly terminate it instance owning the semaphore and Implement memberRemove such that second instance detect it.
3) Examine map to determine semaphores owned my dead instance and call ISemaphore.release() on each.

**Comment by menih** [comment]
Here is code to repro

        HazelcastInstance i1 = Hazelcast.newHazelcastInstance();
        ISemaphore semaphore = i1.getCPSubsystem().getSemaphore("semaphore");
        semaphore.init(1);
        semaphore.acquire();
        i1.shutdown();

        HazelcastInstance i2 = Hazelcast.newHazelcastInstance();
        semaphore = i2.getCPSubsystem().getSemaphore("semaphore");
        semaphore.init(1);
        semaphore.release();

**Comment by menih** [comment]
I figured out how to achieve this... it all has to do with the JDK compatible flag. Only problem is that you have to set it for each individual semaphore. We create semaphores on the fly and potentially have hundreds. I wish there is a way to set the default value of setJDKCompatible flag to true.


        Config config = new Config();
        config.getCPSubsystemConfig().addSemaphoreConfig(new SemaphoreConfig("semaphore", true, 1));

        HazelcastInstance i1 = Hazelcast.newHazelcastInstance(config);
        ISemaphore semaphore = i1.getCPSubsystem().getSemaphore("semaphore");
        semaphore.acquire();
        i1.shutdown();

        HazelcastInstance i2 = Hazelcast.newHazelcastInstance(config);
        semaphore = i2.getCPSubsystem().getSemaphore("semaphore");
        semaphore.release();

**Comment by menih** [comment]
Take it back... this is still an issue... as there is no way to change config after instance had been instantiated... so practically, one would need to know all the semaphores ahead of time. That's not going to work for our use case. We now must have a way to initiate semaphore CP config of JDKCompatible to true BEFORE instance is create.

**Comment by menih** [comment]
Another question - why is it when instance gracefully shuts down, it does not release all semaphores?

**Comment by mmedenjak** [comment]
@mdogan @petrpleshachkov can you provide some guidance on the above?

**Comment by mmedenjak** [comment]
BTW @menih I believe that if you define a semaphore config with the name `default`, the configuration will be applied to all semaphores which do not have a more specific configuration.

**Comment by mdogan** [comment]
Hi @menih,

By default semaphores are session-aware. That means each semaphore acquire/release action is bound to a session (which is automatically managed). When a member dies, its associated session(s) are invalidated and resources associated to that session are released. That also means, you cannot release a permit out of thin air before acquiring a permit first. 

That's why session-aware semaphores are not JDK compatible.  But the good thing is, you don't have to think about releasing permits of a died member anymore. That's automatically managed by Hazelcast.

**Comment by mdogan** [comment]
If you want to use JDK compatible semaphore, then you should handle releasing permits acquired by removed member.

**Comment by mdogan** [comment]
If you want to apply a config to all semaphores, you can define a semaphore with wildcard name `*`. Or even you can group semaphores with sub-matching wildcard names `jdk-*`, `test-*` etc.

**Comment by mmedenjak** [comment]
Closing as it seems this issue has been resolved. Thank you for the answer @mdogan and @menih if you have any further questions, please stop by our [community slack](https://slack.hazelcast.com/) or [google groups](https://groups.google.com/forum/#!forum/hazelcast). Happy Hazelcasting!
