### ISSUE TITLE
Explicitly registering Portable ClassDefinitions fails with multiple PortableFactories and overlapping classIds

### ISSUE THREAD

**Issue by dannyvanleiden** [hazelcast/hazelcast#16820]
**Describe the bug**

To work around some issues I was having with nullable Portable fields, I tried to explicitly register class definitions, following the documentation. This went well until I tried registering some classes for a second PortableFactory, that are using classIds that overlap with those of the first PortableFactory. As far as I understood from the documentation, classIds only need to be unique per PortableFactory. I then got the following exception:

```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Duplicate registration found for class-id[1]!
	at com.hazelcast.internal.serialization.impl.SerializationServiceV1.registerClassDefinitions(SerializationServiceV1.java:191)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.createSerializationService(DefaultSerializationServiceBuilder.java:300)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:237)
	at com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder.build(DefaultSerializationServiceBuilder.java:55)
	at com.hazelcast.instance.DefaultNodeExtension.createSerializationService(DefaultNodeExtension.java:210)
	at com.hazelcast.instance.Node.<init>(Node.java:240)
	at com.hazelcast.instance.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:161)
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:229)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:208)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:158)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at eu.sensara.procare.residentstate.TestCase.main(TestCase.java:120)
```

**Expected behavior**
As described in the javadoc of Portable.getClassId(), I expected classIds to only be unique per PortableFactory, I expected no exception:

```
Returns class identifier for this portable class. Class ID should be unique per PortableFactory.
```

**To Reproduce**

I've reproduced the issue in this self-contained test case:

```
public class TestCase {

    public static class MyPortable1 implements Portable {

        public static final int ID = 1;

        private String stringField;

        @Override
        public int getFactoryId() {
            return MyPortableFactory1.ID;
        }

        @Override
        public int getClassId() {
            return ID;
        }

        @Override
        public void writePortable(final PortableWriter writer) throws IOException {
            writer.writeUTF("stringField", stringField);
        }

        @Override
        public void readPortable(final PortableReader reader) throws IOException {
            stringField = reader.readUTF("stringField");
        }

        public static ClassDefinition getClassDefinition() {
            return new ClassDefinitionBuilder(MyPortableFactory1.ID, ID)
                    .addUTFField("stringField")
                    .build();
        }

    }

    public static class MyPortable2 implements Portable {

        public static final int ID = 1;

        private int intField;

        @Override
        public int getFactoryId() {
            return MyPortableFactory2.ID;
        }

        @Override
        public int getClassId() {
            return ID;
        }

        @Override
        public void writePortable(final PortableWriter writer) throws IOException {
            writer.writeInt("intField", intField);
        }

        @Override
        public void readPortable(final PortableReader reader) throws IOException {
            intField = reader.readInt("intField");
        }

        public static ClassDefinition getClassDefinition() {
            return new ClassDefinitionBuilder(MyPortableFactory1.ID, ID)
                    .addIntField("intField")
                    .build();
        }

    }

    public static class MyPortableFactory1 implements PortableFactory {

        public static final int ID = 1;

        @Override
        public Portable create(final int classId) {
            if (classId == MyPortable1.ID) {
                return new MyPortable1();
            }
            return null;
        }

    }

    public static class MyPortableFactory2 implements PortableFactory {

        public static final int ID = 2;

        @Override
        public Portable create(final int classId) {
            if (classId == MyPortable2.ID) {
                return new MyPortable2();
            }
            return null;
        }

    }

    public static void main(final String[] args) {
        Config cfg = new Config();
        cfg.getSerializationConfig()
                .addPortableFactory(MyPortableFactory1.ID, new MyPortableFactory1())
                .addPortableFactory(MyPortableFactory2.ID, new MyPortableFactory2())
                .addClassDefinition(MyPortable1.getClassDefinition())
                .addClassDefinition(MyPortable2.getClassDefinition());
        HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(cfg);
    }

}
```

**Additional context**

I've produced this issue with Hazelcast version 3.12.6, on openjdk 11.0.6.

It seems like SerializationServiceV1 creates a single HashMap that is then filled with all class definitions (of all PortableFactories), using the classId as the key. The result is that it encounters the same key for a second time and throws the HazelcastSerializationException.

I hope I am reading the documentation correctly. I was not able to find anything specifying this as a known limitation of explictly registering ClassDefinitions.

**Comment by sancar** [comment]
It seems that, you have used `MyPortableFactory1` in `MyPortable2` by mistake. Can you recheck that? 

> It seems like SerializationServiceV1 creates a single HashMap that is then filled with all class definitions (of all PortableFactories), using the classId as the key. The result is that it encounters the same key for a second time and throws the HazelcastSerializationException.

We don't have a single hashmap for all class definitions. Let me try to explain this:
In SerializationServiceV1 we have a Portable Context. Inside that we have 
```
private final ConcurrentHashMap<Integer, ClassDefinitionContext> classDefContextMap =
            new ConcurrentHashMap<Integer, ClassDefinitionContext>();
```
Here key is factory id. 
Inside `ClassDefinitionContext` we have another map. 
```
final ConcurrentMap<Long, ClassDefinition> versionedDefinitions = new ConcurrentHashMap<Long, ClassDefinition>();
```
In this map, the key is the class id.

**Comment by dannyvanleiden** [comment]
Thank you for the quick reply!
You're right, I made a mistake referencing MyPortableFactory1 instead of MyPortableFactory2 from MyPortable2. The issue seems to persist after fixing that however.

Also thank you for explaining how the classDefContextMap does use factoryId as the key. That looks to be setup to properly deal with multiple factories indeed, which is probably why the problem only occurs when explicitly registering ClassDefinitions:

The map I was referring to is the one in SerializationServiceV1.registerClassDefinitions, that is filled with the passed Colelction of ClassDefinitions, by classId. This method seems to be called once, after building the SerializationServiceV1 from DefaultSerializationServiceBuilder.createSerializationService. I'm not entirely sure if I'm reading this correctly, but that classDefinitions Set in DefaultSerializationServiceBuilder seems to be a single collection where in build() all config.getClassDefinitions() get added to.

I hope this clarifies it a bit further.

**Comment by sancar** [comment]
@dannyvanleiden Yes, you are right. Now I see the where problem is.  I will send a pr to fix that. 

Probably because registering class definition is not a common usage, we did not came across so far. Note that this usage is only necessary if you are using `writeNullPortable`. See following doc for details. 

https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#null-portable-serialization

**Comment by dannyvanleiden** [comment]
Thank you for confirming the issue and picking it up.

The reason I needed to explicitly register ClassDefinitions was that it could occur that on the first call to `writePortable` for my Portable classes, `writePortable` would be called for one of the fields, with a null value.
Without explicitly registering the ClassDefinition, `ClassDefinitionWriter.writePortable` would then be called, throwing a 'HazelcastSerializationException' because it was passed a null value.
