### ISSUE TITLE
Make reconnect mode off with client failover config failfast

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#16834]
If client failover config is provided, and user also make reconnect mode `off`, this is an invalid configuration. 
Client Failover config has to have a Reconnect Mode on. 
We can make this config failfast to warn to user before client  opens.

**Comment by pertsodian** [comment]
I think we can throw exception (e.g. `IllegalArgumentException`) in `ClientFailoverConfig#addClientConfig` and `ClientFailoverConfig#setClientConfigs` if input `ClientConfig` has `getConnectionStrategyConfig().getReconnectMode() == OFF`

Does that sound ok? I can make the PR.

**Comment by sancar** [comment]
Hi @pertsodian ,
Thanks for interesting in sending a pr. 
Hazelcast has an exception  for this kind of cases  -> `InvalidConfigurationException` .  
It is not possible to read ClientConfig in ClientFailoverConfig setter methods. You are gonna need to add the check to somewhere that these two are used together. 
See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/HazelcastClient.java#L405

This should be the only single entry point if I am not mistaken. Please check the code for usages of these two configs to make sure they can not be set from anywhere else.

**Comment by pertsodian** [comment]
@sancar If I understand correctly, you either use `ClientConfig` or `ClientFailoverConfig`, but not both (see (HazelcastClient.java#L472)[https://github.com/hazelcast/hazelcast/blob/a5b46106076ee417bf197b1f346becf3dc06c340/hazelcast/src/main/java/com/hazelcast/client/HazelcastClient.java#L472] which is called in `HazelcastClient#newHazelcastClientInternal`

`ClientFailoverConfig` has a list of `ClientConfig`s, each will be attempted to connect. If fail, then try the next client config, hence the name.

`ClientConfig#getConnectionStrategyConfig` and `ClientConnectionStrategyConfig#getReconnectMode` are all public, so we should be able to add the validation in client config setters of `ClientFailoverConfig` ?

**Comment by sancar** [comment]
Yes, you are right. Sorry for my first comment. Your first suggestion was correct. We can check this in the  setters of client failover config(ClientFailoverConfig#addClientConfig and ClientFailoverConfig#setClientConfigs) as you suggested.

**Comment by pertsodian** [comment]
Thanks @sancar. I have raised https://github.com/hazelcast/hazelcast/pull/16886
