### ISSUE TITLE
Use returned object from ManagedContext#initialize method

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#16845]
All codebase should be scanned to find missing places. It is legitimate to return a new object from `initialize` method in some contexts, for example as in spring context a matching bean can be returned from `initialize` method while passed object to that method is left intact.

**Comment by pertsodian** [comment]
Hi, I can work on this one.

**Comment by pertsodian** [comment]
@ahmetmircik Sorry I have a question. Can we safely change the method signature of `ManageContext#initialize` from `Object initialize(Object obj);` to `<T> T initialize(T obj)` ?

This will help to avoid casting Object to wanted class everywhere else.

**Comment by pertsodian** [comment]
Actually, `SpringManageContext` delegates the initialization to `AutowireCapableBeanFactory`, which indicates that the returned object might wrap the input one. So I guess it is NOT safe to assume the returned object of `ManagedContext#initialize` will always be the same as the its input.

```
	/**
	 * Initialize the given raw bean, applying factory callbacks
	 * such as {@code setBeanName} and {@code setBeanFactory},
	 * also applying all bean post processors (including ones which
	 * might wrap the given raw bean).
	 * <p>Note that no bean definition of the given name has to exist
	 * in the bean factory. The passed-in bean name will simply be used
	 * for callbacks but not checked against the registered bean definitions.
	 * @param existingBean the existing bean instance
	 * @param beanName the name of the bean, to be passed to it if necessary
	 * (only passed to {@link BeanPostProcessor BeanPostProcessors})
	 * @return the bean instance to use, either the original or a wrapped one
	 * @throws BeansException if the initialization failed
	 */
	Object initializeBean(Object existingBean, String beanName) throws BeansException;
```
