### ISSUE TITLE
ServiceLoader round-trips URL to URI and loses associated URLStreamHandler

### ISSUE THREAD

**Issue by ulfjack** [hazelcast/hazelcast#16846]
I'm trying to load Hazelcast from a custom ClassLoader that is not backed by a file. Hazelcast calls ```ClassLoader.findResource``` to read the corresponding service descriptions from the ```.jar``` ```META-INF``` directory (like ```META-INF/services/com.hazelcast.instance.impl.NodeExtension```). Unfortunately, the Hazelcast class ```com.hazelcast.internal.util.ServiceLoader``` first converts the URL to a URI, and then converts it back to a URI. If I return a URL with an associated URLStreamHandler, then that gets lost in the conversion process (because URI doesn't support it).

From the source code, it's not readily apparent why this is the case.

The only workaround seems to be to create a custom URLStreamHandlerFactory in the Jvm.

**Comment by mmedenjak** [comment]
Seems this was introduced [here](https://github.com/hazelcast/hazelcast/pull/2757/files#diff-c65f883247a8a0ee77203d603292ad88R118) by @sancar . Sancar, do you remember the reasoning?

**Comment by sancar** [comment]
Unfortunately I don't remember. From the heading of the pr, I assume that changes were accidental when trying to fix a checkstyle/findbugs issue.

**Comment by mmedenjak** [comment]
Thank you Sancar! @ulfjack care to send a PR?
