### ISSUE TITLE
hot restart member java.lang.IllegalStateException: Node failed to start

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#16852]
hot restart test, 
http://jenkins.hazelcast.com/view/hot-restart/job/hot-bounce/50/console

where i kill -9 all cluster members, and restart. 
after a few rounds of this, it fails with

fail HzMember3HZ java.lang.IllegalStateException: Node failed to start!

maybe, some times the cluster is not killed quick enough so the partition table changes just before all cluster members are killed, which leads to Node failed to start.

http://54.147.27.51/~jenkins/workspace/hot-bounce/4.0/2020_04_01-04_16_35/bounce/go

i see passing / fail run's on 4.0 and 4.0.1 and master

**Comment by vbekiaris** [comment]
Fixed in `master` by https://github.com/hazelcast/hazelcast-enterprise/pull/3571

**Comment by linking12** [comment]
I also have this problem in version 4.0.2; What can I do to avoid this problem？ 🙏

**Comment by mmedenjak** [comment]
What's the full stack trace of your error @linking12 ? I believe `java.lang.IllegalStateException: Node failed to start` can have multiple causes and we've fixed only one cause here.

As for the particular case we've fixed, you can upgrade to 4.0.3, which should be released beginning of next week.

**Comment by mmedenjak** [comment]
@linking12 Hazelcast 4.0.3 was released yesterday.
