### ISSUE TITLE
Detecting if a config file is member or client config

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#16866]
When auto-configuring Hazelcast instances, we need to check if a config file is member or client config in order to properly initialize a Hazelcast member or client instance. A public API would be good to detect this.

Please see the related issue and PR:

https://github.com/spring-projects/spring-boot/issues/20856
https://github.com/spring-projects/spring-boot/pull/20881

**Comment by mmedenjak** [comment]
Closing as fixed by the added API. We can open new issues in case we see cases which can be improved.
