### ISSUE TITLE
Improve SQL protocol safety

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#16868]
Currently, we have no guarantees that a message has been delivered to the target member. It means, that the SQL query may hang in cases when there is a message loss (e.g. due to dropped connection), but no membership changes.

A potential solution could be to add counters to track lost messages.

**Comment by devozerov** [comment]
+ Make sure to implement tests that are currently disabled (search for the ticket number in the code base).

**Comment by viliam-durina** [comment]
Closing as this applied to IMDG SQL engine in 4.2
