### ISSUE TITLE
java.lang.IllegalStateException: Unknown protocol: CP2

### ISSUE THREAD

**Issue by letanloc1998** [hazelcast/hazelcast#16899]
**Describe the bug**
Get error when using JHiptser with Hazelcast
java.lang.IllegalStateException: Unknown protocol: CP2

**Expected behavior**

**To Reproduce**

**Additional context**

**Comment by mesutcelik** [comment]
Hi @letanloc1998 , Can you please provide more info about your setup?
Which Jhipster version are you using? Are you getting the exception when you connect to hazelcast cluster?

**Comment by letanloc1998** [comment]
When I try connect with mancenter
I can't fix this error and I can't see any same problem so I'm not using mancenter ~~
This is difficult to use Hazelcast ~~

**Comment by mmedenjak** [comment]
@letanloc1998 sorry that you're having troubles but if you are able, please provide us with more information. We haven't encountered that issue but still, we would like to fix it.
