### ISSUE TITLE
Allow to override multicast configuration by system property

### ISSUE THREAD

**Issue by carstenartur** [hazelcast/hazelcast#16898]
**Please describe the problem you are trying to solve**
...Changing the test environment of a build server now thousands of tests are trying to connect to each other because of the default=on multicast support. 

**Please describe the desired behavior**
...It would be cool if there was a java system property to override the configured default to off

**Describe alternatives you've considered**
...Alternatives are to change the network default to drop UDP or to change a lot of tests to explicitly switch off multicast support

**Comment by mmedenjak** [comment]
Hi @carstenartur ! 

Since there's no system property that is specifically designed to turn off multicast (or any other join strategy), I suggest you try using variables/placeholders in your configuration (https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#using-variables). That way, you can set up the configuration to use both join mechanisms and then control which one gets used with a system property (or JVM argument, I'm not 100% sure).

Can you try it out?

**Comment by carstenartur** [comment]
Hi @mmedenjak ,
thanks for your suggestion. We already use variables but not to switch off multicast. The problem is that we have a lot of copies of code in tests that use hard coded hazelcast instantiation like this or similar to test different aspects of the hazelcast usage:

@Bean(name={"hazelcast"}) 
	public com.hazelcast.config.Config myhazelCastConfig() {
		com.hazelcast.config.Config hazelcast = new com.hazelcast.config.Config()
				.setInstanceName("instance")
				.addMapConfig(new MapConfig()
						.setName("eposmemory")
						.setMaxSizeConfig(new MaxSizeConfig(200,MaxSizeConfig.MaxSizePolicy.FREE_HEAP_SIZE))
						.setEvictionPolicy(EvictionPolicy.LRU)
						.setTimeToLiveSeconds(20));
		
		return hazelcast;
	}

	@Bean(name={"instance"}) 
	public HazelcastInstance myHazelcastinstance(com.hazelcast.config.Config hazelcast) {
		HazelcastInstance newHazelcastInstance = Hazelcast.getHazelcastInstanceByName("instance");
		if(newHazelcastInstance == null)
			newHazelcastInstance = Hazelcast.newHazelcastInstance(hazelcast);
		server.setClusterInstance(newHazelcastInstance);
		return newHazelcastInstance;
	}

Unfortunately such a configuration creates a Multicast configuration to be active (default=on) although it is not recommended way to setup hazelcast and not explicitly requested. Since we migrated our jenkins servers to a new site with different network configuration we have heavy problems with test instances to connect to each other. What I have to do here is to change all the code to add a multicast configuration to be switched off. I can (will) do it. However this issue is a request to add support for a system property to change the default configuration in case there is no explicit configuration for it to off.
If you think that does not make sense we can close  this issue. I know how to help myself even it is now a lot of work.

**Comment by mmedenjak** [comment]
I will admit this does not sound like something of high priority and I don't see a clear way forward. I can imagine that _some_ users might argue that the programmatic configuration should override the system properties whilst others might argue that it should be the other way around.

Given that it's not clear how to proceed and that we already have support for variables which partially addresses this scenario, I'll park this issue in Backlog and we'll see if it gets more support from other users.

**Comment by carstenartur** [comment]
Yes, I agree. However problem is that the default that has been choosen to be active in case it is *not* explicitly defined has issues: The nodes started in tests try to connect to each other. The defaults should lead to a safe state with no unintended connections.
So from my point of view there is a clear way forward. Either change the default to have *no* multicast configuration active (that would be consequent as multicast is not recommended as per hazelcast documentation..) or allow to change the default using a system property what would be a more careful approach with full backwards compatibility. So the systemproperty should only be used in case no programmatic and no config file setting regarding multicast is available.

**Comment by mmedenjak** [comment]
We're not going to change the defaults in the near future as it would be a breaking change that we cannot introduce until a new major version is out and multicast has proven to be a great way to get started using Hazelcast as you don't need any additional configuration. Still, as I mentioned, I'll keep this issue open to see if we need to reconsider.

**Comment by carstenartur** [comment]
Yes, thanks!

**Comment by carstenartur** [comment]
Btw, what is the best practice in case of using hazelcast for hibernates cache implementation to prevent this problem? If I use https://github.com/hazelcast/hazelcast-hibernate5/blob/master/hazelcast-hibernate53/src/main/java/com/hazelcast/hibernate/HazelcastLocalCacheRegionFactory.java
I have neither a hazelcast config nor explicit code and that way every test starts another hazelcast instance using multicast. Some database tests have dozens of active hazelcast instances connecting to each other this way.

**Comment by mmedenjak** [comment]
In most of our tests, we mock the network so we can run multiple tests in parallel without them interfering with each other. Some tests require real network and we run these serially as we don't want instances from different tests to interact. Even though they might be configured so they don't form a cluster (different cluster names), they will still send multicast packets and it will show up in the test logs. 
We distinguish between these two by using different JUnit runners. For instance, this test uses mock network so it can run all test methods in parallel as well as run with other tests in parallel with each test in a different JVM - https://github.com/hazelcast/hazelcast/blob/0877618cd4ab08f3690ce8642152895293d1a4bd/hazelcast/src/test/java/com/hazelcast/client/protocol/ClientMessageTest.java#L36-L38.

On the other hand, this test uses real network so it needs to run in isolation - https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/test/java/com/hazelcast/internal/ascii/RestCPSubsystemTest.java#L63-L65

As you can see, all (most) tests extend `HazelcastTestSupport` which is where the config can be manipulated before starting the instance.

Now, if that still doesn't sound like usable to you, you can always try to do something more hacky like attaching an agent which will change the value of the `MulticastConfig#DEFAULT_ENABLED` field when loading the class. For instance, we use an agent to remove some final modifiers - https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/test/java/com/hazelcast/test/compatibility/CompatibilityTestUtils.java#L31-L55.

**Comment by carstenartur** [comment]
Thanks Matko for sharing all these very good ideas! Though I must say that imho the usage of "System.setProperty(..)" in a static section especially in parallel tests is extremely dangerous. 
(See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java).
However I am sure I can reuse some of your ideas.

**Comment by mmedenjak** [comment]
Fixed with https://github.com/hazelcast/hazelcast/pull/17348, closing.
