### ISSUE TITLE
hazelcast-client:4.0 is missing

### ISSUE THREAD

**Issue by hendrikebbers** [hazelcast/hazelcast#16922]
Looks like the hazelcast-client 4.X was not released. For the Hazelcast server and Hazelcast-hibernate5 artefacts we can migrate to Hazelcast 4 but there is not client artefact at Maven central (or JCenter). [Your documentation](https://hazelcast.org/imdg/clients-languages/java/) already mentions version 4.0.1 of the hazelcast-client but I can not find it anywhere.

**Comment by mmedenjak** [comment]
@hendrikebbers since hazelcast 4.0, the client has been merged into the `hazelcast` JAR (see [here](https://github.com/hazelcast/hazelcast/pull/15366). The website needs to be updated and thank you for letting us know, I'll get someone to do it.

**Comment by hendrikebbers** [comment]
THX @mmedenjak
