### ISSUE TITLE
Hazelcast eviction policy not working on 3.7.8 version for used heap size

### ISSUE THREAD

**Issue by lata4** [hazelcast/hazelcast#16934]
**Describe the bug**
Hazelcast eviction policy not working on 3.7.8 version for used heap size

**Expected behavior**
eviction should happen once used heap size is breached

**To Reproduce**

My config:
```java
 config.setInstanceName(hazlecastInstanceName)
                  .addMapConfig(new MapConfig()
                    .setName(productCacheConfig)
                .setMaxSizeConfig(new MaxSizeConfig(1, 
  MaxSizeConfig.MaxSizePolicy.USED_HEAP_SIZE))
                   .setEvictionPolicy(EvictionPolicy.LRU).setTimeToLiveSeconds(600));
```

Common details that we're often interested in:

- Cluster size, 1
- Version of Java. 1.8

Checking through management center ,new entries do not enter the map once map size is breached but old entries are not evicted with LRU.Please help.

**Comment by ahmetmircik** [comment]
@lata4 can you please share a reproducer for the expected behavior?

**Comment by mmedenjak** [comment]
@lata4 any updates on the issue?

**Comment by ahmetmircik** [comment]
Please try with latest version, if that doesn't help, you can see this similar issue https://github.com/hazelcast/hazelcast/issues/15715
