### ISSUE TITLE
Add tests to verify that ordering of the enums used in the protocol does not change

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#16933]
We should determine the enums used in the protocol and add tests to verify that their ordering or the value does not change in a way that may result in compatibility problems. 

In the client protocol we represent enums with integer values which generally reflects their ordering. So, for backward compatibility, it is important to make sure that they are consistent across Hazelcast versions.

**Comment by mmedenjak** [comment]
@mdumandag @sancar does this issue need to go into 5.0?

**Comment by mdumandag** [comment]
@mmedenjak I don't think this is really important for 5.0, we can do it afterwards.
