### ISSUE TITLE
NotEqualPredicate is missing getAttribute method

### ISSUE THREAD

**Issue by StephenOTT** [hazelcast/hazelcast#16945]
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/query/impl/predicates/NotEqualPredicate.java

compared to:

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/query/impl/predicates/EqualPredicate.java#L141

It does not seem possible to get the attribute that a NotEqualPredicate is applied to.

**Comment by StephenOTT** [comment]
Seems to be inconsistently applied..

GreaterLessPredicate and BetweenPredicate has the getAttribute method.

Missing:
NotEqualPredicate
RegexPredicate
LikePredicate
ILikePredicate
InPredicate
NotPredicate

**Comment by StephenOTT** [comment]
NotPredicate does not even contain/collect the attribute property
`SqlPredicate("age NOT IN (20)")`

**Comment by mmedenjak** [comment]
Hi @StephenOTT !

`EqualPredicate` and `NotEqualPredicate` are private (internal) classes. As a rule of thumb, everything in `impl` or `internal` package is internal. Why do you need `getAttribute()`?

**Comment by jerrinot** [comment]
I'm closing this ticket for inactivity of the reporter. 

Predicates classes are internal. please use the [`Predicates`](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/query/Predicates.java#L180) factory to construct predicates. 

If you have a use-case where you need to know the attribute then feel-free to reopen this issue.
