### ISSUE TITLE
Documentation on Health monitor interval

### ISSUE THREAD

**Issue by ceeaspb** [hazelcast/hazelcast#16956]
**Describe the bug**
Minor issue in that the documentation says that the health monitor is default 30 seconds interval while the code shows it is 20 seconds.

**Expected behavior**
Documentation should reflect the code.

HEALTH_MONITORING_DELAY_SECONDS

https://github.com/hazelcast/hazelcast/blob/eb8ffc40b2e2d7ccfa21e2acfd663bfff1496c6b/hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java#L197

https://docs.hazelcast.org/docs/latest/manual/html-single/#health-monitor

**Comment by Serdaro** [comment]
Thanks a lot for reporting @ceeaspb . Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/1644644da7edc4819f93907cab3d505667254a3b
