### ISSUE TITLE
Predicates do not have managed context injection when predicate is local/not serialized

### ISSUE THREAD

**Issue by StephenOTT** [hazelcast/hazelcast#16957]
a placeholder for coming PR.

When a Predicate is created that expects to have Dep Injection with ManagedContext, if the Predicate is only used in the local JVM, and not serialized to another node, then the Predicate does not receive Dep Injection with managed context.

cc @mmedenjak

**Comment by mmedenjak** [comment]
Thanks for the report. I've added the `first good issue` if someone wants to get started since it should be fairly straightforward. Here's an example - https://github.com/hazelcast/hazelcast/blob/0384245b66c0d06c56bf9c205fc7facf8ff8585e/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L945-L947.

**Comment by Holmistr** [comment]
@StephenOTT Thanks for the issue. To be clear, you wrote `a placeholder for coming PR.`

Does it mean that you're already working on it and you'll be submitting a PR? If so, I would assign this issue to you so nobody else would work on it. Please confirm :)

**Comment by StephenOTT** [comment]
I had planned to write a PR. I have not started it yet.

**Comment by raghu-megh** [comment]
Hello,

I am planning to work on this. How to go abt it? Whatever @mmedenjak  has written is already in the codebase.

Please give me instructions.

Raghuram

**Comment by mmedenjak** [comment]
Hi @raghu-megh ! The example on how it should be done is above and it should be done in both `MapProxyImpl` and `ClientMapProxy`. Also, tests need to be added. Now, better agree with @StephenOTT on who will deliver the fix.

**Comment by StephenOTT** [comment]
I have not started it yet. So if you want to start it please feel free.

**Comment by raghu-megh** [comment]
> Hi @raghu-megh ! The example on how it should be done is above and it should be done in both `MapProxyImpl` and `ClientMapProxy`. Also, tests need to be added. Now, better agree with @StephenOTT on who will deliver the fix.

I have the changes done in both the classes now, now should I follow com.hazelcast.map.impl.journal.AdvancedMapJournalTest.testBackupSafety() test case to test this? What should I assert?

Sorry, if these are basic questions but am learning.

Thanks,
Raghuram

**Comment by mmedenjak** [comment]
`AdvancedMapJournalTest.testBackupSafety` is something completely unrelated. You should create a test which sets up a managed context, starts a single member and then invokes some IMap method with Predicate and Projection. In the end you can assert that the managed context was invoked. Here's a similar test but for another data structure - https://github.com/hazelcast/hazelcast/blob/16ae47b145428d7b9edd9a4b3d91caee259d816b/hazelcast/src/test/java/com/hazelcast/durableexecutor/DurableExecutorServiceTest.java#L265-L280.

**Comment by aditya-32** [comment]
hi @StephenOTT   can you please review the PR

**Comment by srknzl** [comment]
@aditya-32 @mmedenjak is not working at Hazelcast anymore.
