### ISSUE TITLE
SQL: Add member compatibility check to plan

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#16976]
As we add new operators, expressions, and optimizations, the plan generated on a new member may become invalid for the older member. We should implement a generic approach to compatibility handling to ensure that an invalid plan is never sent to a member. 

Rough proposal:
1. When the optimization is started, get the oldest version present in the cluster and add it to the optimization context
1. When a protocol change is introduced (e.g. new operator), we should check whether there is an older version in the cluster. If yes, then we either throw an appropriate exception (e.g. "The operation is not supported on member X of version Y"), or fallback to the previous implementation (e.g. do not do an optimization that will create an unsupported operator, and pick less optimal operator instead)

This task should be implemented before we declare backward compatibility for the SQL feature.

**Comment by mmedenjak** [comment]
Can we use cluster version here? It's supposed to be an indication when certain features introduced in a new version can be used.

**Comment by devozerov** [comment]
Yes, perhaps we will use cluster versions.
