### ISSUE TITLE
Touching an IMap entry with an EntryProcessor changes the TTL

### ISSUE THREAD

**Issue by keteracel** [hazelcast/hazelcast#16987]
**Describe the bug**
Using Hazelcast 4, we noticed the behavior has changed when setting explicit TTLs on IMap entries. Previously, an explicit TTL would be maintained after EntryProcessors operated on the entries. Now  it looks like some very long TTL is applied on calling Entry.setValue(...) in an EntryProcessor.

**Expected behavior**
In Hazelcast 3, the observed behavior is that the TTL is unchanged by an EntryProcessor operating on an entry.

**To Reproduce**
I wrote simple test cases:
Hazelcast 3: https://github.com/keteracel/hazelcast4-tests/blob/master/hz3-tests/src/test/java/hz3/tests/TTLTest.java
Hazelcast 4: https://github.com/keteracel/hazelcast4-tests/blob/master/hz4-tests/src/test/java/hz4/tests/TTLTest.java

Result for HZ3:
![image](https://user-images.githubusercontent.com/195521/81992145-af603500-95f7-11ea-9cbd-6f0de17a5c60.png)

Result for HZ4:
![image](https://user-images.githubusercontent.com/195521/81992286-fbab7500-95f7-11ea-81a7-c983ed0cf145.png)

I didn't see anything in migration guides that suggest this is an expected change.

**Comment by keteracel** [comment]
Adding a sysout before and after the processor we see the following:
`EntryView{key=key1, value=value1, cost=86, creationTime=1589498008000, expirationTime=1589498018000, hits=2, lastAccessTime=1589498008000, lastStoredTime=0, lastUpdateTime=1589498008000, version=1, ttl=10000, maxIdle=9223372036854775807}
EntryView{key=key1, value=value2, cost=86, creationTime=1589498008000, expirationTime=9223372036854775807, hits=3, lastAccessTime=1589498008000, lastStoredTime=0, lastUpdateTime=1589498008000, version=2, ttl=9223372036854775807, maxIdle=9223372036854775807}`

Note that not only does the ttl change, but the expirationTime also changes to a very large number.

**Comment by ahmetmircik** [comment]
Please see related issue: https://github.com/hazelcast/hazelcast/issues/10965.
Unlike before, in 4.0, updates without ttl cancels previously set ttl of an entry. 

I will check migration guide and will add this if this was missed.

**Comment by keteracel** [comment]
Hi @ahmetmircik, thanks for the reply but this is not a `put`, this is an `executeOnKey`. I do not see where I can set a ttl along with `<R> R executeOnKey(@Nonnull K key,
                       @Nonnull EntryProcessor<K, V, R> entryProcessor);`.

**Comment by ahmetmircik** [comment]
Only name of the method is different in this case, `executeOnKey` is doing update  like ordinary `put`. If we only change behavior on entry-processor(EP) side, this will be inconsistent behavior with other update operations. Instead we can add ttl changing capability to passed entry, for example. 

First, this can be a new interface:
```
interface ExtendedMapEntry {
    V setValue(V value, long ttl, TimeUnit timeUnit)
}
```

And its usage example:
```
@Override
public String process(Entry<String, String> entry) {
    return ((ExtendedMapEntry<String, String>) entry).setValue(newValue, 1, TimeUnit.HOURS);
}
```

WDYT?

**Comment by keteracel** [comment]
This would work. And +1 for consistency.

**Comment by keteracel** [comment]
Hi @ahmetmircik, @mmedenjak and @vbekiaris. This is a blocker for us moving to hazelcast 4. Do you think it would be appropriate for me to create a pull request to merge into the 4.0.2 branch?

**Comment by mmedenjak** [comment]
@keteracel yes, feel free to send a PR with the same commit for the `4.0.z` branch. Unfortunately, 4.0.2 is frozen and about to be released any day now but it'll be included in 4.0.3.

**Comment by eleftherias** [comment]
@mmedenjak Is there a suggested workaround we can use until 4.0.3 is released?

**Comment by mmedenjak** [comment]
@eleftherias not sure but maybe it's worth mentioning we're starting release verification for 4.0.3 and it should be released next week. Let us know if that doesn't work for you and we might consider workarounds.

**Comment by eleftherias** [comment]
Thanks @mmedenjak. I'm adding Hazelcast 4 support to [Spring Session](https://github.com/spring-projects/spring-session), which will be released on Wednesday next week.
If 4.0.3 is out before Wednesday, that would be great. 
If not, I'm still looking for a workaround.

**Comment by mmedenjak** [comment]
It depends if we start release verification today, I'll let you know later today or on Monday if we're able to release by Wednesday. If we haven't started release verification by Monday or if we encounter some issues, I'll try to find some workaround. Feel free to remind me if I forget to let you know :)

**Comment by eleftherias** [comment]
@mmedenjak How is the release going? Do you have an expected release day for 4.0.3?

**Comment by mmedenjak** [comment]
We started release verification today. Optimistically we will release on Thursday. If that's already too late, I'll take a look for a workaround tomorrow.

**Comment by eleftherias** [comment]
Thanks for the update @mmedenjak! 
Thursday is too late for us to include 4.0.3. 
If you are able to provide a workaround I would appreciate it.

**Comment by mmedenjak** [comment]
@eleftherias I don't see a good way around it. I think your only option is to invoke `IMap#setTtl` for every mutated entry *after* the EP has completed execution. You probably don't want to invoke the `setTtl` method from inside the entry processor as it might cause a deadlock.
If there are many keys for which you want to update TTL, you best group them by owning member. Then you can execute a task on the owning members which will set the TTL locally. Something like this:

```java
public class Lala {

    public static final String MAP_NAME = "map";

    public static void main(String[] args) {
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        Set<String> keysToUpdate = new HashSet<>();
        keysToUpdate.add("a");
        keysToUpdate.add("b");
        keysToUpdate.add("c");

        IMap<String, String> map = instance.getMap(MAP_NAME);
        map.executeOnKeys(keysToUpdate, e -> {
            // update the entry
            e.setValue(e.getValue());
            return null;
        });

        Map<Member, List<String>> keysByMember = groupKeysByMember(instance, keysToUpdate);
        for (Entry<Member, List<String>> entry : keysByMember.entrySet()) {
            Member owningMember = entry.getKey();
            List<String> keys = entry.getValue();
            instance.getExecutorService("ttlSettingExecutor")
                    .executeOnMember(new TTLSettingRunnable(keys), owningMember);
        }
    }

    private static Map<Member, List<String>> groupKeysByMember(HazelcastInstance instance, Set<String> keysToUpdate) {
        PartitionService partitionService = instance.getPartitionService();
        return keysToUpdate.stream()
                   .collect(Collectors.groupingBy(key -> partitionService.getPartition(key).getOwner()));
    }

    private static final class TTLSettingRunnable implements Serializable, Runnable, HazelcastInstanceAware {
        private HazelcastInstance hazelcastInstance;
        private final List<String> keys;

        public TTLSettingRunnable(List<String> keys) {
            this.keys = keys;
        }

        @Override
        public void run() {
            IMap<Object, Object> map = hazelcastInstance.getMap("map");
            keys.forEach(key -> map.setTtl(key, 1, TimeUnit.SECONDS));
        }

        @Override
        public void setHazelcastInstance(HazelcastInstance hazelcastInstance) {
            this.hazelcastInstance = hazelcastInstance;
        }
    }
}
```

This way, you would avoid a network hop for every mutated entry for which you wanted to set a TTL and just set the TTL locally on the members. Still, this approach might be problematic if there were other operations on the entries between the EP execution and the time the TTL was set.

Alternatively, if you can wait for an additional day for the 4.0.3 release, I guess that would be better :)

**Comment by mmedenjak** [comment]
Hazelcast 4.0.3 was released yesterday.
