### ISSUE TITLE
IMap#addIndex should fail fast for IndexType#BITMAP on HD

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#17032]
seen during investigation of https://github.com/hazelcast/hazelcast-enterprise/issues/2937

**Comment by KowalczykBartek** [comment]
the link is broken

**Comment by mmedenjak** [comment]
@KowalczykBartek it's in a private repo. Maybe @ahmetmircik can give you some pointers on how to add this check.

**Comment by ahmetmircik** [comment]
@KowalczykBartek, link is referring the issue investigated. It doesn't help much for this issue.

Here, as a solution, i was thinking `addIndex` should fail fast, if BITMAP index is asked for a map with NATIVE in-memory-format. 

Thanks for looking into this.
