### ISSUE TITLE
BITMAP index statisctics is not propagated to the LocalMapStats

### ISSUE THREAD

**Issue by erkangurgen** [hazelcast/hazelcast#17047]
**Describe the bug**
The statistics of a BITMAP index is not reflected into the LocalMapStats. This behavior seems to be occurring due to the implementation difference between getRecords() and evaluate() methods on AbstractIndex.java. While getRecord() invokes stats.onIndexHit(), evaluate() method does not have any calls to the stats.onIndexHit().

**Expected behavior**
The operations on Map are expected to be reflected into BITMAP index statistics as reflected into the standard index stats. 

**To Reproduce**

1. Add an index to a Map.
```java 
        IMap<String, MapEntryIndexed> map = hz.getMap("indexedMap");
        map.addIndex("label", false);
```
2. Perform some operations on Map
3. Print LocalMapStats, observe indexStats
```java
        System.out.println(map.getLocalMapStats());
```
4. Repeat step 1,2 and 3. Add BITMAP index instead of standard index
```java
        map.addIndex("BITMAP(label)", false);
```
        
**Additional context**
Tested on Hazelcast v3.12.6

**Comment by sertugkaya** [comment]
ZD 6270

**Comment by mmedenjak** [comment]
@taburet how complicated is this? I see you mentioned "that could be a potential enhancement and should be pretty easy to implement" but I remember us talking about bitmap stats before:
> index memory statistics, bitmap index memory usage is highly dependent on the layout/distribution of the inserted entries, for instance it might cost a single long for every 64 entries if the data is dense, so the cost might be just a single bit for every inserted entry, that's hard to express it in our current memory cost tracking implementation, since we assume that index entries are not sharing the underlying storage and the index memory cost is directly proportional to the number of entries plus the size of each individual entry (computed as deltas, adding the cost on insertion, subtracting the cost on removal), even if it was possible to express it, it's really costly to compute the exact cost, so the performance would be bad, we can "fake" it by assuming for instance equal probability of entries, but that would be really imprecise

But I might be mixing up things.

**Comment by taburet** [comment]
@mmedenjak I believe this specific issues is about query/hits stats and that is pretty easy to implement. Memory usage stats are harder, most likely there is no performant and precise way of doing it live during the index mutation, something like an on-demand stats (when a user explicitly asks to compute the cost) looks like a better way.
