### ISSUE TITLE
Connection-strategy=ASYNC doesn't throw HazelcastClientOfflineException for Unisocket 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#17046]
When smart routing is disabled, connection strategy=ASYNC doesn't throw HazelcastClientOfflineException, instead, client invocation timeout is considered. 

When the client with the same configuration is changed to smartRouting=true, the behavior becomes as expected; any call to Hazelcast throws HazelcastClientOfflineException immediately. 

The issue doesn't reproduce with Hazelcast 4.0.

For reproducer, you can use the following example config: 

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setClusterName("oz");
        clientConfig.getNetworkConfig()
                .setAddresses("127.0.0.1")
                .setSmartRouting(false)
                .setConnectionTimeout(5000);

        ConnectionRetryConfig retryConfig = new ConnectionRetryConfig();
        retryConfig.setEnabled(true);
        retryConfig.setInitialBackoffMillis(1000);
        retryConfig.setMaxBackoffMillis(30000);
        retryConfig.setMultiplier(2);
        retryConfig.setFailOnMaxBackoff(false);
        retryConfig.setJitter(0.2);

        clientConfig.getConnectionStrategyConfig()
                .setAsyncStart(false)
                .setReconnectMode(ClientConnectionStrategyConfig.ReconnectMode.ASYNC)
                .setConnectionRetryConfig(retryConfig)

**Comment by sancar** [comment]
@yozank If this was not a problem for 4.x series, I would like to close it since 3.12 support is ended.

**Comment by mmedenjak** [comment]
@yozank can we close the issue based on Sancar's suggestion?
