### ISSUE TITLE
SQL: Implement Calc operator

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17058]
`Calc` operator is a convenient operator that merges adjacent `Project` and `Filter` operators and eliminates the common sub-expressions. We should support it to allow for more flat execution trees. Such trees will require less memory and CPU resources to execute. 

Implementation plan:
1. Add Apache Calcite optimization rules: `FilterCalcMergeRule`, `ProjectCalcMergeRule`, `FilterToCalcRule`, `ProjectToCalcRule`
1. Consider adding a custom `Calc-Calc` merge rule, see `FlinkCalcMergeRule` in Apache Flink for example
1. Add logical and physical converter rules. Be careful with trait propagation for physical `Calc`
1. Implement the backend: `CalcPhysicalNode`, `CalcExec`

The task is not mandatory for 4.1. It could be moved further if needed.

**Comment by Fly-Style** [comment]
bump
