### ISSUE TITLE
The hazelcast-client.xml fails to load using Spring boot 2.2.6 & hazelcast server/client v4.0.1 [HZ-821]

### ISSUE THREAD

**Issue by mobasherswl** [hazelcast/hazelcast#17051]
**Description**
When [hazelcast-client.zip](https://github.com/hazelcast/hazelcast/files/4734427/hazelcast-client.zip) is provided in spring boot application properties file & packaged as boot jar then the hazelcast provider fails to load the file as it doesn't allow "jar" URI scheme. Following is the method in **AbstractHazelcastCachingProvider** class that throws exception when the URI starts with "jar"

```java
    protected URL getConfigURL(URI location, @Nonnull ClassLoader classLoader)
            throws URISyntaxException, IOException {
        String scheme = location.getScheme();
        if (scheme == null) {
            // interpret as place holder
            location = new URI(System.getProperty(location.getRawSchemeSpecificPart()));
            scheme = location.getScheme();
        }
        URL configURL;
        if ("classpath".equals(scheme)) {
            configURL = classLoader.getResource(location.getRawSchemeSpecificPart());
        } else if ("file".equals(scheme) || "http".equals(scheme) || "https".equals(scheme)) {
            configURL = location.toURL();
        } else {
            throw new URISyntaxException(location.toString(), "Unsupported protocol in configuration location URL");
        }
        return configURL;
    }
```

**Expected behavior**

It should be able to handle the "jar" URI scheme.

**To Reproduce**

Steps to reproduce the behavior, assuming a spring boot application is available with required depedencies & [hazelcast-client.zip](https://github.com/hazelcast/hazelcast/files/4734427/hazelcast-client.zip):

1. Add spring.cache.type=jcache
2. Add spring.cache.jcache.provider=com.hazelcast.client.cache.impl.HazelcastClientCachingProvider
3. Add spring.cache.jcache.config=classpath:hazelcast-client.xml
4. Build a boot jar
5. Run the above jar

**Additional context**

- Java 8
- Spring Boot 2.2.6-RELEASE
- Hazelcast version server/client: 4.0.1
- [hazelcast-client.zip](https://github.com/hazelcast/hazelcast/files/4734427/hazelcast-client.zip)

The stacktrace is as follows:

```java
Caused by: java.net.URISyntaxException: Unsupported protocol in configuration location URL: jar:file:/D:/repo/cmp-service/cmp-rest-impl/build/libs/cmp-rest-impl-0.0.1-SNAPSHOT.jar!/BOOT-INF/classes!/hazelcast/hazelcast-client-dev.xml
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getConfigURL(AbstractHazelcastCachingProvider.java:271)
        at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.getConfigFromLocation(HazelcastClientCachingProvider.java:119)
        at com.hazelcast.client.cache.impl.HazelcastClientCachingProvider.getOrCreateFromUri(HazelcastClientCachingProvider.java:76)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getOrCreateInstanceFromProperties(AbstractHazelcastCachingProvider.java:357)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getOrCreateInstance(AbstractHazelcastCachingProvider.java:321)
        at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.createHazelcastCacheManager(AbstractHazelcastCachingProvider.java:247)
        ... 161 common frames omitted
```

Kindly let me know in case of any details required.

**Comment by mmedenjak** [comment]
Hi @mobasherswl ! Thank you for the report, I've added it to the current milestone so we take a look.

**Comment by leszko** [comment]
How do you put `hazelcast-client.zip` into your project? I miss it. Do you zip your configuration before putting it into the Spring Boot application?

**Comment by mmedenjak** [comment]
@mobasherswl any updates on the issue?

**Comment by mobasherswl** [comment]
The client file is in jar so class path starts with jar prefix. The
hazelcast lib cannot deal with jar class paths.

**Comment by mobasherswl** [comment]
Check AbstractHazelcastCachingProvider.getConfigURL where there as explicit checks

**Comment by mobasherswl** [comment]
Here is a [sample](https://github.com/spring-projects/spring-boot/files/4736179/springboot-hazelcast.zip) project to reproduce the scenario.

**Comment by mmedenjak** [comment]
@mobasherswl thank you for the details. It is true, as mentioned in the spring boot issue, it's something that has to be changed on our side. Still, I don't think this is a critical issue and I'm moving it out of scope. As you noticed, there are alternative and more common ways of providing the configuration by using one of the following schemes: `classpath`, `file`, `http`, `https`.

Still, I'll keep this open as a future enhancement in case there's more community interest. Also, if you're feeling up for it, you can send a PR to add support for the `jar` scheme with an appropriate test.

**Comment by konikvranik** [comment]
Hello, the `classpath:` scheme is no option as I have `hazelcast.xml` packed in my distribution i jar file on classpath. When I reference it by `spring.cache.jcache.config=classpath:hazelcast.xml` or let default value which should be the same, I have the same exception as mentioned above. So there is no option to provide distribution hazelcast config. (using hazelcast v 4.0.3).

The only solution is to force user to unpack the config from distributed archive and put it to workdir os somewhere else and point to it over property.

I don't thing this behavior is just small problem.

**Comment by mmedenjak** [comment]
For now, we're not planning on adding support but please send us a PR if you can as that would speed up the process of fixing this issue.

**Comment by evelknievel** [comment]
We are facing the same problem.
We have a spring boot application with a separate dependency which includes the hazelcast config.
In the IDE it runs fine, as soon as it gets deployed and runned from the jar, we get the exception

`Unsupported protocol in configuration location URL: jar:file:xxxxxx`

To me its quite disturbing this issue is not solved after more than a year.

**Comment by mmedenjak** [comment]
@evelknievel unfortunately there's always many more issues than developers so we have to prioritise. But, I've added this issue to the current scope for re-evaluation. @frant-hartm feel free to see if this can be fixed in the current scope. Repeating myself - @evelknievel if you can send a PR for this, it would speed up the process of fixing this issue.
