### ISSUE TITLE
SQL: Verify the build artifact of the Apache Calcite module

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17065]
1. Verify the content of our assembly 
1. Licenses - check compatibility of the new licences with our legal requirements
1. Check if things like LICENSE, NOTICE, etc. are included in a resulting JAR correctly, i.e. all dependencies are mentioned properly, no accidental file overrides, etc
1. Check for known vulnerabilities for the user versions of dependencies

**Comment by lazerion** [comment]
@Holmistr as checking `4.1-BETA-1` assembly I noticed below under `lib` directory of uploads to download machine after extraction
```
ubuntu@ip-10-0-23-210:/tmp/files/community/hazelcast-4.1-BETA-1/hazelcast-4.1-BETA-1/lib$ ls -ll
total 46036
-rw-rw-r-- 1 ubuntu ubuntu     8038 Sep  4  2020 further-modules.txt
-rw-r--r-- 1 ubuntu ubuntu 11511239 Sep  4  2020 hazelcast-4.1-BETA-1.jar
-rw-r--r-- 1 ubuntu ubuntu 23704698 Sep  4  2020 hazelcast-all-4.1-BETA-1.jar
-rw-r--r-- 1 ubuntu ubuntu   162320 Sep  4  2020 hazelcast-spring-4.1-BETA-1.jar
-rw-r--r-- 1 ubuntu ubuntu 11744428 Sep  4  2020 hazelcast-sql-4.1-BETA-1.jar
```
kindly advise inclusion of `sql` module. 
cc @devozerov

**Comment by devozerov** [comment]
@Holmistr please take a look at the comment https://github.com/hazelcast/hazelcast/pull/17630#issuecomment-701212666 in the related PR. It seems that we have some troubles with LICENCE/NOTICE/MANIFEST files in our artifacts. We need to confirm whether this is a problem or not.

**Comment by devozerov** [comment]
Copy-paste from the mentioned comment:

1. The resulting `MANIFEST.MF` in the `hazelcast-all.jar` doesn't have packages from the `sql` module. Not sure whether this is a problem or not, but looks suspicious
1. Before 4.1 we had `apache-v2-licence.txt` file in the root directory. This is not the case now. Is it ok?
1. The `META-INF/LICENCE` file in the final JAR is ... **Jackson license**, not ours
1. Other JARs that we ship separately (e.g. `hazelcast-spring`, and soon `hazelcast-sql`) **do not have license file at all**!

**Comment by devozerov** [comment]
I continue working on this issue once the PR https://github.com/hazelcast/hazelcast/pull/17630 is merged. Otherwise, the scope of the changes is not clear.

**Comment by devozerov** [comment]
Performed the vulnerability scan with the dependency-check plugin [1]. No vulnerabilities found. 

1) The code:
```
<plugin>
    <groupId>org.owasp</groupId>
    <artifactId>dependency-check-maven</artifactId>
    <version>5.2.4</version>
    <executions>
        <execution>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

2) The command: `mvn verify -DskipTests`

[1] https://jeremylong.github.io/DependencyCheck/dependency-check-maven/

**Comment by devozerov** [comment]
There are two outstanding questions so far: 
1. Whether we need an OSGI metadata in the manifest for the SQL module?
1. What to do with a license? Currently, neither Hazelcast nor 3-rd part licenses are included in the `hazelcast-sql.jar`

For the first question, a separate issue is created https://github.com/hazelcast/hazelcast/issues/17693. The second question will be addressed separately because other modules have similar license problems (e.g. the Spring module).
