### ISSUE TITLE
SQL: Support case-insensitive identifier resolution

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17080]
Currently, we resolve catalog/schema/table/column identifiers in a case-sensitive way. This is not very convenient for users, so we need to resort to case-insensitive resolution:

**Comment by devozerov** [comment]
I tried to implement the case-insensitive resolution and it works mostly works. However, I am still unsure that we need it, so I'd like to ask the community to provide additional opinions.

**Problem Statement**

Hazelcast is a Java-based application. Java identifiers are case-sensitive. Names of distributed objects (maps, indexes) are case-sensitive as well. That is, every identifier in Hazelcast has exactly one string representation.

In contrast, ANSI SQL identifiers without surrounding quotes are normalized to a so-called **case-normal form** (CNF) [1] and then compared in a case-sensitive manner. In SQL an identifier may have many strings representations. E.g. the following identifiers match the table `Employee`: `employee`, `EMPLOYEE`, `"Employee"`.

The problem is: how to map multiple SQL identifiers to a single Java identifier.

**Case-normal form**

SQL defines two ways to define an identifier in the script:
- Unquoted: `SELECT name FROM person`
- Quoted: `SELECT "name" FROM "Person"`

CNF defines a canonical representation of an unquoted identifier, which is the original string converted to upper-case.

SQL identifiers are compared in the following way:
- If the identifier is unquoted, it is converted fo a CNF
- If the identifier is quoted, the quotes are removed
- Resulting strings are compared to each other

Examples:
`employee` -> `EMPLOYEE`
`Employee` -> `EMPLOYEE`
`"Employee"` -> `Employee`

**Proposed solution**
Case-insensitive identifier resolution might be implemented as follows:
- Force Apache Calcite parser to upper-case unquoted identifiers during parsing
- Normalize Hazelcast identifiers (table name, column names) to upper-case as well

**Pros and cons**
The proposed solution will provide case-insensitive resolution of unquoted identifiers, which is in line with ANSI SQL and convenient for users.

The problem is that we will have to map the bigger Java universe to a smaller CNF universe, which may cause conflicts. E.g. consider two IMap-s `myMap` and `MyMap`. They are allowed in Hazelcast, but in SQL CNF they have the same representation `MYMAP`. We will have to resolve such conflicts somehow.

**Possible decisions**
1. Do not support the case-insensitive resolution
1. Support the case-insensitive resolution unconditionally
1. Support optional case-insensitive resolution, that may be turned off in the config

Please share your thoughts. My vote goes for the 3rd.

[1] ANSI SQL Standard, 2003; chapter 5.2, paragraph "Syntax Rules"

**Comment by mdogan** [comment]
When using with quotes, `"myMap"` and `"MyMap"` are different identifiers in SQL representation, right? So users will have an option to use case-sensitive identifiers with quoting. 

If this is the case, I think 2nd option is fine. 3rd one is a plus.

**Comment by devozerov** [comment]
@mdogan yes, with quotes you may select the proper `IMap`. The problem is that if the user does `SELECT * FROM mymap`, we do not know which map will actually be queried. That is, before the query is parsed, we populate our internal scheme with mappings from the identifier to the map. And what we will have is:
- `myMap` -> `myMap`
- `MyMap` -> `MyMap`
- `MYMAP` -> one of these two, depending on the order of map descriptors returned from `NodeEngine` internals

I think that indeed this is not a big deal, because such conflicts should be pretty rare. So if we have good documentation and possibly an ability to turn off the case-insensitive resolution, then it should work fine for the vast majority of cases.

**Comment by Holmistr** [comment]
@devozerov Making sure that I understand correctly. Suppose we have maps `MyMap` and `MYMAP`.

1. `SELECT * FROM "MYMAP"` - this will always query `MyMap`. No space for confusion.
2. `SELECT * FROM MYMAP` - this may query either of the maps. Depending on internal ordering.

If the assumption above is correct, I would go for supporting the case-insensitive resolution unconditionally, no need for additional parameter. If the user has created such confict, he/she will always have a way how to specify precisely. And it's following the ANSI SQL standard.

**Comment by devozerov** [comment]
@Holmistr correction - in your first example the `MYMAP` will be queried.
1. `SELECT * FROM "MYMAP"` - queries `MYMAP`
1. `SELECT * FROM "MyMap"` - queries `MyMap`
1. `SELECT * FROM "myMap"` - fails
1. `SELECT * FROM mymap/MYMAP/MyMap/...` - queries one of these maps, we do not know which exactly

**Comment by nfrankel** [comment]
In the past, I worked with SQL databases that had case-insensitive resolution.

Recently, I had to use one (PostgreSQL if I remember correctly) that was case-sensitive. It sucked - a lot.

I'd go for your 2nd proposal: it's what most users expect. The 3rd proposal seems like a good idea but IMHO defeats the principle of least surprise.

**Comment by tkountis** [comment]
I would suggest a combination of 2 & 3.
I would expect it to be a rare phenomenon having such conflicts on map namings, but I wouldn't bet on it. The ease of use rule in my gut says, default it because its the standard, but let it be configurable to allow for easier migration.

**Comment by viliam-durina** [comment]
The problem with `myMap` and `MyMap` is that they both will be converted to `MYMAP`. Using double quotes doesn't work around the problem. So using:
```sql
SELECT * FROM "myMap"
``` 
will throw `myMap doesn't exist`. If you use double-quoted identifier, you have to use:
```sql
SELECT * FROM "MYMAP"
```
Internally all of:
```sql
SELECT * FROM mymap;
SELECT * FROM MyMap;
SELECT * FROM MYMAP;
```
are converted to:
```sql
SELECT * FROM "MYMAP"
```

But I'm still inclined to use case-insensitive resolution, based on the fact that these conflicts are rare. A workaround is to use DDL to map the IMap under a different name:
```sql
CREATE EXTERNAL TABLE mymap1
OPTIONS ("mapName" 'myMap'); /* we should be case sensitive here */

CREATE EXTERNAL TABLE mymap2
OPTIONS ("mapName" 'MyMap'); 
```

The objects created with these DDL commands will have uppercase names: `MYMAP1`, `MYMAP2`.

The conflict resolution should be stable. That is, in case of a conflict, the same map should always be chosen and the other one is invisible in SQL (unless remapped). We could have this rule: find the first character that is different from the CNF and choose the map where this index is the highest.

For example for names: `myMap`, `Mymap`, the indexes will be 0 and 1, so `MyMap` will be chosen.

This resolution is not 100% stable (see [this question](https://stackoverflow.com/q/62426071/952135)), but it's 100% stable in ascii characters and I suppose non-ascii names are rare too. We can also add a rule that in case of a conflict, use the map where the code of the first different character is lower.

**Comment by viliam-durina** [comment]
@nfrankel PostgreSQL isn't case sensitive...

**Comment by devozerov** [comment]
@viliam-durina I like the idea of predictable handling of conflicts. But I didn't understand your comment about case-sensitivity for `myMap`. This is how it works in the prototype at the moment:
1. Before the query is parsed, we assemble a schema. For the purpose of this discussion, a schema is a map from the table name to the table. We create two mappings for every table - one with the original name, another one with CNF-name. In the latter case, the aforementioned conflict is possible
1. Then during object resolution, we do a lookup in the map

If we have two maps `myMap` and `MyMap`, then three mappings will be created:
1. `myMap` -> `myMap`
1. `MyMap` -> `MyMap`
1. `MYMAP` -> one of the maps, let's say to `myMap`

Now, all the following queries will work:
1. `SELECT * FROM myMap` -> `MYMAP` -> `myMap`
1. `SELECT * FROM "myMap"` -> `myMap` -> `myMap`
1. `SELECT * FROM "MyMap"` -> `MyMap` -> `MyMap`

**Comment by viliam-durina** [comment]
@devozerov OK, I didn't get the idea of multiple mappings before. I don't think it's a good idea. It might look intuitive (use either unquoted identifier or quoted one with correct case, in case of conflict). But it's not intuitive if you know how SQL works.

SQL doesn't specify that "unquoted identifiers should be compared in a case-insensitive way". It specifies that "unquoted identifiers are first converted to CNF and then compared in a case-sensitive way".

For example, if the CNF of your database is uppercase and you do `CREATE TABLE "my_table"` ...`, then there's no way to refer to that table without quotes. Without quotes, `my_table` is converted to `MY_TABLE` and the object name is in lowercase, so it's a different object. You have to use `"my_table"` to avoid the conversion to CNF.  Therefore we can say that identifiers are case-sensitive, but if not quoted, are converted to CNF first, which makes the feel like case-insensitive. As a note, file names on windows work differently: files are indeed named in the original case, but case is ignored when comparing, `file` and `FILE` are considered equal and you can't have both in a single directory. In SQL you can have two objects whose names differ only in case, see [here](https://dbfiddle.uk/?rdbms=postgres_12&fiddle=521a253603517d35a3331d1da9060f39).

And having multiple mappings for one object seems wrong. For example, which object name will we list when listing all objects? `MYMAP` or `MyMap`? If one sees `MyMap` and knows how SQL works, he will think that unquoted identifier can't work and would be surprised to find out that they actually do.

**Comment by viliam-durina** [comment]
In this regard we should also consider whether to convert `MyMap` into `MY_MAP`, that is to put `_` before case change.

I think we should not do it. The conversion is non-obvious and when not quoting identifiers (which is not necessary in most cases), you can still do `SELECT birthDate FROM MyMap`. But when objects will be listed, `MYMAP` will appear. Also frameworks like Hibernate will create queries like `SELECT "BIRTHDATE" FROM "MYMAP" - they work with case-sensitive identifiers and quotes also avoid a possible clash with a keyword.

**Comment by viliam-durina** [comment]
If we use the approach I proposed, there's an issue with DDL. Let's say you have map `MyMap` with `birthDate` field. Then in DDL you must use quotes. Without quotes, the statement:
```sql
CREATE EXTERNAL TABLE MyMap (birthDate DATE);
``` 
will be converted to:
```sql
CREATE EXTERNAL TABLE "MYMAP" ("BIRTHDATE" DATE);
```
And `MYMAP` doesn't exist, only `MyMap` does.

But if one uses correct case, then he's forced to use quotes all the time:

```sql
/* this will work */
CREATE EXTERNAL TABLE "MyMap"("birthDate" DATE);

/* but this won't then */
SELECT birthDate FROM MyMap;

/* this will */
SELECT "birthDate" FROM "MyMap";
```

A DDL that would correctly map mixed-case names to upper case so that it can be used without quotes will look like this:
```sql
CREATE EXTERNAL TABLE MyMap(birthDate DATE)
OPTIONS (
  "mapName" 'MyMap',
  "fieldName.birthDate" 'birthDate');

/* then this will work, with identifiers in any case: */
SELECT birthName FROM MyMap;
```

However, keep in mind that if no Java is used, then we don't map a pre-existing map, we're creating it. In that case there's no issue in DDL at all.

**Comment by devozerov** [comment]
I agree that the proposal has some non-intuitive edge cases. But we build the SQL engine on top of the existing case-sensitive infrastructure, and we cannot do anything about it. The alternative is to reject the idea of supporting case-insensitive resolution at all. 

Please note that there is no uniform handling of identifier resolution across databases. For example:
1. In SQL Server all comparisons are case-insensitive, they even do not have quotes in the first place
2. In MySQL table names are case-sensitive, while column names are not

Therefore, there is no common behavior that user expects. Neither we should assume that users know ANSI SQL - most of them never read the standard. So if our system behaves similarly to a user common sense in most cases, this is already better than not to provide any means of case-insensitive resolution at all. Especially if we can explain the behavior in documentation clearly.

The solution I propose establishes a sensible middle ground between user friendliness and possible problems for the backend where object names are case-sensitive. 

Let's split the whole problem space into two parts
1. System behavior when there are no naming conflicts
1. System behavior when there are conflicts

What exact problematic use cases do you see for both parts?

**Comment by viliam-durina** [comment]
MySQL is case-sensitive on Linux, even if unquoted: https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=f1dd30f7d23cf0286105b4dd8c29dcdd

Quotes are used only if you have spaces or leading numbers in the name.

**Comment by devozerov** [comment]
It is case-insensitive for table names, not for column names. Try `SELECT A FROM t` and it will work.

**Comment by viliam-durina** [comment]
> It is case-sensitive for table names, not for column names. Try `SELECT A FROM t` and it will work.

That's even weirder...
I guess they store one table per file. And that's why it's case sensitive on linux, but not on windows. For columns, they use different rules...
