### ISSUE TITLE
IExecutorService.submitToKeyOwner does not honour PartitionKey interface

### ISSUE THREAD

**Issue by oobles** [hazelcast/hazelcast#17108]
**Describe the bug**
The IExecutorService.submitToKeyOwner should honour an object that implements the PartitionKey interface. If you use an object that implements the PartitionKey interface as the key to an IMap and then attempt to use the same key object as the Object key to the executor submitToKeyOwner the request will be sent to the wrong node.

The client interface does not check for the PartitionKey interface and uses the serialised key value to select the partition.

**Expected behavior**
The submitToKeyOwner sends the request to the partition as returned by the PartitionKey.getPartition function.

This was validated on Hazelcast 4.0.1

**Comment by sancar** [comment]
Hi @oobles , I recheck the code and I believe the code paths are same for both Map and IExecutorService. 
In both keys are passed to serializationService.toData in which we have a check for `PartitionAware` . Then we get the partitionHash from the   Does that explain your concern ? If not can you be more specific, or may be share a code  that  shows it does not work correctly ?

**Comment by oobles** [comment]
Hi, thanks for reviewing. I checked again, and can see it was my fault. :( Appreciate the fast response!
