### ISSUE TITLE
com.hazelcast.collection Package is Missing in IMDG 4.0+ Javadocs

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast#17126]
**Describe the bug**
There are several links from the IMDG Reference Manual and in Google search results to IQueue, ISet and IList Javadocs. They return 404.

**Expected behavior**
The `com.hazelcast.collection` package should be present in the Javadocs.

Before IMDG 4.0, we had, for example, `com.hazelcast.core.IQueue`; see the below working link: https://docs.hazelcast.org/docs/3.12/javadoc/com/hazelcast/core/IQueue.html

For IMDG 4.0+, we should have the `com.hazelcast.collection` for Set, List and Queue Javadocs.

**Additional context**

See https://github.com/hazelcast/hazelcast/pull/15589/files where `*.collection` is excluded.
I am not sure if it was intentional.

**Comment by mmedenjak** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/17161 and https://github.com/hazelcast/hazelcast-enterprise/pull/3658
