### ISSUE TITLE
HealthMonitor logs only print GC metrics as 0 in 3.12 

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#17144]
**Describe the bug**
The HealthMonitor only prints zeroes for the GC counts and times. 

`minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms,`

Analysis of GC logs show the actual values that should be displayed:

![image](https://user-images.githubusercontent.com/20101711/86140629-0c884b00-babf-11ea-8824-fd4c547364d1.png)

**Expected behavior**
The HealthMonitor logs should print the GC metrics that reflect the up-to-date activity of the garbage collector.

**To Reproduce**

I was able to reproduce the issue using the attached ([reproducer.tar.gz](https://github.com/hazelcast/hazelcast/files/4852659/reproducer.tar.gz)) project. It takes an argument for the number of entries to add to an `IMap`. Give enough to surpass a HealthMonitor threshold (such as heap usage).

**Additional context**
* Tested w/ JDK versions 8, 11, and 13
* Tested w/ default collectors as well as setting `-XX:+UseG1GC` explicitly
* Consistently occurs w/ 3.12 (any patch version)

**Comment by sumnerib** [comment]
UPDATE:

If I add the property `-Dhazelcast.diagnostics.metric.level=info`, the GC metrics are printed as part of the `HealthMonitor` log:

`minor.gc.count=151, minor.gc.time=2926ms, major.gc.count=1, major.gc.time=2128ms`

**Comment by mmedenjak** [comment]
Related - in 4.1 we added support for some newer GCs - https://github.com/hazelcast/hazelcast/pull/17561

**Comment by mmedenjak** [comment]
Closing as fixed. @ufukyilmaz please reopen if that's not the case.
