### ISSUE TITLE
SqlException: avoid using same name as well-known classes in public API

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#17182]
In the sql module we declare `SqlException`, which is well-known and frequently used standard Java class (one has to catch it each time he works with JDBC). Its name differs in case (java's is `SQLException`), but this is easy to miss. We should rather use `HazelcastSqlException`.

**Comment by devozerov** [comment]
Will be fixed at https://github.com/hazelcast/hazelcast/issues/17354 together with several other public API changes.
Closing this as duplicate
