### ISSUE TITLE
cluster member kill sql bit map mapBak1HD returned 6 items expected 1

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#17190]
http://jenkins.hazelcast.com/view/kill/job/kill-sql/47/console

/disk1/jenkins/workspace/kill-sql/4.1-SNAPSHOT/2020_07_09-03_43_03/sql/bit-map

fail HzClient3HZ name_predicate-mapBak1HD hzcmd.map.sql.predicate.PersonNamePred threadId=1 global.AssertionException: (firstName=86807 AND lastName=86807) on map mapBak1HD returned 6 items expected 1 

http://54.147.27.51/~jenkins/workspace/kill-sql/4.1-SNAPSHOT/2020_07_09-03_43_03/sql/bit-map

stable cluster version of this member kill test passes.

**Comment by Danny-Hazelcast** [comment]
http://jenkins.hazelcast.com/view/stable/job/scale-up/31/console

/disk1/jenkins/workspace/scale-up/4.1-SNAPSHOT/2020_07_09-06_11_28/sql/bit-map Failed

fail HzMember1HZ name_predicate-mapBak1HD hzcmd.map.sql.predicate.PersonNamePred threadId=1 global.AssertionException: (firstName=2651 AND lastName=2651) on map mapBak1HD returned 3 items expected 1


http://54.147.27.51/~jenkins/workspace/scale-up/4.1-SNAPSHOT/2020_07_09-06_11_28/sql/bit-map

**Comment by mmedenjak** [comment]
@Danny-Hazelcast before this is fixed, can you rerun these tests with this set to `false`? It should fall back to the old index and the tests should pass.

```
    public static final HazelcastProperty PROPERTY_GLOBAL_HD_INDEX_ENABLED
            = new HazelcastProperty("hazelcast.hd.global.index.enabled", true);
```

**Comment by Danny-Hazelcast** [comment]
https://github.com/hazelcast/hazelcast/pull/17338
