### ISSUE TITLE
executeOnEntries with predicate doesn't honor index

### ISSUE THREAD

**Issue by torkeld** [hazelcast/hazelcast#1719]
When executing an entry processor with an index aware predicate the index is never used, instead the predicate is applied to the entire entry set.

**Comment by wimdeblauwe** [comment]
There is a unit test in `com.hazelcast.map.EntryProcessorTest` that references this issue. However, the test is not correct. It does not test for using the index at all. The test will still succeed if you remove the index from the configuration.

The correct test should be like the one in the reproducer at https://github.com/torkeld/hazelcast-issue-reproducer where the unit test checks if the predicate is called or not. If the index is used, the predicate should not be called.

**Comment by LoneRifle** [comment]
Fixed in #8053, with testfix proposed by @wimdeblauwe implemented in 4b37b0e
