### ISSUE TITLE
Bug in clearStorage() of Default record store

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#17205]
The `clearStorage()` method of `DefaultRecordStore` calls `onClear()` on mutation observer after the storage itself is being cleared. For index mutation observer it doesn't work because clearing of the index entries relies on the information from the storage which is already cleared. 

As a result, the global indices may contain dangling pointers. For on-heap indices it will lead to the inconsistent indices while for HD ones it may eventually cause JVM crash. 

However, we have to confirm that changing the order wouldn't violate any logic for other mutation observers. @mmedenjak , @mdogan , @ahmetmircik , guys, WDYT?

The fix needs a backport to 4.0 and 3.x.

**Comment by ahmetmircik** [comment]
For 3.x, there is no indexing mutation observer(which was introduced in 4.0), and we clear storage after clearing indexes. So, from indexing perspective, there should be no such issue.

For 4.0, i checked all mutation-observers, seems it is safe to change order of methods.

**Comment by petrpleshachkov** [comment]
`AbstractInternalQueryCache#clear` has the same issue
