### ISSUE TITLE
Does hazelcast-spring   support profile specific hazelcast.yaml configuration

### ISSUE THREAD

**Issue by bmageshvec** [hazelcast/hazelcast#17229]
Want to understand whether hazelcast-spring support profile specific hazelcast.yaml configuration.

Based on current Spring profile  (spring.profiles.active) will it take automatically if we have different profiles in our project. Please clarify. For example:
```
hazelcast-dev.yaml
hazelcast-test.yaml
hazelcast.yaml
```

**Comment by mesutcelik** [comment]
Hi @bmageshvec ,

If I understood your question correct, you can customize hazelcast config with `spring.hazelcast.config` in each your profile config file. `hazelcast.yaml` will be default one if nothing is specified.

**Comment by mmedenjak** [comment]
Thank you for the confirmation @mesutcelik , closing as answered. @bmageshvec please comment or open a new issue if necessary. Happy Hazelcasting!
