### ISSUE TITLE
LoadBalancer can not be configured declaratively

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#17228]
With Java clients (3.12. and 4.x ), it looks like I cannot specify a class override for client load balancer. https://docs.hazelcast.org/docs/3.12.4/manual/html-single/#configuring-client-load-balancer
This could be a documentation error, or documentation is right, but the XSD schema is wrong.
```
<hazelcast-client>
    ...
    <load-balancer type="random">
        yourLoadBalancer
    </load-balancer>
    ...
</hazelcast-client>
```
is not allowed by the schema. And if it was allowed, a third “type” keyword should be added in order not to generate confusion, for example “custom” ? Programmatic works fine.

**Comment by the-thing** [comment]
I would be happy to work on this. However, I think the proper fix for this would have to break programmatic configuration backwards compatibility as `com.hazelcast.client.config.ClientConfig#loadBalancer` should be replaced with the new `LoadBalancerConfig` containing **type** and **className** for custom load balancer implementation. Later `com.hazelcast.client.impl.clientside.HazelcastClientInstanceImpl#initLoadBalancer` should instantiate selected load balancer using appropriate class loader.

I assume breaking backwards compatibility is not an option for the time being and instantiation should happen inside `com.hazelcast.client.config.impl.ClientDomConfigProcessor#handleLoadBalancer`.

Is that something you are planning to work on or is it community available?

**Comment by sancar** [comment]
Hi @the-thing ,
Yes, breaking the compatibility is not an option. Handling this inside `ClientDomConfigProcessor#handleLoadBalancer.` sounds good to me. 

We would appreciate if you can send a fix for us. Note that, we want to fix this on all three branches. 
3.12.z
4.0.z
4.z

Also, note that other than XML configuration we would like to fix the YAML configuration as well. Please include a fix for that in your pr as well. 

Thanks for your interest. Let us know if you got stuck.

**Comment by burakcelebi** [comment]
Hey @the-thing, could you please let us know if you have any update on this? Please let us know if you need any help :)

**Comment by the-thing** [comment]
Hi @burakcebi, 

I don't need help at the moment, but I have been on holidays and I don't have PC access. I think I should be able to provide PR next weekend unless this is urgent.
