### ISSUE TITLE
CP FencedLock sometimes freezes sometimes fails with Exception after split-brain merge

### ISSUE THREAD

**Issue by lprimak** [hazelcast/hazelcast#17260]
**Describe the bug**
After split-brain healing, lock gives exceptions and/or freeze indefinitely:
```
[2020-07-22T14:46:48.420-0500] [Payara 5.2020.4-SNAPSHOT] [SEVERE] [] [com.hazelcast.cp.internal.operation.unsafe.UnsafeRaftBackupOp] [tid: _ThreadID=35 _ThreadName=hz.priceless_chatelet.partition-operation.thread-0] [timeMillis: 159544720
8420] [levelValue: 1000] [[
  [10.0.1.10]:4900 [development] [4.1-SNAPSHOT] active session: 1 does not exist in CPGroupId{name='Payara/ejb/singleton/StockTicker-1.0-SNAPSHOT_/StockTicker-1.0-SNAPSHOT/StockTicker/lock', seed=0, groupId=48}
com.hazelcast.cp.internal.session.SessionExpiredException: active session: 1 does not exist in CPGroupId{name='Payara/ejb/singleton/StockTicker-1.0-SNAPSHOT_/StockTicker-1.0-SNAPSHOT/StockTicker/lock', seed=0, groupId=48}
        at com.hazelcast.cp.internal.datastructures.spi.blocking.AbstractBlockingService.heartbeatSession(AbstractBlockingService.java:300)
        at com.hazelcast.cp.internal.datastructures.lock.LockService.acquire(LockService.java:62)
        at com.hazelcast.cp.internal.datastructures.lock.operation.LockOp.run(LockOp.java:59)
        at com.hazelcast.cp.internal.operation.unsafe.AbstractUnsafeRaftOp.call(AbstractUnsafeRaftOp.java:65)
        at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:152)
        at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.run(Backup.java:174)
        at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:233)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:429)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:176)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137)
        at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
        at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
]]
```
**Expected behavior**
Locks should work normally after split-brain

**To Reproduce**
There is a test reproduced attached.

What I did is run a locking app on two nodes,
and then "froze" one of them with debugger to get it
to split-brain, and then I waited for a merge, and then it stopped working
with an exception above, or just completely froze indefinitely waiting for a lock.

**Additional context**
Java 8, 2 nodes, Hazelcast 4.1-SNAPSHOT

**Comment by mmedenjak** [comment]
Thank you for the report @lprimak . Without going into the details and judging by just the error message, I assume you are
using sessions with timeout (see `CPSubsystemConfig#sessionTimeToLiveSeconds`) and that the session simply timed out and released the lock. You can increase the timeout but that also means that if the node holding the lock crashes, other nodes will have to wait a long time until the session times out or until someone forces the lock to open. Maybe @mdogan or @petrpleshachkov have some other ideas.

**Comment by lprimak** [comment]
I am not very familiar with the CP subsystem, however, I know it's in unsafe mode and have not been configured in any way,
so not sure if what you are saying is indeed what's occurring here. Not sure if there is a "default" timeout

**Comment by mmedenjak** [comment]
There is definitely a [default timeout](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/config/cp/CPSubsystemConfig.java#L107-L111), I just don't know if it's applied in case of unsafe, I'd say yes but you can also try it out.

**Comment by lprimak** [comment]
Ok, let's say it did timeout, after split-brain healing, shouldn't there be a new session?
The exception occurs from Hazelcast thread and there is no way to catch it or do something about it from the application,
so even if the session did time out, I don't think this is a proper behavior.

In all honesty, I am not too familiar how this is supposed to work, but my gut says that exception like this isn't supposed to happen :)

**Comment by mmedenjak** [comment]
You're probably right, I'll just leave it to the people who know what they are talking about to answer at this point :)

**Comment by mmedenjak** [comment]
@mdogan @petrpleshachkov any ideas about this one?

**Comment by mdogan** [comment]
In _unsafe_ mode we don't support split-brain merges at all. (CP mode is immune to network partitions already :) 

Exception log above is from `UnsafeRaftBackupOp`'s execution, so it doesn't effect the caller side. Other than that, this needs more investigation for unsafe mode under network partitions. I'm not sure how it'll behave exactly, except we are all sure it will be _unsafe_ under partition and _some data_ will be lost.

**Comment by lprimak** [comment]
@mdogan the bigger issue is that sometimes it freezes the whole lock after subsequent tries to acquire it,
thus, in Payara's case, freezes the whole application

**Comment by lprimak** [comment]
@mdogan I have reproduced this in 'interactive' reproducer. Im going to probably have to get that into a test form to make it easy for you guys to reproduce.
The big issue is that lock gets into a 'locked' state after split-brain even though both sides unlocked it. I think it should default to 'unlocked' state if there is any kind of confusion in the cluster in UNSAFE mode.

**Comment by lprimak** [comment]
Another issue here is that reproducer needs Discovery API usage. When it's used, the initial connection is always one node (self) and then later, the discovery API is used to merge the instances together, so when that initial merge happens, the lock can be in an inconsistent state:
Below is a log from the second node starting...

```
Sep 20, 2020 2:02:59 PM com.hazelcast.system
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Hazelcast 4.1-SNAPSHOT (20200920 - 6ed5868) starting at [10.0.1.2]:5711
Sep 20, 2020 2:03:00 PM com.hazelcast.instance.impl.Node
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Using Discovery SPI

*** initial startup ***

Sep 20, 2020 2:03:00 PM com.hazelcast.cp.CPSubsystem
WARNING: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Sep 20, 2020 2:03:00 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Sep 20, 2020 2:03:00 PM com.hazelcast.core.LifecycleService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is STARTING
Sep 20, 2020 2:03:00 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [10.0.1.2]:5711 - 9740f085-fa44-463e-9b93-55f40a352414 this
]

Sep 20, 2020 2:03:00 PM com.hazelcast.instance.impl.Node
WARNING: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Config seed port is 5710 and cluster size is 1. Some of the ports seem occupied!
Sep 20, 2020 2:03:00 PM com.hazelcast.core.LifecycleService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is STARTED
<c> to create cache, <d> to destroy, <p> to print, <l> to lock, <u> to unlock
blank to exit <h> for help, anything else to put in cache ...

*** SPLIT-BRAIN MERGE TIMEOUT ***

Sep 20, 2020 2:03:05 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Initialized new cluster connection between /10.0.1.2:54734 and /10.0.1.2:5710
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] We should merge to [10.0.1.2]:5710, both have the same data member count: 1
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
WARNING: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is merging [tcp/ip] to [10.0.1.2]:5710
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Locking cluster state. Initiator: [10.0.1.2]:5711, lease-time: 60000
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Extending cluster state lock. Initiator: [10.0.1.2]:5711, lease-time: 20000
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Changing cluster state from ClusterState{state=ACTIVE, lock=LockGuard{lockOwner=[10.0.1.2]:5711, lockOwnerId='cd4ee365-7293-4c6e-8340-d0692de6ab84', lockExpiryTime=1600628665656}} to ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, initiator: [10.0.1.2]:5711, transient: false
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.impl.operations.MergeClustersOp
WARNING: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is merging to [10.0.1.2]:5710, because: instructed by master [10.0.1.2]:5711
Sep 20, 2020 2:03:05 PM com.hazelcast.core.LifecycleService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is MERGING
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.ClusterService
WARNING: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Resetting local member UUID. Previous: 9740f085-fa44-463e-9b93-55f40a352414, new: fe5da3e1-d0e8-44ad-8178-918ee408a446
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Connection[id=1, /10.0.1.2:54734->/10.0.1.2:5710, qualifier=null, endpoint=[10.0.1.2]:5710, alive=false, connectionType=MEMBER] closed. Reason: TcpServer is stopping
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.server.tcp.TcpServerConnector
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Connecting to /10.0.1.2:5710, timeout: 10000, bind-any: true
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Initialized new cluster connection between /10.0.1.2:54735 and /10.0.1.2:5710
Sep 20, 2020 2:03:05 PM com.hazelcast.cache.impl.CacheService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] Added cache config: CacheConfig{name='myCache', managerPrefix='/hz/', inMemoryFormat=BINARY, backupCount=1, hotRestart=HotRestartConfig{enabled=false, fsync=false}, wanReplicationRef=null}
Sep 20, 2020 2:03:05 PM com.hazelcast.internal.cluster.ClusterService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [10.0.1.2]:5710 - 6dda74dc-2b04-4813-b409-81937d652e84
	Member [10.0.1.2]:5711 - fe5da3e1-d0e8-44ad-8178-918ee408a446 this
]

Sep 20, 2020 2:03:05 PM com.hazelcast.core.LifecycleService
INFO: [10.0.1.2]:5711 [dev] [4.1-SNAPSHOT] [10.0.1.2]:5711 is MERGED

```

**Comment by lprimak** [comment]
@mdogan see above. This test clearly demonstrates the problem in a simple test case.
Also, if you run the https://github.com/flowlogix/hazelcast-issues program with two nodes and kinda play with it for half hour, you can see that there are many unstable situations you can get into within CP subsystem.

Thanks for your help

**Comment by jerrinot** [comment]
hi @lprimak,
thank you for creating the reproducer, that's definitely helpful! 

First observation:
You wrote: _Another issue here is that reproducer needs Discovery API usage. When it's used, the initial connection is always one node (self) and then later, the discovery API is used to merge the instances together, so when that initial merge happens, the lock can be in an inconsistent state_

This is because the `CacheTester` has the [WAIT_SECONDS_BEFORE_JOIN property](https://github.com/flowlogix/hazelcast-issues/blob/7f1b7137b5b458ad3ead9de0d1c38b73b9e6eeb7/CacheTester/src/main/java/com/flowlogix/hazelcast/cachetester/CacheTester.java#L67) set to "0". When I comment this out and add `config.setProperty(DISCOVERY_SPI_ENABLED.getName(), "true");` then I can see a newly joining member will connect to an already running cluster instead of forming its own cluster first.

**Comment by lprimak** [comment]
Hi, @jerrinot thank you for taking this up.
The discovery API now has it's own issue, so let's take it there:
https://github.com/hazelcast/hazelcast/issues/17586

**Comment by petrpleshachkov** [comment]
@lprimak , can you confirm that you are using `Unsafe` mode and experiencing the issues? Do you have the issues in the production Safe mode?

**Comment by lprimak** [comment]
It's been a while, any progress on this issue

**Comment by mmedenjak** [comment]
@petrpleshachkov have you reached any conclusions regarding this issue?

**Comment by Holmistr** [comment]
Moving this to backlog as unfortunately we can't manage to fix it in 4.2. We'll take a look in the next release.

**Comment by lprimak** [comment]
@Holmistr Time to take a look at this again?
I am not the only one having issues :) @plesingr-aeb

**Comment by lprimak** [comment]
@AyberkSorgun This is still very much an issue with the latest Hazelcast. 5.4-SNAPSHOT
Please bump

**Comment by lprimak** [comment]
Related to #24897 
With CP enabled, neither split brain nor regular node restart functions as expected either, so there seems to be no way to do failover at all as far as I understand it

**Comment by lprimak** [comment]
According to the documentation, FencedLock (and other CP data structures) do not detect crashes or split brain by design. CP needs to be enabled to this to work properly.
