### ISSUE TITLE
Support CASE operator

### ISSUE THREAD

**Issue by taburet** [hazelcast/hazelcast#17329]
1. Revive CASE support from https://github.com/hazelcast/hazelcast/pull/17183/commits/c1a5855c8212e429b5d7245a1906713af01e624b and 7f29e69e24bcd44dec551b9d255171a48bdda0ec.

2. Add end-to-end tests.

3. Try to fix type inference for `case ? when true ... when 1.0 ...`.

4. Make error messages more precise.

**Comment by devozerov** [comment]
General implementation guidelines:
1. Define the `CASE` operator class. We may use `SqlCaseOperator` as a starting point, but replace the inference logic with our own rules.
2. Register the operator in the `HazelcastSqlOperatorTable`.
3. Create the Hazelcast counterpart (`CaseExpression` from the `sql` branch could be used as a starting point).

**Comment by mmedenjak** [comment]
@alex-dukhno how much is missing? I see there are comments on the PR, would it be possible to include this before 4.2 GA?

**Comment by alex-dukhno** [comment]
@mmedenjak it requires review from @devozerov, I hope I addressed all of his comments (in PR and from our call discussing `CASE`)
If there is no critical task on SQL for `4.2` then maybe Vladimir can review it an we could merge it. But AFAI @Holmistr said that `CASE` is not critical functionality for `4.2`

**Comment by devozerov** [comment]
I think we should move it out of 4.2 and merge later with no rush. We agreed to allow for new expressions in patch releases, so we do not need to wait for 4.3 to release this.
