### ISSUE TITLE
Fix ignored test

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#17325]
The random test failures got a bit out of hand. I'm filing this issue to track the tests that we have ignored to unblock the PR builder and the development. We will jump on this list right after the Beta release and we will fix every single one of those.

**Comment by petrpleshachkov** [comment]
Some run parameters for `MapWanSyncAPITest` are ignored.

**Comment by mmedenjak** [comment]
`MapWanSyncAPITest` was fixed so unignored.

**Comment by mmedenjak** [comment]
There are no new tests that were ignored, closing.
