### ISSUE TITLE
Split brain healing may cause index/storage inconsistency

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#17333]
t seems we've introduced a bug here https://github.com/hazelcast/hazelcast/pull/15854#discussion_r468580177. In this PR we've refactored the index updates into observes and do the index update BEFORE updating the storage. The update removes the old entry and inserts new one which is exactly the same because it takes it from the record that is not updated. After that, we do the storage update and remove the old value. The result is a dangling pointer from the index causing inconsistent results on-heap and JVM crashes off-heap.

It seems we have to fix it in all affected versions. I'm wondering, do we have a proper split-brain test for this?

CC @ahmetmircik , @mmedenjak @taburet @Holmistr

**Comment by Holmistr** [comment]
@petrpleshachkov We should backport the fix only into still supported versions which is 4.1, 4.0.x, 3.12.x and 3.11.x

**Comment by mmedenjak** [comment]
Trying to figure out how this relates to https://github.com/hazelcast/hazelcast/issues/17205 - is the difference that this one is related to split-brain healing while the other one relates to regular entry update?

**Comment by petrpleshachkov** [comment]
Yes, this relates to the split-brain healing and this is a regression.

**Comment by Holmistr** [comment]
I see. Therefore, let me change the milestone to the 4.0.x one.

**Comment by mmedenjak** [comment]
Closing as fixed with 4.0.3
