### ISSUE TITLE
ReplicatedMap high memory consumption when replicating

### ISSUE THREAD

**Issue by alexosenov** [hazelcast/hazelcast#17335]
Greetings!
I am having a huge issue with the ReplicatedMap reserving and consuming enormous amounts of heap memory. 
The problem gets even worse when there are 2 or more members. This is my scenario.

1. Start pod-1 with Spring Boot + Kafka + Hazelcast. (Replication factor : 1)
2. The app inits the HazelcastInstace, but NOT the Kafka Consumer.
3. Fetch 1milion rows from the DB and do a putAll in a ReplicatedMap 
**( for loop + put performance is obnoxiously bad)**
4. At this point the HealthMonitor raises and Alert message for Memory Consumption . Spikes up to ~  1.5 - 2GB USED mem. (xmx 5g)
5. At this point the Kafka Consumer kicks in and starts getting from the ReplicatedMap
6. At this point the app uses around 1.5- 2GB steadily ( for the next hours as far as I have monitored). 
 Now if I force a GC the app uses 1.0 - 1.5 const. 
**The problematic object taking most of the memory is byte[]**

So far so good. For the next step lets assume I haven't done a force GC on POD-1 and it is using ~1.5 - 2GB heap.

7. Start POD-2 (replication factor 2) while the first one happily running.
8. POD-2 skips loading anything from the DB. POD-2 starts really fast and joins cluster. 
 Pod-2 Is visible in the Member rebalance message.

9. Pod-1 DOUBLES the USED heap memory = ~4 - 5GB. Apparently for replicating the data to POD-2. 
**byte[] is taking like 2-3GBs of heap.**

At this point there are 2 scenarios. 

Either POD-1 dies (due to the memory consumption), replication fails. (SocketConnectException memberAlive:false)
Then POD-1 restarts skips initial DB load and gets the not fully replicated data back from POD-2 and they both live happily ever after. (1.5gb each)

OR 

You start it with XMX 6-8GB and replication succeeds, BUT 
POD-1 shows 4-5GB heap used out of 6-8. (confirmed with profiler)
POD-2 shows 1.5GB heap used out of 6-8.
POD-1 **NEVER** goes below those 4-5 GB USED ( left it overnight, it evens grows). **byte[] still being the culprit.** 
What's even better is that a force GC on POD-1 drops the used memory to 1.5GB. And now there are 9GB of memory reserved not used at all and not being reclaimed (this might be on our side)

The root of the problem : We can't really start the cluster on Prod with 5milion records.

**Important notes:
Same scenario holds true even with KAFKA disabled.
If POD-1 and POD-2 are started simultaneously the problem persists.
Loading 10k objects leaves enormous footprint as well. 2.5GB**

 
Hazelcast Version: 3.12.8
Topology: Embedded
Discovery: Zookeeper
Serializer : StreamSerializer
Cluster Members: 1 we need 2-3
Cluster Backpressure : OFF
ReplicatedMap - setAsyncFillup(false);
JAVA - -Xmx5120m -XX:+UseSerialGC -Xms512m -XX:-AggressiveHeap

**Comment by jerrinot** [comment]
hi @alexosenov,

thanks for reporting an issue and a great description of the behavior you observe! I wish more reports were as comprehensive as yours!

We could probably improve the memory consumption during replication when a new member joins - to eliminate memory spikes. You could try to change the `hazelcast.partition.max.parallel.replications` property. It's set to 5 by default. You can try to decrease it to see whether this prevents POD-1 from dieing when `Xmx` is set to `5g`.

Now let's focus on the scenario with 6-8GB. If I understand it correctly heap memory utilization drops back to the expected value of 1.5GB when you force a full GC. This indicates it's not a memory leak. If there was a memory leak then the force GC would have not helped. Full GC can only reclaim memory which is not referenced by the application in any way and thus (by definition) cannot be a memory leak. 

I realize this answer is not very helpful and it does not solve your very real problem. Memory not being reclaimed and potentially returned back to the Operating System is a pain, especially in a cloud environment. 
This problem has 2 parts:
1. JVM has to realize some objects are no longer referenced and can be reclaimed. Some GC are lazy and they won't start a new GC cycle if they still have some space marked as unused. Other GCs will start a collection cycle eagerly, even when there is still some space.
2. JVM may or may not return unused memory back to the OS. Again, this depends on a GC implementation. Some GC algorithms happily return memory when they don't need it, others will hoard it even when it's empty. 

I see you are using `-XX:+UseSerialGC` - that's a very old collector, in the fact I am surprised it's still supported. Indeed the SerialGC won't kick in if there is still some memory available. 

You didn't specify what Java version you are using. If you are using a recent version than Shenandoah GC has a good reputation when it comes to returning memory back to the OS. However Shenandoah GC was introduced in JDK 12, if you are on RedHat builds of OpenJDK then you can find its backport even in JDK 11 or maybe even JDK 8 (I am not 100% sure about this)

If you are on older Java version then both G1 or CMS will do well in the #1 point - they start a GC cycle eagerly. CMS won't return memory back to the OS (the point #2). I believe G1 will return, but I am not 100% sure with this. 

I hope this helps you a bit and let me know if you have still any question!

**Comment by alexosenov** [comment]
Thank you for the reply @jerrinot !! 

I will experiment with other GCs and properties. I am running Java-11. A wild guess here, but any idea if the following class is responsible for the replication ?
com.hazelcast.replicatedmap.impl.operation.ReplicationOperation ?

**Comment by jerrinot** [comment]
With JDK 11 your best bet is G1. Unless you are on Red Hat builds of OpenJDK which includes Shenandoah. Shenandoah is also being backported into OpenJDK 11 upstream so eventually it should be available in more distributions. It's not easy, is it? :)

Indeed `com.hazelcast.replicatedmap.impl.operation.ReplicationOperation` is used to data partitions from one member to another. You can see it's created [here](https://github.com/hazelcast/hazelcast/blob/296aac5c8a3a4970851afc55c9e91622db75c131/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java#L327)

**Comment by alexosenov** [comment]
Does ReplicationOperation really pull all of the objects + serialize in order to replicate :?. This should explain the memory spike, I guess.

**Comment by jerrinot** [comment]
@alexosenov: it does. including metadata, etc. See the [serialization logic](https://github.com/hazelcast/hazelcast/blob/97ff57ba92dc1fbfa77720885e7db40757999080/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ReplicationOperation.java#L119)

**Comment by alexosenov** [comment]
@jerrinot Where I can check how it is decided that an Entry should be replicated, because I am observing heap doubling only when a member joins, which means I can use the min.members property to have 2 and batch load the data to circumvent the issue.

**Comment by jerrinot** [comment]
@alexosenov: [ReplicatedMap](https://docs.hazelcast.org/docs/4.0.2/manual/html-single/index.html#replicated-map) is replicated to all members. When a new member is joining then it will get a full replica of all Replicated Maps. 
Example: When you have 5 members in your cluster then each member will have all members stored. Is this the behaviour you want? Replicated Map is usually used for small-ish dataset. 

If you just want to have data available in a cluster then [`IMap`](https://docs.hazelcast.org/docs/4.0.2/manual/html-single/index.html#map) is usually a better structure. It splits the dataset into smaller chunks (partitions) and then each member will get its own chunk. This way you can increase total capacity by adding more members.

**Comment by jerrinot** [comment]
I am closing this issue. 

there is a room for improvement, but everything is working as designed. feel free to re-open it if there are any new discoveries/oddities.
