### ISSUE TITLE
How change the log path of hazelcast?

### ISSUE THREAD

**Issue by clsaa** [hazelcast/hazelcast#17363]
**How change the log path of hazelcast**

**My framework dependence the hazelcast. My framework has a log file independent of business applications**

**So I want to print Hazelcast logs to my frame log file instead of printing directly to the business application log file**

...

**Please describe the desired behavior**
...

**Describe alternatives you've considered**
...

**Comment by jerrinot** [comment]
hi @clsaa, what logging framework is your application using? You can instruct Hazelcast to use a logging library of your choice. see: https://docs.hazelcast.org/docs/4.0.2/manual/html-single/index.html#logging-configuration

Once it's configured then you use a library-specific configuration. 
Example: If your application uses `log4j` then you set `hazelcast.logging.type` property to `log4j`. Hazelcast will uses log4j for its own logging and you use log4j.properties or log4j.xml to configure it.

**Comment by jerrinot** [comment]
I'm closing this issue. Please use community [support forum](https://groups.google.com/forum/#!forum/hazelcast) for questions. thanks!
