### ISSUE TITLE
Lack of connection and read timeouts on ManagementCenterService

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/hazelcast#17387]
openGetTaskConnection method's connection hasn't any timeout settings.

https://github.com/hazelcast/hazelcast/blob/3.12.z/hazelcast/src/main/java/com/hazelcast/internal/management/ManagementCenterService.java#L732

The following settings should be added.

```
connection.setConnectTimeout(CONNECTION_TIMEOUT_MILLIS);
connection.setReadTimeout(CONNECTION_TIMEOUT_MILLIS);
```

Thanks.

**Comment by jgardiner68** [comment]
@emre-aydin Are there any changes needed on the MC side?

**Comment by emre-aydin** [comment]
> @emre-aydin Are there any changes needed on the MC side?

No

**Comment by Holmistr** [comment]
@emre-aydin @ilkerkorkut Looks like this issue is fixed, should we close this issue?
