### ISSUE TITLE
Create the design document for SQL consistency guarantees

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17468]
We have an internal document [1] explaining the consistency guarantees of the engine. To put it short, the engine produces consistent results if there are no concurrent updates, but may produce duplicate rows or miss rows if there are concurrent updates. To fix these inconsistencies we should implement distributed transactions, which is out of the scope of the product strategy for now.

The goal of this issue is to convert the internal document to a public design document.

[1] https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1858371792/Consistency+Model+of+the+new+Query+Engine ((visible to Hazelcast employees only)

**Comment by mmedenjak** [comment]
@devozerov which release is this going into? 4.1?

**Comment by devozerov** [comment]
Ideally - yes, if we have enough time.
