### ISSUE TITLE
Support JSON in the SQL

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17473]
Currently, we do not support JSON objects (`HazelcastJsonValue`) in the SQL. There are explicit checks that disallow queries over such data. 

The main problem is unclear semantics of JSON field type resolution. Specifically, the `Extractors` class will resolve `2` as `java.lang.Long`, while `2.0` will be resolved as `java.lang.Double`. But the SQL engine uses strong typing, so we need more strict rules. A good candidate for such columns could be `DECIMAL`/`java.math.BigDecimal`, because it could handle values in both forms. But it might be slow performance-wise.

The goal of this ticket is to design the semantics of the field resolution and then implement the field extraction logic that will follow these semantics.

**Comment by devozerov** [comment]
No. The current issue is about supporting JSON (`HazelcastJsonValue`) as top-level objects (key, value). 
The mentioned issues are about supporting nested field access and collections for the whole engine. This would possibly require new extraction rules, new optimization rules, and new expressions.

**Comment by mmedenjak** [comment]
True, I'm just expecting a typical JSON to be chock-full of nested objects and collections.

**Comment by gierlachg** [comment]
Already implemented

**Comment by nkonev** [comment]
https://github.com/hazelcast/hazelcast/commit/cf2808730e6a44848bb551dc750439e6d80b9877
