### ISSUE TITLE
Create aliases for TIMESTAMP_WITH_TIME_ZONE data type

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17474]
Presently, to express the timestamp with timezone, we use the data type name `TIMESTAMP_WITH_TIME_ZONE`. Such a naming scheme is uncommon in SQL. Users would expect type specification without underscores (e.g. `TIMESTAMP WITH TIME ZONE`). 

The goal of this issue is to consider alternative namings for this data type. Currently, we have two ideas:
- `TIMESTAMP WITH TIME ZONE` - match user expectations, but would require custom parsing logic
- `TIMESTAMPTZ` - simple to implement, used in Postgres, but maybe not that well known in the community (but who knows?)

**Comment by viliam-durina** [comment]
Currently we also support `TIMESTAMP WITH LOCAL TIME ZONE`, it will use the `TIMESTAMP_WITH_TIME_ZONE` type, which isn't correct. The type `WITH LOCAL TIME ZONE` should not store the TZ, but instead convert the TZ to the TZ of the client session.

In Jet we use `TIMESTAMP WITH TIME ZONE` in the `CREATE MAPPING` command. The variant with underscores or with `LOCAL` doesn't work there.
