### ISSUE TITLE
Split Brain discovery fails in smaller cluster in some edge cases  [HZ-1180]

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#17489]
We have some customer issues (6538, 5832, 5684, 5270) with incident logs and configurations. 

After the split-brain happens, the bigger cluster is able to do the split-brain discovery and send `SplitBrainMergeValidationOp` to the smaller cluster. However, this does not start the split-brain merge, because the merge starts after the small cluster discovers the bigger cluster. 

In some cases, we see that the small cluster does not search for the other clusters. 
This has the following trivial reasons: 

1) If the small clusters' master has an incomplete initial network configuration. i.e. The bigger clusters' master is not in the initial member list configuration of the small cluster's master. 

2) Small cluster master still has network issue so cannot connect to the bigger cluster. 

3) Small cluster is in a state (i.e. FROZEN) that doesn't allow joining. 

The issue still happens without the presence of the above reasons.

**Comment by sertugkaya** [comment]
as previosuly discussed with Jiri, should be backported to 3.12.z as well

**Comment by mmedenjak** [comment]
Recently resurfaced - https://hazelcast.zendesk.com/agent/tickets/7575

**Comment by Holmistr** [comment]
Moving to backlog as it needs to be properly triaged based on sponsorships.

**Comment by AyberkSorgun** [comment]
https://github.com/hazelcast/hazelcast/pull/21552 https://github.com/hazelcast/hazelcast-enterprise/pull/5055
