### ISSUE TITLE
Initiate the split-brain merge process after bigger cluster sends the SplitBrainMergeValidationOp [HZ-1181]

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#17490]
Related to #17489 

There are some cases where the small cluster does not do the split-brain discovery, so the merge process never begins. 

With the current logic, both clusters do the split-brain discovery but the bigger cluster just logs the situation but does not initiate the merge process. 
The small cluster receives the SplitBrainMergeValidationOp from the bigger cluster, prints some logs, and responds to the operation. 

Upon receiving SplitBrainMergeValidationOp, the smaller cluster could initiate the merge process instead of waiting to discover it by itself. 

idea by: @mdogan

**Comment by sertugkaya** [comment]
@mmedenjak  per @mdogan it's possible to backport this to 3.12.x. Can you also confirm and put a milestone for that?

**Comment by Holmistr** [comment]
Moving to backlog as it needs to be properly triaged based on sponsorships.

**Comment by AyberkSorgun** [comment]
https://github.com/hazelcast/hazelcast/pull/21552 https://github.com/hazelcast/hazelcast-enterprise/pull/5055
