### ISSUE TITLE
Durable executor metric for completed count does not reach expected value given cluster scale-in

### ISSUE THREAD

**Issue by lazerion** [hazelcast/hazelcast#17567]
- Scale out 3 members cluster and 1 client
- Wait for sanity on cluster that client discovers 3 members
- Submit `42` `SimpleMapTask` to durable executor service, as [defined here](https://github.com/hazelcast/hazelcast/issues/17557)
```
DurableExecutorService durableExecutorService = client.getDurableExecutorService("stats-test");
durableExecutorService.submit(new SimpleMapTask());
return true;
```
- Scale in cluster to 2
- Wait for sanity on cluster that client discovers 2 members
- Submit `42` `SimpleMapTask` to durable executor service, as [defined here](https://github.com/hazelcast/hazelcast/issues/17557)
- Expect total of `84` completed count for 1 minute

Above case fails at last step with below logs, also attached 
[logs.zip](https://github.com/hazelcast/hazelcast/files/5239155/logs.zip)

```
....
[awaitility-thread] INFO com.hazelcast.it.client.tests.runner.ExecutorMetricsTest - Bounced {totalExecutionTime=59183, creationTime=3200693067173, totalStartLatency=3352, pending=0, cancelled=0, started=70, completed=70}
[awaitility-thread] INFO com.hazelcast.it.client.tests.runner.ExecutorMetricsTest - Bounced {totalExecutionTime=59183, creationTime=3200693067173, totalStartLatency=3352, pending=0, cancelled=0, started=70, completed=70}
```
- If scale in operation or step removed, metrics return expected count of `84`
- Config
```
<durable-executor-service name="stats-test">
        <pool-size>16</pool-size>
        <durability>2</durability>
    </durable-executor-service>
```
- kindly guide.

**Comment by ahmetmircik** [comment]
Your findings seem expected since stats has no backup and they are local to node that execution happens. When node shutdowns, they get lost.

**Comment by lazerion** [comment]
@ahmetmircik Thanks for the guidance, closing, and I updated the cases.
