### ISSUE TITLE
Optimize SQL threading model

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17563]
# Background

Currently, the SQL has the threading model that uses two thread pools:
1. When an operation arrives, it is first processed in the `operation pool`. This is the striped (partitioned) thread pool, where every thread has a dedicated queue. This helps us establish ordering between operations as they arrive. E.g. two consecutive batches sent from a single stream source are guaranteed to be processed by a single operation thread, and thus the order of batches is preserved on the receiver
1. Then, if the operation should trigger the execution of the query fragment (e.g. query start, or the new batch of data), then the control is passed to the `fragment pool`. We use `FJP` because it can balance jobs between threads. Also, this second pool ensures that there are no long-running operations in the `operation pool`, which is important for query cancel and cleanup operations. If we execute queries in the `operation pool`, it may happen that a `cancel` request cannot cancel the query in a timely manner because all threads are busy.

Unfortunately, this approach has severe performance implications: in order to start the execution of the fragment we have to do at least two context switches: `io pool -> operation pool -> fragment pool`. This is especially visible on short workloads when the local processing time is insignificant. E.g. point indexed lookups.

Moreover, while this solution helps us to minimize the risk of re-order of `execute` and `cancel` messages, it is still possible that `cancel` will be processed earlier than `execute` - if the connection was re-established between these two messages, they may get reordered.

Generally, whatever threading model we choose, it should satisfy the following requirements:
1. There should be no more than one context switch on the hot path
1. Two batches from the same stream must be executed in order on the receiver
1. `cancel` operation should be able to actually cancel the query with high probability despite races on the network and threading layers
1. `cancel` and `check` operations must be executed as soon as possible, even if there are a lot of long-running queries 

Below you may find the design of the proposed fix, that satisfies all the requirements.

# Design

## 1. New thread pools

We will still have two thread pools, but they will work differently:
1. `fragment pool` - will execute all data-related operations, such as `execute`, `batch`, `flow-control`. This way, we have only one context switch on the hot path: `io pool -> fragment pool`. This pool will use either `ThreadPoolExecutor` or `FJP` (depends on performance evaluation results) because we need load balancing when executing fragments
1. `system pool` - will execute `cancel` and `check` operations. We cannot execute them in the `fragment pool` because it may have long-running operations.

In order to pick the proper pool, we will add the new flag to the `Packet` class, similarly to `Packet.FLAG_JET_FLOW_CONTROL`.

Now, we have only one thread pool on the hot path, but have races on messages arrive: `cancel` could be executed earlier than `execute`, `batch2` could be processed earlier than `batch1`. Below we discuss how to solve these races

## 2. Ordered batch processing

When a sender sends two batches `batch1` and `batch2` to the receiver, they must be executed in the same order on the receiving side. Otherwise, incorrect results are possible. For example, when the receiver expects a sorted stream of data from the sender.

Luckily, we have a guarantee that a single fragment will never be executed by more than one thread, see `QueryFragmentExecutable.schedule`. Therefore, we may enforce ordering of batches on the inbox level, rather than on the level of the thread pool. 

We will introduce two new fields to the `QueryBatchExchangeOperation` operation:
```
class QueryBatchExchangeOperation {
    ...
    long ordinal;
    boolean ordered;
    ...
}
```
The flow:
1. When the batch arrives, we put it into the queue, as usual (`QueryFragmentExecutable.operations`)
1. Then, we push batches to the inbox (`AbstractInbox.onBatch`). This is guaranteed to happen from a single thread
1. In the `AbstractInbox.onBatch` we check whether the batch is ordered. If not - it is processed right away. If yes - we compare the ordinal of the last processed batch and the current batch. If there is "hole" (e.g. `last=1`, `current=3`), we put the batch into the queue of pending batches. If there are no holes, then we process the current batch, as well as all applicable batches from the queue. For example, for the state `last=1, pending=[3,4,6], current=2`, we will process `[2, 3, 4]`, and after processing the state will be `last=4, pending=[6]`

## 3. Resolving execute-cancel race

The query is always started on a single member, that we call `initiator`. The `initiator` node sends the `execute` request to one or more nodes (including self) that we call `participants`. The query could be canceled after it is started for many reasons, e.g. user request, error, etc. In this case, a `cancel` request is sent from the `initiator` to all `participants`. The problem is that there is no happens-before between `execute` and `cancel` requests:
1. `participant A` may trigger cancel before `execute` is sent to `participant B`, therefore `participant B` may receive `cancel` before `execute`
1. Even if the `initiator` sends `cancel` after `execute` to a particular participant, message reorder in the wire is possible
1. Last, even `cancel` arrived after `execute` to the participant, it may be reordered in the new threading model, because `execute` and `cancel` are executed by different thread pools without any synchronization

We solve the problem by careful analysis of the possible event sequences. We consider only local processing on the `participant` since any order imposed by the `initiator` or the networking layer cannot be guaranteed due to two thread pools.
1. `execute`- query is not canceled, and run to completion normally
2. `execute`, `cancel` - query is started, cancel operation finds the state, and cancels the query
3. `cancel` - cancel operation arrives, but there is no local query. It may mean that the query is not started yet, or that it is already completed. Currently, the `cancel` operation will do nothing in this case, leading to a possible scenario when the query cancel will be missed. In the new design, we will register the surrogate query state with `cancelled=true` flag. similarly to how it is done for batches that arrive earlier than the query is started (`QueryStateRegistry.onDistributedQueryStarted`). Now there are two possible outcomes:
3.1 `execute` arrives after `cancel` - it will find the canceled state, clear it, and do not start execution. This way, the cancellation is never lost
3.2 `execute` never arrives - in this case, we may get the memory leak. Fortunately, we already have a mechanism that ensures that locally registered query is still active on the `initiator` (`QueryState.requestQueryCheck`). The same mechanism will ensure that the cancelled query is cleared from the memory eventually

# Summary
Below is a summary of what needs to be changed:
1. Create two conventional pools `fragment pool` and `system pool`
1. Make sure that `cancel`, `check` and `check_response` operations arrive at `system pool`, while others arrive at `fragment pool`
1. Add ordering logic to `AbstractInbox.onBatch`, add relevant fields to `QueryBatchExchangeOperation`
1. Make sure that `cancel` operation registers a surrogate canceled state, and that `execute` operation clears it without starting the query

**Comment by mmedenjak** [comment]
Overall looks good. 

I'm thinking if we need a "system pool" in the first place. If the operations it executes are simply setting some volatile variable or adding to a concurrent set, the IO thread can do that as well. If it's anything heavier than that, probably we can get away with a single threaded pool. I assume a single threaded pool was what you were aiming for in the first place, it's just not relevant to be mentioned here.

**Comment by devozerov** [comment]
@mmedenjak  The main goal was to have a single thread pool involved in the hot execution paths (query start, batch exchange). It is not a problem to have a separate pool for `cancel` and `check` operations. On the other hand, I agree that provided that these two operations are fast and relatively rare, we may execute them in the IO thread as well.
