### ISSUE TITLE
Missing logger for new 4.1-BETA-1 querying

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17609]
Trying the new SQL on 4.1-BETA-1 gives this message in the logs

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

The application is coded in Spring Boot style using
```
       <properties>
                <java.version>11</java.version>
                <hazelcast.version>4.1-BETA-1</hazelcast.version>
        </properties>

        <dependencies>
                <dependency>
                        <groupId>com.hazelcast</groupId>
                        <artifactId>hazelcast</artifactId>
                </dependency>
                <dependency>
                        <groupId>com.hazelcast</groupId>
                        <artifactId>hazelcast-sql</artifactId>
                        <version>${hazelcast.version}</version>
                        <exclusions>
                                <exclusion>
                                        <groupId>com.hazelcast</groupId>
                                        <artifactId>hazelcast</artifactId>
                                </exclusion>
                        </exclusions>
                </dependency>

                <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter</artifactId>
                </dependency>
        </dependencies>
```

I suspect this message may be coming from Calcite

Suggests that logging is incorrectly configured.

**Comment by neilstevenson** [comment]
Possibly connected, `hazelcast:hazelcast-sql:4-1-BETA-1` shades an old version of Slf4j

```
hazelcast-sql % mvn dependency:tree  | grep slf4j
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:runtime
```

The latest Spring boot (2.3.4.RELEASE) has a runtime dependency on a new version of Slf4j, 1.7.30, so the classpath will contain classes fro both.

**Comment by mmedenjak** [comment]
@devozerov can you take a look?

**Comment by devozerov** [comment]
Apache Calcite relies on SLF4J. Unless there is an SLF4J implementation in the classpath, the aforementioned error message will appear, since it checks for a specific class in runtime unconditionally. 
The simplest solution - is to add and relocate the missing artifact `slf4-log412`. However, this will increase the artifact size even further.

**Comment by mmedenjak** [comment]
> However, this will increase the artifact size even further.
By how much?

Also, I'm unsure if we are supposed to place logging frameworks on the classpath in the first place so maybe we can close this as a known issue. WDYT?

**Comment by devozerov** [comment]
In this case, we will have this annoying error message on every JVM without the SLF4 implementation in the classpath. I am investigating another solution - to define our own `StaticLoggerBinder` that will prevent this error message. This will be a single class in the `sql` module that will help to suppress the warning, without requiring additional dependencies, and not breaking other SLF4j-dependent libraries in the JVM classpath.

**Comment by mmedenjak** [comment]
That would be perfect :)
