### ISSUE TITLE
Parse error on 4.1-BETA new style SQL, single-quotes

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17607]
On 4.1-BETA-1

These work
```
        String query = "SELECT firstName FROM " + mapName + " WHERE lastName = 'Stevenson'";
        String query = "SELECT firstName FROM \"" + mapName + "\" WHERE lastName = 'Stevenson'";
```

But this fails
```
        String query = "SELECT firstName FROM '" + mapName + "' WHERE lastName = 'Stevenson'";
```
with
```
Was expecting one of:
    "LATERAL" ...
    "TABLE" ...
    "UNNEST" ...
    <IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BRACKET_QUOTED_IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    "(" ...
    
```

Map name should be able to be surrounded by single quotes to be consistent with field values.

**Comment by nfrankel** [comment]
I'd disagree. I don't think you'd ever write quotes around table names. I know you'd sometimes use backticks, when the table name is a reserved keyword.

https://stackoverflow.com/questions/11321491/when-to-use-single-quotes-double-quotes-and-backticks-in-mysql

**Comment by neilstevenson** [comment]
Ok, it's pretty low priority. For me, you can escape a field name with single or double quotes, so I'd expect the same for a table name. But it's a fairly obvious error message so it this becomes "*won't fix*" thats ok,

**Comment by mmedenjak** [comment]
@devozerov WDYT, is this simple enough to include in 4.1?

**Comment by devozerov** [comment]
@neilstevenson this as not an issue. It is up to the product to decide which syntax to use for object name and for literals. in our case, we use double-quotes for object names and single quotes for literals. The tokens used for literals and object names are typically different because otherwise, it will be very difficult for the parser to understand what the user meant.

**Comment by mmedenjak** [comment]
Closing as won't fix then, thank you for checking it out.
