### ISSUE TITLE
Hazelcast high CPU load (100%) when application is idle and has not traffic

### ISSUE THREAD

**Issue by ade90036** [hazelcast/hazelcast#17627]
**Describe the bug**
Hazelcast high CPU load (100%) when application is idle and has no traffic. 

![image](https://user-images.githubusercontent.com/6196152/94406166-8507b200-0169-11eb-9060-b483f9c0b1b0.png)

**Expected behavior**
Hazelcast CPU load should be marginal when application is idle and has no traffic.

**Additional context**
- OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
- Hazelcast 3.12.6
- Running embedded mode
- Running on an AWS EKS
- Hazelcast is running on seperate machines ( t2medium )
- Network is established via service discovery via DNS

**Hazelcast logs**

Hazelcast logs show that there was an issue with the connectivity of one of the nodes and the cluster `because it has not sent any heartbeats since` and then it removed the node and re-joined at later stage.

[Node1 -- 192.168.2.197](https://github.com/hazelcast/hazelcast/files/5290853/197.txt)
[Node1 -- 192.168.2.68](https://github.com/hazelcast/hazelcast/files/5290877/68.txt)

**VisualVM**

What i have observed is that after this procedure hazelcast re-joined the node but then i had two hazelcast threads with the same name (**IO.thread-in-1**) competing for CPU

![CPU](https://user-images.githubusercontent.com/6196152/94408363-9900e300-016c-11eb-86f8-75e3e8b0a7e2.jpg)

**Comment by ade90036** [comment]
This is the thread list for the nodes that is experiencing the high CPU (which is the two **IO.thread-in-1**)

![threads1](https://user-images.githubusercontent.com/6196152/94410617-758b6780-016f-11eb-9c85-80e8cbec4e57.jpg)

While the other node that doesn't experience high CPU usage and doesn't have two threads with the same name.

![thread2](https://user-images.githubusercontent.com/6196152/94410723-98b61700-016f-11eb-866f-6380142f5d4c.jpg)

**Comment by ade90036** [comment]
closing issue

apologies, it was something that I have introduced and I didn't spot immediately.

created an hazelcast node extension which is causing this issue under certain conditions and loads.

**Comment by mmedenjak** [comment]
@ade90036 glad to hear you've found the issue. Curious to hear though - why were you creating a custom node extension?

**Comment by ade90036** [comment]
```
[] 2020-09-25 10:02:52.059  INFO --- [           main] com.hazelcast.system                     : [192.168.2.197]:5701 [rapifactor-core] [3.12.6] Using com.hazelcast.instance.SymmetricEncryptionNodeExtension node extension
```
