### ISSUE TITLE
k8s HZ server

### ISSUE THREAD

**Issue by thesreyas** [hazelcast/hazelcast#17655]
Excerpt from *https://github.com/hazelcast/hazelcast-kubernetes*

The recommendation is to use StatefulSet for managing Hazelcast PODs; in case of using Deployment (or ReplicationController), the Hazelcast cluster may start with Split Brain (which will anyway re-form to one consistent cluster in a few minutes).

We have challenges to use Statefulset on k8s. Can you please highlight challenges if we go without statefulset?

**Comment by mmedenjak** [comment]
Question was answered on community slack, closing - https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1601562151081500.

**Comment by thesreyas** [comment]
@mmedenjak 
Thanks for your response
Unfortunately unable to signup to slack
Can you please  post that explanation here? It is very important for us for couple of discussions scheduled tomorrow.

**Comment by mmedenjak** [comment]
You can join the Hazelcast slack by getting an invitation from here - https://slack.hazelcast.com/.
