### ISSUE TITLE
Check whether the OSGI metadata is needed for the SQL module

### ISSUE THREAD

**Issue by devozerov** [hazelcast/hazelcast#17693]
Currently, the `MANIFEST.MF` of `hazelcast-sql.jar` doesn't have OSGI metadata (imports, exports, etc). This metadata is normally created by the `maven-bundle-plugin` (see other modules). The question is whether we need this metadata for the SQL module and if yes - what exactly is needed.

Another possible issue is that the classes from the `hazelcast-sql` module are not added to OSGI imports/exports of the `hazelcast-all.jar`. Again, it is not clear whether this is a problem or not, but for example packages of `hazelcast-spring` module are added to `hazelcast-all.jar`, even the private ones.

**Comment by mmedenjak** [comment]
Moving to backlog.

**Comment by devozerov** [comment]
No indications that this is a problem. The release artifacts passed the usual pre-release checks. Closing.
