### ISSUE TITLE
IMap#iterable(Predicate)

### ISSUE THREAD

**Issue by robinroos** [hazelcast/hazelcast#17735]
Targetting 4.1 

**Proposal**

Take the existing:
```
hazelcast/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java

Line 916 in 4fed159

 public <R> Iterator<R> iterator(int fetchSize, int partitionId, Projection<Map.Entry<K, V>, R> projection, 
```

And create a public API in IMap which differs from the above in that it:

1. does not require partitionId but works across all partitions, and
2. returns Iterable (not Iterator) so that it can be used as a stream source (as in Flux.fromIterable() ).

The actual implementation of the Iterable could be a simple wrapper of the Iterator to start with, and could be optimised in subsequent releases to be more efficient.  

The alternative, of returning an Iterator, is wrong, as no further Spliterator-level optimisation could ever be done.  Of course there is nothing wrong with exposing iterable() and also iterator(), but iterator() would be redundant.

**Please describe the problem you are trying to solve**

Streaming entire content of a map, perhaps subject to a Predicate, specifically such that the entire content of the map is not on Client (of Hazelcast) heap at the same time.

**Please describe the desired behavior**

Expose large portions of a map to applications which may want to externalize them over a Stream (e.g. Spring WebFlux, Reactor, Flux).

**Describe alternatives you've considered**

IMap#values (materializes entire result in client heap and is not viable for large datasets)
PagingPredicate (far too inefficient).
SQLEngine (requires predicate to be turned into a SQL-like String representation)

**Comment by mmedenjak** [comment]
Thank you for the issue, @robinroos . As I think this is a simple implementation, I'll add it to the next patch release. Also, since it's simple, I encourage you to send a PR. We'll be more than happy to review and merge it :)

**Comment by jerrinot** [comment]
fwiw: the new [Sql interface](https://docs.hazelcast.org/docs/4.1.1/manual/html-single/index.html#sql) [returns](https://github.com/hazelcast/hazelcast/blob/b6a11a28b34eda63508fd603da93bd5270ff3101/hazelcast/src/main/java/com/hazelcast/sql/SqlService.java#L135) `SqlResult` which is [extends](https://github.com/hazelcast/hazelcast/blob/0c51b07ee7ace940ee070f97a7ef37156368db38/hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java#L52) `Iterable<SqlRow>`

**Comment by viliam-durina** [comment]
In IMDG 4.1 you can use SQL to read a big map in a streaming way.
