### ISSUE TITLE
4.1: Auto-detection enables multicast joiner even when it's disabled explicitly

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#17748]
I'm starting Jet with this configuration
```java
JetConfig config = new JetConfig();
config.getHazelcastConfig().getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
Jet.newJetInstance(config);
```
and I can see this in my log:
```
14:53:26.273 [ INFO] [c.h.s.d.i.DiscoveryService] No discovery strategy is applicable for auto-detection
14:53:26.345 [ INFO] [c.h.i.i.Node] Using Multicast discovery
```
That's unexpected as multicast is explicitly disabled. 

When I start it with this config:
```java
JetConfig config = new JetConfig();
config.getHazelcastConfig().getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
config.getHazelcastConfig().getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
Jet.newJetInstance(config);
```
then I can see this: `14:54:44.394 [ WARN] [c.h.i.i.Node] No join method is enabled! Starting standalone.`
That's what I want. I believe when join is (explicitly?) disabled then auto-detection should not use it at all.

**Comment by mmedenjak** [comment]
@leszko how complicated is it to address this? We would like to start release verification for 4.1 this week

**Comment by leszko** [comment]
Currently, disabling Multicast has no effect.
```
config.getHazelcastConfig().getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
```

If you want to start standalone, you just disable auto-detection:
```
config.getHazelcastConfig().getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
```

I think that if disabling Multicast would make the auto-detection work but just without Multicast Joiner is slightly weird behavior.

The thing is that the default discovery now is "auto-detection" (not "multicast"). I know it's not 100% backward-compatible, but I guess we agreed on that in [TDD](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/1722908694/Discovery+Strategy+Auto+Detection+Technical+Design+Document) and [PR](https://github.com/hazelcast/hazelcast/pull/17112).

**Comment by jerrinot** [comment]
I recall the discussion now. After talking to Rafal more I am ok with the current behaviour. 
Rafal is going to mark it as a breaking change in the release notes.
