### ISSUE TITLE
Hazelcast IMDG -- Hazelcast Management Center -- Queue statistic

### ISSUE THREAD

**Issue by michele-deluca** [hazelcast/hazelcast#17751]
Hi, I use Hazelcast IMDG and Hazelcast Management Center in free edition and I need the possibility to clear the queue statistic 

- max-age

- min-age

- average-age

it is possible to add them into the future version?

thanks.

@Team: Management Center

@emre-aydin

**Comment by mmedenjak** [comment]
Hi @michele-deluca ! Thank you for the proposal. Added to the backlog so we assess the priority.

**Comment by michele-deluca** [comment]
Hi, have you any news regarding this enhancement?

**Comment by emre-aydin** [comment]
Hi @michele-deluca , unfortunately there are no updates. Let me talk to our PM and try to add this to our list of tasks for the next version.

**Comment by erosb** [comment]
Hello @michele-deluca MC 5.1 was released, including this feature.
