### ISSUE TITLE
Clusteruptime has extremely high values

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hazelcast#17772]
When a Phone Home query executed to find clusters up more than a certain time (e.g clusteruptime > 86400000 * 365 * 5 -- which is 5 years) the query returns hundred thousands of clusters. As an example, one cluster has an uptime of 1588190002492 ms (18381 days).

The bug is verified by @emre-aydin and it is in `com.hazelcast.internal.cluster.ClusterClock#getClusterUpTime` method.

Original issue: https://github.com/hazelcast/callhome/issues/27

**Comment by mmedenjak** [comment]
Moving into 5.1 based on the current scope of 5.0. Feel free to reach out to me if you consider this critical.

**Comment by Holmistr** [comment]
@promanenko @jgardiner68 Would it be possible to get the M&M team to take a look?

**Comment by promanenko** [comment]
@Holmistr unfortunately we don't have a lot of spare capacity in 5.1. 
@jgardiner68 How urgent is the fix?

**Comment by jgardiner68** [comment]
Given that the cluster needs to be up continuously for more than 5 years, I think this is low priority.
@AyberkSorgun this impacts you the most - can you work around it for now so this remains out of the 5.1 scope?
