### ISSUE TITLE
Confusing SQL message when client is disconnected

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#17851]
When client is not connected to cluster and you try to execute a SQL query - you get this error:

```
Client must be connected to at least one data member to execute SQL queries
```

It would be simpler to just say that client is not currently connected to the cluster. Most people will not understand what a data member is and it's not really relevant here (since you can't just have a cluster of lite members)

**Comment by mmedenjak** [comment]
> since you can't just have a cluster of lite members

In fact you can, which is why we have `com.hazelcast.partition.NoDataMemberInClusterException` in the first place, but I guess nobody actually does that.
