### ISSUE TITLE
Missing `user-code-deployment-permission` definition on 3.11 XSD

### ISSUE THREAD

**Issue by ilkerkorkut** [hazelcast/hazelcast#17859]
Missing `user-code-deployment-permission` definition under the `client-permissions` on [3.11 XSD](http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd)

`user-code-deployment-permission` definition should be added.

**Comment by sancar** [comment]
@ilkerkorkut I think this is fixed by https://github.com/hazelcast/hazelcast/pull/14310/files on 3.12 
Closing the issue.
