### ISSUE TITLE
hazelcast-sql-4.1.1-SNAPSHOT clash with Slf4j bindings

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#17862]
See https://github.com/hazelcast/hazelcast-jet/issues/2687. Appears in `hazelcast-jet-sql` but probably a `hazelcast-sql` issue.

When using the new SQL, complaints about multiple loggers

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/application.jar!/BOOT-INF/lib/hazelcast-sql-4.1.1-SNAPSHOT-original.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/application.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.13.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.StaticLoggerBinder]
```

**Comment by mmedenjak** [comment]
@devozerov @viliam-durina can you take a look?

**Comment by mmedenjak** [comment]
Is this fixed with https://github.com/hazelcast/hazelcast/pull/17864?

**Comment by devozerov** [comment]
This is a Jet-specific problem. A similar problem has been solved in IMDG here: https://github.com/hazelcast/hazelcast/pull/17689

**Comment by mmedenjak** [comment]
Thanks for checking, closing.
