### ISSUE TITLE
Cleanup of Rack and Host metadata from Zone Aware group

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#17879]
`HOST` and `RACK` informations at `ZoneAwareMemberGroupFactory` class are not used by any discovery plugin actively. Currently, only JClouds plugin uses `HOST` metadata but this plugins is already deprecated:
https://github.com/hazelcast/hazelcast-jclouds/blob/master/src/main/java/com/hazelcast/jclouds/JCloudsDiscoveryStrategy.java#L40

Azure plugin had used HOST before but it was removed via below commit:
https://github.com/hazelcast/hazelcast-azure/pull/13/files#diff-85cbec642184a3be0fa069a24feaa31789985fe61f84c6bac446de637476fd04L270

As far as I can understand from [PR](https://github.com/hazelcast/hazelcast/pull/8187) and [PRD](https://hazelcast.atlassian.net/wiki/spaces/EN/pages/88899702/More+Partition+Group+Strategies+AWS+Availability+Zones+and+Azure+Failure+Domains+Design) that add these metadata into the codebase, they are JClouds and Azure plugin specific parameters. Those parameters also create some confusion with other member group types like `HOST_AWARE`.

**Comment by mmedenjak** [comment]
Can we mark them as deprecated or document it in the javadoc and ref manual in 4.x?

**Comment by hasancelik** [comment]
@mmedenjak I think we can do both, WDYT @leszko ?

**Comment by leszko** [comment]
Yes, I think we can deprecate.
