### ISSUE TITLE
hazelcast-all 4.1 declares compile-time dependencies

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#17873]
See: https://mvnrepository.com/artifact/com.hazelcast/hazelcast-all/4.1

![image](https://user-images.githubusercontent.com/158619/99884897-a64cc200-2c31-11eb-8c56-181754082a91.png)

That's quite serious, a lot of projects use the hazelcast-all artifact.

**Comment by kwart** [comment]
The problematic piece is `hazelcast-sql` dependency in `hazelcast-all/pom.xml`.  When I comment it out, then the generated `dependency-reduced-pom.xml` is generated correctly without the dependencies.
