### ISSUE TITLE
Understanding Hazelcast prometheus metrics

### ISSUE THREAD

**Issue by shashanka981** [hazelcast/hazelcast#17880]
We are considering to have datadog monitoring in place for hazelcast exposed prometheus metrics. Due to lack of clear and reliable documentation, i had to reach out to understand in detail about these metrics ? 

can you elaborate on these metrics: 

a) When would active connection count and connection count differ ? Is it when a connection goes stale for reason when a member abruptly leaves the cluster?
b) For client connection count metric, for a given client, can there be more than 1 connection to a server member ?
c) How are following metrics differ - hazelcast_HazelcastInstance_ClientEngine_clientEndpointCount and hazelcast_HazelcastInstance_NetworkingService_clientConnectionCount
d) What does the metric "hazelcast_HazelcastInstance_ProxyService_proxyCount" indicate ? For eg: if i create 2 maps and 1 cache on a server member, would the count be considered as 3 regardless of number of replicas?
e) What does this metric represent - hazelcast_HazelcastInstance_clusterTime ? Is it the JVM uptime of the current member or does it represent the entire uptime of cluster ?
f) for metric - hazelcast_HazelcastInstance_OperationService_responseQueueSize , What operations can cause this queue to be used ? can i get a sample operation that cause the operations resposne to be sent to this response queue ?

**Comment by mmedenjak** [comment]
Hey @shashanka981 ! Thank you for the report. Not sure who to ping exactly but maybe @leszko or @emre-aydin could comment. My question being - are the metrics part of public or private API?

**Comment by emre-aydin** [comment]
@mmedenjak currently there's not much documentation about what each metric shows. I think we should treat them as public API and document them. Otherwise their usefulness becomes very limited.

**Comment by mmedenjak** [comment]
Right, thanks for the confirmation. I'll try to answer the original question then.

**Comment by mmedenjak** [comment]
@ufukyilmaz moving out of 4.2 to clean up the non-critical items but please keep working on it and if you manage to complete it before release branch is created, move it back into 4.2

**Comment by mmedenjak** [comment]
Thanks to @ufukyilmaz and others, much has been added to the latest snapshot reference manual (https://docs.hazelcast.com/imdg/latest-dev/list-of-hazelcast-metrics.html) and will be part of the upcoming release. Closing for now, we can improve the content on a per-item basis.
