### ISSUE TITLE
Map 'hits' metric goes down upon entry expiration

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#17930]
**Describe the bug**
If map entries expire (due to `time-to-live` setting for example), then those entries' hits will no longer be counted in the total hits for the Map. This can lead to the hit count fluctuating over time.

**Expected behavior**
The Map hits count increases monotonically (similar to `getCount`).

**To Reproduce**

1. Start a cluster with a map configured with `time-to-live-seconds` > 0. You may also wan a map with default TTL for comparison.
2. Add entries to the map(s).
3. Continuously perform `get()`s with keys in the Map to increase the hit count.
4. Observe (via Management Center, Prometheus, etc.) map hits will go down after entries are expired

**Additional context**

Versions: 4.0.2, 4.1 (haven't tested with others)
Java 11

**Comment by mmedenjak** [comment]
I guess this is because we only count the number of hits for live entries. Possibly we could add a separate metric that only increased. Any further comments @ahmetmircik ?

**Comment by ahmetmircik** [comment]
@mmedenjak Reason is, we check the size of record-store before calculating stats as a precondition, and if there is no entry, no stats is calculated. Hence after all entries are expired, there is no stats. Only removing that size check should be enough to see on Management Center.

**Comment by mmedenjak** [comment]
Great! But if we remove the check, we might return statistics for expired records until they get cleaned up by the expiration cleanup task, right? So eventually, the metric will go down to zero again?

**Comment by ahmetmircik** [comment]
No they don't depend on entry existence. We have them on recordstore level. Even all are expired, we still see the hits.

**Comment by mmedenjak** [comment]
Would you say then that removing this check makes sense? Or is there some reason why we should not remove it?

**Comment by ahmetmircik** [comment]
At first glance, it seems it should be ok to remove it.
