### ISSUE TITLE
SqlResult.close() method isn't thread-safe

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#17936]
The `SqlResult` interface doesn't declare any thread-safety rules. It's obvious that the returned Iterator is not thread-safe, it's also OK that the `iterator()` method itself isn't.

We should declare that `close()` can be called from another thread. This is necessary for Jet because it's common that the iterator's `hasNext` method blocks for a long periods of time. In the future with blocking operators it will also be important for IMDG so that the client waiting for a result can still cancel the query.

The `SqlResultImpl` already is thread-safe. The `SqlClientResult` isn't - it reads `iterator.last`, which is non-volatile and is mutated by the thread accessing the iterator. Also the iterator accesses the `closed` non-volatile field modified by the `close` method.

**Comment by devozerov** [comment]
Fixed in https://github.com/hazelcast/hazelcast/pull/18047
