### ISSUE TITLE
getMap hangs using nearcache and common pool

### ISSUE THREAD

**Issue by FrankSpitulski** [hazelcast/hazelcast#17959]
**Describe the bug**
The `HazelCastInstance.getMap()` function hangs when called in parallel during first use of a given map name if near cache is enabled.

**Expected behavior**
I expect that the default hazelcast spring cache manager can be invoked in parallel.

**To Reproduce**

See this unit test https://github.com/FrankSpitulski/rest-api-example/blob/hazelcast/src/test/java/org/example/hazelcast/services/ExampleServiceTest.java

**Additional context**

I ran this on MacOS 10.15 with jdk 8 and jdk 11. In the unit test you can change the properties at the top to make the test pass or fail and configure logging. Very rarely the test will succeed with the near cache enabled, just run it a few more times.

**Comment by ahmetmircik** [comment]
@FrankSpitulski Thanks for the report. Managed to reproduce the issue, seems all fork-join-pool threads are in waiting state. Except one thread, all are waiting end of map creation, that 1 remaining thread is waiting while trying to create map. When i played with system property `java.util.concurrent.ForkJoinPool.common.parallelism` and set it to 1 your reproducer ended successfully. I have a fix candidate for hazelcast side and will planning to send it after doing some further investigations.

**Comment by ahmetmircik** [comment]
We merged https://github.com/hazelcast/hazelcast/pull/17973 which we think as a solution for the issue. Please reopen this issue, if it is encountered again.
