### ISSUE TITLE
hazelcast WebFilter hazelcast.sessionId cookie not secure and not http only

### ISSUE THREAD

**Issue by ttux** [hazelcast/hazelcast#17951]
The com.hazelcast.web.WebFilter is not working as expected. I am using hazelcast with spring-boot. With the following bean:

```
    @Bean
    public WebFilter webFilter(HazelcastInstance hazelcastInstance) {
        Properties properties = new Properties();
        properties.put("instance-name", hazelcastInstance.getName());
        properties.put("sticky-session", "false");
        properties.put("map-name", "httpSessions");
        properties.put("cookie-path", "/");
        properties.put("cookie-secure", true);
        properties.put("cookie-http-only", true);
        return new WebFilter(properties);
    }
```

The hazelcast.sessionId cookie is not set with secure=true and http-only=true. This is with spring-boot 2.1.17, hazelcast 3.11.7, tomcat 9.0.39.

I have those spring properties set:
```
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
```

The JSESSIONID cookie is secure and http-only.

**Comment by mmedenjak** [comment]
Thank you for the report @ttux ! @enozcan can you take a look or see who can instead?

**Comment by enozcan** [comment]
Hi @ttux,
This one has been fixed but a new version has not yet released (the related issue: https://github.com/hazelcast/hazelcast-wm/issues/95). However, if you set the properties as string this will make it work for the previous versions as well:
```
properties.put("cookie-secure", "true");
properties.put("cookie-http-only", "true");
```
@mmedenjak I believe you can close the issue as it's also reported and fixed in wm repo.

**Comment by mmedenjak** [comment]
Thank you for the confirmation @enozcan ! @ttux please comment on the linked issue if you have further questions. Happy hazelcasting!
