### ISSUE TITLE
Hazelcast throwing Unable to register OperatingSystemMXBean method getMaxFileDescriptorCount used for probe os.maxFileDescriptorCount

### ISSUE THREAD

**Issue by geraldo-netto** [hazelcast/hazelcast#17957]
**Describe the bug**
Dear Friends,   

I'm using Hazelcast 3.11 on windows 10 professional 64 bits, 64 GB of ram with OpenJDK (AdoptOpenJDK 1.8.0_265-b01, mixed mode) and while my application starts with the embedded Hazelcast correctly and Hazelcast works like a charm, I see the following exceptions during the startup:

```
2020-12-09 16:16:45,383 TRACE [main] c.h.i.m.m.OperatingSystemMetricSet - Unable to register OperatingSystemMXBean method getMaxFileDescriptorCount used for probe os.maxFileDescriptorCount
java.lang.NoSuchMethodException: sun.management.OperatingSystemImpl.getMaxFileDescriptorCount()
```

```
2020-12-09 16:16:45,384 TRACE [main] c.h.i.m.m.OperatingSystemMetricSet - Unable to register OperatingSystemMXBean method getOpenFileDescriptorCount used for probe os.openFileDescriptorCount
java.lang.NoSuchMethodException: sun.management.OperatingSystemImpl.getOpenFileDescriptorCount()
```

This is my hazelcast.xml:
```xml
<hazelcast 
    xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.8.xsd"
    xmlns="http://www.hazelcast.com/schema/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <network>
        <port auto-increment="false">5910</port>
        <join>
            <multicast enabled="false" />
        </join>
    </network>
    <map name="token">
        <max-idle-seconds>10</max-idle-seconds>
        <time-to-live-seconds>10</time-to-live-seconds>
    </map>
</hazelcast>
```

**Expected behavior**
It seems to be an issue on how windows handle file descriptors according to [this stackoverflow post](https://stackoverflow.com/questions/45244011/java-getopenfiledescriptorcount-for-windows)

**To Reproduce**
It seems, all it is required is a Windows operating system with OpenJDK with Hazelcast logs on TRACE

**Additional context**
Please, check the attached log
[restapi.log](https://github.com/hazelcast/hazelcast/files/5666977/restapi.log)

**Comment by orcunc** [comment]
Fixed by https://github.com/hazelcast/hazelcast-mono/commit/91604323f07e5cfe373884f41757582046dbb085
long time ago. 

Tested on HZ version 5.5-SNAPSHOT. The issue does not exist any more
