### ISSUE TITLE
MapIndexScanExecTest is not testing what is expected 

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#18030]
I took a more close look at the `MapIndexScanExecTest` and I'm not sure the test is correct. There is a `checkScan` method that is supposed to check in the end the returned results. But instead, it has only the below lines that assert nothing.

```
        results.sort(Integer::compareTo);
        expectedResults0.sort(Integer::compareTo);
```
Moreover, we run the scan only on the local partitions and we actually cannot assume what is the expected result, because the local partitions contain only a part of the entries.

**Comment by mmedenjak** [comment]
@devozerov can you take a look?
