### ISSUE TITLE
4.1 auto-detection re-activates de-activated multicast

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#18042]
If my config looks like only this

```
hazelcast:
  network:
    join:
      multicast:
        enabled: false
```

On IMDG 4.0, this gives
```
c.h.i.i.Node                  : [xxx.xxx.xxx.xxx]:5701 [dev] [4.0.3] No join method is enabled! Starting standalone.
```

On IMDG 4.1, this gives
```
c.h.s.d.i.DiscoveryService    : [xxx.xxx.xxx.xxx]:5701 [dev] [4.1.1] No discovery strategy is applicable for auto-detection
c.h.i.i.Node                  : [xxx.xxx.xxx.xxx]:5701 [dev] [4.1.1] Using Multicast discovery
```

Auto-detection re-activates multicast.

Any cluster set-up standalone (e.g. a JUnit test) can now join others if upgraded, against configuration.

**Comment by jerrinot** [comment]
it's a known and documented behaviour change. see: https://docs.hazelcast.org/docs/rn/index.html#bc-41
it's a dup of https://github.com/hazelcast/hazelcast/issues/17748

**Comment by jerrinot** [comment]
Basically in 4.0 and older this was the default:
1. multicast on
2. everything else off

in 4.1 and newer this is the default:
1. auto-detection on
2. everything else off
So disabling multicast explicitly is a no-op. Also when you enable any mechanism explicitly then the auto-detection is automatically disabled.
