### ISSUE TITLE
Try-catch block does not catch Throwable and as a consequence java.lang.NoClassDefFoundError can not be sent to the Client

### ISSUE THREAD

**Issue by nosan** [hazelcast/hazelcast#18052]
A try-catch block should catch `Throwable` instead of `Exception`.
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryOperation.java#L266
It can not catch `java.lang.NoClassDefFoundError`: and the exception can not be sent to the client.

**Context**:
Customer uploaded a wrong jar to hazelcast classpath (`MyEnum` enum is not present in the final JAR), then customer tries to apply a predicate:
```java
EntryObject e = new PredicateBuilder().getEntryObject();
Predicate predicate = e.get("key").isNotNull();
map.values(predicate) //this call never finish
```

@sancar 

> Ok. Tried in my local. When in memory format of the map is NATIVE, client can not get the exception. When I am switching it to BINARY, the client gets the exception as expected.
Probably something on the NATIVE codepath is swallowing the exception.

**Comment by sancar** [comment]
Fixed by https://github.com/hazelcast/hazelcast-enterprise/pull/3908 and https://github.com/hazelcast/hazelcast/pull/18082
