### ISSUE TITLE
Can add an request for map size in rest api?

### ISSUE THREAD

**Issue by wubumihuo** [hazelcast/hazelcast#18069]
It would be useful to have the ability to request Map size from the REST interface. This will be very userful for our monitoring.
**version:**
We now use Hazelcast Version 4.1.

**update:**
when we want to request map size like GET  {ip}:{port}/hazelcast/rest/maps/test/size ，it give the response of the value in map named "test" and the key is "size".

**code:**
The code in com.hazelcast.internal.ascii.rest.HttpGetCommandProcessor can add the feature?

**Comment by wubumihuo** [comment]
> It would be useful to have the ability to request Map size from the REST interface. This will be very userful for our monitoring.
> **version:**
> We now use Hazelcast Version 4.1.
> 
> **update:**
> when we want to request map size like GET {ip}:{port}/hazelcast/rest/maps/test/size ，it give the response of the value in map named "test" and the key is "size".
> 
> **code:**
> The code in com.hazelcast.internal.ascii.rest.HttpGetCommandProcessor can add the feature?

**Comment by wubumihuo** [comment]
can anyone help me ?

**Comment by mmedenjak** [comment]
Hi @wubumihuo ! Thank you for the suggestion. We will not add this capability for now as we assess it as low priority. I suggest closing this issue until we get more community interest cc @Holmistr @nfrankel

**Comment by wubumihuo** [comment]
@mneedham tks. I'd close the issue,I hope more can watch and  support it  in Backlog
