### ISSUE TITLE
Generalize Sort Merge exchange

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#18063]
In the 4.2 release we introduced a `SortMergeExchangePhysicalRel` that merges sorted input streams from several nodes into a single sorted stream on a single node. This assumes that the sorting is a top-level operator, while it could be not the case in the future. In a more generalized plan, we have to avoid `SortMergeExchangePhysicalRel` and detect that the sorting is needed on the later plan generation stage.

**Comment by mmedenjak** [comment]
@Holmistr @petrpleshachkov can this go to backlog?

**Comment by mmedenjak** [comment]
@viliam-durina how come this is closed? Is it already fixed by something or otherwise obsolete?

**Comment by viliam-durina** [comment]
It's an enhancement, a generalization for future features. We're not going to do more features for the imdg sql engine.
