### ISSUE TITLE
Distributed/Remote ClassLoader

### ISSUE THREAD

**Issue by olamy** [hazelcast/hazelcast#1807]
Currently if I have a look at http://www.hazelcast.org/ Tab "Executor Service".
This sample simply doesn't work on a cluster (multiple nodes) as the inner class MessagePrinter is not defined in the classloader of other nodes.
I wonder if it's a feature you could be interested? (Yes I know it's possible to have jars on remote nodes but not very user friendly).

**Comment by jerrinot** [comment]
for anyone who is interested in this. there is a community project at: https://github.com/serkan-ozal/hermgen

obviously it's not supported by Hazelcast, but it would be great to start some more activity here.

**Comment by mdogan** [comment]
See User Code Deployment: 

http://docs.hazelcast.org/docs/3.8-RC1/manual/html-single/index.html#user-code-deployment-beta

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/UserCodeDeploymentConfig.java

**Comment by noctarius** [comment]
Closing this (still) open issue which was forgotten to be closed after 3.8 release. The @mdogan's comment.
