### ISSUE TITLE
Hazelcast documentation incorrectly states that "local" option is available for ItemListener [HZ-2777]

### ISSUE THREAD

**Issue by mgoldver** [hazelcast/hazelcast#18083]
**Describe the bug**
The documentation states:
`item-listeners: Lets you add listeners (listener classes) for the list items. ... You can set **local** to true if you want to listen to the items on the local member.`

**Expected behavior**
The **local** option is not available for IQueue, ISet, IList or ReplicatedMap ItemListener.

**To Reproduce**
instance.getQueue("someQueue")
                .addItemListener(new MyItemListener<>(), true);
No option to specify if the listener should only run on local member that hosts the queue.

**Comment by mmedenjak** [comment]
Thank you for the report @mgoldver ! I think this is something that needs to be cleaned up on the level of documentation as I don't believe we'll add local listeners for other structures just yet.
