### ISSUE TITLE
Indexes don't support some of the temporal types

### ISSUE THREAD

**Issue by petrpleshachkov** [hazelcast/hazelcast#18109]
Our indexes don't support `LocalTime`, `LocalDate`, `LocalDateTime` and `OffsetDateTime`. Since our Order by solely relies on the indexes, it also imposes limitations on the supported order by field types.

**Comment by mmedenjak** [comment]
@devozerov @viliam-durina @petrpleshachkov how big of a task is this? Is it safe enough and small enough to do before GA release?

**Comment by Holmistr** [comment]
This would be a massive benefit if we could get it in 4.2.

**Comment by viliam-durina** [comment]
I don't know myself but @devozerov mentioned that it might be quite easy.
