### ISSUE TITLE
Removal of canEvictRecord from EvictBatchBackupOperation

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#18111]
A fix is needed for the described issue below after new expiry system merge.
```
private boolean canEvictRecord(Record existingRecord, ExpiredKey expiredKey) {
        if (existingRecord == null) {
            return false;
        }

        // creation time of a record is always same between all replicas.
        // by doing creation time check we can prevent un-wanted record deletion on replicas.
        // un-wanted record deletion example: on primary record was expired and queued but before
        // we send it to backups a new record is added with same key, when we send queued item
        // to backups, backups should not remove it. Comparing creation times to be sure that
        // we are deleting correct record.
        // since 3.11, creationTime is maintained at second accuracy
        return existingRecord.getCreationTime() == zeroOutMs(expiredKey.getCreationTime());
    }
```

**Comment by Holmistr** [comment]
@ahmetmircik @mmedenjak I don't understand the impact of this issue. Could you please clarify? 
Based on the comment, it looks like we're living with it for several releases, there's no community reaction on it, I would say it's OK to move it out of 4.2. Feel free to correct me.

**Comment by ahmetmircik** [comment]
@Holmistr There was a best effort solution for this in versions before 4.2. I removed that during latest expiry system changes but not yet implemented anything in place of it. This is not beta blocker but i have some solution idea and hope to add it into 4.2 before GA.

**Comment by Holmistr** [comment]
@ahmetmircik Sounds good than. Moving back to 4.2.
