### ISSUE TITLE
Serialization of CopyOnWriteArrayList is racy

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18129]
The `CopyOnWriteArrayListStreamSerializer` delegates the serialization to the superclass, which is racy. It first writes the size and then the elements, but the collection can be modified in the meantime. Also the deserialization adds the elements one by one, which causes the copy-on-write.

Causes hazelcast/hazelcast-jet#2864.

**Comment by sancar** [comment]
@viliam-durina @mdumandag 
This race part valid for serialization of any Concurrent DataStructure. 
And the solution is to clone them before writing. 
But I don’t think this should be responsibility of the serializer. Because it can unnecessarily create the clone. 
I think the one passing this object to the serialization should make sure that it is not shared with any other thread. If it must be, the caller should clone it before passing to the serialization.

**Comment by viliam-durina** [comment]
I agree that serialization doesn't normally expect concurrent access to serialized objects. But a concurrent data structure might be an exception. It kind of makes the serializer useless - you use COWAL if you have concurrent access, but you can't serialize. Cloning isn't cheap. And fixing it is easy (pseudocode):
```java
write() {
    writeInt(list.size());
    for (Object o : list) {
        writeObject(o);
    }
    writeObject(TERMINATOR);
}

read() {
    int sizeHint = readInt();
    List<Object> list = new ArrayList<>(sizeHint);
    for (Object o; (o = readObject()) != TERMINATOR; ) {
        list.add(o);
    }
    return new CopyOnWriteArrayList<>(list);
}
```

**Comment by sancar** [comment]
Also keep in mind that we need something backward compatible. 


Written with old versions should be read by new versions. 
This can be implemented by checking version of ObjectDataOutput. If the version is old, then we will not expect `TERMINATOR` and rely on size. 

Written with new versions should be read by old versions. This can work as long as there is no concurrent removal. We can read this object in that case, but if there is something on the same buffer written after this, we can not read it again. For example reading writing List< CopyOnWriteArrayList > will fail. 
Or operations like entrySet/values on a map where the values are  `CopyOnWriteArrayList` will fail.

**Comment by sancar** [comment]
@viliam-durina As we don't want to break compatibility I want to close this as we will not address it.
It seems that we need to live with workarounds. 
Do you have a suggestion ? Are you ok with closing this ?

**Comment by ramizdundar** [comment]
@sancar After we have talked I have a new idea about this one. Let me open a draft PR in few hours.

**Comment by sancar** [comment]
@ramizdundar I think we will need backports for this to 4.1.z and 4.0.z

**Comment by ramizdundar** [comment]
@sancar Ok, I will try two do that.
