### ISSUE TITLE
IMap becomes empty after another client connection

### ISSUE THREAD

**Issue by longtimeago** [hazelcast/hazelcast#18151]
**Describe the bug**
IMap becomes empty after another client connection

**Expected behavior**

**To Reproduce**
Scenario:
1) client 1 put (setAsync) a value to IMap with and starts reading the size of the map (in a cycle); it can see 1
2) client 2 connects to the same IMap and starts reading the size of the map (in a cycle) - it can see ZERO map size
3) client 1 now see ZERO too!

So, the map basically got cleared after client 2 is connected

**Additional context**
Hazelcast server (3.9.2) - 1 node in Docker (docker.io/hazelcast/hazelcast:3.9.2), default `hazelcast.xml`
2 Java clients (3.9.2) running in separate JVMs (1.8.0_242 Coretto), no near-cache, async start
Host OS - Ubuntu 20.04.2 LTS (5.8.0-41-generic)

**Comment by mmedenjak** [comment]
Hi @longtimeago, thank you for your report. @sancar any explanation why this would be the case?

**Comment by sancar** [comment]
I don't have any explanation for that. This should not be possible.
@longtimeago Can you prepare a project to show the failure ?
Is it consistently showing the same behaviour ? 

A long shot but I will note anyway. Only explanation for this behaviour that I have is TTL.
Could you be using the setAsync with TTL accidentally?https://github.com/hazelcast/hazelcast/blob/v3.9.2/hazelcast/src/main/java/com/hazelcast/core/IMap.java#L610

**Comment by longtimeago** [comment]
@sancar thanks a lot for the answer! Let me try to answer your questions one-by-one :)

> Can you prepare a project to show the failure ?

Can't promise but will try :)

> Is it consistently showing the same behaviour ?

Yes, it is. I don't even need to restart Hazelcast server to reproduce that (but after server restart it's the same as well)

> Only explanation for this behaviour that I have is TTL.

Not sure wdym? From what I got even with setAsync and TTL we should not see such behavior, right?

> Could you be using the setAsync with TTL accidentally?

Noup, it was a deliberate decision :)

> 1. client 1 put (setAsync) a value to IMap with and starts reading the size of the map (in a cycle); it can see 1

Note that here reading from the map by client 1 is not our real use-case; it's there just to know what client 1 can see

**Comment by sancar** [comment]
So, you are using TTL. 
I think I did not understand the problem. 
To be clear, if you are using a TTL value lets say 5 seconds. The entry will be deleted from the map after 5 seconds. And this is the expected behaviour. 

From the issue description, I think you are just seeing the expected behaviour. The second client connection is just happens to be at the same time with the TTL end. 

Am I missing something?

**Comment by longtimeago** [comment]
@sancar Oh, wait a sec. Sorry for the mess, lets forget about TTL (I said about TTL because in production use-case we use TTL).

In test case from the issue description the weird behavior is observed with setAsync **without TTL**

**Comment by sancar** [comment]
If this is not TTL, then I don't know where to start.
Client connections does not have any relation with Map directly. I don't see a way for clients to affect Map. 

Another guess. If this is not ttl, only way a client sees an empty map(where it was full initially) could be a cluster being restarted or client disconnecting and connecting back to a different cluster. Please double check your client logs to see this is not happening. 

And please provide a small test suite that we can try and see the problem.

**Comment by mmedenjak** [comment]
@longtimeago are you able to provide more information? ☝️

**Comment by longtimeago** [comment]
@sancar @mmedenjak ouch ... I've found a problem in my code while writing a test case for you. It's not an issue with Hazelcast itself. Really sorry that I didn't checked that before :(

Thanks a lot for your time and help!
