### ISSUE TITLE
map config / eviction size="0" with HazelcastLocalCacheRegionFactory / reported puts>0

### ISSUE THREAD

**Issue by qeepcologne** [hazelcast/hazelcast#18158]
I am using https://github.com/hazelcast/hazelcast-hibernate and set config like that:
```
<map name="de.k2interactive.qeep.users.db.PluginDataDto">
    <eviction size="0" />
</map>
```
to temporary switch off cache.
    
I am not shure if this is working correctly:
- i cannot look into the map because i am using HazelcastLocalCacheRegionFactory
which do not expose maps (only ITopic) for the second level Caches.
- checking EvictionConfig.setSize it says: any non-negative number, nothing found
here about 0 as special value for unlimited or so.

expected behavior:
- Caching is turned off, for that class.
- when i checked hibernate statistics, the number of puts is >0

I also read that size should be greater then hazelcast.partition.count (which is 83 in our setup).
If size 0 is not possible or size is modified based on partition count, there should be some warning
and documentation in code.
Or is i just reported wrong at hibernate (a put for hibernate but immediately dropped in hz)?

**Comment by mmedenjak** [comment]
@qeepcologne thank you for your report. @pivovarit @enozcan any ideas about this issue?

**Comment by enozcan** [comment]
Hi @qeepcologne,

Based on your hazelcast-hibernate version, eviction size of 0 might be assumed as ignoring the size based eviction. That means, cache size will not affect the eviction. Which version do you use?

> a put for hibernate but immediately dropped in hz

What about hit counts? Hibernate might count it as a put but the L2C might evict it immediately. I suggest you to check second level cache hit count also.

**Comment by qeepcologne** [comment]
@enozcan thanks for the quick answer.
version is hazelcast-hibernate53:2.2.0
hitCount and missCount is 0 (but was already 0 before setting the size to zero, that's the reason why i wanted to turn off that cache, because we cache that on a higher level).

**Comment by enozcan** [comment]
@qeepcologne I just verified that in v2.2.0, `eviction-size=0` ends up with Integer.MAX_VALUE eviction size for a region. So this won't be appropriate to use for turning the cache off. But the hit, miss and put statistics for local regions must be correctly reported. Are you sure you're checking the right region's statistics? The following code will return the hit counts for all L2C regions with their names. Make sure the cache names match with  the ones you configured in hazelcast.xml:
```java
Arrays.stream(sf.getStatistics().getSecondLevelCacheRegionNames()).forEach(r ->
    System.out.printf("Region: %s, hits: %d\n", r, sf.getStatistics().getCacheRegionStatistics(r).getHitCount()));
```

**Comment by pivovarit** [comment]
If you just want to bypass the second-level cache, it's better to turn it off at Hibernate's level by setting `hibernate.cache.use_second_level_cache` to `true`. 

However, I'm not sure if that would solve your problem. I assume you want to turn it off only for one particular entity?

**Comment by qeepcologne** [comment]
@enozcan:
´´´eviction-size=0 ends up with Integer.MAX_VALUE´´´
This is what i was afraid of and why i opened the bug for, this is not documented in any way in EvictionConfig.

I was using getDomainDataRegionStatistics but that should make no difference here.

Ok lets change the question: how to turn off the cache for a specific dto for/via hazelcast(config)?
- turning off all caches via use_second_level_cache is obviously not the solution.
- also removing the cache annotation is also not the solution (there are use cases, where we
we use the same dto class in a different context for another data source (e.g. master and slave
database connection, datasource for api (clustered setup with hazelcast) or simple datasource with ehcache for admin-tools, jobs etc.)

**Comment by enozcan** [comment]
@qeepcologne I do not think it's possible to turn off the caching of a specific entry at Hazelcast configuration level. With v2.2.0, LocalRegionCache is backed by Caffeine cache and [it actually supports](https://github.com/ben-manes/caffeine/blob/9423f15d6cdb19e75f71287bf71ba6c11dbd3aa1/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java#L354-L355) cache size of 0 where entries are immediately evicted. But Hazelcast assumes 0 size value as Integer.MAX_VALUE. So this could be included with the following releases. If you think it's good to have and open an issue regarding this (and the documenting part) at https://github.com/hazelcast/hazelcast-hibernate, I believe it will be more visible and people will be more responsive for the plugin in particular.

For the time being, an exhaustive and the closest solution to your problem seems like a map config where eviction size=1 and ttl=1 - it's not efficient at all tho.

**Comment by qeepcologne** [comment]
@enozcan thanks for the detailed explanation, i will move the topic to hazelcast-hibernate.
