### ISSUE TITLE
Hazelcast internal callbacks shouldn't use ForkJoinPool#commonPool [HZ-658]

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#18190]
Using the `ForkJoinPool#commonPool` for Hazelcast operations risks blocking Hazelcast progress due to other misbehaving applications/libraries. Instead, a separate Hazelcast-internal pool should be used for those. Hazelcast code should execute dependent stages on that separate executor.

**Comment by mmedenjak** [comment]
How big of a task would this be? Is it small and safe enough to do in the post-feature-freeze period?

**Comment by vbekiaris** [comment]
There are ~80 production code usages of `whenCompleteAsync(BiConsumer)`, which is the most popular dependent stage execution method. These have to be migrated to use a separate `ForkJoinPool` executor instance with parallelism > 1. I think it is safe to do this after feature freeze. In the long run, we should figure out a way to enforce this rule in the production codebase.

**Comment by Holmistr** [comment]
@vbekiaris @mmedenjak I don't see this as a must have for 4.2. Definitely worth taking a look at higher priority and if we'll have time in 4.2, sure. But the current state has been like this for multiple releases (years?) with no massive impact up to my knowledge.

**Comment by vbekiaris** [comment]
@Holmistr actually this was introduced with 4.0 release, since the bump to JDK 8 + `CompletionStage` for async API. Probably not a must have, but important to fix.
