### ISSUE TITLE
REST returns HTTP 204 (No Content) 

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#18206]
On 4.1.1, I get an HTTP 204 querying a valid map via REST

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/ascii/rest/HttpCommandProcessor.java#L49 and https://docs.hazelcast.com/imdg/latest/management/rest-endpoint-groups.html give the rest end point

If I do this in my code
```
        	hazelcastInstance.getMap("neil").put("hello", "world");
```

Then REST gives me a 204 rather than the size
```
% curl -v http:/127.0.0.1:5701/hazelcast/rest/maps/neil/size
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5701 (#0)
> GET /hazelcast/rest/maps/neil/size HTTP/1.1
> Host: 127.0.0.1:5701
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Content-Length: 0
< 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection 0

```

**Comment by neilstevenson** [comment]
Config,
```
    rest-api:
      enabled: true
      endpoint-groups:
        CLUSTER_READ:
          enabled: true 
        DATA:
          enabled: true 
        HEALTH_CHECK:
          enabled: true 
```

**Comment by neilstevenson** [comment]
Error from logs
```
2021-02-12 17:07:00.945  WARN 57690 --- [.IO.thread-in-0] c.h.internal.nio.ascii.RestApiFilter     : [127.0.0.1]:5701 [dev] [4.1.1] No REST group matching URI: /hazelcast/rest/maps
```

**Comment by vbekiaris** [comment]
@neilstevenson this is not an issue: map `GET` does not return the map's size with the `/size` suffix - this is only applicable to queues. Instead, `size` is interpreted as a key, so `204 NO CONTENT` is an appropriate response since there is no key `size` in your map. See also https://docs.hazelcast.com/imdg/latest/clients/rest.html#retrieving-entries-from-a-map-for-rest-client

**Comment by mmedenjak** [comment]
Thank you for the analysis @vbekiaris ! Closing as a non-issue. Feel free to comment and reopen if this is not the case.
