### ISSUE TITLE
Inefficient IMap.entrySet() on a PartitionIdSet 

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#18240]
https://github.com/hazelcast/hazelcast/pull/17886 introduced IMap.entrySet() on a PartitionIdSet 

It's working, but it's extremely inefficient. It's practically a coincidence that it's working at all. It only works thanks to this fallback: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L125-L128

What is the problem: 
1. at first we execute the fast-path: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L124

But the fast-path fails and the slowpath/fallback kicks in: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L126

The fallback will succeed so it appears as if everything was working fine.  However it means each query is executed twice. 

This is the problem: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L282-L296
This method accepts `PartitionIdSet partitionIdSet` as a parameter, but it only use the `partitionIdSet` to resolve the members owning the request partitions. The actual query operations does NOT contain the partition set -> it will evaluate all partitions owned by the target member. 

This means the result will be thrown away at this point: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L205-L214 
because it contains more partitions than it was requested. 

And finally this will trigger the slowpath: https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L125

How to reproduce it: 
1. Disable the slowpath at https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryEngineImpl.java#L125-L127 -  comment it out
2. Run `whenSelectingPartitionSubset()` test(s)

**Comment by mmedenjak** [comment]
Does this need to go into 4.2? @viliam-durina can you check it out?

**Comment by ahmetmircik** [comment]
Seems like this issue can also be the root cause of slowness in this test: https://github.com/hazelcast/hazelcast/issues/18087 (reverted and tried)

**Comment by mmedenjak** [comment]
cc @mdumandag ☝️

**Comment by viliam-durina** [comment]
@mmedenjak I think it's not critical. It's only used internally from Jet, and in that case the actual PartitionIdSet contains local all partitions of one member, if the cluster is stable. It might be an issue if some partition was migrated, but only until the Jet job restarts.

Anyway, we should fix it.
