### ISSUE TITLE
hazelcast-4.0.2- java.io.EOFException

### ISSUE THREAD

**Issue by mygitdds** [hazelcast/hazelcast#18252]
Hazelcast-4.0.2 has no problem starting a node in k8s, starting the second node and reporting an error com.hazelcast.nio . serialization.HazelcastSerializationException : java.io.EOFException

There is no such problem in the version of hzelcast 3. X, which has occurred in the recent upgrade

**Comment by mmedenjak** [comment]
@mygitdds can you provide the full logs? The exception itself is not enough to diagnose the issue.

**Comment by sancar** [comment]
@mygitdds I am closing the issue because of inactivity. Feel free to reopen if needed.
