### ISSUE TITLE
QueryCache Data Migrated event

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#18275]
Hi,

we can add few types of MapListeners to QueryCache, namely add listener, update, remove, clear all. However, when new node is joining the cluster, there's no event to represent migration of QueryCache data to new node. While it's not urgent or feature-breaking thing, ability to watch for such changes willl be welcome - it will allow full data changes tracking on every node.

We _could_ possibly use partition migration listener, but it's a completely separate kind of listener, not tracking entries like other MapListeners mentioned above. While similar in concept, behaviour is slightly different.

**Comment by Holmistr** [comment]
Hi @TomaszGaweda , thanks a lot for the idea! :) 

We reviewed and discussed the proposal with the team. We concluded that since we don't see that many users use C

**Comment by Holmistr** [comment]
Hi @TomaszGaweda , thanks a lot for the idea! :) 

We reviewed and discussed the proposal with the team. We don't see that many users using Continuous Query Cache and even fewer adding the listeners to it. We concluded that this feature request **at this point** doesn't fit within the longer vision, so I'm going to close this issue.

However, if the demand for it arises from the community, we're happy to reconsider this decision. Please, vote on this issue (e.g. with thumbs up or a comment) if you find it useful as well.
