### ISSUE TITLE
Client endpoints are not immediately removed when the connection is closed

### ISSUE THREAD

**Issue by mdumandag** [hazelcast/hazelcast#18318]
**Describe the bug**
When a client disconnects from the cluster its server-side connection is closed, but its related `ClientEndpoint`
 is not removed immediately.

**Expected behavior**
When the connection related to the client is closed, its endpoint should be removed immediately.

**To Reproduce**

1. Start a member
2. Start a client, and then shutdown it
3. Check the logs, there is a delay between the closing of the connection and endpoint removal.

**Additional context**
This possibly a regression introduced in https://github.com/hazelcast/hazelcast/pull/16925. For client connections, the [code](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java#L178) in 16925 (and also the code in the master) does not call ` fireConnectionRemovedEvent` (the plane index for the client connections is always `-1` and client connections do not exist maps stored inside the plane) which in turn calls https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java#L415 and removes the endpoint. 

ClientEndpoints are removed thanks to https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java#L79 after some delay (the task runs periodically every 10 seconds), but as the comment in the ClientHeartbeatMonitor suggests this should only happen in some edge cases. By default, we should remove client endpoints immediately after their corresponding connection is removed.

**Comment by mmedenjak** [comment]
Moving out of 4.2, feel free to move back if it gets merged/fixed before release branch is created.
