### ISSUE TITLE
ClientStateListener missing from Javadoc

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#18333]
The `com.hazelcast.client.util.ClientStateListener` class, which is used in a [code sample](https://github.com/hazelcast/hazelcast-code-samples/blob/master/clients/client-connection-strategy/src/main/java/com/hazelcast/samples/ClientStrategy.java) as well as an [example in the IMDG docs](https://docs.hazelcast.com/imdg/latest/clients/java.html#async-start-and-reconnect-modes), cannot be found in the public Javadoc. This gives the false impression that it's not for public use.

**Comment by sumnerib** [comment]
Related: https://github.com/hazelcast/imdg-docs/issues/97

**Comment by sancar** [comment]
My findings, 

in 4.x
https://github.com/hazelcast/hazelcast/blob/master/pom.xml#L63
It looks like we are excluding util package from javadoc.
We have the same on 3.12 for releasing snapshot
https://github.com/hazelcast/hazelcast/blob/3.12.z/pom.xml#L813
But it is missing for the actual release. So 3.12 official release javadocs contains all the internal API on the javadoc.

I found this fix for release on 4.0. It needs to be backported to 3.12.x and 
client.util should not be excluded on 4.0.
https://github.com/hazelcast/hazelcast/pull/15589
