### ISSUE TITLE
ListenableFuture support (or similar)

### ISSUE THREAD

**Issue by mjgp2** [hazelcast/hazelcast#1837]
Many operations currently return a Future which you cannot attach a listener of any type to. It is an absolute necessity IMHO that you should be able to be notified, for example, when a map.get has finished - otherwise hazelcast cannot fit into a async/evented stack without using blcokibg operations with a thread pool that supports such a pattern, which is v sad :(

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue.

**Comment by pveentjer** [comment]
I'm going to close this ticket. At quite a few places we are now exposing this 'ListenableFuture' e.g. IMap.getAsync or IAtomicLong.getAsync. So if there are any request for particular methods, please open a ticket for that method(s).
