### ISSUE TITLE
Failing WHERE clause with double quoted condition

### ISSUE THREAD

**Issue by PavloBida** [hazelcast/hazelcast#18382]
If a query contains WHERE clause, with condition value wrapped in double quotes - the application starts behaving as if that value is a column name.

**Actual behaviour**
For the following query:
```
"SELECT registered FROM map_object WHERE eyeColor=\"brown\""
```
We get the following output:
```
com.hazelcast.sql.HazelcastSqlException: From line 1, column 50 to line 1, column 56: Column 'brown' not found in any table
```
Note: if double quotes are replaced with single quotes - application behaves as expected and returns query result.

**Expected behaviour**
Condition value for WHERE clause should be possible to specify in both, single quotes and double quotes.
OR
If there's a constraint and double quotes are not supported by design - output meaningful error message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Execute any SQL query, containing WHERE clause of the following format: WHERE column=\"value\"

The following test is failing of the bug above:
https://github.com/PavloBida/hazelcast/blob/7c2a0e132df1e88396f9e84fbb1c43e91d90b97b/hazelcast-sql-core/src/test/java/com/hazelcast/sql/SqlIntegrationTest.java#L87

**Comment by viliam-durina** [comment]
Double quotes is a basic SQL syntax. Single quotes are used for string literals, double quotes are used for identifiers (i.e. column names, table names...).
