### ISSUE TITLE
TestSpringManagedHazelcastTransaction

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18448]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4379

com.hazelcast.spring.transaction.TestSpringManagedHazelcastTransaction.transactionalServiceBeanInvocation_nestedWithPropagationRequiresNew
com.hazelcast.spring.transaction.TestSpringManagedHazelcastTransaction.transactionalServiceBeanInvocation_rollback

**Comment by gurbuzali** [comment]
cloased via https://github.com/hazelcast/hazelcast/pull/18467
