### ISSUE TITLE
MySqlCdcIntegrationTest

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18451]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4381

**Comment by mmedenjak** [comment]
@jbartok can you take a look?

**Comment by mmedenjak** [comment]
There might be a common theme here as `com.hazelcast.jet.cdc.postgres.MultiTableCacheIntegrationTest` has timed out in http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4432 as well as `com.hazelcast.jet.kinesis.KinesisIntegrationTest` in http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4431, and we have https://github.com/hazelcast/hazelcast/issues/18453 as well.

**Comment by mmedenjak** [comment]
@jbartok there's a new test failure here, can you take a look?

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4505

**Comment by jbartok** [comment]
Yeah, but there's extremely little info in the logs... I still think it's some docker setup problem, but don't know what to do with it... Will try to involve Josef, when he's back on Monday, maybe he has some ideas.

**Comment by mmedenjak** [comment]
Propose to close this one as well. We changed a lot with how tests are run and the maven configuration. There were no failures in the last few days.
