### ISSUE TITLE
PostgresCdcIntegrationTest

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18453]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4377

**Comment by mmedenjak** [comment]
@jbartok can you take a look?

**Comment by mmedenjak** [comment]
Missing logs in build logs as we've afterwards configured the PR builder to archive the logs. Haven't seen any failures lately and there are other similar tests that have failed since this one, with a similar failure, so I propose to close this one for now.

**Comment by mmedenjak** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4620

**Comment by viliam-durina** [comment]
Again: http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4642/testReport/junit/com.hazelcast.jet.cdc.postgres/PostgresCdcIntegrationTest/com_hazelcast_jet_cdc_postgres_PostgresCdcIntegrationTest/
