### ISSUE TITLE
HazelcastOSGiIntegrationTest failure

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#18458]
_master_ 

https://github.com/hazelcast/hazelcast/pull/18436#issuecomment-813110250
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4404/

Stacktrace:
```
java.lang.ClassNotFoundException: com.hazelcast.osgi.HazelcastOSGiService not found by PAXEXAM-PROBE-ba4e08f4-9b2e-4acc-b25a-21e46afdd291 [16]
```

**Comment by jbartok** [comment]
In latest `master` this test has been renamed to `HazelcastOSGiIT` (https://github.com/hazelcast/hazelcast/pull/18889/files). The failure is not there anymore.
