### ISSUE TITLE
com.hazelcast.jet.core.ExecutionLifecycleTest

### ISSUE THREAD

**Issue by mmedenjak** [hazelcast/hazelcast#18531]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4582/
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4585/
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4588

Looks like in all cases multiple tests failed:
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorNonCooperativeCompleteThrows_then_failJob
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorInitThrows_then_failJob
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorCloseThrows_then_jobSucceeds
com.hazelcast.jet.core.ExecutionLifecycleTest.when_executionCancelled_then_jobCompletedWithCancellationException
com.hazelcast.jet.core.ExecutionLifecycleTest.when_jobCancelled_then_psCloseNotCalledBeforeTaskletsDone
com.hazelcast.jet.core.ExecutionLifecycleTest.when_jobCompletesSuccessfully_then_closeCalled
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorOnSnapshotCompleteThrows_then_failJob
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorCompletesSuccessfully_then_closeCalledImmediately
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorProcessThrows_then_failJob
com.hazelcast.jet.core.ExecutionLifecycleTest.when_oneOfTwoJobsFails_then_theOtherContinues
com.hazelcast.jet.core.ExecutionLifecycleTest.when_pmsCloseThrows_then_jobSucceeds
com.hazelcast.jet.core.ExecutionLifecycleTest.when_psCloseThrows_then_jobSucceeds
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorSaveToSnapshotThrows_then_failJob
com.hazelcast.jet.core.ExecutionLifecycleTest.when_processorCooperativeCompleteThrows_then_failJob

**Comment by sumnerib** [comment]
Failed again on _master_ with MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/152/testReport/junit/com.hazelcast.jet.core/ExecutionLifecycleTest/

Failed for many tests within `ExecutionLifecycleTest`.

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
