### ISSUE TITLE
ClientProperties about ClientStatistics is not used

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#18579]
The following properties are not used anymore since 4.0
```java
  public static final HazelcastProperty STATISTICS_ENABLED = new HazelcastProperty("hazelcast.client.statistics.enabled",
            false);
    /**
     * The period in seconds the statistics run.
     */
    public static final HazelcastProperty STATISTICS_PERIOD_SECONDS = new HazelcastProperty(
            "hazelcast.client.statistics.period.seconds", 3, SECONDS);
```
            
I traced it back to this pr. It seems that we are checking metricsConfig instead.
https://github.com/hazelcast/hazelcast/pull/15963
I could not find mention of this on 4.0 changes
https://docs.hazelcast.org/docs/rn/index.html#4-0
Also these properties are still listed on ClientProperties section on Public API.

It seems we should:
- put `@Deprecated` to the property documents on ClientProperties class
- update the reference manual.
- If user sets statistics, we should make sure it will override metrics config as well.
- And we should just mention that default value is changed. This last part does not feel right to do at this moment, I guess there is nothing we can do.

**Comment by ihsandemir** [comment]
It looks like attribute is unused for Java but fo non-java clients, we did not apply this change, can you add tag `All Clients Should Check` so that issues are created in other repos?

**Comment by sancar** [comment]
@ihsandemir I have I accidentally put it to fixing pr rather than the issue. In order not to create duplicate issues, I will not add the tag here as well.
