### ISSUE TITLE
Client latency spike after reconnection  

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast#18596]
Scenario: 

1) The connection between a member and client is blocked 
2) Client drops the connection after heartbeat timeout 
3) Client establishes a new connection to the member 
4) The member drops the old connection due to heartbeat timeout 
5) After a while the member destroys the old client endpoint 
6) Client operations (mutable, with backup) has increased latencies 

The added latencies are as much as `hazelcast.client.operation.backup.timeout.millis` milliseconds. 

The latencies are not seen when `<backup-ack-to-client-enabled>false</backup-ack-to-client-enabled>`.

**Comment by sertugkaya** [comment]
@sancar can we backport this to other 4.x's?

**Comment by sancar** [comment]
@sertugkaya Yes, we can. As soon as the pr is approved, I will prepare the backports.
