### ISSUE TITLE
Default LRU policy could take `last access time` into account

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#18614]
When triggered; LRU can clean up recently put but not yet touched entries.
While this can be remediated with a custom eviction policy such as below, it is discussed and agreed upon that we can provide this ootb.

Per engineering feedback this can be included in the upcoming platform release as well as backporting to 4.x.
ZD 7222

```
public class FixedLRUPolicyComparator extends LRUEvictionPolicyComparator {
    @Override
    public int compare(EvictableEntryView e1, EvictableEntryView e2) {

        long accessTime1 = e1.getLastAccessTime();
        long accessTime2 = e2.getLastAccessTime();

        if( accessTime1 == 0 && accessTime2 == 0) {
            return 0;
        }

        if(accessTime1 == 0) {
            return 1;
        }

        if(accessTime2 == 0) {
            return -1;
        }

        return super.compare(e1, e2);
    }
}
```

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/18624
