### ISSUE TITLE
Writes to a persistent map store may be lost when coalescing is turned on.

### ISSUE THREAD

**Issue by palisie** [hazelcast/hazelcast#18670]
It is a continuation of issue #15060. 
Correction of this issue used sequence number of DelayedEntry to detect a situation when at the time of removing already persisted DelayedEntries there is already a newer DelayedEntry.
But there is still a small window when sequence number is not yet initialized but the DelayedEntry has already been added to the queue. See `WriteBehindStore::add()` @ version 4.1.1

```
public void add(DelayedEntry<Data, Object> delayedEntry) {
        writeBehindQueue.addLast(delayedEntry, false);

        stagingArea.put(delayedEntry.getKey(), delayedEntry);

        delayedEntry.setSequence(sequence.incrementAndGet());
    }
```
	
We are still observing occasional lost updates and we think this is the reason. Under normal circumstances the issue reproduces very rarely. To increase chances of reproduction it is needed to increase frequency of StoreWorker runs. 

Attached a diagram of the problematic mechanism
![image](https://user-images.githubusercontent.com/66956676/117970318-d0ea1e80-b328-11eb-84ac-d53d7c3afbdf.png)

Attached a test case. Contains a modified StoreWorker to increase chance of reproduction.
[CoalescedSequenceTest.zip](https://github.com/hazelcast/hazelcast/files/6466074/CoalescedSequenceTest.zip)

**Comment by nfrankel** [comment]
Just barging in to to thank you for all the diagnostics data @palisie. Great job!

**Comment by Holmistr** [comment]
Hi @palisie , thanks a lot for the report and a nice description. @ahmetmircik will take a look at this issue as he's the expert on the MapLoader stuff but he's on vacation this week, so please bare with us :)

**Comment by palisie** [comment]
I'm adding a corrected version of the test case. Added a wait time after changing the items in cache to allow writes to finish and eliminate any false positives.
[CoalescedSequenceTest-2.zip](https://github.com/hazelcast/hazelcast/files/6471516/CoalescedSequenceTest-2.zip)
