### ISSUE TITLE
Buggy pick-any aggregation [HZ-1228]

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#18695]
I have this test:
```
    @Test
    public void foo() {
        Pipeline pipeline = Pipeline.create();
        pipeline.readFrom(TestSources.itemStream(1))
                .withNativeTimestamps(5000)
                .window(WindowDefinition.sliding(10_000, 1000))
                .aggregate(AggregateOperations.pickAny())
                .writeTo(Sinks.logger());
        jetInstance.newJob(pipeline).join();
    }
```
and I can see it prints this:
```
[...]
15:19:35,792  INFO || - [WriteLoggerP] hz.sleepy_turing.jet.blocking.thread-1 - [127.0.0.1]:5700 [spring-cluster] [5.0-SNAPSHOT] [0632-dc90-2280-0001/loggerSink#0] WindowResult{start=15:19:20.000, end=15:19:30.000, value='SimpleEvent(timestamp=15:14:37.000, sequence=0)', isEarly=false}
15:19:36,792  INFO || - [WriteLoggerP] hz.sleepy_turing.jet.blocking.thread-1 - [127.0.0.1]:5700 [spring-cluster] [5.0-SNAPSHOT] [0632-dc90-2280-0001/loggerSink#0] WindowResult{start=15:19:21.000, end=15:19:31.000, value='SimpleEvent(timestamp=15:14:37.000, sequence=0)', isEarly=false}
[...]
```
This makes no sense. It says the window bounded by `(start=15:19:21.000, end=15:19:31.000)` contains an item with a timestamp set to `15:14:37.000`. Clearly this item does not belong to the window as specified by the bounds. 

The problem is in the impl of [pick any](https://github.com/hazelcast/hazelcast/blob/7e5bbad3eb23600ff807c8d1efd22c466f23b16c/hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java#L42) accumulator: The accumulator had observed an item. The item is later deducted. but the accumulator is still yielding the deducted item. as long as there is at least one non-deducted item. any item.

The fix should be backported into Jet 4.5.z

**Comment by mmedenjak** [comment]
Moving into 5.1 based on the current scope of 5.0. Feel free to reach out to me if you consider this critical.

**Comment by Holmistr** [comment]
Moving to Backlog as of now. We'll reconsider it during planning for the next version.
