### ISSUE TITLE
Select_TcpIpConnectionManager_ConnectMemberTest.connect

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#18694]
The `Select_TcpIpConnectionManager_ConnectMemberTest.connect` failed on PR builder on `master` branch.

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/5077

Stacktrace:
```
java.lang.AssertionError: expected:<1> but was:<2>
```

**Comment by vbekiaris** [comment]
Not sure if this is the cause of failure, however I observe unrelated client instances `hz.client_77` and `hz.client_78` attempting to connect, even though the failed test does not create any client instances. The same client instance names also appear in other tests which do not create any client instances eg `com.hazelcast.nio.IOUtilTest`.
