### ISSUE TITLE
Adopt IMapTraverser on MapScanExecIterator code

### ISSUE THREAD

**Issue by Fly-Style** [hazelcast/hazelcast#18693]

**Comment by mmedenjak** [comment]
@Fly-Style is this supposed to go into 5.0, or is this an enhancement for the future (i.e. Backlog)?

**Comment by Fly-Style** [comment]
@mmedenjak if we'd remove IMDG engine in 5.0, it is supposed to go into 5.0, otherwise in Backlog.
