### ISSUE TITLE
Near-cache inconsistency between XML and YAML

### ISSUE THREAD

**Issue by AyberkSorgun** [hazelcast/hazelcast#18700]
On the server-side, using 4.2,

In Java, `new NearCacheConfig()` results in a near-cache with name 'default' Same for XML, `<xs:attribute name="name" type="xs:string" default="default"/>`

In YAML, if the name section is omitted it defaults to null.

**Comment by Holmistr** [comment]
Moving it to 5.2 as it's not critical.

**Comment by frant-hartm** [comment]
This has already been fixed in https://github.com/hazelcast/hazelcast/pull/19245
