### ISSUE TITLE
Enhancement: auto-cancel job with observable as only sink type

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#18705]
(On Jet 4.5) a job which has
```
        .writeTo(Sinks.observable(observable))
```

is not cancelled if the job is submitted from a client which then disconnects. So the job no longer serves any useful purpose.

If all sinks are observables, the job should be cancelled.

If some sinks are observable, a warning would be useful.

**Comment by gurbuzali** [comment]
I don't think it is a good idea to cancel a job with an observable sink. Observables are not bound to the client, in fact multiple clients may already listening (by adding observers to the observable).

**Comment by mmedenjak** [comment]
Closing as "won't fix" for the time being. We may reassess in the light of new information.
