### ISSUE TITLE
down time free migration for major version upgrades

### ISSUE THREAD

**Issue by cforce** [hazelcast/hazelcast#18713]
It looks like they is no support path (even enterprise grade)  to migrate  from one major version to another rolling without downtime, is there?
This feature is crucial for  HA system setups.

**Comment by mmedenjak** [comment]
@cforce we support migrating from 3.x to 4.0/4.1/4.2 through WAN replication - https://docs.hazelcast.com/imdg/4.2/migration-guides.html#migrating-from-3-12-to-4-0-4-1

**Comment by mmedenjak** [comment]
Right now we're planning on releasing 5.0 and moving to it will be even easier, using rolling upgrades - https://docs.hazelcast.com/imdg/4.2/installation/rolling-upgrades.html.

Closing as this question seems answered, feel free to reopen, comment or create a new issue.

**Comment by mmedenjak** [comment]
@cforce one more info - we're currently considering about releasing a simpler and open-source tool to move some data between major versions. It would have some restrictions which would still make the tool I linked above a better choice in some cases, but I don't want to go into it too much.

I was wondering if you can tell me more about your use case - what structures you would like to migrate, how much data, would you like to keep both major versions running for a longer time (hours/days) before shutting down the older members, what are your other requirements on the migration process...

Such input may prove valuable when we consider releasing this tool.

**Comment by cforce** [comment]
I would prefer a rolling upgrade from at  (latest major-1).(latest minor) to (latest major).(any)  on the same cluster instead of a replication and blue green style major version upgrade. What you linked above  (https://docs.hazelcast.com/imdg/4.2/installation/rolling-upgrades.html) for rolling upgrade does not support between major version, does it?

**Comment by mmedenjak** [comment]
You're right. Rolling upgrades were designed to support changes across minor versions, not major ones. Exceptionally, we're going to enable using RU to make the transition from 4.2 to 5.0.
