### ISSUE TITLE
Benchmark and remove the unnecessary thread hop after job completion

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#18730]
In #18728 we offloaded the completion action to another thread to avoid calling `P.close()` and `PS.close()` methods on a cooperative thread. We need to benchmark the real cost of this and potentially address it - using the `P.closeIsCooperative()` and `PS.closeIsCooperative` methods.

**Comment by Holmistr** [comment]
Moving it to backlog as it's an internal work item.
