### ISSUE TITLE
Checkstyle for master (5.0-SNAPSHOT) fails on Solaris

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18767]
Checkstyle fail for `master` branch on Solaris. It's running by following command with Oracle JDK 8 and Maven 3.6.3:
```
clean install -U -B -DfailIfNoTests=false -DskipTests -Dmaven.test.failure.ignore=true -DvmHeapSettings="-Xms6g -Xmx6g -XX:MaxPermSize=2048m" -DextraVmArgs="-verbose:gc -Xloggc:$WORKSPACE/test_gc.log -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"
```

Output:
```
15:08:02 [INFO] Reactor Summary for Hazelcast Root 5.0-SNAPSHOT:
15:08:02 [INFO] 
15:08:02 [INFO] Hazelcast Root ..................................... SUCCESS [  4.286 s]
15:08:02 [INFO] hazelcast .......................................... SUCCESS [05:48 min]
15:08:02 [INFO] hazelcast-spring ................................... SUCCESS [  8.525 s]
15:08:02 [INFO] hazelcast-spring-tests ............................. SUCCESS [  2.378 s]
15:08:02 [INFO] hazelcast-build-utils .............................. SUCCESS [  6.097 s]
15:08:02 [INFO] hazelcast-jet-extensions ........................... SUCCESS [  0.414 s]
15:08:02 [INFO] hazelcast-jet-kafka ................................ FAILURE [  0.244 s]
15:08:02 [INFO] hazelcast-jet-avro ................................. SKIPPED
15:08:02 [INFO] hazelcast-jet-csv .................................. SKIPPED
15:08:02 [INFO] hazelcast-jet-hadoop-core .......................... SKIPPED
15:08:02 [INFO] hazelcast-sql ...................................... SKIPPED
15:08:02 [INFO] hazelcast-all ...................................... SKIPPED
15:08:02 [INFO] hazelcast-jet-cdc-debezium ......................... SKIPPED
15:08:02 [INFO] hazelcast-jet-cdc-mysql ............................ SKIPPED
15:08:02 [INFO] hazelcast-jet-cdc-postgres ......................... SKIPPED
15:08:02 [INFO] hazelcast-jet-elasticsearch-5 ...................... SKIPPED
15:08:02 [INFO] hazelcast-jet-elasticsearch-6 ...................... SKIPPED
15:08:02 [INFO] hazelcast-jet-elasticsearch-7 ...................... SKIPPED
15:08:02 [INFO] hazelcast-jet-grpc ................................. SKIPPED
15:08:02 [INFO] hazelcast-jet-hadoop-dist .......................... SKIPPED
15:08:02 [INFO] hazelcast-jet-files-azure .......................... SKIPPED
15:08:02 [INFO] hazelcast-jet-files-gcs ............................ SKIPPED
15:08:02 [INFO] hazelcast-jet-files-s3 ............................. SKIPPED
15:08:02 [INFO] hazelcast-jet-hadoop ............................... SKIPPED
15:08:02 [INFO] hazelcast-jet-hadoop-all ........................... SKIPPED
15:08:02 [INFO] hazelcast-jet-kinesis .............................. SKIPPED
15:08:02 [INFO] hazelcast-jet-protobuf ............................. SKIPPED
15:08:02 [INFO] hazelcast-jet-python ............................... SKIPPED
15:08:02 [INFO] hazelcast-jet-s3 ................................... SKIPPED
15:08:02 [INFO] hazelcast-distribution ............................. SKIPPED
15:08:02 [INFO] ------------------------------------------------------------------------
15:08:02 [INFO] BUILD FAILURE
15:08:02 [INFO] ------------------------------------------------------------------------
15:08:02 [INFO] Total time:  06:14 min
15:08:02 [INFO] Finished at: 2021-05-24T18:17:10+03:00
15:08:02 [INFO] ------------------------------------------------------------------------
15:08:02 Waiting for Jenkins to finish collecting data
15:08:02 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast-jet-kafka: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Unable to find suppressions file at location: ${maven.multiModuleProjectDirectory}/checkstyle/suppressions_jet.xml: Could not find resource '${maven.multiModuleProjectDirectory}/checkstyle/suppressions_jet.xml'. -> [Help 1]
15:08:02 [ERROR] 
15:08:02 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
15:08:02 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:08:02 [ERROR] 
15:08:02 [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:08:02 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
15:08:02 [ERROR] 
15:08:02 [ERROR] After correcting the problems, you can resume the build with the command
15:08:02 [ERROR]   mvn <goals> -rf :hazelcast-jet-kafka
```

**Comment by fbarotov** [comment]
It seems, the basic problem is, modules in the project need path information to checkstyle folder located at the root; and we have variable length nested modules. Currently, the project relies on `maven.multiModuleProjectDirectory`, which in default case should not be relied upon since it is an [internal implementation detail](https://issues.apache.org/jira/browse/MNG-6589), thus may not be compatible across platforms. This problem is in fact addressed in the ` mnvw` script.

Thus, there are two ways that I tried which passed checkstyle error

    clean install -U -B -DfailIfNoTests=false -DskipTests -Dmaven.multiModuleProjectDirectory=${workspace} -Dmaven.test.failure.ignore=true -DvmHeapSettings="-Xms6g -Xmx6g -XX:MaxPermSize=2048m" -DextraVmArgs="-verbose:gc -Xloggc:$WORKSPACE/test_gc.log -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"

or 

    ./mvnw clean install -U -B -DfailIfNoTests=false -DskipTests -Dmaven.test.failure.ignore=true -DvmHeapSettings="-Xms6g -Xmx6g -XX:MaxPermSize=2048m" -DextraVmArgs="-verbose:gc -Xloggc:$WORKSPACE/test_gc.log -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime"


After this we come to another layer of dependency issue 🙁 same as the one executed without checkstyle here (http://jenkins.hazelcast.com/job/Hazelcast-master-Solaris-OracleJDK8-without-checkstyle/lastBuild/console)

**Comment by fbarotov** [comment]
Regarding the consecutive error, 

    [ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:test-compile (java) on project    
    hazelcast-jet-grpc: Unable to resolve artifact: Missing:
    [ERROR] ----------
    [ERROR] 1) com.google.protobuf:protoc:exe:sunos-sparc_64:3.13.0
    [ERROR] 
    [ERROR] Try downloading the file manually from the project website.

 Unfortunately there is no protobuf support for solaris https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3

I tried `mvn clean install` by excluding the above module

`mvn clean install -X -U -B -pl !'com.hazelcast.jet:hazelcast-jet-protobuf' -DfailIfNoTests=false -Dmaven.multiModuleProjectDirectory=${workspace} -DskipTests -Dmaven.test.failure.ignore=true -DvmHeapSettings="-Xms6g -Xmx6g -XX:MaxPermSize=2048m" -DextraVmArgs="-verbose:gc -Xloggc:$WORKSPACE/test_gc.log -XX:+PrintGCTimeStamps -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime""`

Unfortunately (x2 ☹️), Jenkins maven plugin does not support reactor module exclusion (i.e., not executing the goal on some modules) https://issues.jenkins.io/browse/JENKINS-26472

**Comment by AyberkSorgun** [comment]
@Serdaro 
We should add a section in Hazelcast 5.0 that the **hazelcast-jet-kafka** extension is not supported on solaris

**Comment by Serdaro** [comment]
Added the related note: https://github.com/hazelcast/hz-docs/commit/fcf68a1b7408965c0c5fbcc4904670b894b37dcc
