### ISSUE TITLE
com.hazelcast.cp.internal.MetadataRaftGroupTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18768]
_master_ (commit 737e470cd5a7d4b8e2866b76f681596058ddcd73)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16/28/testReport/com.hazelcast.cp.internal/MetadataRaftGroupTest/

Almost all tests from `com.hazelcast.cp.internal.MetadataRaftGroupTest` failed with various exceptions. Stacktraces and standard output can be found here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-ZuluJDK16/28/Hazelcast-master-ZuluJDK16-28.tar

**Comment by vbekiaris** [comment]
Machine load related failure (see https://github.com/hazelcast/hazelcast/issues/18770#issuecomment-847854628). Jenkins job configuration was updated with `8` CPU limit and seems to behave better. Closing for now.
