### ISSUE TITLE
Decide the future of InstanceConfig

### ISSUE THREAD

**Issue by ufukyilmaz** [hazelcast/hazelcast#18774]
After we merged `Hazelcast` and `Jet`, we also deprecated `JetInstance` and because of that the naming of this InstanceConfig got a little meaningless.  Consider the renaming [InstanceConfig](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/jet/config/InstanceConfig.java) or relocating configurations in this config object.

**Comment by Holmistr** [comment]
@ufukyilmaz Is this object part of a public facing API? Why I'm asking - if it's internal, we can move it out of 5.0.

**Comment by Holmistr** [comment]
Slack conversation happening: https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1626252504287400
