### ISSUE TITLE
com.hazelcast.cp.internal.datastructures.atomicref.AtomicRefBasicTest

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18770]
_master_ (commit 737e470cd5a7d4b8e2866b76f681596058ddcd73)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16/28/testReport/com.hazelcast.cp.internal.datastructures.atomicref/AtomicRefBasicTest/

13 tests from `com.hazelcast.cp.internal.datastructures.atomicref.AtomicRefBasicTest` failed with various exceptions. Stacktraces and standard output can be found here - https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=us-east-1&prefix=Hazelcast-master-ZuluJDK16/28/Hazelcast-master-ZuluJDK16-28.tar

**Comment by vbekiaris** [comment]
This and other test failures ( #18769 and #18768 ) failed in the same build timing out while attempting to form their test clusters.
The test started executing ~21:10:28. First two members formed a cluster at 21:10:30. The third member required to complete the test cluster initiated startup at 21:10:31 but didn't manage to join until test timed out:

```
21:10:31,185  INFO |test_setAsync| - [MetricsConfigHelper] Thread-2312 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
21:10:32,426  INFO |test_setAsync| - [CPSubsystem] Thread-2312 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] CP Subsystem is enabled with 3 members.
21:10:42,288  INFO |test_setAsync| - [JetService] Thread-2312 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 40

// next log from 5703 appears ~2 minutes later
21:12:49,783  WARN |test_setAsync| - [InvocationMonitor] hz.vigilant_banzai.InvocationMonitorThread - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] MonitorInvocationsTask delayed 16495 ms

// around that time HealthMonitor reports
... load.process=100.00%, load.system=100.00%, load.systemAverage=612.24, thread.count=9955, thread.peakCount=10896 ...

// join times out
21:13:33,626  WARN |test_setAsync| - [MockJoiner] Thread-2312 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Resetting master address because join address timeout
```

**Comment by vbekiaris** [comment]
In job config history I see that an 8 CPU configuration is now gone http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16/jobConfigHistory/showDiffFiles?timestamp1=2021-04-06_07-07-11&timestamp2=2021-05-21_10-33-54 . This seems to result in each test cluster creating threads for all of the machine's CPUs -> machine is overloaded with parallel tests overprovisioning threads -> failures. Can we restore the 8-CPU configuration @olukas ?

**Comment by olukas** [comment]
@vbekiaris sure, I can do that for all jobs. I discussed it previously with @kwart who suggested to keep it empty or set to value `4` or `8`. What should be the best value for that? I'm rather asking before configure it in all jobs.

**Comment by vbekiaris** [comment]
My guess is that leaving `<CPU>` element empty resulted in exposing all of the host's CPUs to the docker container that runs the build -> `Setting number of cooperative threads and default parallelism to 40` -> machine overload. I think `4` or `8` is safer, but that's just my guess. @kwart wdyt?

**Comment by vbekiaris** [comment]
Jenkins job configuration was updated with `8` CPU limit and seems to behave better. Closing for now.
