### ISSUE TITLE
A misleading comment in hazelcast.yaml

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#18789]
This is what the hazelcast.yaml in the distribution currently has:
```
      # The default way to discover nodes: using the IP multicast. This is the
      # simplest technique, but in a cloud setting the network usually doesn't
      # allow multicast.
      multicast:
        enabled: true
```
That's misleading. Since then default is no longer multicast. It's the `auto-detection`. Auto-detection happens to use `multicast` if it cannot detect any better strategy (such as k8s).

**Comment by mmedenjak** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/19037.
