### ISSUE TITLE
Multicast in 5.x uses a different default port than IMDG 4.x

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#18792]
The [yaml config](https://github.com/hazelcast/hazelcast/blob/96d9c0de6500308627f65e00d630c48180ed8d3d/distribution/src/root/config/hazelcast.yaml#L32) in Hazelcast 5.x uses port 54328 for multicast disco. However IMDG 4.x uses a port 54327. Hence Hazelcast 4.x and 5.x do not form a cluster by default.

**Comment by mmedenjak** [comment]
This file was copied from jet repo. With https://github.com/hazelcast/hazelcast/pull/19037, it will be removed and we will use `hazelcast-default.yaml` and `hazelcast-default.xml` from IMDG instead.
