### ISSUE TITLE
No way to get cluster members within DiscoveryStrategy.getPartitionGroupStrategy()

### ISSUE THREAD

**Issue by lprimak** [hazelcast/hazelcast#18795]
**Describe the bug**
In order to do anything useful in ` DiscoveryStrategy.getPartitionGroupStrategy()`, the method needs access
to current cluster members. Currently, there is no way to access the cluster members.
Partition Group API is useless because of this, and this is why this is a bug and not a feature.
API bug.

**Comment by Holmistr** [comment]
Hi @lprimak , thanks for the report. We'll take a look at the issue and its PR. 

Regarding the "Defect" vs. "Enhancement" labels, we just have some internal "guidelines" how we label things, so we changed that.. Don't try to reason about it in more depth :)

**Comment by lprimak** [comment]
> And please don't call our APIs useless, it hurts our feelings and we're people too! 
@Holmistr Sorry about that. Nothing personal intended.
