### ISSUE TITLE
Hazelcast Management Center 4.2021.03 cannot see create/update time in map browser

### ISSUE THREAD

**Issue by wubumihuo** [hazelcast/hazelcast#18805]
**Describe the bug**
Hazelcast Management Center:  4.2021.03
Hazelcast IMDG: 4.2   
WHEN I use management map browser, cannot see create/update time in specific entry

**Comment by mmedenjak** [comment]
@emre-aydin can someone take a look?

**Comment by wubumihuo** [comment]
> @emre-aydin can someone take a look?

tks all. I hava resolved the problem,because th new version 4.2 add the new config "per-entry-statistics-enable" which default is false.  I changed the config to true，and it worked
