### ISSUE TITLE
Jet MySQL CDC tests fails on JDK 16

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18800]
_master_ (commit e19ab8c4bea1cb2a78d91d7da9fb3daf9f637404)

Failed on Zulu JDK 16: 
- http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/2/testReport/com.hazelcast.jet.cdc/
- http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/2/testReport/com.hazelcast.jet.cdc.mysql/

This is probably the same issue as https://github.com/hazelcast/hazelcast-jet/issues/2623 but for JDK 16.

**Comment by jbartok** [comment]
Yes it is. Very strange that they aren't fixing it in the JDK...
Debezium did do a change which fixes the problem in later versions, so upgrading to later versions is a solution, but we would need a lot of testing to make sure nothing else gets broken.

**Comment by mmedenjak** [comment]
@jbartok how big of an effort is it to test with this upgrade? I assume they don't have some kind of "patch" upgrade which is low-risk?

**Comment by jbartok** [comment]
Big. But that's not even the issue. It probably won't even work or there is going to be behavioural change. Now we are on Debezium version `1.2`. We have tested `1.3` and one of the connector wasn't working at all. The latest they have is `1.5` and maybe they fixed a lot of bugs in that (besides introducing new ones), but the point is that we should start poking this bear only when we are prepared to put some serious time into it.
