### ISSUE TITLE
com.hazelcast.jet.server.JetCommandLineTest on Windows

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18830]
_master_ (commit e12baa0f5d0f12b22d60587e6b48ab98b4eb68af)

Failed on Windows with Oracle JDK 8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8-without-checkstyle/3/testReport/com.hazelcast.jet.server/JetCommandLineTest/

Tests from the issue https://github.com/hazelcast/hazelcast/issues/18725 are still failing on Windows. See that issue for stacktraces and standard outputs.

**Comment by mmedenjak** [comment]
@ufukyilmaz can you take a look at this one?
