### ISSUE TITLE
Deserialization of object at server in hazelcast management center dashboard 

### ISSUE THREAD

**Issue by KUCHUSISI** [hazelcast/hazelcast#18859]
![Screenshot from 2021-06-09 10-49-39](https://user-images.githubusercontent.com/77325629/121298036-db400e00-c910-11eb-9f8e-04480d81abd9.png)

![Screenshot from 2021-06-09 10-49-39](https://user-images.githubusercontent.com/77325629/121298104-f0b53800-c910-11eb-9a5f-d248e1698cbe.png)

**Comment by mmedenjak** [comment]
@emre-aydin can someone take a look?

**Comment by emre-aydin** [comment]
@KUCHUSISI you need to configure the client that Management Center uses so that it can deserialize the entry you stored on the map. Please take a look in the reference manual to see how: https://docs.hazelcast.com/management-center/latest/monitor-imdg/monitor-dds.html#map-browser
