### ISSUE TITLE
Bump up the Apache Calcite Library to fix a vulnerability originates from Hazelcast SQL module

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#18905]
Jaromir has sent a [pr](https://github.com/apache/calcite/pull/2399) to fix a possible vulnerability which was included in the calcite 1.27.0 release. 
Calcite is a transitive dependency of Hazelcast SQL module.

**Comment by viliam-durina** [comment]
we're already using 1.28
