### ISSUE TITLE
Consolidate scripts from IMDG and Jet in /bin directory

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#18989]
**Analysis of the current state**

In the IMDG distribution, we had following scripts:
* healthcheck.sh
* start.bat
* start.sh
* stop-all.bat
* stop-all.sh
* cluster.sh
* cp-subsystem.sh

In the Jet distribution, we had following scripts:
* common.sh
* jet
* jet-cluster-admin
* jet-cluster-cp-admin
* jet-start
* jet-start.bat
* jet-stop
* jet-stop.bat
* jet.bat

In current `master` (commit de1557a86c0998a1aed4a918e053a3671823c536), we adopted the Jet scripts and renamed a few of them
* common.sh
* hazelcast (previously jet)
* hazelcast-start (previously jet-start)
* hazelcast-stop (previously jet-stop)
* jet-cluster-admin 
* jet-cluster-cp-admin
* jet-start.bat
* jet-stop.bat
* jet.bat

**To be done**
We need to consolidate those scripts. Some needs renaming and we need to make sure that we don't duplicate the functionality. E.g. "jet-cluster-admin is same as cluster.sh (with some improvements)".

Therefore, items to be done:
- [x] Rename the `jet-start.bat`, `jet-stop.bat` and `jet.bat` to `hazelcast-start.bat`, `hazelcast-stop.bat` and `hazelcast.bat`
- [x] Rename the `jet-cluster-admin` and `jet-cluster-cp-admin`: https://github.com/hazelcast/hazelcast/issues/18816
- [x] Add `healthcheck.sh` script

**Comment by mmedenjak** [comment]
As discussed on slack (https://hazelcast.slack.com/archives/C01JU7ZJYGP/p1624957054074900), this is the proposed final state and changes:
```
common.sh
hz-cli.sh (previously jet)
hz-cli.bat (previously jet.bat, double-check with IMDG start.bat)
hz-start.sh (previously jet-start, double-check if there's anything in IMDG start.sh missing here)
hz-start.bat (renamed from jet-start.bat)
hz-stop.sh (previously jet-stop, double-check if there's anything in IMDG stop-all.sh missing here)
hz-stop.bat (double-check with IMDG stop-all.bat)
hz-cluster-admin.sh (renamed from jet-cluster-admin, double-check if there's anything in IMDG cluster.sh missing)
hz-cluster-cp-admin.sh (renamed from jet-cluster-cp-admin, double-check if there's anything in IMDG cp-subsystem.sh missing)
hz-healthcheck.sh (currently missing, was healthcheck.sh in IMDG) 
```
