### ISSUE TITLE
Libraries from /bin/user-lib are not deployed to cluster for 5.0-SNAPSHOT

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18982]
Directory `/bin/user-lib` could be used for deploying libraries for members (https://docs.hazelcast.com/imdg/4.2/clusters/deploying-code-from-clients.html#configuring-client-user-code-deployment). However it currently cannot be used with current `master` because it's missing in `/bin/hazelcast-start` script.

It is implemented in IMDG 4.2.z in this way: https://github.com/hazelcast/hazelcast/blob/v4.2/hazelcast/src/main/resources/start.sh#L46

**Comment by mmedenjak** [comment]
Since https://github.com/hazelcast/hazelcast/pull/19037, the `bin/user-lib` directory is included in the classpath for both `hz-start` and `hz-start.bat`. The only remaining question is whether this dir should be added by maven assembly or by release pipeline.

**Comment by olukas** [comment]
@mmedenjak `bin/user-lib` directory is currently added by release pipeline. I think it would be better to add it as part of assembly plugin but I suggest to not do it before beta release.

**Comment by mmedenjak** [comment]
Yes, I'm just trying to add that to https://github.com/hazelcast/hazelcast/pull/19037

**Comment by mmedenjak** [comment]
> I suggest to not do it before beta release.

Sorry, read this now, aborting :)

**Comment by mmedenjak** [comment]
For future reference, I tried it and it seems this needs to be added to both `assembly-descriptor.xml` and `assembly-descriptor-slim.xml`:
```xml
    <fileSets>
        ...

        <fileSet> <!-- Create empty directory -->
            <outputDirectory>bin/user-lib</outputDirectory>
            <excludes>
                <exclude>**/*</exclude>
            </excludes>
        </fileSet>

        ...
    </fileSets>
```

**Comment by ramizdundar** [comment]
> Since #19037, the `bin/user-lib` directory is included in the classpath for both `hz-start` and `hz-start.bat`. The only remaining question is whether this dir should be added by maven assembly or by release pipeline.

This is fixed in https://github.com/hazelcast/hazelcast/pull/18999 just to point it out if someone wants lo take a look.
