### ISSUE TITLE
Race condition on cluster member reconnect.

### ISSUE THREAD

**Issue by jbartok** [hazelcast/hazelcast#18980]
At some point we merged in PR https://github.com/hazelcast/hazelcast/pull/18267. Its purpose was to speed up the merge process. The pull request didn't introduce any bugs on its own (at least not that I'm aware of), but it makes an old bug, which might been there since a long time, much likely to manifest. 

One example of the type of failures that happen is this: https://github.com/hazelcast/hazelcast/issues/18751

The merge in of the original pull request has been reverted, mostly because at this moment we don't have the resources to properly fix the underlying bug it reveals (the fix would probably require some major-ish changes of the join process).

The author has submitted a new version of the PR (https://github.com/hazelcast/hazelcast/pull/18932), which is not merged in, but at some point we should attempt to do so and fix the real problem.

**Comment by vbekiaris** [comment]
Closing as the new PR #18932 was merged and `TcpIpJoinTest` hasn't failed (see also https://github.com/hazelcast/hazelcast/pull/18932/files#r722164878).
