### ISSUE TITLE
Leftovers in maven distribution layout

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#18998]
There are some leftovers which need to be removed from our maven distribution build. We're currently adding:
- `README.md` which is just for Jet (this file https://github.com/hazelcast/hazelcast/blob/master/distribution/src/root/README.md) - it should be removed.
- `release_notes.txt` which currently includes Hazelcast Jet Release Notes from https://github.com/hazelcast/hazelcast/blob/master/distribution/src/root/release_notes.txt - it should be removed. `release_notes.txt` file is added to distribution by release pipeline from release notes which are prepared on release branch.
- our build should include empty `bin/user-lib` directory (https://docs.hazelcast.com/imdg/4.2/clusters/deploying-code-from-clients.html#adding-user-library-to-classpath) - it's currently added by release pipeline. We should consider whether it should not be rather added as part of maven distribution build.

See https://hazelcast.atlassian.net/browse/HZ-34 for more details.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/18982

**Comment by mmedenjak** [comment]
Closing as first two items were fixed by the merged PR, and third one can be addressed as part of the related issue.
