### ISSUE TITLE
Jet 4.5 to 5.0-SNAPSHOT migration issue with DiscoveryStrategyFactory reduction

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19027]
If I use Jet 4.5 and `maven-assembly-plugin` to build an executable Jar, this is in it.

```
% grep ^com META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory 
com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategyFactory
com.hazelcast.aws.AwsDiscoveryStrategyFactory
com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategyFactory
com.hazelcast.gcp.GcpDiscoveryStrategyFactory
com.hazelcast.azure.AzureDiscoveryStrategyFactory
```

If I use 5.0-SNAPSHOT (build "20210707 - 104ab2d") it's

```
% grep ^com META-INF/services/com.hazelcast.spi.discovery.DiscoveryStrategyFactory 
com.hazelcast.spi.discovery.multicast.MulticastDiscoveryStrategyFactory
```

This will make migration from Jet to 5.0 problematic for users using, for example, Kubernetes discovery plugin.

**Comment by neilstevenson** [comment]
I don't think this is difficult to work around, by tweaking the Maven setup (putt the hazelcast-kubernetes dependency first), it's more the confusion to figure out what is wrong.

**Comment by Holmistr** [comment]
@neilstevenson We're about to merge the discovery plugins into the 5.0. It should be fixed in Beta. Would you mind retesting later this week?

**Comment by mmedenjak** [comment]
Related PR - https://github.com/hazelcast/hazelcast/pull/19033

**Comment by neilstevenson** [comment]
Works now. Thanks.
