### ISSUE TITLE
SQL error messages sent as null

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19052]
**Describe the bug**
This is the error message a client received as a response to an SQL run: `Error: null`. It was not like before.

**Expected behavior**
I suspect there is a bug. The error messages should be sent correctly.

**To Reproduce**

One way to reproduce:

Run latest 5.0 snapshot, run a client and a server with no extra config. Run the query: `SELECT * FROM TABLE(generate_series(1,3))`

Or simply try to get an SQL error via syntax error etc.

**Comment by viliam-durina** [comment]
@gurbuzali Wasn't this fixed by #19065?

**Comment by gurbuzali** [comment]
no, in the QueryParser the `jetSqlBackend` is null and you get a NPE even before sending the job
