### ISSUE TITLE
Once I add the TO_TIMESTAMP_TZ time function to the SQL query, the LIMIT doesn't work any more.

### ISSUE THREAD

**Issue by vladoschreiner** [hazelcast/hazelcast#19096]
**Describe the bug**

Once I add the TO_TIMESTAMP_TZ time function to the SQL query, the LIMIT doesn't work any more.

This query returns 10 rows, as per the limit clause:
`select trades.symbol, trades.price, trades."timestamp", symbols.this from trades JOIN symbols ON symbols.__key = trades.symbol WHERE symbol = 'ELECU' AND price > 2500 ORDER BY "timestamp" DESC LIMIT 10;`

This query returns all rows, ignoring the limit:
`select trades.symbol, trades.price, TO_TIMESTAMP_TZ(trades."timestamp"), symbols.this from trades JOIN symbols ON symbols.__key = trades.symbol WHERE symbol = 'ELECU' AND price > 2500 ORDER BY "timestamp" DESC LIMIT 10;`

**Expected behavior**

LIMIT should kick in and reduce the output to 10 rows in both cases.

**To Reproduce**

1. Get the the [realtime-trade-monitor](https://github.com/hazelcast/hazelcast-demos/tree/master/realtime-trade-monitor) 
2. Upgrade the Hazelcast dependency in the demo from 5.0-SNAPSHOT to 5.0-BETA-1
3. Add the hazelcast-sql dependency to the jet-server module
4. Follow the instructions to load symbols and ingest trades. 
5. Start an SQL console (`hz-cli sql`).
6. Try both queries

**Additional context**

- I've used the hz-cli from 5.0-BETA-1 ZIP distribution

**Comment by ivanthescientist** [comment]
Don't think this is strictly related to the `TO_TIMESTAMP_TZ` function, I think modifying sort column in projections in any way produces this result. E.g. 
```select trades.symbol, trades.price, abs(trades."timestamp"), symbols.this from trades JOIN symbols ON symbols.__key = trades.symbol WHERE symbol = 'ELECU' AND price > 2500 ORDER BY "timestamp" DESC LIMIT 10;

**Comment by viliam-durina** [comment]
I guess it will be affected by #18968
