### ISSUE TITLE
5.0-BETA-1 mismatching map config [HZ-636]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19137]
Using 5.0-BETA-1, if I start a three node member and create one map, `users` by 
```
this.hazelcastInstance.getMap("users");
```

Running this code on all three
```
        log.info("1 MAP CONFIGS {}",
        this.hazelcastInstance.getConfig().getMapConfigs().size());
        log.info("2 MAP CONFIGS {}",
        this.hazelcastInstance.getConfig().getMapConfigs().keySet());
```

gives differing output.
On the oldest member

```
16:56:36.487 [main] INFO  neil.demo.ApplicationRunner - 1 MAP CONFIGS 1
16:56:36.487 [main] INFO  neil.demo.ApplicationRunner - 2 MAP CONFIGS [default]
```

On other members 
```
16:56:57.078 [main] INFO  neil.demo.ApplicationRunner - 1 MAP CONFIGS 2
16:56:57.078 [main] INFO  neil.demo.ApplicationRunner - 2 MAP CONFIGS [default, user]
```

This in turn results in a mismatching config report on the Management Center

It's not necessarily unique to maps, I think I also saw for IQueue

**Comment by neilstevenson** [comment]
All nodes are launched with the same config, no map configuration.
It is always the master node that reports this configuration (only _default_)
Other nodes report a config object for the created map.

**Comment by neilstevenson** [comment]
Reproducer
```
    public static void main(String[] args) throws Exception {
        Config config1 = new Config();
        Config config2 = new Config();
        HazelcastInstance first = Hazelcast.newHazelcastInstance(config1);
        first.getMap("hello");
        HazelcastInstance second = Hazelcast.newHazelcastInstance(config2);
        TimeUnit.SECONDS.sleep(5L);
        System.out.println("1st node -  " + first.getConfig().getMapConfigs().keySet());
        System.out.println("2nd node -  " + second.getConfig().getMapConfigs().keySet());
        TimeUnit.MINUTES.sleep(1L);
        Hazelcast.shutdownAll();
    }```

Note the behaviour occur when the two nodes are initialised from different config objects

**Comment by Holmistr** [comment]
@neilstevenson Could you please verify whether this is a regression in 5.0 or it was present in 4.x as well?

**Comment by neilstevenson** [comment]
@Holmistr It occurs also with 4.2.1, but was only revealed by 5.0 Management Center

**Comment by Holmistr** [comment]
I see. In that case, I'm moving the milestone to 5.0.1 as it's not a regression and we want to lmit the scope of 5.0 as much as possible.

**Comment by rksharma1972** [comment]
We are facing the issue in Hazelcast 4.2.2 when I add a lite member and try to get all existing maps in cluster. All I get is default map. What is target fix version for 4.x.x?
