### ISSUE TITLE
Don't map OBJECT fields in implicitly-resolved IMaps

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19154]
In the future we plan to add support for nested fields. This would present an issue for b-w compatibility because we would start resolving to the nested type instead of OBJECT, and user applications could be affected.

One can continue to use OBJECT fields with explicit mappings, but since it's explicit, it won't change even if we introduce nested types.

**Comment by Holmistr** [comment]
**Relevant discussions**
* https://hazelcast.slack.com/archives/CJZ745RRT/p1628242703046800
* https://hazelcast.slack.com/archives/CJZ745RRT/p1626688087068900

**Comment by viliam-durina** [comment]
After discussion we decided to not change this. Reasons:
- Seeing object fields is good for interoperability with Java objects already in maps
- We'll state in the documentation that the user should use explicit mapping using CREATE MAPPING with an explicit column list. Implicit mappings and explicit mappings without the column list are meant for ad-hoc queries.

**Comment by Holmistr** [comment]
CC @JakeSCahill :point_up:
