### ISSUE TITLE
SqlClientService.execute might throw RuntimeException and this is not documented

### ISSUE THREAD

**Issue by srknzl** [hazelcast/hazelcast#19207]
**Describe the bug**
(Close this issue if RuntimeExceptions are generally not documented in Java)

SqlClientService.execute might throw RuntimeException and this is not documented

If there are more than 2 distinct member versions, memberOfLargerSameVersionGroup will throw RuntimeException. And since `getQueryConnection` is not in the try block, it will throw a RuntimeException instead of HazelcastSqlException.

**Expected behavior**

Either document RuntimeException might be thrown, or put getQueryConnection() call inside the try block

**Comment by viliam-durina** [comment]
This RuntimeException is essentially an assertion. I never expect the cluster to contain more than 2 versions (we ignore the patch version). I believe the join algorithm allows only members with the cluster version or cluster version+1 to join. If it allowed v+2, this error could be thrown.

It's certainly not something the user should be aware of or be able to deal with.
