### ISSUE TITLE
Node fails to start if it has member configured to its public interface and public address is set to its second public interface 

### ISSUE THREAD

**Issue by slavagithub** [hazelcast/hazelcast#19203]
Node fails to start if it has member configured to its public interface and public address is set to its second public interface
 **Steps to reproduce**
1. Assume your host has 172.28.1.1 and 172.29.1.1 IPs
2. Setup configuration:
_hazelcast:
  cluster-name: hostname-test
  network:
    public-address: 172.28.1.1:5701
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        member-list:
          - 172.29.1.1:5701_
 3. Start node
 **ACTUAL RESULT**
" ErrorResponse{callId=8, urgent=true, cause=java.lang.IllegalArgumentException: Target is this node!" in the log, node failed to start.
**EXPECTED RESULT**
Node should start
**Additionl infromation**
If public IP is set to other node IP and this node is trying to setup a cluster, if will fail to start also and log will contain strange message:" Members {size:0, ver:2} []". Please find reproducer here: https://github.com/slavagithub/hazelcast-qe/blob/master/platform-it/hostnames-test/runner/src/test/java/com/hazelcast/qe/issues/Issue_3_Misconfiguration_ClusterIsNotFormedWIthStrangeError.java

**Comment by fbarotov** [comment]
We investigated it with @slavagithub and the issue is no longer reproducible
