### ISSUE TITLE
Memory for Others reaches 100% and brings down the cluster (v4.2)

### ISSUE THREAD

**Issue by shahidbits** [hazelcast/hazelcast#19242]
**Describe the bug**
We are using Hazelcast (v4.2) as a cache solution. We are using only IMap data structure to store the data.

In Management Center, we are seeing the Map memory is less than 5% and "Others" is taking upto 90% of the heap memory. The value for Others fluctuates between 50 and 90.

We are not able to understand what is it taking this much memory. This sometimes brings down the cluster also, when it reaches 100%.

**Expected behavior**
Since, we are using IMap data strucutures only, we should ideally see 99% free heap memory.

**To Reproduce**

1. Connect to clusters using a client (we are using java client)
2. Add some data into IMap entity through a job
3. Leave it running for few hours and observe the heap memory in Management Center
4. It brings down the VM and the machine becomes unresponsive. VM restart is required to bring up the clusters back.

**Comment by ahmetmircik** [comment]
Could you please share a runnable-reproducer and a heap-dump of incident? I did a small run based on the issue description and there seems everything is ok.

**Comment by shahidbits** [comment]
@ahmetmircik Please find the dump here - https://drive.google.com/file/d/1AxlOtgPIbOQZELRypenGBZBN0nKT2cWx/view?usp=sharing

**Comment by ahmetmircik** [comment]
I see you have many maps 10_000? and jmx was enabled. Can you describe exact usage scenario? Which configurations you use? Again, a reproducer will be more helpful.

**Comment by shahidbits** [comment]
I have simply updated the following file from HZ sample code and using the default client configuration -
hazelcast-code-samples-4.2 > clients > basic > src > main > java > Client.java

Here is the code:

`import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.core.HazelcastInstance;

import java.util.concurrent.ScheduledThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public class Client {

    public static ScheduledThreadPoolExecutor commonZonePoolExecutor = new ScheduledThreadPoolExecutor(5);
    ;

    public static void main(String[] args) throws Exception {
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.getNetworkConfig().addAddress("127.0.0.1:5701", "127.0.0.1:5702");

        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        System.out.println(clientConfig.toString());

        String mapKey = "mymap_%s";
        final int[] mapCtr = {0};

        for (int i = 0; i < 100000; i++) {

            int finalI = i;
            commonZonePoolExecutor.schedule(new Runnable() {
                @Override
                public void run() {
                    if (finalI % 10 == 0) {
                        mapCtr[0]++;
                    }

                    String mapName = String.format(mapKey, mapCtr[0]);
                    String key = "mapistaan_" + mapCtr[0] + "_" + finalI;
                    String value = "v1___" + finalI;

                    client.getMap(mapName).put(key, value);

                    System.out.println("mapName=" + mapName + " key=" + key + " value=" + value);
                }
            }, 0, TimeUnit.SECONDS);
        }

//        HazelcastClient.shutdownAll();
    }
}
`

**Comment by ahmetmircik** [comment]
Thanks for the reproducer. 
I ran it and it seems there is garbage and it extends memory till GC steps in. So `other` part of the chart shows this and it decreases after GC, in my run. Here, source of garbage are metrics and management-center requests which is generated periodically. You can configure metrics collection frequency with `MetricsConfig#setCollectionFrequencySeconds` or even disable them and don't use management-center.

We had some extra garbage created by management-center requests there, i sent a fix for them: https://github.com/hazelcast/hazelcast/pull/19277, you can also try your test with my branch.

But this issue shouldn't take your cluster down. Maybe you can give more memory to jvm or if you share running machine with other apps, this may be another cause. 
Also you can re-run your test without management center and by disabling metrics to see the issue reoccurs without them.

**Comment by shahidbits** [comment]
@ahmetmircik Thanks for taking out time and look into it. With metrics disabled, the performance is better during the test. But, after few hours of test completion, the CPU spikes to 100% and brings down the system.

hazelcast-server-config.xml

metrics:
    enabled: false
    management-center:
      enabled: true
      retention-seconds: 10
    jmx:
      enabled: false
    collection-frequency-seconds: 10


Here are the dump of both the members of HZ cluster -

https://drive.google.com/file/d/1St74a-1oRnW8JMszFcF_6BH674ez5E_T/view?usp=sharing
https://drive.google.com/file/d/1FVtveZrQdOz_5lHuZpofi3nba48gNUcY/view?usp=sharing

**Comment by shahidbits** [comment]
@ahmetmircik I hope we can use v4.2.2 which has the fix. Correct?
