### ISSUE TITLE
TTL not working in combination with Max Idle

### ISSUE THREAD

**Issue by pharkinkFD** [hazelcast/hazelcast#19305]
**Describe the bug**
For a Map that has a non-zero TTL _and_ a non-zero max-idle, each access event causes the expiration time to move forward with `Math.min(ttlMillis, maxIdleMillis)` (in `ExpirationTimeSetter#calculateExpirationTime`). This effectively overrules the original `EntryView#getLastUpdateTime() + EntryView#getTtl()`

**Expected behavior**
TTL should be unaffected by read access; expiration time should take both last-update-time and last-access-time (presumably `now`) in account, i.e.  be set to `Math.min(lastUpdateTime + ttlMillis, now + maxIdleMillis)` so that TTL is respected and continuously read entries are still properly flushed after TTL expires.

**To Reproduce**
Create any IMap with a non-zero TTL and max-idle, put an item in the map and periodically (shorter than ttl and max-idle) read the item. It will never be expired/flushed.

Added the following test-case to `com.hazelcast.map.ExpirationTimeTest` to demonstrate:
```java
    @Test
    public void testExpirationTime_touch_should_not_update_expiration_time_if_ttl_is_before_now_plus_maxIdle() {
        IMap<Integer, Integer> map = createMap();
        final long ttl = 5;
        final long idle = 10;
        final long wait = 2;

        map.put(1, 1, ttl, SECONDS, idle, SECONDS);

        sleepAtLeastMillis(SECONDS.toMillis(wait));
        // getEntryView does not invoke `AbstractEvictableRecordStore#accessRecord`; commenting out the next line makes the test pass
        map.get(1);
        EntryView<Integer, Integer> entryView = map.getEntryView(1);

        long creationTime = entryView.getCreationTime();

        long idleExpirationTime = creationTime + SECONDS.toMillis(wait + idle);
        long ttlExpirationTime = creationTime + SECONDS.toMillis(ttl);

        if (idleExpirationTime < ttlExpirationTime) {
            assertEquals("expiration time should be updated by access", idleExpirationTime, entryView.getExpirationTime());
        } else {
            assertEquals("expiration time should be determined by last-update + ttl", ttlExpirationTime, entryView.getExpirationTime());
        }
    }
```

**Additional context**

This specific behaviour occurs in Hazelcast 4.2, and did *not* occur in our previous version (3.12.6). The mentioned test case was locally added to tag `v4.2`

**Comment by mmedenjak** [comment]
Hi @pharkinkFD ! I think this was a deliberate breaking change in 4.x, but @ahmetmircik may confirm.

**Comment by pharkinkFD** [comment]
Thanks for the response @mmedenjak ! If the change was intentional, maybe some of the documentation should also be modified to warn users not to use the max-ttl in combination with max-idle, or at least that doing so favours idle over ttl. I.e. on https://docs.hazelcast.com/cloud/map-configurations.html#max-idle-seconds the note explicitly states "the entry is considered expired if at least one of the policies marks it as expired.", which is not true (anymore).

**Comment by ahmetmircik** [comment]
No this is a regression. i sent a fix candidate: https://github.com/hazelcast/hazelcast/pull/19395

**Comment by pharkinkFD** [comment]
@ahmetmircik  thank you! Fix looks promising
