### ISSUE TITLE
C# GUID not compatible with Java UUID when used as IMap keys

### ISSUE THREAD

**Issue by mvysny** [hazelcast/hazelcast#19371]
**Describe the bug**
Put an object under the GUID key of `ba258733-d222-4da4-b6dc-f7ea0dece0ff` in C#; on Java's side it will be deserialized under the `a44d22d2-3387-25ba-ffe0-ec0deaf7dcb6` UUID.

**Expected behavior**
Putting an object under the GUID key of `ba258733-d222-4da4-b6dc-f7ea0dece0ff` in C#; on Java's side it should be deserialized under the same `ba258733-d222-4da4-b6dc-f7ea0dece0ff` UUID.

**Additional context**

* C# client version: 4.1
* Java client version: 4.2.1 (also reproducible with Java hazelcast 4.1)
* Java 14

Common details that we're often interested in:
- Detailed description of the steps to reproduce your issue
- Logs and stack traces, if available
- Hazelcast version that you use - 4.2.2
- Cluster size, i.e. the number of Hazelcast cluster members: 1 server, one client, very simple "dev" setup, no security.
- Number of the clients: 1
- Version of Java. It is also helpful to mention the JVM parameters: 14
- Operating system. If it is Linux, kernel version is helpful: Linux 5.11, but also reproducible on Windows 10

**Comment by mdumandag** [comment]
cc @zpqrtbnk @alexb5dh

**Comment by alexb5dh** [comment]
Closed via https://github.com/hazelcast/hazelcast-csharp-client/pull/506
