### ISSUE TITLE
Confusing Message When Using Unsupported Type in SQL 'ORDER BY'

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#19430]
**Describe the bug**
Trying to use ORDER BY on a field that doesn't correspond to a type listed [here](https://docs.hazelcast.com/imdg/4.2/sql/data-types.html) (excluding OBJECT), causes the following exception:

```
com.hazelcast.sql.impl.QueryException: Cannot execute ORDER BY clause, because its input is not sorted. Consider adding a SORTED index to the data source.
```

This happens even if you add a `SORTED` index for the field in question. For example, the following uses `java.sql.Date` instead of one of the `java.time.*` supported types:

```
        HazelcastInstance hz = Hazelcast.newHazelcastInstance();
        IMap<Integer, User> users = hz.getMap("users");
        users.addIndex(new IndexConfig(IndexType.SORTED, "creationDate"));
        users.put(1, new User(1, "John Doe", new Date(System.currentTimeMillis())));
//        users.put(1, new User(1, "John Doe", LocalDateTime.now()));
        try (SqlResult result = hz.getSql().execute("SELECT name FROM users ORDER BY creationDate")) {
            for (SqlRow row : result) {
                System.out.println(row);
            }
        }
```

**Expected behavior**
A different message that doesn't confuse the user about the cause.

**To Reproduce**

Run the attached project.
[reproducer.tar.gz](https://github.com/hazelcast/hazelcast/files/7068686/reproducer.tar.gz)

**Comment by viliam-durina** [comment]
Is this for 4.2? We no longer have this error message in 5.0 anywhere.

**Comment by viliam-durina** [comment]
Closing as it doesn't reproduce in 5.0.
