### ISSUE TITLE
Misleading job cancelled message for SQL fault

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19458]
Using Hazelcast Enterprise 5.0-SNAPSHOT (20210902 - 095fca5, d552967), if I run an SQL query that fails,
this message appears in the logs:

```
08:37:29.718 [hz.kind_kalam.jet.cooperative.thread-0] INFO  com.hazelcast.jet.impl.execution.TaskletExecutionService - [10.172.2.9]:5701 [xxx] [5.0-SNAPSHOT] Job was cancelled by the user.
```

This message is confusing, the user won't be aware of the job.

The SQL that failled is here https://github.com/hazelcast/hazelcast/issues/19457

**Comment by viliam-durina** [comment]
I tested the case in the referenced issue and couldn't reproduce the problem. Can you provide a reproducer?

**Comment by viliam-durina** [comment]
Closing due to lack of feedback and we failed to reproduce it. Feel free to reopen with additional information.
