### ISSUE TITLE
fail-fast or log warning if role-separator is used in name of role in simple authentication configuration

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19477]
We should fail-fast during server start up (or at least log some warning) if role name in simple authentication configuration includes role-separator character. It basically means that expected role name will be split into more roles.

**Comment by AyberkSorgun** [comment]
@olukas could you provide an example config?

**Comment by olukas** [comment]
@AyberkSorgun I'm closing this one. Docs has been improved in the meantime and current behavior makes sense now.
