### ISSUE TITLE
Align query-cache and near-cache handling of OBJECT format [HZ-771]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19487]
Near-cache shares the object is selected.
Query-cache makes a copy of the object.
This is inconsistent and a performance cost for query-cache.

**Comment by Holmistr** [comment]
@ahmetmircik AFAIK you confirmed with Neil that this is a real issue. Do you have any idea on the effort needed for the fix?

**Comment by ahmetmircik** [comment]
This will be a behavior change. Now it is working how it should be in a safest manner. But, yes, this behavior change can increase performance. It can be a 2 days effort max i guess and possibly we need to put it in a minor release. This is not appropriate for patch releases. So closest candidates are 5.0 or 5.1.

**Comment by Holmistr** [comment]
5.0 is out of the question, we don't want to squeeze something like this a day before the code freeze. Especially when we don't have a clear view on the urgency (talking to Neil about it). I'll get back to this.

**Comment by Holmistr** [comment]
It's not an urgent issue and can be moved to 5.2.

**Comment by Holmistr** [comment]
Moving it back to 5.1 as I forgot about a hard customer commit.
