### ISSUE TITLE
SQL distinguish between unmapped and missing 

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19496]
If I do `SELECT * FROM cOmPleXmApName` I get back the message
```
From line 1, column 15 to line 1, column 28: Object 'cOmPleXmApName' not found, did you forget to CREATE MAPPING?
```
whether or not the map exists.

It would be helpful to distinguish between the object doesn't exist (perhaps name typed wrong, user error) and the mapping doesn't exist (operator error)

**Comment by viliam-durina** [comment]
A MAPPING doesn't represent only IMaps, but also kafka topics, files and more in the future. From this point of view the error message is correct. See also #19484.

**Comment by mmedenjak** [comment]
@neilstevenson any thoughts on the behaviour and intent?

**Comment by viliam-durina** [comment]
Closing due to lack of feedback. Reopen if you think this is still an issue.
