### ISSUE TITLE
Don't count SQL queries from MC client in phone homes

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#19498]
MC will execute SHOW MAPPINGS in the SQL browser regularly in the background. It will screw up the phone homes statistics.
The proposed solution is for the SQL engine not to count the SQL  queries executed through the internal MC Java client in phone homes and MC will count them itself. 

CC @jgardiner68

**Comment by viliam-durina** [comment]
Is the problem that it will look like everybody is using SQL heavily, while it's only MC listing the mappings?

**Comment by Holmistr** [comment]
Exactly. Or if the user is just executing a few queries, which signals that it's not some production usage but MC will bump those numbers up and that will distort the data.

**Comment by promanenko** [comment]
In the current design (which is still not final!) MC is not going to execute `SHOW MAPPINGS` in background.
Please put this on hold

**Comment by promanenko** [comment]
We ended up doing `SELECT mapping_external_name FROM information_schema.mappings` in background in MC, so this task needs to be implemented
