### ISSUE TITLE
Vulnerabilities in Apache Commons IO 2.5 used by Hadoop in Jet in HZ 5.0

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19578]
This issue was migrated from issue https://github.com/hazelcast/hazelcast-jet/issues/3066. See the original issue for more details.

**Comment by mmedenjak** [comment]
@gurbuzali I see [this commit](https://github.com/hazelcast/hazelcast-jet/commit/946906f6279546801900fe48890caeb78ddceb2a) in jet repo. Has it been ported to this repo and can we close this issue? Are we still waiting for confirmation?

**Comment by gurbuzali** [comment]
here is the forward-port https://github.com/hazelcast/hazelcast/pull/19586

**Comment by mmedenjak** [comment]
Thanks! Can we close the issue with that PR, or is the CVE still pending verification?

**Comment by mmedenjak** [comment]
I see the commit in the jet repo bumped `Update commons-io:commons-io to 2.7`, but the one you referenced doesn't bump commons-io at all. How come?

**Comment by gurbuzali** [comment]
fixed it on the PR, we can close this after merging I think
