### ISSUE TITLE
Vulnerabilities in Elasticsearch 7.10.0 used by Jet in HZ 5.0

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19576]
This issue was migrated from issue https://github.com/hazelcast/hazelcast-jet/issues/3018. See the original issue for more details.

**Comment by mmedenjak** [comment]
Looking at the original issue, I don't know how this can be fixed in 5.1 (since apparently we're blocked by the license).

**Comment by olukas** [comment]
I'm reopening this one and moving to `5.0.z` stream since we have this issue on 5.0.z stream.
