### ISSUE TITLE
Vulnerabilities in avro and avro-ipc-jetty used by Jet in HZ 5.0

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#19577]
This issue was migrated from issue https://github.com/hazelcast/hazelcast-jet/issues/3063. See the original issue for more details.

**Comment by mmedenjak** [comment]
Not sure if there's anything to do in 5.1 since we're already at the latest version. Possibly we can rely on dependabot to remind us when there's a new version.

**Comment by kwart** [comment]
We already have the avro dependency on version `1.11.0`.
Moreover, even the previous patch versions seem to be **not** affected by the CVE according to the related JIRA https://issues.apache.org/jira/browse/AVRO-3111.

Closing.
