### ISSUE TITLE
Partition threads shouldn't write to sockets

### ISSUE THREAD

**Issue by vbekiaris** [hazelcast/hazelcast#19655]
With the write-through optimization (since #14970 -- enabled by default),
it is possible that an async operation (`OperationService#invokeOnPartitionAsync`)
invoked from a partition thread will end up writing to the socket
from that same partition thread.
Doing IO on partition threads is not desired, as it can introduce unexpected latency spikes.

This must be fixed before #19493 can be merged.

**Comment by Holmistr** [comment]
Moving it to backlog as it's not currently backed by outside demand.

**Comment by vbekiaris** [comment]
closing, confirmed with write-through optimization docs that this is working as designed.
