### ISSUE TITLE
Some Hazelcast log statements missing when used via Spring Boot [HZ-822]

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#19668]
**Describe the bug**

When Hazelcast is used via Spring Boot not all log statements are printed. All debug/trace logs are missing, some info statements are missing.

**Expected behavior**

All log statements are visible according to Spring Boot Logging configuration

**To Reproduce**

Use any starter, e.g. https://github.com/leszko/springboot-caching

Change logging level for com.hazelcast to `debug`. 

Start the application

**Additional context**

Some INFO and WARN logs are visible. 

I haven't investigated this in detail, but I suppose the logging chain is (for the default spring boot starter)
Hazelcast -> JUL (default logger) -> jul-over-slf4j -> logback

Maybe the check for enabled log level is lost in this chain.

The following can be used as workaround

```
-Dhazelcast.logging.type=slf4j
```

**Comment by frant-hartm** [comment]
I have the following finding - the discrepancy between shutdown logs is caused by a bug in JDK - jul's LogManager resets the loggers on shutdown, running concurrently with other shutdown hooks it is not deterministic what runs first and we may or may not see the logs in the configuration using jul see [JDK-8161253](https://bugs.openjdk.java.net/browse/JDK-8161253) and [JDK-8029834](https://bugs.openjdk.java.net/browse/JDK-8029834).

The best solution is always to use slf4j when running with Spring. Spring could automatically configure that if it is not already specified. We can send a PR to Spring.

**Comment by frant-hartm** [comment]
Removed from 5.1 as this can't be fixed on our side directly. cc @Holmistr

**Comment by ldziedziul** [comment]
Merged https://github.com/spring-projects/spring-boot/commit/74a88cd34a320587759bd4c2ce9446e04683d856
