### ISSUE TITLE
Fix sonar blocker issues in SpringHazelcastCachingProvider

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19691]
Use try-with-resources or close this "HazelcastServerCachingProvider" in a "finally" clause.

Change the implementation or suppress sonar warning

https://sonarcloud.io/project/issues?fileUuids=AW9qkIoKkrN6v4yKaPtE&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by Tarankalra** [comment]
Hi @ldziedziul , I would like to take this task. Can you assign to me ?

**Comment by Arham-Aalam** [comment]
Hi @Tarankalra, Are you still working on it? Let me know if I can take it.

**Comment by ldziedziul** [comment]
Hi @Arham-Aalam, feel free to take it over

**Comment by vbekiaris** [comment]
This is a false positive and should be flagged as such in sonar.
