### ISSUE TITLE
Fix sonar blocker issues in SerializationServiceV1

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19694]
ObjectDataInput is not closed in `com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl#extractOperationCallId`

https://sonarcloud.io/project/issues?fileUuids=AW9qkInvkrN6v4yKaN-V&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by BalajiSelvaraj10** [comment]
Can I work on this?

**Comment by ldziedziul** [comment]
Yes, feel free

**Comment by ldziedziul** [comment]
Closing as it seems it's was solved (at least from sonar perspectice)
