### ISSUE TITLE
Fix sonar blocker issues in NearCachePreloaderLock

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19693]
Sonar reports that RandomAccessFile is not closed.

https://sonarcloud.io/project/issues?fileUuids=AW9qkInwkrN6v4yKaOD8&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by ufukyilmaz** [comment]
Since the opened channel should not be closed in the same scope, this one is also false positive.

**Comment by ldziedziul** [comment]
> Since the opened channel should not be closed in the same scope, this one is also false positive.

I think we can improve it by closing RandomAccessFile instead of the channel.

**Comment by ufukyilmaz** [comment]
When we close this `RandomAccessFile`, the channel also closes:
<img width="513" alt="Screen Shot 2021-10-05 at 18 10 57" src="https://user-images.githubusercontent.com/14254028/136050880-93d1c496-ed99-48a3-b571-f4c184d21ecc.png">

**Comment by ufukyilmaz** [comment]
Btw, I saw your implementation in https://github.com/hazelcast/hazelcast/pull/19715, it works 👍. Just forget my comment

**Comment by ldziedziul** [comment]
Yes, currently we were closing only the channel, leaving the file open.
