### ISSUE TITLE
Fix sonar blocker issues in JavaDefaultSerializers

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19695]
`ObjectInputStream` is not closed in `JavaDefaultSerializers.JavaSerializer#read(java.io.InputStream, java.lang.ClassLoader)`

https://sonarcloud.io/project/issues?fileUuids=AXIKzIDqbU5mxILfmQ5D&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by izzy-el** [comment]
Hey! I'd like to contribute. Can I take this issue?

**Comment by ldziedziul** [comment]
Sure, it's yours
