### ISSUE TITLE
Fix sonar blocker issues in ClassDataProvider

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19704]
Avoid controlling endless loop with exception in `loadAnonymousClasses`, e.g. by extracting loading class to the method:
```java
  private boolean tryLoadClass(String innerClassName) {
        try {
            parent.loadClass(innerClassName);
        } catch (ClassNotFoundException ex) {
            return false;
        }
        return true;
    }
```

https://sonarcloud.io/project/issues?fileUuids=AW9qkInxkrN6v4yKaOG2&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by Pinkolik** [comment]
Hello! I would like to work on this issue

**Comment by mmedenjak** [comment]
@ldziedziul I see the PR has been merged, but this issue is still open. Can we close it?
