### ISSUE TITLE
Fix sonar blocker issues in TcpServerAcceptor

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19703]
Change the implementation or suppress sonar warning

https://sonarcloud.io/project/issues?fileUuids=AXFg22iHRhxtzbnQ4_VB&id=hz-os-master&resolved=false&severities=BLOCKER&types=BUG

**Comment by ajesk** [comment]
taking a swing at this one as first issue

**Comment by vbekiaris** [comment]
This is a false positive, see https://github.com/hazelcast/hazelcast/pull/19707#pullrequestreview-771021167

**Comment by ldziedziul** [comment]
Marked as false-positive in Sonar
