### ISSUE TITLE
HAZELCAST_CONFIG env variable resolved against Hazeclast home dir and not current dir

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast#19728]
Although this might be useful when the config file is close to the home dir or under it, it's a surprising behavior and the tab completion doesn't work with it.

**Comment by frant-hartm** [comment]
I think this is the correct behavior. I see 2 situations where what you propose would cause issues:
- having hz-start on path, starting hazelcast from a different directory
- (this is for HAZELCAST_CLIENT_CONFIG, but the behavior should be the same) imagine you have multiple configs (clusters you submit to...) and change what is used using the env variable, you submit a job, then change a folder and then the config becomes invalid

**Comment by mtopolnik** [comment]
This is the way it's used typically:

```
$ HAZELCAST_CONFIG=path/to/config.yaml hz-start
```

You expect this to be the path from the current directory, and you expect to be able to costruct it by relying on tab completion.

The current behavior only makes sense when the config file is inside the hz home directory. If it's close to my work, it makes no sense at all and i can't even use relative paths.

**Comment by frant-hartm** [comment]
Then when you change the directory you need to change the env variable, it doesn't make sense to me. Also, the config files most commonly live in the config folder or in Hazelcast home.

You can always provide a full path.
