### ISSUE TITLE
Javas 16 Records support in Compact Serializer [API-1219]

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast#19753]
Add support for Java 16 record classes in Compact Serialization for no-configuration use case.

Support should be added for classes in top level and as fields.

**Comment by TomaszGaweda** [comment]
@mdumandag: @jerrinot Today I was researching how we can accomplish this issue and it's hard to make it both fast and not-hacky.

Instead of pure reflective approach, I started to think about another possibility: use Janino to generate dedicated serializers. IIRC Spark does it in their serialization too. 

Instead of creating writersCache and readersCache, Reflective Serializer will just have 1 cache: `Class<E> -> CompactSerializer<E>`. 

Pros:
1) Code will be very fast (like, very very fast, as fast as just using field access directly).
2) Record reading and writing will be same as other classes in general; will differ in implementation (reader needs completely other implementation), but it will be easily separated.

Cons:
1) We need to add Janino library, about 890 kiB.

WDYT?

**Comment by TomaszGaweda** [comment]
Hi @mdumandag after some research, I'd left it with your approach. I was afraid that unnecessary array allocation and conversion from primitives to Object will cause performance problems, but maybe it's too soon to tell it. Codegen approach would indeed be faster, but would enforce using exactly once convention - which I think we want to avoid. In case of any performance bottleneck for some specific type, user can always write own serializer

**Comment by ihsandemir** [comment]
Will it work with non-Java clients?

**Comment by mdumandag** [comment]
@ihsandemir you could register an explicit serializer for a record. That way, you can achieve interoperability as you wanted.

It will be very similar to the reflective serializer we already have in that regard.
