### ISSUE TITLE
NPE in address translation

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#19765]
1. Start Hazelcast Cloud 5.0
2. Download Hazecast 5.0 ZIP and configure hazelcast-client.xml to connect to a Cloud instance started in the first step
3. Start Hazelcast console `hz-cli console`
4. Stop the Cloud cluster
5. After some time the console will start printing this:
```
18:11:05.963 [ WARN] [c.h.c.i.c.ClientConnectionManager] hz.client_1 [de-1927] [5.0] Failed to translate address [10.1.3.64]:30003 via address provider Address Provider class com.hazelcast.client.impl.spi.impl.discovery.RemoteAddressProvider could not translate address [10.1.3.64]:30003
18:11:05.963 [ WARN] [c.h.c.i.c.ClientConnectionManager] hz.client_1 [de-1927] [5.0] Could not connect to member acacadb7-6598-49dc-b7df-9b764072edb7, reason java.lang.NullPointerException: Address Provider class com.hazelcast.client.impl.spi.impl.discovery.RemoteAddressProvider could not translate address [10.1.3.64]:30003
```
While some error is expected (a cluster is down after all), the NPE is wrong. 
Also I suspect it does not necessary need a cloud cluster instance. I can help with a reproducer is needed.

**Comment by srknzl** [comment]
Not proficient with Java exception handling, but I think NPE feels a programming error, which might make our code look buggy.

**Comment by jerrinot** [comment]
@mdumandag but if we throw some other exception then Java will not throw NPE
@srknzl: exactly that. when I saw the log message I was convinced it was a Hazelcast bug.

**Comment by ILGO0413** [comment]
Well, the method AddressProvider#translate can return either non-null Address or throw an exception, null cannot be returned at the moment. One can refactor the method to return null and add a new null check in TcpClientConnectionManager#getOrConnectToAddress and TcpClientConnectionManager#getOrConnectToMember methods after AddressProvider#translate method invocation, but it would be better to use a quick solution with HazelcastException as a long-term one.
