### ISSUE TITLE
Add property for hazelcast.client.cloud.url

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#19786]
Cloud needs two properties, URL and TOKEN

There is a property for the token, https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/properties/ClientProperty.java#L207
but not for the URL

**Comment by neilstevenson** [comment]
While a trivial fix, this should be co-ordinated across all client languages

**Comment by sancar** [comment]
@neilstevenson Can you explain why the url parameter is needed ? Should it be something public ?

**Comment by neilstevenson** [comment]
If it's not needed for PROD then it doens't need to be exposed.
