### ISSUE TITLE
SST files not being purged, filesystem seemingly growing without bounds

### ISSUE THREAD

**Issue by APIANT** [hazelcast/hazelcast#19851]
We started using Hazelcast v5 recently (were previously using v4 and older versions for over a year) and are seeing that the management console metrics/datapoints storage directory is growing in size, seemingly without bounds. Lots of files with an .sst extension are stored.  We purged them after they reached 5GB.

According to these, the default persistence of metrics should be 1 day:

https://docs.hazelcast.com/management-center/5.0/metric-persistence
https://docs.hazelcast.com/management-center/5.0/configuring#disk-usage-config

But we have seen hundreds of SST files older than one day.

After setting hazelcast.mc.metrics.disk.ttl.duration to "P1D" in our code, we still see no reduction in the retention of SST files. Files older than one day are being retained.

Next we are setting "hazelcast.client.statistics.enabled" to false to see if that will help to avoid filesystem storage growth.

**Comment by zhmaeff** [comment]
Hi @APIANT could you please retest with MC version 5.0.2?

**Comment by APIANT** [comment]
Yes, will retest this week and report back.

**Comment by APIANT** [comment]
Hi,

We installed MC 5.0.2 on the 16th.  Still have the TTL set to P1D for 1 day retention.

Although the SST files are now correctly being purged after 1 day, we are seeing these LOG files retained:

![image](https://user-images.githubusercontent.com/2120558/142673392-8ef7dad8-96f0-42fd-84ae-6bb857720d60.png)

Shouldn't these also be cleaned up?

**Comment by zhmaeff** [comment]
@APIANT no, it's OK to have logs older than TTL.
We rotate them on MC restart or when log file size exceeds 50MB and we keep only 10 last log files.

**Comment by APIANT** [comment]
Super, thanks for the help!
