### ISSUE TITLE
The IMPOSE_ORDER function should drop late items [HZ-1016]

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19887]
The IMPOSE_ORDER function should not only add watermarks to the stream, but also drop late items. The current implementation doesn't, we rely on the window functions (TUMBLE/HOP) to do it, but it should happen even without a window function.

This test should pass in `SqlImposeOrderFunctionTest`:
```java
    @Test
    public void test_lateItemsDropping() {
        String name = createTable(
                row(timestampTz(10), "Alice"),
                row(timestampTz(11), "Bob"),
                row(timestampTz(5), "Cecilia")
        );

        assertRowsEventuallyInAnyOrder(
                "SELECT * FROM " +
                        "TABLE(IMPOSE_ORDER(" +
                        "  lag => INTERVAL '0.001' SECOND" +
                        "  , input => (TABLE " + name + ")" +
                        "  , timeCol => DESCRIPTOR(ts)" +
                        "))",
                asList(
                        new Row(timestampTz(0), "Alice"),
                        new Row(timestampTz(1), "Bob")
                        // Cecilia is dropped because ti's late
                )
        );
    }
```

**Comment by Fly-Style** [comment]
By @viliam-durina: 

> ...write a processor that will actually do the dropping, we don't have such processor yet. Though we might be fine with `filterStateful`. But the hard part is that there needs to be a rel for this processor in the plan, and the rule matching `aggr`+`slidingWindow` should match this rel too and remove it, because it's not necessary. The `SlidingWindowP` combines all three tasks: dropping late items, adding window bounds and aggregating. And for such a rel we need to also implement the `filter-dropLate-transpose-rule` and so on.
