### ISSUE TITLE
Optimize window aggregation plans

### ISSUE THREAD

**Issue by gierlachg** [hazelcast/hazelcast#19882]
Window aggregation queries produce plans containing this:

```
AggregateLogicalRel(group=[{0}], EXPR$1=[MIN($1)], EXPR$2=[MIN($2)])
  ProjectLogicalRel(window_start=[$3], name=[$1], distance=[$2])
    SlidingWindowLogicalRel(invocation=[TUMBLE($2, DESCRIPTOR($0), 2:INTERVAL DAY TO SECOND)], rowType=[RecordType(TIMESTAMP WITH TIME ZONE ts, VARCHAR name, INTEGER distance, TIMESTAMP WITH TIME ZONE window_start, TIMESTAMP WITH TIME ZONE window_end)])
```

Each of these steps is backed by a separate vertex (Aggregate by 2 of them actually), however, all these three steps can be executed by `SlidingWindowP`. Maybe there can be 2 rules: one merging the `Project` into `SlidingWindowRel`, and the other merging `Aggregate` and `SlidingWindowRel` into `SlidingWindowAggrRel`.

**Comment by Fly-Style** [comment]
It was done as a part of #20342. All rels above are baked into `SlidingWindowAggregatePhysicalRel`, which produce vertexes for single, or two-staged window aggregation.
