### ISSUE TITLE
Rolling-upgrade compatibility of new QueryDataTypes

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19902]
The #19303 PR added new `QueryDataType.JSON`. The #19863 is about to add `ROW`. We need to make sure that mappings with these types aren't added as long as the cluster version is 5.0 because there can be other members that will fail to deserialize this value.

We can write test for this first. If the older members fail gracefully, maybe we don't need to guard against it.

**Comment by tonytheonlypony** [comment]
When testing mapping the JSON QueryDataType on cluster version 5.0, I was able to query for it with no issue. Is there a way to check in the management center whether a member failed to deserialize the value?

**Comment by viliam-durina** [comment]
@tonytheonlypony There's no `QueryDataType.JSON` in 5.0, I'm not sure what you mean. Do you mean that you had all 5.1 members, but the cluster was set to 5.0 version? That's the case this issue asks to be fixed.

**Comment by tonytheonlypony** [comment]
@viliam-durina I started the the initial member by running: 
```
docker run \
    -it \
    --network hazelcast-network \
    --rm \
    -e HZ_CLUSTERNAME=hello-world \
    -p 5701:5701 hazelcast/hazelcast:5.0
```
I also started the other members in a similar fashion. My assumption was that the "5.0" at the end indicates the member is set to version 5.0 (meaning the cluster version is also 5.0).

This is part of how I did a JSON query (according to an example):
```
    person1 = '{ "name": "John", "age": 35 }'
    person2 = '{ "name": "Jane", "age": 24 }'
    person3 = '{ "name": "Trey", "age": 17 }'

    id_person_map.put(1, HazelcastJsonValue(person1))
    id_person_map.put(2, HazelcastJsonValue(person2))
    id_person_map.put(3, HazelcastJsonValue(person3))
```
My guess is that QueryDataType.JSON is different from using  id_person_map.put(1, HazelcastJsonValue(person1)).

**Comment by viliam-durina** [comment]
Native JSON type is a new feature in 5.1. The above code works in 5.0, but the mapping will have `name` and `age` columns. In 5.1 there's an option to have `this` column of JSON type, for which you can use functions such as `JSON_QUERY`. It's useful for deeply nested documents or documents with variable structure. Rolling upgrade functionality is enterprise feature that allows the migration from 5.0 to 5.1 by upgrading members one by one. Until all members are upgraded, there are members with two versions in the same cluster. We need to ensure that 5.0 members don't fail when encountering a mapping with JSON type.

**Comment by viliam-durina** [comment]
It fails gracefully, so it's OK:
```
viliam@viliam-ThinkPad:~/Downloads/hazelcast-5.0.2$ bin/hz-cli sql
Connected to Hazelcast 5.1-SNAPSHOT at [10.212.134.153]:5701 (+0 more)
sql> select cast('1' as json);
Unexpected SQL column type = [15]
```
