### ISSUE TITLE
Ignore or fail for duplicate Kafka topics

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#19948]
When a duplicate topic is passed to the kafka source connector in the `topics` list, it can happen that some partitions are read twice. The issue is that when running the job on one member there will be no duplicates, because we pass a `Set` to `KafkaConsumer.assing` and the duplicates are eliminated. With larger number of members, duplicates are likely.

The fix might be to either remove duplicates from the list, or throw. To maintain b-w compatibility we probably should clean up the list.

Unsure whether this is a defect or just enhancement :)

**Comment by frant-hartm** [comment]
This issue has been fixed by refactoring in https://github.com/hazelcast/hazelcast-jet/pull/2732

In #20565 a regression test and a warning log was added.
