### ISSUE TITLE
SELECT this fails with compact serialization and more than 1 member when class not on classpath [HZ-737]

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#19952]
**Describe the bug**

After inserting data via java client, selecting the object (`SELECT this FROM map`) fails with exception:

```
com.hazelcast.sql.HazelcastSqlException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DefaultCompactReader'

	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:131)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:105)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at CompactTest.name(CompactTest.java:112)
```

Additional details are not available due to #18917.

**Expected behavior**
Should return results, deserialized into domain objects on the client side.

**To Reproduce**

I am not able to reproduce this inside single JVM with 2 member cluster, using the usual FilteringClassLoader, the issue doesn't happen there for some reason - I tried to modify the com.hazelcast.jet.sql.SqlClientCompactQueryTest

So here is more complicated setup using docker and our new docker infra in enterprise repo

this is using:
- docker and testcontainers to start 2 members (hz1, hz2)
- the com.hazelcast.jet.sql.SqlClientCompactQueryTest as base (removed unrelated stuff), it actually gives me a different error message then in with my domain object, so I included both tests

https://github.com/frant-hartm/hazelcast-enterprise/commit/ea8593df6ee0b3ae1efb9139a7f6904cf4cb8f94

Happens both on master and 5.0.

**Comment by sancar** [comment]
I found two problems. One of them is straight forward to solve. Sharing the hard to solve one.

In the ReceiverTasklet there is this following code:

```
 BufferObjectDataInput input = serializationService.createObjectDataInput(payload, PACKET_HEADER_SIZE);
 ....
 final Object item = input.readObject();
 inbox.add(new ObjWithPtionIdAndSize(item, input.readInt(), itemSize));
 ......
 input.close();
```

The Object returned for the Compact is a `DefaultCompactReader`. 
It is a wrapper around `BufferObjectDataInput `which will read it lazily. 
After reading it, we are sending it to another place to process it. 
And we are closing the `BufferObjectDataInput`  . 

When someone tries to read something from the item it gets NullPointerException which at the end looks like 

```
com.hazelcast.sql.HazelcastSqlException: Failed to serialize 'com.hazelcast.internal.serialization.impl.compact.DefaultCompactReader'

	at com.hazelcast.sql.impl.client.SqlClientService.handleExecuteResponse(SqlClientService.java:131)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:105)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at CompactTest.name(CompactTest.java:112)
```

Two Solutions: 
 - Slow but easy to reason: We may get rid of lazy nature of Compact. One less optimization. 
 - Hard to reason but optimized: We may prevent ObjectDataInput to be closed if it is used by somebody else via introducing `ownership` logic. 
 
 I tend to choose slow but easy to reason following the `premature optimization is root of all evil` , but I would like to get second opinions.

**Comment by sancar** [comment]
Thinking more in this code piece on ReceiverTasklet:
```
 BufferObjectDataInput input = serializationService.createObjectDataInput(payload, PACKET_HEADER_SIZE);
 ....
 final Object item = input.readObject();
 inbox.add(new ObjWithPtionIdAndSize(item, input.readInt(), itemSize));
 ......
 input.close();
 ```
 
 This `readObject` code is against the client/server architecture where we try to avoid needing the user classes on the server as much as possible. 
 If we were to carry `Data` here instead, we would not have this problem. Not sure if this is solvable at this point due to backward compatbility.

**Comment by viliam-durina** [comment]
Do we actually need to call `input.close`? It doesn't release any resources, it only assigns `null` to two fields, which apparently cause the NPE. If the deserialized objects have no reference to the data, clearing makes no difference. If they do as in lazy deser, it breaks it.

**Comment by sancar** [comment]
@viliam-durina make sense. I also considered making the close of `BufferObjectDataInput` and `MemoryBlockDataInput` no-op directly together with removing close from here. So that when somebody else closes it  somewhere else, we will not have the same problem.

**Comment by sancar** [comment]
@ihsandemir @mdumandag @viliam-durina 
I proposed two solutions but going with the third one after @viliam-durina 's comment. 
Instead of doing making `close` no-op, I am thinking to remove `Closable` interface all together from these two BufferObjectDataInput and MemoryBlockDataInput

Although it is common to have `Closable` on input streams, it does not seem to serve any purpose as of today. And it is creating confusion.
