### ISSUE TITLE
Diagnostics' Operation Profiler Plugin puts latency under wrong bucket.

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#19968]
**Describe the bug**
Notice the following latency distribution for an operation from the diagnostic logs:

```
                      com.hazelcast.internal.partition.operation.PartitionBackupReplicaAntiEntropyOperation[
                                  count=8,899,137
                                  totalTime(us)=555,742,201
                                  avg(us)=62
                                  max(us)=2,459,660
                                  latency-distribution[
                                          8..15us=85
                                          16..31us=2,040,208
                                          32..63us=6,619,514
                                          64..127us=232,768
                                          128..255us=6,175
                                          256..511us=241
                                          512..1023us=40
                                          2048..4095us=6
                                          4096..8191us=24
                                          8192..16383us=43
                                          16384..32767us=25
                                          32768..65535us=3
                                          1048576..2097151us=5]]
```

`max(us)=2,459,660` but the highest latency bucket logged is `1048576..2097151us=5`. Checking [LatencyDistribution](https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/hazelcast/src/main/java/com/hazelcast/internal/util/LatencyDistribution.java), the expected bucket for this value should be `2097152..4194303us` or index 22. Adding the following assertion to [LatencyDistributionTest.usToBucketIndex()](https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/hazelcast/src/test/java/com/hazelcast/internal/util/LatencyDistributionTest.java#L129) results in failure with actual bucket index being 21.

`assertEquals(22, LatencyDistribution.usToBucketIndex(2459660));`

**Expected behavior**
The value 2,459,660us should go under 2097152..4194303us rather than 1048576..2097151us

**Comment by sertugkaya** [comment]
https://hazelcast.lightning.force.com/lightning/r/Case/5006e00001ZnDJUAA3/view
