### ISSUE TITLE
Spring xml config: Allow spring property placeholders in eviction size.

### ISSUE THREAD

**Issue by volkov** [hazelcast/hazelcast#19997]
I'm trying to configure different cache size in different environments using spring xml configuration:
```(xml)
            <hz:map name="myMap">
                <hz:eviction size="${map.size:7500}"/>
            </hz:map>
```
This is not valid because size could be only non negative integer https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-4.2.xsd#L3782

I think changing type to `parameterized-non-negative-integer` would fix this issue. 
In #5590 similar problem was fixed.

**Comment by ldziedziul** [comment]
Spring property placeholders' support will be enhanced in the 5.1 release. See https://github.com/hazelcast/hazelcast/pull/19629
