### ISSUE TITLE
Make docker-based tests enabled by default [HZ-744]

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#19994]
We shouldn't silently skip docker-based tests when docker is not there but rather disable them explicitly within a systemProperty or maven profile. Something along this lines (maybe extract helper method):
```diff
-        assumeTrue(DockerClientFactory.instance().isDockerAvailable());
+        assumeFalse(System.getProperty("dockerTestsDisabled").equals("true"));
```

I could imagine we could misconfigure docker on a machine and have a false sense of trust in our tests supposedly running on docker, while they would be silently skipped. 

Follow-up questions: 
- Do we really have environments that don't have docker? 
- Can we ask the community to have docker installed?

If so then we could remove the flag completely and assume that docker is there.

**Comment by frant-hartm** [comment]
> have environments that don't have docker?

Yes, we don't have docker configured on our AWS Windows machine, Solaris, MacOS 

Also, some architectures don't have all images available (afaik `adobe/s3mock` was available only for amd64, not arm), these should be handled individually, but currently we don't run docker tests at all there 

>Can we ask the community to have docker installed?
I think it's fine, when running on a machine without docker it should clearly say why it's failing (= missing docker), what to do (set the flag) and what is the implication (= subset of tests won't be run).
