### ISSUE TITLE
Hazelcast 3.8.6 compatibility issue with hibernate 5.2.18

### ISSUE THREAD

**Issue by Jijithnair** [hazelcast/hazelcast#20047]
Description -
We have upgraded the spring security web to 5.5.1 version. As part of solving the compatibility issues, we had to upgrade hibernate as well., to version 5.2.18.

This caused additional issues with hazelcast and hence upgraded the jar to hazelcast-hibernate52 - 1.3.0 (also tried with 1.3.3), as our hazelcast version is 3.8.6.

Now certain operations are throwing the following error:
"com.hazelcast.nio.serialization.HazelcastSerializationException: java. io. InvalidClassException: org hibernate.cache.spi.entry.StandardCacheEntryImpl; local class incompatible: stream classdesc serialVersionUID......"
hence failing to commit the transaction.

Please find the configuration summary:
Hibernate - Upgraded from 5.0.5.Final to 5.2.18
Hazelcast - 3.8.6 - No change
Hazelcast-hibernate - Upgraded from hazelcast-hibernate5 1.2.0 to hazelcast-hibernate52 1.3.0 (tried with 1.3.3 as well)
spring core,aop,beans,orm,tx etc - Upgraded from 5.0.8.Release to 5.3.8

**Comment by frant-hartm** [comment]
Hi @Jijithnair,

Hazelcast 3.8.6 and hazelcast-hibernate52 1.3.0 are no longer supported. If you can reproduce your issue with newer versions of Hazelcast (4.1+) and hazelcast-hibernate (2.2.+) please feel free to reopen and provide an updated configuration.
