### ISSUE TITLE
NearCacheConfig setEvictionPolicy(String evictionPolicy) 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#2010]
needs a String argument ?

however 
 
MapConfig setEvictionPolicy(EvictionPolicy evictionPolicy) 
wants an enum EvictionPolicy 

al the least its inconsistent.

NearCacheConfig has a with default access

static enum EvictionPolicy {
        NONE, LRU, LFU
    }

**Comment by Donnerbart** [comment]
Should be fixed by https://github.com/hazelcast/hazelcast/pull/8854

The new way to configure eviction for Near Caches is the `EvictionPolicy` of the Near Cache. This also works now for the on-heap IMap Near Caches. The old methods are of course still there, but deprecated.
