### ISSUE TITLE
Can  IMap Interface add a "increment" & "decrement"method similar to "Memcached"?

### ISSUE THREAD

**Issue by wjw465150** [hazelcast/hazelcast#2016]
Can  IMap Interface add a "increment" & "decrement" method similar to "Memcached"?

**Comment by tunix** [comment]
Hi @sancar ,

Persistence support for atomic classes would be a huge win for my use case as well. I'm planning to create a lookup table using a few maps and an AtomicLong. The maps will be persisted into the DB (Couchbase) using the MapStore interface. I need to figure out a way of loading/storing AtomicLong back/forth in case of failures. I'll try my changes using the EntryProcessor but again, the native persistent support for atomic classes would be much nicer!
