### ISSUE TITLE
Support for producing EntryStore using MapStoreFactory

### ISSUE THREAD

**Issue by mario45211** [hazelcast/hazelcast#20200]
Hi Hazelcast team!

**Please describe the problem you are trying to solve**
I want to use `MapStoreFactory` to create dynamic `EntryStore` instances per any map in cluster. Currently there is no support for `EntryStore` instances, which is unacceptable for my case, which store must load entries in store with their origin TTLs.

**Please describe the desired behavior**
New interface for `EntryStore` factory ?
```java
public class MyFactory implements EntryStoreFactory<String, Object> {

@Override public EntryStore<String, Object> newEntryStore(String mapName, Properties properties) {
        return new MyEntryStore(mapName);
    }
}
```
Please let me know what you think about such feature.

Best regard!

**Comment by mario45211** [comment]
Solved by changing second generic parameter of `MapStoreFactory` interface like:
```java
class MyFactory implements MapStoreFactory<String, EntryLoader.MetadataAwareValue<Object>>
```

**Comment by willie68** [comment]
Hi,
i was searching for this in the documentation, but i didn't find it. 
Would be nice, if you can document this in 
https://docs.hazelcast.com/hazelcast/5.2/mapstore/implement-a-mapstore
