### ISSUE TITLE
REPLACE does change an SQL VIEW [HZ-1262]

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#20204]
Using Hazelcast Enterprise 5.1-SNAPSHOT (20211215 - a297151, ba01b38)

If I create a view then change the view, the update does not appear to take effect, but not rejection message is given
Eg.
`CREATE OR REPLACE VIEW "neil" AS SELECT JSON_VALUE(this, '$.name' RETURNING VARCHAR) FROM "zipkin2.span"`
then
`SELECT * FROM neil`
does what I expect

But i I then do
`CREATE OR REPLACE VIEW "neil" AS SELECT JSON_VALUE(this, '$.kind' RETURNING VARCHAR) FROM "zipkin2.span"`
and
`SELECT * FROM neil`
it still shows the same output (the `name` not the `kind`)

**Comment by Fly-Style** [comment]
Hi, @neilstevenson. Thanks for report!
I am working on it under https://github.com/hazelcast/hazelcast/issues/20032.

**Comment by mmedenjak** [comment]
@Fly-Style that other issue is in 5.2 milestone, this one is in 5.1. Can you clean this up?

**Comment by viliam-durina** [comment]
Not fixed. Reproducer:
```
    @Test
    public void test_planCacheInvalidation() {
        instance().getSql().execute("CREATE VIEW v AS SELECT 1");
        String queryWithCachedPlan = "SELECT * FROM v";
        assertRowsAnyOrder(queryWithCachedPlan, rows(1, (byte) 1));

        instance().getSql().execute("CREATE OR REPLACE VIEW v AS SELECT 2");
        assertRowsAnyOrder(queryWithCachedPlan, rows(1, (byte) 2));
    }
```

**Comment by viliam-durina** [comment]
a duplciate Jira issue: [HZ-1262](https://hazelcast.atlassian.net/browse/HZ-1262)

**Comment by AyberkSorgun** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/22091
