### ISSUE TITLE
MapScanMigrationStressTest.stressTest_sortedIndex never hits MissingPartitionException

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20290]
The test is supposed to test behavior after migration. However the MissingPartitionException is never caught when running this test.

**Comment by Fly-Style** [comment]
Can't reproduce it, `MissingPartitionException` happens constantly during the test.

**Comment by viliam-durina** [comment]
Ran the test 6 times, the number of times the exception was caught was:
1
3
0
1
0
2

So it most of the times it happens, but not really a _stress test_ :trollface:
Postponing to 5.2

**Comment by Fly-Style** [comment]
`MapScanMigrationStressTest` was rewritten multiple times and was fixed. Personally, counted 5 times during a pretty short test time.
