### ISSUE TITLE
Cannot sign in to Management Center v5.0.4 after upgrade from 4.x, but only on some machines

### ISSUE THREAD

**Issue by APIANT** [hazelcast/hazelcast#20294]
Hi,

We have 8 servers all configured the same.  None of the servers are in a cluster, they are individual machines that don't talk to any other server.

We have upgraded all servers w/ Hazelcast 5.0.2 and Management Center 5.0.4.

After the upgrade, half of the servers can access the Management Center just fine.  The other half show this error in the browser:

Management Center - Unexpected Error
An unexpected error has occurred. Please check the system logs to see the details.

Catalina.out contains this exception:
```
31-Dec-2021 16:46:11.973 SEVERE [ajp-nio-127.0.0.1-8009-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [dispatcher] in context with path [/hazelcast-management-center-5.0.4] threw exception
	com.hazelcast.webmonitor.controller.exception.InvalidOperationApiException: Could not process operation. Reason: Security provider needs to be configured first!
		at com.hazelcast.webmonitor.security.spi.impl.AuthenticationManagerImpl.checkSecurityProviderConfigured(AuthenticationManagerImpl.java:246)
		at com.hazelcast.webmonitor.security.spi.impl.AuthenticationManagerImpl.getAuthenticationProvider(AuthenticationManagerImpl.java:239)
		at com.hazelcast.webmonitor.security.spi.impl.AuthenticationManagerImpl.authenticate(AuthenticationManagerImpl.java:58)
		at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:201)
...
```

The hazelcast.mc.home system variable points to the same directory on each machine.  We deleted the contents of the hazelcast.mc.home directory after installing the upgrade.

If we copy that hazelcast.mc.home directory from a working machine to one that does not, the error goes away and the login page appears.  But we cannot sign in, even with the credentials from the other machine.  If we delete the sql/mc.mv.db file in hopes of clearing out the credentials, then the error appears again.

It seems Management Center is not initializing itself correctly on the machines that are not working.  We cannot figure out why, all the machines are basically copies of each other with the same Java/Tomcat stack, all have the exact same software versions installed.

**Comment by erosb** [comment]
Hello,

> If we copy that hazelcast.mc.home directory from a working machine to one that does not, the error goes away and the login page appears. But we cannot sign in, even with the credentials from the other machine.

What happens if, after copying the home dir from a working server to a non-working server, before you start MC, you add a new user with `./mc-conf.sh user create -H=${MC_DATA} -n=admin -p=p@ssw0rd -r=newadmin` ? 
Does it create the new user successfully? Can you start MC and log in?

**Comment by APIANT** [comment]
Well this is strange.  We didn't change anything at all on the non-operational machines.  I needed to know which ones were not operating vs. the ones that were ok, so I accessed the management console URL on each.  Like magic, all the previously non-operational machines presented the initial screen to configure their authentication method:

![image](https://user-images.githubusercontent.com/2120558/147953192-e7cb38ca-4b31-48c4-8eb5-6d7957bf48b4.png)

So it seems something in background worked some magic to initialize the management center's security system?

When the problem first happened, it was late in the evening.  Then the following day we spent some hours troubleshooting on one of the machines.  Lots of "try this, try that, reboot" cycles.  The other machines were not touched.  So I'm pretty sure the trouble lasted at least 12 hours.  Today is more than 3 days since the 5.0.4 installs were performed.

Let me know if there is any other information you need about this.  But as of now management center is working on all of those machines.

**Comment by erosb** [comment]
There is no background process running when MC is down. I think it was an unrelated local problem. Closing the issue for now, we can reopen any time if the problem comes up again.
