### ISSUE TITLE
Hazelcast fails to compile on Apple M1 Silicon [HZ-800]

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#20310]
**Describe the bug**
When compiling Hazelcast 5.1-SNAPSHOT on an Apple M1 Macbook Pro 2022...
`mvn clean install -DskipTests`

it fails on two extension modules
`hazelcast-jet-grpc`
`hazelcast-jet-protobuf`

with the following log...

```
[ERROR] 1) com.google.protobuf:protoc:exe:osx-aarch_64:3.13.0
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.13.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.13.0 -Dclassifier=osx-aarch_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]   	1) com.hazelcast.jet:hazelcast-jet-grpc:jar:5.1-SNAPSHOT
[ERROR]   	2) com.google.protobuf:protoc:exe:osx-aarch_64:3.13.0
[ERROR]
```
**Solution**

Updating the root `pom.xml` to include dependencies that support Arch64.

`com.google.protobuf.protobuf-java` from `3.13.0` to `3.19.1`

`io.grpc.grpc-protobuf` from `1.34.0` to `1.43.0`

**Comment by dbrimley** [comment]
I've not tested any knock on effects of upgrading these jars, which is why I've not raised a PR.  I'm also not sure if there are other ongoing efforts to support Apple M1 in 5.1 release.

**Comment by mmedenjak** [comment]
I assume there's just no protobuf support for that architecture. Something to look at after BETA cc @frant-hartm @ldziedziul

**Comment by dbrimley** [comment]
I have it compiling fine if we upgrade 2 libraries as per the original issue post.
