### ISSUE TITLE
Split brain recovery depends on lexicographic order of member addresses [HZ-1035]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#20331]
The cluster merge fails after a split-brain in some scenarios when only part of the member addresses is listed in the join configuration.

**Steps to reproduce:**
Let's have a 2 node cluster with member addresses `172.219.0.3:5701` and `172.219.0.4:5701`.
Both members have the following config:
```yaml
hazelcast:
  network:
    join:
      tcp-ip:
        enabled: true
        member-list:
          - 172.219.0.4:5701
```

Let's cause a split-brain (e.g. we can also simply restart one of the nodes). After the connection is reestablished (or node is started), members won't form the cluster again.

When the problematic scenario is running, we can see the `ClusterJoinManager` (172.219.0.4) identifies it should join to the other cluster (172.219.0.3), but its address is not in the member config so it doesn't proceed in the `TcpIpJoiner.searchForOtherClusters()`
```
2022-01-07-09:17:27 [FINE] com.hazelcast.internal.cluster.impl.ClusterJoinManager [172.219.0.4]:5701 [dev] [5.1-SNAPSHOT] Checking if we should merge to: SplitBrainJoinMessage{packetVersion=4, buildNumber=20220105, memberVersion=5.1.0, clusterVersion=5.1, address=[172.219.0.3]:5701, uuid='5910194b-3214-4b7e-ad2b-ad92110376af', liteMember=false, memberCount=1, dataMemberCount=1, memberListVersion=1}
2022-01-07-09:17:27 [INFO] com.hazelcast.internal.cluster.impl.ClusterJoinManager [172.219.0.4]:5701 [dev] [5.1-SNAPSHOT] We should merge to [172.219.0.3]:5701, both have the same data member count: 1
2022-01-07-09:17:27 [FINE] com.hazelcast.internal.cluster.impl.operations.SplitBrainMergeValidationOp [172.219.0.4]:5701 [dev] [5.1-SNAPSHOT] Returning SplitBrainJoinMessage{packetVersion=4, buildNumber=20220105, memberVersion=5.1.0, clusterVersion=5.1, address=[172.219.0.4]:5701, uuid='61be8799-fc37-4898-9132-0e9183ec8914', liteMember=false, memberCount=1, dataMemberCount=1, memberListVersion=1} to [172.219.0.3]:5701
```

**Passing Case:**
If we **replace** the member address with the second one (`172.219.0.3:5701`) in the config, the clusters will join correctly after the split-brain.

As we see, the behavior depends on lexicographic order of addresses: (see [ClusterJoinManager.shouldMergeTo()](https://github.com/hazelcast/hazelcast/blob/v5.0.2/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java#L985) method).

**Expected behavior**
Clusters join after the split-brain even if the members from one subcluster are not listed in the master's configuration of another cluster.

*Note: maybe we could keep the address from a `SplitBrainMergeValidationOp` is some registry within the `Node` and make an attempt to connect to it in the ClusterJoinManager.searchForClusters()`*

**Comment by AyberkSorgun** [comment]
https://github.com/hazelcast/hazelcast/pull/21552 https://github.com/hazelcast/hazelcast-enterprise/pull/5055

**Comment by kwart** [comment]
Reopening, as this one is not resolved by the #21552

Here is a simple reproducer:

```java
import java.util.concurrent.TimeUnit;

import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.config.TcpIpConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.instance.impl.HazelcastInstanceFactory;

public class App {

    public static void main(String[] args) throws Exception {
        boolean passed = false;
        try {
            HazelcastInstance hz1 = Hazelcast.newHazelcastInstance(createConfig(5701, 5801));
            HazelcastInstance hz2 = Hazelcast.newHazelcastInstance(createConfig(5801, 5801));
            TimeUnit.SECONDS.sleep(60);
            assertClusterSize(3, hz1, hz2);
            passed = true;
        } finally {
            HazelcastInstanceFactory.terminateAll();
            System.out.println(passed ? ">>> OK" : ">>> FAILED");
        }
    }

    protected static Config createConfig(int port, int... otherPorts) {
        Config config = new Config().setProperty("hazelcast.member.naming.moby.enabled", "false")
                .setProperty("hazelcast.merge.first.run.delay.seconds", "30")
                .setProperty("hazelcast.merge.next.run.delay.seconds", "20");
        NetworkConfig networkConfig = config.getNetworkConfig();
        networkConfig.setPortAutoIncrement(false).setPort(port);
        JoinConfig join = networkConfig.getJoin();
        join.getAutoDetectionConfig().setEnabled(false);
        join.getMulticastConfig().setEnabled(false);
        TcpIpConfig tcpIpConfig = join.getTcpIpConfig().setEnabled(true).clear();
        for (int otherPort : otherPorts) {
            tcpIpConfig.addMember("localhost:" + otherPort);
        }
        return config;
    }

    public static void assertClusterSize(int expectedSize, HazelcastInstance... instances) {
        for (int i = 0; i < instances.length; i++) {
            int clusterSize = instances[i].getCluster().getMembers().size();
            if (expectedSize != clusterSize) {
                throw new RuntimeException(
                        String.format("Cluster size is not correct. Expected: %d, actual: %d, instance index: %d", expectedSize,
                                clusterSize, i));
            }
        }
    }
}
```

**Comment by ramizdundar** [comment]
@kwart I think we should avoid merging https://github.com/hazelcast/hazelcast/pull/21418 because of the reasons @ufukyilmaz mentioned. In his design, it's accepted that sometimes, manual intervention may be required. In such cases TCP IP config should be updated dynamically. To do that, currently REST API must be enabled and then you can use reload or dedicated endpoint.

Your reproducer should be able to form a cluster if you were to dynamically update the TCP IP list of hz2.

If we want to handle this case automatically, IDK what can we do. https://github.com/hazelcast/hazelcast/pull/21418 may cause concurrent merge, which I'm not sure of its consequences.

**Comment by kwart** [comment]
@ramizdundar I'm trying an alternative solution in #22021 - it adds (temporarily) possible master addresses to  `TcpIpJoiner.knownMemberAddresses` Map. I'll work on improvements and tests next week.
