### ISSUE TITLE
For some types of exceptions the exception cloning process lose the root cause (ExceptionUtil#cloneExceptionWithFixedAsyncStackTrace) [HZ-1243]

### ISSUE THREAD

**Issue by pchondzinski** [hazelcast/hazelcast#20357]
**Bug description**
Method `com.hazelcast.internal.util.ExceptionUtil#cloneExceptionWithFixedAsyncStackTrace` can return not only

> _a cloned exception with the current stacktrace is added on top of the original exceptions stack-trace the cloned exception has the same cause and the message as the original exception_

but also a `null` value (the calling side should be aware of that). And in case of `null` value the calling side should apply appropriate procedures so that the root cause is not lost during exception wrapping. Otherwise the requestor won't have a chance to find out the cause of the encountered issue.
In my case `cloneExceptionWithFixedAsyncStackTrace` method returns `null` for the exception of `org.eclipse.persistence.exceptions.DatabaseException` type.

**Expected behavior**
Correct approach is applied in following methods in `com.hazelcast.spi.impl.AbstractInvocationFuture` class:
```java
    private static RuntimeException wrapRuntimeException(RuntimeException cause) {
        if (cause instanceof WrappableException) {
            return ((WrappableException) cause).wrap();
        }
        RuntimeException wrapped = cloneExceptionWithFixedAsyncStackTrace(cause);
        return wrapped == null ? new HazelcastException(cause) : wrapped;
    }

    private static Error wrapError(Error cause) {
        Error result = cloneExceptionWithFixedAsyncStackTrace(cause);
        return result == null ? cause : result;
    }
```

Where the original exception is taken into consideration when the cloning method returns `null`.

I would expect similar approach as in `wrapRuntimeException` and `wrapError` methods also in following method in `com.hazelcast.spi.impl.operationservice.impl.InvocationFuture` class:

```java
    public static <T> T returnOrThrowWithGetConventions(Object response) throws ExecutionException, InterruptedException {
        if (!(response instanceof ExceptionalResult)) {
            return (T) response;
        }
        response = ((ExceptionalResult) response).getCause();
        if (response instanceof WrappableException) {
            response = ((WrappableException) response).wrap();
        } else if (response instanceof RuntimeException || response instanceof Error) {
            response = cloneExceptionWithFixedAsyncStackTrace((Throwable) response); // here is the cloning procedure that may return null
            // expected behaviour would be as follows:
            // var cloned = cloneExceptionWithFixedAsyncStackTrace((Throwable) response);
            // response = cloned == null ? response : cloned;
        }
        if (response instanceof CancellationException) {
            throw (CancellationException) response;
        } else if (response instanceof ExecutionException) {
            throw (ExecutionException) response;
        } else if (response instanceof InterruptedException) {
            throw (InterruptedException) response;
        } else {
            throw new ExecutionException((Throwable) response); // and thanks to above fixes null value won't become a root cause for the wrapped exception 
        }
    }
```

**Additional context**

Hazelcast version: 5.0

**Comment by mmedenjak** [comment]
Thank you for the report @pchondzinski ! @sancar can you take a look? Is this something that should and can go into 5.1?
