### ISSUE TITLE
De-couple Extractable from the Hazelcast artifacts

### ISSUE THREAD

**Issue by robinroos** [hazelcast/hazelcast#20369]
I maintain DTO classes which live inside Hazelast IMaps but which also have use outside the cluster.  

To benefit frmo Projections it is necessary to implement a Hazelcast interface (Extractable) which references a Hazelcast runtime exception (QueryException).

Could those two classes be pit into an "api" maven artifact which does not change much and which does not introduce any other Hazelcast dependencies?

**Comment by mmedenjak** [comment]
As mentioned in the other issue, SQL is supposed to supersede all of Predicate API, so I don't expect any investment in this area. If there is a use case not supported by the SQL API, please say so.
