### ISSUE TITLE
Admin API to distinguish SQL jobs and to see the underlying query [HZ-1232]

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20372]
This information will be very useful to see in MC. Also user will be able to more easily identify what's the job doing.

We need to consider access rights to this: should any client see it? Any client can already see the list of jobs and their DAG, so maybe yes.

We also should add information if the job is batch or streaming.

**Comment by krzysztofslusarski** [comment]
https://github.com/hazelcast/hazelcast/pull/20502
