### ISSUE TITLE
Reorder HOP function arguments

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20370]
Currently, the arguments of HOP function are: 
- input table
- timestamp column
- hop size
- window size

This is equal to Flink HOP functions. I propose to swap the last two arguments. Reasons:
- first 3 arguments will be equal to TUMBLE
- it's more natural to say "use window of size 10, sliding by 2", compared to "use window sliding by 2, with size of 10"
- Flink authors in [their own paper](https://arxiv.org/abs/1905.12133) use reverse order
- it's not standardized anyway

**Comment by Fly-Style** [comment]
I don't have a strong opinion here. 
If we want to be somehow 'compatible' with Flink - I'd stay with current syntax.
From another hand, the proposed syntax really feels more ... usual.

**Comment by viliam-durina** [comment]
We're not compatible anyway, flink doesn't know IMPOSE_ORDER function which we require...

**Comment by Fly-Style** [comment]
Okay, working on reorder.

**Comment by Fly-Style** [comment]
Ready :)
