### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [hazelcast/hazelcast#20393]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by kwart** [comment]
Thank you for bringing it to our attention, Jamie. The file is now in the repository.

**Comment by JamieSlome** [comment]
@kwart - great, appreciate the response!

You should receive an e-mail shortly, otherwise, you can view the report directly here:

https://huntr.dev/bounties/d63972a2-b910-480a-a86b-d1f75d24d563/
