### ISSUE TITLE
Throw an exception from `DynamicConfigurationAwareConfig#addWanReplicationConfig`

### ISSUE THREAD

**Issue by frant-hartm** [hazelcast/hazelcast#20437]
The method currently silently accepts the config, but the config is not applied. We will fix in #19979.

But for 5.1 (and backport to 5.0 and possibly 4.2) It should throw an exception that we don't support it.

**Comment by Holmistr** [comment]
Is this behavior something new? Could this be fixed consistently in other configs later? 

Asking to understand whether it needs to be in 5.1 scope.

**Comment by ramizdundar** [comment]
> Is this behavior something new?

No

> Could this be fixed consistently in other configs later?

Yes

But also note that not throwing exceptions for unsupported APIs would create more confusions in 5.1 because of dynamic configuration persistence. More people will try to use these APIs now.

**Comment by vbekiaris** [comment]
For 5.1 we agreed to only fix `ClientDynamicClusterConfig#addWanReplicationConfig` and `DynamicConfigurationAwareConfig#addWanReplicationConfig` to throw `UnsupportedOperationException`. 

related broader issue: #10812

**Comment by vbekiaris** [comment]
fixed by #20576
