### ISSUE TITLE
Map get/set latency spikes when adding or removing instances in hazelcast cluster

### ISSUE THREAD

**Issue by vladykin** [hazelcast/hazelcast#20431]
**Describe the bug**
We see huge spikes of Hazelcast operation latency when Hazelcast instances join or leave the cluster.
Operations used are the simplest `IMap.getAsync()` and `IMap.setAsync()`. Normally most of them take less than a millisecond, 99-th percentile is about 2-3 millis, absolute maximum is about 50 millis. 

When a Hazelcast member joins or leaves the cluster, the 99-th percentile jumps to several seconds, absolute maximum can reach dozens of seconds. Seen even 40+ second latency once. However 90-th percentile and below are not affected and stay below 1 millisecond.

This is an example how the spikes look in Grafana:
![hz_spikes](https://user-images.githubusercontent.com/6962285/150243277-f9716090-4379-44b0-a30c-75f18085d844.png)

All Hazelcast members and their clients are deployed in an AWS EKS cluster.
Hazelcast members are added/removed with `kubectl scale statefulset.apps/hazelcast --replicas=N`

**Expected behavior**
I'd expect some increase of latency during adding/removing members due to data repartitioning. However the numbers we see (dozens of seconds) are too large.

**To Reproduce**

1. Deploy Hazelcast to EKS using this yaml: https://github.com/vladykin/hazelcast-load-generator/blob/main/src/main/scripts/hazelcast.yaml
2. Deploy [this load generator](https://github.com/vladykin/hazelcast-load-generator) to the same cluster ([k8s yaml example](https://github.com/vladykin/hazelcast-load-generator/blob/main/src/main/scripts/hazelcast.yaml) is provided)
3. Observe the latency measured by the load generator on its `/metrics` endpoint on port 8080 (scrape it with Prometheus for viewing in Grafana, or just retrieve plain data with curl)
4. Periodically add or remove Hazelcast members using `kubectl scale statefulset.apps/hazelcast --replicas=N` and see how the latency jumps

**Additional context**

The number of Hazelcast members in our experiments was between 1 and 5. Each with a 24 GB heap.

Hazelcast client and member version used is 4.2. Tried upgrading to 5.0.2, but didn't see any improvement --- the spikes are still there.

Don't see anything suspicious in Hazelcast logs.

**Comment by ahmetmircik** [comment]
Hi @vladykin, any GC log?
Did you try to increase partition count to make per-partition data smaller or 
setting `hazelcast.partition.max.parallel.migrations` to a smaller value (it is `10` by default)?

**Comment by vladykin** [comment]
Hi @ahmetmircik 

I can collect a GC log for you. Will `-XX:+PrintGCDetails` be sufficient, or should I add any extra flags?

Haven't played with partitioning parameters yet. The size of the map we have in Hazelcast floats between 10 GB and 100 GB. With 271 partitions, and assuming equal size or the partitions, that's up to 370 MB per partition. Is there a recommended size of the partition I should be targeting? Can I see the actual sizes of the partitions somewhere in Hazelcast logs to check for significant imbalance?

**Comment by vladykin** [comment]
Hi @ahmetmircik,

Meanwhile I've tried increasing partition count and decreasing parallel migrations.
Among the several combinations I tested, the `hazelcast.partition.max.parallel.migrations=2` and `hazelcast.partition.count=2711` showed the best results and helped a lot! The worst latencies are now around 1 second (compared to dozens of seconds before).

Are there any other related properties that could further reduce the latency during repartitioning?

P.S. I guess collecting GC log is no longer relevant.

**Comment by ahmetmircik** [comment]
Happy to see it is better now. Regarding recommended max per-partition size, try to keep it under 200MB. Small partitions are migrated faster.

GC logs might be useful for future reference. It is up to you to share GC logs or closing this issue.
