### ISSUE TITLE
Non-indefinitely blocking Iterator.hasNext()

### ISSUE THREAD

**Issue by promanenko** [hazelcast/hazelcast#20448]
Currently `Iterator.hasNext()` may block indefinitely for a streaming query.
For Management Center SQL streaming support it would be very useful to have `hasNext()` with a timeout or an asynchronous API to subscribe to.

**Comment by Fly-Style** [comment]
I believe, we may close it. (https://github.com/hazelcast/hazelcast/pull/20454)
