### ISSUE TITLE
Add permission for accessing SQL metadata for jobs

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#20545]
The `Job.getJobConfig()` gives access to some security-sensitive information, namely the SQL query text and the query arguments. These can contain sensitive data. Access to these should be protected by a permission.

**Comment by kwart** [comment]
IMO, The READ action in JobPermission is sufficient as long as users are aware of the consequences. We should make it explicit in the documentation.
Something like
* when you run SQL, it's backed by a Jet job;
* if security is enabled, clients with the job read permission granted can see the SQL.

Could we also add a test to verify, the permission is really mandatory? (if we don't have one already)
