### ISSUE TITLE
Is log4j1 really a dependency?

### ISSUE THREAD

**Issue by FireBurn** [hazelcast/hazelcast#20673]
I've been working on a merge request to replace the log4j1 dependency with reload4j which is a fork of the original project (https://reload4j.qos.ch/) maintained by the original author 

Though I'm not convinced log4j1 is actually used anywhere, and it isn't bundled in either the full tgz or the slim tgz

Is it actually required? Or can I instead submit something to remove the references to it?

**Comment by ufukyilmaz** [comment]
Hi,
See the related discussion about this dependency: https://github.com/hazelcast/hazelcast/issues/20330#issuecomment-1007287698

**Comment by FireBurn** [comment]
Thanks
