### ISSUE TITLE
Losing a node under load seems to kill the cluster?

### ISSUE THREAD

**Issue by alpsendil** [hazelcast/hazelcast#207]
Our Hazelcast cluster (v1.9.3) has on more than one occasion failed when a single node died, while the system is under load.

I don't have logs from the failed node, but the other two nodes of a 3 node cluster show the third member failing, and appearing to recover, but ultimately all members are rendered unresponsive.  The cluster had to be shut down completely before it could be restored.

The log entries below show that node "5" was unable to ping node "7".  Connection to "7" is lost at (11:20:34 PM).   Then "7" returned to the cluster, and it looks like two connections are accepted from "7". 

The logs show a connection is lost (at 11:22:58 PM), even though the ClusterManager claims all three members of the cluster to be present.

This is followed by the two previously good nodes (5 and 6) indicating that they are not able to reach 7.  All nodes are then unresponsive, and we were forced to shut everything down and restart.

Any thoughts on what might cause this or how we might avoid it in the future?  Thanks very much for your help!

Alp

Here's an excerpt from our logs:
Jun 20, 2012 11:20:28 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Address[10.1.1.5:5701] will ping Address[10.1.1.7:5701]
Jun 20, 2012 11:20:33 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Address[10.1.1.5:5701] couldn't ping Address[10.1.1.7:5701]
Jun 20, 2012 11:20:33 PM com.hazelcast.cluster.ClusterManager
INFO: [prod] Removing Address Address[10.1.1.7:5701]
Jun 20, 2012 11:20:33 PM com.hazelcast.cluster.ClusterManager
INFO: [prod] 

Members [2] {
    Member [10.1.1.5:5701] this
    Member [10.1.1.6:5701]
}

Jun 20, 2012 11:20:34 PM com.hazelcast.nio.Connection
FINE: [prod] Connection lost /10.1.1.7:57856
Jun 20, 2012 11:20:34 PM com.hazelcast.nio.ReadHandler
WARNING: [prod] hz.1.InThread Closing socket to endpoint Address[10.1.1.7:5701], Cause:java.io.EOFException
Jun 20, 2012 11:20:34 PM com.hazelcast.cluster.ClusterManager
INFO: [prod] Removing Address Address[10.1.1.7:5701]
Jun 20, 2012 11:22:11 PM com.hazelcast.nio.InSelector
INFO: [prod] 5701 is accepting socket connection from /10.1.1.7:57897
Jun 20, 2012 11:22:11 PM com.hazelcast.nio.InSelector
INFO: [prod] 5701 is accepted socket connection from /10.1.1.7:57897
Jun 20, 2012 11:22:58 PM com.hazelcast.nio.InSelector
INFO: [prod] 5701 is accepting socket connection from /10.1.1.7:36101
Jun 20, 2012 11:22:58 PM com.hazelcast.nio.InSelector
INFO: [prod] 5701 is accepted socket connection from /10.1.1.7:36101
Jun 20, 2012 11:22:58 PM com.hazelcast.nio.Connection
FINE: [prod] Connection lost /10.1.1.7:57897
Jun 20, 2012 11:22:58 PM com.hazelcast.nio.ReadHandler
WARNING: [prod] hz.1.InThread Closing socket to endpoint Address[10.1.1.7:5701], Cause:java.io.EOFException
Jun 20, 2012 11:22:58 PM com.hazelcast.cluster.ClusterManager
INFO: [prod] Removing Address Address[10.1.1.7:5701]
Jun 20, 2012 11:23:04 PM com.hazelcast.cluster.ClusterManager
INFO: [prod] 

Members [3] {
    Member [10.1.1.5:5701] this
    Member [10.1.1.6:5701]
    Member [10.1.1.7:5701]
}

Jun 20, 2012 11:23:09 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.6:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:23:14 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.6:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:23:19 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.6:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:34 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.5:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:34 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.5:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:35 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.6:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:39 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.5:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:39 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.5:5701] this has no connection to Address[10.1.1.7:5701]
Jun 20, 2012 11:24:40 PM com.hazelcast.cluster.ClusterManager
WARNING: [prod] Member [10.1.1.6:5701] this has no connection to Address[10.1.1.7:5701]
.
.
.
.

**Comment by ejain** [comment]
I'm seeing the same problem with the current version, 3.4.1, see http://stackoverflow.com/questions/28866777/hazelcast-cluster-failing-after-a-single-node-becomes-unresponsive.

**Comment by nezoat** [comment]
I'm also seeing the exact same issue.  One node under load, invokes a graceful hazelcast shutdown, and the whole cluster becomes unresponsive for sometimes up to three minutes.  When under little load, a node can shutdown cleanly, or sometimes cluster unresponsive period of a few seconds.
