### ISSUE TITLE
Change plan created for index scan with orderby

### ISSUE THREAD

**Issue by krzysztofslusarski** [hazelcast/hazelcast#20713]
For a query like: 
```java
        String sql = "SELECT * FROM  \n" + mapName +
                " WHERE field1 >= 100\n" +
                " AND field1 <= 10000 \n" +
                " ORDER BY field2 ASC LIMIT 20 OFFSET 0";
```

With indices on ```field1``` and ```field2```, the plan created is:
```
SortPhysicalRel(sort0=[$2], dir0=[ASC], offset=[0:TINYINT(0)], fetch=[20:TINYINT(5)], requiresSort=[false])
  IndexScanMapPhysicalRel(table=[[hazelcast, o_4af25e9a_d8e1_40f6_9579_8eb2342c66d5[projects=[0, 1, 2]]]], index=[f2_index], indexExp=[null], remainderExp=[SEARCH($1, Sarg[[100..10000]])])
```

But no sort is necessary, used index is already sort.

**Comment by Fly-Style** [comment]
@krzysztofslusarski `FETCH` and `OFFSET` keywords are the part of `ORDER BY` clause and with current implementation we can't avoid `Sort` rel to be used.

**Comment by Fly-Style** [comment]
To be honest, I don't like the way we are using `fetch` & `offset` in `CreateDagVisitor#onRoot`. 
Maybe, the idea to split `SortLogicalRel` onto two physical rels, like `FetchOffsetPhysicalRel` + `SortPhysicalRel` may have sense...
