### ISSUE TITLE
Hazelcast clients taking long time to get data during node failures

### ISSUE THREAD

**Issue by maheshpvd** [hazelcast/hazelcast#20889]
Hi, I have a question regarding the issue that i'm facing with hazelcast v4.2 during a node failure. During this node failure the client that is trying to fetch data from cache taking long time to get data 20 seconds to 60 seconds. Is this the case during node failure, if yes, can you explain the process that it undergoes in this case. Is there any fix/solution to overcome this case to avoid in future releases. Thanks in advance.

**Comment by vbekiaris** [comment]
closing as this is also being discussed in community slack https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1646390129853909
