### ISSUE TITLE
Export jdk.management/com.ibm.lang.management.internal only for OpenJ9 [HZ-1302]

### ISSUE THREAD

**Issue by ldziedziul** [hazelcast/hazelcast#20908]
Add `--add-exports jdk.management/com.ibm.lang.management.internal` only when OpenJ9 detected.

Otherwise we got `WARNING: package com.ibm.lang.management.internal not in jdk.management` in logs

**Comment by Holmistr** [comment]
Moving to 5.2 Backlog because the warning log line is on every startup. We should make sure that we don't scare the users unnecessarily.

**Comment by ldziedziul** [comment]
> Can I get this ticket issue assigned?

Sure, done
