### ISSUE TITLE
Slack invitation token expired

### ISSUE THREAD

**Issue by jsoref** [hazelcast/hazelcast#20948]
https://github.com/hazelcast/hazelcast/blob/fb720d9e7f4b7643c31fdb61e9b83b6ca8ecc552/.github/ISSUE_TEMPLATE/config.yml#L10-L11

https://slack.hazelcast.com/
<img width="674" alt="image" src="https://user-images.githubusercontent.com/2119212/157913251-10918ae2-1b5b-4a4b-8dce-762976e5ed12.png">

**Comment by jerrinot** [comment]
hi @jsoref,
thanks for reporting this. We are fixing this. In the meantime you can use this link as a workaround: https://join.slack.com/t/hazelcastcommunity/shared_invite/zt-15cklyshx-IcbQVR33YEI182K4RrqkWQ

**Comment by jerrinot** [comment]
fixed. thanks to @vbekiaris and @kwart for help!
