### ISSUE TITLE
org.springframework.expression.Expression as basic type converter is needed

### ISSUE THREAD

**Issue by LaoTsing** [hazelcast/hazelcast#21019]
**Please describe the problem you are trying to solve**
SpelExpression is a most populare type and a lot using as column type in database tables. Spel the most versatile way for a wide range of tasks.

**Please describe the desired behavior**
It would be very convenient if the Expression type was supported as a basic type converter and also registered with:  converters.add(ExpressionConverter.INSTANCE);

**Describe alternatives you've considered**
I did not find a way to add a new basic converter type to Hazelcast.

**Comment by LaoTsing** [comment]
Hello @Holmistr , i found solution with ObjectMapper serialization: 

https://github.com/SevenParadigms/kubernetes-embedded-hazelcast/blob/main/src/main/java/org/sevenparadigms/cache/hazelcast/AnySerializable.java

Both serialize and deserialize operation work in 1000000 times per 1 second

**Comment by Holmistr** [comment]
Awesome @LaoTsing , thanks a lot for letting us know. Glad that you found a good solution.

Just CCing @Serdaro @JakeSCahill as an idea (feel free to ignore it) - perhaps we could add this somewhere in the documentation/guide. Somewhere so it wouldn't get lost as someone has already figured it out :-)

Closing the ticket :-)
