### ISSUE TITLE
Can map-backup become a dynamic feature？

### ISSUE THREAD

**Issue by wubumihuo** [hazelcast/hazelcast#21026]
We use Hazelcast 4.2 and our cluster has 3 Hazelcast nodes, each map has 1 backup, which means each data has one backup on other node. 

We assume each node's Xmx (max JVM heap memory) is 10 Gb. When each node's used heap is 7G (beyond 2/3 of Xmx), then nodeA is shutdown,  nodeB and nodeC become the only two node in the cluster. And nodeB/C would repartition and each node will have the other backup, then the memory will beyond 10G and cluster will shutdown.

So can you give me a feature if one node shuts down in the cluster, the backup will not make effect? This will make our cluster more High availability?

**Comment by Holmistr** [comment]
Hi @wubumihuo , thanks for reporting the issue.

The problem that you're describing is the classic capacity planning problem. Unfortunately, it will always be the case.You're saying `This will make our cluster more High availability`. But this is not actually true. Imagine that you have more (e.g. 2) backups, one member goes down, you ignore repartitioning of the first one (to save memory) but then another one fails and you lost your data. That goes against high availability.

Unfortunately, in this case it would be a dirty workaround going against the AP nature of HZ. The proper solution is to count with the worst case scenario and plan the memory accordingly. 

I'm going to close this question now but feel free to follow up and discuss.
