### ISSUE TITLE
 WARN  c.h.client.impl.connection.ClientConnectionManager - 56 - hz.client_3 [dev] [4.2.2] Could not connect to member 76049df3-04ee-4a85-875f-abcadsfds, reason com.hazelcast.core.HazelcastException: java.io.IOException: null to address /XX.XX.X.XX:5703 

### ISSUE THREAD

**Issue by bugbugmaker** [hazelcast/hazelcast#21095]
WARN  c.h.client.impl.connection.ClientConnectionManager - 56 - hz.client_3 [dev] [4.2.2] Could not connect to member 76049df3-04ee-4a85-875f-abcadsfds, reason com.hazelcast.core.HazelcastException: java.io.IOException: null to address /XX.XX.X.XX:5703。
What caused it

**Comment by vbekiaris** [comment]
duplicate of #21096
