### ISSUE TITLE
Feature Request: JDBC Sink for SQL

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#21109]
Hello there ;-)

I'd like to use Hazelcast for stream processing via SQL and write the results into a database accessible via a JDBC driver. Hazelcast SQL is powerful enough for my stream processing needs, just the sink part is missing. 

This is the idea: Kafka -> Hazelcast -> Database.

**Comment by jerrinot** [comment]
👋 👀 😭 🤷

**Comment by TomaszGaweda** [comment]
>Hello there ;-)
General Jaromir! ;)

One note for future implementers: would be good to have good transaction support here; TBH I felt that it's missing too when I was still using Hazelcast as customer :)

**Comment by frant-hartm** [comment]
This was delivered as beta in #21877.
