### ISSUE TITLE
Hazelcast 5.1.1 bundles outdated org.json:json:20201115

### ISSUE THREAD

**Issue by wfhartford** [hazelcast/hazelcast#21302]
The latest versions of Hazelcast shade the org.json:json:20201115 library, which is outdated and has a known bug described at https://github.com/stleary/JSON-java/issues/654 

Could a future version of Hazelcast upgrade this dependency to the latest version? At the moment, the latest version is  20220320.

**Comment by TomaszGaweda** [comment]
Fixed by PR #21122
