### ISSUE TITLE
Maps stays empty after a put operation with the maximum max-idle-seconds value [HZ-1170]

### ISSUE THREAD

**Issue by idogal** [hazelcast/hazelcast#21330]
After upgrading from 3.12 to 5.1, the same implementation of an `IMap` wrapper stopped working. It seems like when using the `Integer.MAX_VALUE` (2147483647) value for the map's `max-idle-seconds` configuration parameter, the map stays empty after a `put` operation. It works fine with a value of 0, with a value such as 214748364, but _not_ with a value of 2147483646.

The _TTL_ value does not seem to matter (change that), the _near-cache_ configuration does not seem to matter, the _eviction policy_ does not seem to matter.

**Expected behavior**
Map should be filled up with values after a `put` operation if configured with the maximal value that is allowed according to the documentation.

**To Reproduce**
Our implementation is very mature and complex, but possibly having a similar XML configuration.

**Additional context**

- Unfortunately I did not see anything in the logs that indicate an issue.
- Hazelcast 5.1.1 but it also reproduced over 4.2.4.
- Varying cluster size, from 1 to 3.
- Only members, no clients.
- AdoptOpenJDK 11 
- Kubernetes over CentOS

**Comment by ahmetmircik** [comment]
Hi @idogal, thanks for reporting this, this is a bug, for now set it to zero instead, setting it to `Integer.MAX_VALUE` doesn't work as documented.
