### ISSUE TITLE
[TCP/IP Join] member listening 5701, why try to send message to local IP:5702, 5703?

### ISSUE THREAD

**Issue by swxEmily** [hazelcast/hazelcast#21405]
hazelcast version：5.0.3

As the log, each member IP listening at 5701 port, why it send message to 5702, 5703 in the same IP:10.33.27.181? System knows self node listening port.

In our production ENV, some time it send successfully which cause splitbrain. and in this case, member removing event is not notified.
![image](https://user-images.githubusercontent.com/43984746/167977479-f5827e8f-bbff-4ed6-866c-befca1162137.png)

2022-05-12 09:50:27.373 [hz.loving_hodgkin.cached.thread-5] DEBUG c.h.internal.cluster.impl.MembershipManager:63 - [10.33.27.181]:5701 [deception-ws-hazelcast] [5.0.3] Sending member list to the non-master nodes: \n\nMembers {size:2, ver:2} [\n	Member [10.33.27.181]:5701 - 54d8cfd2-d97a-4049-a12e-702205bc7f73 this\n	Member [10.33.27.158]:5701 - e1aac370-79eb-42aa-b9d6-163336bc125a\n]\n 

	Line 3551: 2022-05-12 09:47:32.412 [hz.loving_hodgkin.cached.thread-4] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - [10.33.27.181]:5701 [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to [10.33.27.158]:5702 
	Line 3555: 2022-05-12 09:47:37.453 [hz.loving_hodgkin.cached.thread-4] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - **[10.33.27.181]:5701** [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to **[10.33.27.181]:5702** 
	Line 3559: 2022-05-12 09:47:42.496 [hz.loving_hodgkin.cached.thread-4] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - **[10.33.27.181]:5701** [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to **[10.33.27.181]:5703** 
	Line 3595: 2022-05-12 09:49:27.374 [hz.loving_hodgkin.cached.thread-6] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - [10.33.27.181]:5701 [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to [10.33.27.158]:5703 
	Line 3601: 2022-05-12 09:49:32.417 [hz.loving_hodgkin.cached.thread-6] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - [10.33.27.181]:5701 [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to [10.33.27.158]:5702 
	Line 3605: 2022-05-12 09:49:37.460 [hz.loving_hodgkin.cached.thread-6] DEBUG com.hazelcast.internal.cluster.impl.TcpIpJoiner:63 - [10.33.27.181]:5701 [deception-ws-hazelcast] [5.0.3] Sending SplitBrainJoinMessage to [10.33.27.181]:5702

  hazelcast.xml：
`<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.hazelcast.com/schema/config
           http://www.hazelcast.com/schema/config/hazelcast-config-5.0.xsd">
    <cluster-name>deception-ws-hazelcast</cluster-name>

    <properties>
        <property name="hazelcast.logging.type">slf4j</property>
    </properties>

    <network>
        <port auto-increment="true">5701</port>
        <interfaces enabled="false"></interfaces>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
        <join>
            <auto-detection enabled="false" />
            <multicast enabled="false"></multicast>
            <tcp-ip enabled="true">
                <members>10.33.27.181,10.33.27.158</members>
            </tcp-ip>
            <aws enabled="false"></aws>
            <gcp enabled="false"></gcp>
            <azure enabled="false"></azure>
            <kubernetes enabled="false"></kubernetes>
            <eureka enabled="false">
                <self-registration>true</self-registration>
                <namespace>hazelcast</namespace>
            </eureka>
            <discovery-strategies></discovery-strategies>
        </join>
        <ssl enabled="false" />
        <failure-detector>
            <icmp enabled="false" />
        </failure-detector>
    </network>
    <partition-group enabled="false" />
    <executor-service name="default">
        
        <queue-capacity>0</queue-capacity>
        <pool-size>16</pool-size>
        <statistics-enabled>true</statistics-enabled>
    </executor-service>
    <durable-executor-service name="default">
        <capacity>100</capacity>
        <durability>1</durability>
        <pool-size>16</pool-size>
        <statistics-enabled>true</statistics-enabled>
    </durable-executor-service>
    <scheduled-executor-service name="default">
        <capacity>100</capacity>
        <durability>1</durability>
        <pool-size>16</pool-size>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
        <statistics-enabled>true</statistics-enabled>
    </scheduled-executor-service>
    <security>
        <client-block-unmapped-actions>true</client-block-unmapped-actions>
    </security>
    <queue name="default">
        <max-size>0</max-size>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <empty-queue-ttl>-1</empty-queue-ttl>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </queue>
    <map name="default">
        <in-memory-format>BINARY</in-memory-format>
        <metadata-policy>CREATE_ON_UPDATE</metadata-policy>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <time-to-live-seconds>0</time-to-live-seconds>
        <max-idle-seconds>0</max-idle-seconds>
        <eviction eviction-policy="NONE" max-size-policy="PER_NODE" size="0" />
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
        <cache-deserialized-values>INDEX-ONLY</cache-deserialized-values>
        <statistics-enabled>true</statistics-enabled>
        <per-entry-stats-enabled>false</per-entry-stats-enabled>

    </map>

    <multimap name="default">
        <backup-count>1</backup-count>
        <value-collection-type>SET</value-collection-type>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </multimap>

    <replicatedmap name="default">
        <in-memory-format>OBJECT</in-memory-format>
        <async-fillup>true</async-fillup>
        <statistics-enabled>true</statistics-enabled>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </replicatedmap>

    <list name="default">
        <backup-count>1</backup-count>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </list>

    <set name="default">
        <backup-count>1</backup-count>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </set>

    <reliable-topic name="default">
        <read-batch-size>10</read-batch-size>
        <topic-overload-policy>ERROR</topic-overload-policy>
        <statistics-enabled>true</statistics-enabled>
    </reliable-topic>

    <ringbuffer name="default">
        <capacity>10000</capacity>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <time-to-live-seconds>0</time-to-live-seconds>
        <in-memory-format>BINARY</in-memory-format>
        <merge-policy batch-size="100">com.hazelcast.spi.merge.PutIfAbsentMergePolicy</merge-policy>
    </ringbuffer>

    <flake-id-generator name="default">
        <prefetch-count>100</prefetch-count>
        <prefetch-validity-millis>600000</prefetch-validity-millis>
        <epoch-start>1514764800000</epoch-start>
        <node-id-offset>0</node-id-offset>
        <bits-sequence>6</bits-sequence>
        <bits-node-id>16</bits-node-id>
        <allowed-future-millis>15000</allowed-future-millis>
        <statistics-enabled>true</statistics-enabled>
    </flake-id-generator>
    <serialization>
        <portable-version>0</portable-version>
    </serialization>

    <lite-member enabled="false" />

    <cardinality-estimator name="default">
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <merge-policy batch-size="100">HyperLogLogMergePolicy</merge-policy>
    </cardinality-estimator>

    <crdt-replication>
        <replication-period-millis>1000</replication-period-millis>
        <max-concurrent-replication-targets>1</max-concurrent-replication-targets>
    </crdt-replication>

    <pn-counter name="default">
        <replica-count>2147483647</replica-count>
        <statistics-enabled>true</statistics-enabled>
    </pn-counter>

    <cp-subsystem>
        <cp-member-count>0</cp-member-count>
        <group-size>0</group-size>
        <session-time-to-live-seconds>300</session-time-to-live-seconds>
        <session-heartbeat-interval-seconds>5</session-heartbeat-interval-seconds>
        <missing-cp-member-auto-removal-seconds>14400</missing-cp-member-auto-removal-seconds>
        <fail-on-indeterminate-operation-state>false</fail-on-indeterminate-operation-state>
        <raft-algorithm>
            <leader-election-timeout-in-millis>2000</leader-election-timeout-in-millis>
            <leader-heartbeat-period-in-millis>5000</leader-heartbeat-period-in-millis>
            <max-missed-leader-heartbeat-count>5</max-missed-leader-heartbeat-count>
            <append-request-max-entry-count>100</append-request-max-entry-count>
            <commit-index-advance-count-to-snapshot>10000</commit-index-advance-count-to-snapshot>
            <uncommitted-entry-count-to-reject-new-appends>100</uncommitted-entry-count-to-reject-new-appends>
            <append-request-backoff-timeout-in-millis>100</append-request-backoff-timeout-in-millis>
        </raft-algorithm>
    </cp-subsystem>

    <metrics enabled="true">
        <management-center enabled="true">
            <retention-seconds>5</retention-seconds>
        </management-center>
        <jmx enabled="true" />
        <collection-frequency-seconds>5</collection-frequency-seconds>
    </metrics>

    <instance-tracking enabled="false">

    </instance-tracking>

    <sql>
        <statement-timeout-millis>0</statement-timeout-millis>
    </sql>

    <jet enabled="false" resource-upload-enabled="false">
        <flow-control-period>100</flow-control-period>
        <backup-count>1</backup-count>
        <scale-up-delay-millis>10000</scale-up-delay-millis>
        <lossless-restart-enabled>false</lossless-restart-enabled>
        <max-processor-accumulated-records>9223372036854775807</max-processor-accumulated-records>
        <edge-defaults>
            <queue-size>1024</queue-size>
            <packet-size-limit>16384</packet-size-limit>
            <receive-window-multiplier>3</receive-window-multiplier>
        </edge-defaults>
    </jet>
</hazelcast>
`

**Comment by vbekiaris** [comment]
hi @swxEmily , the behaviour you notice is due to "port auto-increment". When it is enabled:
- if the Hazelcast server finds the port (default 5701) is occupied, it will automatically try to bind to the next (5702, ...)
- similarly, when searching for cluster to join, unless an explicit port number is specified on the addresses in the member list, it will try a sequence of ports.
- 
When you disable it, the periodic split-brain detection mechanism will stop sending messages to ports other than the one defined in your config.

```
<network>
    <port auto-increment="false">5701</port>
...
```

Unless you expect to have more than one members on the same machine (which is anyway not recommended for production), port auto-increment should be turned off.

**Comment by swxEmily** [comment]
ok, I think Document may add usage tips for auto-increment=true
