### ISSUE TITLE
type convert based on SQL features

### ISSUE THREAD

**Issue by tc792617871** [hazelcast/hazelcast#21433]
how can support this : com.hazelcast.sql.HazelcastSqlException: Failed to extract map entry value field "xxx" because of type mismatch [expectedClass=java.lang.Integer, actualClass=java.lang.Long]

**Comment by ivanthescientist** [comment]
Hi @tc792617871, could you please provide more info about when this error occurs, specifically: 

1. The full `CREATE MAPPING` command you're executing. 
2. (If possible) the source code (can be just list of getters and/or fields with their respective data types) of the underlying class that is used for the MAPPING. Or alternatively at least how this field `xxx` is declared in the class and its Getter and Setter.

**Comment by viliam-durina** [comment]
I guess your mapping contained `INT` type, but your actual value class had a `long` field. If you think you've received the error incorrectly, please reopen this issue and provide more information, or, ideally, a reproducer.
