### ISSUE TITLE
Unable to assign service-name and service-port for kubernetes configuration using environment variable in xml [HZ-1226]

### ISSUE THREAD

**Issue by pp185235** [hazelcast/hazelcast#21585]
I have mentioned following in xml,
`<hz:kubernetes enabled="true" service-name="${SERVICE_NAME:myapp}" and service-port="${SERVICE_PORT:5701}" />`

so instead of taking value of variable the whole string is getting assigned as value to service-name 
eg. consider SERVICE_NAME = mynewapp 
so expected is service-name=mynewapp
but actual happening is` service-name=${SERVICE_NAME:myapp}`

similarly for service-port

XML Schema :

```
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context" xmlns:hz="http://www.hazelcast.com/schema/spring" 
    xsi:schemaLocation="http://www.springframework.org/schema/beans 
                http://www.springframework.org/schema/beans/spring-beans.xsd 
                http://www.springframework.org/schema/context 
                http://www.springframework.org/schema/context/spring-context.xsd
                http://www.hazelcast.com/schema/spring 
                http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd 
                http://www.hazelcast.com/schema/config/hazelcast-config.xsd">
```

**Comment by pp185235** [comment]
`<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context" xmlns:hz="http://www.hazelcast.com/schema/spring" 
    xsi:schemaLocation="http://www.springframework.org/schema/beans 
                http://www.springframework.org/schema/beans/spring-beans.xsd 
                http://www.springframework.org/schema/context 
                http://www.springframework.org/schema/context/spring-context.xsd
                http://www.hazelcast.com/schema/spring 
                http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd 
                http://www.hazelcast.com/schema/config/hazelcast-config.xsd">`

**Comment by pp185235** [comment]
I don't have access to view https://hazelcast.atlassian.net//browse/HZ-1226

**Comment by ldziedziul** [comment]
@pp185235 yes, It's just a reflection of this issue in our internal issue tracker.

**Comment by pp185235** [comment]
So this jira is raised to resolve the issue or to reproduce the issue ?

**Comment by pp185235** [comment]
Well thanks for the solution, but this is using the code, and I need to configure it using XML. Can you please help me with that approach.
Thanks

**Comment by pp185235** [comment]
> Hi @pp185235, it's just an analysis of how to fix it, we'll deal with it soon-ish.

Okay..Thanks
