### ISSUE TITLE
SQL storage doesn't replicate data to new member [HZ-1252]

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#21632]
```java
        HazelcastInstance inst = createHazelcastInstance();
        createMapping(inst, "m", Integer.class, Integer.class);
        HazelcastInstance inst2 = createHazelcastInstance();
        inst2.getSql().execute("select * from m");
```
Fails with:
```
Object 'm' not found, did you forget to CREATE MAPPING?
```
As per investigation by @krzysztofslusarski, the cause is that we create the `ReplicatedMapProxy` too early in the member initialization while there's only 1 member in the cluster. Later during the initialization, the member joins the cluster, but since the proxy is already initialized, it doesn't fetch data from other members. The map is synchronized later thanks to anti-entropy, which runs in 30 seconds intervals.

The fix might be to not obtain the proxy until first needed, which should be after the member is initialized. Another fix might be to fix the proxy that it will fetch the data when the member later joins the cluster.

**Comment by pveentjer** [comment]
Another option would be to increase the sync rate so that reconciliation happens earlier. E.g. every second.
