### ISSUE TITLE
Cache performance improvements [HZ-2821]

### ISSUE THREAD

**Issue by ben-manes** [hazelcast/hazelcast#21676]
In order to understand the algorithms and implementation better, I ran a low-level [benchmarks](https://github.com/ben-manes/caffeine/commit/ff58dbe0be8eb6ff6ea8c5eb237e38d472f74eab) against the on heap cache. I used [NearCacheObjectRecordStore](https://github.com/hazelcast/hazelcast/blob/8763a4a6a6059f7e87836286b283e3066ee5c06d/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/NearCacheObjectRecordStore.java) directly because a cluster configuration does not evict promptly and grows unbounded. I believe Hazelcast uses a periodic timer to delay eviction, so while perhaps reasonable in production workloads it is confusing for micro-benchmarks. These results don't invalidate that design, but I hope they offer some insights for improvements.

This [concurrent benchmark](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/GetPutBenchmark.java) measures the reads and writes throughput by using a 100% hit rate and a Zipfian access distribution. This shows the hit penalty and identifies contention hotspots due to the hot/cold request pattern. I observed 22k-28k ops per second on a 4 core macbook using 8 threads. When looking at the implementation, I suspect that this is due to [NearCacheStatsImpl](https://github.com/hazelcast/hazelcast/blob/8763a4a6a6059f7e87836286b283e3066ee5c06d/hazelcast/src/main/java/com/hazelcast/internal/monitor/impl/NearCacheStatsImpl.java#L52-L55) thrashing on the atomic hit / miss counters. This causes a CAS storm as all threads retry updates to the same field, whereas if you used a `LongAdder` the increments would be on per-cpu fields that are summed lazily on read.

The eviction policy's hit rate is as one would expect for a sampled lru / lfu / random policy. The sampling is concurrency friendly, but as shown the other implementation details negate that benefit. Those policies are simple and good in many workfloads, but also very poor in others (e.g. a near 0% hit rate for an analytical loop). A more modern policy, like W-TinyLFU, adapts to maintain a near optimal hit rate across a wider range of workloads.

The other test that I performed was single-threaded rate of eviction. In some caches this can degrade very poorly to low hundreds or less per second. This ranged from 115k - 430k ops/s, whereas low millions per second is a nice goal. Since Hazelcast doesn't actually perform evictions on writes and batches it up periodically, this seems to likely be good enough.

My recommendation is to try `LongAdder` for stats and see if the read throughput can be made competitive. It might also be nice if the local cache used a more advanced policy, but that might be too invasive given the design and you would likely need to swap out the underlying [SampleableConcurrentHashMap](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/util/SampleableConcurrentHashMap.java) (e.g. with Caffeine).

**Comment by ben-manes** [comment]
I realized that I went a little too low-level and [switched](https://github.com/ben-manes/caffeine/commit/fee2dfde2aad426c5f93aaeb36ec4b6d41178b05) to [DefaultNearCache](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/DefaultNearCache.java) which does the eviction immediately (the periodic timer is for expiration only). The observations are otherwise

**Comment by pveentjer** [comment]
@ben-manes could you try to disable the statistics and see the performance impact? Then you have an upper bound on the potential performance gain.

**Comment by ben-manes** [comment]
@pveentjer I can’t without forking the code. It’s hardcoded to an implementation that is always enabled.

https://github.com/hazelcast/hazelcast/blob/14ef0dbefa4a6fa00a50a8873aeea02ec6c3f5e4/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java#L75

**Comment by pveentjer** [comment]
Just comment out the increment methods bodies.

**Comment by ben-manes** [comment]
right, I was only taking a cursory look and had not planned on forking the code to dig in. I can try as time permits, but was just for fun and reporting my observations.

**Comment by pveentjer** [comment]
There are many more shared counters we should get rid of. We are working on next-generation architecture for Hazelcast and to goal is to limit contention (Amdahl's Law) and coherence penalties (Universal Scalability Law) as much as possible since they will limit the speedup.

**Comment by ben-manes** [comment]
That’s great. I spent a lot of time on minimizing cache misses as that dominated costs after achieving linear scaling for read concurrency. A local miss leads to I/O which is milliseconds plus, which leads to higher loading the infrastructure and therefore increases the capacity costs. An improvement to the hit rate has a direct TCO savings. The next step is latency-aware eviction, but that is still in its research phase. Are you planning on revisiting the core caching algorithms?

**Comment by pveentjer** [comment]
A lot of things need to be revised including the IMap and how cache-invalidation works.

**Comment by ben-manes** [comment]
We’ll then feel welcome to borrow liberally from Caffeine. It has a number of tricks that should be at least fun to consider against whatever you end up deciding to do.

**Comment by ben-manes** [comment]
@pveentjer I built a local jar and tried disabling the stats and the per-entry [hit counter](https://github.com/hazelcast/hazelcast/blob/2ccc16db0918b2c0759ec6159800f213e691cc1a/hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/record/AbstractNearCacheRecord.java#L44-L45). Unfortunately the performance did not improve. The zipfian distribution makes hot entries and something, either shared or per entry, is severely throttling your throughput. CLHM (2010) and Caffeine (2015) both reach 100M+ reads/s, and scale linearly with the hardware while maintaining good hit rates. Obviously it might not matter given other system costs (e.g. network i/o), but it does seem like an unnecessary performance limiter. I won't dig in further, but someone on your team might find it fun to figure out.
