### ISSUE TITLE
Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

### ISSUE THREAD

**Issue by 1ssqq1lxr** [hazelcast/hazelcast#21797]
**Describe the bug**
hazelcast 4.2.2 使用一个节点部署集群，运行一段时候后报错如下：Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

**Expected behavior**

**To Reproduce**

3. ...

**Additional context**

**Comment by AyberkSorgun** [comment]
Closing as duplicate
