### ISSUE TITLE
DynamicConfig AddMapConfig MapStoreConfiguration's Properties field is not nullable [HZ-1373]

### ISSUE THREAD

**Issue by mtyazici** [hazelcast/hazelcast#21799]
**Describe the bug**
I generated the codecs for the [DynamicConfig.addMapConfig](https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/DynamicConfig.yaml#L699-L887=) using the Go codec generator in [hazelcast-client-protocol](https://github.com/hazelcast/hazelcast-client-protocol). In the method inputs MapStoreConfig.properties is defined to be nullable. However, when I try to give null values to them, Hazelcast member returns an error. like the following:

The problem is quite similar to https://github.com/hazelcast/hazelcast/issues/21182. I think the tests should be written for all nullable fields to see if there is discrepancy between the protocol definition and implementation.

```
2022-07-18T15:28:22.765Z	ERROR	controllers.Map	Failed with member	{"error": "got exception from server:
java.lang.NullPointerException: \n \n java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:1087)
java.util.Properties.putAll(Properties.java:1350)\n com.hazelcast.client.impl.protocol.util.PropertiesUtil.fromMap(PropertiesUtil.java:31)
 com.hazelcast.client.impl.protocol.task.dynamicconfig.MapStoreConfigHolder.asMapStoreConfig(MapStoreConfigHolder.java:152)
com.hazelcast.client.impl.protocol.task.dynamicconfig.AddMapConfigMessageTask.getConfig(AddMapConfigMessageTask.java:76)
com.hazelcast.client.impl.protocol.task.dynamicconfig.AbstractAddConfigMessageTask.processMessage(AbstractAddConfigMessageTask.java:71)
com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:153)
com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:116)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n java.lang.Thread.run(Thread.java:829)
com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102): "}
```

**Expected behavior**
`properties` field of the `MapStoreConfig` should be nullable

**To Reproduce**

1. Generate codec for the `DynamicConfig.addMapConfig` method in Go client and use the internal client exposed in https://github.com/hazelcast/hazelcast-go-client/pull/754.
2. Send the request to a Hazelcast member with the mentioned fields.

**Additional context**

**Comment by ldziedziul** [comment]
Setting `properties` to `null` is supported, see https://github.com/hazelcast/hazelcast/blob/48110903f26a591949c8b18ca9bec49d31d28199/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/dynamicconfig/MapStoreConfigHolder.java#L166-L168

From the error message you've sent, it seems that the problem is that you use a `null` value as a key or value inside `properties` object which is not allowed. 

Could you double-check that?
