### ISSUE TITLE
Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

### ISSUE THREAD

**Issue by 1ssqq1lxr** [hazelcast/hazelcast#21798]
**Describe the bug**
Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

**Expected behavior**

**To Reproduce**

3. ...

**Additional context**

**Comment by AyberkSorgun** [comment]
Closing as duplicate
