### ISSUE TITLE
[Discuss] Why not put jet in a separate module

### ISSUE THREAD

**Issue by EricJoy2048** [hazelcast/hazelcast#21805]
I only want to use hazelcast and based on the ability of distributed memory management and cluster management provided by hazelcase, we develop our own distributed computing engine.

I found that in the new version, the code of jet is directly put into hazelcast module. Why don't we put hazelcast jet into a module alone. The design of hazelcast is excellent, especially those who want to implement their own computing engine based on hazelcast will be happy to use hazelcast to simplify their work. Hazelcast jet is not necessary for them. On the contrary, the introduction of jet will lead to two sets of computing engines in their own engines.

Thank you.

**Comment by viliam-durina** [comment]
It was a product decision to have only one distribution package. As a part of that we disabled initialization of some Jet parts, unless Jet is actually used, so the overhead, if its features aren't used, is minimal.

**Comment by EricJoy2048** [comment]
> It was a product decision to have only one distribution package. As a part of that we disabled initialization of some Jet parts, unless Jet is actually used, so the overhead, if its features aren't used, is minimal.

Thank you very much.
