### ISSUE TITLE
When the cluster runs a node, after running for a period of time, the data node programming Lite members occasionally appear

### ISSUE THREAD

**Issue by 1ssqq1lxr** [hazelcast/hazelcast#21804]
**Describe the bug**
4.2.2 version Target of invocation cannot be found! Partition owner is null but partitions can't be assigned since all nodes in the cluster are lite members.

-->

**Comment by vbekiaris** [comment]
@1ssqq1lxr the exception is self-explanatory: all your members are lite members, so no member can be assigned as owner or replica of any partitions, therefore partition assignment cannot proceed and you cannot use partitioned data structures on a cluster of lite-only members. You need some non-lite members in the cluster to own data for your partitioned data structures.
I will now close this issue. If you have any additional information or a reason to think you hit a defect, feel free to reopen and provide your hazelcast configuration and steps to reproduce.

**Comment by 1ssqq1lxr** [comment]
WARNING: [127.0.0.1]:5701 [base_old] [4.2.5] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.metrics.managementcenter.ReadMetricsOperation{serviceName='hz:impl:metricsService', identityHash=1479810253, partitionId=-1, replicaIndex=0, callId=-1682996, invocationTime=1659811293705 (2022-08-07 02:41:33.705), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1659811293705, firstInvocationTime='2022-08-07 02:41:33.705', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 08:00:00.000', target=[127.0.0.1]:5701, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:5701 - 361c4d32-1267-479f-a45a-3511f0a9dcaa this has left cluster!}, offered value: com.hazelcast.internal.metrics.managementcenter.ConcurrentArrayRingbuffer$RingbufferSlice@56f3f9bb
java.lang.Exception
        at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219)

**Comment by 1ssqq1lxr** [comment]
"network": {
      "tcpIp": {
        "members": [
          "127.0.0.1"
        ]
      },
      "trustedIps":["192.168.8.57"]
    },
