### ISSUE TITLE
Row count is exactly 4 times higher from S3 than original row count in the file [HZ-1405]

### ISSUE THREAD

**Issue by macsir** [hazelcast/hazelcast#21854]
**Describe the bug**
Row count is exactly 4 times higher when using in SQL file connector to read from S3 than original row count in the file

**Expected behavior**
Row count should always same for the same file.

**To Reproduce**

1. Upload a ~2.7 mil rows csv file into S3 bucket.
2. Create a file mapping locally to connect to the file in S3
3. Select row count from the mapping

**Additional context**
SQL to use
```
CREATE MAPPING ustest
TYPE File
OPTIONS (
    'path' = 's3a://my-bucket/',
    'sharedFileSystem' = 'true',
    'format' = 'csv',
    'glob' = 'ustest.csv',
    'fs.s3a.endpoint' = 's3.region.amazonaws.com',
    'fs.s3a.access.key' = 'abc',
    'fs.s3a.secret.key' = 'efg'
);
```
![Screenshot 2022-07-27 195245](https://user-images.githubusercontent.com/3345149/181220438-c2aa49ee-676d-45e3-9fa3-ff62edfeb638.jpg)
![Screenshot 2022-07-27 195221](https://user-images.githubusercontent.com/3345149/181220451-be061a8c-8079-477b-80e8-787cf934fd8b.jpg)

**Comment by macsir** [comment]
Create a IMAP mapping with same structure and sink into it. It looks like the row count is right.
![image](https://user-images.githubusercontent.com/3345149/181220979-a1b566ee-c1a8-4b71-a689-a8fe618e6e7e.png)

**Comment by frant-hartm** [comment]
@macsir version?

**Comment by macsir** [comment]
Latest one 5.1.2

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by macsir** [comment]
Hi, @frant-hartm Thanks for looking into it. Here is the file I am using in S3.
[us_simplified2 (1).zip](https://github.com/hazelcast/hazelcast/files/9249490/us_simplified2.1.zip)
.

**Comment by frant-hartm** [comment]
@macsir I can confirm this is reproducible with the given file. We will look into it.

Thank you for taking time to report this.

**Comment by frant-hartm** [comment]
As a temporary workaround you can increase the minimum split size to a value larger than your maximum file size, e.g. for 1 GB add the following to your mapping:

'mapreduce.input.fileinputformat.split.minsize'='1073741824'

**Comment by macsir** [comment]
Thanks and will give it go later.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by macsir** [comment]
Thanks for working on this!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
