### ISSUE TITLE
WebFilter using deferred-write: value always null (Version 3.2)

### ISSUE THREAD

**Issue by dfex55** [hazelcast/hazelcast#2187]
Issue opened as proposed by Chris in the Google group (https://groups.google.com/d/msg/hazelcast/gnQQ_aNo2wc/Um3YkYEKCsQJ) 

When upgrading from 3.1 to 3.2 the default behavior of the WebFilter changes. To get the old behavior one has to set

```
<init-param>
    <param-name>deferred-write</param-name>
    <param-value>true</param-value>
</init-param>
```

in the web.xml. deferred-write is the new name for cache-locally which was true by default and is now false by default.

But when using this configuration, the WebFilter has a major bug.

The following works as expected:

```
session.setAttribute("key", "value");
System.out.println(session.getAttribute("key"));
```

But if you try to read the key/value before it was set in the session (e.g. to test if it is in the session), the value will never be written to the map:

```
Object value = session.getAttribute("key");
session.setAttribute("key", "value");
System.out.println(session.getAttribute("key"));
```

The output is always null.

Disabling deferred-write works around the problem, but may introduce performance issues.

Full WebFilter configuration below:

```
<filter>
  <filter-name>hazelcast-filter</filter-name>
  <filter-class>com.hazelcast.web.WebFilter</filter-class>
  <init-param>
    <param-name>map-name</param-name>
    <param-value>app-sessions</param-value>
  </init-param>
  <init-param>
    <param-name>sticky-session</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>
    <param-name>cookie-name</param-name>
    <param-value>hazelcast.session</param-value>
  </init-param>
  <init-param>
    <param-name>cookie-domain</param-name>
    <param-value>appdomain.com</param-value>
  </init-param>
  <init-param>
    <param-name>cookie-secure</param-name>
    <param-value>false</param-value>
  </init-param>
  <init-param>
    <param-name>cookie-http-only</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>
    <param-name>debug</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>
    <param-name>config-location</param-name>
    <param-value>/WEB-INF/hazelcast.xml</param-value>
  </init-param>
  <init-param>
    <param-name>use-client</param-name>
    <param-value>false</param-value>
  </init-param>
  <init-param>
    <param-name>shutdown-on-destroy</param-name>
    <param-value>true</param-value>
  </init-param>
  <init-param>
    <param-name>deferred-write</param-name>
    <param-value>true</param-value>
  </init-param>
</filter>
```

**Comment by dfex55** [comment]
@mesutcelik Can you confirm the related tests for this issue are failing in 3.5 with deferred write?

quick check:
- deferred write true
- new session, key "test" not in session
1. session.setAttribute("test", "value")
2. session.getAttribute("test") -> returns null

quick guess:
In HazelcastHttpSession.setAttribute a new LocalCacheEntry is created if key is not in localCache. The used constructor sets the entry's isReload to true. The HazelcastHttpSession.getAttribute reads the LocalCacheEntry and checks isReload (which is true) and fetches the non existing entry from the distributed map -> null will be returned (always).

Please reopen this issue. Or should I create a new issue?

btw: in total 17 webfilter tests are failing for me

**Comment by mesutcelik** [comment]
can you please create a new issue with sticky attribute value?
