### ISSUE TITLE
Error configuring hazelcast with DSL style "IMap eviction config doesn't support max size policy `ENTRY_COUNT`"

### ISSUE THREAD

**Issue by erwinetchart** [hazelcast/hazelcast#21913]
**Describe the bug**
When i configure a eviction in a map (please see shared code) , once the map is getting used the app throws error (see exception below)

**Expected behavior**
I expect to get the map

**To Reproduce**

1. Setup a map with the eviction LRU or LFU or NONE.
2. Use by the map
3. Error is thrown
4. The app is in clustered but for this case is just a single instance.

**Additional context**

-The application is a spring boot app.
-I'm using spring-hazelcast dependency  that aims to use 5.1 version of hazelcast core.
-I tried updating to 5.1.2 , same behavior. 
-Spring boot version is 2.6.8

      Config config = new XmlConfigBuilder().build();
      config.setClusterName("cluster-name");
      config
            .setInstanceName(instanceName)
            .addMapConfig(new MapConfig()
                  .setBackupCount(1)
                  .setName("example-map")
                  .setEvictionConfig(new EvictionConfig().setEvictionPolicy(LFU))
                  .setMapStoreConfig(new MapStoreConfig()
                        .setInitialLoadMode(EAGER)
                        .setWriteBatchSize(500)
                        .setWriteCoalescing(true)
                        .setEnabled(true)
                        .setFactoryImplementation(mapStoreConfig)
                        .setWriteDelaySeconds(5)));

Logs:
`com.hazelcast.config.InvalidConfigurationException: IMap eviction config doesn't support max size policy `ENTRY_COUNT`. Please select a valid one: [PER_NODE, PER_PARTITION, USED_HEAP_PERCENTAGE, USED_HEAP_SIZE, FREE_HEAP_PERCENTAGE, FREE_HEAP_SIZE, USED_NATIVE_MEMORY_SIZE, USED_NATIVE_MEMORY_PERCENTAGE, FREE_NATIVE_MEMORY_SIZE, FREE_NATIVE_MEMORY_PERCENTAGE].
	at com.hazelcast.internal.config.ConfigValidator.checkMapMaxSizePolicyConfig(ConfigValidator.java:199)
	at com.hazelcast.internal.config.ConfigValidator.checkMapEvictionConfig(ConfigValidator.java:177)`

**Comment by ahmetmircik** [comment]
Hi @erwinetchart, 
This the expected exception, since default max-size-policy in [EvictionConfig](https://github.com/hazelcast/hazelcast/blob/84d0749c90bc844a29f912dc10a3f5777db767a9/hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java#L45) is `ENTRY_COUNT` and it is not a supported policy by `IMap`. Maybe you can use `PER_NODE` max-size-policy instead, it is the closest one.

**Comment by erwinetchart** [comment]
Thanks for clarify @ahmetmircik , i will close the issue.
