### ISSUE TITLE
SQL Browser shows empty data

### ISSUE THREAD

**Issue by Nikhil2508** [hazelcast/hazelcast#21928]
**Describe the bug**
Using hazelcast management centres sql browser for browsing IMAP data. It works perfectly on local. But on production, it is always showing as empty data even when there's data available in MAP. Please help.

**Expected behavior**
Data should be visible on query execution

**Additional context**
Hazelcast version 5.1.2
Hazelcast MC version 5.1.1

**Comment by neilstevenson** [comment]
See https://hazelcastcommunity.slack.com/archives/C01BHE8JN76/p1659954774904289

**Comment by AyberkSorgun** [comment]
Closing as it's discussed in community Slack and added a toast meaningful message for such problems in MC 5.2
