### ISSUE TITLE
SQL - IS NULL condition is ignored if there is another condition for the same column [HZ-1474]

### ISSUE THREAD

**Issue by Leuteris** [hazelcast/hazelcast#21954]
**Describe the bug**

The `IS NULL` condition is ignored if there is another condition for the **same** column.

For example, the following query does not return the rows with `NULL` department.
```sql
SELECT * FROM event_v1 WHERE (department = '62ea652ac920b123fe9c44fb' OR department IS NULL) ORDER BY eventTimestamp DESC LIMIT 30 OFFSET 0
```

The followings queries work as expected:
```sql
SELECT * FROM event_v1 WHERE (department IS NULL) ORDER BY eventTimestamp DESC LIMIT 30 OFFSET 0
```
```sql
SELECT * FROM event_v1 WHERE (department = '62ea652ac920b123fe9c44fb' OR opportunity IS NULL)) ORDER BY eventTimestamp DESC LIMIT 30 OFFSET 0
```
Queries were performed using `com.hazelcast.sql.SqlService`.

**Expected behavior**
The following query should return all rows with `NULL` or '62ea652ac920b123fe9c44fb'  department:
```sql
SELECT * FROM event_v1 WHERE (department = '62ea652ac920b123fe9c44fb' OR department IS NULL) ORDER BY eventTimestamp DESC LIMIT 30 OFFSET 0
```

**Additional context**

Hazelcast Version: 5.1.2

**Comment by viliam-durina** [comment]
Seems that we didn't update to three-valued logic for SEARCH operator when upgrading to calcite 1.27. We need to add that.
