### ISSUE TITLE
tstore member kill test:  store.hybridlog.impl.HybridLogSlotAllocator.tryAllocate(I)   Jvm crash [HZ-1425]

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#22019]
[danny@server16 tiered]$ pwd
/home/danny/workspace/tiered

in a member kill test, i see remaining members crash, during partition migration with

# Problematic frame:
# J 8405 C2 com.hazelcast.internal.tstore.hybridlog.impl.HybridLogSlotAllocator.tryAllocate(I)J (612 bytes) @ 0x00007f8ece0b895e [0x00007f8ece0b8820+0x13e]
downloading results to /nfs/danny/tstore-18aug

  [11:49 AM](https://hazelcast.slack.com/archives/C01PD4KN9FB/p1660819771141609)
during controlled member shutdown i see the same member side crash on the remaining members

  [12:04 PM](https://hazelcast.slack.com/archives/C01PD4KN9FB/p1660820695312339)
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 8616 C2 com.hazelcast.internal.tstore.hybridlog.impl.HybridLogSlotAllocator.tryAllocate(I)J (612 bytes) @ 0x00007f5d01900c86 [0x00007f5d01900ae0+0x1a6]
J 8658 C2 com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl.tryAllocate(J)J (228 bytes) @ 0x00007f5d022b8d3c [0x00007f5d022b8ce0+0x5c]
J 7424 C2 com.hazelcast.internal.tstore.hybridlog.impl.HybridLogImpl.allocate(J)J (170 bytes) @ 0x00007f5d0203bd1c [0x00007f5d0203bce0+0x3c]
J 7221 C2 com.hazelcast.internal.hidensity.impl.TieredStoreRecordProcessor.newPreparedRecord(I)Lcom/hazelcast/map/impl/record/TieredStoreRecord; (55 bytes) @ 0x00007f5d01d561a0 [0x00007f5d01d56000+0x1a0]
J 9465 C2 com.hazelcast.map.impl.recordstore.EnterpriseTieredRecordStore.putOrUpdateReplicatedRecord(Lcom/hazelcast/internal/serialization/Data;Lcom/hazelcast/map/impl/record/Record;Lcom/hazelcast/map/impl/recordstore/expiry/ExpiryMetadat
a;ZJ)Lcom/hazelcast/map/impl/record/Record; (226 bytes) @ 0x00007f5d02750688 [0x00007f5d02750360+0x328]
J 9573 C2 com.hazelcast.map.impl.operation.MapChunk.putOrUpdateReplicatedData(Lcom/hazelcast/map/impl/recordstore/RecordStore;)V (135 bytes) @ 0x00007f5d027fd35c [0x00007f5d027fcfa0+0x3bc]
j  com.hazelcast.map.impl.operation.MapChunk.putInto(Lcom/hazelcast/map/impl/recordstore/RecordStore;)V+17
j  com.hazelcast.map.impl.operation.MapChunk.run()V+84
J 6717 C2 com.hazelcast.spi.impl.operationservice.Operation.call()Lcom/hazelcast/spi/impl/operationservice/CallStatus; (46 bytes) @ 0x00007f5d01b6dc28 [0x00007f5d01b6db40+0xe8]
J 9653 C2 com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(Lcom/hazelcast/spi/impl/operationservice/Operation;)V (40 bytes) @ 0x00007f5d01f4daa8 [0x00007f5d01f4da20+0x88]
j  com.hazelcast.internal.partition.operation.MigrationOperation.runMigrationOperation(Lcom/hazelcast/spi/impl/operationservice/Operation;)V+6

looks like members crash during migrations

**Comment by petrpleshachkov** [comment]
We made many related fixes and most likely fixed this one. @Danny-Hazelcast I close it for now and reopen it if you see it in 5.3/master
