### ISSUE TITLE
Indexing arbitrary object paths

### ISSUE THREAD

**Issue by krokicki** [hazelcast/hazelcast#2202]
I'd like to propose that indexing be expanded to allow for indexing on arbitrary object paths starting from the object stored in the IMap (or any distributed data structure). For example, if I have this object:

class Entity {
  Long id;
  String name;
  Date creationDate;
  User owner;
  Map<String,String> properties;
}

I'd like to be able to create indexes on owner.name, properties.key, and properties.value, and use them to find matching Entity objects in the map.

This is similar in concept to MongoDB's dot notation indexing: http://docs.mongodb.org/manual/core/index-single/#indexes-on-subdocuments

It's also similar to Cassandra's recent addition of support for secondary indexing of collection columns: https://issues.apache.org/jira/browse/CASSANDRA-4511

This kind of feature would be hugely helpful in leveraging the Hazelcast IMDG as a fast online query system. Custom predicates are not fast enough when you scale to millions of objects per node, and breaking down complex objects into multiple indexable maps has many downsides.

**Comment by wimdeblauwe** [comment]
Is this not already possible in 3.5 ? The code in `ReflectionHelper` contains code to split the given attribute on a point (`.`).

**Comment by gurbuzali** [comment]
Yes this is already possible
