### ISSUE TITLE
License issue [HZ-1435]

### ISSUE THREAD

**Issue by ChristianOberleitner** [hazelcast/hazelcast#22104]
Hazelcast is licensed under Apache2. However the file com/hazelcast/org/json/XML.java contains code that is inspired by Stackoverflow (as mentioned in the file itself). Code taken or inspired by stackoverflow automatically runs under CC-BY-SA 4.0 which is a strong copyleft license and conflicts with Apache2 in many aspects

**Comment by frant-hartm** [comment]
Hi @ChristianOberleitner,

thank you for pointing this out. 

First of all the class in question comes from `org.json:json` library, so it would be best to report it upstream - https://github.com/stleary/JSON-java/ 

However, that doesn't mean we can just ignore it.

The [SO post](https://stackoverflow.com/a/21791059/951609) in question refers to [another page](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=5003547) with the same code snippet, so it is not clear if the post author had rights to actually post the snippet. So the `CC-BY-SA 4.0` likely doesn't apply. The copyright ownership and the license is unknown from our point of view.

When we look at the code snippet
https://github.com/stleary/JSON-java/blob/c0a1d5f741154948e9201e99876bb4bb131110b5/src/main/java/org/json/XML.java#L90-L117

```
    private static Iterable<Integer> codePointIterator(final String string) {
        return new Iterable<Integer>() {
            @Override
            public Iterator<Integer> iterator() {
                return new Iterator<Integer>() {
                    private int nextIndex = 0;
                    private int length = string.length();

                    @Override
                    public boolean hasNext() {
                        return this.nextIndex < this.length;
                    }

                    @Override
                    public Integer next() {
                        int result = string.codePointAt(this.nextIndex);
                        this.nextIndex += Character.charCount(result);
                        return result;
                    }

                    @Override
                    public void remove() {
                        throw new UnsupportedOperationException();
                    }
                };
            }
        };
    }
```

- we see it is not identical to the SO code
- most of the lines are just Java syntax sugar for implementing the `Iterable<Integer>` interface:
```
public Iterable<Integer> genericFunctionReturningIterable() {
        return new Iterable<Integer>() {
            @Override
            public Iterator<Integer> iterator() {
                return new Iterator<Integer>() {

                    @Override
                    public boolean hasNext() {

                    }

                    @Override
                    public Integer next() {

                    }

                    @Override
                    public void remove() {

                    }
                };
            }
        };
    }
```
- so this leaves us with less than 10 lines of real code, which would be very similar/identical if a clean room implementation of the idea was done.

For the above reasons we don't consider this a violation of a license or copyright.
