### ISSUE TITLE
Predicates.sql(...) should support parameters 

### ISSUE THREAD

**Issue by uklance** [hazelcast/hazelcast#22162]
When I use [SqlService.execute(...)](https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/sql/SqlService.html#execute-java.lang.String-java.lang.Object...-) I can have parameters in my query
```java
int age = 30;
String name = "foo";
SqlService sqlService = hazelcastInstance.getSql();
try (SqlResult result = sqlService.execute("select * from Employee where name = ? AND age > ?", name, age)) {
   ...
}
```

But when I use [Predicates.sql(...)](https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/query/Predicates.html#sql-java.lang.String-) I'm forced to use string concatenation when passing parameters which is a security risk (sql injection attack)
```java
int age = 30;
String name = "foo";
IMap<Long, Employee> employeeMap = hazelcastInstance.getMap("Employee");
Predicate<Long, Employee> predicate = Predicates.sql("name = '" + name + "' AND age > " + age);
Collection<Employee> matches = employeeMap.values(predicate);
```

I would like a new method added to [Predicates](https://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/query/Predicates.html) which takes arguments
```java
public static <K,V> Predicate<K,V> sql(String expression, Object... arguments)
```

Then I could use parameters in sql predicates
```java
Predicate<Long, Employee> predicate = Predicates.sql("name = ? AND age > ?", name, age);
```

As a workaround I can use the more verbose predicates API but I'd prefer the more readable/succinct sql
```java
Predicate<Long, Employee> predicate = Predicates.and(new Predicate[] {
   Predicates.equals("name", name),
   Predicates.greaterThan("age", age),
};
```

**Comment by vbekiaris** [comment]
Hi @uklance , please use the SQL service, the Predicate API will be deprecated in favour of our more modern and robust SQL engine (`getSqlService()`). In this context, I don't think enhancing the predicate API makes much sense. 
See also https://hazelcast.com/blog/performance-tuning-of-the-hazelcast-sql-engine/

**Comment by uklance** [comment]
Hi @vbekiaris the `SqlService` and `SqlResult` are lacking the ability to get back the full object. In order to get the full object I need to do 2 hits to hazelcast.

eg:
```
int age = 30;
String name = "foo";
SqlService sqlService = hazelcastInstance.getSql();
IMap<Long, Employee> employeeMap = hazelcastInstance.getMap("Employee");
try (SqlResult result = sqlService.execute("select __key from Employee where name = ? AND age > ?", name, age)) {
   Set<Long> keys = new HashSet<Long>();
   result.iterator().forEach(row -> keys.add(row.getObject(0));
   Collection<Employee> employees = employeeMap.getAll(keys).values();
}
```

**Comment by mdumandag** [comment]
@uklance I think you can use `this` to get the full value with a query string like
```
select this from Employee where name = ? AND age > ?
```

**Comment by uklance** [comment]
@mdumandag thanks for the info, I think `this` can do what I want. I'm guessing code would look like:

```
int age = 30;
String name = "foo";
SqlService sqlService = hazelcastInstance.getSql();
try (SqlResult result = sqlService.execute("select this from Employee where name = ? AND age > ?", name, age)) {
   List<Employee> employees = new ArrayList<>();
   result.iterator().forEach(row -> keys.add(row.getObject(0));
}
```
