### ISSUE TITLE
Thundering herd hazelcast with cache annotations

### ISSUE THREAD

**Issue by rvanderboom** [hazelcast/hazelcast#22222]
Hey, we notice some time that if our site is attacked on same cache objects that are marked for invalidated in our near cache (so have to be retrieved from server), we run into a thundering herd issue..
We see that a GET on same object (same cache and sam key) result in at least 100 same calls to our backend and at that time even our database is in the high alert.

We expect no thundering herd since, it thought hazelcast will server old objects from the near cache, and only 1 request will populate the cache with new value ?

So we have 3 hazelcast services and several clients with near cache. 
Since we have NGINX with sticky session, we also see that in the same few milliseconds most requests goes to the same pod. So the pod has issues, as well as the backend database to retrieve the new cache value..

we use hazelcast 5 and java 17, but also with java 4.2 and java 8 this was the case.

Can we change something to influence this behaviour apart from specifying "sync" on our ehcache notations  ?

**Comment by rvanderboom** [comment]
ps: why is there so little documentation about how to avoid thundering herd since its such a crucial thing on high load websites.  Don't see the configuration choices, alternatives or even people talking about this issue.

**Comment by ahmetmircik** [comment]
Hi @rvanderboom, this seems a good improvement candidate.

Thundering herd can happen for a key between the time window that near-cache-population-starts and near-cache-population-ends. Because there is no blocking happens at client side for other requests during this population period. Other requests for the same key can hit server in that time-window. 

But, what i don't get from the issue description is, on the server side, there should be no change for the number of database hits, since loading happens only 1 time per key, rest of the requests for the same key see that loaded data. This is independent of the any thundering-heard-guard. 

Are you sure database hit happens multiple times for the same key?

**Comment by rvanderboom** [comment]
hey,


mm ok i didn’t know the server can be hit multiple times, i read someweren old stale data is returned, meaning only 1 request populates the near cache.

but yes we see also the database hit many times for same key.
but isn’t that because server is hit multiple times and the all try via database to load server cache at same time ?

we do set an read limit because otherwise the hazelcast GC goes crazy and this throws operationexception timeouts.. Or was this a bad idea ?
________________________________

FD Media Groep
Rob van der Boom
Software Developer
Prins Bernhardplein 173, 1097 BL Amsterdam
Postbus 216, 1000 AE Amsterdam
***@***.***
www.fdmediagroep.nl
This message may contain
confidential (business) information and / or information which falls under the
protection of journalistic sources and should be treated as such. If you are
not the addressee of this message, please destroy this message without taking
note of the content and do not use, copy and/or distribute this message and its
content to others.



Van: Ahmet Mircik ***@***.***>
Verzonden: woensdag 14 september 2022 14:59
Aan: hazelcast/hazelcast ***@***.***>
CC: Rob van der Boom ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [hazelcast/hazelcast] Thundering herd hazelcast with cache annotations (Issue #22222)


Hi @rvanderboom<https://github.com/rvanderboom>, this seems a good improvement candidate.

Thundering herd can happen for a key between the time window that near-cache-population-starts and near-cache-population-ends. Because there is no blocking happens at client side for other requests during this population period. Other requests for the same key can hit server in that time-window.

But, what i don't get from the issue description is, on the server side, there should be no change for the number of database hits, since loading happens only 1 time per key, rest of the requests for the same key see that loaded data. This is independent of the any thundering-heard-guard.

Are you sure database hit happens multiple times for the same key?

**Comment by vbekiaris** [comment]
Even if several `get`s are executed concurrently for the same hot key, all are executed by the same partition thread on the Hazelcast member. So if there is a cache miss on the first `get`, assuming you have a `MapLoader` configured the value will be loaded from your database and subsequent `get`s should read the value that is already loaded in memory. So you should only see a single hit to your backing database even if you execute 1000's of concurrent `get`s for that same hot key.

**Comment by rvanderboom** [comment]
THanks, we don't think its a key that doesn't exist, but maybe its somehow caused by our strict readTimeout (operationtimeout) settings, that causes cache not be filled and doing repeated calls ..

We put it to infinite now and see if problem is solved

**Comment by jszap** [comment]
After way too much thought, I've concluded this is much ado about nothing. The concept of tracking client APIs map get(key) operations "misses" in deliberate or inadvertent DOS attacks should mainly be the a responsibility addressed at the client API level(or above), and therefore the Hz cluster should have zero or very little involvement. So, I suggest a rate limiting mechanism in the architecture. Alternatively, a solution where the services handle their own rate limiting using a entryProcessor or a Hazelcast pipeline job to aggregate a tracked "miss" counter store in a Hz iMap. The service use a map listener with a predicate to be notified when to enforce configured thresholds(note, if these thresholds are in an Hz imap they can be dynamically adjusted). This makes sense for DOS attacks with or without nonexistent keys being requested from a Hazelcast backed service API.

**Comment by rvanderboom** [comment]
issue indeed not an issue with correct settings.,
closed it
