### ISSUE TITLE
Near Cache Invalidated Issue

### ISSUE THREAD

**Issue by Nikhil2508** [hazelcast/hazelcast#22233]
**Please describe the problem you are trying to solve**
We have noticed that, when an entry processor is called, it will by default, invalidate the near cache for the key it is called for. Initially we were doing this via the offloadable entry processor. But on trying this out with a read only entry processor, still the near cache invalidation event is fired. This reduces the overall near cache effectiveness in events when we have not updated the entry at all.
...

**Please describe the desired behavior**
Ideally we should not invalidate cache atleast for the read only entry processor. 
...

**Describe alternatives you've considered**
As an alternative we have to now get the entry using map.get instead of readonly hazelcast.
...

Would love to take up the PR and contribute if required.

**Comment by ahmetmircik** [comment]
Hi @Nikhil2508, thanks for the suggestion, it seems to make sense.
I have added this to 5.3 milestone, let's see what we can do.

BTW we are open to PRs, if you want to work on this issue and send a PR for it.

**Comment by Nikhil2508** [comment]
Hey @ahmetmircik sure will raise a PR for same.
