### ISSUE TITLE
Incorrect results with SQL stream-to-stream join [HZ-1499]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22320]
**Describe the bug**
When following [this guide](https://docs.hazelcast.com/tutorials/join-two-streams#context) I do not get the expected results (or any results) from the stream-to-stream join query in the example. This is only when I change the HZ image in the provided `docker-compose.yml` from `image: hazelcast/hazelcast:5.2-BETA-1` to `image: hazelcast/hazelcast:latest-snapshot`. With the BETA it generates the expected results.

**Expected behavior**
I created a Java client class that captures the steps in the guide (attached:[StreamToStreamJoin.txt](https://github.com/hazelcast/hazelcast/files/9634423/StreamToStreamJoin.txt)). Expected output:
```
Sleeping before querying sink map
[__key INTEGER=1, order_ts TIMESTAMP WITH TIME ZONE=2022-03-29T06:01:18Z, total_amount DOUBLE=133548.84, customer_name VARCHAR=Amal, shipment_id VARCHAR=ship-ch833601, ship_ts TIMESTAMP WITH TIME ZONE=2022-03-31T18:13:39Z, warehouse VARCHAR=UPS]
[__key INTEGER=2, order_ts TIMESTAMP WITH TIME ZONE=2022-03-29T17:02:20Z, total_amount DOUBLE=164839.31, customer_name VARCHAR=Alex, shipment_id VARCHAR=ship-as833602, ship_ts TIMESTAMP WITH TIME ZONE=2022-03-31T02:04:13Z, warehouse VARCHAR=UPS]
[__key INTEGER=3, order_ts TIMESTAMP WITH TIME ZONE=2022-03-29T13:44:10Z, total_amount DOUBLE=90427.66, customer_name VARCHAR=Hao, shipment_id VARCHAR=ship-dh833603, ship_ts TIMESTAMP WITH TIME ZONE=2022-03-31T20:47:09Z, warehouse VARCHAR=DHL]
Test run complete
```
Actual output:
```
Sleeping before querying sink map
>>>>>>>>> Should have results!
Test run complete
```

**To Reproduce**

1. Start a Zookeeper + Kafka broker and a HZ cluster. I used the provided Docker compose artifact from the guide. Just make sure to expose the HZ port to the host so the client can connect (i.e. `- "5701:5701"` under `hazelcast.ports:`)
2. Run the attached client code

**Comment by AyberkSorgun** [comment]
[HZ-1499](https://hazelcast.atlassian.net/browse/HZ-1499)

**Comment by viliam-durina** [comment]
I reproduced the issue in IDE. Looks like there is a mistake in the time bounds extraction. I have a fix, but I'm still testing it and updating current tests. I should have a final PR today. It's a blocker for 5.2.
