### ISSUE TITLE
Ordering of columns not preserved in JDBC mapping vs table in external store [HZ-1556]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22410]
**Describe the bug**
When creating a JDBC SQL mapping without specifying the columns (like in below example), the column order is reversed compared to that in remote source table. This affects statements such as `SELECT * FROM ...` and `INSERT INTO <mapping> VALUES`.

```
CREATE MAPPING people
TYPE JDBC 
OPTIONS (
  'externalDataStoreRef'='mysql-database' 
)
``` 

**Expected behavior**

**To Reproduce**

1. Start a member with an `external-data-store` configured
2. Create a JDBC mapping referencing the data store. This should be done without provide any columns explicitly (like above).
3. Execute `SELECT * FROM <jdbc-mapping>` or `INSERT INTO <jdbc-mapping> VALUES` to observe the behavior

**Additional context**

A potential workaround is to specify the columns in the desired order when creating the mapping. For example:

```
CREATE MAPPING people (
 id INT, 
 name VARCHAR 
) 
TYPE JDBC 
OPTIONS ( 
 'externalDataStoreRef'='mysql-database'
)
```

**Comment by viliam-durina** [comment]
The column order isn't reversed, but the order is lost because we put the columns into a HashMap here: 
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L157-L166
