### ISSUE TITLE
JdbcSqlConnector multiple issues

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#22412]
1. the connector doesn't escape or quote identifiers when generating SQL. This enables SQL injection. For example here: 
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L150
or here:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/SelectQueryBuilder.java#L70
and probably more.

2. This should rather by "unsupported column type", instead of "unknown"
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L421

3. We should use the nodeEngine.getLogger() here. This way it won't contain hazelcast instance name:
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L73

4. This is too wide-catching, the illegal-arg-exc is too unspecific. I think the whole try-catch can be removed, I guess it's supposed to "improve" the illegal-arg-exc thrown within `resolveType()` and that it's a leftover:
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L105-L107

5. We throw IllegalStateException in multiple places, but I think this exception is for something else. We should throw `QueryException.error()`.

6. Officially?
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L114

I didn't review everything.

Questions:
- why don't we use `connection.getMetaData().getColumns()` here, as we do in `readPrimaryKeyColumns`?
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L150
- why do we use column type name, and not the constants here?
https://github.com/hazelcast/hazelcast/blob/ee8ce2f87e78086c74d71b339d30eec110e28cde/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L161

**Comment by sumnerib** [comment]
Related to above question 2, when creating a mapping to a table in Postgres w/ a `TIMESTAMP WITH TIME ZONE` column, I get `Unknown column type: timestamptz`. Looks like this is a [PostgreSQL-specific type alias](https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE) returned by [getColumnTypeName()](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnTypeName-int-) which can be "database-specific". Perhaps [getColumnType()](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnType-int-) and [java.sql.Types](https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html) can be used instead which should be consistent across JDBC implementations.

**Comment by sumnerib** [comment]
Same as above with Postgres 'text' column: `Unknown column type: text` (standard pg type rather than alias). It should map to [java.sql.Types.VARCHAR](https://docs.oracle.com/javase/8/docs/api/java/sql/Types.html#VARCHAR).
