### ISSUE TITLE
MapStore init timeout when default map has a GenericMapStore configured [HZ-1598]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22515]
**Describe the bug**
MapStore initialization will fail if a `default` map is configured with `GenericMapStore` as its `map-store`. For example:

```
    <map name="default">
        <map-store enabled="true">
            <class-name>com.hazelcast.mapstore.GenericMapStore</class-name> 
            <properties>
                <property name="external-data-store-ref">postgres</property> 
            </properties>
        </map-store>
    </map>
```

**Expected behavior**
Should not experience timeouts if external store is up and a corresponding table exists in the external store.

**To Reproduce**

1. Start a member with an external store config and `default` map like in the above example 
2. Connect a client and try to `get()` from a map that has a corresponding table in the external DB
3. Observe the errors after a 5 second timeout

**Additional context**

Looks to be caused by attempting to init a MapStore for the internal `__sql.catalog` map. 

Attaching a unit test that captures the behavior: 
[IsaacDefaultMapWithGMSTest.txt](https://github.com/hazelcast/hazelcast/files/9799908/IsaacDefaultMapWithGMSTest.txt)

**Comment by orcunc** [comment]
I don't think this configuration is correct. Becase if we assign a **GenericMapStore** to **"default"** configuraiton, then for every map, Hazelcast will try to create a **GenericMapStore**. However there are **internal/systems** maps, and these will try to execute **"CREATE MAPPING ..."** statements and these will **fail**. One example is
 `"CREATE MAPPING "__map-store.__sql.catalog" EXTERNAL NAME "__sql.catalog" TYPE JDBC OPTIONS (    'externalDataStoreRef' = 'test-database-ref' )`

**Comment by sumnerib** [comment]
Right, the internal `__sql.catalog` is the cause of the issue. I think there are probably two ways to solve this:

1. **Not support configuring MapStore/GenericMapStore for the `default` map**: for this I think it should be explicitly stated in the docs that this is unsupported. Currently the opposite is true, since the [example in the docs](https://docs.hazelcast.com/hazelcast/latest/mapstore/configuring-a-generic-mapstore#quickstart-configuration) actually uses the `default` map. Maybe the member startup could even fail fast if the `default` map was configured incorrectly.
2. **Fix the internal maps so that they aren't affected by the default config**: the user shouldn't have to worry about if their configs have side-effects on the internal maps, if possible. IMHO setting the `default` map in this way can be a valid use-case. Imagine I have 50 DB tables that I want cached in HZ. It would be cumbersome to create separate configs for each map/table.
