### ISSUE TITLE
NormalResponse not always needed

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2252]
Currently when a response is send e.g. for a map.get, a Response object is wrapped around the result. This response object contains the number of backups the caller should wait for. 

But if the call is a readonly call, or there is no change, then  there are no backups and therefor there is no need to send a NormalResponse object over the line. The actual value can be send immediately. This reduces the amount of object litter + deserialization overhead + amount of network traffic.

**Comment by bwzhang2011** [comment]
@noctarius,@pveentjer, any update with such issue.

**Comment by dbrimley** [comment]
Closed as fixed in 3.8
