### ISSUE TITLE
GenericMapStore SQL mapping not removed when IMap is destroyed [HZ-1604]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22528]
**Describe the bug**
When an `IMap` is created with a `GenericMapStore`, if the `IMap` distributed object is destroyed, the internal JDBC mapping used for the `GenericMapStore` is not also removed.

**Expected behavior**
The JDBC mapping is removed when the `IMap` is destroyed.

**To Reproduce**

1. Start an HZ member with a map config that has a `GenericMapStore`
2. Get an instance of the `IMap` and read some values to insure the `GenericMapStore` (and internal JDBC mapping) is initialized
3. Destroy the aforementioned map (i.e. `map.destroy()`)
4. Via SQL, execute `select * from "__map-store.mapName"` and observe that the mapping still exists and can still be used to query the remote table.

**Comment by frant-hartm** [comment]
@sumnerib if #22744 fixes this issue let's close this.
