### ISSUE TITLE
Scientific notation needs better type assignment [HZ-1748]

### ISSUE THREAD

**Issue by burakgok** [hazelcast/hazelcast#22785]
When numeric literals are assigned SQL types:
1. Integers, e.g. 1, 42, receive [the narrowest possible among `TINYINT`, `SMALLINT`, `INTEGER`, `BIGINT`][1] and `DECIMAL`.
2. Floating-point numbers, e.g. 1.2, 4.2, receive [`DECIMAL`][2].
3. Scientific notation (exponential form), e.g. 1e1, 4.2e2, receive [`DOUBLE`][2].
**Note:** Calcite calls the scientific notation "approximate form."

Floating-point numbers, regardless of whether they are represented in the exponential form, are not optimized for storage, unlike integers. Furthermore, having different ranges for different representations of the same floating-number is inconsistent.

Floating-point numbers should receive the narrowest possible among `REAL`, `DOUBLE` and `DECIMAL`, which are converted into Float, Double and BigDecimal internally.

[1]: https://github.com/hazelcast/hazelcast/blob/v5.2.0/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/literal/NumericLiteral.java#L74
[2]: https://github.com/apache/calcite/blob/calcite-1.31.0/core/src/main/java/org/apache/calcite/sql/SqlNumericLiteral.java#L52

**Comment by viliam-durina** [comment]
`REAL`, `DOUBLE` and `DECIMAL` aren't interchangeable. It's not only about the range, but about precision. REAL+DOUBLE are inexact, they cannot exactly represent decimal numbers, only decimal can. Especially financial data must never be expressed with them. They can be considered more effective variant for mathematics. Also, both REAL and DOUBLE can represent a number from 0..1, but double has much more precision, much larger mantissa.

So I think the current choice is correct.

**Comment by burakgok** [comment]
Since we cannot know whether the data will be financial, it is best to leave floating-point numbers as they are, as you pointed out. The numbers that are expressed in the scientific-notation can be tried to optimize, but this notation is used to conveniently express very low/large exponents, so `DOUBLE` is the best choice for them.

**Comment by burakgok** [comment]
The largest possible finite value of `DOUBLE` is 1.7976931348623157e+308. In SQL, literal 1.8e+308 is tried to parse as `DOUBLE` and converted to -Infinity since it is out of range. The exponent is huge and unlikely to be used, but having such a limitation causes an inconsistency because the number is valid in the form 18000...0.
