### ISSUE TITLE
Job failed with OOM in com.hazelcast.internal.serialization.impl.compact.reader.CompactStreamSerializerValueReaderSpecTest [API-2019]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22825]
_master_ (d6d5a65d2ef19591a8c744d779d787e66314efd3)

Failed on Oracle-11 (sonar build): [Jenkins Job link](https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1393/)

<details><summary>Stacktrace:</summary>

```
18:59:50 Exception in thread "timeout-check[8614.740s][info   ][gc] GC(246) To-space exhausted
18:59:50 [8614.740s][info   ][gc] GC(246) Pause Young (Normal) (G1 Evacuation Pause) 2937M->2937M(3072M) 2.415ms
18:59:51 [8614.943s][info   ][gc] GC(247) Pause Full (G1 Evacuation Pause) 2937M->2936M(3072M) 202.797ms
18:59:51 [8615.166s][info   ][gc] GC(248) Pause Full (G1 Evacuation Pause) 2936M->2936M(3072M) 222.833ms
18:59:51 -timer" java.lang.OutOfMemoryError: Java heap space
18:59:51 [8615.194s][info   ][gc] GC(249) To-space exhausted
```

</details>

S3 link for stdout logs: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1393/

**Comment by krzysztofslusarski** [comment]
Most probably the PR https://github.com/hazelcast/hazelcast/pull/20635 created a need for bigger heap. After setting heap size to 10GB the heap after GC chart looked that:
![image](https://user-images.githubusercontent.com/57556371/202279931-2d561141-f70e-48ed-82aa-b7efba8170cf.png)
![image](https://user-images.githubusercontent.com/57556371/202279971-536d19fa-fb6e-446b-919d-c701f0fb05a1.png)
I'm setting the heap size of that build to 6GB

**Comment by sumnerib** [comment]
Failed again on Hazelcast-master-Openj9-17: https://jenkins.hazelcast.com/job/Hazelcast-master-Openj9-17/40/

Errors:

```
23:40:42 [INFO] Running com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_2_2
23:40:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/17 04:40:58 - please wait.
23:40:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/17 04:40:58 - please wait.
23:40:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/17 04:40:59 - please wait.
23:40:59 JVMDUMP032I JVM requested Heap dump using '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-Openj9-17/heapdump.20221117.044058.100.0001.phd' in response to an event
```

and 

```
23:41:25 JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
23:41:25 (ConcurrentLinkedDeque.java:347)
23:41:25 	at java.base/java.util.concurrent.ConcurrentLinkedDeque.addLast(ConcurrentLinkedDeque.java:840)
23:41:25 	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$QueueSynchronizer.addNext(ThreadedStreamConsumer.java:350)
23:41:25 	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$QueueSynchronizer.pushNext(ThreadedStreamConsumer.java:327)
23:41:25 	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer.handleEvent(ThreadedStreamConsumer.java:136)
23:41:26 	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer.handleEvent(ThreadedStreamConsumer.java:47)
23:41:26 
```

**Comment by olukas** [comment]
Failed again on:
ZingJDK8 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8/472/console):
```
02:45:51 [INFO] Running com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_2_1
02:45:58 
02:45:58 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Thread-21"
02:53:18 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
02:53:38 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
02:56:09 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
...
```

OracleJDK8 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK8/225/console):
```
23:32:20 [INFO] Running com.hazelcast.client.protocol.compatibility.MemberCompatibilityNullTest_2_0_1
23:32:27 Exception in thread "fork-1-event-thread" java.lang.OutOfMemoryError: GC overhead limit exceeded
23:32:29 	at java.util.Arrays.copyOfRange(Arrays.java:3664)
23:32:29 	at java.lang.String.<init>(String.java:207)
23:32:29 	at java.nio.HeapCharBuffer.toString(HeapCharBuffer.java:572)
23:32:29 	at java.nio.CharBuffer.toString(Cha
23:32:30 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "fork-1-event-thread"
23:35:45 Exception in thread "timeout-check-timer" java.langExce
23:35:50 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
...
```

CorrettoJDK8 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK8/204/console):
```
17:30:35 [INFO] Running com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_2_4
17:30:52 
17:30:52 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "fork-1-event-thread"
17:30:53 Exception in thread "ti
17:30:57 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
17:30:58 Exception i
17:31:00 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
...
```

OracleJDK11 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK11/347/console):
```
00:03:45 [INFO] Running com.hazelcast.client.replicatedmap.nearcache.ClientReplicatedMapNearCacheBasicTest
00:03:45 [2619.565s][info][gc] GC(6681) To-space exhausted
00:03:45 [2619.565s][info][gc] GC(6681) Pause Young (Normal) (G1 Evacuation Pause) 1971M->1971M(2048M) 9.744ms
00:03:45 [2619.767s][info][gc] GC(6682) Pause Full (G1 Evacuation Pause) 1971M->1970M(2048M) 202.260ms
00:03:45 [2619.800s][info][gc] GC(6683) To-space exhausted
...
00:03:51 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
...
```

Windows with MicrosoftJDK17 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/36/console):
```
19:58:49 [INFO] Running com.hazelcast.client.splitbrainprotection.ringbuffer.ClientRingbufferSplitBrainProtectionReadTest
19:58:49 [3044.490s][info][gc] GC(7536) To-space exhausted
19:58:49 [3044.490s][info][gc] GC(7536) Pause Young (Normal) (G1 Evacuation Pause) 1972M->1972M(2048M) 2.082ms
19:58:49 [3044.726s][info][gc] GC(7537) Pause Full (G1 Compaction Pause) 1972M->1970M(2048M) 236.111ms
19:58:49 [3044.824s][info][gc] GC(7538) To-space exhausted
...
21:47:46 Java heap space
...
```

Openj9-11 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/105/console):
```
08:36:47 [INFO] Running com.hazelcast.client.protocol.compatibility.ClientCompatibilityTest_2_0
08:36:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/19 07:36:59 - please wait.
08:36:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/19 07:36:59 - please wait.
08:36:59 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/19 07:36:59 - please wait.
08:36:59 JVMDUMP032I JVM requested Heap dump using '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-Openj9-11/heapdump.20221119.073659.100.0001.phd' in response to an event
08:37:01 JVMDUMP010I Heap dump written to /home/jenkins/jenkins_slave/workspace/Hazelcast-master-Openj9-11/heapdump.20221119.073659.100.0001.phd
08:37:01 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/19 07:37:01 - please wait.
```

IbmJDK8 (https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/210/console):
```
01:17:12 [INFO] Running com.hazelcast.map.impl.tx.TxnMapNearCacheBasicTest
01:17:40 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2022/11/19 00:17:40 - please wait.
01:17:40 JVMDUMP032I JVM requested System dump using '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-IbmJDK8/core.20221119.001740.97.0001.dmp' in response to an event
01:17:40 JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.798438.
01:17:40 
01:17:46 JVMDUMP012E Error in System dump: The core file created by child process with pid = 798438 was not found. Expected to find core file with name "/home/jenkins/jenkins_slave/workspace/Hazelcast-master-IbmJDK8/core.798438"
01:17:46 JVMDUMP032I JVM requested Heap dump using '/home/jenkins/jenkins_slave/workspace/Hazelcast-master-IbmJDK8/heapdump.20221119.001740.97.0002.phd' in response to an event
```

**Comment by sumnerib** [comment]
Not sure if this one is related. Job failed with OOM trying to publish the test report: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK8-nightly/9/

<details><summary>Stacktrace</summary>
17:26:01 ERROR: Step ‘Publish JUnit test result report’ aborted due to exception: 
17:26:01 java.lang.OutOfMemoryError: Java heap space
17:26:01 	at java.util.Arrays.copyOf(Arrays.java:3332)
17:26:01 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
17:26:01 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
17:26:01 	at java.lang.StringBuilder.append(StringBuilder.java:195)
17:26:01 	at java.io.ObjectInputStream$BlockDataInputStream.readUTFSpan(ObjectInputStream.java:3665)
17:26:01 	at java.io.ObjectInputStream$BlockDataInputStream.readUTFBody(ObjectInputStream.java:3573)
17:26:01 	at java.io.ObjectInputStream$BlockDataInputStream.readLongUTF(ObjectInputStream.java:3548)
17:26:01 	at java.io.ObjectInputStream.readString(ObjectInputStream.java:2053)
17:26:01 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1651)
17:26:01 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
17:26:01 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
17:26:01 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
17:26:01 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
17:26:01 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
17:26:01 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
17:26:01 	at java.util.ArrayList.readObject(ArrayList.java:799)
17:26:01 	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
17:26:01 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:26:01 	at java.lang.reflect.Method.invoke(Method.java:498)
17:26:01 	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
17:26:01 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2322)
17:26:01 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
17:26:01 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
17:26:01 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
17:26:01 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
17:26:01 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
17:26:01 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
17:26:01 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
17:26:01 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
17:26:01 	at java.util.ArrayList.readObject(ArrayList.java:799)
17:26:01 	at sun.reflect.GeneratedMethodAccessor64.invoke(Unknown Source)
17:26:01 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:26:01 Caused: java.io.IOException: Remote call on optane-lab132 failed
17:26:01 	at hudson.remoting.Channel.call(Channel.java:1004)
17:26:01 	at hudson.FilePath.act(FilePath.java:1194)
17:26:01 	at hudson.FilePath.act(FilePath.java:1183)
17:26:01 	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:118)
17:26:01 	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:157)
17:26:01 	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:251)
17:26:01 	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:174)
17:26:01 	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
17:26:01 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
17:26:01 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:26:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:816)
17:26:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:765)
17:26:01 	at hudson.model.Build$BuildExecution.post2(Build.java:179)
17:26:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:709)
17:26:01 	at hudson.model.Run.execute(Run.java:1922)
17:26:01 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
17:26:01 	at hudson.model.ResourceController.execute(ResourceController.java:101)
17:26:01 	at hudson.model.Executor.run(Executor.java:442)
</details>

**Comment by mdumandag** [comment]
I think we can safely close this issue: after changing the job setups in Jenkins (https://hazelcast.slack.com/archives/CFTA0BX6E/p1669127375195139?thread_ts=1669024584.396889&cid=CFTA0BX6E) we no longer see this issue. Also, there have been some updates to the surefire and failsafe plugins in the meantime, they might have also helped.
