### ISSUE TITLE
Job failed with OOM in com.hazelcast.client.protocol.compatibility.MemberCompatibilityTest_2_0

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#22824]
master(commit d6d5a65d2ef19591a8c744d779d787e66314efd3)

Failed on CorrettoJDK11: [Jenkins job link](https://jenkins.hazelcast.com/job/Hazelcast-master-CorrettoJDK11/197/)

<details><summary>Stacktrace:</summary>

```
00:06:05 xception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
00:06:05 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(AbstractQueuedSynchronizer.java:1896)
00:06:05 	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2114)
00:06:05 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.t[3186.579s][info   ][gc] GC(388) To-space exhausted
```

</details>

Link to stdout logs in S3: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-CorrettoJDK11/197/

**Comment by sumnerib** [comment]
Also failed Windows-OracleJDK8 `MemberCompatibilityTest_2_2`: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK8/421/

**Comment by sumnerib** [comment]
Another OOM failure (Oracle-11-sonar): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1395/

This time during test `com.hazelcast.internal.util.concurrent.OneToOneConcurrentArrayQueueTest`

**Comment by krzysztofslusarski** [comment]
Duplicates of https://github.com/hazelcast/hazelcast/issues/22825
