### ISSUE TITLE
com.hazelcast.jet.python.PythonServiceTest - flock: command not found

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#22984]
_master_ (commit 4b12ab0342a9f2844e653a55eea2d3b47edb02df)

Failed on MacOS: https://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/137/testReport/junit/com.hazelcast.jet.python/PythonServiceTest/ in both tests:
* batchStage_mapUsingPython 
* test_channelFn

```
20:32:58,121 DEBUG || - [python] python-init-logger_java.lang.UNIXProcess@66ae160c - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT]
 + flock --exclusive /Users/ec2-user/.jet-pip.lock python3 -m pip install --upgrade pip
20:32:58,124 DEBUG || - [python] python-init-logger_java.lang.UNIXProcess@66ae160c - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] 
./jet_to_python_init.sh: line 9: flock: command not found
```
`flock` used in #22829 to fix #22599 is not available in MacOS build

**Comment by ldziedziul** [comment]
I've installed `flock` on macOS, please re-run it

**Comment by frant-hartm** [comment]
http://jenkins.hazelcast.com/job/Hazelcast-master-MacOS-ZuluJDK8/139/
Passed.
