### ISSUE TITLE
NPE in MulticastConfig.hashCode()

### ISSUE THREAD

**Issue by v00d00c0de** [hazelcast/hazelcast#23177]
Hazelcast 5.2.1.

com.hazelcast.config.MulticastConfig has a member
`private Boolean loopbackModeEnabled` 
and the following hashCode implementation:

   

>  public final int hashCode() {
>         int result = (enabled ? 1 : 0);
>         result = 31 * result + (multicastGroup != null ? multicastGroup.hashCode() : 0);
>         result = 31 * result + multicastPort;
>         result = 31 * result + multicastTimeoutSeconds;
>         result = 31 * result + multicastTimeToLive;
>         result = 31 * result + trustedInterfaces.hashCode();
>         result = 31 * result + (loopbackModeEnabled ? 1 : 0);
>         return result;
>     }

**Describe the bug**
Activating the _hashCode_ method when the _loopbackModeEnabled_ is null (default value if none was provided by the user) causes NPE.

**Expected behavior**
_hashCode_ method does not throw NPE

**Comment by debanjanc01** [comment]
This should be fixed by https://github.com/hazelcast/hazelcast/pull/23180 without changing the value of the hashcode computed keeping all other fields the same.
