### ISSUE TITLE
Migration listener methods (migrationStarted, migrationCompleted, migrationFailed) don't fire when member down

### ISSUE THREAD

**Issue by agherardi** [hazelcast/hazelcast#2318]
Hi,
I have a distributed application that uses an Hazelcast map and registers a migration listener with Hazelcast's partition service.

When a new application node starts, the set of local map keys on the existing nodes becomes smaller - as expected, because the new node takes over some of the keys - and the migration listener migrationStarted and migrationCompleted methods fire - also as expected.

When a node is stopped, the set of local map keys becomes larger - as expected - however none of the callback methods fires.

Is this by design? I'm using Hazelcast 3.2.

Thank you in advance.

**Comment by mdogan** [comment]
Already fixed by https://github.com/hazelcast/hazelcast/pull/4272
