### ISSUE TITLE
Requests to Kubernetes API are sent although DNS Lookup mode is chosen

### ISSUE THREAD

**Issue by ivyanni** [hazelcast/hazelcast#23208]
**Describe the bug**
Last week I moved one of microservices with embedded Hazelcast to K8s and faced an unexpected trouble. Access to Kubernetes API from pods was disabled by cluster admin so I decided to use DNS Lookup for instance discovery. I created a headless service, set _service-dns_ parameter and expected for containers to run. But they stuck on Hazelcast discovery for a while and then container was recreated. Latest logs from killed container (names changed):

> 2022-12-18 12:53:33.964  INFO 28350 --- [           main] c.h.s.d.integration.DiscoveryService     : [192.168.49.1]:5701 [dev] [5.1.3] Kubernetes Discovery properties: { service-dns: hazelcast-kube-demo, service-dns-timeout: 5, service-name: null, service-port: 0, service-label: null, service-label-value: true, namespace: null, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, expose-externally-mode: AUTO, use-node-name-as-external-address: false, service-per-pod-label: null, service-per-pod-label-value: null, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
> 2022-12-18 12:55:34.063  WARN 28350 --- [           main] com.hazelcast.spi.utils.RetryUtils       : Couldn't connect to the service, [1] retrying in 1 seconds...

So it seems that Hazelcast tries to connect to some service for a long time and then liveness probe kills the container.

After some experiments with properties and with enabled debug logs I decided to look into source code and found that `HazelcastKubernetesDiscoveryStrategy` [creates](https://github.com/hazelcast/hazelcast/blob/890f941868313e6827d1b0b8feb57130846bc232/hazelcast/src/main/java/com/hazelcast/kubernetes/HazelcastKubernetesDiscoveryStrategy.java#L49) a `KubernetesClient` instance before `DiscoveryMode` selection. `KubernetesClient` [sends a request](https://github.com/hazelcast/hazelcast/blob/890f941868313e6827d1b0b8feb57130846bc232/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L99) to Kube API to get EndpointSlices when instantiated. So even when user chose DNS Lookup mode and specified _service-dns_ as per docs Hazelcast tries to send a request to Kubernetes API. 
Not only it is a useless request for DNS Lookup mode, it is unexpected for user because docs clearly say which parameters are used for each discovery mode. In my case request to Kube API was unsuccessful and connection hang up so application couldn't start at all.

**Expected behavior**

I expect that when _service-dns_ is specified then DNS Lookup mode will be used for discovery without any requests to Kubernetes API and need to configure kube api connection parameters.

**To Reproduce**

1. Deploy application with embedded Hazelcast and _service-dns_ specified to k8s cluster without access from pods to Kubernetes API
2. Check logs
3. Warning message `Couldn't connect to the service, [1] retrying in 1 seconds...` exists and it takes min 6s by default to start using DNS lookup

**Additional context**

In my case Hazelcast 5.1.3 was used. According to commit history this issue was introduced when [EndpointSlice support was added](https://github.com/hazelcast/hazelcast/commit/74d1a5d3261bfefd37cd139edf41c853b81842cd) and exists since 5.1 release. There is no such problem with Hazelcast 5.0.x and earlier versions.

**Resolution proposal**

1. The main issue is that `KubernetesClient` is created even when it's not needed (as for DNS Lookup mode). So I propose to move `KubernetesClient` instantiation and lifecycle methods invocations (start/stop) to `KubernetesApiEndpointResolver`.
2. Then there are two methods in `HazelcastKubernetesDiscoveryStrategy` that use `KubernetesClient` only when Kube API mode was chosen: `discoverZone` and `discoverNodeName`. So let's move these methods to `EndpointResolver` abstract class and its logic to `KubernetesApiEndpointResolver` subclass. After that checks for Kubernetes API mode could be removed from these methods as this logic will be executed only when `HazelcastKubernetesDiscoveryStrategy` instantiated without _service-dns_ specified.

With these changes `HazelcastKubernetesDiscoveryStrategy` will be responsible only for `KubernetesConfig` creation and appropriate `EndpointResolver`'s lifecycle. All mode-specific logic will be moved to `EndpointResolver` subclasses.

What's your opinion on this proposal? I can open a PR if you are ok with my way of problem resolution.

**Comment by mtyazici** [comment]
Hi @ivyanni, you are right it seems the issue was introduced with EndpointSlice support. 

Your proposal looks good to me. Could you create a PR if you are still interested in fixing it?

**Comment by ivyanni** [comment]
Sure, will do it in a few days.
