### ISSUE TITLE
remove Atomikos dependency, missing source

### ISSUE THREAD

**Issue by dpocock** [hazelcast/hazelcast#2338]
Some of the unit test cases uses Atomikos.  Their approach to open source doesn't appear to be as pronounced as projects like Hazelcast who are 100% open.

The Atomikos web site says it is "open source" under the Apache License v2.0

However, at present they do not publish the source code in a form that can be rebuilt easily on demand.  They do not make their repository accessible to the public.  They only publish stripped-down source JARs in the Maven Central archive and they do not publish the source code of their test cases at all.

There are alternative transaction managers and it appears the test cases could be easily modified to use any of them, it is not much harder than swapping a JDBC driver.

If the Atomikos source does become more accessible then this issue could be closed without any change to Hazelcast.

**Comment by dpocock** [comment]
It looks like some of the Atomikos source, including unit tests, is now on Github at https://github.com/atomikos/transactions-essentials/tree/master/public

If this is everything that is required for Hazelcast then this issue could be closed.

**Comment by jerrinot** [comment]
hi @dpocock: many thanks for heads-up. the source tree on github looks good, I am closing the issue.
