### ISSUE TITLE
com.hazelcast.jet.python - flock: cannot open lock file /home/ubuntu/.jet-pip.lock: Permission denied

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23463]
_master_ (commit eda27a391d99127b52f07a2ec7bca8fac2d02284)

We have several failures with the same problem in logs:
```
[python] python-init-logger_java.lang.UNIXProcess@6fe2ae2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] + flock --exclusive /home/ubuntu/.jet-pip.lock python3 -m pip install --upgrade pip
[python] python-init-logger_java.lang.UNIXProcess@6fe2ae2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] flock: cannot open lock file /home/ubuntu/.jet-pip.lock: Permission denied
ProcessorSupplierWithService] hz.PythonInitCleanupTest_dreamy_hamilton.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [0947-2e68-e186-0001/mapUsingPythonBatch#PS] PythonService context creation failed, will retry
com.hazelcast.jet.JetException: PythonService initialization failed: java.lang.Exception: Initialization script finished with non-zero exit code: 66
```
Failed on ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips-nightly/501/testReport/junit/com.hazelcast.jet.python/

**Comment by Patras3** [comment]
The same failures here:
on _master_ with ibm-8: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips/52/testReport/junit/com.hazelcast.jet.python/PythonServiceTest/

**Comment by olukas** [comment]
This is probably related our FIPS machine (it happened again https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/502/testReport/com.hazelcast.jet.python/PythonInitCleanupTest/cleanupRunsAfterJob/).

It seems to be constant failure.

Most of the tests in `com.hazelcast.jet.python.PythonInitCleanupTest` and `com.hazelcast.jet.python.PythonServiceTest` fail with this issue.

**Comment by kwart** [comment]
Fixed in https://github.com/hazelcast/DevOps/commit/58eb7540537fad34c1707c4575f8551a7c4ff03a
