### ISSUE TITLE
Builds timeout during various tests

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23537]
_master_ (commit 69e630df546ca286eb7544a0c8ed1a9154598349)

Failed on oracle-8: https://jenkins.hazelcast.com/job/Hazelcast-master-OracleJDK8-nightly/933/

Timed out:

```
00:47:54 [INFO] Running com.hazelcast.jet.impl.connector.ReadMapOrCacheP_ConsistencyTest
06:47:47 Build timed out (after 640 minutes). Marking the build as failed.
```

**Comment by sumnerib** [comment]
Another possibly related timeout in oracle-8 (sonar): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/1474/

```
19:29:07 [INFO] Running com.hazelcast.jet.impl.util.ExceptionUtilTest
02:35:48 Build timed out (after 600 minutes). Marking the build as failed.
```

**Comment by olukas** [comment]
It seems that's the culprit for this failure is `com.hazelcast.jet.core.JobUploadTest` test. It fails/timeout in nightly tests and it seems and it affects also other tests execution (the clean up is probably not done properly). The test fails even locally.

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
