### ISSUE TITLE
Cannot deploy Jet job with ActiveMQ source without javax.jms already on classpath

### ISSUE THREAD

**Issue by Holmistr** [hazelcast/hazelcast#23590]
**Describe the bug**
There are multiple issues on the way, so let me describe the whole journey.

I want to submit a Jet job that will read from ActiveMQ using the JMS source. See the following code:
```
        Pipeline pipeline = Pipeline.create();
        pipeline.readFrom(Sources.jmsQueue("JCG_QUEUE",
                () -> new ActiveMQConnectionFactory("tcp://activemq:61616")))
                .withoutTimestamps()
                .writeTo(Sinks.logger());

        HazelcastInstance hz = HazelcastClient.newHazelcastClient();

        JobConfig jobConfig = new JobConfig();

        hz.getJet().newJob(pipeline, jobConfig);
```
 I'll get:
 ```
java.lang.ClassNotFoundException: javax.jms.Destination
```

Ok, makes sense. So I try to add it to the JobConfig:
```
jobConfig.addJar("~/.m2/repository/javax/jms/javax.jms-api/2.0.1/javax.jms-api-2.0.1.jar");
```
But that doesn't help. I verified that the javax.jms.Destination is correctly there and that the path is correct. However, if I add the JAR directly on the member's classpath, it works. **This is the main bug**.

Let me continue the experience. Adding the jms-api.jar resolves the problem with javax.jms.Destination CNFE. But I get another one:

```
java.lang.ClassNotFoundException: org.apache.activemq.ActiveMQConnectionFactory. Add it using JobConfig or start all members with it on classpath
``` 

Far enough, makes sense. The docs (https://docs.hazelcast.com/hazelcast/5.2/integrate/jms-connector#installing-the-connector) say "To use a JMS broker, such as ActiveMQ, you need the client libraries on your members' classpath.". Here I would say it makes sense to mention the specific JAR. So I assume it's "activemq-client" JAR, therefore I'll add

```
jobConfig.addJar("/home/jholusa/.m2/repository/org/apache/activemq/activemq-client/5.15.11/activemq-client-5.15.11.jar");
```

Now I get more funny exception:
```
java.lang.ClassNotFoundException: javax.management.j2ee.statistics.Stats. Add it using JobConfig or start all members with it on classpath
```

Well, I have no idea in which JAR I could find this, but probably I would google this. I would definitely expect this in the documentation. I just got lazy and instead I added "activemq-all" JAR instead:
```
jobConfig.addJar("/home/jholusa/.m2/repository/org/apache/activemq/activemq-all/5.15.11/activemq-all-5.15.11.jar");
```

Finally, I have it working :)

**Comment by orcunc** [comment]
In order to create a connection to JMS broker there are two possible solutions.
1. Having the JMS client libraries on your members' classpath -> This is what the documentation suggests
2. Adding the client libraries to JobConfig.  -> This is what you have tried

Both cases are OK. However in both cases *all* transitive dependencies of the JMS client must be in the classpath. 

In your first attempt with **activemq-client-5.15.11.jar**, you have added only the client jar. The transitive dependencies were missing. Therefore ClassNotFoundException was thrown.

In your second attempt you have added the fat jar **activemq-all-5.15.11.jar** for the client library. So all transitive dependencies were there, and it worked

**Comment by orcunc** [comment]
The documentation has been changes as below
`To use a JMS broker, such as ActiveMQ, you need to add the client libraries and all their transitive dependencies to the classpath of your members. If the broker provides a fat client JAR, you may find it easier to use that instead.`
