### ISSUE TITLE
zero-config compact serialization not working for objects with a UUID field [API-2098]

### ISSUE THREAD

**Issue by shollander** [hazelcast/hazelcast#23698]
**Describe the bug**
With version 5.2.0, it is impossible for zero-config compact serialization to work on objects that have a field of type `java.util.UUID`.
Zero-config serialization fails since there is no compact serializer for `java.util.UUID`. Defining a custom compact serializer for `java.util.UUID` does not work either since there is already a default serializer defined by Hazelcast. This leads to a cache-22 situation.

**To Reproduce**
Given the following class:
```java
public class Employee {
    private UUID id;
    private String name;

    public Employee(UUID id, String name) {
        this.id = id;
        this.name = name;
    }

    public UUID getId() {
        return id;
    }

    public String getName() {
        return name;
    }
}
```
Compact serialization of this class is impossible without defining a custom compact serializer.
When this Employee class is included in another class class that does has have a compact serializer defined, this forces us to write a compact serializer for Employee as well. This can be tedious when there are many classes used that have `UUID` fields.

**Comment by Rokko11** [comment]
I have the same issue when using UUIDs (Spring Boot + Hazelcast Cache). Is there any progress on this issue?

If not, is there any workaround? At the moment I would have to write a custom serializer for each class containing UUIDs. That's not an option on the long run.

**Comment by mdumandag** [comment]
We can provide a way to support this only in zero-config serialization, by adding similar support for UUID fields, as we did for enum, map, set, and list fields. cc @ihsandemir WDYT?

**Comment by Rokko11** [comment]
> We can provide a way to support this only in zero-config serialization, by adding similar support for UUID fields, as we did for enum, map, set, and list fields. cc @ihsandemir WDYT?

Yes, I already tried to hook somewhere into ValueReaderWriters to adapt the CONSTRUCTORS and ARRAY_CONSTRUCTORS arrays. But as overriding static methods is getting dirty I decided to push this bug a little bit ;-)

**Comment by mdumandag** [comment]
For now, you can introduce a wrapper type, add a compact serializer for it, and change your classes to use that field type instead of UUID. This way, you can avoid writing a serializer for your class, and get away by just providing a serializer for your wrapper UUID type

**Comment by Rokko11** [comment]
Introducing a wrapper type is no option for our use-case since it also affects classes from dependent libraries.

Are you open for contribution regarding this defect?

**Comment by srknzl** [comment]
@mdumandag Does it make sense to revert  https://github.com/hazelcast/hazelcast/pull/22219? If we allowed compact serializers to override default serializers, this might be solved by registering a compact serializer for UUID. 

If not, I agree that we can add builtin compact ReaderWriter for UUID.

**Comment by ihsandemir** [comment]
> @mdumandag Does it make sense to revert #22219? If we allowed compact serializers to override default serializers, this would be solved by registering a compact serializer for UUID.
> 
> If not, I agree that we can add builtin compact ReaderWriter for UUID.

@srknzl I agree we can revert that PR. But we also need to remove the check at [here](https://github.com/hazelcast/hazelcast/blob/v5.3.1/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/compact/CompactUtil.java#L242) (which prevents serializing the jdk classes) if the `SerializationConfig.allowOverrideDefaultSerializers` is set to `true`.

what do you guys think @srknzl and @mdumandag ?

**Comment by srknzl** [comment]
If we add the functionality of registering a serializer to use for the zero config compact serializer (reflective serializer), leading to no need to change the default serializers, would it be a good solution? @Rokko11

**Comment by mdumandag** [comment]
I believe something like what Serkan wrote might be a good idea: Allow default serializers to be overridden to be used for the fields of compact serializers; but only for compact, they should not have effect over the serialization system and we should keep using the default serializers for these top-level types. Otherwise, overriding the default serializers for types like uuid might result in unexpected behavior

**Comment by Rokko11** [comment]
Yes, that would be a solution to allow registering serializers for classes in java.util (or other packages by configuration). That indeed was retrospected seen the key problem.

**Comment by ihsandemir** [comment]
@Rokko11 Submitted the fix. Can you please review the PR #25073  and let me know if it works for your case?

**Comment by ihsandemir** [comment]
> 
👆 @Rokko11

**Comment by CreaCloudz** [comment]
Hi, I didn't really follow it but I saw this issue I wanted to know if the addition was made in version 5.3.6 or not regarding uuid's

**Comment by ihsandemir** [comment]
Hello @CreaCloudz There is no default serializer for UUID in compact but you can provide your own UUID serializer/deserializer and register it(see the related PR and issue) which will override our internal UUID serializer, hence be careful when using it since it will be used in other places where we serialize UUIDs) and this will work with the compact serialization.

**Comment by CreaCloudz** [comment]
> Hello @CreaCloudz There is no default serializer for UUID in compact but you can provide your own UUID serializer/deserializer and register it(see the related PR and issue) which will override our internal UUID serializer, hence be careful when using it since it will be used in other places where we serialize UUIDs) and this will work with the compact serialization.

java.lang.IllegalArgumentException: Compact serializer for the class 'class java.util.UUID can not be registered as it overrides the default serializer for that class provided by Hazelcast.

Yes finally when doing mine I always get an error!

**Comment by CreaCloudz** [comment]
> Hello @CreaCloudz There is no default serializer for UUID in compact but you can provide your own UUID serializer/deserializer and register it(see the related PR and issue) which will override our internal UUID serializer, hence be careful when using it since it will be used in other places where we serialize UUIDs) and this will work with the compact serialization.

java.lang.IllegalArgumentException: Compact serializer for the class 'class java.util.UUID can not be registered as it overrides the default serializer for that class provided by Hazelcast.

Yes finally when doing mine I always get an error.. @ihsandemir

**Comment by ihsandemir** [comment]
@CreaCloudz Did you set `SerializationConfig.allowOverrideDefaultSerializers` to `true` as mentioned in above comments?

**Comment by ihsandemir** [comment]
@CreaCloudz 
Why do you need `clientConfig.getSerializationConfig().setAllowUnsafe(true);`?

The rest looks OK.

**Comment by CreaCloudz** [comment]
@ihsandemir 

it was just to test but it doesn't work every time I get an error I'll give you the link to the stackoverflow that I'm doing.

https://stackoverflow.com/questions/77780476/hazelcast-serializer-uuid-not-workging

**Comment by CreaCloudz** [comment]
@ihsandemir I use the HazelCast 5.4.0-SNAPSHOT with docker image, however I compile my jar with version 5.3.6, does this have an impact?

**Comment by ihsandemir** [comment]
@CreaCloudz  The interface does not change, hence I would not expect any effect but just to be safe side, can you please use the same latest version and try again? Can you still share the server start log so that we can observe the commit id of the running server to see if you are on the correct source code base?

**Comment by CreaCloudz** [comment]
@ihsandemir https://pastebin.com/W8DcRUee
