### ISSUE TITLE
Fix complex names in DataLinks

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast#23829]
`DataLinkResource` currently contains `name` as `String`. The name should match EXTERNAL NAME in CREATE MAPPING command, but EXTERNAL NAME is a compound identifier. In `JdbcDataLink` we currently return `schema + '.' + name` as the resource name, but the `.` will be interpreted literally, not as a compound identifier separator. We need to change the resource `name` to `String[]` so that the name doesn't have to be escaped.

We also need to add `DataLink.defaultObjectType()` method to let the UI know which object type is the default, and for which it doesn't need to generate the `OBJECT TYPE` clause in the CREATE MAPPING command.

**Comment by k-jamroz** [comment]
Seems to be implemented by #24339. @frant-hartm can we close this issue?
