### ISSUE TITLE
Scripting use question

### ISSUE THREAD

**Issue by tc792617871** [hazelcast/hazelcast#23875]
hi， we are using Scriping in Hazelcast Management Center，**_Our Hazelcast platform version is 5.1.1，JDK version is 17_**.  
occurs problem below:
`Response from 168.61.12.126:5701:
java.lang.IllegalArgumentException: Could not find ScriptEngine named 'javascript'. Please add the corresponding ScriptEngine to the classpath of this Hazelcast member
Response from 168.61.12.127:5701:
java.lang.IllegalArgumentException: Could not find ScriptEngine named 'javascript'. Please add the corresponding ScriptEngine to the classpath of this Hazelcast member
Response from 168.61.12.128:5701:
java.lang.IllegalArgumentException: Could not find ScriptEngine named 'javascript'. Please add the corresponding ScriptEngine to the classpath of this Hazelcast member`

**Comment by mdumandag** [comment]
For JDK 15 and onwards check out this doc to explicitly add a dependency for the scripting engines, as the one that comes with the JDK is removed on that release. https://docs.hazelcast.com/management-center/5.2/tools/scripting#scripting-languages
