### ISSUE TITLE
[TPC] com.hazelcast.internal.tpc.nio UnsupportedOperationException failures on Windows

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#23918]
_master_ (commit 4a1c61d836eee0d7da9ae05194877fb1ca799275)

Failed on Windows - MicrosoftJDK11: 
1) Three tests with similar stacktrace:
* test_TCP_KEEPCOUNT
* test_TCP_KEEPIDLE
* test_TCP_KEEPINTERVAL
https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/56/testReport/com.hazelcast.internal.tpc.nio/NioAsyncSocketOptionsTest/
```
java.lang.UnsupportedOperationException: 'TCP_KEEPINTERVAL' not supported
	at java.base/sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:215)
	at com.hazelcast.internal.tpc.nio.NioAsyncSocketOptions.set(NioAsyncSocketOptions.java:148)
	at com.hazelcast.internal.tpc.AsyncSocketOptionsTest.test_TCP_KEEPINTERVAL(AsyncSocketOptionsTest.java:184)
```
2) Other tests with similar stacktrace like in point 1:
`'SO_REUSEPORT' not supported`
* https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/56/testReport/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketConfigTest/test_SO_REUSE_PORT/
* https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/56/testReport/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketTest/test_createCloseLoop_withSameReactor/
* https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/56/testReport/com.hazelcast.internal.tpc.nio/NioAsyncServerSocketTest/test_createCloseLoop_withNewReactor/
Unfortunately, due to the timeout of the build, the standard output can only be found by error details in Jenkins.

**Comment by TomaszGaweda** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/23924
