### ISSUE TITLE
com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#23956]
_master_ (commit 73f152ce08cf99119152cbec8c66d54f42ac6a23)

Failed on ibm-8-fips: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips-nightly/521/

<details><summary>Stacktrace:</summary>

```
18:02:04 [INFO] Running com.hazelcast.internal.tpcengine.nio.NioAsyncSocket_RpcTest_Nightly
02:08:40 Build timed out (after 540 minutes). Marking the build as failed.
02:08:41 Stopping Docker container after build completion
```

</details>

S3 Bucket for stdout: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-fips-nightly/521/

**Comment by sumnerib** [comment]
Failed again on _master_ with ibm-8-fips: https://jenkins.hazelcast.com/job/Hazelcast-master-IbmJDK8-fips-nightly/522/

**Comment by sumnerib** [comment]
Also times out in non-nightly on Windows Microsoft-JDK-11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK11/57/

**Comment by olukas** [comment]
Failed again on _master_ with:
- ibm-8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/527/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest_Nightly/
- ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/98/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest_Nightly/

**Comment by olukas** [comment]
Failed again on _master_ with:
- ibm-8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/531/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest_Nightly/
- ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/99/testReport/com.hazelcast.internal.tpcengine.nio/NioAsyncSocket_RpcTest_Nightly/

**Comment by ramizdundar** [comment]
Closed by:

- https://github.com/hazelcast/hazelcast/pull/24267
- https://github.com/hazelcast/hazelcast/pull/24319
