### ISSUE TITLE
Config: Throw InvalidConfigurationException 

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2402]
Currently a HazelcastException is thrown when we run into configuration failures. But we should throw a InvalidConfigurationException.

See XmlConfigBuilder.build:

 Config build(Config config) {
        try {
            parse(config);
        } catch (Exception e) {
            throw new HazelcastException(e);
        }
        config.setConfigurationFile(configurationFile);
        config.setConfigurationUrl(configurationUrl);
        return config;
    }

**Comment by bilalyasar** [comment]
closed via #4701
