### ISSUE TITLE
3.2.1: MapLoader cannot be used with EntryListener, no EntryEvents are emitted

### ISSUE THREAD

**Issue by ollierob** [hazelcast/hazelcast#2407]
I'm using a MapLoader to populate an IMap on-demand.

On the same IMap I have (later) added an EntryListener. At the simplest, this simply logs the events it is given.

I have noticed that, when a new key/value pair are loaded by the MapLoader, the EntryListener never gets a callback on any of its methods. 

What does/doesn't invoke, or help to invoke, the EntryListener:
- A direct put() or remove() operation on the IMap does.
- Having my MapLoader.loadAllKeys() return a non-empty collection doesn't.

This is very surprising (and somewhat disappointing) behaviour.

**Comment by krasnyt** [comment]
2,5 years - what is the current state? Still backlog? No plans for the future?
