### ISSUE TITLE
HazelcastDataLink should support using path for xml/yaml client config [HZ-2202]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24081]
`HazelcastDataLink` has properties `client_xml`/`client_yml` which expect to have client config as a string content. This is really inconvenient for Hazelcast configured by xml/yaml file. We should support the way how to have this client config in separate file and just use path to that file in property of `HazelcastDataLink` (something like `client_xml_path`/`client_yml_path`).

**Comment by ldziedziul** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/24105
