### ISSUE TITLE
Wrong precondition check in MapProxyImpl#compute

### ISSUE THREAD

**Issue by csemrau** [hazelcast/hazelcast#24083]
By random chance, I noticed that MapProxyImpl#compute checks the `key` twice instead of checking the `remappingFunction`.

https://github.com/hazelcast/hazelcast/blob/dee4a19a2afcc14da031c1f59ee8224b74dc1d8e/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L1256

**Comment by vbekiaris** [comment]
good catch, thanks for creating the issue! Care to prepare a fix PR for that?

**Comment by csemrau** [comment]
Will do. I also noticed that

* `computeIfPresent` has the same parameter mixup in its check. I will fix that as well.
* Several methods, including `submitToKeys`, `submitToKey`, and `executeOnEntries`, do not check their `entryProcessor` argument. Method `executeOnEntries` also does not check its `predicate` argument. Is it correct to add a new null checks in those methods?
https://github.com/hazelcast/hazelcast/blob/dee4a19a2afcc14da031c1f59ee8224b74dc1d8e/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L843

**Comment by vbekiaris** [comment]
@csemrau yes, I think null checks you mentioned should exist.
The `predicate` argument in `executeOnEntries` is actually checked (or maybe you found another place where `predicate` is not checked?)
https://github.com/hazelcast/hazelcast/blob/7c3894b1474dba56648cf10ad8441615486fcdea/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxyImpl.java#L871

**Comment by csemrau** [comment]
My bad! I looked at my local copy of the sources which are for an older release. 🤦 

I will add the missing checks I mentioned above.
