### ISSUE TITLE
Allow up/down arrows to navigate command history

### ISSUE THREAD

**Issue by dimas** [hazelcast/hazelcast#2413]
In the CLI where I can query server with:

ns myMap
m.size

etc - it is very frustrating that you cannot use standard readline-like capabilities (sorry, not sure how this thing is called in Java world) like using UP and DOWN arrows to navigate through the command history to let you quickly repeat last command.

**Comment by mark-addy** [comment]
Would a solution requiring a dependency on the jline library be acceptable?

**Comment by gAmUssA** [comment]
@dimas You can try to use `rlwap` utility http://utopia.knoware.nl/~hlub/uck/rlwrap/#rlwrap

I modified my `clienConsole.sh` with rlwrap

```
rlwrap java -server -Djava.net.preferIPv4Stack=true -cp ../lib/hazelcast-all-3.4.2.jar com.hazelcast.client.console.ClientConsoleApp
```

![test](https://cloud.githubusercontent.com/assets/433085/7946950/ebadd0cc-0947-11e5-91f2-42614f76afc9.gif)

Give it a spin!

**Comment by mdogan** [comment]
`ConsoleApp` and `ClientConsoleApp` are just for demo purposes.

**Comment by gAmUssA** [comment]
@mark-addy you can fork `ConsoleApp` and `ClientConsoleApp` and add jline integration.
We will add them to `hazelcast-code-samples` project.
Thank you
