### ISSUE TITLE
KubernetesClient uses infinite timeout in calls to kubernetes api

### ISSUE THREAD

**Issue by jarekczek** [hazelcast/hazelcast#24163]
**Describe the bug**

KubernetesClient class calls kubernetes api using RestClient. No timeout values are set, what results in infinite timeout. In some environments it produces startup errors.

**Expected behavior**
A default timeout (both read and connect) should be set to a reasonable value.

**To Reproduce**

1. Configure kubernetes cluster using kubernetes api (due to #23208 also dns configuration is affected in released versions)
2. Start the application, put the breakpoint in RestClient.call.
3. Notice the timeout values are equal to 0, that is treated as infinite timeout, as specified in JDK URLConnection class.

**Additional context**

Tested locally on 5.1.5.

Affected configuration with tcp filtering enabled gives the following in logs:
2023-03-31T11:43:46.580+02:00 Couldn't connect to the service, [1] retrying in 1 seconds...
2023-03-31T11:45:57.650+02:00 Couldn't connect to the service, [2] retrying in 2 seconds...
Notice 2 minutes difference between calls.

**Comment by hasancelik** [comment]
Hi @jarekczek,

Thanks for the report 👍 

> due to https://github.com/hazelcast/hazelcast/issues/23208, also DNS configuration is affected in released versions

[The fix](https://github.com/hazelcast/hazelcast/pull/24044) was backported to 5.1.z. It will be released with the next version.

About the main issue, your points make sense. We need to define some proper timeouts for RestClient. 

Would you like to create a PR for the fix? As a starting point, we need to modify timeout durations for each REST call, so [callGet()](https://github.com/hazelcast/hazelcast/blob/5.1.z/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L469) method should be more dynamic.

**Comment by semihbkgr** [comment]
Hi @jarekczek 

I sent a PR to fix the issue you pointed in Kubernetes Discovery Plugin.
