### ISSUE TITLE
Version doc on jet-start.sh is confusing.

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#24233]
When visiting https://jet-start.sh/versions it isn't clear that Jet has merged into Hazelcast. It shows the last version 4.5.4. This gives the impression that Jet has been abandoned.

From the documentation, it should be clear what has happened and how users can get the latest version of Jet.

**Comment by frant-hartm** [comment]
The site used to be maintained by the Jet team members, the source is located here:

https://github.com/hazelcast/hazelcast-jet/tree/gh-pages

@Serdaro would you be able to help here?

I think we should put a notice similar to the one in Github repository:
https://github.com/hazelcast/hazelcast-jet#note-on-hazelcast-5

to the following places:
- the home page https://jet-start.sh/
- the versions page https://jet-start.sh/versions
- the downloade page https://jet-start.sh/download
- add a banner to the documentation https://jet-start.sh/docs/get-started/intro

**Comment by Serdaro** [comment]
Let me check.

**Comment by k-jamroz** [comment]
jet-start.sh was decommisioned
