### ISSUE TITLE
com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_scaling [HZ-3922]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24279]
_master_ (commit f7242148a89972cb339dbf927502859f3c2220dd)

Failed on Windows - MicrosoftJDK11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK11/61/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09b3-75ed-8e80-0001/assertCollectedEventually#1}: java.lang.AssertionError: java.lang.AssertionError: 
Expecting all elements of:
  {"0"=[Order{orderId=0, orderTime=1502982566394, itemtId='Item_407', orderUnits=2.0083688339408265, headers={task.generation=0, task.id=0, current.iteration=0}},
    Order{orderId=1, orderTime=1491189738674, itemtId='Item_81', orderUnits=2.1825127497101366, headers={task.generation=0, task.id=0, current.iteration=1}},
    Order{orderId=2, orderTime=1510255507709, itemtId='Item_9', orderUnits=9.073821605836685, headers={task.generation=0, task.id=0, current.iteration=2}},
    ...
    Order{orderId=3998, orderTime=1504310677398, itemtId='Item_174', orderUnits=4.182419553374104, headers={task.generation=0, task.id=2, current.iteration=3998}},
    Order{orderId=3999, orderTime=1501368514020, itemtId='Item_206', orderUnits=7.4377576653022635, headers={task.generation=0, task.id=2, current.iteration=3999}}]}
to satisfy given requirements, but these elements did not:
"0"=[Order{orderId=0, orderTime=1502982566394, itemtId='Item_407', orderUnits=2.0083688339408265, headers={task.generation=0, task.id=0, current.iteration=0}},
    Order{orderId=1, orderTime=1491189738674, itemtId='Item_81', orderUnits=2.1825127497101366, headers={task.generation=0, task.id=0, current.iteration=1}},
    ...
    Order{orderId=100, orderTime=1511524283592, itemtId='Item_573', orderUnits=7.250618518773185, headers={task.generation=0, task.id=0, current.iteration=100}},
    Order{orderId=101, orderTime=1492751430645, itemtId='Item_691', orderUnits=7.264150501812941, headers={task.generation=0, task.id=0, current.iteration=101}}]
error: 
Expecting actual:
  102
to be greater than:
  1000

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_scaling(KafkaConnectIntegrationTest.java:269)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

Stacktrace is longer than 65536 characters (maximum for GH description) - find full stacktrace in S3 bucket, linked below.

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-MicrosoftJDK11/61/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/59/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by srknzl** [comment]
Failed on PR builder https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/18219/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/62/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-MicrosoftJDK17/63/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by Patras3** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/66/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - OracleJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-OracleJDK11/451/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/51/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

Failed again on _5.3.z_ with:
- corretto-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-CorrettoJDK8/91/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
- Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/125/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by sumnerib** [comment]
Failed again on _master_ with Windows - MicrosoftJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-Windows-MicrosoftJDK17/71/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by ihsandemir** [comment]
another failure on PR builder at [here](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/19391/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/)

```
Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0a30-257e-9b80-0001/assertCollectedEventually#1}: java.lang.AssertionError: java.lang.AssertionError: 
Expecting all elements of:
...
...
```

**Comment by frant-hartm** [comment]
Temporarily ignored in #24782

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/130/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by nishaatr** [comment]
Failed again on 5.3.z PR build - https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/19678/
I believe this is related

**Comment by olukas** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/137/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/145/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-OracleJDK8/147/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/149/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/150/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with corretto-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-CorrettoJDK8/120/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Reopening as issue occurred again on: _5.3.z_ (commit fba7eff9bcbd8560909312a38dffec8cc21b1d73)
with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/157/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 
Job was expected to complete with AssertionCompletedException, but completed with: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0b30-c4ae-c240-0001/assertCollectedEventually#0}: java.lang.AssertionError: java.lang.AssertionError: 
Expecting all elements of:
  {"0"=[Order{orderId=0, orderTime=1498655247819, itemtId='Item_68', orderUnits=0.2267591362049627, headers={task.generation=0, task.id=0, current.iteration=0}},
    Order{orderId=1, orderTime=1511640979311, itemtId='Item_2', orderUnits=1.7020681317731665, headers={task.generation=0, task.id=0, current.iteration=1}},
    Order{orderId=2, orderTime=1504079559920, itemtId='Item_7', orderUnits=6.013164413801434, headers={task.generation=0, task.id=0, current.iteration=2}},
    Order{orderId=3, orderTime=1503474220105, itemtId='Item_885', orderUnits=0.6085313622116213, headers={task.generation=0, task.id=0, current.iteration=3}},
    Order{orderId=4, orderTime=1516951848620, itemtId='Item_9', orderUnits=0.6795348235080203, headers={task.generation=0, task.id=0, current.iteration=4}},
    Order{orderId=5, orderTime=1498107818795, itemtId='Item_5', orderUnits=0.294859004165562, headers={task.generation=0, task.id=0, current.iteration=5}},
    Order{orderId=6, orderTime=1502245031357, itemtId='Item_851', orderUnits=2.5026727222091436, headers={task.generation=0, task.id=0, current.iteration=6}},
    Order{orderId=7, orderTime=1514039502762, itemtId='Item_15', orderUnits=4.598275743396208, headers={task.generation=0, task.id=0, current.iteration=7}},
    Order{orderId=8, orderTime=1500917290582, itemtId='Item_3', orderUnits=4.389633679750138, headers={task.generation=0, task.id=0, current.iteration=8}},
...
    Order{orderId=713, orderTime=1516410216089, itemtId='Item_83', orderUnits=6.495012280265072, headers={task.generation=0, task.id=2, current.iteration=713}},
    Order{orderId=714, orderTime=1499535353479, itemtId='Item_2', orderUnits=0.3934555025523052, headers={task.generation=0, task.id=2, current.iteration=714}},
    Order{orderId=715, orderTime=1507591567057, itemtId='Item_80', orderUnits=7.220770999011121, headers={task.generation=0, task.id=2, current.iteration=715}}]
error: 
Expecting actual:
  716
to be greater than:
  1000

	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest.test_scaling(KafkaConnectIntegrationTest.java:309)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>



Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Windows-OracleJDK8/157/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Windows-OracleJDK8/158/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with corretto-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/130/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIT/test_scaling/

**Comment by Patras3** [comment]
Failed again on _5.3.z_ with openjdk-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK8/126/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by olukas** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/162/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with openjdk-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZuluJDK11/130/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by AleksPeychev** [comment]
Failed again on _5.3.z_ with openjdk-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZuluJDK11/132/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by sumnerib** [comment]
Failed again on _5.3.z_ with Windows - OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/167/testReport/junit/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

**Comment by Patras3** [comment]
This comment was automatically generated to summarize test results for the last 30 days.

```

For branch: 5.3.z
Builds between : 2024-07-05 21:09 - 2024-07-26 21:09
Jobs: 1, Runs: 4, Passed: 4, Failed: 0, Skipped: 0, Fail Ratio: 0.00%
Run on:
+------------------------------------------------+
| JDK      | PASSED | FAILED | SKIPPED |  RATIO  |
+------------------------------------------------+
| oracle-8 |   4    |   0    |    0    |   0.00% |
+------------------------------------------------+

Builds Timeline:
2024-07-26 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/13/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
2024-07-19 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/12/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
2024-07-12 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/11/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/
2024-07-05 21:09 - PASSED (oracle-8):
    https://jenkins.hazelcast.com/job/Hazelcast-5.3.z-OracleJDK8/10/testReport/com.hazelcast.jet.kafka.connect/KafkaConnectIntegrationTest/test_scaling/

----------------------------------------
```

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
