### ISSUE TITLE
Unable to create streaming type mappings using 'Mongo' DATA CONNECTION [HZ-2312]

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#24302]
**Describe the bug**
Given a HZ cluster with a `DATA CONNECTION` of type `Mongo`, there isn't a way to create a mapping with this DC that provides unbounded results (i.e. `MongoStream`).

**Expected behavior**
A command like the following will create the "streaming" type mapping:

```
CREATE MAPPING movies_stream EXTERNAL NAME movies
DATA CONNECTION mongodb CONNECTOR TYPE MongoStream
```

Instead the `CONNECTOR` syntax isn't recognized.

**To Reproduce**

1. Create a DATA CONNECTION to MongoDB
```
CREATE OR REPLACE DATA CONNECTION mongodb
TYPE mongo
OPTIONS (
  'connectionString' = 'mongodb://localhost:27017'
)
```

2. Attempt to create mapping
```
CREATE MAPPING movies_stream EXTERNAL NAME movies
DATA CONNECTION mongodb CONNECTOR TYPE MongoStream
```

Error:

```
Encountered "CONNECTOR" at line 31, column 25.
Was expecting one of:
    <EOF> 
    "OBJECT" ...
    "OPTIONS" ...
    ";" ...
    "." ...
```

**Comment by k-jamroz** [comment]
And `OBJECT TYPE` currently seems to be ignored
