### ISSUE TITLE
map wildcard matching is confusing

### ISSUE THREAD

**Issue by galvarez1** [hazelcast/hazelcast#2431]
Just via some testing:

I build up a Map of MapConfig objects programmatically (each MapConfig has its own MapStoreFactory) that are wildcarded:

mapConfigs.put( "Foo*", mapConfigFoo );
mapConfigs.put("FooBar*", mapConfigFooBar );

But i find that if i look for a map called "Foo-1" or "FooBar-1", i get mapConfigFoo in both cases. I would expect in the "FooBar-1" case, i'd get back mapConfigFooBar.

Now, when i lower case everything:

mapConfigs.put( "foo*", mapConfigFoo );
mapConfigs.put("foobar*", mapConfigFooBar );

I do get what i would expect: if i look for "foo-1", i get back mapConfigFoo, and when i look for "foobar-1" i get back MapConfigFooBar.

Now i understand that the behavior is because "first one wins"; it makes sense in a way, but it can be confusing and can trip people up. A "best match" wins would be a better approach.

**Comment by Donnerbart** [comment]
The issue should be resolved with #4316 in Hazelcast 3.5.
