### ISSUE TITLE
DROP DATA CONNECTION which is used in some mapping breaks SQL [HZ-2324]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24337]
**Describe the bug**
When data connection is used for some mapping and it's dropped then it breaks the whole SQL. SQL starts to print message like `Data connection 'mysql' not found` to every command. 

It works fine if data connection is dropped and is not used by any mapping.

**Expected behavior**
When I drop data connection which is used in some mapping I would expect one of following behavior:
- do not allow to drop it since it's used by some mapping
- drop it but in that case drop also all related mappings

I'm not sure what should be better.

**To Reproduce**
Start HZ and MySQL server. Set database `mydb` with table `people` in MySQL server:
```
CREATE DATABASE mydb;
use mydb;
CREATE TABLE people (id INT PRIMARY KEY, name VARCHAR(100));
```

Start hz-cli and create data connection, create mapping and remove data connection. Then run whatever command:
```
sql> CREATE DATA CONNECTION mysql TYPE JDBC OPTIONS('jdbcUrl'='jdbc:mysql://localhost:3306/mydb', 'username'='root', 'password'='123');
OK
sql> CREATE MAPPING people DATA CONNECTION "mysql";
OK
sql> DROP DATA CONNECTION mysql;
OK
sql> SHOW DATA CONNECTIONS;
Data connection 'mysql' not found
sql> SHOW MAPPINGS;
Data connection 'mysql' not found
sql> dowhatever;
Data connection 'mysql' not found
```

**Comment by Fly-Style** [comment]
Closed with https://github.com/hazelcast/hazelcast/pull/24388
