### ISSUE TITLE
Unreachable JDBC data connection slows down other SQL commands [HZ-2326]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24338]
**Describe the bug**
In case when JDBC data connection becomes unreachable and it's used in any mapping then also other SQL commands are slowed down and wait for some timeout (by default 30 seconds for MySQL). I tried that with MySQL, but I expect it will behave the same for other databases and maybe even for other type of data connections.

Example of SQL commands which are affected:
- `SHOW DATA CONNECTIONS;`
- `SHOW MAPPINGS;`
- creating IMap mapping: `CREATE MAPPING cities (__key INT, counteries VARCHAR, cities VARCHAR) TYPE IMap OPTIONS('keyFormat'='int','valueFormat'='json-flat');`
- insert something into IMap: `INSERT INTO cities VALUES (1, 'United Kingdom','London');`

Example of SQL command which is not affected:
- read something from IMap: `SELECT * FROM cities;`

**Expected behavior**
It should block only SQL commands which really needs to access given data connection.

**To Reproduce**

1. Start HZ and MySQL server.
2. Create data connection and use it JDBC mapping
3. Kill MySQL server.
4. Try to run any of mentioned above SQL commands.

**Comment by k-jamroz** [comment]
Ultimate solution to that problem could be lazy catalog (calcite table resolver)
