### ISSUE TITLE
SQL Connector option to set preferred local parallelism

### ISSUE THREAD

**Issue by hhromic** [hazelcast/hazelcast#24357]
**Please describe the problem you are trying to solve**

I am migrating a Java-based Hazelcast Jet Pipeline we have to use Hazelcast SQL queries instead (mainly to be able to provide SQL queries at runtime instead of having to develop Java code for small changes in our deployments).

Our original Jet Pipeline uses Kafka as source and sink and performs data aggregation and enrichment.
One of the key aspects of our original Jet Pipeline is the ability to configure the local parallelism of the Kafka source. This is to provide flexibility during topic partitions design in Kafka and Jet replicas deployment. As a reminder, the default local parallelism for Kafka source processors is `4`. If `numJetMembers x localParallelism > topicPartitions` then there will be idle processors.

While migrating our pipeline to use Hazelcast SQL queries instead, I noticed that there is no way to configure the preferred local parallelism to use in an SQL Connector with the `CREATE MAPPING` statement. Instead, the connector is hard-coded to use the default local parallelism for Kafka sources:
https://github.com/hazelcast/hazelcast/blob/22c3efb6bfc202a6288e147d5d8842024efde8b9/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaSqlConnector.java#L133-L135

**Please describe the desired behavior**

I think there should be an `OPTIONS` key, e.g. `preferredLocalParallelism`, in the `CREATE MAPPING` statement to set the preferred local parallelism of a connector. Of course, each connector's implementation is free to use it or not, hence why is "preferred".

In this way, we can precisely configure the number of Kafka processors per Jet member for distributed consumption, instead of the current hard-coded value of `4`.

**Describe alternatives you've considered**

I searched in the documentation if it's possible to create a Source using the Jet API (as before) and use that as a source in `CREATE MAPPING`, but this does not seem to be possible either.

I then searched the source code, where it seems that indeed it is not possible to configure the preferred local parallelism of a connector.

**Comment by k-jamroz** [comment]
Slack discussion: https://hazelcastcommunity.slack.com/archives/C0159HP69E3/p1682500149633239
