### ISSUE TITLE
Non-shared JDBC data connection cannot be used in SQL mappings [HZ-2378]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24404]
**Describe the bug**
When mapping is trying to be created for JDBC data connection which is not shared then mapping creation failed. No exception is thrown on server side. Output of `hz-cli` prints:
```
sql> CREATE MAPPING people DATA CONNECTION "mysql";
Could not execute readDbFields for table com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector$ExternalJdbcTableName@1c24c521
```

**Expected behavior**
Mapping is created and uses non-shared client.

**To Reproduce**

Start MySQL and create database `mydb` with table `people`.

Try to create mapping through `hz-cli`:
```
sql> CREATE DATA CONNECTION mysql TYPE JDBC NOT SHARED OPTIONS('jdbcUrl'='jdbc:mysql://localhost:3306/mydb', 'username'='root', 'password'='123');
OK
sql> CREATE MAPPING people DATA CONNECTION "mysql";
Could not execute readDbFields for table com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlConnector$ExternalJdbcTableName@aa6c17c
```

Optional - you can try that everything works fine if non-shared is used:
```
sql> CREATE DATA CONNECTION mysql2 TYPE JDBC SHARED OPTIONS('jdbcUrl'='jdbc:mysql://localhost:3306/mydb', 'username'='root', 'password'='123');
OK
sql> CREATE MAPPING people DATA CONNECTION "mysql2";
OK
```

**Comment by orcunc** [comment]
@frant-hartm You need to call validate from the constructor. Otherwise when I execute, 
sql> CREATE DATA CONNECTION mysql TYPE JDBC NOT SHARED OPTIONS('jdbcUrll'='jdbc:mysql://localhost:3306/db', 'username'='
root', 'password'='root');
OK

See the typo in the **jdbcUrll**
