### ISSUE TITLE
SHOW DATA CONNECTIONS prints 'java.util.ArrayList cannot be cast to com.hazelcast.core.HazelcastJsonValue' [HZ-2384]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24415]
**Describe the bug**
If any data connection is created then `SHOW DATA CONNECTIONS;` prints `java.util.ArrayList cannot be cast to com.hazelcast.core.HazelcastJsonValue`.

Failed in revision ebb6c97. It seems to be caused by any of latest commits (it worked fine ~2days ago).

**Expected behavior**
It should show data connections.

**To Reproduce**
```
sql> SHOW DATA CONNECTIONS;
+--------------------+----------------------------------------+
|name                |types                                   |
+--------------------+----------------------------------------+
+--------------------+----------------------------------------+
0 row(s) selected
sql> CREATE DATA CONNECTION mysql TYPE JDBC OPTIONS('jdbcUrl'='jdbc:mysql://localhost:3306/mydb', 'username'='root', 'password'='123');
OK
sql> SHOW DATA CONNECTIONS;
java.util.ArrayList cannot be cast to com.hazelcast.core.HazelcastJsonValue
```

**Comment by k-jamroz** [comment]
I am thinking about reverting the change to SHOW DATA CONNECTIONS - we do not show connector type, sole OBJECT TYPE does not make much sense.

**Comment by k-jamroz** [comment]
Caused by #24356
