### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest.given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24423]
_master_ (commit 0609cc1f35ad1d4f74e3f37cf426895fd3a40c77)

Failed on oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/24/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  [Row{[testDatabaseRef, [Table]]}, Row{[testDatabaseRef2, [Table]]}]
to contain exactly in any order:
  [Row{[testDatabaseRef, [Table]]}]
but the following elements were unexpected:
  [Row{[testDatabaseRef2, [Table]]}]

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:424)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:401)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:361)
	at com.hazelcast.jet.sql.impl.connector.jdbc.MappingJdbcSqlConnectorTest.given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success(MappingJdbcSqlConnectorTest.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: createMappingExternalFieldDoesNotExist in 0.017 seconds.
Started Running Test: given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success
05:26:14,353  INFO |given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
05:26:14,353  INFO |given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
05:26:14,354  INFO |given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
05:26:14,354  INFO |given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230428', buildNumber=20230428, revision=0609cc1, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success(com.hazelcast.jet.sql.impl.connector.jdbc.postgres.PostgresMappingJdbcSqlConnectorTest):'
05:26:10, accumulated pauses: 714 ms, max pause: 667 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/24/

**Comment by olukas** [comment]
Failed again on _master_ with:
- zing-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/29/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
- oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/45/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
- openjdk-19: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OpenJDK-sts-nightly/27/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/

**Comment by orcunc** [comment]
This will be fixed by https://hazelcast.atlassian.net/browse/HZ-2378

**Comment by olukas** [comment]
Failed again on _master_ with:
- ibm-8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/539/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
- ibm-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/103/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
- oracle-8 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/46/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.postgres/PostgresMappingJdbcSqlConnectorTest/given_mappingIsDeclaredWithDataConn_when_DataConnWasRemoved_then_success/
