### ISSUE TITLE
Shared kafka data connection doesn't use shared client [HZ-2395]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24442]
**Describe the bug**
When shared kafka data connection is used it creates a new client for producing every item.

**Expected behavior**
It should use shared client.

**To Reproduce**
If you insert into shared kafka data connection through SQL the new client is created for every insert. It can be reproduced by:
```
sql> CREATE DATA CONNECTION kafka TYPE KAFKA SHARED OPTIONS('bootstrap.servers' = '127.0.0.1:9092', 'key.serializer' = 'org.apache.kafka.common.serialization.StringSerializer', 'value.serializer' = 'org.apache.kafka.common.serialization.StringSerializer');
OK
CREATE MAPPING users DATA CONNECTION "kafka" OPTIONS ('keyFormat' = 'varchar', 'valueFormat' = 'varchar');
OK
sql> INSERT INTO users VALUES ('a','a');
OK
sql> INSERT INTO users VALUES ('a','a');
OK
...
```

**Comment by Fly-Style** [comment]
Closed with https://github.com/hazelcast/hazelcast/pull/24441
