### ISSUE TITLE
CVEs in jackson dependency in version 4.1.10 of hazelcast

### ISSUE THREAD

**Issue by Subrhamanya** [hazelcast/hazelcast#24477]
**Describe the bug**

hazelcast version 4.1.10 is pulling jackson version 2.14.0 which is flagged with a high severity vulnerability.

Resolution for it is to uplift to 2.15.0

Link for reference --> https://github.com/FasterXML/jackson-core/pull/827

Is there any plan to release next version of hazelcast 4.1.x to resolve this?

**Comment by frant-hartm** [comment]
The 4.1.z branch is not maintained anymore (neither for 4.2.z if that matters). If you have a subscription please follow the official channels.

**Comment by Subrhamanya** [comment]
@frant-hartm I don't have a subscription. At least can it be uplifted in the newer version of hazelcast?

https://github.com/hazelcast/hazelcast/blob/master/pom.xml#L107

**Comment by frant-hartm** [comment]
Yes, we will update it there and in all supported versions - 5.0.z, 5.1.z, 5.2.z and 5.3.z

**Comment by QWAJSGGF** [comment]
@frant-hartm is there any timeline that hazelcast planned for 5.3.x version to get this fix?

**Comment by Subrhamanya** [comment]
@frant-hartm Is there any timeline for 5.3.x to get this fix? The reason is it got fixed for 4.2.x a couple of days ago. We can submit the same for our client if it's very far.

**Comment by Prachi-Srivastava-13** [comment]
@frant-hartm Can we get a response to the above question? When will the fix be issue on 5.x versions?

**Comment by AyberkSorgun** [comment]
Hello @Subrhamanya @Prachi-Srivastava-13 Hazelcast v5.3.1 is released, including jackson-core fix https://docs.hazelcast.com/hazelcast/5.3/release-notes/5-3-1
5.0.z, 5.1.z, 5.2.z releases are currently in the pipeline
