### ISSUE TITLE
StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart [HZ-2795]

### ISSUE THREAD

**Issue by arodionov** [hazelcast/hazelcast#24578]
5.3.z version, 5.4 version
The job `Hazelcast-pr-builder` of your PR failed. (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/18528/Hazelcast-pr-builder-18528.zip), [artifacts](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/18528/Hazelcast-pr-builder-18528.zip)).

<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart:247->testWithJobRestart:313->testWithJobRestart:347->HazelcastTestSupport.assertTrueEventually:1304->HazelcastTestSupport.assertTrueEventually:1285->lambda$testWithJobRestart$4:347 expected:<300> but was:<324>
[INFO] 
[ERROR] Tests run: 51, Failures: 1, Errors: 0, Skipped: 1
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

_Originally posted by @hz-devops-test in https://github.com/hazelcast/hazelcast/issues/24575#issuecomment-1551025529_

**Comment by arodionov** [comment]
Failed again with master PR-builder (Hazelcast internal details: [build log](https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/18532/Hazelcast-pr-builder-18532.zip)):
`[ERROR]   StreamKafkaPTest.when_processingGuaranteeNone_then_continueFromBeginningAfterJobRestart:247->testWithJobRestart:313->testWithJobRestart:347->HazelcastTestSupport.assertTrueEventually:1304->HazelcastTestSupport.assertTrueEventually:1285->lambda$testWithJobRestart$4:347 expected:<300> but was:<312>
`

**Comment by k-jamroz** [comment]
Test and feature added in https://github.com/hazelcast/hazelcast/pull/21546

**Comment by arodionov** [comment]
It seems the same TF 
https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/18617/
`[ERROR]   StreamKafkaPTest.when_processingGuaranteeNoneWithConsumerGroup_then_continueFromLastReadMessageAfterJobRestart:267->testWithJobRestart:350->HazelcastTestSupport.assertTrueEventually:1304->HazelcastTestSupport.assertTrueEventually:1285->lambda$testWithJobRestart$4:350 expected:<200> but was:<196>`

**Comment by TomaszGaweda** [comment]
I cannot reproduce the issue after 525 retries :/
