### ISSUE TITLE
FIPS test failures with OpenJ9-11 [HZ-2500]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24628]
After update FIPS jobs from IBM JDK 8 to OpenJ9-11 we have some related test failures:
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-fips/91/testReport/

Following tests failed with various reasons:
- `com.hazelcast.jet.kafka.connect.KafkaConnectIntegrationTest`
- `com.hazelcast.jet.kinesis.KinesisFailureTest`
- `com.hazelcast.jet.kinesis.KinesisIntegrationTest`
- `com.hazelcast.jet.mongodb.dataconnection.MongoDataConnectionAuthTest.should_connect_with_credentials`
- `com.hazelcast.client.config.XmlClientConfigImportVariableReplacementTest.testReplacers`
- `com.hazelcast.client.config.YamlClientConfigImportVariableReplacementTest.testReplacers`
- `com.hazelcast.config.XmlConfigImportVariableReplacementTest.testReplacers`
- `com.hazelcast.config.YamlConfigImportVariableReplacementTest.testReplacers`
- `com.hazelcast.dataconnection.impl.ListResourcesTest.shouldListResourcesDefaultAndNonDefaultSchema`
- `com.hazelcast.spi.utils.RestClientTest.tls13SupportCustomCacert`
- `com.hazelcast.spi.utils.RestClientTest.tls13SupportDefaultCacert`

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Openj9-11-fips/91/

**Comment by olukas** [comment]
Failed again on _master_ with openj9-11 (FIPS mode): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11-fips/93/testReport/

It seems to fail constantly on FIPS.

**Comment by JamesHazelcast** [comment]
I've carried the torch as far as I can on this one - please [refer to my Jira comment](https://hazelcast.atlassian.net/browse/HZ-2500?focusedCommentId=78730) for details on my findings.

**Comment by ihsandemir** [comment]
Another failure for [com.hazelcast.jet.kinesis.KinesisFailureTest.com.hazelcast.jet.kinesis.KinesisFailureTest](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/19161/testReport/junit/com.hazelcast.jet.kinesis/KinesisFailureTest/com_hazelcast_jet_kinesis_KinesisFailureTest/)

See [comment](https://github.com/hazelcast/hazelcast/pull/24944#issuecomment-1620147416) for artifacts

**Comment by olukas** [comment]
We don't run FIPS test suite any more. Closing.
