### ISSUE TITLE
Update Jackson Version to 2.15.1 in 3.12.z

### ISSUE THREAD

**Issue by bkoripalli** [hazelcast/hazelcast#24687]
**Describe the bug**
we are using hazelcast 3.12.13 with vertx 3.9.x  and it has security vulnerability related Jackson 2.14.1, we can't upgrade hazelcast 4 because vertx3.9.x doesn't support hazelcast4 So please update the jackson version to 2.15.1 in 3.12.z branch

**Comment by otramony** [comment]
Hello @frant-hartm. Any plans for this request? Thank you.

**Comment by frant-hartm** [comment]
Hi,

3.12.x is not maintained anymore. We strongly encourage all users to upgrade to the latest version.

If you have an extended support contract you can reach us via our support channels.
