### ISSUE TITLE
com.hazelcast.jet.sql_slow.SqlBasicSlowTest.testSelect

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24681]
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on oracle-11 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/49/testReport/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

A lot of various variant of test `com.hazelcast.jet.sql_slow.SqlBasicSlowTest.testSelect` failed.

<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException
	at com.hazelcast.jet.SimpleTestInClusterSupport.instance(SimpleTestInClusterSupport.java:184)
	at com.hazelcast.jet.sql.SqlTestSupport.createMapping(SqlTestSupport.java:531)
	at com.hazelcast.jet.sql.SqlBasicTest.testSelect(SqlBasicTest.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testSelect[cursorBufferSize:1, dataSetSize:256, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:OBJECT] in 1.965 seconds.
Started Running Test: testSelect[cursorBufferSize:1, dataSetSize:256, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:BINARY]
BuildInfo right after testSelect[cursorBufferSize:1, dataSetSize:256, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:BINARY](com.hazelcast.jet.sql_slow.SqlBasicSlowTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230528', buildNumber=20230528, revision=02e4cbb, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testSelect[cursorBufferSize:1, dataSetSize:256, serializationMode:DATA_SERIALIZABLE, inMemoryFormat:BINARY](com.hazelcast.jet.sql_slow.SqlBasicSlowTest):'
16:59:35, accumulated pauses: 3785 ms, max pause: 1957 ms, pauses over 1000 ms: 2


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/49/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-force-offload/52/testReport/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/53/testReport/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

**Comment by olukas** [comment]
Seems to fail constantly with force-offload.

**Comment by Patras3** [comment]
Still fails:
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/57/testReport/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/59/testReport/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

**Comment by k-jamroz** [comment]
Yet another example of https://github.com/hazelcast/hazelcast/issues/24862#issuecomment-1724042722
SqlSTSInnerNonEquiJoinFaultToleranceStressTest failed, likely before (lack of console output).

```
 <testcase name="" classname="com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest" time="890.456">
    <error message="test timed out after 900 seconds" type="org.junit.runners.model.TestTimedOutException">```

Another indicator
```
Finished Running Test: testSelect[cursorBufferSize:4,096, dataSetSize:4,096, serializationMode:IDENTIFIED_DATA_SERIALIZABLE, inMemoryFormat:BINARY] in 3.196 seconds.
Started Running Test: testSelect[cursorBufferSize:4,096, dataSetSize:4,096, serializationMode:PORTABLE, inMemoryFormat:OBJECT]
17:00:21,766  INFO || - [AppInfoParser] kafka-admin-client-thread | adminclient-2 - App info kafka.admin.client for adminclient-2 unregistered
17:00:21,766  INFO || - [AdminMetadataManager] kafka-admin-client-thread | adminclient-2 - [AdminClient clientId=adminclient-2] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited. Call: fetchMetadata
17:00:21,766  INFO || - [KafkaAdminClient] kafka-admin-client-thread | adminclient-2 - [AdminClient clientId=adminclient-2] Timed out 1 remaining operation(s) during close.
17:00:21,767  INFO || - [Metrics] kafka-admin-client-thread | adminclient-2 - Metrics scheduler closed
17:00:21,767  INFO || - [Metrics] kafka-admin-client-thread | adminclient-2 - Closing reporter org.apache.kafka.common.metrics.JmxReporter
17:00:21,767  INFO || - [Metrics] kafka-admin-client-thread | adminclient-2 - Metrics reporters closed
17:00:21,767  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass
17:00:21,779  INFO || - [LifecycleService] Thread-330 - hz.client_21 [dev] [5.4.0-SNAPSHOT] HazelcastClient 5.4.0-SNAPSHOT (20230730 - 3697857) is SHUTTING_DOWN
```

During `testSelect` execution Kafka is shut down if `@AfterClass`. `SqlBasicSlowTest` does not use Kafka. The output might be however mangled (I don't remember if we use async logging).

**Comment by AleksPeychev** [comment]
A lot variants of SqlBasicSlowTest Failed again on _5.3.z_ with oracle-8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.3.z-OracleJDK8-nightly/9/testReport/junit/com.hazelcast.jet.sql_slow/SqlBasicSlowTest/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
