### ISSUE TITLE
TS hs_err_pid jvm freeze

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#24797]
jvm freeze test,  all members crashed

https://jenkins.hazelcast.com/view/t-store/job/freeze-tstore-All/19/console

/disk1/workspace/freeze-tstore-All/5.4.0-SNAPSHOT/2023_06_12-21_42_53/tstore/tstore-reg

./output/HZ/HzMember2HZ/hs_err_pid10841.log
# Problematic frame:
# J 6899 c2 com.hazelcast.internal.memory.impl.AlignmentAwareMemoryAccessor.getLong(J)J (29 bytes) @ 0x0000ffff6c955b80 [0x0000ffff6c955b40+0x0000000000000040]

./output/HZ/HzMember3HZ/hs_err_pid11161.log
# Problematic frame:
# J 11130 c2 com.hazelcast.internal.tstore.hybridlog.impl.LogBasedHybridLogIterator.advanceToNextSlot()V (205 bytes) @ 0x0000ffff9c8a0e98 [0x0000ffff9c8a0e00+0x0000000000000098]

./output/HZ/HzMember1HZ/hs_err_pid11337.log
# Problematic frame:
# J 11241 c1 com.hazelcast.internal.tstore.hybridlog.impl.LogBasedHybridLogIterator.calculateNextLogicalAddress(J)J (216 bytes) @ 0x0000ffff9d813aec [0x0000ffff9d813640+0x00000000000004ac]

**Comment by ahmetmircik** [comment]
it seems fixed in latest runs: https://jenkins.hazelcast.com/view/t-store/job/freeze-tstore-All/52/
