### ISSUE TITLE
TS hs_err_pid jvm kill test 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#24798]
jvm kill test members crashed

https://jenkins.hazelcast.com/view/t-store/job/kill-tstore-All/20/console

/disk1/workspace/kill-tstore-All/5.4.0-SNAPSHOT/2023_06_12-21_42_49/tstore/tstore-reg

HazelcastException: java.lang.AssertionError: {hlog:'imap/mapBak1HDtstore0/p032',epoch:3035462} - Read 0 bytes for log:0x0020fb3c0(page:32,offset:1029056)

./output/HZ/HzMember2HZ/hs_err_pid30885.log
# Problematic frame:
# J 10419 c1 com.hazelcast.internal.tstore.hybridlog.impl.LogBasedHybridLogIterator.calculateNextLogicalAddress(J)J (216 bytes) @ 0x0000ffff7df70d80 [0x0000ffff7df708c0+0x00000000000004c0]

./output/HZ/HzMember3HZ/hs_err_pid2446.log
# Problematic frame:
# J 9642 c2 com.hazelcast.internal.tstore.compaction.PartitionCompactor.compact(Z)V (235 bytes) @ 0x0000ffff88624f4c [0x0000ffff88624bc0+0x000000000000038c]

./output/HZ/HzMember4HZ/hs_err_pid32696.log
# Problematic frame:
# J 6382 c2 com.hazelcast.internal.util.HashUtil.MurmurHash3_x64_64(Lcom/hazelcast/internal/util/HashUtil$LoadStrategy;Ljava/lang/Object;JII)J (761 bytes) @ 0x0000ffff688e6820 [0x0000ffff688e5c40+0x0000000000000be0]

**Comment by Danny-Hazelcast** [comment]
using 
        <property name="hazelcast.tiered.store.max.log.file.size.in.mb">4</property>

**Comment by ahmetmircik** [comment]
have not seen lately, possibly fixed by latest work.
