### ISSUE TITLE
Hazelcast Platform: evicted entry from the distributed map should be removed from the near cache too.

### ISSUE THREAD

**Issue by rickymemphis** [hazelcast/hazelcast#24857]
**Bug Description**
Using Hazelcast 5.0.2 I have a distributed map with near cache configured (no map store), if I put an entry in the distributed map with a TTL the entry is correctly removed from the distributed map when the TTL expires but it is not removed from the near cache.

**Expected behavior**
The expected behavior is that when the entry expires and it is removed from the distributed map, it is also removed from the the near caches of all the nodes.

**To Reproduce**
Below a code snippet to describe the expected behavior; after the ttl expires, there are no entries in the distributed map, however the entry can still be retrieved.
```
// add map entry
String key = "k1";
map.put(key, "v1", ENTRY_TTL, TimeUnit.SECONDS);

// get map entry in the near cache
String retrievedValue = map.get(key);
Assertions.assertNotNull(retrievedValue);

// wait enough for the entry to be evicted in the distributed map
Sleep.waitFor(ENTRY_TTL * 2 * 1000);
long count = map.getLocalMapStats().getOwnedEntryCount();
Assertions.assertEquals(0, count);

// the map entry is returned from the near cache
retrievedValue = map.get(key);
Assertions.assertNull(retrievedValue);
```

**Additional context**
- I am currently using Hazelcast 5.0.2 and Java openjdk 11.0.13 2021-10-19

Thanks,
Riccardo

**Comment by ahmetmircik** [comment]
Hi @rickymemphis, 

This is a known issue, you can vote for it here: https://github.com/hazelcast/hazelcast/issues/10975

I'm closing this issue in favor of https://github.com/hazelcast/hazelcast/issues/10975.

Thanks,
