### ISSUE TITLE
com.hazelcast.sql.impl.client.SqlResubmissionTest fails with OOME

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#24862]
_master_ (commit 1d92aa7797ee1493223bd4482ec31303ef88446a)

Failed on ZingJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/37/console

<details><summary>Console output:</summary>

```
17:53:21 [INFO] Running com.hazelcast.sql.impl.client.SqlResubmissionTest
18:11:15 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
18:13:27 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
18:15:02 Exception in thread "timeout-check-timer" java.lang.OutOfMemoryError: Java heap space
```

</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK11-nightly/37/Hazelcast-master-ZingJDK11-nightly-37.zip

**Comment by olukas** [comment]
Failed on master on ZingJDK11: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK11-nightly/47/console

<details><summary>Console output:</summary>

```
01:21:00 [INFO] Running com.hazelcast.sql.impl.client.SqlResubmissionTest
01:47:06 Exception in thread "timeout-check-timer" 
01:47:14 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
01:47:52 
01:47:52 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "timeout-check-timer"
01:48:14 Exception in thread "ping-timer-10s" 
01:48:29 Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "ping-timer-10s"
04:44:54 Build timed out (after 640 minutes). Marking the build as failed.
```

</details>

**Comment by k-jamroz** [comment]
Could we stop reporting failures that happened AFTER another heavy test timed out? They are very often some crazy false positives do to stray instances being terminated later (during next test, so they might be part of cluster in that test!). Also static state in tests inheriting from `SimpleTestInClusterSupport` or other tests using similar approach (shared cluster managed by the base class).

**Comment by k-jamroz** [comment]
Closing as false positive (at least the later failure is false positive)
