### ISSUE TITLE
Slow MapListener can crash hz

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2487]
I have been working on reproducing an issue and playing with settings. I have a 3 node cluster (3 different EC2 machines), and map listeners and a configurable delay in the map listener. If I set the delay to e.g. 1 second I run into OperationTimeoutException. This is with Hazelcast 3.2.1, ubuntu 12.04, Oracle Java 1.7.0_55. The Stabilizer test that reproduces this issue, can be found here

https://github.com/hazelcast/stabilizer-atlassian

It takes +/- 10 minutes to get the exception.

[edit]
With Hazelcast 3.3-SNAPSHOT the issue is still happening. For this particular run I didn't get an exception btw, but the worker JVM's stopped responding because of OOME. I'm now downloading the heapdump to figure out what is accumulating.

**Comment by bwzhang2011** [comment]
@degerhz, any progress with such issue ?

**Comment by degerhz** [comment]
@bwzhang2011, it is in our backlog but there is no commitment for any release so far.

**Comment by pveentjer** [comment]
Afaik @ahmetmircik made changes to the design. I don't know if it still can happen.
