### ISSUE TITLE
IMap behaviour for containsKey operation with near cache enabled

### ISSUE THREAD

**Issue by visheshruparelia** [hazelcast/hazelcast#24982]
Creating this issue as per the request by @ahmetmircik  on slack. 

As per the documentation here: https://docs.hazelcast.com/imdg/4.2/performance/near-cache, only `map.get()` requests go to near cache. I would like to understand how the `map.containsKey()` operation works -> whether it consults the near cache first or directly makes a network call to the partition owner of that key. 

Quoting from documentation here: 

> Near Cache works only when you access data via map.get(k) or cache.get(k) methods. Data returned using a predicate is not stored in the Near Cache.

**Comment by orcunc** [comment]
You can see 
https://github.com/hazelcast/hazelcast-mono/blob/5f360c2043e01c6abe6160eaa317c9c2c065e977/hazelcast/hazelcast/src/main/java/com/hazelcast/client/map/impl/nearcache/NearCachedClientMapProxy.java#L107
and
https://github.com/hazelcast/hazelcast-mono/blob/5f360c2043e01c6abe6160eaa317c9c2c065e977/hazelcast/hazelcast/src/main/java/com/hazelcast/client/map/impl/nearcache/NearCachedClientMapProxy.java#L118

that client side near cache first checks the local data structure before making a network call

**Comment by orcunc** [comment]
Closing the issue with the answer requested by the user.
