### ISSUE TITLE
Hazelcast Kubernetes clustering failure after upgrade form 5.1.3 to 5.1.6

### ISSUE THREAD

**Issue by tajdars** [hazelcast/hazelcast#24980]
After 5.1.6, peer to peer clustering stopped working.

Looks like port 8080 is being used to reach out to peer node 

**Sending master question to [peer_ip_address]:8080 
Connection to: [peer_ip_address]:8080 streamId:-1 is not yet in progress 
[peer_ip_address]:8080 is added to the blacklist.** 

With version 5.1.3, correct port 5701 was being used 

**Sending master question to [peer_ip_address]:5701 
Connection to: [peer_ip_address]:5701 streamId:-1 is not yet in progress 
Established socket connection between /my_ip_address:51745 and /peer_ip_address:5701**

What changed ?
How  do I change the config to use the correct port ?

Additional logs 
5.1.3 

Found node service with addresses (private, public): [ip1]:**5701**, null
Found node service with addresses (private, public): [ip2]:**5701**, null
Found node service with addresses (private, public): [ip3]:**5701**, null
Found node service with addresses (private, public): [ip4]:**5701**, null
Found node service with addresses (private, public): [ip5]:**5701**, null
Found node service with addresses (private, public): [ip6]:**5701**, null
Found node service with addresses (private, public): [ip7]:**5701**, null
Found node service with addresses (private, public): [ip8]:**5701**, null

5.1.6

Found node service with addresses (private, public): [ip1]:**8080**, null  
Found node service with addresses (private, public): [ip2]:**8080**, null  
Found node service with addresses (private, public): [ip3]:**8080**, null   
Found node service with addresses (private, public): [ip4]:**8080**, null
Found node service with addresses (private, public): [ip5]:**8080**, null
Found node service with addresses (private, public): [ip6]:**8080**, null
Found node service with addresses (private, public): [ip7]:**8080**, null
Found node service with addresses (private, public): [ip8]:**8080**, null

**Comment by OmarHawk** [comment]
Could be the same as #24688 // #24705

**Comment by tajdars** [comment]
hi @OmarHawk @hasancelik 

Tried with version 5.3.1, no luck.

This code has the issue where the first port (out of multiple) is selected as the containerPort.


https://github.com/hazelcast/hazelcast/blob/v5.3.1/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L352C1-L363C6

**Comment by hasancelik** [comment]
Hi @tajdars,

Thanks for the issue.

The fix will be released with `5.3.2` which will be released in a few days.

**Comment by OmarHawk** [comment]
> Hi @tajdars,
> 
> Thanks for the issue.
> 
> The fix will be released with `5.3.2` which will be released in a few days.

And what about 5.2.x branch? Is there anything planned for that?

**Comment by hasancelik** [comment]
@tajdars [The fix](https://github.com/hazelcast/hazelcast/pull/24841) already merged into 5.2.z branch so it will be available with **5.2.5** release which will be released at October.

**Comment by tajdars** [comment]
hi @hasancelik , tried the 5.3.2 release , still see the issue.

This code is still pulling the first  exposed port as hazelcast port
https://github.com/hazelcast/hazelcast/blob/v5.3.2/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L374C1-L385C6

Code in 5.1.3

https://github.com/hazelcast/hazelcast/blob/v5.1.3/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L225C1-L241C6
which returns null when more then 1 port is exposed by the container and default to port from config

**Comment by OmarHawk** [comment]
> @tajdars [The fix](https://github.com/hazelcast/hazelcast/pull/24841) already merged into 5.2.z branch so it will be available with **5.2.5** release which will be released at October.

Do you have any idea, if it will be November 2023 then (assuming you meant this year's October in the first place ;-) )

**Comment by ahoehma** [comment]
This issue is still present .. .I'm using 5.3.6.
