### ISSUE TITLE
Missing part of the hazelcast-cloud implementation within ClientConfig network configuration [API-2098]

### ISSUE THREAD

**Issue by kwart** [hazelcast/hazelcast#25052]
**Describe the bug**
`ClientConfigXmlGenerator` doesn't have support for the `hazelcast-cloud` config.

**Expected behavior**
The config is supported in the `ClientConfigXmlGenerator`. 

**To Reproduce**

```java
@Test
public void testClientConfigXmlGenerator() throws Exception {
    ClientConfig config = new ClientConfig();
    config.getNetworkConfig().setSSLConfig(new SSLConfig().setEnabled(true));
    config.getNetworkConfig().getCloudConfig().setDiscoveryToken("pAB2kwCdHKbGpFBNd9iO9AmnYBiQa7rz8yfGW25iHEHRvoRWSN")
            .setEnabled(true);
    config.setClusterName("de-5q14tr1o");
    String strConfig = ClientConfigXmlGenerator.generate(config, 2);
    ClientConfig newConfig;
    try (InputStream is = new ByteArrayInputStream(strConfig.getBytes(StandardCharsets.UTF_8))) {
        newConfig = new XmlClientConfigBuilder(is).build();
    }
    assertEquals(config, newConfig);
}
```

Updated 2023-08-07: The description originally mentioned also the `hazelcast-cloud` config missing in full examples. The examples correctly contain it, so that part was removed.

**Comment by ihsandemir** [comment]
@kwart I see the cloud config already available at our full config [xml](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-full-example.xml#L365)/[yaml](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-client-full-example.yaml#L331) files.

**Comment by kwart** [comment]
Ah, you're right. It was probably selective blindness :facepalm: 
I'll update the issue description.
