### ISSUE TITLE
Kubernetes API discovery across namespaces

### ISSUE THREAD

**Issue by felipeheld** [hazelcast/hazelcast#25103]
### Discussed in https://github.com/hazelcast/hazelcast/discussions/24684

<div type='discussions-op-text'>

<sup>Originally posted by **felipeheld** May 29, 2023</sup>
When using Hazecast in its embedded topology and Hazelcast's Kubernetes's API for node discovery I believe it is not possible for nodes to discover one another across namespaces, given only one service name and one namespace definition are allowed in the discovery configuration.

The relevant code is here: https://github.com/hazelcast/hazelcast/blob/120d25873b173dbc3ec157b1d68c3980168978ef/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java#L243-L251

It would have been desirable in my case to have the endpoint be discoverable in more than one namespace, however I am not sure whether I'm actually right in my propositions nor if, were I right, this would be of actual use to other developers.

I'd be more than willing to create a PR, but I honestly believe it'd be better to just ask beforehand, just in case this is the intended behavior as deemed fit by the majority or by people more qualified in the project's development.

</div>

**Comment by SeriyBg** [comment]
Hello, @felipeheld! We do not support multi-namespace discovery. This is done on purpose since, usually, the discovery is via K8s services, which do not support multi-namespaces.
