### ISSUE TITLE
Operation metrics regression [HZ-2818]

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#25110]
Hazelcast 4.0 introduced a regression in the JMX metrics that it removed the "remote operations count" JMX metric together with removing `OperationService` MBean in https://github.com/hazelcast/hazelcast/pull/16425. It should be analyzed if the PR removed other metrics as well and the lost metrics should be restored. 

Related slack discussion [here](https://hazelcastcommunity.slack.com/archives/C015Q2TUBKL/p1690566602832899).

- [ ] Backported to 5.3.z

**Comment by gbarnett-hz** [comment]
@blazember I did a review just now, mapping the current JMX metrics to their resp. equivalents at the time of #16425, and the only one I found missing was the one reported. I will submit PR shortly.

**Comment by gbarnett-hz** [comment]
@blazember  It looks like `operation.invocations.pending` in JMX is the name of the count that exposes what  `OperationServiceImpl#getRemoteOperationsCount()` would otherwise expose, see `@Probe` on `InvocationRegistry.invocations` field. 

I see there's been quite a restructuring of the JMX naming schema. Is this still needed based on what I stated?

**Comment by blazember** [comment]
@gbarnett-hz The difference between the two seems to be that `operation.invocations.pending` includes both local and remote invocations, while `getRemoteOperationsCount()` included only the remote ones. We should most probably add two respective counters for the two kinds, like `operation.invocations.pendingLocal`, `operation.invocations.pendingRemote`.

**Comment by gbarnett-hz** [comment]
Please use `operation.invocations.pending` for the same metric.

Pre-patch https://github.com/hazelcast/hazelcast/pull/16425 there appeared to be two names by which `InvocationRegistry.invocations.size()` was referred: `operation.remoteOperationCount` and `operation.invocations.pending`. Post https://github.com/hazelcast/hazelcast/pull/16425 the `operation.remoteOperationCount` was removed, leaving a single name for attaining such information: `operation.invocations.pending`.
