### ISSUE TITLE
com.hazelcast.client.impl.management.MCMessageTasksTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25260]
_5.3.z_ (commit 845d719e2109a66da9bf851b4f9a63d7da73cd54)

Failed on Windows-Oracle8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/133/

<details><summary>Stacktrace:</summary>

```
20:36:19 [INFO] Running com.hazelcast.client.impl.management.MCMessageTasksTest
20:37:24 #
20:37:24 # A fatal error has been detected by the Java Runtime Environment:
20:37:24 #
20:37:24 #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000075940958, pid=17168, tid=0x00000000000073ac
20:37:24 #
20:37:24 # JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
20:37:24 # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.172-b11 mixed mode windows-amd64 compressed oops)
20:37:24 # Problematic frame:
20:37:24 # V  [jvm.dll+0x400958]
20:37:24 #
20:37:24 # Core dump written. Default location: C:\Jenkins\workspace\Hazelcast-5.maintenance-Windows-OracleJDK8\hazelcast\hs_err_pid17168.mdmp
20:37:24 #
20:37:24 # An error report file with more information is saved as:
20:37:24 # C:\Jenkins\workspace\Hazelcast-5.maintenance-Windows-OracleJDK8\hazelcast\hs_err_pid17168.log
20:37:24 #
20:37:24 # If you would like to submit a bug report, please visit:
20:37:24 #   http://bugreport.java.com/bugreport/crash.jsp
20:37:24 #
20:37:24 hazelcast[default] > Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
```

</details>

Stdout link: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Windows-OracleJDK8/133/

**Comment by sumnerib** [comment]
Hi @DumitruCorini, so far we've only observed this on OracleJDK-8 (specifically on Windows). If it happens again, the test failure will be reported here and include the platform information where it failed. Are you experiencing any issue w/ HZ running on Oracle JDK 11? If so, may I suggest opening a separate GH issue with the details and link to this issue if you think they're related (i.e. if your seeing a JVM crash and/or error with `MCMessageTasksTest`).

**Comment by DumitruCorini** [comment]
We haven't noticed any issue yet, and we'll open a GH issue if we find any. I'll also look into linking it to this one if it is related.
Thank you very much.

**Comment by sumnerib** [comment]
Failed again on 5.3.z with Windows-OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/163/console

**Comment by AleksPeychev** [comment]
Failed again on 5.3.z with Windows-OracleJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/165/console
