### ISSUE TITLE
Map cannot be obtained if store method of map-store is in progress

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25321]
**_This is a regression to behavior in HZ 5.3.z._**
  
**Describe the bug**
If map-store is used for map and storing some item is processed by `store` method of the map-store then size of map (and I guess also other map operations will not work) cannot be obtained until `store` method of map-store finishes. Before the change from PR https://github.com/hazelcast/hazelcast/pull/25108 size of the map could be obtained even during processing of `store` method of map-store.

**Expected behavior**
Processing of `store` method of map-store should not block other map operation like `size()` method.

**To Reproduce**

1. Create following MapStore and put it into `lib` dir of HZ node:
```
public class MyMapStore implements MapStore<String, String> {

    private final ConcurrentMap<String, String> store = new ConcurrentHashMap<>();

    @Override
    public void store(String key, String value) {
        System.out.println("STORING " + key);
        try {
            Thread.sleep(30_000);
        } catch (InterruptedException ex) {
            throw new RuntimeException(ex);
        }
        System.out.println("STORED " + key);
        store.put(key, value);
    }
    // implement also other methods
}
```
2. Set this MapStore for map name MyMap in `hazelcast.xml` config:
```
    <map name="myMap">
        <map-store enabled="true" initial-mode="LAZY">
            <class-name>com.mycompany.simple.hz.mapstore.MyMapStore</class-name>
            <write-delay-seconds>0</write-delay-seconds>
            <write-batch-size>1</write-batch-size>
            <write-coalescing>true</write-coalescing>
        </map-store>
    </map>
```
3. Start server, add any item to `MyMap` and try to read map size. You will not a response until `store` method of MapStore will finish.

**Comment by ahmetmircik** [comment]
Copying conversion between @ahmetmircik and @olukas here for the reasoning of the current behavior:

> if this is expected change I think we should make it more visible (at least in release notes for 5.4) since I think this can be also considered as regression for some cases. WDYT?

This makes sense.

> However I still wonder whether it cannot cause some troubles to the customers - let’s imagine that external mapstore will be unreachable for couple of minutes (it’s something what just happen and we cannot do anything about it) - it means that during that time we’re blocking all operations on map, even those which just read anything from map, is that correct solution?

This has never been a goal. The main goal of offloading is freeing partition threads from expensive executions for other data-structures and system operations. Blocking operations for the same map is ok and this is same behavior with previous no-offloading approach.

**Comment by olukas** [comment]
Thanks @ahmetmircik , closing this since it's not a bug.
