### ISSUE TITLE
The hazelcast 5.3.2 THIRD-PARTY.txt incorrectly includes the JSON license

### ISSUE THREAD

**Issue by lfradin** [hazelcast/hazelcast#25343]
**Describe the bug**
In the hazelcast 5.3.2 jar, the THIRD-PARTY.txt file listing the license of the 3rd party components correctly lists JSON-java version 20230227 as being a public domain license (as seen in the official project directory here https://github.com/stleary/JSON-java/blob/20230227/LICENSE).
Indeed this JSON-java project changed its license from the JSON license to a "Public Domain" license back in version 20220924.

However, hazelcast 5.3.2 still includes the JSON license in the THIRD-PARTY.txt file, which it does not need to.

This triggers alarms on our licensing analysis tools, as our company forbids the use of anything using the JSON license. We will get a waiver, following our analysis, but it would be best to remove the JSON license from the file.

**Expected behavior**
We expect a THIRD-PARTY.txt file not containing the JSON license text.

**To Reproduce**
Just get the hazelcast-5.3.2.jar (for example from maven central), open it as a zip file to extract and view the THIRD-PARTY.txt file at the root. In this file, search for "JSON License", which will lead to the section that should be removed.

**Additonnal Information**
The text seems to come from the following source file: 
hazelcast-build-utils/src/main/resources/hazelcast-thirdparty-template.ftl

**Comment by nishaatr** [comment]
Hi @lfradin 

Thank you for reporting this. 

You are correct about license is set in https://github.com/hazelcast/hazelcast/blob/master/hazelcast-build-utils/src/main/resources/hazelcast-thirdparty-template.ftl. SoI believe its just a question of removing 'The JSON License' from this FTL template

I am just highlighting this here and best wait for Hazelcast engineering team to pick this up and comment

Thanks
Nishaat
