### ISSUE TITLE
Map Entry Diet

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#2548]
The map needs a  diet because there is a lot of overhead for every key/value 

For a Map entry, you need:
- Hash Entry
- Record
- 2 Data (key and value)
- 2 byte arrays (again key and value)

So for every key/value 6 objects are needed. 

Also be default statistics are enabled, which requires an additional statistics object is needed, so by default you get 7 objects per map entry. That is why Hazelcast needs a lot of memory to store data.

**Comment by dbrimley** [comment]
The estimation by @pveentjer is roughly 180 bytes overhead per map entry.  There is reason to believe this could be reduced.

**Comment by burakcelebi** [comment]
Closed as internal request
