### ISSUE TITLE
`StringUtil.trim(String)` implementation doesn't match Javadoc contract

### ISSUE THREAD

**Issue by JackPGreen** [hazelcast/hazelcast#25519]
The Javadoc for `com.hazelcast.internal.util.StringUtil.trim(String)` says:

> This method (compared to String#trim()) doesn't limit to space character

But functionally it removes fewer characters than `String.trim`, which I think is a bug.

Testing every character to identify where the behaviour of `String.trim` & `StringUtil.trim` differ:
```
String format = "| %-4s | %-30s | %-25s | %-25s |%n";
System.out.printf(format, "Code", "Name", ".trim.isEmpty", "StringUtil.trim.isEmpty");
System.out.printf(format, "---", "---", "---", "---");

for (int i = 0; i <= Character.MAX_VALUE; i++) {
    String str = String.valueOf((char) i);

    String javaStringTrim = str.trim();
    String stringUtilTrim = StringUtil.trim(str);

    if (!Objects.equals(javaStringTrim, stringUtilTrim)) {
        System.out.printf(format, i, Character.getName(i), javaStringTrim.isEmpty(), stringUtilTrim.isEmpty());
    }
}
```

| Code | Name                           | .trim.isEmpty             | StringUtil.trim.isEmpty   |
| ---  | ---                            | ---                       | ---                       |
| 0    | NULL                           | true                      | false                     |
| 1    | START OF HEADING               | true                      | false                     |
| 2    | START OF TEXT                  | true                      | false                     |
| 3    | END OF TEXT                    | true                      | false                     |
| 4    | END OF TRANSMISSION            | true                      | false                     |
| 5    | ENQUIRY                        | true                      | false                     |
| 6    | ACKNOWLEDGE                    | true                      | false                     |
| 7    | BEL                            | true                      | false                     |
| 8    | BACKSPACE                      | true                      | false                     |
| 14   | SHIFT OUT                      | true                      | false                     |
| 15   | SHIFT IN                       | true                      | false                     |
| 16   | DATA LINK ESCAPE               | true                      | false                     |
| 17   | DEVICE CONTROL ONE             | true                      | false                     |
| 18   | DEVICE CONTROL TWO             | true                      | false                     |
| 19   | DEVICE CONTROL THREE           | true                      | false                     |
| 20   | DEVICE CONTROL FOUR            | true                      | false                     |
| 21   | NEGATIVE ACKNOWLEDGE           | true                      | false                     |
| 22   | SYNCHRONOUS IDLE               | true                      | false                     |
| 23   | END OF TRANSMISSION BLOCK      | true                      | false                     |
| 24   | CANCEL                         | true                      | false                     |
| 25   | END OF MEDIUM                  | true                      | false                     |
| 26   | SUBSTITUTE                     | true                      | false                     |
| 27   | ESCAPE                         | true                      | false                     |
| 28   | INFORMATION SEPARATOR FOUR     | true                      | false                     |
| 29   | INFORMATION SEPARATOR THREE    | true                      | false                     |
| 30   | INFORMATION SEPARATOR TWO      | true                      | false                     |
| 31   | INFORMATION SEPARATOR ONE      | true                      | false                     |

There exists no input I can see where `StringUtil.trim` removes anything over `String.trim`.

[`String.trim`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#trim()):
> where space is defined as any character whose codepoint is less than or equal to 'U+0020' (the space character)

`StringUtil.trim` uses the `\s` regular expression, which is [defined as](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html):
> A whitespace character: [ \t\n\x0B\f\r]

But there exists other space characters outside of this definition - e.g. `\u2001` ([em quad](https://www.compart.com/en/unicode/U+2001)) - which may be sensible to remove in some cases.

Either:
- The Javadoc should be updated to clarify it removes only whitespace based on the `Pattern` definition, rather than implying it removes more than `String.trim`
- `StringUtil.trim` should handle the extra whitespace characters
   - the regular expression could be updated to use `\p{javaWhitespace}`
   - `String.strip` could be used instead - this is probably more performant than using a regular expression

There are no unit tests to assert the expected behaviour which probably doesn't help.
Method added in bc7f251003943711c71816da67acd984c8dbe747.

**Comment by Gauravsalunke5** [comment]
Added fix in https://github.com/hazelcast/hazelcast/pull/25804
