### ISSUE TITLE
ICache method setExpiryPolicy with CreatedExpiryPolicy set max duration independently on passed value [HZ-3264]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#25547]
**Describe the bug**
ICache method `setExpiryPolicy` suppose to set a new expiry policy for the given key in the cache. However it seems it's currently ignored (tried with `CreatedExpiryPolicy`) and once it's called the given entry is never removed from the cache (instead of using the new policy).

**Expected behavior**
New policy should be applied for the entry with given key in the cache.

**To Reproduce**

Use `cache.setExpiryPolicy` as following:
```
ICache<String, String> cache = client.getCacheManager().getCache("hz/myCache");
cache.put("k", "v", new CreatedExpiryPolicy(new Duration(TimeUnit.MILLISECONDS, 5000)));
cache.setExpiryPolicy("k", new CreatedExpiryPolicy(new Duration(TimeUnit.MILLISECONDS, 6000)));
```
and check that entry "k" is never removed from the cache. If the `cache.setExpiryPolicy()` is not called then entry expires in 5 seconds.

**Comment by gareth-johnston** [comment]
Investigation of this issue and testing has determined that the functionality in the code adheres to the contract of the `ICache`  interface for method `setExpiryPolicy`.

See note on JavaDoc :

    * Note: New time-to-live duration is calculated using newly added entry policy's getExpiryForUpdate method
     * immediately after this operation succeeds.

The result is that the `CacheRecord:expiryTime` will get set to a value determined with the use of the `expiryForUpdate` value provided in the expiry policy.  `CreatedExpiryPolicy` returns a `null` for `expiryForUpdate`, leading to a `-1` expiry on the record - which means we will never expire the record. 

With the test case provided you have two options to achieve the result you expected: 

(1) invoke `setExpiryPolicy` for the cache entry with a policy such as `HazelcastExpiryPolicy` which accepts `createDurationAmount`, `accessDurationAmount`, `updateDurationAmount`-> supply updateDurationAmount as 6000 ms.  
(2) re-invoke the original `put` with the new `CreatedExpiryPolicy`. 

Closing with this context - thanks for raising this issue!

**Comment by gareth-johnston** [comment]
Investigation of this issue and testing has determined that the functionality in the code adheres to the contract of the ICache interface for method setExpiryPolicy.

See note on JavaDoc :

* Note: New time-to-live duration is calculated using newly added entry policy's getExpiryForUpdate method
 * immediately after this operation succeeds.
The result is that the CacheRecord:expiryTime will get set to a value determined with the use of the expiryForUpdate value provided in the expiry policy. CreatedExpiryPolicy returns a null for expiryForUpdate, leading to a -1 expiry on the record - which means we will never expire the record.

With the test case provided you have two options to achieve the result you expected:

(1) invoke setExpiryPolicy for the cache entry with a policy such as HazelcastExpiryPolicy which accepts createDurationAmount, accessDurationAmount, updateDurationAmount-> supply updateDurationAmount as 6000 ms.
(2) re-invoke the original put with the new CreatedExpiryPolicy.

Closing with this context - thanks for raising this issue!
