### ISSUE TITLE
Error executing SQL query using IN operator [HZ-3410]

### ISSUE THREAD

**Issue by federicocodo** [hazelcast/hazelcast#25647]
I'm trying to execute a parameterized sql query using the IN operator, my query is very simple:
```sql
SELECT *
FROM map
WHERE columnName IN (?)
```
As a parameter I pass the Hazelcast client a simple merged list of structured strings like: 'value1', 'value2' but I get an error when running the Hazelcast client.

![image](https://github.com/hazelcast/hazelcast-csharp-client/assets/62144863/106889fc-3f3b-43da-b3d2-d7f2962bbc7c)

Update, I'm trying to debug to see what's happening and found out that it's caused because:

- the query shows more than one row and in my Hazelcast map one row is valued with double while the other is null;
- the hazelcast double class is trying to decode the frame that contains a null value and causes an exception.

Is possible to resolve?

I've already open this issue in the `hazelcast-csharp-client` because it refers to that package for C# and I reported the bug in this project too since no one has seen it yet.

**Comment by Fly-Style** [comment]
Hi, @federicocodo ! Thank you for your review, I added it to our work queue.

**Comment by Fly-Style** [comment]
cc @zpqrtbnk

**Comment by emreyigit** [comment]
Hey, I'm closing the issue since it's duplication of https://github.com/hazelcast/hazelcast-csharp-client/issues/854 and it's already addressed.
