### ISSUE TITLE
com.hazelcast.splitbrainprotection.map.MapSplitBrainProtectionLiteMemberTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25650]
_5.3.z_ (commit 10284c50a1a2e2801eac148ce70e362130bb8717)

Failed on IBM-JDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/105/

<details><summary>Stacktrace:</summary>

```
17:01:54 [INFO] Running com.hazelcast.splitbrainprotection.map.MapSplitBrainProtectionLiteMemberTest
17:07:52 Build timed out (after 480 minutes). Marking the build as failed.
17:07:53 Stopping Docker container after build completion
17:07:54 Build was aborted
```

</details>

Stdout can be found here: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/105/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
