### ISSUE TITLE
com.hazelcast.client.splitbrainprotection.map.ClientMapSplitBrainProtectionReadTest

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25860]
_5.3.z_ (8180fa192399a5202bf85901d40afd38976c15af)

Failed on IBM-JDK-8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/108/

<details><summary>Stacktrace:</summary>

```
17:04:30 [INFO] Running com.hazelcast.client.splitbrainprotection.map.ClientMapSplitBrainProtectionReadTest
17:08:04 Build timed out (after 480 minutes). Marking the build as failed.
17:08:05 Stopping Docker container after build completion
17:08:08 Build was aborted
```

</details>

Std output can be found here: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/108/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
