### ISSUE TITLE
com.hazelcast.client.splitbrainprotection.queue.ClientQueueSplitBrainProtectionReadTest job timeout

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#25963]
_5.3.z_ (commit 52b6537d438c961583badd1f95d36e0618be0dfc)

Failed on IBMJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/110/consoleFull

<details><summary>Stacktrace:</summary>

```
16:07:49 [INFO] Running com.hazelcast.client.splitbrainprotection.queue.ClientQueueSplitBrainProtectionReadTest
16:07:59 Build timed out (after 480 minutes). Marking the build as failed.
16:08:00 Stopping Docker container after build completion
16:08:03 Build was aborted
```

</details>

Standout out can be found here: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/110/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
