### ISSUE TITLE
com.hazelcast.jet.sql.impl.connector.jdbc.mysql 'java.lang.NoClassDefFoundError'

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26141]
_master_ (commit 3d1d89fdb9bbb28f8e23aa1c3cc4d5312ada0017)
Failed on oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/35/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/

<details><summary>Stacktrace:</summary>

```
java.lang.NoClassDefFoundError: Could not initialize class com.hazelcast.jet.sql.impl.opt.logical.ScanCyclicTypeMustNotExecuteRule
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.prepareUnconditionalSubqueryRewriter(CalciteSqlOptimizer.java:1098)
	at com.hazelcast.jet.sql.impl.CalciteSqlOptimizer.<init>(CalciteSqlOptimizer.java:278)
	at com.hazelcast.sql.impl.SqlServiceImpl.start(SqlServiceImpl.java:95)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:292)
	at com.hazelcast.instance.impl.Node.start(Node.java:483)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:124)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:218)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:197)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:135)
	at com.hazelcast.test.TestHazelcastInstanceFactory.newHazelcastInstance(TestHazelcastInstanceFactory.java:240)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWitSupplier(SimpleTestInClusterSupport.java:100)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:88)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:82)
	at com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport.initialize(JdbcSqlTestSupport.java:69)
	at com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdatePredicatePushDownJdbcSqlConnectorTest.beforeClass(MySQLUpdatePredicatePushDownJdbcSqlConnectorTest.java:30)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
11:57:38,844  INFO || - [35] Time-limited test - Creating container for image: mysql:8.0.35
11:57:39,697  INFO || - [35] Time-limited test - Container mysql:8.0.35 is starting: c9d5e059b925d8ddad93325d532c06cb423b56a5a7622b968519719e4a235ee2
11:57:40,375  INFO || - [35] Time-limited test - Waiting for database connection to become available at jdbc:mysql://172.17.0.1:36852/com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport?password=test&user=root using query 'SELECT 1'
11:57:51,899  INFO || - [35] Time-limited test - Container mysql:8.0.35 started in PT13.054493S
11:57:51,900  INFO || - [35] Time-limited test - Container is started (JDBC URL: jdbc:mysql://172.17.0.1:36852/com.hazelcast.jet.sql.impl.connector.jdbc.JdbcSqlTestSupport?password=test&user=root)
11:57:51,937  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
11:57:51,940  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
11:57:51,940  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
11:57:51,940  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20231205 - 3d1d89f) starting at [127.0.0.1]:5701
11:57:51,940  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
11:57:51,940  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
11:57:51,940  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
11:57:51,953  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
11:57:51,955  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
11:57:51,971  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Using Multicast discovery
11:57:51,971  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
11:57:51,978  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
11:57:51,986  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
11:57:51,986  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down multicast service...
11:57:56,986  WARN || - [MulticastService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Failed to shutdown MulticastService in 5 seconds!
11:57:56,987  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
11:57:56,987  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
11:57:56,999  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
11:57:56,999  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 5013 ms.
11:57:57,717  INFO || - [SimpleTestInClusterSupport] Time-limited test - Terminating instance factory in SimpleTestInClusterSupport.@AfterClass

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-mysql-8.0/35/

Affects the following tests:

[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLCreateDataConnectionJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLCreateDataConnectionJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLAllTypesInsertJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesInsertJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLAllTypesSelectJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLAllTypesSelectJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeleteJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLDeleteJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLDeletePredicatePushDownJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLDeletePredicatePushDownJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLInsertJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLInsertJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcFullScanJoinTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcFullScanJoinTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcInnerEquiJoinTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcInnerEquiJoinTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcRightJoinTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcRightJoinTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLJdbcSqlConnectorStabilityTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLJdbcSqlConnectorStabilityTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLMappingJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLMappingJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLPredicatePushDownJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLPredicatePushDownJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSchemaJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSchemaJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSelectJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSelectJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLSinkIntoJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLSinkIntoJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdateJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLUpdateJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySQLUpdatePredicatePushDownJdbcSqlConnectorTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySQLUpdatePredicatePushDownJdbcSqlConnectorTest/___/)
[com.hazelcast.jet.sql.impl.connector.jdbc.mysql.MySqlDownTest.(?)](https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.0/lastSuccessfulBuild/testReport/junit/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/MySqlDownTest/___/)

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-11: https://jenkins.hazelcast.com/job/Hazelcast-master-mysql-8.2/7/testReport/com.hazelcast.jet.sql.impl.connector.jdbc.mysql/

**Comment by TomaszGaweda** [comment]
Solved, job config mistake
