### ISSUE TITLE
com.hazelcast.client.map.ClientMapStoreTest.testNullValuesFromMapLoaderAreNotInsertedIntoMap [HZ-4257]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26184]
_master_ (commit 7ed9b809ec549aeb91af6c3c3b8126649543da15)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/342/testReport/junit/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting code to raise a throwable.
	at com.hazelcast.client.map.ClientMapStoreTest.testNullValuesFromMapLoaderAreNotInsertedIntoMap(ClientMapStoreTest.java:274)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/342/

**Comment by Patras3** [comment]
Failed again on _master_ with OpenJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-OpenJDK17-nightly-Esxi7/62/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by olukas** [comment]
Failed again on _master_ with openjdk-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZuluJDK17-nightly/96/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/346/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/80/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by olukas** [comment]
**Fails constantly** on oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/351/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by olukas** [comment]
Fails constantly also on nightly tests.

**Comment by Patras3** [comment]
One of recent failures for reference:
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/386/testReport/com.hazelcast.client.map/ClientMapStoreTest/testNullValuesFromMapLoaderAreNotInsertedIntoMap/

**Comment by AleksPeychev** [comment]
Test issue, fixed test expectation in https://github.com/hazelcast/hazelcast-mono/pull/755
