### ISSUE TITLE
Native OOM in hazelcast-3-connector tests

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26209]
_5.3.z_ (commit c93e1cca30ac94ad008f27c300db5edc58b59954)

Failed on Windows-Oracle8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-Windows-OracleJDK8/153/console

<details><summary>Stacktrace:</summary>

```
22:03:38 #
22:03:38 # There is insufficient memory for the Java Runtime Environment to continue.
22:03:38 # Native memory allocation (malloc) failed to allocate 1140176 bytes for Chunk::new
22:03:38 # An error report file with more information is saved as:
22:03:38 # C:\Jenkins\workspace\Hazelcast-5.maintenance-Windows-OracleJDK8\extensions\hazelcast-3-connector\hazelcast-3-connector-common\hs_err_pid7272.log
22:03:38 #
22:03:38 # Compiler replay data is saved as:
22:03:38 # C:\Jenkins\workspace\Hazelcast-5.maintenance-Windows-OracleJDK8\extensions\hazelcast-3-connector\hazelcast-3-connector-common\replay_pid7272.log
```

</details>

Stdout logs: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Windows-OracleJDK8/153/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
