### ISSUE TITLE
com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationSlowTest [API-2218] [HZ-4566]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26245]
_master_ (commit 5ecb79121243fb5470750c592c41e63690a0b737)

Failed on zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/63/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/

Following tests failed:
- `com.hazelcast.internal.serialization.impl.compact.schema.testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringPreparationPhase`
- `com.hazelcast.internal.serialization.impl.compact.schema.testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringAcknowledgmentPhase`

<details><summary>Stacktrace:</summary>

```
junit.framework.AssertionFailedError: Expected com.hazelcast.nio.serialization.HazelcastSerializationException to be thrown, but nothing was thrown.
	at com.hazelcast.test.HazelcastTestSupport.assertThrows(HazelcastTestSupport.java:1433)
	at com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationSlowTest.testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringPreparationPhase(CompactSchemaReplicationSlowTest.java:55)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/63/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/66/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/12/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringAcknowledgmentPhase/

**Comment by AleksPeychev** [comment]
Failed again on master with zing-17 : https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/72/consoleFull#16541235993ee7a23a-abdd-4ede-acea-25daf22ff7f1

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/74/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringAcknowledgmentPhase/

**Comment by olukas** [comment]
Failed again on _master_ with ZingJDK21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK21-nightly/14/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringAcknowledgmentPhase/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/76/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/

**Comment by olukas** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/78/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17 :
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/80/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringPreparationPhase/
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/80/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringAcknowledgmentPhase/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/83/consoleFull#16541235993ee7a23a-abdd-4ede-acea-25daf22ff7f1

**Comment by EugeneAbramchuk** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/84/testReport/junit/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringPreparationPhase/

**Comment by sumnerib** [comment]
Failed again on _master_ with zing-17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17-nightly/85/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationSlowTest/testSchemaReplication_whenAMemberThrowsRetryableExceptionAllTheTime_duringPreparationPhase/

**Comment by sumnerib** [comment]
Fails constantly on zing-17

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary
