### ISSUE TITLE
com.hazelcast.collection.impl.list.ListSplitBrainTest.testSplitBrain[mergePolicy:class com.hazelcast.test.SplitBrainTestSupport$ReturnPiCollectionMergePolicy]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26240]
_5.3.z_ (commit 9085d50dc8b485cfa084c388dcdd143240325b04)

Failed on microsoft-11: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-MicrosoftJDK11/69/testReport/junit/com.hazelcast.collection.impl.list/ListSplitBrainTest/testSplitBrain_mergePolicy_class_com_hazelcast_test_SplitBrainTestSupport$ReturnPiCollectionMergePolicy_/
<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-MicrosoftJDK11/69/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
