### ISSUE TITLE
com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26281]
_master_ (commit 0afa6ae72e3267c66c21d3095c922d4cf5d28be1)

Failed on zing-21: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/6/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/

Below tests are failing with: 
`expected:<REPLICA_NOT_SYNC> but was:<SAFE>`
[whenCheckAndTriggerReplicaSync](https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/6/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenCheckAndTriggerReplicaSync)	0.31 sec	Failed
[whenHasMissingReplicaOwners_withAddress_thenWaitForMissingReplicaOwners](https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/6/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasMissingReplicaOwners_withAddress_thenWaitForMissingReplicaOwners)	0.31 sec	Failed
[whenHasMissingReplicaOwners_withoutAddress_thenWaitForMissingReplicaOwners](https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK21/6/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasMissingReplicaOwners_withoutAddress_thenWaitForMissingReplicaOwners)	0.31 sec	Failed

Details for `whenHasMissingReplicaOwners_withAddress_thenWaitForMissingReplicaOwners`
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<REPLICA_NOT_OWNED> but was:<SAFE>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.internal.partition.impl.PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest.whenHasMissingReplicaOwners_withAddress_thenWaitForMissingReplicaOwners(PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.Thread.run(Thread.java:1584)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: whenHasOngoingMigration_withMigrationOnMaster_thenWaitForOngoingMigrations in 0.317 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK21/6/

**Comment by JackPGreen** [comment]
https://hazelcast.atlassian.net/browse/HZ-4458

**Comment by olukas** [comment]
Failed again on _master_ with ZingJDK17: https://jenkins.hazelcast.com/job/Hazelcast-master-ZingJDK17/43/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasMissingReplicaOwners_withoutAddress_thenWaitForMissingReplicaOwners/

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/2/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK21/5/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasOngoingMigration_withLocalMigration_thenWaitForOngoingMigrations/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK21/6/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/

**Comment by Patras3** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/8/testReport/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasMissingReplicaOwners_withoutAddress_thenWaitForMissingReplicaOwners/

**Comment by AleksPeychev** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/10/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/whenHasMissingReplicaOwners_withoutAddress_thenWaitForMissingReplicaOwners/

**Comment by sumnerib** [comment]
Failed again on _5.4.z_ with zing-21: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-ZingJDK21/12/testReport/junit/com.hazelcast.internal.partition.impl/PartitionReplicaStateChecker_triggerAndWaitForReplicaSyncTest/

**Comment by nishaatr** [comment]
Changed Milestone to 6.0.0 to ensure 5.5.0 does not report any Open [issues ](https://github.com/issues?page=1&q=is%3Aopen+milestone%3A5.5.0+repo%3Ahazelcast%2Fhazelcast+repo%3Ahazelcast%2Fhazelcast-enterprise+repo%3Ahazelcast%2Fhazelcast-mono+sort%3Acreated-desc)
Please correct as necessary

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z`. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
