### ISSUE TITLE
com.hazelcast.client.splitbrainprotection.list.ClientListSplitBrainProtectionWriteTest timed out

### ISSUE THREAD

**Issue by sumnerib** [hazelcast/hazelcast#26291]
_5.3.z_ (commit  fa4f6fa77d895da4201c257a3f97be09d9b65933)

Failed on IBMJDK8: https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-IbmJDK8/128/consoleFull

<details><summary>Stacktrace:</summary>

```
17:06:11 [INFO] Running com.hazelcast.client.splitbrainprotection.list.ClientListSplitBrainProtectionWriteTest
17:08:05 Build timed out (after 480 minutes). Marking the build as failed.
17:08:07 Stopping Docker container after build completion
17:08:09 Build was aborted
```

</details>

stdout logs: https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-IbmJDK8/128/

**Comment by olukas** [comment]
Closing the test failure - it doesn't seem to be related to `master` or the latest maintenance stream `5.5.z` and it hasn't fail in the last 3 months. Feel free to reopen test failure if it occurs on `master` or on the latest maintenance stream.
