### ISSUE TITLE
Several jobs failed with Build timed out (after 300 or 640 minutes). Marking the build as failed. [HZ-4653]

### ISSUE THREAD

**Issue by AleksPeychev** [hazelcast/hazelcast#26305]
_master_ (commit bbc9de9267459e2f95ad25441e3e266fbba00749)
Failed on microsoft-21: 
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK21/11/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-javadoc-deploy/781/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-CorrettoJDK17/135/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-OpenJDK17/19/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-17/114/consoleFull
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK21/28/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-OracleJDK17/128/console
 - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-RedHatJDK21/11/console
<details><summary>Stacktrace:</summary>

```
06:05:01 Build timed out (after 300 minutes). Marking the build as failed.
06:05:01 Stopping Docker container after build completion
06:05:04 Build was aborted
06:05:04 Sending e-mails to: core@hazelcast.com jenkins-notification@hazelcast.com
06:05:04 Performing Post build task...

```
</details>

Standard output can be found here - https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MicrosoftJDK21/11/

**Comment by olukas** [comment]
Closing. Issue is too general and various issues mentioned in description are covered as part of other reported issues.
