### ISSUE TITLE
AWS plugin does not support IAM roles

### ISSUE THREAD

**Issue by aberaud** [hazelcast/hazelcast#2630]
Currently the Hazelcast AWS plugin requires EC2 credentials hard-coded in the xml configuration file (or provided directly in Java), while Amazon provides the option to access APIs from running instances using IAM roles. This is suboptimal in term of security (by encouraging storing API keys in repositories and AMIs) and ease of use.

If AWS is enabled and creds are not provided in the configuration, the default behavior should be to check for IAM role membership, retrieve a token, and use it to access the API.

**Comment by ddossot** [comment]
If anyone is interested, here is an alternative implementation of `TcpIpJoinerOverAWS` that uses the AWS EC2 client, which we have created at Unbounce in order to use IAM roles: https://gist.github.com/ddossot/814fadc6e2cf577f87f7

**Comment by noctarius** [comment]
If somebody is interested in a general SPI for all kinds of discovery mechanisms, please read https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI and join the discussion at https://gitter.im/hazelcast-incubator/hazelcast-discovery-spi

**Comment by unixunion** [comment]
+1 for fixing IAM roles.

**Comment by w32-blaster** [comment]
+1 for IAM roles

**Comment by danfink** [comment]
+1

**Comment by jmiddleton** [comment]
+1 for IAM roles. I just got this issue so I used memcached instead.

**Comment by ddossot** [comment]
@jmiddleton You could have used the code I posted above :wink: We use it in production.

**Comment by jmiddleton** [comment]
Yes, that's true. I just saw it but I will try it soon. Is there any plan to incorporate that code to hazelcast?

**Comment by ddossot** [comment]
@jmiddleton I don't think so, I think the official feature will come as part of a bigger revamp of the discovery mechanism (see: https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI )
