### ISSUE TITLE
The branch `5.4.0` was created by mistake instead of a tag.

### ISSUE THREAD

**Issue by OleksandrShkurat** [hazelcast/hazelcast#26313]
This issue is not really about any bug but about a small mistake during `5.4.0` version release.
I tried to find out the release notes for his version, however the latest version here
https://github.com/hazelcast/hazelcast/releases
is still 5.3.7.
At the same time the branch `5.4.0` was created which is not typical in this repo.
Most probably it was a kind of mistake in the release lifecycle

**Comment by JackPGreen** [comment]
Hi - we are in the process of releasing `5.4.0` (from the branch you've mentioned).

Once released, release notes etc will be issued.

**Comment by OleksandrShkurat** [comment]
Got it. Thank you for the fast response.

**Comment by JackPGreen** [comment]
> Hi - we are in the process of releasing `5.4.0` (from the branch you've mentioned).
> 
> Once released, release notes etc will be issued.

https://github.com/hazelcast/hazelcast/releases/tag/v5.4.0
