### ISSUE TITLE
Map (IMap) Corrupting/Losing data when there is competition at task startup

### ISSUE THREAD

**Issue by vinicius-colutti** [hazelcast/hazelcast#26317]
**Describe the bug**

When there is competition at task startup on Java **HazelcastInstance**, to form the server cluster, the Map are corrupting, as if the information/positions were removed from the map.

I got this situation, in AWS ECS environment, using ECS discovery to create the cluster of Hazelcast instances.

And then, I was able to replicate this situation in my local environment, using the simple Hazelcast instances.

Below, I will explain how to replicate the problem.

**Expected behavior**

Not corrupt the map, when one or more tasks are initializing in the same moment.

**To Reproduce**

I disposed a sample application to test this problem: https://github.com/vinicius-colutti/hazelcast-map-trade-off

## Lang, framework and versions

**Lang:** Java17
**Framework:** spring-boot-starter-web 3.1.10
**Hazelcast:** 5.4.0

## What does this application do?

**1.** This application create a simple Hazelcast Instance as a bean
![image](https://github.com/hazelcast/hazelcast/assets/27781962/6efdbc2e-9571-4ce6-bd6d-2f880241edeb)

**2.** Have a controller to get full map and populate the map
![image](https://github.com/hazelcast/hazelcast/assets/27781962/40f53398-47a1-44da-8e37-602823b48662)

**3.** When the application started, I get the map to check size and show the keys-values 
![image](https://github.com/hazelcast/hazelcast/assets/27781962/5c91c0bd-fde8-425c-a3c5-3de8273d2721)

## To Reproduce the problem

**1.** Cluster three tasks in a Hazelcast cluster (differentiating only the HTTP and TCP port on which each node will run)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/c5414fa3-b732-481a-9ac4-e558c9e11abf)

**2.** Then, I populate the map with 10 objects, calling the Hazelcast port 5701 node (or any other)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/4563705c-0f08-49f6-b19d-2bdce7d99896)

**3.** I check if all members have the complete map by calling the HTTP request /getMap
![image](https://github.com/hazelcast/hazelcast/assets/27781962/d4027e55-6e04-4b4a-bab4-fd5c58b3ba87)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/62fcc7b6-4c85-49f3-a442-e42c71d99456)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/ca5eb504-f75c-43fe-90f0-6fd77dbc201b)

**4.** So I stop two cluster nodes
**5.** Then I start both nodes again, pretty much at the same time
**6.** We can already see at startup that the map is no longer complete. We can also see that when I make HTTP requests, the map already responds with another size.
No matter which node I make requests to, they will all return the same size and the same objects.
![image](https://github.com/hazelcast/hazelcast/assets/27781962/f63ac1c1-bf66-434c-828e-d5cf654280ef)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/75f07847-3a5f-498a-b095-5a4663937aad)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/98e2b549-f236-407d-aeab-4f088aa30c02)

**7.** If we repeat the process of stopping the nodes and starting them again, practically at the same time, we can observe the map becoming corrupted again, and in the test carried out the map had only two objects.
![image](https://github.com/hazelcast/hazelcast/assets/27781962/4311d588-bdd3-4836-8891-3c590389b270)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/c2ba0abc-b322-4cee-9459-3ebd7b34da3b)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/e64aa7ac-6c79-4803-b234-2bec87b0cb6b)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/61325497-e5dc-46de-a4ad-ad160c6e0ae7)
![image](https://github.com/hazelcast/hazelcast/assets/27781962/42627047-e523-49f6-92f2-67e972811b6f)

**Additional context**

With **ReplicatedMap**, this problem not occurred.

Regarding **Map**, I didn't find any information in the documentation saying that this is an expected or common situation.

**Comment by k-jamroz** [comment]
> 4. So I stop two cluster nodes

How do you terminate the nodes - gracefully or forcefully? If you terminate them **not** gracefully at the same time, then data loss is possible by design - check documentation about backups and Hazelcast replication. If you have 1 backup (default) and lose 2 members (more than number of backups), then some partitions may lose all replicas.

> With ReplicatedMap, this problem not occurred.

Yes, replicated map keeps copy of entire structure on each member.
