### ISSUE TITLE
com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.delete_updates_last_update_time [HZ-4834] [HZG-221]

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast#26346]
_master_ (commit cf4fdf16f962371a4a5b03a89e5995295c6c98d8)

Failed on oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/100/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.assertLastUpdateTime(LocalRecordStoreStatsImplTest.java:221)
	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.assertLastUpdateTimeUpdated(LocalRecordStoreStatsImplTest.java:210)
	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.delete_updates_last_update_time(LocalRecordStoreStatsImplTest.java:183)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: clear_does_not_update_last_update_time_when_map_is_empty in 0.829 seconds.
20:27:35,174  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [MapServiceContextImpl] Thread-49689 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Force offload is enabled for all maps. This means all map operations will run as if they have map-store configured. The intended usage for this flag is testing purposes.
20:27:35,176  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [Diagnostics] Thread-49689 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
20:27:35,176  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [LifecycleService] Thread-49689 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
20:27:35,176  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [ClusterService] Thread-49689 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 588e532a-2eaa-461a-b349-6296eb94dfd7 this
]

20:27:35,176  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [LifecycleService] Thread-49689 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
20:27:35,177  INFO |delete_does_not_update_last_update_time_when_no_matching_key| - [PartitionStateManagerImpl] delete_does_not_update_last_update_time_when_no_matching_key - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Initializing cluster partition table arrangement...
20:27:35,181  INFO |delete_updates_last_update_time| - [HazelcastTestSupport] Thread-49683 - Shutting down node factory as @After action
20:27:35,181  INFO |delete_updates_last_update_time| - [LifecycleService] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:27:35,181  WARN |delete_updates_last_update_time| - [Node] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Terminating forcefully...
20:27:35,181  INFO |delete_updates_last_update_time| - [Node] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Shutting down connection manager...
20:27:35,181  INFO |delete_updates_last_update_time| - [Node] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Shutting down node engine...
20:27:35,183  INFO |delete_updates_last_update_time| - [NodeExtension] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Destroying node NodeExtension.
20:27:35,183  INFO |delete_updates_last_update_time| - [Node] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
20:27:35,183  INFO |delete_updates_last_update_time| - [LifecycleService] Thread-49683 - [127.0.0.1]:5701 [dev] [5.5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after delete_updates_last_update_time(com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest): BuildInfo{version='5.5.0-SNAPSHOT', build='20240526', buildNumber=20240526, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'delete_updates_last_update_time(com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest):'
20:27:30, accumulated pauses: 830 ms, max pause: 777 ms, pauses over 1000 ms: 0
20:27:35, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-force-offload/100/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-force-offload/101/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/103/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/106/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by sumnerib** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/108/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by orcunc** [comment]
Increased the sleep time in the test

**Comment by olukas** [comment]
Reopening as issue occurred again on: _master_ (commit c02cc08b368e9e020fb81848cdbdfcdaecb35384)
with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/110/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  1722803584564L
to be greater than:
  1722803584564L

	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.assertLastUpdateTime(LocalRecordStoreStatsImplTest.java:222)
	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.assertLastUpdateTimeUpdated(LocalRecordStoreStatsImplTest.java:211)
	at com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest.delete_updates_last_update_time(LocalRecordStoreStatsImplTest.java:184)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:842)

```
</details>


<details><summary>Standard output:</summary>

```
Finished Running Test: remove_does_not_update_last_update_time_when_no_matching_key in 0.468 seconds.
20:33:05,032  INFO |delete_updates_last_update_time| - [HazelcastTestSupport] Thread-18959 - Shutting down node factory as @After action
20:33:05,032  INFO |delete_updates_last_update_time| - [LifecycleService] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
20:33:05,032  WARN |delete_updates_last_update_time| - [Node] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Terminating forcefully...
20:33:05,032  INFO |delete_updates_last_update_time| - [Node] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down connection manager...
20:33:05,032  INFO |delete_updates_last_update_time| - [Node] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Shutting down node engine...
20:33:05,036  INFO |delete_updates_last_update_time| - [NodeExtension] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Destroying node NodeExtension.
20:33:05,036  INFO |delete_updates_last_update_time| - [Node] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
20:33:05,036  INFO |delete_updates_last_update_time| - [LifecycleService] Thread-18959 - [127.0.0.1]:5701 [dev] [6.0.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after delete_updates_last_update_time(com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest): BuildInfo{version='6.0.0-SNAPSHOT', build='20240804', buildNumber=20240804, revision=, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'delete_updates_last_update_time(com.hazelcast.internal.monitor.impl.LocalRecordStoreStatsImplTest):'
20:33:00, accumulated pauses: 667 ms, max pause: 347 ms, pauses over 1000 ms: 0
20:33:05, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-force-offload/110/

**Comment by olukas** [comment]
Failed again on _5.5.z_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-force-offload/89/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/111/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/112/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

Failed again on _5.5.z_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-5.maintenance-force-offload/91/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/114/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/115/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/116/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by olukas** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-force-offload/118/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-force-offload/119/testReport/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with oracle-17 (force-offload): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-force-offload/120/testReport/junit/com.hazelcast.internal.monitor.impl/LocalRecordStoreStatsImplTest/delete_updates_last_update_time/

**Comment by AleksPeychev** [comment]
Fails constantly on `oracle-17 (force-offload)`
