### ISSUE TITLE
Security vulnerability due to com.fasterxml.jackson.core_jackson-core 2.14.2

### ISSUE THREAD

**Issue by DHachemi** [hazelcast/hazelcast#26355]
Hello Hazelcast-Team

**Description**
The security scanner we use in our project, Prisma, has flagged a vulnerability **PRISMA-2023-0067**: "om.fasterxml.jackson.core_jackson-core package versions before 2.15.0 are vulnerable to Denial of Service (DoS). The package does not properly restrict the size or amount of resources that are requested or influenced by an actor, which can be used to consume more resources than intended and leads to Uncontrolled Resource Consumption"

Hazelcast 5.4.0 use jackson-core 2.14.2 as **shaded** dependency. So we can't override the version.

**Suggestion to fix the Problem**:
Please update the jackson-core version to 2.15.0 and release a new hazelcast version as soon as possible. 

Thank you

**Comment by kwart** [comment]
Thanks for the report.

The Jackson version is already bumped (`2.17.1` as of now) - see https://github.com/hazelcast/hazelcast/blob/bc76c4b36459bf6d621869b6963d74bec17130d1/hazelcast-parent/pom.xml#L112.

**Comment by DHachemi** [comment]
Thanks for the response. But sadly the jackson-core version in jar of Hazelcast 5.4.0 is 2.14.2
![grafik](https://github.com/hazelcast/hazelcast/assets/73469378/c417ff45-47ea-4219-8b5a-2f9e802d1a1f)
see the pom.xml or pom.properties
![grafik](https://github.com/hazelcast/hazelcast/assets/73469378/de330733-04e7-4a2a-90fe-c8610c75406e)

**Comment by kwart** [comment]
We don't change released artifacts.
The fix will be present in the next released version.
Enterprise customers will receive the patch in the patch stream (`5.4.z`), and the community edition will receive it in `5.5.0`.

See also the https://hazelcast.com/blog/changes-to-community-edition/

**Comment by ssu2-atl** [comment]
> Enterprise customers will receive the patch in the patch stream (5.4.z), and the community edition will receive it in 5.5.0.

@kwart hi, will there be a Hazelcast 5.4.2 release containing the patch, and if so, when? 😄

**Comment by kwart** [comment]
> @kwart hi, will there be a Hazelcast 5.4.2 release containing the patch, and if so, when? 😄

I'm no longer with Hazelcast, so please ask the support team for the release plans. :pray:
