### ISSUE TITLE
com.hazelcast.jet.JobStatusListenerTest [HZ-4802]

### ISSUE THREAD

**Issue by Patras3** [hazelcast/hazelcast#26366]
_master_ (commit d20a471245471d2cd90d8aaac10403417eb9f279)

Failed on oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/
There are few failures:
* [testListenerDeregistration[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListenerDeregistration_onClient_)	
```
Multiple Failures (2 failures)
 java.lang.AssertionError: expected:<[Jet: NOT_RUNNING -> STARTING, Jet: STARTING -> RUNNING]> but was:<[Jet: STARTING -> RUNNING, Jet: STARTING -> RUNNING]>
 java.lang.AssertionError: <no message>
 ```

* [testListener_jobFails[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListener_jobFails_onClient_)	
```
expected:<[Jet: NOT_RUNNING -> STARTING, Jet: STARTING -> RUNNING, Jet: RUNNING -> FAILED (com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0be7-a06c-e4c6-0001/batchSource#0}: com.hazelcast.jet.JetException: mock error)]> but was:<[Jet: STARTING -> RUNNING, Jet: STARTING -> RUNNING, Jet: RUNNING -> FAILED (com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0be7-a06c-e4c6-0001/batchSource#0}: com.hazelcast.jet.JetException: mock error)]>
```	

* [testListener_restartOnException[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListener_restartOnException_onClient_)	
```
Expected 'length' to be between 5 and 6, but was 9
```	

* [testListener_suspendOnFailure[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListener_suspendOnFailure_onClient_)	
```
Expected 'length' to be between 3 and 4, but was 5
```	

* [testListener_suspend_resume_restart_cancelJob[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListener_suspend_resume_restart_cancelJob_onClient_)		
```
Expected 'length' to be between 9 and 10, but was 17
```

* [testListener_waitForCompletion[onClient]](https://jenkins.hazelcast.com/job/Hazelcast-mono-OS-master-sonar/197/testReport/com.hazelcast.jet/JobStatusListenerTest/testListener_waitForCompletion_onClient_)
```
expected:<[Jet: NOT_RUNNING -> STARTING, Jet: STARTING -> RUNNING, Jet: RUNNING -> COMPLETED]> but was:<[Jet: STARTING -> RUNNING, Jet: STARTING -> RUNNING, Jet: RUNNING -> COMPLETED]>
```

**Comment by Patras3** [comment]
Failed again on _master_ with oracle-17 (sonar build): https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/519/testReport/junit/com.hazelcast.jet/JobStatusListenerTest/

**Comment by AleksPeychev** [comment]
Failed again on _master_ with openj9-21: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-21-nightly/25/testReport/junit/com.hazelcast.jet/JobStatusListenerTest/

**Comment by Fly-Style** [comment]
`git bisect` blames https://github.com/hazelcast/hazelcast-mono/pull/2163

**Comment by olukas** [comment]
Failing constantly.
