### ISSUE TITLE
Potential race conditions messed up the size attribute in the MapIndexService class

### ISSUE THREAD

**Issue by kna3ga** [hazelcast/hazelcast#2714]
Versions affected
-----------------------------
I tested this in 2.6, 2.6.7 and 2.6.9. They all have the same issue

Setup
-----------------------------
I have a map, which has a map loader but not a map store. The map has a TTL of 3 minutes. I also set a max size of 1000 across the cluster for the map. For the tests I ran, I have only two readers that read the map every 10 seconds. The expectation was the map gets recycled every three minutes and the map loader will load entries afterward.

To simplify the test, I used only one node.The other map configurations I used included one copy of asynchronous backup but no backup read. 

Issue
-----------------------------
The setup worked well for two cycles. After that, the size attribute of MapIndexService quickly reached the max size. After that, the system ran into the constant load-and-evict cycles. 

I believe this issue is very likely the same as the issue #2355 reported by another user.

I did some research on my side. I added a few log lines in CMap class. The log lines printed the size of MapIndexService. Please see an example below. The first column is the "Time". You can see the 3-minute gap in the first few lines. The second column is the method where either updateIndexes(record) or mapIndexService.remove(record) was called. The ID column is the id of the record. Key is the key of the record. Active indicates whether the record was active. The before column is the size of MapIndexService before updateIndexes(record) or mapIndexService.remove(record) was called. The after is the counterpart after the call.

The map size should have stayed at 456. As you can see from the example, the value was messed up at 14:14:25.

Do you think this is a bug? Did I configure the map wrong? Thanks for the help!

Time,In Method,ID,Key,Active,Before,After
14:08:18, put, id=4, key=10462, active=true, size=0, size=1
14:11:22, put, id=4, key=10462, active=true, size=456, size=456
14:14:25, put, id=466, key=10462, active=true, size=456, size=457
14:17:25, markEvict, id=1233, key=10462, active=false, size=761, size=761
14:17:26, put, id=2062, key=10462, active=true, size=761, size=762
14:17:43, markEvict, id=2062, key=10462, active=false, size=993, size=992
14:17:43, removeAndPurgeRecord, id=2062, key=10462, active=false, size=1000, size=1000
14:17:48, put, id=2649, key=10462, active=true, size=993, size=994
14:17:55, markEvict, id=2649, key=10462, active=false, size=984, size=983
14:17:57, removeAndPurgeRecord, id=2649, key=10462, active=false, size=995, size=995
14:18:10, put, id=3093, key=10462, active=true, size=969, size=970
14:18:18, markEvict, id=3093, key=10462, active=false, size=985, size=984
14:18:19, removeAndPurgeRecord, id=3093, key=10462, active=false, size=998, size=998
14:18:32, put, id=3538, key=10462, active=true, size=985, size=986
14:18:39, markEvict, id=3538, key=10462, active=false, size=980, size=979
14:18:40, removeAndPurgeRecord, id=3538, key=10462, active=false, size=996, size=996
14:18:54, put, id=3982, key=10462, active=true, size=961, size=962
14:19:02, markEvict, id=3982, key=10462, active=false, size=982, size=981
14:19:03, removeAndPurgeRecord, id=3982, key=10462, active=false, size=994, size=994
14:19:17, put, id=4427, key=10462, active=true, size=977, size=978
14:19:24, markEvict, id=4427, key=10462, active=false, size=968, size=967
14:19:25, removeAndPurgeRecord, id=4427, key=10462, active=false, size=998, size=998
14:19:41, put, id=4872, key=10462, active=true, size=993, size=994
14:19:46, markEvict, id=4872, key=10462, active=false, size=990, size=989
14:19:48, removeAndPurgeRecord, id=4872, key=10462, active=false, size=999, size=999
14:20:03, put, id=5316, key=10462, active=true, size=969, size=970
14:20:10, markEvict, id=5316, key=10462, active=false, size=995, size=994
14:20:11, removeAndPurgeRecord, id=5316, key=10462, active=false, size=999, size=999
14:20:26, put, id=5767, key=10462, active=true, size=985, size=986
14:20:31, markEvict, id=5767, key=10462, active=false, size=997, size=996
14:20:32, removeAndPurgeRecord, id=5767, key=10462, active=false, size=1000, size=1000
14:20:49, put, id=6212, key=10462, active=true, size=962, size=963
14:20:53, markEvict, id=6212, key=10462, active=false, size=975, size=974
14:20:54, removeAndPurgeRecord, id=6212, key=10462, active=false, size=961, size=961
14:21:34, put, id=7136, key=10462, active=true, size=989, size=990
14:21:37, markEvict, id=7136, key=10462, active=false, size=972, size=971
14:21:38, removeAndPurgeRecord, id=7136, key=10462, active=false, size=999, size=999
14:21:57, put, id=7618, key=10462, active=true, size=964, size=965
14:22:00, markEvict, id=7618, key=10462, active=false, size=987, size=986
14:22:01, removeAndPurgeRecord, id=7618, key=10462, active=false, size=962, size=962
14:22:19, put, id=8078, key=10462, active=true, size=995, size=996
14:22:22, markEvict, id=8078, key=10462, active=false, size=992, size=991
14:22:23, removeAndPurgeRecord, id=8078, key=10462, active=false, size=1000, size=1000

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?
