### ISSUE TITLE
Papercut: hazelcast is not wget-able

### ISSUE THREAD

**Issue by Dretch** [hazelcast/hazelcast#2814]
It is not possible to copy the link from http://hazelcast.org/download/ and run `wget` on it:

```
garethsmith@Gareths-MacBook-Pro:~$ --2014-06-24 11:59:29--  http://download.hazelcast.com/download.jsp?version=hazelcast-3.2.3
Resolving download.hazelcast.com... 184.73.156.42
Connecting to download.hazelcast.com|184.73.156.42|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2014-06-24 11:59:29 ERROR 404: Not Found.
```

Clicking the link in a browser works as expected. This makes deploying hazelcast slightly more difficult.

**Comment by Nakiami** [comment]
Same problem
```
wget http://download.hazelcast.com/download.jsp?version=hazelcast-3.4.2&p=
ubuntu@xxx:~$ --2015-04-15 06:28:52--  http://download.hazelcast.com/download.jsp?version=hazelcast-3.4.2
Resolving download.hazelcast.com (download.hazelcast.com)... 184.73.156.42
Connecting to download.hazelcast.com (download.hazelcast.com)|184.73.156.42|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-04-15 06:28:52 ERROR 404: Not Found.
```

**Comment by kobalski** [comment]
Hi Nakiami,
If you want to use wget you should use it like this,
```wget http://download.hazelcast.com/download.jsp --post-data "version=hazelcast-3.4.2&p=&type=zip" -O hazelcast.3.4.2.zip```
Currently our download API only supports HTTP POST.

**Comment by Dretch** [comment]
Is there any chance of reverting to using a GET-able download?

I have noticed other people in my organisation running into this issue and downgrading their opinion of the ease-of-use of Hazelcast as a result.

**Comment by jerrinot** [comment]
I'm re-opening this as I agree it's quite inconvenient. I don't understand why it requires HTTP POST.

**Comment by bilalyasar** [comment]
Can you try `wget "http://download.hazelcast.com/download.jsp?version=hazelcast-3.5.2&p=113242738"` ? it works in my local.

**Comment by jerrinot** [comment]
@bilalyasar: It works for me. I'm closing the ticket again. Thanks for your help!
@Serdaro: Perhaps we could document this?

**Comment by Dretch** [comment]
Ah, it works, but only if you use quotes around the argument to wget, because bash interprets the `&` in the url as an operator.

This is an oversight on my part, apologies, although it would be great if the url was something simple like `http://download.hazelcast.com/download/hazelcast-3.5.2.tar` because that would be wget-able even without quotes.

**Comment by Sequential-circuits** [comment]
I agree: for something that it is still looking for his place in the market, not being able to do a simple wget is a major way to lose potential customers. Hope I am being useful and hope you finally fix this
