### ISSUE TITLE
Network connection loss does not release lock (Again)

### ISSUE THREAD

**Issue by hoegertn** [hazelcast/hazelcast#2818]
The issue https://github.com/hazelcast/hazelcast/issues/2254 is not resolved as of version 3.3-EA2. Is this correct?

Our client code can be found here: https://github.com/cinovo/cloudconductor-client

**Comment by Chandan83** [comment]
The issue can be still reproduced in version 3.5. I reproduced it by repeatedly tcpkilling on port 5701 while the client is trying to tryLock on a constant string. Once in a while, the lock goes in a state when it can no longer be locked again even after restarting the client process.
