### ISSUE TITLE
Heartbeat causing memory leak on server

### ISSUE THREAD

**Issue by mboisver** [hazelcast/hazelcast#2829]
In 2.x, the heartbeat in com.hazelcast.client.ConnectionManager creates new threads for each execution of the heartbeat.  This leads to a memory leak on the server as new CallContext objects are created for each client thread.

Here is the simplified code that creates new threads for each heartbeat execution:

       void scheduleHeartbeatTimerTask() {
              final int TIMEOUT = config.getConnectionTimeout();
              heartbeatTimer.schedule(new TimerTask() {
                     @Override
                     public void run() {
                           //runs repeatedly
                           new Thread(new Runnable() {
                                  public void run() {
                                         Set<Member> members = client.getCluster().getMembers();
                                  }
                           }).start();
                     }
              }, TIMEOUT / 10, TIMEOUT / 10);
       }

![image](https://cloud.githubusercontent.com/assets/7981119/3389855/f84b4a1a-fc98-11e3-93a5-118fae1f35df.png)

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/3323
