### ISSUE TITLE
Provide access to co-located entries from Mappers

### ISSUE THREAD

**Issue by nickersan** [hazelcast/hazelcast#3003]
In order to perform aggregate operations it's common to access values related to those being mapped - the classic customer and order for example.  

Imagine a mapper that sums order values by customer.  The orders, keyed by order id and customer, are co-located with the customers using data-affinity.  When the mapper runs it must get the orders for a given customer and iterate over them.

To do this I have made the mapper NodeAware, which allows me to write the following to get the orders:

``` java
private Collection<Order> getCustomerOrders(CustomerKey customerKey)
{
  List<Order> orders = new ArrayList<>();

  MapService mapService = node.getClusterService().getNodeEngine().getService(MapService.SERVICE_NAME);

  RecordStore recordStore = mapService.getRecordStore(node.getPartitionService().getPartitionId(customerKey), "orders");

  for (Data key : recordStore.keySet())
  {
    OrderKey orderKey = mapService.getSerializationService().toObject(key);

    if (customerKey.equals(orderKey.getCustomerKey()))
    {
      orders.add(mapService.getSerializationService().toObject(recordStore.get(key)));
    }
  }

  return orders;
}
```

This allows the mapper to run in each node without the need for cross-process/network calls that would otherwise be needed to get the related orders.

It works a treat, however it's been pointed out that the APIs I'm using are internal and therefore subject to change.

Given this, please provide API similar to this, which allows co-located to be access cleanly from code running in the nodes of the cluster.

**Comment by noctarius** [comment]
Closed since the API is deprecated now.
