### ISSUE TITLE
PagingPredicate, -  returning duplicated elements, resulting in infinite loop.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#3047]
RP  https://github.com/hazelcast/hazelcast/pull/3042  show Junit test for this issue.

issue first discovered while making a stabilizer test, around queries and indexes.  

looks like range predicates,  run on a map with Ordered Indexes, don't work as expected

**Comment by ihsandemir** [comment]
related to https://github.com/hazelcast/hazelcast/issues/9968
