### ISSUE TITLE
XA conformance tests

### ISSUE THREAD

**Issue by lichtin** [hazelcast/hazelcast#3071]
Hi Ali

To followup on issues #2696 and #2697 that unfortunately are already cosed,
I'd like to pass on the XA test suite to you.
Hope you find it useful to verify Hazelcast XA use cases.

https://gist.github.com/lichtin/aac66eb05c4570863e6c#file-atomikos-hazelcast-tgz

**Comment by gurbuzali** [comment]
should be fixed in 3.5-EA, can you try and re-open if issue still exists

**Comment by lichtin** [comment]
Looking good, thanks!
