### ISSUE TITLE
Client logging configuration only works with system property

### ISSUE THREAD

**Issue by u6f6o** [hazelcast/hazelcast#3103]
Hi, 

We are currently using log4j as our main logger. On the server side we are using a system property to choose the right logging type, on the client side I'd prefer to use the declarative approach (XML) instead, as mentioned here: http://hazelcast.org/docs/latest/manual/html/logging.html

As it looks like, the logging type is not recognized if I am using anything else than the system property option. 

I also had a look on the Logger class provided by hazelcast (com.hazelcast.logging.Logger). The method #getLogger(String name) only takes the system property into account: 

public static ILogger getLogger(String name) {
        //noinspection DoubleCheckedLocking
        if (loggerFactory == null) {
            //noinspection SynchronizationOnStaticField
            synchronized (FACTORY_LOCK) {
                if (loggerFactory == null) {
                    String loggerType = System.getProperty("hazelcast.logging.type");
                    loggerFactory = newLoggerFactory(loggerType);
                }
            }
        }
        return loggerFactory.getLogger(name);
    }

Would be nice, if all other mentioned approachs would work as well.

**Comment by cleishm** [comment]
Hi @sancar,

We've also run into this issue. We'd like to use hazelcast as part of another java library, and thus setting system properties to control logging is not appropriate. The ideal would be to have the ability to inject a logging implementation into the hazelcast instance, and hazelcast client instance, during construction.

Additionally, we're interested in proving some of our time to implement this. However, after spending a little time looking into it already, the code is quite complex and it's not clear the best way to achieve this (there also appears to be two copies of the client code, which is confusing). Would someone at Hazelcast be interested in discussing this with us, and collaborating?

Cheers,
Chris

**Comment by Donnerbart** [comment]
Maybe the Hazelcast Incubator is the right place this change: http://blog.hazelcast.com/2015/02/27/the-hazelcast-incubator/

**Comment by cleishm** [comment]
@Donnerbart I note the following description in that blog: "The Hazelcast Incubator is an incubation process for external Hazelcast extensions.". This couldn't be implemented as an extension - logging is pervasive throughout the core Hazelcast codebase.

**Comment by Donnerbart** [comment]
The blog article may not reflect the whole Incubator purpose. Please have a look at the HEP wiki page: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals

I think this should fit your request quite well. Also you should get the help you need to implement this together with us.

**Comment by noctarius** [comment]
@Donnerbart is right, sounds like a good fit to me, if you're interested drop me a line to discuss further details. You can also join the gitter channel if you prefer realtime communication over email :)

**Comment by u6f6o** [comment]
Not sure if it's a good fit for the incubator. To me it's more like a bug. When I opened this initially, there were >=3 possibilities mentioned in the documentation how to configure the right logger but only one worked correctly. 

We solved this by statically defining the LoggerFactory in our patched hazelcast version and thus it was not important anymore. Since other people suffer on it as well, I'd rather not make it dependent on the incubator decision process.

**Comment by noctarius** [comment]
Yeah it won't be an easy job, especially because we have statically acquired loggers.

**Comment by cleishm** [comment]
@noctarius yeah.

I dropped you an email. Let's chat sometime.

**Comment by vania-pooh** [comment]
So far as I can understand system property remains the only working solution to switch from jdk logger to e.g. slf4j. Is it true for 3.6.x?

**Comment by mustafaiman** [comment]
This issue is resolved by https://github.com/hazelcast/hazelcast/pull/7521 and https://github.com/hazelcast/hazelcast/pull/8518 . Note that these fixes are for master branch therefore they will be available in hazelcast version 3.7. 
@vania-pooh yes for 3.6.x only solution is system property.
Closing this issue, if you experience further problems please feel free to open a new one.

**Comment by vania-pooh** [comment]
@mustafaiman ok, when do you plan to release 3.7?
