### ISSUE TITLE
java.io.EOFException[Could not read protocol type!]

### ISSUE THREAD

**Issue by sathyashree** [hazelcast/hazelcast#3116]
Hi Team,

We are getting an exception in our logs as follows
] Connection [Address[#.#.#.#]:#] lost. Reason: java.io.EOFException[Could not read protocol type!]

We are using 
 jdk version (1.7.0_51), 
 hazlecast.jar(hazelcast-3.2.3) 
vendor (Oracle Corporation)  across the members within the same cluster
Wanted to know why this occurs .Can you please give us pointers 

thanks
Sathya

**Comment by mdogan** [comment]
Network layer has been changed significantly in recent versions. Closing this issue since it's very old.
