### ISSUE TITLE
Configuration: Write behind interval after failure

### ISSUE THREAD

**Issue by lukasblu** [hazelcast/hazelcast#3197]
Hi @ahmetmircik ,

when using write-behind map stores, I'd like to have a way to configure the retry time interval after an exception in store().

Currently, when a store operation fails (e.g. due to a database which is not available), the store call is retried every 3 seconds. This might lead to huge amounts of log output.

What I would like to have is
- either some exponential back-off after a exception, e.g. retry after 2, 4, 8, 16, 32, ... seconds or
- a way to configure a much longer retry interval, e.g. several minutes.

I'm using the latest 3.3 version.

thanks and best,
Lukas

**Comment by bjansen** [comment]
FYI we just had the same problem on our project, but we found a rather easy workaround: just put additional `Thread.sleep()` statements *in your map store*. For example:

```java
public class MyMapStore implements MapStore<String, String>{
	@Override
	public void storeAll(Map<String, String> objects) {
		try {
			doTheActualStore();
		} catch (Exception e) {
			try {
				Thread.sleep(10000); // or whatever value/policy you'd like
			} catch (InterruptedException e1) {
				e1.printStackTrace();
			}
			throw e;
		}
	}
	...
}
```

Don't forget to rethrow the exception to let HZ retry the operation. Of course, this does not prevent other threads from adding more data to the map.

**Comment by Holmistr** [comment]
Closing this as a duplicate in favor of https://github.com/hazelcast/hazelcast/issues/9265
