### ISSUE TITLE
Extend MigrationListener interface with two new events when the whole migration process starts/finishes

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#3234]
Particulary the second (MigrationFinished) event can be very usefull. Listening app can start cache population, for instance.

Can be implemented firing events from InternalPartitionserviceImpl.MigrationThread.run method.

**Comment by Holmistr** [comment]
@mdogan I guess we can close this issue as the functionality is implemented in upcoming 4.0, correct?

**Comment by mdogan** [comment]
Yes, right. Thanks for reminding. This was fixed by https://github.com/hazelcast/hazelcast/pull/15071
