### ISSUE TITLE
Enabling Multicast and TCP/IP node discovery methods froze my instances

### ISSUE THREAD

**Issue by juan-palacios** [hazelcast/hazelcast#3246]
I started two different instances. Configuration was loaded programmatically:

hazelcast.network.multicast=true
hazelcast.network.tcpip=true
hazelcast.network.tcpip.members=localhost:5701,localhost:5702
hazelcast.port=5701

According to the generated thread dumps Hazelcast was trying to complete the Node.join operation, but it kept recursively going from a MulticastJoiner to a TcpIpJoiner and never actually completing the operation. As time went by the stack kept growing. My instances were frozen for over 30minutes until I killed one of them, and the other one was able to complete the join.

**Comment by qerub** [comment]
> […] but you can only have one join configuration active. So either multicast or tcp/ip. You can't have both of them.

You might want to document that clearly on http://docs.hazelcast.org/docs/latest/manual/html-single/hazelcast-documentation.html#hazelcast-clusters too.
