### ISSUE TITLE
Hazelcast client should not just ignore the fact the XML is for server and shouldn't use default xml feature to connect to localhost

### ISSUE THREAD

**Issue by amitohale** [hazelcast/hazelcast#3256]
when hazelcast client is failed to connect to any server node after parsing the server XML, it used the default client XML configuration present in hazelcast-client.jar which always connects to localhost. 

If this is expected behavior, client should log the name of xml as it's not the same configuration one expects it to be.

Example:

my-client-config.xml is same as server configuration with multicast discovery running with multiple nodes and one node on localhost and when I am creating the hazelcast instance it's connected to localhost. And if I kill the localhost node and run the same stuff again, it fails to connect.

ClientConfig conf = new XmlClientConfigBuilder("my-client-config.xml").build();
HazelcastInstance instance = HazelcastClient.newHazelcastClient(conf);

**Comment by bilalyasar** [comment]
closed via #4701
