### ISSUE TITLE
Huge amounts of network traffic with lots of map updates

### ISSUE THREAD

**Issue by voodooless** [hazelcast/hazelcast#326]
We have an map with at least 100k of data per entry (currently we use kryo to make the size small and performance good). The total size is about 10.000 items, but this will be bigger in the future.

This map gets updated very often, between 30 and 400 updates per seconds, randomly divided among the map keys (Long). We have another JVM listening for map updates.

We have at the moment a 3 node cluster, with about 10 tot 15 JVM running lite nodes. We also tried making all of them full nodes, but that didn't help much. We are running hazelcast 2.3.1, we'll try the fresh 2.4 asap.

The map is setup with an async-backup-count=1 and read-bakcup-data=true.

The thing is now that we never get past about 40 updates per second, and that network traffic is though the roof: it somewhere between 50 and 140 MBytes/sec (Tx and Rx combined).

So we are wondering what might cause this traffic. It almost looks like a complete parition is send over the network when we update one single item in the map. Is this so? If so, would increasing the partition count to a much larger number (say a prime number arround 10.000) help? Parition would then be much smaller, and it would mean that syncing them would generate far less traffic, but probably more overhead?

Or have we just missed some vital configuration option?

**Comment by lyubanlight** [comment]
It the same issue with 3.7.2

**Comment by jerrinot** [comment]
@lyubanlight: care to elaborate? what's the same in 3.7.2? You cannot get past 40 update / second?

**Comment by lyubanlight** [comment]
100 MB of data of 50 000 records generate 500Mbps traffic spikes during on 1 min every 10-15 min

**Comment by jerrinot** [comment]
@lyubanlight: can you share a reproducer?
