### ISSUE TITLE
The behaviour of operations that have negative timeout values

### ISSUE THREAD

**Issue by buremba** [hazelcast/hazelcast#3262]
I was going the create an issue about await(long, TimeUnit) method of ICondition but then realized that all of the operations that implements WaitSupport have the same problem too.

I have looked at
await(long, TimeUnit) method of java.util.concurrent.locks.Condition,
poll(long, TimeUnit) method of java.util.Queue,
tryAcquire(int, Long, TimeUnit) method of  java.util.concurrent.Semaphore 
and none of them waits if timeout is a negative value.

However all of the DistributedObject methods that take timeout value works same as their synchronous version.

Here is a test for ICondition:
```
@Test(timeout = 60000)
    public void testAwait_whenNegativeTimeout() throws InterruptedException {
        HazelcastInstance instance = createHazelcastInstance();

        final ILock lock = instance.getLock(randomString());
        final ICondition condition = lock.newCondition(randomString());

        lock.lock();

        assertFalse(condition.await(-1, TimeUnit.MILLISECONDS));
    }
```

Should we change this behaviour or just document it?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/7bdea0ffe89855213f4c8a5ac47041e0d8b06e31
