### ISSUE TITLE
Undocumented local integrity implications of com.hazelcast.web.WebFilter's deferred-write parameter

### ISSUE THREAD

**Issue by BGehrels** [hazelcast/hazelcast#3269]
Due to the LocalCache not being enabled when not setting deferred-write=true, subsequent calls to session,getAttribute("myKey") will neither return the same instance, nor will changes to the returned object be visible to subsequent calls.

```
session.setAttribute("myKey", new ArrayList()); // Will serialize the ArrayList
List list1 = session.getAttribute("myKey"); // Will deserialize the original List
list1.add("myValue"); // Will not be serialized

List list2 session.getAttribute("myKey"); // Will deserialize the original List again
System.out.println(list1 == list2); // false
System.out.println(list1.getSize()) // 1
System.out.println(list2.getSize()) // 0
```

After reading the Servlet Spec, I'm not sure if this behaviour is compliant. The spec is not very verbose regarding this topic. But: Since the behaviour differs when switching deferred-write parameter on and off, it should at least be clearly documented (with a big red warning sign).

Took me quite some time digging through Spring Web Flows source code.

**Comment by mdogan** [comment]
This issue was moved to hazelcast/hazelcast-wm#45
