### ISSUE TITLE
Hazelcast client fails to connect when we provide variables from System properties

### ISSUE THREAD

**Issue by amitohale** [hazelcast/hazelcast#3270]
Hazelcast server configuration supports using dynamic values in config XML by providing the values using system property, which gives us flexibility to use same XML configuration on different machines. 

When we call build over XmlConfigBuilder class, it replaces the dynamic variables using system properties. 
We have a method XmlConfigBuilder.replaceVariables() which does this stuff. 
But this functionality is been missing in client. Can we have this added in client as well?

Here is the snapshot of code which is present in XmlConfigBuilder.java

![image](https://cloud.githubusercontent.com/assets/8443012/3926793/d38e203e-23f4-11e4-8a68-33c1546d9805.png)

**Comment by bilalyasar** [comment]
closed via #4581
