### ISSUE TITLE
Multicast + ConfigCheck

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#3288]
Multicast sends a join request that contains a ConfigCheck. The problem is that multicast is bound to the MTU and since the JoinRequest is send using a single datagram, the size of the ConfigCheck is bound to the MTU. This is going to give problems when the JoinRequest has a lot of information; e.g. when there are many maps configured or maps have a long name. 

Currently this isn't an issue since the ConfigCheck is almost empty; but when more structures are added to it, it is going to give problems.

Perhaps the ConfigCheck should not be part of the JoinMessage at all; but it should be done as part of the tcp connection setup.

**Comment by mmedenjak** [comment]
@pveentjer can this one be closed then?
