### ISSUE TITLE
FactoryImpl maintaining references to ClientEndpoint objects after connection is closed leading to memory leak

### ISSUE THREAD

**Issue by mboisver** [hazelcast/hazelcast#3308]
In 2.x, FactoryImpl maintains references to ClientEndpoint objects even after the client connection has been closed.  Those lingering ClientEndpoint instances, in turn, prevent their CallContext objects from being garbage-collected (we have reported another issue that causes a leak of CallContext objects here: https://github.com/hazelcast/hazelcast/issues/2829).  This causes a memory leak as our client services are restarted.

See the heap dump below.  Note that the connection is not live, and that the ClientEndpoint objects are successfully removed from the ClientHandlerService's references.  The first image is an instance of ClientEndpoint with a connection that is still live, for comparison.

![image](https://cloud.githubusercontent.com/assets/7981119/3959055/af0b97de-2726-11e4-8521-30625cc65be4.png)

![image](https://cloud.githubusercontent.com/assets/7981119/3959059/ca875336-2726-11e4-9a46-09f0d58c16c9.png)

**Comment by mdogan** [comment]
fixed by #5503
