### ISSUE TITLE
[operation] Split operation call timeout

### ISSUE THREAD

**Issue by juan-palacios** [hazelcast/hazelcast#3314]
As explained in issue [1431](https://github.com/hazelcast/hazelcast/issues/1431) the value of 'hazelcast.operation.call.timeout.millis' is double in the remote instance to account for latency. This strategy does not provide configuration flexibility. The default value of the property is 60secs which results in remote nodes waiting for up to 2mins when the remote node is unresponsive.

We'd like to see this property be split into to so that more sensible values can be configured.

**Comment by mmedenjak** [comment]
@juan-palacios closing this issue as the invocation system was changed in 3.7 and I can't find any trace of the call timeout doubling since. Please try upgrading to the newest hazelcast release.
