### ISSUE TITLE
hazelcast web session replication doesn't replicate when shutdown

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3362]
full story is here: https://groups.google.com/forum/#!topic/hazelcast/H1FWmMgBdz4
when server goes to shutdown, our architecture couldn't get whether this process is shutdown or timeout.
so in some cases replication doesn't work.

```
    @Test
    public void test() throws Exception {
        CookieStore cookieStore = new BasicCookieStore();
        executeRequest("write", serverPort1, cookieStore);
        server1.restart();
        assertEquals("value",executeRequest("read", serverPort2, cookieStore));
    }
```

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/7112
