### ISSUE TITLE
Master node does not rejoin the cluster

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#3399]
I bring up 3 nodes in sequential order at a interval of 5 seconds to form a 3 nodes cluster. I then block the port (5701) of the Master node using iptables (command below) and after the configured HA settings, the master node gets disconnected from the other 2 nodes with "Reason: Socket explicitly closed" and goes out of the cluster. Node 2 among the other 2 nodes becomes the new master and the cluster continues to work - all fine so far.

Now I unblock the port (5701) of the old Master node using iptables (command below) and after a few seconds, I see the old Master node establishing connection with Node 2, which is the new Master of the cluster and the connection succeeds. No attempt of handshaking with Node 3.

And then, nothing happens. The cluster sits quiet. I left it on for 15 mins from this point onward and nothing happened. No updates regarding new node joining the cluster, no updates in partition tables, no updates in members info on console. This leads me to believe that the cluster has ignored the new handshake and continues to work as 2 node cluster.

This is easily reproducible on 3.2.4-ee (I had the libraries already setup so went with the enterprise version), RC4-SNAPSHOT.

To reproduce, you just need to spawn server instances using Hazelcast.newHazelcastInstance();

Commands to block and unblock port using iptables:

```
sudo /sbin/iptables -I INPUT -p tcp --destination-port 5701 -j DROP
sudo /sbin/iptables -I OUTPUT -p tcp --dport 5701 -j DROP
sudo service iptables save


sudo /sbin/iptables -I INPUT -p tcp --destination-port 5701 -j ACCEPT
sudo /sbin/iptables -I OUTPUT -p tcp --dport 5701 -j ACCEPT
sudo service iptables save
```

**Comment by demon-xxi** [comment]
Any progress on this issue? It is still happening for us too.

**Comment by ali-sharghi** [comment]
tcp or multicast does not work on centOS:

two nodes on the same VM machine
two nodes on the different VM machine

**Comment by gmarone** [comment]
im also having the same problem.

**Comment by lvca** [comment]
I have the same problem with Hazelcast 3.6.5, documented also here: https://github.com/hazelcast/hazelcast/issues/9358.

**Comment by mdogan** [comment]
The original reported issue is not a bug, should be considered as configuration problem. For other issues please file a separate report.
