### ISSUE TITLE
Add option to allow initial replication of data for WAN replication

### ISSUE THREAD

**Issue by wolfcastle** [hazelcast/hazelcast#344]
This is an enhancement request.

WAN Replication only replicates updates from one cluster to another. If an entire cluster is taken down/fails then reconnects some time later, only updates since it last connected are sent. Any original data in the map that existed prior to the cluster failure is not sent. For very large data sets, this makes sense, as you might not want to (or be able to) send that volume of data over a WAN.

However, some uses only need to synchronize a small amount of data, and it would be useful if there was an option to enable the replication of the initial data at startup.

See https://groups.google.com/d/topic/hazelcast/zYbqcJaik0E/discussion for some background.

**Comment by mmedenjak** [comment]
This feature is available in the enterprise version of hazelcast since 3.7. Please see the relevant section in the reference manual - http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#synchronizing-wan-target-cluster. Because of this, I am closing the issue.
