### ISSUE TITLE
Removal of response thread

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#3444]
There are 2 response threads in the system; client side and serverside. The problem is that this response thread takes work from a response queue. The response queue is accessed concurrently by the IO threads and by the response thread; so therefore it is a contention point + adds additional latency.

The optimization: get rid of the response thread/response queue and let the IO thread directly invocate the future.notifyWithSomeRespone. The actual deserialization of the return value is still done on the user thread (so the thread that does future.get or on a threadpool thread of asynchrononous future listeners). So the amount of work done on the IO thread is little; but the contended response queue is replaced by an uncontended monitor in the future.

Some of the performance tests showed a 10/20% performance improvement.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue.

**Comment by pveentjer** [comment]
I have removed it a few times and I didn't get significant performance improvements. Probably I'll give it another go in HZ 3.6. Also want to get rid of the Response objects completely (more litter). 

For the 3.5 release we are all trying to complete our features; so we don't have much time for this stuff.

**Comment by pveentjer** [comment]
I'm going to close this ticket. We did quite a lot of performance in 3.7, but having this response queue in here still gives the best performance. The main reason is that the io threads are very sensitive to thread notifications; which would be something whey need to do for every response. By offloading this to a dedicated thread (the response thread), the io system is not burdened by this and we get the highest throughput.
