### ISSUE TITLE
Programmatic access to number of immediate/scheduled migration tasks

### ISSUE THREAD

**Issue by daokeeff** [hazelcast/hazelcast#352]
In line with the google groups topic here: https://groups.google.com/forum/?fromgroups=#!topic/hazelcast/2mfz1nPtvKw , it would be useful to have programmatic access to the number of outstanding migration tasks. I'd like to be able to query this number and also to subscribe to notification events for when it changes. 

In particular I'd like to know when all partitions are in a safe state after a failure (i.e. the requisite number of backups has been re-established).

**Comment by enesakar** [comment]
see following API (since 3.3)
http://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/core/PartitionService.html#isClusterSafe()
http://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/core/PartitionService.html#isMemberSafe(com.hazelcast.core.Member)
