### ISSUE TITLE
hazelcast config setStatisticsEnabled behaviour

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3555]
there are some problems with hazelcast setStatisticsEnabled (or LocalStats) behaviour.

1) we can use setStatisticsEnabled method in Collections(set,list) config, but we don't have something like list.getLocalListStats, so what is the purpose of this config? seems there is no documentation about it.

2) for IQueue, when we disable statistics, we can continue to get localQueueStats, i think expected behaviour must `" we couldn't get localQueueStats and Node shouldn't save statistics"`,  following test passes regardless of setStatisticsEnabled true or false:

```
        String name = randomString();
        Config config = new Config();
        QueueConfig queueConfig = config.getQueueConfig(name);
        queueConfig.setStatisticsEnabled(false);
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);
        IQueue queue = hz.getQueue(name);
        System.out.println(hz.getConfig().getQueueConfig(name).isStatisticsEnabled());
        queue.offer("item");
        LocalQueueStats stats = queue.getLocalQueueStats();
        assertEquals(1, stats.getOwnedItemCount());
```

i have tried same case for IMap and result is: `we couldn't get localMapStats when statistics are disabled.` :+1: 
apparently, some statistics methods or behaviours should be revised or documented.

**Comment by burakcelebi** [comment]
Closed as internal request.
