### ISSUE TITLE
AbstractIOSelector cpu high usage  when hazelcastserver and hazelcastclient in the same server

### ISSUE THREAD

**Issue by char1st** [hazelcast/hazelcast#3566]
top

top - 12:01:39 up 1:49, 9 users, load average: 0.01, 0.04, 0.15
Tasks: 184 total, 1 running, 183 sleeping, 0 stopped, 0 zombie
%Cpu(s): 9.6 us, 5.9 sy, 0.0 ni, 83.1 id, 0.6 wa, 0.8 hi, 0.0 si, 0.0 st
KiB Mem: 3922564 total, 2319476 used, 1603088 free, 107004 buffers
KiB Swap: 0 total, 0 used, 0 free. 769192 cached Mem
PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
19915 hu1 20 0 3490176 622308 12408 S 102.7 15.9 5:17.01 java
23049 hu1 20 0 2876348 59852 11980 S 61.5 1.5 0:50.11 java

pidstat -p 19915 -u 1 3 -t

Average: UID TGID TID %usr %system %guest %CPU CPU Command
Average: 1000 - 19955 6.31 6.64 0.00 12.96 - |__java
Average: 1000 - 19956 7.31 15.28 0.00 22.59 - |__java

**Comment by pveentjer** [comment]
I'm going to close this issue. I have not seen any issues with clients/servers on the same machine.
