### ISSUE TITLE
replicated map problems

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3631]
for a while, i am examining replicatedMap codes, logic , working principles , here are my findings:

- we couldn't add entryListener for specific key.. EntryEvents are called everytime. see https://gist.github.com/bilalyasar/0e50fbca77d4b5b70a02

- when we add entry with timeout , and when we add entryListener, after timeout, entry.evicted doesn't called. see: https://gist.github.com/bilalyasar/3729a9864d240215205a

- when we add entry with timeout, and after timeout, actually entry is not removed from map. (memory leak)  i dont have test for this, i am tracking this bug with debug mode. 
problem is at: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/AbstractReplicatedRecordStore.java#L114

- javadoc exceptions problems: there are some cases map doesn't throw exceptions. For example: adding null entryListener, this should be revised.

- also i see that, map.clearAll, evictAll events are not implemented. This could be nice feature.

- when we start instance, instance automatically get distributed proxies with FinalizeJoinOperation, and after instance get proxy calls replicatedMap.initialize() method for synchronize replicatedMap. Also this method is called again when we get hazelcast.getReplicatedMap(). maybe some optimizations could be done in this respect.

**Comment by eminn** [comment]
Fixed by #6176
