### ISSUE TITLE
Setting "public-address" prevents MulticastJoiner from discovering nodes behind NAT

### ISSUE THREAD

**Issue by philmay** [hazelcast/hazelcast#370]
Hi,

I am using Hazelcast Community Edition 2.4 (20121017)

I have been trying to get WAN replication to work with one of my clusters behind a NAT proxy. If I don't set a \<public-address\> in the config for my cluster behind the NAT, the local cluster members behind the NAT find each other correctly, but I get the "Wrong bind request... This node is not requested endpoint" error when the remote cluster tries to send data through the NAT (bind fails?).

If I do set a \<public-address\> in the config, the remote cluster can send data successfully through the NAT, but none of the nodes behind the NAT recognize each other using multicast. It's like each node is in its own single-node cluster.

Is there a way to get the multicast operation to ignore the \<public-address\> setting. I think Hazelcast will work for us if this can be fixed.

Thanks

**Comment by dalgibbard** [comment]
Came across this 'bug' whilst trying to deploy OrientDB (interestingly, in place of our current CouchDB ;-D ) - I'm doing roughly the same thing as the Op, except with tcp-ip in place of multicast. I'm essentially trying to build out three individual global clusters (for this example, consisting of 5 nodes each), and then replicate bi-directionally between each cluster (using wan-replication). The fiddly part comes where:

* I only want to nominate two nodes of each cluster to be the 'global-replicators' (ie. have a Public Address configured)
* All inter-cluster communication should be on the internal interfaces.

The trouble occurs when I configure these public addresses for the boxes which will act as endpoints, and hazelcast starts rejecting traffic on the internal interfaces...

It would be amazing if we could just have a flag which eases up this behaviour; or probably the better options is to let us explicitly define which IPs a server 'owns'?

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?
