### ISSUE TITLE
Statistics API and implementations are not consistent

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#3703]
Some statistics are collected on caller side, some are on owner/executor side, some are mix of former two. Some operation stats are collected before execution, some are after execution.
- `LocalMapStats`: 
  - Most of operation stats are collected on caller, after response received; put, get, remove
  - Some operation stats are collected on owner, after operation execution; tx.put, tx.remove, entry processor operations
  - Event stats are collected on owner, after event published
  - Data stats (owned count, backup count, memory costs etc) are collected on owner
- `LocalQueuStats`:
  - All stats collected on owner node
  - Operation stats are collected after operation execution
- `LocalTopicStats`:
  - When globally ordered, stats are collected before operation execution
  - Otherwise, stats are collected on publisher side before publish

Multimap stats and ReplicatedMap stats are similar to map stats. Executor stats are collected on executor node.

... etc..

**Comment by burakcelebi** [comment]
Closed as internal request.
