### ISSUE TITLE
Hazelcast.getLock() takes considerable time to return Lock object

### ISSUE THREAD

**Issue by somasundaramsekar** [hazelcast/hazelcast#372]
I'm running Hazelcast Cluster with weblogic 11g and trying to sync few operations across cluster. Hazelcast.getLock looked to be a perfect solution. but it turns out that getLock takes 15-20ms to return the lock object, the application currently been deployed on top of Virtualized blades as a part of development and testing environment, if this issue is due to the serialization of keys, then this time might probably increase on live environment, with locking to happen across clusters over the wire, 

Is this a known issue..

**Comment by murali0908** [comment]
I am able to observe this issue in my two-node Hazelcast cluster. Here are the log events where two threads got the lock at the same time. If you look at the log events, there is a 2 milli seconds difference between both threads and both threads got same counter value.

2017-05-15 10:43:37.0419 INFO  ? counter : a
2017-05-15 10:43:37.0421 INFO  ? counter : a
