### ISSUE TITLE
Replicating spring session beans via Hazelcast

### ISSUE THREAD

**Issue by eladh** [hazelcast/hazelcast#3746]
I'm trying to integrate Hazelcast (lasted version - 3.3) session replication.

**Our infrastructure consists of :**
-  Apache 2.0 server for the load balancing 
- Tomcat 7 servers serving our web application 

**Our main reasons are:**
- Duplicate user session for high availability
- Atmosphere web-socket PubSub servlet need share the same data in order to make full  
  broadcasting

**integrating Hazelcast to our Environment:**
- each of the tomcat servers will serve as Hazelcast member
- basically Hazelcast WebFilter is the first one that executes and its
  wrap with :  WebFilter->HazelcastSession->setAttribute() implements
  HttpSession interface
- each time setAttribute is called Hazelcast sync the session attribute
  with the rest of the cluster members.

**now - its seems like every spring bean we injecting scoped as session bean don't get replicated .**

as a workaround :
1. Save only basic session information via @Context annotation
2. Dont use Spring session scope , only Singletons and inject the HazelcastInstance  
   I can Wrap the relevant data as Hazelcast structures

Also, when i looked on other stackoverflow i saw the following  : http://stackoverflow.com/questions/2788774/spring-session-scope-of-a-bean/2788979#2788979?

> The Spring session does not exactly match the HttpSession, and even
> the Spring documentation on the @SessionAttributes annotation says
> that it might be stored in the session or "some conversational
> storage". I got that from [The Spring docs for 2.5][1] I've basically
> quit trying to make sense of it, and just got on with my life, if I
> want something stored in the HttpSession, I just have Spring inject
> the HttpSession to me, assuming you're using Spring MVC its pretty
> easy, instructions on the same page.
> 
>   [1]:
> http://static.springsource.org/spring/docs/2.5.x/reference/mvc.html

**_Its seems strange , Does Spring session beans not exactly match the HttpSession.setAttribute ?
How spring know how to @Inject the proper bean  ?**_
- Maybe Spring save the Beans in an internal data storage and only in
  the Injection phase Spring  getting the proper element using the same
  session id attribute and bind the proper bean.
- is there any way to control this behavior ?

**_Update :**_ 
- debugging spring-web -> ServletRequestAttributes->  is using the
  Server impl HTTPSession (For example - in Dev Jetty - org.eclipse.jetty.server.session.HashedSession) 
- this way the Bean is update in the  HTTPSession but skipping the
  HazelcastSession :-(

```
/**
     * Update all accessed session attributes through {@code session.setAttribute}
     * calls, explicitly indicating to the container that they might have been modified.
     */
    @Override
    protected void updateAccessedSessionAttributes() {
        // Store session reference for access after request completion.
        this.session = this.request.getSession(false);
        // Update all affected session attributes.
        if (this.session != null) {
            try {
                for (Map.Entry<String, Object> entry : this.sessionAttributesToUpdate.entrySet()) {
                    String name = entry.getKey();
                    Object newValue = entry.getValue();
                    Object oldValue = this.session.getAttribute(name);
                    if (oldValue == newValue) {
                        this.session.setAttribute(name, newValue);
                    }
                }
            }
            catch (IllegalStateException ex) {
                // Session invalidated - shouldn't usually happen.
            }
        }
        this.sessionAttributesToUpdate.clear();
    }
```

thanks in advance ,
elad.

**Comment by dbrimley** [comment]
I'm closing this issue as I now think we cover this scenario. @eladh Is this still an issue for you? We now have a specific filter for spring web in the hazelcast-wm module....
https://github.com/hazelcast/hazelcast-wm/blob/master/src/main/java/com/hazelcast/web/spring/SpringAwareWebFilter.java

If you still have a problem even with the new filter could you re-open a new issue.
