### ISSUE TITLE
Cluster Stuck moving from 2.6 to 3.x

### ISSUE THREAD

**Issue by simone-businaro** [hazelcast/hazelcast#3748]
Hello,
Since hazelcast 3.x has come, we tried to move our application from 2.6 to 3.x.
We tried 3 times with hazelcast 3.0, 3.2.5 and 3.3.1.
Unfortunatly every time we face the same issue. During the running of our application at some unpredictable point the hazelcast cluster get stuck.

More in deep, debugging possible operations with the "stuck" cluster, I realize that I can retreive instances of shared object like Maps and IdGenerator but if I try any operation on this instances such as retreive an object from a map or an id from IdGenerator the cluster never is unable to answer and the thread that asks for the object wait forever.

As described, the moment in which the cluster get stuck is unpredictable so I'm not able to provide you a test case.

**Comment by bwzhang2011** [comment]
@simone-businaro, any update with such issue and the stuck problem resolved or not ?

**Comment by simone-businaro** [comment]
Hello,
no at the moment any update, we are still at version 2.6. We will try again to go with the latest version of hazelcast and see if the problem is solved. Meanwhile I think we can close the issue. I will keep you update. 
Thanks
