### ISSUE TITLE
Expose isMaster() method to clients

### ISSUE THREAD

**Issue by nfx** [hazelcast/hazelcast#3760]
`com.hazelcast.instance.HazelcastInstanceImpl#node`, `com.hazelcast.instance.Node#isMaster` and `com.hazelcast.cluster.ClusterService#isMaster` could be re-used for leader election functionality that is already in core of Hazelcast. could those methods be exposed to clients somewhere somehow without hackish solutions with using reflection, or blowing up own zookeeper or any other kind of leader election approach?

**Comment by enesakar** [comment]
@pveentjer 's suggestion seems a workaround. closing the issue.
