### ISSUE TITLE
Client connection buildup rewrite

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#3772]
The client connection build up logic is way too complicate. Apart from it lack of maintainability/understandability, it gets offloaded to a worker thread twice and exceptions are not being reported back correctly. Also it should be properly tested and documented.

The whole things needs to be simplified. Contact me for a simpler threading model (if threading is needed at all).

Addition:
- when a client is not authenticated to connect to a member in the cluster, it should not retry connecting to that member.
- in the exception thrown when the HazelcastClient.newHazelcastInstance is called, it should be very clear what happened. We don't wan to see a useless partition tables exception.

**Comment by sancar** [comment]
Refacoted heavily  in 3.5-SNAPSHOT

**Comment by bwzhang2011** [comment]
@sancar , thanks for review. what I wondered whether the hzInstanceNotActiveException is resovled or not.
