### ISSUE TITLE
[TEST-FIX] HazelcastXaTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3807]
in our nightly build HazelcastXaTest timeout for 3-4 builds.
so also we couldn't run all tests due to this timeout.
```
Running com.hazelcast.xa.HazelcastXaTest
Build timed out (after 150 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/332/console

**Comment by gurbuzali** [comment]
fixed in 3.5-EA
