### ISSUE TITLE
Would be nice to have statistics to IList and ISet

### ISSUE THREAD

**Issue by velo** [hazelcast/hazelcast#3823]
Would be nice to have statistics to IList and ISet, like IMap, IQueue, ICache and Multimap

At least basic stats like:
    `long getLastAccessTime();`
    `long getLastUpdateTime();`
    `long getHits();`

But the more the better!

**Comment by burakcelebi** [comment]
Related https://github.com/hazelcast/hazelcast/issues/6572

**Comment by aberkecz** [comment]
Hi Everyone,

I would be happy to take this task if possible.

**Comment by Holmistr** [comment]
@aberkecz And it's yours! Thank you very much for you effort. I will get in touch with the experts in this matter to provide you some tips and starting points. Looking forward to your contribution!

**Comment by aberkecz** [comment]
Thanks! As we discussed on Gitter, I've already started working on it and have some progress done. I'll do my best to finish it by the end of the week.

**Comment by mmedenjak** [comment]
@aberkecz answered on gitter, don't know if you'll see it so I'll answer here as well. Regarding the `getHits` method - for the list/set stats, it's not very clear. I was thinking maybe we can add it for `CollectionContainsOperation` as well but on the other hand seems it's not a straightforward answer. Maybe we can avoid adding `getHits` in the first version and wait until there's more feedback from the community. I can see there are already other methods that return the number of operations so maybe we use that approach in the future as well.

**Comment by Holmistr** [comment]
Link to PR: https://github.com/hazelcast/hazelcast/pull/16665
