### ISSUE TITLE
[TEST-FAILURE] EvictionTest.testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#3834]
```
java.lang.AssertionError: expected:<1000> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.map.EvictionTest$22.run(EvictionTest.java:1052)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:240)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:256)
	at com.hazelcast.map.EvictionTest.testExpirationDelay(EvictionTest.java:1041)
	at com.hazelcast.map.EvictionTest.testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions(EvictionTest.java:1018)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/324/testReport/junit/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/188/com.hazelcast$hazelcast/testReport/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by mesutcelik** [comment]
**master failure**

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/501/com.hazelcast$hazelcast/testReport/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/12873/com.hazelcast$hazelcast/testReport/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/509/testReport/junit/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3077/testReport/junit/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/220/com.hazelcast$hazelcast/testReport/com.hazelcast.map/EvictionTest/testBackupExpirationDelay_preventsSweepOfEntries_onBackupPartitions/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/6eca783a6ec685323854f0986a55e3225c3f49c0
