### ISSUE TITLE
API change in EntryListener breaks compatibility with the Camel Hazelcast component

### ISSUE THREAD

**Issue by lukasblu** [hazelcast/hazelcast#3859]
Hi,

while resolving issue #3198 , you changed the EntryListener API - EntryEvent.getOldValue() now returns the value which was previously returned in EntryEvent.getValue().

I actually like this change, because it is more intuitive to get the removed value through a call to EntryEvent.getOldValue() instead of calling EntryEvent.getValue().

However, this change requires to change all entry listeners which make use of the value in the EntryListener.entryRemoved() method. One such example is in the Camel Hazelcast component:

org.apache.camel.component.hazelcast.listener.CamelEntryListener.entryRemoved()

See https://git-wip-us.apache.org/repos/asf?p=camel.git;a=blob_plain;f=components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/listener/CamelEntryListener.java;hb=master

I suggest that you ask the Camel people to fix this as soon as possible and add it to yours and their release notes.

Thanks and best,
Lukas

P.s. the following issue also already discovered this problem: #3747

**Comment by ahmetmircik** [comment]
Unfortunately the documentation update doesn't seem to be doable because there will be no new patch version for 3.2. Closing this one.

**Comment by hitendrapratap** [comment]
public class CamelEntryListener extends CamelListener implements EntryListener<Object, Object> {

    public CamelEntryListener(HazelcastDefaultConsumer consumer, String cacheName) {
        super(consumer, cacheName);
    }
    public void entryUpdated(EntryEvent<Object, Object> event) {
        this.sendExchange(HazelcastConstants.UPDATED, event.getKey(), event.getValue());
    }
}

// So in EntryUpdated, we should get the old and new value right. But in exchange we are only new value and not old value? Am i missing something?
