### ISSUE TITLE
Support for load/store on ITopic

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#3881]
Having the ability to store messages put on to an ITopic would allow us to create an event log, and provide durable subscriptions / fault tolerance across our services that are leveraging the ITopic.

If Hazelcast had a way of also triggering the store() operation on multiple nodes (on a partition / sharded basis), then we could easily implement a fault tolerant persistent event log. 

Consumers would need to be able to reconnect and start processing messages from the end (i.e. all new messages) of the Topic, or at some arbitrary point (replay from message N). Think Kafka consumer groups, but without all the hassle.

Such functionality would imply some sort of unique ordering amongst the messages published, and an ability to retrieve them.

Even better would be if Hazelcast provided the distributed persistence / event log functionality on a per ITopic basis, but adding the hooks to do so would be a good start :-).

**Comment by bwzhang2011** [comment]
@StanAccy, how about your plan for topic store just like queue store and make it more robus for durable subscribers.

**Comment by bwzhang2011** [comment]
@StanAccy , how does this going on ?

**Comment by jerrinot** [comment]
We still do not have load/store for regular `ITopic`. However we have added a [load/store](https://github.com/jerrinot/hazelcast/blob/377bd3187d5f423e9de094376f2b706703583c44/hazelcast/src/test/java/com/hazelcast/ringbuffer/impl/RingbufferStoreTest.java#L65-L65) for RingBuffer - a backing structure for the [`ReliableTopic`](https://github.com/jerrinot/hazelcast/blob/4c046c79f45643a1d972b547dbf71b19b55b16b5/hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java#L162-L162)

**Comment by noctarius** [comment]
I guess we can close this issue in favor of the ReliableTopic, as the normal ITopic is meant to provide best performance with tradeoff of reliability.
