### ISSUE TITLE
JvmRoute is not updated after HttpSession failover

### ISSUE THREAD

**Issue by cmuramoto** [hazelcast/hazelcast#3890]
Hello!

On my journey to migrate Terracotta Sessions to Hazelcast's I noticed one small difference during session failover: the **jvmRoute** appended to the JSESSIONID cookie does not get replaced when using Hazelcast. 

The failover works fine, however since the **jvmRoute** does not change, Apache will keep trying to access the dead node and since it can't, it will end up routing the request to another available node, which kills session affinity! 

My test scenario:
1. JBoss Instances (2 nodes, old, 4.3, jvmRoutes web-01 and web-02)
2. App deployed with Hazelcast 3.3.1
3. Apache (1 node, mod_jk 1.2.28)

Steps to reproduce:
1. Have both Applications and Apache running
2. Log In into the application, then note the jsessionId, e.g., xyzw.web-01
3. Kill the node whose session has affinity with (web-01)
4. Continue using the application
5. Check that failover works (OK!), however the JSESSIONID cookie keeps pointing to the dead node
6. Check that Apache keeps trying to access the dead node (e.g. via jkstatus)

I wasn't able to perform load tests yet, however I believe the cluster will be degraded not only due to a member failure, but also due to loss session affinity, and probably this might lead to bugs if **WebFilter** is configured with

``` xml
<init-param>
            <param-name>sticky-session</param-name>
            <param-value>true</param-value>
</init-param>
```

I used to believe that the container was the one be responsible for updating the cookie, but at least in this version of JBoss this is not working. :( Upon further investigation I noticed that Terracotta has some logic to guard against 'server hops' (session migration) and they do so by forcing cookie updates: 

``` java
//Code from TerracottaSessionManager
private void writeCookieIfHop(HttpServletRequest req, HttpServletResponse res, SessionId id) {
    if (id.isServerHop()) {
      Cookie cookie = this.cookieWriter.writeCookie(req, res, id);
      if (this.debugSessions)
        this.logger.info("writing new cookie for hopped request: " + getCookieDetails(cookie));
    }
  }
```

And apparently, according to Hazelcast docs, this should be handled by the framework as well:

_"...As jvmRoute parameter of session ID is different than that of target Tomcat instance, Hazelcast Session Replication Module updates the session ID of the session with the new jvmRoute parameter..."_

However I could not find anything related in the hazelcast-wm module to cope with session migration. Perhaps the doc is referring to the **Valve**-based (enterprise) solution?

Anyway, I ended up solving my problem with the following piece of code:

``` java
private void fixJVMRoute(HttpServletRequest request, HttpServletResponse response) {
        //JVM_ROUTE is set as a System Property, which is picked up by JBoss and reflected in server.xml
        if (JVM_ROUTE != null) {
            Cookie cookie = request.getCookie("JSESSIONID");
            String value;

            if (cookie != null && (value = cookie.getValue()) != null && !value.endsWith(JVM_ROUTE)) {
                cookie.setPath("/");

                final int ix = value.lastIndexOf('.');

                if (ix > 0) {
                    cookie.setValue(value.substring(0, ix + 1) + JVM_ROUTE);
                } else {
                    cookie.setValue(value + "." + JVM_ROUTE);
                }

                response.addCookie(cookie);
            }
        }
    }
```

Another possible solution to this issue would be marking **set_session_cookie**=True in the Apache Load Balancer config, however I wasn't able to test it because this property is available only on mod_jk 1.2.38 onwards and I'm using 1.2.28.

I don't know if this is a enterprise-only feature, but if that's the case, it would be nice to warn open-source users about this particular detail!

**Comment by emre-aydin** [comment]
Hi @cmuramoto ,
[Tomcat container specific session replication plugin](https://github.com/hazelcast/hazelcast-tomcat-sessionmanager) has been open sourced and it does not suffer the problem you have described.

**Comment by mdogan** [comment]
This issue was moved to hazelcast/hazelcast-wm#43
