### ISSUE TITLE
Cluster members not discovering

### ISSUE THREAD

**Issue by bhushankh** [hazelcast/hazelcast#3910]
I am trying to run 2 hazelcast instances on 2 centos nodes and the hazelcast instances cannot see each other. I verified that firewall is off, nodes can ping each other and iperf is able to see multicast. I tried using the test program and it is unable to see other nodes. What should I look for ? I am using hazelcast 2.5.

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?
