### ISSUE TITLE
Feature request: support live upgrade (no-outage)

### ISSUE THREAD

**Issue by victorfuman** [hazelcast/hazelcast#3937]
currently upgrading from Hazelcast 3.1.x to 3.2.x or 3.3.x requires building a new cluster, which is essentially an outage. 3.2.x or 3.3.x is not backward compatible with 3.1.x or earlier version, so 3.2.x or 3.3.x node can't join an existing cluster consisting of 3.1.x nodes.  Please correct me if my understanding is wrong.

No outage upgrade is important for a software to run in prod (at least for some cases). How soon can you please fufil the feature request?
Thanks!

**Comment by markathomas** [comment]
+1 - VERY IMPORTANT!!!

**Comment by bwzhang2011** [comment]
@pveentjer, is it resemble the idea of zero deployment like some feature in gridgain.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?

**Comment by mdogan** [comment]
Rolling upgrade has been implemented in 3.8. See http://docs.hazelcast.org/docs/3.8-RC1/manual/html-single/index.html#rolling-member-upgrades
