### ISSUE TITLE
Failed to obtain lock with Hazelcast 3.3 on two node cluster

### ISSUE THREAD

**Issue by akonapur** [hazelcast/hazelcast#3943]
Hi,
 We are running two nodes of JBOSS 7.2 having HZ-3.3.
During application maintenance both nodes were stopped one by one. When node1 was being stopped we saw errors like:
*Error occurred while Releasing Lock on: queue/MirrorJobs Owner:mirrorJobsManager-9
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!*
We assumed this is to be valid error as the server is goin down. 
Once both the nodes were stopped, then while starting the nodes we reversed the order.
Node2 was started first, it worked fine till the node1 was down. The moment node1 was started, node2 started misbehaving.
All the threads on node2 started waiting to acquire lock *queue/MirrorJobs*. They remained in waiting state for ever making application to freeze.
We tried using tryLock but still the lock was never acquired within specified time.
Can some please suggest any approach?

**Comment by gurbuzali** [comment]
closing this one now, feel free to re-open if your are still experiencing the issue
