### ISSUE TITLE
Improve deployment of classes to nodes

### ISSUE THREAD

**Issue by blagerweij** [hazelcast/hazelcast#400]
I would like to see more mature deployment options, where one can provide a ZIP file (similar to WAR/EAR files) which contains all classes and dependent JAR files to execute tasks on remote nodes. 

Before we were using Hazelcast we were using Gridgain, which offers this (see http://www.gridgain.com/book/book.html#_gar_deployment).

Different options are possible:
1) Peer to peer classloading
2) Archive containing classes, dependent JARs and meta-information

**Comment by pveentjer** [comment]
Distributed classloading has been added to Hazelcast 3.9. So I'm going to close this ticket. Feel free to reopen.

**Comment by fkoner** [comment]
@pveentjer 

Running an application with spring boot What is the best way to ensure that all cluster members have an identical copy of the classes? Making each spring boot application a member of the cluster. Or Using Distributed Classloading. Do You have some example of this type of deployment?
