### ISSUE TITLE
IMap stats showing negative values

### ISSUE THREAD

**Issue by jeffastorey** [hazelcast/hazelcast#4022]
I'm using hazelcast 2.6.7 and after heavy usage of the cache, the number of misses starts showing up negative. Specifically, it is being reported as the negative of the number of hits (e.g. if hits = 20, misses = -20). I'm getting the map stats as follows:

    LocalMapStats mapStats = HazelcastCache.instance.getMap("myMap").getLocalMapStats();
    long hits = mapStats.getHits();
    long misses = mapStats.getMisses();

**Comment by oobles** [comment]
+1.  Would be nice to see this fixed.  It's not even clear what this actually means.  It would be useful to use this information to better configure maps, but this information is not useful.

some_map 
Size 153, 
Get operation count 22050 (hits 43947/misses -21897), 
Put operation count 22050, 
get remove operation count 0, 
Other operation count 716795

**Comment by mdogan** [comment]
@ahmetmircik: is this planned for 3.6?

**Comment by enesakar** [comment]
@muratayan can you work on this issue?

**Comment by muratayan** [comment]
I am on it.
