### ISSUE TITLE
[TEST-FAILURE] QueryIndexingTest.testResultsHaveNullFields_whenUsingIndexes

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4114]
```
java.lang.AssertionError: expected:<2500> but was:<2429>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.map.query.QueryIndexingTest.testResultsHaveNullFields_whenUsingIndexes(QueryIndexingTest.java:92)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OpenJDK8/com.hazelcast$hazelcast/59/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/34/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mdogan** [comment]
Failed on master branch: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12093/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

```
Error Message

employee.getCity();
Wanted 1 time:
-> at com.hazelcast.map.query.QueryIndexingTest.assertGettersCalledNTimes(QueryIndexingTest.java:108)
But was 2 times. Undesired invocation:
-> at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
Stacktrace

org.mockito.exceptions.verification.TooManyActualInvocations: 
employee.getCity();
Wanted 1 time:
-> at com.hazelcast.map.query.QueryIndexingTest.assertGettersCalledNTimes(QueryIndexingTest.java:108)
But was 2 times. Undesired invocation:
-> at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)

	at com.hazelcast.map.query.QueryIndexingTest.assertGettersCalledNTimes(QueryIndexingTest.java:108)
	at com.hazelcast.map.query.QueryIndexingTest.testResultsHaveNullFields_whenUsingIndexes(QueryIndexingTest.java:94)
```

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/187/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2914/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/com.hazelcast$hazelcast/191/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by Donnerbart** [comment]
```
employee.getCity();
Wanted 1 time:
-> at com.hazelcast.map.query.QueryIndexingTest.assertGettersCalledNTimes(QueryIndexingTest.java:108)
But was 2 times. Undesired invocation:
-> at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12551/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by ajermakovics** [comment]
The undesired invocation is due to a query running without indexes and iterating through all entries. Unfortunately it only seems to fail on cloudbees. It would run without indexes if migration is ongoing but in the test explicitly waits for safe state.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK7/194/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/203/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/526/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/526/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/526/testReport/junit/com.hazelcast.map.query/QueryIndexingTest/testResultsHaveNullFields_whenUsingIndexes/

**Comment by mesutcelik** [comment]
no recent failure. closing..
