### ISSUE TITLE
3.3: Call timed-out during wait-notify phase - forever

### ISSUE THREAD

**Issue by lbakman** [hazelcast/hazelcast#4133]
Hi

We have a situation in a system running Hazelcast 3.3 where we have seen the system entering a state where a BasicInvocation is timed out forever. This kind of looks like the situation reported in #4123, but I just wanted to hear if you agree.

In our situation we have 2 servers that tries to take a distributed lock. This has so far been working fine. 2 days ago we started getting this in out log files - a lot:

```
09:11:48.942 11/18/2014 com.hazelcast.spi.impl.BasicInvocation [x.x.x.x]:5701
[dev] [3.3] Call timed-out during wait-notify phase, retrying call:
    BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@166eabb,
    partitionId=139, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000,
    target=Address[y.y.y.y]:5701}
```

We receive between 5 and 10 of these log statements every 15 milliseconds for about 15 minutes. At this point there seem to occur a split between the servers. After the servers join together again, the time-out issue for LockOperation persists - "forever".

At the same time we can see that MasterConfirmation's are sent successfully so the connection between the 2 servers seems to be OK.

The end result of the above problem is that both servers believe they have the lock and perform operations that only one of them should. 

Does this look like the issue reported in #4123 ?

Regards 
Lau

**Comment by RobbieHer** [comment]
@mdogan In my case, it looks like both the nodes think that somebody other than itself has the lock (i.e tryLock does not return ). However, neither of the nodes have the lock. Is there someway to get out of this situation, by clearing out the hazelcast lock maps, without bringing both nodes down simultaneously. We are at version 3.2.6, and we see this on both the nodes

[] 08/11/2015 13:33:55.685 [hz.defaulttenant-defaultorg0.response - platform] DEBUG c.h.spi.impl.BasicInvocation - [10.38.4.184]:5702 [defaulttenant-defaultorg0] [3.2.6] Call timed-out during wait-notify phase, retrying call: BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@5bd21649, partitionId=88, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.38.14.132]:5701}

[] 08/11/2015 13:34:04.808 [hz.defaulttenant-defaultorg0.response - platform] DEBUG c.h.spi.impl.BasicInvocation - [10.38.14.132]:5702 [defaulttenant-defaultorg0] [3.2.6] Call timed-out during wait-notify phase, retrying call: BasicInvocation{ serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation@ce4063e, partitionId=88, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=3, callTimeout=60000, target=Address[10.38.14.132]:5701}

**Comment by mdogan** [comment]
Lock (and wait/notify) mechanisms has many fixes, improvements and changes in recent versions. Please try latest version and feel free to open a new issue if problem still exists.
