### ISSUE TITLE
Questions on Repartitioning

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4146]
**Questions:**
Q.1 In a multi-node cluster, if a node goes out of the cluster while an EntryProcessor was active in a node processing on an entry object, (i) does the repartitioning wait for EntryProcessor to finish its processing before repartitioning could trigger or (ii) is the EntryProcessor forced to stop its execution and re-partitioning takes precedence? 
	Q.1.1 If the answer is (i), does that not impact cluster HA because if EP got stuck in a long running task, the cluster will continue to wait - no? Or is there some kind of timeout?
	Q.1.2 If the answer is (ii), does the EP execution start again after re-partitioning?

**Action to be taken:** 
Capture the answers in Q&A or in Entry Processor docs.

**Comment by hitendrapratap** [comment]
"so they will wait for entry processor to finish." : If that particular node is down then how it will finish the entry processor on the same node. Might be I am not understanding it correct?
