### ISSUE TITLE
Adding further code samples for JCache configuration

### ISSUE THREAD

**Issue by degerhz** [hazelcast/hazelcast#4198]
1. Accessing a cache created using hazelcast.xml configuration. This should use all parts of the cache xsd and should programmatically do Caching.getCache(“sample”) and then exercise all of the features.
2. Same but from a client using hazelcast-client.xml
3. Same as 1 and 2 using Hi-Density Memory Store

**Comment by Serdaro** [comment]
@degerhz, Could you please check the code-samples repo. I think they did it.

**Comment by degerhz** [comment]
Guys, @gurbuzali @serkan-ozal, so you think code samples are in place related to this issue. If so I will close this issue. Thanks @Serdaro :)

**Comment by gurbuzali** [comment]
I believe this PR https://github.com/hazelcast/hazelcast-code-samples/pull/28 covers some of them too.

**Comment by serkan-ozal** [comment]
and also this PR https://github.com/hazelcast/hazelcast-code-samples/pull/27 covers Hi-Density part. So I think we can close this issue.

**Comment by degerhz** [comment]
Thanks @Serdaro @gurbuzali @serkan-ozal
