### ISSUE TITLE
Add partition state version to query results and check when receiving

### ISSUE THREAD

**Issue by ajermakovics** [hazelcast/hazelcast#4206]
While migration is in progress nodes will have different partition state versions. If query is running at that time it can get results from nodes at different stages of migration.
By adding partition state version to query results we can check if migration was happening and re-run the query.
- [ ] Unignore tests in QueryIndexMigrationTest

**Comment by markathomas** [comment]
How does one do this?  The referenced issue with a commit simply ignores some unit tests so I fail to see how this particular issue is resolved.  Is there a commit associated with this issue?

**Comment by ajermakovics** [comment]
That was not intentional. GitHub closed this issue automatically due to the PR message text. Re-opening

**Comment by jerrinot** [comment]
The test has been un-ignored months ago in https://github.com/hazelcast/hazelcast/pull/8501
somehow we forgot to link the fix to this issue. I'm closing it now.
