### ISSUE TITLE
KeyValueSource.hasNext/element/key docs should emphasize differences from Iterator.hasNext/next

### ISSUE THREAD

**Issue by Tembrel** [hazelcast/hazelcast#4218]
`Iterator.hasNext()` does not change state, but `Iterator.next()` does. In contrast, `KeyValueSource.hasNext()` __does__ change state, while `KeyValueSource.element()` and `KeyValueSource.key()` do __not__. This should be documented in the [method comment for `KeyValueSource.hasNext`](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/mapreduce/KeyValueSource.java#L57-L62) (and likewise for `element()` and `key()`).

**Comment by Serdaro** [comment]
@eminn, do you need any help on this, documentation-wise?

**Comment by eminn** [comment]
Thanks for the report, fixed via c1197b6c97860c7d5a0b738a4e61442b387d17b7
