### ISSUE TITLE
Don't log warnings when a node leaves a cluster gracefully

### ISSUE THREAD

**Issue by ejain** [hazelcast/hazelcast#4223]
Log level should be INFO? See http://stackoverflow.com/questions/27240533/how-to-leave-a-hazelcast-cluster-gracefully/

**Comment by Espenhh** [comment]
Is there any plans to do something about this? We experience around 100-200 WARN's in our logs when we release new versions of our apps to productions, which is a bit annoying. We do rolling deploys without downtime, so nodes leaving and joining the cluster is quite expected, and we would love to be able to do this without all the logging noise.

**Comment by mstieghahn** [comment]
Hi there,
we experience the same problem and would appreciate a solution for that issue.

Best,
Michael
