### ISSUE TITLE
thread stuck when about lock

### ISSUE THREAD

**Issue by imhazige** [hazelcast/hazelcast#4229]
Hi, We have encounter a problem same as a post at here:
https://groups.google.com/forum/#!topic/hazelcast/TtkPvcgYdf8

here is the threaddump in our own case:
![screen shot 2014-12-04 at 18 15 43](https://cloud.githubusercontent.com/assets/4122902/5296732/41266256-7be2-11e4-939b-feae4ab54619.gif)

I found it easy to happen when:
network is not stable:
for example we connect to a vpn, the server is running, when disconnect from the vpn, the network will have a reset, in this case, it will happen.

when a node join/leave the cluster.

**Comment by mdogan** [comment]
Invocation/operation infrastructure changed/improved significantly. Please open a new ticket if you still see the issue.
