### ISSUE TITLE
HazelCast Perfomance Test with Spring Batch throws TargetDisconnectedException

### ISSUE THREAD

**Issue by vendetta9** [hazelcast/hazelcast#4230]
I have a HazelCast Server setup with 2 nodes and the server has been healthy and has never shown any issues. My clients are from multiple instances of spring batch and each spring batch has 120 threads and there are five instances of spring batch which means there might be around 120*5=600 threads trying to access IMap to set/get values. 

When I started around 3 instances of the batch, the time taken to set values in IMap goes beyond 50 seconds and slowly the following exception is thrown:

com.hazelcast.spi.exception.TargetDisconnectedException
        at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:128)
        at com.hazelcast.client.spi.impl.ClientCallFuture.get(ClientCallFuture.java:111)
        at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:110)
        at com.hazelcast.client.proxy.ClientMapProxy.set(ClientMapProxy.java:380)
        at com.ebay.app.raptor.dfmailbat.components.cache.client.processor.CacheClient.setDealsResponseInCache(CacheClient.java:101)
        at com.ebay.app.raptor.dfmailbat.components.deal.finder.service.manager.DealFinderManager.getDeals(DealFinderManager.java:59)

Each Spring has one static instance of IMap and uses the same instance to set/get values. Something like this:

static {
        ClientConfig clientConfig = new ClientConfig();

        List<String> addresses = getClusterAddresses();

        if (addresses != null) {
            clientConfig.getNetworkConfig().setAddresses(addresses);
            s_client = HazelcastClient.newHazelcastClient(clientConfig);
        }
        else {
            s_logger.log(LogLevel.ERROR, "No host in Database for hazelcast client set up");
        }

        if (s_client != null) {
            s_map = s_client.getMap("ItemDealsMap");
        }

    }

The s_map is used by all the threads to set/get entries from IMap. I set a eviction time of 12 hours when I set the entries into the IMap. I am using HazelCast 3.3 on both the server and the client. This issue is consistently reproducible when the number of concurrent threads are increased. When I shutdown the spring batch and start again, it works well. Could you please help me with this.

**Comment by mesutcelik** [comment]
any update on the issue?

**Comment by bwzhang2011** [comment]
@vendetta9, how does this going on ? I will do some integration with spring batch and hazelcast, so your issue is important that  how induce the targetDisconnectedException

**Comment by enesakar** [comment]
I am closing it as we can not reproduce the issue. if you can provide your failing test code, please reopen the issue.
