### ISSUE TITLE
Add IQueue.addAll(E... items) and ITopic.publishAll batch methods

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#4233]
Hi, hz team. as https://github.com/hazelcast/hazelcast/issues/3661 pointed out, the addAll bulk operation in IQueue could improve performance when a batch of message processed. from the resource code, the IQueue addAll support collection type data while the original object array is missing,
so addAll for object array should be added as NodeEngine toData parameter is Object. meanwhile, compared with IQueue, could ITopic add publishAll for batch publishing to improve performance

**Comment by bwzhang2011** [comment]
@mdogan, any update with such issue? provide some enhancement officially.

**Comment by pveentjer** [comment]
There are some IQueue performance improvements planned for 3.6. Batching is a very simple way to improve performance.

The ITopic has already a publishAll in my reliable topic branch. The regular eventing system, because it doesn't make use of backups, is of very high speed. Adding a publishAll is not going to make any difference. But the new reliable topic is slower due to the backup. That is why I added it to the topic. It hooks directly into the batching functionality of the underlying ringbuffer.

https://github.com/hazelcast/hazelcast/pull/5217

**Comment by bwzhang2011** [comment]
@pveentjer, thanks for view and feed back. from your words, the topic operated like the JMS while it enables the persistence for reliable way. maybe a better idea is to incorporate those together once the user enable reliable way it will invoke reliable topic or else it use the pure one.batching is the main way to improve performance as we need to transfer a group of messages between our projects. what's the more, as reliable topic has the backup ability, I dare think that it could introduce the transaction topic as you know we've got a lot of use cases which should be completed around the transaction.

**Comment by pveentjer** [comment]
For the time being, due to time constraints, I have dropped the publishAll from the reliable topic. We need to release EA this week and I don't have time to fully test this feature in the next few days. 

I fully understand the need for it; the performance improvements can be huge.

A transactional topic is not on the radar btw. We have a HEP process where users can suggest an improvement.

**Comment by mmedenjak** [comment]
For anyone trying to implement these methods: looks like `IQueue.addAll` already exists and there's already [a PR for `TransactionalQueue.addAll`](https://github.com/hazelcast/hazelcast/pull/16129). So the only remaining method that needs to be implemented is  `ITopic.publishAll`. 
I would prefer if we made it asynchronous as well - so implement `ITopic.publishAllAsync`.

For reference, you can take a look at the implementation of `Ringbuffer#addAllAsync` - the `ITopic` version wouldn't be exactly the same but would be similar in implementation.

**Comment by andrewoelfing** [comment]
Hello,
I would like to take this issue (the part with ITopic.publishAll) and give it a try.

**Comment by Holmistr** [comment]
Hi @andrewoelfing , glad to see you here! And it's yours! :tada: The pointers are already commented above, so I think you're good to go. Feel free to ask any questions if needed!

**Comment by Holmistr** [comment]
Hi @andrewoelfing just checking in - is there anything we can help you out with? I see that you're actually makins progress in your fork. I just want to make sure that you're not stuck on something and just afraid to ask :)

**Comment by andrewoelfing** [comment]
Hello @Holmistr, I think im ready for a PR. I've implemented only the publishAll-method because there is much more missing for the async version (a PublishOperation or something else). In my opinion this could be a next step. :)

**Comment by Holmistr** [comment]
@andrewoelfing Absolutely, go for it :) We will continue with the review there!

**Comment by Holmistr** [comment]
Hi @andrewoelfing , just checking in again if there's anything we can help out with :) Looking forward to your PR!

**Comment by Holmistr** [comment]
PR: https://github.com/hazelcast/hazelcast/pull/16707

**Comment by Holmistr** [comment]
Hi @andrewoelfing , I'm just checking in if there's anything we can help you out with. I saw your PR and I'm sorry that it got closed. However, I would like you to know that we appreciate your effort very much and we're happy to continue on the other approach :) Just bare with us, this happens! :) Nice work so far even though it didn't get merged (yet)!

**Comment by andrewoelfing** [comment]
Hello @Holmistr. Sorry, but I've got stuck on writing unit tests (not the unit test itself but testing the Hazelcast functionality). 
Something wrong with the client protocol (it's actually a mess in my workspace ;) )
It seems to be not so easy to implement some features in such a big (and for me unfamiliar) community project.  
I will write a gitter questions in the next hours.

**Comment by Holmistr** [comment]
Hi @andrewoelfing , yeah, it's not that easy, but you're doing great! :) So no need to apologize! Looking forward to your Gitter questions.

**Comment by andrewoelfing** [comment]
Hello @Holmistr, I've created a new pull request #16946 in this repo and one pull request  in the client protocol repo (https://github.com/hazelcast/hazelcast-client-protocol/pull/318)
