### ISSUE TITLE
Replicated Map test failures

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#4252]
See:
https://github.com/hazelcast/hazelcast/issues/3127
https://github.com/hazelcast/hazelcast/issues/3162
https://github.com/hazelcast/hazelcast/issues/4140
https://github.com/hazelcast/hazelcast/issues/4181
https://github.com/hazelcast/hazelcast/issues/4138

**Comment by mesutcelik** [comment]
I don't see those ReplicatedMap Tests failing anymore. any idea?

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/197/testReport/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/198/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/200/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testEntrySetObjectDelay0/

**Comment by metanet** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/202/testReport/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/207/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testSizeObjectDelay0/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/208/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testSizeBinaryDelay0/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/210/testReport/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/217/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/219/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/222/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testContainsValueBinaryDelay0/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/226/

**Comment by bilalyasar** [comment]
we have 24 test failures:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/229/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/227/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/544/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/231/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/232/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/240/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/248/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapTest/testEntrySetBinaryDelayDefault/

**Comment by hasancelik** [comment]
This time new client side tests are failing
 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/624/

**Comment by eminn** [comment]
Fixed by #6176
