### ISSUE TITLE
Real "hits" statistics for map

### ISSUE THREAD

**Issue by rainerjung** [hazelcast/hazelcast#4253]
Currently the counter "localHits" for a map is retrieved by counting the hits per Record in the RecordStore and then sum them up for all Records in the RecordStore of the map.

"Hit" counters are mostly used to compare against "Get" counters to retrieve the hit ratio. Now the "Get" counters for a map are global get counters, not sums over the get counter of all existing record. So comparing hits and gets leads to nonsense results.

E.g. the get counter can only increase, whereas the hit counter during normal operations can also decrease once the contents of the record store change.

Please implement a real hit counter per map. Thanks!

**Comment by ahmetmircik** [comment]
Merged into https://github.com/hazelcast/hazelcast/issues/4321
