### ISSUE TITLE
Define named instances in the XML configuration

### ISSUE THREAD

**Issue by stodge** [hazelcast/hazelcast#426]
As mentioned here:

https://groups.google.com/forum/?fromgroups=#!topic/hazelcast/GaFEZI3JH4k

a very useful feature would be to define the named instance in XML

For example:

```
<properties><property name="instance.name">testing</property></properties>
```

and:

```
Hazelcast.getHazelcastInstanceByName("testing");
```

This way I could define several named networks in the XML file and I could pass the network/instance name to the application on startup and it could automatically retrieve the named instance to use.

**Comment by Fabryprog** [comment]
to resolve it issue i am writing this feature:

The hazelcast config file is global for ALL instances. I can put an attribute to indicate an PREFIX instance name. 

So, if you have 2 instances will have same prefix instance name!

Can i do it? It is ok?

**Comment by Fabryprog** [comment]
This issue is not a problem! 

I wish resolve it using "instance name" aka prefix name. 

Can you assign me?

**Comment by mustafaiman** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/6513
