### ISSUE TITLE
ClientMembershipEvent does not need to have Member field

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#4282]
In case of member attributes are changed, attribute changed event sent to the clients. All the member attributes serialized and sent to the client for every event since ClientMembershipEvent has Member field, which contains all the attributes. We change the implementation to not to send all the attributes for every event.

**Comment by sancar** [comment]
fixed via https://github.com/sancar/hazelcast/commit/f317644ab2fa2601d9f5d88a78a613b876f7adac in new client.
