### ISSUE TITLE
EC2 Auto Discovery - multiple aws-tag uses "OR" instead of "AND"

### ISSUE THREAD

**Issue by c0rnflex** [hazelcast/hazelcast#4308]
Hi,
I'm trying to have two aws-tags (env and role) so the auto discovery would figure out uniqueness between multiple networks on the same VPC.

Currently, as far as I've figured out, the aws-tags discovery uses "OR" and not "AND", which leads to the loss of uniqueness when using two or more tags, and enforces us to use a unique tag called "env_role".

Please support this.

Thanks

**Comment by mesutcelik** [comment]
Can you please send me your hazelcast.xml configuration?

**Comment by c0rnflex** [comment]
@mesutcelik I'll quote the aws part if you don't mind:
                <aws enabled="true">
                <access-key>***</access-key>
                <secret-key>***</secret-key>
                
                <region>us-east-1</region>
                
                
                
                
                <tag-key>env</tag-key>
                <tag-value>prod</tag-value>
				<tag-key>role</tag-key>
                <tag-value>app</tag-value>
            </aws>

I'd imagine hazelcast will look for instances that contain both tags, but in reality it searches for instances with either env=prod or role=app tags.

**Comment by bilalyasar** [comment]
@c0rnflex currently hazelcast doesn't support using multiple tags.

**Comment by c0rnflex** [comment]
@bilalyasar it does actually. when I use two tags, it looks for instances that are tagged with EITHER ONE of them. 
I think the logic should be that it looks for instances that are tagged with BOTH of them.

**Comment by bilalyasar** [comment]
@c0rnflex, with 3.6 you can use `hazelcast-jclouds`, it supports multi-tag feature.

**Comment by kobalski** [comment]
@c0rnflex Closing this issue, you can use `hazelcast-jclouds` for multi-tag feature. `3.6-EA2` is out, you can try jclouds integration.
Please see docs on how to use jclouds from docs : http://docs.hazelcast.org/docs/3.6-EA2/manual/html-single/index.html#discovering-members-with-jclouds
