### ISSUE TITLE
[TEST-FAILURE] BasicCacheTest.testCompletionTest

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4319]
```
junit.framework.AssertionFailedError: expected:<2> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at com.hazelcast.cache.BasicCacheTest.testCompletionTest(BasicCacheTest.java:203)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/283/testReport/junit/com.hazelcast.cache/BasicCacheTest/testCompletionTest/

**Comment by bilalyasar** [comment]
again failed:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/com.hazelcast$hazelcast/112/testReport/junit/com.hazelcast.cache/BasicCacheTest/testCompletionTest/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/475/com.hazelcast$hazelcast/testReport/com.hazelcast.cache/BasicCacheTest/testCompletionTest/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/33/testReport/junit/com.hazelcast.cache/BasicCacheTest/testCompletionTest/

**Comment by serkan-ozal** [comment]
test fixed via https://github.com/hazelcast/hazelcast/commit/a72460c49828b8086e685d358c5b2f8695bbcec6
