### ISSUE TITLE
[map] IMap jmx statistics evicted together with the map entry

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#4321]
Hazelcast 3.3.3 I have the following map config:

```xml
<hz:map name="xdm-xml" async-backup-count="1" backup-count="0" in-memory-format="OBJECT"
     eviction-policy="LRU" time-to-live-seconds="0" max-size-policy="USED_HEAP_PERCENTAGE" 
     max-size="25" eviction-percentage="10" max-idle-seconds="3600">
/hz:map>
```
When system starts and caches populated and get hits the stats present relevant values for localHits and localGetOperationCount attributes. But after 1 hour of idle some entries evicted and localHits/localGetOperationCount attributes became less and less.. till 0. Looks like you store get/hits statistics together with the entry itself and it gets evicted together with entry.

One more issue with stats: the map contains > 12M of values. Getting statistics for this map takes several minutes - looks like they're aggregated from the map entries too!

**Comment by stefano-salmaso** [comment]
Hi all,
I fell into the same issue. Are there any updates on this?
If the number of "hits" is not related to the number of "gets" ... "hits" loses its value.

**Comment by samshay** [comment]
Hi,
I have the same problem :(

**Comment by stefano-salmaso** [comment]
Hi,
could we have an update on this?
For me having wrong statistics is worse than not having them!!!

Thanks
Stefano

**Comment by jerrinot** [comment]
Hi,

right now the aggregated stats indeed shows "hits/miss of entries currently present in the map". I agree this is unexpected it should be changed into "hits/miss since a map (record store) was created". 

I am adding this from backlog into 3.10.
