### ISSUE TITLE
Cache Custom Eviction Policy Support

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4324]
* User should be able to specify his/her custom eviction strategy factory implementation to provide his/her custom eviction strategy implementation (such as Sampling based, etc ...) extends from `com.hazelcast.cache.impl.eviction.EvictionStrategy` by programmatically and by XML configuration.

* User should be able to specify his/her custom eviction policy evaluator factory implementation to provide his/her custom eviction policy evaluator implementation (such as LRU, LFU, etc ...) extends from `com.hazelcast.cache.impl.eviction.EvictionPolicyEvaluator` by programmatically and by XML configuration.

**Comment by serkan-ozal** [comment]
@Serdaro, currently, I couldn't started to work on this improvement. So since there is no implementation and PRD, we can ignore documentation at current state :). Thanks for your interest. Maybe forward to another milestone.

**Comment by youngm** [comment]
I recently ran into a use case where this would be useful.  I need LRU eviction to consider creation time as an "Access" so that items I newly place in the cache don't get immediately evicted.  I look forward to this issue getting implemented.

**Comment by serkan-ozal** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/8013
