### ISSUE TITLE
JCache sync listener completion latch problems

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#4335]
This is a follow-up issue for https://github.com/hazelcast/hazelcast/pull/4333. See PR comments for more info.

Sync listener completion latch has some problems:

- It's not defined what will happen a completion event doesn't arrive; throw error or silently ignore
- There's a hardcoded 5min upper bound limit for completion latch await
- There's no way of knowing status of invocation during latch wait phase. What if operation is already timed-out? What if invocation has failed? When operation/invocation fails, latch.await() should be notified and caller should get failure result immediately.

**Comment by serkan-ozal** [comment]
closed via #5332
