### ISSUE TITLE
When near cache is used, cached entries from remote node are evicted by idleness, despite being read

### ISSUE THREAD

**Issue by jacum** [hazelcast/hazelcast#4358]
Another issue with near cache.

Code and config 
https://gist.github.com/jacum/26fb34048a297445bb29

Results:
nearCacheSize before expiration 475; map 1000 waiting ...
Elapsed 0; near cache 475; map 1000 waiting ...
Elapsed 10; near cache 475; map 1000 waiting ...
Elapsed 20; near cache 475; map 1000 waiting ...
Elapsed 30; near cache 475; map 1000 waiting ...
Elapsed 40; near cache 475; map 1000 waiting ...
Elapsed 50; near cache 433; map 720 waiting ...
Elapsed 60; near cache 475; map 525 waiting ...
Elapsed 70; near cache 475; map 525 waiting ...
Elapsed 80; near cache 475; map 525 waiting ...
Elapsed 90; near cache 475; map 525 waiting ...
Elapsed 100; near cache 475; map 525 waiting ...
Elapsed 110; near cache 475; map 525 waiting ...
Elapsed 120; near cache 475; map 525 waiting ...
Elapsed 130; near cache 475; map 525 waiting ...

Expected results:
max-idle-seconds has the very same semantic, no matter whether near cache is used or not
when entries being read regularly, they do not expire.

Actual results:
entries that are local to the node do not expire, entries on the other node (taken from near cache) do expire.

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/357c134c304e71ffaba881af853589adc52cc5a0

**Comment by lukasblu** [comment]
Hi @jacum 

short input from my side: the inconsistency you describe above when using a near cache between local and remote entries is really not nice. However, there is a way around it which I personally think should always be used: enable caching of local entries!

To do so call nearCacheConfig.setCacheLocalEntries(true);

Doing so makes sure you have the same behavior on local as well as on remote entries.

Cheers,
Lukas

**Comment by jacum** [comment]
setCacheLocalEntries - unfortunately, this causes stale reads and is not acceptable in our case

**Comment by lukasblu** [comment]
Hi @jacum ,

did you follow the discussion here #4671 and/or the pull request here #4710 ? If this is fixed, then no stale reads should be possible andymore on the local near cache.

Best,
Lukas
