### ISSUE TITLE
ICache,  max-size-policy is broken, under Cluster Member crash 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4359]
during a stabilizer run where we experienced an unexpected member node crash,
EvictionICacheTest encountered this exception.

```
Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.61.158.137
   time=Sun Dec 21 21:19:50 UTC 2014
   workerAddress=client:10.61.158.137
   workerId=worker-10.61.158.137-6-client
   test=TestCase{
          id=icacheMaxMediume
        , class=com.hazelcast.stabilizer.tests.icache.EvictionICacheTest
        , basename=maxCachMediume1
    }
   cause=junit.framework.AssertionFailedError: icacheMaxMediume: cache maxCachMediume1 size=8497 configuredMaxSize=1000 estimatedMaxSize=3523
	at junit.framework.Assert.fail(Assert.java:57)
	at com.hazelcast.stabilizer.tests.icache.EvictionICacheTest$WorkerThread.run(EvictionICacheTest.java:159)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.stabilizer.tests.utils.ThreadSpawner$DefaultThread.run(ThreadSpawner.java:88)

]
```

do we expect max-size-policy to hold under member node crash,  ?

**Comment by Danny-Hazelcast** [comment]
@serkan-ozal,  I see you have closed this ticket however,  have we conducted a simulator test under member node termination conditions to verify this is the case ?.  If not we should leave this issue open.

**Comment by noctarius** [comment]
I think this was an auto-close from github because of the issue reference :)

**Comment by serkan-ozal** [comment]
@Danny-Hazelcast right, in this case I am waiting a verify with stabilizer test for this issue from you

**Comment by gurbuzali** [comment]
Hi @Danny-Hazelcast can you verify if this issue is still valid ?

**Comment by gurbuzali** [comment]
I'm closing the issue, can you please re-open if it is still valid

**Comment by Danny-Hazelcast** [comment]
I would rather keep the issue which have a test to reproduce them open,  other wise we could well forget about it.   I was planning running this issue again to day

**Comment by gurbuzali** [comment]
ok waiting your results

**Comment by Danny-Hazelcast** [comment]
@gurbuzali @serkan-ozal 

I did some runs,  on a dynamically sized (only members)  where members joined every 1 min,  to a max cluster size of 4,  head steady,    then ramped back down at an interval of 1 min.  EvictionICacheTest
I also run under a condition of "kill -9" of a member node

all though the size of the cache is bigger than the configuredMaxSize,  It is always less than the estimatedMaxSize
```
cacheMaxSz: cache maxCacheSmall size=1626 configuredMaxSize=271 observedMaxSize=1626 estimatedMaxSize=1626
```

This issue looks fixed to me,
