### ISSUE TITLE
HazelcastInstanceNotActiveException after recovering from split brain

### ISSUE THREAD

**Issue by oshany** [hazelcast/hazelcast#4365]
Hi,

After recovering from a split-brain scenario some clients get disconnected and can't connect again,  getting HazelcastInstanceNotActiveException

Here are the details:
-Version: 3.3.3
Nodes: 3 (Nodes are running on tomcat instances, Java 1.7.51 (Oracle), Running on Linux)
Clients: 6. The clients are running on the same tomcat instances, and connecting to the local node (localhost:5701).
-cluster discovery is done using the AWS client
-Mege policy is om.hazelcast.map.merge.PassThroughMergePolicy

To simulate the split-brain scenario we isolate the communication between 1 node and the other 2 via IP tables. Running thie following on 1 node to block the other 2:

iptables -A INPUT -s 172.30.111.86,172.30.101.183 -j DROP && iptables -A OUTPUT -s 172.30.111.86,172.30.101.183 -j DROP

To restore we dimply drop the iptable rules:
iptables -D INPUT -s 172.30.111.86,172.30.101.183 -j DROP && iptables -D OUTPUT -s 172.30.111.86,172.30.101.183 -j DROP

After the restoration, on the instance that was isolated, the clients are disconnected and getting the exception. Here is the log: http://pastebin.com/raw.php?i=ibf1Z5vi

Thanks

**Comment by sancar** [comment]
It looks like you found the solution already. Sorry for not being able to return back to you. I checked the latest docs, it seems we have added documentation for connection-attempt-period and connectio-attempt-limit . See http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#client-network-configuration
