### ISSUE TITLE
hazelcast 3.4 - 3.5 Binary Compatibility,  issue

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#4371]
MapLoader `Set<K> loadAllKeys();`   changed to  `Iterable<K> loadAllKeys();`   in  3.5  

its not binary compatible.

do we guarantee binary compatibility in minor releases?

**Comment by pveentjer** [comment]
HZ 3.5 should be a drop in replacement for 3.4; without needing to recompile code.

**Comment by pveentjer** [comment]
Hi @ajermakovics can you have a look at this one? Problably the way to fix it would be to intercept the exception and do some reflection, to make sure that it still works.

**Comment by Danny-Hazelcast** [comment]
with that Pr merged, closing this issue
