### ISSUE TITLE
hazelcast console in windows7 via telnet

### ISSUE THREAD

**Issue by talipkorkmaz** [hazelcast/hazelcast#4377]
I want to access hazelcast console without management tool of hazelcast.
And want to use whole commands of hazelcat via telnet.
Is this possible?

> telnet localhost 5701 
Accessing is ok but after entering a character it forcely exit.
Any idea?

**Comment by pveentjer** [comment]
The Hazelcast Console App is just a toy. There is no remoting support and none is planned for it.
