### ISSUE TITLE
Add Google Compute Engine support for clustering

### ISSUE THREAD

**Issue by saturnism** [hazelcast/hazelcast#4387]
Currently there is aws support in hazelcast using S3.  This should be easily adaptable to GCE's Cloud Storage.

**Comment by pires** [comment]
Would be great if someone from Hazelcast would take a peak at what the community is doing to help. But you can see for yourself #2313

**Comment by kobalski** [comment]
Closing this issue, because with 3.6 google-compute integration will be provided with `hazelcast-jclouds` and Discovery SPI.
You can try it with `3.6-EA2`, here is documentation http://docs.hazelcast.org/docs/3.6-EA2/manual/html-single/index.html#discovering-members-with-jclouds.
