### ISSUE TITLE
UserContext not settable for an instance before EntryProcessors/BackupEntryProcessor start arriving

### ISSUE THREAD

**Issue by ChristerF** [hazelcast/hazelcast#4394]
In an EntryProcessor you can make the EP "instance aware" and the Hazelcast instance will be injected into the EP before executing. That is a really good feature.

A typical use case would be to get hold of some "singletonish" subsystem that the EP needs access to via the "getUserContext" method.

However, there is no practical way of putting things in the UserContext  *before* EPs and BackupEPs start arriving when a node is joining a cluster.

In order to put something in the UserContext you need access to the HazelcastInstance. But it turns out there is no way to get hold of the HazelcastInstance before EP:s start executing on the node (assuming a high traffic scenario).

The reason is that the Hazelcast instance is not returned (newHazelcastInstance) until the node has started to join the cluster and in a high traffic environment the UserContext will thus not have had a chance to be initialized. 

Potential fixes could include having LifeCycleEvent include a reference to the instance (that would enable populating the UserContext during the STARTING phase). Another potential fix would be to return quicker and not wait for a cluster join before returning the instance.

**Comment by mdogan** [comment]
What about setting/adding `UserContext` using `Config` API?

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/Config.java#L823

```java
Config config = new XmlConfigBuilder().build();
config.getUserContext().put("key", "value");
HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);
....
```

**Comment by ChristerF** [comment]
I didn't realize that existed - will give it a shot and let you know.

**Comment by ChristerF** [comment]
@mdogan that worked - thanks for the pointer!
