### ISSUE TITLE
Setting to populate near cache upon put/set

### ISSUE THREAD

**Issue by kuseman** [hazelcast/hazelcast#4399]
Hi,

We use hazelcast as a cache in a load balanced environment, we are really dependent upon near cache, thus we have almost only read requests.
The flow is simply: check if a map contains a key, if not load data from Elasticsearch then put to map.

When next request comes in to the same node that made the put, the near cache is empty and thus a new get will occur which is kind of waste because the item was prior in memory.

Would it be "logical" to add a feature that populates the near cache upon put/set?
Or is this already possible to do today?

Thanks for a really awesome library btw :)

**Comment by de-git** [comment]
That would be really useful to avoid network latency when accessing frequently updated values.
A work-around I found so far is to implement my own cache, kept reasonably up-to-date using an entry listener.

**Comment by mdogan** [comment]
This is already implemented. See `NearCacheConfig.LocalUpdatePolicy`.
