### ISSUE TITLE
ExecutorService queue size limit and monitoring (enhancement request)

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast#44]
It would be nice to be able to configure a maximum queue size for an ExecutorService such that if there are more tasks submitted than available execution threads and queue slots, then newly submitted tasks will be immediately rejected.  

A possible configuration variation would be to discard the oldest task instead of the newest task.  (this variation would be comparable to Java's 'DiscardOldestPolicy' RejectedExecutionHandler http://download.oracle.com/javase/6/docs/api/index.html?java/util/concurrent/ThreadPoolExecutor.DiscardOldestPolicy.html )

I would also be nice for the current queue size to be exposed on the ExecutorService API, so that it can be monitored.  (and adding to the JMX attributes and monitor tool would be handy as well)

Note, this is a follow up to the forum thread:
https://groups.google.com/d/topic/hazelcast/ybl9paUGUDQ/discussion

<p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=543</p>

**Comment by archit1012** [comment]
Other possible configuration is to block the thread which tries to put in the queue instead of discarding it.
That is exactly what I want, Currently I am using my own blocking queue to get this working.
