### ISSUE TITLE
Optimization: IsStillRunning simplification

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#4410]
Instead of each operation asking if something is still running; let the other system every x seconds return a list of invocations that have been running for more than y seconds. 

The current approach causes additional pressure on a system under pressure since:
- no additional operations need to be executed while a system already is executing operations slowly.
- data can be packet a lot more efficient since a single result could contains just a bunch of longs (the callid's from an invoking machine). So less io/serialization pressure.
- simplification of the invocation logic; currently it has too many responsibilities and the flow is very hard to understand.

So if member1 has 2 operations executing on member 3, and member 2 has 5 operations executing on member 3. And these are all operations that have been running longer than the given limit, then member 3 sends 2 callid's back to member1 and 5 callid's back to member 2. Probably we need to have a dedicated packet id for this.

member 3 can do a periodic check over all operation-threads, and see which operations have been running for a certain amount of time. And to each member that has long running operations, it sends the list of 'their' call id's.

On the invoking side, the system can then timeout operations that were not mentioned in a 'isstillrunning' packet for a too long time.

**Comment by pveentjer** [comment]
This will also help us to get rid of the difference between the future.andThen and the future.get.

**Comment by pveentjer** [comment]
One of the other problems with the current design is that we are only checking what is currently executing, not what is in the pipeline:
- in the connection write-queue (operation and response)
- operation queue.

So it could be that is still running returns false, because the operation has not yet been picked up yet.

**Comment by jerrinot** [comment]
that's the reason I'm sceptical when it comes to usefulness of the while IsStillRunning vehicle. it covers only a very small portion of possibly delays and IMHO it's not worth the extra complexity.

**Comment by pveentjer** [comment]
I would also like to get rid of it completely. We have the heart beat that detect when a node is not usable. So we can lift on that mechanism afaik.

**Comment by pveentjer** [comment]
is still running operation has been removed and replaced by Operation timeout logic cleanup.
