### ISSUE TITLE
Allow the Hazelcast JCA Connector to specify an instance name

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast#4412]
As of Hazelcast 3.4, when using both the Hazelcast JCA Connector and Hazelcast as 2nd level cache for Hibernate, there is no way for Hibernate to re-use the same instance created by the Hazelcast JCA connector. This would be possible if the Hazelcast JCA Connector would allow to specify the instance name. The instance name for 2nd level cache for Hibernate can be specified as a property (hibernate.cache.hazelcast.instance_name).

**Comment by juanavelez** [comment]
@kobalski @enesakar I think this can be solved by PR #6513

**Comment by mustafaiman** [comment]
Solved via https://github.com/hazelcast/hazelcast/pull/6513 as stated.
