### ISSUE TITLE
Missing dependency in module.xml for JBoss 7 AS

### ISSUE THREAD

**Issue by juergen-roberg** [hazelcast/hazelcast#4415]
The documentation for Hazelcast 3.4 (Chapter 10.3.5) describes the following JBoss module.xml:
```xml
<module xmlns="urn:jboss:module:1.0" name="com.hazelcast">
<resources>
  <resource-root path="."/>
  <resource-root path="hazelcast-<version>.jar"/>
  <resource-root path="hazelcast-jca-<version>.jar"/>
</resources>
<dependencies>
  <module name="javax.api"/>
  <module name="javax.resource.api"/>
  <module name="javax.validation.api"/>
  <module name="org.jboss.ironjacamar.api"/>
</dependencies>
</module>
```
This results in an NoClassDefFoundError for sun.misc.Unsafe.
<code>
10:52:24,481 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 59) MSC000001: Failed to start service jboss.ra.deployer."hazelcast-jca-rar-3.4": org.jboss.msc.service.StartException in service jboss.ra.deployer."hazelcast-jca-rar-3.4": JBAS010446: Failed to start RA deployment [hazelcast-jca-rar-3.4]
<strong>
...
<strong>
Caused by: java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at com.hazelcast.nio.UnsafeHelper.findUnsafe(UnsafeHelper.java:122) [hazelcast-3.4.jar:3.4]
	at com.hazelcast.nio.UnsafeHelper.<clinit>(UnsafeHelper.java:65) [hazelcast-3.4.jar:3.4]
	at com.hazelcast.nio.UTFEncoderDecoder$UnsafeBasedCharArrayUtfWriter.<clinit>
...
</strong>
</code>
Please add sun.jdk as a dependency to module.xml.
```xml
<module xmlns="urn:jboss:module:1.0" name="com.hazelcast">
<resources>
  <resource-root path="hazelcast-3.4.jar"/>
  <resource-root path="hazelcast-jca-3.4.jar"/>
</resources>
<dependencies>
  <module name="sun.jdk"/>
  <module name="javax.api"/>
  <module name="javax.resource.api"/>
  <module name="javax.validation.api"/>
  <module name="org.jboss.ironjacamar.api"/>
</dependencies>
</module>
```

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/bc863f8576e3a85c7a54506893db51c478e30ed5
