### ISSUE TITLE
distributed query performed sequentually

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#4417]
Found in Hazelcast 3.3.3 and 3.3.4. 
I have a client and two cache servers, in test env all of them are started on the same machine. Client submits a task to one of the servers. On the server side, the task build a predicate and get keySet as

	Predicate pp = Predicates.equal("pathId", xPath.getPathId());
	Predicate<XDMDataKey, XDMElements> f = Predicates.and(pp, new QueryPredicate(pex, value));
	Set<XDMDataKey> xdmKeys = xdmCache.keySet(f);

I expected the query to be run in parallel on both cache nodes using partition threads (as it is stated in the reference manual: http://docs.hazelcast.org/docs/3.3/manual/html-single/hazelcast-documentation.html#distributed-query). But what I see is:

- the predicate applied to all entries owned by server which run the task. It is applied in a loop from the thread running task;
- when all local entries applied the predicate is serialized and sent to the second cache node;
- on the second node predicate is deserialized and applied to all entries owned by this node, from one thread;
- then the results sent back to the first node and returned as a keySet.

Is it a bag or it is expected behaviour? Is it possible to run the query in parallel on cache nodes from partition threads?

Thanks, Denis.

**Comment by dsukhoroslov** [comment]
I had a look at what's going on at this keySet() call. Hazelcast creates number of Features per each cluster Member, every Feature runs QueryOperation on corresponding Member. QueryOperation is  allowed to run from caller thread because it is not PartitionAware. When OperationService run Features it just starts them one by one. The first Feature in my case was assigned to the local Member and it invocation has blocked all subsequent Features because its QueryOperation was invoked from the caller thread. So, the fix to this issue is quite simple: put Feature for local Member at the very end of the Features list.

In order to parallelize local query execution the QueryOperation should be PartitionAware. But probably it'll give too much overhead: when partition number > number of partition threads, the same query will run several times from the same thread sequentially, for no reason. I'd assign  QueryOperations to partition threads, in this way one thread will exec query on all partitions which belongs to it.

BTW, why not use <hz:executor-service name="hz:query" ..> for this task?

Thanks, Denis.

**Comment by dsukhoroslov** [comment]
Sorry, I lost something in the last line :). The question was: what about dedicated query service "hz:query", why not use it for this task?

**Comment by dsukhoroslov** [comment]
Hi,

About the local query parallelization (the second part od the issue explained above): in my case it does not work because the query is indexed. Ok, let's skip it for a while. Can I suggest a simple fix for the first part of the issue? Can we patch QueryOperation.runParalel method in the following way:

    protected void runParallel(final Collection<Integer> initialPartitions) throws InterruptedException, ExecutionException {
        final NodeEngine nodeEngine = getNodeEngine();
        final ExecutorService executor
                = nodeEngine.getExecutionService().getExecutor(ExecutionService.QUERY_EXECUTOR);
        final List<Future<Collection<QueryableEntry>>> lsFutures
                = new ArrayList<Future<Collection<QueryableEntry>>>(initialPartitions.size());
        int localId = -1;
        for (Integer partitionId : initialPartitions) {
            if (nodeEngine.getPartitionService().getPartition(partitionId).isLocal()) {
            	localId = partitionId;
            } else {
            	Future<Collection<QueryableEntry>> f = executor.submit(new PartitionCallable(partitionId));
            	lsFutures.add(f);
            }
        }
        if (localId >= 0) {
        	Future<Collection<QueryableEntry>> f = executor.submit(new PartitionCallable(localId));
        	lsFutures.add(f);
        }

        final Collection<Collection<QueryableEntry>> returnedResults = getResult(lsFutures);
        for (Collection<QueryableEntry> returnedResult : returnedResults) {
            if (returnedResult == null) {
                continue;
            }
            for (QueryableEntry entry : returnedResult) {
                result.add(new QueryResultEntryImpl(entry.getKeyData(), entry.getKeyData(), entry.getValueData()));
            }
        }
    }

The patch just submit execution on the local member at the very end, preventing query to be blocked at the very beginning. Could someone make this patch or you want me to send a pull request for this?

Thanks, Denis.

**Comment by gurbuzali** [comment]
Hi,
There may be more that one partition which is local, so above solution is lacking.
Actually I still don't see why it does block on `executor.submit` if it is local

**Comment by dsukhoroslov** [comment]
Hi,

may be I'm wrong, but when I debug my case, I got feeling that the method runParallel works on member's basis somehow. I debug it in cluster of two nodes and and got two futures only, but I have 271 partitions. Ok, let me debug it again, will provide more details tomorrow.

**Comment by dsukhoroslov** [comment]
it seemse to be fixed in HZ 3.5.x
