### ISSUE TITLE
LocalRegionCache cleanup is wrong

### ISSUE THREAD

**Issue by u6f6o** [hazelcast/hazelcast#4445]
Hi, 

When I configure a ttl of 0 (according to documentations means eternal cache), my cache is fully evcited all the time. I added  a test method to LocalRegionCacheTest class to make it reproducible: 

    /**
     * According to documentation (http://docs.hazelcast.org/docs/3.3/manual/html-single/hazelcast-documentation.html)
     * 0 means eternal cache but instead we get evict everything all the time cache 
     *
     * time-to-live: Maximum time in seconds for each entry to stay in the map.
     * If it is not 0, entries that are older than and not updated for this time
     * are evicted automatically. Valid values are integers between 0 and Integer.MAX VALUE.
     * Default value is 0 and it means infinite. Moreover, if it is not 0, entries are
     * evicted regardless of the set eviction-policy.
     *
     *
     */
    @Test
    public void testCleanup() {
        HazelcastInstance instance = mock(HazelcastInstance.class);
        Config config = mock(Config.class);
        MapConfig mapConfig = mock(MapConfig.class);
        MaxSizeConfig maxSizeConfig = mock(MaxSizeConfig.class);

        when(config.findMapConfig(eq(CACHE_NAME))).thenReturn(mapConfig);
        when(mapConfig.getMaxSizeConfig()).thenReturn(maxSizeConfig);
        when(instance.getConfig()).thenReturn(config);

        when(maxSizeConfig.getSize()).thenReturn(10);
        when(mapConfig.getTimeToLiveSeconds()).thenReturn(0); // <- eternal cache

        LocalRegionCache localRegionCache = new LocalRegionCache(CACHE_NAME, instance, null, false);

        for (int i=1; i<=5; i++) {
            String key = "key" + i;
            String value = "value" + i;
            localRegionCache.put(key, value, value);
        }
        assertEquals(5, localRegionCache.size());
        localRegionCache.cleanup();
        assertEquals(5, localRegionCache.size());

        verify(instance).getConfig();
        verify(config).findMapConfig(eq(CACHE_NAME));
        verify(mapConfig).getMaxSizeConfig();
        verify(mapConfig).getTimeToLiveSeconds();
        verify(maxSizeConfig).getSize();
        verifyNoMoreInteractions(instance, config, mapConfig, maxSizeConfig);
    }

**Comment by u6f6o** [comment]
Besids that, basic features like using LRU or LFU evcition are also missing. CleanupService has a default interval and delay of 1 minute which also cannot be configured.

**Comment by u6f6o** [comment]
For my local tests I applied a dirty quick fix by doing: 
-            if (v.getCreationTime() + timeToLive < now) {
+            if (timeToLive > 0 && v.getCreationTime() + timeToLive < now) {

**Comment by u6f6o** [comment]
Hi, 

I tried to implement LFU on my own for the LocalRegionCache following the semantics from ClientNearCache. I'd appreciate if you could have a short look on it and tell me your oppinion about it. If the code is of any use for use, feel free to use it (https://github.com/u6f6o/hazelcast/commit/81dceb13633b10342d5e6a06eb94babae724658d).

I'd have one question though. How can I access the hazelcast threadpools to submit the evictions? On ClientNearCache it's done by context.getExecutionService().execute(, whereas context is the ClientContext

Thx, 
Ulf

**Comment by u6f6o** [comment]
I realized that this one was fixed in the meantime by #3882

**Comment by emrahkocaman** [comment]
Closing this ticket, thanks @u6f6o.
