### ISSUE TITLE
Same key in Different Named Caches Get deleted in the previously entered Caches.

### ISSUE THREAD

**Issue by ShenalSenarath** [hazelcast/hazelcast#4447]
When using the following dependencies

        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.0.0</version>
        </dependency>

        
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.3.3</version>
        </dependency>

Different Named caches have being put the same key and different values. 

At the end only the last put key value pair is existing in the cache. The key value pairs of the same name in other named caches disappears. As a solution i have prepended the cache name to the key and it works but this defeats the whole purpose of having named caches.

**Comment by serkan-ozal** [comment]
Hi @ShenalSenarath,

* Can you share your test code to understand the case better ?
* Can you also try with hazelcast **3.4** version to reproduce the same issue ?

Thanks.

**Comment by ShenalSenarath** [comment]
The issue is not there in 3.4 Thank you.

**Comment by serkan-ozal** [comment]
@ShenalSenarath ok thanks.

**Comment by serkan-ozal** [comment]
@gurbuzali can we close this issue or should fix on 3.3.x branch ?

**Comment by gurbuzali** [comment]
I've set the milestone to 3.4 and closing the issue.
but it would be good to have the reproducer test in our code base. can your provide it @ShenalSenarath ?

**Comment by ShenalSenarath** [comment]
Sorry I couldn't produce the results with a simpler test code. But this happens in a large system. Where there are lot of key pairs. I coudn't I think this is due to a hash collision. And I have found the same kind of a problem where key value pair disappear from the cache. 

Run two instance of the this program and you will get the first output value as "null". But change any string value in the code and run the results will be as expected and will return the both values. Or change the version of the Hazelcast into

```
    <dependencies>

        <dependency>
            <groupId>javax.cache</groupId>
            <artifactId>cache-api</artifactId>
            <version>1.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>3.3.3</version>
        </dependency>

    </dependencies>
```

```java
import javax.cache.Cache;
import javax.cache.CacheManager;
import javax.cache.Caching;
import javax.cache.configuration.MutableConfiguration;
import javax.cache.expiry.AccessedExpiryPolicy;
import javax.cache.expiry.Duration;
import java.util.Scanner;

/**
 * @author shenalsenarath on 1/7/2015.
 */
public class testJCache {
    public static void main(String []args) throws InterruptedException {
        String cacheName="TypedProperties";
        String cacheName1="SampleProperties";

        MutableConfiguration<String, Object> config = new MutableConfiguration<String, Object>();
        config.setStoreByValue(true)
                .setTypes(String.class, Object.class)
                .setExpiryPolicyFactory(AccessedExpiryPolicy.factoryOf(Duration.ETERNAL))
                .setStatisticsEnabled(false);

        //createCache
        CacheManager cacheManager= Caching.getCachingProvider().getCacheManager();
        Cache<String,Object> cache,cache1;

        if(cacheManager.getCache(cacheName,String.class,Object.class)==null){
            //This will run in the first instance creating all the caches
            cache = cacheManager.createCache(cacheName,config);
            byte number= 42;
            cache.put("propertyShortPrimitive42"+cacheName,number);
            cache1 = cacheManager.createCache(cacheName1,config);
            Integer num=1111;
            cache1.put("property.integer"+cacheName1,num);
            System.out.println("Cache Created and added the value");
        }else{
            //This will run in the instances after the first one
            cache = cacheManager.getCache(cacheName,String.class,Object.class);
            cache1 =  cacheManager.getCache(cacheName1,String.class,Object.class);
            System.out.println("Values from Cache");
            System.out.println(cache.get("propertyShortPrimitive42"+cacheName));//This will return a null. This is the issue
            System.out.println(cache1.get("property.integer" + cacheName1));

        }

        System.out.println("Press any key to exit ");
        Scanner in = new Scanner(System.in);
        in.nextLine();
        System.out.println("End");
    }
}
```
