### ISSUE TITLE
Duplicate 'store' call on MapStore when eviction happens

### ISSUE THREAD

**Issue by dirkvanrensburg** [hazelcast/hazelcast#4448]
When using write-behind and entries are evicted, which have not been stored yet, duplicate calls to the map store is made. This results in errors when the primary key is part of the map entry data and duplicate records in the database when it is not.

I will add a stabilizer test to illustrate this. It is easily reproducible when the mapstore is slow.

**Comment by dirkvanrensburg** [comment]
See hazelcast-stabilizer pull request: https://github.com/hazelcast/hazelcast-stabilizer/pull/475

**Comment by ahmetmircik** [comment]
Hi @dirkvanrensburg, 

This is a known issue thanks for the report and test. 
The gotcha part here trying to address this issue https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/writebehind/WriteBehindStore.java#L206

It should be fixed. 

Btw can you please retry the test by setting `MapStoreConfig#setWriteCoalescing` to `false` by using latest master? Problem should not be seen when using that setting.

**Comment by dirkvanrensburg** [comment]
Hi @ahmetmircik 

That did the trick, thanks. I updated the test to set that flag so the test will pass and updated the pull request. Not sure if you guys are interested in that or not.

I guess there are already some test covering this, so do you plan to merge this into the stabiliser tests or should I close the pull request.

PS: Note that I have a contributor agreement in place via the company I work for (Ecetera)
