### ISSUE TITLE
A bug in ClientNearCache eviction comparator

### ISSUE THREAD

**Issue by u6f6o** [hazelcast/hazelcast#4451]
In the ClientNearCache class there is the following comparator: 

    private final Comparator<CacheRecord<K>> comparator = new Comparator<CacheRecord<K>>() {
        public int compare(CacheRecord<K> o1, CacheRecord<K> o2) {
            if (EvictionPolicy.LRU.equals(evictionPolicy)) {
                return ((Long) o1.lastAccessTime).compareTo((o2.lastAccessTime));
            } else if (EvictionPolicy.LFU.equals(evictionPolicy)) {
                return ((Integer) o1.hit.get()).compareTo((o2.hit.get()));
            }

            return 0;
        }
    };

It is later on used in a TreeSet to finde the entries that should be evicted. Problem is, if there are CacheRecords with the same hit count or lastAccessTime (depending on LFU/LRU), you'll only add one of these although most likely all of them should be evicted. 

Think it's a minor issues since this will most likely not happen that often. Maybe you should rely on the CacheRecord key as well though?

**Comment by sancar** [comment]
It is not likely to happen in LRU option. But I think in LFU case, it can be problematic. Solution is easy. I am trying to write a test to verify the problem. 

And it seems that same problem can happen for node side near cache also.

Thanks for bug report.

**Comment by u6f6o** [comment]
Yes, LRU shouldn't matter normally. I already wrote a test to verify my assumption, if you're intersted, I can post it later on here.

**Comment by sancar** [comment]
One more test is always welcome.

**Comment by u6f6o** [comment]
I realised that I changed the visibility of the cache field to package protected, so it won't help you :-(. Not sure if JIT will optimize it anyways, but wouldn't it be probably better to have one LFU comparator and one LRU comparator instead of checking for it every time compare method is called?

**Comment by sancar** [comment]
Thanks @u6f6o . I updated my pr according to your comments.
