### ISSUE TITLE
Execution of predicates on Maps with MapStore

### ISSUE THREAD

**Issue by romix** [hazelcast/hazelcast#446]
Hi,

This discussion is a bit old and the question was asked more than once, e.g. here (https://groups.google.com/forum/?fromgroups=#!topic/hazelcast/lOa53m5LLVY and https://groups.google.com/forum/?fromgroups=#!topic/hazelcast/iCmkBT-cYdw), but let me give it another try.

I understand that currently Hazelcast takes only active entries in the Map into account when executing predicates. I also understand that Hazelcast cannot know, when it should consult the MapStore.

But I'd like to suggest the following idea:
- What if Hazelcast would optionally allow to configure a map instance in such a way that every time when predicate is to be evaluated, Hazelcast would first invoke a user-specified class with some callback methods? This class could be a implementing a MapStore or may be a new dedicated interface (something like PredicateEvaluationListener). Such a class could contain a user-defined logic that would decide if it needs to query a persistent store or if it can safely ignore the evaluation of a given predicate. In case it queries a persistent store and gets some results, it would return them to Hazelcast which could then return them or merge them with the results produced by the usual execution of this predicate on active entries in memory.
- Optionally, the callback could indicate in its return value (or by some other means) that Hazelcast should not execute the predicate on active entries and simply return the results obtained by querying the persistent store, because they already cover/include all matching active entries. By default Hazelcast should execute a given predicate on active entries to stay backwards-compatible.
- Optionally per config, one could indicate that after Hazelcast evaluated predicate on in-memory entries, it should invoke a callback that can do post-processing. E.g. it could filter the result or enrich them with something from the MapStore or the like.

IMHO, the implementation of such a proposal is very straight forward (add a configuration option and invoke a callback class if provided), and the feature could be very useful, as with it, one could make Hazelcast behave more like a usual database, when it performs SQL queries. Typically, you expect from a DB that it takes ALL stored entries into account and not only a subset of entries that is currently kept in memory. This is a very natural semantics. And with this feature, those who need this semantic, can implement it to their liking.

What do you think about it?
-Leo

**Comment by mdogan** [comment]
This is still not on the roadmap. Closing.

**Comment by rmannibucau** [comment]
+1for this feature otherwise feature are exclusive but no validation guarantees it which is very error prone + it  is useful
