### ISSUE TITLE
Add GroupBy/Having, Combined aggregations to Hazelcast Aggregations

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#4480]
To enhance the use cases for Hazelcast Aggregations we need to add support to combine multiple Aggregators to be executed in one shot and add GroupBy/Having support as well.

Further information available in the internal PRD.

**Comment by jcbozonier** [comment]
This would be great. Right now what's the best way to do a group by? I imagine it ending in some sort of MultiMap data structure.
