### ISSUE TITLE
Possible data loss on split brain syndrome.

### ISSUE THREAD

**Issue by akoledzhikov** [hazelcast/hazelcast#4481]
I have a cluster of 3 Hazelcast nodes which hold a shared map with a bunch of entries in it. Two of them are on the same machine (A) and one is on a different one. The backup count for this map is 5 (sync 3 async 2).
I disable the network interface on machine A. After the node on B has detected the network split and declared the other 2 nodes dead, I check the map - there are several missing records.
After some investigation, I found out that a record is restored from backup only if the current node is its first backup holder:

if (deadAddress.equals(partition.getOwner()) && thisAddress.equals(partition.getReplicaAddress(1))) // taken from InternalPartitionServiceImpl

But, in my case, I suppose that for some partitions, the lone node on B is neither the owner, nor the first backup.

Sorry, but I cannot attach sample test code right now - the issue happened on one of our production systems :/ If you want, I can prepare a simple test case, but would take some time.

**Comment by hasancelik** [comment]
Thanks for reporting your issue . Now we have information about cluster size and steps to reproduce. Could you provide more information like,

-hazelcast version , 
-version of Java , 
-integration module versions if available (e.g. Tomcat, Jetty, Spring, Hibernate) with detailed configuration information (web.xml, Hibernate configuration, Spring context.xml etc.)

We would be grateful if you can provide a simple test case.

**Comment by akoledzhikov** [comment]
Hazelcast version - 3.2.3
Version of java - not sure if relevant, reproduced it with various builds of 1.6 and 1.7
Integration module - none used

Sample test code - http://pastebin.com/1gZm6JZS
Actually, it seems that you do not have to use different machines and drop the network interface on one of them - it is enough to start 3 cluster nodes and then kill 2 of them (almost) simultaneously.
Thanks :)

**Comment by hasancelik** [comment]
Thanks for information and simple test case. We are on it.

**Comment by maseev** [comment]
Any news on this issue?

**Comment by metanet** [comment]
Hi @maseev 

We are currently working on #5444 and this issue is also related to it. We expect our fix to be merged into master in a couple of weeks. 

Regards
