### ISSUE TITLE
[TEST-FAILURE] LockTest.testKeyOwnerDies

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4495]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.concurrent.lock.LockTest.testKeyOwnerDies(LockTest.java:747)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/445/testReport/junit/com.hazelcast.concurrent.lock/LockTest/testKeyOwnerDies/

**Comment by mesutcelik** [comment]
@gurbuzali ,

Can you please check that one? It has never failed on master so far.
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/2740/testReport/com.hazelcast.concurrent.lock/LockTest/testKeyOwnerDies/history/

**Comment by gurbuzali** [comment]
we are testing lock backup with this test and I remember we've fixed/improved related with lock-backup.
I think we can close it
