### ISSUE TITLE
Cleanup of GroupProperties

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#4505]
Some of the properties mentioned in GroupProperties aren't used anymore, for example "hazelcast.jmx.detailed".

Those properties should be removed from sourcebase and documentation. There are also some examples in the documentation where old properties are still used. Those should be cleaned up / updated as well.

**Comment by Serdaro** [comment]
Dear Core team,
Please let me know when the clean up is completed.

**Comment by Serdaro** [comment]
Documentation side is cleaned up. Texts for the following properties removed:
hazlecast.jmx.detailed
hazelcast.partition.migration.zip.enabled
hazelcast.system.log.enabled

I guess the next step is on the Dev team.

**Comment by magiccrafter** [comment]
The documentations are still not quite complete.
The programmatic way for setting a configuration in the documentation won't compile at all:
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#monitoring-with-jmx
i.e. this is not going to work
config.setProperty(GroupProperty.ENABLE_JMX, "true");
