### ISSUE TITLE
Allow declarative JCache configuration

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#4510]
Declarative JCache configuration would make JCache easier to use. Currently I have to create a configuration, call createCache(), etc.

The contract of 
```java
  <K, V> Cache<K, V> getCache(String cacheName);
```
says:
>    * Implementations that support declarative mechanisms for pre-configuring
   * {@link Cache}s may return a pre-configured {@link Cache} instead of
   * <code>null</code>.

I can imagine hazelcast.xml would be a good place for this.

**Comment by pveentjer** [comment]
Even if we can't use that method, we can always put a method Hazelcast.newICache that behaves in the same was as e.g. IMap.

**Comment by jerrinot** [comment]
@pveentjer: true.

Yes another reason for the declarative configuration:
It allows you to use implementation-specific features without your (Java) code depending on implementation specific classes.

**Comment by gurbuzali** [comment]
We do have declarative configuration for jcache

**Comment by jerrinot** [comment]
Oh, really. I must have missed it. Is it in the hazelcast-full.xml example
config?

**Comment by gurbuzali** [comment]
http://docs.hazelcast.org/docs/3.4/manual/html-single/hazelcast-documentation.html#jcache-configuration

**Comment by jerrinot** [comment]
Silly me! Thanks a lot Ali!
