### ISSUE TITLE
[TEST-FAILURE] client.ClientRegressionTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4516]
```
Running com.hazelcast.client.ClientRegressionTest
Build timed out (after 90 minutes). Marking the build as aborted.
```

our 3.x-IbmJDK1.7 build timed out due to this test.
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/450/console

**Comment by bilalyasar** [comment]
new timeout: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/197/console

**Comment by sancar** [comment]
Closing this one since it did not failed over 1 month.

**Comment by bilalyasar** [comment]
new failure:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/72/console

**Comment by sancar** [comment]
Timeout seems like jenkins problem. I looked at the logs and actually test did not timeout. There are other tests starting after ClientRegressionTest and passed . I am closing this one.
