### ISSUE TITLE
QueryIndexMigrationTest.testQueryWithIndexDuringJoin

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4517]
```
java.lang.AssertionError: expected:<500> but was:<493>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.map.query.QueryIndexMigrationTest.testQueryWithIndexDuringJoin(QueryIndexMigrationTest.java:232)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/429/testReport/junit/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by mesutcelik** [comment]
This hasn't failed lately. Have we fixed such an issue before?

WDYT @ahmetmircik ?

**Comment by ahmetmircik** [comment]
dont remember a fix but it looks like we can close it till the next failure.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/2746/testReport/junit/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by mesutcelik** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/4686

**Comment by mesutcelik** [comment]
have we fixed that problem in maintenance?

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/46/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3095/testReport/junit/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by mesutcelik** [comment]
no recent failure. closing.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/77/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/850/com.hazelcast$hazelcast/testReport/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.7/com.hazelcast$hazelcast/140/testReport/junit/com.hazelcast.map.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/182/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<500> but was:<499>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexDuringJoin(QueryIndexMigrationTest.java:234)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/4366/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<500> but was:<498>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexDuringJoin(QueryIndexMigrationTest.java:234)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/163/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by vbekiaris** [comment]
Fixed by #8403

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:372)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:297)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:909)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:614)
	at com.hazelcast.test.HazelcastTestSupport.waitAllForSafeState(HazelcastTestSupport.java:610)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexDuringJoin(QueryIndexMigrationTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/983/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexDuringJoin/

**Comment by vbekiaris** [comment]
This looks like a legitimate timeout due to load in the test environment:
- Test starts at 05:00:06,542
- Test's nodes start:
```
05:00:07,424  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2807 - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10984 is STARTED
05:00:10,498  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2810 - [127.0.0.1]:10987 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10987 is STARTED
05:00:17,367  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2808 - [127.0.0.1]:10985 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10985 is STARTED
05:00:18,351  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2809 - [127.0.0.1]:10986 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10986 is STARTED
05:00:23,392  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2811 - [127.0.0.1]:10988 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10988 is STARTED
```
- There is continuous `TRACE` level logging from `MigrationOperation`s, `PartitionReplicaStateChecker` etc:
`05:00:29,541 TRACE |testQueryWithIndexDuringJoin| - [PartitionReplicaStateChecker] testQueryWithIndexDuringJoin - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] Missing replica=4 for partitionId=0 `
- When reaching timeout, the cluster is still executing migrations:
```
05:01:05,340 DEBUG |testQueryWithIndexDuringJoin| - [MigrationManager] hz._hzInstance_5894_dev.migration - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] Finished Migration: MigrationInfo{uuid=05d7329a-84b4-4643-a533-a922164552b0, partitionId=213, source=null, sourceUuid=<invalid-uuid>, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:10985, destinationUuid=cf65d1b1-1a65-40dc-bc60-6756b5760958, destinationCurrentReplicaIndex=-1, destinationNewReplicaIndex=4, master=[127.0.0.1]:10984, processing=false, status=ACTIVE}
...
05:01:05,347 DEBUG |testQueryWithIndexDuringJoin| - [PartitionStateOperation] hz._hzInstance_5898_dev.generic-operation.thread-0 - [127.0.0.1]:10988 [dev] [3.7-SNAPSHOT] Applied new partition state: true. Version: 1626, caller: [127.0.0.1]:10984
...
05:01:06,543 DEBUG |testQueryWithIndexDuringJoin| - [PartitionStateOperation] hz._hzInstance_5898_dev.priority-generic-operation.thread-0 - [127.0.0.1]:10988 [dev] [3.7-SNAPSHOT] Applied new partition sta
te: true. Version: 1682, caller: [127.0.0.1]:10984
05:01:06,546  INFO |testQueryWithIndexDuringJoin| - [LifecycleService] Thread-2803 - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] [127.0.0.1]:10984 is SHUTTING_DOWN
05:01:06,546 TRACE |testQueryWithIndexDuringJoin| - [Node] Thread-2803 - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] We are being asked to shutdown when state = ACTIVE
05:01:06,546  WARN |testQueryWithIndexDuringJoin| - [Node] Thread-2803 - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] Terminating forcefully...
05:01:06,546  INFO |testQueryWithIndexDuringJoin| - [Node] Thread-2803 - [127.0.0.1]:10984 [dev] [3.7-SNAPSHOT] Shutting down connection manager...
```
