### ISSUE TITLE
Hazelcast 3.4 + Spring 3.2 + Hibernate 4.3.6

### ISSUE THREAD

**Issue by magx2** [hazelcast/hazelcast#4519]
I'm trying to run Hazelcast with Spring and Hiberante 4. The problem is that when I'm starting an application I get error: _org/hibernate/cache/QueryResultsRegion_. Probably the problem is that in _hazelcast-all-3.4_ is dependecy to _hazelcast-hibernate3-3.4_. Also with _hazelcast-spring-3.4_ there is the same problem, because it depends on _hazelcast-hibernate3-3.4_ (i.e. look at this [this example](https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-hibernate-2ndlevel-cache/pom.xml)).

So is there any way to integrate *Hazelcast 3.4* + *Spring 3.2* + *Hibernate 4.3.6*?

**Comment by bilalyasar** [comment]
@magx2 as you said you have dependency like:
```
   <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-all</artifactId>
            <version>${hazelcast.version}</version>
        </dependency>
```
if you have, can you convert it?:
```
        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast-hibernate3</artifactId>
            <version>${hazelcast.version}</version>
        </dependency>

        <dependency>
            <groupId>com.hazelcast</groupId>
            <artifactId>hazelcast</artifactId>
            <version>${hazelcast.version}</version>
        </dependency>
```
hazelcast-all includes hazelcast-hibernate3 and hazelcast-hibernate4 this causes problem.

**Comment by magx2** [comment]
@bilalyasar but what it will gives me? I think that I should throw out *hazelcast-hibernate3* and put hibernate4 instead of it.

Also I need to Integrate it with Spring 3. On [maven](http://mvnrepository.com/artifact/com.hazelcast/hazelcast-spring/3.4) I see that *hazelcast-spring* depends on *hazaelcast-hibernate3*.

**Comment by mesutcelik** [comment]
It seems @magx2 is right... hazelcast-spring module shouldn't depend on any hazelcast-hibernate specific version... 

What we can do is to remove compile time dependency on hazelcast-hibernate3 and load related class at runtime.

if the developer who wants to use hazelcast-spring module wants also to configure hazelcast-hibernate 2nd level cache module, he just needs to add related hazelcast-hibernate jar file to the classpath.

**Comment by magx2** [comment]
Also in **hazelcast-hibernate4** (in pom.xml) you have dependecy to hibernate **4.2.13.Final**. The latest version of hibernate is **4.3.8**.

**Comment by Tancerd** [comment]
Hello, i have the same problem. 
Are there any chances to fix this defect in closest time?
