### ISSUE TITLE
[lock] API to merge ILock / IMap::lock after splitbrain

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#4524]
After a splitbrain situation we need to support resolving conflicting locks using ILock or IMap::lock .

**Comment by mmedenjak** [comment]
The lock service should implement `SplitBrainHandlerService`

**Comment by mmedenjak** [comment]
As `ILock`, `ISemaphore`, `ICountDownLatch` are very sensitive data structures that cannot be simply merged between two clusters in non-trivial cases, we choose not to provide this option and consider implementing linearizable locks in the future. See: https://hazelcast.atlassian.net/wiki/spaces/PM/pages/194871307/Merge+Policies+for+Additional+Data+Structures
