### ISSUE TITLE
Index ignores null keys

### ISSUE THREAD

**Issue by dayman** [hazelcast/hazelcast#4525]
This test will fail.
```
public class HazelcastIndexTest {

    public static class TestClass implements Serializable {
        private String field;

        public TestClass(final String field) {
            this.field = field;
        }

        public String getField() {
            return field;
        }

    }

    @Test
    public void hazelcastIndexDoesntWork() {
        final HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(null);
        final IMap<String, TestClass> map = hazelcast.getMap("map");
        
        // given
        map.addIndex("field", false); // if we remove this line, test will pass
        map.put("1000", new TestClass(null));
        map.put("1001", new TestClass("not null"));

        // when
        final Predicate emptyFieldPredicate = Predicates.notEqual("field", "value");
        final Collection<TestClass> emptyFieldValues = map.values(emptyFieldPredicate);

        // then
        assertThat(emptyFieldValues, hasSize(2));
    }

}
```
Apparently test should return both of the entries but it ignores one with "null" value.
If we remove index for "field", it will pass.

**Comment by hasancelik** [comment]
Thanks for reporting your issue. Please share with us the following information, to help us resolve your issue quickly and efficiently.
* **Hazelcast version** that you are using  (e.g. 3.4, also specify minor release or latest snapshot)
* **Hazelcast configuration** (hazelcast.xml or programmatic configuration)
* **Cluster topology**
  * Number of Hazelcast member nodes
  * Number of Hazelcast clients
* **Operating System** (for Linux kernel version will be helpful)
* **Logs and Stack Traces** (if available)
* **Integration module versions** if available (e.g. Tomcat, Jetty, Spring, Hibernate)
  ** Detailed configuration information (web.xml, Hibernate configuration, Spring context.xml etc.)

**Comment by dayman** [comment]
**Hazelcast version**: 3.4
**Hazelcast configuration**: I launched embedded instance (with Hazelcast.newHazelcastInstance(null)), so the configuration was default, no xml file.
And as you can see I added index manually from code. 
But also experienced absolutely same problem when launched hazelcast with xml configuration contained
```
<map name="map">
  <backup-count>0</backup-count>
  <async-backup-count>0</async-backup-count>
  <read-backup-data>true</read-backup-data>
  <indexes>
    <index>field</index>
  </indexes>
</map>
```
**Cluster topology**: one node
**Operating system**: Ubuntu 14.04
**Integration module versions**: no other libraries during the test

**Comment by muratayan** [comment]
Hello @dayman,

This is the intended behavior of `Predicates`. If you also want to access to `null` values you should explicitly look for them as well. 

Example:
```java
        // when
        final Predicate emptyFieldPredicate = Predicates.notEqual("field", "value");
        final Predicate nullPredicate = Predicates.equal("field", null);
        final Collection<TestClass> emptyFieldValues = map.values(Predicates.or(emptyFieldPredicate, nullPredicate));

        // then
        assertEquals(2, emptyFieldValues.size());   
```

Check out this SQL equivalent: 
![screen shot 2015-03-24 at 4 43 57 pm](https://cloud.githubusercontent.com/assets/4989547/6804203/169a63de-d245-11e4-9e1d-0a5263903d6b.png)

Please let me know if there are any contradictions.

**Comment by dayman** [comment]
Hello @muratayan.

As I mentioned the problem only appear when you add index for the field. If there is no index it works fine. So I can't agree this behavior is intended, it should at least work identically for both cases.

**Comment by muratayan** [comment]
Hey @dayman,
 
You are right, it should behave the same way when you don't use the index. I'm working on it, I'll let you know soon.

**Comment by dimas** [comment]
Is it by design that 
```java
Predicates.not(Predicates.equal("field", "value"));
```
still returns null values ?
