### ISSUE TITLE
Allow Comparable objects in a collection to be added to an index

### ISSUE THREAD

**Issue by dirkvanrensburg** [hazelcast/hazelcast#4547]
Some objects contains a collection in them and it will be useful to allow the values in the collection to be added to an index if they are Comparable.

*For example:* Given a Document object with a Collection of categories.

```java
public class Document implements Serializable {
    private String contents;
    private List<String> categories;
}
```
An index can be added for the *`categories`*

```java
map.addIndex( "categories", false);
```
To find all the documents with the category 'fiction'

```java
EntryObject e = new PredicateBuilder().getEntryObject();
Predicate p = e.get("categories").equal("fiction");

Collection<Document> documents = map.values(p);
```

**Comment by jerrinot** [comment]
fixed by #6525
