### ISSUE TITLE
ReplicatedMap does not re-sync after merge

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#4557]
After a splitbrain situation the ReplicatedMap is not merged. From user perspective it is very expected to at least see a try to re-sync the content.

The question is what side (which cluster) should try to send data to what other cluster? As far as I remember that was one of the reasons it wasn't implemented since everybody would have to send data to everybody else.
I don't think this is just a basic bugfix that can be done in a few minutes like just implement a listener and we're done. This needs to get some more thoughts.

**Comment by pveentjer** [comment]
AFAIK you don't have control on who gets asked; AFAIK the oldest cluster will ask the youngest cluster; come join me and create your merge tasks. This could be a problem in itself; imagine that you have a 10 node cluster and the oldest member gets cut off. When it eventually joins, the youngest cluster will try to merge their state in the oldest member. Please someone correct me if I'm wrong @gurbuzali @mdogan.

I see that your ReplicatedMapService doesn't implement SplitBrainHandlerService; so is not going to deal with merging and afaik the system will just discard everything from the youngest cluster.

**Comment by noctarius** [comment]
I know all that, the reason I said it isn't just done by implementing the listener :)

**Comment by eminn** [comment]
Fixed by #6176
