### ISSUE TITLE
NullPointerException in ServiceLoader when classloaders break contract

### ISSUE THREAD

**Issue by hcoles** [hazelcast/hazelcast#4563]
Although classloader.getResources should never return null, some classloaders break the contract (e.g the classloader used by SBT see https://github.com/sbt/sbt/issues/1368).

This prevents hazelcast being used in tests launched from sbt.

A null check in com.hazelcast.util.ServiceLoader.findHighestReachableClassLoader would allow hazelcast to be used from SBT and in other situations where classloaders misbehave.

**Comment by pveentjer** [comment]
@serkan-ozal @noctarius can you have a look? Classloaders always give me a headache.

**Comment by noctarius** [comment]
I guess a null check might be ok since it will just ignore this classloaders. Are you sure the application will work then as expected? Have you tried to patch Hazelcast and run it?

**Comment by serkan-ozal** [comment]
From my side also, a simple null check should fix the problem wtihout any side effect.

**Comment by pveentjer** [comment]
http://cdn.lolcaption.com/wp-content/uploads/2013/01/lolcaption-funny-demotivational-posters-antimotivational-demotivationpostes-overconfidence-this-is-going-to-end-in-disaster-cat-eagle.jpg

;)

**Comment by serkan-ozal** [comment]
BTW, @jerrinot has already sent a PR (https://github.com/jerrinot/sbt/commit/fbde253178b60439070dd4f49fc62eafa08eb285) to SBT repository by changing returning null to empty collection. So it should fix the problem at SBT side, so there should be no change need in our code base. Lets wait user to verify this PR fixed the problem :)

**Comment by hcoles** [comment]
I've confirmed that a simple null check in hazelcast fixes the issue. I'd be happy to submit a PR, but unfortunately a freshly checked out hazelcast gives both test failures and test errors on my machine.

While I agree the correct place to fix this is within SBT, this small change to hazelcast would make it usable for people tied to early versions of SBT.

**Comment by serkan-ozal** [comment]
@hcoles, what about the PR (https://github.com/jerrinot/sbt/commit/fbde253178b60439070dd4f49fc62eafa08eb285) sent by @jerrinot to SBT repository ?

**Comment by hcoles** [comment]
@serkan-ozal That PR was withdrawn as it didn't compiled on < Java 7 (SBT requires 6).

I've raised my own

https://github.com/sbt/sbt/pull/1853

It isn't yet merged, and as the SBT travis checks seem to error even without a change I'm not confident that it will be merged any time soon.

Even if this is merged, it will still mean that hazelcast is not usable with earlier versions of SBT. 

Upgrading SBT for a build is a by no means guaranteed to be painless (breaking change in the api has been common), so I'd argue that it would still be worth fixing within hazelcast.

**Comment by jerrinot** [comment]
I guess we should include the workaround in Hazelcast codebase. There doesn't seem to be much activity on the SBT side.

**Comment by serkan-ozal** [comment]
@jerrinot ok, right. I am OK with a null check in our code base and don't see any side-effect at this point.

**Comment by hcoles** [comment]
The 0.13.8 release of SBT included my fix, so it's now possible to use hazelcast with SBT.

Although this solves the issue for me - you might still want to consider adding the null check on the hazelcast side for the benefit of people stuck with earlier sbt versions.

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/5d85eb03705e109c5e709f30f5ca60d704d75bb5
