### ISSUE TITLE
Hazelcast support for Spring Transaction

### ISSUE THREAD

**Issue by mostafafci** [hazelcast/hazelcast#4584]
hello,

is there any way to add Hazelcast transaction to the Spring transaction manager - some thing like org.springframework.jdbc.datasource.DataSourceTransactionManager-

**Comment by mesutcelik** [comment]
There is already an issue for that feature. https://github.com/hazelcast/hazelcast/issues/611

**Comment by mostafafci** [comment]
do you expect the release of this feature will be soon?

**Comment by mesutcelik** [comment]
It could be in 3.6 but not decided yet...

**Comment by bwzhang2011** [comment]
@mesutcelik , such should be taken into consideration and gain the priority in the plan for the new features releasing. for spring integration is very important.
