### ISSUE TITLE
Management Console-Map-TimeTravel  Not Working

### ISSUE THREAD

**Issue by CatchSandeepVaid** [hazelcast/hazelcast#4590]
I have a Map m and say at 10:00 i inserted (Key1,Value1, 2,TimeUnit.MINUTES ) in it and after 2 minutes i.e @ 10:02, i put another entry in map as (Key1,Value2, 10,TimeUnit.MINUTES ).

Now on management console if i navigate back to say 10:01, for key Key1, its showing value as Value2 instead of Value1. So this is a major bug.

**Comment by emrahkocaman** [comment]
Hi @CatchSandeepVaid, time-travel is only for inspecting statistics. Old values of data structures can not be seen.
