### ISSUE TITLE
NearCacheConfig.readData reads "maxSize" twice

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4609]
```
    public void readData(ObjectDataInput in) throws IOException {
        ...
        maxSize = in.readInt();
        maxSize = in.readInt();
        ...
    }
```

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/NearCacheConfig.java

**Comment by Donnerbart** [comment]
Code like that should always be suspicious. Looks like a good thing for checkstyle or FindBugs rule.

**Comment by jerrinot** [comment]
how this could ever worked?

**Comment by serkan-ozal** [comment]
node idea. I found this while writing unit test for my near cache impl on client

**Comment by ahmetmircik** [comment]
Why is `NearCacheConfig` serializable?

**Comment by serkan-ozal** [comment]
AFAIK, when the cache is created at client side such as `cacheManager.createCache(cacheName, cacheConfig)`, `CacheConfig` is send over `CacheCreateConfigRequest` and also there is `NearCacheConfig` inside `CacheConfig`. And so they are all serialized to nodes

**Comment by ahmetmircik** [comment]
Thanks @serkan-ozal i did not know it is used in jcache.

**Comment by serkan-ozal** [comment]
@ahmetmircik you are welcome. It was defined in `CacheConfig` but always `null` since we didn't use it for JCache as I know :) So I think, because of it is not used/set, it was not serialized so there was no error until now.
