### ISSUE TITLE
Integrating HazelcastCacheManager into spring-context-support subproject

### ISSUE THREAD

**Issue by mulderbaba** [hazelcast/hazelcast#4612]
It'd be great if possible moving `HazelcastCacheManager` class into `spring-context-support.jar` under package like: `org.springframework.cache.hazelcast` similar like `Ehcache` does with its manager: `org.springframework.cache.ehcache.EhCacheCacheManager`. This approach would be convenient for the new comers that started using `spring-cache` subproject.

**Comment by serkan-ozal** [comment]
I think also, it would be great a `org.springframework.cache.hazelcast.HazelcastCacheManager` implementation just delegates to `com.hazelcast.spring.cache.HazelcastCacheManager` wtihout any logic. So our internal fixes/enhancements doesn't effect to `HazelcastCacheManager` on Spring's repository.

**Comment by mesutcelik** [comment]
I think that is something that has to be done on the spring framework repository. 

@serkan-ozal , @mulderbaba ,
you are free to contribute :)

**Comment by mesutcelik** [comment]
AFAIK, there is no such plan on the spring side... @snicoll might give us more info.

I am closing this for the time being.

**Comment by snicoll** [comment]
I've requested a correlated improvement in hazelcast to rely on `hazelcast-spring` and have the `hazelcast` library being pulled transitively. That way, Spring users can add `hazelcast-spring` and be good to go. @mesutcelik is that merged already? Thanks!

**Comment by mesutcelik** [comment]
Those are merged PRs.
https://github.com/hazelcast/hazelcast/pull/4912
https://github.com/hazelcast/hazelcast/pull/4948
