### ISSUE TITLE
Split brain can not be recovered

### ISSUE THREAD

**Issue by Neway6655** [hazelcast/hazelcast#4615]
I met the split brain merge issue recently, using hazelcast 2.6.9.

I found that the cluster can not be merged automatically after split brain, and I did some analysis based on the log and tcpdump result, together with the source code, found that it maybe a bug of hazelcast: split brain can not be recovered from two clusters, if both of them do not have a 'real' master.

Some more details: There are two clusters(e.g. cluster A and cluster B), after split brain, and cluster A has three members (M1, M2, M3), M1 and M2 thinks M3 is their master, but M3 does not think so, because i get the log from M3: "M1/M2 has sent MasterConfirmation, but this node is not master!"
while cluster B has two members (M2, M3), and M3 thinks M2 is its master, but M2 does not think so, because the log in M2 shown: "M3 has sent MasterConfirmation, but this node is not master!", so I guess, cluster A and B do not has a 'real' master, because the master(M3 and M2) do not admit themselves as the masters. 

One more thing in my case is that: there are two hazelcast instances (one normal member and one lite member) in one machine, with different port (5801 and 5802).

So, please help to check with the code, because i just go through the code quickly, and found that the cluster seems can not be merged in my case, and please correct me if anything is wrong.

Thanks!

**Comment by hasancelik** [comment]
Thanks for reporting your issue. Please share with us the following information, to help us resolve your issue quickly and efficiently.
* **Hazelcast configuration** (hazelcast.xml or programmatic configuration)
* **Java version** (also JVM parameters can be added)
* **Operating System** (for Linux kernel version will be helpful)
* **Logs and Stack Traces** (if available)
* **Unit Test**(if you can include a unit test which reproduces your issue, we would be grateful)
* **Integration module versions** if available (e.g. Tomcat, Jetty, Spring, Hibernate)
  * Detailed configuration information (web.xml, Hibernate configuration, Spring context.xml etc.)

**Comment by Neway6655** [comment]
We have a hazelcast configuration file template and using programmatic configuration as well, here is the hazelcast.xml file:

```xml
  <group>
    <name>dev</name>
    <password>dev-pass</password>
  </group>
  <network>
    <port auto-increment="true">5801</port>
    <join>
      <multicast enabled="true">
        <multicast-group>224.2.2.5</multicast-group>
        <multicast-port>54388</multicast-port>
      </multicast>
    </join>
    <interfaces enabled="true">
      <interface>192.168.0.15</interface>
      <interface>192.168.0.16</interface>
      <interface>192.168.0.17</interface>
      <interface>192.168.0.18</interface>
      <interface>192.168.0.19</interface>
      <interface>192.168.0.20</interface>
    </interfaces>
  </network>
  <properties>
    <property name="hazelcast.max.no.heartbeat.seconds">60</property>
  </properties>
```
And here is the configuration code:
```java
public void initInstance() throws Exception {
    try {
        Config config = new XmlConfigBuilder().build();
        initGroupConfig(config);
        if (liteMember) {
	        config.setLiteMember(liteMember);
        } else {
	        initMapConfig(config);
        }
......
private void initGroupConfig(Config config) {
      GroupConfig groupConfig = new GroupConfig();
      groupConfig.setName(OAUTH_GROUP_NAME);
      groupConfig.setPassword(OAUTH_GROUP_PASSWORD);
      config.setGroupConfig(groupConfig);
      logger.info("Setting up hazelcast for group '" + OAUTH_GROUP_NAME + "'");
}

private void initMapConfig(Config config) {
    MapConfig mapConfig = new MapConfig("master");
    mapConfig.setBackupCount(1);
    mapConfig.setTimeToLiveSeconds(30);
    mapConfig.setEvictionPolicy("NONE");

    MaxSizeConfig maxSizeConfig = new MaxSizeConfig();
    maxSizeConfig.setMaxSizePolicy(MaxSizeConfig.POLICY_MAP_SIZE_PER_JVM);
    maxSizeConfig.setSize(512);
    mapConfig.setMaxSizeConfig(maxSizeConfig);

    config.addMapConfig(mapConfig);    
}
```
And please note that we have two hazelcast instances(with same group) in one machine, one for normal member and one for lite member.

We used jrockit-jdk, info as below:
java version "1.6.0_85"
Java(TM) SE Runtime Environment (build 1.6.0_85-b13)
Java HotSpot(TM) 64-Bit Server VM (build 20.85-b01, mixed mode)

Operating System Info:
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.5 (Santiago)
Release:        6.5
Codename:       Santiago

Kernel version: Linux 2.6.32-431.40.1.el6.x86_64

Logs: 
Here are part of logs in one machine:
Feb 12, 2015 11:42:20 PM com.hazelcast.cluster.ClusterManager$MasterConfirmation
WARNING: [192.168.0.18]:5802 [exposure-oauth] Address[192.168.0.16]:5801 has sent MasterConfirmation, but this node is not master!
Feb 12, 2015 11:42:21 PM com.hazelcast.cluster.ClusterManager$MasterConfirmation
WARNING: [192.168.0.18]:5802 [exposure-oauth] Address[192.168.0.18]:5801 has sent MasterConfirmation, but this node is not master!
Feb 12, 2015 11:42:26 PM com.hazelcast.cluster.ClusterManager$MasterConfirmation
WARNING: [192.168.0.18]:5802 [exposure-oauth] Address[192.168.0.16]:5802 has sent MasterConfirmation, but this node is not master!

And interesting logs in another machine:
Feb 12, 2015 11:42:21 PM com.hazelcast.cluster.ClusterManager$MasterConfirmation
WARNING: [192.168.0.16]:5801 [exposure-oauth] Address[192.168.0.18]:5802 has sent MasterConfirmation, but this node is not master!

Unit Test: sorry that we can not reproduce this issue by unit test.

Integration module versions:
Weblogic version: 10.3.3.0
Spring version: 3.1.1.RELEASE

Please let me know if you need more info. Thanks!

**Comment by hasancelik** [comment]
Thanks for detailed information. We are working on it.

**Comment by hasancelik** [comment]
Could you send to me unit test you wrote? Maybe I can benefit from this test. It is timesaving for us.

**Comment by Neway6655** [comment]
We do not have the unit test, since this issue was occasionally occurred in our test environment.

**Comment by Neway6655** [comment]
Any updates about this issue? Thanks!

**Comment by Neway6655** [comment]
I wrote a unit test for this issue, please help to check:

```java
	@Test
	public void testOutOfSyncMemberListTwoFakeMastersIssue4615()
			throws Exception {
		Config c1 = buildConfig(false);
		Config c2 = buildConfig(false);
		Config c3 = buildConfig(false);

		c1.getNetworkConfig().setPort(45701);
		c2.getNetworkConfig().setPort(45702);
		c3.getNetworkConfig().setPort(45703);

		List<String> allMembers = Arrays
				.asList("127.0.0.1:45701, 127.0.0.1:45702, 127.0.0.1:45703");
		c1.getNetworkConfig().getJoin().getTcpIpConfig().setMembers(allMembers);
		c2.getNetworkConfig().getJoin().getTcpIpConfig().setMembers(allMembers);
		c3.getNetworkConfig().getJoin().getTcpIpConfig().setMembers(allMembers);

		final HazelcastInstance h1 = Hazelcast.newHazelcastInstance(c1);
		final HazelcastInstance h2 = Hazelcast.newHazelcastInstance(c2);
		final HazelcastInstance h3 = Hazelcast.newHazelcastInstance(c3);

		final MemberImpl m1 = (MemberImpl) h1.getCluster().getLocalMember();
		final MemberImpl m2 = (MemberImpl) h2.getCluster().getLocalMember();
		final MemberImpl m3 = (MemberImpl) h3.getCluster().getLocalMember();

		// All three nodes join into one cluster
		assertEquals(3, h1.getCluster().getMembers().size());
		assertEquals(3, h2.getCluster().getMembers().size());
		assertEquals(3, h3.getCluster().getMembers().size());

		final Node n1 = TestUtil.getNode(h1);

		n1.clusterManager.enqueueAndWait(new Processable() {
			public void process() {

				// Simulates node1 getting an out of order member list. That
				// causes node1 to think node2 is the master.
				List<MemberInfo> members = new ArrayList<MemberInfo>();
				members.add(new MemberInfo(m2.getAddress(), m2.getNodeType(),
						m2.getUuid()));
				members.add(new MemberInfo(m1.getAddress(), m1.getNodeType(),
						m1.getUuid()));
				n1.clusterManager.updateMembers(members);
				n1.setMasterAddress(m2.getAddress());
			}
		}, 5);

		// Give the cluster some time to figure things out. The merge and
		// heartbeat code should have kicked in by this point
		Thread.sleep(30 * 1000);

		System.out.println("n1's master: " + n1.getMasterAddress());
		System.out.println("n2's master: "
				+ TestUtil.getNode(h2).getMasterAddress());

		assertEquals(m1, h1.getCluster().getMembers().iterator().next());
		assertEquals(m1, h2.getCluster().getMembers().iterator().next());
		assertEquals(m1, h3.getCluster().getMembers().iterator().next());

		assertEquals(3, h1.getCluster().getMembers().size());
		assertEquals(3, h2.getCluster().getMembers().size());
		assertEquals(3, h3.getCluster().getMembers().size());
	}
```

Thanks!

**Comment by Neway6655** [comment]
@hasancelik I have wrote a unit test for this issue, could you help to have a check, thanks a lot!

**Comment by hasancelik** [comment]
Thanks for unit test. We will solve this issue ASAP.

**Comment by enesakar** [comment]
Closing the issue. Can you check if issue exists in 3.x versions?

**Comment by Neway6655** [comment]
Yes, I have checked it in 3.3.5 version before, it was passed. 
Close it.
