### ISSUE TITLE
MapLoaderLifecycleSupport init method not called for MapLoader

### ISSUE THREAD

**Issue by rajkumarsrikanth** [hazelcast/hazelcast#4623]
Hi
If we have a MapLoader implementation that implements MapLoaderLifecyleSupport interface, the init method is not invoked.

Hazelcast Version Used 3.4
Spring Version 4.1.4
Jdk 7 Update 75

public class Main {

	public static void main(String[] args) {
		ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(
				"spring.xml");
		HazelcastInstance hazelcastServer = context
				.getBean(HazelcastInstance.class);
		IMap<Integer, String> sampleMap;
		sampleMap = hazelcastServer.getMap("SAMPLE");
		String value = sampleMap.get(1);
		System.out.println(value);
		context.close();
	}
}

@Component("sampleMapLoader")
public class SampleMapLoader implements MapLoader<Integer, String>,
		MapLoaderLifecycleSupport {

	private static final Logger LOGGER = Logger
			.getLogger(SampleMapLoader.class);

	@Override
	public String load(Integer key) {
		String value = String.valueOf(key);
		return value;
	}

	@Override
	public Map<Integer, String> loadAll(Collection<Integer> keys) {
		Map<Integer, String> valueMap = new HashMap<Integer, String>();
		for (Integer key : keys) {
			valueMap.put(key, load(key));
		}
		return valueMap;
	}

	@Override
	public Set<Integer> loadAllKeys() {
		Set<Integer> keySet = new HashSet<Integer>();
		for (int i = 0; i < 10; i++) {
			keySet.add(i);
		}
		return keySet;
	}

	@Override
	public void init(HazelcastInstance hazelcastInstance,
			Properties properties, String mapName) {
		LOGGER.info("init method called");
	}

	@Override
	public void destroy() {
		LOGGER.info("destroy method called");
	}
}

spring.xml

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:tx="http://www.springframework.org/schema/tx" xmlns:task="http://www.springframework.org/schema/task"
	xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
						http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.1.xsd
						http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.1.xsd
						http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-4.1.xsd
						http://www.springframework.org/schema/task http://www.springframework.org/schema/task/spring-task-4.1.xsd
						http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.4.xsd">

	<context:component-scan base-package="hazelcastsimple" />
	<context:annotation-config />

	<hz:hazelcast id="hazelcastServer">
		<hz:config>
			<hz:properties>
				<hz:property name="hazelcast.logging.type">log4j</hz:property>
			</hz:properties>
			<hz:network port="5701" port-auto-increment="true">
				<hz:join>
					<hz:multicast enabled="false" />
					<hz:tcp-ip>
						<hz:members>localhost</hz:members>
					</hz:tcp-ip>
				</hz:join>
			</hz:network>
			<hz:map name="SAMPLE">
				<hz:map-store enabled="true" implementation="sampleMapLoader"
					write-delay-seconds="0" initial-mode="EAGER" />
			</hz:map>
		</hz:config>
	</hz:hazelcast>
</beans>

**Comment by ajermakovics** [comment]
Thanks for reporting. Interestingly enough we have a fix already  https://github.com/hazelcast/hazelcast/pull/4488
