### ISSUE TITLE
3rd Party License (minimal-json) needs to be included into the release builds

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#4625]
The MIT License of the embedded minimal-json dependency (shaded dependency) needs to be included into the license folder of the zip/tar archives as well as it needs to be added to licensing mentions.

**Comment by noctarius** [comment]
*ping* this is important! currently we're breaking the MIT license agreement, can somebody please look into this!

**Comment by eminn** [comment]
License file added via bed63ba644417d50251ed7df5f4e59e585c8af66
