### ISSUE TITLE
Factory Id's of DataSerializerHook's should be taken from a single place

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#4626]
Currently, `DataSerializerHook` implementations use factory id's as hard-coded values such as

``` java
public final class MapDataSerializerHook implements DataSerializerHook {

    public static final int F_ID = FactoryIdHelper.getFactoryId(FactoryIdHelper.MAP_DS_FACTORY, -10);

    ...

}
```

This usage may cause collision factory id usages between different `DataSerializerHook` implementations. So it can be good such as a constant interface like `DataSerializerHookConstants` and all factory id's are registered to here and taken from here as constant.

``` java
public interface DataSerializerHookConstants {

    ...
    int MAP_DS_FACTORY_ID = -10;
    ...

}
```

**Comment by gurbuzali** [comment]
:+1:

**Comment by pveentjer** [comment]
+1 Current approach is fragile

**Comment by pveentjer** [comment]
I fixed this issue quite some time ago. See FactoryIdHelper. So I'm going to close this ticket.
