### ISSUE TITLE
[TEST-FAILURE] TxnMultiMapTest.testListener

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#4640]
```
Failed tests: 
  TxnMultiMapTest.testListener:165 expected:<2> but was:<0>
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/11938/

Was reproducible by removing the `Thread.sleep(100);` and repeating the test with `@Repeat`. Maybe the hardcoded sleep time isn't sufficient sometimes. Should we change this to `assertTrueEventually`?

**Comment by eminn** [comment]
Even though I removed the sleep, I couldn't be able to reproduce it. Is there any other setting that you've used to reproduce the issue. I've made more than 100 local runs, no success.

**Comment by Donnerbart** [comment]
Hmm, in one run I changed the assert order (first check remove, than put). But I got just I error in ~2500 runs. So maybe the cluster needs some additional load (occupied threads, hickup in the vm builder cloud) to fail.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/497/com.hazelcast$hazelcast/testReport/com.hazelcast.multimap/TxnMultiMapTest/testListener/
