### ISSUE TITLE
Hazelcast Shutdown Hook calls terminate() instead of shutdown()

### ISSUE THREAD

**Issue by jeffreybolle** [hazelcast/hazelcast#4648]
The default behaviour of a Hazelcast instance is to register a JVM shutdown hook that calls terminate()  on that instance.

Calling terminate() causes Hazelcast to forcibly shutdown the instance without ensuring that the data on the node being shutdown has finished syncing to the remaining nodes in the cluster.

I would argue that the default behaviour should be to call shutdown() which cleanly shuts down the Hazelcast instance and waits until all data has finished syncing to other nodes.

I am more than happy to submit a patch for this issue.

**Comment by eminn** [comment]
Hi @jeffreybolle,
Your suggestion seems reasonable, instead of changing the default behavior, we can introduce an a boolean GroupProperty [1] which is named like `hazelcast.shutdownhook.terminate` with a default value of `true`, that controls the behavior of the shutdown hook. If set to true, shutdown hook will terminate the instance, if set to false, instance will be shutdown gracefully.

I'd be glad if you submit a patch for that.


[1] https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/instance/GroupProperties.java

**Comment by jeffreybolle** [comment]
Hi @eminn,

Your solution sounds sensible if you want to maintain backwards compatibility for existing users.  However I think it would be a good idea to ensure that the default behaviour of terminating without waiting for the cluster to be in a safe state is well documented because it is not what most users would expect.

Thanks,
Jeffrey

**Comment by eminn** [comment]
Hi @jeffreybolle ,

Documentation update is added to the reference manual via 1fcb0aa65c92c0b455286ff3fff9405a29571d3e . Now, I'd be grateful if you introduce aforementioned system property to make shutdown behavior, in the shutdown hook, configurable.

**Comment by nc2it** [comment]
i'm facing some interesting scenario here. my application running on the server which is dependent on hazelcast (that runs as node). when i do hot deployment (via jenkis).  this new build creating new node and old node is not shutting down. means it is creating multiple nodes on the same machine.

**Comment by rehevkor5** [comment]
Just to be clear: the stop.sh that's included in the distribution does not perform a clean shutdown unless you add a shutdown hook that calls eg. `Hazelcast.shutdownAll();` correct? The distro should set a better example!

**Comment by cyriljoui** [comment]
Hi!

I agree with @eminn , it is a real problem to terminate hazelcast node by default.
In my case we've got some trouble because of this!

Do you have some news about this issue?

Thank you

**Comment by jerrinot** [comment]
I've been thinking a bit about this and I am not sure whether calling `shutdown()` instead `terminate()` from the shutdown hook is a good idea. 

Graceful shutdown is potentially a long process as it may involve data migrations, etc. 
JMV shutdown hooks should be [quick](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)) 

The shutdown hook should be treated as the last-resort option. A healthy application should call Hazelcast `shutdown()` as the part of it's exit procedure / undeployment. It should not rely on JVM shutdown hooks.

**Comment by jerrinot** [comment]
after discussion with @mdogan I'm ok with adding a property to control the shutdown hook behaviour. 

I still think relying on the shutdown hook is not a good idea, but having this behavior configurable may work for some.

**Comment by jerrinot** [comment]
@jeffreybolle: in the latest master you can use a [property](https://github.com/hazelcast/hazelcast/pull/9359/files#diff-62a908b694d7ccb15b3348e6751b58f4R275) to initiate graceful shutdown from the JVM shutdown hookl
