### ISSUE TITLE
[TEST-FAILURE] NearCacheTest.testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4656]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/450/com.hazelcast$hazelcast/testReport/com.hazelcast.map.nearcache/NearCacheTest/testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/457/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testNearCacheInvalidation_WithRandom_whenMaxSizeExceeded/

**Comment by ahmetmircik** [comment]
My previous fix had typo this commit should fix it https://github.com/hazelcast/hazelcast/commit/d6580243103d3cf7fd0c04260e96b1cd886c0fdc
