### ISSUE TITLE
ReplicatedMap size should return 0 on removed keys

### ISSUE THREAD

**Issue by sergiocard** [hazelcast/hazelcast#4666]
following test fails, size() returns 1:

    @Test
    public void testContainsKey_returnsFalse_onRemovedKeys() throws Exception {
        HazelcastInstance node = createHazelcastInstance();
        ReplicatedMap<Integer, Integer> map = node.getReplicatedMap("default");
        map.put(1,Integer.MAX_VALUE);
        map.remove(1);

        assertTrue(map.size() == 0);
    }

**Comment by eminn** [comment]
Thanks for the report.

**Comment by sergiocard** [comment]
ok, thanks to you
