### ISSUE TITLE
Memory Distribution Imbalance (Possible Memory leak?)

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#4687]
Reproduce steps...

(1) Start one hazelcast cluster member. -Xmx3G -Xmx3G -XX:-UseConcMarkSweepGC
(2) Start a client and prime one million entries of a DataSerializable object containing 14 longs, 1 Double, 1 List<String> with ~ 20 entries.  I don't believe however this is the cause, you could maybe try with primitives.  The Key is a Long
(3) Use default map config (so backup = 1)
(4) Now start a second cluster member wait for migration to complete.  Perform full GC and observe heap size. Both should be roughly same.
(5) Now add 3rd member, wait for migration to complete. Perform full GC, memory should be less than first two.
(6) Now add 4th member, wait for migration to complete. Perform full GC, memory will be less than 3rd and considerable less than members 1 & 2.

On my laptop the retained member after full GC at end of the incremental starts was :-
Member 1 : 950mb
Member 2 : 950mb
Member 3 : 750mb
Member 4 : 650mb

I performed heap dumps on Member 1 and Member 4 and noted that Member 1 (oldest) had 1.4 million com.hazelcast.nio.serialization.DefaultData entries and Member 4(youngest) had 989,000 entries. Examining Management Centre shows an even distribution of Map entries.

I tried this test again but with backups=0, started one member and primed, then added 2,3,4 members incrementally.  The memory was evenly balanced, so it appears there might be an issue with setting backups to 1 and then starting with 1 member priming a large dataset and then incrementally adding members.

**Comment by gurbuzali** [comment]
version ?

**Comment by dbrimley** [comment]
3.4.1

-- Sent from my iPhone

**Comment by mdogan** [comment]
My initial finding is that, partition distributions seem correct (we already have several tests for that). But first nodes contain more than expected map backup data which looks like a memory leak. 

Even when 4th node is started, 3rd one contains more than expected backup (which is still lower than data hold on initial two nodes).

**Comment by mdogan** [comment]
Here is the sample result, 4 nodes, started one-by-one, `1000000` entries, 24 partitions:

Node1:
```
Owned-Entries: 249556, Backup-Entries: 499748
Owned-Partitions: 6, Backup-Partitions: 18
```

Node2:
```
Owned-Entries: 249920, Backup-Entries: 500252
Owned-Partitions: 6, Backup-Partitions: 18
```

Node3:
```
Owned-Entries: 250320, Backup-Entries: 333554
Owned-Partitions: 6, Backup-Partitions: 18
```

Node4:
```
Owned-Entries: 250204, Backup-Entries: 249678
Owned-Partitions: 6, Backup-Partitions: 18
```

**Comment by mdogan** [comment]
Changed test to gather more detailed entry counts. Each node prints its owned entry count per-replica...

After 3rd node is up and sync, state is like following:
*Node1*: `[332981, 333263, 166485, 0, 0, 0, 0]`
*Node2*: `[333111, 333183, 167069, 0, 0, 0, 0]`
*Node3*: `[333908, 333554, 0, 0, 0, 0, 0]`

After 4th node is started:
*Node1*: `[249556, 250214, 166485, 83049, 0, 0, 0]`
*Node2*: `[249920, 249848, 83425, 166979, 0, 0, 0]`
*Node3*: `[250320, 250260, 0, 83294, 0, 0, 0]`
*Node4*: `[250204, 249678, 0, 0, 0, 0, 0]`

This clearly show backups are leaking.

**Comment by bwzhang2011** [comment]
@mdogan, how does this going on ? backup potential memory leak resolved ?

**Comment by bwzhang2011** [comment]
@mdogan, well done. here comes my doubt,  @dbrimley, does 3.5 snapshot has the same problem (need to be merged like such patch)
