### ISSUE TITLE
Client destroys all connections when a reconnection happens

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#4692]
When client's connected node is shutdown, client reconnects to another node in the cluster, at this time after reconnection is  completed, while trying to clean resources of the old node, client sends an operation to all nodes in the cluster to destroy all connections to itself. This causes unnecessary reconnections and operation retries.

**Comment by pveentjer** [comment]
@eminn @gurbuzali is this ticket still open? And is it only an issue with the old client or also with the new one?

**Comment by sancar** [comment]
@pveentjer Logic behind the implementation did not change during this development. What is there still there. And Emin and me look at this issue together, and could not find the actual problem behind the issue. In short, It needs some more work.

**Comment by mesutcelik** [comment]
that seems fixed after this test passing #4647
