### ISSUE TITLE
[TEST-FAILURE] JoinStressTest.testMulticastJoinWithManyNodesMultipleGroups

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4697]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/403/testReport/junit/com.hazelcast.cluster/JoinStressTest/testMulticastJoinWithManyNodesMultipleGroups/

**Comment by muratayan** [comment]
I was able to reproduce the issue both on 'master' and 'maintenance-3.x' after repeating the test ~45 times. Now trying to find what causes that.

**Comment by muratayan** [comment]
Changing multicastConfig.setMulticastTimeoutSeconds(5) to multicastConfig.setMulticastTimeoutSeconds(15) in initNetworkConfig method seems to be solving the problem. 

Tested 100 times, all passed.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/409/testReport/junit/com.hazelcast.cluster/JoinStressTest/testMulticastJoinWithManyNodesMultipleGroups/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/423/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/JoinStressTest/testMulticastJoinWithManyNodesMultipleGroups/

**Comment by mesutcelik** [comment]
no recent failure. closing
