### ISSUE TITLE
eviction-policy and time-to-live and idle-time for multimap

### ISSUE THREAD

**Issue by hazelcast** [hazelcast/hazelcast#47]
<b>What steps will reproduce the problem?</b>
1. use multimap and try to use &quot;eviction-policy&quot; or &quot;max-idle&quot; or &quot;time-to-live&quot;
2. these setting are not being acted upon.

<b>What is the expected output? What do you see instead?</b>
These settings are being supported for maps and since multimap is based on map, the behavior should be consistent.

<b>What version of the product are you using? On what operating system?</b>
1.9.3, all supported OS's.

<p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=577</p><hr/><h2>earlier comments</h2>
<p><strong>lasagni said, at 2011-11-30T08:56:08.000Z:</strong></p>

<p>It is not trivial what the implementation should be.

For my use case I would like every single entry to have an own time to live (or idle time). To me this looks like an intuitive solution.

Another possible implementation could be to associate the time to live (or idle time) with the key. In this case all entries with this key would be removed when the time to live of the oldest entry with the same key expires.
</p><p><strong>dousti said, at 2011-12-01T11:34:38.000Z:</strong></p>

<p>The crux of the matter is consistency.  "eviction-policy" and "max-idle" and "time-to-live" with the same (consistent) interpretation for both maps and multimaps. We are not talking about specific use cases. The TTL in a map applies uniformly to all the entries; the same should be supported for multimap, ie, the TTL expires and that particular entry would be removed from the multimap, not all the entries with the same key.</p><p><strong>lasagni said, at 2011-12-03T21:49:31.000Z:</strong></p>

<p>The question is: is it a map of bags or just a bag with an index. Anyway having the configurable settings have any effect would be fine ;-)</p>

**Comment by jdanwmal** [comment]
This is also a requirement for a large project and I am working on. I have implemented some custom eviction mechanism but it's not very efficient, as I do not really have the entry age for an LRU implementation. Any plans to add this soon?

**Comment by PieperCH** [comment]
Any news plans for this feature? Do we still need to iterate through all entries manualy to evict the oldest ones?

**Comment by MeYoGui** [comment]
We also need this feature... Any progress on this ?

**Comment by Amocode** [comment]
Hello,
Did you manage to progress on this feature ?
Is there another way of setting a TTL for a Multimap, I tried by creating a custom Config of the HZ instance and by creating a MultiMap with this Config.

**Comment by doctorpangloss** [comment]
Yep, definitely interested in it too

**Comment by kirill133** [comment]
Interested too - this will make our code look better and work safer.

Currently we are using additional IMap with TTL and the same key.
Cleaning MultiMap happens on IMap entry eviction.

But as we are also using Hazelcast client mode we have a problem when all clients are down 
- the event is never triggered and MultiMap contains orphan entries.

**Comment by eanbiso** [comment]
Hi, is there any progress on this issue? Will it be possible to enable TTL and eviction policies for MultiMap too?
Many thanks
