### ISSUE TITLE
Add default property to xml configuration

### ISSUE THREAD

**Issue by antonlisovenko** [hazelcast/hazelcast#4713]
Hi.

Spring has the default value configuration in it:
${my.server.port:defaultValue}
This is very convenient for creation of library spring configuration that is given to different clients: they do not need to specify the property each time, but can override the property in case they need

I have the hz client configuration that is spread through different clients:

```xml
            <hz:network connection-attempt-limit="50"
                        connection-attempt-period="5000"
                        connection-timeout="1000"
                        redo-operation="true">
                <hz:member>
                    <!-- Format: domain_name/ip[:port] -->
                    ${judgements.hz.server.address}
                </hz:member>
            </hz:network>
```

most of them need to wait for long and endure server restarts as they are batch offline processes. But there is UI client that should fail fast in case hz server is not available and avoid long hangs of page. That's why I could create something of this kind:

```xml
            <hz:network connection-attempt-limit="${attempts.number:50}"
                        connection-attempt-period="${attempts.period:5000}"
                        connection-timeout="1000"
                        redo-operation="true">
                <hz:member>
                    <!-- Format: domain_name/ip[:port] -->
                    ${judgements.hz.server.address}
                </hz:member>
            </hz:network>
```

and will not have to set connection parameters for all clients specifically, but only for one of them (UI)

Is this possible? Seems this should not be very difficult as Hz already supports properties.

**Comment by emre-aydin** [comment]
This has been implemented with Variable Replacers and available in HZ 3.10. See the relevant section in documentation: http://docs.hazelcast.org/docs/3.10/manual/html-single/index.html#propertyreplacer - AFAIK it doesn't support default values but you can easily extend `com.hazelcast.config.replacer.PropertyReplacer` and configure it to have default values.
