### ISSUE TITLE
WebFilter RequestWrapper.getSession() returns null

### ISSUE THREAD

**Issue by Mircea-Exswap** [hazelcast/hazelcast#4717]
The problem is that sometimes when I try to get a session the returned value is null. Unfortunately I was not able to create a proper test case. 
The reason for this null is when you are getting the **hazelcastSession** from the **session** map, you are returning the value without checking if it is null. The problematic line is here https://github.com/hazelcast/hazelcast/blob/v3.4.1/hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java#L605

**Comment by bilalyasar** [comment]
@Mircea-Exswap can you give some config details? Do you use sticky session enabled mode?

**Comment by Mircea-Exswap** [comment]
@bilalyasar this is the configuration that we are using: 

<hz:instance-name>hazelcastServer</hz:instance-name>
<hz:group name="${cluster.name}" password="${cluster.password}" />
<hz:properties>
    <hz:property name="hazelcast.merge.first.run.delay.seconds">5</hz:property>
    <hz:property name="hazelcast.merge.next.run.delay.seconds">5</hz:property>
    
    <hz:property name="hazelcast.memcache.enabled">false</hz:property>
    <hz:property name="hazelcast.rest.enabled">false</hz:property>
    <hz:property name="hazelcast.socket.bind.any">false</hz:property>
    <hz:property name="hazelcast.wait.seconds.before.join">0</hz:property>
    <hz:property name="hazelcast.version.check.enabled">false</hz:property>
</hz:properties>
<hz:network port="${cluster.defaultPort}">
    <hz:join>
        <hz:multicast enabled="false" />
        <hz:tcp-ip enabled="true">
            <hz:members>${cluster.ip-members}</hz:members>
        </hz:tcp-ip>
    </hz:join>
</hz:network>

**Comment by Mircea-Exswap** [comment]
@bilalyasar Here is the configuration that we use:

```
<hz:instance-name>hazelcastServer</hz:instance-name>
<hz:group name="${cluster.name}" password="${cluster.password}" />
<hz:properties>
    <hz:property name="hazelcast.merge.first.run.delay.seconds">5</hz:property>
    <hz:property name="hazelcast.merge.next.run.delay.seconds">5</hz:property>
    <!-- We don't have memcache -->
    <hz:property name="hazelcast.memcache.enabled">false</hz:property>
    <hz:property name="hazelcast.rest.enabled">false</hz:property>
    <hz:property name="hazelcast.socket.bind.any">false</hz:property>
    <hz:property name="hazelcast.wait.seconds.before.join">0</hz:property>
    <hz:property name="hazelcast.version.check.enabled">false</hz:property>
</hz:properties>
<hz:network port="${cluster.defaultPort}">
    <hz:join>
        <hz:multicast enabled="false" />
        <hz:tcp-ip enabled="true">
            <hz:members>${cluster.ip-members}</hz:members>
        </hz:tcp-ip>
    </hz:join>
</hz:network>
```

**Comment by bilalyasar** [comment]
with 3.5, web filter has new design and many known issues have been fixed.. so i am closing this issue until new report or failure.
