### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetectorBasicTest.testSlowOperationOnGenericOperationThread

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4719]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/538/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/SlowOperationDetectorBasicTest/testSlowOperationOnGenericOperationThread/

**Comment by Donnerbart** [comment]
`SlowOperationDetector` is a new feature from me, I'll have a look ASAP.

It's a complete separate thread/system, so failures should not be critical for other features.

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/pull/4725

**Comment by bilalyasar** [comment]
@Donnerbart 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3055/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowOperationOnGenericOperationThread/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3063/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowOperationOnGenericOperationThread/

**Comment by Donnerbart** [comment]
There's already a fix pending for this :)

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/com.hazelcast$hazelcast/41/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowOperationOnGenericOperationThread/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast/518/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetectorBasicTest/testSlowOperationOnGenericOperationThread/
