### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetector_EntryProcessorTest.testNestedSlowEntryProcessor

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4720]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/538/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/SlowOperationDetector_EntryProcessorTest/testNestedSlowEntryProcessor/

**Comment by Donnerbart** [comment]
`SlowOperationDetector` is a new feature from me, I'll have a look ASAP.

It's a complete separate thread/system, so failures should not be critical for other features.

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/pull/4725
