### ISSUE TITLE
AwsConfig ignores the region when providing AWS endpoint

### ISSUE THREAD

**Issue by bwieliczko** [hazelcast/hazelcast#4731]
In `hazelcast-client.xml`, if we configure `region` but don't provide the `host-header`, the config will provide a default endpoint value of `ec2.amazonaws.com` whereas my expectation is to use the region so the endpoint would be e.g. `ec2.eu-west-1.amazonaws.com`

Is this intentional?

I'm using hazelcast 3.4 but it looks like it's the same in master.

**Comment by mdogan** [comment]
Closed by https://github.com/hazelcast/hazelcast/pull/5774
