### ISSUE TITLE
[TEST-FAILURE] InvocationNetworkSplitTest Failures

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4734]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/746/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/

**Comment by mesutcelik** [comment]
@eminn ,

This one has failed as well. This is another test in the same class.

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/165/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/488/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/167/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/170/testReport/junit/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/467/testReport/junit/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK8/176/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario1/
