### ISSUE TITLE
MapLoaderLifecycleSupport works only on instances of MapStore

### ISSUE THREAD

**Issue by zeratul021** [hazelcast/hazelcast#4763]
Class **BasicMapStoreContext**, method *callLifecycleSupportInit* (line 206 in version 3.4.1) checks whether the (map) store is an instance of **MapLoaderLifecycleSupport**.

I think it would make sense to check for the existence of a map loader as well for the cases where you need read-only map store configuration. Currently I need to implement **MapStore** with empty methods to have the lifecycle supported. This would probably mean adding a *getMapLoader*  to the **MapStoreWrapper** class.

Thanks in advance for a response.

**Comment by ahmetmircik** [comment]
Hi Marek,
Thanks for reporting this, fortunately it is an already fixed issue and will be available in 3.4.2 (i guess release will be available in next week). Please check this issue https://github.com/hazelcast/hazelcast/issues/4623 and  the fix of it https://github.com/hazelcast/hazelcast/pull/4624

**Comment by zeratul021** [comment]
Hey Ahmet,

thanks for prompt response and good news. Sorry for duplicate - apparently searching for "map loader" or "lifecycle" in issue was not enough :/ - will try harder next time.

Cheers.
