### ISSUE TITLE
[TEST-FAILURE] NearCacheTest.testNearCacheInvalidation_WithLFU_whenMaxSizeExceeded

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4765]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/751/com.hazelcast$hazelcast/testReport/com.hazelcast.map.nearcache/NearCacheTest/testNearCacheInvalidation_WithLFU_whenMaxSizeExceeded/

**Comment by ahmetmircik** [comment]
typo fixed https://github.com/hazelcast/hazelcast/commit/3af9c0792b640c4eb629a23025e5218871effc3c
