### ISSUE TITLE
[TEST-FAILURE] ClientMemberAttributeTest.testPresharedAttributes

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4766]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/363/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientMemberAttributeTest/testPresharedAttributes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/496/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientMemberAttributeTest/testPresharedAttributes/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/369/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientMemberAttributeTest/testPresharedAttributes/

**Comment by sancar** [comment]
https://github.com/hazelcast/hazelcast/pull/4769
