### ISSUE TITLE
Native Memory not displayed for IMaps in Management Center

### ISSUE THREAD

**Issue by rajkumarsrikanth** [hazelcast/hazelcast#4767]
Hazelcast Version Used : 3.4.1

We have implemented a MapLoader with in-memory-format as NATIVE. But the usage of the map is not correctly reflected on the Management Center. The management center still shows the native memory used as 0KB.

**Comment by emrahkocaman** [comment]
For `Map` tab, heap cost can only be calculated for a map when map's in-memory format is `BINARY`. 
For `Home` tab, native memory is only shown for JCache impl.
Map support will come in 3.6.

**Comment by mustafaiman** [comment]
Closing it since support will come in 3.6.
