### ISSUE TITLE
[TEST-FAILURE] ClientTxnMapTest.testUnlockAfterRollback

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4771]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client/364/testReport/junit/com.hazelcast.client.txn/ClientTxnMapTest/testUnlockAfterRollback/

**Comment by sancar** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/4769
