### ISSUE TITLE
Native Memory Configuration for Spring Integration

### ISSUE THREAD

**Issue by rajkumarsrikanth** [hazelcast/hazelcast#4772]
Hi Team,

We are using Hazelcast Version 3.4.1.
Currently in this version, we do not have spring tags available to configured Native Memory Configuration.
It will be great if the same configuration will be availed using Spring tags.

**Comment by bwzhang2011** [comment]
+1

**Comment by mesutcelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/5015
