### ISSUE TITLE
[TEST-FAILURE]  jsr107.tck.CachingTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4778]
```
javax.cache.CacheException: Error opening URI [hazelcast]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:89)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:113)
	at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:153)
```
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-maintenance/300/
org.jsr107.tck.CachingTest.getCacheManager_URI
org.jsr107.tck.CachingTest.getCacheManager_nullUriParameter
org.jsr107.tck.CachingTest.cachingProviderGetNonExistentCache
org.jsr107.tck.CachingTest.getCacheManager_defaultURI
org.jsr107.tck.CachingTest.getCacheManager_nonNullProperties
org.jsr107.tck.CachingTest.getCacheManager_nullClassLoader
org.jsr107.tck.CachingTest.getCacheManager_singleton
org.jsr107.tck.CachingTest.getCacheNullValueClass
org.jsr107.tck.CachingTest.cachingProviderGetCache

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/771/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/793/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-maintenance/314/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/825/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-master/881/

**Comment by serkan-ozal** [comment]
I am not sure is this really a JCache issue. As far as I seen from the logs, multicast joiner founds another node on AWS and creates a cluster with this node. Possibly there was another test cluster running on AWS

```
...

INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] Creating MulticastJoiner
Mar 24, 2015 6:56:08 AM com.hazelcast.core.LifecycleService
INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] Address[192.168.0.196]:5701 is STARTING
Mar 24, 2015 6:56:08 AM com.hazelcast.cluster.impl.MulticastJoiner
INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] Trying to join to discovered node: Address[192.168.0.27]:5701
Mar 24, 2015 6:56:08 AM com.hazelcast.nio.tcp.SocketConnector
INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] Connecting to /192.168.0.27:5701, timeout: 0, bind-any: true
Mar 24, 2015 6:56:08 AM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] Established socket connection between /192.168.0.196:39883 and ip-192-168-0-27.ec2.internal/192.168.0.27:5701
Mar 24, 2015 6:56:14 AM com.hazelcast.cluster.ClusterService
INFO: [192.168.0.196]:5701 [dev] [3.5-SNAPSHOT] 

Members [2] {
	Member [192.168.0.27]:5701
	Member [192.168.0.196]:5701 this
}

...
```

**Comment by serkan-ozal** [comment]
With this commit https://github.com/bilalyasar/jsr107tck/commit/46e377730c14ed576530b005dcf113dff5b266a1, TCK tests will run in standalone mode without join. So this should fix the problem. I am closing this issue now. If it fails again, we can reopen it.

**Comment by mesutcelik** [comment]
There are still problems with TCK tests

https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/835/
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/836/

**Comment by serkan-ozal** [comment]
we have applied similar fix to TCK-Client also. Lets wait and see if it will fail or not again.

**Comment by mesutcelik** [comment]
ok. i will reopen if it fails again.

**Comment by mesutcelik** [comment]
@serkan-ozal ,

Can you please have a look?
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/840/

**Comment by serkan-ozal** [comment]
@mesutcelik I have seen this failure and will talk with @bilalyasar. The problem is that `CachingProviderClassLoaderTest` and `CachingProviderTest` tests are not dependent to `HazelcastTestSupport` class. So Hazelcast instance is not created since `HazelcastTestSupport` class is not loaded by classloader (since not touched yet) and so its static initializer is not called. I will come up a better solution instead of relying of `HazelcastTestSupport` class static initializer.

**Comment by serkan-ozal** [comment]
BTW, this also explains why this problem occurs randomly.

**Comment by mesutcelik** [comment]
Ok good. 
What about this one which has failed just now?
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/843/

**Comment by serkan-ozal** [comment]
As seen from the log, `CachingTest` is the first test run and it has no dependency to `TestSupport` class. So node is not created and client couldn't connect to anywhere

**Comment by serkan-ozal** [comment]
I think, we need a startup listener (maybe for surefire plugin) that is called before all tests so we can move instance creation code from `TestSupport` class to here. So we don't touch TCK test codes.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/javax.cache$specific-implementation-tester/845/testReport/junit/org.jsr107.tck.integration/CacheLoaderWithoutReadThroughTest/shouldLoadSingleExistingEntryUsingLoadAll/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-maintenance/339/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/854/

**Comment by serkan-ozal** [comment]
On my local, seems that this works. I will talk this with @bilalyasar 

in `pom.xml` of `cache-tests` module

``` xml
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        ...
                        <configuration>
                            <properties>
                                <property>
                                    <name>listener</name>
                                    <value>org.jsr107.tck.testutil.TCKTestListener</value>
                                </property>
                            </properties>
                           ...
                        </configuration>
                    </plugin>
                </plugins>
            </build>
```

and `TCKTestListener` to create a instance at the startup of the tests for client instead of creating at `org.jsr107.tck.testutil.TestSupport` since there is no guarantee that `org.jsr107.tck.testutil.TestSupport` class is loaded (and called its static initializer) by classloader before all of the tests running. But with `maven-surefire` plugin listener support, `TCKTestListener` class is created before tests run.

``` java
package org.jsr107.tck.testutil;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import org.junit.runner.notification.RunListener;

public class TCKTestListener extends RunListener {

    static {
        Config config = new Config();
        config.getNetworkConfig().getJoin().getAwsConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        Hazelcast.newHazelcastInstance(config);

        System.out.println("Hazelcast instance created ...");
    }

}
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/856/
@serkan-ozal, i will make necessary changes today.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/890/

**Comment by bilalyasar** [comment]
i updated repos, closing this issue for now. thanks @serkan-ozal for your suggestion.

**Comment by serkan-ozal** [comment]
We have talked with @bilalyasar, and will add listener for surefire plugin to `implementation-tester/specific-implementation-tester` module instead of `cache-tests` module
