### ISSUE TITLE
Consul Resolver

### ISSUE THREAD

**Issue by decoomanj** [hazelcast/hazelcast#4789]
I've created an IP-resolver for Consul. How could I contribute to your project?

**Comment by bwzhang2011** [comment]
maybe you could ask or leave some msg to @noctarius for more details.

**Comment by Donnerbart** [comment]
We have a new initiative for community contributions, the Hazelcast Incubator. Please have a look a our blog: http://blog.hazelcast.com/2015/02/27/the-hazelcast-incubator/

**Comment by vgoldin** [comment]
@decoomanj could you share your project on your github meanwhile? very interested to check it out.

**Comment by mesutcelik** [comment]
I think you have already contacted @noctarius . Thanks for contribution.

**Comment by noctarius** [comment]
Hey @vgoldin feel free to contact me add at any time :)

**Comment by decoomanj** [comment]
@vgoldin Check out https://github.com/decoomanj/hazelcast and  https://github.com/decoomanj/hazelcast-consul. You must recompile hazelcast due to the current plugin-problematics. I will enhance the code in the coming week(s), but it is running in our environment without problem. You can publish your service-adress to consul, and then it works without problem.

**Comment by noctarius** [comment]
The Hazelcast Incubator Community is already working on that problem :) https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI

**Comment by decoomanj** [comment]
Working on it ;-)
