### ISSUE TITLE
unpredictable warning when initializing with Config    

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#4790]
when upgraded to hz3.5 snapshot for testing, my project has got some warning message like this:
No configuration found for hazelcastmq.txn-topic, using default config!
while tracing, I noticed that such originated from Config class for the method of  'private <T> T lookupByPattern(Map<String, T> configPatterns, String itemName)' at line 901.

But I could not know that why it would induce the warning message (both would be ok under 3.4.x version).
so I dare say it should do some enhancement.

**Comment by pveentjer** [comment]
It is a warning that no concrete configuration was found, so the system is using a default. This log message should not have been logged under the warning level imho but on info or even debug. This 'warning' is new since HZ 3.5

**Comment by bwzhang2011** [comment]
@pveentjer, thanks for review. I set my hazelcast cluster configuration through hazelcast-spring but it is ok since it swithced to hazelcast 3.4+ but the warning as you described is in hz3.5. and I don't quite understand why concrete configuration is needed for wild card is support in hazelcast configuration

**Comment by pveentjer** [comment]
I think you can ignore it safely. Imho warning is not a warning, but just a debugging message.

**Comment by Donnerbart** [comment]
Issue is resolved and will not be part of the 3.5 release.
