### ISSUE TITLE
Unable to unzip/untar downloaded hazelcast 3.4.1 file

### ISSUE THREAD

**Issue by Belkacem** [hazelcast/hazelcast#4793]
I'm trying to unzip hazelcast 3.4.1 7zip tells me that the file is corrupted.

**Comment by gAmUssA** [comment]
@Belkacem Could you provide full link from where you downloaded Hazelcast?

**Comment by gAmUssA** [comment]
@Belkacem I can't reproduce this problem with `hazelcast-3.4.1.zip` downloaded from `http://hazelcast.org/download/`. Used `7zip` and `unzip`.

`7z x hazelcast-3.4.1.zip`

![1 apple localhost zsh 2015-03-13 14-51-31](https://cloud.githubusercontent.com/assets/433085/6645174/99af3564-c990-11e4-9ecc-177478ad5b90.png)

**Comment by Belkacem** [comment]
Thanks for the quick reply, our company's proxy is doing something nasty with the file, i just made a sham checksum of the file at home it's not the same I retrieve at work behind the company's proxy. 
I'll find a way to transfer it.
Sorry for the false issue.
Cheers
