### ISSUE TITLE
Distributed read/write lock support

### ISSUE THREAD

**Issue by laurentvaills** [hazelcast/hazelcast#481]
Hello,

We have a question regarding distributed lock support.
Hazelcast provides distributed exclusive lock but it seems that distributed shared lock is not supported... 
We would like to use Hazelcast in our open source project but we need to allow concurrent access to multiple threads for reading a shared resource and restricting access to a single thread for writing this shared resource.

We have tried a workaround by using 2 distributed semaphores to perform the distributed read/write lock but it doesn't work in case of a cluster member's death (tokens acquired on a semaphore by this node are never released). So the other nodes can always stay blocked. 
Hazelcast lock implementation behaves just like java.util.concurrent.lock.ReentrantLock. Any chance to have same behaviour than java.util.concurrent.lock.ReentrantReadWriteLock ?
Thanks

**Comment by noctarius** [comment]
Is this still valid? I don't think so :)

**Comment by laurentvaills** [comment]
I don't think so too.

**Comment by wenerme** [comment]
Dose any one still want a rw lock except me ?

**Comment by adobni** [comment]
Not having read write locks seems to be causing performance problems for some applications.

**Comment by Petikoch** [comment]
I'd like to have a `ReadWriteLock` implementation on top of Hazelcast
