### ISSUE TITLE
Documentation - No query example

### ISSUE THREAD

**Issue by alexandrnikitin** [hazelcast/hazelcast#4811]
There's no query example in "9. Distributed Query" section "9.1.2 Employee Map Query Example" paragraph. [Link to the page](http://docs.hazelcast.org/docs/3.4/manual/html/distributedquery.html)

**Comment by alexandrnikitin** [comment]
Found it. :smiley:

**Comment by Serdaro** [comment]
:)

**Comment by alexandrnikitin** [comment]
got it, just keep reading :blush:
