### ISSUE TITLE
Management Center - Internet Explorer 9 Compatability Issues

### ISSUE THREAD

**Issue by rajkumarsrikanth** [hazelcast/hazelcast#4812]
Hi Team,

The Management Center shipped with Hazelcast 3.4 version has compatability issues with Internet Explorer 9 and 10. The screen freezes right after selecting the hazelcast group. I believe there is some java script error which gets ignored in chrome or Firefox.

**Comment by mustafaiman** [comment]
I tested this with both IE9 and IE10 on windows 7. I tested with Hazelcast `3.4`, `3.4.1`, `3.5.5` and `3.6-RC1`. I used two cluster groups with two nodes at each test. I still could not reproduce the freeze. Do you still experience the issue?

**Comment by pveentjer** [comment]
Closing the ticket due to lack of response + not being able to reproduce the problem. Also it is an old ticket.
