### ISSUE TITLE
Hazelcast management center

### ISSUE THREAD

**Issue by Belkacem** [hazelcast/hazelcast#4826]
Hi,
I have a little issue in management center when there's lot of topics open in hazelcast the maps view can't be unfolded.
Cheers
![part of management center](https://cloud.githubusercontent.com/assets/419224/6693132/3da6a268-ccd1-11e4-9efc-05eaee9c579c.png)

**Comment by emrahkocaman** [comment]
Hi @Belkacem ,

Could please share 
-Mancenter version
-Your browser
-Approximate number of topics to reproduce this behaviour?

**Comment by Belkacem** [comment]
Hi,
Browsers and version :
 -Chrome : latest
 - Firefox : 36
Mancenter version : 3.4
Number of topics : +300 (approximately)
Cheers

**Comment by Belkacem** [comment]
Hi,
Were you able to reproduce the bug?
Thanks in advance.

**Comment by Belkacem** [comment]
Hi,
Did you reproduce the Bug?
I'm rolling back to 3.3.5 this bug is very annoying.
Thanks.

**Comment by emrahkocaman** [comment]
Hi @Belkacem ,
Unfortunately not, I've tried with 500 topics and no luck so far. (With latest Chrome and Firefox 36).

**Comment by Belkacem** [comment]
The Topic section unfold normally, the problem is that when you have maps and Multi maps, when you have a lot of topics:
The multimaps and topic sections unfold normally, but the Map section is stuck.

**Comment by Belkacem** [comment]
@emrahkocaman 
It behaves as if there were no maps in the cluster.

**Comment by emrahkocaman** [comment]
I'll check that.

**Comment by Belkacem** [comment]
Hi @emrahkocaman 
There's something I think worth mentioning, when I start my nodes at firs before the topics are created, the maps are visible and the maps section unfolds normally and contains all the distributed maps in the cluster, but when the Topics are created the maps disappear, here's what happens in the maps that have been opened in the management console: 
![image](https://cloud.githubusercontent.com/assets/419224/7155033/ba76a536-e35b-11e4-890a-c33a10b73694.png)

**Comment by Belkacem** [comment]
@emrahkocaman FYI the maps do exist in the cluster, just they're not monitored anymore in the management console.

**Comment by emrahkocaman** [comment]
Hi @Belkacem , now I got it.
Number of visible data structures is limited, it's 100 by default. 
You need to increase this limit on the Hazelcast side. 
There is group propery named "hazelcast.mc.max.visible.instance.count" for this purpose.

**Comment by Belkacem** [comment]
It's working now, the problem is that in the previous version when the instance count is reached, the new instances are ignored, but since 3.4 the older ones are discarded, this behaviour change hasn't been notified in the release notes.
Thanks !
