### ISSUE TITLE
Hazelcast-V3.4.1: provide a minimum key-value store implementation with no features (eviction, stats etc) but with less memory overhead

### ISSUE THREAD

**Issue by arghyakusumdas** [hazelcast/hazelcast#4829]
It will be a nice feature for many memory intensive workload.

**Comment by dsukhoroslov** [comment]
Just did it for internal purpose on my project. If you're interested I'll share the code (extremely simple).

**Comment by mdogan** [comment]
Closing in favor of https://github.com/hazelcast/hazelcast/issues/7372
