### ISSUE TITLE
Hazelcast management center

### ISSUE THREAD

**Issue by Belkacem** [hazelcast/hazelcast#4831]
Hi,
I have a little issue in management center when there's lot of opened topics in hazelcast the maps list can't be unfolded.
Cheers
![part of management center](https://cloud.githubusercontent.com/assets/419224/6693132/3da6a268-ccd1-11e4-9efc-05eaee9c579c.png)

**Comment by emrahkocaman** [comment]
Seems like this issue is related with https://github.com/hazelcast/hazelcast/issues/4826
let's close this one continue discussion on the https://github.com/hazelcast/hazelcast/issues/4826
