### ISSUE TITLE
HazelcastCacheManager#getCacheNames() should not be lazy

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#4844]
Here is a test that showcases the problem

```java
@Test
public void getCacheNamesShouldNotBeLazy() {
	Config c = new Config();
	c.addMapConfig(new MapConfig("test"));
	HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance(c);
	HazelcastCacheManager cacheManager = new HazelcastCacheManager(hazelcast);

	System.out.println("Before getCache --> " + cacheManager.getCacheNames());
	cacheManager.getCache("test");
	System.out.println("After getCache --> " + cacheManager.getCacheNames());
}
````
If you run this, `getCacheNames` returns an empty collection even though a cache with name `test` has been configured.

**Comment by gurbuzali** [comment]
Hi, you are adding a `MapConfig` not `CacheSimpleConfig`.
Below is the correct one:
```
        Config config = new Config();
        CacheSimpleConfig simpleConfig = new CacheSimpleConfig().setName("name");
        config.addCacheConfig(simpleConfig);
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);

        HazelcastServerCachingProvider provider = HazelcastServerCachingProvider.createCachingProvider(instance);
        CacheManager cacheManager = provider.getCacheManager();

        System.out.println("Before getCache --> " + cacheManager.getCacheNames());
        Cache<Object, Object> cache = cacheManager.getCache("name");
        System.out.println("After getCache --> " + cacheManager.getCacheNames());
```
Lazy initialization of the cache can be observed from the test but I'm not sure if this is a bug.
it comes down to the `managed` keyword, since the cache is not created yet Hazelcast does not manage it. `getCache` method simply triggers that creation.

**Comment by snicoll** [comment]
I am not saying it's a bug but it's a bit inconsistent with the other `CacheManager` implementations. If you can expose the caches that you know, you should do so immediately and not wait for the first access. 

`org.springframework.cache.support.AbstractCacheManager` in the Spring Framework code base is an example of what I mean.

Are you saying `MapConfig` is wrong and shouldn't be used? 

In any case, it would be nice if you could align to `AbstractCacheManager` and avoid computing the list of cache names every time the getter is accessed.

**Comment by serkan-ozal** [comment]
Hi @snicoll, 

Currently our Spring cache manager is based on `IMap` implementation and caches are not needed to be defined as static. I mean, if there is a map config for specified cache name, this config is used to create distributed map storage for that cache. Otherwise, a default map is created.

So, lazy cache creation is the result of this behaviour.

**Comment by snicoll** [comment]
Yes, Mesut explained that to me. 

It's a bit unclear what you do in `getCacheNames` you can't do when we create the cache manager. If you don't do anything special, then I'd have a cache set that is empty initially and every time `getCache` is called, you'd add that to that private set. 

If `getCacheNames()` does something smart on the hazelcast instance, I'd argue it should do so asap and then fallback to a private set. In other words, I don't think it's necessary that `getCacheNames()` recompute the whole set every time...

**Comment by serkan-ozal** [comment]
Hi @snicoll, 

As far as I understood, you say that no need to recompute cache names at each `getCache(name)` call by iterating over IMap instances on Hazelcast instance for getting cache names.
Create an initial cache names set at creation of `HazelcastCacheManager` and add each created cache at call of `getCache(name)` method to this private cache names set.

Did I get it right?

Thanks.

**Comment by serkan-ozal** [comment]
Hi @snicoll 
I am closing this ticket now since Hazelcast handles cache as lazy and no need to static cache definition.

Please feel free to reopen this issue if you see another problem.

Regards.

**Comment by snicoll** [comment]
Sorry for the late reply. Yes, your description is how `AbstractCacheManager` works. However, you may have customers relying on the current behaviour (seeing caches as they are being added to the underlying `HazelcastInstance`) so it may be a better idea to leave it like that. My primary concern was performance but I am not sure we should call this method a lot (we don't!). Thanks for the support!
