### ISSUE TITLE
implement IMap.valuesRemove(Predicate)

### ISSUE THREAD

**Issue by uscholz** [hazelcast/hazelcast#486]
IMap offers the method  
|  Collection<V>    values(Predicate predicate) 

If you plan to remove the values matching the predicate, you have to access them twice. That could be avoided by a method 

|  Collection<V>    valuesRemove(Predicate predicate) 

which gets and removes the values in one step. Please implement it.

**Comment by RadoslawOsinski** [comment]
Is there any simmilliar API for com.hazelcast.core.MultiMap?

**Comment by RadoslawOsinski** [comment]
Is there any method similiar to IMap.executeOnEntries(EntryProcessor) for MultiMap? Is it possible to use AbstractEntryProcessor on MultiMap to remove elements? I have tried to cast MultiMap to IMap to use "executeOnEntries" method. But this was a bad idea, because of:

> java.lang.ClassCastException: com.hazelcast.multimap.impl.ObjectMultiMapProxy cannot be cast to com.hazelcast.core.IMap
