### ISSUE TITLE
MapLoaderLifecycleSupport.init not called for MapLoader

### ISSUE THREAD

**Issue by troesler** [hazelcast/hazelcast#4862]
Hi,

I've been running some tests with version 3.4.1 and the MapLoaderLifecycleSupport.init method is not called for the MapLoader interface.  Only when I add the MapStore interface to our persistence class is the init method called.  In previous versions for example 3.3.2, the init method was called for the MapLoader interface.

Regards,
Thomas

**Comment by ajermakovics** [comment]
Hi Thomas,

It's been fixed in #4623 and should be in the upcoming 3.4.2 release.

Thanks for reporting!
