### ISSUE TITLE
Expose statistics for IMap.putMany

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#4868]
Hello team,

Recently, I faced an issues when I can't see the throughput statistics on Management Center when I use `IMap.putMany()`. Issue in ManCenteter repo https://github.com/hazelcast/management-center/issues/159
Apparently, ManCented depends on exposed statistics from IMap.

Is it possible to add this statistics for putMany?

Thanks

**Comment by emrahkocaman** [comment]
Closed by https://github.com/hazelcast/hazelcast/pull/6096
