### ISSUE TITLE
inconsistency between default hazelcast xml and default config object

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4874]
they should be same. and currently they are different. 
example see: #945

**Comment by gurbuzali** [comment]
we can have a unit-test for this, it should be easy to write down

**Comment by jerrinot** [comment]
@bilalyasar: Do you think this is something we should backport into a maintenance release?

**Comment by bilalyasar** [comment]
@jerrinot , i think this should be for 3.6 or 3.6+

**Comment by jerrinot** [comment]
@bilalyasar: I agree, that's why I asked.

**Comment by pveentjer** [comment]
@bilalyasar any update on this item?

**Comment by pveentjer** [comment]
Fixed with this PR:

https://github.com/hazelcast/hazelcast/pull/8123
