### ISSUE TITLE
[TEST-FAILURE] MulticastJoinTest Failures

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4876]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/508/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test_whenDifferentBuildNumber/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/487/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test_whenInterfacesEnabled/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/510/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test_whenDifferentBuildNumber/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/12459/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/2920/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test/

**Comment by serkan-ozal** [comment]
I am not familiar with the content and the test, just a quick look to thread dumps and seems that there are threads from 3 different instances.

```
hz._hzInstance_1438_dev
hz._hzInstance_1437_dev
hz._hzInstance_1418_dev
```

As I understand the test, there must be 2 instance maximum at any time. Seems that there is an extra instance (maybe from previous tests since there is a significant difference between instance sequences 1437/1438 and 1418).

Maybe this can be helpful.

**Comment by eminn** [comment]
I think we need to adopt practice of using random group name per cluster in the tests.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/17/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test_whenDifferentBuildNumber/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/573/testReport/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/520/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3018/com.hazelcast$hazelcast/testReport/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/32/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/211/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test_whenIncompatiblePartitionGroups/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/32/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/537/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/45/com.hazelcast$hazelcast/testReport/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/541/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test_whenIncompatiblePartitionGroups/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3089/testReport/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/45/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster/MulticastJoinTest/test/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/549/testReport/junit/com.hazelcast.cluster/MulticastJoinTest/test_whenInterfacesEnabled/

**Comment by eminn** [comment]
I am closing this issue since this is related to a network isolation problem which is fixed by CloudBees.
