### ISSUE TITLE
[TEST-FAILURE] LockSplitBrainTest.testLockSplitBrain_acquireSameLock

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4877]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/63/com.hazelcast$hazelcast/testReport/com.hazelcast.concurrent.lock/LockSplitBrainTest/testLockSplitBrain_acquireSameLock/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/10/com.hazelcast$hazelcast/testReport/com.hazelcast.concurrent.lock/LockSplitBrainTest/testLockSplitBrain_acquireSameLock/

**Comment by eminn** [comment]
I am closing this issue since this is related to a network isolation problem which is fixed by CloudBees.
