### ISSUE TITLE
New member cannot join cluster

### ISSUE THREAD

**Issue by AlbertHsuD** [hazelcast/hazelcast#4887]
Using the cluster name and cluster password option, a new members cannot join the cluster. After debugging through the code, I found that the new member only receives JoinRequest, and never receives JoinMessage.

In the NodeMulticastListener class, the handleNotActiveOrNotJoined method only receives JoinRequest, and never receives JoinMessage. Therefore, the hostname (IP) never been set to materAddress.

Albert Hsu

**Comment by mdogan** [comment]
This looks like a environment multicast issue. Please check your OS, network etc allow multicast packets.
