### ISSUE TITLE
LockStore not cleared when map is destroyed causing OutOfMemory

### ISSUE THREAD

**Issue by karvind00** [hazelcast/hazelcast#4888]
Hazelcast version:3.4.1
Cluster size:1
Number of the clients:1
Version of Java:1.6_45
OS: Linux version 2.6.32-358.el6.x86_64

In the com.hazelcast.concurrent.lock.LockStoreContainer class when clearLockStore is called the lockStores map entry is not removed.

I have attached screenshot of the heap dump from JVisualVM
![lock_store_heap_dump](https://cloud.githubusercontent.com/assets/11635278/6811251/cef6ec94-d223-11e4-9aa5-d90f6fdc7c9e.PNG)
. Notice how com.hazelcast.spi.DefaultObjectNamespace and  com.hazelcast.concurrent.lock.LockStoreImpl classes hang around even after the map has been removed.

The lockstore objects pile up till the server finally runs out of memory

**Comment by karvind00** [comment]
Added the following change and it fixed the issue for me. Hopefully this will make it to any future releases.

Index: LockStoreContainer.java
===================================================================
--- LockStoreContainer.java	(revision 15013)
+++ LockStoreContainer.java	(working copy)
@@ -57,6 +57,7 @@
         if (lockStore != null) {
             lockStore.clear();
         }
+		lockStores.remove(namespace);
     }
 
     LockStoreImpl getOrCreateLockStore(ObjectNamespace namespace) {

**Comment by dfeist** [comment]
@mdogan Any plans to get this into a release, it's a pretty significant memory leak IMO, given simply creating/destroy maps provokes it.

**Comment by mdogan** [comment]
Sorry @karvind00 & @dfeist. Somehow we missed this report. It's seems to be a memory leak. Thanks for the report.
