### ISSUE TITLE
[TEST-FAILURE] ClientSemaphoreThreadedTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4892]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK8/188/artifact/hazelcast-client/target/surefire-reports/com.hazelcast.client.map.ClientSortLimitTest-output.txt

**Comment by sancar** [comment]
This one is probably related to following test
Started Running Test: ClientSemaphoreThreadedTest.concurrent_trySemaphoreWithTimeOutTest

From the "com.hazelcast.client.map.ClientSortLimitTest-output.txt " it can be seen that ClientSortLimitTest tests are passed but next class(ClientSemaphoreThreadedTest) caused the timeout. 

@Danny-Hazelcast I see your commits related to marking and unmarking this test as Problematic. Can you share your findings related to this test ? 

I am updating the issue name also.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/538/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/542/console

**Comment by mesutcelik** [comment]
no recent failure. closing.
