### ISSUE TITLE
[TEST-FAILURE] EvictionTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4894]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/492/console

**Comment by ahmetmircik** [comment]
Seems a CI system internal error, closing now.

**Comment by bilalyasar** [comment]
@ahmetmircik according to logs, there are some exceptions in this test class logs, is this expected behaviour?
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/492/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.EvictionTest-output.txt

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/503/console

**Comment by metanet** [comment]
Related failures (ResponseAlreadySentException) are here: 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/503/artifact/hazelcast/target/surefire-reports/com.hazelcast.map.EvictionTest-output.txt

Closed since not failed recently.
