### ISSUE TITLE
The batch launcher should include the JCache API

### ISSUE THREAD

**Issue by trajano** [hazelcast/hazelcast#4902]
If I use a JCache enabled application with a Hazelcast that is running by default without JCache API loaded it will fail with 
<pre>
org.apache.catalina.LifecycleException: java.lang.NoClassDefFoundError: javax/cache/configuration/CompleteConfiguration
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5920)
</pre>
My suspicion is that the Hazelcast server bundle that I run from server.bat does not include JCache API libraries.  With JCache moving forward perhaps it should be added by default.

**Comment by serkan-ozal** [comment]
Hi @trajano,
We don't use any third party library in our bundle. So JCache is optional. 

For your case, you must add JCache library into `lib` folder and must add its path to classpath definition in `server.bat` or `server.sh`

For example if you are using **JCache 1.0.0**,

on **Windows**, you may change `CLASSATH` variable definition in `server.bat` like this:
```
...
set CLASSPATH=..\lib\hazelcast-all-${project.version}.jar;..\lib\cache-api-1.0.0.jar
...
```

or 

on **UNIX** and **MacOSX**, you can change `CLASSATH` variable definition in `server.sh` like this:
```
...
export CLASSPATH=$HAZELCAST_HOME/lib/hazelcast-all-${project.version}.jar:$HAZELCAST_HOME/lib/cache-api-1.0.0.jar
...
```

Regards.
