### ISSUE TITLE
[TEST-FAILURE] MigrationAwareServiceTest failures

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4903]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.7/com.hazelcast$hazelcast/189/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/542/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenBackupNodesTerminated_withThreeBackups/

**Comment by bilalyasar** [comment]
com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenNodesStartedParallel_withTwoBackups
com.hazelcast.spi.MigrationAwareServiceTest.testPartitionDataSize_whenNodesStartedParallel_withSingleBackup
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/549/#showFailuresLink

**Comment by mesutcelik** [comment]
duplicate of https://github.com/hazelcast/hazelcast/issues/5393
