### ISSUE TITLE
Connecting to hazelcast server from hazelcast client

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#4904]
I have the hazelcast server running with the config as follows,

Config config = new Config();

// MapConfig

config.setMapConfigs(getMapConfig());

// Serialization factory

config.setSerializationConfig(getSerializableFactory());

In this case, When hazelcast server is running in remote machine, I have to connect to my hazelcast server from hazelcast client.

But when I try to connect via Hazelcast client,

ClientConfig clientConfig = new ClientConfig(); clientConfig.getNetworkConfig().addAddress(IP:PORT);

Am able to connect to Hazelcast server,

But when I get map [hazelcast.getMap(test).values()] It shows the exception that it is expecting my configuration of seralization factory in hazelcast client config,

So When I add the serialization config [Which has Serialization factory class pointing to beans]

clientConfig.setSerializationConfig(getSerializableFactory());

It works fine,

So Is there a way that I can connect to Hazelcast server without using Serialization Config. The reason is If there is any change happening in beans which I will update in hazelcast server (In remote location), I have to update that in my hazelcast client too.

Thanks and Regards, Harry

**Comment by asimarslan** [comment]
Yes you have to configure serialization on both side for your use case.
