### ISSUE TITLE
Missing Documentation of Network Config for JCache

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#4905]
Current documentation does not include configuring network settings in a Hazelcast cluster using JCache. See below for example:

For JCache Server:
Config config = new Config();
config.setNetworkConfig(networkConfig);
config.<Many_Other_Configurations>;

HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
CacheManager cacheManager = HazelcastServerCachingProvider.createCachingProvider(instance).getCacheManager();

Do Similar thing for JCache Client:
ClientConfig clientConfig = new ClientConfig();
clientConfig.setNetworkConfig(networkConfig);
clientConfig.<Many_Other_Configurations>;

HazelcastInstance instance = HazelcastClient.newHazelcastClient(clientConfig);
CacheManager cacheManager = HazelcastClientCachingProvider.createCachingProvider(instance).getCacheManager();

The issue came into notice by a customer issue asking following question:

"We are using JCache / HZ 3.3.x. We cannot find any information on how to 
a) set the port of the hazelcast server to connect to 
b) set multiple IP addresses/cluster members 
c) set name of the group and password

Questions 
1. How can i do this? Can I use NetworkConfig in combination with JCache? How?"

**Comment by noctarius** [comment]
As we discussed internally it is non-public api (in your example) and there are two official ways from 3.4 onwards and both are documented :)

Please find the docs here: http://docs.hazelcast.org/docs/3.4/manual/html/jcache-icache.html

Anything else is internal use only and might change at any time!

Sorry but I'm going to close it :D

**Comment by noctarius** [comment]
I'm still convinced we can close this but let's decide someone else. The pointed out class is internal API, it is located inside a .impl. package which clearly marks it that way. 3.4 has an officially supported and documented way, therefore I won't go and add documentation for this on any version :)

**Comment by wildnez** [comment]
The shared link for 3.4 documentation still does not talk about Cache Provider based on Client Config. And it also shows that one has to rely on putting all configurations in a file (properties). How can the whole thing be configured purely at run time?

**Comment by noctarius** [comment]
Nope it talks about instance-name based referencing an existing HazelcastInstance and it talks about configuration referencing. There are two different types and sections.

But you're right, client is not mentioned :)

**Comment by noctarius** [comment]
Here's a ClientConfig example:

```
ClientConfig clientConfig = new ClientConfig();
ClientNetworkConfig networkConfig = clientConfig.getNetworkConfig();

networkConfig.addAddress("127.0.0.1", "127.0.0.2");

// Create a named HazelcastInstance
HazelcastInstance hazelcastInstance = HazelcastClient.newHazelcastClient(clientConfig);
String clientName = hazelcastInstance.getName();

CachingProvider cachingProvider = Caching.getCachingProvider();

// Create Properties instance pointing to a named HazelcastInstance
Properties properties = new Properties();
properties.setProperty(HazelcastCachingProvider.HAZELCAST_INSTANCE_NAME, clientName);

URI cacheManagerName = new URI( "my-cache-manager" );
CacheManager cacheManager = cachingProvider
        .getCacheManager( cacheManagerName, null, properties );
```

**Comment by serkan-ozal** [comment]
@noctarius @wildnez 
Guys, Is it enough mentioning `ClientConfig` example in our documentation? WDYT?

**Comment by noctarius** [comment]
Well since we currently can't set a clients name upfront I guess this is ok, any idea what else you want to add?

**Comment by serkan-ozal** [comment]
@noctarius So I think, adding your sample code to `Named Instance Scope` section is enough. If it is OK, I will add them to document after talking with @Serdaro

**Comment by serkan-ozal** [comment]
closed by https://github.com/hazelcast/hazelcast/commit/db009b5422733e9a7a4d5bb2f4fbc0831f92f1b3
