### ISSUE TITLE
Entry still returned when querying on an Indexed field which is an Enum

### ISSUE THREAD

**Issue by Fritsi** [hazelcast/hazelcast#4910]
If I add an Index to a Map which has an Enum type, and I delete an entry from the Map, then if I do a map.values(new SqlPredicate("myEnumField = ''ENUM_VALUES")) it will still return the deleted item.
I think the reason for this is that during adding the Index the Enum value will be converted to String, and during delete in com.hazelcast.query.impl.UnsortedIndexStore#removeIndex the oldValue parameter will be an Enum value, but com.hazelcast.query.impl.UnsortedIndexStore#mapRecords will store a String, so mapRecords.get(oldValue) won't work.
Hazelcast version: 3.2.3

**Comment by mdogan** [comment]
Closing in favor of #8305
