### ISSUE TITLE
Test of getLocalExecutorStats() is failing spuriously

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast#4911]
The commit bd9bb627bb9dceae1c2971ea0e4f0abae097d893 has commented out a test of `getLocalExecutorStats()` because it is failing spuriously. After fixing this issue the test should be enabled.

This is probably related to issue #4677.

**Comment by jerrinot** [comment]
why not to use @Ignore instead? ignored tests are still in statistics. now the test is invisible.

**Comment by mtopolnik** [comment]
@jerrinot Should I open a pull request with that change? :)

**Comment by jerrinot** [comment]
well, you directly pushed a commit to comment out the test to the master. I guess you can use the same strategy now?

**Comment by mtopolnik** [comment]
I didn't, I wouldn't dare :) It's a commit on the branch that was merged.

**Comment by jerrinot** [comment]
oh, please accept my apology for such accusation!  (now I have to blame reviewers instead of you:)))

I think it's worth sending a PR to uncomment it and add `@Ignore` (unless you are working on a proper fix right now)

**Comment by mtopolnik** [comment]
I'm not working on a fix, but given my experience with PR's, even a trivial change may require days of attending to the PR (the dreaded cycle of rebase -> jenkins fail -> verify -> pass -> rebase -> jenkins fail).
