### ISSUE TITLE
[TEST-FAILURE] SingleNodeTest.cancelWhileQueued

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#4915]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/511/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/17/com.hazelcast$hazelcast/testReport/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by muratayan** [comment]
I am working on this.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/33/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by gurbuzali** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/5022

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/405/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/594/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by muratayan** [comment]
```java
assertFalse(queuedFuture.isDone());
assertTrue(queuedFuture.cancel(true));
assertTrue(queuedFuture.isCancelled());
assertTrue(queuedFuture.isDone());
```
Sometimes queuedFuture is mysteriously finishing before `cancel(true)` operation.

In theory it should remain in the queue while first task is still running which is:
```java
Callable task1 = new SleepingTask(100);
Future inProgFuture = executor.submit(task1);
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/408/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/602/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/47/testReport/junit/com.hazelcast.executor/SingleNodeTest/cancelWhileQueued/
