### ISSUE TITLE
Query execution should be async

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#4919]
Currently the query execution uses a thread from the generic thread pool to wait for the completion of the query running on each partition. This should be done in an async way to prevent consuming this generic thread. The problem is that generic threads are used for all kinds of things for example system messages like heartbeat. If the pool is empty, heartbeat will be slowed down or potentially not work at all.

**Comment by ajermakovics** [comment]
Although this is about queries there are other scenarios where async execution would be useful. For example, loading data from a database without blocking partition threads. One option: add a `getResponseAsync` method in Operation class returning ICompletableFuture.

**Comment by pveentjer** [comment]
You can always do that without changes in the Operation. Just set up your own response handler class and inject it in the operation. And give it callback abilities.

**Comment by mdogan** [comment]
Most probably, this is going to be implemented in the context of https://hazelcast.atlassian.net/wiki/display/PM/Query+Async+API

**Comment by dbrimley** [comment]
Closed as fixed in 3.9
