### ISSUE TITLE
[TEST-FAILURE] TomcatWebFilterTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4944]
```
Running com.hazelcast.wm.test.TomcatWebFilterTest
Build timed out (after 200 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/512/console

**Comment by mesutcelik** [comment]
I don't think that is related to TomcatWebFilterTest. Somehow build took so long and it failed at the point where we run TomcatWebFilterTest. TimeStamper plugin will give us more info about such timeouts
