### ISSUE TITLE
hazelcast 3.3.2 sensitive to VM disk access latency

### ISSUE THREAD

**Issue by victorfuman** [hazelcast/hazelcast#4951]
We use hazelcast 3.3.2 + JDK/JVM 7 on VMs and nodes form a separate cluster (not in embedded mode).We noticed whenever the VM's shared storage (underlying physical disk access) is slow (hazelcast node sees higher cpu iowait), hazelcast becomes unstable (e.g. higher get latency, hazelcast sometimes even crashes). We use log4j and only does very limited logging (i.e. logs the hazelcast internal monitor data every 5 seconds). As a in-memory grid, hazelcast should not be sensitive is disc access slowdown. This seems a bug to me (even though tough to reproduce using code). More details about the environment (where problem appeared) can be found in the post https://groups.google.com/forum/#!topic/hazelcast/E3j8__GlwYU.

**Comment by jerrinot** [comment]
Hi @victorfuman, thanks for creating the issue. Could you try to reproduce it and then switch off logging (e.g. by using the NOP logger) and ran the same scenario again? 

Also you mentioned it sometimes even crash - could you be more specific? What do you mean by crash? An exception being thrown? or a hard JVM crash?

**Comment by mdogan** [comment]
Not enough information.
