### ISSUE TITLE
[TEST-FAILURE] map.MapTransactionTest

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4975]
```
05:06:24 Running com.hazelcast.map.MapTransactionTest
06:38:34 Build timed out (after 100 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/510/

**Comment by eminn** [comment]
Closing the issue since there isn't enough log information and the failure is not seen lately.
