### ISSUE TITLE
hazelcast spring config variable replacement and schema validation

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4979]
currently we support this feature for server side and client side but not the in spring.
full story is here: https://groups.google.com/forum/#!topic/hazelcast/CumyEVvxZuE

**Comment by mesutcelik** [comment]
For the system property replacement part, **property-placeholder** is already available to use.

http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#xsd-config-body-schemas-context-pphc

**Comment by mesutcelik** [comment]
property-placeholder is already available and that is what is asked in the google groups.
