### ISSUE TITLE
[TEST-FAILURE] impl.BackpressureRegulatorStressTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#4996]
```
01:27:47 Running com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest
04:15:23 Build timed out (after 200 minutes). Marking the build as aborted.
04:15:24 FATAL: command execution failed
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/517/console

**Comment by pveentjer** [comment]
Hi Bilal, I'll have a look at this one.

**Comment by pveentjer** [comment]
Should be fixed with this PR:
https://github.com/hazelcast/hazelcast/pull/5009

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/525/console

**Comment by mesutcelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/5009

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/528/console

BackpressureRegulatorStressTest took 2.5 hours to complete which led build timeout.

```
01:37:20 Running com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest
04:08:06 Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9,045.341 sec - in 
```

**Comment by metanet** [comment]
Same here: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/529/artifact/hazelcast/target/surefire-reports/com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulatorStressTest.txt

2.5 hours

**Comment by pveentjer** [comment]
My bad. I was running locally for 30 minutes per test because I wanted to test is issue I was running into. SInce there are 5 tests --> 150 minutes of running time. I reduced it to 5 minutes a test (the original setting).
