### ISSUE TITLE
Hazelcast 3.3.2 - time based eviction

### ISSUE THREAD

**Issue by RovoMe** [hazelcast/hazelcast#5014]
As we are currently experimenting with Hazelcast for its applicability as a caching solution for a leaky-bucket filter, which relies on the eviction of entries, we noticed some inconsitencies with the timing behavior when entries actually evict. 

As there might be different eviction time-frames for different clients (not sure if we are really going in that direction) we make use of [put(K, V, long, TimeUnit)](http://docs.hazelcast.org/docs/latest/javadoc/com/hazelcast/core/IMap.html#put%28K,%20V,%20long,%20java.util.concurrent.TimeUnit%29). To test the eviction behavior of entries using this method we came up with this simple unit test:

    @Test
    public void testEvictionOnkeyUpdate() throws Exception {
        String testMap = "testMap";
        HazelcastInstance hazelcast = Hazelcast.newHazelcastInstance();
        HazelcastInstance hzClient = HazelcastClient.newHazelcastClient();

        IMap<String, String> map = hzClient.getMap(testMap);

        // # 1: does an entry evict correctly?
        map.put("key", "test", 1L, TimeUnit.SECONDS);
        assertThat(map.size(), is(equalTo(1)));

        Thread.sleep(900L);

        assertThat(map.size(), is(equalTo(1)));

        Thread.sleep(900L);

        assertThat(map.size(), is(equalTo(0)));

        // # 2: when does an entry evict if it is updated?
        map.put("key", "test", 1L, TimeUnit.SECONDS);

        Thread.sleep(900L);

        assertThat(map.size(), is(equalTo(1)));

        map.put("key", "test", 1L, TimeUnit.SECONDS);

        Thread.sleep(900L);

        assertThat(map.size(), is(equalTo(1)));

        // Thread.sleep(900L); // assert below FAILS!
        // Thread.sleep(2500L); // FAILS also!
        Thread.sleep(3000L); // SUCCEEDS

        assertThat(map.size(), is(equalTo(0)));

        HazelcastClient.shutdownAll();
        Hazelcast.shutdownAll();
    }

There is no further configuration defined for this test (`INFORMATION: Loading 'hazelcast-default.xml' from classpath.`) and the unit-test is the only Hazelcast instance (`Members [1] { Member [192.168.1.113]:5701 this }`). All except the last assert work correctly. The last assert only succeeds if the `Thread.sleep(...)` is set to three seconds in my particluar case.

Is this behavior expected? Is there any other way to define client-specific time-outs of entries which do evict almost immediately after the specified TTL?

**Comment by ahmetmircik** [comment]
Hi Roman,
It is expected behavior, please read the comment [here] (https://github.com/hazelcast/hazelcast/blob/v3.3.2/hazelcast/src/main/java/com/hazelcast/map/DefaultRecordStore.java#L188). Expired entries can not be reached but when you check the size you may see that map still has some entries to be swept but eventually that size should come to zero. You can also check that behavior by using eventual assertions like [this](https://github.com/hazelcast/hazelcast/blob/v3.3.2/hazelcast/src/test/java/com/hazelcast/test/HazelcastTestSupport.java#L114)
