### ISSUE TITLE
high cpu usage due to hazelcast (version 3.4.1)

### ISSUE THREAD

**Issue by janhoef** [hazelcast/hazelcast#5021]
we are running several hazelcast instances in a jboss 6 server cluster and encountered high cpu usage  due to com.hazelcast.nio.AbstractIOSelector. In the instances 9 servers are configured.
Do you have any idea how we can decrease the impact on the cpu. Hazelcast takes 40% of the cpu.

**Comment by pveentjer** [comment]
When did you see this CPU usage increase? E.g. from 3.4 to 3.4.1?

**Comment by janhoef** [comment]
we had first version 3.2 had no problem. Upgraded to 3.4.1 and deployed it. A few weeks all was in acceptable boundaries but now the last 2 weeks cpu exploded. see jvisualvm printscreen. How can I collect information to track down the cause?
![hzcpu](https://cloud.githubusercontent.com/assets/11850224/7042017/ccedff98-ddde-11e4-90da-84b481558867.JPG)

**Comment by pveentjer** [comment]
So only when a member is running for a long time, cpu usage is increased. Correct? How long is this period?

**Comment by janhoef** [comment]
I think we didn't change anything on the servers.
I attached the trend from begin march till now. Problem is there more than 2 weeks.
Can I collect some hazelcast data to find the cause of the problem? Or what actions I can take to solve the problem?

**Comment by janhoef** [comment]
we were on version 3.2 and not on 3.4.1. I think the version 3.2 had a problem. When hazelcast was idle, cpu utilization increased.

**Comment by janhoef** [comment]
We will do an upgrade to 3.4.1 and look whether this upgrade solves the cpu utilization of hazelcast.
Everyone has an idea how I can gather extra data to find the reason of this?

**Comment by pveentjer** [comment]
You could enable the Java Flight Recorder if you are using an Oracle JVM.

http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html

**Comment by fridlyos** [comment]
Hello... Having a similar issues on a cluster with 3 instances.  Can't find the root cause.  One of the instances started acting up - hazelcast is pretty much the only activity there, and it's running at 80-90% cpu.  Have you been able to resolve the issue?  Any suggestions?

Would appreciate any help in this...

Thanks...

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ? cpu usages occupied by some IO thread in hazelcast seemed high after running a period of time

**Comment by pveentjer** [comment]
No update on this particular issue. 

Probably best to enable the Flight Recorder and see what is happening.

**Comment by mdogan** [comment]
Network layer has been significantly changed in latest releases. Please try latest version and feel free to open a new issue if problem still exists.
