### ISSUE TITLE
[TEST-FAILURE]  MapTransactionTest.testTxnBackupDies

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5031]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/198/com.hazelcast$hazelcast/testReport/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by eminn** [comment]
Closing the issue since the test is not failing recently.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.map.MapTransactionTest.testTxnBackupDies(MapTransactionTest.java:214)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3669/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/693/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3894/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16424/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/278/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3968/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/18/testReport/junit/com.hazelcast.map/MapTransactionTest/testTxnBackupDies/
