### ISSUE TITLE
hazelcast spring xsd and hazelcast default config xsd out of sync

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5034]
they are not same. there are some parameters  and their default parameters are not same. 2 xsd should be revised.

**Comment by mesutcelik** [comment]
hazelcast-spring.xsd has to import hazelcast-config.xsd or hazelcast-client-config.xsd or parts of them. That way we don't have to maintain/sync 3 seperate xsd files. 

Config import feature can be used to achieve this.

**Comment by dsukhoroslov** [comment]
hazelcast-spring xsd miss the folowing hazelcast elements at all:

- reliable-topic
- semaphore
- ringbuffer
- import

any plans to add them in 3.7?

**Comment by mmedenjak** [comment]
Reliable topic, semaphore and ringbuffer support is included in the 3.8 release. There have been some fixes for other structures as well:
https://github.com/hazelcast/hazelcast/pull/9360
https://github.com/hazelcast/hazelcast/pull/9370
These fixes affect hazelcast.xml config, Spring config and XML generation.

Other config options need to be checked.

**Comment by mmedenjak** [comment]
The PRs for this have been merged and will be included in 3.8. I propose to close the issue.

**Comment by mmedenjak** [comment]
Lots of XSD and XML config options have been fixed in 3.8, this including. I am closing this issue, please reopen if there are additional missing values.
