### ISSUE TITLE
Add IAtomicInteger

### ISSUE THREAD

**Issue by manderson23** [hazelcast/hazelcast#5036]
Add an equivalent to IAtomicLong for java.util.concurrent.atomic.AtomicInteger.

**Comment by pveentjer** [comment]
Why not use the IAtomicLong.

**Comment by manderson23** [comment]
I'm potentially looking to evaluate using Hazelcast where I currently use AtomicInteger. It just seemed to make more sense to keep the same type as I don't really want to be concerned with casting etc.

Wouldn't it make sense for Hazelcast to provide distributed implementations of a range of atomic variables?

**Comment by pveentjer** [comment]
It makes sense but you are the first one asking for an IAtomicInteger. Most people are fine with an IAtomicLong.

**Comment by manderson23** [comment]
Would this be a copy/paste/modification of the IAtomicLong implementation? If so are you open to receiving a PR?

**Comment by mdogan** [comment]
This can be easily achieved by encapsulating IAtomicLong into a custom IAtomicInteger. No need to implement anything further.
