### ISSUE TITLE
SlowOperationDetector disable logging option

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5043]
There should be an option to disable the SlowOperatioDetector logging the stacktraces to the log file. It is very noisy and if you already using the management center or the performance monitor, there is no need to have the stacktraces written to the normal log file.

**Comment by pveentjer** [comment]
There should be a hint logging to indicate to the end user that this feature is available. So the first time you log something on the logger, we should hint about the exist

**Comment by Donnerbart** [comment]
Do you want an option just for the stack trace part or the whole logging of the `SlowOperationDetector`? I could create two properties. We could also differ between the first occurence of an operation and the follow ups:
```
SLOW_OPERATION_DETECTOR_LOGGING_LEVEL = {"none", "first", "always"};
SLOW_OPERATION_DETECTOR_LOGGING_STACKTRACE = {"none", "first", "always"};
```

or just:
```
SLOW_OPERATION_DETECTOR_LOGGING_STACKTRACE = {"false", "true"};
```
