### ISSUE TITLE
[TEST-FAILURE] ReplicatedMapHitsAndLastAccessTimeTest.test_hitsAndLastAccessTimeSetToAnyValueAfterStartTime_objectDelayDefault

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5045]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/515/com.hazelcast$hazelcast/testReport/com.hazelcast.replicatedmap/ReplicatedMapHitsAndLastAccessTimeTest/test_hitsAndLastAccessTimeSetToAnyValueAfterStartTime_objectDelayDefault/

**Comment by eminn** [comment]
Closing the test failure since it is not failing recently
