### ISSUE TITLE
[TEST-FAILURE] CustomDataSourceMapReduceTest Timeout

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5046]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast$hazelcast/206/testReport/junit/com.hazelcast.mapreduce/CustomDataSourceMapReduceTest/testMapReduceWithCustomKeyValueSource/

**Comment by metanet** [comment]
Closing this one since not failing for a long time. This timeout failure could be related to the bug fixed with #5306. We should re-open it if it fails again and make more investigation on this.
