### ISSUE TITLE
[TEST-FAILURE] RawProtocolTest.testAuthenticateWithUsernameAndPassword

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5048]
**There are 58 failures**
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/506/

**Comment by sancar** [comment]
This build does not seem healthy. I checked the method it does not fail now. Given that it's been 1 month and did not fail again , I assume it is fixed. Closing the issue.
