### ISSUE TITLE
Running scripts other than JavaScript

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#5053]
Hi,

Documentation on scripting features http://docs.hazelcast.org/docs/3.4/manual/html-single/hazelcast-documentation.html#scripting should directly state that to use other scripting languages corresponding jars (e.g. groovy.jar and groovy-jsr223.jar or groovy-all.jar) should be available in member node classpath.

Thanks

**Comment by Serdaro** [comment]
I will get advice related to this from the integration team tomorrow. Thank you.

**Comment by gAmUssA** [comment]
Thanks @Serdaro

**Comment by gAmUssA** [comment]
any updates on this one @Serdaro @emrahkocaman ?

**Comment by Serdaro** [comment]
Not for now Viktor. You will be informed with the GitHub notification.
