### ISSUE TITLE
[TEST-FAILURE] MapReduceTest.testMapperReducer

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5056]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/509/com.hazelcast$hazelcast/testReport/com.hazelcast.mapreduce/MapReduceTest/testMapperReducer/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3109/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testMapperReducer/

**Comment by metanet** [comment]
Closing this one since not failing for a long time. This timeout failure can be related to the bug fixed with #5306. We should re-open it if it fails again and make more investigation.
