### ISSUE TITLE
Support constum types for indicies / value extract

### ISSUE THREAD

**Issue by Fritsi** [hazelcast/hazelcast#5066]
Hi,

Our problem is that we have an immutable class with a guava optional field.

    public final class ValueClass {

        private final String name;

        private final String value;

        public ValueClass(String name, String value) {
            this.name = name;
            this.value = value;
        }

        public String getName() { return name; }

        public String getValue() { return value; }

    }

    public class MyClass {

        private final Optional<ValueClass> value;

        public MyClass(Optional<ValueClass> value) {
            this.value = value;
        }

        public Optional<ValueClass> getValue() {
            return value;
        }

    }

It would be great if we could add indicies like:

    addIndex("value.orNull.name", false)

or do a query like

    map.select(new SqlPredicate("value.orNull.name = 'test'")

Currently the problem is that we get an Exception saying no name attribute on class Object, because the result type of ValueClass.getValue().orNull() is object.

It's easy to solve this problem by modifying http://grepcode.com/file/repo1.maven.org/maven2/com.hazelcast/hazelcast-all/3.4.1/com/hazelcast/query/impl/ReflectionHelper.java like:

    if (clazz.equals(Optional.class)) {
        clazz = (Class<?>)(((ParameterizedType) method.getGenericReturnType()).getActualTypeArguments()[0])
    }

Of course introducing a dependency on the guava library for this shouldn't be done, so maybe the Config could me modified so we can add custom value extractors?

Currently we have to add another method like:

    public ValueClass getValueOrNull() { return value.orNul(); }

to make this work.

We don't want to implement Portable or something like that in our class.

And of course we also have to consider using Java 8 Optional or Scala Option.

**Comment by noctarius** [comment]
Hey that for the explanation. We already have thought of this feature to make it a Hazelcast Incubator project but then as a full blown customizable indexing system. Would you be interested in helping out on this feature as part of the community process?

**Comment by Fritsi** [comment]
Yes, definitely.

**Comment by jerrinot** [comment]
I quite like this one. It should be relatively straightforward to implement. @Fritsi: Are you still interested in this one?

**Comment by jerrinot** [comment]
Custom extractors included in Hazelcast 3.6.
Fixed by #6525
