### ISSUE TITLE
[TEST-FAILURE] PartitionLostListenerStressTest.test_partitionLostListenerInvoked_when2NodesCrashed_withData

### ISSUE THREAD

**Issue by metanet** [hazelcast/hazelcast#5071]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/534/com.hazelcast$hazelcast/testReport/com.hazelcast.partition/PartitionLostListenerStressTest/test_partitionLostListenerInvoked_when2NodesCrashed_withData/

PartitionLostListenerStressTest tests start 5 nodes, put 5000 entries to each one of 5 maps and shutdown some of the nodes. After the cluster becomes stable again (etc. migrations, replica syncs completed), assertions are done.

The failure above is because timeout occurs before the cluster becomes stable again.

**Comment by metanet** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/536/testReport/junit/com.hazelcast.map/MapPartitionLostListenerStressTest/test_mapPartitionLostListenerInvoked_when3NodesCrashed_withData/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/537/testReport/junit/com.hazelcast.partition/PartitionLostListenerStressTest/test_partitionLostListenerInvoked_when1NodeCrashed_withData/

**Comment by metanet** [comment]
Fixed by 18df8d9e2d91f14e1d8e99efb4829c337da6f5b6
