### ISSUE TITLE
Document performance impact of TWO_PHASE vs. LOCAL TransactionType

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#5075]
We have 2 types of TransactionType

```java
public enum TransactionType {

        /**
         * The two phase commit is more than the classic two phase commit (if you want a regular two phase commit,
         * use local). Before it commits, it copies the commit-log to other members, so in case of member failure,
         * another member can complete the commit.
         */
        TWO_PHASE(1),

        /**
         * Unlike the name suggests, local is a two phase commit. So first all cohorts are asked
         * to prepare if everyone agrees then all cohorts are asked to commit. The problem happens when
         * during the commit phase one or more members crash, that the system could be left in an inconsistent state.
         */
        LOCAL(2);
```

I ran our MapTransactionTest in a lab and measured effect of the TWO_PHASE type. All other settings were kept as default.
Throughput with TWO_PHASE - 27,759 ops / s
Throughput with LOCAL - 73,680 ops / s

That's a massive difference! TWO_PHASE happens to be a default type.

Our documentation already has a nice chapter describing `TransactionType`, but there is nothing about performance implications.

**Comment by bwzhang2011** [comment]
+1

**Comment by bwzhang2011** [comment]
@jerrinot, would you mind leaving more message for the performance issue between LOCAL and TWO-PHASE ?
