### ISSUE TITLE
[TEST-FAILURE] ClientMemberAttributeTest.testChangeMemberAttributes

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5099]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:603)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:596)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:588)
	at com.hazelcast.client.ClientMemberAttributeTest.testChangeMemberAttributes(ClientMemberAttributeTest.java:76)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-new/405/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
old issue: https://github.com/hazelcast/hazelcast/issues/3778

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast-client-new/87/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-new/34/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast-client-new/536/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client-new/597/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3044/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast-client-new/409/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3051/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-new/40/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/45/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3066/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/
@sancar  this is client-new module failure. fyi.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-new/43/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast-client-new/521/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/com.hazelcast$hazelcast-client-new/46/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/51/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast-client-new/549/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by sancar** [comment]
closed via #5296

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast-client-new/67/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3186/testReport/junit/com.hazelcast.client/ClientMemberAttributeTest/testChangeMemberAttributes/
