### ISSUE TITLE
[TEST-FAILURE] ClientMultiMapListenersTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5100]
```
01:55:31 Running com.hazelcast.client.multimap.ClientMultiMapListenersTest
02:54:18 Build timed out (after 100 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/407/console

**Comment by sancar** [comment]
Note: this is related to old client.

**Comment by sancar** [comment]
There is nothing in the tests that can cause buildTimeout unless there is an unexpected environment problem. And since logs are lost, I dont have any clue to further investigate. I am closing this for now.
