### ISSUE TITLE
Hazelcast management center negative CPU Utilization

### ISSUE THREAD

**Issue by Belkacem** [hazelcast/hazelcast#5118]
![image](https://cloud.githubusercontent.com/assets/419224/7237252/94e39534-e79a-11e4-8326-8d1d6378acef.png)

**Comment by Belkacem** [comment]
Version 3.4

**Comment by emrahkocaman** [comment]
Hi @Belkacem , This info is provided by [OperatingSystemMXBean#getSystemCpuLoad](https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad--) and it's possible that this method can return negative values when cpu load is not available.
