### ISSUE TITLE
ICompletableFuture callback from getAsync not always invoked

### ISSUE THREAD

**Issue by youngm** [hazelcast/hazelcast#5133]
I brought this up on the google group [0].  However, I think this is a real issue so I decided to go ahead and file the issue.

The following code example fails for me every time on Hazelcast 3.4.2.  If I remove the "map.set" then it passes every time.

```
HazelcastInstance instance = Hazelcast.newHazelcastInstance();
IMap<Object, Object> map = instance.getMap("map");
map.set("key", "Some Value");
ICompletableFuture f = (ICompletableFuture) map.getAsync("noneexistentkey");
final CountDownLatch latch = new CountDownLatch(1);
f.andThen(new ExecutionCallback() {
	public void onResponse(Object response) {
		latch.countDown();
	}
	public void onFailure(Throwable t) {
	}
});
if (latch.await(10, TimeUnit.SECONDS)) {
	System.out.println("Success");
} else {
	System.out.println("Failure");
}
Hazelcast.shutdownAll();
```

[0] https://groups.google.com/d/msg/hazelcast/4YveWBvUTN0/Wg3Y_nOS7aAJ

**Comment by pveentjer** [comment]
This is a duplication of the following issue:

https://github.com/hazelcast/hazelcast/issues/5001

It is already resolved in master. It was still on my list to get it backported to 3.4.x branch.

**Comment by youngm** [comment]
@pveentjer Awesome!  Hazelcast rocks!

**Comment by pveentjer** [comment]
The backport fixes
https://github.com/hazelcast/hazelcast/pull/5136
