### ISSUE TITLE
Records with an index on an attribute that is also part of the key of an IMap persists after removal

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#5148]
We are seeing some weird behavior from Hazelcast after following these steps:

1. Start a cluster with 2 members
2. Add an object to an IMap where the key of the IMap is a PartitionAwareKey with the key is the same as an attribute on the object
3. Segment the cluster
4. Remove the object from one of the nodes
5. Re-join the cluster (object will be merged back)
6. Remove the object again

At this point, a call to retrieve the object using the PartitionAwareKey will correctly return null; however, using the Predicates API will return the previously deleted object!

As a workaround, removing the index for the attribute that is a part of the key seems to resolve the issue but for my company this attribute is what is queried most often thus we need it fixed.

I tried debugging the issue and it appears IndexService is correctly removing the entry but still the predicate queries return deleted objects.  I have a test case that reproduces the issue I'll be happy to share.

**Comment by jerrinot** [comment]
Thank you for reporting the issue. 
It would be a great help if you could share the test case + your Hazelcast version and configuration.

**Comment by markathomas** [comment]
I'll be happy to provide the test case but how do I get it to you?  Can I
attach the files on Github?

**Comment by jerrinot** [comment]
If it it just 1 or two files then https://gist.github.com is the easiest
option. Otherwise you can upload an archive somewhere and post a link here.
The other option is to upload it as a regular GitHub project.

**Comment by markathomas** [comment]
Here is the Gist link: https://gist.github.com/markathomas/7c152528cff2ae46af27

You may have to run it a couple of times but it's easy to spot the failure. When it occurs the output will look like this:
```
Map 1 query by uuid: 1
Map 2 query by uuid: 1
Map 1 query by display id: 0
Map 2 query by displayId: 0
Map 1 get by affinity key: null
Map 2 get by affinity key: null
```
All the queries should show zero results returned.

**Comment by markathomas** [comment]
Update: we have determined this bug is not exclusive to having the index as part of the key.  We have found that any index has the potential to cause this issue. For now, we have had to resort to removing all indexes form our system.
