### ISSUE TITLE
[TEST-FAILURE] InvalidConfigurationTest.testWhenValid_AsyncSemaphoreBackupCount

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5171]
```
java.lang.IllegalArgumentException: the sum of backup-count and async-backup-count can't be larger than than 6
	at com.hazelcast.util.Preconditions.checkAsyncBackupCount(Preconditions.java:206)
	at com.hazelcast.config.SemaphoreConfig.setAsyncBackupCount(SemaphoreConfig.java:161)
	at com.hazelcast.config.XmlConfigBuilder.handleSemaphore(XmlConfigBuilder.java:1294)
	at com.hazelcast.config.XmlConfigBuilder.handleXmlNode(XmlConfigBuilder.java:288)
	at com.hazelcast.config.XmlConfigBuilder.handleConfig(XmlConfigBuilder.java:243)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/515/testReport/junit/com.hazelcast.config/InvalidConfigurationTest/testWhenValid_AsyncSemaphoreBackupCount/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/95/testReport/junit/com.hazelcast.config/InvalidConfigurationTest/testWhenValid_AsyncSemaphoreBackupCount/

**Comment by pveentjer** [comment]
I'll have another look at it. Very strange problem because it should be deterministic, but can't produce it locally.

**Comment by bilalyasar** [comment]
@pveentjer https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/InvalidConfigurationTest.java#L417 this should be 0.

**Comment by bilalyasar** [comment]
@pveentjer default async [backup is 1] (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/InvalidConfigurationTest.java#L417 ) .
when [this line] (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/InvalidConfigurationTest.java#L171)  returns 6, it fails.

**Comment by pveentjer** [comment]
Are you able to reproduce it? When I run InvalidConfigurationTest with a freshly pulled upstream, I don't get any exceptions.

**Comment by bilalyasar** [comment]
yes i reproduced it with repeat annotation, and it fails after 3-5 iteration.

**Comment by pveentjer** [comment]
ok.. thanks.. strange... this should be a deterministic problem.

**Comment by bilalyasar** [comment]
it is deterministic because test gets random async-backup count. 
and when test gets random async-backup-count which is 6, it fails. because normal backup-count is already 1 and when we sum two of them it goes to 7. (failure)

**Comment by pveentjer** [comment]
ahhhh

**Comment by bilalyasar** [comment]
yes, the solution is making [backup-count of this line] (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/InvalidConfigurationTest.java#L417) to 0.
