### ISSUE TITLE
[TEST-FAILURE] ClientMapUnboundReturnValues_BasicTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5172]
```
com.hazelcast.spi.exception.TargetDisconnectedException: null
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:111)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:92)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:147)
	at com.hazelcast.client.proxy.ClientMapProxy.values(ClientMapProxy.java:811)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalRunWithoutException(ClientMapUnboundReturnValuesTestSupport.java:228)
	at 
```
ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_NoPreCheck
ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_PreCheck
ClientMapUnboundReturnValues_BasicTest.testClientMap_withException_PreCheck
ClientMapUnboundReturnValues_BasicTest.testClientMap_withException_NoPreCheck
ClientMapUnboundReturnValues_BasicTest.com.hazelcast.client.map.ClientMapUnboundReturnValues_BasicTest
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/546/

**Comment by bilalyasar** [comment]
similar failures:
ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_PreCheck
ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withException_NoPreCheck
ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withoutException_NoPreCheck
ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withoutException_PreCheck
ClientMapUnboundReturnValues_TxnTest.com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/546/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/547/console
and nightly build goes to timeout due to this test.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/548/console
and nightly build timeout 4 times last 5 build.

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/549/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/550/console 6 timeout last 7 days.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/551/ 7/8 timeout

**Comment by bilalyasar** [comment]
@Donnerbart https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/554/console

**Comment by Donnerbart** [comment]
PR with a fix is pending since yesterday late afternoon.

**Comment by Donnerbart** [comment]
The timeout issue has been resolved. The tests with `withoutException` are still failing, due to problems with the new client. Those should go green without any modifications as soon as the new client is fixed.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/560/#showFailuresLink

**Comment by Donnerbart** [comment]
The following tests are "expected" to fail until the new client gets fixed:
```
com.hazelcast.client.map.ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_PreCheck
com.hazelcast.client.map.ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_NoPreCheck
com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withoutException_NoPreCheck
com.hazelcast.client.map.ClientMapUnboundReturnValues_TxnTest.testClientTxnMap_withoutException_PreCheck
```
It's all `withoutException` tests which use the normal `values()`, `keySet()` and `entrySet()` methods (which don't use queries, so the new feature is not active here).

Those tests work with 3.4.2 and the 3.5 old client. They should also work with the new client, but they don't. After some tests there seems to be a general problem with the new client which also affects these tests.

I think we should leave them activated as additional monitoring for the issue with the new client.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/563/#showFailuresLink

**Comment by Donnerbart** [comment]
Seems to be fixed since this nightly build: https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/566/
