### ISSUE TITLE
removeAttribute will prevent any updates by setAttribute in deferred write mode

### ISSUE THREAD

**Issue by davidsiefert** [hazelcast/hazelcast#5186]
Some legacy code (of mine, not yours) is calling:
~~~~
session.removeAttribute("blah");
// a few lines of code later...
session.setAttribute("blah", "my new blah attribute");
~~~~

What happens is that since "blah" is marked for removal, at the end of the request "blah" will never be propagated to be "my new blah attribute".

**Comment by davidsiefert** [comment]
I currently have a fix for this I would like to submit.  Will push to fork later.

**Comment by davidsiefert** [comment]
@mattbague is pairing with me on the fix.

**Comment by davidsiefert** [comment]
So I submitted a pull request, and the devops bot seems to have gone through a test-commit cycle.... so what happens now?

**Comment by mesutcelik** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/5189
