### ISSUE TITLE
src/test/java/com/hazelcast/wm/test/JettyWebFilterTest.java does not fail properly

### ISSUE THREAD

**Issue by davidsiefert** [hazelcast/hazelcast#5188]
It appears that the container reuse in these 'slow' tests does not properly set up for each test.  We discovered this during writing a test for issue #5186 where reordering the test config parameters from:
~~~~
new Object[]{"node - not deferred", "node1-node.xml", "node2-node.xml"}, //
new Object[]{"node - deferred", "node1-node-deferred.xml", "node2-node-deferred.xml"}, //
new Object[]{"client - not deferred", "node1-client.xml", "node2-client.xml"}, //
new Object[]{"client - deferred", "node1-client-deferred.xml", "node2-client-deferred.xml"} //
~~~~
to
~~~~
new Object[]{"node - deferred", "node1-node-deferred.xml", "node2-node-deferred.xml"}, //
new Object[]{"client - deferred", "node1-client-deferred.xml", "node2-client-deferred.xml"}, //
new Object[]{"node - not deferred", "node1-node.xml", "node2-node.xml"}, //
new Object[]{"client - not deferred", "node1-client.xml", "node2-client.xml"} //
~~~~

got our test to fail properly.

**Comment by bilalyasar** [comment]
@davidsiefert i tried to reproduce your case in my local, and didn't succeed it. Can you give some environmental details like java version, jdk type, also which OS?
And when you try in local, do you still encounter this failure?

**Comment by mesutcelik** [comment]
I am closing this right now. please feel free to reopen if you still see the problem exists.
