### ISSUE TITLE
hazelcast client should have same discover abilities as server

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#520]
The hazelcast client should have the same network discovery abilities as the server; so multicast, tcp-ip cluster, aws.

**Comment by bwzhang2011** [comment]
@sancar, how does this going on ? could discovery function for client api could be merged into hz3.5 ?

**Comment by pveentjer** [comment]
Afaik it isn't on the roadmap for 3.5. Maybe 3.6

**Comment by noctarius** [comment]
I guess this will be approached using HEP2 - https://hazelcast.atlassian.net/wiki/display/COM/HEP+2+-+Hazelcast+Discovery+SPI

**Comment by bwzhang2011** [comment]
@noctarius, @pveentjer, any update with such issue ? hope clientapi brings support for discovery not long in the future.

**Comment by jerrinot** [comment]
@bwzhang2011: The new discovery SPI works equally well on both member and client sides. 

I suppose the next logical step is to migrate the existing "built-in" discovery strategies to use the Discovery SPI. @noctarius: Do you have any plans around this? :) Is there anything missing in the SPI?

**Comment by bwzhang2011** [comment]
@jerrinot, thanks for feedback. I read the 3.6 manual but I could not find the chapter or example for discovery spi support in client sides. this will be very helpful and the client only need to connect to the discovery provider without knowing the tree hazelcast cluster address for it would be changed. so would you mind leaving more message to introduce for that ?

**Comment by bwzhang2011** [comment]
@jerrinot, I did the test with hazelcast-zookeeper project and I found that if discovery enabled, the performance seems drop download due to the middle-ware service discovery provider brought in, e.g when I tested with IQueue between client and cluster in original configuration, the cost for data processing near to the cost like ping method e.g about 1~2ms, but since I switched to discovery configuration, half of the testing would drop down to 15ms which seems very slow afterwards. so hope hazelcast team could help improve such.

**Comment by jerrinot** [comment]
@bwzhang2011: Hi there,

clients do support SPI Discovery. I'll make sure it's included in the manual, thanks for spotting this!

The performance degradation is very strange, the Discovery SPI is nowhere near a hot-path for a regular operations. Do you have a code to share? Even the 1-2ms seems quite excessive, what network do you use?

**Comment by ukjbrown** [comment]
+1 It's frustrating that with the old lite member, this would have worked as expected. I'm not sure why it was decided that should be dropped before all the equivalent functionality was available within HazelcastClient.

**Comment by jerrinot** [comment]
@ukjbrown: Thanks for your feedback! 
I have good news: Hazelcast 3.6 has Lite Members back.

**Comment by ukjbrown** [comment]
Thanks @jerrinot, will have to look at upgrading. Using Spring Boot, so been stuck on 3.5.5 provided by that but since the spring boot auto configuration for Hazelcast is currently fairly basic (as of 1.3.3), I could disable that if necessary.

**Comment by jerrinot** [comment]
@ukjbrown: I am very glad to hear that. Happy Hazelcasting!

**Comment by jeppec** [comment]
Are there any estimates for when clients will be able to support discovery using multicast?

**Comment by jerrinot** [comment]
@jeppec: I am not sure if by "native" you mean "Java client" (native as in "not a lite member") or C++, Python and other clients. 

If Java is what you are up to then there is good news: In Hazelcast 3.7 (which will be release REALLY soon) it's possible to use multicast discovery on clients. See http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#discovering-native-clients

**Comment by jeppec** [comment]
@jerrinot Ah yes, it's the Java client I'm referring to :)

Is there a way to configure the multicast discovery using (Java) code (the example shows the XML approach) ?

**Comment by jerrinot** [comment]
@jeppec it absolutely is possible to use a programmatic configuration. XML config parser does nothing else then converting XML into equivalent Java configuration. 

On a server side you can get an access to discovery configuration via `config.getNetworkConfig().getJoin().getDiscoveryConfig()`
on a client-side you can do the same via 
`clientConfig.getNetworkConfig().getDiscoveryConfig()`

Do not forget to enable the Discovery SPI via `config.setProperty("hazelcast.discovery.enabled", "true")`

**Comment by jeppec** [comment]
It works perfectly @jerrinot - thanks :) 
Are there properties that can control connection timeouts, retries, time between retries?

**Comment by bilalyasar** [comment]
@jeppec we have two logic there,
sender: which sends member-ip informations continuously. ( in every 2 seconds)
receiver: that listens network when node needs other members' ip addresses. for example: initial start, split-brain cases etc, ( timeout is 3 seconds)
they are not configurable for now.

**Comment by jeppec** [comment]
Thanks for the response @bilalyasar - I think the current settings options are sufficient for our needs.

**Comment by sancar** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/8118 in 3.7

**Comment by nikhilvs** [comment]
Any chance of this feature(or AWS discovery)  in Python client ?
