### ISSUE TITLE
ReplicatedMap: keys: 0, values: 1

### ISSUE THREAD

**Issue by jl2008** [hazelcast/hazelcast#5210]
As per the following email thread. No further details available at this point, I'll try to get more.

Peter Veentjer <alarmnummer@gmail.com>

It sounds like a bug to me. Because there should not be a null element; either the item should be there or it should not be. It can't be in some intermediate state.

Can you create a github ticket for it?

On Wed, Apr 29, 2015 at 6:48 PM, Jean Luc <jeanluc2008@gmail.com> wrote:
A co-worker told me about the behaviour he had just observed. Two nodes (v 3.4.2), a ReplicatedMap with a single entry. One of the nodes calls remove(). On the another one, for a short while (seconds), map.keySet() is empty, but map.values() is not empty but has a null element. The replication delay is not changed from the default one.

Is this normal behaviour? Should ReplicatedMaps be always iterated through the keys instead of taking values()?

Thanks a lot,
JL

**Comment by eminn** [comment]
Fixed by #6176
