### ISSUE TITLE
Changes made by interceptor do not appear in backup

### ISSUE THREAD

**Issue by akoledzhikov** [hazelcast/hazelcast#5211]
Hazelcast version : 3.2.3
I have the following setup - 2 applications, each of them running a hazelcast node, with backup count = 2. Each of them also has a hazelcast client, which is used to write some data into a distributed map. Finally, there is an interceptor attached to this map, which slightly modifies any incoming entries in its interceptPut method.

The problem is, that if I kill one of the nodes, entries restored from backup are in their state before the interceptor modified them. 
Sample test application here - http://pastebin.com/nHRnqYHY

NB1: This only happens if I write the new entries using the Hazelcast client. If I write directly using the HZ node instance, everything is OK.
NB2: Another thing, which is slightly inconvenient - in the afterPut method, I also get the unmodified value.

**Comment by akoledzhikov** [comment]
And this is my current workaround - http://pastebin.com/iSJyQsPK

**Comment by eminn** [comment]
Thanks for reporting the bug, providing a test case and a suggested solution. The fix for this issue will be available for 3.4.3 and 3.5 versions.
