### ISSUE TITLE
[TEST-FAILURE] ClientMapNearCacheTest Failures

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5212]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/changes
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3090/console
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3091/testReport/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/538/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/520/

**Comment by bilalyasar** [comment]
timeout: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/546/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/100/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3096/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3100/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast-client-new/3105/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testGetAsyncPopulatesNearCache/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast-client-new/48/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testGetAsyncPopulatesNearCache/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3110/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.map/ClientMapNearCacheTest/testGetAsyncPopulatesNearCache/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/610/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/526/

**Comment by bilalyasar** [comment]
test ignored see: #5229 
https://github.com/hazelcast/hazelcast/commit/467824b

**Comment by mesutcelik** [comment]
Some other tests in the same Test class still failing.

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/423/testReport/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/56/console

**Comment by sancar** [comment]
I ignored the whole class for now. I will look into this as soon as possible.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/427/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3147/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/536/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/110/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/537/console

**Comment by sancar** [comment]
I made two fixes to this with https://github.com/hazelcast/hazelcast/pull/5311 and https://github.com/hazelcast/hazelcast/pull/5296. Closing for now.

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: readFromCacheTime > readFromClusterTime
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapNearCacheTest.testNearCacheFasterThanGoingToTheCluster(ClientMapNearCacheTest.java:179)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-OpenJDK6/com.hazelcast$hazelcast-client/273/testReport/junit/com.hazelcast.client.map/ClientMapNearCacheTest/testNearCacheFasterThanGoingToTheCluster/
