### ISSUE TITLE
[TEST-FAILURE] SlowOperationDetector_purgeTest.testPurging_Invocation

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5218]
```
Expected 4 total invocations, but was 3. Log: 
{"operation":"com.hazelcast.map.impl.operation.PartitionWideEntryWithPredicateOperation","stackTrace"
:"java.lang.Thread.sleep(Native 
Method)\n\tjava.lang.Thread.sleep(Thread.java:340)\n\tjava.util.concurrent.TimeUnit.sleep(TimeUnit.java:
386)\n\tcom.hazelcast.test.HazelcastTestSupport.sleepSeconds(HazelcastTestSupport.java:202)\n\tcom.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/607/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_Invocation/

**Comment by Donnerbart** [comment]
I didn't change the purging tests in the last PR where I fixed all other failing tests, since they didn't fail yet. So I most probably have to do the same tweaks for these tests, too. I'll have a look ASAP.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/619/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_Invocation/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/623/testReport/junit/com.hazelcast.spi.impl.operationexecutor.slowoperationdetector/SlowOperationDetector_purgeTest/testPurging_Invocation/

**Comment by Donnerbart** [comment]
Should be fixed via https://github.com/hazelcast/hazelcast/commit/d067a8e.

**Comment by Donnerbart** [comment]
Seems to work :)
