### ISSUE TITLE
TransactionalQueue should add addAll support.

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#5222]
compared with IQueue, TransactionalQueue should add addAll method support just out of the sake for batch data transaction commit.

**Comment by bwzhang2011** [comment]
Sometimes, we use the IQueue interface as the default one but for transaction we use TransactionalQueue and we could make some innovation way to make it work together.

**Comment by bwzhang2011** [comment]
please take a look at issue: https://github.com/hazelcast/hazelcast/issues/4233. currently, we faced up with batch message with transactionQueue processing, hope such could be added officially.
@mdogan, would you mind sparing some time to take a look at? just some improvement but very helpful

**Comment by noctarius** [comment]
Write a proposal and add it yourself using the Hazelcast Incubator (https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals). This is a fairly easy addition and would be a nice and small feature :)

**Comment by bwzhang2011** [comment]
@noctarius, thanks for review with such suggestion. I will try to handle such proposal these days.

**Comment by bwzhang2011** [comment]
@noctarius, sorry for such postponed for a week. I've submitted one and hope you could make some modification if not describe accurate when you have your spare time.
