### ISSUE TITLE
Hazelcast WebFilter locahCache stale when deferredWrite=true

### ISSUE THREAD

**Issue by haixiliu** [hazelcast/hazelcast#5242]
This bug is reported on 3.4.2.

During our upgrade from 1.9.4.3 to 3.4.2, I ran into inconsistency when using Hazelcast WebFilter to cluster http session across multiple nodes in a cluster. So I have done the following to look for the issue:

1. I ran my webapp with hazelcast embedded, with WebFilter enabled. Therefore it's a single node cluster. 
2. I access the webapp via browser, to trigger HazelcastHttpSession to be created in the cluster and on the local node.
3. Through debugging, I examined the session object during a browser request, thus can view the localCache value of the session object.
4. Via a Hazelcast client, I connect to the cluster, and examine the session object in cluster, it's the same as the localCache value above.
5. Via the Hazelcast client, I changed a property on the session object in cluster, and verified that its value changed.
6. Through debugging a browser request, I examine the session object again and found the property I changed in cluster wasn't present.

The above steps proved that after a node retrieves a session object from the clusterMap and stores it in localCache, update to that session object in the clusterMap (even for a single node cluster) will NOT be broadcast to appropriate nodes for their localCache to be reloaded from the clusterMap to get latest version of the session object.

The following is the code I used in my hazelcast client to modify a property:
<pre>
ClientConfig clientConfig = new XmlClientConfigBuilder().build();
HazelcastInstance client = HazelcastClient.newHazelcastClient();
IMap map = client .getMap("httpSessionMap");
NetChefSessionState st = (NetChefSessionState) map.get("HZ5BCAAF164C094D5188B79C2B75F73686::hz::scopedTarget.netChefSessionState");
		st.getUserSession().setUserFirstName("Haixi");
map.put("HZ5BCAAF164C094D5188B79C2B75F73686::hz::scopedTarget.netChefSessionState", st);
</pre>

Comparing the WebFilter.java from 1.9.4.3 and 3.4.2, the older version has the following in getClusterMap().addEntryListener section of init(), while the new version does not:
<pre>
               public void entryUpdated(EntryEvent entryEvent) {
                    if (!entryEvent.getMember().localMember()) {
                        markSessionDirty((String) entryEvent.getKey());
                    }
                }
</pre>

I am not sure whether this is no longer important, but I cannot find code in WebFilter.java of the new version that broadcasts a change for an object in the clusterMap, so it can be refreshed from a node.

**Comment by mesutcelik** [comment]
Session might be expired while you are doing your test. Can you increase session expire time and try again?

**Comment by haixiliu** [comment]
@mesutcelik , Can you explain a bit more about session expiration in this case? I don't think it has a role in my test. My webapp has session timeout set at 1 hour, and I don't see it expired during my test. (Otherwise I will see sessionDestroyed() being invoked). Thanks. - Haixi

**Comment by haixiliu** [comment]
Hello, I have debugged this bug and created a fix for it (attaching the content of the patch below). Basically I added code to mark the appropriate cache entry in the correct HazelcastHttpSession object to be reloaded, upon an update to an entry in the clustermap for httpsession (stored in hazelcast cluster). Can you kindly review and let me know whether the fix makes sense? Also, can you let me know whether/when this fix, once verified, will be incoroprated in future releases of Hazelcast? 

Thanks!
- Haixi

<pre>
Index: hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java	(revision 7)
+++ hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java	(revision )
@@ -205,7 +205,10 @@
                 }
 
                 public void entryUpdated(EntryEvent<String, Object> entryEvent) {
+					if (entryEvent.getMember() == null || !entryEvent.getMember().localMember()) {
+						resetLocalCache((String) entryEvent.getKey());
-                }
+					}	
+                }
 
                 public void entryEvicted(EntryEvent<String, Object> entryEvent) {
                     entryRemoved(entryEvent);
@@ -290,7 +293,20 @@
             }
             hazelSession.destroy();
         }
+    }
+
+	private void resetLocalCache(String key) {
+		String sessionId = extractSessionId(key);
+		String attributeKey = extractAttributeKey(key);
+		HazelcastHttpSession hazelSession = sessions.get(sessionId);
+		if (hazelSession != null && hazelSession.localCache != null && hazelSession.localCache.get(attributeKey) != null) {
+			hazelSession.localCache.get(attributeKey).reload = true;
+		}
+	}
+
+	private String extractSessionId(String key) {
+		return key.substring(0, key.indexOf(HAZELCAST_SESSION_ATTRIBUTE_SEPARATOR));
-    }
+	}
 
     private String extractAttributeKey(String key) {
         return key.substring(key.indexOf(HAZELCAST_SESSION_ATTRIBUTE_SEPARATOR) + HAZELCAST_SESSION_ATTRIBUTE_SEPARATOR.length());

</pre>

**Comment by bilalyasar** [comment]
@haixiliu, when you get the session object, web filter marks all cache entries as `reload=true`.
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java#L617
You enabled deferred-write, right?.

**Comment by haixiliu** [comment]
@bilalyasar , Yes I enabled deferred-write. I read/debug through the code, and in getSession, it usually returns at line 606: https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java#L606. Therefore, prepareReloadingSession(hazelcastSession); doesn't get executed.

Can you confirm my finding is true bug?

Thanks.

**Comment by bilalyasar** [comment]
yes, seems this is a bug. And scenario as follows: ( nonsticky + deferred-write=true)
1) request goes to server1. session.put("key","value")
2) request goes to server2. session.put("key","value2")
3) request goes to server1 again. and server1 doesn't get real value from distributed map. and returns old value.
and seems your fix correct, but i have to examine a little bit more why we have removed entry-listener  code snippet. 
thanks @haixiliu

**Comment by haixiliu** [comment]
@bilalyasar. Thanks. Can you let me know what is the scheduled release time for 3.5?

**Comment by bilalyasar** [comment]
this issue should be solved via https://github.com/hazelcast/hazelcast/pull/5474

**Comment by haixiliu** [comment]
@bilalyasar, Thanks for the update.

I looked at the code changes with #5474, and thought it would resolve the issue I reported here. 

However, the code change also seems to defeat the purpose of deferredwrite option. 

In its original design, when deferredwrite=true, update to session attributes will be kept local (to the node) and used by local (the same node) until the request is finished, at which point all updates to session attributes all pushed to the clustered map.

With the code change from #5474, in the method of readSessionFromLocal(), which is called by getSession(), it marks reload=true for ALL session attributes (regardless whether they are changed or not). As a result, whenever my application needs to get a session attribute, it will ALWAYS read from the cluster map, instead of using local cached value. And since we use spring to manage session scoped bean, spring invokes getSession() many many times during a single request, code execution of our application+hazelcast+spring is very inefficient.

I would suggest to add a check in HazelcastHttpSession.updateReloadFlag() method, to set the reload flag to be true for an entry ONLY when it's dirty.

Please let me know whether my suggestion makes sense, or I am missing something in my analysis.

Thank you!

- Haixi

**Comment by haixiliu** [comment]
@bilalyasar,

Please correct me if I am wrong, but in addition to the comments I made above, I think the code change also created another bug.

When deferredwrite=true, update to session attributes are kept local to the node in HazelcastHttpSession.setAttribute() method, and since HazelcastHttpSession.getAttribute() will always get a new copy from cluster map when stickysession=false, code execution will not see the update to a session attribute made by itself earlier during the same request.

Please let me know whether I am missing something in the code.

Thank you,

- Haixi

**Comment by bilalyasar** [comment]
Hi @haixiliu ,
at first glance, seems you are right. In the case of calling `getSession`method many times ( in the same request) will cause marking `reload` flag as true many times...And this causes losing some updates..
So as you suggested somehow we have to be aware of number of calling times  `getSession` method..
Tomorrow, i will write test for your case..

**Comment by bilalyasar** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/5537

**Comment by asantoso** [comment]
I am using 3.5.4. this issue remains. updateReloadFlag() is invoked multiple times during one request when it passes multiple filters chain, such that session.getAttribute() always returns NULL.
