### ISSUE TITLE
Heartbeat only removes a member if it is related to the master node

### ISSUE THREAD

**Issue by youngm** [hazelcast/hazelcast#5253]
Is posted this on the mailing list but I got impatient and decided to create an issue: https://groups.google.com/d/msg/hazelcast/WiA1xOYf-ys/ZAlytzRAGyoJ

While investigating https://github.com/hazelcast/hazelcast/issues/5209 I was curious why the hearbeat doesn't repair the channel that stops working.

Although I don't have a test case (since it is hard to duplicate simply) when looking through the code it appears that the heartbeat only repairs a channel if the current node is the master [0] or if the node a slave is checking the heartbeat against is the master [1].  Perhaps I'm missing something?

It appears that this is why my channel doesn't self repair when it gets in the messed up state like the state in https://github.com/hazelcast/hazelcast/issues/5209.

Thoughts?

Mike

[0] https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java#L344

[1] https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java#L391

**Comment by youngm** [comment]
Ran into another issue today where where working heart beats may have resolved the issue sooner than me manually restarting the server.  It would be nice if this could get addressed for 3.7.  Doesn't seem like a hard fix.

**Comment by youngm** [comment]
@pveentjer I'd like to attempt to submit a PR for this issue.  Is the general assumption about the issue correct?  Should heartbeat work for connections between any node not just from node to master and visa versa?

Thanks.

**Comment by youngm** [comment]
Hmm....Looks like this code has changed quite a bit.  Perhaps it is not longer an issue.  I'll investigate.  Thanks.

Mike

**Comment by youngm** [comment]
I cannot duplicate this issue with 3.7.  Nice job fixing it. :)

**Comment by youngm** [comment]
Actually I just realized my test didn't really exercise the original issue.

This is still an issue.

To duplicate new I create a hazelcast cluster for 3 or more.  On one of the nodes I use iptables to block communication with another non master node.

`iptables -A OUTPUT -d 'ip of other non master node' -j DROP`

Notice that hazelcast never makes any attempts to reset the connection.

Though this brings up a more complex question.  If resetting the connection doesn't fix the issue what is the appropriate behavior?  Should it notify the master so the node should be removed from the cluster for everyone?  Should those 2 nodes now know that they don't have a connection with each other and now send requests through other nodes that would have gone directly to each other?

I think attempting to connection reset is at least a good first step.

**Comment by mdogan** [comment]
This issue should have been fixed by https://github.com/hazelcast/hazelcast/pull/10137.

Summary of related change is, master node removes the non-heartbeating node directly but non-master node just suspects from it (which is used to elect the new master when current master is suspected too) and closes/resets the connection.
