### ISSUE TITLE
[TEST-FAILURE] writebehind.WriteBehindOnBackupsTest

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5258]
```
01:53:05 Running com.hazelcast.map.mapstore.writebehind.WriteBehindOnBackupsTest
05:05:27 Build timed out (after 250 minutes). Marking the build as aborted.
05:05:28 FATAL: command execution failed
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/557/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/613/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/548/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/562/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/618/console

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/066e196ee5ce6fddb4b079440db37ba153388167
