### ISSUE TITLE
Hazelcast 3.5-SNAPSHOT does not start in OSGI

### ISSUE THREAD

**Issue by jamesceddy** [hazelcast/hazelcast#5274]
When testing the lastest hazelcast from master, hazelcast is not starting as an OSGI bundle. It looks like the osgi package was refactored but the dynamic class loading of the Script engine was missed. "com.hazelcast.osgi.ScriptEngineActivator" should be "com.hazelcast.internal.osgi.ScriptEngineActivator"

Once I changed this hazelcast started ok in Apache Felix.

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/osgi/Activator.java#L69

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/ec39be798b20a3c68f73af4dada185e932989d37
