### ISSUE TITLE
[TEST-FAILURE] MapLoaderMultiNodeTest.testLoadAgain_whenLoadedAllCalledMultipleTimes

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5275]
```
java.lang.AssertionError: expected:<2> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.mapstore.MapLoaderMultiNodeTest.testLoadAgain_whenLoadedAllCalledMultipleTimes(MapLoaderMultiNodeTest.java:125)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8/com.hazelcast$hazelcast/555/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadAgain_whenLoadedAllCalledMultipleTimes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/548/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast/532/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast/534/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadAgain_whenLoadedAllCalledMultipleTimes/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7-Quality-Outreach/com.hazelcast$hazelcast/58/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadAgain_whenLoadedAllCalledMultipleTimes/

**Comment by ajermakovics** [comment]
Should be fixed with https://github.com/hazelcast/hazelcast/pull/5295
