### ISSUE TITLE
wan replication WanBatchReplication can cause OOM on target cluster

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#5280]
3.5-EA2

using com.hazelcast.enterprise.wan.replication.WanBatchReplication as the implementation 

we have found It's possible to cause an OOM on the target cluster.

Using WanBatchReplication with -Dhazelcast.enterprise.wanrep.batch.size=1  will not cause an OOM
but the default of 50 will

using WanNoDelayReplication also suffered from this issue but I has been fixed.

**Comment by jerrinot** [comment]
I'm adding the `Integration` label as I believe @emrahkocaman is working on this.

**Comment by emrahkocaman** [comment]
Moved: https://github.com/hazelcast/hazelcast-enterprise/issues/219
