### ISSUE TITLE
[TEST-FAILURE] MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#5282]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/548/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/535/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/com.hazelcast$hazelcast/535/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadsAll_whenLazyModeAndLoadAll/

**Comment by gurbuzali** [comment]
should be fixed via https://github.com/hazelcast/hazelcast/pull/5295
