### ISSUE TITLE
Combiner's finalizeCombine() is not final operation on a combiner

### ISSUE THREAD

**Issue by zeratul021** [hazelcast/hazelcast#5283]
I tried to use this method to null-out all variables as per contract (...intended to cleanup internal state...) but got null-pointers later.

Once the mapping is done, the *DefaultContext#finish()* first calls the *finalizeCombine()* on all combiners and then calls (suspicious) *requestChunk()* which in turn calls *finalizeChunk() + reset()* that most probably rely on internal state which is now gone.

Maybe I got the usage wrong, would then somebody be able to explain a proper use-case?

**Comment by noctarius** [comment]
Oh thanks, good catch.

**Comment by noctarius** [comment]
Ok the problem is that the combiners are finalized after every mapping phase (per partition) but combiners are not removed from combiner cache.

**Comment by noctarius** [comment]
I broke down finish into to separate calls since the finalization for combiners kicked in too early, you were definitely right :) Thanks again for digging into that!

**Comment by zeratul021** [comment]
Sure, no problem :)
We currently heavily prototyping with Hazelcast and looking in every nook and cranny in the API, especially the Map/Reduce.
