### ISSUE TITLE
[TEST-FAILURE] RingbufferAddAllReadManyStressTest failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5298]
com.hazelcast.ringbuffer.impl.RingbufferAddAllReadManyStressTest.whenNoTTL
com.hazelcast.ringbuffer.impl.RingbufferAddReadOneStressTest.whenLongTTLAndSmallBuffer
com.hazelcast.ringbuffer.impl.RingbufferAsyncAddWithBackoffStressTest.whenTTLEnabled
```
java.lang.AssertionError: No error should have been thrown, but ConsumeThread-1 completed error expected null, but was:<java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: sequence:1 is too large. The current tailSequence is:-1>
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/563/#showFailuresLink

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/566/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/567/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenLongTTLAndSmallBuffer/

**Comment by pveentjer** [comment]
It is on my list for today.

**Comment by pveentjer** [comment]
SHould be resolved.

**Comment by bilalyasar** [comment]
new failure:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/579/console

**Comment by pveentjer** [comment]
I made some minor test modifications. I'm going to close it since it currently doesn't fail. It should not be 'possible' for the test to run for that long since it is bound by time and assertTrueEventually is done to prevent infinite waiting.

**Comment by bilalyasar** [comment]
new failure
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/605/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/606/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/612/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
@pveentjer 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/613/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/614/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
@pveentjer 
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/618/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/627/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/628/console

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/630/testReport/junit/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/639/com.hazelcast$hazelcast/testReport/com.hazelcast.ringbuffer.impl/RingbufferAddAllReadManyStressTest/whenNoTTL/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/640/console

**Comment by pveentjer** [comment]
I'm closing this one since it hasn't happened for 3 months. I have changed some settings in the tests so that it is less problematic.
