### ISSUE TITLE
Lazy deserialize while executing entry-processor

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#5301]
Currently key/value are deserialized prior to execution of entry-processor by default
This leads to need to the domain object at server-side, even if entry-processor never uses it

**Comment by mesutcelik** [comment]
Can we also check that if following methods are requiring domain objects in the classpath?

* ClienMapProxy.keySet(Predicate predicate)
* ClienMapProxy.entrySet(Predicate predicate)
* ClientMapProxy. executeOnEntries(EntryProcessor entryProcessor)

@sancar , 
I think you can comment on this as well. I know you already checked and have some findings.
