### ISSUE TITLE
Implementing our own SSL in hazelcast

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#5307]
Hi all,

I come to know that ssl is enterprise in hazelcast, But for the first one year I cannot buy a enterprise version, Is it possible to implement our own ssl code for hazelcast. Is there any provision for it. Is there an specific interface like context factory or any other way that we can implement our own SSL code between client to server and server to server.

Thanks a lot,
Harry

**Comment by mdogan** [comment]
Please ask your questions on Hazelcast Google Group (https://groups.google.com/forum/#!forum/hazelcast). Github issue list is only for bug reports and enhancement requests.
