### ISSUE TITLE
Hazelcast and Stunnel for own SSL

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#5308]
Hi all,

I made a study on stunnel and configured the stunnel server on hazelcast server port.
    1. Installed the stunnel in my environment
    2. Created the self signed certificate and private key using OpenSSL and added them in stunnel pem file.
    3. Added the corresponding Stunnel Client and Stunnel Server config in the following format

```
                 Stunnel Client                                             Stunnel Server
                       8000               -------------------->                    9999

                Stunnel Server                                              Hazelcast Server
                       9999               -------------------->                    5701
            Where,
                        8000 - Some unused port
                        9999 - Some unused port
                        5701 - Hazelcast Server
            When I do netstat, Am able to see all the process properly running,

                       tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      25914/stunnel4          -   Stunnel Client
                       tcp        0      0 127.0.0.1:9999          0.0.0.0:*               LISTEN      25914/stunnel4          -   Stunnel Server
                       tcp6       0      0 :::5701                 :::*                    LISTEN      30716/java                       -   Hazelcast Server

4. As per the documentation,
            When I want to connect to the destination server, I want to connect via Stunnel client, So I used the corresponding stunnel client port  (Configured as port 8000)  in hazelcast client connection. 
```

It is instead of connecting to 5701 directly, I want to connect to stunnel client via port 8000 as https://192.168.X.X:8000, but when I do that via hazelcast client It does some address validation and shows Unable to connect to server error.  Since address not resolved. 

Is there a way to use our own ssl in hazelcast. Am in a situation of not able to buy a hazelcast enterprise version. please do the needfull. Hazelcast ppl please create a way for me.

**Comment by gAmUssA** [comment]
@hariprasanth1234 for client config you disable smartRouting and try again

```
<hazelcast-client>

    <network>
        <smart-routing>false</smart-routing>
    </network>

</hazelcast-client>
```

**Comment by hariprasanth1234** [comment]
@gAmUssA, 

smart-routing to false, does not make any change, 

May 16, 2015 7:20:38 AM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.4] is STARTING
May 16, 2015 7:20:38 AM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.4] is STARTED
May 16, 2015 7:20:38 AM com.hazelcast.client.spi.impl.ClusterListenerThread
SEVERE: Error while connecting to cluster!
java.lang.IllegalArgumentException: Can't resolve address: https://127.0.0.1:1111/:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200)
	at com.hazelcast.nio.Address.<init>(Address.java:69)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:258)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:86)


Address validation still happens,

For your information, 

Am configuring the https connection in client config, which is completely wrong, 

                ClientConfig clientConfig = new ClientConfig();
		clientConfig.setSerializationConfig(getSerializableFactory());
		clientConfig.getNetworkConfig().setSmartRouting(false);
		clientConfig.getNetworkConfig().addAddress(
				new StringBuilder().append("https://127.0.0.1:1111/").toString());

so is there a way i can configure it, I want to point my client to server communication and server to server communication go via my stunnel client server.


Thanks and Regards,
Harry

**Comment by noctarius** [comment]
You probably have to create your own AddressTranslator to translate between private (localhost) and public address (the other side of the stunnel). You can look into the clients code how it is used for AWS but also not sure it'll work.

**Comment by hariprasanth1234** [comment]
Noctarius,

My main goal is to establish SSL between Hazelcast server to Hazelcast server communication. Please do help me on the server to server communication part.

 What are the changes I need to make it achievable,

I made a study and found a path for server to server communication,

 'com.hazelcast.instance.NodeExtension' in META-INF/services

But still I dont understand its usage completely.

Please do help me on establishing SSL communication between Hazelcast server and Hazelccast server communication  part.

I prefer using sTUNNEL, but if you have any other idea on Hazelcast server to Hazelcast server communication please do share with me. My life is in trouble a week. 

Thanks you so much noctarius.

**Comment by enesakar** [comment]
closing issue. please use google email group if there are further questions.

**Comment by uditkumawat** [comment]
@hariprasanth1234 I am also facing the same problem.Did you get the solution for Stunnel communication between two hazelcast instances ?
