### ISSUE TITLE
@SpringAware/@Autowired annotations does not work on Callable task

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#5323]
I have a simple Callable task like this:

```
@SpringAware
public class SchemaAdministrator implements Callable<Boolean> { 
	
    private SchemaManagement schemaService;
	
    @Autowired
    public void setSchemaService(SchemaManagement schemaService) {
        this.schemaService = schemaService;
    }
    ...........
}
```

the task is created on client node and executed on server node via ExecutorService. The code works perfectly in HZ 3.4.2 but does not work any more in HZ 3.5-EA. The SchemaService setter just not invoked. Please have a look.

Thanks, Denis.

**Comment by mesutcelik** [comment]
Enabling `@SpringAware` by default was causing performance hit so we disabled it by default in 3.5-EA. 
Can you try to add `<hz:spring-aware />` into your context xml?

for more info:
http://docs.hazelcast.org/docs/3.5-EA/manual/html-single/hazelcast-documentation.html#spring-managed-context-with-springaware

**Comment by dsukhoroslov** [comment]
yep, it helps. Thanks a lot!

**Comment by dsukhoroslov** [comment]
BTW, what is a performance issue you mentioned? I have many callable tasks which require injection of dependencies. Do I need to do this in some other way rather then @SpringAware?

**Comment by emrahkocaman** [comment]
Hi @dsukhoroslov ,

`SpringAware` annotation is scanned by `java.lang.Class.getAnnotation(Class)`  (See [SpringManagedContext]( https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/java/com/hazelcast/spring/context/SpringManagedContext.java#L54)) which makes some `synchronized` calls and searches all classpath even a user doesn't use `@SpringAware` at all.

For those users, we've changed the default behaviour and disabled classpath scan by default 
and for the users of  `@SpringAware` `<hz:spring-aware/>` tag is introduced.

When enabled, performance characteristics of `@SpringAware` is the same as before, so I don't think that you need to this in another way.

**Comment by dsukhoroslov** [comment]
thanks!

**Comment by dtitov** [comment]
Is it possible to programmatically set property `<hz:spring-aware />` somewhere? I'm using Java configuration for Spring (Spring Boot), so I don't have any XML files and don't really want to create any...

**Comment by emrahkocaman** [comment]
Hi @dtitov , this is not possible currently.
We need to introduce a system property and/or `@EnableSpringAware` like annotation.
Could you please create an issue for that?

**Comment by dtitov** [comment]
Done.

**Comment by emrahkocaman** [comment]
Thanks.

**Comment by dgabm** [comment]
Hi team,
Sry for adding this issue here, but I saw no related discution elsewhere.
I have the following issue configuring hazelcast spring with spring-aware:

spring-config.xml
`<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:camel="http://camel.apache.org/schema/spring" xmlns:p="http://www.springframework.org/schema/p"
	xmlns:hz="http://www.hazelcast.com/schema/spring"
	xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
       http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd
       http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring-3.2.xsd"
    profile="!test">
...
	<hz:hazelcast id="instance">
	    <hz:config>
	      <hz:spring-aware />
	      <hz:group name="test" password="test"/>
	      <hz:network port="5701" port-auto-increment="false">
	        <hz:join>
	          <hz:multicast enabled="true">
	            <hz:multicast-group>224.2.2.3</multicast-group>
                <hz:multicast-port>54327</multicast-port>
	         </hz:multicast> 
	          <hz:tcp-ip enabled="false">
	            <hz:members>127.0.0.1</hz:members>
	          </hz:tcp-ip>
	        </hz:join>
	        <hz:interfaces enabled="false">
            	<hz:interface>10.10.1.*</hz:interface>
			</hz:interfaces>        
	      </hz:network>
	      	<hz:map name="postgresMap">
		    <hz:map-store enabled="true" implementation="postgresMapStore"
		        write-delay-seconds="0"/>
	    	</hz:map>
	    </hz:config>
	  </hz:hazelcast>`
Exception at startup:
Line 27 in XML document from class path resource [spring-config.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 27; columnNumber: 26; cvc-complex-type.2.4.a: Invalid content was found starting with element 'hz:spring-aware'.  One of '{http://www.hazelcast.com/schema/spring":instancname, ...}is expected.

Tahks in advance for the help.

**Comment by dsukhoroslov** [comment]
the `spring-aware` element was added in HZ v. 3.5. So you must change the xsd name to `hazelcast-spring-3.5.xsd` at the top of your context.

**Comment by dgabm** [comment]
Thanks

**Comment by Elinow** [comment]
Is spring-aware supported for Java configs in Spring? I try to create HazelcastInstance and Config objects via conscructors and factories.
