### ISSUE TITLE
3.5-EA docs incorrect

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#5340]
In the "Upgrading from 3.x" section of the 3.5-EA docs the "Introducing the spring-aware element" section references `<hz:spring-aware enabled="false"/>`; however, the 3.5 Spring XSD has changed the definition of this element to be a type of  `xs:string` with no attributes.  The docs should be updated to reflect this change and, in my opinion, the type should be `xs:boolean`.

**Comment by emrahkocaman** [comment]
Starting with 3.5 `SpringAware` is disabled by default and can be enabled by adding `<hz:spring-aware />` tag. See [Spring Integration]( https://github.com/hazelcast/hazelcast/blob/master/hazelcast-documentation/src/SpringIntegration.md) for sample usage.
I've updated "Upgrading from 3.x" section also.
Thanks for reporting @markathomas .
