### ISSUE TITLE
Thread.sleep in MapProxySupport slows instance start up

### ISSUE THREAD

**Issue by mahileeb** [hazelcast/hazelcast#5349]
I've noticed that our automated tests have slowed down since upgrading to 3.5EA due to the Thread.sleep(1000) at MapProxySupport:664 causing the load of each map to take at least one second.

Is there someway this can be changed to a wait/notify instead of a fixed sleep?

**Comment by mahileeb** [comment]
It's actually worse than 1sec per map, seems more like 4sec. All these maps are empty on start so loading should be instant

**Comment by bwzhang2011** [comment]
@gurbuzali, would you mind introducing the sleep use case in MapProxySupport and how to adjust such parameter just as @mahileeb pointed out.
