### ISSUE TITLE
Partition imbalance with PartitionGroupConfiguration of type HOST_AWARE

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#5355]
During some Simulator runs I noticed a partition imbalance with the  `PartitionGroupConfiguration` we use:
```
    <partition-group enabled="true" group-type="HOST_AWARE">
    </partition-group>
```

I made a cleanup of the `PartitionDistributionTest` and added new test cases with that configuration which fail (#5354). Just clusters with an odd member count seem to fail.

Here is the output of the new tests:
```
testTwoNodes_defaultPartitions_HostAware()
12:05:12,369 [127.0.0.1]:5001 Partition count: 271, nodes: 2, average: 135
12:05:12,395 [127.0.0.1]:5001 Node: 1, local partition count: 135
12:05:12,426 [127.0.0.1]:5001 Node: 2, local partition count: 136

testThreeNodes_defaultPartitions_HostAware()
12:00:18,107 [127.0.0.1]:5030 Partition count: 271, nodes: 3, average: 90
12:00:18,111 [127.0.0.1]:5030 Node: 1, local partition count: 136
12:00:18,122 [127.0.0.1]:5030 Node: 2, local partition count: 68
12:00:18,124 [127.0.0.1]:5030 Node: 3, local partition count: 67
AssertionError: Node: 2, local partition count: 68,
    partition count: 271, nodes: 3, average: 90

testFourNodes_defaultPartitions_HostAware()
12:05:15,691 [127.0.0.1]:5003 Partition count: 271, nodes: 4, average: 67
12:05:15,737 [127.0.0.1]:5003 Node: 1, local partition count: 68
12:05:15,767 [127.0.0.1]:5003 Node: 2, local partition count: 68
12:05:15,768 [127.0.0.1]:5003 Node: 3, local partition count: 67
12:05:15,769 [127.0.0.1]:5003 Node: 4, local partition count: 68

testFiveNodes_defaultPartitions_HostAware()
12:00:00,378 [127.0.0.1]:5006 Partition count: 271, nodes: 5, average: 54
12:00:00,386 [127.0.0.1]:5006 Node: 1, local partition count: 68
12:00:00,400 [127.0.0.1]:5006 Node: 2, local partition count: 45
12:00:00,400 [127.0.0.1]:5006 Node: 3, local partition count: 45
12:00:00,410 [127.0.0.1]:5006 Node: 4, local partition count: 46
12:00:00,411 [127.0.0.1]:5006 Node: 5, local partition count: 67
AssertionError: Node: 2, local partition count: 45,
    partition count: 271, nodes: 5, average: 54

testTenNodes_defaultPartitions_HostAware()
12:05:25,514 [127.0.0.1]:5007 Partition count: 271, nodes: 10, average: 27
12:05:25,548 [127.0.0.1]:5007 Node: 1, local partition count: 27
12:05:25,578 [127.0.0.1]:5007 Node: 2, local partition count: 27
12:05:25,580 [127.0.0.1]:5007 Node: 3, local partition count: 27
12:05:25,581 [127.0.0.1]:5007 Node: 4, local partition count: 27
12:05:25,581 [127.0.0.1]:5007 Node: 5, local partition count: 27
12:05:25,582 [127.0.0.1]:5007 Node: 6, local partition count: 27
12:05:25,583 [127.0.0.1]:5007 Node: 7, local partition count: 27
12:05:25,584 [127.0.0.1]:5007 Node: 8, local partition count: 28
12:05:25,585 [127.0.0.1]:5007 Node: 9, local partition count: 27
12:05:25,591 [127.0.0.1]:5007 Node: 10, local partition count: 27

testFifteenNodes_defaultPartitions_HostAware()
12:00:33,300 [127.0.0.1]:5033 Partition count: 271, nodes: 15, average: 18
12:00:33,301 [127.0.0.1]:5033 Node: 1, local partition count: 17
12:00:33,302 [127.0.0.1]:5033 Node: 2, local partition count: 16
12:00:33,305 [127.0.0.1]:5033 Node: 3, local partition count: 17
12:00:33,309 [127.0.0.1]:5033 Node: 4, local partition count: 20
12:00:33,309 [127.0.0.1]:5033 Node: 5, local partition count: 17
12:00:33,310 [127.0.0.1]:5033 Node: 6, local partition count: 19
12:00:33,310 [127.0.0.1]:5033 Node: 7, local partition count: 20
12:00:33,310 [127.0.0.1]:5033 Node: 8, local partition count: 17
12:00:33,310 [127.0.0.1]:5033 Node: 9, local partition count: 17
12:00:33,310 [127.0.0.1]:5033 Node: 10, local partition count: 19
12:00:33,310 [127.0.0.1]:5033 Node: 11, local partition count: 17
12:00:33,310 [127.0.0.1]:5033 Node: 12, local partition count: 20
12:00:33,312 [127.0.0.1]:5033 Node: 13, local partition count: 19
12:00:33,312 [127.0.0.1]:5033 Node: 14, local partition count: 19
12:00:33,313 [127.0.0.1]:5033 Node: 15, local partition count: 17
AssertionError: Node: 1, local partition count: 17,
    partition count: 271, nodes: 15, average: 18
```

**Comment by Donnerbart** [comment]
Note: The unit tests and the Simulator tests were all executed on a single machine with multiple Hazelcast instances.

**Comment by jerrinot** [comment]
@Donnerbart: Is this still reproducible with the latest SNAPSHOT?

**Comment by Donnerbart** [comment]
I think so, since I added new tests which test for this imbalance. The imbalance throws an `AssertionError` in the internal test method, which those test cases expect: `@Test(expected = AssertionError.class)` So as long as the tests are green, the imbalance should still be there.

**Comment by pveentjer** [comment]
I believe there is not really an permanent imbalance, but a temporary one. 

https://github.com/hazelcast/hazelcast/issues/8213

This one shows the process of migration and it can take quite some time.

**Comment by jerrinot** [comment]
I believe [the test](https://github.com/hazelcast/hazelcast/pull/5354/files#diff-3af7f4240e2f48e837be2c2a4999d8aeR90) David wrote shows it's not a temporary condition. There is still a very minor imbalance. 

`local partition count: 17, partition count: 271, nodes: 15, average: 18`
`271 / 15 = 18.066` -> members should have 18 or 19 partitions. however there was at least one member with 17 partitions. 

the test does not take backup replicas into consideration, this could possible explain it.

**Comment by metanet** [comment]
> local partition count: 17, partition count: 271, nodes: 15, average: 18
271 / 15 = 18.066 -> members should have 18 or 19 partitions. however there was at least one member with 17 partitions.

This is completely safe. Partition distribution algorithm does not pursue exactly average partition distribution. It allows a small difference. 

Another thing is what happens with odd number of cluster members, for instance: `testFiveNodes_defaultPartitions_HostAware()`.

When you start 5 nodes, they all share the same host and fall into a single member group. Before partition distribution is done, they are divided into two member groups since there is more than 1 node in the cluster to at least guarantee a single backup. Lets say we have two groups as [Node1, Node2] and [Node3, Node4, Node5]. After this point, partition distribution balance is considered among the groups, not the nodes. So a distribution like [68, 68], [45, 45, 45] is ok for the distribution algorithm since total partition count of each group is very close to each other.
