### ISSUE TITLE
Hazelcast 3.0 - Map Local Entry Listener gives no Value on entryEvicted

### ISSUE THREAD

**Issue by notz** [hazelcast/hazelcast#537]
I have entry listener on a maps that listens on local evicted items. The map is defined as <Long, GenericEvent>. GenericEvent is Serializable. 

On entryEvicted(EntryEvent<Long, GenericEvent> entryEvent) the call to entryEvent.getValue() always returns a null value.

**Comment by TheBellman** [comment]
Has this behaviour reverted? Using 3.6.2, both tests shown above consistently are giving me a null value. I have also tried specifying retention of the value using 

    addLocalEntryListener(new EventCacheListener(), (Predicate<String, String>) mapEntry -> true, true);

where `EventCacheListener` implements `EntryEvictedListener`. Note that this is occurring during development, with a single-node cluster.

**Comment by TheBellman** [comment]
Please ignore my previous - the problem existed between keyboard and chair. In order to observe the value of the entry that was evicted, it is necessary to use 

    entry.getOldValue()

rather than

    entry.getValue()
