### ISSUE TITLE
hazelcast keys partition issue

### ISSUE THREAD

**Issue by evredinka** [hazelcast/hazelcast#5371]
then i run two hazelcast instances with following configuration, after theese instanses form a cluster of 2 members, i execute instanse.getMap(myMap).size (to start loading data to myMap)

as i can see from 1000 elements (it is the expected map size), the first node has near 514, the other near 63 entries

so not all data are loading and partitions are not equal
![2015-05-26_124813](https://cloud.githubusercontent.com/assets/12608352/7809794/80180c4e-03a5-11e5-91ef-07913918ede9.jpg)

without element with "instanse-ref" everything works fine, data is distributed through two members in equal portions

**Comment by bilalyasar** [comment]
@evredinka I tried your case with many different scenarios.. in all scenarios  every node has nearly equal data portions and total size was 1000.
In your case, do you observe some data loss? 
Can you provide more scenario detail?
If i don't provide `instance-ref`, execution goes to fail-fast. What is your hz version?
very little note: hazelcast only guarantees that data's will be distributed nearly equal over nodes. For 1000 key, it can be (512,488).

**Comment by evredinka** [comment]
@bilalyasar, i'm using hazelcast-all (v. 3.4.2)

the scenatio is: to start launcher main method: the first instance is up and i can see that loadAllKeys() method is called, then start launcher method again: the second instance is up and loadAllKeys() is called too, after two instances is up i try lo load data in my map, from logs i can see that loadAll() is called
with instance-ref loadAllKeys() is called before i touch the map (data - 1000 integers - is not full loaded and not in equal portion)
without instance-ref loadAllKeys() is called after i touch the map(data - 1000 integers - is full loaded and in equal portions)

i use jConsole to check data in my IMap with localOwnEntryCount value

so my hazelcast context looks like in the picture i have already provided

i use main class to start one instance, than another:

import com.hazelcast.core.HazelcastInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.applet.AppletContext;
import java.util.concurrent.TimeUnit;

public class Launcher {

    private static final Logger log = LoggerFactory.getLogger(Launcher.class);

    public static void main(String[] args) throws InterruptedException {
        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("hz-context.xml");

        HazelcastInstance instance = (HazelcastInstance) context.getBean("hzInstance");

        log.info("-----> cluster size: {}", instance.getCluster().getMembers().size());

        if (instance.getCluster().getMembers().size() == 2) {
            log.info("-----> cluster size: {}", instance.getCluster().getMembers().size());
            instance.getMap("test-map").size();
        }
    }

}

and my TestMapStore:

import com.hazelcast.core.MapStore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.*;
import java.util.stream.IntStream;

import static java.util.stream.Collectors.toMap;
import static java.util.stream.Collectors.toSet;

public class TestMapStore implements MapStore<Integer, Object> {

    private static final Logger log = LoggerFactory.getLogger(TestMapStore.class);

    @Override
    public void store(Integer integer, Object o) {
    }

    @Override
    public void storeAll(Map<Integer, Object> map) {
    }

    @Override
    public void delete(Integer integer) {
    }

    @Override
    public void deleteAll(Collection<Integer> collection) {
    }

    @Override
    public Object load(Integer integer) {
        log.debug("load.enter;");
        return null;
    }

    @Override
    public Map<Integer, Object> loadAll(Collection<Integer> collection) {
        log.debug("loadAll.enter;");
        Set<Integer> integerSet = IntStream.rangeClosed(1, 1000).boxed().collect(toSet());
        Map<Integer, Object> map = integerSet.stream().collect(toMap(Integer::intValue, (o) -> o));
        return map;
    }

    @Override
    public Set<Integer> loadAllKeys() {
        log.debug("loadAllKeys.enter;");
        Set<Integer> integerSet = IntStream.rangeClosed(1, 1000).boxed().collect(toSet());
        return integerSet;
    }

}

**Comment by evredinka** [comment]
is there any news?
p.s. it seems like there is no such problem in new hz 3.5

**Comment by mdogan** [comment]
There were many changes/fixes in MapLoader design. If you still observe the problem, please reopen the issue.
