### ISSUE TITLE
[TEST-FAILURE] MergePolicyTest test failures

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5394]
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
```
com.hazelcast.map.MergePolicyTest.testPutIfAbsentMapMergePolicy
com.hazelcast.map.MergePolicyTest.testHigherHitsMapMergePolicy
com.hazelcast.map.MergePolicyTest.testCustomMergePolicy
com.hazelcast.map.MergePolicyTest.testLatestUpdateMapMergePolicy
com.hazelcast.map.MergePolicyTest.testPassThroughMapMergePolicy

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/489/

**Comment by eminn** [comment]
This problem has been fixed by https://github.com/hazelcast/hazelcast/commit/e725487bbcc32a781d091a101534fd468c8f3c50
