### ISSUE TITLE
Corrupted archive

### ISSUE THREAD

**Issue by jsirex** [hazelcast/hazelcast#5412]
1. Go to http://hazelcast.org/download/
2. Click download tar.gz

Got:
```
tar zxf hazelcast-3.4.2.tar.gz 
tar: This does not look like a tar archive
tar: Skipping to next header

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Re-downloading archive can produce different archive (wrong size 59Mb vs 45Mb)

**Comment by kobalski** [comment]
Hi, 
@jsirex I have tried to download the file hazelcast-3.4.2.tar.gz from  http://hazelcast.org/download/. There seems to be no problem, file size has to be 68.1Mb. Are you behind a proxy, because there is an old issue just like you mentioned. (https://github.com/hazelcast/hazelcast/issues/4793). I could not reproduce your case for now.

**Comment by jsirex** [comment]
May be it is related. Anyway I'm planning to download this archive automatically (I'm using Chef). I'll check it from another place later.

And one more useful thing: could you please publish checksums of your artifacts, so I can prove that I'd downloaded archive correctly.

**Comment by gAmUssA** [comment]
@jsirex Hazelcast artifacts that we publish to the maven central have SHA1 checksums. For example

http://search.maven.org/#artifactdetails%7Ccom.hazelcast%7Chazelcast-all%7C3.5-EA%7Cjar 

Here is a url format that you can use in your automation scripts

```
String baseUrl = "http://repo1.maven.org/maven2";
String url = format("%s/com/hazelcast/%s/%s/%s-%s.jar", baseUrl, artifact, version, artifact, version);
```

I hope it helps
Cheers,
Vik

**Comment by jsirex** [comment]
Probably I have posted issue to wrong sub-project....

I don't need a jar but distributive of hazelcast standalone (hazelcast-3.4.2.tar.gz). May be it was temporary issues with site or with Internet connection. Now I can download archive without issues.
But I still don't know its checksum.

**Comment by jsirex** [comment]
UPD: 
Downloading manually `hazelcast-3.4.2.tar.gz` from hazelcast.org with browser has checksum:
`484a1a0b53f8bbddd9ee61917183201ddd2eb74262efb460e2d14fc355f0fc26`

Downloading file via wget:
```bash
$ wget -c 'http://download.hazelcast.com/download.jsp?version=hazelcast-3.4.2&type=tar&p=109629376' -O /tmp/1.tar.gz
$ sha256 /tmp/1.tar.gz
55b4ebd549b0ef4b55e20db325543736be7246cd6e46ea6ab8783667477d3fbc /tmp/1.tar.gz
$ wget -c 'http://download.hazelcast.com/download.jsp?version=hazelcast-3.4.2&type=tar&p=109629376' -O /tmp/2.tar.gz
$ sha256sum /tmp/2.tar.gz 
282eb2f7fe4def63ddc9367968302392b9e8679bb189dc5edab3c53bcc2b99ce  /tmp/2.tar.gz
```
Now, I don't know is my downloaded archive valid.

PS. Also I unable to find this installation archive in maven repo (only jars).

**Comment by jsirex** [comment]
Actually I'd figured out it. For standalone installation I don't need whole archive but only single jar.

Now I understood what @gAmUssA talking about.

I can build my own package on runtime using only this library
