### ISSUE TITLE
[TEST-FAILURE]  ExecutionDelayTest.testExecutorRetriesTask_whenOneNodeShutdowns

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5422]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/450/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.executor/ExecutionDelayTest/testExecutorRetriesTask_whenOneNodeShutdowns/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3265/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.executor/ExecutionDelayTest/testExecutorRetriesTask_whenOneNodeShutdowns/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/84/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.executor/ExecutionDelayTest/testExecutorRetriesTask_whenOneNodeShutdowns/

**Comment by toktarev** [comment]
The problem is (for 2 nodes):

Node A (owner)
Node B

Client sends Auth Request to node B
Node A dies
Node B checks that A is dead and send AuthenticationException to the client

**Comment by toktarev** [comment]
https://github.com/hazelcast/hazelcast/pull/5447/files

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5447

@toktarev ,
Can you please include following keywords in your commit messages? This way issue will be closed when PR is merged.
https://help.github.com/articles/closing-issues-via-commit-messages/
