### ISSUE TITLE
Mapstore Asynchronous not working in using as common map store factory

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#5436]
Hi all,

Am using the custom commonMapStoreFactory by implementing the interface 'MapStoreFactory<String, Object>'

I call commonMapStore implementation using newMapStoreFactory method available in it.

Everything works fine,

               final MapStoreConfig mapStoreConfig = new MapStoreConfig();
		mapStoreConfig.setFactoryClassName(
				"org.db.mapstore.CommonMapStoreFactory");
		mapStoreConfig.setEnabled(true);
		mapStoreConfig.setWriteDelaySeconds(1);

But what happens is.

When I do,   map.put("1","test");   

It synchronously calls the 'load' method then 'store' method in commonMapStore, As per documentation it has to be in Asynchronous way since my writeDelay is 1 second, Why it is synchronous?

1. Is there a parameter I need to change?

                MapConfig mapConfig = new MapConfig();
		mapConfig.setName(DatabaseConstants.test);
		mapConfig.setMapStoreConfig(getMapStoreConfig());
		hazelcastMapConfigs.put(DatabaseConstants.test, mapConfig);

NOTE:  Where getMapStoreConfig is what I have given above

Thanks and Regards,
Hari Prasanth.L

**Comment by ajermakovics** [comment]
Hi @hariprasanth1234 

`put` needs to return the old value so it calls `load` to get it. If you don't need the old value try `imap.set`

**Comment by hariprasanth1234** [comment]
Thanks @ajermakovics...

**Comment by ajermakovics** [comment]
You're welcome! Let's close the issue?
