### ISSUE TITLE
[TEST-FAILURE]  ClientNearCacheTest.putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCacheWithBinaryInMemoryFormat

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5437]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3268/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.cache.nearcache/ClientNearCacheTest/putToCacheAndUpdateFromOtherNodeThenGetUpdatedFromClientNearCacheWithBinaryInMemoryFormat/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK8/451/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3269/testReport/

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/5443
