### ISSUE TITLE
[TEST-FAILURE] IbmJDK1.6 Errors

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5455]
During Last two builds, we had lots of IBM JDK 1.6 failures. 

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/569/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/568/

**Comment by toktarev** [comment]
I suppose that  problem is in MapReduceTest
Here in HazelcastParallelClassRunner

private static final int MAX_THREADS = !TestEnvironment.isMockNetwork() ? 1
               : Math.max(Runtime.getRuntime().availableProcessors(), 8);

We acquire all cores for tests at the same time

We have:
MapReduceTest has more then 16 tests, 16 cores on jenkins.

I suggest to reduce amount of parallel tests to Runtime.getRuntime().availableProcessors()/2.

It helped on my test build.

**Comment by toktarev** [comment]
https://github.com/toktarev/hazelcast/commit/d7551a8f9ae3635ebab884938c5c97ee7055fca8

**Comment by mesutcelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/pull/5465

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/581/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/580/
we still have failures.

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/588/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/589/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-IbmJDK1.6/258/

**Comment by mesutcelik** [comment]
no recent failure... closing...
