### ISSUE TITLE
TransactionContext.getXAResource().setTransationTimeout(..) doesn't work

### ISSUE THREAD

**Issue by pablolagreca** [hazelcast/hazelcast#5483]
When I use XA in hazelcast TransactionContext.getXAResource().setTransationTimeout(..) doesn't work. It only works if I set the timoeut using TransactionOptions. It should work with setTransactionTimeout(..) to honor de XAResource interface.

**Comment by gurbuzali** [comment]
which version are you using ? should be fixed in 3.5-EA and latest master
please see https://github.com/hazelcast/hazelcast/pull/5350

**Comment by gurbuzali** [comment]
should be fixed in 3.5, please reopen if you still encounter the issue
