### ISSUE TITLE
Hazelcast Client: set OutOfMemoryHandler

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#5484]
Provide API `HazelcastClient.setOutOfMemoryHandler` for setting client `OutOfMemoryHandler` same way as `Hazelcast. setOutOfMemoryHandler`

**Comment by gurbuzali** [comment]
you can use `OutOfMemoryErrorDispatcher.registerClient(client);` as a workaround

**Comment by sancar** [comment]
Fixed via https://github.com/hazelcast/hazelcast/commit/764ff063ffba3cb5209e5d69b6829ed7b99f715c

**Comment by gAmUssA** [comment]
@gurbuzali Yes, this is exactly how I work around this ;). Thank you

**Comment by bwzhang2011** [comment]
@sancar, any update with hazelcast client support with reliable topic ?

**Comment by pveentjer** [comment]
This is not the appropriate topic to ask this question.
