### ISSUE TITLE
Memory leak in hazelcast cluster caused by race condition on node join

### ISSUE THREAD

**Issue by PetroSemeniuk** [hazelcast/hazelcast#5485]
The way how issue is reproducible in _our_ environment
* Start _node1_
* Load _node1_ with large number of http requests (each request will result into hundreds of hazelcast operations)
* Starting _node2_ when load is running
* You'll see map size node _node2_ growing above configured max size. Issue is _not_ reproducible if load is applied after node joined.

I was unable to reproduce issue using unit test, however when debugging it looks like check in 
MaxSizeChecker#isEvictablePerNode doesn't succeed (hz. v3.4.2) and number of items returned is less than number if item returned by map.size.

Issue is reproducible on hz 3.3.1 as well.

Would be awesome to know if this is known issue or/and if any workaround exist.

**Comment by PetroSemeniuk** [comment]
Ok, after few days of debugging I found what is wrong. 
Our vase (wildcard) config is to allow near caches for all maps with max size unspecified. Then later during lifetime we requesting map with correct mapconfig and it correctly update max size (we are doing update at map container level).

However race condition happens when invalidation event is sent and picked up by InvalidateNearCacheOperation, it will create near cache with defauk (unbounded) size which is MAX_INTEGER.

https://github.com/atlassian/hazelcast/pull/29/files addresses this (soon to be merged int atlassian fork which I believe will be soon merged into hazelcast master as well)

**Comment by PetroSemeniuk** [comment]
@ahmetmircik @gurbuzali hey guys, given that final intention of https://github.com/atlassian/hazelcast/pull/29/files is ti be merged into hazelcast master, can I have early code review feedback on it?

**Comment by bwzhang2011** [comment]
@PetroSemeniuk, any process with such issue ? was it also confirmed with hz3.5+ ?

**Comment by bwzhang2011** [comment]
@PetroSemeniuk, any update with such issue ?

**Comment by ahmetmircik** [comment]
Hi @PetroSemeniuk, closing this issue, we are not supporting dynamic configuration of near-cache. You need to provide configuration before creation of map and it shouldn't be changed during lifetime.
