### ISSUE TITLE
[TEST-FAILURE] LocalTopicStatsImplTest timeout

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5500]
```
01:54:47 Running com.hazelcast.monitor.impl.LocalTopicStatsImplTest
03:50:06 Build timed out (after 150 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/95/console

**Comment by Donnerbart** [comment]
I can't see any reason for this. The whole monitor package tests are quite simple and complete in ~1 second on my machine.

I just did a very small change to those tests to make all tests compatible with  `@Repeat` and ran the tests for 100k times. No problems so far.

https://github.com/hazelcast/hazelcast/commit/a951c7e

**Comment by bilalyasar** [comment]
Did you try to reproduce failure in cloudbees environment?

**Comment by Donnerbart** [comment]
Not yet. The test is really very simple, it's not even starting a Hazelcast instance. The only thing I found so far was the member variable thing which prevented the use of `@Repeat()`.

If it fails again I will spend more time on this. Right now I'm not 100% if the other test failures had any influence on this or not :(
