### ISSUE TITLE
Give HazelcastClient an option to handle connecting lazily and in non-blocking manner

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#552]
If the cluster is not yet available when a client is started it would be fine to give HazelcastClient (in Hazelcast 3) an option to try to connect an infinite times but does not block. So it should behave quite similar to a normal member node (but just does not open a cluster).
If not connected there could be an NotConnectedException or requests could be queued the same way it happens when client reconnects after loosing cluster connection due to member outage.
With this option it would be possible to use a client as an replacement for Hazelcast lite members.

**Comment by sancar** [comment]
Same request by community
http://stackoverflow.com/questions/29677561/how-to-handle-error-being-thrown-by-clusterlistenerthread-during-the-instantiati/33285200#33285200

**Comment by dzidor** [comment]
Hello everybody,

Yes my use case is I have a Hazelcast client bean with Spring. And it will connect to a Hazelcast server node to get data if it's up otherwise my database, but of course my Hazelcast server instance may be down and I want my app to continue dealing with database in this case. How can I handle that with my app Hazelcast/Spring client.

Any ideas, please?

**Comment by marcolattarulo** [comment]
I managed to connect asynchronously creating the hazelcast client in a different thread, using the Future class.
It works, the connection fails as far as the Hazelcast instance is down, and it is established properly when the hazelcast  instance goes up, but in the meantime my microservice starts and works without problem (but obviously it does not rely on the Hazelcast datas... in my case it's not a problem)

**Comment by webashutosh** [comment]
Hi,

Can someone please post an example of how client creation was offloaded to another thread (I am working in a Spring environment ... currently declared the client as a bean in the application context, which is causing failures during application startup if the cluster is down)

Thanks!

**Comment by dbrimley** [comment]
Looks like this is an earlier version of an issue recently create here https://github.com/hazelcast/hazelcast/issues/9692

**Comment by sancar** [comment]
Fixed via https://github.com/hazelcast/hazelcast/pull/10729
ClientConnectionStrategyConfig is introduced to configure clients to be open lazily in 3.9 
For details you can see this doc:
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#configuring-client-connection-strategy
