### ISSUE TITLE
Partition Groups does not work

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#5527]
the issue is discussed here: https://groups.google.com/forum/#!topic/hazelcast/7aPUQxk6Rbw

**Comment by dsukhoroslov** [comment]
the test case is:

import java.util.Set;

import junit.framework.Assert;

import org.junit.Test;

import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MemberGroupConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.config.PartitionGroupConfig;
import com.hazelcast.config.PartitionGroupConfig.MemberGroupType;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;

public class PartitionGroupTest {

	@Test
	public void testPartitionGroups() throws Exception {
	
		String adminIP = "127.0.0.1";
		String localIP = "xx.xx.xx.xx"; // set your local address here
		
		Config adminConfig = new Config();
		adminConfig.getNetworkConfig().setPort(5781);
		adminConfig.getNetworkConfig().setPortAutoIncrement(true);
		NetworkConfig network = adminConfig.getNetworkConfig();
		JoinConfig join = network.getJoin();
		join.getMulticastConfig().setEnabled(false);
		join.getTcpIpConfig().addMember(adminIP).addMember(localIP).setEnabled(true);
		PartitionGroupConfig partitionGroupConfig = adminConfig.getPartitionGroupConfig();
		partitionGroupConfig.setEnabled(true).setGroupType(MemberGroupType.CUSTOM);
		MemberGroupConfig adminGroupConfig = new MemberGroupConfig();
		adminGroupConfig.addInterface(adminIP);
		MemberGroupConfig cacheGroupConfig = new MemberGroupConfig();
		cacheGroupConfig.addInterface(localIP);
		partitionGroupConfig.addMemberGroupConfig(adminGroupConfig);
		partitionGroupConfig.addMemberGroupConfig(cacheGroupConfig);
		HazelcastInstance admin = Hazelcast.newHazelcastInstance(adminConfig);
		
		IMap<Long, String> adminMap = admin.getMap("test");
		for (long i=0; i < 100; i++) {
			adminMap.put(i, String.valueOf(i));
		}

		Config cacheConfig = new Config();
		cacheConfig.getNetworkConfig().setPort(5781);
		cacheConfig.getNetworkConfig().setPortAutoIncrement(true);
		network = cacheConfig.getNetworkConfig();
		join = network.getJoin();
		join.getMulticastConfig().setEnabled(false);
		join.getTcpIpConfig().addMember(adminIP).addMember(localIP).setEnabled(true);
		partitionGroupConfig = cacheConfig.getPartitionGroupConfig();
		partitionGroupConfig.setEnabled(true).setGroupType(MemberGroupType.CUSTOM);
		//MemberGroupConfig adminGroupConfig = new MemberGroupConfig();
		//adminGroupConfig.addInterface(adminIP);
		//MemberGroupConfig cacheGroupConfig = new MemberGroupConfig();
		//cacheGroupConfig.addInterface(localIP);
		partitionGroupConfig.addMemberGroupConfig(adminGroupConfig);
		partitionGroupConfig.addMemberGroupConfig(cacheGroupConfig);
		HazelcastInstance cache = Hazelcast.newHazelcastInstance(cacheConfig);

		Thread.sleep(5000);
		
		Set<Long> keys = adminMap.localKeySet();
		System.out.println("admin keys size is: " + keys.size());
		IMap<Long, String> cacheMap = cache.getMap("test");
		keys = cacheMap.localKeySet();
		System.out.println("cache keys size is: " + keys.size());
		Assert.assertTrue(keys.size() == 0);
	}	
	
}

**Comment by pveentjer** [comment]
Which HZ version?

**Comment by dsukhoroslov** [comment]
3.5 and earlier

**Comment by bwzhang2011** [comment]
@dsukhoroslov, @pveentjer , any update with such issue ?

**Comment by jerrinot** [comment]
Hi @dsukhoroslov,

this is not a bug; It's expected behaviour. See [this](https://groups.google.com/d/msg/hazelcast/7aPUQxk6Rbw/9OvUC8cxAwAJ) for details.

Feel free to re-open this issue if you still think there is a bug.
