### ISSUE TITLE
Spring xml config: boolean type validation

### ISSUE THREAD

**Issue by asidyakin** [hazelcast/hazelcast#5528]
In spring config, when trying inject boolean property in hazelcast bean(<hz:hazelcast:....</hz:hazelcast)
throw exception
Caused by: org.xml.sax.SAXParseException: cvc-datatype-valid.1.2.1: '${statistics.enabled}' is not a valid value for 'boolean'.

solutions:
1. Custom XMLBeanDefinitionReader with disabled schema validation
2. Not XML configuration (java)

Such approachs aren't applicable in our project.

Need all boolean properties change from xs:boolean to xs:string in hazelcast-spring.xsd

**Comment by dsukhoroslov** [comment]
the same issue is mentioned here: https://github.com/hazelcast/hazelcast/issues/4700

**Comment by mesutcelik** [comment]
@bilalyasar ,

is it possible fail fast here by checking the value is either spring placeholder like `${statistics.enabled}` or in a type of it should be i.e. `boolean`?

**Comment by bilalyasar** [comment]
@mesutcelik , no it is not possible, in xsd we couldn't define multiple types.

**Comment by mesutcelik** [comment]
not in the xsd but programatically.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5590
