### ISSUE TITLE
WebFilter broken in 3.4.3 and 3.5 - getAttribute always returns null - existing tests are failing

### ISSUE THREAD

**Issue by dfex55** [hazelcast/hazelcast#5531]
In 3.4.3 and 3.5 the WebFilter is broken (again).

The test written for issue #2187 fails for me with deferred-write set to true.
(17 WebFilter tests in total are failing for me)

You can reproduce this error with the following steps
- set deferred-write to true
- set an attribute on an empty session (e.g. setAttribute("key", "test"))
- get the attribute for the same key before it is copied to the distributed map (e.g. in the same request: getAttribute("key"))

The expected result is to get "test", but the current implementation always returns null.

I think the test got broken with the commit 98850a51c610de0259cede1eea5f1054af4b0b7f

In HazelcastHttpSession.setAttribute a new LocalCacheEntry is created:
```java
    entry = new LocalCacheEntry(transientEntry);
```
which uses the following constructor:
```java
    public LocalCacheEntry(boolean transientEntry) {
        this.transientEntry = transientEntry;
        this.reload = true;
    }
```
As you can see, reload is set to true, which causes the HazelcastHttpSession.getAttribute method to load the key from the distributed map:
```java
public Object getAttribute(final String name) {
        LocalCacheEntry cacheEntry = localCache.get(name);
        Object value = null;

        if (cacheEntry == null || cacheEntry.isReload()) {
            try {
                value = webFilter.getClusteredSessionService().getAttribute(id, name);
                if (value == null) {
                    return null;
                }
         …
```
As the distributed map is empty, null will be returned.

Just as a note:

The other constructor of LocalCacheEntry does not set reload to true:
```java
 public LocalCacheEntry(boolean transientEntry, Object value) {
        this(transientEntry);
        this.value = value;
 }
```
Also LocalCacheEntry.setValue doesn't set reload to false. So if a value is set on an entry that has reload set to true, the value will get lost when calling getAttribute.

HazelcastHttpSession.getAttribute creates a LocalCacheEntry but never puts it in the localCache - wondered if it is intentional.

**Comment by bilalyasar** [comment]
Hi @dfex55,
for the your set/get case, you are right. Seems it is bug and i sent a PR for that bug.
And for failing other tests, there can be some network/connection problem in your computer, can you try again with closing multicast in tests? https://github.com/hazelcast/hazelcast/blob/master/hazelcast-wm/src/test/webapp/WEB-INF/hazelcast.xml#L29 and you need to enable tcp/ip with interface `127.0.0.1`
These tests are running in our CI continuously   and we don't see such failures. like 17 failures.

**Comment by jnehlmeier** [comment]
@bilalyasar The test failures we see are part of the JettyWebFilterTest and TomcatWebFilterTest which both are in the "NightlyTest" JUnit category. So you would need to use the a corresponding Maven profile to execute them. I have used the "nightly-build" profile.

I have re-executed the tests with disabled multicast and instead used tcp ip on 127.0.0.1 but tests are still failing. You can see the results in: https://gist.github.com/jnehlmeier/0f52624d496afa2cc433

To execute the tests I used a fresh checkout of the 3.5 release and executed
```
export JAVA_HOME=...path to java 8...
mvn -DskipTests clean install
mvn -P nightly-build -pl hazelcast-wm test
```
This has been done on Mac OS 10.9.5 with Oracle JDK 8_u45.

**Comment by bilalyasar** [comment]
@jnehlmeier can you try again with closing network? e.g: wifi.

**Comment by dfex55** [comment]
@bilalyasar Network is fully functional. The errors do not happen because hazelcast has problems creating a cluster or has communication problems.

Can you confirm JettyWebFilterTest is running without errors for you with the 3.5 tag?

In your CI builds the JettyWebFilterTest is _not_ executed.

**Comment by mesutcelik** [comment]
Hi @dfex55 ,

We have nightly build which is executed through *nightly-build* profile and we don't see any problem. 
Can you please give us more info about which tests are failing in your local, possibly with stack traces?

**Comment by jnehlmeier** [comment]
@mesutcelik 
I work on the same team as dfex55 and I have executed the tests.

I have updated `hazelcast/pom.xml` to activate hazelcast logging during the `nightly-build` tests by changing `-Dhazelcast.logging.type=none` to `-Dhazelcast.logging.type=jdk`. The `logging.properties` file I have used contained 
```
handlers = java.util.logging.ConsoleHandler
.level = FINE
```
and I have launched the tests using 
```
mvn -DskipTests clean install
mvn -Djava.util.logging.config.file=/path/to/logging.properties -P nightly-build -pl hazelcast-wm test
```
I have updated the GIST https://gist.github.com/jnehlmeier/0f52624d496afa2cc433 to include full maven output as well as surefire outputs including hazelcast log output. Basically the `JettyWebFilterTest` and `TomcatWebFilterTest` failed quite a bit while `SpringAwareWebFilterTest` and `WebFilterSessionCleanupTest` worked without issue. The GIST only includes the surefire output of the `JettyWebFilterTest `.

The output is the result of running the tests using TPC/IP config instead of multicast config.To do that I changed the src/test/webapp/WEB-INF/hazelcast.xml
```
-            <multicast enabled="true">
+            <multicast enabled="false">
                 <multicast-group>224.2.2.3</multicast-group>
                 <multicast-port>54327</multicast-port>
             </multicast>
-            <tcp-ip enabled="false">
+            <tcp-ip enabled="true">
+            <member>127.0.0.1</member>
             </tcp-ip>

-        <interfaces enabled="false">
-            <interface>10.10.1.*</interface>
+        <interfaces enabled="true">
+            <interface>127.0.0.1</interface>
         </interfaces>
```

I trust you when you say these tests work for you, maybe the log output helps you to spot something unusual. As already said this has been done on Mac OS 10.9.5 and Java 8_u45 using Maven 3.1.1.

**Comment by kobalski** [comment]
Hi @jnehlmeier ,
We will try to run our tests with the configurations you have provided, meantime can you try running tests with  `-Djava.net.preferIPv4Stack=true`. Sometimes, these tests can fail on Macs due to IPV6 interface.

**Comment by jnehlmeier** [comment]
@kobalski while in my provided GIST a total of 53 tests failed with `-Djava.net.preferIPv4Stack=true` only 39 failed, although I am not sure if that property is really responsible for the change. Maybe its more like a timing issue.

However I have run the tests with the above configuration on our CI server (Ubuntu, OpenJDK 7 and Oracle JDK 8) and they all work without issues. Seems like a Mac OS problem.

**Comment by bilalyasar** [comment]
@jnehlmeier ,  I created a public build for testing and couldn't see any problem.
https://hazelcast-l337.ci.cloudbees.com/job/session-replication-test/

**Comment by jnehlmeier** [comment]
@bilalyasar, yeah on Linux/Ubuntu things work fine for us as well as said in my previous comment. However on two different Mac OS hosts the tests fail. If you have access to Mac OS then try running tests on Mac OS using Oracle JDK. For now we just ignore it and run tests on Linux if we need to.

Maybe issue #5188 is kind of related and @davidsiefert has also used OS X.

**Comment by bilalyasar** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/5537
