### ISSUE TITLE
minimal-json with provided scope is not picked up by shade plugin

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast#5543]
Currently minimal-json config is : 
```       
 <dependency>
            <groupId>com.eclipsesource.minimal-json</groupId>
            <artifactId>minimal-json</artifactId>
            <version>0.9.2</version>
            <scope>compile</scope>
  </dependency>
```

we need to find a way to change the scope to **provided** while keeping shade plugin work with minimal-json to include the library in hazelcast.jar

**Comment by jerrinot** [comment]
the shade plugin generates `dependency-reduced-pom.xml` (or something like this) 
isn't this what we should upload to maven central (and all other repositories) instead of our main pom.xml ? as I assume it doesn't contain the shaded libs.

**Comment by mesutcelik** [comment]
minimal-json classes are not included inside the hazelcast.jar file. That is the problem.

**Comment by jerrinot** [comment]
but if you change the scope of the json library to compile? then the classes will be included in the hazelcast.jar and the dependency won't be visible in the `reduced-dependency-pom.xml` at the same time?
