### ISSUE TITLE
[TEST-FAILURE] IOBalancerStressTest.testEachConnectionUseDifferentSelectorEventually

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5552]
```
java.lang.AssertionError: Values should be different. Actual: Thread[hz._hzInstance_28_dev.IO.thread-in-1,5,_hzInstance_28_dev]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/609/testReport/junit/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by gurbuzali** [comment]
I've manged to reproduce it (just once) with finest logging enabled.
here is a log snippet looks suspicious to me
```
11:19:34,038 DEBUG [IOBalancer] hz._hzInstance_3_dev.IOBalancerThread - [127.0.0.1]:5703 [dev] [3.6-SNAPSHOT] I/O imbalance is detected, but no suitable migration candidate is found.
```

**Comment by pveentjer** [comment]
This test was generously provided by Ali to reproduce the problem:

```
public void testEachConnectionUseDifferentSelectorEventually() {
        Config config = new Config();
        config.setProperty(GroupProperties.PROP_IO_BALANCER_INTERVAL_SECONDS, "1");
        config.setProperty(GroupProperties.PROP_IO_THREAD_COUNT, "2");

        HazelcastInstance instance1 = Hazelcast.newHazelcastInstance(config);
        HazelcastInstance instance2 = Hazelcast.newHazelcastInstance(config);
        HazelcastInstance instance3 = Hazelcast.newHazelcastInstance(config);

        instance2.shutdown();
        instance2 = Hazelcast.newHazelcastInstance(config);

        IMap<Integer, Integer> map = instance1.getMap(randomMapName());

        long deadLine = System.currentTimeMillis() + TEST_DURATION_SECONDS * 1000;
        for (int i = 0; System.currentTimeMillis() < deadLine; i++) {
            map.put(i % 1000, i);
        }

        TcpIpConnectionManager manager1 = (TcpIpConnectionManager) getConnectionManager(instance1);
        Address address1 = getAddress(instance1);

        TcpIpConnectionManager manager2 = (TcpIpConnectionManager) getConnectionManager(instance2);
        Address address2 = getAddress(instance2);

        TcpIpConnectionManager manager3 = (TcpIpConnectionManager) getConnectionManager(instance3);
        Address address3 = getAddress(instance3);

        assertUseDifferentSelectors(manager1, address2, address3);
        assertUseDifferentSelectors(manager2, address1, address3);
        assertUseDifferentSelectors(manager3, address1, address2);

    }
```

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/532/com.hazelcast$hazelcast/testReport/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by bilalyasar** [comment]
also master nightly: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/627/testReport/junit/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/533/com.hazelcast$hazelcast/testReport/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/630/testReport/junit/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/541/com.hazelcast$hazelcast/testReport/com.hazelcast.nio.tcp.iobalancer/IOBalancerStressTest/testEachConnectionUseDifferentSelectorEventually/

**Comment by pveentjer** [comment]
Was already resolved in master, but not yet resolves in maintenance. It is a fix in the test.
