### ISSUE TITLE
[TEST-FAILURE] ClientServiceTest.testConnectedClientsWithReAuth

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5570]
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.client.impl.HazelcastClientProxy.getClient(HazelcastClientProxy.java:280)
	at com.hazelcast.client.impl.HazelcastClientProxy.getMap(HazelcastClientProxy.java:113)
	at com.hazelcast.client.ClientServiceTest.testConnectedClientsWithReAuth(ClientServiceTest.java:258)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client/578/testReport/junit/com.hazelcast.client/ClientServiceTest/testConnectedClientsWithReAuth/

**Comment by bilalyasar** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast-client-new/582/testReport/junit/com.hazelcast.client/ClientServiceTest/testConnectedClientsWithReAuth/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/14222/testReport/junit/com.hazelcast.client/ClientServiceTest/testConnectedClientsWithReAuth/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/14220/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client/ClientServiceTest/testConnectedClientsWithReAuth/

**Comment by mdogan** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/14219/testReport/junit/com.hazelcast.client/ClientServiceTest/testConnectedClientsWithReAuth/
