### ISSUE TITLE
What is port 9000?

### ISSUE THREAD

**Issue by hamanhlam** [hazelcast/hazelcast#5575]
Hi.
In this article http://docs.hazelcast.org/docs/latest/manual/html/installingsimulator.html. "Please ensure that all remote machines are reachable via TCP ports 22, 9000".
What is port 9000?
Thanks.

**Comment by Serdaro** [comment]
@Donnerbart Could you please advise?

**Comment by Donnerbart** [comment]
Port 9000 is the port the Agent uses. Have a look at the "Key Concept" section for the glossary, please: http://docs.hazelcast.org/docs/latest/manual/html/simulatoroverview.html

There is an image in the docs which shows the network layout, but the link is broken. I guess we have to copy the file into another path, Serdar?

![network](https://cloud.githubusercontent.com/assets/4196298/8325515/959526a8-1a5a-11e5-92ff-e65fab3e2b07.png)

**Comment by Serdaro** [comment]
In the Single HTML version, it is okay, I am checking it for the Multi HTML one.

**Comment by hamanhlam** [comment]
Hi. I am seting up this simulator based on that network layout but I don't know which service belongs to port 9000?.
"Port 9000 is the port the Agent uses", can you help to give me more info?. My Agent is using Windows os, I can not found which service is using port 9000, and how can install on Windows.

**Comment by Donnerbart** [comment]
Please read the documentation as suggested. "Agent" is a component of Simulator which is installed and started by Simulator itself. It has nothing to do with services from the operating system. The port is needed for the internal communication of Simulator.

**Comment by noctarius** [comment]
PS: Does Simulator work with Windows since it uses SSH and I assume shell commands / tools? :)

**Comment by hamanhlam** [comment]
@noctarius  can use cygwin and install openssh.

**Comment by Donnerbart** [comment]
There is already another ticket for this: https://github.com/hazelcast/hazelcast-simulator/issues/690

**Comment by noctarius** [comment]
@hamanhlam yeah ok true, that's possible (I guess Posix services for Windows might also work) but it feels wrong to me ;-)

**Comment by hamanhlam** [comment]
@Donnerbart  yes, but nobody help me, so I create new topic in hazelcast issues.
I still get error when I run my test. 
```gitpm@gitpm /cygdrive/d/development/hazelcast-simulator-0.5/my-tests```
$ ./run.sh

output:
Couldn't connect to publicAddress:10.8.15.126:9000

**Comment by noctarius** [comment]
Looked at the firewall settings? Maybe the Windows Firewall blocks the port / java executable?

**Comment by Donnerbart** [comment]
I think a response time of a day is fine for a company working in a lot of different timezones :)

I think together with the (missing) picture and the glossary it should be clear what we mean with "Agent" in the Simulator part of the documentation, and that the Coordinator uses port 9000 to communicate with our Agent component.

I think we should leave this issue for the documentation fix. I'll assign this to @Serdaro and he can close it when the image is fixed.

Please let's talk about your setup issues in the other ticket: https://github.com/hazelcast/hazelcast-simulator/issues/690
