### ISSUE TITLE
AtomicReference.getAndSet throws HazelcastSerializationException

### ISSUE THREAD

**Issue by wslaasya** [hazelcast/hazelcast#5617]
AtomicReference.getAndSet throws HazelcastSerializationException.
if any node other than the first one that joins the cluster, tries to update the atomic reference, this exception is thrown

**Comment by pveentjer** [comment]
Which HZ version are you using? This problem AFAIK is solved.

**Comment by pveentjer** [comment]
@wslaasya can you give an update? Otherwise I'm going to close this ticket since the serialization issue has been addressed in latest 3.4 and 3.5.

**Comment by wslaasya** [comment]
I was using 3.4.. Will try upgrading to 3.5 and test.
I could not find any issues for AtomicReference.getAndSet so opened this

**Comment by jerrinot** [comment]
@wslaasya: do you have any update? Your domain object should be serializable. The easiest thing is to simply implement `java.io,Serializable` interface, but it's not the best option performance-wise. 

See http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#serialization for  details.

**Comment by pveentjer** [comment]
Have you tried with the latest 3.4? Because this bug has been resolved in one of the patch releases.

**Comment by enesakar** [comment]
closing. you can re-open if issue still exists
