### ISSUE TITLE
ResponseThread should log exception

### ISSUE THREAD

**Issue by Leperous** [hazelcast/hazelcast#5619]
(Hazelcast 3.5.0)

The com.hazelcast.spi.impl.classicscheduler.ResponseThread::process method may catch throwables. When this occurs, it logs an unhelpful message, and ignores the actual exception. 

This method should be improved so as to additionally log the cause, or at least the exception class and message.

In my case, it was catching a HazelcastSerializationException to do with an overridden DataSerializable class. I could only figure this out from debugging the application.

**Comment by pveentjer** [comment]
I'll take this one
