### ISSUE TITLE
Eager initialization of empty map takes seconds

### ISSUE THREAD

**Issue by atschofen** [hazelcast/hazelcast#5632]
Hi guys,

we have the problem that our application with 25 persistent maps (all with eager initialization) starts very slow even if there is no data to be loaded. This is due to the fact that each map takes at least 1 second to be initialized in Hazelcast 3.4.2. In Hazelcast 3.5, it's 2 seconds.

By debugging the startup, I found that the MapProxySupport#waitUntilLoaded method is probably the reason for the delay. It immediately executes PartitionCheckIfLoadedOperations and then sleeps 1 second before retrying on the partitions where it was not yet successful. And there are always partitions to retry. 

Is there any particular reason why the sleep time is so long, or could it also be shorter or even configurable? Another option would be to sleep for a very short amount of time before executing the checkIfLoaded operations the first time. With the right choice of wait time, they should usually be successful right away without retrying in case of no data to load. Or do the PartitionCheckIfLoadedOperations have to be executed right away in order to actually trigger the intialization?

This is a unit test to reproduce the problem. It fails if map initialization takes more than half a second.

```java
public class TestMap2 extends TestCase {

	private static final String mapName = "testMap";
	
	public void testMapStore() throws Exception {

		// create shared hazelcast instance config
		final Config config = new XmlConfigBuilder().build();

		// create shared map store implementation
		DummyMapStore store = new DummyMapStore();

		// configure map store
		MapStoreConfig mapStoreConfig = new MapStoreConfig();
		mapStoreConfig.setEnabled(true);
		mapStoreConfig.setClassName(null);
		mapStoreConfig.setInitialLoadMode(InitialLoadMode.EAGER);
		mapStoreConfig.setImplementation(store);
		MapConfig mapConfig = config.getMapConfig(mapName);
		mapConfig.setMapStoreConfig(mapStoreConfig);
	
		HazelcastInstance hcInstance = Hazelcast.newHazelcastInstance(config);
		try {
			long time = System.currentTimeMillis();
			hcInstance.getMap(mapName);
			time = System.currentTimeMillis() - time;
			System.out.println("Time to get map [ms]: " + time);
			assertTrue("Getting map took more than 500 ms", time <= 500);
		} finally {
			hcInstance.getLifecycleService().shutdown();
		}
		
	}
	
	private static final class DummyMapStore implements MapStore<String, String> {

		@Override
		public String load(String arg0) {
			return null;
		}

		@Override
		public Map<String, String> loadAll(Collection<String> arg0) {
			return new HashMap<String, String>();
		}

		@Override
		public Set<String> loadAllKeys() {
			return new HashSet<String>();
		}

		@Override
		public void delete(String arg0) {}

		@Override
		public void deleteAll(Collection<String> arg0) {}

		@Override
		public void store(String arg0, String arg1) {}

		@Override
		public void storeAll(Map<String, String> arg0) {}
		
	}
	
}
```

Thanks for having a look!

Cheers,
Andreas

**Comment by ajermakovics** [comment]
Hi Andreas,
Thanks for the test case! You're right, there's an issue in eager mode. Since map loading is offloaded to another thread we don't immediately know that its loaded.
We do have a ticket where this is reported (#5349) so I'll just close this one. You could add yourself as a watcher there.

**Comment by atschofen** [comment]
Hi Andrejs,

ok, thanks, I didn't see that issue :)

Cheers,
Andreas

**Comment by atschofen** [comment]
@ajermakovics Is there any information on when this will be fixed?

**Comment by ajermakovics** [comment]
@atschofen Aiming for 3.5.1 patch release but no due date yet

**Comment by atschofen** [comment]
@ajermakovics OK great, thanks!
