### ISSUE TITLE
Hazelcast Map eviction is not occurred in cluster

### ISSUE THREAD

**Issue by imvipul** [hazelcast/hazelcast#5635]
Hi,

I am using hazelcast 3.4.2 and I am using IMap from hazelcast. Map eviction is working fine for me on my local environment but on cluster it is not working.

you can see my created nodes in my clusters in below line at the time of Map item eviction it evict item only from -> { Member [10.116.168.127]:5702 this }. and whatever items cached into another node it will not evict.

Members [5] {
Member [10.116.168.127]:5701
Member [10.116.168.126]:5701
Member [10.116.168.128]:5701
Member [10.116.168.127]:5702 this
Member [10.116.168.127]:5703
}

I am using programmatic approach for creating map and setup it's attributes.

           MapConfig mapCfg = new MapConfig();
    mapCfg.setName(mapName);
    mapCfg.setInMemoryFormat(InMemoryFormat.OBJECT);
    mapCfg.setBackupCount(backUpCnt);
    mapCfg.setTimeToLiveSeconds(ttl);

    mapCfg.setMaxSizeConfig(new MaxSizeConfig(0, MaxSizePolicy.PER_NODE));
    mapCfg.setEvictionPolicy(EvictionPolicy.NONE);
    mapCfg.setMergePolicy("com.hazelcast.map.merge.PutIfAbsentMapMergePolicy");
Can any one help suggest me why it is not working.

**Comment by imvipul** [comment]
Can any one help suggest me why it is not working or it's a defect of hazelcast

**Comment by ahmetmircik** [comment]
Hi @imvipul ,

* Zero means Integer.MAX_VALUE to enable eviction you should set a value other than zero for example 10000.
```
mapCfg.setMaxSizeConfig(new MaxSizeConfig(10000, MaxSizePolicy.PER_NODE)); 

```

* Setting eviction policy to NONE means `don't do eviction`, if you want to evict, please use one of LRU or LFU.
```
mapCfg.setEvictionPolicy(EvictionPolicy.LRU); 
```

**Comment by gurbuzali** [comment]
please re-open the issue if you still encounter it after you've applied @ahmetmircik 's comments

**Comment by imvipul** [comment]
Hi ahmetmircik 

I tried with those option also.

When i connect with my cluster and i have following nodes

Members [5] {
Member [10.116.168.127]:5701
Member [10.116.168.126]:5701
Member [10.116.168.128]:5701
Member [10.116.168.127]:5702 this
Member [10.116.168.127]:5703
}

but in case of Eviction policy LRU or LEU it only evict for Member [10.116.168.127]:5702 this node and elements from other node remains as it is.

**Comment by ahmetmircik** [comment]
Hi @imvipul ,
Can you retry by setting this:
```
mapCfg.setMinEvictionCheckMillis(0)
```

if it also does not help, can you please send a simple test to reproduce the issue?

**Comment by ahmetmircik** [comment]
@imvipul any update?

**Comment by imvipul** [comment]
Hi,

Sorry buddy busy with some other issue will update you tomorrow.

**Comment by ahmetmircik** [comment]
Hi @imvipul, for a very long time we didn't hear from you, closing this issue now, when you have a failing test to reproduce the issue, we can re-open it. 

FYI: In my tests i did not manage to reproduce the issue.
