### ISSUE TITLE
Instantiating custom LoggerFactory two times

### ISSUE THREAD

**Issue by dbatyuk** [hazelcast/hazelcast#5641]
Hi,

I am using hazelcast 3.4.1 and I implement custom LoggerFactory. While starting application it creates custom LoggerFactory two times if you are using XmlConfigBuilder for example. XmlConfigBuilder has LoggerFactory.getLogger(...) which creates custom LoggerFactory first time as it doesn't exist yet. Second time it is created when Hazelcast.newHazelcastInstance -> Node.init -> LoggingServiceImpl.init is called as it need to instantiate for application and it doesn't know that it exists already. 

I think it would be better to prepare some singleton solution in LoggerFactory interface and stop using public constructor. Attaching stack traces of creating those two instances.

![firstinstance](https://cloud.githubusercontent.com/assets/1583370/8454507/9c0a9f20-2006-11e5-9839-99875825fabf.png)
![secondinstance](https://cloud.githubusercontent.com/assets/1583370/8454512/a049c408-2006-11e5-9b74-6169808c29d7.png)

Thank you

**Comment by mmedenjak** [comment]
Still present in 3.8 - there are several calls to `com.hazelcast.logging.Logger#newLoggerFactory`, some of which are synchronized with a lock, some of which are not. This can lead to two factories being created.
