### ISSUE TITLE
Hazelcast Map.put(K key, V value) vs Map.put(K key, V value, long ttl, TimeUnit timeunit)

### ISSUE THREAD

**Issue by imvipul** [hazelcast/hazelcast#5650]
Hi,

Can you help me to figure out performance difference between `Map.put(K key, V value)` vs `Map.put(K key, V value, long ttl, TimeUnit timeunit)` because map eviction is not working for me (#5635) and I must have to know because I am using `Map.put(K key, V value, long ttl, TimeUnit timeunit)` in my application which is storing 4000 records into Map in 1 sec.

Best Regards

Vipul

**Comment by ahmetmircik** [comment]
reopened https://github.com/hazelcast/hazelcast/issues/5635, closing this one.

**Comment by imvipul** [comment]
Hi,

Please reopen this one.

Ans please update me on this.

**Comment by ahmetmircik** [comment]
Hi @imvipul, first of all #5635 should not be an issue, eviction should simply work.

For the question, there should not be any performance difference between `map#put(K key, V value)` vs `map.put(K key, V value, long ttl, TimeUnit timeunit)`. But if you don't need the returned value from `map#put`, you can use `map#set` and expect more performance.
