### ISSUE TITLE
[transaction] Tx Optimization: merge prepare/commit for single partition

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5657]
If a group of operations falls in the same partition, instead of sending one (merged) operation for prepare and one (merged) operation for the actual writing; just send a single operation to the partition where the merge and then the write is executed as a single operation.

This way you reduce the number of remote calls by 2 since everything can be done in a single remote call.

**Comment by burakcelebi** [comment]
Closing and putting on hold, will review at later point.

**Comment by mmedenjak** [comment]
This issue is a part of a collection of TX related issues that should be inspected based on the decision on the future of TX - https://hazelcast.atlassian.net/wiki/spaces/PM/pages/36208869/Core+Technical+Debt+-+Transactions
