### ISSUE TITLE
Session ID management error by Hazelcast 3.5 Filter based replication

### ISSUE THREAD

**Issue by gvachet** [hazelcast/hazelcast#5660]
After a logout request that invalidates the session and setMaxAge(0) on JSESSIONID cookie, a 500 HTTP error is raised at the next logging request (checked on FireFox and on IE). This NPE is raised with the 3.5 edition but not with the 3.5 Early Access version. The difference is that the Early Access edition generates a new session Id but the Hazelcast 3.5 version keeps the previous Id of the invalidated session.

Filter based Web session replication by Hazelcast 3.5 or 3.5 EA
Server version:        Apache Tomcat/8.0.17
OS Name:               Linux
Java version:           1.7.0_60-b19

Note: code and logs are available but support by this issue interface.

**Comment by emrahkocaman** [comment]
Closing this issue and creating a new one since session replication module is moved to hazelcast-wm repo. Please follow https://github.com/hazelcast/hazelcast-wm/issues/16
