### ISSUE TITLE
Portable : StringArrayField and BooleanArrayField missing from ClassDefinitionBuilder

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#5661]
Hi

Is there any reason why there is not a StringArrayField and BooleanArrayField in the ClassDefinitionBuilder?  It seems all the other primitives are supported apart from these two.

**Comment by gurbuzali** [comment]
you mean `IntegerArraySerializer`, `LongArraySerializer` vs... ?

**Comment by dbrimley** [comment]
addUTFArrayField and addBooleanArrayField

**Comment by mdogan** [comment]
Fixed by 5678ad57cb1777d0cf065de93684431133619e4a
