### ISSUE TITLE
[TEST-FAILURE] MapReduceTest.testExceptionDistributionWithCollator

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5663]
```
org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.sleepWithBusyWait(InternalPartitionServiceImpl.java:1027)
	at com.hazelcast.partition.impl.InternalPartitionServiceImpl.prepareToSafeShutdown(InternalPartitionServiceImpl.java:981)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-zulu1.6/com.hazelcast$hazelcast/22/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testExceptionDistributionWithCollator/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/663/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testExceptionDistributionWithCollator/

**Comment by Donnerbart** [comment]
Increased test timeout of exception throwing tests to same as normal tests via https://github.com/hazelcast/hazelcast/commit/161b8b008ddfbfe42b66db59b04eb76d098bebc1
