### ISSUE TITLE
Create Client-based JCA Adapter

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast#5667]
Currently if you want to use Container-Managed Transactions with Hazelcast within a JEE Application Server, we need to use the provided JCA Adapter. This JCA Adapter creates a HZ instance.

We would like the option to allow the configuration of the JCA Adapter to be either Server or Client-based. 

This would give us the best of two worlds: HZ Clients and XA Resources managed by the container. As it stands if we want to use Transactional Clients we need to manually manage the transactions.

**Comment by jerrinot** [comment]
Hi @juanavelez,
I think it's a logical enhancement. Thank you for reporting this.

**Comment by juanavelez** [comment]
Hi @jerrinot. Thank you for the quick reply. I am not sure what you mean by logical enhancement. From looking at the code, it seems it is "hardcoded" to create Server instances. Would you mind expanding on your answer? Thanks!

**Comment by jerrinot** [comment]
@juanavelez: I'm sorry, I meant a "reasonable" or "sensible" enhancement. 
In other words: I like what you are proposing and we should implement it.

**Comment by mesutcelik** [comment]
Hi @juanavelez ,
We have a schedule for 3.6 already and not sure if we can add it but you are always welcome to make such contributions.

just let us know if you need any help.

**Comment by juanavelez** [comment]
Hi @mesutcelik ,

Thanks for the update. I have a couple of questions regarding the contribution and more specifically related to this particular issue. Let me know if I can post these questions directly here or if it'd better to send them to your email address.

**Comment by mesutcelik** [comment]
whichever you prefer...
mesut _at_ hazelcast _dot_ com

**Comment by pdudits** [comment]
Really looking forward for this feature. We are using hazelcast for kind of service registry for our application deployed in glassfish, and we are having race conditions because applications want to register at same time when cluster is building up after startup.

So having client-only JCA adapter would be great approach for us. @juanavelez, is there a branch one could look at and try?

**Comment by juanavelez** [comment]
@pdudits Unfortunately I have not been not given authorization by my US employer to share my changes. Sorry.

**Comment by jerrinot** [comment]
Hi @juanavelez,

many thanks for your effort. We are currently in Feature Freeze phase before 3.7 release, but your PR looks very promising and I'm looking forward to have it merged into Hazelcast 3.8!

@mesutcelik: WDYT?

**Comment by mesutcelik** [comment]
Hi @juanavelez ,

I am on holiday this and next week so i can't check it those days. maybe @emrahkocaman ?  However, as your PR has been sent to hazelcast-ra repository, we can release the module right away unless you use a new feature in hazelcast 3.7 master branch.

Thanks for the contribution. 

P.S: I see you have already sent the contributor agreement. Welcome to Hazelcast Family 👍

**Comment by juanavelez** [comment]
@mesutcelik Yes, you were the one who told me to put it there (https://github.com/hazelcast/hazelcast-ra/issues/4). And yes, if it can be released right away, I'd appreciate it. I did not use any 3.7-related features.
