### ISSUE TITLE
AbstractEvictableRecordStore.getEvictableSize: DefaultRecordStore.size returns number of elements, not currentPartitionSize, EvictionOperator.evictableSize called with wrong value

### ISSUE THREAD

**Issue by LoneRifle** [hazelcast/hazelcast#5669]
[AbstractEvictableRecordStore.getEvictableSize](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/AbstractEvictableRecordStore.java#L238) is called by removeEvictableRecords, ie, called whenever entries have to be evicted. This in turn calls size(), which is currently implemented by DefaultRecordStore to return the number of entries, not the current size of the partition. 

The number of entries hence gets passed as currentPartitionSize to [EvictionOperator.evictableSize](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/eviction/EvictionOperator.java#L181), and hence will lead to inconsistent calculations for all expressions referencing that argument, ie:
* lines 190-191 - for per partition eviction policies
* lines 200-201 - for per node eviction policies
* line 209 - for used/free percentage/size eviction policies.

**Comment by ahmetmircik** [comment]
Hi @LoneRifle , can you point what is the difference between `current-size-of-partition` and `number-of-entries-in-DefaultRecordStore`?

**Comment by LoneRifle** [comment]
Hi Ahmet,

Having re-read the impl and consulted the docs, I now stand corrected: the two terms should be identical. I was originally under the impression that for the size/percent-based policies, the eviction percentage does not refer to the number of entries but the amount of space consumed.Thanks.
