### ISSUE TITLE
hazelcast client property "connectionTimeout" not working when node is unavailable due to network issues

### ISSUE THREAD

**Issue by vitaliy31matuzko** [hazelcast/hazelcast#5675]
Hi everyone, could someone take a look at this issue:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hazelcast/HaxS3Vxl7x8/Tq8eVgZ6EXcJ

**Comment by sancar** [comment]
This is fixed in 3.6 closing the issue. There is no hardcoded try count anymore. And sorry for late response.
