### ISSUE TITLE
com.hazelcast:hazelcast-code-generator depends on Freemarker

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#5678]
Spring Boot provides a dependency management for the latest and greatest and as such we have  upgraded to Hazelcast 3.5. It turns out that in that release (I think) `com.hazelcast:hazelcast-code-generator` brings a compiled scope dependency on `org.freemarker:freemarker:jar`.

So basically your users have freemarker in their classpath now. Could you please fix that ASAP and release 3.5.1?

See https://github.com/spring-projects/spring-boot/issues/3418

**Comment by mesutcelik** [comment]
that is already fixed and will be released in 3.5.1 soon.
You can check it already with 3.5.1-SNAPSHOT.
