### ISSUE TITLE
Map updates cause NearCache updates, not invalidation

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#5679]
When NearCache is enabled, all updates on IMap (put, replace etc) should also update the values stored in NearCache instead of sending a value invalidation event to NearCache. Consistency of updating values inside NearCache should be configurable - Eventual (update in NearCache will reflect eventually) or Strong (updates should be part of one atomic operation initiated by the requester of map.put or map.replace). 

Let me know if this calls for a PRD.

Thanks.

**Comment by dbrimley** [comment]
Are there any plans to provide this feature in the near future?

**Comment by sancar** [comment]
@wildnez 
This sounds like Continuous Query Cache. Does that solve your requirements ?

**Comment by burakcelebi** [comment]
@wildnez WDYT? Can this be closed?

**Comment by dbrimley** [comment]
You can now link a local map to a CQC, so I think this solves the issue.
