### ISSUE TITLE
Hazelcast : Set Map Configuration to Cluster Node without Creating Instance of Hazelcast locally

### ISSUE THREAD

**Issue by imvipul** [hazelcast/hazelcast#5682]
Hi

Below are my cluster members and I wan to pass some Map configuration to those node so once that Map create all node use that configuration.

Members [3] {
       Member [169.185.209.99]:5701
       Member [165.203.252.170]:5701
       Member [169.185.209.169]:5701
     }

How can i pass Map config without creating hazlecast Instance on (169.164.232.143) my local system.

this is really urgent..

Thanks
Vipul

**Comment by pveentjer** [comment]
Hazelcast doesn't support dynamic configuration of data-structures; so you
need to add the map configuration to the Hazelcast configuration.

**Comment by burakcelebi** [comment]
Dynamic configuration is added with 3.9: http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#dynamically-adding-configuration-on-a-cluster

Let us know if you have any questions.
