### ISSUE TITLE
Not seeing Hazelcast 3.4.4 on http://hazelcast.org/download/

### ISSUE THREAD

**Issue by dayasakti** [hazelcast/hazelcast#5687]
As per https://github.com/hazelcast/hazelcast/issues/5538#issuecomment-113915885

By right, i think we should be seeing 3.4.4 too under the Previous Production Releases. However 3.4.3 seems to be the latest out of 3.4 version. 

I can confirm that it's not a browser cache on my side though 

Was 3.4.4 being taken out from the download list?

**Comment by mesutcelik** [comment]
Thx for the warning. It is fixed now.

**Comment by dayasakti** [comment]
Cool thanks
