### ISSUE TITLE
Hzelcast memory increasing without any activity

### ISSUE THREAD

**Issue by sgulati89** [hazelcast/hazelcast#5688]
Recently we got an interesting issue; We had default setup of on node cluster of Hazelcast and we had an entry level expiration set for an element. Entry gets removed from the map; as we cane see the count to be zero/empty. 
However we see cluster performance a bit weird; its Heap Size goes on increasing even though there is no activities in the cluster. We have also see OutofMemoryError. 

It's collect stats attribute is set to true and mancenter configured and deployed separately.
Heap dump is also not giving clear picture. 
I suspect there is some background thread creating objects in memory which are not garbage collected.

In case you have any idea about this; it will be of great help. We are using Hazelcast 3.4.1

![hazelcast](https://cloud.githubusercontent.com/assets/2961056/8643377/7870c1b4-2922-11e5-9c6a-b1e6794141c4.png)

**Comment by pveentjer** [comment]
Can you switch to 3.5 and check if this behavior still happening?

If the issue is still happening, can you generate a heap dump when an OOME happens?

**Comment by sgulati89** [comment]
We tried using 3.5 and 3.5.2 , however it is now giving another issue.

Getting following error while starting hazelcast 

Invalid content was found starting with element 'read-backup-data'. One of '{"http://www.hazelcast.com/schema/config":statistics-enabled, "http://www.hazelcast.com/schema/config":max-size, "http://www.hazelcast.com/schema/config":item-listeners}' is expected.

However, as per the documentation <read-backup-data> tag is supported.

Following is an example map configuration
```xml
<map name="test">
		<backup-count>0</backup-count>
		<async-backup-count>1</async-backup-count>
		<read-backup-data>true</read-backup-data>
		<eviction-policy>NONE</eviction-policy>
</map>
```

**Comment by jerrinot** [comment]
@sgulati89: That's is strange. I could not reproduce the issue. Could you post your full configuration file? Or a minimal configuration where you can still reproduce the XML parsing error. Thanks!

**Comment by mdogan** [comment]
No feedback. Please feel free to open a new issue if problem still exists.
