### ISSUE TITLE
[TEST-FAILURE] WanReplicationTest.EntryWithDefault_TTL_Replication_Issue

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5691]
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.hazelcast.wan.WanReplicationTest$2.run(WanReplicationTest.java:235)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:740)
	at com.hazelcast.wan.WanReplicationTest.assertKeysIn(WanReplicationTest.java:233)
	at com.hazelcast.wan.WanReplicationTest.EntryWithDefault_TTL_Replication_Issue(WanReplicationTest.java:370)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/633/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/549/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/645/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/651/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by hasancelik** [comment]
3.x-maintenance:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/557/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by hasancelik** [comment]
3.x maintenance:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/com.hazelcast$hazelcast/559/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by emrahkocaman** [comment]
Should be fixed with above commits.

**Comment by hasancelik** [comment]
Failed again, nightly build result is:
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/661/testReport/junit/com.hazelcast.wan/WanReplicationTest/EntryWithDefault_TTL_Replication_Issue/

**Comment by emrahkocaman** [comment]
@hasancelik , another timing issue. 
sent another update (https://github.com/hazelcast/hazelcast/commit/cd34a8eb8dadc8bfec327b452a3a3cad07cd295c).
