### ISSUE TITLE
deleting hazelcast-documentation module

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#5693]
We moved hazelcast-documentation to new https://github.com/hazelcast/hazelcast-reference-manual repo, so we need to delete hazelcast-documentation module
- [x] we need for master branch. 
- [x] we need for maintenance-3.x branch

**Comment by bilalyasar** [comment]
module is moved with commit history, so we didn't lose the commit history.

**Comment by Serdaro** [comment]
:+1:

**Comment by bilalyasar** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/5743 and https://github.com/hazelcast/hazelcast/pull/5751
