### ISSUE TITLE
Hazelcast is not able to unlock few elements after forceunLock on IMap and MultiMap

### ISSUE THREAD

**Issue by imvipul** [hazelcast/hazelcast#5706]
Hi,

In my application I am storing values in IMap and Multimap like anything. so Some time hazelcast is not able to unlock few elements after forceunLock also can you suggest me how to unlock elements in such a condition and how to know how many elements are loacked and which are those elements.

**Comment by jerrinot** [comment]
Hello @imvipul,

thank you for reporting the issue!

Could you please be more specific? What does it mean "Hazelcast is not able to unblock" ? Are you getting an error? Is it just hanging indefinitely? How you are locking the elements? What version of Hazelcast are you using? Are you using client-server topology or server-to-server? Do you have code to reproduce the issue?

**Comment by enesakar** [comment]
closing issue, you can re-open it providing more info, test code if possible.
