### ISSUE TITLE
hazelcast-config-3.5.xsd doesn't contain "instanceName"

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast#5711]
I recently upgraded my version to 3.5. My hazelcast.xml configurations contain "intanceName" fail to start. 

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
    xmlns="http://www.hazelcast.com/schema/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>dev</name>
        <password>devdev</password>
    </group>    
    <instanceName>server</instanceName>    
    <network>
        <port auto-increment="true">5701</port>
        <join>
            <multicast enabled="false"/>
              <tcp-ip enabled="true">
                  <members>127.0.0.1</members>
            </tcp-ip>
        </join>
    </network>
</hazelcast>

The schema "hazelcast-config-3.5.xsd" doesn't contain "instanceName" element.

**Comment by Fabryprog** [comment]
Hello @RubavathiSrinivasan, can you attach your hazelcast-config xml file? 

According to https://github.com/hazelcast/hazelcast/issues/426 this features is PENDING status

**Comment by RubavathiSrinivasan** [comment]
Hello @Fabryprog , I added instance name using <property>. It works fine. Thank you.

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
    xmlns="http://www.hazelcast.com/schema/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
        <name>dev</name>
        <password>password</password>
    </group>    
    <properties>
    <property name="instance.name">usermaps</property>
    </properties>
    <network>
        <port auto-increment="true">5701</port>
        <join>
            <multicast enabled="false"/>
              <tcp-ip enabled="true">
                  <members>127.0.0.1</members>
            </tcp-ip>
        </join>
    </network>
</hazelcast>

**Comment by Fabryprog** [comment]
can you close this issue? thanks!
