### ISSUE TITLE
Interfaces enabled='false' doesn't work

### ISSUE THREAD

**Issue by nick7ikin** [hazelcast/hazelcast#5728]
I have several network interfaces on my PC:
192.168.12.10 - is my local network IP
192.168.122.1 - is IP of my virtual network interface that is used by virtual machine

Hazelcast by default connects to 122.1.
I tried to forbid this network both in hazelcast.xml
```
    <network>
        <interfaces enabled="false">
            <interface>192.168.122.*</interface>
        </interfaces>
    </network>
```
 and programmatically
```
        Config cfg = new ClasspathXmlConfig("hazelcast.xml");
        InterfacesConfig interfacesConfig = new InterfacesConfig().addInterface("192.168.122.*").setEnabled(false);
        cfg.getNetworkConfig().setInterfaces(interfacesConfig);
```

I've managed to connect it to 192.168.12.10 interface specifying enabled interfaces:
```
    <network>
        <interfaces enabled="true">
            <interface>192.168.12.*</interface>
        </interfaces>
    </network>
```
but for me is more preferable to specify forbidden interfaces. Is there any way, did I miss something?

**Comment by gurbuzali** [comment]
you are misunderstanding the `enabled=false` term here. it means `interfaces` feature will not be used while configuring, not to disable the interface you've specified inside it.
So basically it is ignored while configuring if it is `enabled=false`

**Comment by nick7ikin** [comment]
Thanks for explanations, but is there any way to specify IP range that have to be excluded by Hazelcast from consideration?

**Comment by gurbuzali** [comment]
afaik no, hazelcast does not have such ability
