### ISSUE TITLE
Client test improvements

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#5740]
Since client tests are in a state that can run parallel and fast, we can do further improvements like
1) Reducing code duplication in the tests and making use of server tests to test the client
 @pveentjer Idea is to have a base class that both server and client will extend to do its own tests. 
example base class https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/concurrent/atomiclong/AtomicLongBasicTest.java  
Two of its extendees
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/concurrent/atomiclong/AtomicLongBasicLocalTest.java

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/concurrent/atomiclong/AtomicLongBasicDistributedTest.java

Same logic can be used to test clients.

2) Cleaner test methods
Currently server tests have HazelcastTestSupport that hides the details about creating instances. 
Similar can be done as HazelcastClientTestSupport . To do that we need to change the way we use test supports since current api design is not fit to clients.

**Comment by burakcelebi** [comment]
Become obsolete. Closing.
