### ISSUE TITLE
Maven profile checkstyle and findbugs not exist!

### ISSUE THREAD

**Issue by Fabryprog** [hazelcast/hazelcast#5746]
Hello everybody,

The maven profile **mvn clean compile -Pqa** not exist but it is documented here: https://github.com/hazelcast/hazelcast#checkstyle--findbugs

best regards

**Comment by mesutcelik** [comment]
good catch! we need to update our readme file

here are the commands:
`mvn clean compile -P findbugs`
`mvn clean validate -P checkstyle`

**Comment by Serdaro** [comment]
Thank you.

**Comment by Fabryprog** [comment]
@Serdaro Can you re-open this issue?

When I had launched *mvn clean validate -P checkstyle* command i received an error because maven not compile subproject! 

I fix it using this command *mvn clean compile validate -P checkstyle*.

King regards!

**Comment by Serdaro** [comment]
@mesutcelik , can you comment? Should I change the README accordingly?

**Comment by mesutcelik** [comment]
I see no problem with `mvn clean validate -P checkstyle`

@Fabryprog ,
Can you please post error message here?

**Comment by Fabryprog** [comment]
Hello,

I cannot do it because now i have another error:

1) git clone https://github.com/hazelcast/hazelcast.git
2) mvn clean validate -P checkstyle

What has changed?

CONSOLE LOG:


[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Hazelcast Root
[INFO] hazelcast-code-generator
[INFO] hazelcast
[INFO] hazelcast-cloud
[INFO] hazelcast-client
[INFO] hazelcast-client-new
[INFO] hazelcast-hibernate
[INFO] hazelcast-hibernate3
[INFO] hazelcast-hibernate4
[INFO] hazelcast-wm
[INFO] hazelcast-spring
[INFO] hazelcast-ra
[INFO] hazelcast-jca
[INFO] hazelcast-jca-rar
[INFO] hazelcast-build-utils
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hazelcast Root 3.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ hazelcast-root ---
[INFO] Deleting c:\Users\fabryprog\workspace_github\TTT\hazelcast\target
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.12:checkstyle (default) @ hazelcast-root ---
[INFO] Starting audit...
Audit done.

[WARNING] Unable to locate Source XRef to link to - DISABLED
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hazelcast-code-generator 3.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ hazelcast-code-generator ---
[INFO] Deleting C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\target
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.12:checkstyle (default) @ hazelcast-code-generator ---
[INFO] Starting audit...
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecCodeGenerator.java:60: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecCodeGenerator.java:70: Line is longer than 130 characters (found 133).
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecCodeGenerator.java:156:11: 'if' is not followed by whitespace.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecCodeGenerator.java:268:27: ',' is not followed by whitespace.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:33: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:33:41: '{' is not preceded with whitespace.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:43:5: Variable access definition in wrong order.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:53:5: Executable statement count is 73 (max allowed is 20).
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:53:5: Method length is 93 lines (max allowed is 60).
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:63:20: '104' is a magic number.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:133:27: '104' is a magic number.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:269: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodecModel.java:287: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodeGenerationUtils.java:21: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodeGenerationUtils.java:23:5: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodeGenerationUtils.java:24:5: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodeGenerationUtils.java:25:5: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\CodeGeneratorMessageTaskFactory.java:50: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\MessageFactoryModel.java:22: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\MessageTypeEnumModel.java:29: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\MessageTypeEnumModel.java:99: Missing a Javadoc comment.
C:\Users\fabryprog\workspace_github\TTT\hazelcast\hazelcast-code-generator\src\main\java\com\hazelcast\client\protocol\generator\Model.java:19: Missing a Javadoc comment.
Audit done.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hazelcast Root .................................... SUCCESS [2.181s]
[INFO] hazelcast-code-generator .......................... FAILURE [1.015s]
[INFO] hazelcast ......................................... SKIPPED
[INFO] hazelcast-cloud ................................... SKIPPED
[INFO] hazelcast-client .................................. SKIPPED
[INFO] hazelcast-client-new .............................. SKIPPED
[INFO] hazelcast-hibernate ............................... SKIPPED
[INFO] hazelcast-hibernate3 .............................. SKIPPED
[INFO] hazelcast-hibernate4 .............................. SKIPPED
[INFO] hazelcast-wm ...................................... SKIPPED
[INFO] hazelcast-spring .................................. SKIPPED
[INFO] hazelcast-ra ...................................... SKIPPED
[INFO] hazelcast-jca ..................................... SKIPPED
[INFO] hazelcast-jca-rar ................................. SKIPPED
[INFO] hazelcast-build-utils ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.435s
[INFO] Finished at: Mon Aug 03 10:56:04 CEST 2015
[INFO] Final Memory: 14M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.12:checkstyle (default) on project hazelcast-code-generator: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 22 checkstyle errors. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hazelcast-code-generator

**Comment by mesutcelik** [comment]
Can you please send us some more info? OS,java version,mvn version?

**Comment by Fabryprog** [comment]
$ java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) Client VM (build 24.60-b09, mixed mode, sharing)

$ javac -version
javac 1.7.0_60

$ mvn --version
Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
Maven home: c:\Users\fabryprog\apache-maven-3.0.4
Java version: 1.7.0_60, vendor: Oracle Corporation
Java home: c:\Program Files (x86)\Java\jdk1.7.0_60\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
