### ISSUE TITLE
Metrics: Is Still Running Count

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#5755]
Count how many times a TraceableIsStillExecutingOperation or IsStillExecutingOperation has been invoked.

**Comment by jerrinot** [comment]
@pveentjer: are you going to implement this?

**Comment by pveentjer** [comment]
I'm working on getting rid of the whole mechanism :)

**Comment by jerrinot** [comment]
so this can be closed then?

**Comment by pveentjer** [comment]
Depends if I manage to get the invocation improvement into 3.6.

**Comment by pveentjer** [comment]
I'm going to close this ticket since we don't have 'is still running operations' anymore due to the new timeout mechanism.
