### ISSUE TITLE
Data loss in Hazelcast Map when some nodes in cluster are restarted

### ISSUE THREAD

**Issue by mat102** [hazelcast/hazelcast#5762]
We have been using Hazelcast 2.6.8 and upgraded to 3.5. The reason for upgrading was what appear to be intermittent problems with caching data. However the upgrade has not solved the problem. 

We are trying to cache 100 java plain objects in a Hazelcast IMap, which we cache from an external database. Cached objects are shared across the cluster via Hazelcast's ConcurrentMap. We have a cluster of 6 nodes and whenever we stop and start 2 out of these 6 nodes we find that some of the java objects are missing, its occurrence along with the number of missing varies, though when missing the number is usually about 90 objects in the map rather then 100.

Initially backup-count property has been set to 3, but due to failures we increased it to 6.

The IMap method used is the loadAll method to retrieve the data. This is the configuration we are using, StoreClass implements the Hazelcast MapStore:

    <map name="objectsMap">
    <backup-count>6</backup-count>
    <near-cache>
    <time-to-live-seconds>0</time-to-live-seconds>
    <max-idle-seconds>6000</max-idle-seconds>
    <eviction-policy>LRU</eviction-policy>
    <max-size>5000</max-size>
    <invalidate-on-change>true</invalidate-on-change>
    </near-cache>

    <map-store enabled="true">
    <class-name>StoreClass</class-name>
    <write-delay-seconds>0</write-delay-seconds>

**Comment by Fabryprog** [comment]
:+1: 

Hello, i confirm this defect but i haven't a test case to demonstrate it!

It is true "sometimes" :-|

**Comment by nick7ikin** [comment]
please check discussion #5444. It could be similar issue

**Comment by enesakar** [comment]
closing this, please track #5444
