### ISSUE TITLE
NullPointerException invoking com.hazelcast.map.impl.DefaultRecordStore.isLoaded()

### ISSUE THREAD

**Issue by MarceloMadruga** [hazelcast/hazelcast#5770]
Hi,
I'm using hazelcast 3.5 and sometimes I get NullPointerException when using MapStores. It happens when the some code access an IMap instance  which triggers DefaultRecordStore.isLoaded() and this method calls FutureUtil.allDone(loadingFutures) where somehow loadingFutures has one null entry. I observed that this null entry is added from loadAllFromStore method in line 100 this null value comes from recordStoreLoader instance that is actually a RecordStoreLoader.EMPTY_LOADER created at AbstractRecordStore.createRecordStoreLoader method. Now what I don't understand is why mapStoreContext.getMapStoreWrapper() at line 213 somethimes returns null, I really couldn't get the pattern.

protected RecordStoreLoader createRecordStoreLoader(MapStoreContext mapStoreContext) {
        return mapStoreContext.getMapStoreWrapper() == null
                ? RecordStoreLoader.EMPTY_LOADER : new BasicRecordStoreLoader(this);
    }

**Comment by Fabryprog** [comment]
:+1: 

Hello, i confirm this defect but i haven't a test case to demonstrate it!

It is true "sometimes" :-|

**Comment by MarceloMadruga** [comment]
Hi Fabrizio,

I'm sorry about that, I'll build up a test case for it. I couldn't identify
the pattern yet, but sometimes when the node comes up and I try to access
the map, the mapStoreContext is null even with the configurations set in
place correctly. So I have to stop the node and start it up again, then it
works normally. I'm testing it as a standalone node.



2015-07-23 4:55 GMT-04:00 Fabrizio Spataro <notifications@github.com>:

**Comment by MarceloMadruga** [comment]
Ok, no luck reproducing this in a single test case... Could check it out @ https://github.com/MarceloMadruga/hazelcastMapstoreTest
So, more updates... I'm also using spring in my project (not in the test case) and perhaps it overlaps the map creation (bean) with the Hazelcast instance (also a bean) creation and that does not happen often, so I just managed to initialize my beans in the correct order and the issue was gone... But maybe, some null reference protection could be coded in one of these two classes:

com.hazelcast.util.FutureUtil

public static void checkAllDone(Collection<Future> futures) throws Exception {
        for (Future f: futures) {
            //if (f.isDone()) {
            if (f != null && f.isDone()) {
                f.get();
            }
        }
    }

... Or in com.hazelcast.map.impl.DefaultRecordStore
add a null check before adding a Future instance in loadingFutures collection

if(f !=null){
    loadingFutures.add(f)
}

lines 80, 93 and 100

But, I'm not sure if doing that you could be omitting a major issue.

**Comment by jerrinot** [comment]
@MarceloMadruga: Thank you for reporting the issue. 
Could you please post here a full stacktrace of the `NullPointerException` and exact version of Hazelcast you are using? 

#5885 fixes a possible NPE exception. I have seen NPE when some members had MapStore, but the configuration was missing on other members.

**Comment by enesakar** [comment]
We have solved a NPE in #5885. Please check with master 3.6-EA, if problem still exists you can reopen the issue.

**Comment by jerrinot** [comment]
just a clarification: the fix has been back-ported into a maintenance branch -> the latest 3.5.x patch release has the fix as well.

**Comment by qweek** [comment]
Hi, jerrinot
Could you provide patch version?
I get the same bug in 3.5.4

**Comment by qweek** [comment]
Reproduced in tests in MapStore:

	HZ2: 13:55:22.834 ERROR   [hz._hzInstance_1_dev.partition-operation.thread-1] --- c.hazelcast.map.impl.DefaultRecordStore  : [localhost]:9999 [3.5.4] Exception while loading map c.m.e 
	HZ2: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	HZ2:     at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.FutureUtil.checkAllDone(FutureUtil.java:346) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.DefaultRecordStore.checkIfLoaded(DefaultRecordStore.java:141) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.operation.MapSizeOperation.run(MapSizeOperation.java:41) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2: Caused by: java.lang.NullPointerException: null
	HZ2:     at c.d.r.f.d.s.s.a.load(a.java:97) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a.lambda$loadAll$2(a.java:124) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a$$Lambda$28/863580295.accept(Unknown Source) ~[na:na]
	HZ2:     at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_20]
	HZ2:     at c.d.r.f.d.s.s.a.loadAll(a.java:122) ~[classes/:na]
	HZ2:     at com.hazelcast.map.impl.MapStoreWrapper.loadAll(MapStoreWrapper.java:143) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.mapstore.AbstractMapDataStore.loadAll(AbstractMapDataStore.java:56) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadAndGet(BasicRecordStoreLoader.java:166) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.doBatchLoad(BasicRecordStoreLoader.java:139) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:125) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:50) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:108) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_20]
	HZ2:     at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2: 13:55:22.835 ERROR   [hz._hzInstance_1_dev.partition-operation.thread-0] --- c.hazelcast.map.impl.DefaultRecordStore  : [localhost]:9999 [3.5.4] Exception while loading map c.m.e 
	HZ2: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	HZ2:     at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.FutureUtil.checkAllDone(FutureUtil.java:346) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.DefaultRecordStore.checkIfLoaded(DefaultRecordStore.java:141) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.operation.MapSizeOperation.run(MapSizeOperation.java:41) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:137) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:154) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:110) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:101) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:76) [hazelcast-all-3.5.4.jar:3.5.4]
	HZ2: Caused by: java.lang.NullPointerException: null
	HZ2:     at c.d.r.f.d.s.s.a.load(a.java:97) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a.lambda$loadAll$2(a.java:124) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a$$Lambda$28/863580295.accept(Unknown Source) ~[na:na]
	HZ2:     at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_20]
	HZ2:     at c.d.r.f.d.s.s.a.loadAll(a.java:122) ~[classes/:na]
	HZ2:     at com.hazelcast.map.impl.MapStoreWrapper.loadAll(MapStoreWrapper.java:143) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.mapstore.AbstractMapDataStore.loadAll(AbstractMapDataStore.java:56) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadAndGet(BasicRecordStoreLoader.java:166) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.doBatchLoad(BasicRecordStoreLoader.java:139) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:125) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:50) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:108) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_20]
	HZ2:     at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2: 13:55:22.836 ERROR   [hz._hzInstance_1_dev.partition-operation.thread-0] --- c.h.map.impl.operation.MapSizeOperation  : [localhost]:9999 [3.5.4] null 
	HZ2: java.lang.NullPointerException: null
	HZ2:     at c.d.r.f.d.s.s.a.load(a.java:97) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a.lambda$loadAll$2(a.java:124) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a$$Lambda$28/863580295.accept(Unknown Source) ~[na:na]
	HZ2:     at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_20]
	HZ2:     at c.d.r.f.d.s.s.a.loadAll(a.java:122) ~[classes/:na]
	HZ2:     at com.hazelcast.map.impl.MapStoreWrapper.loadAll(MapStoreWrapper.java:143) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.mapstore.AbstractMapDataStore.loadAll(AbstractMapDataStore.java:56) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadAndGet(BasicRecordStoreLoader.java:166) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.doBatchLoad(BasicRecordStoreLoader.java:139) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:125) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:50) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:108) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_20]
	HZ2:     at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2: 13:55:22.837 ERROR   [hz._hzInstance_1_dev.partition-operation.thread-1] --- c.h.map.impl.operation.MapSizeOperation  : [localhost]:9999 [3.5.4] null 
	HZ2: java.lang.NullPointerException: null
	HZ2:     at c.d.r.f.d.s.s.a.load(a.java:97) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a.lambda$loadAll$2(a.java:124) ~[classes/:na]
	HZ2:     at c.d.r.f.d.s.s.a$$Lambda$28/863580295.accept(Unknown Source) ~[na:na]
	HZ2:     at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_20]
	HZ2:     at c.d.r.f.d.s.s.a.loadAll(a.java:122) ~[classes/:na]
	HZ2:     at com.hazelcast.map.impl.MapStoreWrapper.loadAll(MapStoreWrapper.java:143) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.mapstore.AbstractMapDataStore.loadAll(AbstractMapDataStore.java:56) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadAndGet(BasicRecordStoreLoader.java:166) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.doBatchLoad(BasicRecordStoreLoader.java:139) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.loadValuesInternal(BasicRecordStoreLoader.java:125) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader.access$100(BasicRecordStoreLoader.java:50) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.map.impl.BasicRecordStoreLoader$GivenKeysLoaderTask.call(BasicRecordStoreLoader.java:108) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:57) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:209) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_20]
	HZ2:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_20]
	HZ2:     at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_20]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[hazelcast-all-3.5.4.jar:3.5.4]
	HZ2:     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) ~[hazelcast-all-3.5.4.jar:3.5.4]

**Comment by gurbuzali** [comment]
can you please share your tests
