### ISSUE TITLE
HazelCast client spring configuration failure: "no declaration can be found for element 'hz:client'"

### ISSUE THREAD

**Issue by yjanezou** [hazelcast/hazelcast#5782]
Hi, I am adding hazelcast client into the spring configuration file as follows:

<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:jaxrs="http://cxf.apache.org/jaxrs"
    xmlns:context="http://www.springframework.org/schema/context"
    xmlns:util="http://www.springframework.org/schema/util"
    xmlns:hz="http://www.hazelcast.com/schema/spring"
    xsi:schemaLocation="http://www.springframework.org/schema/beans  http://www.springframework.org/schema/beans/spring-beans-4.1.xsd 
    http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.1.xsd 
    http://cxf.apache.org/jaxrs http://cxf.apache.org/schemas/jaxrs.xsd 
    http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.1.xsd  
    http://www.hazelcast.com/schema/spring  http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd">
    
    <hz:client id="hazelcastClient">
          <hz:group name="hazelgroup" password="hazelpass" />  
      .....

and I got errors like following:
The matching wildcard is strict, but no declaration can be found for element 'hz:client'

Could you advise what's wrong? thanks!

**Comment by bilalyasar** [comment]
@yjanezou , you closed the issue. did you solve your issue?

**Comment by yjanezou** [comment]
Thanks @bilalyasar , yeah, it was a different issue, so i closed this one.
