### ISSUE TITLE
hazelcast client side configuration

### ISSUE THREAD

**Issue by yjanezou** [hazelcast/hazelcast#5797]
Hi, I am testing an application which uses the Hazelcast Native Java Client API to connect to a Hazelcast cluster. The application uses hazelcast(IMap) as a cache to replace memcached. I wonder if anything related to cache could be configured at client side such as ttl per map? I saw such configuration can be done on the cluster server side though. But for our case, we may dynamically (on client side) add more types of map which could have different ttls.

**Comment by gurbuzali** [comment]
all configuration related to data structures should be at server-side, you cannot configure them from client-side.
However you can make use of wildcard configuration. 
http://docs.hazelcast.org/docs/3.5/manual/html/usingwildcard.html#using-wildcard

**Comment by yjanezou** [comment]
then how about the ICache?  what kind of client side configuration can be done?
