### ISSUE TITLE
Nearcache Invalidation on cache element expiry

### ISSUE THREAD

**Issue by shivlim** [hazelcast/hazelcast#5806]
Hello
Iam very new to hazelcast and have a question in this regard.We are migrating from ehcache to hazelcast and in the process i bumped into an issue(?) with hazelcast.I looked at nearcache docs but couldnt find anything about its design.
I have a simple map in hazelcast and elements are added to it during runtime and TTL is set on individual elements when they are added to map.
So i configured nearcache for this map as shown below
```
NearCacheConfig nearCacheConfig = new NearCacheConfig();
        nearCacheConfig.setMaxSize({somemaxsize})
                .setMaxIdleSeconds({somemaxidleseconds});


 mapConfig.setNearCacheConfig(nearCacheConfig);
```
But it seems like nearcache always have stale entries forever(Till max idle time expires i think).So even if an element gets expired in actual map,nearcache has that entry sitting there.But if an entry is updated in Map,it gets propagated to nearcache.So is this how its supposed to work because i was thinking expired elements will also be propagated to nearcache and that element will be removed.Is there anyway to resolve this issue where TTL of entries in nearcache is dynamic?
Hazelcast version used is 3.4.2

Many Thanks

**Comment by jerrinot** [comment]
@shivlim: Thank you for reporting this. This seems like a bug to me. @ahmetmircik ?

**Comment by enesakar** [comment]
Hi @shivlim
This is a design decision. Hazelcast handles map expiration and nearcache expiration independently.
There are seperate configurations and users are expect to handle them.
thanks for the report but I am closing the issue as we do not have a plan to change this design decision.
