### ISSUE TITLE
MapLoader blocks the entire partition when loading single entry

### ISSUE THREAD

**Issue by torkeld** [hazelcast/hazelcast#5818]
The MapLoader.load(key) method seems to be executed by the partition thread, which means that all other operations on the partition will be blocked until loading is done. A very common use case for the MapLoader is to load data from a DB, which arguable could take some time. Should really access to all other entries in that partition be blocked just because one single entry is being loaded from the DB?

From the documentation in chapter 6.1.5 Map Persistence I read:
"
NOTE: Loading process is performed on a thread different than the partition threads using ExecutorService.
"
This seems to be contrary to the actual behavior.

Reproducer: https://github.com/torkeld/hazelcast-issue-reproducer/blob/master/src/test/java/test/MapLoadTest.java

Note, although the test uses get(), the behavior is the same for executing entry processors too.

Reproduced with Hazelcast 3.2.2 and 3.4.4.

**Comment by gurbuzali** [comment]
Hi, 
The documentation is misleading and should be updated accordingly, thanks for pointing out.
The behavior you've pointed out above is strongly related with our threading-model. You check out the threading-model section of the documentation for further information
http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#threading-model

**Comment by Serdaro** [comment]
@ahmetmircik , can we look into this?

**Comment by Serdaro** [comment]
Fixed by the commit: https://github.com/hazelcast/hazelcast-reference-manual/commit/846968e59b7e8525957ff001ed935ba38c1037f5

Thank you.

**Comment by torkeld** [comment]
I understand that this bug is a manifestation of your underlying threading model, we've bumped into this design flaw before as outlined in https://github.com/hazelcast/hazelcast/issues/3146, but that doesn't mean that it can't be fixed. 
This bug essentially makes the MapLoader completely useless for any production grade system that cares about latency. Not only does the load method block a partition but all partitions that are owned by that thread, unless configured to use the same amount of threads as partitions.

How are we supposed to implement a read-through cache that doesn't block other entries while fetching and entry from backend storage?

**Comment by pablo-u** [comment]
Hi @torkeld, i'm experiencing the same issue with the reloading of my caches. Did you find a workaround?
Thanks!

**Comment by torkeld** [comment]
The only workaround I'm aware of is to not use Hazelcast...

**Comment by bacsog** [comment]
Hi,

This is clearly a major issue that will result in messed up latency characteristics. Even if there is no easy solution...

**How about at least providing a way for clients to protect vital services by introducing isolated thread-pools**?

So the most latency-sensitive caches could live on "privileged" thread-pools that does not get easily exhausted by some careless client requesting large amount not-so-important data.
