### ISSUE TITLE
NullPointerException in com.hazelcast.web.WebFilter$RequestWrapper.readSessionFromLocal

### ISSUE THREAD

**Issue by cszmajda** [hazelcast/hazelcast#5823]
We are seeing this error, seems to be new in Hazelcast 3.5.0:

```
30-Jul-2015 00:47:57.806 SEVERE [http-nio-7990-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [] threw exception
 java.lang.NullPointerException
        at com.hazelcast.web.WebFilter$RequestWrapper.readSessionFromLocal(WebFilter.java:486)
        at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:461)
        at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:392)
...
```

Was this introduced with https://github.com/hazelcast/hazelcast/pull/5471?

**Comment by bilalyasar** [comment]
Do you use session replication with another framework? (like spring) 
also do you have a scenario?

**Comment by cszmajda** [comment]
We are just using Hazelcast session replication, exactly as described in http://hazelcast.com/use-cases/web-session-clustering/generic-web-session-replication/.

It happens intermittently, to some users randomly.  Once a user triggers the problem, it seems to persist until they clear their `hazelcast.sessionId` cookie or the node is restarted. 

Looking at the code, should it not be more careful about a possible `null` return value from `sessions.get(hazelcastSessionId)`?

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/5840
