### ISSUE TITLE
hazelcast-wm WebFilter throwing NullPointerException

### ISSUE THREAD

**Issue by haixiliu** [hazelcast/hazelcast#5824]
After upgrading to 3.5.1, we are running into NullPointerException raised from WebFilter quite often in our selenium test as part of our CI process. Our Selenium test suite will run after new code is deployed into smoke servers cluster with two nodes (with a 3 minutes waiting period between end of deployment and start of SE tests). The cycle of new code deployment is every two hours or less, and the timeout of our application is defined at 60 minutes. 

The root cause of our error is NullPointerException raised from line 475 of WebFilter.java. I tried to find why hazelcastSession is null at this point and the one possible scenario is:

* originalSession's id exist as key in map originalSessions.
* The value of hazelcastSessionId based on the above key is not null.
* There is no entry based on above hazelcastSessionId as key in map sessions.

I don't know how that can happen, but it seemed to happen, and caused a NullPointerException.

I looked into the code handling the removal of entries from both originalSessions and sessions map (I believe these two map should be in sync in terms of entries), and I found a potential in method destroyOriginalSession() in WebFilter. On line 127, we are calling sessions.get(), instead of sessions.remove(), which was the case in 3.4.2 code. This change introduced potential discrepancy between originalSessions and sessions, which can result in NullPointerException on line 475 as I saw.

Can you kindly look into this issue? What's the reason behind the code change on line 127 in WebFilter in 3.5.1?

Thanks,

-Haixi

**Comment by bilalyasar** [comment]
@haixiliu, this issue seems similar to https://github.com/hazelcast/hazelcast/issues/5823 we are working on it.

**Comment by bilalyasar** [comment]
@haixiliu, this pr should fix the this issue [https://github.com/hazelcast/hazelcast/pull/5840] 
Can you try with 3.5.2-SNAPSHOT or can you try with applying fix to your project?

**Comment by haixiliu** [comment]
I will certain try and let you know.

Thanks!

- Haixi

**Comment by bilalyasar** [comment]
This issue should be solved by https://github.com/hazelcast/hazelcast/pull/5840
