### ISSUE TITLE
Management Center does not show the caches.

### ISSUE THREAD

**Issue by yjanezou** [hazelcast/hazelcast#5825]
Hi, the application has created and can use the cache (created thru  "cache = cacheManager.createCache(CACHE_NAME, config);),
 
But in the management center, there is no cache listed under Caches section. Previously I used IMap, and I can see maps created under Maps section. Could you advise? thanks.

**Comment by bilalyasar** [comment]
Did you enable cache ststistics in cache config?

**Comment by Serdaro** [comment]
Also, I think "management-enabled" element should be set as "true".

**Comment by yjanezou** [comment]
thanks, it works now!

**Comment by bilalyasar** [comment]
so i am closing the issue.
