### ISSUE TITLE
time-to-live-seconds 0 does not work

### ISSUE THREAD

**Issue by julianrz** [hazelcast/hazelcast#5837]
`<ringbuffer name="ring">
        <capacity>10</capacity>
        <time-to-live-seconds>0</time-to-live-seconds>
</ringbuffer>`

Ringbuffer<Object> ring = hazelcastInstance.getRingbuffer("ring");
long ret = ring.addAsync(bb.array(), OverflowPolicy.FAIL).get();

ret is never negative, unlike what the doc says (0 means unlimited). Setting to large number works.
This is at least in 3.5 and 3.5.1

**Comment by pveentjer** [comment]
0 doesn't mean unlimited, it means that there is no time to live.

```
   * Time to live can be disabled by setting timeToLiveSeconds to 0. It means that items won't get removed because they
     * retire. They will only overwrite. This means that when timeToLiveSeconds is disabled, that after tail did a full
     * loop in the ring that the size will always be equal to the capacity.
  
```

So in this case it will always overwrite and therefor the value will never be null.
