### ISSUE TITLE
hazelcast 3.5.1 is not able to make cluster using hzelcast-cloud plugin 3.5 in EC2 instances.

### ISSUE THREAD

**Issue by jainishshah17** [hazelcast/hazelcast#5849]
Not able to create cluster because of signature version. our system uses version 2 and cloud plugin use signature version 4.

Header with plugin 3.5 (not working)
https://ec2.amazonaws.com/?Action=DescribeInstances&Version=2014-06-15&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=KEY%2F20150801%2Fus-west-2%2Fec2%2Faws4_request&X-Amz-Date=20150801T003233Z&X-Amz-Expires=30&X-Amz-Signature=XXX&X-Amz-SignedHeaders=host

Header with plugin 3.4(working)
https://ec2.us-west-2.amazonaws.com/?SignatureVersion=2&Action=DescribeInstances&Version=2011-05-15&Signature=XXX&AWSAccessKeyId=KEY&SignatureMethod=HmacSHA256&Timestamp=2015-08-01T01%3A03%3A31.725Z

**Comment by bilalyasar** [comment]
@jainishshah17 , We made a fix to current master and maintenance branches. Can you try your case with 3.5.2-SNAPSHOT or 3.6-SNAPSHOT?

**Comment by mesutcelik** [comment]
Hi @jainishshah17 ,
I am closing the issue. please feel free to reopen it if you still see the problem.
