### ISSUE TITLE
MapListeners

### ISSUE THREAD

**Issue by RubavathiSrinivasan** [hazelcast/hazelcast#5856]
hi, we want to send a notification across hazelcast cluster when a new entry is added in hazelcast map.

MapListeners are not sending events across clusters. 
Ex, We have 3 hazelcast nodes, node1,node2 and node3, If we add a new entry in node1 it should be notified to other nodes also(map is synchronized but we need events for our own processing). Is there any options?

Thanks

**Comment by ahmetmircik** [comment]
Hi @RubavathiSrinivasan, can you please provide a simple test code which shows what the expected behaviour should be?

**Comment by RubavathiSrinivasan** [comment]
We have a map "servers", and we add an entry to the map using rest api . 
If we call rest api on node 1 server we are updating  local DB on node1 server.
The maps on three nodes are in sync. But the local DB on other nodes are not getting updated(since the rest api on node2 and node 3 are not getting called).
We want a event which can be triggered on othere 2 nodes whenever an entry is added to the "servers" map.

Sorry we couldn't share our code.Please let me know if you need any other clarifications .

Thanks

**Comment by RubavathiSrinivasan** [comment]
If we receive events on node2 and node3 on new entry we can update the localDB of the node2 and node3 servers.

node1, node2 and node3 on on Load balancer. So any server can be called at any time. But the local DB on these servers to be in sync.

**Comment by ahmetmircik** [comment]
Did you try by registering a map-listener on each node via `IMap#addEntryListener(MapListener listener, boolean includeValue)`? This way you should be notified for any event occurred on any node.

**Comment by RubavathiSrinivasan** [comment]
yes I tried, but If we add a entry on node1 , the listener is invoked on node1 itself. Actually it should be invoked on node2 and node3 .

**Comment by ahmetmircik** [comment]
It seems working. Here is my test:
```
public class MapListenerTest {

    public static void main(String[] args) throws InterruptedException {
        String mapName = "test";

        HazelcastInstance node1 = Hazelcast.newHazelcastInstance();
        HazelcastInstance node2 = Hazelcast.newHazelcastInstance();
        HazelcastInstance node3 = Hazelcast.newHazelcastInstance();

        IMap<String, String> map1 = node1.getMap(mapName);
        IMap<String, String> map2 = node2.getMap(mapName);
        IMap<String, String> map3 = node3.getMap(mapName);

        map1.addEntryListener(new ListenAdd(), true);
        map2.addEntryListener(new ListenAdd(), true);
        map3.addEntryListener(new ListenAdd(), true);

        map1.put(String.valueOf(1), String.valueOf(1));
        map2.put(String.valueOf(2), String.valueOf(2));
        map3.put(String.valueOf(3), String.valueOf(3));

        TimeUnit.SECONDS.sleep(3);
        
        Hazelcast.shutdownAll();

    }

    private static class ListenAdd implements EntryAddedListener<String, String> {
        @Override
        public void entryAdded(EntryEvent<String, String> event) {
            System.err.println("event = " + event);
        }
    }
}

```

**Comment by RubavathiSrinivasan** [comment]
Hi, We configured the listeners in hazelcast.xml instead of progamatic and it works fine . Thank you

**Comment by Serdaro** [comment]
@ahmetmircik , does this mean MapListeners cannot be configured declaratively?

**Comment by ahmetmircik** [comment]
No @Serdaro . Map-listeners should be configurable either programmatically or declaratively, if this is not the case it is bug.

**Comment by Serdaro** [comment]
Ok, thank you.
