### ISSUE TITLE
InvocationNetworkSplitTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5862]
new failure same as  #4779

```
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:61)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/633/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by jerrinot** [comment]
I think I know what's going on here: The test creates [creates a cluster](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNetworkSplitTest.java#L80) of 3 members, introduces a [split-brain](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNetworkSplitTest.java#L230) and then attempts to [heal it.](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNetworkSplitTest.java#L105) 


Now the healing process has two-steps: first it calls [prepareMerge](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java#L904) which schedules the actual merge. However the test also calls the same scheduled merge on [its own](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNetworkSplitTest.java#L106). So at the end of the day there are 2 threads attempting to call the `merge()` method. The `merge()` is protected by a [AtomicBoolean](https://github.com/hazelcast/hazelcast/blob/cb49de684405d9864deaef2e91e5bc62303bf129/hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java#L915) to ensure only 1 thread is doing a merge. In most cases it's the test thread which win the CAS. But if the scheduled thread wins then the test-thread will lose the CAS on and will return before the merge is completed -> Test Failure.

**Comment by metanet** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/5939

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: expected:<3> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:107)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationNetworkSplitTest.testWaitingInvocations_whenNodeSplitFromCluster(InvocationNetworkSplitTest.java:60)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6/com.hazelcast$hazelcast/7/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodeSplitFromCluster/

**Comment by mesutcelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-OracleJDK1.6/com.hazelcast%24hazelcast/316/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/InvocationNetworkSplitTest/testWaitingInvocations_whenNodePartiallySplitFromCluster_scenario2/

**Comment by mesutcelik** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/22ba15013db95101f4bfddf01eb6172fca2f70ee
