### ISSUE TITLE
Filter Based Web Session Replication, creates a lot of sessions in tomcat manager

### ISSUE THREAD

**Issue by StepanMelnik** [hazelcast/hazelcast#5871]
hazelcast-all-3.5.2 creates a lot of extra sessions in tomcat /manager/html/sessions while using "Filter Based Web Session Replication" solution.

Test plan:
1. use hazelcast-filter in web.xml
2) run tomcat8 on separated nodes and switch between tomcat nodes using c:\Windows\System32\drivers\etc\hosts
3) open tomcat manager/html/sessions on all nodes and check a list of sessions.

You should see extra sessions in tomcat manager.
Some of the sessions connected to static resources (.css, .js, etc). Some of the sessions created with a random id.

When hazelcast filter creates a HZ session, we should have one session in tomcat manager.

**Comment by bilalyasar** [comment]
Hi, @StepanMelnik, thanks your feedback:
I am going to reproduce your case, until now i couldn't reproduced. I am using `docker-tomcat8` + `hazelcast-code-samples filter-based web application`...

If you have time, I have some questions: 
When you disable web filter, what happens in sessions page?
Does your application has many users? ( maybe some Ddos etc)
thanks again.

**Comment by mdogan** [comment]
@bilalyasar: are you working on this? any update?

**Comment by StepanMelnik** [comment]
I do not work with the solution anymore.
We continue to work with
https://tomcat.apache.org/tomcat-8.0-doc/cluster-howto.html

On 27 November 2015 at 09:58, Mehmet Dogan <notifications@github.com> wrote:

> @bilalyasar <https://github.com/bilalyasar>: are you working on this? any
> update?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/5871#issuecomment-160076095>
> .
>



-- 
Hälsningar/Regards

*Stepan Melnik*
RnD Engineer
+380 99 168 05 82
stepan.melnik@viskan.se <sten.selin@viskan.se>

*Viskan Distanshandel System AB*
Druveforsvägen 8
504 33 Borås, Sweden
+46 33-20 60 20
www.viskan.se

**Comment by mesutcelik** [comment]
Thanks for the feedback @StepanMelnik .
please don't hesitate to reopen the issue if you can reproduce the problem.
