### ISSUE TITLE
VersionCheck uses hardcoded domain name and doesn't follow redirects

### ISSUE THREAD

**Issue by CleverMoose** [hazelcast/hazelcast#5880]
We have noticed a new error message in our logs saying:
ERROR [STDERR] [Fatal Error] :6:3: The element type "hr" must be terminated by the matching end-tag "&lt;/hr&gt;".

It seems the source of the error is VersionCheck which uses hardcoded domain name to fetch XML version document at https://hazelcast.com/version.jsp?version=2.6.1.
This url redirects to a new domain. However, VersionCheck doesn't follow HTTP redirect and attempts to parse returned HTML document.

**Comment by kobalski** [comment]
@CleverMoose Thanks for the feedback. We have disabled HTTP to HTTPS redirection on our website. You should not see the exception in your logs now. I am closing the issue, please feel free to reopen, if you see any other problems.

**Comment by CleverMoose** [comment]
I've checked latest version of VersionCheck and it seems that only purpose of this class is to report HZ cluster specific information to Hazelcast:
```
        parameterCreator.addParam("version", version);
        parameterCreator.addParam("m", hazelcastNode.getLocalMember().getUuid());
        parameterCreator.addParam("e", Boolean.toString(isEnterprise));
        parameterCreator.addParam("l", MD5Util.toMD5String(hazelcastNode.getConfig().getLicenseKey()));
        parameterCreator.addParam("p", downloadId);
        parameterCreator.addParam("c", clusterService.getClusterId());
        parameterCreator.addParam("crsz", convertToLetter(clusterService.getMembers().size()));
        parameterCreator.addParam("cssz", convertToLetter(hazelcastNode.clientEngine.getClientEndpointCount()));
        parameterCreator.addParam("hdgb", nativeMemoryParameter);
        parameterCreator.addParam("ccpp", Integer.toString(clusterClientStats.get(ClientType.CPP)));
        parameterCreator.addParam("cdn", Integer.toString(clusterClientStats.get(ClientType.CSHARP)));
        parameterCreator.addParam("cjv", Integer.toString(clusterClientStats.get(ClientType.JAVA)));
        parameterCreator.addParam("cuptm", Long.toString(clusterUpTime));
        parameterCreator.addParam("nuptm", Long.toString(runtimeMxBean.getUptime()));
        String urlStr = BASE_VERSION_CHECK_URL + parameterCreator.build();
```
To me this seems to be very different from declared (and legacy) functionality:
```
hazelcast.version.check.enabled 	  	Enable Hazelcast new version check on startup.
```
Do I miss something? 
Thank you

**Comment by kobalski** [comment]
Yes, you are right new versions of hazelcast does not use version check functionality. We will bring back version check with the new version of hazelcast. Also with the new versions, we are sending those information about the cluster. We will clearly state what data we collect in our documentation.  I am reopening this issue, you can follow updates from here.

**Comment by kobalski** [comment]
@CleverMoose We will refactor version check in 3.6 and name classes and properties accordingly.  Currently what `VersionCheck` class does sending cluster info to us daily. `3.6` is not released yet but we documented what data is collected and how to disable it. You can find more info here in `3.6-EA` docs : http://docs.hazelcast.org/docs/3.6-EA/manual/html-single/index.html#phoning-home. I am closing this issue for now.
