### ISSUE TITLE
partitionService is not updated when memberAdded or PostJoin.

### ISSUE THREAD

**Issue by wenerme** [hazelcast/hazelcast#5884]
In memberAdded or PostJoin, the partition info is not updated, so I can not rely on these callback.

I implement a new service by follow the spi, what I want to do is when new node added, I will rebackup the data, how can I achieve this ?

**Comment by pveentjer** [comment]
Which HZ version are you using?

**Comment by wenerme** [comment]
3.5

**Comment by mdogan** [comment]
@wenerme: Partitioning info is updated whenever needed lazily after cluster membership changes. It means, partitions are migrated one by one and their replicates. If you have partitioned data, you should implement `MigrationAwareService`.

**Comment by gurbuzali** [comment]
I'm closing this issue, the solution to the issue is in @mdogan 's response.
