### ISSUE TITLE
question about hazelcast configuration and cluster deployment

### ISSUE THREAD

**Issue by yjanezou** [hazelcast/hazelcast#5892]
I wonder how to make a 0-down-time if a configuration change needs to be deployed. if a cluster has 4 nodes, are all these nodes need to be bounced to get the new configuration, or just one node bouncing can pick up the change and communicate it to other nodes? 

For example, if we need to change the backup-count from 1 to 3 in production env, what steps would you advise? Thanks!

**Comment by mdogan** [comment]
Please ask your questions on google group: https://groups.google.com/forum/#!forum/hazelcast
