### ISSUE TITLE
Client MaxAggregation , MinAggregationTest, SumAggregationTest and AvgAggregationTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5916]
```
02:55:06 Running com.hazelcast.client.mapreduce.aggregation.MaxAggregationTest
04:39:50 Build timed out (after 150 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/623/console
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/617/consoleFull

**Comment by hasancelik** [comment]
```
15:55:54 Running com.hazelcast.client.mapreduce.aggregation.MinAggregationTest
17:29:16 Build timed out (after 150 minutes). Marking the build as aborted.
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3615/console

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/953/console

**Comment by sancar** [comment]
@toktarev Any idea related to these failures ?

**Comment by toktarev** [comment]
@sancar, Is it possible to check thread dump ?

**Comment by sancar** [comment]
We have thread dumps when test failed with assert, we don`t have thread dump, when we had timeouts.
So, from jenkins we don`t have that information

**Comment by hasancelik** [comment]
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1033)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1326)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:282)
	at com.hazelcast.client.proxy.ClientMapReduceProxy$ClientCompletableFuture.get(ClientMapReduceProxy.java:207)
	at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:106)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance/com.hazelcast$hazelcast-client/967/testReport/junit/com.hazelcast.client.mapreduce.aggregation/MaxAggregationTest/testLongMaxWithExtractor/

**Comment by sancar** [comment]
Similar issue https://github.com/hazelcast/hazelcast/issues/5074 is merged to this.

**Comment by sancar** [comment]
Same issue https://github.com/hazelcast/hazelcast/issues/5096
It seems like we completely ignored that test.

**Comment by metanet** [comment]
see comment: https://github.com/hazelcast/hazelcast/issues/7783#issuecomment-233252321

**Comment by mdogan** [comment]
map reduce will be deprecated soon. won't fix.
