### ISSUE TITLE
[TEST-FAILURE] metrics.metricsets.OperatingSystemMetricSetTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#5917]
```
04:32:04 Running com.hazelcast.internal.metrics.metricsets.OperatingSystemMetricSetTest
06:27:40 Build timed out (after 150 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/618/console

**Comment by pveentjer** [comment]
There is nothing obvious in this test which can lead to a timeout and the issue has not appeared since then. So I'm going to close this one.
