### ISSUE TITLE
Suspicious behavour of testRecovery_singleInstanceRemaining

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#5923]
https://github.com/hazelcast/hazelcast/blob/08857da91e497365437700243db026fda4c5c31a/hazelcast/src/test/java/com/hazelcast/xa/HazelcastXATest.java#L152  seems to have two operational modes:
- fast mode (<10s) 
- slow mode - (>2 minutes)

There is nothing in between. My guess is either our transaction recovery or the test itself is racy - sometimes a transaction is recovered successfully, but sometimes it's waiting for a timeout (2 minutes)

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/623/testReport/com.hazelcast.xa/HazelcastXATest/testRecovery_singleInstanceRemaining/history/

![image](https://cloud.githubusercontent.com/assets/158619/9197458/003a463e-403d-11e5-8836-b71ed76fd730.png)

**Comment by jerrinot** [comment]
It seems like a side-effect of #5602 - the recent changes in the lock operations. 

I can see the transaction is recovered, it's even committed, but the record is not unlocked because of this [check]( https://github.com/jerrinot/hazelcast/blob/8c6e4f9d4a4068811d17ad5e19189a83babab71d/hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java#L137)

**Comment by jerrinot** [comment]
I can reproduce & detect the problem reliably by annotating the `testRecovery_singleInstanceRemaining` test by
```
    @Test(timeout = 60 * 1000 * 1)
    @Repeat(100)
```

When I randomize the initial [`callId`](https://github.com/jerrinot/hazelcast/blob/8c6e4f9d4a4068811d17ad5e19189a83babab71d/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/CallIdSequence.java#L100) on members then the issue is gone. 

Now the question is how to fix this properly. I could split the `referenceId` into `lockReferenceId` and `unlockReferenceId` and it would probably fix this very test. But I'm afraid it's not a real solution as a transaction rollback would be still affected. @mdogan: What's your view?

**Comment by mdogan** [comment]
I did not understand, how lock and unlock are using the same `callId`? Aren't they separate invocations?

**Comment by jerrinot** [comment]
They are. However in  transactional map both invocations might be initiated by a different members and they might have the same callID -  purely by a chance. That's why randomization of initial callID makes this to go away.

**Comment by mdogan** [comment]
Ah I see. `lock` and `unlock` can be called by different members in transactions. For normal lock operations, this cannot happen. 

Maybe we can use some different reference-id (different from call-id) for transactional locks. Or we can remove reference check for them...
