### ISSUE TITLE
console.sh from the "demo" directory doesn't work as shown in the introduction video

### ISSUE THREAD

**Issue by csbubbles** [hazelcast/hazelcast#5958]
I was trying to follow the first introduction video from [this page](http://hazelcast.org/getting-started/).

* Downloaded Hazelcast v. 3.5.1 ([tar.gz](http://download.hazelcast.com/download.jsp?version=hazelcast-3.5.1&type=tar&p=112428420))
* Extracted files
* Ran console.sh from two different terminals

The expected result shown in the video should have created the only cluster formed with two nodes in it. However, what I got was two different clusters each of which contains the only node.

Is this a bug or am I missing something or doing something wrong? If this is expected behavior, the video should be changed I guess.

Below are the screenshots of logs from two instances.

`#1`

<img width="457" alt="screen shot 2015-08-13 at 8 44 29 pm" src="https://cloud.githubusercontent.com/assets/56697/9267143/e1e71edc-41fe-11e5-925e-c96569b27b91.png">

`#2`

<img width="462" alt="screen shot 2015-08-13 at 8 44 34 pm" src="https://cloud.githubusercontent.com/assets/56697/9267147/e6987a52-41fe-11e5-88ae-3badcc0ef24b.png">

**Comment by bilalyasar** [comment]
@csbubbles i saw your mail in google groups. Did you solve your issue? Can we close this issue?

**Comment by bilalyasar** [comment]
any update?

**Comment by bilalyasar** [comment]
i am closing this issue, if you encounter the problem again, please feel free to open issue. Also you can ask your questions in hazelcast mail group.
