### ISSUE TITLE
Write-behind process makes lots of unnecessary array copies under high load.

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#6006]
https://groups.google.com/forum/#!msg/hazelcast/4XA4RPCTDhQ/EbYeyglKAwAJ

**Comment by bwzhang2011** [comment]
@ahmetmircik, any update with such issue ?

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/6e46bff33f4fb3659963fcec87d271655fe8b721
