### ISSUE TITLE
Hazelcast lastest snapshot run fail due to ClientExceptionFactory brought in for creation from ClientEngineImpl.

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast#6010]
The lastest hazelcast brought in ClientExceptionFactory due to @sancar did for exception processing. but it failed due to the initialization of hazelcast instance due to the creation of ClientExceptionFactory 
as it should addd jcache api for initialization. so it's better to build the jcache jar into hazelcast (to be the fat one).
@sancar, if you have time, please spare some time and take a look at.

**Comment by sancar** [comment]
Thanks for the report.

**Comment by bwzhang2011** [comment]
Thanks for quick fix and look forward to such to be merged soon.
