### ISSUE TITLE
[TEST-FAILURE] client.lock.ClientConditionTest.testLockConditionSimpleUsage

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6023]
```
java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.lock.ClientConditionTest.testLockConditionSimpleUsage(ClientConditionTest.java:73)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast-client-new/650/testReport/junit/com.hazelcast.client.lock/ClientConditionTest/testLockConditionSimpleUsage/

**Comment by Donnerbart** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/16841/testReport/

**Comment by sancar** [comment]
@Donnerbart I think test has failed because of the followung change in your pr. 
https://github.com/hazelcast/hazelcast/pull/6741/files#diff-fc13bbcc6b8e746edd3266fed5d3d14aL46

Can you verify and close this issue ?

**Comment by Donnerbart** [comment]
You're right. I was looking at the wrong client, sorry!
