### ISSUE TITLE
Documentation should mention that public-address also accepts port

### ISSUE THREAD

**Issue by tliron** [hazelcast/hazelcast#6024]
Right now, the documentation and all examples only specify an _address_:

http://docs.hazelcast.org/docs/latest/manual/html/networkconfiguration.html#public-address

Actually, you can specify "host:port". This usage is critical for some deployment environments: for example, if you're using LXC it's very likely that your public port is different from your bound port. We've tested this and it works. (Actually, there's no way it could work without this feature.)

Furthermore, you should mention this in the config class, which is currently not documented at all:

http://docs.hazelcast.org/docs/3.5/javadoc/com/hazelcast/config/NetworkConfig.html#setPublicAddress(java.lang.String)

**Comment by Serdaro** [comment]
Thank you @tliron, required information added both to the reference manual (with examples) and to the JavaDoc.
