### ISSUE TITLE
There should be a way to create JCache Cache manager declaratively when using Spring Configuration

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6036]
There is not a nice & supported way to create an instance of JCache CacheManager when using declarative Spring configuration. 

JCache CacheManager is needed to glue JCacheCacheManager (provided by Spring) and Hazelcast. I could come-up with something like this (not tested):

```xml
<beans>
  <hz:hazelcast id="hazelcastInstance" >
<!--		[...] -->
  </hz:hazelcast>

  <bean id="cachingProvider" 
    class="com.hazelcast.client.cache.impl.HazelcastServerCachingProvider"  <!-- this is a problem as it relies on a impl class -->
    factory-method="createCachingProvider">
   <constructor-args ref="hazelcastInstance" />
  </bean>

  <bean id="jcacheCacheManager" factory-bean="cachingProvider" factory-method="getCacheManager" />

  <bean id="cacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
    <constructor-args ref="jcacheCacheManager" />
  </bean>
</beans>
```

It's not exactly concise and it relies on our implementation details. 

Something like this would be nice:
```xml
<hz:hazelcast id="hazelcastInstance" >
  <hz:config id="hazelCastConfig">
<!--  [...]  -->
  </hz:config>
           
  <hz:cache-manager id="jcacheCacheManager"> <!-- This would create a JCache CacheManager from this Hazelcast instance -->
    <some configuration, URI, etc.. />
  </hz:cache-manager>
</hz:hazelcast>

  
<bean id="springCacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
  <constructor-args ref="jcacheCacheManager" />
</bean>
```

**Comment by mustafaiman** [comment]
Hi @jerrinot 
I am trying to implement what you suggested. However I see a problem with your configuration.
Entry point for JCache API is `Caching.getCachingProvider()` method. This creates a new Hazelcast instance(server or client) and returns `HazelcastCachingProvider` based on this instance. Therefore we cannot use JCache API's entry point when parsing Spring XML configuration.

We can use `HazelcastServerCachingProvider` and `HazelcastClientCachingProvider` classes internally to create JCache caching provider which uses the instance we want(the instance Spring creates as a bean in this case). However Spring creates hazelcast instance based on the configuration specified between `<hz:hazelcast>...</hz:hazelcast>` tags. JCache CacheManager cannot be constructed from an instance which is not yet created.

What I suggest is as follows:
```xml
<hz:hazelcast id="instance">
    <hz:config>
            ...
    </hz:config>
</hz:hazelcast>

<hz:cache-manager id="hazelcastJCacheCacheManager" instance-ref="instance" name="hazelcastJCacheCacheManager" />

<bean id="cacheManager" class="org.springframework.cache.jcache.JCacheCacheManager">
    <constructor-arg ref="hazelcastJCacheCacheManager" />
</bean>
```
This way we can make Spring create a JCache cache manager that uses Hazelcast instance we want by specifying in `instance-ref` attribute.

I could not see a nice way to make it possible to put `<hz:cache-manager>` between `<hz:hazelcast>` and `</hz:hazelcast>` tags. Do you see a possible solution to the problem that I described?

**Comment by jerrinot** [comment]
@mustafaiman: I see. You explanation makes sense to me.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/6450
