### ISSUE TITLE
[TEST-FAILURE] atomiclong.AtomicLongAdvancedTest.testMultipleThreadAtomicLong

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6055]
```
java.lang.AssertionError: CountDownLatch failed to complete within 50 seconds , count left: 10
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:717)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:710)
	at com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testMultipleThreadAtomicLong(AtomicLongAdvancedTest.java:45)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/656/testReport/junit/com.hazelcast.concurrent.atomiclong/AtomicLongAdvancedTest/testMultipleThreadAtomicLong/

**Comment by sancar** [comment]
Same failures seen also here
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/659/#showFailuresLink
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/675/#showFailuresLink

**Comment by gurbuzali** [comment]
some failures 
```
	Test Result (2 failures / +2)

    com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongSpawnNodeInParallel
    com.hazelcast.concurrent.atomiclong.AtomicLongAdvancedTest.testAtomicLongFailure
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/1501/

**Comment by vbekiaris** [comment]
Not reproducible locally with a 1000-iteration execution of `AtomicLongAdvancedTest`, let's monitor builds for further failures.
