### ISSUE TITLE
XmlBuilder does not set URL in the config it parses

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#6061]
I am integrating Hazelcast in Spring Boot and I found what I think is an inconsistency. If I create the `HazelcastInstance` with the _default_ `newHazelcastInstance` static method then I get an `HazelcastInstance` whose `Config` has a valid `configurationUrl` property.

However, the following code gives me a null `configurationUrl`:

```
Config cfg = new XmlConfigBuilder(url).build();
```

Looking at `XmlConfigBuilder` it doesn't do anything with the parameter (except initializing the input stream). How about specifying the `configurationUrl` as well?

**Comment by bilalyasar** [comment]
@snicoll, seems this is small bug.
If i understand correctly, you can use this as a workaround:
```
Config cfg = new XmlConfigBuilder(url).build();
cfg.setConfigurationUrl(url);
```

**Comment by snicoll** [comment]
I'd rather put in the "inconsistency" bucket indeed :smile:

**Comment by snicoll** [comment]
Note that I am checking on my end if the url points to a file or not (calling the appropriate `configurationUrl` or `configurationFile`). If you fix this, then both attributes may be set if our url points to a file. I guess that won't be a problem, right?

**Comment by snicoll** [comment]
You have the same inconsistency if you load via the `hazelcast.config` system property (i.e. a file or URL to classpath is specified but does not show up in the `Config`).
