### ISSUE TITLE
Typo in documentation for the hazelcast.config

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#6064]
The [latest version of the documentation](http://docs.hazelcast.org/docs/latest/manual/html/configuringhazelcast.html) has a typo:

> The path can be a normal one or a classpath reference with the prefix CLASSPATH.

That's actually `classpath:`

**Comment by jerrinot** [comment]
@snicoll: Good fidinding, thanks for letting us know!

**Comment by Serdaro** [comment]
:+1:
