### ISSUE TITLE
hazelcast-wm >= 3.3 OSGI Manifest spring package imports should not be required

### ISSUE THREAD

**Issue by fwassmer** [hazelcast/hazelcast#6072]
Starting with hazelcast-wm 3.3.0 spring packages are imported and required in the Manifest.mf,
so hazlecast-wm can only be started when spring is also installed:

>org.springframework.context;version="[3.1,4)",
>org.springframework.security.core.session;version="[3.1,4)",
>org.springframework.security.web.session;version="[3.1,4)",
>org.springframework.web.context;version="[3.1,4)",
>org.springframework.web.context.support;versio n="[3.1,4)"

Those dependencies should be set to be optional with resolution:=optional
in the pom (  `<Import-Package>...` ):
e.g.: `org.springframework.context;version="[3.1,4)";resolution:=optional`

**Comment by bilalyasar** [comment]
@fwassmer yes your findings seems logical. If you want, you can create PR about this issue..

**Comment by fwassmer** [comment]
PR created: https://github.com/hazelcast/hazelcast/pull/6073

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/pull/6073
