### ISSUE TITLE
Inconsistent and potentially buggy design in BasicCompletableFuture

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#6080]
While working on a follow up of the #6062 together with Marko we've noticed some inconsistent and potentially buggy design in BasicCompletableFuture.
A pull request with an Unit Test will document what is meant here.

We've also came up with a couple of improvements that may be done in BasicCompletableFuture and AbstractCompletableFuture as soon as #6062 is merged.

**Comment by jerrinot** [comment]
@tombujok: What you are planning to do with this issue?

**Comment by tombujok** [comment]
@jerrinot Should be fixed through #6106
