### ISSUE TITLE
Hazelcast support for Spring Transaction API

### ISSUE THREAD

**Issue by kevin-long** [hazelcast/hazelcast#611]
A nice feature for Hazelcast 3.1 would be support for Spring's Transaction API. Ideally, methods could be annotated rather than the using the existing programmatic interface.

**Comment by bwzhang2011** [comment]
@emrahkocaman, thanks a lot for self-assigned for hazelcast spring transaction integration. I think it's very useful in distributed transaction area. some helpful or official support originated from hazelcast will be much more popular but thank you all the same with other support like @mpilone  support. hope it could be merged int hz-spring in 3.5 I think it's not a very complex one as there's many to be the choice.

**Comment by bwzhang2011** [comment]
@emrahkocaman, any update with such issue ?

**Comment by bwzhang2011** [comment]
@emrahkocaman, any update with such issue ?

**Comment by bwzhang2011** [comment]
@emrahkocaman, any update with such issue ?

**Comment by bwzhang2011** [comment]
@emrahkocaman, any update with such issue ? I've heard that the latest manual referred such as some new feature in hazelcast3.6.

**Comment by bwzhang2011** [comment]
@emrahkocaman, any update with such issue ?

**Comment by emrahkocaman** [comment]
Implemented by https://github.com/hazelcast/hazelcast/pull/7469
