### ISSUE TITLE
[TEST-FAILURE] CacheInvokeTest

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#6126]
com.hazelcast.client.cache.jsr.CacheInvokeTest.existingException
```
Error Message

expected IllegalAccessError; observed com.hazelcast.client.UndefinedErrorCodeException: Class name : java.lang.IllegalAccessError , Message : null
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/752/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.cache.jsr/CacheInvokeTest/existingException/

com.hazelcast.client.cache.jsr.CacheInvokeTest.noValueException
```
Error Message

expected IllegalAccessError; observed com.hazelcast.client.UndefinedErrorCodeException: Class name : java.lang.IllegalAccessError , Message : null
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/752/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.cache.jsr/CacheInvokeTest/noValueException/

com.hazelcast.client.cache.jsr.CacheInvokeTest.removeException
```
Error Message

expected IllegalAccessError; observed com.hazelcast.client.UndefinedErrorCodeException: Class name : java.lang.IllegalAccessError , Message : null
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/752/com.hazelcast$hazelcast-client-new/testReport/com.hazelcast.client.cache.jsr/CacheInvokeTest/removeException/

**Comment by serkan-ozal** [comment]
`IllegalAccessError` must be defined in `ClientProtocolErrorCodes` and must be created in `ClientExceptionFactory`. I will send a PR for fix.
