### ISSUE TITLE
C++ client shows high CPU

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6129]
This is 3.5.

The following code causes large spike in CPU usage (90%) as soon as connected with Hazelcast server.

void connect()
{
ClientConfig cf;
cf.getGroupConfig().setLicenceKey("licencekey");
Address addr("192.168.1.2,5701);
cf.addAddress(addr);
HazelcastClient *hc = new HazelcastClient(cf);
IMap<long, std::string>mymap = hc->getMap<long,std::string>("mapname");
}

Is there a bug that is causing high cpu or is there something else that needs to be configured?

**Comment by sancar** [comment]
An issue causing high cpu usage is fixed in 3.5.1 and in 3.6-SNAPSHOT. Can you try with a newer version ?

**Comment by ihsandemir** [comment]
We had the busy loop problem that was fixed as @sancar mentioned. This will most probably solve the mentioned problem. 

If it does not solve the problem, it will be helpful to get thread dump of the process to see what is going on.

**Comment by wildnez** [comment]
Cool. Let me get it tested on 3.5.2 and come back.

Thanks.

**Comment by sancar** [comment]
@wildnez Closing this for now. If you see the problem in any other version please open another issue.
