### ISSUE TITLE
Extra '\r\n' in body of REST api responses

### ISSUE THREAD

**Issue by sreis** [hazelcast/hazelcast#6144]
I'm running a single instance of the latest Hazelcast docker build and trying out the REST API. 

So it's `Hazelcast 3.5.2` with `java 1.7.0_79 OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)`

My simple golang client was complaining of `Unsolicited response received on idle HTTP channel starting` so I checked with `curl` and got this `* Excess found in a non pipelined read: excess = 2, size = 3, maxdownload = 3, bytecount = 0`

This is a screenshot of Wireshark showing an extra 2 bytes `\r\n` at the end of the message.
![hazelcast get debug](https://cloud.githubusercontent.com/assets/495294/9717918/b610449a-556e-11e5-8086-68d6237dab70.png)

Steps with `curl`:
`curl -v -X POST http://192.168.99.100:5701/hazelcast/rest/maps/example/foo -d bar`
`curl -v http://192.168.99.100:5701/hazelcast/rest/maps/example/foo`

This does the right thing:
`curl -v http://192.168.99.100:5701/hazelcast/rest/maps/example/doesnotexist`

**Comment by Donnerbart** [comment]
The REST client code sample is broken due to this issue as well. You can use it to easily check if the defect has been fixed:
```
Value for key1 is value1

Exception in thread "main" java.io.StreamCorruptedException: invalid stream header: FFFFFFE9
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:806)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
	at RestClient.main(RestClient.java:41)
```
The problematic line is:
```
objectInputStream = new ObjectInputStream(byteArrayInputStream);
```
(see https://github.com/hazelcast/hazelcast-code-samples/blob/master/clients/client-rest/src/main/java/RestClient.java#L40)

**Comment by jerrinot** [comment]
it's fixed in both maintenance and master branches.
