### ISSUE TITLE
NearCache: block until all clients have been updated

### ISSUE THREAD

**Issue by eolivelli** [hazelcast/hazelcast#6145]
In version 3.5.1 when a client updates (Map.pu, or Map.remove) the NearCache the method return without waiting for other clients to be notified of the change.
This results in possible inconsistencies of the NearCaches of different clients.

Would it be possible to have an option (per cache configuration, or per method invocation) to wait for the NearCache of other clients to be "at least" invalidated ?

**Comment by sancar** [comment]
This will require coordination between clients, which we don't have. 
And use case of this seems very limited. Therefore, we have no plans to implement this feature.

**Comment by eolivelli** [comment]
@sancar thank you. So the Hazelcast approach and roadmap is clear about this topic.

**Comment by burakcelebi** [comment]
If you find this useful then please add +1 or please contribute to development via the HEP process.

https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals
