### ISSUE TITLE
ILock{name='LeaseLockTest0'} has lease time =-1 and is locked =false

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6152]
A lock which has been obtained with a lease,  whose lease has expired and is no longer locked 
reports its    lock.getRemainingLeaseTime()  as -1,   I was expecting 0.

**Comment by gurbuzali** [comment]
here is the JavaDoc for `getRemainingLeaseTime`
```
    /**
     * Returns remaining lease time in milliseconds.
     * If the lock is not locked then -1 will be returned.
     *
     * @return remaining lease time in milliseconds.
     */
```
