### ISSUE TITLE
Unable to implement with Hibernate4

### ISSUE THREAD

**Issue by adityakrawat** [hazelcast/hazelcast#6161]
Hi Hazelcast,

Error while implementing with hibernate

Hibernate Conf: 
                 .....................
		<property name="hibernate.cache.use_second_level_cache">true</property>
		<property name="hibernate.cache.use_query_cache">false</property>
		<property name="hibernate.cache.use_minimal_puts">true</property>
		<property name="hibernate.cache.region.factory_class">com.hazelcast.hibernate.HazelcastCacheRegionFactory</property>
		<property name="hibernate.cache.hazelcast.use_native_client">true</property>
                .................................

Error: Unable to create hibernate session due to 
           java.lang.ClassNotFoundException: org.hibernate.cache.QueryResultsRegion

Checked with Hazelcast 3.5.2 and hibeanate4

**Comment by kobalski** [comment]
@adityakrawat Seems like hibernate-core jars are missing in your projects classpath. Can you make sure hibernate-core jars are present in your projects configuration? `hazelcast-hibernate4.jar` does not include hibernate-core jars. See sample app for hibernate 2nd Level Cache : https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/hibernate-2ndlevel-cache

**Comment by mesutcelik** [comment]
@adityakrawat ,
I am closing this. please feel free to reopen when suggestion doesn't work...
