### ISSUE TITLE
IOBalancer has a memory leak

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#6199]
IOBalancer keeps references of all the socket reader/writers but when destroying the connection they release the references for only the ones which has endpoints.

It could be seen from the image below that socket writers consume %77 of the total memory after all the connections to hazelcast are destroyed.

<img width="1372" alt="screen shot 2015-09-14 at 10 55 32 am" src="https://cloud.githubusercontent.com/assets/378108/9844850/44b6e3ba-5acf-11e5-9e08-558af95128bd.png">

**Comment by jerrinot** [comment]
good one!

**Comment by serkan-ozal** [comment]
good finding :+1:

**Comment by mahileeb** [comment]
we're seeing another memory leak in IOBalancer in v3.6 - Socket readers/writers are building up in LoadTracker.lastEventCounter. They are getting added to the ItemCounter by updateNewWorkingImbalance the handler is not removed from the ItemCounter when removeHandler is called.

Can we re-open this issue or should I open a new one?

**Comment by eminn** [comment]
I am working on a reproducer for your case.

**Comment by eminn** [comment]
Thanks @mahileeb issue has been fixed and the fix will be available on 3.6.2 and 3.7
