### ISSUE TITLE
[TEST-FAILURE] executor.CompletableFutureTest.cancellation_afterDone_taskNotCancelled_flagsSetCorrectly

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6202]
```
java.lang.AssertionError: Cancellation should not succeed after task is done
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at com.hazelcast.executor.CompletableFutureTest.cancellation_afterDone_taskNotCancelled_flagsSetCorrectly(CompletableFutureTest.java:218)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/661/testReport/junit/com.hazelcast.executor/CompletableFutureTest/cancellation_afterDone_taskNotCancelled_flagsSetCorrectly/

**Comment by hasancelik** [comment]
@tombujok Do you have any idea about this issue ? Any relation with #6020 ?

**Comment by tombujok** [comment]
@hasancelik I'll have a look.

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK9-Quality-Outreach/com.hazelcast$hazelcast/195/testReport/junit/com.hazelcast.executor/CompletableFutureTest/noCancellation_afterDone_flagsSetCorrectly/
