### ISSUE TITLE
Proposition: MapClientProxy should also use near cache in getAll and getAsync methods

### ISSUE THREAD

**Issue by blancqua** [hazelcast/hazelcast#624]
For now, as I see in the code of Hazelcast 2.6, the near caching is only used in the method "get" on MapClientProxy. Might be a good enhancement also using it on getAll and getAsync, and maybe others.

Kind regards,
Wouter Blancquaert, Software Architect

**Comment by geemein80** [comment]
We would like to continue to use version 2.6...

Is there any danger in overriding MapClientProxy.getAsync( K key ) and have it use the near cache? If not, what is the reason for this? Thanks.
