### ISSUE TITLE
InvocationFuture race: race on exception

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#6247]
When an InvocationFuture processes a  thrown exception e.g one from the operation.run, it will rewrite the stacktrace so that both local and remote stacktraces are integrated. 

```
 private Object resolveApplicationResponse(Object unresolvedResponse) {
        ...

        if (response instanceof Throwable) {
            Throwable throwable = ((Throwable) response);
            if (invocation.remote) {
                fixRemoteStackTrace((Throwable) response, currentThread().getStackTrace());
            }
            return throwable;
        }

        return response;
    }
```

The problem is that this exception-instance can be shared between multiple threads since the future can be shared between multiple threads. So you have multiple threads modifying a stacktrace of the same exception instance.

Solution: clone the exception first.

Edit: for a remote thrown exception this probably isn't an issue since each thread will get a Data and deserialize that data. Not completely sure about this. But for local exception is could certainly be an issue.

**Comment by mdogan** [comment]
@pveentjer: are you going to fix this in 3.6?

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?  please take a look at #4809 when timeout invoked, hazelcast itself will rewrite the stacktrace as you commented.  by the way, would you mind leaving more message for us that how to adjust to be prevented from such like #4809 described (what's more, for IQueue test, it's not related to memory consumption or network issue) and some times it's very easy to lead to such.

**Comment by jerrinot** [comment]
@pveentjer: are you working on this one?

**Comment by pveentjer** [comment]
I think the best approach is to change our current exception handling strategy and always wrap the thrown exception by some unchecked version of the ExecutionException. This way there is no need for exception rewriting. The main problem is unwrapping the exception where needed.

**Comment by tombujok** [comment]
@pveentjer Will you tackle it in 3.7?

**Comment by pveentjer** [comment]
This issue isn't going to be fixed in 3.x. We need to break API's to make this work properly.

**Comment by mmedenjak** [comment]
Current version uses `com.hazelcast.util.ExceptionUtil#fixAsyncStackTrace` for both remote and local invocations:
https://github.com/mmedenjak/hazelcast/blob/a8e4d5265630e9ca2dbb4c0c45d9d8db4bb948fb/hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java#L124-L128
