### ISSUE TITLE
Map.Lock does not expire correctly for short lived locks 

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast#6257]
Lock expiry doesn't seem to work correctly for short lived locks, i.e. locks which are <1s.

Modifying ClientMapTest.testLockTtl by changing the expiry values to 100ms and 200ms from the originals of 2 and 5 seconds will result in a test failure. 
```
    @Test
    public void testLockTtl() throws Exception {
        final IMap map = createMap();
        map.put("key1", "value1");
        assertEquals("value1", map.get("key1"));
        map.lock("key1", 100, TimeUnit.MILLISECONDS);
        final CountDownLatch latch = new CountDownLatch(1);
        new Thread() {
            public void run() {
                map.tryPut("key1", "value2", 200, TimeUnit.MILLISECONDS);
                latch.countDown();
            }
        }.start();
        assertTrue(latch.await(10, TimeUnit.SECONDS));
        assertFalse(map.isLocked("key1"));
        assertEquals("value2", map.get("key1"));
        map.forceUnlock("key1");
    }
```

**Comment by jerrinot** [comment]
I would say this is a feature, not a bug. The lock lease is ceiled into seconds so the lock is held longer then expected by the other thread. 

When you check the return value of the `tryPut` then it's false. Hence the latch is release pre-maturely. 

Perhaps we could document this behaviour better.

**Comment by gurbuzali** [comment]
I also think that this is not a bug, no need to be precise on a millisecond level in a clustered environment.
