### ISSUE TITLE
possible problem with IQueue in failover scenario

### ISSUE THREAD

**Issue by tmazzaro** [hazelcast/hazelcast#6280]
Hello, 
we have two members in a HZ cluster. we use IQueue with

backup-count=1

and we add programmatically an ItemListener withing a static initializer. 

this queue is used to pub / consume event from-to different parts of the system

in a failover scenario where one of the nodes is shutdown and then resumed, we observe some of the events pushed to the queue dont trigger the listener, which is not invoked. 
Is there something we are missing eg something we need to do in the lifecycle of the node, or maybe a known issue? 
Thanks
TM

**Comment by pveentjer** [comment]
I guess this is caused because events are getting lost since the events send, are not highly available.

**Comment by bwzhang2011** [comment]
@gurbuzali, @pveentjer, any update with such issue ?

**Comment by gurbuzali** [comment]
As @pveentjer mentioned in a fail-over scenario events are not highly available and may get lost.
We plan to enhance our eventing-system so that it will be highly available in failover scenarios

**Comment by gurbuzali** [comment]
I've created another issue to clearly state this in our reference-manual https://github.com/hazelcast/hazelcast-reference-manual/issues/100

Thank you for your contribution
