### ISSUE TITLE
IdGenerator enhancement: provide more control on the pre-allocated ids range

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#6281]
It'd be nice to be able to specify custom size of pre-allocated range. The 1000000 size used by default can be too big under some circumstancies. I propose just to add a new overloaded method:

boolean init(long id, int size); 

where the idGen could be initialized with custom range size. This is backward-compatible change, existing code will still use default range size of 1000000.

Thanks, Denis.

**Comment by dsukhoroslov** [comment]
Also, would be nice to be able to configure the generator from hazelcast/spring XML config file.

**Comment by jerrinot** [comment]
Hi @dsukhoroslov,

I don't really know the IdGenerator that much, but could you please describe a use-case where too large range is harmful?

**Comment by dsukhoroslov** [comment]
Hi @jerrinot 

Imagine that someone use idGen to generate Ids, but assign only an int part of the id to his key, just in order to keep space.

**Comment by wimdeblauwe** [comment]
+1 for this. We are using the IdGenerator to generate unique ids which are then stored in the database. It would be nice if the id's generated from different nodes are not so far apart. I understand this will have a small performance penalty if you make this lower, but this will be no problem for my type of application.

**Comment by pveentjer** [comment]
It makes sense to have it configurable. This way one can have control on how often a new id-sequence needs to be checked out.

**Comment by gurbuzali** [comment]
we don't use `1000000` as default, it is `10000`. I believe this is an acceptable value. contributions are welcome to make it configurable

**Comment by mmedenjak** [comment]
@dsukhoroslov @wimdeblauwe is the chunk size of `10000` still too large for you? Can we close this issue?

**Comment by dsukhoroslov** [comment]
@mmedenjak, there is no one value which will fit all cases. The range must be configurable.

**Comment by dbrimley** [comment]
We would recomend that you upgrade to flake ids which are coming 3.10.  Flake has a configurable pre-fetch size.
