### ISSUE TITLE
Possible issue in OperationThread

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast#6318]
It looks like ```OperationThread.priorityPendingCount()``` should be returning ```scheduleQueue.prioritySize()``` instead of ```scheduleQueue.normalSize()```

```
    @Probe
    int priorityPendingCount() {
        return scheduleQueue.normalSize();
    }

    @Probe
    int normalPendingCount() {
        return scheduleQueue.normalSize();
    }

```

**Comment by jerrinot** [comment]
@juanavelez: Great finding, many thanks!

**Comment by bwzhang2011** [comment]
@juanavelez, @jerrinot, shoud this be back port ?

**Comment by jerrinot** [comment]
@bwzhang2011: I just send a PR to the master branch. Probes in 3.5 are less detailed and this functionality is missing -> this issue is not present there.

**Comment by bwzhang2011** [comment]
@jerrinot, thanks for feed back.
