### ISSUE TITLE
[TEST-FAILURE] ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_NoPreCheck & _PreCheck

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6327]
```
java.lang.AssertionError: Unwanted QueryResultSizeExceededException was thrown while calling IMap.values() with limit 100000 and upperLimit 150000
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.failUnwantedException(ClientMapUnboundReturnValuesTestSupport.java:196)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.internalRunWithoutException(ClientMapUnboundReturnValuesTestSupport.java:241)
	at com.hazelcast.client.map.ClientMapUnboundReturnValuesTestSupport.runClientMapTestWithoutException(ClientMapUnboundReturnValuesTestSupport.java:86)
	at com.hazelcast.client.map.ClientMapUnboundReturnValues_BasicTest.testClientMap_withoutException_PreCheck(ClientMapUnboundReturnValues_BasicTest.java:30)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/723/testReport/junit/com.hazelcast.client.map/ClientMapUnboundReturnValues_BasicTest/testClientMap_withoutException_PreCheck/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/723/testReport/junit/com.hazelcast.client.map/ClientMapUnboundReturnValues_BasicTest/testClientMap_withoutException_NoPreCheck/

**Comment by Donnerbart** [comment]
This is expected since Peter changed the underlying methods to use the query system. I have to adapt the tests, the JavaDoc of the methods (which may now throw the `QueryResultSizeExceededException`) and maybe the reference manual.

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/724/#showFailuresLink

**Comment by Donnerbart** [comment]
Should be fixed via: https://github.com/hazelcast/hazelcast/commit/8225b75bcd08303b057ea0a4abdfa8566895cd4e (until the new client or maybe the txn map proxy will be switched)

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client-new/736/testReport/junit/com.hazelcast.client.map/ClientMapUnboundReturnValues_BasicTest/testClientMap_withoutException_PreCheck/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client-new/736/testReport/junit/com.hazelcast.client.map/ClientMapUnboundReturnValues_BasicTest/testClientMap_withoutException_NoPreCheck/

**Comment by Donnerbart** [comment]
As I already wrote, will be fixed: "until the new client or maybe the txn map proxy will be switched to use predicates as well". We switched the new client to use the queries as well, so the failure is now in the new client (was old client before).

Has already been fixed via: https://github.com/hazelcast/hazelcast/commit/0189aadfaf447e62c18d7177287ec1d8211b0ee8
