### ISSUE TITLE
Wrong numbers in CPU Utilisation columns in ManCentre - 3.4.1

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6336]
Numbers in CPU utilisation columns are not aligned with the chart in 4th column in Management Centre. See attached screenshots. This is 3.4.1.
![image001](https://cloud.githubusercontent.com/assets/7980465/10213855/dbf00366-682f-11e5-9d4b-34fa297efccc.png)
![image002](https://cloud.githubusercontent.com/assets/7980465/10213856/dbf46cee-682f-11e5-9f33-8c4eefa56f82.png)

**Comment by emrahkocaman** [comment]
Moved to https://github.com/hazelcast/hazelcast/issues/6344
