### ISSUE TITLE
Hazelcast fails to shutdown reliably during testing

### ISSUE THREAD

**Issue by Dretch** [hazelcast/hazelcast#6339]
I have a set of integration tests that create a new Spring container, containing a new Hazelcast instance for each test class. This is using `SpringJUnit4ClassRunner`.

Hazelcast doesn't always shutdown at the end of each test - it stays alive and forms a cluster with the new Hazelcast from the following test. This seems to happen more often with `3.5.2` (vs `3.4.1`). This behaviour means our integration tests often fail.

I realise this is a rather vague bug report - I will try and put together a repeatable test...

**Comment by mesutcelik** [comment]
Hi @Dretch ,
Were you able to reproduce the problem? That would help us alot as reproducing the problem consistently is mostly hardest part of the fixing the issue.

**Comment by Dretch** [comment]
@mesutcelik 

Unfortunately thus far I have not been able to reproduce the problem with a simple test case. I will try again when I have time.

**Comment by enesakar** [comment]
closing issue. please re-open it when you can reproduce it, providing a test if possible.

**Comment by nicusX** [comment]
Hi,
I was able to reproduce the problem and somehow found a workaround.
Unfortunately it requires a full (but minimalistic) Spring Boot application to reproduce.
https://github.com/nicusX/hazelcast-6339

Apparently, when running integration tests (Spring test loading Application Context and Hazelcast through Spring boot) you should NOT explicitly call ```Hazelcast.shutdownAll()``` in the```@After```  method. Something that works fine in non-Spring tests.

**Comment by hcapitaine** [comment]
Hi,

I'm having the same issue. It would be great to reopen it or link it to a new one.

Thanks

**Comment by Bert-R** [comment]
@enesakar: I have created a repo with a repro for this issue: https://github.com/Bert-R/hazelcast-shutdown-issue

Can you please reopen this issue and work on a fix?

**Comment by gurbuzali** [comment]
Hi @Bert-R 
Hazelcast by-design does not shutdown itself, you need to call the shutdown explicitly.
And if you want to close your application at the end, you can call `close` on the returning context like this.
```
        SpringApplication app = new SpringApplication(TheApplication.class);
        app.setWebEnvironment(false);
        ConfigurableApplicationContext context = app.run(args);
        context.close();
```

**Comment by Bert-R** [comment]
That would work for a ``CommandLineRunner``, but it doesn't address the case of a web service that fails to start.

I now understand the perspective of Hazelcast, but shouldn't Spring Boot be shutting down Hazelcast in such cases? I didn't start Hazelcast, so I shouldn't have to stop it, right?

**Comment by gurbuzali** [comment]
I see your point but I don't think this is a Hazelcast related issue. I suggest you to open an issue on springboot repository

**Comment by Bert-R** [comment]
Done. Thanks for looking into this.

**Comment by Bert-R** [comment]
As pointed out by @wilkinsona on spring-projects/spring-boot#7418, in our case, it was a matter of initializing Hazelcast properly.
