### ISSUE TITLE
StreamSerializers for collections

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#634]
There are no streamserializers for collections like list, map etc. So a user needs to write them themselves.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?  for the batching process way, batch support for serializer is appreciated.

**Comment by mmedenjak** [comment]
Related: https://github.com/hazelcast/hazelcast/issues/8791

**Comment by ihsandemir** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/15371

**Comment by mmedenjak** [comment]
Thanks for the implementation @ihsandemir , closing.
