### ISSUE TITLE
ManCentre documentation on CPU utilisation to be more elaborate

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6344]
In the following description - 

"The first column lists the nodes with their IPs and ports. The next columns list the loads on each CPU for the last 1, 5 and 15 minutes. The last column (Chart) graphically shows the utilization of CPUs. When you move the mouse cursor on a desired graph, you can see the CPU utilization at the time where the cursor is placed. Graphs under this column shows the CPU utilizations approximately for the last 2 minutes."

There's required more elaborate description of "loads on each CPU". Something like:

The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time.

**Comment by emrahkocaman** [comment]
@Serdaro ,

We show system load average in the columns named 1min, 5mins and 15 mins;
From javadocs of the utility methods that we use to gather this data;
`The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average.
If the load average is not available, a negative value is returned.`
Javadoc: https://docs.oracle.com/javase/8/docs/api/java/lang/management/OperatingSystemMXBean.html?is-external=true#getSystemLoadAverage--

And in the chart, we show cpu load;
`the "recent cpu usage" for the whole system. A value of 0.0 means that all CPUs were idle during the recent period of time observed, while a value of 100.0 means that all CPUs were actively running 100% of the time during the recent period being observed. All values betweens 0.0 and 100.0 are possible depending of the activities going on in the system. If the system recent cpu usage is not available, a negative value is shown`.
Javadoc: https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad--

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/9904aa8bbe2d107d8d733cd9ffd62ec3bd9b03e8
