### ISSUE TITLE
XSDs for Spring Configuration Not Visible

### ISSUE THREAD

**Issue by pjreid** [hazelcast/hazelcast#6390]
I'm trying to use the __hz__ namespace in my Spring Application Context. However the XSDs for this are not available.

The published url - *http://hazelcast.com/schema/spring/hazelcast-spring.xsd* redirects to an _https_ url. However that ur returns a 404 response.

**Comment by pjreid** [comment]
Added an additional dependency for __hazelcast-spring-<version>.jar__

With that in place the XSDs are read directly from the Jar file rather than the web. It still would be nice if the XSDs were visible on the URIs though ;0)

**Comment by jerrinot** [comment]
I agree. It should be published. It will require some sort of versioning, but that's just an implementation detail.

**Comment by mesutcelik** [comment]
Hi @pjreid ,
We have published xsds already. https://hazelcast.com/schema/spring/hazelcast-spring-3.6.xsd
is this what you need?

**Comment by pjreid** [comment]
Thanks Mesut, that is helpful.

If I was being very fussy, I would suggest that having the entire directory visible would be nice too. ATM if I try to browse the root directory - https://hazelcast.com/schema/spring/ <https://hazelcast.com/schema/spring/> I get a 403 Forbidden response.

Thanks,

Paul

**Comment by mesutcelik** [comment]
Hi @pjreid ,
You can see the list of all XSDs in the following URLs.
https://hazelcast.com/schema/spring/
https://hazelcast.com/schema/client-config/
https://hazelcast.com/schema/config/
