### ISSUE TITLE
ManCenter - Provide ability to vary length of histograms when viewing IMap

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#6403]
The current ManCenter (3.5.2) shows various graphs at the top of the page when viewing an IMap.  The x-axis seems to be fixed at 1.5 mins.  It would be great to be able to configure a different time period for display ( ideally any rolling window period ).

**Comment by emre-aydin** [comment]
Closing the issue as it's very old and we have plans to make graphs more configurable in the near future.
