### ISSUE TITLE
Id like to be able to see total getRequests on an IMap (in mancenter or via code)

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#6404]

**Comment by emre-aydin** [comment]
Closing as we already provide this statistic on Management Center.

**Comment by StanAccy** [comment]
I don't believe the stat shows all get requests. I'll double check but I
believe there are scenarios where we don't inc the count.

**Comment by emre-aydin** [comment]
@StanAccy feel free to re-open the issue with your findings.
