### ISSUE TITLE
Improper eviction with USED_HEAP_PERCENTAGE in 3.5.0

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6411]
Problem:

No of members in cluster : 1
For Hazelcast server we  configured 32 GB as heap memory size. USED_HEAP_PERCENTAGE was set to 10% . Eviction should happen once heap crosses approximately 3.2 GB mark .
 
Cache configuration:
 
               <map name="Cache1">
                                                <in-memory-format>BINARY</in-memory-format>      
                                                <backup-count>0</backup-count>        
                                                <async-backup-count>1</async-backup-count>              
                                                <max-size policy="USED_HEAP_PERCENTAGE">10</max-size>
                                                <eviction-policy>LFU</eviction-policy>
                                                <eviction-percentage>1</eviction-percentage>              
                                                <merge-policy> com.hazelcast.map.merge.HigherHitsMapMergePolicy</merge-policy>             
                                                </map>                                               
 
We populated Cache1 with entries, and  when hazelcast server JVM  crossed 4 GB size, the totalEvictedEntryCount in JConsole was still 0 for Cache1.
 
Then we  added more entries to Cache1 and when localOwnedEntryMemoryCost crossed 3.2GB mark , the eviction happened as per the configuration(1% eviction percentage) of the cache.

This behaviour could not be verified using Management Centre as ManCentre itself shows quite heap usage, even when no data is stored in Hazelcast server.

**Comment by enesakar** [comment]
already fixed

**Comment by dmitry-tsechoev** [comment]
Assalamu alaykum. Good day.

Please, check also FREE_HEAP_PERCENTAGE policy of max-size for the map. I've had similar problems in version 3.5.3.

Upon reaching the limit memory consumption continued to grow. It seems that the eviction does not start.

Part of config:

<map name="rfr_main">
    <backup-count>0</backup-count>
    <time-to-live-seconds>18081</time-to-live-seconds>
    <max-idle-seconds>18081</max-idle-seconds>
    <eviction-policy>LRU</eviction-policy>
    <max-size policy="FREE_HEAP_PERCENTAGE">20</max-size>
    <eviction-percentage>25</eviction-percentage>
    <read-backup-data>false</read-backup-data>
</map>

![selection_005](https://cloud.githubusercontent.com/assets/7009886/11805916/a07843d0-a320-11e5-9e4f-3822a43494d4.png)

The same with FREE_HEAP_SIZE policy.

Regards.

**Comment by ahmetmircik** [comment]
Hi @dmitry-tsechoev, 

Did you try by to set `<min-eviction-check-millis>0</min-eviction-check-millis>` to zero default is 100 ms? 

```
<map name="rfr_main">
    <backup-count>0</backup-count>
    <time-to-live-seconds>18081</time-to-live-seconds>
    <max-idle-seconds>18081</max-idle-seconds>
    <eviction-policy>LRU</eviction-policy>
    <max-size policy="FREE_HEAP_PERCENTAGE">20</max-size>
    <eviction-percentage>25</eviction-percentage>
    <read-backup-data>false</read-backup-data>
    <min-eviction-check-millis>0</min-eviction-check-millis>  <------ HERE
</map>
```

And also please try your case with the latest SNAPSHOT version.

To use the snapshot with maven, just replace ${hazelcast.version} below with  `3.6-RC2-SNAPSHOT`
```
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>${hazelcast.version}</version>
</dependency>
<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

**Comment by dmitry-tsechoev** [comment]
Thank you for your answer and help, Ahmet.
