### ISSUE TITLE
Received a JoinRequest with a different packet version!

### ISSUE THREAD

**Issue by niteshjain132** [hazelcast/hazelcast#6430]
Upgraded from Hazlecast 3.0.x to 3.5.2 and when two nodes connects using multicast i see this in log repeatedly..

Node1:

WARNING: [x.x.x.x]:5701 [hazelCluster] [3.5.2] Received a JoinRequest with a different packet version! This -> 4, Incoming -> 1, Sender -> /x.x.x.x
Oct 12, 2015 11:57:15 AM com.hazelcast.cluster.impl.MulticastService

Node2:
WARNING: [x.x.x.x]:5701 [hazelCluster] [3.5.2] Received a JoinRequest with a different packet version! This -> 4, Incoming -> 1, Sender -> /x.x.x.x
Oct 12, 2015 11:53:52 AM com.hazelcast.cluster.impl.MulticastService

Hazelcast network configuration :
<pre>

            multicast-group :  224.2.2.4
            multicast-port : 34466
            multicast-time-to-live : 64
            multicast-timeout-seconds : 2
</pre>

**Comment by jerrinot** [comment]
@niteshjain132: Hi, it seems like there is an older version of Hazelcast  running in your network.

**Comment by niteshjain132** [comment]
WARNING: [x.x.x.x]:5701 [hazelCluster] [3.5.2] Received a JoinRequest with a different packet version! This -> 4, Incoming -> 1, Sender -> /x.x.x.x

the Sender x.x.x.x is the one who is sending JoinRequest ?

**Comment by jerrinot** [comment]
@niteshjain132: That is correct.

**Comment by jerrinot** [comment]
@niteshjain132: Please let me know if you found an older Hazelcast version running in your network. 
You can prevent this by using a different multicast address in different clusters. See this: http://docs.hazelcast.org/docs/3.5/manual/html/multicast.html

**Comment by niteshjain132** [comment]
Thanks @jerrinot 
Updating the Multicast address/port worked, as there were older version of hazelcast running in the same network.

**Comment by jerrinot** [comment]
@niteshjain132: That's great to know! I'm closing this issue. Feel free to re-open it if you experience this issue again.
