### ISSUE TITLE
Eviction with "eviction-percentage" does not work

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6432]
With the following properties:

           <map name="Cache1">
                        <in-memory-format>BINARY</in-memory-format>      
                        <backup-count>0</backup-count>        
                        <async-backup-count>0</async-backup-count>              
                        <max-size policy="PER_NODE">400</max-size>
                        <eviction-policy>LRU</eviction-policy>
                        <eviction-percentage>20</eviction-percentage>              
                        <merge-policy> com.hazelcast.map.merge.HigherHitsMapMergePolicy</merge-policy>             
           </map>                                               

Add 420 entries and IMap.size returns 378 whereas size should have been 320. This is consistently reproducible.

After discussion with @gurbuzali it turns out that the documentation at http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#configuring-map-eviction needs to be corrected to the following:

eviction-percentage: When max-size is reached, the specified percentage of a map's partition will be evicted. For example, if set to 25, 25% of the entries will be evicted. Setting this property to a smaller value will cause eviction of a smaller number of partition entries. Therefore, if entries are inserted frequently, smaller percentage values may lead to overheads. Valid values are integers between 0 and 100. The default value is 25.

**Comment by ahmetmircik** [comment]
@wildnez did you try by to set `<min-eviction-check-millis>0</min-eviction-check-millis>` to zero default is 100 ms?

**Comment by wildnez** [comment]
@ahmetmircik yes I did and it did not have any impact.

**Comment by gurbuzali** [comment]
fixed via https://github.com/hazelcast/hazelcast-reference-manual/commit/ff78720989b996c151e78bd08450076eacd721c9
