### ISSUE TITLE
Spring security integration - setting properties in SpringAwareWebFilter

### ISSUE THREAD

**Issue by mpusarla** [hazelcast/hazelcast#6438]
I am trying to integrate Hazelcast in spring security. Configured SpringAwareWebFilter instead of WebFilter. I used to have the following configuration in applicationContext.xml

    <bean id="hazelcastWebFilter" class="com.hazelcast.web.WebFilter">
		    <constructor-arg>
			    <props>
				    <prop key="map-name">sessions</prop>
				    <prop key="sticky-session">true</prop>
				    <prop key="test1">${app.cookie}</prop>
				    <prop key="test2">${app.secure}</prop>
			    </props>
		    </constructor-arg>
    </bean>

but now, with springAwareWebFilter, the only way I can specify the properties is using the init-param.

I would like to keep the properties separate from the web.xml? Can you let me know how can i set the properties outside web.xml?

**Comment by serkan-ozal** [comment]
@mpusarla you are right. 
`SpringAwareWebFilter` should have a constructor which takes properties as argument like this:

``` java
public class SpringAwareWebFilter extends WebFilter {
    
    ...

    public SpringAwareWebFilter(Properties properties) {
        super(properties);
    }

    ...
}
```

I will add this to `SpringAwareWebFilter` then you can use `SpringAwareWebFilter` as `WebFilter` by constructor argument in `applicationContext.xml`.

Thanks for reporting this one.

**Comment by mpusarla** [comment]
Thanks!
