### ISSUE TITLE
Determine memory-size of IMap should not iterate over all records

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#6442]
To determine the memory size of an IMap is done by iterating over all map entries and therefor has complexity of O(N) with N being the number of entries. This should be reduced to O(1) by updating the size on every change made on a map.

Chewing through all member is bad.. it will hog a thread for a long time.. it will polute the caches. This is done done periodically to update the management center.

Other data-structures like ICache should be checked as well.

**Comment by gurbuzali** [comment]
Check `SizeEstimator` interface, it is already done as you've suggested for IMap

**Comment by pveentjer** [comment]
Closing this ticket since it s already implemented.
