### ISSUE TITLE
Nodes get kicked if they are not reachable by at least one node

### ISSUE THREAD

**Issue by dctr** [hazelcast/hazelcast#6464]
Hi,

i am using Vert.x and i think my problem is hazelcast-specific, so i post my issue here and hope i am right.

I want a hazelcast cluster of three nodes A, B1, and B2, where the Bs can talk to A but not to each other (due to some network restrictions).

The Bs get the IP address of A and the log shows them connecting. However, a few seconds later B1 discovers B2 is not reachable and it gets kicket out of the cluster.

I did not find any possibility to specifiy the minimum number of node reachable before leaving or a voting to kick a node for non-reachability.

Did i overlook something or is this maybe a missing feature in hazelcast.

Regards,

dctr

**Comment by enesakar** [comment]
Yes, currently if a node is reachable by master node (the oldest one), then it is not kicked out from cluster even other nodes can not connect it.

**Comment by gurbuzali** [comment]
This behavior is not provided currently and not planned in the near future
