### ISSUE TITLE
HazelcastClientCacheManager  getNearCacheManager()  Missing,  backward Incompatibility

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#6477]
the method  getNearCacheManager()  from  class HazelcastClientCacheManager has been removed ?

and is now a causing backward  Incompatibility

**Comment by Danny-Hazelcast** [comment]
@sancar,  did this method move some where else ?  

I also see HazelcastClientCacheManager  is in an impl package,  
and so is not picked up by the binary / source compatibility check,  i made on the jar's

http://54.87.52.100/~jenkins/workspace/compatibility/os/compat_reports/hazelcast-all/3.5.2_to_3.5.3/compat_report.html

but with a name like HazelcastClientCacheManager  sounds like i want to use it.

**Comment by sancar** [comment]
I have removed it because it was never used and it is in impl package. 
@serkan-ozal  also know about this, he was telling me that he will put that to a well defined public api for a customer use case. I don't know the current status. 
@serkan-ozal ?

**Comment by serkan-ozal** [comment]
yes, I had thought that I should have a better way but couldn't spare time on it. I think we can add the old one at the moment.

**Comment by serkan-ozal** [comment]
I have added back the old one. I will handle it in better way later.

**Comment by serkan-ozal** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/0a0bb8ca3cf5d6f1762df8f950a774ec1a838e29
