### ISSUE TITLE
Hazelcast : Email alert notification is not working for 2.4 version

### ISSUE THREAD

**Issue by AnshumanDwivediTCS** [hazelcast/hazelcast#6506]
We have observed that Hazelcast "mancenter" email alert notification does not work properly for 2.4 version. 

In below log, we can observe the same  -
----------------------------------------------------------------------------------------------------------
Email could not send to myid@mydomain.com
Email could not send to myid@mydomain.com
Email could not send to myid@mydomain.com
Oct 18, 2015 8:38:29 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-apr-8080"]
Oct 18, 2015 8:38:29 AM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-apr-8009"]
Oct 18, 2015 8:38:29 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina

**Comment by mesutcelik** [comment]
Hi @AnshumanDwivediTCS ,

Email notifications are coming with better support in 3.6. We are releasing 3.6-EA soon so you can try it immediately and give us the feedback. That would be much appreciated.

Here are a few options to be notified about latest news and releases.
* follow Hazelcast Twitter Account [@hazelcast](https://twitter.com/hazelcast) 
* check out Hazelcast Download Page http://hazelcast.org/download/
* join Hazelcast Google Groups https://groups.google.com/forum/#!forum/hazelcast

I am closing this issue now as Hazelcast 2.4 is too old to add email notifications features.

**Comment by AnshumanDwivediTCS** [comment]
Ref : https://github.com/hazelcast/hazelcast/issues/3693
