### ISSUE TITLE
[Feature request] Add possibility to enable "spring-aware" mode programmatically

### ISSUE THREAD

**Issue by dtitov** [hazelcast/hazelcast#6514]
Hi! 

According to last comments in thread (https://github.com/hazelcast/hazelcast/issues/5323#issuecomment-149307371) the need to have possibility to enable "spring-aware" mode programmatically had appeared. 

Probably that can be achieved via introducing a system property and/or @EnableSpringAware like annotation.

**Comment by dsukhoroslov** [comment]
The Config class should get isSpringAware/setSpringAware methods, probably?

**Comment by dtitov** [comment]
Yes, that would be nice, I guess.

**Comment by dtitov** [comment]
How's it going, guys?

**Comment by mesutcelik** [comment]
We are in Feature Freeze now so we can't add new features into current release(3.6).However, this request is one of the items that we might put into next release(3.7).

please follow-up this issue for the progress.

many thanks.

**Comment by dtitov** [comment]
Sorry for bothering, but is there any update? What are the plans about 3.7 release and about this feature?

**Comment by emrahkocaman** [comment]
Hi @dtitov ,

Here is the code snippet to enable `SpringAware` annotation programmatically.

```
    @Bean
    public SpringManagedContext managedContext() {
        return new SpringManagedContext();
    }

    @Bean
    public HazelcastInstance instance() {
        Config config = new Config();
        config.setManagedContext(managedContext());
        return Hazelcast.newHazelcastInstance(config);
    }
```
I've also created a sample project;
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/springaware-annotation

Can you please give this a try and share the results with us?

**Comment by dtitov** [comment]
Thank you! That works perfectly.

**Comment by messo** [comment]
@emrahkocaman wouldn't the method invocation of `managedCotnext()` will create a new object? I would write the following:

```java
    @Bean
    public SpringManagedContext managedContext() {
        return new SpringManagedContext();
    }

    @Bean
    public HazelcastInstance instance(SpringManagedContext managedContext) {
        Config config = new Config();
        config.setManagedContext(managedContext);
        return Hazelcast.newHazelcastInstance(config);
    }
```

**Comment by dtitov** [comment]
@messo , I guess if you call `managedContext()` within Spring configuration class, it returns the singleton instance of a bean without creating new one.

**Comment by messo** [comment]
@emrahkocaman @dtitov thanks, I had to check it, but yes indeed, it seems the whole config class is enhanced as a CGLIB proxy, and the method invocation of `managedContext()` goes through the same proxy. Thanks! :)

**Comment by dtitov** [comment]
Thanks for checking it, now we know it for sure :)

**Comment by emrahkocaman** [comment]
@dtitov @messo Thanks for trying this out guys. Invoking `@Bean` annotated methods within a `@Configuration` annotated class should not be a problem since the config class is subclassed with CGLIB.
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/beans.html#beans-java-further-information-java-config

I'm closing this issue then. Please do not hesitate to reopen it if you've problems.
