### ISSUE TITLE
Possible memory leak with IMap.containsKey

### ISSUE THREAD

**Issue by gfelisberto** [hazelcast/hazelcast#6517]
I am making some tests with IMap in Hazelcast 3.5.3.  These tests are being run with -Xms100M -Xmx100M.

My Map has <Integer, String> where I had 2MB Strings, running with no eviction  will exhaust memory around 30 items.

First I added an eviction policy at 20 items. This made the test run perfectly with items being evicted when needed.

I then added a MapStore. As these are just local tests the store simply saves and loads to a file in disk, in a real scenario persistence would be done to a distributed persistence. With the MapStore i can recover items that were present in the past and update them.

Problem happens when I use containsKey for a value that exists in the MapStore. I see the Item being loaded from the Store but it does not get added to the Map (no event being triggered in this case), eventually the system crashes with no memory.

The code is a bit long so I added it to a gist: https://gist.github.com/gfelisberto/1075ea5428920c9a2746 I can move it here if needed.

**Comment by gfelisberto** [comment]
After some more testing I found that changing line 77 from:
if (cache.containsKey(keyCount)) {
to
if (cache.get(keyCount) != null) {

also triggers the load from the store, as expected, but the values never get evicted.

**Comment by pveentjer** [comment]
@ahmetmircik can you have a look?

**Comment by ahmetmircik** [comment]
@gfelisberto Thanks for reporting this one.

**Comment by gfelisberto** [comment]
Thank You!!

**Comment by gfelisberto** [comment]
I just now had a chance to run my bug report agains 3.5.4 and it still happens. It actually seems worst than before.

In 3.5.3 there is some eviction during the loading of the cache. Now no eviction happens and the test fails much sooner.

**Comment by gurbuzali** [comment]
re-opening, let me check what went awry

**Comment by gurbuzali** [comment]
Hi @gfelisberto 
The problem with your setup is you are using default partition count (271) and a max-size=20 per-node.
This results in dividing max-size(20) to partitionCount(271) to find out per-partition max-size which will end up being 1 (ceiled to it since 0 as max-size meaningless). So practically you cannot set max-size lower than the partitionCount if you are using a single node. You can set partitionCount to 1 and see it for yourself. 

I believe this behavior should be documented clearly, I've created another issue for this https://github.com/hazelcast/hazelcast-reference-manual/issues/99

Thank you for your contributions

**Comment by gfelisberto** [comment]
Ok, that makes sense. 

I did some changes to accommodate those requirements:
mapConfig.setMaxSizeConfig(new MaxSizeConfig(300, MaxSizeConfig.MaxSizePolicy.PER_NODE));
mapConfig.setMinEvictionCheckMillis(10);
Also increase the cycle size to 500, the Thread.sleep decreased to 25 and  the memory to 900MB.

The main cycles works OK with keys being loaded and evicted, but the third cycle with the containsKey() I only see loades and no evictions and it still crashes with no memory.

**Comment by gurbuzali** [comment]
sorry for wasting your time, I've found out that the fix couldn't made into 3.5.4 release. it will be released in 3.5.5, please see my PR milestone. I've updated the issue's milestone accordingly.

**Comment by gfelisberto** [comment]
This is still not fixed in the 3.5 branch.

I was testing my code with 3.5.5 and results were strange, I was getting null values from cache for things previously added.
I changed my code a bit to detect those issues (the GIST has the new version) and tested with several versions.

**3.5.5**
After just 16 insertions into the cache it starts triggering eviction of objects that were just added and get(K) returns a null instead of the expected value.


**3.6-EA**
No eviction is seen in the last loop and it crashes:
Feb 12, 2016 6:45:25 PM com.hazelcast.map.impl.operation.ContainsKeyOperation
SEVERE: [172.18.0.38]:5701 [dev] [3.6-EA] Java heap space
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.ensureAvailable(ByteArrayObjectDataOutput.java:360)


**3.6-EA2**
No eviction is seen in the last loop and it crashes:
Feb 12, 2016 7:35:43 PM com.hazelcast.map.impl.operation.ContainsKeyOperation
SEVERE: [172.18.0.38]:5701 [dev] [3.6-EA2] Java heap space
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.ensureAvailable(ByteArrayObjectDataOutput.java:360)

**3.6-RC1**
This does not crash with OutOfMemoryError nor does it return null values. But as with version 3.5.5 it starts eviction really early on and releases values that were just added to the cluster not following the LRU policy.
