### ISSUE TITLE
Thread Dumps freeze in Man Centre

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6536]
Management Centre shows same thread dumps for all the connected members, same traces, same thread IDs and all on same line numbers. 

jstack pid shows correct dumps - different for all members. This is consistently reproducible.

**Comment by emrahkocaman** [comment]
It's an UI bug. Thread dumps are appended to the modal window.
Fixed.
Master: https://github.com/hazelcast/management-center/commit/bf8032514af44abd1e044d1d4a5fac60091d4a77
Maintanance :  https://github.com/hazelcast/management-center/commit/d4d0e479fced00cee367a459f9449294602f5e4c
