### ISSUE TITLE
Incorrect Map Hit count in Man Centre

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6537]
Hit count of a Map on individual members as well as Total Hit count keeps fluctuating. Both Hit count - individual member and Total, should only increase based on application and not fluctuate.

**Comment by emrahkocaman** [comment]
@wildnez , I've put a key and get it 4 times and see no problem there.

![image](https://cloud.githubusercontent.com/assets/2887123/10663377/9b7c295a-78c3-11e5-9781-5ddb856b7417.png)

Do you have a suggestion to reproduce it?

**Comment by wildnez** [comment]
Leave it running for long hours, I'd say 4 - 5 and keep on pounding Maps. You can add a delay of 1 sec between 2 map calls.

**Comment by enesakar** [comment]
do we store hit count on records? if yes, we can lose some stats like hits when record is evicted or removed?

**Comment by ahmetmircik** [comment]
@enesakar yes it is on records.

**Comment by muratayan** [comment]
@wildnez is eviction or removal of entries happening? If so it is related to what @enesakar mentioned above. @pveentjer also suggested that we should change the way of collecting map stats (https://github.com/hazelcast/hazelcast/issues/6442) so this could be a feature request for 3.7.
