### ISSUE TITLE
Wrong documentation of Client SSL

### ISSUE THREAD

**Issue by wildnez** [hazelcast/hazelcast#6539]
Documentation at http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#ssl is wrong:

ClientConfig config = new ClientConfig();
config.getSocketOptions().setSocketFactory( new SSLSocketFactory( props ) );

2 problems here:
a. config.getSocketOptions() is a deprecated API
b. there is no setSocketFactory(......) method

SSL on Client can not be configured using this documentation.

**Comment by david-strom-hazelcast** [comment]
Please keep me (one of the tech writers) in the loop on this.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/7c38d994f80805f956dfe4bce949ac0a1e188590
