### ISSUE TITLE
Clear all maps from mancenter console

### ISSUE THREAD

**Issue by mozinrat** [hazelcast/hazelcast#6553]
is there a way to delete all maps from mancenter console

we can do for individual maps as below

> ns mapname
> m.clear

but how to execute clear on all maps.

**Comment by royremi** [comment]
Any progress on that? would be wonderful to be able to go in the consol and flush all the maps in 1 command!

**Comment by jbee** [comment]
Hi!
You can use the following script: 
```javascript
function clearMaps() {
    var instances = hazelcast.getDistributedObjects();
    var res = "";
    for each(instance in instances) {
        if (instance.getServiceName() == "hz:impl:mapService") {
            var map = hazelcast.getMap(instance.getName());
            map.clear();
            res += "cleared " + instance.getName() + "\n";
        }
    }
    return res;
}
clearMaps();
```

**Comment by emre-aydin** [comment]
Closing this as there's a workaround. @royremi feel free to reopen if this doesn't solve your problem.
