### ISSUE TITLE
ManCenter should show serialization setting for Maps in MapConfig

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#6585]
It would be helpful to see the IMap serialization type (BINARY etc) in the MapConfig within ManCenter.  If this could be shown as a read-only property on the config dialog, it would be helpful.

**Comment by muratayan** [comment]
Thank you for your improvement suggestions (along with #6572 & #6573).

**Comment by burakcelebi** [comment]
Closed as internal request
