### ISSUE TITLE
Distributed Events missing registration examples in documentation

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/hazelcast#6595]
Within the current documentation we have a few missing code samples for distributed events.

http://docs.hazelcast.org/docs/latest/manual/html-single/hazelcast-documentation.html#distributed-events

For example, MembershipListener docs show an interface implementation but there is no sample code of where or how to register this listener, there is no mention of this at all. The same is true for MigrationListener, PartitionLostListener, LifecycleListener and also MessageListener.

**Comment by pveentjer** [comment]
Should this not be an issue in the documentation repo?

https://github.com/hazelcast/hazelcast-reference-manual

**Comment by dbrimley** [comment]
Hi Peter,

Close this and moving over.  Thanks for the tip

David.
