### ISSUE TITLE
Management Center - I'd like to be able to sort/filter the "Memory/CPU Utilization" view by host name

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#6598]
With larger grids, trying to find specific instances is a bit of a chore (ManCenter v3.5.3).  If we could sort the various tables by hostname (specifically in this case the Memory Utilization and CPU Utilization on the "Home" tab) it would be helpful.  
On a similar note, it would also be helpful if we could sort the list of Members by hostname / IP address as well.

Furthermore, for the CPU/Memory utilization views, what I really want is a quick filter.  I want to be able to select the view, and start typing to filter the data view.  On larger grids, just being able to sort is better than it is currently, but what we really want to do is locate a specific node - so a quick filter would be ideal.  Maybe you could add a little search icon (magnifying glass) in to one of the upper corners.  Clicking that would pop-out/open a single text search box, and then the view would dynamically filter based on entered text.  The more I think about this, I think this would be a useful feature on _all_ data views - much easier than paging through 10+ pages of nodes (for Map analysis, CPU etc)

**Comment by emre-aydin** [comment]
This has been implemented with grid views in MC 3.10.
