### ISSUE TITLE
Custom credintials class is not de-serialized on the server side

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#6615]
HZ 3.6-EA. 
I use custom cridentials class which inherits from UsernamePasswordCredential class. I need to provide some additional auth data from client to server. Till version 3.5.3 it works fine: the custom credentials class was deserialized and used on the server side. In 3.6-EA the standard UsernamePasswordCredential class deserialized instead. Auth message created on the server side is AuthenticationMessageTask, but it must be AuthenticationCustomCredentialsMessageTask, I believe.

Please have a look.
Thanks, Denis.

**Comment by enesakar** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/6644
