### ISSUE TITLE
Add CDI Support 

### ISSUE THREAD

**Issue by dansiviter** [hazelcast/hazelcast#6617]
This means JCache `CacheLoader`, JCache `CacheWriter`, `MapLoader`, `MapStore` and distributed tasks can have resources injected using `@Inject` and should honour the scope defined for those beans. Is should also be implied that if injected then they are also `transient` to not fall foul of serialisation semantics.

The initial implementation could support the CDI reference implementation Weld.

This is related to #6616

**Comment by jerrinot** [comment]
This is a duplicate of #440
