### ISSUE TITLE
inconsistency between hazelcast invalid config exceptions

### ISSUE THREAD

**Issue by bilalyasar** [hazelcast/hazelcast#6624]
In hazelcast, if user has invalid config, we are throwing invalid config exceptions. In some cases, we are throwing run time exceptions. We need to examine those exceptions and provide consistency.

**Comment by mesutcelik** [comment]
any example?

**Comment by kobalski** [comment]
One example can be like here, that line was only throwing `RuntimeException` before : https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java#L152

**Comment by mmedenjak** [comment]
Closing as duplicate of https://github.com/hazelcast/hazelcast/issues/14713
