### ISSUE TITLE
MapLoader blocks the partition when loading an entry [HZ-1176]

### ISSUE THREAD

**Issue by timurstrekalov** [hazelcast/hazelcast#6646]
I understand that this is the "expected behaviour", judging by #5818 (although I'm not sure if it's expected by any user implementing a MapLoader), but I believe this is a massive problem, which basically makes any real-life MapLoader implementation a performance issue waiting to happen.

I do think this should be addressed and not discarded by simply acknowledging it in the documentation.

**Comment by ChristerF** [comment]
+1 This is very fundamental and we would love to know if there is a plan to change this.

**Comment by krasnyt** [comment]
+1
Any update in 2018?

**Comment by Holmistr** [comment]
@krasnyt @ChristerF @timurstrekalov I know it's been a long time now but we're finally implementing this one in 5.2. Sorry it took so long :)
