### ISSUE TITLE
com.hazelcast.cluster.impl.MulticastJoiner#calculateTryCount quite high in virtualized environment

### ISSUE THREAD

**Issue by marcust** [hazelcast/hazelcast#6687]
Im running hazelcast inside a dockerized environment on Mesos, which makes me set a different public visible address and port than the one actually configured as port.

The way calculateTryCount works makes me get a really high try count
```
"[172.31.32.142]:31866 [dev] [3.5.2] Starting SocketAcceptor on sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:5701]"
"[172.31.32.142]:31866 [dev] [3.5.2] finished starting threads, calling join"
"[172.31.32.142]:31866 [dev] [3.5.2] Searching for master node. Max tries: 78547"
"Old String constructor doesn't seem available"
"[172.31.32.142]:31866 [dev] [3.5.2] Dropped: JoinRequest{packetVersion=4, buildNumber=20150826, address=Address[172.31.32.142]:31866, uuid='89670c95-1ea6-410e-aa9d-aae63b9345d9', credentials=null, memberCount=1, tryCount=1}"
```

which basically makes findMasterWithMulticast never return (well, technically it will return after two hours, but that is a little bit long to wait for the startup of the initial node).

Can you somehow limit that? I'm not sure that I understand all the implications here (or the way calculateTryCount uses all those factors and for what reasons) thus I can't PR.

**Comment by metanet** [comment]
Closed by #6884
