### ISSUE TITLE
Misleading log in EventServiceImpl

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#6723]
There exists a misleading log entry in EventServiceImpl.sendEvent method. It says:

`logFailure("IO Queue overloaded! Failed to send event packet to: %s", subscriber);`

However; the failure is not about IO queue, indeed it is about connection drop.

**Comment by eminn** [comment]
fixed via 324d099b6da7bdbf43a7e527837d90ff94d6929a
