### ISSUE TITLE
A Question For Spring Security With Session

### ISSUE THREAD

**Issue by vrigan** [hazelcast/hazelcast#6725]
The problem is session is null;

For example:
send 'index.html' request
create new session 123456 and Hazelcast will save it too
response session 123456

send 'api/authentication' take session 123456 
auth ok and response new session 654321

When Spring Security on auth by org/springframework/security/web/authentication/AbstractAuthenticationProcessingFilter.java line 223;
This function will do Spring Security SessionFixation;

In servlet3.1 default SessionFixation Strategy is ChangeSessionId,So the session will be change;

After Hazelcast will auto found the not in originalSessions sesssion(654321) and remove it;

**Comment by mesutcelik** [comment]
Hi @vrigan ,

Do you have any test case to reproduce the problem?

**Comment by vrigan** [comment]
Problem details is missing;Close issues;
