### ISSUE TITLE
Management center. Throughput differs from get, put and removes sum

### ISSUE THREAD

**Issue by Matzz** [hazelcast/hazelcast#6730]
Hi,
I have situation where throughput differs from sum of gets, puts and removes. Throughput is about 4k but gets, puts and removes are on 0. I attach the screen
![screen](http://cdn.pbrd.co/images/26v1Ilsh.png)

**Comment by emrahkocaman** [comment]
Hi @Matzz, This might be happening since time period is selected  "Last Minute"  in "Map Through Data Table" and in charts also. What is time period of "Throughput" chart and can you please share your management center version?

**Comment by emrahkocaman** [comment]
Closing this issue since throughput graphs/charts are depending on the selected time period.
