### ISSUE TITLE
Timeout for threads waiting to acquire lock on Imap key 

### ISSUE THREAD

**Issue by shyam4u** [hazelcast/hazelcast#6739]
I am trying to acquire a lock on a key of a Imap by using Imap.tryLock(key)

Below is a code snippet to show how am acquiring lock .For a non existent key ,I am making an entry into the Imap to get the lock .

    public boolean lock(final String key) throws Exception {
        boolean acquiredLock = false;
        if (key == null) {
            throw new IllegalArgumentException("key to be locked cannot be null");
        }

        try {
            if (!getIMap().containsKey(key)) {
                getIMap().put(key, "anyValue");
            }
            acquiredLock = getIMap().tryLock(key);
            if (acquiredLock) {
                getIMap().lock(key, 30, TimeUnit.SECONDS);
            }
        } catch (final Exception exception) {
            LOG.error("Exception occured while trying to lock the key: ");
            throw exception;
        }
        return acquiredLock;
    }
    public void unlock(final String key) throws Exception {
        try {
            getIMap().forceUnlock(key);
            getIMap().remove(key);

        } catch (final Exception e) {
            LOG.error("Exception occured while trying to unlock the key: ", e);
            e.printStackTrace();
            throw e;
        }
    }

At my application layer where i need this lock .I call this lock method and do my operation after acquiring lock .Once my operation is done ,I trigger the unlock .
Now my question is 
1.If there are say 3 threads T1 ,T2,T3 waiting for this lock and say T4 already have the lock and is currently doing stuff .T1,T2,T3 can only get lock if T4 finishes its work or the lease time expires .
I need to know if there is a way in which I can make each of the waiting thread to wait for say 20 secs max to acquire lock or else timeout and don't try to get the lock anymore.
I could think of 2 things 
1.Retry for a fixed no of times say .If fixed no of attempts fails to acquire lock timeout and skip the operation to be done after acquiring lock .The fixed no of times check can be wrapped in this lock method.
2.If a thread fails to acquire lock then sleep for say 2 secs and again try .If it fails to acquire skip the operation .

Any suggestions would be a welcome .Let me know if you see any glaring issue in this code block.

**Comment by gurbuzali** [comment]
we've introduced tryLock with lease time in 3.6
```
/**
     * Tries to acquire the lock for the specified key for the specified lease time.
     * <p>After lease time, the lock will be released.
     * <p/>
     * <p>If the lock is not available, then
     * the current thread becomes disabled for thread scheduling
     * purposes and lies dormant until one of two things happens:
     * <ul>
     * <li>the lock is acquired by the current thread, or
     * <li>the specified waiting time elapses.
     * </ul>
     * <p/>
     * <p><b>Warning:</b></p>
     * This method uses <tt>hashCode</tt> and <tt>equals</tt> of the binary form of
     * the <tt>key</tt>, not the actual implementations of <tt>hashCode</tt> and <tt>equals</tt>
     * defined in the <tt>key</tt>'s class.
     *
     * @param key           key to lock in this map.
     * @param time          maximum time to wait for the lock.
     * @param timeunit      time unit of the <tt>time</tt> argument.
     * @param leaseTime     time to wait before releasing the lock.
     * @param leaseTimeunit unit of time to specify lease time.
     * @return <tt>true</tt> if the lock was acquired and <tt>false</tt>
     * if the waiting time elapsed before the lock was acquired.
     * @throws NullPointerException if the specified key is null.
     */
    boolean tryLock(K key, long time, TimeUnit timeunit, long leaseTime, TimeUnit leaseTimeunit)
            throws InterruptedException;
```
You don't need to put an entry to use lock, you can simply say:
```getIMap().tryLock(key, 20, TimeUnit.SECONDS, 30, TimeUnit.SECONDS);```
checkout 3.6-EA (EarlyAccess) to try it out

**Comment by shyam4u** [comment]
Thanks ..let me try this

**Comment by shyam4u** [comment]
We cannot use hazelcast 3.6 EA .Do you have work around ...
