### ISSUE TITLE
Acquiring lock on a key in Imap for multithreading set up  

### ISSUE THREAD

**Issue by shyam4u** [hazelcast/hazelcast#6742]
I have a Imap on which I plan to acquire a lock against a key in the Imap .There would be multiple threads trying to acquire the lock and I have 2 conditions to satisfy .

1.I have the luxury to skip the operation needed to be performed after acquiring the lock -if the wait time for acquiring the lock is more than 20 milliseconds .
2.After completion of my lock I can unlock the key and I also plan to have a lease time for which the lock can be acquired by a thread .

Below is my code block 
1. Here I check if a lock is available and if I acquired the lock ,I again lock the key for 40 milliseconds(lease time) .The lock is released after the operation is done or after lease time if over .
2. If another thread comes to acquire the lock ,I t would wait for 20 secs or it should skip the operation .
My questions here wrf to the code below 
For a thread who acquired the lock am i locking twice ? 
What will happen if I triggger the below statement in sequence for a thread who acquired the lock.

 boolean acquiredLock = getImap().tryLock(key, 20, TimeUnit.Milliseconds);
            if (acquiredLock) {
                getImap().lock(key, 40, TimeUnit.Milliseconds);
                LOG.debug("locked for key  and by thread>>>>>>" + Thread.currentThread().getName());
            }

**Comment by shyam4u** [comment]
I cannot use the latest version of Hazelcast and my project uses 3.3

**Comment by gurbuzali** [comment]
yes, above code will achieve what you want. it will cost 2 network hops for locking though.
And for unlocking you need to unlock twice(which again will cost 2 network hops) or use forceUnlock.

**Comment by shyam4u** [comment]
will forceUnlock remove all locks on a key .So if in this process I lock twice do I need to trigger forceUnlock twice ?

**Comment by shyam4u** [comment]
When the lock is applied by the same thread .it should ideally be one lock

**Comment by shyam4u** [comment]
Is there any way I can get how many locks are currently put on a Imap and which are the keys which are currently locked ??

**Comment by jerrinot** [comment]
`forceUnlock()` will remove all reentrant locks. It's sufficient to call it just once.

**Comment by shyam4u** [comment]
If I use a forceUnlock ..think of this situation ..
We have thread T1 and T2 waiting for a lock on key 1 and currently say T3 is executing .T3 finished it stuff and triggerred the forceUnlock ..in that case will T1 and T2 get a lock or not??

**Comment by jerrinot** [comment]
I believe so. either T1 or T2 should acquire the lock. That's the behaviour I'd expect.

**Comment by shyam4u** [comment]
In the above code block I have pasted I would end up doing 4 network hops for locking a key and finally unlocking them ..do u suggest any alternative way of doing it .You can refer to this issue for a detailed code block of my issue 

https://github.com/hazelcast/hazelcast/issues/6739

**Comment by shyam4u** [comment]
Do u say if T1 and T2 are waiting and still within 20 s (wait time configured for locks to via TryLock) the invoking of a forceUnlock () by another thread would have no effect on them ?

**Comment by jerrinot** [comment]
If multiple threads are waiting to acquire a lock and the lock is released then one of the waiting threads will acquire the lock. It does not matter if the release was done via regular `unlock()`, `forceUnlock()` or expired lease time.

Bear in mind the lock expirations have a resolution of 1 second. If you lock a key for 40ms then it will be released in +-1s. 

The another issue could be this:

- T1 acquires a lock with lease time set to 10 second. T2 is waiting to acquire the same lock
[...10 seconds later...]
- lease for T1 expires ---> T2 acquires the lock
- T1 is done with its work and calls `forceUnlock()` <--- this could be a problem as it will remove the lock ownership from T2. 

I don't know what you are trying to achieve, but if I was you then I would try to solve it without using locks. EntryProcessors can be often replace locking. Obviously this highly depends on your use-case.

**Comment by shyam4u** [comment]
Yes that is what I am worried as well because the forceUnlock would always release the lock irrespective of the thread who locked it .In the situation you described above , T1  would be releasing the lock when T2 has just started working after acquiring a lock ...

**Comment by shyam4u** [comment]
I cannot use an entryProcessor as we have multiple projects sharing the same cluster and using entry processor would affect all of them ..

**Comment by pveentjer** [comment]
I'm going to close this ticket since it isn't really a ticket. Feel free to continue discussing. If a bug comes up are a feature is needed; feel free to create a new ticket.
