### ISSUE TITLE
replicatedmap.destroy() goes into an infinite loop

### ISSUE THREAD

**Issue by eminn** [hazelcast/hazelcast#6754]
`destroyDistributedObject()` method on `ReplicatedMapService` iterates over partition containers and record stores and destroys them. While destroying, record store calls `destroyDistributedObject()` which leads to an infinite loop.

**Comment by pveentjer** [comment]
How can it end in an infinite loop because the object is removed from the partition before it gets destroyed.

```
  public void destroy(String name) {
        ReplicatedRecordStore replicatedRecordStore = replicatedStorages.remove(name);
        if (replicatedRecordStore != null) {
            replicatedRecordStore.destroy();
        }

    }
```

So if   replicatedRecordStore.destroy() leads to a call to ReplicatedMapService, the loop will be broken because the replicatedRecordStore doesn't exist anymore.

Or am I wrong?

**Comment by eminn** [comment]
You are right about that, the loop is broken at some point but even if so, the call to replicated map service leads to unnecessary iteration of partition containers again and again.
