### ISSUE TITLE
Not able to flush the haselcast cache once it reaches configured number of entries

### ISSUE THREAD

**Issue by niteshjain132** [hazelcast/hazelcast#6761]
configuration in hazelcast.xml

<map name="TEST_CACHE">
    <max-size policy="PER_NODE">3</max-size>
    <eviction-policy>LFU</eviction-policy> 
</map>

Test code

public class Test implements EntryEvictedListener , Serializable{

    private static final long serialVersionUID = -1927328346902661527L;
    private static HazelcastInstance hazelcastInstance = HazelCacheUtil
            .getHazelCacheInstance();
    private static volatile IMap<Object, Object> hazel_cache = hazelcastInstance
            .getMap("TEST_CACHE");

    public static void main(String[] args) throws Exception {
        hazel_cache.addEntryListener(new Test(),true);

        for (int i = 0; i < 3; i++) {
            hazel_cache.put(i+1, new Test());
        }
        System.out.println(hazel_cache);

        System.out.println("");
        for (Entry e : hazel_cache.entrySet()) {
            System.out.println(e.getKey() + " : " + e.getValue());
        }
    }

    @Override
    public void entryEvicted(EntryEvent e) {
        System.out.println(e.getKey()+" : "+e.getOldValue()+"\n");
    }
}

and in entryEvicted i'm only getting the 3rd entry object

 Entry EVICTED
 3 : com.test.CAO.Test@5a6b6126

is there any way to flush the cache content into a file/db once max-size is reached ?

**Comment by gurbuzali** [comment]
can you please clarify the configuration of hazelcast, and please share all of the cofiguration.

**Comment by niteshjain132** [comment]
@gurbuzali , please find the below configuration xml used

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<group>
		<name>hazelCluster</name>
		<password>hazelCluster</password>
	</group>
	<network>
		<join>
			<multicast enabled="true">
				<multicast-group>224.2.2.4</multicast-group>
				<multicast-port>34466</multicast-port>
				
				<multicast-time-to-live>64</multicast-time-to-live>
				<multicast-timeout-seconds>2</multicast-timeout-seconds>
			</multicast>
		</join>
	</network>
	
	<map name="TEST_CACHE">
		<max-size policy="PER_NODE">3</max-size>
		<eviction-policy>LFU</eviction-policy> 
	</map>
	
	<properties>
		
		
		<property name="hazelcast.icmp.ttl">64</property>
		
		<property name="hazelcast.icmp.enabled">true</property>
		
		<property name="hazelcast.icmp.timeout">3000</property>
	</properties>
</hazelcast>

**Comment by gurbuzali** [comment]
Hi,
since you've defined a max size of 3 per node, whenever that size reached eviction kicks in.
eviction mechanism will try to evict some entries, default `MapConfig.evictionPercentage` is 25 so hazelcast will try to evict 1/4 of the entries. And hazelcast will fire an eviction-event for only the evicted entries.

Please find more info regarding eviction here:
http://docs.hazelcast.org/docs/3.5/manual/html-single/hazelcast-documentation.html#map-eviction

you can ask your questions regarding the usage of hazelcast on Hazelcast Google Group
https://groups.google.com/forum/#!forum/hazelcast

**Comment by niteshjain132** [comment]
Hi @gurbuzali i have updated the eviction percentage to 100, even then its not evicting all the entries in the map

```
<map name="TEST_CACHE">
		<max-size policy="PER_NODE">10</max-size>
		<eviction-percentage>100</eviction-percentage>
		<eviction-policy>LRU</eviction-policy> 
		<time-to-live-seconds>0</time-to-live-seconds>
	</map>
```
