### ISSUE TITLE
Small corrections to Mastering Hazelcast

### ISSUE THREAD

**Issue by gfelisberto** [hazelcast/hazelcast#6762]
In the Mastering Hazelcast I found some issues:

Chapter 10 - Transactions

The first example:
TransactionContext txCxt = hz.newTransactionContext();
TransactionalMap<String, String> map = txCxt.getMap("map");
txCxt.beginTransaction();

This gives an error, the txCxt.beginTransaction(); needs to be called before getting the TransactionalMap.

10.1-

There is no beginTransaction(), and also the context.getMap("employees"); should be txCxt.getMap("employees");

**Comment by Serdaro** [comment]
Thank you @gfelisberto , I will correct it this week.

**Comment by Serdaro** [comment]
Fixed by https://github.com/hazelcast/hazelcast-book/commit/3578eaa442d137972220988d70950e1094b35187
