### ISSUE TITLE
3.6-EA: java.io.EOFException when using Kryo to serialize EntryProcessors

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#6781]
I have a custom Kryo serializer that I use to serialize most of my classes, and it works well with Hazelcast 3.5.
With Hazelcast 3.6-EA, however, Kryo is not working with EntryProcessors.
In a cluster of 2+ nodes, I'll get *com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException* whenever the EntryProcessor is invoked.
I'm using Kryo 3.0.3.

Here's what the full stack trace looks like:

    Nov 19, 2015 6:01:32 PM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
    SEVERE: [10.192.16.109]:5701 [dev] [3.6-EA] Failed to process packet: Packet{header=1, isResponse=false, isOperation=true, isEvent=false, partitionId=80, conn=Connection [/10.192.16.109:5701 -> /10.192.16.109:19307], endpoint=Address[10.192.16.109]:5702, alive=true, type=MEMBER} on hz._hzInstance_1_dev.partition-operation.thread-0
    com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.EOFException
        at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:71)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:166)
        at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:232)
        at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:371)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPacket(OperationThread.java:184)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:137)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
        at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
    Caused by: java.io.EOFException
        at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataInput.readBoolean(ByteArrayObjectDataInput.java:115)
        at com.hazelcast.spi.impl.operationservice.impl.operations.Backup.readInternal(Backup.java:233)
        at com.hazelcast.spi.Operation.readData(Operation.java:568)
        at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:121)
        at com.hazelcast.internal.serialization.impl.DataSerializer.read(DataSerializer.java:47)
        at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
        at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:160)
        ... 6 more

The following code reproduces the issue 100% (**be sure to start at least two instances of it** - the Exception does not happen when running in a single node):

    package hazelcast;

    import com.esotericsoftware.kryo.Kryo;
    import com.esotericsoftware.kryo.io.Input;
    import com.esotericsoftware.kryo.io.Output;
    import com.hazelcast.config.Config;
    import com.hazelcast.config.SerializationConfig;
    import com.hazelcast.config.SerializerConfig;
    import com.hazelcast.core.Hazelcast;
    import com.hazelcast.core.HazelcastInstance;
    import com.hazelcast.core.IMap;
    import com.hazelcast.map.EntryBackupProcessor;
    import com.hazelcast.nio.ObjectDataInput;
    import com.hazelcast.nio.ObjectDataOutput;
    import com.hazelcast.nio.serialization.StreamSerializer;
    import org.objenesis.strategy.StdInstantiatorStrategy;

    import java.io.IOException;
    import java.io.InputStream;
    import java.io.OutputStream;
    import java.io.Serializable;
    import java.util.Map;

    /**
     * Created by fschuh on 11/19/2015.
     */
    public class TestKryoSerializer {
        static HazelcastInstance hazelcastInstance;

        static class TestPojo implements Serializable {
            public String name;
            public int value;
        }

        public interface EntryProcessorFunction<K, V> extends Serializable {
            Object process(Map.Entry<K, V> entry);
        }

        static class TestEntryProcessor<K, V> implements com.hazelcast.map.EntryProcessor<K, V>, EntryBackupProcessor<K, V>, Serializable {
            private final EntryProcessorFunction<K, V> function;
            private volatile boolean isEntryNull;

            public TestEntryProcessor(EntryProcessorFunction<K, V> function) {
                this.function = function;
            }

            @Override
            public Object process(Map.Entry<K, V> entry) {
                System.out.println("Processing Primary");

                if(entry.getValue() == null)
                    isEntryNull = true;
                else
                    isEntryNull = false;

                return function.process(entry);
            }

            @Override
            public void processBackup(Map.Entry<K, V> entry) {
                if(!isEntryNull && entry.getValue() == null) {
                    System.out.println("Processing Backup received null... Hazelcast still synchronizing, no need to process backup");
                    return;
                }

                System.out.println("Processing Backup");
                function.process(entry);
            }

            @Override
            public EntryBackupProcessor<K, V> getBackupProcessor() {
                return this;
            }
        }

        static class TestFunction implements EntryProcessorFunction<String, TestPojo> {
            @Override
            public Object process(Map.Entry<String, TestPojo> entry) {
                // update entry
                TestPojo v = entry.getValue();
                int oldValue = v.value;
                v.value++;

                // call setValue()
                entry.setValue(v);

                System.out.println("Pojo value: " + v.value);

                return entry.getValue().value;
            }
        }

        public static class MyKryoSerializer<T> implements StreamSerializer<T> {
            Kryo kryo;
            public MyKryoSerializer() {
                kryo = new Kryo(); // NOT thread safe!

                // enable instantiation without default constructor declaration
                kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(
                        new StdInstantiatorStrategy()));
            }

            @Override
            public int getTypeId() {
                return 1;
            }

            @Override
            public void write(ObjectDataOutput objectDataOutput, T object) throws IOException {
                Output output = new Output((OutputStream) objectDataOutput);
                kryo.writeClassAndObject(output, object);
                output.flush();
            }

            @Override
            @SuppressWarnings("unchecked")
            public T read(ObjectDataInput objectDataInput) throws IOException {
                InputStream in = (InputStream) objectDataInput;
                Input input = new Input(in);

                return (T)kryo.readClassAndObject(input);
            }

            @Override
            public void destroy() {
            }
        }

        public static void setUp() throws Exception {
            System.out.println("Node starting...");

            Config config = new Config();

            SerializationConfig serializationConfig = new SerializationConfig()
                    .addSerializerConfig(new SerializerConfig()
                            .setClass(MyKryoSerializer.class)
                            .setTypeClass(TestEntryProcessor.class)
                    );

            config.setSerializationConfig(serializationConfig);

            hazelcastInstance = Hazelcast.newHazelcastInstance(config);
        }

        public static void main(String[] s) throws Exception {
            setUp();

            TestPojo pojo = new TestPojo();
            pojo.name = "name";
            pojo.value = 1;

            IMap<String, TestPojo> map = hazelcastInstance.getMap("test_map");

            // put
            map.put("key", pojo);

            TestEntryProcessor<String, TestPojo> entryProcessor = new TestEntryProcessor<>(new TestFunction());

            // run in a loop
            for(;;) {
                Object result = map.executeOnKey("key", entryProcessor);
                Thread.sleep(500);
            }

        }

    }

**Comment by fschuh** [comment]
Just tested with 3.6-RC2-SNAPSHOT, problem still exists.

**Comment by sancar** [comment]
Hi,
Here is the situation. When Kryo reading an object from InputStream that is passed to it, sometimes it decides to read the byte-array ahead and messing the position for others that will read the rest.

How is it passing in 3.5 and not in 3.6-RC1?
It seems, the position when we pass the InputStream to Kryo has changed. And it turns out, when kryo hits that new position it makes bulk read, but in 3.5, it does not.

I tried setting limit in Input class etc but no luck. You will probably need to ask Kryo team about it.

**Comment by sancar** [comment]
Closing it for now. If you have further questions, you can reopen it.

**Comment by fschuh** [comment]
I can confirm to you that I've been using Kryo since Hazelcast 3.2, for a long time now, and never had such issues. They only showed up in 3.6.

But the big question is: why does it only happen with EntryProcessors? Why is it working fine with regular get()/put()? Do you do anything special with InpuStreams when it comes to EntryProcessors?

Something must have been changed from 3.5 to 3.6 - everything was running fine before.

**Comment by sancar** [comment]
When we leave the kyro serialization at the end of stream, you don't see the issue. Or byte buffer used only by Kyro and hazelcast is not serializing and deserializing the buffer, you don't see the issue. Keep in my that, there could be several other places and it is working because Kyro does not do a batch read on these cases. But when your data size changes, you may come accross the issue.

**Comment by mdogan** [comment]
Problem with using Kryo is, it assumes it's the only one reading from input or writing to output. Because of that you need to `flush()` Kryo output whenever you serialize with Kryo to make it visible by Hazelcast.

Bu on reading side it's more complicated. Kryo reads as many as possible bytes from output stream to its internal buffers and keeps de-serializing from its buffer. This is for providing better performance but when Kryo is used with another serialization library, it consumes from the stream more than expected. And the one reading after Kryo reads wrong value or gets EOF.

See following test:

```java
@org.junit.Test
public void testKryo() throws IOException {
    SerializerConfig serializerConfig = new SerializerConfig();
    serializerConfig.setTypeClass(DummyValue.class).setImplementation(new DummyValueSerializer());
    SerializationConfig config = new SerializationConfig().addSerializerConfig(serializerConfig);

    SerializationService serializationService = new DefaultSerializationServiceBuilder()
            .setConfig(config)
            .build();

    DummyValue value = new DummyValue("test");
    int k = 123;

    BufferObjectDataOutput out = serializationService.createObjectDataOutput(1024);
    out.writeObject(value);
    out.writeInt(k);

    BufferObjectDataInput in = serializationService.createObjectDataInput(out.toByteArray());
    Assert.assertEquals(value, in.readObject());
    Assert.assertEquals(k, in.readInt());
}

static class DummyValue {
    String value;

    public DummyValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DummyValue value1 = (DummyValue) o;

        return !(value != null ? !value.equals(value1.value) : value1.value != null);
    }

    @Override
    public int hashCode() {
        return value != null ? value.hashCode() : 0;
    }
}

private static class DummyValueSerializer implements StreamSerializer<DummyValue> {
    static final ThreadLocal<Kryo> KRYO_THREAD_LOCAL = new ThreadLocal<Kryo>(){
        @Override
        protected Kryo initialValue() {
            Kryo kryo = new Kryo();
            // enable instantiation without default constructor declaration
            kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(
                    new StdInstantiatorStrategy()));
            return kryo;
        }
    };

    @Override
    public int getTypeId() {
        return 111;
    }

    @Override
    public void write(ObjectDataOutput out, DummyValue object) throws IOException {
        final Kryo kryo = KRYO_THREAD_LOCAL.get();
        Output output = new Output((OutputStream) out);
        kryo.writeObject(output, object);
        output.flush();
    }

    @Override
    public DummyValue read(ObjectDataInput in) throws IOException {
        final Kryo kryo = KRYO_THREAD_LOCAL.get();
        Input input = new Input((InputStream) in);
        return kryo.readObject(input, DummyValue.class);
    }

    @Override
    public void destroy() {
    }
}
```

This test fails with `java.io.EOFException: Cannot read 4 bytes!`, Hazelcast can't read integer from stream because Kryo comsumes all input into its buffers.

However, if you change the serialization order of `int` and `DummyValue` then it works because Kryo will be the last comsumer.

Like;
```java
...
BufferObjectDataOutput out = serializationService.createObjectDataOutput(1024);
out.writeInt(k);
out.writeObject(value);

BufferObjectDataInput in = serializationService.createObjectDataInput(out.toByteArray());
Assert.assertEquals(k, in.readInt());
Assert.assertEquals(value, in.readObject());
```

**Comment by mdogan** [comment]
A hacky workaround may be to set buffer size of Kryo to `1`.

```java
...
Input input = new Input((InputStream) in, 1);
...
```

**Comment by fschuh** [comment]
I see - so the issue happens because other serializers are being used other than Kryo.
But why did it never happen before the 3.6 release? 
Was there some major changes in Hazelcast serialization on 3.6?

**Comment by fschuh** [comment]
I'm pretty sure there were other serializers working together with Kryo in 3.5.

**Comment by mdogan** [comment]
No. You got me wrong. I'm trying to explain issue on Kryo side not Hazelcast. 

Let's remove Hazelcast from the picture and just use raw output and input. Even when you use plain `ByteArrayOutputStream` and `ByteArrayInputStream`, this test fails. Because Kryo consumes all input from stream.

```java
@org.junit.Test
public void testKryo() throws IOException {
    Kryo kryo = new Kryo();
    kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

    DummyValue value = new DummyValue("test");

    ByteArrayOutputStream out = new ByteArrayOutputStream();
    Output output = new Output(out);
    kryo.writeObject(output, value);
    output.flush();
    out.write(1);

    ByteArrayInputStream in = new ByteArrayInputStream(out.toByteArray());
    Input input = new Input(in);

    Assert.assertEquals(value, kryo.readObject(input, DummyValue.class));
    Assert.assertEquals(1, in.read());  // <------- Here in.read() will return -1, EOF.
}
```

**Comment by fschuh** [comment]
Thanks for that, I understand now. I have already opened an issue about it on the Kryo page.

For anyone who's trying to use Kryo with Hazelcast, I did some tests here and had success with Chunked encoding. And it performs just as well as using regular encoding.
Here's a Kryo serializer that's working well even with Hazelcast 3.6:

    public static class MyKryoSerializer<T> implements StreamSerializer<T> {
		static final ThreadLocal<Kryo> KRYO_THREAD_LOCAL = new ThreadLocal<Kryo>(){
			@Override
			protected Kryo initialValue() {
				Kryo kryo = new Kryo();
				// enable instantiation without default constructor declaration
				kryo.setInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(
						new StdInstantiatorStrategy()));
				return kryo;
			}
		};
	

        @Override
        public int getTypeId() {
            return 1;
        }

        @Override
        public void write(ObjectDataOutput objectDataOutput, T object) throws IOException {
			final Kryo kryo = KRYO_THREAD_LOCAL.get();
            OutputChunked output = new OutputChunked((OutputStream) objectDataOutput, 4096);
            kryo.writeClassAndObject(output, object);
            output.endChunks();
            output.flush();
        }

        @Override
        @SuppressWarnings("unchecked")
        public T read(ObjectDataInput objectDataInput) throws IOException {
			final Kryo kryo = KRYO_THREAD_LOCAL.get();
            InputStream in = (InputStream) objectDataInput;
            InputChunked input = new InputChunked(in, 4096);

            return (T)kryo.readClassAndObject(input);
        }


        @Override
        public void destroy() {
        }
    }

**Comment by qweek** [comment]
You can use another approach.
Mark your position before read and restore correct position after:

    // mark current position
    input.mark(MAX_READ_LIMIT);
    
    // read data
    getKryo().readObject(input, type);
    
    // current position equals to used bytes
    final int position = input.position();
    // reset stream to mark
    input.reset();
    // skip to valid position
    if (input.skip(position) != position) {
        throw new KryoException("Failed to skip input stream");
    }
You can create proxy classes around `Input` and `Output` for this fix.

**Comment by markathomas** [comment]
@qweek what is MAX_READ_LIMIT?  the chunk size to read?

**Comment by thekalinga** [comment]
I'm currently using 3.7-EA and I still have the same issue. This is happening if I try to store and retrieve a collection List<SomeObject>, where SomeObject is registered with hazelcast

```xml
<hazelcast>
<!-- a lot more config-->
    <serialization>
        <serializers>
            <serializer type-class="com.acme.SomeObject"
                        class-name="com.acme.SomeObject"/>
        </serializers>
    </serialization>
</hazelcast>
```

**Comment by jerrinot** [comment]
@thekalinga: are you using `OutputChunked` and `InputChunked` in your serializer implementation as recommend at https://github.com/EsotericSoftware/kryo/issues/372#issuecomment-165362759 ?

**Comment by thekalinga** [comment]
Sorry, I am an idiot.

I just realised I was using input & output stream as described in [mastering hazelcast guide](http://hazelcast.org/mastering-hazelcast/) instead of `InputChunked` & `OutputChunked`.

After changing to chunked, I no longer see the issue.

Thank you

**Comment by jerrinot** [comment]
@thekalinga mistakes happen, I'm glad it's working for you now! 

Do you think you could share your implementation? I think a general Hazelcast Kryo serializer could be a nice open source project! So other people could just re-use it. If you cannot / do not want to release it for any reason than that's fine too. Happy Hazelcasting!

**Comment by thekalinga** [comment]
I have created a generic version of the serializer

```java

public abstract class GenericHazelcastKryoSerializer<T> implements StreamSerializer<T> {

  private final int typeId;

  public GenericHazelcastKryoSerializer(int typeId) {
    this.typeId = typeId;
  }

  @Override
  public int getTypeId() {
    return typeId;
  }

  @Override
  public void write(ObjectDataOutput objectDataOutput, T product)
      throws IOException {
    Kryo kryo = getSharedThreadLocalKyro();
    OutputChunked output = new OutputChunked((OutputStream) objectDataOutput, 4096);
    kryo.writeClassAndObject(output, product);
    output.endChunks();
    output.flush();
  }

  protected abstract Kryo getSharedThreadLocalKyro();

  @Override
  public T read(ObjectDataInput objectDataInput)
      throws IOException {
    InputStream in = (InputStream) objectDataInput;
    InputChunked input = new InputChunked(in, 4096);
    Kryo kryo = getSharedThreadLocalKyro();
    return (T) kryo.readClassAndObject(input);
  }

  @Override
  public void destroy() {
  }

}
```

```java
public class SomeObjectKryoSerializer extends GenericHazelcastKryoSerializer<SomeObject> {

  private static final ThreadLocal<Kryo> kryoThreadLocal
      = new ThreadLocal<Kryo>() {
    @Override
    protected Kryo initialValue() {
      Kryo kryo = new Kryo();
      kryo.register(SomeObject.class);
      return kryo;
    }
  };

  public SomeObjectKryoSerializer() {
    super(SerializationId.SOME_OBJECT);
  }

  @Override
  protected Kryo getSharedThreadLocalKyro() {
    return kryoThreadLocal.get();
  }

}
```

```java
public class SerializationId {
  public static final int SOME_OBJECT = 1;

  private SerializationId() {
    // todo: throw exception as this should never be instantiated, even using reflection
  }
}
```

and the xml will look like this

```xml
<hazelcast>
<!-- a lot more config-->
    <serialization>
        <serializers>
            <serializer type-class="com.acme.SomeObject"
                        class-name="com.acme.SomeObjectKryoSerializer"/>
        </serializers>
    </serialization>
</hazelcast>
```

**Comment by jerrinot** [comment]
I started a community project aiming to provide easy-to-use Kryo integration into Hazelcast: https://github.com/jerrinot/subzero
