### ISSUE TITLE
MapLoaderMultiNodeTest.testLoadAgain_whenLoadedAllCalledMultipleTimes

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6783]
```
java.lang.AssertionError: expected:<20000> but was:<10000>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.mapstore.MapLoaderMultiNodeTest.testLoadAgain_whenLoadedAllCalledMultipleTimes(MapLoaderMultiNodeTest.java:127)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/303/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadAgain_whenLoadedAllCalledMultipleTimes/

**Comment by jerrinot** [comment]
possibly related to #5035

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/45/testReport/junit/com.hazelcast.map.mapstore/MapLoaderMultiNodeTest/testLoadAgain_whenLoadedAllCalledMultipleTimes/

**Comment by mesutcelik** [comment]
@jerrinot ,

Do you think this one can be moved to 3.7 as well? I see #5035 is already moved.

**Comment by enesakar** [comment]
thanks @mesutcelik for mentioning. moved to 3.7

**Comment by tombujok** [comment]
I'm almost sure that this is related to #5453

**Comment by tombujok** [comment]
I've run this test for more than 24h on Jenkins on various JDKs (Zulu, IBM, Open-JDK, various versions) and it hasn't failed. 

What is more it has not failed since December 2015. I has been probably fixed with a series of fixes committed by me between December 2015 and January 2016
