### ISSUE TITLE
Dynamic wan replication configuration

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#6794]
Hi - 

I would like to be able to dynamically (at runtime) alter/define the WAN replication configuration.

Is this possible? If so any pointers to samples or what classes in the API I should be looking into?

**Comment by mesutcelik** [comment]
Thanks @bitsofinfo for the consideration. It is actually a duplicate of https://github.com/hazelcast/hazelcast/issues/592 so i am closing this ticket. 

Unfortunately we don't have dynamic configuration at the moment. I hope we will get it in future releases.

**Comment by bitsofinfo** [comment]
what the advantage is to WAN replication out of the box, vs just listing WAN connected Hazelcast IPs individually in the normal peer cluster setup?
