### ISSUE TITLE
Map entry event listeners are not invoked on clients of WAN replication target cluster

### ISSUE THREAD

**Issue by otarisvanidze** [hazelcast/hazelcast#6802]
[#5058](https://github.com/hazelcast/hazelcast/pull/5058) fixes similar issue but on target cluster itself. Clients of such cluster receive ```REMOVED``` events only. It's fairly easy to reproduce by adding client to ```clusterB``` in ```WanReplicationTest.willFireNewOnMergeEventAtReceivingCluster```.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/6937
