### ISSUE TITLE
3.6 AbstractDiscoveryStrategy, get access to invoking Hazelcast instance?

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#6811]
I am writing a DiscoveryStrategy that extends from AbstractDiscoveryStrategy, and I need to get access to the Hazelcast instance that is invoking this... i.e. i'd like to include the hazelcast group name that this node is configured to be a member of so I can include it in where I am registering the node with 

How can I get access to this?

In reference I am working on this discovery SPI impl and wanted this functionality there: https://github.com/bitsofinfo/hazelcast-consul-discovery-spi

**Comment by bitsofinfo** [comment]
Hazelcast.getAllHazelcastInstances() won't work for me, cause I have no idea what instance is the instance invoking the constructor of my AbstractDiscoveryStrategy instance

**Comment by pveentjer** [comment]
Good question.

I'm looking at the code and I remember one should be able to get access to an object using some casing, but I don't see how it can be done. @noctarius do you remember?

**Comment by noctarius** [comment]
It was changed since the DiscoveryNode is passed to the strategy now. There is no way (at the moment) to do that but we might want to make some properties like groupname available as an attribute of the DiscoveryNode?

Another option I removed again was the possibility to use HazelcastInstanceAware and inject it before DiscoveryStrategy::start is called.

**Comment by bitsofinfo** [comment]
I think the DiscoveryStrategy should just have full access to the instance invoking it.

**Comment by pveentjer** [comment]
I don't know if that is a good thing. The idea is to keep the discovery API disconnected from the Hazelcast API as much as possible to prevent dependency cycles.

**Comment by bitsofinfo** [comment]
People are going to create DiscoveryStrategy impls in with behaviors you guys can't full predict at this point with regards to what information they need access to. I get the concern about dependency cycles but at least give it some sort of complete read-only view into the entire hazelcast config.

**Comment by mesutcelik** [comment]
Hi @bitsofinfo ,
We are already passing [local DiscoveryNode](https://github.com/hazelcast/hazelcast/blob/v3.7-EA/hazelcast/src/main/java/com/hazelcast/spi/discovery/DiscoveryStrategyFactory.java#L68) as of 3.7-EA to the Discovery Plugins but as i see that is not sufficient for your case. You wanna see the whole hazelcast config object i suppose.

Unfortunately, we are in a feature freeze now so i have to move the milestone to 3.8. However, we can continue to discuss the solution in this issue and you are always welcome to contribute the feature. It will be much appreciated.

**Comment by dbrimley** [comment]
Closing this issue as I don't feel that access to a HazelcastInstance is required in terms of DiscoverySPI.  If required please feel free to re-open a new issue with more detailed requirements.
