### ISSUE TITLE
3.6-EA DiscoveryStrategy, only one call to discoverNodes() ever...?

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#6813]
Trying to implement a DiscoveryStrategy that will let us dynamically add previously **unknown** nodes to the cluster over time... however it appears that discoverNodes() is only called 1x on startup and never called again... so those nodes that go offline are properly (detected by hz) removed from the cluster, however, if we bring new nodes online, the existing running nodes seem to discover them ok (but not via discoverNodes())..... but what no nodes are up and all nodes start up simultaneously and the DiscoveryStrategy impl only sees **itself** as a member at that point in time, it can never join the cluster....?

**Comment by noctarius** [comment]
All of the nodes would have to have the discovery at the exact same time, your DiscoveryStrategy is also free to wait for a couple of seconds to see if nodes come up. The discoverNodes is called at startups or at regular interval when Hazelcast tries to detect if there might be a second cluster that needs to be merged (for example after split-brain).

**Comment by bitsofinfo** [comment]
thanks
