### ISSUE TITLE
Outgoing ports on clients should be configurable

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6845]
Right now clients always use ephemeral ports for outgoing connections. 

There should be a way to force using specific port numbers - we already have this ability in member configuration.

**Comment by sancar** [comment]
Duplicate Enhancement request closing this one. And setting old one to 3.7 
https://github.com/hazelcast/hazelcast/issues/6350

**Comment by mukul4u2005** [comment]
Hi All

I am excited about this feature, just I want to confirm one more thing like I was thinking to use the endpoint security on server side at map level. Can we able to define the ip with port number in security configuration on server side ?

<map-permission name="test" principal="dev">
  <endpoints>
           <endpoint>127.0.0.1:5704</endpoint>
          </endpoints>
  <actions>
		        <action>put</action>
		        <action>create</action>
		        <action>read</action>
		        <action>remove</action>
	      	</actions>
    	</map-permission>

Please suggest about that.

Thanks
Mukul
