### ISSUE TITLE
ClientQueueTest.testListener fails spuriously

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast#6852]
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.client.queue.ClientQueueTest.testListener(ClientQueueTest.java:515)
```

**Comment by sancar** [comment]
@mtopolnik Can you share a jenkins build log ? Is failure from legacy client or new client ?

**Comment by mtopolnik** [comment]
It was the new client. Ill have to dig through past builds and try to find it, it's gone from my PR page.

**Comment by mtopolnik** [comment]
Here it is:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/17047/

**Comment by sancar** [comment]
@mtopolnik Thanks

**Comment by hasancelik** [comment]
@mtopolnik : I talked with @sancar and @enesakar ,before ignore this test we will wait until another failure. In this period, I will observe all builds from Jenkins (default builds and pr builder).

**Comment by enesakar** [comment]
closing test failures whose test has not failed in last week
