### ISSUE TITLE
OBJECT in-memory format will still serialize map entries after EntryProcessor calls when configuring Hazelcast from an XML file

### ISSUE THREAD

**Issue by fschuh** [hazelcast/hazelcast#6863]
If you use EntryProcessor operations on a map with OBJECT in-memory format, the objects will still be serialized after every call if you happen to be configuring Hazelcast from an XML file.

If you configure Hazelcast from code, this issue doesn't happen and OBJECT works as expected (no serialization/deserialization is performed).
The issue happens in single node clusters as well.

At first I thought it could be something wrong with my XML file, but I've stripped it down to the simplest configuration possible and still get the issue.

Here is some reproduction code:

    package hazelcast;

    import com.hazelcast.config.*;
    import com.hazelcast.core.*;
    import com.hazelcast.map.EntryBackupProcessor;
    import com.hazelcast.nio.ObjectDataInput;
    import com.hazelcast.nio.ObjectDataOutput;
    import com.hazelcast.nio.serialization.DataSerializable;

    import java.io.IOException;
    import java.io.Serializable;
    import java.util.Map;

    /**
     * Created by fschuh on 11/25/2015.
     */
    public class TestEntryProcessorOBJECTSerializationSingleNode {

        static HazelcastInstance hazelcastInstance;

        static class TestPojo implements DataSerializable {
            public String name;
            public int value;

            @Override
            public void writeData(ObjectDataOutput out) throws IOException {
                System.out.println("Serializing TestPojo: " + this);
                out.writeUTF(name);
                out.writeInt(value);
            }

            @Override
            public void readData(ObjectDataInput in) throws IOException {
                name = in.readUTF();
                value = in.readInt();

                System.out.println("Deserializing TestPojo: " + this);
            }

            public String toString() {
                return "{name: " + name + ", value: " + value + "}";
            }
        }

        static class TestEntryProcessor<K, V> implements com.hazelcast.map.EntryProcessor<K, V>, EntryBackupProcessor<K, V>, Serializable {
            private final EntryProcessorFunction<K, V> function;
            private volatile boolean isEntryNull;

            public TestEntryProcessor(EntryProcessorFunction<K, V> function, String mapName) {
                this.function = function;
            }

            @Override
            public Object process(Map.Entry<K, V> entry) {
                if(entry.getValue() == null)
                    isEntryNull = true;
                else
                    isEntryNull = false;

                Object result = null;

                result = function.process(entry);

                return result;
            }

            @Override
            public void processBackup(Map.Entry<K, V> entry) {
                if(!isEntryNull && entry.getValue() == null) {
                    System.out.println("Processing Backup received null... Hazelcast still synchronizing, no need to process backup");
                    return;
                }

                function.process(entry);
            }

            @Override
            public EntryBackupProcessor<K, V> getBackupProcessor() {
                return this;
            }
        }

        public interface EntryProcessorFunction<K, V> extends Serializable {
            Object process(Map.Entry<K, V> entry);
        }

        static class TestFunction implements EntryProcessorFunction<String, TestPojo> {
            @Override
            public Object process(Map.Entry<String, TestPojo> entry) {
                // update entry
                TestPojo v = entry.getValue();
                int oldValue = v.value;
                v.value++;

                // call setValue()
                entry.setValue(v);

                return entry.getValue().value;
            }
        }

        public static void setUp() {
            // with this hard coded configuration OBJECT works as expected
            Config config = new Config();
            config.addMapConfig(new MapConfig()
                    .setName("test_map")
                    .setBackupCount(1)
                    .setInMemoryFormat(InMemoryFormat.OBJECT)
            );

            // with this XML configuration OBJECT will start serializing TestPojos after every EntryProcessor call
            // just comment out this line to see the expected OBJECT behavior
            config = new ClasspathXmlConfig("object_serialization_test.xml");

            hazelcastInstance = Hazelcast.newHazelcastInstance(config);

        }

        public static void main(String[] s) {
            setUp();

            TestPojo pojo = new TestPojo();
            pojo.name = "name";
            pojo.value = 1;

            IMap<String, TestPojo> map = hazelcastInstance.getMap("test_map");

            // put
            map.put("key", pojo);

            // run in a loop
            for(int i = 0; i < 50; i++) {
                Object result = map.executeOnKey("key", new TestEntryProcessor<>(new TestFunction(), "test_map"));
            }

            System.out.println("Finished");
            hazelcastInstance.shutdown();
        }
    }

This sample code, on the setUp() method, shows both ways of setting up Hazelcast (hardcoded and XML). If you comment out the XML line, OBJECT will work as expected (no serialization will happen).
When serialization happens, you'll see a lot of output from the DataSerializable.

Here is the XML configuration:

    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.5.xsd"
               xmlns="http://www.hazelcast.com/schema/config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <properties>
            <property name="hazelcast.mancenter.enabled">false</property>
            <property name="hazelcast.memcache.enabled">false</property>
            <property name="hazelcast.rest.enabled">false</property>
            <property name="hazelcast.wait.seconds.before.join">0</property>
            <property name="hazelcast.logging.type">log4j2</property>
            <property name="hazelcast.jmx">true</property>
        </properties>

        <group>
            <name>dev</name>
            <password>dev-pass</password>
        </group>
        <management-center enabled="false">http://localhost:8080/mancenter</management-center>
        <network>
            <port auto-increment="true" port-count="10000">5701</port>
            <outbound-ports>
                
                <ports>0</ports>
            </outbound-ports>
            <join>
                <multicast enabled="true">
                    <multicast-group>224.2.2.3</multicast-group>
                    <multicast-port>54327</multicast-port>
                </multicast>
                <tcp-ip enabled="false">
                    <interface>192.168.1.28</interface>
                </tcp-ip>
                <aws enabled="false">
                    <access-key>my-access-key</access-key>
                    <secret-key>my-secret-key</secret-key>
                    
                    <region>us-west-1</region>
                    
                    <host-header>ec2.amazonaws.com</host-header>
                    
                    <security-group-name>hazelcast-sg</security-group-name>
                    <tag-key>type</tag-key>
                    <tag-value>hz-nodes</tag-value>
                </aws>
            </join>
            <interfaces enabled="false">
                <interface>10.10.1.*</interface>
            </interfaces>
            <ssl enabled="false"/>
            <socket-interceptor enabled="false"/>
            <symmetric-encryption enabled="false">
                
                <algorithm>PBEWithMD5AndDES</algorithm>
                
                <salt>thesalt</salt>
                
                <password>thepass</password>
                
                <iteration-count>19</iteration-count>
            </symmetric-encryption>
        </network>
        <partition-group enabled="false"/>
        <executor-service name="default">
            <pool-size>16</pool-size>
            
            <queue-capacity>0</queue-capacity>
        </executor-service>

        <map name="test_map">
            
            <in-memory-format>OBJECT</in-memory-format>

            
            <backup-count>1</backup-count>
        </map>

    </hazelcast>

I feel this has severe negative impact on OBJECT in-memory format performance, as all serializations during an EntryProcessor call happen on the partition thread, which slows down unrelated gets/puts on different maps.

Tested on Hazelcast version 3.5.3.

**Comment by gurbuzali** [comment]
Hi,
The issue does not occur because of xml configuration, it is because you are enabling JMX via xml.
When you enable JMX, internally a listener gets registered which serialize/deserialize the object.

**Comment by fschuh** [comment]
I see.
But why is that the case?
How can I enable JMX and not have the serialization taking place?

**Comment by gurbuzali** [comment]
I've checked the jmx code and it should not cause any deserialization.
This looks like a bug, I've created a different issue for that
https://github.com/hazelcast/hazelcast/issues/6866
Thank you for reporting

**Comment by fschuh** [comment]
You're welcome. Glad to know the root of the issue was found.
Guess I'll be turning JMX off for a while until this issue is sorted out.
