### ISSUE TITLE
Client heartbeat timeout check issue

### ISSUE THREAD

**Issue by nick7ikin** [hazelcast/hazelcast#6873]
I've tried to setup heartbeat with 1 sec interval and timeout 300 millis, because I need to be notified about network outage asap. It should be quite lightweight settings for local network.
```
 clientConfig.setProperty("hazelcast.client.heartbeat.interval", "1000");     
 clientConfig.setProperty("hazelcast.client.heartbeat.timeout", "300");      
```
As a result I've got client always reconnecting to cluster. As I see the reason could be in class ```ClientConnectionManagerImpl```. Heartbeat sending and timeout checking is performed in the same method ```ClientConnectionManagerImpl.HeartBeat.run()``` that is scheduled to be run with heartbeat.timeout interval:
```
            ClientConnectionManagerImpl.HeartBeat heartBeat = new ClientConnectionManagerImpl.HeartBeat();
            this.executionService.scheduleWithFixedDelay(heartBeat, (long)this.heartBeatInterval, (long)this.heartBeatInterval, TimeUnit.MILLISECONDS);
```
And during heartbeat timeout check its value is compared to ```(now - connection.lastReadTime())```. So if we put in on a time diagram it will look like: 
```
  t1 send heartbeat                 t3 heartbeat timeout                         t4 heartbeat timeout check
--|-----------------|---------------|--------------------------------------------|-
                   t2 heartbeat response 
```
So currently in order to detect that timeout is exceeded it compares heartbeat timeout value (which is ```t3 - t1```) with ```now - lastRead``` (which is ```t4 - t2```). It's obvious that in some cases ```t4 - t2``` can be greater than real heartbeat response time (which is ```t2 - t1```). I believe for solving this issue heartbeat sending and heartbeat timeout check should be scheduled separately.

**Comment by sancar** [comment]
```
clientConfig.setProperty("hazelcast.client.heartbeat.interval", "1000");     
clientConfig.setProperty("hazelcast.client.heartbeat.timeout", "300");
```


Timeout value should be larger than interval. 
Client  should send new PingRequest for each "hazelcast.client.heartbeat.interval" , if there is not already packet going on. 

And if "hazelcast.client.heartbeat.timeout" is reached connection is marked as not heartbeating. When this happens, no request is permitted to send over it(accept Ping) .

With your settings, there is a time interval that you can not detect. Does that make sense ?

**Comment by nick7ikin** [comment]
I've understood your way of implementation.
As for me it would be more convenient to setup in the way I've said, for example "send heartbeat with 1000 millis interval and each time caller must reply in 300 millis".
Cause with current implementation it's harder to specify precise timeouts. For example, you told that 
> Timeout value should be larger than interval

but it's not enough condition. If i set interval = 1000 millis and timeout = 1100 millis it still disconnects
1. let it sends 1st heartbeat at 0 millis
2. got response at 200 millis
3. at 1000 millis it performs the following logic
* did the timeout is reached? (```now - connection.lastReadTime() > heartBeatTimeout```): 1000 millis - 200 millis > 1100 millis - no, timeout isn't reached
* should we send next heartbeat? actually the same calculation - no, we shouldn't
4. at 2000 millis we perform the same calculations, but it occurs that timeout already reached.

So it seems that timeout should be at least large than 2*interval.

**Comment by sancar** [comment]
> I've understood your way of implementation.
> As for me it would be more convenient to setup in the way I've said, for example "send heartbeat with 1000 millis interval and each time the caller must reply in 300 millis".
> Cause with current implementation it's harder to specify precise timeouts. For example, you told that

>> Timeout value should be larger than interval
> but it's not enough condition. If i set interval = 1000 millis and timeout = 1100 millis it still disconnects

> let it sends 1st heartbeat at 0 millis
> got response at 200 millis
> at 1000 millis it performs the following logic:
> did the timeout is reached? (now - connection.lastReadTime() > heartBeatTimeout): 1000 millis - 200 millis > 1100 millis - no, timeout isn't reached
> should we send next heartbeat? actually the same calculation - no, we shouldn't.

Not same calculation. In second check right hand side is heartbeat interval. When timeout and interval values this close, it is not a meaningful check.

> at 2000 millis we perform the same calculations, but it occurs that timeout already reached.
> So it seems that timeout should be at least larger than 2*interval.

That is correct. Basically if you want a small timeout set timeout small. And if you want precise check, make the interval much more smaller.  Something like following:

Timeout 1000
Interval 200

And our defaults are 

Timeout 60 seconds
Interval 5 seconds

So this means client will check each 5 seconds if 60 second is reached. And each 5 seconds sends a packet to node to say it is alive. 

By the way, why do you want to detect connection problems with such a small latency? If you set a small value, when there are small delays client will take action. It may do more harm than good. 

I am closing the issue. If you still think think there is a bug and have a suggestion, you are welcome to reopen the issue.

Regards.

**Comment by nick7ikin** [comment]
Hi, @sancar. Thanks for your explanations.
I believe your example should be added to documentation.

> By the way, why do you want to detect connection problems with such a small latency? If you set a small value, when there are small delays client will take action. It may do more harm than good.

We run our application (that uses hazelcast) in local network so these settings are not very demanding. Also our application should be very responsive so if there are any network issues its better to block application for that period of time.
