### ISSUE TITLE
InMemoryFormat.OBJECT does not work with USED_HEAP_SIZE and USED_HEAP_PERCENTAGE

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#6875]
We can even fail-fast if one tries to configure a map with those values
please see comment https://github.com/hazelcast/hazelcast/issues/4885#issuecomment-159674825

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/a08b0a1a06d17f384498ce50730860e9b8753444
