### ISSUE TITLE
Spring configuration support for Discovery SPI

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#6913]
It appears our namespace for Spring configuration does not support Discovery SPI.

**Comment by markathomas** [comment]
+1 - IMO this should be in a 3.6 patch release.  Spring users should not have to wait on 3.7 for support for a feature that is already available.

**Comment by jerrinot** [comment]
@mesutcelik: WDYT?

**Comment by mesutcelik** [comment]
I am ok with that. @emrahkocaman was working on the fix so he will be backporting to maintenance as well..

**Comment by emrahkocaman** [comment]
I see no harm from backward compatibility point of view, backporting it should not be a problem. I'm setting milestone as 3.6.1.

**Comment by markathomas** [comment]
Thanks you @emrahkocaman. When can we expect 3.6.1 to be released?  I have a client waiting on this support.

**Comment by emrahkocaman** [comment]
Hi @markathomas , I can't give an exact date now but as 3.6 is recently released
3.6.1 should follow within a month or so.
