### ISSUE TITLE
QueueItemListenerOnReconnectTest TimeOut

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#6915]
```
04:13:10 Running com.hazelcast.client.listeners.QueueItemListenerOnReconnectTest
05:59:12 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/36/consoleFull

**Comment by cangencer** [comment]
I would suspect this might be same issue as #6833

**Comment by cangencer** [comment]
Closing this, timeouts have been added for the tests and can be re-opened if we get a more specific test failure
