### ISSUE TITLE
Delay re-partition process on HZ instance startup.

### ISSUE THREAD

**Issue by ssozonoff** [hazelcast/hazelcast#6922]
Hello,

Per this discussion thread
https://groups.google.com/forum/#!topic/hazelcast/1Dg7cfYUnH8

We are looking for a way to delay the re-partition process when a node joins a cluster. Our application is based on the Java Spring framework and we have a Database backed MapStore which is wired by Spring. The problem is that the Hazelcast instance gets initialised and starts re-partitioning before the Spring Context is fully initialiased and so the MapStore implementation is not ready.

Could we either have a parameter to delay the re-partition process on startup or a parameter to disable the automation of the re-partition and a method to kick it off ourselves which we could connect to a Spring Context Listener ?

Thanks,
Serge

**Comment by zeratul021** [comment]
+1 as we have the exact same problem but we are using Guice.

**Comment by oksyque** [comment]
+1 as we also have this issue (spring + hazelcast)

**Comment by rameshprml** [comment]
Hi,

Implement Thread.wait() in any one of below interface methods to delay the partition migration and notify the same thread, when the Spring process get completed:

1. MigrationListener
 - migrationStarted(): Implement Thread.wait() inside this method.
 - Example URL: http://docs.hazelcast.org/docs/3.5/manual/html/distributedevents.html#migration-listener

2. MigrationAwareService
 - beforeMigration(PartitionMigrationEvent e)
 - Example URL: http://docs.hazelcast.org/docs/3.5/manual/html/spipartitionmigration.html

Regards,
Ramesh P

**Comment by mdogan** [comment]
By 3.9, you can use the new promote lite member to data member feature. It allows a lite member to be upgraded to a data member in runtime. So, you can start new instance as a lite member then promote it to a data member when application is up & ready.

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/core/Cluster.java#L102

```java
   /**
     * Promotes local lite member to data member.
     * When this method returns both {@link #getLocalMember()} and {@link #getMembers()}
     * reflects the promotion.
     *
     * @throws IllegalStateException when member is not a lite member or mastership claim in progress
     *                              or local member cannot be identified as a member of the cluster
     *                              or cluster state doesn't allow migrations/repartitioning
     *
     * @since 3.9
     */
    void promoteLocalLiteMember();
```

**Comment by mdogan** [comment]
Again by 3.9, you can disable migrations in all cluster by switching cluster state to `NO_MIGRATION`.  In `NO_MIGRATION` state of the cluster, migrations (partition rebalancing) and backup replications are not disabled. When a new member joins, it will not be assigned any partitions until cluster state changes to `ACTIVE`.

You can change cluster state via API or Management Center.

```java
HazelcastInstance instance = ...;
instance.getCluster().changeClusterState(ClusterState.NO_MIGRATION);
```

See http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#managing-cluster-and-member-states
