### ISSUE TITLE
What if all nodes are not in a defined pool ?

### ISSUE THREAD

**Issue by jeunii** [hazelcast/hazelcast#6930]
Hi all,

I have a hazel cast instance defined in my setup.
<tcp-ip enabled="true">
                <member>SeverA</member>
                <member>SeverB</member>
                <member>SeverC</member>
                <member>SeverD</member>
                <member>SeverE</member>
                <member>SeverF</member>
                <member>SeverG</member>
                <member>SeverH</member>
                <member>SeverI</member>
                <member>SeverJ</member>
            </tcp-ip>

And this pool is defined onservers for SeverA to ServerH

BUT the pools defined on ServerI & ServerJ are : 

 <tcp-ip enabled="true">
                <member>SeverI</member>
                <member>SeverJ</member>
          </tcp-ip>

Do you guys think this will be a problem for ServerA to ServerH ? Since I & J do not see them ?

**Comment by noctarius** [comment]
Hey @jeunii 

We love every contribution from the community, unfortunately the issue tracker is not the place for general questions but bug reports. Please use stackoverflow (as you did, please find my answer) or the Google Groups.

As mentioned, I answered on stackoverflow, I'm going to close this issue.

Thanks,
Chris
