### ISSUE TITLE
buggy quorum definition in Spring config

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#6946]
The definition for Quorum service in hazelcast-config-3.5.xsd is:

<code>

    <xs:complexType name="quorum">
        <xs:all>
            <xs:element name="quorum-size" type="quorum-size" minOccurs="0" maxOccurs="1"/>
            <xs:element name="quorum-type" type="quorum-type" minOccurs="0" maxOccurs="1"/>
            <xs:element name="quorum-function-class-name" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="quorum-listeners" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="quorum-listener" type="quorum-listener" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</code>

thus, the elements quorum-size, quorum-type and quorum-function-class-name are optional. But the quorum definition in hazelcast-spring-3.5.xsd is:

<code>

    <xs:complexType name="quorum">
        <xs:all>
            <xs:element name="quorum-size" type="quorum-size" maxOccurs="1"/>
            <xs:element name="quorum-type" type="quorum-type" maxOccurs="1"/>
            <xs:element name="quorum-function-class-name" type="xs:string" maxOccurs="1"/>
            <xs:element name="quorum-listeners" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="quorum-listener" type="quorum-listener" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</code>

here the minOccurs attribute is ommited in quorum-size, quorum-type and quorum-function-class-name elements, making all of them mandatory (the default minOccurs value is 1). This just does not make sence, please fix.

And one more issue: quorum-size element defined as:

    <xs:simpleType name="quorum-size">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

but, if I specify the size as 1 I got an exception on app start: 

<code>

     PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'size' threw exception; nested exception is com.hazelcast.config.InvalidConfigurationException: Minimum quorum size cannot be less than 2

</code>

if you don't want it to be < 2 then specify this in the schema, please.

**Comment by dsukhoroslov** [comment]
This is in HZ 3.5.4 and HZ 3.6-EA2.

**Comment by mustafaiman** [comment]
thank you for pointing this out. we will fix it.

**Comment by dsukhoroslov** [comment]
please port the fix to HZ-3.6 too
