### ISSUE TITLE
Indexes not getting used when calling predicates from transactional maps

### ISSUE THREAD

**Issue by TinoSM** [hazelcast/hazelcast#6956]
Hi,

I'm testing Hazelcast and I found a problem with predicates on transactional maps (while in a transaction).

````Java
 TransactionalMap employees1 = context.getMap("testCache");
 employees1.values(new BetweenPredicate("msj1Mandatory.value", 4, 5)).size();
````
I perform this query 100 times inside a transaction

Timings are similar when using Indexes or when not indexing:

		<indexes>
			<index ordered="true">msj1Mandatory.value</index>
		</indexes>

Plus If I create a custom Predicate I can see that the apply() method is being called. When using a view of the same cache with IMap interface it gets the values directly from the filter() method.

Is this a bug, or expected behaviour?

Thanks,

**Comment by gurbuzali** [comment]
here is a code snippet which shows that it uses indexes and not calls `apply`
code works for 3.5 and higher versions, can you try it with the version you are using?
```
public static void main(String[] args) throws Exception {
        Config config = new Config();
        config.setProperty(GroupProperty.PARTITION_COUNT, "1");
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
        IMap<Object, Object> map = instance.getMap("map");
        map.addIndex("value", true);

        map.put("key", new MyObject(5));


        BetweenPredicate predicate = new BetweenPredicate("value", 4, 6) {
            @Override
            public Set<QueryableEntry> filter(QueryContext queryContext) {
                System.err.println("filter");
                return super.filter(queryContext);
            }

            @Override
            public boolean apply(Map.Entry mapEntry) {
                System.err.println("apply");
                return super.apply(mapEntry);
            }
        };
        System.err.println("Without Transaction size: " + map.values(predicate).size());



        TransactionContext context = instance.newTransactionContext();
        context.beginTransaction();
        try {
            TransactionalMap<Object, Object> transactionalMap = context.getMap("map");
            System.err.println("With Transaction size: " + map.values(predicate).size());
            context.commitTransaction();
        } catch (Exception e) {
            context.rollbackTransaction();
            e.printStackTrace();
        }


    }
```

**Comment by TinoSM** [comment]
Thanks!

After reviewing the code, I found that in my transactions I'm adding new objects to the cache inside the same transaction, so those items which are not commited do not exist in the index, and they are probably processed using apply.

PS: In your snippet,

System.err.println("With Transaction size: " + map.values(predicate).size());

should be

System.err.println("With Transaction size: " + transactionalMap.values(predicate).size());
