### ISSUE TITLE
In-memory data is ignored during Merge (policy ADD_NEW_ENTRY) and loaded by MapLoader

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#6968]
Here is the scenario for the issue:

1- A cluster with 7 members (6 lite, 1 regular) sets up. Configured merge policy for maps is hz.ADD_NEW_ENTRY.
2- Split brain occurs with 4 lite members to 2 lite + 1 regular members.
3- Merge takes place on the side with only lite members and data is lost.

Related to the issue #6770

**Comment by mdogan** [comment]
Hazelcast 2.x development is discontinued. Won't fix.
