### ISSUE TITLE
Unit tests should have default timeout

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#6978]
Unittests currently don't have a default timeout and this can lead to a single unit tests stalling the build till the build run into a timeout. This is a problem because apart from this problematic test, any other problematic test is hidden.

Therefor by default each unit test should have a default timeout of a few minutes unless one is defined explicitly.

**Comment by Donnerbart** [comment]
We should define a constant in `HazelcastTestSupport` for this, so if we need to adjust this value it will be in a single place. For example: `HazelcastTestSupport.DEFAULT_TEST_TIMEOUT`
