### ISSUE TITLE
[hibernate] SoftLocking leads to deserialization of data on server

### ISSUE THREAD

**Issue by ehucka** [hazelcast/hazelcast#6985]
hazelcast 3.6-EA2
hibernate 3.6.10.Final

I use the hazelcast as 2nd level cache for hibernate. It is simple 2 members cluster - 
one embedded member in tomcat and one standalone member for asynchronous backup. 
The cache works fine alone in the embedded member only but when I start the standalone server 
it starts to fire exceptions java.lang.ClassNotFoundException: org.hibernate.cache.entry.CollectionCacheEntry.

I prefer the data would not be deserialized on server from binary format just like in 3.5.4 version.
I had to switch from 3.5.4 to 3.6 version because the cluster sometimes (very often) locked application in put operations.

[stacktrace.txt](https://github.com/hazelcast/hazelcast/files/51160/stacktrace.txt)

**Comment by emrahkocaman** [comment]
Moved to Hibernate repo (https://github.com/hazelcast/hazelcast-hibernate/issues/12)
