### ISSUE TITLE
Missing com.hazelcast.client.impl.protocol.codec.CacheContainsKeyCodec 

### ISSUE THREAD

**Issue by guhuaping** [hazelcast/hazelcast#7019]
Latest code (master) seems miss this file, and build failed, is it intentionally and available for commercial version only or missed checked in?

thanks

**Comment by Donnerbart** [comment]
Codec files are generated, so this file is not part of the checked in source code, but generated during the compilation. Can you please execute a `mvn clean install -DskipTests` and check if the file is being generated? It should be located in `./hazelcast/target/generated-sources/annotations/com/hazelcast/client/impl/protocol/codec`

**Comment by guhuaping** [comment]
Thanks, it works after svn clean install -DskipTests
