### ISSUE TITLE
Improve generics in EntryProcessors related methods in IMap

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#7028]
`IMap` has methods as `Object executeOnKey(K key, EntryProcessor entryProcessor);` instead of `Object executeOnKey(K key, EntryProcessor<K, V> entryProcessor);`

It can lead to bugs where an entry processor accidentally changes a type of the value stored -> `ClassCastException`. What's worst the exception will likely be thrown later during a different operation -> a very hard to find class bugs.

Furthermore the `EntryProcessor` should probably use a generic type as its return value. So
instead of the current:

``` java
public interface EntryProcessor<K, V> extends Serializable {
    Object process(Map.Entry<K, V> entry);
[...]
```

we should have:

``` java
public interface EntryProcessor<K, V, R> extends Serializable {
    R process(Map.Entry<K, V> entry);
[...]
```

Attention must be paid to possible compile-time compatibility issues when introducing these changes.

**Comment by LoneRifle** [comment]
@tombujok @jerrinot I plan to submit a PR in relation to this issue, unless @tombujok has already started work on this?
