### ISSUE TITLE
ICache.iterator() fetchSize is not configurable

### ISSUE THREAD

**Issue by alparslanavci** [hazelcast/hazelcast#7041]
ICache's iterator method returns an Iterator which fetches the 100 number of entries at a time. This number is hard coded now, and should be configurable.

**Comment by jerrinot** [comment]
@alparslanavci: do you think it should be configurable on per-cache basis?

**Comment by pveentjer** [comment]
Why should this be configurable? Of course everything can be made configurable, but you also start to expose more and more of the internals this way. Apart from that it adds complexity.

**Comment by alparslanavci** [comment]
Actually, this is a customer request. They want to specify how many entries can be fetched at a time because of their high-performance needs.
