### ISSUE TITLE
AWS authentication should use default credentials

### ISSUE THREAD

**Issue by tlamerig** [hazelcast/hazelcast#7087]
In the status quo, running Hazelcast in AWS mode requires the user to specify either access/secret key or IAM role. This is unfortunate because both an IAM role and a bunch of EC2 instances can be created dynamically using CloudFormation, in which case the IAM role gets a non-predictable id. CloudFormation will make sure to assign this role to the EC2 instances. The non-predictable id makes it much harder to deploy a Hazelcast application with the correct IAM role name.

The solution is to make Hazelcast (com.hazelcast.aws.impl.DescribeInstances#getKeysFromIamRole) not retrieve credentials for an explicit IAM role but rather for the default IAM role. That way, a Hazelcast instance can run on AWS completely WITHOUT ANY credentials.

An example of this approach can be found in com.amazonaws.internal.EC2MetadataClient#getDefaultCredentials, which is used by com.amazonaws.auth.InstanceProfileCredentialsProvider.

**Comment by bilalyasar** [comment]
@tlamerig , for the workaround: maybe you can set iam-role name as environment variable. Then in hazelcast.xml you can use that environment variable.

**Comment by tlamerig** [comment]
@bilalyasar tx for the suggestion, that may work for me, for now.

**Comment by tlamerig** [comment]
Milestone seems incorrect (3.6.2 has already been released)

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/8100
