### ISSUE TITLE
3.6 Docs are incorrect for Enterprise WAN Replication

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7099]
http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#enterprise-wan-replication-configuration

states that the Strategy classes are in the following package:
com.hazelcast.wan.impl.

The enterprise code is expecting classes in:

con.hazelcast.enterprise.wan.replication

Using the former package results in a ClassCastException.

**Comment by StanAccy** [comment]
I think I misread the doc page - the page has both non-enterprise and enterprise settings (which have different package names)

**Comment by Serdaro** [comment]
WAN chapter will go through a full review before the final release of 3.6. Thanks for the issue.

**Comment by mesutcelik** [comment]
@Serdaro ,
I am closing this issue. Can we create a new issue in Reference Manual Repository? I think documentation repo should be natural host for the issue...

**Comment by Serdaro** [comment]
@mesutcelik :+1: 
https://github.com/hazelcast/hazelcast-reference-manual/issues/95
