### ISSUE TITLE
3.6 EA3 ManCenter WAN Queue counts incorrect

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7100]
The queue counts shown in ManCenter do not seem correct.

We sent a test case of 20 entries across a WAN replication (using Batch) and ended up with a non-zero count displayed in the UI.

**Comment by emrahkocaman** [comment]
Fixed by https://github.com/hazelcast/hazelcast-enterprise/commit/eb8a3ea5785a7dafce9ced624f36181767262782
