### ISSUE TITLE
I'd like to be able to enable SSL on WAN replication links independently of internal cluster SSL.

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7128]

**Comment by pveentjer** [comment]
This is probably going to be added to HZ 3.10.

**Comment by burakcelebi** [comment]
Closed as internal request

**Comment by vertex-github** [comment]
For the sake of clarity, this was a customer request that wanted to enable SSL on WAN rep but not have SSL enabled within the cluster.

**Comment by burakcelebi** [comment]
Many thanks @vertex-github. Added your comment to the PRD.
