### ISSUE TITLE
ClientRegressionWithMockNetworkTest Failures

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7133]
**testOperationRedo
testDeadlock_WhenDoingOperationFromLifecycleListener
testNearCache_WhenRegisteredNodeIsDead
testDeadlock_WhenDoingOperationFromLifecycleListener
testDeadlock_WhenDoingOperationFromLifecycleListener_and_NearCache
testClientReconnect_thenCheckRequestsAreRetriedWithoutException**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/71/

**ClientRegressionWithMockNetworkTest.testClientReconnect_thenCheckRequestsAreRetriedWithoutException**

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/72/testReport/junit/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testClientReconnect_thenCheckRequestsAreRetriedWithoutException/

**Comment by cangencer** [comment]
This is the same issue as #6153, so closing this one as a duplicate.

**Comment by cangencer** [comment]
On closer inspection,  not all test failures in this were related to classloader deadlock in #6153. However they seem to have the same cause as #7134, so reopening the issue

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/74/

**Comment by cangencer** [comment]
Looks like some of these are still failing:

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-ZuluJDK7/lastCompletedBuild/com.hazelcast$hazelcast-client-legacy/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/testDeadlock_WhenDoingOperationFromLifecycleListener_and_NearCache/

**Comment by sancar** [comment]
Issue seems to be different. New failures are related to `testDeadLock.*` tests. 
And after the fix #7159, they are also not failing.

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/4279/

**Comment by ihsandemir** [comment]
Submitted PR for fixing the last issue: https://github.com/hazelcast/hazelcast/pull/7215
