### ISSUE TITLE
missing flush() api in all ADT

### ISSUE THREAD

**Issue by publicocean0** [hazelcast/hazelcast#7238]
I found flush() api  just in imap ADT. I dont find it in multimap

**Comment by jerrinot** [comment]
actually I just realized there is no map store in multi map. `flush` makes sense only in structures backed by a store. Is this correct?

**Comment by publicocean0** [comment]
ah ok, but when hz is shutdowning ... it is not necessary to call flush for granting the data is atomically sent to the cluster ? ( i dont know exactly how works ) even if just a second before of shutdown , is updated the map. My app is strongly interactive ... for this reason my worries :)

**Comment by jerrinot** [comment]
All methods on the `MultiMap` interface are sync. 
They are blocking the calling thread until the call is finished. There is no need to call flush before shutdown. 

Flush is useful only when you have a map store defined. See it's contract:
```
/**
     * If this map has a MapStore, this method flushes
     * all the local dirty entries by calling MapStore.storeAll() and/or MapStore.deleteAll().
     */
    void flush();
```

It has no effect if a map has no map store defined.

**Comment by publicocean0** [comment]
ah ok , so then it is not necessary :)

**Comment by jerrinot** [comment]
Great, I am glad I could clarify this for you
Have a great day!
Jaromir
