### ISSUE TITLE
loadAll() in Store problem

### ISSUE THREAD

**Issue by publicocean0** [hazelcast/hazelcast#7239]
loadAll() in Store is not correct , replace it with Iterator. If the collection is loaded from DB with a million of items, what does it happen?

**Comment by jerrinot** [comment]
this sounds as a sensible enhancement. @ahmetmircik: WDYT?

**Comment by publicocean0** [comment]
surely :)

2016-01-04 15:18 GMT+01:00 Jaromir Hamala <notifications@github.com>:

**Comment by jerrinot** [comment]
Hello @publicocean0,

just a clarification - there is `loadAll()` method in both `MapStore` and `IMap` intefaces. Which one do you think should be replaced?

**Comment by publicocean0** [comment]
The better thing is to replace  both if it is possible , for my opinion. The priority is for MapStore , because developer can decide to not use the second one in a big store, but first one is not completely depended on himself.

**Comment by tombujok** [comment]
Thanks for your feedback guys. The thing is that the map-loader will never load a million items if not asked to do so. 

The sequence of operations looks as follows: first the MapLoader's `Iterable<K> loadAllKeys()` methos is called to load all the keys. It uses the `Iterable` interface so we are on a safe-side here.
Then the map loader sends the keys in `batches` - values for each `batch` of keys will be loaded using the `loadAll` method. 

The `batch` size can be adjusted - it's a property on the `MapKeyLoader`. It's wired-up as a property:
`MAP_LOAD_CHUNK_SIZE("hazelcast.map.load.chunk.size", 1000),` - by default it's 1000.

That being said - the `loadAll` method shouldn't actually use the `Iterable` - it should be implemented in such a way that it's optimised for `batch` loading of chunks that are of reasonable size. Of course it may be "abused", but IMHO the current implementation is fine.

**Comment by publicocean0** [comment]
Sorry but in the last version of HZ , 3.4 (seeing docs http://docs.hazelcast.org/docs/3.4/javadoc/com/hazelcast/core/MapLoader.html)   :   
<pre>
V 	load(K key)
Loads the value of a given key.
Map<K,V> 	loadAll(Collection<K> keys)
Loads given keys.
Set<K> 	loadAllKeys()
Loads all of the keys from the store.
</pre> 
so Iterable<K> loadAllKeys() doesnt exist!!!

So the problem is simply moved to this API :)

**Comment by tombujok** [comment]
The last version is 3.5.x
http://docs.hazelcast.org/docs/3.5/javadoc/com/hazelcast/core/MapLoader.html
```
Iterable<K>	loadAllKeys()
```

**Comment by publicocean0** [comment]
ah all ok :)

**Comment by tombujok** [comment]
OK. Thx. I'm closing the issue then.
