### ISSUE TITLE
In ManagementCenter, I'd like the option to have the browser tab name (title) changed to the cluster name

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7243]
3.6-122315-Enterprise:

When dealing with multiple clusters within ManagementCenter, I'd like to be able to change the browser tab title to reflect the cluster name, rather than "Hazelcast Management Center".  This allows us to open multiple tabs within a browser, one per cluster, and be able to easily switch between tabs.  If this could be done as an option (or as default) it would be helpful.  Keep the Hazelcast icon in the tab title for easy tab recognition.

**Comment by emrahkocaman** [comment]
Resolved by https://github.com/hazelcast/management-center/commit/2bd53149ab3cbe55896d68cb9ff51c02f3f8ffdc
