### ISSUE TITLE
Management Center WAN Replication metrics take a long time to stabilize

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7244]
Enterprise-3.6-122315 / Management Center:

I wrote a client program to load entries in to a WAN replicated IMap (with exception on overrun enabled).  I added Dropwizard.io Metrics to the client loader program to view the throughput in order to compare the figures shown in ManCenter WAN tab (for outbound recs/s).  WRQ size was set to 2000, loading in batches of 1000 entries <Integer,String>.  The Dropwizard metrics stabilize on a throughput number far quicker than the figures in ManCenter do.  Could the responsiveness of the Outbound Recs/s metric be improved? It currently seems to under-report WAN replication performance for 10s of seconds before reaching the same figure as the client side reported metrics.

**Comment by emrahkocaman** [comment]
Fixed by https://github.com/hazelcast/management-center/commit/7348035a12dae0153cc35bd34506c97cda8aff87
