### ISSUE TITLE
Please could you provide an enterprise-javadoc.jar in the Enterprise bundle

### ISSUE THREAD

**Issue by StanAccy** [hazelcast/hazelcast#7245]
Enterprise 3.6-122315

Please could you provide an enterprise Javadoc JAR bundle so that we can install the JavaDocs in a dev repo along side the enterprise-client.jar and enterprise.jar.  This way IDEs can auto-import the Javadocs for the Enterprise APIs and provide context sensitive completion/help within the IDE.

**Comment by vertex-github** [comment]
Any chance this could be added for the 3.6.1 release - its a pain working with the Enterprise JAR and not having the Javadocs mapped.

**Comment by hasancelik** [comment]
Enterprise javadoc jars were deployed to 3.7-SNAPSHOT repo.3.6.2 will have these jars.You can try with master and give feedback us.
