### ISSUE TITLE
hazelcast objects destroy mechanism

### ISSUE THREAD

**Issue by yangmin1989** [hazelcast/hazelcast#7246]
I use Lock and Map via hazelcast.I find that the heap memory on hazelcast server keep increasing.All the Locks and Maps I created  are destroyed by method destroy(),but the memory can not be destroyed by garbage collector even via FGC.So when my program run for some time,hazelcast server will go down.
Why?
    I dumped the heap,and find that Locks and Maps has been destroyed.However, many other objects related to Locks and Maps  are not been destroyed.So the more new Locks and Maps I create,the faster the heap increases.
   There are the kind of object relavant still exist in heap when I destroy Lock and Map:
1.ConcurrentMap<ObjectNamespace, EntryTaskScheduler> evictionProcessors in LockServiceImpl 
2.ConcurrentMap<ObjectNamespace, LockStoreImpl> lockStores in LockStoreContainer 
3.ConcurrentMap<String, LocalMapStatsImpl> statsMap in LocalMapStatsProvider
   Is this bugs of hazelcast?  or hazelcast doesnt surpport the scene that keep creating  new DistributedObjects and destroy them?
  Attach files is the screenshot of the heap distribution.
expecting your answer,thanks

**Comment by yangmin1989** [comment]
my hazelcast version is 3.4.1
Attach files is the screenshot of the heap distribution.

**Comment by yangmin1989** [comment]
![Uploading lockStores.gif…]()
![Uploading heap.gif…]()

**Comment by pveentjer** [comment]
Hi @yangmin1989 I saw your question on stackoverflow and since it contains very valuable information, I'll place it here:

http://stackoverflow.com/questions/34605244/hazelcast-objects-destroy-mechanism

Thank you for your excellent analysis. 

Can you make a test that reproduces the issue?

**Comment by yangmin1989** [comment]
@pveentjer  I have reproduced the issue many times with the program which work for business of my company. if nessasary,i'd like to make a simple test for this issue and reproduce it once again.

**Comment by yangmin1989** [comment]
@pveentjer  I write a simple project which can reproduce this issue. The code is here:
https://github.com/yangmin1989/hazelcast-test
Please review this issue.Thanks!

**Comment by yangmin1989** [comment]
@pveentjer  Have you reproduced this issue? I am expecting your response.Thanks!

**Comment by mdogan** [comment]
This issue is not reproducible since 3.6. Looks like already fixed. Following are related fixes:

https://github.com/hazelcast/hazelcast/pull/5673
https://github.com/hazelcast/hazelcast/pull/6951
https://github.com/hazelcast/hazelcast/pull/6971
