### ISSUE TITLE
TopicOverloadDistributedTest

### ISSUE THREAD

**Issue by sancar** [hazelcast/hazelcast#7266]
Tests under TopicOverloadDistributedTest  are spuriously failing even in local machine.
Test itself might be wrong, needs review.
Test can be found here https://github.com/hazelcast/hazelcast/pull/7265

**Comment by jerrinot** [comment]
assigning this to @sancar as it's his test and it is not merged yet.

**Comment by sancar** [comment]
Closing this one because, we fixed the issue in the test before merging it.
