### ISSUE TITLE
QuorumListener not invoked

### ISSUE THREAD

**Issue by hos-p** [hazelcast/hazelcast#7300]
Hi,
I'd like to have 3 node cluster and for reacting on quorum lost events I'd like to use QuorumListener registered in QuorumConfig. But it seems to me that it doesn't work as I expected.

Scenario (3 nodes => quorum = 2):
- Node1 starts
- Node2 starts
- Node2 crashes => Node 1 lost quorum but my QuorumListener was not invoked on Node1.

Using Hazelcast 3.5.4.

Is it bug or am I missing something? Is there another mechanism for quorum events which I can use?

**Comment by jerrinot** [comment]
Hi @hos-p,

thanks for reporting the issue. Could you please share your configuration and listener implementation?

**Comment by jerrinot** [comment]
you can find example usages in this test: https://github.com/hazelcast/hazelcast/blob/v3.5.4/hazelcast/src/test/java/com/hazelcast/quorum/QuorumListenerTest.java#L44

**Comment by hos-p** [comment]
Thanks for sample. Seems to me that invocation of quorum listener needs at least attempt to perform map operation and in my case there was none. So it's not a bug but my misunderstanding of quorum listener. Is there any other quorum event mechanism for hazelcast instance not just for map and its operations?

**Comment by jerrinot** [comment]
@hos-p: the current behaviour is working as designed, but it seems we could change it to support even your case. @eminn is looking into it. we are rushing with 3.6 release so chances are it will take a few days. 

Up to my knowledge quorum is supported in IMap since Hazelcast 3.5 and in JCache since 3.6 (currently in RC1)
