### ISSUE TITLE
OSGI optional dependencies for jclouds

### ISSUE THREAD

**Issue by david-t-daniel** [hazelcast/hazelcast#7318]
For the 3.6 version of hazelcast it would be preferred if org.jclouds.* were marked as optional dependencies in the manifest file.

**Comment by mesutcelik** [comment]
I think adding `org.jclouds.*` entry [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-all/pom.xml#L91) should fix the problem. @kobalski ?

**Comment by david-t-daniel** [comment]
I think you would probably have to do something more like is done for log4j as you are including both org.jclouds and org.jclouds.googlecloud  It is probably better to list the packages rather than use the * operator.
