### ISSUE TITLE
Hazelcast 3.5.5 release date

### ISSUE THREAD

**Issue by mirkosertic** [hazelcast/hazelcast#7325]
Hi,

We are waiting for the fix of #6731. When will Hazelcast 3.5.5 be released?

Thanks at all,
Mirko

**Comment by mesutcelik** [comment]
Hi @mirkosertic ,

We are planning to start stability/performance testing next week so you can assume it by the end of next week. 

Btw, you can always ask such questions to [Hazelcast Google Group](https://groups.google.com/forum/#!forum/hazelcast)
