### ISSUE TITLE
When used as cache manager, Hazelcast does not preserve parent class' attribute values

### ISSUE THREAD

**Issue by lobofa** [hazelcast/hazelcast#7330]
I am developing an application using Hazelcast as our cache manager, and we have the following issue: when we retrieve a cached object, the same has all its properties set excepting those attibutes that belongs to the object's parent class.

Example:
```java
@MappedSuperclass
public abstract class AbstractEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    public Long getId() {					return id;			}
    public void setId(Long id) {			this.id = id;		}
	
}

@Entity
@Table(name = "products")
public class Product extends AbstractEntity implements Serializable {

	@Column(name = "name", length = 100, nullable = false)
    private String name;
	
	public String getName() {				return name;		}
    public void setName(String name) {		this.name = name;	}
	
}
```
In other class ...

```java
    @Cacheable
    @Transactional(readOnly = true)
    @PreAuthorize(AuthorizationRules.IS_AUTHENTICATED)
    public Product getSafe(Long id) {
        Product product = productRepository.findOne(id);
        return product;
    }
```

Beans definition

```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:p="http://www.springframework.org/schema/p" xmlns:cache="http://www.springframework.org/schema/cache"
    xmlns:hz="http://www.hazelcast.com/schema/spring"
    xsi:schemaLocation="
        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
        http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache-4.1.xsd
        http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd">

    <cache:annotation-driven cache-manager="cacheManager" />

    <bean id="cacheManager" class="com.hazelcast.spring.cache.HazelcastCacheManager">
        <constructor-arg ref="instance" />
    </bean>

    <hz:hazelcast id="instance">
        <hz:config>
			...
			<hz:map name="products" backup-count="1" max-size="1000" eviction-percentage="30" read-backup-data="true"
                time-to-live-seconds="3600" max-idle-seconds="300" eviction-policy="LRU" 
                merge-policy="com.hazelcast.map.merge.PutIfAbsentMapMergePolicy" />
		</hz:config>
    </hz:hazelcast>
</beans>
```

The first time that the method annotated with @Cacheable is called, the Product instance has the 'id' property (declared in the parent class) with the correct value.

![product-before-cached](https://cloud.githubusercontent.com/assets/12830581/12335752/7aa8c716-badf-11e5-8930-3fe484753a7f.jpg)

But when this method is called again (and the cached object is returned), the same has the 'id' property with null.

![product-after-cached](https://cloud.githubusercontent.com/assets/12830581/12335753/7ab0356e-badf-11e5-939d-10311348b45d.jpg)

Environment

JDK 1.7.0_79
Spring Framework 4.1.6
Hazelcast 3.5.2

**Comment by emrahkocaman** [comment]
Hi @lobofa ,

Base class should also be `Serializable`. 
Could you please change your `AbstractEntity` class to implement `Serializable` interface?

**Comment by serkan-ozal** [comment]
Yes, even though concrete class is `Serializable` since base class is not  `Serializable` its fields are ignored while serializing so only fields in concrete class are serialized. 

So,
* As @emrahkocaman stated, you may declare your base class as `Serializable` 
* You may define the required fields inside private static final field `serialPersistentFields`
* You may handle super class state by custom `readObject` / `writeObject` methods inside concrete class.

For more information, you can look at Java Serialization support.

You may examine related JDK classes `java.io.ObjectOutputStream`, `java,io,ObjectStreamClass` if you want to look at this behaviour more detailed.

**Comment by lobofa** [comment]
Thank you. It works
