### ISSUE TITLE
Access data is not updated by local reads when reading from backup is enabled

### ISSUE THREAD

**Issue by GhostInAMachine** [hazelcast/hazelcast#7354]
Related to https://github.com/hazelcast/hazelcast/issues/7341

Steps to reproduce:

1. Create a map and enable reading from backups
2. Get local keys by using *localKeySet* method
3. Iterate over those keys and perform a get on each one
4. Take a look at entry view of each key
5. Observe that access timestamps are not updated

**Comment by tombujok** [comment]
It's just another manifestation of the problem described here #7341
So i'm closing this one as a duplicate.
