### ISSUE TITLE
add map.partition-strategy configuration into Spring config

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7363]
It is possible to specify partition-strategy in HZ confug, but not in Spring config. Please add it. Not implemented in any HZ versions, afaik.
Also, would be nice to be able to specify not only class implementing partoition strategy, but an implementing instance as well.

Thanks, Denis

**Comment by dsukhoroslov** [comment]
Hi @jerrinot 

I can implement it for 3.7. As well as other configuration parameters missed in spring-integration.

**Comment by jerrinot** [comment]
@dsukhoroslov: That would be awesome! 
@mesutcelik: I guess you will not complain about this? ;-)

**Comment by mesutcelik** [comment]
we are looking forward to your PR @dsukhoroslov :)

**Comment by dsukhoroslov** [comment]
ok, started to work on it in scope of this issue and #6567. If you're aware of any other configuration elements missed in Spring - please tell me, I'll try to handle them too.

**Comment by elgamilg** [comment]
@dsukhoroslov: I have a similar issue and noticed the following properties are also missing from the Spring config in 3.6.1:
- In <hz:multicast> there is no way to specify "trusted-interfaces"
- In <hz:network> there is no way to specify "port-count"
- In <hz:aws> there is no way to specify "iamRole"

**Comment by mesutcelik** [comment]
Hi @dsukhoroslov ,
Have you had some time to work on this? 

@elgamilg has pointed some more properties missing in the current implementation. It would be great if you include them as well.

**Comment by dsukhoroslov** [comment]
Hi @mesutcelik,

Yes, I started and did all changes in schema, but had no time to finish it in java. Hopefully will do next week. Sure, I'll add the properties mentioned by @elgamilg.
I'm still waiting when my PR #7546 will be merged. It is not comfortable to work with more then one forks at the same time.

**Comment by dsukhoroslov** [comment]
solved by #8202
