### ISSUE TITLE
Optimize Record<V> and RecordStatistics  implementation

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#7372]
The current Record implementation eats a lot of memory. In my case for 35M cached objects the overhead caused by ObjectRecordWithStats and RecordStatistics instances became 4.7G. In order to prevent long GC pauses I'm going to use native memory, but even this will not help when the Record overhead is so high. 

The current Record impelmentation is:

```
abstract class AbstractBaseRecord<V> implements Record<V> {

    protected long version;
    /**
     * evictionCriteriaNumber may be used for LRU or LFU eviction depending on configuration.
     */
    protected long evictionCriteriaNumber;
    protected long ttl;
    protected volatile long lastAccessTime;
    protected volatile long lastUpdateTime;
    protected long creationTime;
```

here a lot of long fields are used. Not all of them must be long, I believe. At least, not for all use cases. In many cases the cache life time is so long and takes less than 50 days even in prod env (system maintenance once a month is obvious). And a life time of cached entries even shorter, usually. So, it'd be possible to provide another Record emplementation which will cause twice less overhead. And no need to change Record interface:

```
abstract class TinyAbstractBaseRecord<V> implements Record<V> {

    protected int version; // allows up to 2^32 updates: up to 49.7 days with every millisecond update

    protected int evictionCriteriaNumber; // in case of LFU the number of hits ca be used instead, which is int. If there is no RecordStatistics then it can be stored as int. In case of LRU just use lastAccessTime.

    protected int ttl; //just use one bit for time units condition (ms or days) and other bits to store the actual value

    protected volatile int lastAccessTime; // coded as number of milleseconds after creationTime

    protected volatile int lastUpdateTime; // coded as number of milleseconds after creationTime

    protected long creationTime;  // ok, let's leave it long
```

the same optimization can be applied to RecordStatistics class on lastStoredTime and expirationTime fields.

The MapConfig should get some new parameter (long-live: true/false ?) which will specify what kind of RecordFactory MapContainer will create.

If you agree I can provide PR.

Thanks, Denis.

**Comment by jerrinot** [comment]
@dsukhoroslov: thank you for your suggestion. This would save 20B per record. While I agree we should decrease our memory overhead I am not sure about this very case. 

@ahmetmircik: What do you think about this?

**Comment by pveentjer** [comment]
We know the map is not very memory efficient. One simple way to reduce overhead is to disable the statistics for the map using MapConfig.statisticsEnabled setting;so do you need these statistics at all?

**Comment by dsukhoroslov** [comment]
Yes I turn it off. Moreover, for my usecase I did even more extreme Record implemetation: it has key and value fields only, nothing else. Saves a lot of memory for me (in real case I'll have up to 150M cached entries, so the saved space is significant). I can provide it as a PR too.

**Comment by dsukhoroslov** [comment]
BTW, this functionality was requested by #4829

**Comment by ahmetmircik** [comment]
@jerrinot : Already considering some similar changes to reduce that memory footprint problem, i guess it may be a part of 3.7 enhancements. But there is also some other considered changes which need to be done before this enhancement like eviction mechanism changes. For this reason, if @dsukhoroslov sent his work, most probably, it will become obsolete.

**Comment by jerrinot** [comment]
@ahmetmircik: what's the situation here?

**Comment by mmedenjak** [comment]
Related: 
https://github.com/hazelcast/hazelcast/issues/2548
https://github.com/hazelcast/hazelcast/issues/3451

**Comment by mmedenjak** [comment]
We'll be optimising the record overhead for NATIVE memory in 4.2 with the concept of "pay for what you use"

**Comment by ahmetmircik** [comment]
Besides NATIVE, BINARY and OBJECT formats will also benefit from this optimization.

**Comment by mmedenjak** [comment]
That's great, I forgot about that. In that case, you can see some related issues above. I guess we can then bring them into the 4.2 milestone and close then with the PRs as well.

**Comment by mmedenjak** [comment]
@ahmetmircik can we close this issue now that the situation has improved?

**Comment by ahmetmircik** [comment]
@mmedenjak yes seems so.

**Comment by mmedenjak** [comment]
Thank you for the awesome improvement, closing.
