### ISSUE TITLE
Best way to remotely validate hazelcast on a given port is functioning/available

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#7381]
Hi,
Continuing to work on this discovery strategy for consul: https://github.com/bitsofinfo/hazelcast-consul-discovery-spi

With consul you can register health checks, in the form of a small script. For hazelcast I am currently just doing the following port checks like `exec 6<>/dev/tcp/#HAZELCAST_IP/#PORT || (exit 3)`

This works fine in detecting if a given HZ instance is "up" (at least as the port is concerned), however in the hazelcast logs on the instance being checked, I see these kinds of errors/warnings.

Is there a better way to do this kind of checking (that could be done via a script such as the above), or a way to avoid HZ logging these connections, with no obvious compliance to the HZ gossip/cluster protocol?

```
Nov 20, 2015 6:57:50 PM com.hazelcast.nio.tcp.SocketAcceptorThread
INFO: [192.168.0.208]:5701 [hazelcast-consul-discovery] [3.6-RC1] Accepting socket connection from /192.168.0.208:53495
Nov 20, 2015 6:57:50 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [192.168.0.208]:5701 [hazelcast-consul-discovery] [3.6-RC1] Established socket connection between /192.168.0.208:5701 and /192.168.0.208:53495
Nov 20, 2015 6:57:50 PM com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketWriter
WARNING: [192.168.0.208]:5701 [hazelcast-consul-discovery] [3.6-RC1] SocketWriter is not set, creating SocketWriter with CLUSTER protocol!
Nov 20, 2015 6:57:50 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [192.168.0.208]:5701 [hazelcast-consul-discovery] [3.6-RC1] Connection [/192.168.0.208:53495] lost. Reason: java.io.EOFException[Could not read protocol type!]
```

**Comment by harish324** [comment]
@bitsofinfo Did you ever find a suitable health check?

**Comment by bitsofinfo** [comment]
No, this is still outstanding. It would be nice if HZ exposed some way to indicate it is up, other than just a socket connect on this port (which results in that above output)

**Comment by mdogan** [comment]
Since 3.8, Hazelcast provides health check via HTTP.

See https://github.com/hazelcast/hazelcast/pull/9284
