### ISSUE TITLE
no-op multiple entry operations should update `get` and `hit` count

### ISSUE THREAD

**Issue by emrahkocaman** [hazelcast/hazelcast#7389]
`AbstractMultipleEntryOperation` increments put/remove counts when entries are updated/removed
but if an `EntryProcessor` does only `get` then `get`/`hit` count is not updated.

Stats updated when entry added/updated;
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/operation/AbstractMultipleEntryOperation.java#L157

Stats updated when entry removed;
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/operation/AbstractMultipleEntryOperation.java#L146

**Comment by tombujok** [comment]
@gurbuzali @jerrinot @ahmetmircik do we have a consensus to implement it? The fix is easy but there's a question if an `EP.process(entry)` method may be treated as a get/hit? EP may be also treated as a full-table scan query. Also users who monitor the stats may be surprised by a sudden increase...
