### ISSUE TITLE
Distributed Class loading (Feature Request)

### ISSUE THREAD

**Issue by the100rabh** [hazelcast/hazelcast#7394]
There should be this ability in Hazelcast to do distributed loading of classes so that jobs like MapReduce and Aggregate can be done more effectively. 

Things like custom predicates will not work for aggregate if using through Hazelcast client as in https://github.com/hazelcast/hazelcast/issues/7386

Without this feature, map reduce and aggregate becomes highly restrictive and if we need to add a new predicate, it would mean restarting the entire cluster which is not desirable at all.

**Comment by serkan-ozal** [comment]
Hi,

This may take your interest https://github.com/serkan-ozal/hermgen

Regards.

**Comment by bwzhang2011** [comment]
@serkan-ozal, maybe it's better to make it accepted and merged into hazelcast master branch and make it to be the feature.

**Comment by metanet** [comment]
@serkan-ozal such feature could be nice

**Comment by vertex-github** [comment]
+1 (although I recall seeing a similar issue logged so this could be a duplicate)

**Comment by bwzhang2011** [comment]
@serkan-ozal, any update with such issue ? hope such feature could be provided officially.

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/9331
