### ISSUE TITLE
Hazelcast issue with session attribute listeners

### ISSUE THREAD

**Issue by valsaraj** [hazelcast/hazelcast#7415]
Hi,

This ticket is regarding this post: https://groups.google.com/forum/#!topic/hazelcast/C5WL8mW1lk4.
**SessionAttributeListener not working after adding Hazelcast session replication**

> We are using SessionAttributeListener  in our application and was working fine in single node and clustered environment. We added Hazelcast session replication recently and now SessionAttributeListener  not working.

Please suggest a solution.

Thank you,
Valsaraj

**Comment by mesutcelik** [comment]
closing this as discussion is already on Google Groups.
