### ISSUE TITLE
Potential NPE in MembershipEvent.getMembers()

### ISSUE THREAD

**Issue by nilskp** [hazelcast/hazelcast#7429]
`MemberAttributeEvent` extends `MembershipEvent` and calls its constructor using `null` for `Set<Member> members`, which means that `MembershipEvent.getMembers()` will return `null`. 
If intentional, it's not documented that `getMembers()` can return `null`.

**Comment by jerrinot** [comment]
It should NOT return null. Liskop subs. principle should be applied here.

**Comment by jerrinot** [comment]
I wonder what's the reason for having NULL here. 
@noctarius: Do you have any idea?

**Comment by pveentjer** [comment]
I guess it is caused by improper use of class hierarchy and now the member attribute event needs to provide a members set.
