### ISSUE TITLE
Mapstore store all method invocation stops after certain time

### ISSUE THREAD

**Issue by sivacj521** [hazelcast/hazelcast#7451]
We have a hazelcast cluster that works for sometime and it stops persisting data to DB when a brust of Put request is performed on the cache. Cache never recovers after this, in order for us to get the persistence going we had to bounce all our cluster instances one at a time. When they all bounced we see persistence continuing. We don't see any exceptions or anything on the store itself.. we are using 3.5 version. We also noticed that writes to store all invocation stops once dirty county goes to 0. But when maps starts to get data those are not stored.Any help is appreciated. There is no exception or anything useful in logs when this happens. The cluster itself is fully functional after this but store all never gets kicked in until we restart the cluster in a staggered way. Is this a issue with 3.51?

**Comment by jerrinot** [comment]
Hello @sivacj521,

thank you for reporting the issue. Without having any evidence it's hard to tell what is going on. Are you using write-through or write-behind? Could you try it with Hazelcast 3.6 or at least the latest 3.5.x patch release. 

If that does not help then I'd recommend to use DEBUG logging and gather some additional data.

**Comment by sivacj521** [comment]
Sure, we are using write-behind, we will turn on DEBUG logging and will see if we can replicate the issue with 3.6.

**Comment by ahmetmircik** [comment]
Please try with 3.6.2 or a higher version and open an issue if issue still exists.
