### ISSUE TITLE
All JMX Beans disappear when single Hazelcast instance is shut down in the same JVM

### ISSUE THREAD

**Issue by mirkosertic** [hazelcast/hazelcast#7467]
I am running multiple Hazelcast 3.5.5 instances in the same JVM. When i programatically shutdown one instance, all other existing instances are also deregistered as JMX Beans, but they are still alive and running. Creating a new instance programatically then only registers the new instance, all others are no longer available via JMX.

All running Hazelcast Instances should always be visible by JMX (if JMX is enabled).

**Comment by mirkosertic** [comment]
This seems to happen if two applications using Hazelcast are deployed in one Tomcat running in the same JVM. Shutting down the last Instance of one application also unregisters the still living instances in the other application.

**Comment by mirkosertic** [comment]
This should do the trick:

```java
    public static void shutdownAll() {
        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        try {
            Set<ObjectName> entries = mbs.queryNames(new ObjectName(DOMAIN + ":*"), null);
            for (ObjectName name : entries) {
                if (mbs.getClassLoaderFor(name) == ManagementService.class.getClassLoader()) {
                    if (mbs.isRegistered(name)) {
                        mbs.unregisterMBean(name);
                    }
                }
            }
        } catch (Exception e) {
            Logger.getLogger(ManagementService.class.getName())
                    .log(Level.WARNING, "Error while shutting down all jmx services...", e);
        }
    }

```

**Comment by emrahkocaman** [comment]
Hi @mirkosertic ,

I'm not able to reproduce your case. When  `HazelcastInstance#shutdown` method is called,
it'll call `ManagementService#destroy` (`shutdownAll` should not be called) method which unregisters the MBeans of only related instance. (by instance name). Not all of MBeans are unregistered.

Please see;

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/jmx/ManagementService.java#L92

Here is the test that I've created and not able to reproduce your issue.

https://gist.github.com/emrahkocaman/92755f326c186fbf2579

**Comment by mirkosertic** [comment]
See my comment at https://gist.github.com/emrahkocaman/92755f326c186fbf2579

**Comment by emrahkocaman** [comment]
@mirkosertic, but this happens only if INSTANCE_MAP size is 0. All instances are needed to be shutdown for this to work, am I missing something?

**Comment by emrahkocaman** [comment]
@mirkosertic Can you please check my previous comment?

**Comment by mirkosertic** [comment]
I have checked the comment. Indeed, it is called if INSTANCE_MAP size is zero. 

We are running two web applications on the same tomcat in the same JVM. 
In each web application a single Hazelcast instance is created.
There is only one PlatformMBeanServer for the JVM, and the two Hazelcast instances are registered as MBeans on the single PlatformMBeanServer.

The tricky part is the ClassLoader. The Hazelcast JAR is distributed in every WAR file, and hence every web application has its own Classloader. And from the point of view of a single web application, INSTANCE_MAP is one and not two. And now if the single Hazelcast instance is shutdown, INSTANCE_MAP will become 0, and this triggers the shutdown of EVERY registered instance MBean in the current JVM, and this will also kill the remaining instance.

I hope this makes the Bug clearer...
