### ISSUE TITLE
Hazelcast should provide an abstract Mapper implementation which invokes the Supplier given to Aggregation#getMapper()

### ISSUE THREAD

**Issue by messo** [hazelcast/hazelcast#7477]
Currently it is very cumbersome to write an implementation for `Aggregation` interface, since the `Mapper` interface isn't _ready_ to accept the `Supplier` passed to the mapper implementation used in aggregations.

`SupplierConsumingMapper` shows a way to do it, but `SimpleEntry` is not part of the public API.

A proposal has been made by @jerrinot in https://github.com/hazelcast/hazelcast/pull/7412#issuecomment-178682272. Basically there could be an `AbstractSupplyingMapper` which takes the `Supplier` instance given to the aggregation, makes a `Map.Entry` from the key-value pair given to the `Mapper`, invokes the `supply` method, and leaves the actual emitting to the context to the implementation.

**Comment by tombujok** [comment]
Since 3.8 the Map-Reduce aggregations are deprecated. Use the Fast-Aggregations instead (plz mind it's a link to Early-Access docs):
http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#fast-aggregations
