### ISSUE TITLE
I'd like to be able to initialize an IMap immediately after config

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#7518]
HZ 3.6

It would be helpful (for testing purposes) if we could set a flag on the IMap config that would trigger IMap initialization immediately after load - perhaps an XML element in the <map> for "init-on-startup"=true

**Comment by jerrinot** [comment]
@vertex-github: thanks for you suggestion. what's a use-cases for this?

**Comment by vertex-github** [comment]
In this situation, primarily for testing and comparison against other
IMDGs.  However, I've also seen clients looking for the IMaps etc within
ManCenter after startup - especially those coming from Coherence.

N

**Comment by burakcelebi** [comment]
Closed as internal request
