### ISSUE TITLE
Thread safety on MapContainer.addInterceptor

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#7520]
The `addInterceptor()` method in `com.hazelcast.map.impl.MapContainer()` isn't thread safe.

For example, if two concurrent attempts are made to inject the same interceptor, these will be different interceptor objects with the same id.
In this case, the call to `interceptorMap.put(id, interceptor)` will increase the map size by one,
but the call to `interceptors.add(interceptor)` will increase the list size by two.

**Comment by jerrinot** [comment]
fixed by #7531

**Comment by jerrinot** [comment]
re-opening until it's confirmed by @ahmetmircik

**Comment by ahmetmircik** [comment]
closed by https://github.com/hazelcast/hazelcast/pull/7531
