### ISSUE TITLE
Infinite Loop with NonBlockingSocketReader and ClientReadHandler

### ISSUE THREAD

**Issue by hazelcastuser2016** [hazelcast/hazelcast#7522]
- Hazelcast version: 3.6
- Cluster size: 2
- Java version: 7

The "return" statement in the following method can determine an **infinite loop**:

com.hazelcast.nio.tcp.nonblocking.**NonBlockingSocketReader.handle()**

        if (!connection.isAlive()) {
            logger.finest("We are being asked to read, but connection is not live so we won't");
            return;
        }

We had a scenario where killing one member caused  com.hazelcast.nio.tcp.TcpIpConnection.close(Throwable) to be invoked on the other member, but a failure in socketChannel.close() invocation happened.
However, TcpIpConnection "alive" flag was set to false.
Then, com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(SelectionKey) continued to be invoked because SelectionKey was still valid, with aforementioned handle() method returning because connection was not alive.
So the loop never ends, because selector is still valid and never closed (a read from the channel would probably return an EOF but the return statement prevents the read).

The same problem happens with:

com.hazelcast.client.connection.nio.**ClientReadHandler.handle()**

        if (!connection.isAlive()) {
            if (logger.isFinestEnabled()) {
                logger.finest("We are being asked to read, but connection is not live so we won't");
            }
            return;
        }

**Comment by pveentjer** [comment]
I'm working on getting this bug squashed for the 3.7 release. Do you know the type of exception you got when you called the socketchannel.close()?
