### ISSUE TITLE
3.6:  DiscoveryStrategy destroy() not being called on shutdown

### ISSUE THREAD

**Issue by simon-temple** [hazelcast/hazelcast#7545]
I have a custom DiscoveryStrategy and I can't seem to get destroy() to be called on shutdown.

I'm assuming the hz.ShutdownThread will call destroy() on all enabled DiscoveryStrategies.

Am I doing something wrong?

**Comment by simon-temple** [comment]
I'm not using a service registration file.  Instead I add it directly:
`join.getDiscoveryConfig().addDiscoveryStrategyConfig( new DiscoveryStrategyConfig( myFactory ) );`

**Comment by simon-temple** [comment]
ouch!  removeShutdownHook() throws

            try {
                if(this.groupProperties.getBoolean(GroupProperty.SHUTDOWNHOOK_ENABLED)) {
                    Runtime.getRuntime().removeShutdownHook(this.shutdownHookThread);
                }

                this.discoveryService.destroy();
            } catch (Throwable var10) {
                ;
            }

**Comment by simon-temple** [comment]
Workaround

`config.setProperty(` "hazelcast.shutdownhook.enabled", "false" );

**Comment by noctarius** [comment]
What's the exception thrown? Maybe the discovery shutdown should be moved to a finally block

**Comment by simon-temple** [comment]
IllegalStateException - If the virtual machine is already in the process of shutting down

**Comment by noctarius** [comment]
Possible to provide a full blown stacktrace? Doesn’t sounds like it's supposed to happen.

**Comment by simon-temple** [comment]
I can confirm that is thrown from here:

```
if(hooks == null)
            throw new IllegalStateException("Shutdown in progress");

```
in ApplicationShutdownHooks: 82

The exception is ignored so it's hard to get you the stack trace

`catch (Throwable ignored)`

**Comment by emrahkocaman** [comment]
I'll move `discoveryService.destroy();` to it's own try-catch block and this'll solve the problem but I didn't understand why there is an exception while removing shutdown hook and I'm not able to reproduce the problem.

@simon-temple A simple project or test case that reproduces the problem would be great.

**Comment by emrahkocaman** [comment]
@simon-temple Any luck to provide a test case?
