### ISSUE TITLE
Docker images are huge - please could they be reduced in size

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#7553]
The two Docker images are massive - could they be pared down please?  I noticed that within the ManagementCenter image that the expanded Hazelcast JARs are present in addition to the Hazelcast.zip (which is around 100Mb on its own).

Also, perhaps some of the docs could be stripped out as this is another chunk of space.

**Comment by bilalyasar** [comment]
we tried some optimization and reduced the size by 50%. 
it will be available with 3.6.2 release.

**Comment by mesutcelik** [comment]
closing now. please reopen if you still think some more improvement is needed.
