### ISSUE TITLE
3.6/3.7-SNAPSHOT: Restarted master node in 2 node cluster fails to connect

### ISSUE THREAD

**Issue by simon-temple** [hazelcast/hazelcast#7561]
I have two nodes in my cluster.  If I restart the 'none-master' node it reconnects fine.  However if I restart the master node the 'none-master' attempts to reconnect to the master but master never rejoins the group.

The master node reports a single:
`2016-02-19 09:22:07,354 INFO  [com.hazelcast.logging.Log4jFactory$Log4jLogger] (cached7) [192.168.1.137]:5701 [dev] [3.7-SNAPSHOT] Established socket connection between /192.168.1.137:5701 and /192.168.1.107:49528 (Log4jFactory.java:50)
`
The none-master node repeats this log message every 20 seconds:
`2016-02-19 09:22:07,378 INFO  [com.hazelcast.logging.Log4jFactory$Log4jLogger] (cached5) [192.168.1.107]:5701 [dev] [3.7-SNAPSHOT] Address[192.168.1.137]:5701 should merge to this node , because : node.getThisAddress().hashCode() < joinMessage.address.hashCode() , this node data member count: 1 (Log4jFactory.java:50)`

I am using a custom DiscoveryStrategy:

```
JoinConfig join = networkConfig.getJoin();
join.getMulticastConfig().setEnabled( false );
join.getAwsConfig().setEnabled( false );
join.getTcpIpConfig().setEnabled( false );
config.setProperty( "hazelcast.discovery.enabled", "true" );
join.getDiscoveryConfig().addDiscoveryStrategyConfig( new DiscoveryStrategyConfig( myFactory ) );

```

I don't understand the hashcode comparison logic...

It seems related to the joinMessage and the DataMemberCount always being 1

Setting hazelcast.initial.min.cluster.size to 2 had no effect

**Comment by kobalski** [comment]
@simon-temple I tried to reproduce your issue with a test DiscoveryStrategy implementation like below, 
with two nodes as two separate jvm processes. I could safely kill and restart both master and non-master node and two node cluster is formed without any problem. There might be a problem in your DiscoveryStrategy impl, Could you please share a small test code which reproduces your? It would be really helpful to identify the problem.

```
public class DiscoverySPITest {

    public static void main (String[] args) {

        Config config = new XmlConfigBuilder().build();
        JoinConfig join = config.getNetworkConfig().getJoin();
        join.getMulticastConfig().setEnabled(false);
        join.getAwsConfig().setEnabled(false);
        join.getTcpIpConfig().setEnabled(false);
        config.setProperty( "hazelcast.discovery.enabled", "true" );
        config.getNetworkConfig().setPort(50001);

        InterfacesConfig interfaces = config.getNetworkConfig().getInterfaces();
        interfaces.clear();
        interfaces.setEnabled(true);
        interfaces.addInterface("127.0.0.1");

        DiscoveryStrategyFactory factory = new TestDiscoveryStrategyFactory();

        DiscoveryConfig discoveryConfig = join.getDiscoveryConfig();
        discoveryConfig.getDiscoveryStrategyConfigs().clear();

        DiscoveryStrategyConfig strategyConfig = new DiscoveryStrategyConfig(factory, Collections.<String, Comparable>emptyMap());
        discoveryConfig.addDiscoveryStrategyConfig(strategyConfig);

        Hazelcast.newHazelcastInstance(config);

    }

    private static class TestDiscoveryStrategy implements DiscoveryStrategy {

        @Override
        public void start() {
        }

        @Override
        public Collection<DiscoveryNode> discoverNodes() {
            try {
                List<DiscoveryNode> discoveryNodes = new ArrayList<DiscoveryNode>(2);
                Address address = new Address("127.0.0.1", 50001);
                discoveryNodes.add(new SimpleDiscoveryNode(address));
                address = new Address("127.0.0.1", 50002);
                discoveryNodes.add(new SimpleDiscoveryNode(address));
                return discoveryNodes;
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        @Override
        public void destroy() {
        }
    }

    public static class TestDiscoveryStrategyFactory implements DiscoveryStrategyFactory {

        public TestDiscoveryStrategyFactory() {
        }

        @Override
        public Class<? extends DiscoveryStrategy> getDiscoveryStrategyType() {
            return TestDiscoveryStrategy.class;
        }

        @Override
        public DiscoveryStrategy newDiscoveryStrategy(DiscoveryNode discoveryNode, ILogger logger,
                                                      Map<String, Comparable> properties) {
            return new TestDiscoveryStrategy();
        }

        @Override
        public Collection<PropertyDefinition> getConfigurationProperties() {
            return Collections.<PropertyDefinition>emptyList();
        }
    }
}
```

**Comment by simon-temple** [comment]
Hi kobalski
I've performed a few more tests running two JVM instances on the same host using ports 50001 and 50002.  I'm still getting the same issue.

It's going to be difficult for me to share my code with you.  However I have noticed a couple of behavioural difference between my implementation and your test case...

You should modify you discoverNodes() to read address values from an external text file.  Only update this file once your node(s) are running.  This will ensure the discovery of nodes added or removed is performed some time after the node is started.  To ensure discoverNodes() is called more frequently I set these config values:

config.setProperty( "hazelcast.merge.first.run.delay.seconds", "15" );
config.setProperty( "hazelcast.merge.next.run.delay.seconds", "45" );

To test, simply add entries to the external file when you start nodes and remove entries from the file when you stop them.  It should not be long before you start to see:
2016-03-17 09:39:12,696 INFO  [com.hazelcast.logging.Log4jFactory$Log4jLogger] (cached8) [192.168.1.147]:50001 [dev] [3.6] Address[192.168.1.147]:50002 should merge to this node , because : node.getThisAddress().hashCode() < joinMessage.address.hashCode() , this node data member count: 1 (Log4jFactory.java:50)

One other difference is that I run with host IP addresses not loopback addresses: InetAddress.getLocalHost().getHostAddress().  Don't add the 127.0.0.1 interface... use default behaviour and don't specify interfaces.

**Comment by mdogan** [comment]
@simon-temple: Do you still have issues with using Discovery SPI? If yes, please reopen the issue and share your implementation with us to inspect.
