### ISSUE TITLE
Instance name should not be overriden while creating cache manager from specified config file

### ISSUE THREAD

**Issue by serkan-ozal** [hazelcast/hazelcast#7567]
Currently, while creating `CacheManager` backed by custom hazelcast instance from given config file, regardless from instance name is specified or not in the config file, instance name is set as config url but when there is specified instance name in the config file, that instance name should be used instead of config url.

Also, it would be better to specify instance name via `(HazelcastCachingProvider.HAZELCAST_INSTANCE_NAME` property when instance config is taken from specified config file via `HazelcastCachingProvider.HAZELCAST_CONFIG_LOCATION`.

**Comment by toanil01** [comment]
Hello,

I recently upgraded my jars from hazelcast-3.6.2 to hazelcast-3.12.11. with this configuration i'm getting the org.hibernate.cache.CacheException: No instance with name [hcinstance] could be found.

where i given entry in hibernate-cfg.xml at the time sessionFactory creation 
<property name="hibernate.cache.hazelcast.instance_name">hcinstance</property>

If i remove the <property name="hibernate.cache.hazelcast.instance_name">hcinstance</property> tag from the hibernate.cfg.xml file and added <instance-name>hcinstace</instace-name> in the hazelcast.xml file i'm getting Caused by: com.hazelcast.core.DuplicateInstanceNameException: HazelcastInstance with name 'hcinstance' already exists! error.

if i remove the <instacne-name> property from the both the places, able to get the hazelcast intance but i can see the more members are joining by comparing the old env.

please suggest

this is my hazelcast.xml
---------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.hazelcast.com/schema/config
                               http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd"
           xmlns="http://www.hazelcast.com/schema/config">

    <group>
        <name>hchibernate</name>
        <password>password</password>
    </group>
	<license-key>XXXXXX</license-key>
    <management-center enabled="true">http://localhost:9080/mancenter</management-center>
	<instance-name>hcinstance</instance-name>
    <network>
        <port auto-increment="true" port-count="100">5701</port>
        <outbound-ports>
            <ports>0</ports>
        </outbound-ports>
		
        <join>
			<multicast enabled="false"></multicast>
            
            <tcp-ip enabled="true">
                <members>localhost</members>
            </tcp-ip>
        </join>
        <interfaces enabled="false">
            <interface>10.40.0.104</interface>
            <interface>10.92.0.95</interface>
        </interfaces>
        <ssl enabled="false"/>
        <socket-interceptor enabled="false"/>
        <symmetric-encryption enabled="false">
            <algorithm>PBEWithMD5AndDES</algorithm>
            <salt>thesalt</salt>
            <password>thepass</password>
            <iteration-count>19</iteration-count>
        </symmetric-encryption>
    </network>

    <partition-group enabled="false"/>

    <executor-service name="default">
        <pool-size>16</pool-size>
        <queue-capacity>0</queue-capacity>
    </executor-service>

    <queue name="default">
        <max-size>0</max-size>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
        <empty-queue-ttl>-1</empty-queue-ttl>
    </queue>

    
    <map name="default">
        <in-memory-format>BINARY</in-memory-format>
        <backup-count>1</backup-count>
        <read-backup-data>false</read-backup-data>
        <async-backup-count>0</async-backup-count>
        <time-to-live-seconds>750</time-to-live-seconds>
        <max-idle-seconds>750</max-idle-seconds>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="PER_NODE">100000</max-size>
        <eviction-percentage>25</eviction-percentage>
        
        
    </map>

    <multimap name="default">
        <backup-count>1</backup-count>
        <value-collection-type>SET</value-collection-type>
    </multimap>

    <multimap name="default">
        <backup-count>1</backup-count>
        <value-collection-type>SET</value-collection-type>
    </multimap>

    <list name="default">
        <backup-count>1</backup-count>
    </list>

    <set name="default">
        <backup-count>1</backup-count>
    </set>

    <jobtracker name="default">
        <max-thread-size>0</max-thread-size>
        
        <queue-size>0</queue-size>
        <retry-count>0</retry-count>
        <chunk-size>1000</chunk-size>
        <communicate-stats>true</communicate-stats>
        <topology-changed-strategy>CANCEL_RUNNING_OPERATION</topology-changed-strategy>
    </jobtracker>

    <semaphore name="default">
        <initial-permits>0</initial-permits>
        <backup-count>1</backup-count>
        <async-backup-count>0</async-backup-count>
    </semaphore>

    <serialization>
        <portable-version>0</portable-version>
    </serialization>

    <services enable-defaults="true"/>
</hazelcast>

hibernate-cfg-xml
--------------------------------------------
<session-factory>

		
		<property name="connection.datasource">jdbc/pay</property>
		<property name="dialect">org.hibernate.dialect.DB2Dialect</property>
		<property name="show_sql">false</property>
		<property name="use_outer_join">false</property>
		<property name="transaction.manager_lookup_class">org.hibernate.transaction.WebSphereExtendedJTATransactionLookup</property>
		<property name="hibernate.transaction.factory_class">org.hibernate.transaction.CMTTransactionFactory</property>

		<property name="hibernate.transaction.flush_before_completion">true</property>
		<property name="hibernate.transaction.auto_close_session">true</property>
		<property name="hibernate.jdbc.use_scrollable_resultset">true</property>

		
		<property name="hibernate.cache.use_second_level_cache">true</property>
		<property name="hibernate.cache.use_query_cache">true</property>
		<property name="hibernate.cache.region.factory_class">com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory</property>
		<property name="hibernate.cache.hazelcast.use_native_client">false</property>
		<property name="hibernate.cache.hazelcast.instance_name">hcinstance</property>
		<property name="hibernate.cache.hazelcast.shutdown_on_session_factory_close">true</property>
		
		<property name="hibernate.generate_statistics">false</property>
