### ISSUE TITLE
Aggregation stuck on failure (because of infinite timeout of AbstractCompletableFuture)

### ISSUE THREAD

**Issue by Exricel** [hazelcast/hazelcast#7569]
For quite a while I am having the error during aggregation. (since 3.5.4, and now in 3.6 it still persist)

Scenario:
1) 2 members ('Member A', 'Member B') are executing.
2) 'Member-A' calls IMap.aggregate and at the same moment 'Member-B' is going down(taskkill).

3) The thread which called aggregation on Member A will wait forever (because AbstractCompletableFuture has get(Long.MAX_VALUE, TimeUnit.MILLISECONDS))

From the thread dump.

"1217@c3p0.task-executor-0@8467" prio=5 tid=0x51 nid=NA waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:230)
      at com.hazelcast.spi.impl.AbstractCompletableFuture.get(AbstractCompletableFuture.java:191)
      at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:757)
      at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:731)
...

I even tried to use lease locks (from 3.6) to to deal with such behavior. But it's not working.

And this issue may be related https://github.com/hazelcast/hazelcast/issues/5916.

---

java: jdk1.7.0_80
hazelcast versions: 3.5.4, 3.5.5; 3.6.
cluster size: 2-5 members
OS: Windows 7

**Comment by tombujok** [comment]
Thx for reporing @Exricel 
It would help me a lot to analyse it sooner if you submitted a gist with a short test case that would enable reproducing the problem (without killing the second node etc.)

**Comment by Exricel** [comment]
It's hard to reproduce because of timing, but to understand behavior it may be better to check ignored tests from this commit https://github.com/hazelcast/hazelcast/commit/bc74c4689d8d16cf8e7f23ea69585ad6ed6bbc50.

From class:
 hazelcast/src/test/java/com/hazelcast/mapreduce/MapReduceTest.java

public void testKeyedMapperCollator()
public void testKeyPredicateMapperCollator()

The logic is the same, but issue (#5916) was issued only as bug for Client. 
Although it's exist also in the core.

**Comment by bwzhang2011** [comment]
@tombujok, any update with such issue ?

**Comment by mdogan** [comment]
MapReduce framework and aggregation over MapReduce are deprecated since 3.8. `IMap` has now better and more efficient aggregation built-on its query engine. 

```java
   /**
     * Applies the aggregation logic on all map entries and returns the result
     * <p>
     * Fast-Aggregations are the successor of the Map-Reduce Aggregators.
     * They are equivalent to the Map-Reduce Aggregators in most of the use-cases, but instead of running on the Map-Reduce
     * engine they run on the Query infrastructure. Their performance is tens to hundreds times better due to the fact
     * that they run in parallel for each partition and are highly optimized for speed and low memory consumption.
     *
     * @param aggregator aggregator to aggregate the entries with
     * @param <R>        type of the result
     * @return the result of the given type
     * @since 3.8
     */
    <R> R aggregate(Aggregator<Map.Entry<K, V>, R> aggregator);

    /**
     * Applies the aggregation logic on map entries filtered with the Predicated and returns the result
     * <p>
     * Fast-Aggregations are the successor of the Map-Reduce Aggregators.
     * They are equivalent to the Map-Reduce Aggregators in most of the use-cases, but instead of running on the Map-Reduce
     * engine they run on the Query infrastructure. Their performance is tens to hundreds times better due to the fact
     * that they run in parallel for each partition and are highly optimized for speed and low memory consumption.
     *
     * @param aggregator aggregator to aggregate the entries with
     * @param predicate  predicate to filter the entries with
     * @param <R>        type of the result
     * @return the result of the given type
     * @since 3.8
     */
    <R> R aggregate(Aggregator<Map.Entry<K, V>, R> aggregator, Predicate<K, V> predicate);
```

See http://docs.hazelcast.org/docs/3.8.2/manual/html-single/index.html#fast-aggregations

Please try the new aggregation api and feel free to reopen issue if problem still exists.
