### ISSUE TITLE
Expose HazelcastInstance from Spring's CacheManager

### ISSUE THREAD

**Issue by snicoll** [hazelcast/hazelcast#7571]
#4978 intended to expose the `HazelcastInstance` from `com.hazelcast.spring.cache.HazelcastCacheManager` - unfortunately https://github.com/hazelcast/hazelcast/commit/43092ce22e696c9612a1dd2667f87da59c5418a7 did so on the JSR-107 version. 

This issue is about implementing the original request.

**Comment by serkan-ozal** [comment]
Hi @snicoll 
As I understood, you want us to expose Hazelcast instance through `com.hazelcast.spring.cache.HazelcastCacheManager`, right?

**Comment by snicoll** [comment]
Yes. 

That's what I asked in the other issue and I wasn't aware you had two classes named `HazelcastCacheManager`.
