### ISSUE TITLE
NetworkConfig.setPortCount is not chainable (3.6)

### ISSUE THREAD

**Issue by phax** [hazelcast/hazelcast#7595]
Please make `NetworkConfig.setPortCount" to`return this`

**Comment by jerrinot** [comment]
Hi @phax,

thanks for you suggestion. This is a good catch, the method should indeed return `this`! 

It's tricky to change it now as the return type is a part of method signature (on byte-code level) and adding a return type would break binary compatibility.

**Comment by mmedenjak** [comment]
Closing in favour of https://github.com/hazelcast/hazelcast/issues/11669
