### ISSUE TITLE
Hazelcast Distributed executor not working in Tomee container

### ISSUE THREAD

**Issue by kmpraveen09** [hazelcast/hazelcast#7636]
Tomee has Hazelcast jar in it's library. I am working with Hazelcast 3.5 version. The application is deployed in multiple tomee instances and Hazelcast cluster has formed successfully. However when i tried distributed executor to execute the task on other JVM, the task executed successfully on other JVM but the control is not coming back to the source JVM. Finally the Future task timeouts and returns null. Other Hazelcast features (distributed map, cluster formation etc.) are working fine except distributed executor. I have used same version of Hazelcast in pom.xml with scope provided. 
Surprising behavior is - deleting the Hazelcast jar from Tomee library and including explicit dependency on Hazelcast jar of same version (3.5) in the application is working fine. Not able to comprehend this behavior. Please investigate and let us know the solution and root cause.

**Comment by jerrinot** [comment]
Hi @kmpraveen09, this is quite tricky scenario to help with. Do you have any logs? Could you enable DEBUG logging and reproduce it? If Hazelcast on its own is working fine then it seems like an issue in Tomee integration. Have you tried to contact Tomee guys?

**Comment by kmpraveen09** [comment]
Thanks for your response. Unfortunately there are no logs. The issue happens always. The control leaves the callable task on the other JVM as we got the log of the last statement execution. After that we don't see any logs in the application. Only source JVM has error logs after timeout. Whether tomee intervenes in distributed executor flow execution?

**Comment by kmpraveen09** [comment]
Got some clue. Looks like an issue with serialization. Request got deserialized and processed at the other JVM. While serializing the response, issue occurs.  What is the role of container at this point ? In the context of this issue, how these two aspects differ - hazelcast jar provided by the container at run-time and hazelcast jar packaged in the application ? Can you help investigate in this direction?

**Comment by kmpraveen09** [comment]
Appreciate any input regarding the pointers given.

**Comment by noctarius** [comment]
Can you please link to the TomEE issue (as your above link is unfortunately to this issue :-))

**Comment by kmpraveen09** [comment]
https://issues.apache.org/jira/browse/TOMEE-1723

**Comment by wildnez** [comment]
@kmpraveen09: we are trying to reproduce this issue at our end. Can you share a sample application that can help us speed up identifying the problem?

**Comment by wildnez** [comment]
@kmpraveen09 do you still have plans to share the reproducible use case with us or are you okay with the suggested solution of defining class loader through Hazelcast API?

**Comment by kmpraveen09** [comment]
Thanks for suggesting the solution. The issue has been resolved by setting the class loader in the config so that container classloader won't be used. We can use config.setClassLoader(getClass().getClassLoader()) 
or config.setClassLoader(Thread.currentThread().getContextClassLoader()) if config is set in static method.

**Comment by mesutcelik** [comment]
Thanks @kmpraveen09 , 
Excellent to hear that is resolved. We will update the documentation with this info.
