### ISSUE TITLE
Documentation issue with hazelcast.discovery.enabled

### ISSUE THREAD

**Issue by bitsofinfo** [hazelcast/hazelcast#7657]
The documentation at http://docs.hazelcast.org/docs/3.6/manual/html-single/ states in numerous places for tcp/multicast/aws/SPI discovery, statements like the following which say this should be TRUE

```
 <properties>
    <property name="hazelcast.discovery.enabled">true</property>
  </properties>
```

However if you have a config (such as I do) that is setup like this:

```
<properties>
   <property name="hazelcast.discovery.enabled">true</property>
        .....
</properties>

<join>
            <multicast enabled="false">
                <multicast-group>224.2.2.3</multicast-group>
                <multicast-port>55002</multicast-port>
            </multicast> 
            <tcp-ip enabled="true">
                <member>127.0.0.1:5701</interface>
                <member>127.0.0.1:5702</interface>
            </tcp-ip>
            <aws enabled="false"/>       
             <discovery-strategies>
        
               <discovery-strategy enabled="false"
                   class="org.bitsofinfo.hazelcast.discovery.consul.ConsulDiscoveryStrategy">

              ....
                 </properties>
               </discovery-strategy>
             </discovery-strategies>
                 
        </join>
```

Despite having `tcp-ip` enabled = TRUE, and the discovery strategy = FALSE.... the `AbstractJoiner` selected will **never** be the `TcpIpJoiner` but always the `DiscoveryJoiner` (returning zero nodes/members). 

The same applies for multicast = TRUE. It doesn't work if `hazelcast.discovery.enabled=true`  (as per the docs in the "Discovering Members by Multicast" section)

Burned a lot of hours trying to figure this out. I suspect the documentation has a simple copy-paste error. But the larger question is why even have a `hazelcast.discovery.enabled` property at all. Just respect the `enabled` attrs in the config for the various discovery mechanisms, whether they be legacy ones or the new SPI ones.

**Comment by Serdaro** [comment]
You are right @bitsofinfo , it has been corrected. It will be placed with the upcoming development docs upload this weekend.

Please have a look at http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#discovery-spi for more information on the discovery strategy concept.

**Comment by Serdaro** [comment]
Closing now.
