### ISSUE TITLE
[query] Iterator instead Collection for predicate results

### ISSUE THREAD

**Issue by publicocean0** [hazelcast/hazelcast#7675]
I advice to replace Set with Iterator .... for huge Map :) 
IMap<String, Employee> map = hazelcastInstance.getMap( "employee" );

EntryObject e = new PredicateBuilder().getEntryObject();
Predicate predicate = e.is( "active" ).and( e.get( "age" ).lessThan( 30 ) );

Set<Employee> employees = map.values( predicate );

**Comment by mmedenjak** [comment]
@publicocean0 you can use a `PagingPredicate` to page through results. There's also a map partition iterator which is private API but would give you better performance coming in 3.9. It is possible that we expose it as public API as well.
Can you upgrade to a newer version or try the paging predicate?

**Comment by publicocean0** [comment]
Maybe but not i m working in another project.... i can make a attempt in 1-2 months

**Comment by mmedenjak** [comment]
Closing this for now. Please try out the suggested solutions and open a new issue if you are encountering other issues.
