### ISSUE TITLE
Map events on Hazelcast client

### ISSUE THREAD

**Issue by manishonline** [hazelcast/hazelcast#7680]
Hi,

Can a hazelcast java client listen to events on a Map?

```     
        GroupConfig groupConfig = new GroupConfig("cas3sit","dev-pass");
        ClientConfig clientConfig =  new ClientConfig();
        clientConfig.setGroupConfig(groupConfig);
        ClientNetworkConfig clientNetworkConfig = new ClientNetworkConfig();
        clientNetworkConfig.setAddresses(Lists.newArrayList("127.0.0.1:7701"));
        clientConfig.setNetworkConfig(clientNetworkConfig);
        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        final IMap iMap = client.getMap("trades");
        iMap.addEntryListener(new EntryAddedListener(){
            
            @Override
            public void entryAdded(EntryEvent event) {
                System.out.println("Trade::: "+Thread.currentThread().getName()+ event.getKey()+","+event.getValue());
            }
        },true); 
```

Above is my code to listen for events.

If I insert in the map trades, then events are getting called but no when some insertion is there in remote map.

Is there some issue with the configuration or hazelcast clients can't listen to events in remote map?

**Comment by sancar** [comment]
This listener gets any event triggered by either clients or  servers on same map. 
Here is a sample code that works.
```
        HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        final CountDownLatch countDownLatch = new CountDownLatch(1);
        IMap<Integer, Integer> map = client.getMap("trades");
        map.addEntryListener(new EntryAddedListener() {
            public void entryAdded(EntryEvent event) {
                countDownLatch.countDown();
                System.out.println(event);
            }
        }, true);

        instance.getMap("trades").put(1, 1);
        if (countDownLatch.await(20, TimeUnit.SECONDS)) {
            System.out.println("SUCCESS");
        } else {
            System.out.println("FAIL");
        }
```

**Comment by manishonline** [comment]
Here is my code. I don't think I am doing anything drastically different from what your have done above.

`
                       {

        GroupConfig groupConfig = new GroupConfig("cas3sit","dev-pass");
        ClientConfig clientConfig =  new ClientConfig();
        clientConfig.setGroupConfig(groupConfig);
        ClientNetworkConfig clientNetworkConfig = new ClientNetworkConfig();
        clientNetworkConfig.setAddresses(Lists.newArrayList("127.0.0.1:7701"));
        clientConfig.setNetworkConfig(clientNetworkConfig);
        //clientConfig.addAddress("127.0.0.1:7701");
        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        final IMap tradeCache = client.getMap("trades");
        tradeCache.clear();
        tradeCache.addEntryListener(new EntryAddedListener(){

            @Override
            public void entryAdded(EntryEvent event) {
                System.out.println(Thread.currentThread().getName()+" Trade::: "+ event.getKey()+","+event.getValue());
                System.out.println("TradeCache size :: "+tradeCache.size());
            }
        },true);
        ExecutorService executorService = Executors.newSingleThreadExecutor();

        executorService.submit(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i< 20;i++){
                    //tradeCache.put("TradeString"+i,i);
                    System.out.println(Thread.currentThread().getName()+" Iteration "+i+" TradeCache size "+tradeCache.size());
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        });
       
        try {
            Thread.currentThread().join();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }`



Here is the output. You can see size of trade cache jumping from 0 to 3 but System.out in MapListener not being called
`

pool-4-thread-1 Iteration 1 TradeCache size 0
pool-4-thread-1 Iteration 2 TradeCache size 0
pool-4-thread-1 Iteration 3 TradeCache size 0
pool-4-thread-1 Iteration 4 TradeCache size 0
pool-4-thread-1 Iteration 5 TradeCache size 0
pool-4-thread-1 Iteration 6 TradeCache size 3
pool-4-thread-1 Iteration 7 TradeCache size 3
pool-4-thread-1 Iteration 8 TradeCache size 3
pool-4-thread-1 Iteration 9 TradeCache size 3
pool-4-thread-1 Iteration 10 TradeCache size 3
pool-4-thread-1 Iteration 11 TradeCache size 3
pool-4-thread-1 Iteration 12 TradeCache size 3
pool-4-thread-1 Iteration 13 TradeCache size 3
pool-4-thread-1 Iteration 14 TradeCache size 3
pool-4-thread-1 Iteration 15 TradeCache size 3
pool-4-thread-1 Iteration 16 TradeCache size 3
pool-4-thread-1 Iteration 17 TradeCache size 3
pool-4-thread-1 Iteration 18 TradeCache size 3
pool-4-thread-1 Iteration 19 TradeCache size 3



`

**Comment by sancar** [comment]
Where is the server, what it is doing in the mean time? Should I think the line uncommented ?

`//tradeCache.put("TradeString"+i,i);`

**Comment by manishonline** [comment]
Server is running on the same machine but different jvm at Port 7701. While
client is waiting, the server is calculating some trades and putting
results into trades cache.

If I uncomment below line i.e. put some entries into trades cache from the
client JVM then Event is fired.

Not when entries are being put by the server process.

On Monday, March 7, 2016, mustafa sancar koyunlu <notifications@github.com>
wrote:

> Where is the server, what it is doing in the mean time? Should I think the
> line uncommented ?
>
> //tradeCache.put("TradeString"+i,i);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/7680#issuecomment-193311692>
> .
>


-- 
Sent from MetroMail

**Comment by sancar** [comment]
What  is the version of hazelcast ?

**Comment by manishonline** [comment]
Client on 3.5.4

Server on 3.5.3

On Tuesday, March 8, 2016, mustafa sancar koyunlu <notifications@github.com>
wrote:

> What is the version of hazelcast ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/7680#issuecomment-193321090>
> .
>


-- 
Sent from MetroMail

**Comment by gurbuzali** [comment]
Here is the test:
```
 public void test() throws Exception {
        final HazelcastInstance instance = Hazelcast.newHazelcastInstance();
        new Thread() {
            @Override
            public void run() {

                IMap<Object, Object> trades = instance.getMap("trades");
                for (int i = 0; i < 1000; i++) {
                    trades.put(i, i);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }.start();

        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        final IMap tradeCache = client.getMap("trades");
        tradeCache.clear();
        tradeCache.addEntryListener(new EntryAddedListener() {

            @Override
            public void entryAdded(EntryEvent event) {
                System.out.println(Thread.currentThread().getName() + " Trade::: " + event.getKey() + "," + event.getValue());
                System.out.println("TradeCache size :: " + tradeCache.size());
            }
        }, true);

        new Thread() {
            @Override
            public void run() {
                for (int i = 0; i < 20; i++) {
                    //tradeCache.put("TradeString"+i,i);
                    System.out.println(Thread.currentThread().getName() + " Iteration " + i + " TradeCache size " + tradeCache.size());
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }.start();
    }
```

And the output:
```
Thread-2 Iteration 0 TradeCache size 0
hz.client_0.event-7 Trade::: 1,1
TradeCache size :: 1
Thread-2 Iteration 1 TradeCache size 1
hz.client_0.event-6 Trade::: 2,2
TradeCache size :: 2
Thread-2 Iteration 2 TradeCache size 2
hz.client_0.event-8 Trade::: 3,3
TradeCache size :: 3
Thread-2 Iteration 3 TradeCache size 3
hz.client_0.event-10 Trade::: 4,4
TradeCache size :: 4
Thread-2 Iteration 4 TradeCache size 4
hz.client_0.event-10 Trade::: 5,5
TradeCache size :: 5
Thread-2 Iteration 5 TradeCache size 5
hz.client_0.event-8 Trade::: 6,6
TradeCache size :: 6
Thread-2 Iteration 6 TradeCache size 6
hz.client_0.event-10 Trade::: 7,7
TradeCache size :: 7
Thread-2 Iteration 7 TradeCache size 7
hz.client_0.event-10 Trade::: 8,8
TradeCache size :: 8
Thread-2 Iteration 8 TradeCache size 8
hz.client_0.event-8 Trade::: 9,9
TradeCache size :: 9
Thread-2 Iteration 9 TradeCache size 9
hz.client_0.event-6 Trade::: 10,10
TradeCache size :: 10
Thread-2 Iteration 10 TradeCache size 10
hz.client_0.event-10 Trade::: 11,11
TradeCache size :: 11
```
