### ISSUE TITLE
IMap TTL eviction delay 

### ISSUE THREAD

**Issue by magiccrafter** [hazelcast/hazelcast#7722]
Hi all, 

I have an IMap with the following configurations:
mapConfig.setName("sessions");
**mapConfig.setEvictionPolicy(EvictionPolicy.NONE);**
mapConfig.setInMemoryFormat(InMemoryFormat.OBJECT);
mapConfig.setBackupCount(1);
**mapConfig.setTimeToLiveSeconds(5);**

Hazelcast version used: 3.5.5
The entries of the map are not evicted at the specified time (5sec) but a couple of seconds later. If there are a lot of entries this time randomly increases/decreases. I checked the issues and found out this: https://github.com/hazelcast/hazelcast/issues/6118 which works but only if I workaround it by changing the EvictionPolicy to LRU one. 

After the change the configuration is:
mapConfig.setName("sessions");
**mapConfig.setEvictionPolicy(EvictionPolicy.LRU);**
mapConfig.setInMemoryFormat(InMemoryFormat.OBJECT);
mapConfig.setBackupCount(1);
**mapConfig.setTimeToLiveSeconds(5);**

and 

then explicit call map's **get()** method to trigger the eviction. That works and is pretty sharp.

To reproduce the issue check this gist:
https://gist.github.com/magiccrafter/3493be64ddd7dca78dfb

Thanks and regards,
Nasko

**Comment by ahmetmircik** [comment]
Hi @magiccrafter,

TTL expiration can occur in two ways:
 - By explicitly calling  `IMap#get` on key (entry is immediately removed from IMap)
 - With the help of a background sweeper task (entries will be removed gradually from IMap, not needs  
   an explicit touch)

I use your gist and slightly changed it to print the map#size, size decreases in time means expired entries   are removed from IMap, please see this [gist](https://gist.github.com/ahmetmircik/0b9d68bb859aedb33929)

**Comment by magiccrafter** [comment]
Hi @ahmetmircik 

Thanks for the fast response. I am aware of the sweeper task which was introduced for performance reasons and scalability. When I try to explicitly get on a key the time is not sharper and the entry is not getting evicted immediately at least in my tests. I've updated the [gist](https://gist.github.com/magiccrafter/3493be64ddd7dca78dfb) with more statistics. If I manually do check and evict it is sharp and predictable. I just wonder if I can rely on hazelcast to do this the same predictable way. Please check the gist. I've added both: the manual eviction and the one with get().

Thanks

**Comment by ahmetmircik** [comment]
Hi @magiccrafter, 

We added three system parameters to control (speed up/slow down) expiration process by starting version 3.7.1. Although these are internal parameters and subject to change, you can use them to control expirations.
`hazelcast.internal.map.expiration.task.period.seconds`
`hazelcast.internal.map.expiration.cleanup.percentage`
`hazelcast.internal.map.expiration.cleanup.operation.count`

I'm closing this issue, thanks.
