### ISSUE TITLE
Id like to be able to provide a TTL on entries when loading via the MapLoader

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast#7728]
See https://groups.google.com/forum/#!topic/hazelcast/j27QsD3GdDc for discussion

**Comment by sertugkaya** [comment]
We got another customer request for this enhancement today. FYI.

**Comment by bacsog** [comment]
+1

**Comment by vertex-github** [comment]
This could also be used by another customer - use case is to cache null values from the DB in order to reduce hits on the DB. TTL added to the "null" value within IMap would allow significant reduction in DB hits

**Comment by vertex-github** [comment]
And another potential use case by another customer. :-)

**Comment by CharanPai** [comment]
This feature would be helpful for us too:
We too have the necessity to set TTL while loading from DB

**Comment by hiyelbaz** [comment]
+1

**Comment by mfaghloumi** [comment]
+1

**Comment by mmedenjak** [comment]
This is now available in Hazelcast 4.0. Please see https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#loading-and-storing-persistent-data and the `com.hazelcast.map.EntryLoader` and `com.hazelcast.map.EntryStore` interfaces.

**Comment by vertex-github** [comment]
Woohoo! Thanks!
