### ISSUE TITLE
Documentation: Incorrect default number of operations threads

### ISSUE THREAD

**Issue by johmag** [hazelcast/hazelcast#7741]
Under the section "Operation Threading" it states that the default number of partition-aware operation threads is (2 x number of cores). However, when looking at the code and observing the actual number of threads created runtime is seems like the default value is instead (1 x number of cores).

**Comment by jerrinot** [comment]
hi @johmag: good finding, thanks for reporting it!

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/c1518265d4266ff8abf803116a4b746dae65329f.
