### ISSUE TITLE
Better separator for local-remote parts of exceptions

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#7744]
We use this separator when rewriting a stacktrace of exceptions:

`private static final String EXCEPTION_SEPARATOR = "------ End remote and begin local stack-trace ------";`

see: https://github.com/jerrinot/hazelcast/blob/eef987b9920f3f7b4c506e433b0d067cab9ba93c/hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java#L31-L31

I always have to think hard to tell what part of the stacktrace is the local part and what is the remote part. The separator could indicate it. Something along this: ` ------ End remote stack-trace. Local stack-trace follows bellow ---`

**Comment by pveentjer** [comment]
Fixed in this pr:

https://github.com/hazelcast/hazelcast/pull/7761
