### ISSUE TITLE
Logging settings via ClientConfig

### ISSUE THREAD

**Issue by pschmeltzer** [hazelcast/hazelcast#7764]
Reference:
http://stackoverflow.com/questions/35902586/hazelcast-exception-in-logging/

`ClientConfig#setProperty("hazelcast.logging.type", "log4j")` does not appear to work

Setting via system property however works properly. E.g. -Dhazelcast.logging.type=slf4j 
I'm not sure exactly the state of the client instance without setting the system property as it was throwing a strange message formatting exception inside log4j

**Comment by oguzdemir** [comment]
Thanks for reporting this issue, I reproduced this behaviour. I am working for solving this issue.
