### ISSUE TITLE
typing mistake in documentatoin for 3.6.1; chapter 6 "Ringuffer"

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7770]
Documentation for 3.6.1 has a typing mistake Ringuffer: on page 49.
The correct name of a data type is Ringbuffer.

**Comment by Donnerbart** [comment]
Thanks for the report, I've created a PR to fix this.

**Comment by yilativs** [comment]
You are welcome!
PS http://docs.hazelcast.org/docs/3.6/manual/pdf/hazelcast-documentation-3.6.pdf link on page http://hazelcast.org/documentation/ is dead

**Comment by Donnerbart** [comment]
Thanks again, I gave our web-team a shout!

**Comment by yilativs** [comment]
You are welcome. Tomorrow will send a suggestion on how to improve your Docker image ;-)
