### ISSUE TITLE
[map] [wan] MapLoader events

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#7771]
`MapLoader.load()` does not create an entry event, as it is essentially a `get()`.
`MapLoader.loadAll()` uses `IMap.putTransient()` and so generates EntryAdded events.

This is inconsistent, and the latter is problematic for WAN replicated clusters.

**Comment by ahmetmircik** [comment]
related issue: https://github.com/hazelcast/hazelcast/issues/1542

**Comment by vertex-github** [comment]
If we could get an option to disable the WAN replication of `loadAll` events it would be great

**Comment by burakcelebi** [comment]
Closed as internal request
