### ISSUE TITLE
QueueStore JavaDoc is not accurate, needs enhancement

### ISSUE THREAD

**Issue by gurbuzali** [hazelcast/hazelcast#7775]

**Comment by mdogan** [comment]
@gurbuzali: What's not accurate? Are you going to enhance it?

**Comment by gurbuzali** [comment]
First of all it is a copy/paste version of MapStore, secondly we should mention that we use iteration order of set returned by `loadAllKeys` method while populating the queue from store.

**Comment by tombujok** [comment]
@gurbuzali I quickly came up with sth like this #8603. Plz have a look if it's any better for you.
