### ISSUE TITLE
MapReduceTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7783]
```
04:26:41 Running com.hazelcast.mapreduce.MapReduceTest
07:04:17 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/854/console

**Comment by Donnerbart** [comment]
`com.hazelcast.mapreduce.MapReduceTest.testMapperReducerChunked`

**Error Message**
test timed out after 60000 milliseconds

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:485)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:187)
	at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:321)
	at com.hazelcast.map.impl.proxy.MapProxySupport.putInternal(MapProxySupport.java:292)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:105)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:95)
	at com.hazelcast.mapreduce.MapReduceTest.testMapperReducerChunked(MapReduceTest.java:490)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/2478/testReport/junit/com.hazelcast.mapreduce/MapReduceTest/testMapperReducerChunked/

**Comment by mesutcelik** [comment]
no recent failure. closing...

**Comment by hasancelik** [comment]
```
04:51:44 Running com.hazelcast.mapreduce.MapReduceTest
08:31:46 Build timed out (after 300 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/967/console
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/278/console
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/967/consoleFull
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/541/console

**Comment by metanet** [comment]
I don't think we have someone working one this. Most probably, it will require major work. Moving milestone to 3.8.

**Comment by hasancelik** [comment]
```
04:52:47 Running com.hazelcast.mapreduce.MapReduceTest
06:56:23 Build timed out (after 240 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/304/console

**Comment by hasancelik** [comment]
```
04:17:17 Running com.hazelcast.mapreduce.MapReduceTest
07:58:43 Build timed out (after 240 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/1011/console

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/671/console

**Comment by jerrinot** [comment]
MapReduce is deprecated in 3.8. Hazelcast JET is a further replacement.
