### ISSUE TITLE
Can't configure an instance of PortableFactory in config hazelcast.xml, but it works when configured programmatically.

### ISSUE THREAD

**Issue by neaflo** [hazelcast/hazelcast#7786]
Hi,

Using 3.6 I have the below in hazelcast-client config, where MyPortableFactory is coming from a shared module.

```
    <serialization>
        <portable-factories>
            <portable-factory factory-id="1">MyPortableFactory</portable-factory>
        </portable-factories>
    </serialization>
```

When I try to put a class which implements Portable in a distributed map I get "Could not find PortableFactory for factory-id: 1". I put println in [writePortable] of this class and I see [writePortable] called twice before the exception triggers. [readPortable] is never called.

However, when I configure the client instance programmatically like below, it works:

```
        ClientConfig clientConfig = new ClientConfig();
        SerializationConfig srzConfig = clientConfig.getSerializationConfig();
        srzConfig.addPortableFactoryClass(1, "MyPortableFactory");
        _hazelcastInstance = HazelcastClient.newHazelcastClient(clientConfig);
```
Is this an issue with the xml configuration for PortableFactory, or I'm doing something wrong?

I have put the same <serialization> element in the nodes and still didn't work. 

Below are the 2 classes used:

```
public class DummyData implements Portable {

    private Long id;
    private String name;

    public DummyData() {
    }

    public DummyData(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    @Override
    public int getFactoryId() {
        return MyPortableFactory.FACTORY_ID;
    }

    @Override
    public int getClassId() {
        return MyPortableFactory.CLASS_ID_DUMMYDATA;
    }

    @Override
    public void writePortable(PortableWriter writer) throws IOException {

        System.out.println("Serialize");

        writer.writeLong("id", id);
        writer.writeUTF( "name", name );
    }

    @Override
    public void readPortable(PortableReader reader) throws IOException {

        System.out.println("Deserialize");

        id = reader.readLong("id");
        name = reader.readUTF("name");
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public class MyPortableFactory implements PortableFactory {

    public final static int CLASS_ID_DUMMYDATA = 1;

    public final static int FACTORY_ID = 1;

    @Override
    public Portable create(int classId) {

        switch (classId) {
            case CLASS_ID_DUMMYDATA:
                return new DummyData();
            default:
                return null;
        }
    }
}
```

**Comment by jerrinot** [comment]
Hi @neaflo,

How do you create your client `HazelcastInstance`? Do you use `HazelcastClient.newHazelcastClient();` (=the argument-less factory method) or `HazelcastClient.newHazelcastClient(clientConfig);` ?

I believe the XML config is ignored when you are using programmatic configuration.

**Comment by neaflo** [comment]
Hi @jerrinot ,

I'm not trying to mix them. I do HazelcastClient.newHazelcastClient(clientConfig); when loading the config programmatically and HazelcastClient.newHazelcastClient(); when loading it from XML config.

**Comment by jerrinot** [comment]
@neaflo: that's interesting. 

Do you have any other setting in the `hazelcast-client.xml` file? What if you change the `MyPortableFactory` to a non-existing class. Is the client still starting? 

I tried to reproduce it and everything is working as expected on my side thus I assume you XML config is  ignored for some reason.

**Comment by neaflo** [comment]
Thanks for the hint, just done a quick test with a non-existing class and the client was still running apparently. And realized that you used "hazelcast-client.xml" as the config file and actually this was the issue - my xml file was named "hazelcast.xml". Thanks, it's sorted!

**Comment by jerrinot** [comment]
@neaflo: I am very glad to hear it. Happy Hazelcasting!
