### ISSUE TITLE
[documentaiton for 3.6.1] bug If globalOrderEnabled is disabled, messages are ordered

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7794]
Section : Ordering Messages as Published
The documentation for 3.6.1 has the following phrase: "If globalOrderEnabled is **disabled**, messages are **ordered**"

The correct version should be "If globalOrderEnabled is **disabled**, messages are **not ordered**".

**Comment by Serdaro** [comment]
Thank you @yilativs . Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/8f5915e483e2416e2551b79fac88d3eaca7f0340

**Comment by yilativs** [comment]
You are welcome @Serdaro Thanks for great documentation, it is a pleasure to help to improve it

**Comment by Serdaro** [comment]
More than welcome :) Really appreciate the help.
