### ISSUE TITLE
[bug in documeneation 3.6.1] wrong example 

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7795]
Section: Ordering Messages as Published

member1 -> c1, **b1**, a2, c2
member2 -> c1, c2, a1, a2

should be replaced with 
member1 -> c1, **a1**, a2, c2
member2 -> c1, c2, a1, a2

**Comment by Serdaro** [comment]
Thank you @yilativs. Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/8f5915e483e2416e2551b79fac88d3eaca7f0340
