### ISSUE TITLE
Can't connect to a existing hazelcast instance from my application

### ISSUE THREAD

**Issue by LeonardoGomesRibeiro** [hazelcast/hazelcast#7858]
Hello!
I am trying to connect to a hazelcast instance from my java application and it seems not to connect to the existing server... Could you guys help me on this? 

I have an application using hibernate and hazelcast that works fine but when I'm running other application that uses spring mvc and jdbc template it is not working well...

Tomcat log: 
`INFO: [LOCAL] [dev] [3.5.1] Prefer IPv4 stack is true.
Mar 28, 2016 10:56:09 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.5.1] Picked Address[192.168.250.170]:5702, using socket ServerSocket[addr=/0.0.0.0,localport=5702], bind any local is true
Mar 28, 2016 10:56:09 AM com.hazelcast.spi.OperationService
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Backpressure is disabled
Mar 28, 2016 10:56:09 AM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Starting with 2 generic operation threads and 4 partition operation threads.
Mar 28, 2016 10:56:10 AM com.hazelcast.system
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Hazelcast 3.5.1 (20150727 - 795ce7d) starting at Address[192.168.250.170]:5702
Mar 28, 2016 10:56:10 AM com.hazelcast.system
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Copyright (c) 2008-2015, Hazelcast, Inc. All Rights Reserved.
Mar 28, 2016 10:56:10 AM com.hazelcast.instance.Node
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Creating MulticastJoiner
Mar 28, 2016 10:56:10 AM com.hazelcast.core.LifecycleService
INFO: [192.168.250.170]:5702 [dev] [3.5.1] Address[192.168.250.170]:5702 is STARTING
Mar 28, 2016 10:56:20 AM com.hazelcast.cluster.impl.MulticastJoiner
INFO: [192.168.250.170]:5702 [dev] [3.5.1] 

Members [1] {
	Member [192.168.250.170]:5702 this
}
`
I've added this to my applicationContext.xml

`<hz:map id="myAppsMap" name="myApplicationsMap" instance-ref="instance-test"/> 
	      <hz:hazelcast id="instance-test" >	  
        <hz:config> 
            <hz:map name="map" read-backup-data="true">
                <hz:map-store enabled="true" write-delay-seconds="60" initial-mode="EAGER"/>
            </hz:map>
        </hz:config>
    </hz:hazelcast>`

and when I open the mancenter I can not see any map entry on it... 

My controller class I'm doing like this: 

`@Autowired
	HazelcastInstance instance;`
and to write and delete from the cache I'm doing like this:
`IMap<Object, Object> hzMap = instance.getMap("default");
if (hzMap.containsKey("key") {
    		.... get the key
    	}
`
My hazelcast.xml has this on it: 

```
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config 3.5.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
 	<name>dev</name> 
        <password>dev_pass</password>
    </group>
    <management-center enabled="true">http://host:9090/mancenter</management-center>
    <network>
        <port auto-increment="true" port-count="100">5701</port>

I'm missing something? Or am I doing something wrong?

Thanks!!

**Comment by mesutcelik** [comment]
Hi @LeonardoGomesRibeiro ,
you should enable management-center property in your applicationContext.xml.

https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.7.xsd#L36

Can you try and let us know the result?

**Comment by LeonardoGomesRibeiro** [comment]
Hi @mesutcelik 
Right now I got the following error: 

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.UnsupportedOperationException: Client cannot access cluster config!

Could you help me?

**Comment by LeonardoGomesRibeiro** [comment]
This error was resolved. I noticed that I was returning a ModelAndView but it is not serializable, so I had to convert it to ModelMap and it worked!

Thanks!

**Comment by mesutcelik** [comment]
you are welcome!
