### ISSUE TITLE
AsyncResponseHandlerTest.whenShutdown

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7864]
```
No interactions wanted here:
-> at com.hazelcast.spi.impl.operationservice.impl.AsyncResponseHandlerTest$3.run(AsyncResponseHandlerTest.java:95)
But found this interaction on mock 'Mock for PacketHandler, hashCode: -1458712034':
-> at com.hazelcast.spi.impl.operationservice.impl.AsyncResponsePacketHandler$ResponseThread.doRun(AsyncResponsePacketHandler.java:112)
Actually, above is the only interaction with this mock.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/173/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/AsyncResponseHandlerTest/whenShutdown/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/439/com.hazelcast$hazelcast/testReport/com.hazelcast.spi.impl.operationservice.impl/AsyncResponseHandlerTest/whenShutdown/

**Comment by hasancelik** [comment]
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK8/com.hazelcast$hazelcast/762/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/AsyncResponseHandlerTest/whenShutdown/

**Comment by jerrinot** [comment]
This test is fragile. It assumes `queue.take()` will throw `InterruptedException`, but there is a race between consumer and the interrupting thread - the exception is not guaranteed to be thrown. I think this is not a bug, it's ok according to the contract of `BlockingQueue`

**Comment by pveentjer** [comment]
Yes. My test is a bit shitty; must be lack of coffee when I wrote it.
