### ISSUE TITLE
Max-size not working correctly

### ISSUE THREAD

**Issue by kuldeep9922** [hazelcast/hazelcast#7868]
Hi, 

I'm working on 2 caches and their configurations are described below.
cache2 works fine and loads only 70 entries out of 166 entries available but cache1 loads 842 entries out of 988 entries however max-size defined is 100. It's showing some random behavior. If I change max-size to 20 then it loads around 759 entries out of 988. 

Please guide me about the possible problem.

Environment:
Spring 3.1.1
Hibernate
hazelcast version 3.4

Cache 1 configuration:
```
 <hz:map name="cache1"
	                backup-count="1"
	                max-size="100"
	               	eviction-percentage="20"
	                eviction-policy="LRU"
	                time-to-live-seconds="1200"
	                read-backup-data="true"
	                merge-policy="com.hazelcast.map.merge.LatestUpdateMapMergePolicy"
	        >
</hz:map>
```

Cache 2 configuration:
```
<hz:map name="cache2"
	                backup-count="1"
	                max-size="70"
	                eviction-percentage="20"
	                eviction-policy="LRU"
	                time-to-live-seconds="1200"
	                read-backup-data="true"
	                merge-policy="com.hazelcast.map.merge.LatestUpdateMapMergePolicy"> 
</hz:map>
```

**Comment by ahmetmircik** [comment]
Hi @kuldeep9922, 

I did not manage to reproduce that by using 3.4. Here is my [test code](https://gist.github.com/ahmetmircik/99f30be4fbdb42dc4c56dc8b32f742f1). 

Can you please send a reproducer?

**Comment by kuldeep9922** [comment]
I didn't add MinEvictionCheckMillis and its working fine as of now but I have some questions. 

1) Even if we don't specify MinEvictionCheckMillis, then why isn't it adding a default value 0 as in max-size-policy. 
2) MinEvictionCheckMillis is for evicting some entries when map is full. How is it related to max-size?

Actually, I can't understand the purpose of using MinEvictionCheckMillis to maintain max-size.
Kindly explain.

**Comment by kuldeep9922** [comment]
Thanks, It worked by setting value of MinEvictionCheckMillis as 0 only.
