### ISSUE TITLE
How to set the cache time with java?

### ISSUE THREAD

**Issue by LeonardoGomesRibeiro** [hazelcast/hazelcast#7891]
Hi,
Is there a way to set the cache of the map using java code?
Right now my code to create a map is like this:  `getInstance().getMap('mycache'); // I noted that when executing this, a namespace entry is created and I can see it on mancenter application`

But I've noted that after some seconds or a minute, the cache is gone :(
Is there a way to set the cache  time for 8 hours?

**Comment by mesutcelik** [comment]
Hi @LeonardoGomesRibeiro ,

I think you should check how to configure eviction policies.
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#evicting-map-entries

please feel free to reopen this issue if you see a problem.

You can always ask your questions to [Hazelcast Google Groups](https://groups.google.com/forum/#!forum/hazelcast). That is the best place to reach out Hazelcast community for Q&A purposes.

Thanks for using Hazelcast...
