### ISSUE TITLE
Make ClassDefinition and FieldDefinition Serializable

### ISSUE THREAD

**Issue by iaptekar** [hazelcast/hazelcast#7918]
If you want to do some check that the objects on a cluster and the client connecting to it are compatible, you will want to pass ClassDefinitions across for comparison. This currently is a problem as the  two classes are not Serializable

**Comment by sancar** [comment]
We have no plan to add this feature. Doing these classes Serializable will cause missusages. Implementing a wrapper Serializable class as workaround is always possible.

**Comment by burakcelebi** [comment]
If you find this useful then please add +1 or please contribute to development via the HEP process.

https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Enhancement+Proposals
