### ISSUE TITLE
Hazelcast multimap configuration question

### ISSUE THREAD

**Issue by philnate** [hazelcast/hazelcast#7924]
I'm somewhat puzzled about what configuration a hazelcast multimap actually support in version 3.5/3.6.
Checking the documentation for version 3.5  (http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#multimap-configuration) I can read there

`Most of the MultiMap configuration elements and attributes have the same names and functionalities explained in the Map Configuration section` pointing to http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#map-configuration

Checking the same for 3.6 I can't find this kind of information.
Looking into the sources (https://github.com/hazelcast/hazelcast/blob/3.5.6/hazelcast/src/main/java/com/hazelcast/config/MultiMapConfig.java) it seems that 3.6 config is right, in terms of that no common map config options are supported for multimap. But the class doesn't seem to differ much/at all for 3.5 either.

So is this information wrong for 3.5, or does multimap in fact support near cache, etc?

**Comment by enesakar** [comment]
sorry for late answer. multimap does not support near cache for now.
