### ISSUE TITLE
[improvement]   an improvement needed for hazelcast-documentation-3.6.1 manual for consistency reasons

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7933]
an improvement needed for  hazelcast-documentation-3.6.1 manual for consistency reasons

There is no mentioning of  how to integrate hazelcast with spring till page 234 but on the page 112  
we suddenly have "_the following is an example of the equivalent Spring configuration_".

**Comment by Serdaro** [comment]
Moving this issue to hazelcast-reference-manual repo.

Thank you @yilativs , you can track this at https://github.com/hazelcast/hazelcast-reference-manual/issues/151.
