### ISSUE TITLE
[bug][documentation] hazelcast-documentation-3.6.1.pdf jcache provider example has wrong version in maven dependency  configuration

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7934]
hazelcast-documentation-3.6.1.pdf jcache provider example has wrong version in maven dependency  configuration

Activating Hazelcast as JCache Provider
<dependency>
<groupId>com.hazelcast</groupId>
<artifactId>hazelcast-all</artifactId>
<version>**3.4**</version> should be **3.6.1**
</dependency>

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/4f5655be6b10aa6ec4282ab56397b5980d99c491.
