### ISSUE TITLE
[bug][documentation] hazelcast-documentation-3.6.1.pdf long lines are truncated

### ISSUE THREAD

**Issue by yilativs** [hazelcast/hazelcast#7937]
hazelcast-documentation-3.6.1.pdf long lines are truncated

Comparing Serialization Interfaces section
string in table is More CPU and memory usage efficient than Serializable - Reflection is not **used during des**
should be More CPU and memory usage efficient than Serializable - Reflection is not used **during deserializaton**

same problem happens in 
section 19.3.1 I/O Threading
NOTE: You can also specify counts for input and output threads separately. There are hazelcast.io.input.thread.**coun**
should be .count

**Comment by Serdaro** [comment]
@yilativs, could you please kindly open reference manual related issues on the hazelcast-reference-manual repo?

**Comment by yilativs** [comment]
Sure Serdar, will do.

**Comment by Serdaro** [comment]
Issue opened in the reference manual repo.
