### ISSUE TITLE
HazelcastHttpSession getAttributeNames still returns entries that were only read but not written

### ISSUE THREAD

**Issue by eysegal** [hazelcast/hazelcast#7942]
This issue is a reopen of #7033 which was supposed to be fixed in #7766 .
Problem is that the null value entries are created with reload=false (HazelcastHttpSession.getAttribute, line 118) where WebFilter.NULL_ENTRY is created with reload=true (WebFilter, line 96, LocalCacheEntry, line 38), so the equals returns false.

**Comment by mesutcelik** [comment]
Hi @eysegal ,

Can you write your test case based on [this one](https://github.com/hazelcast/hazelcast/blob/maintenance-3.x/hazelcast-wm/src/test/java/com/hazelcast/wm/test/WebFilterSlowTests.java#L64)?

**Comment by eysegal** [comment]
Hi,

Thank you for your reply. Actually I haven't download the project and compiled it, just went over the source code and saw the problem... 
I don't fully understand the test, what's the context "read" stands for?

**Comment by mesutcelik** [comment]
first request : we do a [read](https://github.com/hazelcast/hazelcast/blob/maintenance-3.x/hazelcast-wm/src/test/java/com/hazelcast/wm/test/TestServlet.java#L62)

second request: we assert if [no attributeNames are returned](https://github.com/hazelcast/hazelcast/blob/maintenance-3.x/hazelcast-wm/src/test/java/com/hazelcast/wm/test/WebFilterSlowTests.java#L67).

**Comment by eysegal** [comment]
The test fails if 'sticky-session' is set to 'true'.
So looking at this test, when changing node1-node-deferred.xml and node2-node-deferred.xml sticky-session configuration to true:

```
<init-param>
  <param-name>sticky-session</param-name>
  <param-value>true</param-value>
</init-param>
```

Then the test fails on:
```
org.junit.ComparisonFailure: expected:<[]> but was:<[key]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.wm.test.WebFilterSlowTests.test_getAttributeNames_AfterGetAttribute(WebFilterSlowTests.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by mesutcelik** [comment]
I have applied the same change to two XML files  and run the test on 3.6.3-SNAPSHOT but i don't see any error.

Have you changed the test or some other part of the code base? Can you verify that?

**Comment by eysegal** [comment]
The only change I made locally is running just the node - deferred tests in JettyWebFilterTest:
```
@RunWith(WebTestRunner.class)
@DelegatedRunWith(Parameterized.class)
@Category(SlowTest.class)
public class JettyWebFilterTest extends WebFilterSlowTests {

    @Parameters(name = "Executing: {0}")
    public static Collection<Object[]> parameters() {
        return Arrays.<Object[]>asList(
                //new Object[]{"node - not deferred", "node1-node.xml", "node2-node.xml"}, //
                new Object[]{"node - deferred", "node1-node-deferred.xml", "node2-node-deferred.xml"}//, //
                //new Object[]{"client - not deferred", "node1-client.xml", "node2-client.xml"}, //
                //new Object[]{"client - deferred", "node1-client-deferred.xml", "node2-client-deferred.xml"} //
        );
    }

    public JettyWebFilterTest(String name, String serverXml1, String serverXml2) {
        super(serverXml1, serverXml2);
    }

    @Override
    protected ServletContainer getServletContainer(int port, String sourceDir, String serverXml) throws Exception{
        return new JettyServer(port,sourceDir,serverXml);
    }
}

```

**Comment by eysegal** [comment]
I've also just ran test_getAttributeNames_AfterGetAttribute and not the other tests

**Comment by eysegal** [comment]
Yes, just verified locally, the test passes successfully when running it with all other tests.

**Comment by eysegal** [comment]
@mesutcelik have you confirmed the bug?

Thanks
