### ISSUE TITLE
IMAP eviction before reaching max-size

### ISSUE THREAD

**Issue by mmussche** [hazelcast/hazelcast#7956]
Hello, 
I'm testing the eviction policy of an IMap with this configuration : 

```
<map name="TestMap2">
        <backup-count>0</backup-count>
        <in-memory-format>BINARY</in-memory-format>
        <time-to-live-seconds>0</time-to-live-seconds>
        <max-idle-seconds>0</max-idle-seconds>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="PER_NODE">5000</max-size>
        <eviction-percentage>25</eviction-percentage>
        <min-eviction-check-millis>100</min-eviction-check-millis>
        <merge-policy>com.hazelcast.map.merge.LatestUpdateMapMergePolicy
        </merge-policy>
</map>
```

According to the documentation, this should start evicting when 5000 entries are added to the map, but it seems to be evicting when 4750 entries are added.

Am I missing something in the configuration? I have the issue with versions 3.5.1, 3.5.5 and 3.6.1

Here is my test code : 

```
IMap<String, CacheData> map = hz.getDistributedObject("hz:impl:mapService", "TestMap2");
        CacheData cache;
        byte[] data = "data".getBytes();
        byte[] content = "content".getBytes();
        try {
            for(int i = 0; i<4000; i++){
                cache = new CacheData(data,content);
                map.put("key"+i,cache);
            }
            assertEquals(4000,map.getLocalMapStats().getOwnedEntryCount()); //OK
            for(int i = 4000; i<4750; i++){
                cache = new CacheData(data,content);
                map.put("key"+i,cache);
            }
            assertEquals(4750,map.getLocalMapStats().getOwnedEntryCount()); //java.lang.AssertionError: expected:<4750> but was:<4742>
```

**Comment by jerrinot** [comment]
@mmussche: thanks for reporting this. 
The eviction algorithm is probabilistic. It might kick in before the upper bound is reached, this is expected.

**Comment by mmussche** [comment]
@jerrinot 
Is there no way to fill a map with exactly it's max size before eviction to kick in?

**Comment by ahmetmircik** [comment]
Hi @mmussche, 

IMap internally does eviction on partition basis, that means when you use `PER_NODE` policy with a maxSize of 5000, it _translates that maxSize to partition-max-size_ by using this equation
 `partition-max-size = maxSize * memberCount / partitionCount`. And when entry-count in that partition exceeds `partition-max-size`, eviction starts on that partition. 

In your case, it can be that entries in a partition exceeded partition-max-size and eviction was started. So what you see is totally expected.

**Comment by mmussche** [comment]
How is the number of partitions per node defined?

**Comment by jerrinot** [comment]
@mmussche: there are 271 partitions by default. the partitions are distributed among all members of your cluster. each partition can have multiple replicas depending on your backup count. 

You can read more about it at http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#data-partitioning.

@Serdaro: can you please update Reference Manual to stress this?

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/e8079aa8e560daf5dafe54bedae82562b160a9f2
