### ISSUE TITLE
QueueMigrationTest.testMigration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#7964]
```
java.lang.AssertionError: expected:<100> but was:<0>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.collection.impl.queue.QueueMigrationTest.test(QueueMigrationTest.java:51)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast/189/testReport/junit/com.hazelcast.collection.impl.queue/QueueMigrationTest/test/

Full output:
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/189/artifact/hazelcast/target/surefire-reports/com.hazelcast.collection.impl.queue.QueueMigrationTest-output.txt

**Comment by gurbuzali** [comment]
not failed recently and we had an enhancement on migration. I'll close this one, we can re-open if those enhancements didn't solve this issue.

**Comment by mmedenjak** [comment]
`QueueMigrationTest.testMigration:74->testReplication:98 expected:<100> but was:<99>`

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3958/
