### ISSUE TITLE
TargetNotMemberException exception

### ISSUE THREAD

**Issue by mdugdug** [hazelcast/hazelcast#8006]
We are using Hazelcast 3.6 version in production. We are seeing issues when one of the member drops from the cluster. During this time, client gets an error "TargetNotMemberException" and aborts the code. We do not want to catch this exception in client code and continue the logic until member joins the cluster again. 

What is the recommended approach to handle such issues?

**Comment by jerrinot** [comment]
Hi @mdugdug,

this is an expected default behaviour. You configure auto-retrying via https://github.com/jerrinot/hazelcast/blob/eef987b9920f3f7b4c506e433b0d067cab9ba93c/hazelcast-client/src/main/java/com/hazelcast/client/config/ClientNetworkConfig.java#L234-L234
