### ISSUE TITLE
Deserialization of dynamic proxy instances ignores configured ClassLoader

### ISSUE THREAD

**Issue by zerhacker** [hazelcast/hazelcast#8033]
This is a bug in the method
`public static ObjectInputStream newObjectInputStream(final ClassLoader classLoader, final InputStream in) throws IOException`
of the class [com.hazelcast.nio.IOUtil](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/nio/IOUtil.java).
The current implementation is:
```
    public static ObjectInputStream newObjectInputStream(final ClassLoader classLoader, final InputStream in) throws IOException {
        return new ObjectInputStream(in) {
            protected Class<?> resolveClass(final ObjectStreamClass desc) throws ClassNotFoundException {
                return ClassLoaderUtil.loadClass(classLoader, desc.getName());
            }
        };
    }

```
The method
`protected Class<?> resolveProxyClass(String[] interfaces) throws IOException, ClassNotFoundException`
of the ObjectInputStream must be overridden as well.
This bug affects all versions of hazelcast.

**Comment by jerrinot** [comment]
@zerhacker: good finding! are you interested in sending a PR?

**Comment by zerhacker** [comment]
Hmm, I never done this before. But I can try it...

**Comment by jerrinot** [comment]
@zerhacker: that would be great. Let me know if you need any help. I usually hangout at https://gitter.im/hazelcast/hazelcast

We would need you to sign a Contributor Agreement: https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement in order to accept a change.

**Comment by jerrinot** [comment]
fixed by #8047
@zerhacker: once more thanks for an excellent contribution!

**Comment by zerhacker** [comment]
Hello Jaromir,

it was an interesting experience. ;-)
Do you know what the planned release date for Hazelcast 3.7 is?

Best regards

Falk

**Comment by jerrinot** [comment]
@zerhacker: 
We are just about to enter a feature freeze. 

It usually takes 2-5 weeks to get it into the state where we are happy to release. Please take this with a  grain of salt.
