### ISSUE TITLE
Separate bind port from connect port

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#8036]
I'm proposing separating the bind port from connect port for a using Hazelcast better with Docker.  Since Docker ports have to be exposed manually on container start there is a need to explicitly increment the port number to bind to when you run multiple Hazelcast Docker containers on the same host yet you still need to start at the default port of 5701 in order to connect to the first container.  What I'm saying is you should be able to do something like

docker run -it -p 5701:5701 hazelcast // runs on 5701, starts cluster search at 5701
docker run -it -p 5702:5702 -e bindPort=5702 -e searchPort=5701 // app reads env and runs on 5702 but cluster search starts at 5701 to connect to first container

The problem arises when you explicitly set the port variable of NetworkConfig as that is the starting point for searching for other cluster members but given the scenario described above this is undesirable.

**Comment by leszko** [comment]
@markathomas , is it still a valid issue? If yes, then could you write a use case when you need to bind a port different than 5701 inside the container?

**Comment by markathomas** [comment]
i worked around this issue by running all containers on 5701 and setting hazelcast.local.localAddress to the host address while also forwarding port 5701 -> 5701 in the AWS ECS container definition.  This works on hazelcast 3.6.5 but apparently not on 3.9+ so i think it's still a valid issue

**Comment by leszko** [comment]
I actually tried 3.9+ with `hazelcast.local.localAddress` and Docker (as described in [1]) and it works fine. I haven't tried `hazelcast.local.localAddress` on AWS ECS, but it should be ok. Could you write what is the exact problem you get on AWS ECS?

[1] https://github.com/hazelcast/hazelcast-docker#hazelcast-hello-world

**Comment by markathomas** [comment]
i'll see if i can get you the error in the next day or two.  got a release
to finish first!

>

**Comment by mmedenjak** [comment]
@markathomas any updates on the issue? I hope you finished your release successfully :)

**Comment by markathomas** [comment]
yes, i did.  thank you for asking.  i've been slammed lately and haven't had a chance to look at it. feel free to close this if you want as i'm not sure when i can get to it.

**Comment by leszko** [comment]
@markathomas @mmedenjak , closing. Please reopen if the issue still exists.
