### ISSUE TITLE
AWS discovery implicitly depends on port assignment

### ISSUE THREAD

**Issue by markathomas** [hazelcast/hazelcast#8037]
AWS discovery should provide a means of overriding a starting point for the port to connect to after discovering the IP addresses of connectable hosts instead of implicitly relying on the port variable of NetworkConfig.  What I've discovered is that running multiple cluster hosts in AWS on the same machine will not connect to each other if one has port set to 5701 and another to 5702 even if they have the same group settings and AWS tag type and value.  This issue also relates to #8036.

**Comment by leszko** [comment]
Fixed in https://github.com/hazelcast/hazelcast-aws/pull/70
