### ISSUE TITLE
GracefulShutdownCorrectnessTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8064]
```
21:21:57 Running com.hazelcast.internal.partition.GracefulShutdownCorrectnessTest
23:40:56 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/4964/console
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/895/console

**Comment by mdogan** [comment]
closed by https://github.com/hazelcast/hazelcast/issues/8077
