### ISSUE TITLE
MigrationCorrectnessTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8066]
```
05:47:44 Running com.hazelcast.internal.partition.MigrationCorrectnessTest
07:43:38 Build timed out (after 180 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/894/console

**Comment by mdogan** [comment]
closed by https://github.com/hazelcast/hazelcast/issues/8077

**Comment by hasancelik** [comment]
```
04:06:49 Running com.hazelcast.internal.partition.MigrationCorrectnessTest
08:31:45 Build timed out (after 300 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/320/console

**Comment by metanet** [comment]
Closing the issue since we don't have this failure for a long time.
