### ISSUE TITLE
Cluster.shutdown() ignores lifecycle listeners

### ISSUE THREAD

**Issue by zeratul021** [hazelcast/hazelcast#8070]
Expanding from discussion on https://groups.google.com/forum/#!topic/hazelcast/wbI8i2PlkVc

_ClusterServiceImpl_ has method shutdownNodes which calls **node.shutdown(false)**. The same applies for _ShutdownNodeOperation_.

Shouldn't it call _LifecycleService_ instead so the proper listeners are invoked before and after?

Cluster shutdown functionality seems really useful but in our case lot of stuff relies on the listeners for deinitialization.

**Comment by zeratul021** [comment]
Would this be available for backport to 6.3? Or is too big of a change?

**Comment by jerrinot** [comment]
@zeratul021: many thanks for reporting the issue! A fix will be included in Hazelcast 3.6.3 too 
See #8164
