### ISSUE TITLE
cloud auto discovery in CHINA region

### ISSUE THREAD

**Issue by fwrq41251** [hazelcast/hazelcast#8073]
```
<aws enabled=”true”>
<access-key>my-access-key</access-key>
<secret-key>my-secret-key</secret-key>
<region>us-east-1</region>
<host-header>ec2.amazonaws.com</host-header>
<security-group-name>sg-hazelcast</security-group-name>
<tag-key>type</tag-key>
<tag-value>hz-nodes</tag-value>
</aws>
```
when the region is set to "cn-north-1",
server raise a exception:
*java.net.UnknownHostException: ec2.cn-north-1.amazonaws.com*
and the host should be *ec2.cn-north-1.amazonaws.com.cn*.
and when host-header is set to "ec2.cn-north-1.amazonaws.com.cn",
the config does not work.
does hazelcast now version support china region or not ?

**Comment by fwrq41251** [comment]
ps:i am using hazelcast version:3.2.6

**Comment by noctarius** [comment]
Did you try to configure host-header for China?

`<host-header>ec2.amazonaws.com.cn</host-header>`

PS: You're using a pretty old version of Hazelcast which might not work anymore when old datacenters deactivate old signature algorithm for signing REST API requests.

**Comment by fwrq41251** [comment]
@noctarius 
i have tried this.
so the newest version support china region? and how should the config be like?

**Comment by mesutcelik** [comment]
here is the latest doc. I don't see any config change.
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#discovering-members-within-ec2-cloud

Can you please try with the latest stable version that is hazelcast 3.6.2

**Comment by bilalyasar** [comment]
This issue is very similar to https://github.com/hazelcast/hazelcast/issues/5653 and it was already solved with 3.5.2

**Comment by fwrq41251** [comment]
i have taken a look at code in hazelcast 3.6.2.
```
endpoint = awsConfig.getHostHeader();
if (awsConfig.getRegion() != null && awsConfig.getRegion().length() > 0) {
	setEndpoint("ec2." + awsConfig.getRegion() + ".amazonaws.com");
}
```
since the region in awsconfig cannot be set to empty(the set method has an empty check),the host-header config will never work?

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/8102
