### ISSUE TITLE
Extend LocalExecutorStats with "getRunningTasks"

### ISSUE THREAD

**Issue by noctarius** [hazelcast/hazelcast#8080]
Currently you get information like started, completed, pending but not how much tasks are running inside a specific distributed executor service. This information, however, can be used for load balancing use cases and would remove the workaround to keep your own data structures up and running.

**Comment by tkountis** [comment]
@noctarius isn't this `STARTED` - `COMPLETED` or something more?

**Comment by mmedenjak** [comment]
Closing as it seems there is already a way how to get these.
