### ISSUE TITLE
Cache entries are lost when size > 10K

### ISSUE THREAD

**Issue by asarigul** [hazelcast/hazelcast#8099]
Hello,

When a cache's size is relatively big, some entries are lost (in our case, we put 12800 unique objects, and the lost ones were **always** the same objects). I did not observe this case when cache size < 10K. 

Here is a test to reproduce the issue:

```
	@Test
	public void test() {
		try (Cache<Integer, Integer> cache = create("test", Integer.class, Integer.class)) {
			for (int i = 1000;; i = i + 1000) {
				test(cache, i);
				System.out.println("OK with " + i + " entries");
			}
		}
	}

	private static void test(Cache<Integer, Integer> cache, int size) {
		fill(cache, size);
		Assert.assertEquals(size, allValues(cache).size());
	}

	private static void fill(Cache<Integer, Integer> cache, int size) {
		cache.clear();
		for (int i = 0; i < size; i++) {
			cache.put(i, i);
		}
	}

	private static <K, V> Cache<K, V> create(String cacheName, Class<K> keyClass, Class<V> valueClass) {
		return Caching.getCachingProvider().getCacheManager().createCache(cacheName,
				eternalExpiryConfig(keyClass, valueClass));
	}

	private static <K, V> Configuration<K, V> eternalExpiryConfig(Class<K> keyClass, Class<V> valueClass) {
		MutableConfiguration<K, V> config = new MutableConfiguration<>();
		config.setExpiryPolicyFactory(EternalExpiryPolicy.factoryOf());
		return config;
	}

	private static <K, V> List<V> allValues(Cache<K, V> cache) {
		List<V> values = new ArrayList<>();
		for (Iterator<Cache.Entry<K, V>> it = cache.iterator(); it.hasNext();) {
			values.add(it.next().getValue());
		}
		return values;
	}
``` 

This is the output:

```
OK with 1000 entries
OK with 2000 entries
OK with 3000 entries
OK with 4000 entries
OK with 5000 entries
OK with 6000 entries
OK with 7000 entries
OK with 8000 entries
OK with 9000 entries
OK with 10000 entries

java.lang.AssertionError: expected:<11000> but was:<10991>
```

In this scenario, existing entry size was constant, ie: when I put 11K (0 ... 10999), I always get 10991 elements back. 
For 12K puts -> java.lang.AssertionError: expected:<12000> but was:<11961>
For 13K puts -> java.lang.AssertionError: expected:<13000> but was:<12845>
For 14K puts -> java.lang.AssertionError: expected:<14000> but was:<13611>
...

Hazelcast version on our server was 3.6, but I could reproduce the issue with the same results with 3.6.2.

**Comment by jerrinot** [comment]
Hi @asarigul,

JCache (unlike IMap) uses eviction by default. You can configure your own threshold, see http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#jcache-eviction

I'm closing this issue as it's working as expected.

**Comment by asarigul** [comment]
Hi @jerrinot 

Thanks for the info. So, if this is the case, I will increase the max_size for eviction. 

But I wonder, if the default is 10K, how could I get 13611 elements in the cache after I put 14K?

**Comment by noctarius** [comment]
The eviction uses a per-partition heuristic to run in consistent runtime - sanitized 0(1) - and as a local operation only. That said you can get slightly higher or lower values depending on partition distribution.

**Comment by asarigul** [comment]
Hi there again @jerrinot  @noctarius 

Although I added the following part to my hazelcast.xml, the entries are still evicted after 10K. Do you have any idea?

```
<cache name="test">
	<eviction size="20000" max-size-policy="ENTRY_COUNT" eviction-policy="LRU" />
</cache>
```

I'm sure hazelcast is configured with that xml (I see the correct path in hz startup logs), and I run my tests against "test" cache.
