### ISSUE TITLE
Too much cpu used when Hazelcast is idle

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast#81]
<b>What steps will reproduce the problem?</b>
<b>1.</b>
This simple instantiation of multiple members:

  HazelcastInstance inst1 = Hazelcast.newHazelcastInstance(null); 
                HazelcastInstance inst2 = Hazelcast.newHazelcastInstance(null); 
                HazelcastInstance inst3 = Hazelcast.newHazelcastInstance(null); 
                HazelcastInstance inst4 = Hazelcast.newHazelcastInstance(null); 
1. is producing (on Windows 7, clearly listed by Task Manager and ProcExplorer a CPU usage &gt; 1% for each additional instance. 4%
2. using Jprofiler we can see the following
   51,4% - 487 ms - 2 inv. com.hazelcast.cluster.ClusterService.run 
   39,8% - 376 ms - 4 inv. com.hazelcast.nio.SelectorBase.run 
   6,0% - 56.424 µs - 2 inv. com.hazelcast.impl.management.ManagementCenterService$UDPSender.run 
   2,3% - 21.438 µs - 2 inv. com.hazelcast.impl.management.ManagementCenterService$UDPListener.run 
   0,4% - 3.615 µs - 2 inv. java.util.concurrent.ThreadPoolExecutor$Worker.run 
   0,2% - 2.005 µs - 2 inv. com.hazelcast.impl.MulticastService.run 

In particular it seems that CheckPeriodics(), dequeueProcessables(), ProcessSelectionQueue, dequeuePackets() are doing a kind of while(true){ queue.poll(); } 

<b>What is the expected output? What do you see instead?</b>
We would expect to see a minimal CPU consumption when hazelcast is idle. Possibly &lt; 0.1 %

<b>What version of the product are you using? On what operating system?</b>
Tested on various platforms including Windows 7. Version is 1.9.4.6

<b>Please provide any additional information below.</b>

Is there a way to reduce the polling? Very critical having an instance using when idle much less than 0.1% of the cpu.

<p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=789</p><hr/><h2>earlier comments</h2>
<p><strong>russell.silva@singlemindconsulting.com said, at 2012-03-01T21:03:49.000Z:</strong></p>

<p>I am experiencing the same issue.  "top" reports high CPU usage for the Java process.  Java VisualVM profiling reports high CPU usage for ClusterService.run and SelectorBase.run as it did for the reporter.</p>

**Comment by StepanMelnik** [comment]
Found that "Filter Based Web Session Replication" solution uses almost all cpu in hazelcast-3.4.5 and hazelcast-all-3.5.1 versions. 

hazelcast-all-3.4.2 works better but have completely different implementation comparing with the latest version.

![high_cpu](https://cloud.githubusercontent.com/assets/3713877/9106125/2687d824-3c1e-11e5-8d77-a2aa55d02c6f.png)


Tested with jdk1.7.0_71 and jdk1.8.0_51 versions.
Tested on Windows7 and WindowsServer 2012.

**Comment by kobalski** [comment]
@StepanMelnik thank for reporting the issue. It is fixed with PR https://github.com/hazelcast/hazelcast/pull/5832. You can try 3.6-SNAPSHOT for now. The fix will be available in closest minor release.

**Comment by mesutcelik** [comment]
@StepanMelnik ,
I think you can also try 3.5.2-SNAPSHOT. Backport PR https://github.com/hazelcast/hazelcast/pull/5834

**Comment by StepanMelnik** [comment]
Seems to work better. Thanks.

**Comment by NiranjanBS** [comment]
Am using 3.6.2 new release still taking high CUP usage.
Verified in java 1.7.0_75 and 1.8.0_77.
OS Windows 7.
![untitled](https://cloud.githubusercontent.com/assets/9413835/14461410/0ae0165e-00e0-11e6-9a11-78631f5ce367.png)
![untitled1](https://cloud.githubusercontent.com/assets/9413835/14461409/0add3312-00e0-11e6-924b-0013c2a344cc.png)

**Comment by noctarius** [comment]
Can you please put this into a new ticket and provide some more information about what you're doing and how the use case (maybe even some code fragments) look like?

**Comment by NiranjanBS** [comment]
Hi @noctarius thanks, I raised new ticket #7943.
