### ISSUE TITLE
Multinode - Wan Configuration problem

### ISSUE THREAD

**Issue by hariprasanth1234** [hazelcast/hazelcast#8122]
Hi Guys,

We used the following configuration in the WAN replication config,

In Node 1 (london), added the newyork configuration as target 

         private static WanReplicationConfig getWanReplicationConfig() {
		WanReplicationConfig wanReplicationConfig = new WanReplicationConfig();
		wanReplicationConfig.setName("payoda");
		
		WanTargetClusterConfig nyWanTargetClusterConfig = new WanTargetClusterConfig();
		nyWanTargetClusterConfig.setGroupName("newyork");
		nyWanTargetClusterConfig.setGroupPassword("newyork");
		nyWanTargetClusterConfig.setReplicationImpl("com.hazelcast.wan.impl.WanNoDelayReplication");
		List<String> endPoints = new ArrayList<String>();
		endPoints.add("192.168.12.109:5701");
		endPoints.add("192.168.12.110:5701");
		nyWanTargetClusterConfig.setEndpoints(endPoints);
		
		List<WanTargetClusterConfig> wanTargetClusterConfigList = new ArrayList<WanTargetClusterConfig>();
		wanTargetClusterConfigList.add(nyWanTargetClusterConfig);
		wanReplicationConfig.setTargetClusterConfigs(wanTargetClusterConfigList);
		
		return wanReplicationConfig;
	}
   	

and In Node 2 (newyork), added the london as target configuration.

           private static WanReplicationConfig getWanReplicationConfig() {
		WanReplicationConfig wanReplicationConfig = new WanReplicationConfig();
		wanReplicationConfig.setName("payoda");
		
		WanTargetClusterConfig londonWanTargetClusterConfig = new WanTargetClusterConfig();
		londonWanTargetClusterConfig.setGroupName("london");
		londonWanTargetClusterConfig.setGroupPassword("london");
		londonWanTargetClusterConfig.setReplicationImpl("com.hazelcast.wan.impl.WanNoDelayReplication");
		List<String> endPoints = new ArrayList<String>();
		endPoints.add("192.168.12.59:5701");
		endPoints.add("192.168.12.60:5701");
		londonWanTargetClusterConfig.setEndpoints(endPoints);
		
		List<WanTargetClusterConfig> wanTargetClusterConfigList = new ArrayList<WanTargetClusterConfig>();
		wanTargetClusterConfigList.add(londonWanTargetClusterConfig);
		wanReplicationConfig.setTargetClusterConfigs(wanTargetClusterConfigList);
		
		return wanReplicationConfig;
	}

1) For Join config, In both nodes used as TCP IP Config is enabled,

final String hazelCastIps = "192.168.12.59:5701,192.168.12.60:5701";
		joinConfig
				.getTcpIpConfig()
				.addMember(hazelCastIps)
				.setEnabled(false);

What happens is data replicated only within cluster and not replicating across WAN, I mean from london to newyork or newyork to london

2)  For Join config, In both nodes used as MULTICAST IP Config is enabled,

All the 4 IP's forms the cluster,

What happens is data is also replicated across WAN, I mean from london to newyork and also from newyork to london, that is good. 
But when I try to read the data from one node (lets say 192.168.12.109), It points to another IP across WAN for fetching the data, How to avoid that, In case of READ in newyork node IP, I want to fetch the data only from the newyork cluster.

**Comment by mesutcelik** [comment]
I see a discussion going on already at https://groups.google.com/forum/#!topic/hazelcast/bD4giW4S1RY
so closing this ticket.
