### ISSUE TITLE
IAtomicReference#alter does not persist changes

### ISSUE THREAD

**Issue by KIC** [hazelcast/hazelcast#8149]
For some reason when I just want to alter an AtomicReference<MyObject> like so:

```
  ref.alter(node -> {
            node.nextNodes[0] = lala;
            node.nextKeys[0] = "lala";
            return node;
        });
```

then nothing changes. A later get will still return the old object. But when i change this to alterAndGet

```
  ref.alterAndGet(node -> {
            node.nextNodes[0] = lala;
            node.nextKeys[0] = "lala";
            return node;
        });
```

then everything works as expected. But in fact I do not want so send the whole object over wire, I just want to modify a property.

**Comment by jerrinot** [comment]
@KIC: thanks for reporting this issue. What Hazelcast version are you using? Is it with client-member or member-member topology?

**Comment by KIC** [comment]
I am usng 3.6.2 but I also could reproduce it with 3.5.5. Yes I use client, server instances but the issue also remans by just using one local server.

**Comment by jerrinot** [comment]
@KIC: interesting, we have integration tests for this running with each change. see https://github.com/hazelcast/hazelcast/blob/v3.5.5/hazelcast/src/test/java/com/hazelcast/concurrent/atomicreference/AtomicReferenceBasicTest.java

Can you please provide a reproducer? thanks!

**Comment by KIC** [comment]
Sure:

```
package com.mindbusters.range.cache.column.stuff.hazelcast;

import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IAtomicReference;

import java.io.Serializable;
import java.util.Arrays;

/**
 * Created by kic on 11.05.16.
 */
public class Issue {
    public static class MyClass implements Serializable {
        private static final long serialVersionUID = -3394196400279204634L;
        public String[] someArray;

        public MyClass() {
            this.someArray = new String[10];
        }

        @Override
        public String toString() {
            return Arrays.toString(someArray);
        }
    }

    public static void main(String[] args) {
        HazelcastInstance hi = Hazelcast.newHazelcastInstance();
        IAtomicReference<MyClass> foo = hi.getAtomicReference("foo");

        foo.set(new MyClass());

        foo.alter(mc -> {
            mc.someArray[0] = "hello";
            return mc;
        });

        System.out.println(foo.get()); // prints [null, null, null, null, null, null, null, null, null, null]

        foo.alterAndGet(mc -> {
            mc.someArray[0] = "hello";
            return mc;
        });

        System.out.println(foo.get()); // prints [hello, null, null, null, null, null, null, null, null, null]

    }
}
```

**Comment by jerrinot** [comment]
@KIC: Many thanks, there is really bug which manifests itself only when your function mutates the original object instead of returning a new instance. The same issue was already fixed for `alterAndGet()`, see #2495

I'll send a fix for `alter()` too. In meantime you can use this as a workaround:
```java
        foo.alter(mc -> {
            MyClass copy = new MyClass();
            copy.someArray = mc.someArray;
            copy.someArray[0] = "hello";
            return copy;
        });
```

**Comment by KIC** [comment]
Hmmm ... I have tried to add an `equals() { return false; }` but it seems to be the only solution to make a new object. However does this mean with `apply` I am not writing to the original object and every update leads to a serialization of a potentially big object graph? Seems to be uncool :-) Could I configure that behavior?

**Comment by jerrinot** [comment]
@KIC: your are right. There is always a serialization. However bear in mind the cost of serialization is usually dwarfed by a network latency. Also when your function actually modifies an object then we need to serialize it anyway - as we need to send a backup over a network. 

I agree there is still a room for optimization - for the cases where the function does not do any modification and there is no need to backup anything. The only question is whether it's worth it. 

It boils down to the problem of detecting a modification in an object graph. I see these options:
1. Hazelcast could do what Hibernate does: Instrument an object and try to detect changes
2. Provide a new interface a user could implement. Something along these lines:
```java
public interface ModCountable {
  /**
  * Return monotonically increasing sequence counting object modifications.
 */
  int getModCount();
}
```

The first approach feels to be rather complex & fragile. It's also hard to implement it without introducing external dependencies (CGLib, asm, etc..)

The 2nd approach is trivial to implement, but I'm always reluctant to introduce a new public interface - as each new interface means additional complexity for our end-user. Simplicity is our key value.

There is yet another option: We could change a contract so the function would not be allowed to modify passed object and it would have to return a new instance (when modified) - then it's again trivial to detect changes. However this is a compatibility breaking change -> it's a no-go. 

I'd recommend you to use an optimized serialization method for you domain object - Java Serialization has not been really designed for space/time effectivity. Have a look at [DataSerializable](https://github.com/jerrinot/hazelcast/blob/75251c4f01d131a9624fc3d0c4190de5cdf7d93a/hazelcast/src/main/java/com/hazelcast/nio/serialization/DataSerializable.java#L33-L33) or [IdentifiedDataSerializable](https://github.com/jerrinot/hazelcast/blob/75251c4f01d131a9624fc3d0c4190de5cdf7d93a/hazelcast/src/main/java/com/hazelcast/nio/serialization/IdentifiedDataSerializable.java#L30-L30) - they are usually much faster - that should do the trick.

Feel free to re-open this ticket if you unnecessary serialization become your bottleneck.
