### ISSUE TITLE
map.containsKey() always returns true 

### ISSUE THREAD

**Issue by nadilas** [hazelcast/hazelcast#816]
I have a MapStore class prepared with all the override methods, which works fine (empty database turns out to be empty map). 
Checking back after initialisation whether the map contains one of the expected values (enum key) the map returns true, thus the app does not try to put the new value in.
Checked with Literal String key as well, map.containsKey() method with size=0 returns true all the time, for any keys.
Is this a known phenomena?

**Comment by Sergey80** [comment]
http://stackoverflow.com/questions/31897616/hazelcast-get-always-returns-null-containskey-always-return-false
