### ISSUE TITLE
Performance: caller uuid as a real UUID

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8165]
Instead of using a string, which requires 2 objects, it can be a UUID which requires just 1 object. Apart from that a UUID can very cheaply be serialized/deserialized by using 2 longs (most/least significant bits).

Also deserialzation leads to less litter since only a single object is needed (UUID) instead of 2 (String + char-array).

**Comment by burakcelebi** [comment]
Closed as internal request.
