### ISSUE TITLE
Performance: address inefficient

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8166]
Address is quite inefficient since it relies on strings.

In case of an ip4 address, just 6 bytes are needed + the object address overhead. So perhaps we should have dedicated subclasses e.g. Ipv4Address. 

Address is the general workhouse for addressing and if space can be reduced here, everything that makes use of addresses, will benefit from it .e.g operations.

Deserializing would be cheaper since you don't rely on string encoding (very inefficient) but you also get less litter (no string, byte-array is needed). This is 2 objects litter less per invocation!

**Comment by pveentjer** [comment]
I was too early with this one. Address is not shipped on an operation.

**Comment by jerrinot** [comment]
There is still a lookup into a Map Adress -> Connection for each packet (?) . While this doesn't add to a network payload it still means the lookup is slower than necessary.
