### ISSUE TITLE
InvalidConfigurationTest depends on system locale setting

### ISSUE THREAD

**Issue by zerhacker** [hazelcast/hazelcast#8169]
The tests check the messages of the InvalidConfigurationExeptions thrown by the XmlConfigBuilder.
But these messages are often extracted from SAXParseExceptions which are localized.
So the maven build is platform dependend and fails.

**Comment by zerhacker** [comment]
There are several options to fix this:

1. The maven build can be configured to a fixed locale.
- Con: test executions in an ide may still fail.
2. The InvalidConfigurationTest can set the default locale in a @Before setup() method.
- Con: This is not side effect free.
3. The tests could be changed. Relying on exception messages is in general a bad practice. (But its "only" test code.)
- Con: None. But more work.

**Comment by jerrinot** [comment]
@bilalyasar: can you please have a look? thanks!

**Comment by bilalyasar** [comment]
can you run with `-Djaxp.debug=1` parameter and post the logs? I want to reproduce this issue in my local.

**Comment by zerhacker** [comment]
The build is running... Meanwhile: here is my `mvn --version` output:

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: **de_DE**, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.4", arch: "x86_64", family: "mac"

**Comment by zerhacker** [comment]
Here is the maven build log file:
[build.txt](https://github.com/hazelcast/hazelcast/files/263518/build.txt)
There are other tests that fail caused by locale sensitivity.

**Comment by pveentjer** [comment]
I'll fix it. Just remove the message content check; one should not assert on messages.
