### ISSUE TITLE
Missing CacheWriter / CacheLoader implementation classes shouldn't be a requirement on the client side

### ISSUE THREAD

**Issue by burakcelebi** [hazelcast/hazelcast#8175]
When a CacheWriter / CacheLoader is set up on JCache configuration and this configuration is sent to a Hazelcast client, due to how the JCache configuration works, those implementation classes need to be available in the client’s classpath.

**Comment by serkan-ozal** [comment]
I don't understand why `CacheWriter / CacheLoader` classes must be exist on client classpath. 

Client can only specify factory without any compile-time dependency to `CacheWriter / CacheLoader` class and it can create `CacheWriter / CacheLoader` at server with reflection. For example:

``` java
    class MyCacheLoaderFactory 
            implements Factory<CacheLoader>, HazelcastInstanceAware {
        
        private static final String CACHE_LOADER_IMPL_CLASS_NAME = "com.mycompany.MyCacheLoader";
        
        private HazelcastInstance hazelcastInstance;
        
        @Override
        public void setHazelcastInstance(HazelcastInstance hazelcastInstance) {
            this.hazelcastInstance = hazelcastInstance;
        }

        @Override
        public CacheLoader create() {
            ClassLoader cl = hazelcastInstance.getConfig().getClassLoader();
            try {
                return ClassLoaderUtil.newInstance(cl, CACHE_LOADER_IMPL_CLASS_NAME);
            } catch (Exception e) {
                throw new RuntimeException("CacheLoader instance cannot be created!", e);
            }
        }

    } 
```

Note that, here class of `CacheLoader` implementation is not exist on client's classpath but server's classpath.

**Comment by noctarius** [comment]
Sure you can work around it using reflection but this does not really answer the initial problem :) The factory needs to be available on the clients classpath, since it is part of the configuration.

**Comment by serkan-ozal** [comment]
I don't think factory should be a problem from client side.
``` java
cacheConfig.setCacheLoaderFactory(
        javax.cache.configuration.FactoryBuilder.factoryOf("com.mycompany.MyCacheLoader"));
``` 
simply should be enough if there is no specific classloader requirement.

**Comment by serkan-ozal** [comment]
what is the status of this issue?

**Comment by serkan-ozal** [comment]
Closing this one since as I had mentioned above, cache loader/writer is not needed to be exist at client's classpath.
