### ISSUE TITLE
Small fix in IAtomicLong documentation

### ISSUE THREAD

**Issue by gfelisberto** [hazelcast/hazelcast#8215]
Small correction to the docs.

In the docs for [IAtomicLong](http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#sending-functions-to-iatomiclong) states: 

> The following sample Function implementation doubles the original value.

It should be:

> The following sample Function implementation adds 2 to the original value.

Also it should not be Function but actually IFunction.

**Comment by Serdaro** [comment]
Thank you @gfelisberto. I will fix in the Reference Manual repo and reference the fix here.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/3571bf17038643a673a97485083924f36e585c8b
