### ISSUE TITLE
Hazelcast background threads & JavaEE

### ISSUE THREAD

**Issue by hendrikebbers** [hazelcast/hazelcast#8216]
Hazelcast creates some background threads / threadpools that are for example used to trigger listeners on new messages in a topic. This will happen in any environment like JavaSE, Spring or JavaEE. In JavaEE you normally should not create your own threads since this threads won't be managed by the container. Before JavaEE 7 there wasn't a real solution to create a managed Thread in an JavaEE environment. But JavaEE 7 contains managed executors. Based on this solution it would be perfect if I could configure Hazelcast by using custom executors. In that case you could simply inject executors that are managed by the container and use them for Hazelcast.

**Comment by pveentjer** [comment]
I don't think we are interested.

**Comment by tombujok** [comment]
Thanks for your feedback @hendrikebbers and @pveentjer.  I understand that JEE container is unaware of HZ threads, but to be honest we want it to be unaware. The container would not be able to do anything good with this knowledge and IMHO switching to JEE executors could cause significant performance degradation.

HZ is tuned to achieve the highest performance possible in given environment thus switching to JEE executors is probably a no-go for us currently. 

I'll close this issue now but if there's any significant traction here we may re-open this discussion.
