### ISSUE TITLE
documentation for time-to-live-seconds is inaccurate, conflicting, and confusing

### ISSUE THREAD

**Issue by hzisfun** [hazelcast/hazelcast#8222]
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#configuring-map-eviction

Under "time-to-live:" section says, "... entries that are older than this time and not updated for this time are evicted automatically."

http://docs.hazelcast.org/docs/3.6/javadoc/com/hazelcast/config/MapConfig.html#setTimeToLiveSeconds(int)

says, "... Updates on the entry do not change the eviction time."

I made a small test that shows that the manual is correct and the Java docs are incorrect ... calling IMap.executeOnKey with an EntryProcessor that calls entry.setValue() does, in fact, cause the entry to stay in the map beyond the time at which it would have expired had the value not been modified. Note that this is the behavior I desire ... I'm not asking for this behavior to change ... I'm just asking for the Java docs to be updated to reflect the fact that updates to the entry do change the eviction time - as most people would expect.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast/commit/c0fbe356a6e2ddccc373f5d0d93f8345665d6bc7
