### ISSUE TITLE
IAM Role fully support needed

### ISSUE THREAD

**Issue by kylixtan** [hazelcast/hazelcast#8243]
mostly EC2 instance is launched with "IAM Role" attached, that will just provide all the authentication info for APP to access EC2 resource with temporary key.

for hazelcast auto-discovery config on EC2, the only required informaiton will be instance filter, such as tag, security groups, region etc.

**Comment by mesutcelik** [comment]
Hi @kylixtan ,
Thanks for contacting us.

We are already supporting IAMRole in 3.6.x. What is the problem here? I couldn't get the problem or request from the description above.

please see the [3.6.x doc](http://docs.hazelcast.org/docs/3.6/manual/html-single/) for more info.

**Comment by kylixtan** [comment]
The IAM Role is attached to EC2 instance, we don't need to put this info in
the config file. you could just find it automatically, that will be cool.

that is also the aws tools' standard access method.

2016-05-25 15:22 GMT+08:00 Mesut Celik <notifications@github.com>:

> Hi @kylixtan <https://github.com/kylixtan> ,
> Thanks for contacting us.
>
> We are already supporting IAMRole in 3.6.x. What is the problem here? I
> couldn't get the problem or request from the description above.
>
> please see the 3.6.x doc
> <http://docs.hazelcast.org/docs/3.6/manual/html-single/> for more info.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hazelcast/hazelcast/issues/8243#issuecomment-221493482>
>



-- 
Tan Liuxing
Kyix.Tan@Gmail.com

**Comment by mesutcelik** [comment]
Hi @kylixtan ,

if you use `DEFAULT` as iamrole in hazelcast config, that would solve your problem but that has only been added lately. Can you please try 3.6.3-SNAPSHOT if that works? cc: @bilalyasar

**Comment by bilalyasar** [comment]
Hi @kylixtan ,
We have added this feature with this PR https://github.com/hazelcast/hazelcast/pull/8100 
Can you try with 3.6.3 version ( which is recent release of hazelcast)
your config will be like:
```
<aws enabled="true">
    <access-key>my-access-key</access-key>
    <secret-key>my-secret-key</secret-key>
    <iam-role>DEFAULT</iam-role>
  </aws>
```

**Comment by mesutcelik** [comment]
Hi @kylixtan 

any update?
