### ISSUE TITLE
Derived metrics

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8259]
The current metrics show the actual value in the probe; which is very useful but it is difficult to determine e.g. packets per second, operations per second etc. 

For inspiration see:
http://metrics.dropwizard.io/3.1.0/manual/core/

**Comment by pveentjer** [comment]
2 mandatory derived probes are send and receive bandwidth. In packets and bytes/second.

**Comment by pveentjer** [comment]
and operation/invocations per second

**Comment by dbrimley** [comment]
Mertrics flow should not be aggregated or grouped, this should be left to other applications like Carbone/Graphite for the actual aggregation.

Management Centre will also aggregate in future versions.
