### ISSUE TITLE
embedded member hzInstance.getCluster().shutdown();  cluster not restarting.

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8271]
I have HZ member imbedded into an application jvm,  
I have a 4 node cluster, on 4 boxes, in 4 application jvm's

when i call   hzInstance.getCluster().shutdown();   from one of the nodes.  all the Hz member instance will be showdown.  inside the application jvm.

I see in the logs, this is the case. and all members shutdown

how to “restart” the hz member instance’s inside my application jvm's ?

inside my application jvm's I 'new' the HZ instances  to restart the cluster, inside my application.
hzInstance = Hazelcast.newHazelcastInstance(config);

however, in the log i see nothing printed,  there is no signe that a hz member node was created.
even.  my application is not able to print to system out.  all out put is lost.

I can not,  re-create the cluster in the application jvm's.

hazelcast 3.6.3, and 3.7-SANPSHOT

i also checked using  hzInstance.shutdown();
shutting down 1 member and then restarting the Hz instance in the application JVM 
using
hzInstance = Hazelcast.newHazelcastInstance(config);
which works as expected.

**Comment by Danny-Hazelcast** [comment]
I see this issue with

``` java.runtime.name: OpenJDK Runtime Environment
sun.boot.library.path: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64/jre/lib/amd64
java.vm.version: 24.95-b01
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/
 ```

but using 
``` java.runtime.name: Java(TM) SE Runtime Environment
sun.boot.library.path: /home/ec2-user/jdk1.8.0_92/jre/lib/amd64
java.vm.version: 25.92-b14
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/ ```

it work ok

**Comment by Danny-Hazelcast** [comment]
also worked with.

sun.boot.library.path: /home/ec2-user/jdk1.7.0_79/jre/lib/amd64
java.vm.version: 24.79-b02
java.vm.vendor: Oracle Corporation
java.vendor.url: http://java.oracle.com/

**Comment by mdogan** [comment]
Closing since problem looks like an environment issue.
