### ISSUE TITLE
Remove partitionId from Packet

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8274]
Partition id should not be part of packet:
- not everything needs a partition id, e.g. response.
- in case of an operation, the partition id already is part of the operation payload itself and therefor there is no reason for duplication.

The partition id is needed when an operation is being offered to the operation executor and one can look directly into the bytes of the serialized operation to retrieve it; just as we retrieve the callid in case of a serialization failure.

Removing the packet id would shave 4 bytes from every invocation and 4 bytes from the response.

**Comment by mdogan** [comment]
@pveentjer: Is this still planned in 3.8?

**Comment by dbrimley** [comment]
This involves wider work on redesign of network protocol and can only be addressed in 4.0

**Comment by burakcelebi** [comment]
Closed as internal request.
