### ISSUE TITLE
Docs: Configuring Replicated Map 

### ISSUE THREAD

**Issue by magiccrafter** [hazelcast/hazelcast#8297]
In Section:
**Replicated Map Declarative Configuration**

The **statistics-enabled** configuration by default is set to true: 

current:
If set to true, the statistics such as cache hits and misses are collected. The default value is **false**.
correct one:
If set to true, the statistics such as cache hits and misses are collected. The default value is **true**.

**Comment by Serdaro** [comment]
Thank you @magiccrafter , I will update it accordingly.

**Comment by Serdaro** [comment]
Fixed by https://github.com/hazelcast/hazelcast-reference-manual/commit/e7243d4ccc65b1e1aa054a88ef9b1115bf5cbcbd
