### ISSUE TITLE
Set a different NIC for WAN replication

### ISSUE THREAD

**Issue by rbouikila** [hazelcast/hazelcast#8325]
Hi all,

I would like use hazelcast cluster in my company.

I want to create two hazelcast clusters (site 1 & site 2) with wan replication. All servers have two network interfaces.
    - First interface is dedicated for production. (10.x.x.x)
    - Second interface is dedicated for WAN Replication. (192.168.x.x)

Hazelcast doesn't support this setup yet. Can you consider the opportunity to add this feature?

Regards,

**Comment by mmedenjak** [comment]
Hi, sorry for the long delay. Currently this is targeted for 3.11.

**Comment by mmedenjak** [comment]
Unfortunately this won't make it into 3.11. We are considering 3.12.

**Comment by mmedenjak** [comment]
Hi @rbouikila!

This has been added into 3.12. You can now expose a hazelcast instance through different server sockets for different sources: https://docs.hazelcast.org/docs/latest/manual/html-single/#advanced-network-configuration.

Closing this issue. Happy hazelcasting!
