### ISSUE TITLE
Verify StringPartitioningStrategy works as expected with all structures supporting the usage of the strategy

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#8328]
While reviewing this issue:
https://github.com/hazelcast/hazelcast/issues/7947 and PR https://github.com/hazelcast/hazelcast/pull/8321 

We found that there may be some other places where StringPartitioningStrategy strategy may be missing when determining the partition Id. We need to look at the ClientPartitionService.getPartitionId usages. The tests should also be added for other containers if missing.

**Comment by sancar** [comment]
We have rechecked the need of using `StringPartitioningStrategy`. It seems there is no extra fix required.
