### ISSUE TITLE
PhoneHome TLS/HTTPS

### ISSUE THREAD

**Issue by nkavian** [hazelcast/hazelcast#8333]
Consider using SSL for PhoneHome.

https://github.com/kobalski/hazelcast/blob/cdf8d851e9c6440df13956fc80aed6d5e448ff31/hazelcast/src/main/java/com/hazelcast/util/PhoneHome.java#L62

**Comment by mmedenjak** [comment]
Closing in favour of https://github.com/hazelcast/callhome/issues/35

**Comment by nkavian** [comment]
The link you shared generates a 404. Is the repository private?

**Comment by kwart** [comment]
Reopening this one, so we can track it on the HZ side too. 
@mmedenjak We should resolve this before releasing 4.2.

**Comment by kwart** [comment]
This was also discussed within pull request #17892.

**Comment by mmedenjak** [comment]
@nkavian yes, the repository is private. Agree this should be addressed before 4.2-GA
