### ISSUE TITLE
ReadBackupData and MaxIdleSeconds relation - documentation

### ISSUE THREAD

**Issue by BogdanEM** [hazelcast/hazelcast#8354]
> MapConfig com.hazelcast.config.MapConfig.setMaxIdleSeconds(int maxIdleSeconds)
> 
> Maximum number of seconds for each entry to stay idle in the map. Entries that are idle(not touched) for more than maxIdleSeconds will get automatically evicted from the map. Entry is touched if get, getAll, put or containsKey is called. Any integer between 0 and Integer.MAX_VALUE. 0 means infinite. Default is 0.

Seems that when we have a backup with ReadBackupData to true, doing a `map.get()` does not "touch" the map entry. So even though we have constant reads from that entry, when `maxIdleSeconds` is reached the entry is evicted from the map.

This seems to be the desired behavior, as I see the code inside `MapProxyImpl`, but I wasn't able to find this "gotcha" in the documentation. Could you please point this out in the documentation? If it's already documented and was my failure to find it, just ignore me :)

I'm using Hazelcast 3.6.2.

**Comment by enesakar** [comment]
You are right, we should document it.

**Comment by Serdaro** [comment]
@BogdanEM , the last paragraph of the section http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#enabling-backup-reads actually provides the gotcha (starting with "Please note that"). But let me make it more visible. Thank you.
