### ISSUE TITLE
Queue messages can get lost on the client heartbeat timeout

### ISSUE THREAD

**Issue by GhostInAMachine** [hazelcast/hazelcast#8360]
When client loses a heartbeat on a connection it will resolve all invocation futures to TargetDisconnectedException for all invocations that were made with this connection. 

Imagine the following:

User is polling a queue with timeout. Then, while he is waiting for response, the heart beat is lost and the future gets resolved to an exception. After that heartbeat is restored, queue item arrives to the client, but at this point future is already resolved and user gets this message:

```
The Future.set() method can only be called once.
```

This essentially leads to the message loss since the item was already removed from the server, but it cannot be consumed on the client.

**Comment by asimarslan** [comment]
I think this is a major problem on core side. It may happen for other distributed types as well. For the heartbeat specific case, one may increase heartbeat time-out.

**Comment by asimarslan** [comment]
@jerrinot Can you comment on this message lost issue?

**Comment by jerrinot** [comment]
a queue does not have any ACK mechanism. if there is a connection closed between HZ server and a consumer then a message can be lost. 

RingBuffer/ReliablyTopic can be used for use-cases where this is not acceptable.

**Comment by swelltt0576** [comment]
@GhostInAMachine  do you have any test for this case? can you send my one ,please?

my email: s.well.tt@qq.com

**Comment by jerrinot** [comment]
closed by mistake

**Comment by sancar** [comment]
@GhostInAMachine Solution is either to increase heartbeat timeout or to use RingBuffer/ReliablyTopic  if it is applicable to your use case. 

Heartbeat timeout should not be happening in a healthy cluster.  My advice is to solve that problem first. Either your heartbeat value is too low, or your network having some issues. 

Closing this for now. Feel free to ask questions if issue remanins.
