### ISSUE TITLE
Portable EntryProcessor is not being called on portable objects [3.6.3]

### ISSUE THREAD

**Issue by dharamthakkar** [hazelcast/hazelcast#8365]
[portabledemo - sample.zip](https://github.com/hazelcast/hazelcast/files/310668/portabledemo.-.sample.zip)

Hi Team,

Server : QueryCollectionsPortableDemo.java
Client : HzClient.java

I have created multiple PortableFactories as I have multiple class definitions. 
[EPPortableFactory - EntryProcessor Portable Factory]
[PersonPortableFactory - Person objects portable factory]

I was trying out various alternatives to query nested collections. But when trying EntryProcessor using,
Map<Integer, Object> r = map.executeOnEntries(new PersonEntryProcessor("left-leg","LL"));

it gives me 0 size result. Even I tried to return all PersonPortable, but still it gives 0 result set

Why I am behind portable?
Well, join operations are not supported by hazelcast. So I am firing join queries on database and creating PersonPortable with nested list<Tuple>

PersonPortable {
 List(Tuple) rows;
}

Tuple {
 name;
value;
}

Thanks & Regards,
Dharam Thacker

**Comment by jerrinot** [comment]
Hi @dharamthakkar,

there is a bug in your `PersonEntryProcessor` class. You are missing assignments. This is your code:
```java
@Override
	public void readPortable(PortableReader reader) throws IOException {
		reader.readUTF("name");
		reader.readUTF("value");
		System.out.println("Read portable was called");
	}
```

but it should be:
```java
	@Override
	public void readPortable(PortableReader reader) throws IOException {
		name = reader.readUTF("name");
		value = reader.readUTF("value");
		System.out.println("Read portable was called");
	}
```

I'm closing this issue as everything is working as designed on Hazelcast side. Feel free to open a new one when you encounter another issue.
