### ISSUE TITLE
[config] Simplify readonly config

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#8366]
Instead of subclassing and overriding methods, we change the behavior. So once a HazelcastInstance is created using some config, we create a deep clone of the original config and that cloned config will then be the configuration for the created HazelcastInstance. Any modification to the original configuration will not matter since it is a different Config instance.

This needs to be documented carefully.

**Comment by pveentjer** [comment]
Current implementation with readonly is frequently broken due to storage of the readonly config. Any thread can call the readonly config, but there is no volatile variable, so there is no happens before relation.

**Comment by mmedenjak** [comment]
Related : https://github.com/hazelcast/hazelcast/issues/10812

**Comment by tombujok** [comment]
Not crucial in 3.x. Moving to 4.0

**Comment by dbrimley** [comment]
4.0 as this breaks stuff.

**Comment by burakcelebi** [comment]
Closed as internal request.
