### ISSUE TITLE
How to create secure communication in Open Source?

### ISSUE THREAD

**Issue by vivekach** [hazelcast/hazelcast#8370]
Hello,

We are ready to buy Open Source code. We want to implemented secure communication between two hazelcast or across all hazelcast which are on same network.

Please let's know how it possible,

Thanks 

Vivek Acharya

**Comment by jerrinot** [comment]
Hello @vivekach,

It's great to hear you are considering buying a support. Hazelcast typically runs in trusted data centres. Secured communication is not included in open source releases.

If you are in untrusted network then you have multiple choices:
- Use transport-level security: VPN, Docker secure network, etc.
- Implement your own security. `NodeExtension` is a good entry point. Bear in mind this is not a part of public API and it can change without any notice.
- Drop an email to `sales@hazelcast.com` and I'm sure my collegues can help you with a commercial arrangement.  This will support further Hazelcast development as a nice side-effect;-) 

This is a community forum and to me it does not feel appropriate to talk about about commercial offerings. Feel free to drop me an email for more info: `jaromir@hazelcast.com`

**Comment by vivekach** [comment]
Thank you so much for reply.

**Comment by jerrinot** [comment]
@vivekach: you are very welcome. feel free to ping me for more info!

**Comment by trajano** [comment]
You can use TLS but that requires enterprise http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#tlsssl
