### ISSUE TITLE
Hazelcast GC overhead issue

### ISSUE THREAD

**Issue by ankitbeohar90** [hazelcast/hazelcast#8383]
Hi,

@jerrinot @enesakar @pveentjer 
```
I have a data file size 250mb and records count is 22259254 in it.
I run below code:-

package org.examples.hazelcast.helloworld;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Map;
import java.util.Queue;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;


public class GettingStarted3 {
	public static void main(String[] args) throws Exception {
        Config cfg = new Config();
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(cfg);
        Map<String, String> mapCustomers = instance.getMap("customers");
        BufferedReader in = new BufferedReader(new FileReader("C:\\Work@Clear\\Hazelcast\\dummydataaaa.txt"));
        String line = "";
        
        while ((line = in.readLine()) != null) {
            String parts[] = line.split(" ");
            mapCustomers.put(parts[0], parts[1]);
        }
        in.close();
 
        System.out.println("Customer with key 1: "+ mapCustomers.get(1));
        System.out.println("Map Size:" + mapCustomers.size());
 
        
    }
}
```

It throws OutOfMemory error at also consume 7GB memory.
I do not have any idea  why its taking so much memory means for 250mb file its taking 7gb.
Configuration is default RAM-8GB also its working with simple java hash map program.

**Comment by pveentjer** [comment]
Make a heap dump when the OOME happens and display the instance count per class. I guess it is caused by the inefficiency of the IMap; there is like 200/300 bytes overhead per key/value.

One way to make it a bit less expensive is to disable map statistics, something like this:
```
MapConfig mapConfig = new MapConfig("customers")
mapConfig.setStatisticsEnabled(false)
```

**Comment by bwzhang2011** [comment]
@pveentjer, is it confirmed in latest hazelcast and any improvement around this before the G.A released ?

**Comment by ankitbeohar90** [comment]
![heap_dump](https://cloud.githubusercontent.com/assets/17118840/16142443/e115a600-3482-11e6-8a08-64233cf3840b.JPG)

@pveentjer Please check attached

**Comment by pveentjer** [comment]
@ankitbeohar90 I don't see an obvious bug. Hazelcast is just inefficient with small values. Solution: give more heap to the process.
