### ISSUE TITLE
creating random uuid key that may cause a memory leak

### ISSUE THREAD

**Issue by ldanielts** [hazelcast/hazelcast#8387]
Hi,

I am starting to use Hazelcast. It is working perfectly and I manage to store and retrieve what I want to be cached in my application.

However, the following log entry has appeared in my catalina.out files and I am worried.

`SEVERE: The web application [/usermgmtbackend] created a ThreadLocal with key of type [com.hazelcast.util.UuidUtil$1] (value [com.hazelcast.util.UuidUtil$1@6becdc5]) and a value of type [java.util.Random] (value [java.util.Random@58b743f8]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.`

Would you please take a look?

Thanks in advance.

Daniel Tavares

**Comment by pveentjer** [comment]
We need to have fast access to a Random so we put it on a thread local. Nothing to be concerned about.

**Comment by ldanielts** [comment]
Ok, thanks a ton for the prompt reply.

**Comment by pveentjer** [comment]
You are welcome.

**Comment by lukasblu** [comment]
Hi @pveentjer and @enesakar  ,

sure, this is not super serious, but it would be nice to cleanup anyway. Thread locals can - or rather should - be removed when you know that you are not using them anymore. E.g. during shutdown ;-)

Best,
Lukas

**Comment by Mario-Eis** [comment]
This IS super serious, if one does automatic deployments in application server environments and the applications shutdown is faulty with each deployment due to running threads that are never ended.

**Comment by Donnerbart** [comment]
This has been fixed in Hazelcast 3.8 via https://github.com/hazelcast/hazelcast/pull/9691
