### ISSUE TITLE
OutOfMemoryError on addition of new Hazelcast box, cluster become unstable and went down.

### ISSUE THREAD

**Issue by vishalnigam20** [hazelcast/hazelcast#8425]
Hi,
I was trying to scale my Hazelcast cluster and was adding 1 more Hazelcast box. As soon as box is added the cluster become unstable and went down. the other instances started throwing OutOfMemoryError.

Here are the details and logs of issue
Details:-
Hazelcast Version:  3.4.5
Java Version : Java 8
Cluster Size : 4
OS:  Linux

Logs:-
```
DATE: com.hazelcast.cluster.impl.operations.JoinRequestOperation
SEVERE: [XX.XX.XX.XX]:PORT [myapplication] [3.4.5] Java heap space
java.lang.OutOfMemoryError: Java heap space
com.hazelcast.nio.serialization.ByteArrayObjectDataOutput.toByteArray(ByteArrayObjectDataOutput.java:292)
com.hazelcast.nio.serialization.StreamSerializerAdapter.toData(StreamSerializerAdapter.java:56)
com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:227)
com.hazelcast.nio.serialization.SerializationServiceImpl.toData(SerializationServiceImpl.java:208)
com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:180)
com.hazelcast.spi.impl.BasicOperationService.send(BasicOperationService.java:349)
com.hazelcast.cluster.impl.ClusterServiceImpl.isJoinRequestFromAnExistingMember(ClusterServiceImpl.java:711)
com.hazelcast.cluster.impl.ClusterServiceImpl.handleJoinRequest(ClusterServiceImpl.java:602)
com.hazelcast.cluster.impl.operations.JoinRequestOperation.run(JoinRequestOperation.java:40)
com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:750)
```

Events:- 
A new box was added to the cluster and it joined the cluster
Some Socket exception thrown by hazelcast 
Box which was added automatically left the cluster
Box again came back and re joined the cluster
Box become unresponsive and other boxes in cluster was trying to contact it
Other boxes in cluster were constantly trying to contact the that box in cluster 
Other boxes start throwing OutOfMemoryError

**Comment by enesakar** [comment]
What are the heap size in each node (JVM) ? 
Can you also provide some rough estimate about the amount you store in each box?

**Comment by vishalnigam20** [comment]
Thanks for getting back.
I have 5gb of JVM Heap space on each box.
Whole cluster with 4 boxes(excluding new box) holds 0.25-5 million objects of 12kb of pure payload. Just to add more information back up is on for full safety and sync mode is set to FULL_SYNC. 

Please let me know if further details required.

**Comment by vishalnigam20** [comment]
Any updates please?

**Comment by tombujok** [comment]
@vishalnigam20 Could you plz retest with 3.6.4 or 3.7-SNAPSHOT? 
If it fails plz post your whole configuration

**Comment by vishalnigam20** [comment]
I am afraid its not possible for me, the scenario explained is from live application. I would not be in position to upgrade live application to another version as it will be a huge risk and may have impact on live system. (Please let me know if you think otherwise.)

On the other hand any advice on precautionary measures to avoid such issues will be helpful.

**Comment by mmedenjak** [comment]
@vishalnigam20 you can run your app with `-XX:+HeapDumpOnOutOfMemoryError` which will produce a heap dump file on `OutOfMemoryError`. Can you analyse that heap dump and see which objects take up the most heap space? 
It is possible that the replication operation in addition to the map data takes up more space than what the JVM can handle. You can try increasing the partition count so that the replication operation for each partition is smaller. The migrations might take longer but the cluster might be more stable. Please reply when you have more information.

**Comment by vishalnigam20** [comment]
Hi @mmedenjak ,
We did analyze Heap Dump at the time of issue, it was last year so couldn't remember exactly but it was mostly full of byte streams. And no other direct indication of related objects.

Yes, That was also my assumption for such issue, we significantly increased hardware size(not an ideal solution though) and kept aggressive TTLs since then don't see that problem. But thanks for sharing the partitioning information, it seems a good point.

**Comment by mmedenjak** [comment]
Ok, I'll close this issue then, feel free to open a new one when you have more information or encounter a new problem.
