### ISSUE TITLE
Hazelcast 3.7 EA release

### ISSUE THREAD

**Issue by ankitbeohar90** [hazelcast/hazelcast#8432]
Hi Hazelcast,

@enesakar @eminn 

As per your release announcement "http://blog.hazelcast.com/category/releases/"  spark connector is available but if I referenced your repo "https://github.com/hazelcast/hazelcast-spark/"  I put "import com.hazelcast.spark.connector" in my hazelcast 3.7EA code.
So can you guys provide me exact spark connector lib name so I can get that.

**Comment by eminn** [comment]
Hi @ankitbeohar90 ,

It is not available with EA release, but you can use it with our 3.7-SNAPSHOT release. 

So you can try it like below

```xml
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>3.7-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-spark</artifactId>
    <version>0.1-SNAPSHOT</version>
</dependency>

<repository>
    <id>sonatype-snapshots</id>
    <name>Sonatype Snapshot Repository</name>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

**Comment by eminn** [comment]
Hi @ankitbeohar90, I am closing this issue, if you have any problems with the Spark Connector you can create an issue to the Spark Connector repository using this link : https://github.com/hazelcast/hazelcast-spark/issues .
