### ISSUE TITLE
Hazelcast Demo application depends on JDK

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#8445]
JRE should be enough on all platforms. 

See [this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/hazelcast/yHLdPg4gMsU) for details. 

See also:
![image](https://cloud.githubusercontent.com/assets/158619/16301973/20a1b430-3951-11e6-9b20-6cf1290ab2eb.png)

**Comment by emrahkocaman** [comment]
Interesting! 
I've made a push to my code samples fork (https://github.com/emrahkocaman/hazelcast-code-samples/commit/177b8f3baae4fad66c57af113b5cbcc6f090b77d) but it closed this issue . Reopening it.
