### ISSUE TITLE
IdGeneratorStressTest.testMultipleThreads

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8447]
```
java.lang.OutOfMemoryError: Java heap space
	at com.hazelcast.util.collection.LongHashSet.<init>(LongHashSet.java:54)
	at com.hazelcast.concurrent.idgen.IdGeneratorStressTest.testMultipleThreads(IdGeneratorStressTest.java:73)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5320/testReport/junit/com.hazelcast.concurrent.idgen/IdGeneratorStressTest/testMultipleThreads_clusterSize_1_/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5320/testReport/junit/com.hazelcast.concurrent.idgen/IdGeneratorStressTest/testMultipleThreads_clusterSize_6_/

**Comment by jerrinot** [comment]
@hasancelik: do you have a heapdump?

**Comment by hasancelik** [comment]
@jerrinot: unfortunately we do not have for this build.

**Comment by tombujok** [comment]
I tried to reproduce it locally without luck though.

**Comment by tombujok** [comment]
Hasan reduced the number of ids per thread in a commit which should solve it. Plz reopen if reappears.
