### ISSUE TITLE
Hazelcast 3.6 server not compatible with Hazelcast 3.5 client

### ISSUE THREAD

**Issue by dfabulich** [hazelcast/hazelcast#8457]
Download Hazelcast 3.6.3 (latest as of today) and Hazelcast 3.5.5.

Create this test Nashorn script as `test.js`:
```javascript
config = new com.hazelcast.client.config.ClientConfig();
config.getNetworkConfig().addAddress("localhost:5701");
hazelcast = com.hazelcast.client.HazelcastClient.newHazelcastClient(config);
map = hazelcast.getMap("test")
println(map.keySet().size())
```

In the 3.6.3 directory, run `bin/start.sh`, then run the Nashorn script:

```bash
jrunscript -cp lib/hazelcast-3.6.3.jar:lib/hazelcast-client-3.6.3.jar test.js
```

The script will run successfully and print the number 0.

Run the Nashorn script again in the 3.5.5 directory with the 3.5.4 jars.

```bash
jrunscript -cp lib/hazelcast-3.5.4.jar:lib/hazelcast-client-3.5.4.jar test.js
```

Expected: Client 3.5 should behave the same as Client 3.6 when talking to a 3.6 server.

Actual: The 3.5 client hangs forever when connecting to the 3.6 server.

```
$ jrunscript -cp lib/hazelcast-3.5.4.jar:lib/hazelcast-client-3.5.4.jar test.js
Jun 27, 2016 9:38:33 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.5.4] is STARTING
Jun 27, 2016 9:38:33 PM com.hazelcast.core.LifecycleService
INFO: HazelcastClient[hz.client_0_dev][3.5.4] is STARTED
```

**Comment by gurbuzali** [comment]
Thank you for detailed analysis but we do not support different minor versioned clients and servers to work with each other for versions below 3.6. Please take a look at the note in [Java Client](http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#hazelcast-java-client) section of our reference manuel

**Comment by gurbuzali** [comment]
```
For Hazelcast 3.5. release, a new client library is introduced in the release package: hazelcast-client-new-<version>.jar. This is an experimental version of the library. It is the new Java native client library that has the support for different versions of clients in a Hazelcast cluster. This support is not valid for the releases before 3.5 and can be used fully starting with Hazelcast 3.6.
```
