### ISSUE TITLE
NearCacheTest.testGetAsyncPopulatesNearCache

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8459]
```
java.lang.AssertionError: Near cache owned entry count should be > 400 but was 66
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAsyncPopulatesNearCache(NearCacheTest.java:554)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5353/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAsyncPopulatesNearCache_batchInvalidationEnabled_true_/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/527/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAsyncPopulatesNearCache_batchInvalidationEnabled_true_/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast/247/testReport/junit/com.hazelcast.map.nearcache/NearCacheTest/testGetAsyncPopulatesNearCache_batchInvalidationEnabled_false_/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/248/

**Comment by ahmetmircik** [comment]
should be fixed by https://github.com/hazelcast/hazelcast/commit/225cd0a78a8ae00aa413d344f00a8ca41131223c

**Comment by hasancelik** [comment]
```
java.lang.AssertionError: Near cache owned entry count should be > 400 but was 277
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.nearcache.NearCacheTest.testGetAsyncPopulatesNearCache(NearCacheTest.java:556)
```
https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/248/com.hazelcast$hazelcast/testReport/com.hazelcast.map.nearcache/NearCacheTest/testGetAsyncPopulatesNearCache_batchInvalidationEnabled_false_/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/250/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testGetAsyncPopulatesNearCache_batchInvalidationEnabled_true_/

**Comment by ahmetmircik** [comment]
closed via https://github.com/hazelcast/hazelcast/commit/361bd27d85a451c7c5a5c26d33d12d603e1f05a9 for member and https://github.com/hazelcast/hazelcast/commit/7d756ad906d3c1dcbd55ea29db70c829c617b45d for client
