### ISSUE TITLE
ClassNotFoundException: javax/cache/Cache

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#8475]
HZ 3.7-EA. It requires JCache jar right on startup even when I don not use any JCache classes in my code. It is not required in HZ 3.6.3. 
Please have a look.

Thanks, Denis.

**Comment by vbekiaris** [comment]
I guess you are using Hazelcast with Spring framework; if that's the case, there's already #8352 which has been addressed in current `master` branch.

**Comment by dsukhoroslov** [comment]
Yes, looks like this is my case. Ok, I'm closing the issue then.

Thanks, Denis.

**Comment by vbekiaris** [comment]
Great, thank you Denis, your contributions are always appreciated.
