### ISSUE TITLE
failed to resolve value placeholder in spring context in hazelcast 3.6

### ISSUE THREAD

**Issue by LetheSham** [hazelcast/hazelcast#8500]
hot-restart tag cannot resolve placeholder for value at both "enabled" and "fsync".
e.g.: `<hz:hot-restart enabled="${hazelcast.hot-restart}" fsync="${hazelcast.hot-restart.fsync}"/>`
will throw:
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 212 in XML document from class path resource [hz.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 212; columnNumber: 76; cvc-datatype-valid.1.2.1: '${hazelcast.hot-restart.fsync}' is not a valid value for 'boolean'.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)

**Comment by mesutcelik** [comment]
Those have to be marked as `parameterized-boolean`
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.7.xsd#L2651
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/resources/hazelcast-spring-3.7.xsd#L2659
