### ISSUE TITLE
MulticastConfig - misleading method name and javadoc

### ISSUE THREAD

**Issue by landro** [hazelcast/hazelcast#8502]
The method name and javadoc in MulticastConfig.java is misleading in hazelcast 3.6.4 and previous versions. 

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/MulticastConfig.java#L263

```
    /**
     * Enables or disables the loopback mode in the multicast discovery mechanism.
     *
     * @param enabled true to enable the loopback mode, false to disable.
     * @return the updated MulticastConfig
     */
    public MulticastConfig setLoopbackModeEnabled(boolean enabled) {
        this.loopbackModeEnabled = enabled;
        return this;
    }
```

The value is used to call the setLoopbackMode on the java MulticastSocket where a boolean value of true will disable loopback of multicast datagrams according to javadoc:

http://download.java.net/jdk7/archive/b123/docs/api/java/net/MulticastSocket.html#setLoopbackMode(boolean)

```
    /**
     * Disable/Enable local loopback of multicast datagrams
     * The option is used by the platform's networking code as a hint
     * for setting whether multicast data will be looped back to
     * the local socket.
     *
     * <p>Because this option is a hint, applications that want to
     * verify what loopback mode is set to should call
     * {@link #getLoopbackMode()}
     * @param disable {@code true} to disable the LoopbackMode
     * @throws SocketException if an error occurs while setting the value
     * @since 1.4
     * @see #getLoopbackMode
     */
    public void setLoopbackMode(boolean disable) throws SocketException {
        getImpl().setOption(SocketOptions.IP_MULTICAST_LOOP, Boolean.valueOf(disable));
    }
```

It would probably make sense to deprecate the setLoopbackModeEnabled method, and create a new one which uses the same semantics as the setLoopbackMode()

**Comment by tombujok** [comment]
I can see it's misleading to you but I'd say that the JDK method is even more misleading. Don't you think that the HZ method is less misleading to people that don't know the JDK method by heart?

**Comment by enesakar** [comment]
closing issue. please use mail group for further discussion.
