### ISSUE TITLE
Implement new method in Spring Cache Interface introduced in 4.3

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast#8504]
Spring added a new method to make sure that multiple calls form multiple threads to cached methods only call the method once, with an option. Is it possible to implement this method ?

**Comment by tombujok** [comment]
Could you point out the method in Spring Javadoc? 
Maybe you would like to submit a PR with this change? 
It doesn't seem to be a big feature and your'll get life-long community credits ;)

**Comment by gokhanoner** [comment]
It seems that this method is implemented in hazelcast 3.7 ;)

https://github.com/hazelcast/hazelcast/blob/master/hazelcast-spring/src/main/java/com/hazelcast/spring/cache/HazelcastCache.java#L70

**Comment by tombujok** [comment]
Great. thx for feedback!
