### ISSUE TITLE
ExecutorService.SYSTEM_EXECUTOR's Thread Pool Core Size set to Runtime.getRuntime().getAvailableProcessors

### ISSUE THREAD

**Issue by juanavelez** [hazelcast/hazelcast#8528]
Ran into a situation using a VM where (unbeknownst to me) the available number of cores was set to 1, so the SYSTEM_EXECUTOR's Thread pool core size was set to 1, preventing (in my case) any merge from happening as the tasks to merge would never start because the original task (ClusterMergeTask::run) that would submit the merge tasks to run would be running in that only available thread.

Would it be possible to allow the SYSTEM_EXECUTOR (and others) to have a core size that it is not dependent on the number of available cores, maybe as a configuration property?

**Comment by vbekiaris** [comment]
@juanavelez you can override the default size of the `SYSTEM_EXECUTOR` (or any other hazelcast core executor) using hazelcast configuration as you would configure any of your own executors. For example this XML config snippet should set your `SYSTEM_EXECUTOR` thread pool size to 8:
```
    <executor-service name="hz:system">
        <pool-size>8</pool-size>
    </executor-service>
```

If you feel there is something else to investigate further, please do not hesitate to reopen this issue.
