### ISSUE TITLE
add group name to all HZ threads

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#8542]
There are a number of HZ threads with name like "cached16", "scheduled" or "pool-1-thread-2". Do you mind to add the thread's HZ cluster name to the thread name, like it is done for partition operation threads, event threads, etc? In my case I have several HZ instances working in the same JVM, so it is not clear to which HZ instance the "cached16" thread belongs.

Thanks, Denis

**Comment by pveentjer** [comment]
:+1:

**Comment by dsukhoroslov** [comment]
Hi, @jerrinot. Any chance to implement it for 3.8?

**Comment by jerrinot** [comment]
@dsukhoroslov: let's see what we can do. 
I see the cached threads already have a Hazelcast instance name in names in the 3.8-SNAPSHOT. I see: `hz._hzInstance_1_dev.cached.thread-1`

However I see `MetricsRegistry-thread-2` and probably there is a few others.

**Comment by jerrinot** [comment]
related to https://github.com/hazelcast/hazelcast/issues/9210
