### ISSUE TITLE
When a key of a ReplicatedMap is a HashMap (or contains a HashMap) it may fail to get/remove the value

### ISSUE THREAD

**Issue by eysegal** [hazelcast/hazelcast#8547]
When using ReplicatedMap we saw that we get a lot of cache misses when the key contains a HashMap. We then understood that even though two HashMaps are equal, if they have different internal table sizes then they are considered as 2 different keys for retrieving the appropriate partition.

See the example unit test, ran on ReplicatedMapTest (the last assert fails the test):

```
@Test
public void testMapKey() {
  TestHazelcastInstanceFactory nodeFactory = createHazelcastInstanceFactory(1);

  HazelcastInstance instance1 = nodeFactory.newHazelcastInstance(buildConfig(InMemoryFormat.OBJECT));
  final ReplicatedMap map1 = instance1.getReplicatedMap("default");
  Map<String, Object> keyMap1 = new HashMap<String, Object>(5); // The size set is important as it creates the map with some size but map.keySet creates the map with the default size
  keyMap1.put("A", 0);
  keyMap1.put("B", -1);
  map1.put(keyMap1, "TestValue");
                
  Object keyMap2 = map1.keySet().iterator().next(); // This creates a new key which is a duplicate of the original key        
        
  assertEquals(keyMap1, keyMap2);
  assertEquals("TestValue", map1.get(keyMap1));
  assertEquals("TestValue", map1.get(keyMap2));
}
```

**Comment by eminn** [comment]
Hi @eysegal,

When you put your key/value pair to hazelcast, it will serialize it into `Data` object, which is an internal representation of your data, and sent over the wire or made some calculations to find where this data is located.

While converting your `HashMap` key to `Data`, Java Serialization will kick in and convert your `HashMap` contents to a byte array. In this process the internal state of the `HashMap` (loadFactor, threshold etc.) also has an effect on your serialized byte array.

In the de-serialization step, Java serialization rebuilds your elements correctly, but the internal state is not the same anymore. (which is your keyMap2 in your use case) So when this de-serialized object serialized to the byte array, the resulting byte array is different from the byte array serialized in the first place. To make it concrete, `toData(keyMap1) != toData(keyMap2)` .

That is the reason why you cannot access your k/v pair via `map1.get(keyMap2)`.

You can check this behavior in the following test without hazelcast being involved; 

```
     @Test
    public void testHashMapSerialization() throws Exception {
        HashMap map1 = new HashMap();
        map1.put("A", 0);
        map1.put("B", -1);


        ByteArrayOutputStream byteArrayOutputStream1 = new ByteArrayOutputStream();
        ObjectOutputStream outputStream1 = new ObjectOutputStream(byteArrayOutputStream1);
        outputStream1.writeObject(map1);
        outputStream1.flush();
        byte[] bytes1 = byteArrayOutputStream1.toByteArray();


        ByteArrayInputStream byteArrayInputStream1 = new ByteArrayInputStream(bytes1);
        ObjectInputStream objectInputStream1 = new ObjectInputStream(byteArrayInputStream1);
        HashMap map2 = (HashMap) objectInputStream1.readObject();


        ByteArrayOutputStream byteArrayOutputStream2 = new ByteArrayOutputStream();
        ObjectOutputStream outputStream2 = new ObjectOutputStream(byteArrayOutputStream2);

        outputStream2.writeObject(map2);
        outputStream2.flush();

        byte[] bytes2 = byteArrayOutputStream2.toByteArray();
        assertTrue(Arrays.equals(bytes1, bytes2));
    }

```

**Comment by eminn** [comment]
I am closing the issue since there is not much we can do about this.

**Comment by eysegal** [comment]
I understand, but what you're basically saying is that HashMaps should not be used as keys in a ReplicatedMap?
Is there a way to workaround this limitation?

**Comment by eminn** [comment]
Hi @eysegal,

Yes, HashMap is not a suitable key for ReplicatedMap.

You can register a custom serializer for your composite key by having a look at this : http://docs.hazelcast.org/docs/latest-dev/manual/html-single/index.html#custom-serialization
