### ISSUE TITLE
Allow access to attributeName for AbstractPredicate

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#8554]
I am trying to create my custom predicate, and need read access to attributeName field defined in AbstractPredicate. Currently this field has package-level access. 
Is it possible to add protected String getAttributeName() method?

https://github.com/hazelcast/hazelcast/blob/e29b970b16a1b9d36a1e0b9318719b52fffa32d6/hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AbstractPredicate.java#L43

**Comment by tombujok** [comment]
The `AbstractPredicate` is in the `impl` package thus it should not be extended by the users. This is not public API thus it may change between major (or minor) releases.

In order to build your own predicate just implement the `Predicate` or `IndexAwarePredicate` interface.
