### ISSUE TITLE
MigrationThread leak

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast#8560]
`MigrationThread` can leak after shutting down or even forcefully terminating Hazelcast. It retains the entire `HazelcastInstance`.

`InternalPartitionServiceImpl`:
```java
    @Override
    public void shutdown(boolean terminate) {
        logger.finest("Shutting down the partition service");
        migrationManager.stop();
        reset();
    }
```
`MigrationManager`:
```java
void stop() {
        migrationThread.stopNow();
    }
```
`MigrationThread`:
```java
    void stopNow() {
        queue.clear();
        interrupt();
    }
```
Thread is interrupted, but not joined. In particular, the thread will block forever in some cases, one of which is the following:
`RepairPartitionTableTask#commitPromotionsToDestination`:
```java
                PromotionCommitOperation op = new PromotionCommitOperation(...);
                Future<Boolean> future = nodeEngine.getOperationService()
                        .createInvocationBuilder(SERVICE_NAME, op, destination)
                        .setTryCount(Integer.MAX_VALUE)
                        .setCallTimeout(Long.MAX_VALUE).invoke();
                boolean result = future.get();
```

**Comment by mdogan** [comment]
This looks like an invocation system issue to me. Invocation is not notified when instance is being shutdown.

**Comment by mtopolnik** [comment]
What about Hazelcast leaving live threads behind?  Shouldn't we join on the migration thread?

**Comment by metanet** [comment]
MigrationThread is already supposed to complete here. Its task queue is cleared during shutdown. So, it should complete its ongoing task (if there is any) and complete. Our guess here is even if the system is being shutdown, a new invocation can be initiated and it will not be notified. This is not a partition-service specific problem. We are trying to verify this issue.

**Comment by mtopolnik** [comment]
Letting the migration thread die on its own pace is against our fail-fast doctrine and has presently resulted in the loss of 2 engineering man-days. I have submitted a PR which makes the shutdown procedure wait until the thread is dead.

Also noteworthy is that, with that in place, the `CacheHotRestartTest` is not blocking and timing out, instead it is passing.

**Comment by metanet** [comment]
As I stated earlier, we were suspecting a problem in the invocation system, and now we reproduced it. The problem is not solely about the migration thread.

**Comment by mtopolnik** [comment]
This issue is solely about the absence of fail-fast behavior in the migration thread shutdown.

**Comment by mdogan** [comment]
_absence of fail-fast behavior in the migration thread shutdown_ only causes leaking the migration thread and the instance behind it. I agree it's a problem on its own and needs fixing.

But bigger problem is, even with fail fast behaviour, shutdown may block forever.

**Comment by metanet** [comment]
Yes, that is why I am saying that the problem is not solely about migration thread.

**Comment by mtopolnik** [comment]
That means we all agree here. This issue has a narrow focus, but the problem I met also involves further issues downstream from it, within the invocation system.
