### ISSUE TITLE
Enable near-cache enabled map creation outwith hazelcast/config

### ISSUE THREAD

**Issue by Syneil** [hazelcast/hazelcast#8562]
Using Spring 3.2.11 and Hazelcast 3.6.2.

We have a modular enterprise application running over a single hazelcast instance with data sharing/caching requirements deferred to each module. This means that if service B needs an IMap with near-caching enabled, the near-cache configuration should be defined in its own context, NOT in the "parent" module where the hazelcast instance is defined.

It seems that currently, near-cache configurations must be under /beans/hazelcast/config/map/near-cache, which is inviable for our architecture.

Any corrections or advice very welcome!
Thanks

**Comment by mesutcelik** [comment]
Hi @Syneil ,

sorry for the late reply!

You might be achieving this by defining each map config in its own module context and importing them to parent module configuration. It is like structuring your configs along with your module structuring.

I would also suggest to ask such questions in [Hazelcast Google Groups](https://groups.google.com/forum/#!forum/hazelcast) which is more natural for discussions. 

I am closing this issue so please feel free to continue in Hazelcast Google Groups
