### ISSUE TITLE
Something wrong with the schema link -  https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd

### ISSUE THREAD

**Issue by sudan92hard** [hazelcast/hazelcast#8578]
Hi,
I am getting the following error for the schema link - 
https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd

As a result I am not able to start my application in spring. The spring framework Root Context is breaking during tomcat server start up. I think this is due to the SSL Certificate Problem. Anyone help me on this regard?

**Comment by sudan92hard** [comment]
I am getting the following error message:

hazelcast.com uses an invalid security certificate. The certificate expired on Saturday, July 23, 2016 12:05 PM. The current time is Monday, July 25, 2016 11:25 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by varun56** [comment]
We are also facing this issue and app is unable to start.

SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 24 in XML document from ServletContext resource [/WEB-INF/spring/root-context.xml] is invalid; nested exception is org.xml.sax.SAXParseException; lineNumber: 24; columnNumber: 41; cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'.
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:399)

**Comment by jerrinot** [comment]
Hello,

we are aware of the situation and our web admin is working on it as I'm writing this. I'm looking into a possible workaround - I'll post it here if I find one. 

@sudan92hard, @varun56: could you share you spring config? schemas definitions should be enough.

**Comment by varun56** [comment]
@jerrinot - Thanks. Please find the config as below.

<beans xmlns="http://www.springframework.org/schema/beans"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xmlns:context="http://www.springframework.org/schema/context"
			xmlns:cache="http://www.springframework.org/schema/cache"
			xmlns:hz="https://www.hazelcast.com/schema/spring"
			xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.2.xsd
			https://www.hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

**Comment by noctarius** [comment]
See the comment on the mail. Please change your schema url to use http instead of https.

**Comment by jerrinot** [comment]
@varun56: 
as a workaround you can try to change the schema location from `https://www.hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd` to `http://www.hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd`

this should work with no internet connection at all as a Spring internal resolution should kick in. See https://github.com/jerrinot/hazelcast/blob/d964efcda0fcf1ebb8e1ec9af1ba47aa7dcada0d/hazelcast-spring/src/main/resources/META-INF/spring.schemas#L1-L1 <- it defined a mapping for  `http://www.hazelcast.com/schema/spring https://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd` to a file which is packages inside the Hazelcast Spring JAR.

**Comment by noctarius** [comment]
PS: the problem is, that the spring.schema file doesn't contains redirect for https right now. We'll fix it and we're terribly sorry for the inconvenience.

**Comment by jerrinot** [comment]
The certificate problem has been fixed. Once more sorry for inconvenience. 

We are going to amend the schema handlers mapping so even the HTTPS locations will use local mapping.

**Comment by varun56** [comment]
thanks @jerrinot @noctarius 
This issue is resolved now. Thanks again for your quick action.
