### ISSUE TITLE
Under high load and high ICache.getAsync calls near-cache updates may cause OOM

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#8593]
Client updates ICache near cache using the ClientExecutionService userExecutor in an async way for getAsync API. The queue for the userExecutor is unbounded. If the userExecutor threads are slower in consuming these tasks in the executors queue, the queue may grow and this may cause OutOfMemory error. The queue items has reference to Invocation, Request ClientMessage and Response ClientMessage and these may be big objects.

**Comment by sancar** [comment]
Fixed via https://github.com/hazelcast/hazelcast/pull/8649
