### ISSUE TITLE
CachePartitionIteratorMigrationTest Timeout

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8597]
```
05:24:25 Running com.hazelcast.cache.CachePartitionIteratorMigrationTest
08:31:49 Build timed out (after 300 minutes). Marking the build as aborted.
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.8/293/console

**Comment by jerrinot** [comment]
@hasancelik: do you know why the logs weren't uploaded to S3? There isn't much we can do w/o having the logs.

**Comment by eminn** [comment]
Closing this since this is an ignored test. The problem cannot be related to this test. See https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/cache/CachePartitionIteratorMigrationTest.java
