### ISSUE TITLE
Hazelcast Cluster Configuration and TCP-IP Interfaces

### ISSUE THREAD

**Issue by marcelalburg** [hazelcast/hazelcast#8598]
Hello,

currently it's not possible to add an interface to the tcp-ip section.

http://docs.hazelcast.org/docs/3.5/manual/html/networkconfiguration.html

network -> join -> tcp-ip -> interface.

But i cannot found a setter in:

`com.hazelcast.config.Config.getNetworkConfig().getJoin().getTcpIpConfig()`

Thanks
Marcel

**Comment by jerrinot** [comment]
@marcelalburg: Hi, what you are trying to achieve? 
the `<interface>` element in XML `tcp-ip` joiner is just to specify where are additional members listening. It's actually an [alias](https://github.com/jerrinot/hazelcast/blob/ba493a51464e78fe2b3a265bc38bb59e7b8622d9/hazelcast/src/main/java/com/hazelcast/config/XmlConfigBuilder.java#L814-L814) for `<members/>`

If you are trying to select an interface where a Hazelcast member will bind itself to then have a look at [this](https://github.com/jerrinot/hazelcast/blob/eef987b9920f3f7b4c506e433b0d067cab9ba93c/hazelcast/src/main/java/com/hazelcast/config/NetworkConfig.java#L207-L207)

**Comment by vishal7038** [comment]
I am using hazelcast-3.5. 
You can see the IPs inside TcpIpConfig like this:
Loop through your IPs and set it like this:

`config.getTcpIpConfig().addMember(member);`

Thanks

**Comment by pierregangloff** [comment]
Thanks jerrinot! That is one thing that the hazelcast team should review.

I was pulling my hair for such a long time only to find your answer that explained the diff between the < interface > inside tcp [which is an alias to member] and the < interface > inside network (which is used to define the network interface]. I had the set it in the wrong place!!! Thanks!!

Yes indeed (I would suggest hazelcast stops using "interface" as an alias to avoid confusing newbies like me but I understand this is likely for backwards compatibility for an earlier bad decision or something):

Set<String> memberTags = new HashSet<String>(Arrays.asList("interface", "member", "members"));

**Comment by jerrinot** [comment]
@pierregangloff that's certainly a good recommendation and something we should fix in the upcoming Hazelcast 4.0. cc @mmedenjak

**Comment by mmedenjak** [comment]
Thanks for the heads-up, already part of our plans for config cleanup :)

**Comment by pierregangloff** [comment]
if it doesn't make it (to avoid introducing a breaking change for people who want to get a "drop in jar replacement"), that explanation could make it into the documentation (WARNING: when you define network interfaces, make sure to put it under the < network > element). Thank you all for this great project!!
