### ISSUE TITLE
userExecutor usage and internalExecutor usages mixed up

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#8651]
Client near cache implementation uses userExecutor which is also used by other purposes such as making callbacks to lifecycle listeners. A client may block operation of near cache updates by a slow lifecycle listener. This needs to be addressed.

**Comment by sancar** [comment]
This change seems like caused by a refactoring done  here https://github.com/hazelcast/hazelcast/pull/7939

It seems like it does not affect just near cache but almost all executor usages. Changing the title accordingly.
