### ISSUE TITLE
[transaction] [map] 3.7 MapTransactionTest keys have been incremented unexpectedly, 

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#8696]
3.7 xlarge simulator runs, we hit this exception,  for the 2nd time.

http://54.87.52.100/~jenkins/workspace/Release/3.7/ee/xlarge/output-MapTransactionTest-keysInc/

```
ERROR 05:45:12 Failure #1 C_A6_W1 MapTransactionTest WORKER_EXCEPTION[java.lang.AssertionError: MapTransactionTest: 8 keys have been incremented unexpectedly out of 1000 keys expected:<0> but was:<8>]
FATAL 05:45:27 1 critical failures have been detected!!!
FATAL 05:45:28 1 critical failures have been detected
INFO  05:47:32 Done!
```

**Comment by bwzhang2011** [comment]
@gurbuzali, any update with such issue ? as 3.7 is about to be released soon.

**Comment by Danny-Hazelcast** [comment]
we have a replication of this issue,  during 3.7.1 OS xlarge runs

full logs at http://54.87.52.100/~jenkins/workspace/Release/3.7.1/os/xlarge/output-fail-Txn/

**Comment by Danny-Hazelcast** [comment]
again while running 3.7.1 we replicated this issue 

full logs at http://54.87.52.100/~jenkins/workspace/Release/3.7.1-2nd/os/xlarge/output-Fail-Txn/

**Comment by Danny-Hazelcast** [comment]
so it seems we only see this issue in xlarge cluster size,  using EE or OS
hope fully with the extra logging in latest fails, we can progress this issue

**Comment by bwzhang2011** [comment]
@Danny-hazelcast, any update with such issue ?

**Comment by Danny-Hazelcast** [comment]
no update for this issue

**Comment by mmedenjak** [comment]
@Danny-Hazelcast where is the test code? We will probably move this into backlog because transactions need a serious overhaul but I would like to see what is failing here

**Comment by Danny-Hazelcast** [comment]
MapTransaction@class = com.hazelcast.simulator.tests.map.MapTransactionTest

https://github.com/hazelcast/hazelcast-simulator/blob/master/tests/tests-hz/src/main/java/com/hazelcast/simulator/tests/map/MapTransactionTest.java

**Comment by mmedenjak** [comment]
The issue seems to refer to the lack of proper transaction isolation. Moving to backlog with other transaction issues.

**Comment by Danny-Hazelcast** [comment]
issue not failing in recent simulator runs
