### ISSUE TITLE
Aggregations using SupplierConsumingMapper for the Mapper stage are inefficient

### ISSUE THREAD

**Issue by magiccrafter** [hazelcast/hazelcast#8711]
Here is the complete description:
http://stackoverflow.com/questions/26256381/is-hazelcasts-built-in-countaggregation-really-inefficient

**Comment by bwzhang2011** [comment]
@magiccrafter, so any update with such issue and how could you improve map-reduce in hazelcast for countaggregation ?

**Comment by noctarius** [comment]
Engineering is working on a better solution. The utilized chunking approach in the mapreduce framework didn't perform to expectations (and yeah I wronte it but I admit it failed :-))

**Comment by bwzhang2011** [comment]
@noctarius, glad to hear that, mapreduce in hazelcast seems a better solution but no popular as its cache use cases, hope it could be improved as expected. we're looking forward some simple solution replacement to hadoop mapreduce.

**Comment by enesakar** [comment]
we have changed design of aggregation in 3.8 for efficiency. please retry with 3.8 early access and reopen if needed.
