### ISSUE TITLE
Client tasks should be bounced back when a member has not completed start yet

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#8715]
Clients tasks should not be processed until a member start is completed. "start completed" means (among other things) that loading for HotRestart was completed. 

Serving client requests before loading is completed lead to consistency issues. For example: 
- a member with HotRestart was just started
- entry is stored in the persistence store, but it is not loaded yet into `RAMStore` -> the entry does not exist for a client.  
- loading is finished
- the entry is created "out-of-thin-air" (for the client)

See: `NodeExtension.isStartCompleted()`

Some tasks still have to be processed even when member start is not completed: e.g. the Heartbeat task.

**Comment by ihsandemir** [comment]
The PRs are merged. Closing the issue.
