### ISSUE TITLE
Feature Request: Consistent interface for IMap and TransactionalMap

### ISSUE THREAD

**Issue by ebrandsberg** [hazelcast/hazelcast#8729]
In creating code that will conditionally need to operate on data in Hazelcast, I noticed that the two classes IMap and TransactionalMap have different methods, and don't have a consistent interface for the more advanced functions.  For example, I have to use code such as the following:

```
        if (map instanceof IMap)
            keys = ((IMap)map).keySet(new SqlPredicate(predicate));
        else if (map instanceof TransactionalMap)
            keys = ((TransactionalMap)map).keySet(new SqlPredicate(predicate));
```

and:

```
                if (map instanceof IMap)
                    ((IMap)map).set(key, rowData, ttl, TimeUnit.MILLISECONDS);
                else if (map instanceof TransactionalMap)
                    // transactionalMap's set doesn't have the ttl options, but the put does.
                    ((TransactionalMap)map).put(key, rowData, ttl, TimeUnit.MILLISECONDS);
```

If these various calls had a single interface, it would make mixed transactional/non-transactional code much easier to deal with.

**Comment by jerrinot** [comment]
@ebrandsberg: this is a good idea, many thanks!
