### ISSUE TITLE
Spring xml config: the smart routing attribute defaults to false while the docs say its enabled

### ISSUE THREAD

**Issue by fmacicasan** [hazelcast/hazelcast#8746]
Hello,

The smart routing attribute defaults to false while the documentation (and the ClientNetworkConfig) defaults to true.

Is there any reasoning behind this choice?

We relied on the "docs default" and now we are experiencing "Wait for owner connection is timed out" errors (which shouldn't be triggered if smart routing is enabled).

`<xs:attribute name="smart-routing" use="optional" type="xs:boolean" default="false"/>`

Note: We are using hazelcast 3.3.3, but the spring config default is the same in the latest release.

Thanks for the info!
Florin.

**Comment by jerrinot** [comment]
@fmacicasan: we good catch. I think it's an error, many thanks thanks for reporting!
