### ISSUE TITLE
Hazelcast Stream Data from Map

### ISSUE THREAD

**Issue by amit2103** [hazelcast/hazelcast#8753]
Hi,

What is the standard way to stream data from Hazelcast maps  ? I have around 1 million objects in map, and I want to iterate from each of them for a usecase. Is java 8 keys.stream() a good fit/ I dont want to load all the data from the stream but may be do it in chunks if possible.

Does paging predicates work with KeySet?

**Comment by tombujok** [comment]
Hi

Yes, `PagingPredicate` is supported in the `keySet()` method.

Could you share your use-case?  We are working on fast-aggregations that will enable aggregating data in a distributed way - partition by partition. It would be great to consider your  while we implement it.

**Comment by amit2103** [comment]
Basically we need to get all data in keySet and get them by chunks because otherwise we will get a outofmemory error.

IF we can process the keys in different nodes by a partition that will be a bonus.
How do you do that currently? Process all data in keys by chunks in separate nodes without processing the same data twice?

**Comment by tombujok** [comment]
In order not to get an OOME just use the PagingPredicate

In order to do that concurrently you could:

- run an EntryProcessor
- run a Runnable on all nodes and process local data only

**Comment by amit2103** [comment]
How to get local data only? If its a replicated map, that will be a problem right?

**Comment by mdogan** [comment]
IMap has a `localKeySet()` method to fetch local keys only, optionally with a `Predicate`. Also, you can consider using [Hazelcast Jet](http://jet.hazelcast.org/) which has built-in Java 8 Streams support for IMap.
