### ISSUE TITLE
Declarative Hibernate 2nd level cache and Hazelcast Instance Configuration in Spring

### ISSUE THREAD

**Issue by larshelge** [hazelcast/hazelcast#8764]
This issue is about adding support for declarative configuration for Hibernate 5 second level cache through the Spring Hazelcast namespace.

The Spring Hazelcast namespace configuration works well with Hibernate 4 as you can create a region factory based on a Spring-defined Hazelcast instance through the namespace with: 

<pre><code>&lt;hz:hibernate-region-factory id="regionFactory" instance-ref="instance"/&gt;</code></pre>

and inject the region factory into the `LocalSessionFactoryBean` through the `cacheRegionFactory` property.

Now in Spring Hibernate 5, the `cacheRegionFactory` property is no longer exposed and so it is no longer possible to inject the region factory. Hence the region factory no longer takes effect during startup.

The difference between the `LocalSessionFactoryBrean` found in Spring Hibernate 4 and 5 is illustrated here: 
- [Hibernate4](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/hibernate4/LocalSessionFactoryBean.html#setCacheRegionFactory-org.hibernate.cache.spi.RegionFactory-)
- [Hibernate5](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/hibernate5/LocalSessionFactoryBean.html)

It would be useful to find an alternative approach to support declarative region factory configuration in Spring 4.2+ and Hibernate 5+.

**Comment by jkrizanic** [comment]
Any solution found regarding this?

**Comment by mesutcelik** [comment]
Hi,

I just updated the title to be more clear on the issue. This issue was first raised to share the same hazelcast instance with Hibernate in Spring environment and spring-hibernate5 integration does not support it anymore. We also found out that pre Spring 4.0 users can't configure this so we decided to go for a generic solution which does not depend on `cacheRegionFactory` setting.

**Comment by emre-aydin** [comment]
@larshelge @jkrizanic,

You can configure your Hazelcast instance declaratively and pass its `instance-name` as a Hibernate property to achieve the same goal. Unfortunately, there's no way to pass the created `RegionFactory` directly to Hibernate, as Hibernate 5 no longer accepts `RegionFactory` as a parameter.

First, you need to set the cache region factory (by using `hibernate.cache.region.factory_class`) to either `com.hazelcast.hibernate.HazelcastCacheRegionFactory` or `com.hazelcast.hibernate.HazelcastLocalCacheRegionFactory`. Then, you need to use `hibernate.cache.hazelcast.instance_name` parameter documented [here](https://github.com/hazelcast/hazelcast-hibernate/blob/master/README.md#setting-p2p-for-hibernate). Also note that you don't need `hz:hibernate-region-factory` element anymore, just the `instance` definition is enough with these parameters passed to Hibernate.

I have modified the original Hazelcast Spring Hibernate second level cache sample project to show this. See [here](https://github.com/emre-aydin/spring-hibernate5-2ndlevel-cache/blob/master/src/main/resources/dataContext.xml#L31-L32) and [here](https://github.com/emre-aydin/spring-hibernate5-2ndlevel-cache/blob/master/src/main/resources/applicationContext-hazelcast.xml#L32) for the relevant changes.
