### ISSUE TITLE
Calling clear() on a Durable map (backed by a MapStore) isn't reflected in the underlying MapStore

### ISSUE THREAD

**Issue by jeppec** [hazelcast/hazelcast#8770]
I've attached a Spock specification that exemplifies the problem (I also have a Java version which uses Hamcrest instead if you're interested). I've tested against 3.7 as well as 3.7.1-SNAPSHOT and the problem exists with both versions.

In the test I define general durability for maps with name pattern "hz.durable.map:*"
In a sequence I create a HzInstance - load a map called "hz.durable.map:map1" - add 3 keys/values to it.
Close the Hz instance.
Loads a new Hz instance - clears the "hz.durable.map:map1" and can then see that the change isn't reflected in the underlying MapStore.
IF I after loading the second Hz instance, but before calling clear() on the map, perform an operation that initializes/loads Map content from the underlying MapStore, such as size(), remove(1) then clear() is perfectly reflected MapStore (from debugging I can see that the ClearOperation only contains a RecordStore instance AFTER size()/remove()/etc have been called)

`import com.hazelcast.config.*
import com.hazelcast.core.Hazelcast
import com.hazelcast.core.MapLoader
import com.hazelcast.core.MapStore
import com.hazelcast.core.MapStoreFactory
import spock.lang.Specification

import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.ConcurrentMap
import java.util.stream.Collectors

/**
 *
 */
class MapDurabilitySpec extends Specification {

    def "Clearing a map with multiple values are visible on another node started after the first node is shutdown"() {
        given:
        def hz1 = Hazelcast.newHazelcastInstance(createTcpHazelcastConfig())
        def map1 = hz1.getMap("hz.durable.map:map1")
        map1.put(1, "Hello")
        map1.put(2, "World")
        map1.put(3, "!")
        map1.size() == 3
        MyMapStoreFactory.printSharedMapSize()
        hz1.shutdown()

        when:
        def hz2 = Hazelcast.newHazelcastInstance(createTcpHazelcastConfig())
        def map2 = hz2.getMap("hz.durable.map:map1")
        println("BEFORE CLEAR")
        MyMapStoreFactory.printSharedMapSize()
        //map2.size() == 3 // If map2.size() == 3 is executed then map.clear() works
        //map2.remove(1) // If map2.remove(1) is executed BEFORE map.clear() then map.clear() works!
        map2.clear() // Why isn't CLEAR working when called by itself - seems to be because no keys have been loaded prior to calling clear
        println("AFTER CLEAR - BEFORE SIZE CHECK")
        MyMapStoreFactory.printSharedMapSize()
        map2.size() == 0
        println("AFTER SIZE CHECK")
        MyMapStoreFactory.printSharedMapSize()
        hz2.shutdown()

        def hz3 = Hazelcast.newHazelcastInstance(createTcpHazelcastConfig())
        def map3 = hz3.getMap("hz.durable.map:map1")
        println("AFTER LOAD OF NEW HZ INSTANCE")
        MyMapStoreFactory.printSharedMapSize()
        println("BEFORE SIZE CHECK IN THEN")

        then:
        map3.size() == 0
    }

    public Config createTcpHazelcastConfig() {
        Config config1 = new Config()
        config1.setProperty("hazelcast.phone.home.enabled", "false")
        config1.setProperty("hazelcast.logging.type", "slf4j")
        NetworkConfig networkConfig1 = config1.getNetworkConfig()
        networkConfig1.setPort(10571)
        networkConfig1.getInterfaces()
                .addInterface("127.0.0.1")
        JoinConfig joinConfig1 = networkConfig1.getJoin()
        joinConfig1.getMulticastConfig()
                .setEnabled(false)
        joinConfig1.getTcpIpConfig()
                .setEnabled(true)
        addDurableMapsToConfig(config1)
    }

    private Config addDurableMapsToConfig(Config config) {
        MapConfig mapConfig1 = config.getMapConfig("hz.durable.map:*")
        MapStoreConfig mapStoreConfig1 = mapConfig1.getMapStoreConfig()
        mapStoreConfig1.setEnabled(true)
        mapStoreConfig1.setFactoryImplementation(new MyMapStoreFactory())
        return config
    }

    public static class MyMapStoreFactory implements MapStoreFactory<Object, Object> {
        private static ConcurrentMap<Object, Object> map = new ConcurrentHashMap<Object, Object>()

        static def printSharedMapSize() {
            println("sharedMap size: " + map.size())
        }

        @Override
        public MapLoader<Object, Object> newMapStore(String mapName, Properties properties) {
            println("CREATING MapStore for '" + mapName + "' - sharedMap size " + map.size())
            return new MyMapStore(mapName)
        }

        public static class MyMapStore implements MapStore<Object, Object> {
            private final String mapName

            public MyMapStore(String mapName) { this.mapName = mapName }

            @Override
            public void store(Object key, Object value) {
                println("Store    -> Map: '" + mapName + "', Key: '" + key + "', Value: '" + value + "'")
                map.put(key, value)
            }

            @Override
            public void storeAll(Map<Object, Object> map) {
                println("StoreAll -> Map: '" + mapName + "', Entries: " + map)
                map.putAll(map)
            }

            @Override
            public void delete(Object key) {
                println("Delete   -> Map: '"+ mapName +"', Key: '" + key + "'")
                map.remove(key)
            }

            @Override
            public void deleteAll(Collection<Object> keys) {
                println("DeleteAll-> Map: '" + mapName + "', Keys: " + keys)
                keys.forEach({ key ->
                    map.remove(key)
                })
            }

            @Override
            public Object load(Object key) {
                println("Load    -> Map: '" + mapName + "', Key: '" + key + "'")
                return map.get(key)
            }

            @Override
            public Map<Object, Object> loadAll(Collection<Object> keys) {
                println("LoadAll -> Map: '" + mapName + "', Keys: " + keys)
                return map.entrySet()
                        .stream()
                        .filter({ e -> keys.contains(e.getKey()) })
                        .collect(Collectors.toMap({ e -> e.key }, { e -> e.value }))
            }

            @Override
            public Iterable<Object> loadAllKeys() {
                println("LoadAllKeys-> Map: '" + mapName + "' - with " + map.keySet().size() + " keys")
                return map.keySet()
            }
        }
    }

}`

**Comment by tombujok** [comment]
Thx for the report @jeppec. Looks like a potential bug indeed.

Could you plz submit a gist with the test (spock is fine)
Could you also describe happy-path and unhappy-path separately in bullet points, I don't quite get the difference now.

**Comment by jeppec** [comment]
Sure @tombujok  :)
Here's the unhappy path: https://gist.github.com/jeppec/d8add5d93946e03d902d5af6ade11d25
Here's the happy path: https://gist.github.com/jeppec/cf3b7e613dac50ef8a7dbee8486cbc8d

There only difference between the two is `map2.size() == 3`, before calling `map2.clear()`, which initializes/loads the map from the underlying MapStore. If this is done then the ClearOperation has a RecordStore instance attached. If the Map has NOT been properly loaded from the underlying MapStore then the ClearOperation has a null RecordStore instance variable.

Let me know if you have any questions :)

**Comment by tombujok** [comment]
Thx for the report and awesome tests @jeppec!
I had a look at it and the situation looks as follows:

- your map-store is configured to LAZY (which is the default mode). It means that without any explicit operation on the map's data the map will not be loaded. 
- `clear` is a special kind of operation because it does not trigger the load, so if the map is not loaded it will not load the data. I know that it may sound unintuitive, but the MapStore interface does not have a clearAll method - you need to have the keys. So you would need to load all the keys from the MapStore to delete them.
- just change the loading mode to EAGER for your test to work. I don't know if it's acceptable for your business use-case. If not, just make sure that the map has been actually used before calling clear.

Do you feel brave enough to submit a PR to the hazelcast-manual repo to describe it there? :)

Hope it helps!
