### ISSUE TITLE
Fix logging on multiple HZ instances run in different apps on a web-server

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#8774]
Due to static-context logging the behaviour is non-deterministic now.

**Comment by shahaf-sameach** [comment]
hi, a new contributor, would like to try this one if possible...

**Comment by Holmistr** [comment]
Hi @shahaf-sameach , I'm sorry that we missed your message. Would you be actually still willing to take a look?

**Comment by Tarush-Singh35** [comment]
I would like to look into this issue can you tell me how can I get started

**Comment by Holmistr** [comment]
@frant-hartm :point_up:

**Comment by frant-hartm** [comment]
This issue description is unclear without a reproducer or at least a description of the environment.

I am closing the issue. If anyone faces something similar please create a new ticket with all details required to reproduce.

@Tarush-Singh35 Feel free to pick any other issue with the `good first issue` label.
