### ISSUE TITLE
[Hazelcast .NET client 3.6.3] - declarative configuration reader doesn't parse imports

### ISSUE THREAD

**Issue by otrebor** [hazelcast/hazelcast#8776]
Declarative configuration combined with the use of the import tag enables us to maintain in different files the configuration parameters that are depending on the environment from the ones common to each environment. Unfortunately this feature seems to be not implemented in the .NET client v3.6.3. It also seems not parsing the element named "executor pool size"

**Comment by vbekiaris** [comment]
@otrebor there is a separate repository for the .NET client, if you don't mind I am closing this issue and please open it in https://github.com/hazelcast/hazelcast-csharp-client/issues
