### ISSUE TITLE
No default serializer for Map or Set

### ISSUE THREAD

**Issue by weizhang1992** [hazelcast/hazelcast#8791]
I have a Map as value in Cache. I implement IdentifiedDataSerializable interface for myObjecta, myObjectb which inside the Map. But hazelcast will use java.io.serializable to serialize whole Map and it's key & value. Seems like hazelcast only provide default serializer for ArrayList, LinkedList...but not HashMap, HashSet...

For example:
```java
Map< myObjecta, myObjectb> myMap;
myCache.put("hello",  myMap);
```

Why hazelcast don't provide the default serializer for HashMap?

**Comment by sancar** [comment]
Related to https://github.com/hazelcast/hazelcast/issues/8791. 
Closing this one. These serializers needs  to be added in 4.0 because of compatibility issues.
