### ISSUE TITLE
Hazelcast 3.6.3 com.hazelcast.client.AuthenticationException in Java Client 

### ISSUE THREAD

**Issue by aunlu** [hazelcast/hazelcast#8819]
There are multiple instances of the same client process. Randomly, some of the clients gets the following exception:

Aug 31, 2016 2:15:09 PM com.hazelcast.client.spi.impl.ClientMembershipListener
INFO: 

Members [2] {
        Member [10.0.0.56]:5701
        Member [10.0.0.26]:5701
}

Aug 31, 2016 2:57:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/10.0.0.26:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Aug 31, 2016 2:57:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/10.0.0.26:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Aug 31, 2016 2:57:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/10.0.0.26:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Aug 31, 2016 2:57:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/10.0.0.26:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]
Aug 31, 2016 2:57:20 PM com.hazelcast.client.connection.nio.ClientConnection
WARNING: Connection [/10.0.0.26:5701] lost. Reason: com.hazelcast.client.AuthenticationException[Invalid credentials!]

Credentials are correct, because other instances can connect without any problem. Also, when I restart failed client instances, they are connected. 

OS: Solaris 10. Java: 1.7.0_80
Hazelcast server nodes run on 10.0.0.56 and 10.0.0.26. Hazelcast clients run on 10.0.0.56.

**Comment by anirudh-wa** [comment]
Hi,

Is this issue fixed ?

**Comment by anirudh-wa** [comment]
I see the same in 3.6.2. Is this only in 3.6.3 ?

**Comment by sancar** [comment]
Fixed in 3.8 via https://github.com/hazelcast/hazelcast/pull/9506
