### ISSUE TITLE
QuorumService inconsistent state

### ISSUE THREAD

**Issue by gAmUssA** [hazelcast/hazelcast#8820]
Team,

from discussion with @metanet: 

> When cluster service starts during node start, it registers itself as the only member and publishes the membership event.  `QuorumService` is a `MembershipAwareService`, therefore it is expected to update quorums when it receives these membership events. If I don’t miss anything, the problem is as follows: services are not registered to ServiceManager yet when cluster service publishes this event on node start. So, it seems that QuorumService is missing it and failing to update its internal quorum status (initial value is “true” but I think it should be sth like “not-decided”).

Test to reproduce.

```
@Test
public void test() {
        Config config = new Config();
        QuorumConfig quorumConfig = new QuorumConfig().setName(randomString()).setEnabled(true);
        quorumConfig.setSize(3);
        quorumConfig.setType(QuorumType.READ_WRITE);
        config.addQuorumConfig(quorumConfig);
        HazelcastInstance hazelcastInstance = createHazelcastInstance(config);
        System.out.println(hazelcastInstance.getQuorumService().getQuorum("q").isPresent());
}
```

returns `true`.

[ZD ticket `1961`](https://hazelcast.zendesk.com/agent/tickets/1961)

**Comment by jerrinot** [comment]
The simplest fix is to update the quorum state with a single (`this`) member when a node is starting. 

The question is whether it's a desirable solution when it comes to listeners. As it could be unexpected for the users to have the listener called everytime when a member is starting. 

Theoretically we could avoid calling listeners when the initial (`this`) member is set. 
The contract of `QuorumListener` says `Called when quorum presence state is changed.` 
So a possible interpretation could be: "when the quorum is established for the first time then it's not a state change". but I am not sure if this interpretation is practical. 

@eminn, @metanet: WDYT?
