### ISSUE TITLE
Logging noise for "Unsafe is unavailable"

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast#8852]
In 3.7 we seem to log in `WARNING` level the “unsafe unavailable” message along with the full stack trace (see https://github.com/hazelcast/hazelcast/blob/7ad3462a62f73316650b6d915e37c83f5d70b7b8/hazelcast/src/main/java/com/hazelcast/internal/memory/impl/UnsafeUtil.java#L58-L58)

while previously the stack trace was not logged in 3.6. We can not log the exception unless trace level is on.

**Comment by pveentjer** [comment]
We should  log the stacktrace when trace enabled, and otherwise just display the message.
