### ISSUE TITLE
MapStore update

### ISSUE THREAD

**Issue by xoff69** [hazelcast/hazelcast#8857]
hello,

a) I have a MapStore and a Map using it.

b) I run Predicate on my Map and for each values selected by the Predicate, I want to update some attribute of the value objet.

 Collection<Course> courses = map.values(new MyPredicate());
for( Course course:courses){
   course.setTimestamp(System.currentTimeMillis());
}

c)
Is there a way to set the course as "dirty" to force store in mapstore ?
At this time, I reset the course in the map to force update by map.set(course.getId(), course); in my loop but I think it's not very elegant.

Ideas ?

Regards
Christophe

**Comment by ahmetmircik** [comment]
answered here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/hazelcast/dEMSiyHmsf0/SQRbv-qlAAAJ
