### ISSUE TITLE
ClientMapNearCacheTest.testNearCacheTTLExpiration

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#8864]
**[batchInvalidationEnabled:true]**

```
java.lang.AssertionError: we expected to have all map entries in the Near Cache (NearCacheStatsImpl{ownedEntryCount=10572, ownedEntryMemoryCost=1057200, creationTime=1473384791294, hits=0, misses=50000, ratio=0.0%, evictions=0, expirations=40493}) expected:<50000> but was:<51073>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.map.nearcache.NearCacheTestSupport.testNearCacheExpiration(NearCacheTestSupport.java:93)
    at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.testNearCacheTTLExpiration(ClientMapNearCacheTest.java:867)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast-client/323/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/testNearCacheTTLExpiration_batchInvalidationEnabled_true_/

**Comment by mmedenjak** [comment]
This is possibly fixed as @Donnerbart changed that assertion 10 days after the failure - https://github.com/hazelcast/hazelcast/commit/3b679a5251751d196418c98361b310a168365d1d

And I haven't observed any test failures afterwards.

**Comment by Donnerbart** [comment]
Yes, let's close the issue until it re-appears (the test setup is a bit racy anyways, we may have a look if we can improve it when moving it to the unified test setup).
