### ISSUE TITLE
SEVERE on shutting down Servlet

### ISSUE THREAD

**Issue by Mario-Eis** [hazelcast/hazelcast#8877]
When shutting down a Servlet instance using a distributed Hazelcast cache (3.7.1), in Apache Tomcat (8.5.4) the following SEVERE happens:

`14-Sep-2016 10:18:36.786 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [com.hazelcast.internal.util.ThreadLocalRandom$1] (value [com.hazelcast.internal.util.ThreadLocalRandom$1@29af0b2d]) and a value of type [com.hazelcast.internal.util.ThreadLocalRandom] (value [com.hazelcast.internal.util.ThreadLocalRandom@2927174]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.`

This seems somehow related to https://github.com/hazelcast/hazelcast/issues/4354

**Comment by pveentjer** [comment]
We are not going to fix this. The threadlocals are needed for all kinds of purposes and there is no clear way to clean out the threadlocals unless we are going to track the threads; which also can lead to problems.

**Comment by Donnerbart** [comment]
This has been fixed in Hazelcast 3.8 via https://github.com/hazelcast/hazelcast/pull/9691
