### ISSUE TITLE
Running Hazelcast in an AWS VPC without Internet

### ISSUE THREAD

**Issue by imesh** [hazelcast/hazelcast#8878]
Is it possible to specify proxy settings (proxy host, port, credentials) when running Hazelcast in an AWS VPC without having internet access?

I checked the code and found that hostHeader parameter [1] can be used for specifying the hostname but couldn't find a way to specify proxy credentials. Appreciate if someone can confirm whether there is any other way to do this. Thanks!

[1] https://github.com/hazelcast/hazelcast/blob/d0336a3b51893688e0d8116ec5c94d428a252e39/hazelcast/src/main/java/com/hazelcast/config/AwsConfig.java#L51

**Comment by imesh** [comment]
I investigated this issue further and found that proxy host and port are supported using following system properties:

```java
https.proxyHost
https.proxyPort
```

However, when the proxy server is secured, com.hazelcast.aws.impl.DescribeInstances does not send proxy credentials. This was fixed and sent a pull request: https://github.com/hazelcast/hazelcast-aws/pull/10

**Comment by mdogan** [comment]
Issue belongs to https://github.com/hazelcast/hazelcast-aws/
