### ISSUE TITLE
Option to externalize the path of hazelcast cookie in WebFilter

### ISSUE THREAD

**Issue by shaktitripathy** [hazelcast/hazelcast#8915]
While there is option to set the cookie_name, domain_name from java configuration, there is no option for setting the path. By default it takes the context path as the cookie path.

Another option is to make, com.hazelcast.web.WebFilter addSessionCookie method protected so that it can be extended.

**Comment by mesutcelik** [comment]
Hi @shaktitripathy ,

I think what you are asking has already been done in hazelcast-wm repository. see the release 3.7.1
https://github.com/hazelcast/hazelcast-wm/releases/tag/v3.7.1

please see the parameter `cookie-path` in [hazelcast-wm documentation](https://github.com/hazelcast/hazelcast-wm/blob/master/README.md#setting-up-session-clustering)

Is it what you are looking for?

**Comment by mesutcelik** [comment]
I am closing the issue. please feel free to reopen if you think `cookie-path` is not what you require.
