### ISSUE TITLE
start.sh can't handle space in file path

### ISSUE THREAD

**Issue by kedar-joshi** [hazelcast/hazelcast#8943]
Hi,
I am facing an issue while starting Hazelcast using `start.sh`. As per my observation, `start.sh` can't handle white space in the file path properly. Due to this, start script exits with following error -

```
lg@lg-System-Product-Name:~/RMH/Practice Projects/Runtime softwares/hazelcast-3.7.1/bin$ ./start.sh
JAVA_HOME found at /opt/jdk8
Path to Java : /opt/jdk8/bin/java
start.sh: 43: export: Projects/Runtime: bad variable name
```
I found that the problem is caused by following `line 43`

```
export CLASSPATH=$HAZELCAST_HOME/lib/hazelcast-all-3.7.1.jar
```
and just wrapping the value part in `"` fixes the issue

```
export CLASSPATH="$HAZELCAST_HOME/lib/hazelcast-all-3.7.1.jar"
```

I am using ` Hazelcast v3.7.1` on `Ubuntu 16.04`

It works fine on Windows because Windows version of the script already wraps the classpath in `"`

```
start "hazelcast" "%RUN_JAVA%" %JAVA_OPTS% -cp "%CLASSPATH%" "com.hazelcast.core.server.StartServer"

```

**Comment by jerrinot** [comment]
hi @kedar-joshi, it's a good finding. would you like to send a Pull Request with a fix?

**Comment by kedar-joshi** [comment]
@jerrinot I would love to send a fix. 
As I am new to this, is there anything else I should know apart from the guidelines mentioned in https://github.com/hazelcast/hazelcast/blob/master/CONTRIBUTING.md
