### ISSUE TITLE
What happen when maploader is restored

### ISSUE THREAD

**Issue by Jan-Marcek** [hazelcast/hazelcast#8969]
Hello everyone,

I have a situtation where I use map and mapLoader. There are 3 nodes in the cluster. One of them goes down. As I read in documenatation node 1's backup should be restored from remaing node. Now, what happen when node 1 starts again? 
There should happen redistributation of partitions between tree nodes. Will node 1 load all data from DB? Or it just read backup from two nodes without loading data via MapLoader? 

It would be best to point on a concrete class where it is implemented. 
Thank you

**Comment by enesakar** [comment]
It will read backup from two nodes without loading data via MapLoader.
closing the issue. please re-open if needed.
