### ISSUE TITLE
Hazelcast IQueue in clusterd environment receives item on all the members

### ISSUE THREAD

**Issue by nitinlodhe** [hazelcast/hazelcast#8973]
hazelcast version: 3.6.4

I am using client server topology in myproject and trying to execute some operations on my hazelcast server.

I am putting the serialized bean on my hazelcast queue from client as below

IQueue<SerializedBean> queue = HzUtil.getInstance().getQueue("myqueue");

boolean  status = queue.offer(serializedBean,<timeoutvalue>,TimeUnit.MILLISECONDS );
on my hazelcast server I have registered listener and I am running hazelcast in cluster mode.

<hz:queue name="myqueue">
    <hz:item-listeners>
        <hz:item-listener implementation="myqueueImpl" include-value="true"/>
    </hz:item-listeners>
</hz:queue>

    public class MyqueueImpl implements ItemListener<SerializedBean> {

        public void itemAdded(ItemEvent<SerializedBean> inputMessage) {
            System.out.println("Item added to the queue ");
            //sometask
        }

    public void itemRemoved(ItemEvent<SerializedBean> removedItem) {

            System.out.println("Item removed from the queue ");
        }
}
Issue:

what I have observed that the queue item is received and picked up and executed on both the members of the cluster. I want the item to be picked up only once once on any of the cluster member. Please let me know what exactly I am missing

**Comment by jerrinot** [comment]
Hi @nitinlodhe,

this is an intentional feature - the queue item is not consumed by firing your listener(s). If you want to consume the item, then you can call `poll()` or `take()`.
