### ISSUE TITLE
Getting HazelcastSerializationException from .Net Client when retrieving data from Java Hazelcast intance

### ISSUE THREAD

**Issue by manikandan22k** [hazelcast/hazelcast#8985]
I'm loading database data into `IMap<string,` MemberDetails>`in my Java project. Here the MemberDetails contains List of MemberDetail. Where MemberDetail contains 3 column's setter/getter. Both MemberDetails & MemberDetail are POJO classes and implements Serializable interface in Java. 
   I'm trying to get the`IMap<string, MemberDetails>` from .Net webservice using HazelCast .Net client dll. I'm able to contact Hazelcast member which is running Java Environment and get the IMap object from .Net. But when i try to retrieve data from the IMap (which i got from .net client) it throws HazelcastSerializationException saying that "There is no suitable deserialization method found for this type -100" from .Net client. 
Please help me on this issue to resolve. Do i need to use any Serializable interface from Hazelcast? Or is there any Deserialization method to be implemented in .Net Client? Thanks in advance.

**Comment by sancar** [comment]
You need to make your MemberDetails class implement either IdentifiedDataSerializable or Portable.  
Both on server and client. For server side see doc here.
http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#serialization

For client side portable class see:
https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Examples/Models/Customer.cs
Corresponding factory class should look like this
https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Examples/Models/ExamplePortableFactory.cs

Similarly you can use identifiedDataSerilizable an example class
https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Examples/Models/Employee.cs
For this one you need to implement a class extending this interface
https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Net/Hazelcast.IO.Serialization/IDataSerializableFactory.cs


This how you use in an application. Note that you need to register factory classes to client configuration.

https://github.com/hazelcast/hazelcast-csharp-client/blob/master/Hazelcast.Examples/Map/MapPortableExample.cs
