### ISSUE TITLE
Logging Configuration through hazelcast.xml

### ISSUE THREAD

**Issue by ghost** [hazelcast/hazelcast#9]
Currently logging configuration is possible through the 
hazelcast.logging.type parameter, say by passing in a value (e.g, -
Dhazelcast.logging.type=log4j) at the command line. 

It would make configuration much more flexible if the hazelcast.xml 
configuration file also supported logging configuration. <p>Migrated from http://code.google.com/p/hazelcast/issues/detail?id=252</p><hr/><h2>earlier comments</h2>

<p><strong>jefftrimm said, at 2011-02-08T18:13:08.000Z:</strong></p>

<p>FWIW, this is problematic for us right now.  Namely, user story is that we have a mixed-application environment where there is a strong desire to not manage application-specific settings in the JVM startup script of the webapp container (which is running multiple other non-hazelcast applications).</p>

**Comment by hz-highfive** [comment]
The job `hazelcast-pr-builder` of your PR failed ([log](sss), [artifacts](aaa)). 
Through arcane magic we have determined that the following fragments from the build log may contain 
information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
bbb
</details>
</pre>
