### ISSUE TITLE
Hazelcast kills the JVM at shutdown?

### ISSUE THREAD

**Issue by lvca** [hazelcast/hazelcast#9041]
I'd like to provide a way to restart Hazelcast, so I tried calling `HazelcastInstance.shutdown()` and reconfigure it, but at `HazelcastInstance.shutdown()` the JVM exits.

Do you have any settings to avoid this behavior? Thanks.

**Comment by jerrinot** [comment]
Hi @lvca,

Hazelcast does not kill JVM on `shutdown()`, that wouldn't make us a good JVM citizen:)

However `shutdown()` stops bunch Hazelcast internal threads and JVM exits when a last non-daemonic thread exits. Perhaps that could be a reason why you observe the JVM exit?

**Comment by lvca** [comment]
Good, so it has to be the lack of non-daemon threads in the app. Thanks.
