### ISSUE TITLE
High CPU Usage with Hazelcast 3.6.2

### ISSUE THREAD

**Issue by SomannaDC** [hazelcast/hazelcast#9061]
Hi,

We are facing High CPU Usage with Hazelcast 3.6.2 client for Session replication, Is there a fix for this issue?

![image](https://cloud.githubusercontent.com/assets/21066961/19158372/12d018b0-8bae-11e6-9d1f-4adb1e61efa2.png)

**Comment by pveentjer** [comment]
Did the cpu usage change compared to e.g. 3.6.1

Can you run with a more reliable profiler like JFR and send us the JFR file. I stopped caring about sampling and instrumentation based profilers quite some time ago because often one is chasing ghosts.

**Comment by jerrinot** [comment]
Hi @SomannaDC, do you have any update?

**Comment by mdogan** [comment]
No feedback. Feel free to open a new issue if problem still exists.
