### ISSUE TITLE
hazelcast.heartbeat.interval.seconds documentation and code discrepancy

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#9070]
Default value is 1 in [docs](http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#system-properties) but 5 in [source](https://github.com/hazelcast/hazelcast/blob/v3.7.2/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L266)

**Comment by Serdaro** [comment]
@ahmetmircik , Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/2121a08b44e4f574469b1d46dbd75cc98e4dbd65 for master and maintenance Reference Manuals.
