### ISSUE TITLE
Hazelcast write behind reliability

### ISSUE THREAD

**Issue by amit2103** [hazelcast/hazelcast#9103]
Hi All,

Thanks for the wonderful product.
How reliable is Hazelcast write behind?

if the primary which processes the writes fail, will the write behind be retried.

**Comment by ahmetmircik** [comment]
Hi, if map has backup configured, after fail, backup will become new primary and it will continue the processing.

**Comment by jerrinot** [comment]
Hi, 

I'm closing this as it's not a real issue. Please prefer [user forum](https://groups.google.com/forum/#!forum/hazelcast) for questions.

thanks for understanding!

**Comment by amit2103** [comment]
@jerrinot  Okay..yea thats fine.
