### ISSUE TITLE
XSI Schema Location https://www.hazelcast.com/schema/spring/hazelcast-spring-3.4.xsd gives org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'.

### ISSUE THREAD

**Issue by Gurkirat2210** [hazelcast/hazelcast#9114]
I'm using Hazelcast 3.6 for Hibernate 2nd level cache configuration. Below is my cnfig in XML.

```
    xmlns:hz="http://www.hazelcast.com/schema/spring"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd 
        http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop.xsd
        http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
        http://www.springframework.org/schema/jee http://www.springframework.org/schema/jee/spring-jee.xsd
        http://www.springframework.org/schema/lang http://www.springframework.org/schema/lang/spring-lang.xsd
        http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx.xsd
        http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util.xsd
        http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd
        http://www.springframework.org/schema/cache http://www.springframework.org/schema/cache/spring-cache.xsd
        http://www.hazelcast.com/schema/spring https://www.hazelcast.com/schema/spring/hazelcast-spring-3.4.xsd">
```

When I deploy my war in Tomcat-7.0.54, I get following error:

```
ERROR 15-Oct-16 11:49:09 ContextLoader:initWebApplicationContext:308 Context initialization failed
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpath:applicationContext-hazelcast.xml]
Offending resource: ServletContext resource [/WEB-INF/applicationContext.xml]; nested exception is org.springframework.beans.factory.xml.XmlBeanDefinitionStoreException: Line 26 in XML document from class path resource [applicationContext-hazelcast.xml] is invalid; nested exception is org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'.
```

If I use http instead of https, I get : 
```
 Invocation of init method failed; nested exception is org.hibernate.cache.CacheException: com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
```

**Comment by mesutcelik** [comment]
Hi @Gurkirat2210 ,

Are you using hazelcast-all.jar? If not, can you please make sure hazelcast-spring.jar is in your classpath?

**Comment by Gurkirat2210** [comment]
I'm not using hazelcast-all.jar. But I'm using following jars associated with hazelcast:
hazelcast-3.6.4.jar
hazelcast-spring-3.6.4.jar
hazelcast-hibernate4-3.6.4.jar
hazelcast-client-3.6.4.jar

As I'm using them in a Spring-Maven Project, so all these dependencies are placed in WEB-INF/lib folder in my compiled WAR file.

**Comment by mesutcelik** [comment]
Thanks @Gurkirat2210 !

Can you please try with that definition instead of 3.4 xsd?
`http://www.hazelcast.com/schema/spring
		http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd"`

**Comment by Gurkirat2210** [comment]
I tried that but it still gives me 301 error. Here my stack trace for referance.
` org.hibernate.cache.CacheException: com.hazelcast.core.HazelcastException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 35; s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:287)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1106)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:585)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:464)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:385)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:284)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4760)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5184)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:581)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1686)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

I think I have figured it out. When I provide this file for hibernate 2nd level chache configuration, like this:
`<property name="hibernateProperties">
	<props>
		....
		<prop key="hibernate.cache.provider_configuration_file_resource_path">/applicationContext-hazelcast.xml</prop>
		......		
	</props>
</property>`

This file is parsed in context of hazelcast-hibernate4-3.6.4.jar & not in context of hazelcast-spring.jar. So the URL is not mapped to loacal XSD schema lying in the hazelcast-spring.jar and tomcat-server tries to locate file on hazelcast server. As hazelcast has moved their content to HTTPS from HTTP, it gets 301 error.

But even in this scenario, when we try to get schema from hazelcast server, instead of returning 301 error, my request should be automatically redirected to HTTPS.

**Comment by mesutcelik** [comment]
`spring https schema support` has been introduced in hazelcast 3.7.

Can you please try `http` as i pasted below in my previous comment?

`http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd"`

P.S: when you share a stack trace it would be better to use triple backticks instead of one. It is more readable and i already updated previous comments.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by Gurkirat2210** [comment]
Hey mesutcelik
I tried `http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd` but it gives me 301:Saw Permanently Error.

Let me explain my scenario in detail:-
I am using my hazelcast.xml file for configuring both:
	1. Manual cache maps & queues
	2. Hibernate 2nd level cache

So initially when manual cache maps are configured, it is done by hazelcast-spring.jar, which maps the xsd URL to local xsd schema file lying inside this hazelcast-spring.jar file. But second time, when I use my xml file to configure hibernate 2nd level cache, it doesnt happen in the context of hazelcast-spring.jar. This time the URL is not mapped to local schema files inside hazelcast-spring.jar. So the application goes to internet with this URL (`http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd`), which returns `301:Moved Permanently Error`.

**Comment by mesutcelik** [comment]
@Gurkirat2210 ,

I feel that you are using `spring` tags inside the hazelcast.xml. That is not how it is supposed to work. If you are in spring environment, your all `hazelcast` and `hibernate 2nd level cache` configuration should be in your `applicationContext.xml`.

I think this example can be useful for you.
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-hibernate-2ndlevel-cache

**Comment by Gurkirat2210** [comment]
@mesutcelik 
By hazelcast.xml, I meant applicationContext-hazelcast.xml file. I did all my hazelcast.xml & hibernate 2nd level cache config in this file. I have included this file in my applicationContext.xml file.

This is my applicationContext.xml file: 
```<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:context="http://www.springframework.org/schema/context"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.1.xsd 
        http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd"
>        
	<import resource="applicationContext-core.xml"/>
	<import resource="classpath:applicationContext-hazelcast.xml"/>
	<import resource="applicationContext-security.xml"/>
 	<import resource="applicationContext-quartz.xml"/>
</beans>
```

In my applicationContext-corexml, this is where I configure my hibernate 2nd level cache:
```
	<bean id="mySessionFactory" class="org.springframework.orm.hibernate4.LocalSessionFactoryBean" primary="true" depends-on="cacheManager">
        <property name="dataSource" ref="myDataSource" />
        <property name="packagesToScan" value="com.xxx.entity" />
        <property name="entityInterceptor" ref="entityInterceptor" />
        <property name="hibernateProperties">
            <props>
				<prop key="hibernate.show_sql">${hibernate.show_sql}</prop>
				<prop key="hibernate.dialect">org.hibernate.dialect.SQLServer2005Dialect</prop>
				<prop key="hibernate.query.substitutions">true 'T', false 'F'</prop>
				<prop key="hibernate.cache.use_second_level_cache">true</prop>
				<prop key="hibernate.cache.use_query_cache">true</prop>
				<prop key="hibernate.cache.region.factory_class">com.hazelcast.hibernate.HazelcastCacheRegionFactory</prop>
				<prop key="hibernate.id.new_generator_mappings">true</prop>
				<prop key="hibernate.jdbc.batch_size">20</prop>
				<prop key="hibernate.cache.hazelcast.instance_name">vmorc_hz_instance</prop>		
				<prop key="hibernate.cache.provider_configuration_file_resource_path">/hibernate-2nd-level-cache.xml</prop>		
			</props>
        </property>
    </bean>

```

**Comment by mesutcelik** [comment]
That could be the problem. 
`<prop key="hibernate.cache.provider_configuration_file_resource_path">/applicationContext-hazelcast.xml</prop>`

This normally accepts `hazelcast.xml` instead of spring configuration. 

Can you configure `regionFactory` by using existing hazelcast instance configuration.
https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-hibernate-2ndlevel-cache/src/main/resources/dataContext.xml#L22
https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-hibernate-2ndlevel-cache/src/main/resources/applicationContext-hazelcast.xml#L32

**Comment by Gurkirat2210** [comment]
I tried the config mentioned in links.. I'm getting:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mySessionFactory' defined in ServletContext resource [/WEB-INF/applicationContext-core.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'cacheRegionFactory' of bean class [org.springframework.orm.hibernate4.LocalSessionFactoryBean]: Bean property 'cacheRegionFactory' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
```
I explored it and found that in `spring-orm-3.1.1.RELEASE.jar`(which I'm using), there isnt any variable named `cacheRegionFactory` in `org.springframework.orm.hibernate4.LocalSessionFactoryBean`.

**Comment by mesutcelik** [comment]
Can you check the following? setter is available in `org.springframework.orm.hibernate4.LocalSessionFactoryBean`

http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/orm/hibernate4/LocalSessionFactoryBean.html#setCacheRegionFactory-org.hibernate.cache.spi.RegionFactory-

What is your Spring version?
you might be hitting that bug now.. 
https://github.com/hazelcast/hazelcast/issues/8764

**Comment by Gurkirat2210** [comment]
This variable was added in Spring 4.0.
I'm using Spring 3.1.1

**Comment by mesutcelik** [comment]
Ok. Unfortunately you need upgrade to Spring 4+ to be able to use this configuration.
We are working on a generic solution and you can follow up https://github.com/hazelcast/hazelcast/issues/8764 for the solution.

I am closing so please feel free to update https://github.com/hazelcast/hazelcast/issues/8764

**Comment by ripunjDev** [comment]
As in ehcache we have diskstore where we could control the location of temp directory and I don’t see the equivalent in hazelcast.

<diskStore path="java.io.tmpdir/ehcache" />

Is there a configuration we can add to the xml to control the location to keep it part of our install directory?

**Comment by ripunjDev** [comment]
As in ehcache we have diskstore where we could control the location of temp directory and I don’t see the equivalent in hazelcast.
`<diskStore path="java.io.tmpdir/ehcache" />`

Is there a configuration we can add to the xml to control the location to keep it part of our install directory?
