### ISSUE TITLE
Backup lost if "maxIdle" property is used

### ISSUE THREAD

**Issue by MeYoGui** [hazelcast/hazelcast#9153]
Hi,

I'm facing an issue with an IMap distributed on two different nodes.

 I'm using this IMap with :
- only one "**Async Backup**"
- **MaxIdleSeconds** set to 10 seconds.  
- **readBackupData** set to false
- Default **eviction-policy** (NONE)

In the beginning I'm putting some values in the map but after that the values are only accessed and not updated for quite a long period (like 10 or 15 minutes).

What is the problem ?

In the beginning (before 10 seconds elapsed), the backup is working great ... 

![image](https://cloud.githubusercontent.com/assets/4062869/19607392/7e4044e0-9797-11e6-9ee1-891c06ff26d3.png)

But after 10 seconds : all the backups are lost !

![image](https://cloud.githubusercontent.com/assets/4062869/19607413/ad5f069e-9797-11e6-8b07-409142533aa4.png)

_If I change the amount of seconds for the MaxIdle property to an higher value (let's say 300 seconds) then everything is working well until 300 seconds._ 

**The backups gets evicted if I use MaxIdle property, is that a normal behavior ?** 

For information : using a "sync" backup didn't solve the problem at all.
The only "workaround"is to use a TTL instead but that's not what I want because my values are not updated for a certain amount of time and I want eviction if not "accessed" for 10 seconds.

I don't have any workaround here and it's quite a severe issue to integrate Hazelcast in our system.
If you want more information, don't hesitate.

Hazelcast version : 3.7.2

**Comment by ahmetmircik** [comment]
Hi @MeYoGui, if you are using `imap#get`, can you please try to get value via EntryProcessor by using `imap#executeOnKey`? You can touch backup entry with EntryBackupProcessor in this case and expiration time will be shifted.

**Comment by MeYoGui** [comment]
Hi @ahmetmircik, 
Yes I'm using get()  method from IMap. 
I'll try your solution with the executeOnKey()  method as you propose. I'll let you know if it's working. 

I'm just not sure about the performance of this way of doing... Is that efficient ?  (I'm doing almost 3k get/s)

**Comment by MeYoGui** [comment]
I tried via the EntryProcessor. It worked well, the backup is now touched and I haven't seen any lack of performance except that the code is less intuitive now...

You may update your documentation to tell about this behavior as this is not expected at all (and quite dangerous : backup is lost), don't you think ?

Are you still going to change the get() method to touch the backup ?

**Comment by MeYoGui** [comment]
Hi  @ahmetmircik, any news about this issue ? What is the plan for this ?

**Comment by ahmetmircik** [comment]
Sorry just seen your comment, indeed my suggestion was a workaround. When we have a feasible solution, we will update this ticket. Please   watch this issue for the updates and thanks for reporting it.

**Comment by jerrinot** [comment]
I am moving this into 3.9 as it requires major changes with consequences. 
I see this is a serious deficiency and I'll do my best to have this in the plan for 3.9.

**Comment by MeYoGui** [comment]
Allright, I'll keep an eye on this :+1: Thanks
