### ISSUE TITLE
putToCacheAndGetInvalidationEventWhenNodeShutdown test randomly fails

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#9172]
putToCacheAndGetInvalidationEventWhenNodeShutdown test simulates member shutting down using the code:
((LifecycleServiceImpl) instanceToShutdown.getLifecycleService())
                .fireLifecycleEvent(LifecycleEvent.LifecycleState.SHUTTING_DOWN);

The cache invalidation listener is CacheEventHandler. The Connection manager also listens for this event. The order in which these listeners are called changes the result of the test.

Fail case: Connection manager listener called first closing the connections, and then the CacheEventHandler listener is called but the cache invalidation can not be delivered since the connection was closed.

Pass case: CacheEventHandler listener called first and then the Connection manager listener.

A possible solution is to invalidate near caches at the client side when CLIENT_DISCONNECTED (us client lifecycle listener).

For the maintenance-3.x, the corresponding tests are:
putToCacheAndGetInvalidationEventWhenNodeShutdownWithBinaryInMemoryFormat
putToCacheAndGetInvalidationEventWhenNodeShutdownWithObjectInMemoryFormat

**Comment by ihsandemir** [comment]
The test is put to ignore with PR https://github.com/hazelcast/hazelcast/pull/8848 . Hence, lets not forget to reopen the test with the fix PR.

**Comment by sancar** [comment]
Fixed by https://github.com/hazelcast/hazelcast/commit/68b6547aedcce5d32883f7acfeb132e0d66e2990
