### ISSUE TITLE
Get wrong value after use IMap.replace 

### ISSUE THREAD

**Issue by tvd12** [hazelcast/hazelcast#9184]
I have a class named Game:

```java
public class Game implements Serializable {
    private static final long serialVersionUID = -6321023979310869132L;
    private int id = 0;
}
```

and it's serializer

```java
public class Game implements StreamSerializer<Game> {
  // read and write int
}
```

I've put to the map value: map.put("game", new Game(id = 1));

now I use: ```java map.replace("game", new Game(id = 2));```

But when I use ```java map.get("game")``` after replace, I get: game.id = 0.

It's a bug or I'm wrong? Please show me.

**Comment by jerrinot** [comment]
@tvd12: this seems like a bug in your serializer. Can you post source code of both `Game` and the serializer here?

**Comment by tvd12** [comment]
@EqualsAndHashCode(callSuper = false)
public class Game implements Serializable {
    private static final long serialVersionUID = -6321023979310869132L;
    
    @Getter @Setter
    private String id;
    @Getter @Setter
    private long money;
    @Getter @Setter
    private int typeId;
    @Getter @Setter
    private int turnCount;
}

public class GameSerializer implements StreamSerializer<Game> {

    /* (non-Javadoc)
     * @see com.hazelcast.nio.serialization.Serializer#getTypeId()
     */
    @Override
    public int getTypeId() {
        return 111;
    }

    /* (non-Javadoc)
     * @see com.hazelcast.nio.serialization.Serializer#destroy()
     */
    @Override
    public void destroy() {
        // TODO Auto-generated method stub
        
    }

    /* (non-Javadoc)
     * @see com.hazelcast.nio.serialization.StreamSerializer#write(com.hazelcast.nio.ObjectDataOutput, java.lang.Object)
     */
    @Override
    public void write(ObjectDataOutput out, CaoThapGame object) throws IOException {
        Game game = new Game();
        out.writeLong(game.getMoney());
        out.writeInt(game.getTypeId());
        out.writeUTF(game.getId());
        out.writeInt(game.getTurnCount());
    }

    /* (non-Javadoc)
     * @see com.hazelcast.nio.serialization.StreamSerializer#read(com.hazelcast.nio.ObjectDataInput)
     */
    @Override
    public CaoThapGame read(ObjectDataInput in) throws IOException {
        CaoThapGame game = new CaoThapGame();
        game.setMoney(in.readLong());
        game.setTypeId(in.readInt());
        game.setId(in.readUTF());
        game.setTurnCount(in.readInt());
        return game;
    }
    
}

**Comment by jerrinot** [comment]
@tvd12: there is a bug in the `write()` method of the serializer: 
```java
    @Override
    public void write(ObjectDataOutput out, CaoThapGame object) throws IOException {
        Game game = new Game(); <--- this should not be there
        out.writeLong(game.getMoney());
        out.writeInt(game.getTypeId());
        out.writeUTF(game.getId());
        out.writeInt(game.getTurnCount());
    }
```

During serialization you create a new instance of the `Game` and then you serialize this new instance instead of serializing the `object` instance passed you by Hazelcast. It should look like this:
```
    @Override
    public void write(ObjectDataOutput out, Game object) throws IOException {
        out.writeLong(object.getMoney());
        out.writeInt(object.getTypeId());
        out.writeUTF(object.getId());
        out.writeInt(object.getTurnCount());
    }
```
