### ISSUE TITLE
thread names assigned to all threads created by Hazelcast

### ISSUE THREAD

**Issue by vloo** [hazelcast/hazelcast#9210]
it would be nice to have names assigned to all threads created by Hazelcast (and not default ones eg: pool-2-thread-1, pool-2-thread-2)
I have found 2 case where Hazelcast creates ThreadPool - but without name pattern
TcpIpConnectionManager:
private final ScheduledExecutorService scheduler = new ScheduledThreadPoolExecutor(4);
and
MetricsRegistryImpl
private final ScheduledExecutorService scheduledExecutorService = new ScheduledThreadPoolExecutor(2);

Have nice day (-:

**Comment by Petikoch** [comment]
+1
