### ISSUE TITLE
Make operation retrying optional

### ISSUE THREAD

**Issue by GhostInAMachine** [hazelcast/hazelcast#9305]
Certain operations such as `Map.get` are retried when an IO problem happens. This is great for most users, however, some might prefer the operation to fail fast without waiting for an invocation to time out .

**Comment by pveentjer** [comment]
In those cases isn't it better to just do Map.asyncGet(timeout,unit)? Because they you have a lot better control on how long you actually want to wait. No matter if there are io issues, network congestion, slow operation blocking the partition etc.

**Comment by pveentjer** [comment]
I'm going to close this ticket. For control on waiting time, please use the above suggested approach. If you really want something else, feel free to reopen this ticket.
