### ISSUE TITLE
Cache event listeners triggers multiple events when the listener is configured using the xml

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast#9315]
When we create an EventListener to log on events such as create, update, expire, etc.. , and when we restart the client by keeping the server in place, for the first client start we see one printout for the first hit to an event, and when we restart the client we see two printouts for the second event, and when we restart the client again we see four for the third event, eight for the fourth, and so on. 

This happens when listener is configured using the xml:
```
    <cache name="entrylistenertestcache">
        <expiry-policy-factory>
            <timed-expiry-policy-factory expiry-policy-type="CREATED" duration-amount="1" time-unit="SECONDS"/>
        </expiry-policy-factory>
        <cache-entry-listeners>
            <cache-entry-listener old-value-required="false" synchronous="false">
                <cache-entry-listener-factory class-name="com.hazelcast.client.cache.CacheEntryListenerTestFactory"/>
            </cache-entry-listener>
        </cache-entry-listeners>
    </cache>
```

**Comment by sancar** [comment]
fixed by #9233 and #9316
