### ISSUE TITLE
Reloading of `MapStore` data triggers `EntryAddedListener#entryAdded`

### ISSUE THREAD

**Issue by vpavic** [hazelcast/hazelcast#9348]
If Hazelcast map data is persisted using `MapStore`, upon reload of data from the underlying store (typically on application startup), `EntryAddedListener#entryAdded` is triggered. Technically this is a new entry however from perspective of business logic that uses Hazelcast as data store the generated event presents a duplicate.

It would be nice to have an option of making event publishing configurable in this scenario.

See [discussion on gitter](https://gitter.im/hazelcast/hazelcast?at=583eca8e38afd97d3b8429bd) and spring-projects/spring-session#680 for more background.

**Comment by jerrinot** [comment]
@vpavic: thanks!

**Comment by gaganis** [comment]
Hi all!

I have read the gitter discussion on this and I found it quite intriguing and it got me thinking so I got motivated to chip in my thoughts. Not very useful when the only stay in my head, right? :)

I also can see and agree with @jerrinot this is one of these problems that are difficult to precisely pinpoint the right solution.

**Semantics**

There are two perspectives that influence the semantics of this problem.

_As a distributed data structure_

One view we can have of the map is like a distributed object. In this view we think of the map as one homogenous entity. When we use this framework of mind and we think "add to the map", in essence with it as added when it is first added to the distributed map. So when the entries are comming into memory we consider them already already added and in this case I would say that they are "loaded" as the best term I can supply.

I believe this is how @vpavic was thinking in this case. And it is totally natural to be surprized when thinking from this perspective.

_As something that exists in the jvm_

On the other hand we have the view of a group of entries that exist in the jvm these entries can come into the jvm(added to) and it legitimate that we would want to know tha entries have come into the jvm, both internally in Hazecast's API and as users. Some other part of a user's application might need to know what entries are loaded in this service so to provide it's services.

**First thought on how to solve this**

My first thought on how to solve this would have been to separate the semantics into two different. One that expresses the addition of an entry to the map as a single distributed entity. This one would use the term "add"

The other would express the coming in to the jvm for an entry. This would use the term "load"

Though and please do correct me if I am wrong. I suspect that the term add has been used extensively and pervesively in the interal and external API. This probably makes this unrealistic as a solution.

**Solving it using a configuration option**

There is definitely a pretty useful concept that @jerrinot tried to apply, that of using the product to provide information about added map through a listener way. That idea is very powerful both for performance and ease of use reasons.

On the other hand I believe it wouldn't be a very good idea to add a configuration option as requested by @jerrinot. This area is already confusing semanticaly and adding a configuration option would make it even more confusing for users in general.

**How to provide the functionality**

Taking into account the constraints and the very useful use case for our users to be able to know when an entry is added from the perspective of the map as one whole distributed entity it would be a good feature.

The way forward with this would be the introduction of a event mechanism to provide users information for the map as whole distributed entity. This should be very distinct from the current notion of EntryAdded. This also makes it very difficult to find a good naming scheme for it.

This is a difficult problem to solve and design correctly and it would require a lot of thinking.

On how it is to be implemented unfortunately at this point I cannot provide any good ideas, I do not know a lot about the internal implementation architecture and design details.

Some ideas that could be completely wrong :) might be the following:

This could use techniques like freshness metadata on entries. Is it newly added? Has it been added to the jvm first time? Has it been replicated? Has it been loaded from a store? This is where it gets tricky. What if it failed to replicate but is loaded first time to the jvm from a central store.

Hope this is helpful!

**Comment by jerrinot** [comment]
@gaganis: Hello, I would like to thank you for an awesome & thought-provoking input! 
Feedback like this is very much appreciated. 

I absolutely agree adding yet another option is bad for simplicity - one of the core Hazelcast values. 
I would very much appreciate if you could try to elaborate your idea about metadata. I can provide you details about the current impl, just ping me at https://gitter.im/hazelcast/hazelcast

**Comment by gaganis** [comment]
Hi @jerrinot, Thank for reading my comment to the end! It is cool that you found it helpful.  

I will get back to you on the. I want to think about it a bit more. In the meantime could you please provide some help? I have look at _"An Architect’s View of Hazelcast"_ document is some other document in that spirit but describes more lower levels on how hazelcast operates?

If you are aware of it, could you also point me out the class or hierarchy of classes that are used to describe an entry in memory. That would be a good place for me to start unwinding the code :)

Thanks!

**Comment by ahmetmircik** [comment]
@mmedenjak that's right. 

By starting version 3.11 and by default, `LOADED` events will be published for loaded entries and implementing `EntryLoadedListener` will be sufficient to listen them. There will be no publication of ADDED event for `EntryAddedListener`. So for example, when doing initial load from a map-store, only LOADED events will be generated.

**Comment by mmedenjak** [comment]
Thank you, closing the issue as fixed then. @vpavic please comment or open a new issue if this does not suit you.

**Comment by mmedenjak** [comment]
The BETA release (EA) should be available in a couple of days.

**Comment by mmedenjak** [comment]
Hi @vpavic, the BETA release is available for download: https://hazelcast.org/download/
