### ISSUE TITLE
Improve key state marking in nearcached getAll

### ISSUE THREAD

**Issue by ahmetmircik** [hazelcast/hazelcast#9403]
instead of key based marking partition based approach can be used

**Comment by tombujok** [comment]
@ahmetmircik Can you provide more details? How can one implement it?

**Comment by ahmetmircik** [comment]
Actually i have a pr for that https://github.com/hazelcast/hazelcast/pull/9567
When we are ok with that PR, this issue will be fixed. Assigning myself.
