### ISSUE TITLE
The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'

### ISSUE THREAD

**Issue by mohan595** [hazelcast/hazelcast#9406]
I am using the hazelcast for the first time and  trying to set up Hazelcast spring config in our application.
I am getting the following error message when loading the context 

org.xml.sax.SAXParseException: schema_reference.4: Failed to read schema document 'http://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

Caused by: org.xml.sax.SAXParseException: cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'hz:hazelcast'.

My Spring config schema definition is 

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:hz="http://www.hazelcast.com/schema/spring"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation=
               "http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
				http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd
              	http://www.hazelcast.com/schema/spring http://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">
   
	<hz:hazelcast id="cacheInstance">
        <hz:config>
            <hz:group name="${name}" password="${password}"/>
            <hz:properties>
                <hz:property name="hazelcast.merge.first.run.delay.seconds">5</hz:property>
                <hz:property name="hazelcast.merge.next.run.delay.seconds">5</hz:property>
            </hz:properties>
            <hz:network port="${defaultPort}" port-auto-increment="true">
                <hz:join>
                    <hz:multicast enabled="true" multicast-group="224.2.2.3" multicast-port="54327" />
                  
                </hz:join>
            </hz:network>
        </hz:config>
    </hz:hazelcast>

</beans>

I tried different versions of the schema like 3.1, 3.6, 3.7, 3.8 and got the same error message.

Can someone please help use with this issue.

**Comment by mohan595** [comment]
Here is the schema details

<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:hz="http://www.hazelcast.com/schema/spring"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation=
               "http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
				http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd
              	http://www.hazelcast.com/schema/spring http://hazelcast.com/schema/spring/hazelcast-spring-3.7.xsd">

**Comment by mohan595** [comment]
Can you please let us know if some one is looking into this issue.

**Comment by mesutcelik** [comment]
Are you using hazelcast-all.jar file in your classpath?

**Comment by mohan595** [comment]
No,

I am using 

hazelcast-3.6.0.jar,
hazelcast-client-3.6.0.jar,
hazelcast-spring-3.6.0.jar

**Comment by mesutcelik** [comment]
I think that is normal if you tried those jars with 3.7 xsd. Can you please try to set xsd to 3.6? From your previous comment, i see that you already tried so you can also use [versionless](https://github.com/hazelcast/hazelcast-code-samples/blob/master/hazelcast-integration/spring-configuration/src/main/resources/applicationContext.xml#L9) version of the spring definition.

Here is a [code sample](https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-configuration) you can use as well.Can you please send us the output of following command executed under `spring-configuration` folder?

`mvn exec:java -Dexec.mainClass="com.hazelcast.springconfiguration.HazelcastDataTypes"`

**Comment by mohan595** [comment]
Thanks for the quick response, appreciate your help with this.

I tried with 3.6 xsd still i got the same exception.
But i tried schema from the the same code that you provided, it seems to work fine now.
Can you let me know what version is this generic one points to..

**Comment by mesutcelik** [comment]
generic does always refer to the version of the hazelcast version you are using.

see below what is used in hazelcast-spring-3.7.4.jar
https://github.com/hazelcast/hazelcast/blob/v3.7.4/hazelcast-spring/src/main/resources/META-INF/spring.schemas#L18

**Comment by mesutcelik** [comment]
I see it is working fine for you so I am closing this issue. please feel free to reopen if you see similar problem...
