### ISSUE TITLE
ScheduledExecutorServiceTest.stats

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9431]
```
java.lang.AssertionError: expected:<2.0> but was:<-58.0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at com.hazelcast.scheduledexecutor.ScheduledExecutorServiceTest.stats(ScheduledExecutorServiceTest.java:167)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x/com.hazelcast$hazelcast/6161/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceTest/stats/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/1128/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceTest/stats/

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/697/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceTest/stats/

https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast/1319/testReport/junit/com.hazelcast.scheduledexecutor/ScheduledExecutorServiceTest/stats/

**Comment by tkountis** [comment]
This should now be fixed.
