### ISSUE TITLE
IExecutor and high availability

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#944]
Currently, when a tasks is send to a member, and that member fails, all pending tasks for that member are gone.

It would be nice if you can configure that instead of on ordinary queue being used, there is a IQueue. This way, when a member fails, a different member can take over the unprocessed tasks.

**Comment by zeratul021** [comment]
Hello,

what is the current status of this feature?

I'm currently trying to achieve exactly the same thing. I looked at Hazeltask project but I think it's no longer maintained (dependency on Hazelcast 3.1). The code is not leveraging the SPI, however the original author mentioned it in the future plans. Maybe some code could be reused but I think a real distributed object implemntation (alternative to executor service maybe) would be a good idea.

**Comment by bwzhang2011** [comment]
@pveentjer, any update with the issue ?

**Comment by bwzhang2011** [comment]
@pveentjer, any update with such issue ?

**Comment by gurbuzali** [comment]
We've introduced DurableExecutorService in 3.7
