### ISSUE TITLE
Hazelcast Management Center not Working with tomcat 8 and above

### ISSUE THREAD

**Issue by sandeshk** [hazelcast/hazelcast#9452]
Mancenter (v3.7.4) is having error while running with Tomcat 8 and above.

/mancenter/login.jsp gives below error:

`HTTP Status 500 - java.lang.NoSuchMethodError: org.apache.jasper.runtime.TagHandlerPool.get(Ljava/lang/Class;)Ljavax/servlet/jsp/tagext/JspTag;`

**Comment by hasancelik** [comment]
Hi @sandeshk,

This issue will be fixed in Management Center(v3.7.5)

Thanks for your report.
