### ISSUE TITLE
Asynchronous MapLoader

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#9507]
For the writing part of a MapLoader (MapStore) we have an option to do it async to prevent hogging the partition threads. But we don't have an option to asynchronously load a value for the same reason.

It would be good to have an option that for a given map (or any other data-structure that potentially accesses a slow external resource) to have the option that the load is executed asynchronously and the operation thread being freed.

So when the load comes in, it is MapLoader.load is executed asynchronously and the partition thread is freed. Once the load completes, the task/operation is rescheduled on the original partition thread and completes. So the main logic that updates the internals remains where it is

**Comment by pveentjer** [comment]
Probably best to make it the default to offload and perhaps we should even not provide an option at all to do it on the partition thread.

**Comment by burakcelebi** [comment]
Closed as internal request.
