### ISSUE TITLE
Near Cache pre-loader fails when invalidations are enabled

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#9536]
The Near Cache pre-loader uses `getAll()` to populate the Near Cache again. That method has a known issue when Near Cache invalidations are enabled.

The Near Cache pre-loader tests have been prepared with parameters and are failing at the moment. The additional parameter can easily be activated, once the original issue has been fixed:
https://github.com/hazelcast/hazelcast/commit/3c30eef57d0d7d0e6268cfefe1c703d88929e576
https://github.com/hazelcast/hazelcast-enterprise/commit/9b5c4b19e836c7ac1581bbd401ad0700567a64a1

Depends on https://github.com/hazelcast/hazelcast/issues/9403

**Comment by jerrinot** [comment]
fixed by #9660
