### ISSUE TITLE
WARN  c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.7.4] Unable to get alive cluster connection, try in 0 ms later, attempt 1 of 2. IN JBOSS

### ISSUE THREAD

**Issue by RobinsChens** [hazelcast/hazelcast#9564]
in jboss 

WARN  c.h.c.s.impl.ClusterListenerSupport - hz.client_0 [dev] [3.7.4] Unable to get alive cluster connection, try in 0 ms later, attempt 1 of 2.

**Comment by sancar** [comment]
Depending on your configuration and environment this could be normal to see. This is logged when client tries all configured member addresses to connect and fails to connect them. There could be several reasons for not able to connect, like servers are not ready/open , credentials are wrong ... etc. It will attempt to connect to cluster again as it said. 
See following docs to configure attempt limit and attempt period
http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#setting-connection-attempt-limit
http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#setting-connection-attempt-period

And please ask similar questions in our google group
https://groups.google.com/forum/#!forum/hazelcast
