### ISSUE TITLE
3.8-SNAPSHOT scheduled executor hprof under load

### ISSUE THREAD

**Issue by Danny-Hazelcast** [hazelcast/hazelcast#9583]
we can very easily OOME a member by scheduling tasks.

2 members,  40 clients

each client scheduled 1 task to 1 executor with 0 sec delay, each iteration / flat out  
```
schedule_task@class=hz.executor.scheduled.Schedule
schedule_task@executorCount=1
schedule_task@scheduleCount=1
schedule_task@delaySec=0
schedule_task@repeating=true
```

Members using "-Xms2G -Xmx2G"

GC charts.

http://54.87.52.100/~jenkins/workspace/temp/scheduled-executor-hprof/gc.html

http://54.87.52.100/~jenkins/workspace/temp/scheduled-executor-hprof/hz/stable/scheduled-executor/output/HZ/HzMember1HZ/verbosegc.log.png

http://54.87.52.100/~jenkins/workspace/temp/scheduled-executor-hprof/hz/stable/scheduled-executor/output/HZ/HzMember2HZ/verbosegc.log.png

Hprofs

http://54.87.52.100/~jenkins/workspace/temp/scheduled-executor-hprof/hz/stable/scheduled-executor/output/HZ/HzMember1HZ/

http://54.87.52.100/~jenkins/workspace/temp/scheduled-executor-hprof/hz/stable/scheduled-executor/output/HZ/HzMember2HZ/

under

**Comment by Danny-Hazelcast** [comment]
test code run by clients 

https://github.com/Danny-Hazelcast/hzCmd-bench/blob/zeta/src/main/java/hz/executor/scheduled/Schedule.java

**Comment by Danny-Hazelcast** [comment]
is there some Q setting,  max scheduled tasks.  which could prevent unconstrained resource usage ?

**Comment by Danny-Hazelcast** [comment]
executor.schedule(counter, delaySec, TimeUnit.SECONDS); 

throws  RejectedExecutionException if the task cannot be scheduled for execution

however i don't see this and i get, member hprof

**Comment by Danny-Hazelcast** [comment]
using 

schedule_task@class=hz.executor.scheduled.Schedule
schedule_task@executorCount=1
schedule_task@scheduleCount=1
schedule_task@delaySec=9900

**Comment by tkountis** [comment]
@Danny-Hazelcast how are you trying to reproduce the 'cannot be scheduled' ? Under normal conditions you shouldn't expect a Rejected exception.

**Comment by Danny-Hazelcast** [comment]
by calling executor.schedule(counter, delaySec, TimeUnit.SECONDS); with a long delay
repeatedly until the member OOME

**Comment by tkountis** [comment]
I am confused, this issue is not yet addressed, so there is no cap in the amount of tasks you can schedule, therefore RejectedException will never be thrown. Just making sure we are on the same page.

**Comment by Danny-Hazelcast** [comment]
yes, that is correct,
