### ISSUE TITLE
Cluster can be frozen when node number decreases below min.cluster.size

### ISSUE THREAD

**Issue by enesakar** [hazelcast/hazelcast#961]
Currently "hazelcast.initial.min.cluster.size" is effective on in initial load of the cluster.
You can extend functionality to lifespan of the cluster,
so whenever cluster size is below predefined value, all operations are rejected.
This is useful expecially for cases like split brain.

**Comment by albertocsm** [comment]
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#defining-a-cluster-quorum
