### ISSUE TITLE
size() doesn't match the actual element number of Set<QueryableEntry>

### ISSUE THREAD

**Issue by marsbible** [hazelcast/hazelcast#9614]
Set<QueryableEntry> set = ((IndexAwarePredicate) predicate).filter(queryContext);
int size = set.size();
    
int act_size = 0;
for(QueryableEntry queryableEntry : set) {
     act_size++;
}

assert size==act_size;    =====> **Here will throws AssertionError**
__________________________________________________________________________________
The issue is in com.hazelcast.query.impl.AndResultSet, size() will return the size of setSmallest,
but iterator will return the intersection size of setSmallest,otherIndexedResults,lsNoIndexPredicates.
So the inconsistence occurs.  

See the following code:

  ```
public int size() {
     return setSmallest.size();
  }
    
  public boolean hasNext() {
		if (currentEntry != null) {
			return true;
		}

		for (; it.hasNext();) {
			QueryableEntry entry = it.next();

			if (checkOtherIndexedResults(entry) && checkNoIndexPredicates(entry)) {
				currentEntry = entry;
				return true;
			}
		}

		return false;
}  
```

**Comment by tombujok** [comment]
@marsbible Good observation! It's a clear bug.

**Comment by tombujok** [comment]
@marsbible Fixed. It will be backported to 3.7.5 that should be released soon. (https://github.com/hazelcast/hazelcast/pull/9633)
