### ISSUE TITLE
trylock doesn't block throws operationtimeoutexception on 3.6.4

### ISSUE THREAD

**Issue by iody** [hazelcast/hazelcast#9627]
anyone encountering this:

com.hazelcast.core.OperationTimeoutException: No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation

test: what I'm doing is just having 1 line trylock(key,10, seconds, 10, seconds) in a rest service. and it throws that error immediately on teh 2nd run. the error goes away when trying again after the lease time. isn't it supposed to block wait 10sec instead of throwing operationtimeoutexception when lock is already acquired?

**Comment by tombujok** [comment]
@iody could you post a minimal viable reproducer?

**Comment by iody** [comment]
it happens on prod environment only. test environment seems blocking.

error:No response for 120000 ms. Aborting invocation! Invocation{serviceName='hz:impl:lockService', op=com.hazelcast.concurrent.lock.operations.LockOperation{identityHash=375918893, serviceName='hz:impl:lockService', partitionId=197, replicaIndex=0, callId=24966827, invocationTime=1489030773702 (Thu Mar 09 03:39:33 UTC 2017), waitTimeout=-1, callTimeout=60000, namespace=DefaultObjectNamespace{service='hz:impl:mapService', objectName=...}}, partitionId=197, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[...]:5701, backupsExpected=0, backupsCompleted=0, connection=null} No response has been received!  backups-expected:0 backups-completed: 0

**Comment by pveentjer** [comment]
In Hazelcast 3.7 the timeout mechanism has been replaced. Can you switch to 3.8 and see if the problem still persists? If see, we can spend more time on analyzing the issue.

**Comment by iody** [comment]
@pveentjer I'm using 3.6. 3.8 is still early access?

**Comment by mdogan** [comment]
Rolling upgrade is available after 3.8 and between only +/-1 minor versions.

**Comment by mdogan** [comment]
Closing issue right now. If the problem still appears after 3.8+, please reopen.
