### ISSUE TITLE
XML parsing error for tcp-ip element : Element 'tcp-ip' cannot have character [children], because the type's content type is element-only

### ISSUE THREAD

**Issue by bklau** [hazelcast/hazelcast#9628]
I'm using the Docker image from https://hub.docker.com/r/hazelcast/hazelcast/

I tried to set my custom hazelcast.xml via -Dhazelcast.config and got this parsing error:
xception in thread "main" com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.3: Element 'tcp-ip' cannot have character [children], because the type's content type is element-only.
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:186)
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:220)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:203)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:196)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:123)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at com.hazelcast.core.server.StartServer.main(StartServer.java:46

My sample hazelcast.xml is below
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.7.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <network>
    <public-address>${hazelcast.network.public-address}</public-address>
    <port auto-increment="false"  port-count="3">${hazelcast.network.port}</port>
    <join>
      <multicast enabled="false">
      </multicast>
      <aws enabled="false">
      </aws>
      <tcp-ip enabled="true">
          <members>10.0.0.2</members>
      </tcp-ip>
    </join>
  </network>
  <group>
    <name>${hazelcast.group.name}</name>
    <password>${hazelcast.group.password}</password>
  </group>  
</hazelcast>

**Comment by bilalyasar** [comment]
Thanks for reporting.
Can you post your docker run command please?

**Comment by bklau** [comment]
I  extends  the Docker image and just add a hazelcast.xml and a run.sh where in the run.sh, i have:

exec java -cp $CLASSPATH $JAVA_OPTS com.hazelcast.core.server.StartServer

where JAVA_OPTS has -Dhazelcast.config=/opt/hazelcast/hazelcast.xml and CLASSPATH is just pointing to that hazelcast3.xxx.jar

**Comment by bklau** [comment]
So its really simple, ADD run.sh and hazelcast.xml
and CMD["run.sh"] in my Dockerfile
Nothing complicated

**Comment by bklau** [comment]
FROM hazelcast/hazelcast:latest
# Fix sh
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get install -y dnsutils net-tools iperf &&  rm -rf /var/lib/apt/lists/*
ADD hazelcast.xml /opt/hazelcast/
ADD run.sh /
RUN chmod +x /run.sh
CMD ["/run.sh"]

**Comment by bklau** [comment]
If don't specified the -Dhazelcast.config=hazelcast.xml, it defaults to using the hazelcast.default.xml in the hazelcast3xxx.jar which is multicast and I don't want that because I want to use tcp cluster  instead.

**Comment by bklau** [comment]
@bilalyasar : Is it possible that "<members>" element are not supported with  hazelcast.3.7.xsd schema?
<tcp-ip enabled="true">
   <members>10.0.0.1,10.0.1.3</members>
</tcp-ip>

**Comment by bklau** [comment]
@bilalyasar : Question : Is "members" element not supported in  hazelcast3.7.xsd schema?

**Comment by bklau** [comment]
@bilalyasar : I added a sample  custom hazelcast.xml that you can run against the Docker image
[hazelcast.txt](https://github.com/hazelcast/hazelcast/files/702232/hazelcast.txt)

**Comment by bilalyasar** [comment]
it should work.. you are using env. variable in config. But are you sure that you are passing those environment variables correctly?

**Comment by bklau** [comment]
java -cp /opt/hazelcast/hazelcast-all-3.7.4.jar:/*  -Dhazelcast.network.port=5701 -Dhazelcast.network.public-address=eb5fe1032f7a:5701 -Dhazelcast.group.name=my_group -Dhazelcast.group.password=my_secret -Dhazelca
st.socket.bind.any=false -Dhazelcast.members.list=10.0.0.4,10.0.0.6,10.0.0.7,10.0.0.8,10.0.0.2 -Dhazelcast.config=/opt/hazelcast/hazelcast.xml com.hazelcast.core.server.StartServer
Jan 12, 2017 4:51:56 PM com.hazelcast.config.XmlConfigLocator
INFO: Loading configuration /opt/hazelcast/hazelcast.xml from System property 'hazelcast.config'
Jan 12, 2017 4:51:56 PM com.hazelcast.config.XmlConfigLocator
INFO: Using configuration file at /opt/hazelcast/hazelcast.xml
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.3: Element 'tcp-ip' cannot have character [children], because the type's content type is element-only.
        at com.hazelcast.config.AbstractXmlConfigHelper.schemaValidation(AbstractXmlConfigHelper.java:186)
        at com.hazelcast.config.XmlConfigBuilder.parseAndBuildConfig(XmlConfigBuilder.java:220)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:203)
        at com.hazelcast.config.XmlConfigBuilder.build(XmlConfigBuilder.java:196)
        at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:123)
        at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)
        at com.hazelcast.core.server.StartServer.main(StartServer.java:46)

**Comment by bklau** [comment]
@bilalyasar  :  as shown in output above is how the System property got passed in:
java -cp /opt/hazelcast/hazelcast-all-3.7.4.jar:/* -Dhazelcast.network.port=5701 -Dhazelcast.network.public-address=eb5fe1032f7a:5701 -Dhazelcast.group.name=my_group -Dhazelcast.group.password=my_secret -Dhazelca
st.socket.bind.any=false -Dhazelcast.members.list=10.0.0.4,10.0.0.6,10.0.0.7,10.0.0.8,10.0.0.2 -Dhazelcast.config=/opt/hazelcast/hazelcast.xml com.hazelcast.core.server.StartServer

**Comment by bklau** [comment]
Even if I hardcoded the "members" element, I still get the error.

**Comment by bklau** [comment]
@bilalyasar  Would you be able to give me a sample hazelcast.xml that use tcp-ip clustering that uses that members element?. I can test it out. Thx.

**Comment by emre-aydin** [comment]
@bklau, I think your `hazelcast.xml` configuration is wrong. Below I post a sample configuration excerpt to configure TCP/IP discovery with members, taken from [documentation page](http://docs.hazelcast.org/docs/3.7/manual/html-single/index.html#discovering-members-by-tcp):
```
<hazelcast>
   ...
  <network>
    ...
    <join>
      <multicast enabled="false">
      </multicast>
      <tcp-ip enabled="true">
        <member>machine1</member>
        <member>machine2</member>
        <member>machine3:5799</member>
        <member>192.168.1.0-7</member>
        <member>192.168.1.21</member>
      </tcp-ip>
      ...
    </join>
    ...
  </network>
  ...
</hazelcast>
```

**Comment by bklau** [comment]
I found this except from the latest hazelcast 3.7.4 documentation-
>As shown above, you can provide IP addresses or hostnames for member elements. You can also give a >range of IP
>addresses, such as 192.168.1.0-7.
>Instead of providing members line-by-line as shown above, you also have the option to use the members >element
>and write comma-separated IP addresses, as shown below.
><members>192.168.1.0-7,192.168.1.21</members>...

**Comment by bklau** [comment]
@bilalyasar I'm suspecting that maybe the issue might be that the wrong hazelcast.xsd might be picked up or used during the  hazelcast.xml parsing?. Classloading issue? Just a thought.

**Comment by bklau** [comment]
@bilalyasar I finally was able to make it worked by downloading the hazelcast-default.xml and modified it.
I was abled to bind to all TCP IP list in the "members" element.
