### ISSUE TITLE
AWS Discovery only tries 3 ports 5701, 5702 & 5703 while joining cluster

### ISSUE THREAD

**Issue by AjitDas** [hazelcast/hazelcast#9640]
I have a application which internally uses hazelcast and application is deployed in AWS as a docker container. It works fine when I start my docker container and expose host port 5701/5702/5703 mapped to each of docker container internal port 5701. (i.e `docker run .............. -p 5701:5701` or `docker run .............. -p 5702:5701` or `docker run .............. -p 5703:5701`). I am also setting public address accordingly like `$DOCKER_HOST:5701` or  `$DOCKER_HOST:5702` or `$DOCKER_HOST:5703`.

But when I start my containers mapped to any other host ports than these ports then it's not joining the cluster. Looks like AWS discovery is only looking for private instances IPs and then only check for 5701/5702/5703 port in these private IPs.

Can someone please tell how to configure in AWS discovery to scan for more ports ?  FYI am using `hazelcast-all-3.7.4.jar`

With TCPDiscovery we can specify auto increment and increment count, but with docker auto increment doesn't make sense as each docker container will be it's isolated runtime with just one port mapped/exposed to host (in Dockerfile  `EXPOSE 5701`).

Here is my sample `hazelcast-spring.xml` configuration file.

```
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:hz="http://www.hazelcast.com/schema/spring"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
              http://www.hazelcast.com/schema/spring http://www.hazelcast.com/schema/spring/hazelcast-spring.xsd">

    <!-- Hazelcast Instance configuration -->
    <hz:hazelcast id="sampleHazelcastInstance">
        <hz:config>
            <!-- Hazelcast Instance Name -->
            <hz:instance-name>${sample.hz.instance.name}</hz:instance-name>
            <hz:group name="${sample.hz.group.name}" password="${sample.hz.group.pwd}"/>
            <hz:management-center  enabled="${sample.hz.management.center.enabled:false}" url="${sample.hz.management.center.url:}" update-interval="5"/>
            
            <hz:properties>
                <hz:property name="hazelcast.shutdownhook.enabled">${sample.hz.shutdownhook.enabled:false}</hz:property>
                <hz:property name="hazelcast.icmp.enabled">${sample.hz.icmp.enabled:true}</hz:property>
                <hz:property name="hazelcast.socket.bind.any">${sample.hz.socket.bind.any:true}</hz:property>
        		<hz:property name="hazelcast.socket.server.bind.any">${sample.hz.socket.server.bind.any:true}</hz:property>
                <hz:property name="hazelcast.socket.client.bind.any">${sample.hz.socket.client.bind.any:true}</hz:property>
				<hz:property name="hazelcast.max.no.heartbeat.seconds">${sample.hz.max.no.heartbeat.seconds:30}</hz:property>
				<hz:property name="hazelcast.client.max.no.heartbeat.seconds">${sample.hz.client.max.no.heartbeat.seconds:30}</hz:property>
                <hz:property name="hazelcast.logging.type">${sample.hz.logging.type:slf4j}</hz:property>
                <hz:property name="hazelcast.local.localAddress">${sample.hz.localAddress}</hz:property>
            </hz:properties>
            
            <hz:network port="${sample.hz.network.port:5701}" port-auto-increment="${sample.hz.network.port.auto.increment:false}" 
            	public-address="${sample.hz.publicAddress}">
            	<hz:outbound-ports>
            		<hz:ports>0</hz:ports>
            	</hz:outbound-ports>
                <hz:join>
                    <hz:multicast enabled="${sample.hz.multicast.enabled:false}" />
                    <hz:tcp-ip connection-timeout-seconds="${sample.hz.tcpip.conn.timeout:30}" enabled="${sample.hz.tcpip.enabled:false}" />
                    <hz:aws enabled="${sample.hz.aws.enabled:true}" 
                    	access-key="${sample.hz.aws.access.key}"
                    	secret-key="${sample.hz.aws.secret.key}"
                    	iam-role="${sample.hz.aws.iam.role}"
                    	region="${sample.hz.aws.region:us-east-1}"
                    	host-header="${sample.hz.aws.host.header:ec2.amazonaws.com}"
                    	security-group-name="${sample.hz.aws.security.group.name}"
                    	tag-key="${sample.hz.aws.tag.key}"
                    	tag-value="${sample.hz.aws.tag.value}" 
                    	connection-timeout-seconds="${sample.hz.aws.conn.timeout:30}" />
                </hz:join>
				<hz:reuse-address>true</hz:reuse-address>
            </hz:network>
            
          	<!-- Hazelcast Distributed Map configuration -->
       
</beans>
```

**Comment by AjitDas** [comment]
I added `hazelcast.tcp.join.port.try.count` in hazelcast configuration to a higher value 10 (with a default=5)  still it's not working, I guess `com.hazelcast.cluster.impl.TcpJoinerOverAWS` is not reading from `com.hazelcast.spi.properties.GroupProperty` correctly.

```
com.hazelcast.spi.properties.GroupProperty.java
 /**
     * The number of incremental ports, starting with port number defined in network configuration,
     * that will be used to connect to a host which is defined without a port in the TCP-IP member list
     * while a node is searching for a cluster.
     */
    public static final HazelcastProperty TCP_JOIN_PORT_TRY_COUNT
            = new HazelcastProperty("hazelcast.tcp.join.port.try.count", 3);
```

```
<hz:properties>
          <hz:property name="hazelcast.tcp.join.port.try.count">${sample.hz.tcp.join.port.try.count:5}</hz:property>
<hz:properties>
```

**Comment by AjitDas** [comment]
Few more interesting observation it starts scanning from port 5701 i.e lets I start both my docker containers with public port mapped to host as 5702 and 5703 in 2 different AWS machine instance then also it doesn't work. It expects one of port to be started with 5701. This is something wired logic of identifying the members. TcpJoinerOverAWS only identifies the machines IPs and due to missing port it starts with port 5701 which is correct way of doing it but then it should continue scan other ports till the try count matches by incrementing the ports. Please take a look at this not sure how this works for others may be everyone using 5701 port only to start with.

**Comment by mesutcelik** [comment]
Hi @AjitDas ,

As stated above, `com.hazelcast.cluster.impl.TcpJoinerOverAWS` not using the GroupProperty `hazelcast.tcp.join.port.try.count`.  That looks like the problem.  I have created a new issue on hazelcast-aws repo : https://github.com/hazelcast/hazelcast-aws/issues/17

You can follow up the problem from there.

**Comment by AjitDas** [comment]
Hi @mesutcelik 

you might take a look at the port scanning as well, it doesn't work if I start my containers with a host port mapped to 5702 or 5703 etc. It always expects one of the instance member to have port 5701 and that should be started first, and later other members can connect to that. I think this is also a bug please take a look at it this is stopping me to implement in AWS in my application. I am not sure how long it's going to fix am afraid I have to opt other option if something I can't make it work as I have some tight timelines for delivery.

For example I have 2 separate applications running in 2 instances (1 container instance in every machine) and am starting the application with port 5701 and 5702 ports respectively but when I start app with 501 port works and find other members where as app started with 5702 are not able to find the other members.

**Comment by anuragpathak2608** [comment]
HI, can someone comment on how you managed security for hazelcast public port?

**Comment by mesutcelik** [comment]
> HI, can someone comment on how you managed security for hazelcast public port?
Can you please ask your questions to Hazelcast Google Groups? You have a better chance to get some answers.

https://groups.google.com/forum/#!forum/hazelcast
