### ISSUE TITLE
Classloader Leakage in ClockTest (PermGen Space OOME)

### ISSUE THREAD

**Issue by Donnerbart** [hazelcast/hazelcast#9650]
We seem to have an issue with the `ClockTest`, which sometimes seems to produce a PermGen OOME failure:
```
11:45:29 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project hazelcast: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: There was an error in the forked process
11:45:29 
[ERROR] java.lang.OutOfMemoryError: PermGen space
```

This could be a production issue with a real leak or just a test issue with the `FilteringClassloader` which is used in that test to create multiple instances of the `Clock` singleton. Another path to explore would be the `ClassloaderUtil` which supports caching. Maybe our test classes are stacked up there for no good reason.

At least it makes me suspicious that the `ClockTest` (which doesn't start any HZ instance) takes about 3 seconds to execute `test_whenConfiguringClockOffset_thenSystemOffsetClockIsCreated` (which is the actual test to create a new `Clock` singleton with the second internal implementation).

**Comment by Donnerbart** [comment]
![screenshot from 2017-01-16 14-51-55](https://cloud.githubusercontent.com/assets/4196298/21985510/5e675aac-dbfb-11e6-93a5-c1223d51e24b.png)
This is the allocation profile from just a single `startIsolatedNode()` and the shutdown of it. This doesn't look very healthy to me (84 MB in about 3 seconds, just for class loading related code). If this is polluting the PermGen Space I can image why this is causing troubles. I'll have a look now what's going on there in detail.

**Comment by Donnerbart** [comment]
I ran the tests with Java 6, since Java 8 has no PermGen Space anymore. Unfortunately JFC is not available in JDK 6, so I used VisualVM for a quick peek into the PermGen space.

I modified the test to call `startIsolatedNode();` and `shutdownIsolatedNode();` in a loop until it ran into the OOME:
![screenshot from 2017-01-17 15-16-22](https://cloud.githubusercontent.com/assets/4196298/22023831/1fdf23d2-dcc8-11e6-9d83-8f2e0fb33ab6.png)
If I understand the PermGen correctly, most of the space is used up by method metadata and constant references (`static final String` and other primitives) etc. (see http://coding-geek.com/jvm-memory-model/). So it's much more data than just a view MB for the classes alone. Also the number of instances is quite high, due to the number of method metadata being cached.

We still could have a sneaky classloader leak issue. I found two articles which explain how a classloader leak can happen and how to detect it (with a JDK 6):
http://frankkieviet.blogspot.de/2006/10/classloader-leaks-dreaded-permgen-space.html
http://frankkieviet.blogspot.de/2006/10/how-to-fix-dreaded-permgen-space.html

I will try to run the explained heap dump, to see if it's one of our classes holding a reference. It could very well be a similar thing like the `Level` class from the example, since we have logging framework implementations in the code base.

**Comment by Donnerbart** [comment]
In the Visual GC we can see very easily, that the PermGen Space is never garbage collected, although I allow it via `-XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled`:
![screenshot from 2017-01-17 15-23-13](https://cloud.githubusercontent.com/assets/4196298/22024035/f3b786a4-dcc8-11e6-883e-2f74d24eeb79.png)

**Comment by Donnerbart** [comment]
I made a very small test to reduce the noise in the heap dump (no JUnit etc.).
```java
package com.hazelcast.util;

public class LeakTest extends AbstractClockTest {

    public static void main(String[] args) {
        LeakTest test = new LeakTest();
        test.startIsolatedNode();
        test.shutdownIsolatedNode();

        while (true) {
            System.gc();
        }
    }
}
```
I ran the application with these VM options: `-ea -server -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled`

And then tried to find references to the created `HazelcastInstance`: https://gist.github.com/Donnerbart/d572f544a78949846e9e652085b79d46

I'm not 100% sure yet how to interpret this. But it looks like there is still a reference in a `ThreadLocal` instance kept. If so we can garbage collect until the sun dies, the created classes will never vanish.

**Comment by Donnerbart** [comment]
It really seems to be the `ThreadLocalRandom`. I improvised a removal in the shutdown (of course just of the thread which calls the shutdown method), and now the GC works for the PermGen.
![screenshot from 2017-01-17 18-28-41](https://cloud.githubusercontent.com/assets/4196298/22031976/d2050f4e-dce2-11e6-8554-11b3ffb23f7d.png)

**Comment by pveentjer** [comment]
If you want to use '-XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled' you also need to use '-XX:+UseConcMarkSweepGC'.

**Comment by Donnerbart** [comment]
Actually it's working with the default setting. The missing setting were **not** the root cause at all. The GC is working fine with a Oracle 6 without any configuration in my test branch.

**Comment by Donnerbart** [comment]
The leakage in the case of the `ClockTest` is caused by the usage of `ThreadLocalRandom` in `BackpressureRegulator` in the user thread, which is never cleaned up. https://github.com/hazelcast/hazelcast/pull/9683 is a possible fix for exactly this scenario, but I think this leakage can also happen with any other custom or external classloader.

Jaromir pointed me to an article with a more general approach to cleanup `ThreadLocal` leftovers: http://www.javaspecialists.eu/archive/Issue229.html

**Comment by Donnerbart** [comment]
The approach of Heinz Kabutz is not applicable for our use case. It relies heavily on the JDK implementation (reflection on JDK internals) and is optimized for try-with-resource blocks. The crux is that the `ThreadLocal` object is created and removed in every try block. We want to have those values for a longer runtime and just clean them up at the HZ instance shutdown. I think a kind of `ThreadLocalRegistry` which calls `remove()` in the end is a better solution for us.

**Comment by Donnerbart** [comment]
After a lot of trial, error and research we came up with a very simple root cause and solution: Don't subclass `ThreadLocal` and don't override `initialValue()`. Kudos to Jaromir for finding this fix in the depths of the internet.

Applying this fix we could fix the leakage, at least for our `FilteringClassLoader` use case, without any complex registry or JDK dependent cleanup code. We will also introduce a test like TomCat or other containers do to check our code for such leakages, to prevent wrong `ThreadLocal` implementations in the future.

**Comment by Donnerbart** [comment]
We are going to introduce a test on a base like https://github.com/apache/tomcat/blob/811450a84ca29e38d42e041be85b2deed4058ebb/java/org/apache/catalina/loader/WebappClassLoaderBase.java#L1823 to prevent future classloader leaks.
