### ISSUE TITLE
Support of hazelcast properties starting scan port (other than default 5701) with AWS TCP Joiner

### ISSUE THREAD

**Issue by AjitDas** [hazelcast/hazelcast#9664]
I have multiple applications using embedded hazelcast deployed in AWS bundled as docker container. I am using AWS discovery for my applications. My applications are deployed something like this (i.e one container for a given application in each AWS instance)

**AWS Instance-1**
docker run .......  -p 5701:5701 ..... app1
docker run .......  -p 5702:5701 ..... app2
docker run .......  -p 5703:5701 ..... app3

**AWS Instance-2**
docker run .......  -p 5701:5701 ..... app1
docker run .......  -p 5702:5701 ..... app2
docker run .......  -p 5703:5701 ..... app3

**AWS Instance-3**
docker run .......  -p 5701:5701 ..... app1
docker run .......  -p 5702:5701 ..... app2
docker run .......  -p 5703:5701 ..... app3

I have configured in my hazelcast config with something like this.

```
            <hz:network port="${sample.hz.network.port:5701}" port-auto-increment="${sample.hz.network.port.auto.increment:false}" 
            	public-address="${sample.hz.publicAddress}">
            	<hz:outbound-ports>
            		<hz:ports>0</hz:ports>
            	</hz:outbound-ports>
                <hz:join>
                    <hz:multicast enabled="${sample.hz.multicast.enabled:false}" />
                    <hz:tcp-ip connection-timeout-seconds="${sample.hz.tcpip.conn.timeout:30}" enabled="${sample.hz.tcpip.enabled:false}" />
                    <hz:aws enabled="${sample.hz.aws.enabled:true}" 
                    	access-key="${sample.hz.aws.access.key}"
                    	secret-key="${sample.hz.aws.secret.key}"
                    	iam-role="${sample.hz.aws.iam.role}"
                    	region="${sample.hz.aws.region:us-east-1}"
                    	host-header="${sample.hz.aws.host.header:ec2.amazonaws.com}"
                    	security-group-name="${sample.hz.aws.security.group.name}"
                    	tag-key="${sample.hz.aws.tag.key}"
                    	tag-value="${sample.hz.aws.tag.value}" 
                    	connection-timeout-seconds="${sample.hz.aws.conn.timeout:30}" />
                </hz:join>
				<hz:reuse-address>true</hz:reuse-address>
            </hz:network>
```

From the above configutation my AWS discovery is working fine and it's identifying all 3 private ips of AWS instance for all 3 applications but **only app1 is able to find other cluster members and join not app2 & app3**. When I dig into issue I found the default scanning port for TCP joiner (which is what AWS discovery uses with `TcpIpJoinerOverAWS`) is `5701` and it increments the port scanning from that port only. Since app2 and app3 are started with 5702 and 5703 host ports it can't find it's peer cluster members. Default port of 5701 is fine when we don't specify the ports in ip address and that will work for non AWS simple TCP joiner but in case of AWS discovery API itself can only identify list of private IPs by AWS joiner (without any ports) in that case application need to have a way to specify what scanning ports it should start with and it should be configurable via hazelcast poperties (not only forced and mandatory with 5701).

This is a major issue with multiple hazelcast applications deployed in AWS instances and it should be looked on high priority as it limits and enforces application to use only one AWS instance, in my case if I have to use hazelcast here I have to deploy it as many as 9 AWS instances instead of 3 when I know my applications are small and can co-exists in same instances as they can be logically groups to one business functionality.

**Comment by AjitDas** [comment]
any update on this please ?

**Comment by gsaslis** [comment]
@AjitDas I think this is an issue with the Hazelcast AWS plugin, so perhaps you should raise this issue in that repo: https://github.com/hazelcast/hazelcast-aws

**Comment by AjitDas** [comment]
Thanks @gsaslis  I have created issue in https://github.com/hazelcast/hazelcast-aws https://github.com/hazelcast/hazelcast-aws/issues/18
