### ISSUE TITLE
hazelcast-all contains outdated hazelcast-aws

### ISSUE THREAD

**Issue by JChrist** [hazelcast/hazelcast#9698]
Hello.
The hazelcast-all jar, which is the one included in hazelcast-docker, downloaded from [maven repo](https://github.com/JChrist/hazelcast-docker/blob/master/hazelcast-oss/Dockerfile#L7), contains an [outdated version](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-all/pom.xml#L159) of hazelcast-aws

Is there some specific reasoning behind this?

**Comment by mesutcelik** [comment]
Hi @JChrist ,

hazelcast-all-3.7.x.jar files are stable versions of current hazelcast distribution so we actually don't want to upgrade dependencies for the sake of stability. Minor versions of newly released dependencies like hazelcast-aws might introduce some behavioral change...

On the other hand, you can expect the latest versions on hazelcast-3.8.

I suppose you are asking that for ECS support. right?

**Comment by JChrist** [comment]
Hi @mesutcelik !
Yes, ECS support is what I was looking for.
Looking forward to next milestone release then :)

**Comment by jerrinot** [comment]
@mesutcelik: this can be closed then?
