### ISSUE TITLE
DefaultWriteBehindProcessor: do not add whole batchMap in failureList in case of failure

### ISSUE THREAD

**Issue by dsukhoroslov** [hazelcast/hazelcast#9733]
when we use storeAll/deleteAll methods in MapStore interface, it is possible that underlying implementation has stored/deleted some entries from the supplied batch and then gets an exception on some particular entry in the middle of the batch. In order to handle this scenario properly the MapStore could remove from the supplied batch entries which were properly stored in the underlying persistent store. The only thing to improve in the DefaultWiteBehindProcessor is to properly synchronise the map passed to processBatch method with the initial batchMap (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/mapstore/writebehind/DefaultWriteBehindProcessor.java#L243):

```
            @Override
            public boolean run() throws Exception {
                callBeforeStoreListeners(batchMap.values());
                final Map map = convertToObject(batchMap);
                try {
                    final boolean result = operationType.processBatch(map, mapStore);
                } catch (Exception ex) {
                    // leave in batchMap only entries which were left in the map...
                   throw ex;
                }
                callAfterStoreListeners(batchMap.values());
                return result;
            }
```
I can provide PR for this, if you wish.

Thanks, Denis.

**Comment by ahmetmircik** [comment]
Hi @dsukhoroslov, please go ahead and send your pr.

**Comment by dsukhoroslov** [comment]
in which version you expect to include it? 3.7.5 would be great

**Comment by mdogan** [comment]
@dsukhoroslov; 3.7.5 has passed the QA process and scheduled for release already. 

You can send a PR based on 3.7.6 (maintenance-3x branch). Also please make a forward-port for 3.8 (master) too.

**Comment by dsukhoroslov** [comment]
the PR is #9738. Will port it to master when it'll be agreed.

**Comment by ahmetmircik** [comment]
since this is an enhancement, only a pr for master branch will be ok.

**Comment by dsukhoroslov** [comment]
but we need it in the 3.7.x version, asap.
