### ISSUE TITLE
Hazelcast 3.8 Enterprise version release date

### ISSUE THREAD

**Issue by SuryaPolisetty** [hazelcast/hazelcast#9761]
Any scheduled  release date for Hazelcast 3.8 enterprise version

**Comment by mdogan** [comment]
Currently planned in February 2017. 

Please ask Hazelcast related questions in our mail group: http://groups.google.com/group/hazelcast

**Comment by arunengr** [comment]
Any scheduled release date for Hazelcast 3.8 enterprise version
