### ISSUE TITLE
Hazlecast data looks to be overwrriten between nodes when node is restarted

### ISSUE THREAD

**Issue by Annapoornar** [hazelcast/hazelcast#9796]
Hi, 

I have the set up like this. I have two dropwizard Microservices instances, each of this is the TCP IP member of the hazlecast .

when I restart one of the node, where other node is updating the cache with the processed data, the data updated by the already running (not restarted one) is not visible. (I mean updated data is not there).

Can you please help me with this behaviour?

the hazlecast configuration in my dropwizard application is like this:

hazelcast:
  groupName: Symphony-rdcapdev1
  instanceName: Symphony
  port: 5900
  portAutoIncrement: false
  backupCount: 2
  asyncBackup: true
  evictionPolicy: NONE
  maxIdleSeconds: 86400
  multicast:
    enabled: false
  tcpIp:
    enabled: true
    members:
      - rdcapdev1-wrangler1.altidev.net
      - rdcapdev1-falcon1.altidev.net

**Comment by metanet** [comment]
Hi @Annapoornar 

It seems like you are using async backups. Are you doing a graceful shutdown while restarting the node? If not, some updates hitting the restarting node may no be replicated to the other node yet. So you can lose those updates.

**Comment by metanet** [comment]
Closing this one since we don't hear a response for a while.
