### ISSUE TITLE
Would be nice to have EntryProcessor returning ListenableFuture - not blocking caller.

### ISSUE THREAD

**Issue by ChristerF** [hazelcast/hazelcast#980]
The current EntryProcessor implementation blocks the client until a result is retrieved or timeout has happened. It would be great if a ListenableFuture (like the one in Google Guava) could be returned to enable attachment of a callback for the result.

**Comment by pveentjer** [comment]
We did a lot of work on the internals and we are exposing more api's using a listenable future. So I think we can complete this one in 3.8.

**Comment by LoneRifle** [comment]
I believe this was resolved by #7967 and should be closed. @ispringer and @ChristerF , can you confirm?

**Comment by ispringer** [comment]
We're running an older version of HZ so I can't easily confirm, but the fix sounds good.

**Comment by pveentjer** [comment]
There are a bunch of different flavors by now:

ICompletableFuture submitToKey(K key, EntryProcessor entryProcessor);
void submitToKey(K key, EntryProcessor entryProcessor, ExecutionCallback callback);

So I'm going to close this one.
