### ISSUE TITLE
MapLoader bug in 3.1 - loadAll() is called with empty keyset many times

### ISSUE THREAD

**Issue by Lumpusz** [hazelcast/hazelcast#983]
Hi,

When I used hazelcast 2.5 for loading a map with 75 records, to a cluster that has 3 hosts, MapLoader's loadAllkeys() returned a set with size 75, and loadAll() was called 3 times, each with with a Set containing ~25 records.
Using hazelcast 3.1 I've been experiencing a strange behaviour. Although the set, returned by loadAllKeys() has the correct size, loadAll() is called, multiple times (>3), and the given keySet often has 0 or 1 size, instead of ~25.
Because of this maploading became extremely slow.

Lumpusz

**Comment by enesakar** [comment]
map load all functionality is design mostly for scenarios with high number entries to be loaded. so I do not think we will invest resource to optimize load all for low number of records. but any community contribution will be welcome.
