### ISSUE TITLE
NonBlockingIOThreadingModel improper null check

### ISSUE THREAD

**Issue by pveentjer** [hazelcast/hazelcast#9835]
The newSocketReader/writer do a null check on the connection.

This is broken because there is no happens before relation between unsetting the item in the array on shutdown and reading it.

Probably best to replace the threads array on shut down and then do something like this:
```
   Threads threads  = this.threads;
   if (threads == null) {
         throw new IllegalStateException("IO thread is closed!");
   }
   NonBlockingIOThread outputThread = threads[index];
```

Probably also best not to null the items in the array.

**Comment by mdogan** [comment]
Fixed by https://github.com/hazelcast/hazelcast/pull/10360
