### ISSUE TITLE
Document behaviour of aggregators when extracted value is null

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast#9858]
see https://github.com/hazelcast/hazelcast/pull/9854#discussion_r100519099

**Comment by jerrinot** [comment]
Builtin aggregations such as `Average` or `sum` assume an aggregated entry is non-null. 

If an aggregated attribute is a `null` then e.g. Average aggregation will throw an Exception. 
This can be prevented by using a predicate to only aggregate entries where the attribute is not null. 

We could implement auto-skipping of null values in aggregations, but:
1. It make certain aggregations impossible ("`Count` how many entries have attribute `foo` set to null?")
2. It's conflating entry selection and entry processing. 

We can already do `map.aggregate(count("age"),  new SqlPredicate("name = 'Joe' and age is not null")` if needed.

**Comment by tombujok** [comment]
Closed via

- #9924
- #9913
- #9901
