### ISSUE TITLE
Question: is it safe to instrument hazelcast server with new relic?

### ISSUE THREAD

**Issue by dmitrymz** [hazelcast/hazelcast#9914]
we would like to integrate new relic infrastructure with our hazelcast nodes as its more convenient just plain jmx console. we are using open-source version, and just need basic jvm stats.

question: is it safe to instrument hazelcast server node with new relic?

**Comment by jerrinot** [comment]
@dmitrymz: we don't test this. I don't know new relic, I guess if you instrument just high-level structures such as `IMap` then it should be fine. However intrumenting internals (e.g. IO classes) might have quite some negative performance impact. Please use [Hazelcast forum](https://groups.google.com/forum/#!forum/hazelcast) for questions, GitHub issues are for reporting bugs and feature requests. Thanks for understanding.
