### ISSUE TITLE
LocalMapStatsUnderOnGoingClientUpdateTest.stats_generated_when_member_restarted_under_ongoing_client_update

### ISSUE THREAD

**Issue by tombujok** [hazelcast/hazelcast#9928]
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/7247/

**Comment by ahmetmircik** [comment]
fixed via https://github.com/hazelcast/hazelcast/commit/2684aeea94f7c30fc3e1c450247b7ae2b29b4d33
