### ISSUE TITLE
CachePartitionLostListenerConfig in CacheConfig is not serialized

### ISSUE THREAD

**Issue by asimarslan** [hazelcast/hazelcast#9932]
JCache requires a cache being created on a node/client and used on other nodes/clients.

 `CachePartitionLostListenerConfig` is part of `CacheConfig` and it is not part of its serialization. 

Please note that `CacheConfig` has client compatibility restrictions and we cannot just add the required serialization.

**Comment by asimarslan** [comment]
The initial PR that caused the problem : https://github.com/hazelcast/hazelcast/pull/6005

**Comment by mmedenjak** [comment]
Related to config cleanup - https://github.com/hazelcast/hazelcast/issues/12617

**Comment by mmedenjak** [comment]
@ihsandemir is this fixed with https://github.com/hazelcast/hazelcast/pull/15608?

**Comment by ihsandemir** [comment]
@mmedenjak Yes, it is fixed by https://github.com/hazelcast/hazelcast/pull/15608
