### ISSUE TITLE
Refactor MigrationListener API

### ISSUE THREAD

**Issue by mdogan** [hazelcast/hazelcast#9934]
Refactor `MigrationListener` to make it more user friendly. Currently, migration started/completed/failed events are fired. 

Instead, we can notify when a primary migration is done and when a backup replication is 
completed. Having separate events for migration start and complete doesn't add any value.

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/issues/3234 for additional request.

**Comment by mdogan** [comment]
See https://github.com/hazelcast/hazelcast/issues/2318

**Comment by burakcelebi** [comment]
Closed as internal request.
