### ISSUE TITLE
Add ability to set attribute on Hazelcast clients

### ISSUE THREAD

**Issue by bardyamomeni** [hazelcast/hazelcast#9948]
Recently I am working on a project that requires a lot of distribution and I chose Hazelcast for its requirements, on one of the modules I use Hazelcast client to connect to main cluster members and in the meantime the main cluster members must know each client attributes like module id.

But as I work with Hazelcast client, I didn't find anything like MemberAttributeConfig for HazelcastClientConfig (I know clients are not members), but I needed an attribute attached to a client so when ClientListener methods on the main cluster are invoked, I know which client is connected and identify them by custom attributes attached to them.

So as enhancement to HazelcastClient could have configurable attributes (maybe even immutable after construction) and the Client interface (used in ClientListener) have methods to access these attributes.

Thanks

**Comment by ehartmann** [comment]
Just to let you know that I have exactly the same need.
