### ISSUE TITLE
[docker] hazelcast into docker swarm, Virtual IP problem

### ISSUE THREAD

**Issue by Fabryprog** [hazelcast/hazelcast#9963]
Hello,
i using hazelcast (tcp discovery) into a docker swarm cluster.

According to official documentation (https://docs.docker.com/engine/swarm/networking/) swarm assign a VIP and a "fisical" IP for every service.

When a hazelcast member try to connect to another i have a conflict IP because hazelcast match any service with 2 different IP (VIP and IP)

How to resolve it?

**Comment by Fabryprog** [comment]
I temporary fix with custom discovery strategy using swarm API and SimpleDiscoveryNode with only virtual IP (without host name)

`Address address = new Address(null, InetAddress.getByName(ip), NetworkConfig.DEFAULT_PORT);
servers.add(new SimpleDiscoveryNode(address));`

It is working perfectly!!!!

**Comment by lokinell** [comment]
I have the same problem.

**Comment by bitsofinfo** [comment]
Try: https://github.com/bitsofinfo/hazelcast-docker-swarm-discovery-spi

**Comment by tombujok** [comment]
@jerrinot Matko pushed his final changes to this PR since he didn't have access to your branch. He wanted you to push the final state of the PR since he didn't know the details of the whole scope of the work you did here. Here's his PR:
https://github.com/hazelcast/hazelcast/pull/11548

**Comment by mmedenjak** [comment]
@Fabryprog @lokinell @bitsofinfo 
there is a new SPI that has just been merged and which will be released in the 3.9 version. It will allow you to define the bind and public address when starting the hazelcast instance and if used correctly it can be used to avoid issues when forming a cluster.
For now you will have to use the SPI yourself and write an implementation which will fix your issue but we are planning on releasing implementations of our own which will be bundled into plugins such as the docker or AWS plugin for easier deployment.
Please check out the new SPI:
https://github.com/hazelcast/hazelcast/blob/3cede71cad1fe87312f0901ff77f903ed2d4383d/hazelcast/src/main/java/com/hazelcast/spi/MemberAddressProvider.java
Please create a new issue or reopen this one if this does not suit your use case.

**Comment by bitsofinfo** [comment]
related: https://github.com/hazelcast/hazelcast/issues/10801
