### ISSUE TITLE
ManCenter docs are incorrect for cluster that has more than 2 members

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast#9969]
http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#getting-started-to-management-center

*When you try to connect to a cluster that has more than 2 members without entering a license key or if your license key is expired, the following dialog box appears.
......
Here, you can either choose to connect to a cluster without providing a license key or to enter your license key. If you choose to continue without a license, Management Center still continues to function but you will only be able to monitor up to 2 members of your cluster.*

Current behaviour is user can not see any information at mancenter dashboard if cluster that has more than 2 members.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/1766b379871e3cc913875646d37086578efcd05c.
