### ISSUE TITLE
Missing documentation for configuring log4j2 as logging framework

### ISSUE THREAD

**Issue by kedar-joshi** [hazelcast/hazelcast#9970]
Although, Log4j2 is supported as a logging framework, official Hazelcast documentation is missing steps to configure it. 

The documentation currently only mentions jdk, log4j, slf4j and none.

Please add log4j2 as another supported configuration for logging framework.

**Comment by jerrinot** [comment]
@kedar-joshi:

good catch, thanks!

cc @Serdaro

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/hazelcast-reference-manual/commit/e3c45aa27b3b1518ab3abd42e7eb7881636e137c

**Comment by Serdaro** [comment]
Finalized the closure with https://github.com/hazelcast/hazelcast-reference-manual/commit/b52d3785b9b8261cd881c1600f9f9cb8cd02d252
